### ISSUE TITLE
Disabling Sneak in Physics Override Does Not Work

### ISSUE THREAD

**Issue by jordan4ibanez** [minetest/minetest#11492] opened 2021-07-28 00:37 UTC
##### Minetest version

```
5.4.1 - stable
```

##### OS / Hardware

Operating system: Windows 10
CPU: Ryzen 5600x

##### Summary

Disabling sneak with the physics override does not work

##### Steps to reproduce

```
minetest.register_on_joinplayer(function(player)
    player:set_physics_override({sneak = false})
end)
```

**Comment by ElCeejo** [comment] 2021-07-28 01:05
Also on 5.4.1 and I can confirm that this doesn't work.

**Comment by StrychtenOfClamity** [comment] 2021-07-28 01:10
Tried it on Minetest 5.4.1 here locally and can confirm this does not work.

**Comment by sfan5** [comment] 2021-07-28 07:58
Putting the given code into a mod and enabling it on either an MTG or devtest world will produce the wanted behaviour (you fall off node edges when sneaking). Tested on 5.5.0-dev.

**Comment by rubenwardy** [comment] 2021-07-28 10:21
Check for other calls to set physics override

**Comment by jordan4ibanez** [comment] 2021-07-28 17:54
I give up on explaining this so I just made a video: https://www.youtube.com/watch?v=-j4M-iQKCEA

**Comment by sfan5** [comment] 2021-07-28 18:12
Ah in that case this will have been fixed by f30dcdb504adb02724e3a5faa30a951eb907b33f, there was a subtle issue when a game only ever called certain methods once.
Mind downloading a 5.5.0-dev build to test?

**Comment by SmallJoker** [comment] 2021-07-28 18:40
> I give up on explaining this so I just made a video: https://www.youtube.com/watch?v=-j4M-iQKCEA

The issue at 3:30 (moving into wrong direction) is likely a duplicate of #10962.

**Comment by sfan5** [comment] 2021-07-28 18:42
details from IRC that weren't mentioned initially:
```
<sfan5> wait okay so the bug is not "set_physics_override doesn't do anything", correct?
<jordan4ibanez> The bug is set_physics_override({sneak = false}) not only doesn't disable sneaking, it allows you to slow down like you're sneaking, clips on random collision geometry/nothing at all, completely breaks movement, sometimes clips into nodes
<jordan4ibanez> allows you to slow down like you're sneaking, when I see the settings "sneak = false", I would assume that setting this to false would turn the sneak key from an engine implementation of 
```

I don't consider the "allows slowing down" a bug as that is controlled by `movement_speed_crouch`, but this could probably be better documented.

The test game: https://github.com/jordan4ibanez/bug_showcase
Can't notice anything out of the ordinary on my machine.

**Comment by debagos** [comment] 2021-07-30 18:11
I tested it on my laptop with recent master and @jordan4ibanez _bug_showcase_ game.
Besides the unexpected behavior (movement speed gets still reduced), the movement is completely normal and as expected (falling off node edges).
```
{
        new_move = true,
        jump = 1,
        speed = 1,
        sneak = false,
        sneak_glitch = false,
        gravity = 1
}
```
I am using KDE Neon (Ubuntu 20.04), so I guess this bug only appears on Windows builds?

**Comment by kay27** [comment] 2021-07-31 00:36
I run 5.4.1 on win10 and the main thing `{sneak = false}` changes - I can go out of cliffs...
The physics not exactly the same, sometimes it slightly differs. By pressing C once I can see glitches better. But I slide into blocks more often without pressing sneak key... To be honest it looks almost normal, like slightly decreased collision box or just too wide hands. Maybe the problem is too much performant CPU :)

But doesn't it mean no way to disable slow down by pressing the key?

**Comment by sfan5** [comment] 2021-07-31 10:08
This is actually two bugs reports in one:
* "With sneak disabled the player still slows down": This is not a bug. You can modify the speed via `movement_speed_crouch` and the upcoming #11465
* "Collision detection/physics break": This is only happens at high fps (>150) and is already tracked in #10962.

Therefore closing this.

**Closed by sfan5** 2021-07-31 10:08 UTC
Labels: Unconfirmed bug
