### ISSUE TITLE
CAO shading option is inconsistent?

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#11754] opened 2021-11-04 00:17 UTC
##### Minetest version

```
Minetest 5.4.0
```

##### OS / Hardware

Operating system: Linux

##### Summary
The shader option that was added in https://github.com/minetest/minetest/pull/10033 seems inconsistent from my perspective. Setting it to false and enabling shaders in Minetest settings results in shaders being turned off for the entity. This is expected. However, setting it to true and disabling shaders in the Minetest settings results in shaders being turned off for the entity. I expected shaders to still be on for that entity.

At the time that this was made, it was intended mostly to allow shading to be turned off by developers. However, it doesn't seem the same was added for having shaders on. For similar reasons that were stated for having shaders off, I would like to be able to turn them on when necessary. Minetest is considered a game engine, so I expect to be able to choose what I would like the player to see. Having to hope if a player has a setting set to what you want is frustrating. Other game engines do not give an option to a player like this while not allowing the developer to choose how they want it.

The expected result when I read the lua api was that nil/undefined would allow the player to choose what shading option they want while explicitly setting it to true or false would let the developer decide.

I'm not sure if this should count as a bug or a feature request, so I apologize if this was labelled incorrectly.

##### Steps to reproduce
Set shaded to false for an entity and observe that shading for it is always off not matter what setting the player chooses. Set shaded to true and observe that shading is dependent on what the player chooses.

**Comment by sfan5** [comment] 2021-11-07 16:30
This is a good point, but there is no good way to change this currently. Hardware without shader support exists and is (still) supported by Minetest so there are situations in which you could not force CAO shading to be enabled even if you wanted.

There's also the general question of in how far game creators need to be able to control certain options. So far efforts have been focused on making sure users don't _enable_ undesirable settings. The reverse can also be argued but I think this will require some discussion (should smooth lighting fall under this? mipmapping?).

**Comment by pikachuiscool2** [comment] 2021-11-07 19:01
> This is a good point, but there is no good way to change this currently. Hardware without shader support exists and is (still) supported by Minetest so there are situations in which you could not force CAO shading to be enabled even if you wanted.

Ahh, I wasn't aware that. That makes sense.

> There's also the general question of in how far game creators need to be able to control certain options.

There are situations where this affects gameplay. Something like prop hunt where having the props blend in with the environment would not be able to depend on shading being on. Players could turn it off and have an advantage. I'm sure there are plenty of other ways to cheat at prop hunt, but at least this would eliminate a very easy option. Currently the only consistent option is to disable shading and bake the shading into the entity texture. That seems a bit ridiculous if Minetest could offer a way to enforce shading.

Since Minetest can't implement this right now or even in the near future, I'm going to close this. Thank you for the response!

**Comment by sfan5** [comment] 2021-11-08 21:11
We might in fact drop non-shader support soon with work on a new renderer hopefully starting. So if it's important to you you can choose to keep this open.

**Comment by pikachuiscool2** [comment] 2021-11-12 12:18
In that case, I'll reopen this. I would like it to be taken into consideration if a rewrite is likely to happen.

**Comment by thetaepsilon** [comment] 2021-11-22 13:18
I'd actually like to raise an opinion which may weigh in on this somewhat - for a while, I've wanted the ability to make entity models that look fully consistent as being part of the world as opposed to something that sticks out like a sore thumb. The original rational of this in my case was experimenting with multipart blocks via entities (possibly inside existing blocks, e.g. waterloggable underwater blocks a la a certain other block game, but not limited to just that)*.

Baking a mimicry of block shading into a model is rather fragile; it doesn't react upon rotation like one would like (e.g. I'd expect the tinting to adjust to reflect surface normals), and doesn't take into account the difference between sky and block light tinting, so can never be perfect. And one is also duplicating values from the engine which could break, especially with custom client side shaders**.
Then if one decides to rely upon entity shading, this returns to the above discussed points also.

 Hence I would say there is some merit to being _some property_ or combination of that will guarantee a consistent look regardless of client settings (even if we have to stick to model face tinting hacks and such in the meantime), and one that is "world seamless". I am open to the idea of making the latter a separate request or duplicating this comment elsewhere if the issue is felt to diverge or pollute the original too much but I felt it tied in with @pikachuiscool2 mentioning prop hunt type games where blending in with the world is necessary.



*PS: yes, I know this particular idea would have performance implications, but the potential for this wasn't something I was willing to pass up... until I hit the shading issue and got discouraged for a while. It was more something I was hoping to explore and then see if it could be made more performant via engine features if the potential proved worthwhile. It should be noted that in this case the entities could be for visuals only, the "block parts" could be simulated for game logic in other ways.

**This actually suggests a preference for such a renderer re-write to use _the same shader_ for both entities and blocks at a bare minimum, if at all possible, thus guaranteeing consistency because all triangles would be equal so to speak regardless of custom shaders or edits to the inbuilt ones. Though, naturally this does indeed require the renderer to always use shaders for more things and handle normals and such there, because baking block tints into the geometry would no longer be possible. Others would likely have backwards compat concerns for this.

**Comment by sfan5** [comment] 2024-11-13 14:03
closing due to #15421

**Closed by sfan5** 2024-11-13 14:03 UTC
Labels: @ Client / Audiovisuals, Request / Suggestion
