### ISSUE TITLE
Add minetest.register_on_player_damage

### ISSUE THREAD

**Issue by Xeno333** [minetest/minetest#15088] opened 2024-08-30 18:39 UTC
### Problem

When adding enchants to armor in Mineclone2/Mineclonia and the like, they must cancle damage on hp change via register_on_player_hpchange this passes player, hp_change and reason but the problem is that hp_change has been floored to the players health. It doen't pass damage, it passes floor(damage, player_health), the problem is if you cancle out a fraction of damage then when the player has 1 hp, a fraction could be 0.1, leading to logarithmic decrease in damage dealt. For example say 10 dmg is dealt to a player at 1 hp, and the armor takes out 10% now it is 0.1 (because of being floored) which is less than 1, leading to it not being dealt at all, when it should be 9 hp damage, there by killing the player. 

### Solutions

Add minetest.register_on_player_damage and pass player, damage, reason to the function. This way damage can be cancled and not be floored to the players health.

### Alternatives

I haven't thought of any.

**Comment by appgurueu** [comment] 2024-08-30 18:43
Duplicate of #14344, possible solutions are discussed there.

Personally I'm a fan of either a parameter modders can set, or supplying the real damage in another HP change reason field / another parameter passed to the callback.

I'm not a big fan of this solution in particular, because it (1) is limited to only damage (2) puts us in a weird position where we have two API functions that sound like one does a strict subset of the other, but one has a weird legacy limitation.

**Closed by appgurueu** 2024-08-30 18:43 UTC
Labels: Feature request

**Comment by Xeno333** [comment] 2024-08-30 18:44
ah ok i looked and couldnt seem to find that issue lol
