### ISSUE TITLE
All node/block breaking speads should be the same in creative

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4466] opened 2016-08-26 11:59 UTC
For example if you break a wood block it just takes a second but if you break an iron block it takes you 3 seconds I think all these speeds should be the same (all blocks should break at the speed of wood)
This is based on https://github.com/minetest/minetest_game/issues/1267

**Comment by Wayward1** [comment] 2016-08-26 12:42
Duplicate of #4462

**Comment by rubenwardy** [comment] 2016-08-26 12:48
duplicate of game#1267

**Closed** 2016-08-26 12:47 UTC
Labels: Duplicate
