### ISSUE TITLE
No aux1 for android

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#4260] opened 2016-06-29 09:08 UTC
it turns out that android users cannot use the aux1 key for mods that require it like sprint, so would it be possible to add an onscreen icon next to the walking arrows for just such a thing :)

**Comment by est31** [comment] 2016-06-30 16:57
hmm in fact that seems to be the only relevant key...

Do you have a possible icon we could use? Obviously needs to be under a free license.

**Comment by everamzah** [comment] 2016-06-30 17:44
Either a solid circle or a square outline?  It's hard to imagine an icon for auxiliary 1.

**Comment by paramat** [comment] 2017-09-15 07:07
Duplicate of #2873

**Closed by paramat** 2017-09-15 07:07 UTC
Labels: Android, Duplicate, Feature request
