### ISSUE TITLE
UI aborts when Lua crashes in get_staticdata callback

### ISSUE THREAD

**Issue by pgimeno** [minetest/minetest#8377] opened 2019-03-14 17:49 UTC
##### Issue type
 - Bug report
 
##### Minetest version

Tested in 0.4.16 and current master (5.1.0-dev)

##### Summary

When server and client are both started from the UI, a Lua error within `get_staticdata` not only stops the server, it also aborts, taking the UI with it. It may affect more functions than that, not sure.

From this report: https://forum.minetest.net/viewtopic.php?p=345650#p345650

##### Steps to reproduce

Install this mod:

```lualocal tex = "unknown_object.png"
local entityname = 'bug:item'

minetest.register_entity(':' .. entityname, {
  visual = "cube",
  textures = {tex, tex, tex, tex, tex, tex},
  get_staticdata = function(self)
    local z; z = -z  -- force Lua error
  end,
})

minetest.after(1, function()
  local pos = minetest.get_player_by_name("singleplayer"):get_pos()
  pos.x = pos.x + 2
  minetest.add_entity(pos, entityname)
end)
```

Activate it and start a singleplayer game.

Output:

```
2019-03-14 18:17:29: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'bug_getstaticdata' in callback environment_Step(): Runtime error from mod 'bug_getstaticdata' in callback luaentity_GetStaticdata(): $MINETEST/bin/../mods/bug_getstaticdata/init.lu
2019-03-14 18:17:29: ERROR[Main]: a:8: attempt to perform arithmetic on local 'z' (a nil value)
2019-03-14 18:17:29: ERROR[Main]: stack traceback:
2019-03-14 18:17:29: ERROR[Main]: 	$MINETEST/bin/../mods/bug_getstaticdata/init.lua:8: in function <$MINETEST/bin/../mods/bug_getstaticdata/init.lua:7>
2019-03-14 18:17:29: ERROR[Main]: 	[C]: in function 'add_entity'
2019-03-14 18:17:29: ERROR[Main]: 	$MINETEST/bin/../mods/bug_getstaticdata/init.lua:15: in function 'func'
2019-03-14 18:17:29: ERROR[Main]: 	$MINETEST/bin/../builtin/common/after.lua:18: in function <$MINETEST/bin/../builtin/common/after.lua:4>
2019-03-14 18:17:29: ERROR[Main]: 	$MINETEST/bin/../builtin/game/register.lua:419: in function <$MINETEST/bin/../builtin/game/register.lua:399>
2019-03-14 18:17:29: ERROR[Main]: stack traceback:
2019-03-14 18:17:29: ERROR[Main]: 	[C]: in function 'add_entity'
2019-03-14 18:17:29: ERROR[Main]: 	$MINETEST/bin/../mods/bug_getstaticdata/init.lua:15: in function 'func'
2019-03-14 18:17:29: ERROR[Main]: 	$MINETEST/bin/../builtin/common/after.lua:18: in function <$MINETEST/bin/../builtin/common/after.lua:4>
2019-03-14 18:17:29: ERROR[Main]: 	$MINETEST/bin/../builtin/game/register.lua:419: in function <$MINETEST/bin/../builtin/game/register.lua:399>
2019-03-14 18:17:29: ERROR[Main]: stack traceback:
2019-03-14 18:17:29: ACTION[Server]: singleplayer leaves game. List of players: 
2019-03-14 18:17:29: WARNING[Server]: ScriptApiBase::objectrefGetOrCreate(): Pushing ObjectRef to removed/deactivated object, this is probably a bug.
2019-03-14 18:17:29: ACTION[Main]: Server: Shutting down
terminate called after throwing an instance of 'LuaError'
  what():  Runtime error from mod 'bug_getstaticdata' in callback luaentity_GetStaticdata(): $MINETEST/bin/../mods/bug_getstaticdata/init.lua:8: attempt to perform arithmetic on local 'z' (a nil value)
stack traceback:
	$MINETEST/bin/../mods/bug_getstaticdata/init.lua:8: in function <$MINETEST/bin/../mods/bug_getstaticdata/init.lua:7>
Aborted
```

Bactrace:

```
Thread 1 "minetest" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff2b1142a in __GI_abort () at abort.c:89
#2  0x00007ffff34280ad in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff3426066 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff3425089 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff34259dd in __gxx_personality_v0 () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff2e8bf33 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#7  0x00007ffff2e8c437 in _Unwind_Resume () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#8  0x00005555560785ea in ServerEnvironment::deactivateFarObjects (this=0x555556e4fb40, _force_delete=true) at $MINETEST/src/serverenvironment.cpp:1983
#9  0x0000555556071127 in ServerEnvironment::~ServerEnvironment (this=0x555556e4fb40, __in_chrg=<optimized out>) at $MINETEST/src/serverenvironment.cpp:464
#10 0x0000555556071388 in ServerEnvironment::~ServerEnvironment (this=0x555556e4fb40, __in_chrg=<optimized out>) at $MINETEST/src/serverenvironment.cpp:481
#11 0x0000555556048b91 in Server::~Server (this=0x555556b1ee10, __in_chrg=<optimized out>) at $MINETEST/src/server.cpp:293
#12 0x0000555556048f3e in Server::~Server (this=0x555556b1ee10, __in_chrg=<optimized out>) at $MINETEST/src/server.cpp:308
#13 0x0000555555c3b63d in Game::~Game (this=0x7fffffffd2b0, __in_chrg=<optimized out>) at $MINETEST/src/client/game.cpp:955
#14 0x0000555555c4fcda in the_game (kill=0x5555566474c0 <porting::g_killed>, random_input=false, input=0x555556a543a0, map_dir="$MINETEST/bin/../worlds/CheckObjects", playername="singleplayer", password="", address="", port=65140, error_message="AsyncErr: environment_Step: Runtime error from mod 'bug_getstaticdata' in callback environment_Step(): Runtime error from mod 'bug_getstaticdata' in callback luaentity_GetStaticdata(): ...netest-git-m"..., chat_backend=..., reconnect_requested=0x7fffffffd63f, gamespec=..., simple_singleplayer_mode=true) at $MINETEST/src/client/game.cpp:4203
#15 0x0000555555bef83a in ClientLauncher::run (this=0x7fffffffdae0, game_params=..., cmd_args=...) at $MINETEST/src/client/clientlauncher.cpp:273
#16 0x0000555555fdfa2d in main (argc=1, argv=0x7fffffffe2e8) at $MINETEST/src/main.cpp:212
```

It may affect more callbacks, I don't know. I've tried with `on_generated` and that one only closes the server, as expected.

**Comment by rubenwardy** [comment] 2019-03-14 18:00
duplicate of #8352

**Closed by rubenwardy** 2019-03-14 18:00 UTC
