### ISSUE TITLE
VR (3D mode) on Android non-functional

### ISSUE THREAD

**Issue by Qiangong2** [minetest/minetest#8896] opened 2019-09-03 16:11 UTC
##### Minetest version

```
Latest Google Play version
```

##### OS / Hardware

Operating system: Android 8.1
CPU: Snapdragon 835

GPU model:
OpenGL version:

##### Summary

The VR settings do not work on Android. No matter what you set, it does not work. I am trying to get Minetest working using either cardboard or daydream. 

##### Steps to reproduce

Go to Advanced Settings
Select a 3D mode
Start Game
It will stay stuck at a black screen for all eternity

**Comment by rdococ** [comment] 2019-09-03 16:46
I get this bug too. Interestingly, for me at least, the leftmost row of pixels is still active.

**Comment by Qiangong2** [comment] 2019-09-03 17:01
Oh, I don't even get that. That might be related to different screen resolutions though

**Comment by Qiangong2** [comment] 2019-09-06 05:17
Even compiling the latest git commit does not work

**Comment by srifqi** [comment] 2020-01-31 10:35
On Android, only anaglyph mode that can be used. Others are still broken on Android. You can read more here: https://github.com/minetest/minetest/issues/4874#issuecomment-438564099

---

> Even compiling the latest git commit does not work

What is the error? Can you successfully compile now?

**Comment by Qiangong2** [comment] 2020-01-31 15:56
> > Even compiling the latest git commit does not work
> 
> What is the error? Can you successfully compile now?

I meant that compiling from the latest git does not make 3d work

I can compile Minetest just fine. I just thought the bleeding edge would have it fixed. Unfortunately not

**Comment by 6543** [comment] 2020-03-20 16:04
split view does not work (horizontal & vertical afected)

Device: OnePlus 5T
Android: 9
MT v: f-droid latest (5.1.0.25)

**Comment by rubenwardy** [comment] 2020-06-20 15:15
Duplicate of #4874

**Closed by rubenwardy** 2020-06-20 15:15 UTC
Labels: Android, Bug
