### ISSUE TITLE
Waving liquid render bug if solid block is above liquid

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9005] opened 2019-09-29 12:09 UTC
##### Minetest version
```
5.1.0-RC1
```

##### Summary
If a solid block is directly above a waving liquid, and waving liquids are enabled, there's a render bug. The area below the solid block has no visible liquid, thus creating an odd “hole” in the liquid. See screenshot.

![HV0zjrmtZF_IND](https://user-images.githubusercontent.com/3686677/65836075-31f4e800-e2e6-11e9-9b05-f1b0efb9ea24.png)

##### Steps to reproduce
0. Enable waving liquids
1. Start MTG
2. Take any solid block like dirt
3. Place the block so that it is directly above water or lava
4. Look at the dirt and the area below

**Comment by paramat** [comment] 2019-09-29 17:21
Long known issue but oddly not a duplicate.
I guess that with waving liquids disabled, the liquid surface contacts the underside of the solid node, and so is not drawn, and it remains that way with waving liquids enabled?

**Comment by Jummit** [comment] 2019-10-08 18:39
Code responsible:
https://github.com/minetest/minetest/blob/b49dfa92ce3ef37b1b73698906c64191fb47e226/src/client/content_mapblock.cpp#L642-L652

**Comment by random-geek** [comment] 2019-10-20 02:11
@paramat Couldn't this be fixed by always drawing the top faces of liquid nodes when waving liquids is enabled?

**Comment by DS-Minetest** [comment] 2019-10-20 11:01
> @paramat Couldn't this be fixed by always drawing the top faces of liquid nodes when waving liquids is enabled?

This wouldn't be correct if the solid node above the liquid is under water.

**Comment by v-rob** [comment] 2019-10-20 22:29
Well, check if the node drawtype above the water is `liquid` or `flowingliquid`, and if it isn't, draw the top.  Otherwise, don't draw it like it is currently.

(This is probably harder than I think it is.)

**Comment by paramat** [comment] 2019-10-21 19:06
Duplicate of #3075 which should not have been closed. I reopened and edited it.

**Closed by paramat** 2019-10-21 19:06 UTC
Labels: @ Client / Audiovisuals, Bug, Duplicate, Low priority, Shaders
