### ISSUE TITLE
Make settings dialog easily navigable with keyboard

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#13903] opened 2023-10-20 23:43 UTC
### Minetest version

```true
5.7.0-279-gb1dec37ad
```

### Active renderer

OpenGL 1.4

### Irrlicht device

X11

### Operating system and version

Debian GNU/Linux 11.7

### CPU model

Intel(R) Core(TM) Duo CPU      T2400  @ 1.83GHz

### GPU model

Intel Corporation Mobile 945GM/GMS, 943/940GML Express Integrated Graphics Controller (rev 03)

### OpenGL version

OpenGL 1.4

### Summary

In the new settings dialog it seems I can no longer navigate using the keyboard.

This was possible in the old settings dialog. Am I missing something important?

### Steps to reproduce

1. Enter the settings dialog.
2. Select something in the left column.
3. Press up and down and page up and page down and tab and enter and other keys.
4. Notice that it does not change what setting is selected.

**Comment by rubenwardy** [comment] 2023-10-20 23:55
This is a formspec limitation, unfortunately. We decided that it was better to have a more understandable settings menu than keyboard usability, especially as formspec improvements in the future will fix that and all other formspecs.

Probably a duplicate of #11392

**Comment by erlehmann** [comment] 2023-10-21 00:02
It is possible to fix that other issue without fixing this one. So I would say it is not a duplicate.

**Comment by rubenwardy** [comment] 2023-10-22 13:22
Duplicate of #11392 

To fix this issue, we need more support for keyboard control in formspecs - including focus styling and keyboard shortcuts. That's what that other issue asks for

**Closed by rubenwardy** 2023-10-22 13:22 UTC
Labels: Feature request, @ Mainmenu, UI/UX
