### ISSUE TITLE
Player "steps" up when jumping next to a node

### ISSUE THREAD

**Issue by LuciusofLegend** [minetest/minetest#12775] opened 2022-09-16 23:07 UTC
##### Minetest version
```
Minetest 5.6.0
```

##### OS / Hardware

Operating system: Manjaro Linux
CPU: Intel i5-10500H

##### Summary

Sometimes while jumping around, you get pushed up a little bit in a jerky manner.  Depending on your jump physics, this can result in clearing two full nodes even when that would not normally be possible.

##### Steps to reproduce
Join most any Minetest world (I have reproduced the issue in Minetest game, Dev Test, and my own game)
Stand next to any solid node and hold w
Jump while still holding w

You will notice that your player does a little hop at the top of the node, kind of like when you step onto snow from normal ground.  In fact, that's my theory.  The engine thinks you need a step-up, and gives you one.  By the way, this allows you to jump up 2 nodes in all the games I mentioned.

If that really is the cause of the bug, maybe the fix is as simple as checking if the player is mid-air before stepping up.

**Comment by debagos** [comment] 2022-09-17 07:09
>Join most any Minetest world
Stand next to any solid node and hold w
Jump while still holding w

I'm unable to reproduce it. Guess I need more clear instructions. A video would help a lot by the way.
>Depending on your jump physics

Does it happen with default physics (no armor etc) as well?

**Comment by GoodClover** [comment] 2022-09-17 15:20
> You will notice that your player does a little hop at the top of the node, kind of like when you step onto snow from normal ground. In fact, that's my theory. The engine thinks you need a step-up, and gives you one.

Correct, this is the "intended" behavior.
A way to configure it would be nice though…

**Comment by LuciusofLegend** [comment] 2022-09-17 23:55
> Correct, this is the "intended" behavior. A way to configure it would be nice though…
>
> I cannot reproduce the 2 node jumping.  Unless by that you mean holding jump and walking into a slope, where you "glide" up.

You're right.  What I originally noticed was probably intended behavior.  Sorry about that :/.  However, there is still some odd behavior.  As you can see in the video below (thanks for the suggestion debagos), when I jump (holding w and spacebar) I do an extra high jump, which isn't 100% ideal:


https://user-images.githubusercontent.com/83921153/190878255-4bdc2355-1c1d-4403-a0d5-3f48708106a5.mp4

In that video, all physics settings are default, and I'm using a new world on Minetest Game.  Obviously, this isn't a high priority issue, but it would be nice to fix sometime.  If you need more information, let me know and I'll see what I can do :)

**Comment by IrrlichtMt4** [comment] 2022-09-18 08:21
I think a setting would be good for this in the advanced tab/controls tab would be nice.

**Comment by Zughy** [comment] 2023-10-06 22:52
As said in the comments, it's intended behaviour. Not a bug, closing

**Closed by Zughy** 2023-10-06 22:52 UTC
Labels: Unconfirmed bug, @ Server / Client / Env.
