### ISSUE TITLE
Add a threading API so mods can use multiple threads/processors.

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#3375] opened 2015-11-15 03:41 UTC
I would love to see this particular API added to minetest: http://lualanes.github.io/lanes/

It is a LUA API that makes it easy to use mutiple processors and make mods that are multithreaded.  Right now, minetest has a major performance problem if you want to make LUA mods that take a long time to process.  If the LUA mod is unable to finish it's calculation before the next minetest step, then the players will experience lag while the server is backed up processing whatever.

This particular problem is most noticeable with LUA mapgens.  Some LUA mapgens take anywhere from 500ms to 2 minutes!  However, if you were to add the lanes API to minetest, it would be possible to write LUA mapgens that have ZERO (NO) lag effect on the game... even if it literally took 5 minutes for the mapgen!

Sitenote:
How would I use the lanes API to make a slow LUA mapgen cause no lag?

I might do something like this:

```
1. Setup the mapgen in minetest:
minetest.register_on_generated(mymapgen)
function mymapgen(minp,maxp,blockseed)
    -- 1. get the data and store it in a variable using voxelmanip
    local map_block = voxelmanip:get_data()
    -- 2. start a lanes (separate thread) to generate the map using the voxelmanip data
    -- 3. lock that section of the map (using a function attached to minetest.is_protected to prevent players changing that part of the map while it's being worked on)
end

2. Next, I would add a function to check if the mapgen is done on each gametick.
minetest.register_globalstep(is_mapgen_done)
function is_mapgen_done(dtime)
    --1. check if the lanes (thread) I started earlier has finished
    --2. If it has finished, write that data to the map (voxelmanip)
    --3. remove the minetest.is_protected
end
```

I should add that this not just about mapgen (although that is the biggest one that can benefit)... but any mod requiring long calculations... maybe an AI that uses a simple technique to begin with... but in the background calculates using a better method or complex power or routing system... or anything that might take longer than one minetest step to calculate.....

Sidenote: I may be unable to reply back to this post if you have any follow up questions, so I will just leave it to the minetest devs to discuss it.

multithreading

**Comment by minetestname** [comment] 2015-11-15 03:47
I should emphasize that **the main purpose for having this is to eliminate the lag caused by mods that take a long time to process** ... by moving heavy calcuations away from the single game thread, mods can be designed to not lag the server (like some do now ... and quite badly).

**Comment by paramat** [comment] 2015-11-15 04:09
Kwolekr is working on this it's intended for the future.

**Comment by est31** [comment] 2015-11-15 06:31
Getting threaded lua mapgen is more involved than just adding support for a library. You would need to solve the lock problem. Currently we have a script lock _and_ we do need locks inside the callbacks. I haven't done my own tests to confirm, but according to kwolekr, most of the mapgen is copying the map around, so basically I/O is the bottleneck.

**Comment by est31** [comment] 2015-11-15 06:43
And I'm not very sure, but I think kwolekr mentioned that luaJIT itself already forbids multithreaded access. So we would need multiple distinct luaJIT environments.

**Comment by RobertZenz** [comment] 2015-11-15 08:57
Note that there is #3182, which is about having mapgen run in its own thread, by default.

**Comment by ShadowNinja** [comment] 2015-11-16 03:18
This is already implemented, but it's currently only available to the main menu Lua environment.

**Comment by paramat** [comment] 2016-06-02 06:46
Duplicate of #3182

**Comment by est31** [comment] 2016-06-02 16:04
@paramat there is more to minetest than mapgen.

**Comment by sofar** [comment] 2016-06-02 21:03
Possible uses I can see:
- doing large computational transformations like sedimentology does (large scale erosion)
- AI code for entities
- mesecons circuitry update calculation

**Comment by paramat** [comment] 2016-06-03 07:44
Yeah, i looked at the first comment and it seemed mostly about mapgen, but not only.
Related to #3182

**Comment by paramat** [comment] 2017-09-15 06:18
Very non-trivial, kwolekr was trying to make this possible but came up against issues.

**Comment by NewbProgrammer101** [comment] 2018-11-20 04:05
reviving a non-trivial, much-requested feature thread.

**Comment by sofar** [comment] 2018-11-20 04:11
Please don't necrobump unless you have code or a significantly new development that influences the idea or scope has occurred.

**Comment by sfan5** [comment] 2021-02-28 16:50
It'd be useful to revive the discussion here to discuss one point: Sharing of environment and/or objects between threads.

Every thread (or lane) needs its own Lua environment, sharing globals is thus impossible.
Sharing the `Environment` (basically what all API functions work on) between threads is infeasible, you end up with locking everywhere which defeats the whole point.
(In other words: the code example is not useful, it will never work like that.)

Adding LuaLanes as a generic threading + IPC solution would make sense (and is suddenly not "non-trivial" anymore) and is the goal we should strive for. And as pointed out by ShadowNinja we already have such a solution that runs async jobs on worker threads for the mainmenu code.
#11006 details an API that is much more likely to actually work.

Also, a threading API will not help for mapgen (see #3182 for that), mapgen code should run on the emerge thread anyway.
You can't do this with a generic threading API, it needs to be specifically cut out for the mapgen.

**Comment by sfan5** [comment] 2022-05-02 19:06
Added.

**Closed by sfan5** 2022-05-02 19:06 UTC
Labels: @ Server / Client / Env., @ Script API, Feature request, Supported by core dev
