### ISSUE TITLE
[Android] Chat console cannot be opened/used

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#10781] opened 2021-01-04 18:24 UTC
## Problem
Currently it is possible to see only the latest chat messages that pop up directly on the screen. But it is impossible to look through all chat history as it happens on other platforms by just pressing 'T' key.

**Comment by sfan5** [comment] 2021-04-23 17:50
duplicate of #7607

**Closed by sfan5** 2021-04-23 17:50 UTC
Labels: Feature request
