### ISSUE TITLE
Mods don't get loaded anymore when the depend on other mods.

### ISSUE THREAD

**Issue by debagos** [minetest/minetest#11507] opened 2021-08-01 14:15 UTC
I just updated my server to the lastest master branch and when I fired it up again, out of ~250 mods only a handful got loaded.
All mods that only depend on default are working fine, but mods who depend (even just optional_depend) on some other mods won't get loaded. This is so annoying, I just can't bring my server online in this state... Almost the whole world is now "unknown" as you can imagine.

I changed noting besides updating Minetest and it worked fine beforehand btw... Last time I updated was round about 3 months ago.

**Comment by debagos** [comment] 2021-08-01 14:33
An example from my log:
`ERROR[Main]: mod "3d_armor" has unsatisfied dependencies:  "bakedclay" "ethereal" "moreores"`

Those dependencies are optional, why do they make the mod fail?
Interestingly all 3 mods are installed and activated and other optional dependencies like **player_monoids** are not mentioned at all in the (--verbose) log.

**Comment by SmallJoker** [comment] 2021-08-01 16:13
Duplicate of #8601

**Closed by SmallJoker** 2021-08-01 16:13 UTC
Labels: Unconfirmed bug
