### ISSUE TITLE
Expire players (like nickserv on IRC does)

### ISSUE THREAD

**Issue by codeandfix** [minetest/minetest#10960] opened 2021-02-17 21:15 UTC
## Problem

Everytime a new one-time-player connects it reserves a username.
thats broken by design. most players wont come again or will change their name.
so we need an option to:

## Solutions

a) expire old names if not used by n days
b) if no name is selected, give the player a random Guest12345 name like on IRC.
c) if a player connects without a password, all data should be deleted after disconnection

## Alternatives

mods can do this, but this is not a mod job i think

**Comment by SmallJoker** [comment] 2021-02-18 08:36
If server owners want this feature, it should be possible to implement this easily using the Lua API which allows deleting auth and player data.

**Comment by hecktest** [comment] 2021-02-19 12:36
If a mod is capable of something, it's probably fine to make it a mod.

If this is built in, there's potential to create surprising and dangerous situations if someone would have this setting enabled, while running a legacy mod or game that doesn't anticipate it. It also becomes another thing that mods must be aware of, which is a kind of burden on the programmer, such burdens must be minimized.

Imagine a memory manager that can yank a pointer from under you at any time. Doesn't sound like a fun thing to work with. This is the same, only on a longer time scale. A player name (a unique identifier of sorts) can suddenly become invalid, or worse, re-used. It just doesn't feel right to give lower level code the ability to mess with references potentially used by the code above it, you know? Even if it's perfectly possible to deal with it using some sort of notifications or checks, it reeks of bad design.

Seems much more natural that mod code can do something like this on demand, rather than have to deal with it all the time. And this is already supported.

**Comment by codeandfix** [comment] 2021-02-20 16:39
maybe it can done by a mod, but then we should have mod sql database access.
all mods should be able to read out database and should have a very simple api like asterix has, to set name=value etc by a mod.
or SQL, too. so mods dont have to have write access to the filesystem.
i promote one table per mod with a prefix like mod_modname for each mod.
then an access system where you can allow r/w/none access for each mod to general data or mod specific data.

**Comment by SmallJoker** [comment] 2021-02-20 17:14
> maybe it can done by a mod, but then we should have mod sql database access.

The backends `leveldb` and `dummy` are not SQL-based. Accessing databases from Lua API is a duplicate of #10371.

**Closed by SmallJoker** 2021-02-20 17:14 UTC
Labels: Feature request, Possible close
