### ISSUE TITLE
Dungeons outside

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5204] opened 2017-02-10 13:37 UTC
I can find a lot of dungeons outside. And I mean a lot. I think this is not by intention

![screenshot_20170210_143459](https://cloud.githubusercontent.com/assets/16163058/22828569/4ed2f20c-ef9e-11e6-8cf2-1246f2935be5.png)

**Comment by paramat** [comment] 2017-02-10 15:31
It is by intention and is one of the best features of Minetest, do you not find them stunning?

**Comment by paramat** [comment] 2017-02-10 15:48
> And I mean a lot

Are you using a smaller chunksize? These are not common.

**Comment by MarkuBu** [comment] 2017-02-10 17:05
> Are you using a smaller chunksize? 

No, but I fly around very often to search biomes

**Comment by paramat** [comment] 2017-02-10 17:36
These are not as common as the issue suggests. It's good you noticed these and reported, but do you personally wish to have a setting to avoid this happening? Or would you prefer they continue to happen but you have control over dungeon density, therefore reducing how often these happen?

When we had floating dungeon slices we also used to have many floating dungeons completely disconnected from the ground. When i fixed the slices this almost completely stopped floating dungeons so that we only have a few protruding dungeons that are almost always connected to the ground.

**Comment by MarkuBu** [comment] 2017-02-10 18:17
>  but do you personally wish to have a setting to avoid this happening?

I think yes. They could be a nice gameplay feature, but it should be possible to disable them if it is not wanted.

**Comment by ExeterDad** [comment] 2017-02-11 18:05
Dungeons by definition are underground. Just doesnt seem right. Im not so sure they are rare either.

**Comment by purveyor-of-points** [comment] 2017-02-12 07:52
I personally like them, but it'd be nice to be able to ensure certain structures stop generation when "outside". I'd ideally like it to be more of a mod/subgame feature than another toggleable menu feature, though.

**Comment by MarkuBu** [comment] 2017-02-12 12:31
Something like this is cool

![screenshot_20170212_132855](https://cloud.githubusercontent.com/assets/16163058/22862061/824218ea-f127-11e6-8f18-97462538b755.png)

**Comment by paramat** [comment] 2017-02-12 20:08
If there's enough demand i could add a setting, the default would be current behaviour.

**Comment by MarkuBu** [comment] 2017-02-20 10:42
I would like to have something like this as default. It's a great entrance 

![screenshot_20170220_113952](https://cloud.githubusercontent.com/assets/16163058/23121635/75f44a5a-f761-11e6-8f22-77dd08be09b2.jpg)

**Comment by paramat** [comment] 2017-02-20 19:05
That is the intended default, dungeons cut at terrain surface.

**Comment by hkzorman** [comment] 2017-02-22 15:38
@paramat Do you think it possible to use the dungeon generation code (albeit customized) to create surface buildings? Some kind of villages?

**Comment by paramat** [comment] 2017-02-22 21:24
I have a PR to enable above-ground structures built by dungeon code.

**Comment by hkzorman** [comment] 2017-02-24 00:38
Would it be possible to configure them to have only one room, and many structures in a same area?

**Comment by paramat** [comment] 2017-02-24 00:41
They could have one room, and there could be many in a mapchunk, but will not be placed on the ground and will not look like village houses, just windowless boxes. Villages are best done another way.

**Comment by nerzhul** [comment] 2017-06-25 12:58
OMG it's very ugly, please fix that it's non sense and non realistic

![capture d ecran de 2017-06-25 14-20-53](https://user-images.githubusercontent.com/119752/27516255-af781ce0-59b6-11e7-95b2-eedd0bdfe097.png)

**Comment by kilbith** [comment] 2017-06-25 14:09
You don't understand, those are ancient alien structures and it belongs to the charm of Minetest...  /s

![capture d ecran de 2017-06-25 16-08-12](https://user-images.githubusercontent.com/7883281/27516767-a35ecf30-59c0-11e7-9895-de0b346b20f8.png)

**Comment by red-001** [comment] 2017-06-25 15:14
it's aliens all the way down

**Comment by C1ffisme** [comment] 2017-06-25 17:17
Just to give my opinion, the overground dungeons can look really, really ugly compared to structures in other games.

**Comment by paramat** [comment] 2017-06-25 19:39
They make excellent bases when you convert them and make a few structural additions.
kilbith i like your meme but that's not really suitable for a Github thread.

I will add a setting.

**Comment by red-001** [comment] 2017-06-25 21:58
maybe make them look less like magically floating rooms and mores like ruins.

**Comment by paramat** [comment] 2017-06-25 22:08
That's not possible, they do look like ruins.

**Comment by paramat** [comment] 2017-06-25 23:37
I will make a PR with default enabled which is what i strongly prefer (these are my favourite feature of MT mapgen) but devs will have to make a decision on the setting together
I have seen just as many players saying they like these as those saying they do not, and normally when we add a setting the past behaviour is kept as the default.

To be clear, before anyone states it, although some may not like these, this is an intentional feature, not a bug. I have worked on the dungeon code a lot and intentionally let these occur.

**Comment by paramat** [comment] 2017-06-26 03:05
@SmallJoker these are not something that was meant to be fixed a while ago and was not. What i fixed then was very common floating 'dungeon slices' and floating dungeons. When that was fixed the number of outside-ground dungeons reduced a lot but a few continued to protrude from the ground, but they are at least connected with the ground and the much lower occurence makes them more acceptable.

**Comment by paramat** [comment] 2017-06-26 03:20
![screenshot_20150414_031532](https://user-images.githubusercontent.com/3686677/27523411-ef1aefbc-5a24-11e7-96fd-275ef2e64184.png)

![screenshot_20150601_033421](https://user-images.githubusercontent.com/3686677/27523434-09659f34-5a25-11e7-97da-4b7257f744ef.png)

![screenshot_20150627_083001](https://user-images.githubusercontent.com/3686677/27523447-1f7e0928-5a25-11e7-9ee5-ebc1073868cd.png)

![screenshot_20150828_065642](https://user-images.githubusercontent.com/3686677/27523454-2c39767a-5a25-11e7-98d4-4628e36b88f5.png)

![screenshot_20150829_045641](https://user-images.githubusercontent.com/3686677/27523470-4f148dd8-5a25-11e7-9aa2-2028e8ff4ef7.png)

![screenshot_20151005_051955](https://user-images.githubusercontent.com/3686677/27523493-62300d8e-5a25-11e7-8f32-55997d70fd1b.png)

![screenshot_20160327_121858](https://user-images.githubusercontent.com/3686677/27523523-97460ed8-5a25-11e7-918a-c7e1095ce83a.png)

![screenshot_20160628_045940](https://user-images.githubusercontent.com/3686677/27523533-ab563eca-5a25-11e7-8b3d-d2f82e6b9cd4.png)

![screenshot_20161219_040850](https://user-images.githubusercontent.com/3686677/27523669-a2eb0e7c-5a26-11e7-8597-6a000e0764c9.png)

**Comment by paramat** [comment] 2017-06-26 03:29
@MarkuBu your screenshot shows pale nodes embedded in the cobble by a subgame or mod, that makes the dungeon look much worse.

**Comment by paramat** [comment] 2017-06-26 05:20
PR coming for setting.

**Comment by C1ffisme** [comment] 2017-06-26 17:02
Okay, you've sold me on that 6th picture.

![](https://user-images.githubusercontent.com/3686677/27523493-62300d8e-5a25-11e7-8f32-55997d70fd1b.png)

**Comment by paramat** [comment] 2017-07-02 12:39
#6051 merged.

**Closed by paramat** 2017-07-02 12:39 UTC
Labels: @ Mapgen, Request / Suggestion
