### ISSUE TITLE
Minetest launcher

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4917] opened 2016-12-16 17:08 UTC
The Idea of this Request is To have a official minetest launcher this would provide an Easy way to get updates and install updates this can also be used to install mods and subgames 
This would be really useful for newcomers and noobies

**Comment by est31** [comment] 2016-12-16 17:52
Duplicate of  #2442 and of #3289

**Closed by est31** 2016-12-16 17:52 UTC
