### ISSUE TITLE
Update mods automatically

### ISSUE THREAD

**Issue by BruceMustache** [minetest/minetest#10212] opened 2020-07-21 10:25 UTC
## Problem

Currently I'm using https://github.com/NathanSalapat/Minetest_Mods_Updater to update my mods the problem is that I have to clone all repositories and can't use the GUI or download then of contentDB or whatever
ie: Update mods is crucial to ensure they are working and gain the best of they

## Solutions

Mods can "say" its source in mod.conf and minetest will update all in a configurable time and after that generate a changelog

## Alternatives

Alternatives can be show in this issue

**Comment by NathanSalapat** [comment] 2020-07-21 12:55
If you download the mods via the contentDB you'll see when there is an update available for them, and can then update them that way.

Automatically updating all the mods may not always be a good idea, as a mod update could break things, so it's probably best to leave the updating to the user.

If you are using my script I don't see where your problem is, it already does exactly what you are asking for.

**Comment by BruceMustache** [comment] 2020-07-21 14:01
@NathanSalapat 
`Automatically updating all the mods may not always be a good idea, as a mod update could break things, so it's probably best to leave the updating to the user.`

So maybe "content" tab can have a button  "update" that if user presses will look for updates and after that user can select which mods to  update
`If you are using my script I don't see where your problem is, it already does exactly what you are asking for.`

The problems of your is script that a found was:
1. If a folder doesn't have a .git folder it will not be updated (otherwise can't find another solution for that)
2. Can't run it on Android or Windows
3. Not a built-in feature of minetest

**Comment by rubenwardy** [comment] 2020-07-21 14:01
PR: #9995

**Comment by BruceMustache** [comment] 2020-07-21 14:04
Nice!

**Comment by rubenwardy** [comment] 2020-07-21 14:14
It only works if you download the mod using ContentDB. It uses ContentDB's API to look for updates

**Comment by rubenwardy** [comment] 2020-07-21 21:43
this is arguably a duplicate of https://github.com/minetest/minetest/issues/7369

**Comment by paramat** [comment] 2020-07-21 21:43
I agree that auto-updating is problematic, rubenwardy's PR is better as updating all mods is an option.

**Closed** 2020-08-18 23:01 UTC
Labels: Feature request
