### ISSUE TITLE
Particles - Add option to collide with liquids

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#9834] opened 2020-05-08 00:08 UTC
This would be helpful for a number of reasons, the main one I can see now is weather effects like rain continuing under water. Also smoke effects happen underwater as well.

**Comment by paramat** [comment] 2020-05-08 00:34
Duplicate of #4305 (the title is for a general feature, but the issue was initially for particles colliding with liquid, so best discuss there).

**Closed** 2020-05-08 00:34 UTC
Labels: Duplicate, Feature request
