### ISSUE TITLE
Touching a wall while falling, sometimes gets fall damage without landing on it, in version 0.4.15

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#5330] opened 2017-03-02 14:41 UTC
It's difficult to reproduce this bug:
https://www.youtube.com/watch?v=9G1zKrO7NgA

This needs to be fixed as soon as possible.

**Comment by Wuzzy2** [comment] 2017-03-02 16:10
Information: The green blocks in the video are slime blocks (`mcl_core:slimeblock`) from MineClone 2, they use `bouncy=44` as a group.

**Comment by dsohler** [comment] 2017-03-10 11:25
Confirmed on latest stable Linux build. I remember that this issue isn't new. I had this several times already since I started playing MT ~2 years ago.

**Comment by JRottm** [comment] 2017-08-10 17:51
Possibly fixed by PR #6209.
With e63df5ce80eb1a0955e04f75ce8f72f119dc5f3c I was able to reproduce this, but with 248a1a8d65c483edcab328d898cc570071d6a182 not any more. (But maybe I just wasn't trying often enough.)

Please confirm and, hopefully, close this issue. Thanks.

**Comment by SmallJoker** [comment] 2017-08-11 12:33
Closing until someone can reproduce this but with the recent collision detection fixes.

**Comment by Wuzzy2** [comment] 2017-08-11 14:07
I have tested this in 0.4.16 and **I was badly hurt**! :-(
Said commits came in before 0.4.16.

I suggest to do the experiment at least 20 times and constantly push against the wall, or a corner.

**Comment by SmallJoker** [comment] 2017-08-11 14:42
@Wuzzy2 what commits? These above are from last week, hardly believable that they were in the stable 0.4.16 build before the actual PR (#6209) was created. Does it also happen in the most recent development build?

**Comment by jastevenson303** [comment] 2017-08-11 17:53
Shoot whats that other issue with going through nodeboxes with a lot of lag.  Actually, you can slide into the corner of even a solid node with little to no lag.  I bet this is related.

**Comment by Wuzzy2** [comment] 2017-08-11 20:45
Reproduced in bb1c71158613c1f17c57e53ad489b076a11e3828.

Is this enough to re-open this?

**Comment by JRottm** [comment] 2017-08-12 13:37
Last time I jumped 15 times from Y=130, killed me early 3x before PR, but 0x after it, but appearently that was just dumb luck. After 20 jumps from Y>1000 I can confirm bug is still there. :-(  Sorry for getting your hopes up.

**Comment by SmallJoker** [comment] 2020-04-13 06:48
Does this still happen after #9343 ?

**Comment by oilboi** [comment] 2020-04-14 01:56
> Does this still happen after #9343 ?

It's swapped to the z and x axis

**Comment by TheTermos** [comment] 2020-04-14 15:16
> It's swapped to the z and x axis

Can you elaborate what the problem is?

Previously the problem occurred along all axes, probably it was just the most apparent along Y.
Axis order hasn't changed, and all axes are handled identically. I can't think of a reason for it to occur for x/z but not y.

**Comment by oilboi** [comment] 2020-04-14 18:36
> > It's swapped to the z and x axis
> 
> Can you elaborate what the problem is?
> 
> Previously the problem occurred along all axes, probably it was just the most apparent along Y.
> Axis order hasn't changed, and all axes are handled identically. I can't think of a reason for it to occur for x/z but not y.

No, but I can show you https://youtu.be/rXiIHmhjK7M

**Comment by sfan5** [comment] 2020-04-14 19:01
Note that item entities currently have a somewhat <i>special</i> relationship to collision detection (because they do not have access to the results).

I tried to reproduce the problem in your video here and couldn't get it to happen. But #9668 might also fix this for item entities especially.

**Comment by TheTermos** [comment] 2020-04-14 20:46
> No, but I can show you https://youtu.be/rXiIHmhjK7M

Great, a video is worth a thousand pictures.

- can you please list games/mods you've been using, in particular those responsible for item drop and pistons?
- please try to reproduce the player related issues with vanilla MTG.

**Comment by sfan5** [comment] 2020-04-15 00:05
Trivially reproducable with minetest_game (gcc 9.3.0):
https://0x0.st/iQjx.mp4

Interestingly when compiled with clang 9, I can't reproduce any of this. Notably (db95ff22865e8aa5eb512a1ac1f2f8715c18e3c8) that build is <b>without</b> `-ffast-math`.

**Comment by oilboi** [comment] 2020-04-15 00:32
> Note that item entities currently have a somewhat special relationship to collision detection (because they do not have access to the results).
> 
> I tried to reproduce the problem in your video here and couldn't get it to happen. But #9668 might also fix this for item entities especially.

I made a video which will help with this below



> > No, but I can show you https://youtu.be/rXiIHmhjK7M
> 
> Great, a video is worth a thousand pictures.
> 
> * can you please list games/mods you've been using, in particular those responsible for item drop and pistons?
> * please try to reproduce the player related issues with vanilla MTG.

Here is a video in which I will try to explain this and try to help with whatever is actually going on. (Hint, I have no idea, I just take guesses, but show you the effects in minimal and default game)
https://youtu.be/weZ1ws57Mqc

**Comment by oilboi** [comment] 2020-04-15 01:07
> Trivially reproducable with minetest_game (gcc 9.3.0):
> https://0x0.st/iQjx.mp4
> 
> Interestingly when the engine was compiled with Clang 9, I can't reproduce any of this. Notably ([db95ff2](https://github.com/minetest/minetest/commit/db95ff22865e8aa5eb512a1ac1f2f8715c18e3c8)) that build is without `-ffast-math`.

I will try this too!

**Comment by TheTermos** [comment] 2020-04-15 10:05
> Interestingly when the engine was compiled with Clang 9, I can't reproduce any of this. Notably ([db95ff2](https://github.com/minetest/minetest/commit/db95ff22865e8aa5eb512a1ac1f2f8715c18e3c8)) that build is without `-ffast-math`.

So this is compiler dependent.
Do I understand correctly, the build without -ffast-math worked as expected? That'd be intuitive.

I believe the ultimate cause is this #9346 
Once I done a fix here https://github.com/TheTermos/minetest/tree/object-position-precision but it is terribly outdated now.

At one point I had a hack in collision detection, an offset  to compensate for fp error, but I removed it as it didn't seem necessary on my system, I'm going to have to bring it back.

**Comment by sfan5** [comment] 2020-04-15 10:13
> Do I understand correctly, the build without -ffast-math worked as expected?

Yes, not necessarily compiler dependent I just can't test clang + fast-math right now.

**Comment by TheTermos** [comment] 2020-04-15 10:32
Well, compiler as in compiler/options.
-ffast-math is expected to cause problems for fp calculations, especially with 32 bit float. But I guess enforcing specific options is out of the question, and there are no guarantees it would work in all cases.
I'm just bringing back the hack.

**Comment by sfan5** [comment] 2020-04-15 10:48
> But I guess enforcing specific options is out of the question

Well not really. `-ffast-math` is set by our CMake script and I wouldn't expect any package maintainers to add this flag on their own, so the flag could just be removed from there.
(Or perhaps replaced with a safe subset of `-ffast-math`.)

**Comment by TheTermos** [comment] 2020-04-15 11:29
That'd be cool to check how different compilers do without the flag.
However I'm afraid I can't be of much help, I'm on Win and only managed to get MSVS to work.

**Comment by TheTermos** [comment] 2020-04-15 14:24
@oilboi can you try and compile 5.3 dev without the `-ffast-math` flag set?

The pistons, I guess we'll come back to that after the precision issue is resolved, 
but I wouldn't be surprised if they still don't work as expected after that.
Before object-player collisions were ignored client side, #9343 changes that so previous assumptions may not hold.
Also one potential problem i see is the piston uses move_to with 'countinuous' param left at default false. If I understand the docs correctly this is roughly equivalent to setting position, and that could be evil.

**Comment by sfan5** [comment] 2020-04-15 14:44
Probably not very useful but I have narrowed the problem to these two flags: `-funsafe-math-optimizations -ffinite-math-only` (a subset of `-ffast-math`, [documentation](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html))

@TheTermos would you mind coming to IRC for extended discussion of this?

**Comment by TheTermos** [comment] 2020-04-15 15:02
> @TheTermos would you mind coming to IRC for extended discussion of this?

Sure, 
just never used irc so please tell me what to do ;)

**Comment by sfan5** [comment] 2020-04-15 15:07
Visit [freenode's webchat](https://webchat.freenode.net/?channels=#minetest-dev), pick a nickname and the rest is hopefully self-explanatory.

**Comment by TheTermos** [comment] 2020-04-15 21:42
Thanks @sfan5 my findings based on the debug output:
axisAlignedCollision worked correctly, the problem with fp precision must have occured earlier outside the function. It returns the time it takes for the collision to occur, which then is used to calculate position, so the problem here seems to be:`(distance/speed)*speed != distance`

Hope #9682 resolves the issue without the need for hacks.

**Closed** 2020-04-16 08:23 UTC
Labels: Bug
