### ISSUE TITLE
It should be possible to add assets without requiring server restart

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest#5040] opened 2017-01-14 18:19 UTC
Hi, i hope my title is not too confusing.
I am/was working on a skinserver.
The mod-endpoint checks for a skinfile called like the playername and if available,
it simply applies the skin to it `on_joinplayer`.

Now i ran into the following problem:
When a new skin is added and the player rejoins, Minetest actually sees "hey, there is a skin!" and applies `nil`/a not available skinfile to the player because the file is not yet initialized by the server as it seems.
The result is a dummyimage for the skin which confuses the players.

**Comment by sfan5** [comment] 2017-01-14 18:43
duplicate of #4845

**Closed by sfan5** 2017-01-14 18:43 UTC
