### ISSUE TITLE
Fix floating sand by turning it into sandstone

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6403] opened 2017-09-10 14:29 UTC
This is 50% bug report and 50% feature request. :D 

In the v7 mapgen (and possibly others, I haven't tested) it is common for falling nodes like sand to float, especially in deserts. Floating sand is relatively easy to find.
This is very common around cave entries. Sometimes the amount of floating sand can be quite large and the CPU will cry when they start falling all at once. xD So in general the mapgen should avoid to generate floating falling nodes.

Here's an example with coords and seed:
![](https://i.imgur.com/tw0bPY2.png)
https://i.imgur.com/tw0bPY2.png

My creative idea to fix this is to simply turn any floating falling node into a different non-falling node. A floating falling node is any node which is a falling node above a non-walkable node. To simplify this check, the mapgen might only check against air, water and lava.
For example, sand becomes sandstone, silver sand becomes silver sandstone, etc.

I'm not sure how the engine could support this with the Biome API. Maybe add a `*_solidified` variant (or whatever you like to call it) for each `node`.
That is:

* `node_top_solidified` is the “solidified” version of `node_top`
* `node_filler_solidified` is the “solidified” version of `node_filler`
* and so on
* If `nil`, the node is not modified even when floating. This is entirely optional
* Therefore, if the subgame does not implement this, nothing is changed

Now a subgame like Minetest Game could simply add `node_top_solidified = "default:desertsandstone"` and `node_filler_solidified = "default:desertsandstone"` to the desert biome definition. This not only fixes floating sand, but also makes some interesting-looking cave entrances or bridges. Like this (built by me, I replaced the desert sand by hand):

![](https://i.imgur.com/H9CPgWi.png)

I don't know if we have floating sand in v6.

I'm posting this in `minetest` and not `minetest_game` because you'll find deserts and sand in virtually all subgames.

**Comment by HybridDog** [comment] 2017-09-10 18:07
In reality there're also sometimes things which collapse if you touch them. l'd prefer making only parts of it to sandstone to prevent huge falls.

**Comment by Wuzzy2** [comment] 2017-09-10 20:42
Huh? The point of making sand to sandstone so they do *not* fall. Why only making a part of it to sandstone?
AFAIK setting a node is not the same as “touching” it and AFAIK it doesn't trigger falling. So setting sand to sandstone should be safe.

**Comment by raymoo** [comment] 2017-09-11 04:13
@Wuzzy2 I think that @HybridDog meant that in real life you sometimes have unstable structures.

**Comment by paramat** [comment] 2017-09-11 16:19
The biome-generating code will only place biome surface nodes (dirt, grass, sand etc.) if there is stone below supporting it. This issue is caused by cave generation, which simply places air but does not check if it is excavating from under a biome surface node, i guess for simplicity and speed.

I don't see these unsupported surface nodes as a big issue as they are only above cave entrances, and it is fun to have some volumes of falling nodes to punch and collapse. But yes we can consider making sure all biome surface nodes are supported.

> turn any floating falling node into a different non-falling node.

Only acting to support falling nodes is too complex, as we then need to access nodedefs, the best way to do this is to turn the node to the local biome stone node, which is exactly what biome-generation code does to keep biome surface nodes supported. it is much faster to access the biome stone node than the 'falling' nodedef, and the biome stone is often already known by cave generation.
So if this is done it will be done for all biome surface nodes not just falling nodes (which is exactly how biome-generating code acts too).

> I'm not sure how the engine could support this with the Biome API. Maybe add a *_solidified variant (or whatever you like to call it) for each node.

Far too overcomplex, just placing the biome stone node is fine and looks more consistent with the environment. For example in your screenshot above that sandstone looks out of place because there is no other sandstone around anywhere, that would look much better as desert stone, which is the correct stone to use in that situation.

Will consider.

**Comment by paramat** [comment] 2017-09-11 17:12
This happens in all mapgens.
I can understand this not being coded because the vast majority of caves are underground in solid stone where these checks would be pointless. So doing this for the pseudorandom large caves or massive caverns is pointless.
I will consider it for the 3D noise tunnels though, as these are the ones that often reach the surface.

**Comment by paramat** [comment] 2017-09-11 19:30
Yes i will work on this. Our 3D noise tunnels are larger now and significantly shape the surface, adding supporting stone will make them seem more like valid terrain and will give some nice visual definition.

**Comment by Wuzzy2** [comment] 2017-09-11 20:09
> and it is fun to have some volumes of falling nodes to punch and collapse.

This should be up to the subgame author to decide whether this behaviour is desired. As I said, there's always the option to not use the “solidification”.

> Only acting to support falling nodes is too complex, as we then need to access nodedefs

Not if my biome API suggestion is implemented. If this is done, Minetest can just blindly plug in the name provided in the biome definition, no need to access anything at all.

> > I'm not sure how the engine could support this with the Biome API. Maybe add a *_solidified variant (or whatever you like to call it) for each node.

> Far too overcomplex

I don't see how a few added fields are too complex. I stick to my suggestion that it should be possible to replace the sand with a node chosen by the subgame author (not just biome stone). but I am open to discussion about how the API should look.

> just placing the biome stone node is fine and looks more consistent with the environment.

This should be up to the subgame developer to decide. 
But using the biome stone node as a fallback if `top_node_solidified` missing is a good idea.

>  For example in your screenshot above that sandstone looks out of place because there is no other sandstone around anywhere, it is foreign to that biome, that would look much better as desert stone, which is the correct stone to use in that biome.

Paramat, in a lot of your arguments you are overgeneralizing. What is true for MTG is not true for other subgames. I'm actually fine if you want to use desert stone in MTG. But there other subgames are different. The reason for this Biome API suggestion I made this suggestion is to make the API more flexible.

Note that for my subgame, I want this:

![](https://i.imgur.com/rQ8ePJZ.png)
![](https://i.imgur.com/4CiPF4Z.png)

And not this:
![](https://i.imgur.com/JbWzEdr.png)

**Comment by paramat** [comment] 2017-09-11 20:47
PR #6408

**Comment by paramat** [comment] 2017-09-11 20:54
> I don't see how a few added fields are too complex.

Adding biome fields is a major change that needs a lot of justification.

> This should be up to the subgame developer to decide.

Not if the implementation is unjustified.

> What is true for MTG is not true for other subgames.

I'm referring to all subgames, anything but the biome stone node is somewhat out of place, and also inconsistent with how mapgen places biome stone instead of unsupported biome nodes everywhere else. I agree that your idea (and the implementationin your subgame) can look good, but the implementation necessary is unjustified, sorry.

**Comment by Wuzzy2** [comment] 2017-09-13 05:47
What kind of justification is required for Biome API changes?

**Comment by paramat** [comment] 2017-09-14 01:02
Adding new fields needs significant justification, you can see that the one's we have are all very fundamental and heavily used. I'm still unsure we needed 'depth of riverbed' or if that should have been hardcoded.

**Comment by paramat** [comment] 2017-09-14 03:18
#6408 merged.
:-1: for this specific request.

**Closed by paramat** 2017-09-14 03:18 UTC
Labels: @ Mapgen, Request / Suggestion
