### ISSUE TITLE
Server Sent Settings

### ISSUE THREAD

**Issue by FatalError42O** [minetest/minetest#13539] opened 2023-05-28 21:09 UTC
## Problem

The problem: 
Certain features apart of user configured settings can cause unpredictable behavior that modders cannot work around. 
A very personal and depressing example, is my 3dguns mod that I had developed but I have since abandoned in realization of the many issues, the prime one being- viewbobbing. 
Here's a video example: https://youtu.be/V7ivox3edl0

This solution would not only solve this problem, but offer a large number of benefits for modders to stylize and control their mods and games.

## Solutions

The server should be allowed to send a table (or perhaps a string in the config format) with settings that will overwrite the user's settings temporarily (i.e. until server exit or overwrite from server). Exclusions should apply for certain attributes and config settings (see the following)

acceptable settings from categories (from config menu, excuse me if the technical names are wrong, because they are lol):

- Advanced.TemporarySettings
- Graphics and Audio (excluding graphics.3d, graphics.screenshots, graphics.FPS.fps_max, graphics.FPS.fps_max_unfocused, graphics.FPS.undersampling and MAYBE excluding graphics.filteringAndAntialiasing) 
- Controls

 
## Additional context

Problems this could solve: 

- View bobbing, cinematic mode, fall bobbing, and other offsets causing improper and unpredictable camera alignment (allowing for highly enhanced camera control for modders such as myself), 
- Enforce settings (such as "build where you stand") which could potentially be problematic or buggy in some situations
- Allow direct sensitivity changing by storing user sensitivity
- Add a host of graphics options
- Lower the near plane (once again see 3dguns, this would allow the player to see their arms which would look *amazing*
- Force enable fog! This would solve the "seeing people and entities through walls" issue which plagues pvp servers.
- Crosshair and selectionbox colors and changes, enforcing entity selection box.

I think it's also important that the (relevant data) from the user config can be pulled, to allow the game to know what the player wants without breaking that desired behavior. This could be accomplished in the same format that is provided to the function called to set the player's (relevant) config. This would put some of the user's settings at the discretion of the modder.

For a number of reasons, the user config of course would not be effected in any way by the server's overset config, and thus would be completely separate.

**Comment by wsor4035** [comment] 2023-05-28 21:14
duplicate of https://github.com/minetest/minetest/issues/11227

**Closed** 2023-05-28 21:14 UTC
Labels: Duplicate, Feature request
