### ISSUE TITLE
Critical bugs to be fixed before 0.4.13

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3031] opened 2015-08-10 16:21 UTC
0.4.13 will be hopefully released some day, but until then this list of bugs has to be fixed:

* #3011

Please suggest new bugs to be added in irc, or on this thread, but it should be discussed whether the bug fulfills the following criteria:
1. For those affected, it ruins playing (e.g. crashes minetest often, etc.)
2. Is a regression since 0.4.11. If it affects an added feature since then, it should be added below.

On consensus, core devs can edit this issue comment to add the specific issue.

Bugs affecting new features since 0.4.11, which can be avoided by not using the feature:
* #3027
* #3032

**Comment by PilzAdam** [comment] 2015-08-10 16:33
https://github.com/minetest/minetest/issues?q=is%3Aopen+is%3Aissue+label%3Ablocker
The "blocker" label marks are issues that need to be fixed before the next release. No need to create a new issue for that.

**Comment by est31** [comment] 2015-08-10 16:46
The blocker label is useless, there is no actual discussion happening whether its a blocker. Also, there are devs who keep a list of blocker bugs in their brains, without tracking them at github. It  seems the current ways aren't ok for them.
As a technical argument, I can't subscribe the blocker label, and the label can be added to very old bugs, so I can't even see which issue got the label recently.

**Comment by paramat** [comment] 2015-08-10 17:10
#2653
It seems 'client unload unused data timeout' is perhaps not actually freeing memory by deleting mesh data, even though meshes disappear from view. Memory use can rise at 0.3 to 0.7 GB per minute when flying over the world, this means only 10 minutes playing time on a machine (like mine) with 8GB RAM.
Also, memory use often does not drop when exiting from a world to the menu, although this behaviour varies. It is necessary to exit the game completely to clear the memory.
However i am getting erratic confusing results, and reducing the timeout value sometimes seems to help.
Even if all this is fixed, the timeout value needs to be reduced to no more than 5 minutes (2.5GB mesh data).

**Comment by PilzAdam** [comment] 2015-08-10 17:12
@est31 When the blocker label was introduced there was a rule that it may only be added to issues together with a comment explaining why it is a blocker. If such a comment is missing from any of the issues marked as blocker then the label can be removed.

A label offers a better overview than an issue with a ton of links and it's easier to mark them as blocker (no need to search for the issue that marks issues as blockers for the next release).

**Comment by est31** [comment] 2015-08-10 17:35
that rule makes sense, then the blocker label is indeed much more attractive. Perhaps have both issue and label?

**Comment by PilzAdam** [comment] 2015-08-10 17:54
@est31 The issue is probably helpful directly before the release, but the label should be the main indicator for blocking issues.

**Comment by est31** [comment] 2015-08-10 18:42
@VanessaE brought up #2945 and #2984 for addition on the list.

**Comment by nerzhul** [comment] 2015-08-20 09:30
0.4.13 was released

**Closed by nerzhul** 2015-08-20 09:30 UTC
Labels: blocker, bug, High priority
