### ISSUE TITLE
Player's head/camera moving on its own

### ISSUE THREAD

**Issue by ivarec** [minetest/minetest#4287] opened 2016-07-06 01:38 UTC
Sometimes the player's camera starts moving on its own, as if I'm moving the mouse, but without me giving any kind of input to the game. It's a slow and continues move on a single direction, e.g. to the right. I've seen a somewhat similar issue at #4221, but in my case disabling **enable_joysticks** in minetest.conf doesn't help. There are a few people [reporting the same thing on Reddit](https://www.reddit.com/r/Minetest/comments/4ehcmd/mouse_moves_on_its_own/).

How can I help debugging this? Where should I look in the code and how should I instrument it?

Version 0.4.14 on Windows 10.

**Comment by est31** [comment] 2016-07-06 01:46
IDK, print out dx and dy inside `Game::updateCameraOrientation` ?

I'd have said its the joysticks, but you've ruled that out apparently.

**Comment by Philipbenr** [comment] 2016-07-06 01:47
Does it generally progress to the left or right?

**Comment by haolez** [comment] 2016-07-06 02:22
Laptop. Happens with touchpad and I think it happens with my external USB mouse as well. Gotta confirm that second part.

Is there a way to print traces in the screen itself (like the fps counter)? Might be easier than checking the console.

**Comment by haolez** [comment] 2016-07-06 02:23
> Does it generally progress straight to the left/right?

Yes, it's perfectly straight to the left/right.

**Comment by Philipbenr** [comment] 2016-07-06 02:33
Then I can confirm. This has happened to me before. I am also on a laptop, and it was running Slackware 14.1 64bit and Minetest 0.4.10 (I believe) at the time. It is gone, and I have no clue what the fix is. I am still using a laptop too, with no issues

**Comment by haolez** [comment] 2016-07-06 02:37
I will get some data from the code itself. Will post back in a couple days.

**Comment by paramat** [comment] 2016-07-06 07:01
This has happened to me before with a laptop touchpad, i can't remember how i fixed it.

**Comment by haolez** [comment] 2016-07-06 11:36
It seems to be a rounding issue when dividing the screen size by 2. There are several possible fixes. I proposed one at #4289.

**Comment by est31** [comment] 2016-07-06 16:56
Uneven screen size? That's weird.

**Comment by haolez** [comment] 2016-07-06 17:16
Yeap. My window was fixed as 800x600. Maybe this is a consequence of a bug somewhere else, but I think a fix like this should be used regardless because it might affect a lot of players as-is.

**Comment by haolez** [comment] 2016-07-31 21:07
I've done more research on this issue and the problem seems to originate in Irrlicht. It seems that we are setting the cursor position to the exact center of the screen, but Irrlicht will return the cursor position with rounding errors afterwards.

In my tests, I'm using a **800x600** screen. I've instrumented Game::updateCameraOrientation at the very beggining when getting the mouse coordinates and screen size and also Game::updateCameraDirection just before calling setMousePos. Here are some sample logs when the player's head starts moving to the right on its own:

```
setMousePos(400,300)
mouse.x:401
mouse.y:300
screen.w:800
screen.h:600
=====================
setMousePos(400,300)
mouse.x:401
mouse.y:300
screen.w:800
screen.h:600
=====================
...
```

And it goes on like this forever. As you can see, we set the X position to 400 and Irrlicht returns 401 soon afterwards. So, if I understand correctly, Irrlicht is failing to properly update the cursor position on specific scenarios that are not clear yet (but it's very easy to reproduce on my machine).

I'll try to get more information on this, but meanwhile we could try to come up with an acceptable workaround. The bug doesn't seem easy to fix. Some help from a Minetest engine guru would be highly appreciated :)

**Comment by kahrl** [comment] 2016-07-31 21:37
@haolez hmm, interesting results.

On Windows, Irrlicht uses the functions [SetCursorPos](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648394(v=vs.85).aspx) and [GetCursorPos](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648390(v=vs.85).aspx) to set and get the cursor position. A web search for "SetCursorPos GetCursorPos off by one" leads to this page: [Bug with GetCursorPos in Windows 8 Pro (MSDN Forums)](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/9e21ae38-cd25-4c37-affa-52678c918d46/bug-with-getcursorpos-in-windows-8-pro?forum=windowsgeneraldevelopmentissues)

Which suggests that the bug might be due to Windows's DPI virtualization. @haolez: what is the DPI setting on the affected machine?

Maybe the bug could be fixed by calling the [SetProcessDPIAware function](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633543%28v=vs.85%29.aspx) or by adding an application manifest that says the program is DPI aware, like recommended in the thread that I linked to.

**Comment by haolez** [comment] 2016-07-31 22:05
Wow! My dpi is set to **144**, @kahrl. It actually looks good on my screen, so it must have been set by the vendor of my laptop. This might be related to HiDPI screens on Windows.

I'll adjust to 96 and try to reproduce the issue again later today.

**Comment by haolez** [comment] 2016-08-01 08:46
@kahrl seems to have nailed it. I can't reproduce the issue when dpi is set to 96 (100%). Any other configuration will make it reproducible again.

**Comment by haolez** [comment] 2016-08-01 09:22
Disabling DPI awareness using Windows compatibility mode fixes the issue, but then it becomes... DPI enabling aware. The window gets smaller than what it was before. This might surprise a lot of users who have not been experiencing this bug at all. Don't know.

Anyway, since it's a bug in Windows 8 and 10, we might try to add a workaround specific to these versions. But that might bloat the code a little :)

I'll leave this call to the dev team.

**Comment by kahrl** [comment] 2016-08-01 19:11
As far as I know, the correct way to disable DPI virtualization is via the application manifest.

If `SetProcessDPIAware` (or the newer `SetProcessDPIAwareness`) is not defined by the Windows headers, it could still be called via a `LoadLibrary` + `GetProcAddress` workaround; however that is not recommended as the function might be called too late, for example some DLLs might have already been ininitialized and have cached the DPI settings before the function is called. An application manifest however is applied before all DLLs are loaded, so this problem would not arise.

I don't have a Windows machine to test on, so I can't test anything (and so I won't create a pull request for this). But adding an application manifest should be pretty simple in theory:

* Add the following line to `misc/winresource.rc`:
```
CREATEPROCESS_MANIFEST_RESOURCE_ID RT_MANIFEST "app.manifest"
```
* Create `misc/app.manifest` with the following content:
```
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
  <assemblyIdentity type="win32" name="minetest" version="0.0.0.0"/>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <asmv3:application>
    <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware>true</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>
</assembly>
```
Notes:
* `<requestedExecutionLevel level="asInvoker" .../>` means that elevation to admin is not needed.
* `<requestedExecutionLevel ... uiAccess="false"/>` means that access to protected system UI is not needed.
* `<dpiAware>true</dpiAware>` disables DPI virtualization.
* I'm not sure if the `version` attribute of `assemblyIdentity` needs to match the minetest version. That would make the release process a tiny bit more complicated.

And yes, there probably needs to be some code added that scales the default window size according to DPI (at least on Windows). As for the other parts of DPI awareness, I think all of that is already handled by the code that scales forms and fonts according to DPI, so that should be fine.

**Comment by tomasbrod** [comment] 2016-08-06 16:44
Can confirm on Linux, old hp centrino laptop debian touchpad, trackpad and usb mouse connected, mouse cursor does not move on its own outside minetest. 
This was long ago, since then I bought a new laptop that solved the issue.

**Comment by echosa** [comment] 2016-08-17 01:24
I downloaded the game this week and I experience mouse drifting in Windows 10 on my MacBook Pro. When I run the game in OS X 10.11.6, I don't have the drifting issue; it only happens in Windows. (I don't have a Linux install to try.) I use an Evoluent Vertical Mouse 4 (wireless). I believe this also happened when using the trackpad, but I don't remember. (I'm not in Windows right now.)

**Comment by est31** [comment] 2016-08-17 01:28
I think the bug is reported by enough people and reproducible enough to get the blocker label. It even has a fix proposed.

**Comment by haolez** [comment] 2016-08-17 02:43
The fix is not so good, as it might introduce a small regression. I couldn't find the time yet to continue on the DPI effort, but I suggest the following workaround for any players bumping into this issue until a valid fix is proposed:

1. Create a shortcut to minetest.exe
2. Go to Properties->Compatibility
3. Disable the checkbox for the DPI stuff

**Comment by rubenwardy** [comment] 2016-08-17 10:57
I can reproduce this on the W10 partition of my laptop, but not the Xubuntu 16.04 one. As expected

**Comment by echosa** [comment] 2016-08-18 13:19
@haolez's suggested workaround seems to work. :+1:

**Comment by neuhaus** [comment] 2016-09-18 09:35
I also get this issue. It's highly annoying.

I'm on W10 Pro with a 3840x2160 screen.

**Comment by paramat** [comment] 2016-11-07 22:03
#4701 merged, hopefully fixed.

**Comment by ClobberXD** [comment] 2018-11-14 04:29
Just came across this issue today, and realized that I've been facing this issue too. My pointer automagickally drifts to the right all of a sudden, once or twice an hour. I use 0.4.17 on both Ubuntu 18.04 and Windows 7, and I'm guessing the problem is only on Windows. I'll observe this phenomenon more carefully, and will confirm then.

**Comment by SmallJoker** [comment] 2018-11-15 18:53
Maybe the scaling of Windows messes up the mouse centring function. Try to apply compatibility options to the Minetest executable (mainly those about scaling) and check whether the issue persists after restarting Minetest.

**Comment by Innomen** [comment] 2018-11-15 22:22
> Also digging out old answers. Try to adjust the DPI settings of the Minetest executable: [#4287 (comment)](https://github.com/minetest/minetest/issues/4287#issuecomment-240298978)

Yeah, that works for now for me as well. I use a shortcut in the root anyway because bin folder hehe.

**Closed** 2021-01-29 18:59 UTC
Labels: @ Client / Audiovisuals, Bug, Windows
