### ISSUE TITLE
Add translation into English for mod translation

### ISSUE THREAD

**Issue by BrunoMine** [minetest/minetest#6605] opened 2017-11-10 01:20 UTC
Currently my `modname.en.tr` is ignored.
My mods are primarily in Portuguese (my native language).
Writing wrong terms in the code causes great problems in the future.
I consider this a bug. I wish it was fixed before the release.

Minetest version : 0.5.0-dev-20a85d7
OS : Ubuntu 17.10

**Comment by sfan5** [comment] 2017-11-10 16:03
duplicate of #6503

**Closed by sfan5** 2017-11-10 16:03 UTC
Labels: @ Script API, @ Translation, Bug
