### ISSUE TITLE
Multiple output slots for joint production

### ISSUE THREAD

**Issue by spixi** [minetest/minetest#7767] opened 2018-10-03 22:54 UTC
##### Issue type
 - Feature request

##### Minetest version
```
Minetest 0.4.14 (Linux)
Using Irrlicht 1.8.1
Build info: VER=0.4.14 BUILD_TYPE=Gentoo RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=0 STATIC_SHAREDIR="/usr/share/minetest"
```

##### Summary
Currently, crafting only allows one product. There is the replacement feature, but it currently only works correctly for stacks of one item (e. g. lava bucket -> empty bucket) . It would be great, if there were multiple output slots. That would allow you to produce multiple different items from one crafting receipt at the same time. If you take the first output item, the input must be consumed and the input slots must be locked until all output slots are empty.

The following snippet does not work, because it just displays the craftpreview field three times instead of three separate fields.

```
minetest.register_on_joinplayer(function(player)
  player:set_inventory_formspec(player:get_inventory_formspec().."list[current_player;craftpreview;7,0;1,1;]list[current_player;craftpreview;7,2;1,1;]")
end)
```

**Comment by SmallJoker** [comment] 2018-10-04 17:59
Feels a lot like a duplicate since this request comes each year. Will mark as feature request until the original report is found.

**Comment by spixi** [comment] 2018-10-04 18:10
@SmallJoker Thank you. I could not find an issue containing the term "joint product", "co-product" or "coproduct".

**Comment by paramat** [comment] 2018-10-04 18:30
Duplicate of #7300

**Closed by paramat** 2018-10-04 18:30 UTC
Labels: @ Script API, Feature request
