### ISSUE TITLE
Players spawn at 0,0,0 after login

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4728] opened 2016-11-04 21:43 UTC
When you login, you start at 0,0,0 (not even on spawn or home), your previous position on server is lost for unknown reason.
Happens on Liberty Land (few days old 0.4.14-dev) and Xanadu (0.4.14) to some players... like me.

This bug is different from https://github.com/minetest/minetest/issues/4403 :trollface:

LL admin said to me that roughly 10 days ago build was working OK, soooo my suspects are >_>:
https://github.com/minetest/minetest/commit/9d25242c5c1411d692254cf910345d51c9a24fa3
https://github.com/minetest/minetest/commit/595932a8602292f28333ce14e20cee4b6d8820c1

@nerzhul 

this appears to be dupe of https://github.com/minetest/minetest/issues/4718

**Comment by est31** [comment] 2016-11-04 23:32
Marking as blocker, for the case its indeed a regression.

**Comment by paramat** [comment] 2016-11-05 00:23
Duplicate, discuss in #4718

**Comment by est31** [comment] 2016-11-05 00:33
Its no dupe

**Comment by est31** [comment] 2016-11-05 00:35
Errmm sorry, you were right.

**Closed by est31** 2016-11-05 00:35 UTC
Labels: Blocker, Bug
