### ISSUE TITLE
Reducing the hotbar size to something lower than the current selected slot doesn't bring you back to one of those still present

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#11921] opened 2022-01-02 18:07 UTC
##### Minetest version

```
5.4.2 | 5.5.0-dev (e030d9c, latest)
```

##### Summary
If you have an hotbar slot selected (let's say n°8) and then you reduce the hotbar item count to something that is lower (let's say 5), your hand will still point to slot n°8, that is now out of bounds. This doesn't allow you to do some actions, like opening a chest, interacting with a `signs_lib` sign etc., and every click generates this in the log:
`ACTION[Server]: Player: singleplayer tried to access item=8 out of hotbar_itemcount=5; ignoring.`

It'd be best to automatically select either the biggest of the lowest slot still present in the hotbar, also because it's not something you notice that easily. In fact, I spent an hour debugging and backtracking with a friend the other day, thinking that my mod had broken the game somehow.  
Another case is this minigame called [Sumo](https://content.minetest.net/packages/MisterE/sumo/) that reduces your hotbar to 1, giving you a stick to push people around. If you were on another slot before entering the match, you have to manually select the first slot or you won't be able to play (because you need the stick)

##### Steps to reproduce
```lua
minetest.register_on_joinplayer(function(player)

    player:hud_set_hotbar_itemcount(10)
    
    -- now manually go on the 10th slot and wait
    
    minetest.after(3, function()
        player:hud_set_hotbar_itemcount(8)
    end)

    -- now you're out of bounds

end)
```

**Comment by sfan5** [comment] 2022-01-02 19:47
duplicate of #11525

**Comment by Zughy** [comment] 2022-01-02 20:47
@sfan5  that issue is different, it's about resizing the hotbar to something bigger than the inventory, which causes a crash. Here is about reducing the current hotbar, having the hand of the player pointing to something that it is not in the hotbar (if the hand was in one of the removed slots), causing bugs (but not crashes)

**Closed** 2023-01-08 13:03 UTC
Labels: Bug, @ Client / Audiovisuals, Beginner Friendly, UI/UX
