### ISSUE TITLE
Password field misbehavior: contents pan out of visible range proportionally to width of plain text string

### ISSUE THREAD

**Issue by vintprox** [minetest/minetest#13269] opened 2023-03-02 11:13 UTC
##### Minetest version

```
5.6.1
Flatpak
```

##### OS / Hardware

Operating system: Manjaro Linux 22.0.2
CPU: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx

GPU model: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] (rev c2)
OpenGL version: 4.6

##### Summary

I encountered this problem when pasting my long password (that I took from password manager) in the "Password" field that is used for connection through Minetest upstream launcher. It was long enough to make the field freak out and not show anything, even with maximized window.

The more you type, the more it pans contents to the left. If window width is reduced, field width is reduced too, hence it takes less characters to make contents move away out of visible range.

Peculiar formula is observed. If you insert just a lot of exclamation marks or dots, which have the least visible character width, despite being masked behind asterisk/stars, it takes more of them to make password field freak out. But, if you type wide symbols (like `@`, `W`, etc.), it takes less to do that. If you reduce window width, shift occurs more prominently.

Considering that I've got this issue on Full HD width (1920) and using password consisting of 40 mixed characters, I think it is worth reconsidering the algorythm that form uses for this input field. And it happens only with password field, because it's supposed to show every symbol as asterisk.

Easy fix would be to account for the visible width of asterisks, not plain text password (or use monospace font for calculations, which is not robust idea).

##### Steps to reproduce

1. Open "Join Game" tab in Minetest launcher.
2. Start typing different stuff in "Password" field.
3. Once the width of plain text string exceeds the field width (that you can't see because of asterisks), observe how asterisks move to the left the more you type.
4. Type some more and see how it goes completely out of visible range.
5. Select entire string by pressing `Ctrl+A` and delete it.
6. See that everything returns to how it was before you started typing anything.
7. Try pasting password into the field by pressing `Ctrl+V`.
8. Depending on the width of underlying plain text string, it will display asterisks, shift them to the left, or make them disappear.
9. Given that you inserted the correct password, you still should be able to log in to the server. It's just a visual bug of the form.

**Comment by Desour** [comment] 2023-03-02 18:48
Duplicate of #9368, which was closed, because it was an upstream issue. Now we use our own irrlicht fork, so this should be fixable.

**Comment by sfan5** [comment] 2023-03-03 22:29
Closing in favor of reopened older issue.

**Closed by sfan5** 2023-03-03 22:29 UTC
Labels: Unconfirmed bug, Duplicate, Formspec
