### ISSUE TITLE
Minetest 5.5.1 fails to run with OpenGL 2.1

### ISSUE THREAD

**Issue by Noisytoot** [minetest/minetest#12518] opened 2022-07-07 18:09 UTC
##### Minetest version

```
5.5.1
```

##### OS / Hardware

Operating system: GNU Guix System
CPU: Intel Core 2 Duo P8600

GPU model: Intel Integrated Graphics
OpenGL version: 2.1

##### Summary

Minetest fails to run with the error:
```
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  0 ()
  Serial number of failed request:  115
  Current serial number in output stream:  115
```

This does not occur with LLVMpipe when using OpenGL 3.0 or newer (`LIBGL_ALWAYS_SOFTWARE=true MESA_GL_VERSION_OVERRIDE=3.0`), but does occur when using hardware acceleration or LLVMpipe with OpenGL 2.1 (`LIBGL_ALWAYS_SOFTWARE=true MESA_GL_VERSION_OVERRIDE=2.1`).

##### Steps to reproduce

Run Minetest 5.5.1 with the environment variables `MESA_GL_VERSION_OVERRIDE=2.1` (not required if the OpenGL 2.1 is the latest version supported by your GPU) and `LIBGL_ALWAYS_SOFTWARE=true` set (not required if your GPU supports OpenGL 2.1).

**Comment by sfan5** [comment] 2022-07-07 19:23
This is very likely a duplicate of #12467

**Comment by Noisytoot** [comment] 2022-07-07 21:44
This bug seems to only occur in release mode. It does not occur in debug mode with either 5.5.1 or the latest master. At least on the latest master, minetest sometimes fails to start with the following error, which is very weird as it does not always occur and minetest does not even use libxcb:
```
2022-07-07 20:36:25: WARNING[Main]: Irrlicht: X Error: GLXBadFBConfig
2022-07-07 20:36:25: WARNING[Main]: Irrlicht: From call : unknown
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
minetest: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted
```

**Comment by SmallJoker** [comment] 2022-07-08 08:31
Rough testing results:

 * Minetest 2022-05-01 (IrrlichtMt4) + IrrlichtMt4 : success
 * Minetest 2022-05-27 (IrrlichtMt6) + IrrlichtMt4 : success (program fails later on due to Irrlicht version mismatches)
 * Minetest 2022-05-27 (IrrlichtMt6) + IrrlichtMt6 : fail
 * Minetest 2022-05-27 (IrrlichtMt6) + IrrlichtMt5 : fail
 * Minetest 2022-05-01 (IrrlichtMt4) + IrrlichtMt6 : fails early (same error as reported)
 * Minetest 2022-05-01 (IrrlichtMt4) + IrrlichtMt5 : fails early (same error as reported)

The testing results indicate that the issue lies between IrrlichtMt 4 and 5 and is not caused by Minetest.

**Comment by sfan5** [comment] 2022-07-08 08:34
here's a guess -> https://github.com/minetest/irrlicht/commit/d59bcdbd0706ac5eb90f55e346904315a9eaf3e2

**Comment by SmallJoker** [comment] 2022-07-08 08:36
@sfan5 Yes, reverting that commit gets rid of the reported error.

**Closed** 2022-07-09 20:08 UTC
Labels: Bug, Upstream issue, Linux, @ Client rendering engine

**Comment by erlehmann** [comment] 2022-07-24 17:49
For the record, this was also an issue when building Minetest on Reform 2.
