### ISSUE TITLE
Add Reconnect Button when Connection timed out

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10241] opened 2020-07-30 10:48 UTC
## Problem

If i want to join a server that just start up, i will get a connection timed out error.
I want a button to reconnect

## Solutions

I don't know, just add a button to reconnect

## Additional context

In minetest.request_shutdown, i can set a bool to enable/disable the reconnect button.

**Comment by SmallJoker** [comment] 2020-07-30 17:15
Duplicate of #8520

**Closed by SmallJoker** 2020-07-30 17:15 UTC
Labels: Feature request
