### ISSUE TITLE
error messages: lines are not filled up

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest#4785] opened 2016-11-17 14:28 UTC
![errormessage](https://cloud.githubusercontent.com/assets/7613443/20392375/dc89fdb6-acd7-11e6-859b-0b032a41ba60.png)
(i replaced my name with `<me>` with gimp, my name wasnt much bigger)
**shouldnt be the lines filled up to the end?**
(im not totally sure, if this issue is already reported because i didnt know exactly for what i should search)

**Comment by est31** [comment] 2016-11-17 15:00
Yeah its because line wrap is implemented in lua and not in the drawing code. Probably irrlicht should handle this in the perfect case...

**Comment by rubenwardy** [comment] 2016-11-23 17:14
possible duplicate of #3807

**Closed** 2016-11-23 18:31 UTC
Labels: Duplicate, Feature request

**Comment by DS-Minetest** [comment] 2016-11-23 19:01
#### i think, this issue isnt about the same

this issue here is, that for example the `/init.lua:` is not fully written in one line, although there is enough space. instead the `a:` is written into a new line.

that other issue is a feature request for
> a formspec element to show a text box

**Comment by ShadowNinja** [comment] 2016-11-24 05:25
This is a hack/bug.  The line just gets split after a certain number of characters instead of being properly wrapped based on drawn width since the engine doesn't support that.
