### ISSUE TITLE
placing blocks when jumping

### ISSUE THREAD

**Issue by erika564** [minetest/minetest#15282] opened 2024-10-13 15:12 UTC
In game when you jump and place two blocks really fast below you, you end up clipping inside the other block. After that if you try to sneak to prevent falling, it  doesn't work and you fall.

https://drive.google.com/file/d/1jCBYRDndyA3T7fhUwr0vtSdPtbjGsdsm/view?usp=sharing

**Comment by appgurueu** [comment] 2024-10-13 17:07
Possible duplicate of #9625, see also #14068

**Closed** 2024-10-13 17:08 UTC
Labels: Duplicate
