### ISSUE TITLE
Sneaking while jumping in 2 blocks high room will make player float

### ISSUE THREAD

**Issue by debagos** [minetest/minetest#15482] opened 2024-11-26 22:02 UTC
### Luanti version

```true
Luanti 5.11.0-dev-8c56434 (Linux)
Using LuaJIT 2.1.1724512491
Built by GCC 14.2
Running on Linux/6.11.5 x86_64
BUILD_TYPE=Release
```

### Operating system and version

openSUSE Tumbleweed

### Summary

Holding the crouch and the jump keys at the same time while in a two blocks high space will result in the player floating right underneath the ceiling until any key is released.

### Steps to reproduce

Place a block right above your head and hold jump and crouch at the same time.

**Comment by appgurueu** [comment] 2024-11-27 00:14
I can reproduce. Likely a regression caused by #14332.

**Comment by debagos** [comment] 2024-11-27 00:51
I tested https://github.com/minetest/minetest/commit/df8a600b228c93e0a2ab1ef40dfa250b0c994718 and https://github.com/minetest/minetest/commit/567f85752de80d89559ca6dcedf58d684dc71710 but both versions have this behavior, means it must have been introduced earlier than that.

**Comment by debagos** [comment] 2024-11-27 01:14
Tested releases starting from `5.0.0` and the first release that shows this behavior is `5.3.0`.
Then also tested `5.4.1`, `5.5.0`, `5.6.1` and `5.8.0` and they all show the "wrong" behavior.
So it seems that it got introduced between release `5.2.0` and `5.3.0`.

**Comment by LoneWolfHT** [comment] 2024-11-27 05:33
Is sneak_glitch or new_move set?

**Comment by debagos** [comment] 2024-11-27 12:38
> Is sneak_glitch or new_move set?

I used default configs and the bundled _devtest_ game in all my tests.
Which means in current dev and latest release `sneak_glitch = false` and `new_move = true` in my tests.
Now I tested all combinations of these two settings on the latest dev and also 5.10.0 release and it doesn't have any effect on the mentioned behavior.

**Comment by nininik0** [comment] 2024-11-27 16:28
I suggest adding 3d_armor_flyswim it has a similar bug, exept when you crouch and fall, if you die you mysteriously get sent upwards.

**Comment by v-rob** [comment] 2024-12-17 20:23
Duplicate of #12640

**Closed by v-rob** 2024-12-17 20:23 UTC
Labels: Bug, Low priority, @ Client / Controls / Input, Regression
