### ISSUE TITLE
Blocks at Resolving address...

### ISSUE THREAD

**Issue by bugbuka** [minetest/minetest#12172] opened 2022-04-04 11:57 UTC
##### Minetest version

```
5.5.0
```

##### OS / Hardware

Operating system: macOS Monterey
CPU: intel

GPU model: AMD 5300

##### Summary

<img width="925" alt="Screen Shot 2022-04-04 at 20 00 17" src="https://user-images.githubusercontent.com/4723950/161539384-33e09566-3039-4d05-b8de-ce8429d7e0ed.png">

**Comment by sfan5** [comment] 2022-04-04 16:00
Can you retest with `--verbose --trace` and post the log here?
Do you know if applications need special permissions for network access on macOS?

**Comment by bugbuka** [comment] 2022-04-05 02:16
[verbose.log](https://github.com/minetest/minetest/files/8414350/verbose.log)

here is the verbose log.
i do not know any special permissions for network access on monterey.

**Comment by SmallJoker** [comment] 2022-04-05 17:18
At L3920, "singleplayer" is recognized with the newest protocol version.

1. TOSERVER_INIT is received by the server
2. TOCLIENT_HELLO is sent by the server (length 0x25, reliable)
3. Client: TOCLIENT_HELLO is processed in `ConnectionReceiveThread::receive` (`ProcessPacket from peer_id: 1`)
   * strips BASE_HEADER_SIZE (7)
   * `ConnectionReceiveThread::processPacket` finds PACKET_TYPE_RELIABLE
   * strips RELIABLE_HEADER_SIZE (3)
   * `ConnectionReceiveThread::processPacket` finds PACKET_TYPE_ORIGINAL
   * strips ORIGINAL_HEADER_SIZE (1)
   * Resulting bytes: 0x25 (OK)
4. Client:  The event *should* be put into the queue and later processed by `Receive`
5. Client:  `Receive: got event: CONNEVENT_DATA_RECEIVED` (in `Connection::Receive`) never appears.

`TOCLIENT_HELLO` seems to be eaten somewhere, but I cannot figure out why.

**Comment by bugbuka** [comment] 2022-04-06 11:32
![wait_time_ms](https://user-images.githubusercontent.com/4723950/161964990-99316b74-b709-430b-a761-0308d1451471.png)
[semaphore.txt](https://github.com/minetest/minetest/files/8426440/semaphore.txt)
after applying above change, , it does not work. result in the same error.

it seems like some kind of dead lock.

**Comment by bugbuka** [comment] 2022-04-14 07:17
any feedback? this issue blocks me.

**Comment by SmallJoker** [comment] 2022-04-14 11:30
I kinda hoped that someone with some more knowledge about MacOS would jump in - which did not happen.

If this is really a deadlock, please run Minetest in gdb and Ctrl+C (break) once the game is stuck.
```
$ gdb minetest
r         -- literal to start the process
^C        -- Ctrl+C user input
bt full   -- print full backtrace
```
Optimally, there's one backtrace which points to a lock await.

**Comment by bugbuka** [comment] 2022-04-14 13:51
MacBook-Pro:minetest tom$ gdb ./build/macos/minetest.app/Contents/MacOS/minetest
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin21.1.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./build/macos/minetest.app/Contents/MacOS/minetest...
(gdb) r
Starting program: /Users/tom/game/minetest-root/minetest/build/macos/minetest.app/Contents/MacOS/minetest
Unable to find Mach task port for process-id 84140: (os/kern) failure (0x5).
 (please check gdb is codesigned - see taskgated(8))
(gdb)

**Comment by SmallJoker** [comment] 2022-04-22 17:41
@bugbuka Sorry for the delay. I do not know why `gdb` does not work there but I had yet another idea: Might the packets be discarded silently, but for the wrong reason?

https://github.com/minetest/minetest/blob/4558793caf48d63c74574ba740a96c92d0afcc2c/src/network/connectionthreads.cpp#L999-L1000

Which log output do you get if you insert `errorstream << e.what() << std::endl;` into this `catch` block?

**Comment by bugbuka** [comment] 2022-05-02 11:28
run ./build/macos/minetest.app/Contents/MacOS/minetest

2022-05-02 19:25:06: [Main]: Automatically selecting world at [/Users/tom/Library/Application Support/minetest/worlds/w1]
2022-05-02 19:25:11: WARNING[Main]: \!/ Mod security should never be disabled, as it allows any mod to access the host machine.Mods should use minetest.request_insecure_environment() instead \!/
         __.               __.                 __.  
  _____ |__| ____   _____ /  |_  _____  _____ /  |_ 
 /     \|  |/    \ /  __ \    _\/  __ \/   __>    _\
|  Y Y  \  |   |  \   ___/|  | |   ___/\___  \|  |  
|__|_|  /  |___|  /\______>  |  \______>_____/|  |  
      \/ \/     \/         \/                  \/   
2022-05-02 19:25:12: ACTION[Main]: World at [/Users/tom/Library/Application Support/minetest/worlds/w1]
2022-05-02 19:25:12: ACTION[Main]: Server for gameid="minetest" listening on 0.0.0.0:57221.
2022-05-02 19:25:12: ERROR[ConnectionReceive]: Got a SET_PEER_ID
2022-05-02 19:25:12: ERROR[ConnectionReceive]: Got a SET_PEER_IDGot an ACK
2022-05-02 19:25:12: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:25:17: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:17: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:25:17: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:17: ERROR[ConnectionReceive]: Got a PINGGot an ACK
2022-05-02 19:25:22: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:22: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:25:22: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:22: ERROR[ConnectionReceive]: Got a PINGGot an ACK
2022-05-02 19:25:27: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:27: ERROR[ConnectionReceive]: Got a PINGGot an ACK
2022-05-02 19:25:27: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:27: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:25:32: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:32: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:25:32: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:32: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:25:37: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:37: ERROR[ConnectionReceive]: Got a PINGGot an ACK
2022-05-02 19:25:37: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:37: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:25:42: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:42: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:25:42: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:42: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:25:47: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:47: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:25:47: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:47: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:25:52: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:52: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:25:52: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:52: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:25:57: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:57: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:25:57: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:25:57: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:26:02: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:26:02: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:26:02: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:26:02: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:26:07: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:26:07: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:26:07: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:26:07: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:26:12: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:26:12: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:26:12: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:26:12: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:26:17: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:26:17: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:26:17: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:26:17: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:26:22: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:26:22: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:26:22: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:26:22: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:26:27: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:26:27: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:26:27: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:26:27: ERROR[ConnectionReceive]: Got an ACK
^C2022-05-02 19:26:29: [Main]: INFO: signal_handler(): Ctrl-C pressed, shutting down.
^C2022-05-02 19:26:31: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:26:32: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:26:32: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 19:26:32: ERROR[ConnectionReceive]: Got a PING
2022-05-02 19:26:32: ERROR[ConnectionReceive]: Got an ACK

**Comment by SmallJoker** [comment] 2022-05-02 18:42
That looks correct. My output looks as follows:
```
2022-05-02 20:39:19: ERROR[ConnectionReceive]: Got a SET_PEER_ID
2022-05-02 20:39:19: ERROR[ConnectionReceive]: Got a SET_PEER_IDGot an ACK                                                                                         
2022-05-02 20:39:19: ERROR[ConnectionReceive]: Got an ACK                                                                                                          
Unified Inventory. Inventory size: 409
2022-05-02 20:39:19: ERROR[ConnectionReceive]: Got an ACK
2022-05-02 20:39:19: ERROR[ConnectionReceive]: Got an ACK                                                                                                          
2022-05-02 20:39:19: ERROR[ConnectionReceive]: Got an ACK                                                                                                          
2022-05-02 20:39:19: ERROR[ConnectionReceive]: Got an ACK                                                                                                          
2022-05-02 20:39:19: ERROR[ConnectionReceive]: Got an ACK                                                                                                          
2022-05-02 20:39:19: ERROR[ConnectionReceive]: Got an ACK                                                                                                          
2022-05-02 20:39:19: ERROR[ConnectionReceive]: Buffered a split packet chunk                                                                                       
2022-05-02 20:39:19: ERROR[ConnectionReceive]: Buffered a split packet chunkGot an ACK                                                                             
2022-05-02 20:39:19: ERROR[ConnectionReceive]: Buffered a split packet chunk  
```
PING appears after approx. 4 seconds similar to your case.

To make sure: do you have any additional mods enabled? If so, does disabling them make a difference?

**Comment by bugbuka** [comment] 2022-05-03 03:06
no, have no additional mods.

https://user-images.githubusercontent.com/4723950/166400175-5506a2f5-7075-45e7-8dfc-20f5d544146f.mov

**Comment by bugbuka** [comment] 2022-05-03 03:27
it is wield, it can work now. i do not know what changes make this work.

**Comment by bugbuka** [comment] 2022-05-03 03:45
i re-compile all the source code, then run minetest with 
./build/macos/minetest.app/Contents/MacOS/minetest
it blocks.

exit the game with ctrl + c, re-run the app, the blocks gone.

**Comment by tmarcinkevicius** [comment] 2022-05-27 12:18
Hey, 

Is minetest 5.5.1 brew package still has this issue? 
I tried it today. Freezes on “Resolving address..."

**Comment by paradust7** [comment] 2022-06-05 23:57
Confirmed this is still a problem, and determined the reason.

The offending code is here:

https://github.com/minetest/minetest/blob/381f84ee2788eb462999701e902bd22271cfcb2e/src/defaultsettings.cpp#L457-L460

This is incompatible with the way fps_max is used, as a divisor:

https://github.com/minetest/minetest/blob/381f84ee2788eb462999701e902bd22271cfcb2e/src/client/game.cpp#L4081-L4084

This is undefined behavior, causing frametime_min to overflow, so that the first sleep_ms() below blocks forever.

**Comment by paradust7** [comment] 2022-06-06 00:10
After fixing this, there's a new bug with the mouse movement. I'll work on fixing that too, and then getting it fixed on brew.

**Closed** 2022-06-06 10:03 UTC
Labels: Bug, @ Build, macOS
