### ISSUE TITLE
FPS on Android works great, but linux, not so great

### ISSUE THREAD

**Issue by VenomousSteam81** [minetest/minetest#12633] opened 2022-08-02 03:58 UTC
##### Minetest version
```
Minetest 5.5.1 (Linux)
Using Irrlicht 1.9.0mt5
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/app/share/minetest"
STATIC_LOCALEDIR="/app/share/locale"
```

##### OS / Hardware
Operating system: ChromeOS
CPU: MediaTek mt8173 (4 threads, 1.70GHz)

GPU model:
OpenGL version:

##### Summary
I installed the Android app, which runs very well, but has one downside; it lacks full mouse support. I then installed the flatpak version on Linux, and it is tearing, and has bad lag
##### Steps to reproduce
**N/A**

**Comment by Zughy** [comment] 2022-08-02 11:30
Hello, can you please provide info about your GPU and OpenGL version as well? Can't really tell without such info

**Comment by VenomousSteam81** [comment] 2022-08-02 16:36
Now it won't run. I'm getting this error:
```
venom@penguin:~$ flatpak run net.minetest.Minetest
2022-08-02 11:35:51: [Main]: Automatically selecting world at [/home/venom/.minetest/worlds/test]
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  0 ()
  Serial number of failed request:  727
  Current serial number in output stream:  727
  ```

**Comment by SmallJoker** [comment] 2022-08-02 16:52
Duplicate of #12467 and #12518

Please try a newer Minetest development (-dev) build.

**Closed by SmallJoker** 2022-08-02 16:52 UTC
Labels: Unconfirmed bug, Performance, Linux, Action / change needed

**Comment by VenomousSteam81** [comment] 2022-08-02 17:05
Ok, thank you.
