### ISSUE TITLE
Black screen and then crash on Android

### ISSUE THREAD

**Issue by aouelete** [minetest/minetest#3583] opened 2016-01-18 00:14 UTC
I installed Minetest v0.4.13 from FDroid on my Samsung Galaxy S3 and when I try to run it, the screen turns black and the phone freezes and eventually reboots.
Is this a problem specific to the FDroid version (since I have seen screenshots of Minetest running on Android)?

**Comment by est31** [comment] 2016-01-18 00:34
Nope, there are no actual differences between play store build and f-droid build.

Can you provide a logcat?

And in the sdcard folder, there should be a directory called "minetest". It might be that you have installed one of minetest's unofficial forks, eg via playstore, which save to the same folder, and this causes a conflict. Can you rename/remove that directory?

**Comment by aouelete** [comment] 2016-01-18 17:42
Ok, here's some more information:

As soon as I launch the app, the screen turns black and stays that way for about a minute and a half, until the phone reboots (tested multiple times, both fdroid and playstore).
Logcat: [minetest.log.txt](https://github.com/minetest/minetest/files/94775/minetest.log.txt)
Also, my phone is still stuck on Android 4.1.2 (could that have anything to do with it?) and is rooted (probably does not matter).

I did not see any directories called minetest.

**Comment by est31** [comment] 2016-01-18 19:12
```
java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1891]: 29610 could not load needed library 'libiconv.so' for 'libminetest.so' (load_library[1093]: Library 'libiconv.so' not found)
	at java.lang.Runtime.loadLibrary(Runtime.java:370)
	at java.lang.System.loadLibrary(System.java:535)
	at net.minetest.minetest.MtNativeActivity.<clinit>(MtNativeActivity.java:94)
	... 15 more
```
Seems this is a dupe of #3291 , which is fixed in current master.

**Closed by est31** 2016-01-18 19:12 UTC
Labels: Android

**Comment by aouelete** [comment] 2016-01-19 00:48
Ok. I'm guessing there's no way to get the latest version until a new release comes out?

**Comment by est31** [comment] 2016-01-19 21:26
Either [build it yourself](http://dev.minetest.net/Android), or get apks from:

* @nerzhul 's official nightly builds page: https://jenkins.unix-experience.fr/job/minetest-android-OfficialRepository-RollingRelease/
* Or from the forums, build section, read the threads for more info: https://forum.minetest.net/viewforum.php?f=42
