### ISSUE TITLE
Drawtypes have side effects

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10735] opened 2020-12-21 12:54 UTC
## Problem

Drawtypes are not purely visual as they should be, some having undesirable, not toggleable side effects (see "Additional context").

## Solutions

Make drawtypes proper drawtypes, that is, solely affecting the visuals based on node def, neighborhood, param1 & 2. Allow enabling the side effects but don't force them, and don't make them drawtype-dependant.

## Alternatives

Rename the field to something like "nodetype" which would be less misleading.

## Additional context

* `drawtype = "flowingliquid"` can not be used without registering a liquid, which is handled by Minetest's liquid propagation algorithms, which only support infinite liquids, making it impossible to register proper finite liquids (except if using `drawtype = "leveled" which results in undesirably ugly liquids)
* `drawtype = "plantlike"` allows falling nodes to convert the "plant" to a dropped item. IIRC there was an issue for the plantlike side effects.

**Comment by Wuzzy2** [comment] 2020-12-21 17:45
I can confirm the part about `flowingliquid`.

But I can not confirm the part about `plantlike`. Do you have evidence that the dropped item is actually caused by the drawtype being `plantlike`? Because as far I know, what causes nodes to drop as item is when they are `buildable_to=true` and `walkable=false`, and that `plantlike` has nothig to do with it.

**Comment by Wuzzy2** [comment] 2020-12-21 18:15
Relevant code in `src/nodedef.cpp`:

```
	case NDT_LIQUID:
		assert(liquid_type == LIQUID_SOURCE);
		if (tsettings.opaque_water)
			alpha = 255;
		solidness = 1;
		is_liquid = true;
		break;
	case NDT_FLOWINGLIQUID:
		assert(liquid_type == LIQUID_FLOWING);
		solidness = 0;
		if (tsettings.opaque_water)
			alpha = 255;
		is_liquid = true;
		break;
```

So yeah, it's not only `flowingliquid` but also `liquid`. The engine currently forces you to only use those drawtypes for actual liquid nodes. I agree it would be better to make those drawtypes "pure" and completely independent from  `liquid_type`.

**Comment by Wuzzy2** [comment] 2021-01-10 21:02
@appgurueu and others: Can u plz review #10737?

**Comment by Wuzzy2** [comment] 2021-06-22 10:14
#10737 has been merged. `liquid` and `flowingliquid`  are now "pure" drawtypes and can be used without the node being an actual physical liquid.

But I don't understand this:

> drawtype = "plantlike" allows falling nodes to convert the "plant" to a dropped item.

What do you mean with that and how do I reproduce this?

**Closed** 2021-09-24 10:36 UTC
Labels: Request / Suggestion, Possible close
