### ISSUE TITLE
A fatal error occured

### ISSUE THREAD

**Issue by MidnightPhantom** [minetest/minetest#12543] opened 2022-07-15 12:57 UTC
Man when I used the following mods
MTG mods, mpd, morelights, morelights_dim, nextgen_bedrock and edit mods this happened
2022-07-14 14:31:32: ERROR[Main]: A serialization error occurred:
2022-07-14 14:31:32: ERROR[Main]: ServerEnvironment::loadMeta(): EnvArgsEnd not found!
2022-07-14 14:31:32: ERROR[Main]: The server is probably running a different version of Minetest.
2022-07-14 14:31:32: ACTION[Main]: Server: Shutting down
2022-07-14 14:31:32: ERROR[Main]: In thread 1:
2022-07-14 14:31:32: ERROR[Main]: /home/stefan/mt-build/build/minetest_64/minetest/src/serverenvironment.cpp:e9: createIntroductionTimesString: A fatal error occurred: attempted to query on non fully set up LBMManager
The world was made in 5.5.1 and was also running on the same version. 

If this is not the correct place to report this bug please tell me where to report.

**Comment by rubenwardy** [comment] 2022-07-15 13:06
Thanks for the report. This happens when env_meta.txt in the world folder is corrupted (perhaps you cut the computer power recently?).

You can either restore the file from backup or delete it

Duplicate of #9425

**Closed** 2022-07-15 13:07 UTC
