### ISSUE TITLE
Android - Black Screen

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2724] opened 2015-05-27 03:31 UTC
While a world is loading, switching off the display until the lockscreen shows and then unlocking the phone will lead to a black screen instead of the loading bar. When the next stage of loading is reached, the regular animation is shown. Tested on official version on Google Play and one of Wayward_One's recent builds.

**Comment by MoNTE48** [comment] 2015-05-27 13:01
Confirm

**Comment by Wayward1** [comment] 2015-05-27 15:23
I can confirm as well

**Comment by est31** [comment] 2015-06-01 21:31
dupe of #2409, minetest isn't rendered while loading, inside certain "loading steps"

**Closed by est31** 2015-06-01 21:31 UTC
Labels: Android, bug

**Comment by MoNTE48** [comment] 2015-08-24 09:15
Fix https://github.com/minetest/minetest/pull/2999
