### ISSUE TITLE
Cannot L/R click with latest dev

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#15559] opened 2024-12-15 09:27 UTC
### Luanti version

```true
Luanti 5.11.0-dev (202412141820)
```

### Irrlicht device

Wayland

### Operating system and version

Ubuntu 25.04

### CPU model

AMD Ryzen 7 7840HS

### GPU model

AMD Radeon 780M

### Active renderer

OpenGL 4.6

### Summary

Cannot punch or right-click in-game anymore, that includes right-clicking to place blocks or spawn mobs and punching to dig or pick up items.

### Steps to reproduce

Create new world, try to place something or spawn something.

**Comment by sfan5** [comment] 2024-12-15 10:55
duplicate of already fixed #15557

**Closed by sfan5** 2024-12-15 10:55 UTC
Labels: Unconfirmed bug
