### ISSUE TITLE
Server crash when entities fly out of world range(?)

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#4097] opened 2016-05-06 18:19 UTC
2 users reported a server crash when attempting to serialize an entity that has moved out of the world range:

https://github.com/minetest/minetest_game/issues/1073#issuecomment-217494116

```
minetest: /build/minetest-8aSVRa/minetest-201605031017/src/util/serialize.h:278: void writeF1000(irr::u8*, irr::f32): Assertion `i >= ((float)(s32)((-0x7FFFFFFF - 1) / 1000.0f)) && i <= ((float)(s32)((0x7FFFFFFF) / 1000.0f))' failed.
Abgebrochen (Speicherabzug geschrieben)
```

```
2016-05-05 09:29:46: ERROR[Main]: ServerError: Lua: Runtime error from mod 'falling_extras' in callback luaentity_Step(): Node name is not set or is not a string!
2016-05-05 09:29:46: ERROR[Main]: stack traceback:
2016-05-05 09:29:46: ERROR[Main]:   [C]: in function 'add_node'
2016-05-05 09:29:46: ERROR[Main]:   /home/erno/.minetest/mods/hmods/falling_extras/init.lua:155: in function </home/erno/.minetest/mods/hmods/falling_extras/init.lua:89>
AL lib: FreeContext: (0x22de5c0) Deleting 8 Source(s)
minetest: /build/minetest-3RL0_P/minetest-201605041647/src/util/serialize.h:278: void writeF1000(irr::u8*, irr::f32): Assertion `i >= ((float)(s32)((-0x7FFFFFFF - 1) / 1000.0f)) && i <= ((float)(s32)((0x7FFFFFFF) / 1000.0f))' failed.
Abgebrochen
```

Note, this is somehow readily exposed by TNT, since it "ejects" entities in large amounts. How it's possible that entities are flung 32km is yet beyond me - since TNT limits velocity of ejecta to 250m/s, which makes it unlikely that they will ever fly that far. I currenly assume that there is a divide by (almost) zero condition and items slip past the 250m/s limit somehow.

Irregardless, while it may appear that the bug in TNT would be the problem, It is obvious that it shouldn't crash the serialization code and the server:

-> it's entirely valid to mine down to -31000 and drop items into the "void"
-> the items should just "disappear" - get deleted

**Comment by sofar** [comment] 2016-05-06 18:23
FTR if an item shoots up at 250m/2 it will go up a maximum of 3125m. It will at most go 6250m sideways at 45 degree angle.

**Comment by sofar** [comment] 2016-05-07 01:51
I can't actually reproduce this at world edge. :/

**Comment by tenplus1** [comment] 2016-05-07 10:25
Try spawning an object out of range, like 40000,0,0

**Comment by est31** [comment] 2016-05-07 15:36
There are two different things here:

1. Spawning entities/players out of range like @tenplus1 outlined. Commit f61f817b9c170942a5b3ce3591125c2191645cd0 added this. The behaviour here is perfectly fine, but mods need to verify user input e.g. for teleportation to be inside those limits.

2. Floats being sent outside of f1000 valid ranges. This causes the crash @sofar mentioned and was added in commit 42cf5e972d1e27a92048712bc79806e1a088b96c . This has been added in order to at least crash and not cause undefined and weird behaviour.

The range for 1. is the world generation limit. The range for 2. is much larger: its `0x7FFFFFFF / 1000.0 = 2 147 483 647 / 1000`, which is `2 147 483`.

The assertion added by 2. is only checked in debug builds, release builds still have the old behaviour of buggy and weird but non crashing behaviour. It is intented to have the engine make sure that all f1000 s that are sent to be inside the limits that the assertion checks for. You are encouraged to find specific causes for what causes the values exceed these limits, and to send patches to fix it. The crash has been added to help you finding those cases.

**Comment by paramat** [comment] 2016-05-07 18:30
Unconfirmed as is possibly a mod issue, should this be removed from engine milestones?

**Comment by sofar** [comment] 2016-05-07 19:04
I might look into circling back to the TNT entity spawning code and see if there is a gap there later before release.

**Comment by paramat** [comment] 2016-05-07 20:59
Re-added the game issue to milestones so removing it here.

**Comment by paramat** [comment] 2016-05-09 18:02
https://github.com/minetest/minetest_game/pull/1084 hopefully fixes this. It seemed to be a divide by zero error in vector:normalize().

**Comment by AntumDeluge** [comment] 2017-04-16 00:00
Not sure if this is the same issue, but I didn't want to open a new one in case it is. But I just updated my local server to 0.4.15 & had the same/similar message occur:

`minetest: /build/minetest-JrSZG2/minetest-0.4.15/src/util/serialize.h:278: void writeF1000(irr::u8*, irr::f32): Assertion `i >= F1000_MIN && i <= F1000_MAX' failed.`

I don't understand how the code works all that well, but what I gather from reading this post is that the crash occurs because an entity attempted to spawn outside the bounds of world? Likely this is from a mod that I have installed?

**Closed** 2018-05-16 14:13 UTC
Labels: Bug
