### ISSUE TITLE
minetest doesn't allow me to type all Hungarian characters into the chat

### ISSUE THREAD

**Issue by imre84** [minetest/minetest#9976] opened 2020-06-01 15:58 UTC
##### Minetest version
```
Minetest 5.2.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

OS: Ubuntu 19.10
CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz

##### Summary
Despite LANG=hu_HU.UTF-8 being exported I'm only able to write specific (but not all the) Hungarian accented characters

all the Hungarian accented characters are as follows:
```
$ echo -n "aáeéiíoóöőuúüű         AÁEÉIÍOÓÖŐUÚÜŰ"|hexdump -C
00000000  61 c3 a1 65 c3 a9 69 c3  ad 6f c3 b3 c3 b6 c5 91  |a..e..i..o......|
00000010  75 c3 ba c3 bc c5 b1 20  20 20 20 20 20 20 20 20  |u......         |
00000020  41 c3 81 45 c3 89 49 c3  8d 4f c3 93 c3 96 c5 90  |A..E..I..O......|
00000030  55 c3 9a c3 9c c5 b0                              |U......|
00000037
$ echo $LANG
hu_HU.UTF-8
```

**Comment by SmallJoker** [comment] 2020-06-01 16:01
Duplicate of #302, one of the oldest open issues.

**Closed by SmallJoker** 2020-06-01 16:01 UTC
Labels: Unconfirmed bug
