### ISSUE TITLE
Option to treat nodes as submerged in a certain liquid

### ISSUE THREAD

**Issue by rdococ** [minetest/minetest#9915] opened 2020-05-22 19:40 UTC
Certain things, such as underwater plants, need to coexist in the same block space as liquids like water. Unfortunately, Minetest does not support any features that would make this easy to do, so two workarounds have developed:

* The submerged node replaces the node that it would have grown on, and the blocks that it actually occupies are still just plain liquid nodes. This is the method used by MTG's kelp, but it's not very flexible. It only really works with plants that need to grow from a specific solid block, and variations between individual plants become very tricky to implement.
* The submerged nodes are given the same post color effect as the liquid they're meant to be submerged in, given ladder physics (which you can sort of swim in), and any other attributes of the liquid such as drowning. This is closer, but it may result in code being repeated, leads to inaccurate swimming physics, and the boundaries between the nodes and the water are still rendered.

Both of these have their advantages and drawbacks, but I propose a simple solution as the best of both worlds.

There would be a new property, `submerged_in`. If this property is set to the name of a liquid node, all instances of the node will be treated as if submerged in that liquid. Liquid boundaries will not be drawn (unless the node is next to air), the post effect color is applied, true swimming physics is applied and all other properties of the specified liquid are too.

This would work very simply for underwater plants and anything else that can only exist in one kind of water. For other kinds of nodes that might or might not be submerged in different liquids, it would be more difficult, but this feature would still improve it.

**Comment by sfan5** [comment] 2020-05-22 21:32
duplicate of #7836 which was closed in favor of #3074

**Closed by sfan5** 2020-05-22 21:32 UTC
Labels: Feature request
