### ISSUE TITLE
Browse online content doesn't recognize packages as installed when installed via git

### ISSUE THREAD

**Issue by randomMesh** [minetest/minetest#10713] opened 2020-12-09 08:39 UTC
##### Minetest version
```
Minetest 5.4.0-dev-6d7067fd3 (Linux)
```

##### Summary
If you install a package via git, Minetest does not recognize it's installed.

MineClone2 already installed (via git):
![2020-12-09-094127_1920x1080_scrot](https://user-images.githubusercontent.com/32773707/101606025-2f6e4200-3a03-11eb-8579-89f748ee6ca6.png)

Able to install it again:
![2020-12-09-094149_1920x1080_scrot](https://user-images.githubusercontent.com/32773707/101606034-32693280-3a03-11eb-9841-4668a00d7401.png)

##### Steps to reproduce
Install a game via git, for example MineClone2
```bash
cd games
git clone https://git.minetest.land/Wuzzy/MineClone2.git
```
Open Minetest, go to the "Browse online content" tab.
You can install MineClone 2 again as Minetest does not recognize it is installed already.

**Comment by SmallJoker** [comment] 2020-12-10 16:30
Duplicate of #8293

**Closed by SmallJoker** 2020-12-10 16:30 UTC
Labels: Unconfirmed bug
