### ISSUE TITLE
Save server

### ISSUE THREAD

**Issue by minecraftchest1** [minetest/minetest#11315] opened 2021-06-04 00:12 UTC
## Problem

When connecting to a server by adding it's IP manually, you have to add the connection info every time. 

## Solutions

Add an option to save a server, ir automatically save the server on join. 

## Alternatives

Advertise the server, but this means making a private server public. 

## Additional context

Android

**Comment by rubenwardy** [comment] 2021-06-04 00:14
What version on Android? This should already be the case

**Comment by minecraftchest1** [comment] 2021-06-04 00:43
The credits page shows 5.4.0![Screenshot_20210603-194316_Minetest.jpg](https://user-images.githubusercontent.com/42992675/120729138-01deee80-c4a4-11eb-9176-573daef31a3f.jpg)

**Comment by AntumDeluge** [comment] 2021-06-04 09:44
Duplicate of #11200. Has been fixed in 5.4.1. But we still don't have a 5.4.1 Android build.

**Comment by sfan5** [comment] 2021-06-04 09:59
Indeed, as mentioned this was already fixed in 5.4.1 but we don't have a build of that for Android yet (@rubenwardy :eyes:)

**Closed by sfan5** 2021-06-04 09:59 UTC
Labels: @ Mainmenu, Unconfirmed bug
