### ISSUE TITLE
Minetest For iOS

### ISSUE THREAD

**Issue by BlackBear847** [minetest/minetest#10151] opened 2020-07-03 21:55 UTC
The Problem Is There Is No Minetest For Fire Is or iOS

I Play A Lot Of Games And I Like The Idea of Minetest But You Can Only Get It On Android
I Think This Is Needed So That Minetest Can Be More Popular And So People Like Me Can Play 
It On A Larger Variety Of Mobile Devices (Amazon And Apple Devices)

                                                              Sincerely,
                                                                Gavin

P.S. My Friend Plays This Game And He Loves It

**Comment by rubenwardy** [comment] 2020-07-03 22:00
Minetest is already available for FireOS - you can download it through the F-Droid app store, a free and open source Android store

**Comment by BlackBear847** [comment] 2020-07-03 22:03
Could You Guys Submit the minetest.apk files directly to iOS and FireOS?

**Comment by BlackBear847** [comment] 2020-07-03 22:05
BTW My Main Device is A Fire Tablet

**Comment by rubenwardy** [comment] 2020-07-03 22:07
For FireOS: No, I do not want to support an unnecessary app store. Just get F-Droid.

For iOS: there are legal issues that prevent us from making a port, and also the fact that none of the developers have a macbook

**Comment by BlackBear847** [comment] 2020-07-03 22:08
How To Get F-Droid?

**Comment by Zughy** [comment] 2020-07-03 22:28
https://f-droid.org/

**Comment by paramat** [comment] 2020-07-03 23:26
MT on iOS is not possible, and is a duplicate of #9154 

(I encourage you to avoid capital letters on all words, as it is irritating for many people.)

**Closed by paramat** 2020-07-03 23:26 UTC
Labels: Duplicate, Request / Suggestion

**Comment by iMonZ** [comment] 2021-03-15 09:29
> For FireOS: No, I do not want to support an unnecessary app store. Just get F-Droid.
> 
> For iOS: there are legal issues that prevent us from making a port, and also the fact that none of the developers have a macbook

You Don't need to have an MacBook for Development (OpenCore)
And there are Unofficial app stores too
