### ISSUE TITLE
Mip mapping uses an incorrect downscaling algorithm

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6867] opened 2018-01-01 17:48 UTC
missing gamma correction: http://www.ericbrasseur.org/gamma.html?i=1
on mipmaps: https://paroj.github.io/gltut/Texturing/Tut16%20Mipmaps%20and%20Linearity.html
I noticed that mipmapping ignores gamma when downscaling, you can test it by using the gamma dalai lama as some texture:
![screenshot_20180101_183548](https://user-images.githubusercontent.com/3192173/34469591-f281467c-ef22-11e7-880c-a09c97ac3b95.png)
Note that you likely need to watch the image in 1:1 size because browsers also use incorrect downscaling.

Here's another example where you can see the impact: A black white chess board pattern looks (and is) brighter than the texture downscaled by the mipmapping algorithm:
![screenshot_20180101_184206](https://user-images.githubusercontent.com/3192173/34469654-1fd7aa98-ef24-11e7-8d79-921be5454340.png)
Please take care to view this screenshot in 1:1, too.

**Comment by numberZero** [comment] 2018-01-04 22:37
Correctly, gamma should be applied after rendering (or as last operation in fragment shader). But currently it is effectively applied on meshgen, that is, on a per-vertex basis.

**Comment by SmallJoker** [comment] 2018-03-08 18:22
@HybridDog How is this issue different to #6846? Both are reporting the suboptimal mipmap downscaling algorithm.

**Comment by HybridDog** [comment] 2018-03-08 19:16
This issue is about missing gamma correction and the other one is about the alpha channel problem

**Comment by paramat** [comment] 2018-07-14 14:29
Duplicate of #6846

**Closed by paramat** 2018-07-14 14:29 UTC
Labels: @ Client / Audiovisuals

**Comment by HybridDog** [comment] 2023-12-21 16:24
> Duplicate of #6846

No, this issue is about missing gamma correction and it is still not fixed.
