### ISSUE TITLE
Frame stutter seems worse since 2-3 months ago

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#10683] opened 2020-12-01 15:54 UTC
##### Minetest version
5.4.0-dev commit 3176daee7 (latest commit at time of issue opening).

##### OS / Hardware
Operating system: Linux Ubuntu 18.04.5 LTS
CPU: Intel® Core™ i5-4670T CPU @ 2.30GHz × 4 
GPU model: Intel® HD Graphics 4600 (HSW GT2) (integrated GPU, no graphics card)

##### Details

Frame stutter with default settings seems worse since 2-3 months ago, but i am not entirely certain it is worse and have not rigorously tested. Maybe it has always been this bad, but, it is unbearable for me with current default settings.
Perhaps others might notice this too.

Over the last 2-3 months there have been many changes to default settings, making them more intensive, this might be related and might be entirely or partially the cause.

I suspect this stutter is meshgen related because this stutter is the stutter i remember from a few years ago that was greatly improved by celeron55's meshgen-related PR #5595

##### How to reproduce

Use MTG, start a new world, leave view range at default 190, fly fast over terrain at the default 20n/s speed.
Terrain moves in a stuttering way.
Stutter is particularly bad when panning the camera while flying fast, i assume this is due to suddenly bringing a large number of new mapblocks into view and so creating a large number of new meshes.

The previous version of this comment is below:
///////////////////////////////////////////////////////////////////////////
~Details
I have suddenly noticed this after updating to the latest commit, my settings and configuration has not changed (although some defaults have been changed by commits, see below).
Rendering has bad and visually uncomfortable frame stutters.
FPS seems slightly lower, even in low-load situations (MTG in non-forest biomes), it often drops down to 50 where previously it was always nearer 60.
dtime jitter often rises to 200%-350%.
The commit i was previously on was from 2-3 weeks ago, possibly around November 15th
Suspect PRs / commits:
#10660 
2f6393f49d5ebf21abfaa7bff876b8c0cf4ca191
be8d1d2d99ad835b5de7277b7b518c334113e795
I will try reverting some of these setting defaults changes locally to see if they help.
@lhofhansl 
The reason i suspect mesh generation is because the only other time i have experienced stutter this bad was many years ago. I seem to remember it was fixed by celeron55 in a commit related to mesh generation, probably #5595 which set the value of a setting that has been recently changed in the suspect commit 2f6393f49d5ebf21abfaa7bff876b8c0cf4ca191 . I will try reverting that setting change locally.
How to reproduce
Keep view range at the new default of 190.
Fly continuously in a straight line over terrain, the movement of terrain noticeably stutters.~

**Comment by hecktest** [comment] 2020-12-01 17:04
Any difference between singleplayer and pure client?

**Comment by paramat** [comment] 2020-12-01 17:16
My suspicion above was correct.
I reverted the change to meshgen_block_cache_size in https://github.com/minetest/minetest/commit/2f6393f49d5ebf21abfaa7bff876b8c0cf4ca191
I added this line to minetest.conf:
`meshgen_block_cache_size = 20`
Stutter is much improved, back to how it was before, dtime jitter now stays below 150%, FPS is slightly higher.

I vaguely remember the discussions we had with celeron55 while choosing the setting default value, i seem to remember it is quite sensitive and 20 was chosen to be optimum.
Unless i misunderstand something i request a revert of this setting change @lhofhansl 
Maybe it is related to having a graphics card or not, i do not and very many MT users do not. The stutter is so bad i think the setting should be set to be bearable for those without graphics cards. As it is currently MT is visually unbearable.

**Comment by hecktest** [comment] 2020-12-01 20:03
I don't understand though, shouldn't meshing be cheaper if you do _not_ have a GPU, because you don't need to cross the PCI-e bus with the result? And shouldn't a bigger cache reduce stutter, according to the comment right above? This setting might be poorly understood.

**Comment by lhofhansl** [comment] 2020-12-03 03:34
Wait the stutter improves when you make meshgen_block_cache_size **smaller**?! That does not make any sense.

**Comment by lhofhansl** [comment] 2020-12-03 03:52
@paramat `meshgen_block_cache_size` is the only setting you reverted back?

**Comment by sfan5** [comment] 2020-12-03 14:38
I wonder if this is related to / the same issue I noticed here: https://irc.minetest.net/minetest-dev/2020-11-26#i_5755760

> I don't understand though, shouldn't meshing be cheaper if you do not have a GPU, because you don't need to cross the PCI-e bus with the result?

To my knowledge interacting with the Intel's integrated GPUs still crosses the PCI bus.

(And to be precise, if you really _didn't_ have a graphics card you would not have any video output.)

**Comment by sfan5** [comment] 2020-12-03 14:49
Okay after testing messing with `meshgen_block_cache_size` does not fix my issue from IRC, perhaps it makes the stutter less severe(?).

To this issue:

I can't reproduce it on my system (dedicated gpu: NVIDIA GTX 1050 Ti), there is no difference between `meshgen_block_cache_size` 20 or 40. There's some subtle stutter once in a while but I don't know if that's it.
Though if the change really kills performance on Intel GPUs it's clear it needs to be reverted.

**Comment by hecktest** [comment] 2020-12-04 05:10
What I meant was that there's no VRAM to copy the VBOs to. But oh no, the driver is probably making a private copy of the buffer. That might be slower than walking the bus.

**Comment by paramat** [comment] 2020-12-04 19:06
> Wait, the stutter improves when you make meshgen_block_cache_size smaller?! That does not make any sense.

Oops, i misunderstood how it worked. It makes sense a larger cache would reduce stutter, just as the setting comment states.
So i am no longer sure that change was the cause of the stutter, maybe i was misled by a coincidence and the cause is elsewhere. I need to investigate more carefully.
> Edit: Also remember we increased the default viewing_range and active_block_range.

I have used view range 190 for a long time, so must be something else.
> @paramat meshgen_block_cache_size is the only setting you reverted back?

Yes. But perhaps i messed up somehow =)
> I can't reproduce it on my system (dedicated gpu: NVIDIA GTX 1050 Ti), there is no difference between meshgen_block_cache_size 20 or 40.

Thanks, i need to check everything again.

So, i no longer request a revert of that setting, i will update after more careful testing.

**Comment by lhofhansl** [comment] 2020-12-04 20:00
A larger `active_block_range` would lead to server side "stutter", i.e. server dTime delays. But it does not explain client stuttering.

Perhaps the client block cache causes stuttering...? As part of the viewing_range increase, I also increased that from 5000 to 7500 blocks. So if you fly around and load 7500 within 10 minutes (that's the client expiration time of that cache) that maintenance overhead could increase. It's a far shot and I doubt that's a problem, but it's something to check at least.

It's also possible that the larger overhead of the mesh cache (not the block cache) also causes issues on slower machines - although I doubt that here as well.

Did you try rolling back 2f6393f entirely? (There's queue size increase there as well)

**Comment by paramat** [comment] 2020-12-04 20:33
This is odd ...
Early on in retesting, but, i seem to have confirmed that reverting `meshgen_block_cache_size` back to 20 improves stutter and reduces jitter. I know this makes no sense and i can hardly believe it myself =)
Nothing else changed, identical testing situation (start new world, fly fast over terrain).

However, this may not be the only cause of the stutter, i need to try reverting some other settings.
Beginning to suspect the increased generate and send distances, my view range has always been 190, but now there are more blocks sent and rendered.
I am feeling unsure about those increases, i think i prefer them unchanged and default view range matching them at 160.
Also i apologise because i approved that PR but did not actually test it, but then it was also approved by nerzhul.
Anyway, i will try reverting those to see if they make a difference.

> A larger active_block_range would lead to server side "stutter"

It is not that, as i usually have that set to 1 in configuration, because i am usually doing mapgen work instead of playing and MTG ABMs are therefore a lot of unnecessary load.
> Did you try rolling back 2f6393f entirely?

Not yet.

**Comment by paramat** [comment] 2020-12-04 21:19
>  i seem to have confirmed that reverting meshgen_block_cache_size back to 20 improves stutter and reduces jitter.

Problem is the improvement is slight, so i keep wondering if i am imagining it.

However, reverting multiple recent setting increases by lhofhansl makes a significant improvement, so i suspect the cause might be the combined effect of all these increases.
Reverting client_mapblock_limit results in no improvement.
However, i am still testing.

What i am certain of is that within the last month of commits, stutter has got much worse and is now unbearable for me.
It concerns me because i have a reasonable machine that could perhaps be considered a rough medium of MT users.
Having settings set to high is far worse than too low, because the result of 'too high' is enough to make someone write off MT as unusable, whereas 'too low' settings have much less of a negative impact: everything runs smoothly but the distances are just not particularly high.
I have a feeling some settings have been pushed up too high recently, and this is partly my fault for approving that PR without testing.

The stutter is particularly bad when panning the camera while flying fast, i guess because the view frustrum defines what blocks are rendered and a sudden pan brings a large amount of new blocks into view.

**Comment by paramat** [comment] 2020-12-04 21:28
Testing notes so far:
```
On commit 3176dae

Suspect PRs/commits:

#10660 Improve sky rendering performance
2f6393f Increase limit for simultaneous blocks sent per client and the meshgen cache.
be8d1d2 Increase default emerge queue limits and limit enqueue requests for active blocks.
aa4d3cb Increase defaults for viewing_range, active_object_range and related settings

To reproduce:
New world, leave view range at default 190, fly fast over terrain.

Reverting max_block_generate_distance, max_block_send_distance, makes only a slight improvement.
Reverting meshgen_block_cache_size makes only a slight improvement.
Reverting client_mapblock_limit makes no improvement.

Reverting max_block_generate_distance, max_block_send_distance, meshgen_block_cache_size makes
a significant improvement.
```

**Comment by lhofhansl** [comment] 2020-12-05 02:50
> Reverting max_block_generate_distance, max_block_send_distance, meshgen_block_cache_size makes
a significant improvement.

Well, yeah, if you send viewer blocks to the client, the client will render viewer blocks, hence does less work. That should not really come as a surprise.
Without it though we cannot increase the default viewing_range to 190, though, you need 12 map blocks distance to cover 190 nodes. If we roll these back we need to roll back default viewing_range to 100 as well.

> Having settings set too high is far worse than too low

To high for what? Some old laptop from 2010? In which case I really do not care.

The intent of all of these changes was to make it better by default for half-way decent machines.
Let's _please_ not be stuck with MT forever supporting 10yo machines. It's bad and frustrating enough as is.
Nobody is changing or even knows about this, so people take one look at MT, determine is sucks badly, and then move on.
Seen this enough in videos, or badly setup servers.

Or perhaps we should have a set of settings for fast machine and one for slow.

**Comment by lhofhansl** [comment] 2020-12-05 03:08
Oops. Didn't mean to close.

**Comment by lhofhansl** [comment] 2020-12-05 03:31
Also this:
> Reverting max_block_generate_distance, max_block_send_distance, makes only a slight improvement.

Seems to be at odds with this:
> Reverting max_block_generate_distance, max_block_send_distance, meshgen_block_cache_size makes
a significant improvement.

Did you mean some other settings?

**Comment by Adnan1091** [comment] 2020-12-05 11:56
Wait,doesn't this was persist on Android the whole time? #9703

**Comment by paramat** [comment] 2020-12-05 15:49
> Without it we cannot increase the default viewing_range to 190, though, you need 12 map blocks distance to cover 190 nodes. If we roll these back we need to roll back default viewing_range to 100 as well.

It does not need to be 100 obvously. I suggested the matching view range of 160, which you stated you were ok with in the issue. I wrote above:
> I am feeling unsure about those increases, i possibly prefer them unchanged and default view range matching them at 160.

> To high for what? Some old laptop from 2010? In which case I really do not care.

If we are referring to a crappy 10 year old laptop i agree, but it is obvious from this issue i am referring to 'too high' for my fairly decent desktop.
I expect you care about MT being unbearably stuttery for perhaps 50% of users.
Besides, i was not referring to particular machines, i was discussing the approach to the optimum balance of default settings, with the emphasis on 'balance', i am not suggesting lowering settings for the crappiest of machines.
> The intent of all of these changes was to make it better by default for half-way decent machines.

That is what my machine is, and it seems possible the new settings are too high for that and make MT unbearable.
> Let's please not be stuck with MT forever supporting 10yo machines.

I am not suggesting that and you know that. All core devs support a continuous and moderate increase in default settings.
> so people take one look at MT, determine is sucks badly, and then move on.

Stutter becoming unbearable, which it is now with default settings, is far more likely to do this than the previous moderate settings that make everything run smoothly. This is also a very negative and extreme depiction.

**Comment by paramat** [comment] 2020-12-05 16:01
I am very unsure about this. All the time i have spent on this issue i have been tired and i have not rigorously tested.
My tests so far are unreliable so i have removed my testing notes.
Many things i wrote above i no longer support so i have 'struck-through' a lot of text.
I have also rewritten the first comment to make it up to date with my latest thoughts.
Currently i am not motivated to test this rigorously, so will leave this open as 'unconfirmed' for now.

**Comment by lhofhansl** [comment] 2020-12-05 17:11
This is hard to test, because it happens sometimes only.

I think it behooves us to identify the source of the jitter.
Obviously there's server-side and client-side jitter.

Server jitter manifest is many way, one of which is dtime jitter.

Client jitter manifests in frame-stutter, what you're seeing here. The main source of that used to be mesh generation, which was since moved to a separate thread, and the generated meshes are cached in the mesh-cache (which is why I wanted to increase that, but apparently that does not help).
We need to find the other reasons for stutter. The only work done on the main thread should be processing input and rendering the scene, everything else should happen on another thread.

There're also locking issues (both client and server), updating the the map or a block is done under a global lock(!)

**Comment by lhofhansl** [comment] 2020-12-05 17:39
The other part of my "frustration" is that you cannot just "increase[...] settings to [your] personal optimum" since you have to know how everything relates.

Increasing the viewing_range will just lead to a visibly jagged horizon. When I started with MT I had to look at the code to figure out, "oh, I need to actually increase `max_block_send_distance`", then still sometimes the horizon would not load... "oops, need to also `max_block_generate_distance`". Then entities just disappeared at a short range. So now `active_block_range` and `active_object_send_range_blocks`. Oh... And it's still not working... Oh these are blocks, not nodes, etc, etc.

Now I'm an engineer so I can easily figure it out. But if you look at it from a distance it's pretty ridiculous.

So some thoughts:

- At least single player could adjust.
- The server could advertise it's block send/generate distance, and the client could default to a matching viewing_range.
- `active_block_range` and `active_object_send_range_blocks` could be derive default from the send distance, etc.
- more...?

It's not "bad" that the viewing_range is by default, what's "bad" is that you need to CS degree to increase it :)

**Comment by lhofhansl** [comment] 2020-12-05 18:00
Sorry for the barrage...

I wonder if it's related to the camera_offset. The client actually goes through and updates every single blocks with the new location, on the main thread (I think) and so the more block there are in the cache the more blocks needs to be changed.

I think @hecktest had a solution for that.

**Comment by hecktest** [comment] 2020-12-05 18:57
Camera offset? It's much worse than that.

So here's a translateMesh function. This iterates on every vertex of a mesh and adds a delta vector to each position.
https://github.com/minetest/minetest/blob/07e0b527cf3e6e4f1bf36823940216efef59d8c9/src/client/mesh.cpp#L152
When a block is meshed, this O(n) translate is called to put it in its right spot. Model matrix? What's that?
https://github.com/minetest/minetest/blob/ed22260822086f84016aa8384c3174bfc6d1739d/src/client/mapblock_mesh.cpp#L1182
And because the mapblock is positioned in the offset space by this mechanism, every time the offset changes...
https://github.com/minetest/minetest/blob/ed22260822086f84016aa8384c3174bfc6d1739d/src/client/mapblock_mesh.cpp#L1311
Yikes.

**Comment by lhofhansl** [comment] 2020-12-05 19:12
Yes. Yikes. The reason for doing this are shader precision issues apparenyl. Not sure a (shader side) model matrix would fix the precision issues.

**Comment by lhofhansl** [comment] 2020-12-05 19:17
And if we do it via a model matrix, we need my change in #10688 (so that wave and plant displacement can still be done in world space).

**Comment by lhofhansl** [comment] 2020-12-05 19:40
I can confirm that disabling camera offset removes a big source of client stutter (and that stutter is expected to be proportional to the blocks in range (not the visible blocks).
I have a (very) simple change - until we find a better one - that only translates meshes for visible blocks, which reduces by stutter by about 50%. Not great, but not bad either. I'll post a PR.

**Comment by hecktest** [comment] 2020-12-05 19:41
There won't be any precision issues if you just apply the offset to the model matrix instead. That's what I did to fix it that one time, everything was fine at the map's edge. You'll sooner run into issues by repeatedly adding and subtracting round decimal numbers to floats.

**Comment by lhofhansl** [comment] 2020-12-05 19:46
Let's apply #10700 first (just created). Then we can get rid of the jazz the right way.

**Comment by hecktest** [comment] 2020-12-05 22:11
Please tell me if #10702 reduces the stutter.

**Comment by lhofhansl** [comment] 2020-12-06 01:44
It does. With far viewing_range (400++) I used to see up to 500%, with #10700 the worst was 250%, with #10702 the worst is less than 150% (which I presume has other causes).

**Comment by Oblomov** [comment] 2020-12-06 20:17
I don't know if this is relevant or not, but I have been experiencing similar issues to the ones reported by @paramat on 5.3. For no apparent reason, both on an iGP and on the dGP of a fairly recent, high-end laptop. What makes this extremely challenging to debug is the fact that it's not consistently reproducible: I may get a one or two plays without any issues, and then several where the game suddenly starts having “fits”, with the FPS dropping enormously, and the drawtime of the individual frame spiking to ridiculous values (I'm not joking: worst cases on the iGP have been as high as _seconds per frame_) —all while doing exactly the same things in exactly the same environment.

(This might be relevant or not in case someone wants to try to bisect the cause for the stutter: it may be older than anything done recently in -dev, and/or it might be independent from the MT engine itself and be related instead to recent changes in e.g. drivers.)

**Comment by lhofhansl** [comment] 2020-12-06 22:07
Thanks @Oblomov. There have been some fixed since 5.3. For example MT failed to clean out the HW buffers used on the graphics card, so over time FPS get lower and lower until the blocks expire from the client cache (10 minutes by default). That was fixed.

**Comment by hecktest** [comment] 2020-12-06 22:13
@Oblomov 
Those "fits" don't sound like meshing stutter, they sound like data unloads, and map saves (if singleplayer). _Seconds per frame_ in particular sounds like map saves. It might also be the recently implemented VBO pruning.

**Comment by hecktest** [comment] 2020-12-07 03:32
Okay, so I've definitely noticed the stutter "fits" too. It only happens after a while, and registers in the time spent non-rendering.
Could that be a client data unload? The default time interval for that is 10 minutes, and the intensity of the stutter may vary depending on how much there actually is to unload.

**Comment by lhofhansl** [comment] 2020-12-07 05:27
I doubt that causes issues on the client. The server can go away compressing blocks for a while, but not the client. Even in SinglePlayer mode these are different threads.

**Comment by hecktest** [comment] 2020-12-08 06:19
For what it's worth, I haven't been getting the lag with more frequent unloads. Are you sure that no part of them blocks the main thread, like locking some mapblocks for instance?

**Comment by lhofhansl** [comment] 2020-12-09 03:11
@paramat ? You have been conspicuously quiet on this. :)

**Comment by hecktest** [comment] 2020-12-10 00:58
Wow, look at this. This is happening on every client unload even with #10714 applied, on a flat map with time frozen, etc etc. Where are those remeshes coming from? (watch the whole thing)
![meshes](https://user-images.githubusercontent.com/42101236/101707085-cd591f80-3a8a-11eb-9971-f801424f56ce.gif)
And of course it goes away when client unloads are disabled.

**Comment by lhofhansl** [comment] 2020-12-11 04:11
Interesting... I assume these are the remeshes that cannot be done from from meshgen-cache alone - which is why I wanted to increase its size.

**Comment by lhofhansl** [comment] 2020-12-12 17:09
Let's close this and open more specific issues as we see issues.

**Comment by Fixer-007** [comment] 2020-12-16 15:07
Bisecting may help identifying exact cause?

**Closed** 2021-01-08 15:37 UTC
Labels: @ Client / Audiovisuals, Performance, Possible close, Unconfirmed bug

**Comment by ata-star** [comment] 2021-02-19 18:33
> Let's close this and open more specific issues as we see issues.

#10648

**Comment by lu-ccc** [comment] 2021-02-20 01:24
Never seen a minetest over 50 fps
