### ISSUE TITLE
Any mouse movement causes camera to point at the floor and rapidly spin

### ISSUE THREAD

**Issue by triffid** [minetest/minetest#9570] opened 2020-03-31 02:47 UTC
##### Minetest version

```
5.1.1
```

##### OS / Hardware

Operating system: Gentoo
CPU: i7 7700K

GPU model: GTX1060
OpenGL version: OpenGL core profile version string: 4.6.0 NVIDIA 440.64

##### Summary
Installed the game just now to have a look, but any mouse movement causes camera to point at the floor and rapidly spin, which makes the game unplayable.

I tried changing mouse sensitivity as per suggestion in another issue, but it only makes the camera spin faster.

Mouse look works perfectly in every other game I have, both through wine and Linux native.

##### Steps to reproduce
1. start
2. hit play
3. move mouse

**Comment by triffid** [comment] 2020-03-31 02:49
Checked more closely, all mouse movements cause the camera to spin counter-clockwise regardless of mouse direction.

**Comment by Jordach** [comment] 2020-03-31 04:36
I can confirm this in a stranger environment, where mouse grabbing seems to go a bit wonky.

When using remote desktop to Windows 10 from a macOS device, Minetest suffers similar symptoms.

**Comment by triffid** [comment] 2020-03-31 06:14
Fwiw there's nothing strange like VMs here, just native Linux with Xorg+evdev+nvidia drivers, ie a fairly common linux desktop environment.

**Comment by sfan5** [comment] 2020-03-31 09:48
possible duplicate #8539

Works perfectly fine here with Xorg+libinput+nvidia. In fact, aren't most distros using libinput these days?

**Comment by SmallJoker** [comment] 2020-03-31 16:25
Related #4287, #7186

Either this is a mouse locking issue, the mouse is placed 1px off-center, or the sensitivity is way too high.

> I tried changing mouse sensitivity as per suggestion in another issue

How about `mouse_sensitivity = 0.001`?

**Comment by triffid** [comment] 2020-04-01 07:31
With mouse_sensitivity=0.001 the behaviour remains the same, but it spins slower.

All four mouse movement directions cause a counter-clockwise camera rotation and it remains staring at the ground.

I also noticed that it seems to warp the mouse to the bottom right corner of the window, as my panel keeps popping up and making the cursor visible.

I tried changing DPI from 72 to 120, with no change.

**Comment by v-rob** [comment] 2020-04-01 21:41
I have the same problem (Linux Mint virtual machine from Win10 where I compile Minetest for my PRs), but it appears slightly differently:  It will spin a lot (I don't remember whether it was clockwise or counter-clockwise) until it points at the floor, and after pointing at the floor for a while while still spinning, it will move straight up, and the alternate again every few spins.

It's a royal pain although it doesn't affect me much because I only work on formspecs.

**Comment by lucasburlingham** [comment] 2020-04-06 18:18
I have tried to use MT on all sorts of VM's, Remote Protocols, but none of them have worked in windowed mode. Have you tried to use full-screen mode instead of windowed?

**Comment by triffid** [comment] 2020-04-06 18:20
I am not using a VM or any remote protocol.

I'm running minetest locally on a native Linux desktop.

**Comment by Montandalar** [comment] 2020-04-07 03:38
I can confirm this is an issue on my Debian virtual machine. Using a Windows 7 virtualbox as the host, and Debian 10 running i3 window manager.

**Comment by triffid** [comment] 2020-04-16 12:14
Still happening in 5.2.0, however when in windowed mode it now warps the mouse cursor outside the game window on mouseover.

Seems like it's caused by minetest getting confused by my mouse speed setting; if I set the speed to exactly 1 it works - definitely an issue with minetest, as literally every other game I have works perfectly regardless of mouse speed setting.

**Comment by sfan5** [comment] 2020-04-16 13:29
this is definitely a duplicate of #8539 then

**Closed by sfan5** 2020-04-16 13:29 UTC
Labels: @ Client / Controls / Input, Linux, Unconfirmed bug

**Comment by thackel** [comment] 2020-09-25 11:54
Today i experienced this issue and could solve it, so i post a solution altought the issue has been closed.
I ran minetest 5.3.0 in a VirtualBox 6.1.14 VM with Xubuntu 20.04 and had the wild spinning problems.

I just had do disable the "mouse integration" and then all worked fine. Of course the mouse is then locked in the VM but that's not a real problem when you know how to unlock it (normally right ctrl).

**Comment by verymilan** [comment] 2022-04-13 07:52
I currently experience this after the most recent release update of my client in macOS. I can run other games such as Veloren just fine althrough it's a hackintosh, but Minetest now not only lacks performance, but rendered itself unplayable because any movement would make my camera spin like crazy. :(

**Comment by gardners** [comment] 2024-07-13 00:07
Happen with a fresh build from github of 5.9.0 on PureOS (debian based).

Any further progress on this?

**Comment by gardners** [comment] 2024-07-13 00:09
Did not happen with the 5.4.0 build via PureOS packages, if that provides any helpful clue.

**Comment by sfan5** [comment] 2024-07-14 09:53
Please open a new issue with all details then.
