### ISSUE TITLE
Screenshot in fullscreen mode is all black

### ISSUE THREAD

**Issue by SolidBlock-cn** [minetest/minetest#11204] opened 2021-04-17 08:46 UTC
##### Minetest version

```
5.4.1
```

##### OS / Hardware

Operating system: Windows 10
CPU:

GPU model: OpenGL
OpenGL version: 4.6.0

##### Summary

In fullscreen mode, the screenshot is totally black.
##### Steps to reproduce

In the "settings", search for "fullscreen" and set it "ON".
Use the shortcut (F12 by default) to get a screenshot.

**Comment by SmallJoker** [comment] 2021-04-17 12:40
Duplicate of #6649 but using Windows this time.

**Closed by SmallJoker** 2021-04-17 12:40 UTC
Labels: Unconfirmed bug
