### ISSUE TITLE
convergent devices, touchscreen support

### ISSUE THREAD

**Issue by okias** [minetest/minetest#12785] opened 2022-09-19 17:03 UTC
## Problem
Minetest should be able detect (at least) on Linux,
- when there is no mouse connected and display touchscreen controls
- when mouse is connected, it should hide onscreen controls

Since most of modern Linux phones has convergent features (see https://github.com/minetest/minetest/issues/11275#issuecomment-988501225 ), re-compiling binaries between switching or having two builds isn't much feasible.

## Solutions

Implement runtime switch instead of compile time option `ENABLE_TOUCH`

**Comment by rubenwardy** [comment] 2022-09-19 17:06
Effectively a duplicate of: #10062 and #11275 

they should be merged into a single issue

**Comment by rubenwardy** [comment] 2022-09-19 17:07
Duplicate of #10062

**Closed by rubenwardy** 2022-09-19 17:07 UTC
Labels: Feature request
