### ISSUE TITLE
[SUGGESTION] SerializationError AutoFix

### ISSUE THREAD

**Issue by DevynCJohnson** [minetest/minetest#2694] opened 2015-05-12 14:27 UTC
I have had a SerializationError recently and I fixed it thanks to this thread - https://forum.minetest.net/viewtopic.php?id=8125 . Perhaps, Minetest should be made to put dummy values in env_meta.txt when the file is empty.

**Comment by PilzAdam** [comment] 2015-05-12 14:54
Duplicate of #2663.

**Closed** 2015-05-12 19:23 UTC
Labels: duplicate
