### ISSUE TITLE
Object's cube visual type's textures (tiles) don't mirror a nodes

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest#7966] opened 2018-12-11 14:34 UTC
##### Issue type

 - Feature request
 
##### Minetest version

```
f318366
```

##### OS / Hardware

Operating system:
CPU:

GPU model:
OpenGL version:

##### Summary

Hi.  When setting an object's visual type to "cube", in this case the player, the textures field doesn't mirror that of the node's.  So, for example you can use three texture fields in the node def, and show all six sides; but on the object, it only shows the three.  Same for only one field, showing "Unknown Node" texture for others.  Also, I think the texture modifiers and texture options don't work.  Sorry, I'll report more on the particulars soon.
##### Steps to reproduce

```
minetest.register_on_joinplayer(function(player)
local node = minetest.registered_nodes["default:dirt_with_grass"]
player:set_properties({visual_type = "cube", textures = node.textures})
end)
```
Untested, I'll refine later but for now it should suffice.

Edit:
```
minetest.register_on_joinplayer(function(player)
  player:set_properties({visual = "item", textures = {"default:furnace"})
end)
```
Notice the reversed front/back orientation in third-person camera mode.

**Comment by jastevenson303** [comment] 2018-12-11 14:37
Use case: https://github.com/jastevenson303/Glitchtest/blob/master/mods/jas0/classes.lua#L80 https://github.com/jastevenson303/Glitchtest/blob/master/mods/jas0/classes.lua#L398

**Comment by stujones11** [comment] 2018-12-11 21:24
> Untested, I'll refine later but for now it should suffice.

I can tell you that nodes have tiles, not textures and their number can vary. Making the cube visual mirror the behaviour may well be possible but likely not so trivial. If you want to mimic a node then you should use the new `item` visual.

**Comment by paramat** [comment] 2018-12-12 03:11
Seems like certain node texture features are not yet coded for objects, somewhat understandable as objects are much less used. So a feature request not a bug.

**Comment by jastevenson303** [comment] 2018-12-12 11:04
Thank you Stu, Paramat.  I'll try the item visual type, and I changed the report to indicate feature request.  I'll report back soon with what works and doesn't, thanks again.

**Comment by jastevenson303** [comment] 2018-12-12 11:30
Awesome @stujones11 thanks so much!  It works way better, and was super easy to do.  I actually had to update to use this feature!  :D

@paramat I'm not sure what to do with this issue now.  It's resolved, for me.

**Comment by jastevenson303** [comment] 2018-12-12 15:15
The only issue I have had so far is that the front and back are reversed:

3rd person /rear/ view (first F7 press):
![screenshot_20181212_101031](https://user-images.githubusercontent.com/23448162/49878780-6995b080-fdf6-11e8-8e94-ed3155d794f0.png)

3rd person /front/ view (second F7 press):
![screenshot_20181212_101043](https://user-images.githubusercontent.com/23448162/49878795-71edeb80-fdf6-11e8-883f-010499511df5.png)

https://github.com/jastevenson303/Glitchtest/blob/master/mods/jas0/classes.lua#L421

Ps. paramat, just a heads up, I noticed when making this player node class physical, that sneak jumping `air' glitch I brought up with you some time ago occurred.  The only thing is, that node class uses new_move.  :/  I turned physical off, (no jumping on top of other player's) for now, and will file an issue later.  Bye.

**Comment by stujones11** [comment] 2018-12-12 22:58
> The only issue I have had so far is that the front and back are reversed:

I am not quite sure what I am supposed to be looking at here but if there is a reversal of texture then it is a bug in the `wieldmesh` composition. However, that would be a different issue, unless you you re-title this one ;)

**Comment by paramat** [comment] 2018-12-13 03:43
Ok, closing then.
Making the player 'physical' is a bad idea anyway, the player is specifically meant to be non-physical.

**Closed by paramat** 2018-12-13 03:43 UTC
Labels: Feature request, Not a bug
