### ISSUE TITLE
Formspec and HUD images scale badly

### ISSUE THREAD

**Issue by indriApollo** [minetest/minetest#2419] opened 2015-03-02 16:32 UTC
Scaled images in a formspec are ugly. Is there a possibility to implement svg support ?
![Imgur](http://i.imgur.com/bqCfPkJ.png)
![Imgur](http://i.imgur.com/Y1PUGaG.png)
Should be : 
![Imgur](http://i.imgur.com/7tOutAN.png)

My actual workaround is to use 500x500 images. That's huge overkill.

**Comment by rubenwardy** [comment] 2015-03-04 08:37
This is needed for scalability, which also needs to be fixed.

**Comment by rubenwardy** [comment] 2015-03-04 15:31
A quick search: http://irrlicht.sourceforge.net/forum/viewtopic.php?t=43979

**Comment by VanessaE** [comment] 2015-03-08 04:53
SVG support would be nice indeed, but as long as we're still dealing with raster images (and we will be probably forever, whether we have SVG support or not), the best solution would be similar to what Warr1024 does with https://github.com/minetest/minetest/pull/2462, but for formspec images instead of in-world.

That is, if the source image is smaller than the final, displayed size of the inventory slot or whatever, use nearest-neighbor to upscale the source image by exactly 2x, 3x, 4x, ... whatever it takes to get it as close as possible to that bounding box without going over.  From that multiplied size, scale it up the rest of the way with Lanczos.

If the source image is already larger, just scale it down directly to the final size with Lanczos.

Either way, the image stays as sharp as possible at any size, but still fits perfectly into the inventory slot.

**Comment by Warr1024** [comment] 2015-03-09 12:25
Note that this affects HUD images as well, not just formspecs.  In code, grep -r draw2DImage currently appears 29 places throughout guiEngine.cpp, guiChatConsole.cpp, hud.cpp, cguittfont/CGUITTFont.cpp, guiTable.cpp, drawscene.cpp, guiFormSpecMenu.cpp.

Some testing indicates that we don't need anything as fancy as a Lanczos filter to resample the image.  Once scaled large enough, a simple linear/box filter will produce good results, if potentially not as sharp as Lanczos.  We can also upscale the image directly to the smallest integer size large enough to cover the target area; power-of-2 scaling is not necessary.  Luckily, Irrlicht includes video::IImage::copyToScaling and video::IImage::copyToScalingBoxFilter methods to do exactly these things.

draw2DImage accepts an ITexture as the parameter for what to draw, and the rectangle into which to draw it.  We could replace each of these calls with a wrapper that (1) looks up the texture and dimensions in a cache for existing pre-scaled textures, (2) if it doesn't exist, extract the image from the texture, pre-scale it, store it in the cache, and then (3) draw it.

Textures cannot be scaled--only images--and we don't keep the original images around used to create textures.  Changing that to keep the original images could affect a lot of code.  There are, however, supposedly ways to convert a texture back into an image (http://irrlicht.sourceforge.net/forum//viewtopic.php?t=22268); this seems risky (might not work on all video drivers...?) though the Irrlicht docs seem to imply that we should be able to expect it to work.

**Comment by Warr1024** [comment] 2015-03-20 04:51
I have a prototype working, at least, on my own desktop computer.  Some additional testing would be welcome.

https://github.com/Warr1024/minetest/commits/guiscaling

Before:
![before](https://cloud.githubusercontent.com/assets/324806/6746225/2261dfa6-ce9b-11e4-90ac-ec68be568d55.png)

After:
![after](https://cloud.githubusercontent.com/assets/324806/6746226/254fd326-ce9b-11e4-8646-489708458a20.png)

**Comment by Warr1024** [comment] 2015-04-02 13:10
Since 6d61375c, use setting `gui_scaling_filter = true`.

**Comment by indriApollo** [comment] 2015-04-30 09:01
Formspec images are now well scaled in the latest master, thanks @Warr1024

**Comment by CasimirKaPazi** [comment] 2017-05-01 15:06
Can we please reopen this issue. It's broken again (or still?).

MTG inventory. See how the middle part of the stick is distorted.
![](http://screenshot.ru/upload/images/2017/05/01/screenshot_20170501_1657179085c.png)

gui_scaling and gui_scaling_filter don't help in this case.

**Comment by rubenwardy** [comment] 2017-05-01 15:16
We still need a good way of scaling icons, either with vector graphics or a way of efficiently scaling down a high res icon to the right resolution

**Comment by paramat** [comment] 2017-05-01 15:50
The dustbin in creative inventory is often distorted, as is the icons proposed here https://github.com/minetest/minetest_game/pull/1666#issuecomment-289329587

**Comment by paramat** [comment] 2018-04-08 20:53
For information, i found a current workaround is to use a 128x128 RGBA texture with a slight blur, see current creative mod in MTG.

**Comment by Warr1024** [comment] 2018-04-26 23:08
If you use gui_scaling_filter, then all 2D icons will be scaled with an algorithm that tries to find at least a reasonable balance between crisp pixels and avoiding aliasing/jaggies.  Unless the scaling factor is an exact integer multiple, no perfect solution is possible.

However, this does not apply to 3D models, which some of the inventory icons now are.  Those are pushed through the normal 3D rendering pipeline, with its own applicable anti-aliasing settings.  A pure software solution for this is not likely; it will depend a lot on the capabilities of your 3D hardware.

**Comment by sfan5** [comment] 2020-05-04 17:59
So, how come `gui_scaling_filter = true` isn't enabled by default?

**Comment by Terumoc** [comment] 2020-05-04 19:27
> So, how come `gui_scaling_filter = true` isn't enabled by default?

Sorry to but in, but could this be the reason?:
`2020-05-04 14:23:43: ERROR[Main]: Irrlicht: Invalid size of image for OpenGL Texture.`

this error only starts showing up with the option turned on in MT 5.2.0 for me

**Comment by Zughy** [comment] 2022-06-18 23:43
Duplicate of #10733, which is, to me, more complete. Closing here

**Closed by Zughy** 2022-06-18 23:43 UTC
Labels: @ Client / Audiovisuals, Feature request, Formspec
