### ISSUE TITLE
minetest.register_input_binding()

### ISSUE THREAD

**Issue by jordan4ibanez** [minetest/minetest#15240] opened 2024-10-06 05:58 UTC
### Problem

Can't register keys to anything. Arbitrary input defaults. No extensions. Static. Multiple requests for fix.

### Solutions

minetest.register_input_binding(name, default_value_optional)

Default setting (disabled) only allows the engine to add key bindings. Can transition current hard codes into api.

Player has to enable this like mod channels.

If enabled allows mods to register input bindings.

Checks if existing name, errors if so.

Possibility for player to set limit to number of keybindings available.

Replace input bit api thing with minetest.get_input(name) up or down.

Possibility for analog input bindings to be made to help players with disabilities.

Possibility for minetest.register_analog_input(name, default).

Possibility for dead zone configuration.

The bindings object (in the database) should be immutable. There would be no minetest.unregister_input(). Once registered in game no taking away. Prevents issues.

Can create default game menu which can change these for the player.

Mods can extend it to make it look cool or re-arrange it.

### Alternatives

N/A

**Comment by SmallJoker** [comment] 2024-10-06 07:14
Related: https://github.com/minetest/minetest/issues/8058#issuecomment-1773526319

Duplicate of #5825
Duplicate of #2731
Duplicate of #12488

**Closed by SmallJoker** 2024-10-06 07:14 UTC
Labels: Feature request
