### ISSUE TITLE
`set_properties` interrupts player animations

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9429] opened 2020-02-24 16:37 UTC
##### Minetest version
```
5.1.1
```

##### Summary
Calling `set_properties` and setting the `nametag_color.a` to `0` interrupts the current player animation.

##### Steps to reproduce
Paste this into a mod:
```lua
minetest.register_globalstep(function()
    for _, player in pairs(minetest.get_connected_players()) do
        player:set_properties({nametag_color={r=0, g=0, b=0, a=0}})
    end
end)
```
Now press F7 to check 3rd person. Walk and see the animation playing incorrectly.

**Comment by sfan5** [comment] 2020-02-24 18:49
Sounds like a duplicate but can't find the original issue.

**Comment by SmallJoker** [comment] 2020-02-24 19:21
Duplicate of #6572

**Closed by SmallJoker** 2020-02-24 19:21 UTC
Labels: Unconfirmed bug
