### ISSUE TITLE
Optionally adjust view range automatically based on server's max_block_send_distance

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#4773] opened 2016-11-14 05:18 UTC
Right now the user has to find the right view range in order to hide rendering artifacts when blocks haven't been retrieved from the server.

If the client could learn about the servers max_block_send_distance we could default to automatically setting view range to max_block_send_distance * 16. (or perhaps even max_block_send_distance * 16 / 0.9 - see https://github.com/minetest/minetest/blob/master/src/game.cpp#L4113)

For example the current defaults are max_block_send_distance = 9, view range = 100, the view range could either be increased, or max_block_send_distance reduced.

Could be fancy and set view range = min(max_block_send_distance, max_block_generate_distance) * 16.

This would give user by default a good experience.

**Comment by paramat** [comment] 2016-11-14 08:24
:-1: This doesn't take into account 'max block generate distance', in some situations world is only generated out to 6 blocks, in other situations pre-existing world up to 10 blocks is sent. It's not essential to hide the edge of loaded world, it's unavoidable anyway as world rendering often lags, especially with mods running.

> Could be fancy and set view range = min(max_block_send_distance, max_block_generate_distance) * 16.

Nope, when world is already generated out to a large distance a player will not want to see only 6 blocks = 96 nodes.

**Comment by lhofhansl** [comment] 2016-11-14 16:24
Fair enough.

Surely, though, it's never useful to have the view range _greater_ than max_block_send_distance * 16.

**Comment by paramat** [comment] 2016-11-14 17:19
Yeah i think it is useful to have it greater.
I can't stand anything less than 190, and prefer 260, your suggestion would set it to 160.
The issue is, although max block send distance is 160 nodes, as you move around you load in a much larger area of world and often want to see this using a view range larger than 160. The visible edge of unloaded world is only present in the direction of travel into unloaded world. So the send distance doesn't seem particularly important.

**Comment by lhofhansl** [comment] 2016-11-14 22:23
Not sure it can be easily done, though. The client would need to be able to learn about (some of) the server settings.

**Comment by paramat** [comment] 2016-11-15 14:05
Exactly, so i'm suggesting not doing anything :]

**Comment by lhofhansl** [comment] 2016-11-16 23:44
We can close this. I will note that currently we're sending more data to the clients than these - by default - will allow a user to see, so there's waste there. (might make the send range a bit bigger to hide some of the lag, but I found that never works right)

view range defaults to 100, max_block_send_range to 9. We could default view range to 150 or max_block_send_range to 6... Or - as I said - close it :)

**Comment by paramat** [comment] 2016-11-17 01:11
> view range defaults to 100, max_block_send_range to 9. We could default view range to 150 or max_block_send_distance to 6

I think it's this way because many players are able to use a view range of 160+ (and 160 is still too short for me personally), however the reason the default view range is set lower is to not cause very low FPS on low-power devices and smartphones for new players. View range is quick and easy to change, but block send distance isn't so easy to change.
So i don't think it's a good idea to either reduce block send distance or increase default view range.

As you don't mind a close i will close this.

**Closed by paramat** 2016-11-17 01:11 UTC
Labels: @ Client / Audiovisuals, Feature request
