### ISSUE TITLE
Music for Subgames and Minor Menu tweeks

### ISSUE THREAD

**Issue by ExeVirus** [minetest/minetest#9285] opened 2020-01-05 05:03 UTC
Hello everyone, I have been working on getting main menu music working on a subgame basis, as well as the main menu in general. I wanted to share my progress and expected changes I will be submitting in a PR soon:

1. I have been able to have subgames have their own main menu music provided in their "menu" folder. Currently they are named as "<subgamename>_menu.ogg", i.e. "minetestgame_menu.ogg". Let me know if you disagree with this thought process.

2. I have been able to have this music stop when switching between subgames and to carry through to the other tabs.

          2a. I think having the music carry to other tabs is a good idea, but then it makes those tabs    
          kind of jarring. For example, When I select "minimal" subgame, and switch to the settings tab, 
          the background and header change back to the default "MINETEST" header and background. 
          I propose that instead, the header and background from the currently selected subgame  
          carries through to that tab, contributors tab, and the content tab (but not the online tab).

3. I currently have an issue with the lua access to sound, as we only can stop sounds that are playing by calling sounds_stop. In reality, we should have a stop_all_sounds function exposed, as well as a get_all_sounds function exposed that returns handles&names to all currently playing sounds so a user can stop them or restart them after playing an important sound. Does anyone see an issue with adding these functions?

4. The current way we find local music is extremely inefficient, just read [here](https://github.com/minetest/minetest/blob/91114b562fb2c65467485008b810836f951274ea/src/gui/guiEngine.cpp#L110) Notice that this is for local music only, so maybe not a big issue?

5. All this work implies that minetest game will have music now, as that would be possible. I can compose one for the PR submission, but I think we should reach out to the community for song submissions. 

             5a. That said, any subgame that doesn't provide a menu.ogg file should also default to this 
             music (same for minimal)

6. The online tab is unrelated to subgames, as we know, because each server effectively provides the subgame. This means this tab should either use the current subgame music, the default minetest game music, or some other music. 

7. The loading screen will automatically stop the currently playing menu music. Perhaps it shouldn't until the game is completely loaded? Or perhaps there should be a specific loading music?

Okay, that's it for today's work, Can y'all provide some feedback and suggestions?

**Comment by benrob0329** [comment] 2020-01-05 08:32
The loading bar should play music provided by the server IMO, but that may be difficult.

**Comment by Wuzzy2** [comment] 2020-01-05 10:01
TBH, I am not too happy with the idea because of the way how the main menu currently works.
Looks like the music will just switch immediately when you select a new game which might not be very pleasant to hear at when you switch through games. Especially if (what I assume) the music will always reset to start instead of continuing where it stopped. That having said, I have not actually tested this.
Also, another problem I have is that this seems to be singleplayer-specific only.

Maybe music could work with a differently structured main menu, but not really with our current main menu.

I agree that the loading screen should have music. But not from the server (that would need download time).

**Comment by Moth-Tolias** [comment] 2020-01-05 10:06
will opus be supported in addition to ogg?

**Comment by ExeVirus** [comment] 2020-01-05 12:18
Well, opus will not be supported by this project, because minetest does not support opus. currently we use .ogg for everything like music. We could support more filetypes, however. 

Wuzzy, that is a good point. I think that to mitigate your exact issue, I have been leading towards making the currently select d subgame music play for all tabs and menus and load screen. This way the music only changes when you change subgames.

**Comment by rubenwardy** [comment] 2020-01-05 12:33
Note that my menu redesigns already make it so the game selection is for all tabs, not just single player

**Comment by ExeVirus** [comment] 2020-01-05 12:38
Rubenwardy, can you link to that PR?

**Comment by rubenwardy** [comment] 2020-01-05 13:07
It's painful to search on my phone, look for the tabview layouter pr by me

**Comment by rubenwardy** [comment] 2020-01-05 13:20
#8758

**Comment by ExeVirus** [comment] 2020-01-05 13:25
okay, in light of that PR, I will be breaking my work into two PRs. one for the lua additions for sounds, likely a play_music, pause_music, pause_sound, stop_all_sounds, stop_music, etc.

and one for the eventual state of the main menu to include subgame provided music and making that play through to the load screen.

**Comment by rubenwardy** [comment] 2020-01-05 13:29
have you tried adding music with the correct name to games/game/menu ?

**Comment by ExeVirus** [comment] 2020-01-05 15:18
Yes, I have gotten music to successfully load from each appropriate
subgame/menu folder. Currently I name them game_menu.ogg.

**Comment by benrob0329** [comment] 2020-01-05 15:31
`sound_fade` should be used to make it less jarring.

**Comment by ExeVirus** [comment] 2020-01-05 15:39
Right now I'm planning on the music_play function to only allow a single
song to be played at a time (other songs/tunes can be played as sounds).
When a new one is to be played over a currently playing song, the music
would automatically Crossfade.

**Comment by paramat** [comment] 2020-01-05 19:09
> I have been able to have subgames have their own main menu music provided in their "menu" folder. Currently they are named as "_menu.ogg", i.e. "minetestgame_menu.ogg". Let me know if you disagree with this thought process.

Great, we need this.
> All this work implies that minetest game will have music now,

No, it does not have to use the feature. Also, we have been through this before a few years ago, with huge amounts of arguing, trying to choose music is an absolute nightmare as music is so subjective.
MTGame is rather neutral and universal so it becomes even more difficult to choose music for it. I think it should not have music.
Another issue is that MTGame is unique in bing developed by a large number of core devs (8) all with wildly varying attitudes, so choosing music will be even more difficult.
> That said, any subgame that doesn't provide a menu.ogg file should also default to this music (same for minimal)

Absolutely no =) Unsuitable music is far worse than no music.
> The online tab is unrelated to subgames, as we know, because each server effectively provides the subgame. This means this tab should either use the current subgame music, the default minetest game music, or some other music.

Ii is best to use the music of the currently selected game (if music exists for it, if not, silence), because before you connect you have not yet switched away from the currently selected game.
MTGame music will be unsuitable, and treats MTGame as more important than other games.
'Some other music' implies music chosen for the MT engine, again, we gave been through that before with huge amounts of arguing, it is impossible to choose. Besides, an engine cannot have music as it is completely neutral.

We do not have to always have music playing. Music should only play if the currently selected game includes it.
> The loading screen will automatically stop the currently playing menu music

Not a problem.

**Comment by paramat** [comment] 2020-01-05 19:15
> Looks like the music will just switch immediately when you select a new game which might not be very pleasant to hear at when you switch through games.

Seems ok, games are rarely switched, and how could anyting else make sense when the background image changes at that time?

**Comment by benrob0329** [comment] 2020-01-05 21:16
Idea for polish: We have a timer that starts when you open the main menu (opening Minetest initially or leaving a server for example). This is used to start the music from where it would currently be playing. Then if the player switches between subgames the music starts from where it would be if it had always been playing, rather than starting over and it feels more "fluid", as if the game is waiting in the background.

**Comment by ExeVirus** [comment] 2020-01-05 22:09
Benrob: While I see how that could be more polished, having a Crossfade into the beginning should be almost as polished. The issue with your idea is let's say we have a 10 minute song load up and you change games at minute 7, and the song you switch to is 2 minutes long. it's hard for us to program all that checking into openal for seeing how long a given song will be, and then jumping to a specific point in the song. 

To save on Dev time, I personally will just implement a Crossfade to the start of the selected subgame music.

**Comment by hecktest** [comment] 2020-01-11 07:35
Yay, more hardcoding.

**Comment by rubenwardy** [comment] 2021-01-31 19:51
Duplicate of #8596

**Closed by rubenwardy** 2021-01-31 19:51 UTC
Labels: Discussion, Feature request, Question, Sounds, Supported by core dev
