### ISSUE TITLE
Object attached to a player's bone lags behind

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#9124] opened 2019-11-18 11:50 UTC
An object attached to any bone on a player entity will sometimes lag behind. This happens randomly, at times it will behave correctly.
Looks like there's unnecessary interpolation being applied instead of the object just being parented to the bone.
This is visible both on the player's client, and on other connected clients.
Mobs and other server entities are not affected, or at least I've yet to see that happen.
![helmet lag](https://user-images.githubusercontent.com/42101236/69049999-64c37e80-0a01-11ea-9a44-521f450de137.gif)

**Comment by hecktest** [comment] 2019-11-18 22:06
Upon closer inspection I noticed that the attachee doesn't lag relative to the bone, just relative to the player position. It animates fine but the root is off.

**Comment by Warr1024** [comment] 2019-11-19 14:11
Duplicate of #2318

**Comment by rubenwardy** [comment] 2019-11-19 14:25
You've definitely linked to the wrong issue there

**Comment by Warr1024** [comment] 2019-11-19 14:27
Fixed.

**Closed** 2019-11-19 14:29 UTC
Labels: Unconfirmed bug
