### ISSUE TITLE
No sound on Android dev build

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2904] opened 2015-07-11 20:23 UTC
I can build and run the apk just fine, but there is no sound. However, if I install a pre-built one, the sound does work. Also, according to <a href="http://irc.minetest.ru/minetest-dev/2015-07-10#i_4316811">this</a> discussion on IRC, I am not the only one experiencing this problem.

**Comment by est31** [comment] 2015-07-29 18:12
Confirmed. Also confirmed on 1cb404522f1fd2f856383e10e409048468df0849. Also tested my own build (to be sure its not a setup bug) of 315b00d15081d1f56f0e2de22a4ff1a393ab7f22 (the commit f-droid uses for 0.4.12.12) and couldn't reproduce there.

**Comment by est31** [comment] 2015-07-29 23:34
Bisected it to c788b1732225ed0c118ed11b184bb5d3b35e1f7c, #2455. There seems to be one of those optimisations which don't work.

**Comment by est31** [comment] 2015-08-02 17:44
fixed by 47225346be9ab0d55bc2dbc71b6c0f085f47a75e

**Closed by est31** 2015-08-02 17:44 UTC
Labels: Android
