### ISSUE TITLE
Add support for overriding sounds using texture packs

### ISSUE THREAD

**Issue by Hume2** [minetest/minetest#11487] opened 2021-07-26 07:39 UTC
## Problem

Textures can be modified using texture packs but there is no such option for sounds. It can be useful for servers which provide some kind of music. The amount of transferred data to client is limited by players who have a poor connection, which also limits the quality of music and sounds which can be used on a server. One way to cope with the issue is providing low quality media and a texture pack containing higher quality media which can be downloaded optionally. This is possible with textures but not with sounds.

## Solutions

When sounds are present in a texture pack which is used, these sounds shall override the sounds provided by mods.

## Alternatives

Maybe the players could choose the quality of media before joining a server.

## Additional context

I was requested to add music tracks to LV music player in the technic mod but I didn't want to add that much media to the server. So I had an idea that I could put there dummy tracks, which could be overriden by an official texture pack that could be downloaded separately. However, I forgot that such feature is not available in Minetest.

**Comment by rubenwardy** [comment] 2021-07-26 10:04
Duplicate of #4093

**Closed by rubenwardy** 2021-07-26 10:04 UTC
Labels: Feature request
