### ISSUE TITLE
Falling nodes loses their meta info

### ISSUE THREAD

**Issue by vladtcvs** [minetest/minetest#5232] opened 2017-02-14 12:32 UTC
Minetest 0.4.14

How to reproduce: create mod with init.lua:
```
heavy_cube={}

minetest.register_node("heavy_cube:cube", {
        description = "Heavy cube",
        groups = {cracky = 3, falling_node = 1},
        is_ground_content = false,
        on_construct = function(pos)
                local meta = minetest.get_meta(pos)
                local cnt = meta:get_float("counter")
                minetest.log("action", "Construct. Counter: "..cnt)
                meta:set_float("counter", 0)
        end
})

minetest.register_abm({
        nodenames = {"heavy_cube:cube"},
        interval = 5,
        chance = 1,
        action = function(pos)
                local meta = minetest.get_meta(pos)
                local cnt = meta:get_float("counter")
                minetest.log("action", "Counter: "..cnt)
                cnt = cnt + 1
                meta:set_float("counter", cnt)
        end
})
```

then, put this cube on the groud, wait for a little, and remove ground under the cube. The counter resets.

```
2017-02-14 15:30:57: ACTION[Server]: singleplayer places node heavy_cube:cube at (-2,9,4)
2017-02-14 15:30:57: ACTION[Server]: Construct. Counter: 0
2017-02-14 15:31:00: ACTION[Server]: Counter: 0
2017-02-14 15:31:05: ACTION[Server]: Counter: 1
2017-02-14 15:31:10: ACTION[Server]: Counter: 2
2017-02-14 15:31:11: ACTION[Server]: singleplayer digs default:dirt_with_dry_grass at (-1,8,4)
2017-02-14 15:31:12: ACTION[Server]: singleplayer digs default:dirt_with_dry_grass at (-2,8,4)
2017-02-14 15:31:12: ACTION[Server]: Construct. Counter: 0
2017-02-14 15:31:15: ACTION[Server]: Counter: 0
```

**Comment by Wayward1** [comment] 2017-02-14 14:46
Just FYI, the latest Minetest release is 0.4.15

**Comment by vladtcvs** [comment] 2017-02-14 20:41
0.4.15 has the same problem

**Comment by red-001** [comment] 2017-02-16 16:08
duplicate of #4087

**Closed** 2017-02-16 16:24 UTC
