### ISSUE TITLE
Broken movement if you sneak on collision box that lies entirely in another node

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest#12612] opened 2022-07-30 01:17 UTC
##### Minetest version
```
5.5.1, 5.6.0-dev-de8ce9a8ff999c7ab9562528a972d5426a9f7cec
```

##### OS / Hardware
Operating system: linux

##### Summary
when a node's nodebox exists entirely within another node, startling behavior develops when you stand on it and press "sneak"

##### Steps to reproduce
1. load this mod:
```lua
local no_flicker = 1 / 4096

minetest.register_node("nodebox_jank:node", {
	drawtype = "nodebox",
	paramtype2 = "facedir",
	node_box = {
		type = "fixed",
		fixed = {{
	         -1 / 2 + no_flicker,
	         -1 / 2 + no_flicker,
	         -1 / 32 + 1,
	         1 / 2 - no_flicker,
	         1 / 2 - no_flicker,
	         1 / 32 + 1
         }},
	},
})
```

2. place a line of these. param2 matters, though it works in all directions. 
3. jump on top of the first in the series (it is directional, pay attention).
4. press sneak

result:

https://user-images.githubusercontent.com/25628292/181864685-9ce283cc-6b25-45f3-87ee-09f157a4152f.mp4

possibly related:
* #9993

**Comment by fluxionary** [comment] 2022-07-30 01:26
```
you spin me right 'round, baby, right 'round
like a record, baby, right 'round, 'round, 'round
```

https://user-images.githubusercontent.com/25628292/181864985-007c3a7c-a2b6-473f-9d94-f56b37ae1040.mp4

**Comment by Wuzzy2** [comment] 2022-08-01 07:50
Bug confirmed.

Note: The issue poster here is **NOT** referring to *the* Sneak Glitch, but a bug in sneaking. The video shows that the player moves very fast, almost teleporting, as soon you press the sneak key, on these very strange nodes.

Suggested new title: “Broken movement if you sneak on collision box that lies entirely in another node”

I wonder if Minetest should officially support it if the collision box lies *entirely* in another node. Currently, there is nothing in the `lua_api.md` that disallows this. The only rule is that the collision box must lie entirely within +/- 1.45, which is the case here.

**Comment by fluxionary** [comment] 2022-08-01 20:11
> Suggested new title: “Broken movement if you sneak on collision box that lies entirely in another node”

fine by me

> I wonder if Minetest should officially support it if the collision box lies _entirely_ in another node. Currently, there is nothing in the `lua_api.md` that disallows this. The only rule is that the collision box must lie entirely within +/- 1.45, which is the case here.

the use case here is to allow "window panes" to be placed inside of other nodebox/mesh nodes, so that they "fit": 

![screenshot_20220801_131105](https://user-images.githubusercontent.com/25628292/182236231-3f6eea1f-f010-42a9-b796-6ee16fc8f4f3.png)

**Comment by rubenwardy** [comment] 2022-08-01 20:42
> ![screenshot_20220801_131105](https://user-images.githubusercontent.com/25628292/182236231-3f6eea1f-f010-42a9-b796-6ee16fc8f4f3.png)

Offtopic but: Wait, did you take this image on Your Land? I was standing behind you, wondering why your were staring at a window

**Comment by fluxionary** [comment] 2022-08-01 21:11
> Offtopic but: Wait, did you take this image on Your Land? I was standing behind you, wondering why your were staring at a window

=D exactly.

**Comment by Skamiz** [comment] 2022-08-06 08:58
For what it's worth, I have used this behavior as a feature, in the past. I made an (unreleased (yet)) mod which uses it to add a transportation method where the cost scales linearly with the distance traveled.

This is also the same behavior which you may notice during jump and runs where sneaking allows you to latch onto a fence from a greater distance then you would expect. (Which is sometimes require to complete them map, since mapmakers rely on this.) By which I mean it isn't limited to cases where the collision box leaves the origin node. It's just that these cases make the 'error' more apparent, since it allows you to chain the effect.

Personally I don't consider this behavior problematic, just a quirk of the minetest engine to be aware of.

**Comment by fluxionary** [comment] 2022-08-06 14:12
> I made an (unreleased (yet)) mod which uses it to add a transportation method where the cost scales linearly with the distance traveled.

the engine anticheat code ("moved_too_fast") prevents you from traveling too far using this glitch. however, the anticheat can be disabled (https://github.com/minetest/minetest/blob/4fbcc33ee08e521015529ba4f494fc9cff771ebb/builtin/settingtypes.txt#L663-L664).

**Comment by Skamiz** [comment] 2022-08-06 19:30
Ahh, that's too bad. Though not the part I am all that worried about since the behavior can be easily replicated with a global step. I mostly liked it for being an unintentional feature. (Maybe somewhat related bug/feature: If you place the collision box just right, above the actual node, you can create a surface which is only traversible by constant jumping, otherwise you sink through the floor.)

More concerning to me is that the fix for this might alter the behavior of sneak snapping even if the collision doesn't leave the origin node, which could break a lot of jump'n'runs. (Not that Minetest has all that many of these admittedly.)
On the other hand it might open new opportunities?

Eh, what happens, happens. Just gotta beat the current map I am playing before that point.

**Closed** 2022-10-17 11:56 UTC
Labels: Bug, @ Server / Client / Env.
