### ISSUE TITLE
[Bug] Worsening of sneak glitch bug

### ISSUE THREAD

**Issue by Rui-Minetest** [minetest/minetest#3087] opened 2015-08-20 21:08 UTC
http://youtu.be/zGVkKNbXBBc

**Comment by JohnWayne1986** [comment] 2015-08-20 22:28
I can confirm that. It is even simpler: If you have
Block
Air
Block
Air
Block
you can climb up with sneak and jump.

And additionally: If a block is above you while climbing up, you won't collide with it.

**Comment by Rui914** [comment] 2015-08-20 22:58
@JohnWayne1986 
I didn't collide with the block.
Perhaps, because the mapblock is not loaded (client_mapblock_limit = 1 in minetest.conf).
I'm sorry to have caused your misunderstanding...

**Comment by BlockMen** [comment] 2015-08-21 12:06
The glitching through block(s) should be fixed by #3089.

The other two described things are actually correct behavior, since it is just one node checked whether its sneakable. And since sneak_glichting is enabled by deault the search algorithm finds the node "behind" (or this 2 blocks higher). So either we can change the search and check each loop 3 to x nodes but you could still sneak_glitch on this :AIR BLOCK AIR BLOCK AIR ...  OR we disable sneak_glitching by default.

IMO its wrong to allow this behavior at all.

**Closed** 2016-11-04 13:49 UTC
Labels: @ Client / Audiovisuals, Bug
