### ISSUE TITLE
odd mouse behaviour 

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#6245] opened 2017-08-13 11:11 UTC
so for some reason my mouse is moving by it self
[here is what it looks like](https://youtu.be/hkpLn87yvZU ) 
note the straht lines of movment that happen evry now and then (and before you ask no my mouse is not broken it works fine in other games)

my specs
My operating system is windows 10 
model: predator G3-710
processor: intel(R) Core(TM) i7-6700 CPU @ 3,40GHz 3,40
RAM memory 16,0 GB
system type 64-bits operatigsystem, x64-processor
I'm using minetest 0.4.16
And cinematic mode is off

**Comment by rubenwardy** [comment] 2017-08-13 11:14
Which version of Minetest are you using? Is cinematic mode on?

**Comment by tobyplowy** [comment] 2017-08-13 11:19
@rubenwardy I'm using minetest 0.4.16
No cinematic mode is off

**Comment by Fixer-007** [comment] 2017-08-13 11:45
Are you in fullscreen mode? Show your config.

**Comment by tobyplowy** [comment] 2017-08-13 12:12
> Are you in fullscreen mode?

no im using windowed mode

im not sure if this is the file you need but it may be
[config.zip](https://github.com/minetest/minetest/files/1220440/config.zip)

**Comment by paramat** [comment] 2017-08-14 10:22
Do you mean a constant slow drift when you are not moving the mouse? This is a known issue, it happened to me once, i think it's caused by a hardware setting.

**Comment by paramat** [comment] 2017-08-14 10:25
See #4287

**Comment by tobyplowy** [comment] 2017-08-14 11:04
> Do you mean a constant slow drift when you are not moving the mouse? 

Yes

> See #4287 

So my issue is a duplicate?
Also it doesn't seem to be fixed XD

**Comment by paramat** [comment] 2017-08-14 11:34
Try altering your screen DPI setting.

**Comment by tobyplowy** [comment] 2017-08-14 11:42
@paramat yes that fixes it :)

But I think that fix needs to be standard in the Mt engine

**Comment by paramat** [comment] 2017-08-14 12:09
There was a PR merged, otherwise your DPI is nothing to do with MT.

**Closed by paramat** 2017-08-14 12:09 UTC
