### ISSUE TITLE
Feature request: Implement LOD

### ISSUE THREAD

**Issue by TristanCottam** [minetest/minetest#14502] opened 2024-03-28 21:50 UTC
### Problem

Increasing the viewing range greatly impacts frame rate, preventing players from enjoying views of far-reaching landscapes.

### Solutions

Implementing **LOD** _(Level Of Detail)_ would allow greatly increasing the viewing range while keeping the impact on frame rate minimal.

### Alternatives

Endure the lag.

### Additional context

I'm unsure if this feature request should rather be made to [minetest/irrlicht](https://github.com/minetest/irrlicht).

I don't have any experience in developing Minetest, but I'd gladly give it a try. Any hints and tips would be greatly appreciated!

**Comment by SmallJoker** [comment] 2024-03-29 08:08
Duplicate of #13087
which is a duplicate of #6607

Closely related: #10647

**Closed by SmallJoker** 2024-03-29 08:08 UTC
Labels: Feature request, @ Client rendering

**Comment by TristanCottam** [comment] 2024-03-29 12:52
I saw all those issues, however:
- #13087 was deemed to be of "low quality" (for being too vague).
- #6607 only tackles distant plant rendering.
- #10647 only tackles "texture" LOD (if I understand correctly).

To be clear, this issue tackles "mesh" LOD, [as described in this Wikipedia article](https://en.wikipedia.org/wiki/Level_of_detail_(computer_graphics)). Am I right in thinking this type of LOD hasn't been clearly requested in any previous issue?

**Comment by lhofhansl** [comment] 2024-03-30 22:31
In the past we really did not look into this much because usually it would take too long anyway to transfer blocks from the server to the client. There was an attempt at "farmap", which got abandoned (#3502 and #12690).

But, in the meanwhile we tackled low-hanging fruit: #5320 (with some followups such as #13133), that reduce server work for blocks the client cannot see.
On the client we did #13133 (and its generalization: #13179).

This is all to say. A viewing_range of 1000 is already doable on medium H/W (30-60 FPS on my 5yo Laptop).
And... I think we are ready to finally tackle LOD (mesh and texture). Obviously this is not a trivial change.
