### ISSUE TITLE
Emission maps

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#9495] opened 2020-03-09 23:52 UTC
I propose adding emission maps to entities and nodes
It would work something like adding an overlay texture that has no darkening effect due to light.

Maybe draw it over the texture darkener?
Literal emission?
```lua
emission_map = {
    "default_mineral_mese.png",
}
```

**Comment by Df458** [comment] 2020-03-10 00:23
I wholeheartedly support something like this, though I think this issue might be a duplicate of #9075?

**Comment by paramat** [comment] 2020-03-10 00:24
Yes it is.

**Closed by paramat** 2020-03-10 00:24 UTC
Labels: @ Client / Audiovisuals, Duplicate, Feature request
