### ISSUE TITLE
Allow mods to temporarily change key-bindings while inside formspecs

### ISSUE THREAD

**Issue by herbert-west2** [minetest/minetest#12878] opened 2022-10-19 19:10 UTC
A place where this would be useful, for example, is in the MineClone2 game, where in order to accurately represent the behavior of MC the shift key should craft an entire stack when held down in the crafting area.

**Comment by SmallJoker** [comment] 2022-10-19 19:14
Duplicate of #11392 and #12488

**Closed by SmallJoker** 2022-10-19 19:14 UTC
Labels: @ Script API, Feature request, @ Client / Controls / Input, Formspec

**Comment by herbert-west2** [comment] 2022-10-19 19:52
My apologies, I saw those but they were very hard to read so I wasn't sure what they were saying
