### ISSUE TITLE
20 feb 2016 commits caused regression with walking near/on nodeboxes

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3767] opened 2016-02-23 00:42 UTC
Examples: 
* walking near cottages:fence_small will make you half-jump repeatedly
* mesecons_pressureplates:pressure_plate_stone_off - when walking off it you will hear fast jittery walk sound

To test this you can go to "Liberty Land" server to -202 17 -8 and -201 22 -9 (second floor). 
This bug happens only on some nodeboxes.

Requesting @ShadowNinja or @nerzhul

**Comment by est31** [comment] 2016-02-23 00:45
yeey I knew it that code must not be touched. if you do, you introduce a bug.

probably caused by 60dc01dc258db842e229351b871d0989e3e7d62c

**Comment by paramat** [comment] 2016-02-23 12:58
Also i must test continuous running up stairs isn't broken.

**Comment by paramat** [comment] 2016-02-27 18:11
Please test #3796

**Comment by paramat** [comment] 2016-02-27 19:57
https://github.com/minetest/minetest/commit/60dc01dc258db842e229351b871d0989e3e7d62c will be reverted soon.

**Comment by kilbith** [comment] 2016-02-28 08:43
> 60dc01d will be reverted soon.

What are you waiting then ? It roughly takes 30s...

```
git stash
git revert 60dc01d
git push
```

**Comment by nerzhul** [comment] 2016-03-01 10:20
Fixed by reverting

**Closed by nerzhul** 2016-03-01 10:20 UTC
Labels: @ Server / Client / Env., bug
