### ISSUE TITLE
Some realistic shaders for minetest ?

### ISSUE THREAD

**Issue by TNZ9** [minetest/minetest#9539] opened 2020-03-23 10:30 UTC
Hello, I've played minetest since a few months, the game itself is very good but there is a thing making me jealous of minecraft, it's the graphics quality. 
I've seen some minecraft GLSL shaders demos and it's just incredible compared with minetest quality.
I know that mintest also supports GLSL shaders but i didn't ever find any shaders pack for minetest.
So I'd like to know : 
- Are there some minetest shaders packs which look as good as the minecraft ones ?
- If there isn't any shaders pack for minetest, is there a way to import minecraft ones into minetest ?

**Comment by SmallJoker** [comment] 2020-03-23 16:50
There's no such thing as "shader packs". Shaders are provided as built-in content and can be found [here: client/shaders/](https://github.com/minetest/minetest/tree/master/client/shaders).
Porting shaders to Minetest would be possible to degree, but I believe most would need more information provided by the Minetest engine to render everything as intended.

**Comment by TNZ9** [comment] 2020-03-23 20:12
Ok, thank you, I'll probabbly try to learn from minetest shaders and write new ones

**Comment by TNZ9** [comment] 2020-03-23 20:13
But if you could provide me some info about how I should integrate some shaders to minetest, it would be a huge help.

**Comment by paramat** [comment] 2020-03-23 22:33
Yeah, it is better to write new shaders dedicated to MT than try to port from elsewhere.

There is already a lot of discussion and information about shaders in this repository's issues and PRs, i suggest searching and reading to learn more.
We can answer very specific questions but have no time for general shader tutoring, so it is down to you to research and learn =)

**Comment by TNZ9** [comment] 2020-03-24 08:06
Yes, I'll pick some infos in she shaders issues to learn the shaders integration. (and maybe have a time to learn GLSL, it would be a good start point :smile:  )
Thank you for this idea, I didn't think to do it.

**Comment by appgurueu** [comment] 2020-03-28 21:20
It's relatively easy to tweak the shaders, and you can get quite aesthetically pleasing results. The more impressive results, however, would most likely require changes in the rendering pipeline.

**Comment by paramat** [comment] 2020-03-29 23:00
Questions answered so closing.

**Closed by paramat** 2020-03-29 23:00 UTC
Labels: @ Client / Audiovisuals, Question, Shaders

**Comment by Ygarr** [comment] 2021-06-10 18:03
Please add some resources
