### ISSUE TITLE
Some number keys still not working

### ISSUE THREAD

**Issue by edricus** [minetest/minetest#8224] opened 2019-02-12 10:47 UTC
##### Issue type
 - Bug report
 
##### Minetest version
```
Minetest 0.4.17.1 (Linux)
Using Irrlicht 1.8.4
Build info: VER=0.4.17.1 BUILD_TYPE=Release RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1
```
##### OS / Hardware
Operating system: Archlinux, Linux 4.20.7
CPU: Intel Core i7-4720HQ

##### Summary
issue https://forum.minetest.net/viewtopic.php?id=3792 still not fixed. Azerty keyboard, can't input the number 7 for exemple

##### Steps to reproduce
Set the keymap to fr_FR.UTF-8 and try to input a "7" in a field (world name for exemple)

**Comment by SmallJoker** [comment] 2019-02-16 10:42
Duplicate of #3170

**Closed by SmallJoker** 2019-02-16 10:42 UTC
Labels: @ Client / Controls / Input, Bug
