### ISSUE TITLE
Nodes can be registered after startup

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#13591] opened 2023-06-13 18:36 UTC
##### Minetest version
```
Minetest 5.8.0-dev-c91182e1b (Linux)
```

##### OS / Hardware
Operating system: Linux
CPU: Ryzen

##### Summary
A node can be registered after startup has finished. The client will treat it as unknown, but the server seems to handle it like a properly registered node: timers are run, lighting is updated, etc.

##### Steps to reproduce
Create a mod like:
```lua
minetest.after(4, function()
	local gcn = minetest.get_current_modname
	minetest.get_current_modname = function()
		return "wtf"
	end
	minetest.register_node("wtf:stone", {
		description = ("WTF Stone"),
		tiles = {"default_stone.png"},
		groups = {cracky = 3, stone = 1},
		drop = "basenodes:stone",
		paramtype = "light",
		light_source = 12,
		on_timer = function(pos, elapsed)
			minetest.set_node(pos, {name="basenodes:stone"})
		end,
	})
	minetest.get_current_modname = gcn
	local pos = {x=128, y=16, z=128}
	minetest.set_node(pos, {name="wtf:stone"})
	minetest.get_node_timer(pos):set(3, 0)
end)
```
Add it to a devtest world.
Observe that an “unknown” node appears shortly after game start at the given position. And shortly after that, it is replaced with stone.
Try `/giveme wtf:stone 99`, observe that it works, giving “unknown” items. Try placing these items, observe that they are placed and light up the surrounding area.

**Comment by numberZero** [comment] 2023-06-13 18:45
#### Background

I wanted to make sure `registered_nodes` is finalized (read-only) by the time `on_mods_loaded` is run. Apparently it isn’t.

**Comment by Desour** [comment] 2023-06-13 18:54
Duplicate of #13496.

**Closed by Desour** 2023-06-13 18:54 UTC
Labels: Unconfirmed bug
