### ISSUE TITLE
dynamic texture-strings filling up memory

### ISSUE THREAD

**Issue by ninnghazad** [minetest/minetest#3806] opened 2016-03-02 13:12 UTC
When creating combined textures on the fly and reassigning texture-strings in rapid succession,
memory-usage climbs endlessly. 
This happens for example when using digiline:lcd (or dronetest:display), as it uses the technique above.
I think this is because the old generated texture data doesn't get removed - i don't mean the source-images used in the combined texture. 
TextureSource::m_name_to_id and m_textureinfo_cache get filled up it seems, and i can't see a way to remove unwanted textures from these within the modding-api as of now. 
Also it seems the way ids are generated from m_textureinfo_cache somewhat prevents from really removing stuff from it (it's a vector).
Maybe a way to set the name string to id-as-a-string for both would suffice - as it seems the string is what actually uses most of the memory in this case. "" wouldn't do cause m_name_to_id is a map, hence "id". But that would be rather ugly, reducing the problem without solving it.
Ideas?

I know this isn't new and some people seem to know about it (or so the IRC logs say), but as it is still an issue...

**Comment by rubenwardy** [comment] 2023-12-11 17:58
Duplicate of #11531

**Closed by rubenwardy** 2023-12-11 17:58 UTC
Labels: Bug, @ Client / Audiovisuals, Feature request
