### ISSUE TITLE
item/wielditem entities shaded incorrectly

### ISSUE THREAD

**Issue by deltanedas** [minetest/minetest#10765] opened 2020-12-31 08:27 UTC
##### Minetest version
```
dev 9250b5205
```

##### OS / Hardware
Operating system: GNU/Linux
CPU: Intel Core 2 Duo P8400

GPU model: Intel HD 4000
OpenGL version: 2.1

##### Summary
Entities using the `wielditem` visual (from [my covers mod](https://gitgud.io/deltanedas/covers)) are too dark at night, using torches for light.
![Screenshot_08:18:17](https://user-images.githubusercontent.com/39013340/103401532-1576d980-4b41-11eb-9dcc-85bf56d6c5a3.png)

Lighting boost, etc. options are not used.

##### Steps to reproduce
1. set time to night
2. place a torch
3. place some covers over blocks and see how they're visibly darker

**Comment by DeltaNedas** [comment] 2020-12-31 16:34
also occurs with `visual = "item"` entities

**Comment by appgurueu** [comment] 2021-01-08 20:45
Possibly caused by #9374

**Comment by dcbrwn** [comment] 2021-02-15 16:09
If it still reproduces and nobody is working on this, I can take a look. Probably shaders need some tuning.

@DeltaNedas what was the previous version of MT that you used as a reference?

**Comment by DeltaNedas** [comment] 2021-02-17 07:09
@dcbrwn 5.3.0-dev

**Comment by dcbrwn** [comment] 2021-03-08 13:14
Sorry for the delay. I tried messing around with shaders but without any luck. Lighting in object_shader doesn't take torch colors into account and only depends on scalar light level, contrary to nodes_shader. Changing this may result in another unwelcome breaking change. We need help of someone more familiar of how lighting works in minetest.

I tried reproducing this in 5.3.0 and it looks the same. In 5.2.0, oddly enough, covers actually rendered black. Probably because I had to downgrade the mod too.

5.5.0, 5.3.0 https://snipboard.io/8lTK7s.jpg
5.2.0 https://snipboard.io/hc0Oxv.jpg

**Comment by Zughy** [comment] 2022-06-17 18:23
![imagen](https://user-images.githubusercontent.com/63455151/174356010-2779bec0-bb7f-40bd-9913-32071d0b1d00.png)

![imagen](https://user-images.githubusercontent.com/63455151/174355994-02c725c8-5366-4b66-ba0e-850845ab1176.png)

@deltanedas you mean the one on the left?

**Comment by Zughy** [comment] 2022-06-19 10:31
Actually, everything seems fine

![imagen](https://user-images.githubusercontent.com/63455151/174476678-ea7cb4b0-7d60-45a6-b86c-e79dface1695.png)

**Comment by appgurueu** [comment] 2022-06-19 14:21
Potentially fixed by https://github.com/minetest/minetest/commit/e92a217bd19ee0b28890a7b33e5c6d7c037354cc

**Comment by sfan5** [comment] 2022-06-19 14:34
Unlikely.

**Closed** 2022-07-24 16:50 UTC
Labels: Unconfirmed bug, @ Client / Audiovisuals, Possible close
