### ISSUE TITLE
Sanitise world directory names and store full name elsewhere

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4875] opened 2016-12-09 22:48 UTC
Tested in 0.4.14 on GNU/Linux.

When you create a new world, and the world name has a slash anywhere in its name, the world is not created correctly. It seems that no world is created after clicking on “create”.

E.g. if you enter “v/test”, Minetest will not create a world called “v/test”.
I noticed that behind the scenes, in `worlds` Minetest creates the directory `v` which in turn contains `test`. As if Minetest interprets the user input as a directory tree.

I suspect the issue may be similar on Windows, but with a backslash instead of a slash. This is not tested.

I see two possible fixes:

* Somehow escape these characters in the world directory name
* Forbid to use this characters in world names

**Comment by juhdanad** [comment] 2016-12-09 23:41
I don't think anyone would complain if Minetest forbade slashes in world names.

**Comment by paramat** [comment] 2016-12-10 00:16
Yes slashes should obviously be disallowed.

**Comment by Wuzzy2** [comment] 2016-12-10 09:39
Yeah, I don't care if slashes and backslashes are ruled out.
But the issue is a bug then because now Minetest allows you to create worlds which don't appear in the world list. Very confusing.

Also needs to be tested on Windows because of backslashes.

**Comment by bigfoot547** [comment] 2016-12-10 21:22
`..` also puts the world a directory back.
e.g. `~/.minetest/<world>`

**Comment by SmallJoker** [comment] 2016-12-11 10:27
Hehe, funny bug. Let's generate worlds everywhere :)
But right, these characters should be either disallowed, trimmed or replaced with an underscore.

**Comment by Wuzzy2** [comment] 2016-12-11 10:38
I think just stripping characters might be not enough.
Minetest should be 100% certain that a world directory can ONLY end up in `worlds` and nowhere else, no matter what the user entered. I suspect there might be more checks neccessary.

**Comment by C1ffisme** [comment] 2016-12-11 18:46
(Game who's name must not be spoken) does this by saving the actual name of the world in the settings of the world, and replacing bad characters in the name with underscores. That way you can still name your world: "Testing things / Screenshots". Or maybe some form of ASCII art: `/\/\y <ool \/\/orld.`

**Comment by rubenwardy** [comment] 2016-12-11 20:08
I agree with above approach. It also allows them to use unicode the name

**Comment by Wuzzy2** [comment] 2016-12-11 22:18
C1ffisme's approach doesn't work. The approach breaks when you add two worlds for which their names only differ at one character which is also “bad”. Example:

* “Hello/World”
* “Hello\World”

The first world will create directory “Hello_World”. The creation of the second world will fail since the folder name will also be “Hello_World” which is already taken.

**Comment by rubenwardy** [comment] 2016-12-11 22:19
Hello_World2

**Comment by Wuzzy2** [comment] 2016-12-11 23:05
OK, this modification makes the approach legit. :-)

**Comment by dsohler** [comment] 2016-12-18 22:14
> Hehe, funny bug. Let's generate worlds everywhere :)

I don’t think it’s funny. It’s a very stupid and avoidable [Bobby Tables situation](https://xkcd.com/327/). Simply sanitizing user input everywhere. No matter how hypothetical the expoit might be.

**Comment by red-001** [comment] 2016-12-24 12:14
well that wouldn't be as simple as it seems. See https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

**Comment by dsohler** [comment] 2016-12-26 13:17
To avoid creating an illegal name by using “N-U-L” (and others) as name that would be sanitized to `NUL` we could add `world_` as a prefix by default so it would be `world_NUL` (and `world_NUL_2` for “N\U/L” as a second world name).

**Comment by beyondlimits** [comment] 2016-12-26 21:26
Creating a world:
- Keep letters and digits; replace everything else with underscore.
- When creation fails, try adding digit to the end of name. For example if creating directory `myworld` fails, try creating `myworld1`, then `myworld2` etc. Count up to 100 and when still no success, notify user about the problem.
- Keep real name (that is to be displayed) within `map_meta.txt`.

Obtaining a name from existing world:
- If there is a name within map_meta.php, display it; otherwise display directory name.

**Comment by dsohler** [comment] 2016-12-27 15:32
@beyondlimits the problem is that you actually can create a folder or file named `NUL` in Windows (at least when I tested it the last time in Windows 7). It's only the GUI that denies it. So you would still run into issues when the name and the sanitizing ends up in `NUL` (o any of the other forbidden names).

As far as I understand `map_meta.txt` isn’t exactly for storing actual metadata about the world but more like for technical information for the map generator.  `world.mt` already contains metadata (game ID, creative mode, etc.) so storing the world name there would be the better solution.

**Comment by bigfoot547** [comment] 2016-12-28 00:03
@dsohler :+1: 
But.... What is the name of the folder going to be?

**Comment by red-001** [comment] 2016-12-28 11:06
see #4962

**Comment by beyondlimits** [comment] 2016-12-28 11:42
@dsohler more details please about how you created `NUL` directory.

The problem that Windows won't let you create directory called `NUL`, `CON`, `AUX` and a bunch of other special names is just a matter of some stupid backward compatibility with very old applications. Neither I care nor I have found any program that would take it into account.

Within Windows shell `mkdir NUL` simply doesn't work, `mkdir NUL\.` works but without easy way to access the directory.

Some test: http://kopy.io/KbptS

**Comment by red-001** [comment] 2016-12-28 12:08
you can make it using `mkdir \\.\c:\nul`

**Comment by dsohler** [comment] 2016-12-28 13:28
Can’t test right now because I don’t have any Windows machines available but if I remember correctly I was able to create a file `NUL` by creating `foo.txt` and then renaming it to `NUL` on command line while renaming on GUI was refused by Windows.

**Comment by red-001** [comment] 2017-01-17 16:19
related: #5059

**Comment by rubenwardy** [comment] 2018-07-26 14:18
duplicate of #3588

**Comment by paramat** [comment] 2020-05-06 23:06
For me it seems better and simpler to just refuse a non-compliant world name in main menu and display a message of explanation. No need to store the display name, avoids duplicates, as well as teaching users how to properly name their worlds and so avoid repeating the problem.

**Comment by SmallJoker** [comment] 2020-07-28 17:17
#9432

**Closed by SmallJoker** 2020-07-28 17:17 UTC
Labels: Bug
