### ISSUE TITLE
[Request] Improve EnvArgsEnd errors

### ISSUE THREAD

**Issue by Ryan-Nolan** [minetest/minetest#2663] opened 2015-05-02 12:31 UTC
Instead of an error being thrown when the EnvArgsEnd is missing:
https://github.com/minetest/minetest/blob/master/src/environment.cpp#L532

Why not just have minetest reset the file?

Not sure if this has already been looked at before, but for such a simple error i cant see any reason why this hasnt been done already.

**Comment by PilzAdam** [comment] 2015-05-03 16:38
Silently recreating files when they are corrupted is not a good idea.

**Comment by est31** [comment] 2015-05-03 16:54
Perhaps a nicer error message? `This is likely caused by the file m_path_world + DIR_DELIM "env_meta.txt" being corrupted.`

**Comment by crazyR14** [comment] 2015-05-03 17:20
We all know what the cause is and those that don't can find the reason and solution on the wiki. My issue is this inly really happens when the server isn't shut down properly... But then having to mess about to fix something so simple and with very little importance seems to be daft. I don't see nothing wrong with "auto fixing" this paticicular file. 

@PilzAdam I can see your point but with this particular file it has only 3 lines with information that actually probably doesn't need saving anyhow. I can not see why could go wrong with auto fixing it. As for silently. Doesn't need to be silently. jus add a message to explain that I was corrupt but has been fixed.

**Comment by rubenwardy** [comment] 2015-05-04 15:04
@crazyR14 the file contains game_time which is the number of seconds since the world was created. This is needed in several parts of the logic.

YvesLevier is receiving problems where the env_meta.txt appears to be completely correct, but there is still that message.

http://paste.ubuntu.com/10984514/
http://paste.ubuntu.com/10984752/

**Comment by crazyR14** [comment] 2015-05-04 18:29
@rubenwardy that is correct. but the `time_of_day` i dont think needs to be stored in file though, and as for `game_time` the fix for the file corruption ruins the logic becasue the wiki clearly states that the numbers do not matter. so maybe a better more reliable way of storing it is needed?

**Comment by rubenwardy** [comment] 2015-05-05 08:24
> A player called YvesLevier is receiving problems where the env_meta.txt appears to be completely correct, but there is still that message.

Turns out that they failed to mention that they linked the env_meta.txt file to another location, but didn't do it properly - the file was blank. What a waste of time.

**Comment by Splizard** [comment] 2016-02-03 03:58
Crashing the server because it can't read the time from a file is ridiculous, from an end user perspective if they force closed the server and the file ended up blank (this has happened to me) the server should not crash. It should instead try and overwrite the file or ignore it and reset the time.

**Comment by Splizard** [comment] 2016-02-03 04:12
Something like this would be good..

[Uploading 0001-Fix-2663.patch.txt…]()

**Comment by 0-afflatus** [comment] 2016-02-17 10:45
I generally end up copying the env_meta.txt over from the last backup, which messes up the age of the world. Is that better than auto-fixing it? I don't know.

**Comment by Ryan-Nolan** [comment] 2016-04-28 18:02
How about seen as this is one of the few files that often end up corrupted. 

have the saving system for it making a backup of it before saving so simply copying it to: env_meta.txt.back

then make it so that if the game finds a corrupt original it replaces the original with the backup....  ??

^the possibility of the above would all depend on how often minetest writes to env_meta.txt. Does anyone know?

**Comment by paramat** [comment] 2018-05-16 01:06
Any core dev support?

**Comment by Ryan-Nolan** [comment] 2018-05-16 10:28
So this is fixed then? with the possible close tag being added?

**Comment by paramat** [comment] 2018-05-16 17:19
Maybe i misunderstand but is this a bug? It seems a request for a different behaviour in response to a corrupted file, and seems a little controversial from the comments. Current behaviour is correct it seems (just maybe not ideal)?
What are core dev thoughts?

**Comment by rubenwardy** [comment] 2018-05-16 17:20
Surely the correct fix is to stop this from happening?

Does this even happen any more with safeWriteToFile?

**Comment by sfan5** [comment] 2018-05-16 17:42
`safeWriteToFile` is used for writing map_meta since 2013:
https://github.com/minetest/minetest/commit/d718b0b34eda84744778fa12a01d5be5f03753d3#diff-baa4d2d0ffafdec2b86baf065fba252bR592

**Comment by Fixer-007** [comment] 2018-05-21 16:00
Still happens, for example when sudden loss of electricity

**Comment by paramat** [comment] 2018-06-16 14:07
@Ryan-Nolan any test results? This might be closed in 4 days otherwise.

**Comment by Ryan-Nolan** [comment] 2018-06-19 13:35
Sorry @paramat i havent had the time to test it, but @Fixer-007 claims that this bug still exists.

**Comment by SmallJoker** [comment] 2018-06-19 13:47
Neither sqlite nor any other database is safe from sudden power outdate. If only that is left over as an issue, then this here can be closed.

**Comment by sfan5** [comment] 2018-06-19 18:43
Actually, every decent database is [ACID](https://en.wikipedia.org/wiki/ACID)-compliant, meaning it retains file consistency **even** when power is suddenly lost.
The `rename` call in safeWriteToFile is similarily atomic, if the file ends up corrupted you can only blame your OS.

In any case this issue is fine to close.

**Closed by sfan5** 2018-06-19 18:43 UTC
Labels: Bug, Possible close, Request / Suggestion

**Comment by Ryan-Nolan** [comment] 2018-06-19 21:53
This will be my last reply on this topic but further up in this discussion I'm sure it was mentioned that one idea would be for the system to create a backup of the file before writing to the actual file. that way if the actual file does get corrupt the data can still be retrieved. Anyhow ive said my peace :)
