### ISSUE TITLE
nill value error (/misc_helpers.lua:717)

### ISSUE THREAD

**Issue by aerozoic** [minetest/minetest#6789] opened 2017-12-14 23:58 UTC
Server is running 4.16 stable on freeBSD 11.1 and here is the repo for the server: https://github.com/UGXaero/UGXrealms if needed.

IDK specifically what caused this:

```
2017-12-14 20:20:51: ACTION[Server]: HALINA digs stairs:slab_silver_sandstone at (-9949,26,7638)
2017-12-14 20:20:57: ACTION[Main]: [playereffects] Server shuts down. Rescuing data into playereffects.mt
2017-12-14 20:20:57: ACTION[Main]: IRC: Disconnected.
2017-12-14 20:20:57: ACTION[Server]: HALINA leaves game. List of players: 
2017-12-14 20:20:57: ACTION[Server]: nghia leaves game. List of players: 
2017-12-14 20:20:57: ACTION[Server]: xraulx leaves game. List of players: 
2017-12-14 20:20:57: ACTION[Server]: XxestuarcraftxX leaves game. List of players: 
2017-12-14 20:20:57: ACTION[Server]: SirAlexRuiz leaves game. List of players: 
2017-12-14 20:20:59: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'stairs' in callback item_OnPlace(): /usr/local/share/minetest/builtin/common/misc_helpers.lua:717: attempt to perform arithmetic on a nil value
2017-12-14 20:20:59: ERROR[Main]: Stack Traceback
2017-12-14 20:20:59: ERROR[Main]: ===============
2017-12-14 20:20:59: ERROR[Main]: (2) Lua field 'pointed_thing_to_face_pos' at file '/usr/local/share/minetest/builtin/common/misc_helpers.lua:717'
2017-12-14 20:20:59: ERROR[Main]: 	Local variables:
2017-12-14 20:20:59: ERROR[Main]: 	 placer = userdata: 0x00ee3698
2017-12-14 20:20:59: ERROR[Main]: 	 pointed_thing = table: 0x01a65678  {type:node, above:table: 0x01a65768, under:table: 0x01a656a0}
2017-12-14 20:20:59: ERROR[Main]: 	 eye_offset_first = table: 0x01a65980  {y:0, x:0, z:0}
2017-12-14 20:20:59: ERROR[Main]: 	 node_pos = table: 0x01a656a0  {y:26, x:-9948, z:7638}
2017-12-14 20:20:59: ERROR[Main]: 	 camera_pos = table: 0x01a65aa0  {y:24.121999740601, x:-9948.0546875, z:7638.46875}
2017-12-14 20:20:59: ERROR[Main]: 	 pos_off = table: 0x01a65bc0  {y:0, x:0, z:0}
2017-12-14 20:20:59: ERROR[Main]: 	 look_dir = table: 0x01a65c50  {y:0.47101190686226, x:-0.50647139549255, z:-0.72224271297455}
2017-12-14 20:20:59: ERROR[Main]: 	 offset = nil
2017-12-14 20:20:59: ERROR[Main]: 	 nc = nil
2017-12-14 20:20:59: ERROR[Main]: 	 oc = table: 0x01a65ce0  {1:y, 2:x, 3:z}
2017-12-14 20:20:59: ERROR[Main]: 	 (*temporary) = table: 0x01a65d08  {}
2017-12-14 20:20:59: ERROR[Main]: 	 (*temporary) = nil
2017-12-14 20:20:59: ERROR[Main]: 	 (*temporary) = number: nan
2017-12-14 20:20:59: ERROR[Main]: 	 (*temporary) = string: "z"
2017-12-14 20:20:59: ERROR[Main]: 	 (*temporary) = number: 0
2017-12-14 20:20:59: ERROR[Main]: 	 (*temporary) = number: 3
2017-12-14 20:20:59: ERROR[Main]: 	 (*temporary) = number: nan
2017-12-14 20:20:59: ERROR[Main]: 	 (*temporary) = string: "jump"
2017-12-14 20:20:59: ERROR[Main]: 	 (*temporary) = boolean: false
2017-12-14 20:20:59: ERROR[Main]: 	 (*temporary) = string: "attempt to perform arithmetic on a nil value"
2017-12-14 20:20:59: ERROR[Main]: (3) Lua function 'rotate' at file '/home/UGX/.minetest/games/UGXrealms/mods/minetest_game/stairs/init.lua:30' (best guess)
2017-12-14 20:20:59: ERROR[Main]: 	Local variables:
2017-12-14 20:20:59: ERROR[Main]: 	 itemstack = userdata: 0x01a65668
2017-12-14 20:20:59: ERROR[Main]: 	 placer = userdata: 0x00ee3698
2017-12-14 20:20:59: ERROR[Main]: 	 pointed_thing = table: 0x01a65678  {type:node, above:table: 0x01a65768, under:table: 0x01a656a0}
2017-12-14 20:20:59: ERROR[Main]: 	 p0 = table: 0x01a656a0  {y:26, x:-9948, z:7638}
2017-12-14 20:20:59: ERROR[Main]: 	 p1 = table: 0x01a65768  {y:26, x:-9948, z:7638}
2017-12-14 20:20:59: ERROR[Main]: 	 param2 = number: 2
2017-12-14 20:20:59: ERROR[Main]: 	 placer_pos = table: 0x01a65860  {y:24.121999740601, x:-9948.0546875, z:7638.46875}


-------------
  Separator
-------------
```
:large_orange_diamond:

**Comment by paramat** [comment] 2017-12-15 00:00
Duplicate of #6643

**Closed by paramat** 2017-12-15 00:00 UTC
Labels: Bug, Duplicate
