### ISSUE TITLE
Settings menu: Tooltip for game setting with same name is identical for all games

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#13933] opened 2023-10-26 23:49 UTC
### Minetest version

```true
5.8.0-dev-2ce14ce4e
```

### Active renderer

OpenGL 4.5

### Irrlicht device

X11

### Operating system and version

Parabola

### OpenGL version

4.5

### Summary

If you have multiple games installed that use the same setting name in settingtypes.txt, the tooltip of this setting in the settings menu will always be the same for all games, even if settingtypes.txt clearly differs.

### Steps to reproduce

Generic steps:

1. Have two games installed or create them by hand
2. Make sure there is a setting in the settingtypes.txt of both games with the same name, but with a different tooltip
3. Go to the settings menu and enter the setting name in search and press Enter
4. Go through all the games and read the tooltip of the setting you test

Expected: The individual tooltip for the setting appropriate to the game will show up.
Actual: The same tooltip will appear for all games (it seems from the 1st game of the list)

Specifc steps:
Same as above, but install Hades Revisited and Repixture and search for `mobs_spawn`.

**Comment by rubenwardy** [comment] 2023-10-27 00:17
This is effectively a duplicate of #13664 - these should be merged into one issue

The cause is that the new settings GUI considers the setting name to be a primary key

**Comment by rubenwardy** [comment] 2023-10-27 00:20
Duplicate of #13664   (will change to be less specific)

**Closed by rubenwardy** 2023-10-27 00:20 UTC
Labels: Unconfirmed bug
