### ISSUE TITLE
Flowing Water: Inappropriate flowing behavior in direction east

### ISSUE THREAD

**Issue by Enrikoo** [minetest/minetest#8775] opened 2019-08-10 13:47 UTC
![screenshot_20190810_152902](https://user-images.githubusercontent.com/33701012/62822573-b304ee00-bb85-11e9-88e4-32d3ae9d8200.png)

`Minetest 0.4.16 - 5.1.0`

The problem is that if I want to cover a sea, it doesnt cover as fast as it should be in all directions. In direction east the behavior of flowing water is unexpected.

I was placing water liquid on the lava sea and then I expected that I dont like the behavior of flowing water.

**Comment by paramat** [comment] 2019-08-10 18:38
Duplicate of #5802

**Closed by paramat** 2019-08-10 18:38 UTC
Labels: Unconfirmed bug
