### ISSUE TITLE
Hand glitch after teleportation

### ISSUE THREAD

**Issue by BBmine** [minetest/minetest#6135] opened 2017-07-13 22:02 UTC
I compile the latest daily build myself, and I recently noticed that when I teleport via /spawn, /tpr, or /home, my hand disappears. It flashes back when I move my mouse.

**Comment by octacian** [comment] 2017-07-13 22:52
Duplicate of #6102, which is also probably technically a duplicate of #6063.

PS: I can confirm this too :P

**Comment by lisacvuk** [comment] 2017-07-14 09:36
Mine is not a duplicate. IIRC, the original issue was closed when I reported mine.

**Comment by BBmine** [comment] 2017-07-14 11:20
@octacian really? I didn't know. I thought I had looked before I posted too :P

**Closed** 2017-07-14 17:37 UTC
Labels: @ Client / Audiovisuals, Bug, Duplicate
