### ISSUE TITLE
Change Default Font to Match UI

### ISSUE THREAD

**Issue by threehymns** [minetest/minetest#11518] opened 2021-08-06 17:44 UTC
## Issue

The current default font does not match the rest of the UI. Could we change the default font to something like [Silkscreen](https://www.fontsquirrel.com/fonts/Silkscreen)? This font has a license that allows free personal and commercial use.

## Example Screenshot

![image](https://user-images.githubusercontent.com/70611435/128550726-017803df-edcb-448a-89b3-6d984fd0328f.png)

**Comment by yw05** [comment] 2021-08-06 20:20
This font needs better coverage for sure.
![Screenshot_20210806_221751](https://user-images.githubusercontent.com/37980625/128566832-210ccd47-a322-4aa7-b8d5-25e719846331.png)

**Comment by threehymns** [comment] 2021-08-06 21:59
@yw05, I was only suggesting that as a general example. We could use any "pixel" font with good coverage.

**Comment by yw05** [comment] 2021-08-06 23:13
Then I suppose this is more or less a duplicate of #11455?

**Comment by threehymns** [comment] 2021-08-07 16:50
> Then I suppose this is more or less a duplicate of #11455?

Yes, I opened this before I realized that there was already a similar issue being discussed. This issue can be closed as long as there is already another similar issue/pull request in the works.

> This font needs better coverage for sure.

Yes, I understand the need for a font with good coverage. (It is also true that pixel/bitmap style fonts could be a problem when translating Minetest into different languages.)

**Comment by yw05** [comment] 2021-08-07 19:03
> It is also true that pixel/bitmap style fonts could be a problem when translating Minetest into different languages.

What I realized after working with Unifont (the font suggested in that PR) is with characters like these (U+1ED6 and U+1ED7) where the uppercase and lowercase letters are hardly distinguishable:
![unifont-13 0 06-1ed6](https://user-images.githubusercontent.com/37980625/128611055-68bba66d-4581-47f6-be29-ec994ab7103b.png)

**Closed** 2021-08-07 22:53 UTC
Labels: Duplicate, Feature request, Possible close
