### ISSUE TITLE
Smooth lighting regression after 2cf9014

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#6578] opened 2017-11-03 16:19 UTC
Regression in "Smooth lighting: Fix light leaking through edge-connected corners" (2cf9014)

I've noticed this weird rendering on default config with shaders or without:
![default](https://user-images.githubusercontent.com/16494741/32384221-de8b388c-c0c2-11e7-9649-3b4933f1b7c4.png)

Look to the left and center examples, there is smoothing problem between nodebox and full block, if I make it one black higher - problem is gone. Problem is not visible at daylight when smooth lighting is disabled. Ground is at Y=20.5.

**Comment by paramat** [comment] 2017-11-03 16:22
@numberZero

**Comment by Fixer-007** [comment] 2017-11-03 16:23
Faulty commit is between 4e19791c and 75320e7e.

**Comment by numberZero** [comment] 2017-11-03 16:38
75320e7 has nothing to do with lighting. But 2cf9014 might break it, applying ambient occlusion wrongly.

**Comment by Fixer-007** [comment] 2017-11-03 16:41
Can confirm regression is caused by https://github.com/minetest/minetest/commit/2cf9014160085303cda333334784ac4938edc086

**Comment by numberZero** [comment] 2017-11-03 16:49
Basically, 2cf9014 violates one important principle: there was exactly one light value at each point in the space. That’s no longer true. So, `MapblockMeshGenerator::getSmoothLightFrame` should take that into account to produce correct result.

**Comment by paramat** [comment] 2017-11-03 18:07
I can confirm this bug.

**Comment by DTA7** [comment] 2017-11-03 22:54
@numberZero Yes, you're right, it is because the ambient occlusion is calculated differently for solid and non-solid nodes.
For solid nodes, the amient_occlusion count starts at 3, and for the node itself and its 
 three "adjacent" (taxicab distance of 1 or 2) nodes in face direction, the counter is increased by 1 if the param_type is not CPT_LIGHT or if the solidness is 2. The counter is further increased by one if the node in face direction with distance 3 is obstructed or if it also fulfills this condition.
Thus, I think the ambient occlusion counter in the bottom corners of the solid node in @Fixer-007's image should be 6.
For non-solid nodes, the counter starts at 0, and is increased in the same condition for the nodes of taxicab distance 0 or 1. The other 4 nodes can be obstructed, showing the same behaviour as the possibly obstructed node for solid nodes.
This should make the counter for this corner (belonging to the stair) 5, which still triggers the ambient occlusion, but visibly weaker than for a counter of 6.
Did I count this correctly?

**Comment by numberZero** [comment] 2017-11-04 18:34
> Did I count this correctly?

I think so. The problem is that these values should be the same in such situation.

> the amient_occlusion count starts at 3

At 4 effectively, as the node itself is always solid in this code path.

There is always some difference, but it may be larger than 1: e.g. here the solid node has ambient occlusion of 6, while the non-solid one (the bottom-right one) has occlusion of 3 at the same point:
![screenshot_20171104_212116](https://user-images.githubusercontent.com/7352626/32408281-86cd585c-c1a6-11e7-8b84-80707452e75d.png)

**Comment by DTA7** [comment] 2017-11-04 19:34
@numberZero How do you suppose the ambient occlusion should be calculated? In the same way for solid nodes as for non-solid nodes?

**Comment by numberZero** [comment] 2017-11-04 20:17
Well, that may not be the best but certainly the simplest solution.

**Comment by paramat** [comment] 2017-11-14 03:07
2cf9014160085303cda333334784ac4938edc086 also causes bug #6574

**Comment by paramat** [comment] 2017-12-23 19:54
@DTA7 and/or @numberZero  please could you work on this?

**Comment by DTA7** [comment] 2017-12-23 21:26
@paramat I'll try making the calculation for ambient occlusion the same for solid and non-solid nodes.

**Comment by paramat** [comment] 2018-01-12 05:59
#6838 merged.

**Closed by paramat** 2018-01-12 05:59 UTC
Labels: @ Client / Audiovisuals, Bug
