### ISSUE TITLE
Allow Multiple Cloud Layers

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#13407] opened 2023-04-09 14:09 UTC
## Problem

Minetest is currently restricted to having only one cloud layer. You can't have multiple cloud layers at all.

## Solutions

Make it possible to define multiple cloud layers.

## Additional context

For example, someone may want their sky to look a little more realistic and earthlike, by defining multiple cloud layers at differing heights.

![Cloud Layers](https://user-images.githubusercontent.com/114245896/230777566-9ad651fc-59ba-4fa2-a134-bf10480281a5.png)

**Comment by wsor4035** [comment] 2023-04-09 20:40
duplicate of https://github.com/minetest/minetest/issues/11366

**Comment by wsor4035** [comment] 2023-04-11 00:02
this issue is for a very specific thing, the linked one is handling sky layers overall. obviously not going to list every specific use case of the proposal

**Comment by sfan5** [comment] 2023-04-11 10:18
I don't think hecks proposal includes clouds.

**Comment by Zughy** [comment] 2023-04-17 09:29
Clouds are discussed after a couple of comments though (https://github.com/minetest/minetest/issues/11366#issuecomment-864417073), I think it makes more sense to keep everything in there, since the Sky layer API is needed to create different cloud layers

**Closed by Zughy** 2023-04-17 09:29 UTC
Labels: Duplicate, Feature request
