### ISSUE TITLE
Most Lua entity data fields are lost at shutdown

### ISSUE THREAD

**Issue by Echoes91** [minetest/minetest#2547] opened 2015-03-24 10:26 UTC
As an example, arrows are Lua entities with speed, acceleration and chance to break stored inside. Across a server reboot while an arrow is flying only speed is retained, acceleration goes to 0,0,0 (the arrow goes straight) and the rest becomes nil (causing crashes). Is there a reason for it or any way to keep other (constant) values too?

**Comment by ShadowNinja** [comment] 2015-03-27 18:36
`get_staticdata()` and `on_activate(static_data)` are supposed to be used to store and set this information since not everything stored in an entity's definition is supposed to be preserved through block loads.  If the velocity is stored automatically the acceleration should probably be stored too though.

**Comment by Wuzzy2** [comment] 2015-06-26 00:40
Close this issue as “not a bug”?
Btw: Maybe the documentation needs to be clarified, it also took me some time to realize the importance of using the staticdata stuff.

**Closed** 2015-08-31 08:33 UTC
Labels: not a bug
