### ISSUE TITLE
If i try to change keys to russian layout then game crash, 0.4.13, Linux

### ISSUE THREAD

**Issue by amadin** [minetest/minetest#3341] opened 2015-11-05 07:37 UTC
If i try to change keys to russian layout then press "Save" - game crash, ALTLinux 7.0.5, 32-bit, minetest 0.4.13-dev from github.

-------------
  Separator
-------------

2015-11-05 09:13:13: WARNING[Main]: Irrlicht: Unsupported texture format
2015-11-05 09:13:42: ERROR[Main]: In thread b695b740:
2015-11-05 09:13:42: ERROR[Main]: /mnt/sda3/minetest-master-13/src/keycode.cpp:125: KeyPress::KeyPress(const char*): A fatal error occured: Unexpected multibyte character
2015-11-05 09:13:42: ERROR[Main]: Debug stacks:
2015-11-05 09:13:42: ERROR[Main]: DEBUG STACK FOR THREAD aefffb40: 
2015-11-05 09:13:42: ERROR[Main]: #0  virtual void* UpdateThread::run()
2015-11-05 09:13:42: ERROR[Main]: DEBUG STACK FOR THREAD af7ffb40: 
2015-11-05 09:13:42: ERROR[Main]: #0  virtual void* UpdateThread::run()
2015-11-05 09:13:42: ERROR[Main]: DEBUG STACK FOR THREAD b695b740: 
2015-11-05 09:13:42: ERROR[Main]: #0  int main(int, char**)

**Comment by est31** [comment] 2015-11-05 14:08
Dupe of  #2951. Please don't open multiple bug reports for the same bug, only because they appear in a new version of minetest as well.

**Closed by est31** 2015-11-05 14:08 UTC
