### ISSUE TITLE
Minetest only using one emergethread with lua mapgen

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest#4534] opened 2016-09-20 19:10 UTC
Hi there, i expected slow mapgen generation time on my local client and saw that it's only using one emergethread:

![2016-09-20-204318_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/18684637/2dda53f4-7f75-11e6-9916-cdaac7d79cfb.png)

The client is running at 7eacdc7bb8ec8f8b06b5e0b2464af219e623cd56
The mapgen is fine without mods but should it become nearly frozen just with [integral](https://github.com/duane-r/integral) and [skylands](https://github.com/HeroOfTheWinds/skylands-master)? Shouldn't Minetest take use of all the emerge threads?

Tested the same on the server where the mapgen time is "ok" so far but creates huge lag.
In this case the server thread is under heavy load, i know this is the old multithreading problem since Minetest only allows Lua for modding. In this case is moretrees, plantlib, sealife, farming by tenplus1 and darkage active. The mentioned mods above are planned for the server but they would make it unplayable if emergeblocks stays on one thread (my main point!).

![2016-09-20-205718_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/18684911/44626be2-7f76-11e6-8a7d-a471fe575179.png)

The server is also at 7eacdc7bb8ec8f8b06b5e0b2464af219e623cd56.

kind regards

**Comment by MarkuBu** [comment] 2016-09-20 20:46
Tried this once too. Didn't really work. Maybe 220% CPU usage instead of 210% on a hexacore

**Comment by Fixer-007** [comment] 2016-09-20 20:56
try disabling darkage, it caused constant heavy CPU usage for me.

**Comment by tchncs** [comment] 2016-09-20 20:58
@Fixer-007 i will not turn off darkage, it is a public server in production and darkage is a very important part for all the players!
However, my point is that emergethreads only work in _one thread_. 
This is why i created this issue.

**Comment by Fixer-007** [comment] 2016-09-20 21:41
>i will not turn off darkage

other way just to test it is create local copy of the server and run it without darkage or with it and mod profiler enabled. While I profiled last version back then it was eating cpu like crazy, I filed bug report to mod maker.

**Comment by tchncs** [comment] 2016-09-20 21:44
>other way to test is to create local copy of the server and run it without darkage or with it and mod profiler enabled. While I profiled last version back then it was eating cpu like crazy, I filed bug report to mod maker.

I did not create the issue because the busy server thread caused by mods like darkage.
I know that mods like darkage cause a higher load because the singlethreading.
The problem in this issue is that it looks like the tasks for the worldgen are not handeled by multible emergethreads like configured. The threads spawn but only one is used.

**Comment by everamzah** [comment] 2016-09-20 22:26
Works for me testing without any mods.

![4](https://cloud.githubusercontent.com/assets/1761623/18691076/a3d89c70-7f5f-11e6-96cd-3a00fd32b40c.png)
![4a](https://cloud.githubusercontent.com/assets/1761623/18691074/a3d60168-7f5f-11e6-9025-dbcfd6eed79a.png)
![4b](https://cloud.githubusercontent.com/assets/1761623/18691075/a3d6e4c0-7f5f-11e6-9108-46fc1e524216.png)

**Comment by paramat** [comment] 2016-09-21 01:12
> The mapgen is fine without mods but should it become nearly frozen just with integral and skylands? Shouldn't Minetest take use of all the emerge threads?

The Lua server is single thread, so any Lua mapgens cause a lot of Lua lag, up to 2s per generated mapchunk on a fairly fast machine (but not frozen). There is discussion about multi-threaded Lua mapgen elsewhere in another issue, it is desired and has been considered.
If you have several players rapidly exploring skylands then the Lua lag can become almost continuous. This is the big problem with using Lua mapgens on a server.

> In this case is moretrees, plantlib, sealife, farming by tenplus1 and darkage

moretrees is very slow (and creates lighting bugs) (and is not needed in non-mgv6 mapgens).
darkage code looks not good to me.

**Comment by tchncs** [comment] 2016-09-21 07:47
So i got this wrong? I thought lua mapgen is the reson for the overloaded server thread on my server and don't affect the emergethread as it was on my local client.

**Comment by paramat** [comment] 2016-09-22 03:16
> I thought lua mapgen is the reson for the overloaded server thread on my server

Correct.

> and don't affect the emergethread as it was on my local client.

I don't know if this is correct.

**Comment by paramat** [comment] 2016-12-19 07:38
> The mapgen is fine without mods but should it become nearly frozen just with integral and skylands?

Skylands alone can take 4s per mapchunk to generate on slower computers, lua mapgen occurs in the server in 'on generated', so the core mapgen cannot move on to the next mapchunk immediately, it has to wait for lua mapgen to finish.
Lua mapgen has nothing to do with emergethreads on the client, the client is just waiting for the mapblocks to be sent.

>  In this case is moretrees, plantlib, sealife, farming by tenplus1 and darkage active. The mentioned mods above are planned for the server but they would make it unplayable if emergeblocks stays on one thread (my main point!).

The slowness caused by these mods has nothing to do with emergethreads on the client.

> I did not create the issue because the busy server thread caused by mods like darkage.
I know that mods like darkage cause a higher load because the singlethreading.
The problem in this issue is that it looks like the tasks for the worldgen are not handeled by multible emergethreads like configured. The threads spawn but only one is used.

Why are you confusing the slow server with threads in the client?
"the tasks for the worldgen are not handeled by multible emergethreads like configured. The threads spawn but only one is used."
Lua mapgen is single threaded in the server, so why are you talking about the emergethreads in the client?

> If so, i don't get why emerge was busy on my local client 

This seems to be the issue here, with slow lua mapgen mods perhaps somehow one client emergethread becomes busy?

**Comment by tchncs** [comment] 2016-12-19 19:26
@paramat i guess you got me wrong:

I tested those mods on my local client first and wasn't connected to any server.

> The slowness caused by these mods has nothing to do with emergethreads on the client. Do you mean 'emergethreads' here instead of 'emergeblocks'?

Yes, sorry.

So my misunderstanding here is, that multibe emergethreads only affecting the c mapgen and mods using luamapgen stay in their own thread? I guess when i wrot this is didn't really know about this two options, but now i do :D

**Comment by paramat** [comment] 2016-12-20 03:38
> I tested those mods on my local client first and wasn't connected to any server.

Ah ok sorry i misunderstood, by 'local client' you mean singleplayer: local client plus local server. When you play locally there is still a server.
The core C++ mapgen is multithreaded, but all Lua runs in a single thread, including Lua mapgen.

So, i hope you agree, i will close this as a duplicate of #3182

**Closed by paramat** 2016-12-20 03:38 UTC
Labels: @ Client / Audiovisuals, Possible close, Unconfirmed bug
