### ISSUE TITLE
Setting player speed to 0 triggers infinite anticheat position reset

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#14790] opened 2024-06-28 07:25 UTC
### Minetest version

```true
Minetest 5.9.0-dev-e0da1296a (Windows)
```

### Summary

Setting player speed via physics overrides now triggers infinite rubber-banding due to the anticheat. Before it would just freeze player velocity.

Might be a good opportunity to make setting player speed to 0 also set their velocity to 0, or scale it accordingly somehow.

```
2024-06-28 00:21:56: ACTION[Server]: Server: LandarVargan moved too fast: V=-4.97, H=3.90151; resetting position.
2024-06-28 00:21:56: ACTION[Server]: Server: LandarVargan moved too fast: V=-6.91, H=3.90084; resetting position.
2024-06-28 00:21:56: ACTION[Server]: Server: LandarVargan moved too fast: V=-8.89, H=3.90084; resetting position.
2024-06-28 00:21:56: ACTION[Server]: Server: LandarVargan moved too fast: V=-10.15, H=3.90017; resetting position.
2024-06-28 00:21:56: ACTION[Server]: Server: LandarVargan moved too fast: V=-0.989998, H=3.90084; resetting position.
2024-06-28 00:21:56: ACTION[Server]: Server: LandarVargan moved too fast: V=-3.00999, H=3.90151; resetting position.
2024-06-28 00:21:56: ACTION[Server]: Server: LandarVargan moved too fast: V=-4.97, H=3.90084; resetting position.
2024-06-28 00:21:56: ACTION[Server]: Server: LandarVargan moved too fast: V=-6.91, H=3.90084; resetting position.
2024-06-28 00:21:56: ACTION[Server]: Server: LandarVargan moved too fast: V=-8.87, H=3.90084; resetting position.
2024-06-28 00:21:56: ACTION[Server]: Server: LandarVargan moved too fast: V=-10.16, H=3.90017; resetting position.
2024-06-28 00:21:57: ACTION[Server]: Server: LandarVargan moved too fast: V=-1.02, H=3.90084; resetting position.
2024-06-28 00:21:57: ACTION[Server]: Server: LandarVargan moved too fast: V=-2.97, H=3.90084; resetting position.
2024-06-28 00:21:57: ACTION[Server]: Server: LandarVargan moved too fast: V=-4.97, H=3.90151; resetting position.
2024-06-28 00:21:57: ACTION[Server]: Server: LandarVargan moved too fast: V=-6.91, H=3.90084; resetting position.
2024-06-28 00:21:57: ACTION[Server]: Server: LandarVargan moved too fast: V=-8.89, H=3.90084; resetting position.
2024-06-28 00:21:57: ACTION[Server]: Server: LandarVargan moved too fast: V=-10.15, H=3.90017; resetting position.
```

### Steps to reproduce

* Use this code:
```lua
minetest.register_on_joinplayer(function(player)
	minetest.after(4, function()
		player:set_physics_override({
			speed = 0
		})
	end)
end)
```
* Join the game and start jump-running.

**Comment by Zughy** [comment] 2024-06-28 10:59
Related https://github.com/minetest/minetest/pull/13796

**Comment by sfan5** [comment] 2024-07-07 20:51
Would be helpful to bisect.

**Comment by appgurueu** [comment] 2024-07-30 17:47
I'm fairly sure the problem is that our anticheat code just checks against player movement speed when it should check against velocity. A player with a speed of zero can still have either residual velocity (from the jump-running in this case) or for example `add_velocity` (fwiw, I don't see how our anticheat code would ever have worked correctly with add velocity to begin with).

What our anticheat should be doing instead is validating player velocity *changes* given player movement parameters and taking into account `add_velocity` etc. This is probably not trivial.

**Comment by sfan5** [comment] 2024-07-30 20:30
I think the problem here is not the anticheat code at all, but rather that the client physics code behaves differently than before.

**Comment by Zughy** [comment] 2024-08-19 22:20
> Before it would just freeze player velocity

It seems it's back to its previous behaviour (5.10-dev). Closing

**Closed by Zughy** 2024-08-19 22:20 UTC
Labels: Unconfirmed bug, @ Script API, Regression
