### ISSUE TITLE
item_image does not display palette coloring when palette_index is set

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest#13435] opened 2023-04-16 22:59 UTC
##### Minetest version
```
5.8.0-dev-9d736e8b8baeeacad9cfa94edd18adfcaf000029
```

##### Irrlicht version
```
1.9.0mt10-dev-c4ab49201b128bbaf4d58f00d685faa6ee3cb2c1
```

##### OS / Hardware
Operating system: linux
GPU model: nvidia Quadro T2000 Mobile
OpenGL version: OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.3.5

##### Summary
when trying to use a node w/ palette coloring w/ the `item_image[]` formspec element, the resulting image does not reflect the palette coloring. 

##### Steps to reproduce
1. get a test mod w/ images from here: https://github.com/fluxionary/minetest-item_image_bug
2. run the `/item_image_bug` chatcommand
3. you should be presented w/ the following formspec:

![image](https://user-images.githubusercontent.com/25628292/232347730-ff9506c1-9fbb-4782-8b87-2391b8615109.png)

expected behavior:
the items in the upper row should be the same color as those in the lower row.

**Comment by fluxionary** [comment] 2023-04-17 00:05
i just tested, and things work absolutely fine if i use `item_image_button` instead of `item_image`.

**Comment by v-rob** [comment] 2024-08-31 00:20
Duplicate of #10459

**Closed by v-rob** 2024-08-31 00:20 UTC
Labels: Bug, @ Script API, Formspec
