### ISSUE TITLE
Entities can get out of map boundaries (±31000)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5824] opened 2017-05-26 14:37 UTC
Currently, it is easily possible for entities to end up outside of map boundaries.

Either when the player is near the border of the world and sends an entity without collision check through.
Or an entity gets teleported there somehow (bad `setpos`).

Entities should *never* be outside of map boundaries. Players will rarely or never encounter these entities so keeping these entities is just a way.

Modders almost never consider the possibility that their entity may be *outside* of the map boundaries and do not act accordingly. And I don't think they should be required for doing so, because that would require modders to add boilerplate to *all* entities!

I suggest:
* Make sure all entities can not get outside of the map boundaries in the first place
* Figure out why non-player entities (e.g. falling nodes, dropped items) do not collide with map boundaries (see also: #2702)
* If it happens anyway, quickly destroy damage any entity outside of map boundaries.
* Both of these apply to players as well; but players get killed instead
* Entities should be destroyed regardless of `damage_enabled`

An alternative to insta-kill / insta-destroy would be causing damage (if the entity is not `immortal`)

Related issue: https://github.com/minetest/minetest/issues/2702

**Comment by paramat** [comment] 2017-05-26 16:08
By map boundaries do you mean the u16 limit for nodes, the 'max map gen limit' of 31000 or the set 'map gen limit'?

I have worked a lot on world-edge issues recently, see my PRs, there were a lot of bugs caused by the first implementation of a settable 'map gen limit' and some of these bugs were caused by trying to limit objects to within the set limit, so please be cautious with this, it's more complex than it seems.

The correct and current implementation of 'map gen limit' is that it limits mapgen and nothing else.

But yes i support work on limiting entities, if they fall out of the bottom of the world they seem to cause problems.
Apparently it is possible to go off the edge of the world in a boat too.

**Comment by paramat** [comment] 2017-05-26 16:36
Note that currently, because 'map gen limit' only limits mapgen, it is possible to generate a world with the maximum limit 31000, then reduce the limit afterwards, however in this case the world previously generated remains visible, accessible and playable.
So, limiting of entities must not be done at the 'map gen limit' setting but at MAX_MAP_GENERATION_LIMIT or the u16 node limit instead.

**Comment by Wuzzy2** [comment] 2017-05-26 20:36
Yes, I meant the boundaries in which the map generates in and actual nodes can be found.

Argh, I totally forgot that you now can arbitrarily reduce the size of the generated world. I still had the assumption that the world has fixed-size boundaries. Damn, this makes it indeed much trickier than I suggested, I agree. :D

I still think the issue is valid.

But surely entities can be destoyed safely if they are way outside of +/- 31000 for some reason. I am admittedly not so sure what to do if the server uses a reduced mapgen limit (<31000) and an entity is outside of that area, but still inside the +/- 31000 box.
The simplest answer to that would be “nothing”, but then we would end up with entities floating around in areas where they won't do anything.

No, I did not see your latest fixes (I am rarely running on bleeding edge), but I sure am looking forward for 0.4.16. :-)

**Comment by dsohler** [comment] 2017-05-26 21:37
> Both of these apply to players as well; but players get killed instead

Better port them inside again. They may unwillingly end up outside by a glitch or bug - and get punished by having their inventory deleted, too?

**Comment by kilbith** [comment] 2017-05-26 22:22
Patch (untested):

```Lua
local builtin_item = minetest.registered_entities["__builtin:item"]
local mapgen_limit = tonumber(minetest.settings_get("mapgen_limit"))

local item = {
	on_step = function(self, dtime)
		builtin_item.on_step(self, dtime)
		local pos = self.object:get_pos()
		local to_remove = false

		for _, v in pairs(pos) do
			if v > mapgen_limit or v < -mapgen_limit then
				to_remove = true
				break
			end
		end

		if to_remove then
			self.object:remove()
		end
	end
}

setmetatable(item, builtin_item)
minetest.register_entity(":__builtin:item", item)
```

**Comment by nerzhul** [comment] 2017-05-27 07:51
@kilbith yeah a such thing in core can be good, i think i will look at this before release, at least to remove the items (can be done directly in LuaEntitySAO which is facter

**Comment by Wuzzy2** [comment] 2017-05-27 10:18
I don't like the patch, it only affects item entities.

> and better remove all SAO 

Yes, please. It would be strange if it only worked for item entities.

> except players (which will be teleported back)

Define “back”. Do you mean killing them and forcing them to respawn? I don't see that just a normal teleportation (without kill) makes sense, especially since it is not clear to me to which point exactly.

**Comment by nerzhul** [comment] 2017-05-27 10:27
No, by teleporting back i mean teleporting to nearest valid coordinate, at map limit

**Comment by Wuzzy2** [comment] 2017-05-27 11:41
This sounds like a good chance way to make the player stuck inside stone when he/she was underground.
And even if not, I think this behaviour would be way too unpredictable as players can end up in unexpected places where they may not supposed to be. Either kill them or teleport them as if they respawned.

Why do I suggest killing? Well, let's suppose its an endless scary vacuum out there where nothing can survive. :D

**Comment by nerzhul** [comment] 2017-05-27 12:21
Killing them seems reasonable but they definitively loose their stuff a single teleport at near valid Spawn is better i think

**Comment by Wuzzy2** [comment] 2017-05-27 13:12
It's not like players will always end up outside the world. Its more about maintaining a valid game state.

**Comment by paramat** [comment] 2017-05-27 20:50
> Note that currently, because 'map gen limit' only limits mapgen, it is possible to generate a world with the maximum limit 31000, then reduce the limit afterwards, however in this case the world previously generated remains visible, accessible and playable.
So, limiting of entities must not be done at the 'map gen limit' setting but at MAX_MAP_GENERATION_LIMIT (31000) or the u16 node limit instead.

Disregard this, i now think the removal should be at the set 'map gen limit' what ever that is.
'Map gen limit' is now set per-world so really should not be changed afterwards in map_meta.txt, so issues about reducing the limit are low priority.

**Comment by paramat** [comment] 2017-05-27 20:55
Not sure about players. Most players will not be able to travel beyond the world edge becuae they hit ignore, those who can will have 'noclip' so will be admin who i feel should be allowed to fly anywhere within a u16 limit.

**Comment by nerzhul** [comment] 2017-05-28 07:01
yes players are blocked at the limit without noclip

**Comment by paramat** [comment] 2017-05-31 03:43
PR #5856

**Comment by paramat** [comment] 2017-06-03 18:14
#5889 merged, removes Lua SAO entities just outside outermost generated terrain.

**Comment by nerzhul** [comment] 2017-06-03 18:29
Fixed

**Closed by nerzhul** 2017-06-03 18:29 UTC
Labels: Bug, Request / Suggestion

**Comment by paramat** [comment] 2017-06-03 18:58
There are some other issues mentioned in the first post, not sure if can be closed.
