### ISSUE TITLE
VR Support (Read and ask that you do not consider it a duplicate)

### ISSUE THREAD

**Issue by animetrom** [minetest/minetest#14315] opened 2024-01-27 17:06 UTC
### Problem

There are mods in Minecraft, such as Vivecraft, which allow character interaction with 6 degrees of freedom.

### Solutions

It would be really cool to have the ability to either be native to the game, or have support for developers to create their own VR mods.

### Alternatives

I understand that we have a "3d mode" with split screen, but I would like the freedom of being able to use my arms in-game with my controllers to perform actions.

### Additional context

I sincerely ask you to highlight this, as it would be very interesting to have something like this in the game.

**Comment by rubenwardy** [comment] 2024-01-27 17:17
This is a duplicate of #8586

I don't see anything here that isn't already covered by that ticket - that ticket asks for both head tracking and vr controls

**Comment by appgurueu** [comment] 2024-01-27 18:10
Agreed. You can comment on that issue if you feel anything specific is missing there.

**Closed by appgurueu** 2024-01-27 18:10 UTC
Labels: Duplicate, Feature request
