### ISSUE TITLE
Better android touch controls and full menu.

### ISSUE THREAD

**Issue by FlameFireling** [minetest/minetest#7507] opened 2018-06-30 09:26 UTC
##### Issue type

 - Feature request
##### Minetest version

```
0.4.17.1(android build: 0.4.17.20)
```

##### OS / Hardware

Operating system: Android 6.0.1
CPU: ARMv7

GPU model: Mali-T720
OpenGL version: OpenGL es-cm 1.1
Screen size: 4.2 inches
##### Summary

Handier touch controls. As the current ones are small and hard to tap. Multicraft has handy controls for example. And forgot to mention about full menu (ui) as you CAN'T change worlds you can have only one.

**Comment by rubenwardy** [comment] 2018-06-30 10:00
Duplicate of #1760 #2500

**Closed** 2018-06-30 10:00 UTC

**Comment by SmallJoker** [comment] 2018-06-30 10:43
For joystick movement controls, see #7126
Please get a 5.0.0-dev Android build to make use of this feature.
