### ISSUE TITLE
Chance that ABM is called with wrong node

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8378] opened 2019-03-14 23:54 UTC
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0
```

##### Summary
There is a chance that an ABM is called with a `node` that's not allowed, i.e. a node that is not in the `nodenames` table of the ABM defintion. This is bad because the `nodenames` table doesn't include air and thus destroy any assumption I can make as a modder and is breaking mods and games.

This is a regression, it didn't happen in 0.4.17.1.

##### Steps to reproduce
1. Use this mod code:

```
local REPLACE_WITH_NODE = "air"
minetest.register_abm({
	label = "Test ABM node",
	nodenames = { "group:wood" },
	neighbors = { "group:water" },
	chance = 1,
	interval = 1,
	action = function(pos, node)
		minetest.chat_send_all("ABM calls! pos="..minetest.pos_to_string(pos).." node.name="..tostring(node.name))
		if not node or minetest.get_item_group(node.name, "wood") == 0 then
			minetest.chat_send_all("BUG DETECTED! ABM was called with wrong node: "..tostring(node.name))
		else
			minetest.chat_send_all("OK")
		end
		minetest.set_node(pos, { name = REPLACE_WITH_NODE })
	end,
})
```

2. Use the mod in MineClone 2
3. Go into Creative Mode and give yourselves any wood planks and a water bucket
4. Place

EXPECTED:
The wooden planks turn into air when water touches it. The chat only says “ABM calls!” and “OK”.

ACTUAL:
The wooden planks turn into air when water touches it. The chat says:

> ABM calls! (…) node.name = mcl_core:acaciawood
> OK!
> ABM calls! (…) node.name = air
> BUG DETECTED! ABM was called with wrong node: air

So this means first the ABM is called with air as its `node` argument.

Air is not member of the `wood` or `water` group (I checked at runtime).

Now comes the weird part:
Repeat the experiment in Minetest Game. No error here. WTF?

##### Random guess
It might be a timing-related bug. MCL2 is much more heavyweight than MTG.

**Comment by paramat** [comment] 2019-03-15 00:10
ABM PR not in 0.4.17.1 #7555 
@lhofhansl

**Comment by Wuzzy2** [comment] 2019-03-15 00:13
LOL

**Comment by lhofhansl** [comment] 2019-03-24 21:41
I don't see how #7555 can sneak in an entirely incorrect node type.
The cache is pre-filter, even when the cache can't rule out the ABM call we do the normal logic.

**Comment by BluebirdGreycoat** [comment] 2019-03-29 18:32
I may be remembering incorrectly, but wasn't this bug reported before for some other pre-v5 Minetest version?

**Comment by paramat** [comment] 2019-03-29 19:47
In case it helps, see the patches from https://github.com/minetest/minetest/issues/5375#issuecomment-285962414 onwards.

**Comment by minertestdude** [comment] 2019-05-20 07:01
this causes repeated hardcrash in online server using mods like basic_machines, see reference from ac-minetest ^^^^

**Comment by DS-Minetest** [comment] 2019-05-22 13:37
Can't this simply be fixed by checking the requirements for the callback to be called before each call? I.e. check if the node is really matching `nodenames` and if there is a suitable neightbour and don't call the callback if the conditions are not met.

**Comment by paramat** [comment] 2019-05-28 21:05
ABMs are already very intensive, so any fix needs to be simple and lightweight.

**Comment by TurkeyMcMac** [comment] 2022-11-27 13:46
I can't reproduce this. Perhaps it was fixed in the interim? Can you still reproduce it?

**Comment by Wuzzy2** [comment] 2022-11-27 16:24
I can also no longer reproduce it. Minetest 5.6.1, MineClone 2 0.80.

**Comment by TurkeyMcMac** [comment] 2022-11-27 16:25
Thanks, closing this then.

**Closed by TurkeyMcMac** 2022-11-27 16:25 UTC
Labels: Bug, @ Server / Client / Env., Possible close
