### ISSUE TITLE
Formspec background color: Set both “window” and fullscreen color

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4716] opened 2016-11-02 02:33 UTC
I have experimented with the formspec element `bgcolor` a bit.
I have tried to *both* set the background color for the “window” (second parameter = `false`) and for the “fullscreen” (second parameter = `true`).
Example: `bgcolor[#FF0000FF;false]bgcolor[#00FF0080;true]`
Here, I expect to have a reddish fullscreen background with a green “window” in the center. But it seems Minetest lets only the final `bgcolor` decide, so I only end up with a reddish background for the entire screen.

It seems Minetest only supports one of these at a time. Meaning, either you set the “window” color, then the fullscreen background is completely transparent. Or you set the “fullscreen color”, then you change the color of the entire screen, including the “window”.

I wish Minetest supports setting both. Sidenote: Minetest Game seemingly is using a “window” color but it actually just fakes it by using a background image (`background`).

**Comment by rubenwardy** [comment] 2016-11-02 13:46
Seems related to (now fixed) #4397

**Comment by paramat** [comment] 2018-09-20 00:54
@Wuzzy2 does the fixing of #4397 alter this issue?

**Comment by Wuzzy2** [comment] 2018-09-20 21:45
I don't think so, as apparently only `background` was touched, not `bgcolor`.
Haven't tested it yet, however.

**Comment by rubenwardy** [comment] 2018-09-20 22:48
I was saying that the cause is probably similar

**Comment by paramat** [comment] 2018-10-25 15:30
Any core dev support?

**Closed** 2018-11-26 09:11 UTC
Labels: @ Client / Audiovisuals, Core dev consideration needed, Feature request, No core dev support long term
