### ISSUE TITLE
Wielded is glichted on certain OpenGL versions

### ISSUE THREAD

**Issue by BlockMen** [minetest/minetest#2350] opened 2015-02-18 13:45 UTC
This seems to be related to the OpenGL version. EDIT: or the fact that those "low" versions are on integrated graphics, not dedicated.
![000](https://cloud.githubusercontent.com/assets/3742497/6248137/a5cf99ea-b77c-11e4-8435-8690989c669d.png)
(image by addi)

See also: https://forum.minetest.net/viewtopic.php?f=6&t=10862

**Comment by PilzAdam** [comment] 2015-02-18 14:03
Works for me on OpenGL 4.4.0

**Comment by BlockMen** [comment] 2015-02-18 14:07
@PilzAdam Indeed, 4.4.0 works aswell for me, 4.2.0 not

**Comment by MT-Modder** [comment] 2015-02-18 14:46
I have this problem with OpenGL 2.0.0

**Comment by Novatux** [comment] 2015-02-18 15:11
Works fine for me, with OpenGL 2.1

**Comment by indriApollo** [comment] 2015-02-18 15:31
Works fine here, opengl 3.0

**Comment by PilzAdam** [comment] 2015-02-18 17:53
Irrlicht doesn't use any modern OpenGL functions anyway (AFAIK), so this might be just a driver specific problem?

**Comment by MT-Modder** [comment] 2015-02-18 18:34
Well it worked before 0.4.11 but now it looks like crap.

**Comment by kilbith** [comment] 2015-02-18 20:48
Works fine with OpenGL 2.1

**Comment by RHRhino** [comment] 2015-02-21 12:29
I also use OpenGL 4.2.0. Could that cause all those weird graphic bugs I reported lately?
https://github.com/minetest/minetest/issues/2035
https://github.com/minetest/minetest/issues/2179

**Comment by BlockMen** [comment] 2015-02-21 12:47
@RHRhino seems indeed to be related to #2035 
I can reproduce this with nodesboxes and integrated Graphics

@MT-Modder Do you use MT with integrated or dedicated graphics?

**Comment by MT-Modder** [comment] 2015-02-21 14:40
@BlockMen  Integrated.

**Comment by Wuzzy2** [comment] 2015-02-24 07:07
Works for me, using OpenGL 3.0.

**Comment by Megaf** [comment] 2015-02-25 10:13
@BlockMen I can confirm, It's the very same thing here.

Nvidia 320M, OS X Yosemite. 
It's a somehow new bug, it worked several version ago.
OpenGL 2.1 by the way.
I'm not sure why such an old version of OpenGL is being used on OS X.

**Comment by RHRhino** [comment] 2015-03-06 14:35
Is anyone working on that? Or is there a way for me to fix that e.g. change the Opengl version?

**Comment by BlockMen** [comment] 2015-08-11 11:52
Since it's not clearly stated by firstpost: I don't know if the reason is the "wrong" OpenGL version or the fact that it happens on integrated graphics. But since I can't divide them (or idk how i could) i can't say more about or test it.

And yes, it is still present (2015-08-11) Introduced with 0.4.11 IIRC when the wieldmesh was redone.

**Comment by RHRhino** [comment] 2015-08-12 06:57
Yes this issue is still present for me too. It would be cool if it could be fixed before the next release. IMO the wieldmesh isn't a problem - it just looks bad, but the other weird effects https://github.com/minetest/minetest/issues/2035 are really annoying.

**Comment by Fixer-007** [comment] 2016-01-18 16:29
Fix is available here: https://github.com/minetest/minetest/pull/3586

**Comment by paramat** [comment] 2016-01-25 19:39
Fix is merged.

**Closed by paramat** 2016-01-25 19:39 UTC
Labels: @ Client / Audiovisuals, bug, High priority, Need user feedback, obscure
