### ISSUE TITLE
Server v5.6.1 crashes when v5.3.0 Client connects

### ISSUE THREAD

**Issue by Rexelpitlum** [minetest/minetest#13376] opened 2023-03-31 19:04 UTC
###### Sever-Version:
```
Minetest 5.6.1 (Linux)
Using Irrlicht 1.9.0mt8
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

###### Client Version:
```
Minetest 5.3.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
```

###### Server OS
Operating system: Ubuntu 22.04.2 LTS
CPU: AMD Epic (Cloud Server)

###### Client OS
Operating system: Debian GNU/Linux 11 (bullseye)
CPU: Intel Core i3-1115G4

##### Summary
I am running a Minetest server using the latest release version (v5.6.1)
When connecting with a v5.3.0 client (Debian 11), the server crashes.
This does not happen for 5.6.1 clients (on recent Ubuntu systems).

##### Steps to reproduce
See above.

##### Server Syslog output:
```
Mar 31 18:36:13 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:13: ACTION[Server]: Rexelpitlum [xx.xx.xx.xx] joins game. List of players: Rexelpitlum
Mar 31 18:36:13 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:13: WARNING[Server]: 3d_armor[set_player_armor]: Detached armor inventory is nil
Mar 31 18:36:13 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:13: ACTION[Main]: Server: Shutting down
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:14: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'wieldview' in callback environment_Step(): (load):27: core.check_player_privs expects a player or playername as argument.
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:14: ERROR[Main]: stack traceback:
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:14: ERROR[Main]: #011[C]: in function 'error'
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:14: ERROR[Main]: #011/usr/share/minetest/builtin/game/misc.lua:23: in function 'check_player_privs'
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:14: ERROR[Main]: #011(load):27: in function 'is_creative_enabled'
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:14: ERROR[Main]: #011(load):1303: in function 'hide_items'
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:14: ERROR[Main]: #011(load):1320: in function 'get_items_fs'
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:14: ERROR[Main]: #011(load):1559: in function 'make_fs'
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:14: ERROR[Main]: #011(load):177: in function 'func'
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:14: ERROR[Main]: #011/home/minetest/.minetest/mods/3d_armor/3d_armor/api.lua:341: in function 'run_callbacks'
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:14: ERROR[Main]: #011/home/minetest/.minetest/mods/skinsdb/init.lua:49: in function 'update_player_visuals'
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:14: ERROR[Main]: #011/home/minetest/.minetest/mods/3d_armor/wieldview/init.lua:53: in function 'update_wielded_item'
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:14: ERROR[Main]: #011/home/minetest/.minetest/mods/3d_armor/wieldview/init.lua:64: in function 'func'
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:14: ERROR[Main]: #011/usr/share/minetest/builtin/common/after.lua:20: in function </usr/share/minetest/builtin/common/after.lua:5>
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 minetest[650]: 2023-03-31 18:36:14: ERROR[Main]: #011/usr/share/minetest/builtin/game/register.lua:431: in function </usr/share/minetest/builtin/game/register.lua:417>
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 systemd[1]: minetest.service: Main process exited, code=exited, status=1/FAILURE
Mar 31 18:36:14 ubuntu-2gb-nbg1-2 systemd[1]: minetest.service: Failed with result 'exit-code'.
```

**Comment by SmallJoker** [comment] 2023-03-31 19:06
Duplicate of #13343.

**Closed by SmallJoker** 2023-03-31 19:06 UTC
Labels: Unconfirmed bug
