### ISSUE TITLE
emissive texturing

### ISSUE THREAD

**Issue by Tcll** [minetest/minetest#10093] opened 2020-06-23 01:00 UTC
so I'm working on a high tech mod and was hoping to create emissive sections of a texture for various node/entity definitions, think of minecraft's Applied Energistics 2
specifically Charged Certus Quarts ore, but the various ME blocks also function similarly (aside from being light sources on top):
![](https://cdn-ak.f.st-hatena.com/images/fotolife/m/mntone/20161129/20161129115317.png)
![](https://forum.mineaurion.com/assets/uploads/files/1545391286467-df8df1fc-f8f9-4aa9-8c03-9d8e3b7fc72e-image.png)

how can I achieve this in minetest??
note that I'm not looking to use a light source to make things glow
I just want to make 1 section of a texture look like it's glowing without actually emitting any world light, which is why I specifically mentioned the ore above

EDIT:
for minetest specifically, mese ore could have the yellow spots glow like the mese block

**Comment by ClobberXD** [comment] 2020-06-23 09:52
Related: #8854

**Comment by paramat** [comment] 2020-06-24 00:08
Duplicate of #9075 and #9495

**Closed by paramat** 2020-06-24 00:08 UTC
Labels: @ Client / Audiovisuals, Feature request

**Comment by Tcll** [comment] 2020-06-24 00:39
@rubenwardy I just want to note the title was accurate before you changed it
despite not mentioning it, I've yet to find any documentation for supporting emissive textures on nodes.
nobody's even answered [my thread](https://forum.minetest.net/viewtopic.php?t=24154) about it

btw, just to note, it's entirely possible to map an emissive texture overlay within the modifiers
granted you might need to get a bit hacky with blending, but if you know how to setup a shadeless bit mask, you can just defer/ignore shading through that ;)

**Comment by rubenwardy** [comment] 2020-06-24 00:39
It's because it's not supported

**Comment by paramat** [comment] 2020-06-24 00:51
Emissive texturing is not possible in MT, so a title like 'Document emissive texturing' suggests it is possible but the documentation is missing.
If there is no documentation about a feature, that feature very probably does not exist.

**Comment by Tcll** [comment] 2020-06-24 00:52
eh I mean, I was just as much pushing for documentation as I was for support
but I see where you're coming from, sorry.
