### ISSUE TITLE
Improve received hit feedback

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#3691] opened 2016-02-11 10:45 UTC
The current "red fade out" hit effect is not very effective, because:
- It takes too much time to fade out
- It feels "floaty" (not as though you've been hit)
- The red makes it hard to see, and easier to receive more hits and die

Satisfying hit feedback is needed to make combat fun.

I suggest to look at how other FPS games implement hit feedback in order to find a better solution (shaking the view a tiny bit, without any red overlay, would be a better solution already).

**Comment by RealBadAngel** [comment] 2016-02-11 11:55
playing "ouch.ogg" ?

**Comment by rubenwardy** [comment] 2016-02-11 13:17
Some visual feedback is needed too

**Comment by paper-pauper** [comment] 2016-02-11 14:47
That's why I recommended a slight screen shaking/tilting. If you want a good example, go play OpenArena or watch a video of it.

**Comment by RealBadAngel** [comment] 2016-02-11 16:00
anyway this is duplicate of issue #3429

**Comment by C1ffisme** [comment] 2016-02-11 17:15
@RealBadAngel This isn't a duplicate of that issue. That issue deals with the red screen, this issue deals with replacing that red screen with something more pleasant. (Er... At least something that isn't a red screen.)

I would prefer knockback, as it would feel more like you were hit, and less like someone poured transparent red paint over you.

**Comment by paramat** [comment] 2016-02-13 01:15
I agree the red screen is bad in many ways. A very short red flash would be better.

**Comment by est31** [comment] 2016-02-13 01:18
:-1: I like it how it is right now. If you get hurt, it hurts. You have to concentrate to fight back. It actually works if you managed to damage the other party as well. They get the flash too.

**Comment by C1ffisme** [comment] 2016-02-13 01:50
@est31 Actually, because your damage value is less if you spam-click, the red screen could be considered a timer, as in "Gotta run before the screen goes normal!".

If the player's controls or speed were messed up by being damaged, that would be a bit more challenging (if not more realistic).

**Comment by est31** [comment] 2016-02-13 15:24
You still can run away with a red screen. If you are slowed down thats even worse for you.

**Comment by Calinou** [comment] 2016-02-13 19:14
What about using a texture that's overlaid on the screen, with a specific blend mode? Here are some mockups made with GIMP:

- [50% opacity, Normal blend mode](https://lut.im/O1f3Gaf12R/pj90N7aDJxswHhPF.jpg)
- [100% opacity, Add blend mode](https://lut.im/5mNCbKKrqw/RYKpWjZdgaN0AHWP.jpg)
- [100% opacity, Substract blend mode](https://lut.im/NNqELHfl35/jos7wMVQaeFC4ysS.jpg)

The Substract blend mode has the upside of not brightening dark areas (so that fighting in caves doesn't brighten your whole screen).

**Comment by est31** [comment] 2016-02-13 19:28
Looks nice, does it work without postprocessing shaders?

**Comment by est31** [comment] 2016-02-13 19:28
Ah its a texture... Yeah that would probably work.

**Comment by C1ffisme** [comment] 2016-02-13 21:29
@Calinou That actually looks a lot better than the current feedback by far.

**Comment by paper-pauper** [comment] 2016-02-14 13:34
@Calinou the first one looks the best, IMO. Would really like to see it in motion.

**Comment by sofar** [comment] 2016-02-17 00:19
I'm more of a fan of the 3rd texture (subtract mode).

**Comment by 0-afflatus** [comment] 2016-02-17 23:58
I prefer subtract mode, but 50% normal is acceptable.
Altogether a great improvement.

**Comment by paper-pauper** [comment] 2016-02-18 08:15
I retract the previous statement, I didn't take into consideration dark areas. Subtract for me too, then.

**Comment by ObaniGemini** [comment] 2016-04-10 09:19
:+1: subtract with maybe a less 0xffffff color :p

**Comment by rubenwardy** [comment] 2016-04-10 13:16
I like the subtract mode, it looks more fitting

**Comment by Ferk** [comment] 2016-04-10 16:38
With substract you won't get any visual feedback at all in the dark.
Imho, normal is best, but reduce the brightness of the texture a bit so dark areas are not that red vs bright areas.

**Comment by paramat** [comment] 2016-04-10 20:44
And make the damage flash much shorter.

**Comment by paramat** [comment] 2016-10-04 23:07
^ I agree with the first post and Ferk's post above.

Watching let's play videos there are often situations where the player is being attacked by multiple mobs, the rapid taking of damage causes the red screen to be near-constant. In a dark area this is blinding, at the exact moment when you need your vision the most. It's frustrating and unnecessary.

The damage flash only needs to be very short and does not need to be as intense.

**Comment by paramat** [comment] 2016-10-04 23:54
Code https://github.com/minetest/minetest/blob/master/src/game.cpp#L3366 and https://github.com/minetest/minetest/blob/master/src/game.cpp#L4276
Damage amount controls initial alpha and is reduced per-frame for the fade. Alpha can hit a maximum of 180 when receiving 10 HP damage.

**Comment by paramat** [comment] 2016-10-05 00:09
I think damage-tilt is redundant since we have damage flash, the tilt could be difficult to notice in a combat situation where you are moving around a lot. Anyone else find the camera tilt literally painful? It's like an short, intense feeling of dizzyness and disorientation.

**Comment by paramat** [comment] 2016-10-05 00:37
See #4573

**Comment by paramat** [comment] 2018-05-04 21:09
#4573 merged.

**Closed by paramat** 2018-05-04 21:09 UTC
Labels: @ Client / Audiovisuals, Feature request
