### ISSUE TITLE
Poor mip mapping of certain textures with transparent pixels

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6846] opened 2017-12-26 14:48 UTC
When looking at dry shrubs some nodes away with enabled mip-mapping, the details are lost:
![screenshot_20171226_114656](https://user-images.githubusercontent.com/3192173/34358732-af08be36-ea52-11e7-98db-69fee0b1d60e.png)
![turds](https://user-images.githubusercontent.com/3192173/34358804-0ed27226-ea53-11e7-8481-a433d221224b.png)

When you are near to them, the texture is bigger and you can see the details:
![screenshot_20171226_114703](https://user-images.githubusercontent.com/3192173/34358741-b80a4d92-ea52-11e7-8cb8-b9f1d98e2462.png)

I guess this is caused by semi transparency, mip maps are downscaled with linear interpolation (afaik), so the fine leaves of the downscaled dry shrub become semi-transparent, but the transparency of pixels is clamped to invisible or opaque.
However, the problem still happened when I've set use_texture_alpha to true in the dry shrub's node definition.

Related problems:
* The colour values from invisible (alpha=0) pixels are included in the interpolation of the downscaling algorithm: https://github.com/minetest/minetest_game/issues/2801, https://github.com/minetest/minetest_game/issues/1397
* The mip map generation ignores the sRGB colour space, which can cause darkness: https://github.com/minetest/minetest/issues/6867

Possible solutions:
* Use a custom mip map generation algorithm: https://github.com/minetest/minetest/issues/6917, http://www.irrlicht3d.org/pivot/entry.php?id=1526
* Increase the opacity of every second pixel in a chessboard pattern: https://github.com/minetest/minetest/issues/6846#issuecomment-554473407

<I sometimes get dancing text on github>

**Comment by benrob0329** [comment] 2017-12-26 14:56
I can confirm that the mipmap goes to crap once transparency is involved.

**Comment by paramat** [comment] 2017-12-26 17:50
Notice though that distant long grass somewhat keeps it's full size, so it may be due to dry shrub being a texture with a low density of single-pixel detail, which therefore then disappears. Perhaps this is an expected result of mipmap?

**Comment by raymoo** [comment] 2017-12-27 03:04
Could also be a result of nearest-neighbor sampling on minification. Or it's not interpolating between mipmaps.

**Comment by benrob0329** [comment] 2017-12-27 05:36
Actually I take it back, the mipmap seems to have trouble with specific patterns and transparency. A pure checkerboard transparency pattern will turn completely opaque, whereas a semi-random pattern will fair better with distance.

**Comment by HybridDog** [comment] 2017-12-27 08:06
> A pure checkerboard transparency pattern will turn completely opaque

Maybe a checkerboard with semi-transparent instead of opaque pixels turns invisible.

**Comment by HybridDog** [comment] 2017-12-30 11:51
I guess that's the same problem:
http://www.irrlicht3d.org/pivot/entry.php?id=1526

**Comment by Fixer-007** [comment] 2017-12-30 23:52
>http://www.irrlicht3d.org/pivot/entry.php?id=1526

Oh it looks exactly what I have on my ATI X800 GTO.

**Comment by HybridDog** [comment] 2017-12-31 07:47
Can anybody implement the fix in minetest?

**Comment by paramat** [comment] 2018-01-01 09:14
Assuming mip mapping is part of Irrlicht can it be altered at all in MT?
For dry shrubs though we have been considering using one of the special plantlike drawtypes for it, that will thicken it up.

**Comment by HybridDog** [comment] 2019-11-15 18:23
I think I have found a solution approach:
```diff
diff --git a/client/shaders/nodes_shader/opengl_fragment.glsl b/client/shaders/nodes_shader/opengl_fragment.glsl
index 19e6c2d8..cdadb12c 100644
--- a/client/shaders/nodes_shader/opengl_fragment.glsl
+++ b/client/shaders/nodes_shader/opengl_fragment.glsl
@@ -210,6 +210,12 @@ void main(void)
 	col = applyToneMapping(col);
 #endif
 
+	// Spatial multiplex transparency
+	float alpha = base.a;
+	if (mod(int(gl_FragCoord.x) + int(gl_FragCoord.y), 2) == 0) {
+		alpha += 0.5;
+	}
+
 	// Due to a bug in some (older ?) graphics stacks (possibly in the glsl compiler ?),
 	// the fog will only be rendered correctly if the last operation before the
 	// clamp() is an addition. Else, the clamp() seems to be ignored.
@@ -222,7 +228,7 @@ void main(void)
 	float clarity = clamp(fogShadingParameter
 		- fogShadingParameter * length(eyeVec) / fogDistance, 0.0, 1.0);
 	col = mix(skyBgColor, col, clarity);
-	col = vec4(col.rgb, base.a);
+	col = vec4(col.rgb, alpha);
 
 	gl_FragColor = col;
 }
```
before:
![before](https://user-images.githubusercontent.com/3192173/68965490-34e76180-07dc-11ea-9bb5-6b226f6f34d6.png)
after:
![after](https://user-images.githubusercontent.com/3192173/68965497-39ac1580-07dc-11ea-9e99-2b233e21ad22.png)
![after2](https://user-images.githubusercontent.com/3192173/68965580-69f3b400-07dc-11ea-916f-dd73addb3fb7.png)
If a texture with transparency is rendered, usually non-opaque fragments are discarded. I have changed it so that only every second fragment, in a chessboard pattern, is discarded if there is semi-transparency.
This needs to be disabled for textures for which blending is enabled (see for example the water).
In addition to fixing this mipmapping problem, the change would also enable some semi-transparency support to textures which have `use_texture_alpha` set to false.

**Comment by paramat** [comment] 2019-11-15 19:12
That looks worse to me. The decorations are now more visible yes, but the chessboard appearence makes them look bad.

**Comment by HybridDog** [comment] 2019-11-15 19:19
It only works on high resolution screens. The downscaled mip maps may also be wrong because I think there is white colour in the usually unused rgb values of fully-transparent pixels; these invisible white colour may get mixed into the final colour during downscaling.

**Comment by sfan5** [comment] 2019-11-15 21:28
Shouldn't downscaling just be fixed then?

**Comment by HybridDog** [comment] 2019-11-15 21:35
> Shouldn't downscaling just be fixed then?

I have implemented a downscaling algorithm for mipmap generation. It is executed on the CPU and significantly increases the game initialization time.
https://github.com/minetest/minetest/issues/6917#issuecomment-359444125

**Comment by HybridDog** [comment] 2019-11-17 18:59
I have found another solution: https://github.com/HybridDog/minetest/commit/c8cae3bd7fda271c8c930984e0e5f7620194e24e
![2019-11-17-193727_1920x1080_scrot](https://user-images.githubusercontent.com/3192173/69012124-92adb200-0972-11ea-8011-0f594dc2f84c.png)
If the alpha value is between 0 and 1, the colour is taken from the base texture. This should effectively disable semi-transparent colour values which emanate from the mipmapping's downscaling which (probably) mixes colour from invisible texels.
For testing, I've used the bias parameter, which offsets the mipmap level and does not set it to zero.
#
OT:
I've also disabled mip mapping for every second pixel in a chessboard pattern out of curiosity.
No mip mapping:
![2019-11-17-193903_1920x1080_scrot](https://user-images.githubusercontent.com/3192173/69012257-1ddb7780-0974-11ea-8a6e-0ca60ef38bf3.png)
Mip mapping enabled in chessboard pattern:
![2019-11-17-193843_1920x1080_scrot](https://user-images.githubusercontent.com/3192173/69012261-27fd7600-0974-11ea-8078-b5dc52b6731a.png)
Mip mapping in every pixel:
![2019-11-17-193929_1920x1080_scrot](https://user-images.githubusercontent.com/3192173/69012267-3a77af80-0974-11ea-9b29-fa080e8924ef.png)
I think this reduces mip mapping artifacts and moire patterns at the same time.

**Comment by Calinou** [comment] 2019-11-17 21:27
> I think this reduces mip mapping artifacts and moire patterns at the same time.

This can be better achieved by enabling anisotropic filtering. The performance impact should be negligible on today's hardware, especially given the texture sizes used in Minetest :slightly_frowning_face:

**Comment by hecktest** [comment] 2019-12-05 16:15
I'd like to suggest an option to force mip off for specific nodes and entities. Most engines have an option like this for those rare edge cases where mips do not work.
![ugly](https://user-images.githubusercontent.com/42101236/70252630-0da00680-1782-11ea-8ce4-0736c1873829.gif)
Some alpha textures just can't be mipped properly and look better without, especially with transparency on every other pixel. (breaks badly on odd mips as the resulting alpha is 0.5)
Mips also tend to screw with ^[makealpha as the original color still bleeds to the lower mips, skewing the final color. And since the color for makealpha is usually something "pure" like black, white, cyan, magenta... it's very noticeable.
AF helps with none of this, the only solution is to disable the mips.

**Comment by HybridDog** [comment] 2019-12-24 17:42
> HybridDog's approach seems interesting but I'd like to see it in motion.

You can easily test it by adding a few lines to your fragment shader: https://github.com/minetest/minetest/compare/minetest:9c28acd...HybridDog:c8cae3b?w=1

**Comment by Wuzzy2** [comment] 2020-01-19 05:12
It can get so bad that some textures might become completely invisible! I noticed this in `devtest`:

https://satoshiupload.com/images/PSrBfBg79Z.png

All pine trees in this screenshot have pine needles, but the pine needles in the background are invisible. They become visible once you come closer.

**Comment by SmallJoker** [comment] 2021-01-24 08:37
Mipmapping depends on alpha=0 RGB values as well, s shown in https://github.com/minetest/minetest_game/issues/2801

Cross-linking to complete the circle of related issues.

**Comment by TheTermos** [comment] 2021-01-24 12:49
> ![ugly](https://user-images.githubusercontent.com/42101236/70252630-0da00680-1782-11ea-8ce4-0736c1873829.gif)
> Some alpha textures just can't be mipped properly and look better without

This one is easily resolved by being deliberate about the color of transparent pixels and using RGB mode.

> It can get so bad that some textures might become completely invisible!

And this one by ensuring proper local density of opaque pixels.

This issue is a few years old, so maybe instead of reinventing the wheel, issuing some guidelines about texture design would be a better solution.

Here's a grass texture with transparent pixels' color following the radial gradient similar to that on opaque pixels:
![grass](https://user-images.githubusercontent.com/55103816/105630629-8fe9ff00-5e4a-11eb-944d-420d1d4bf6de.gif)

**Comment by Calinou** [comment] 2021-01-24 13:15
@TheTermos This is indeed the good way to fix mipmapping issues, but we need to make sure that people who optimize PNGs in the future don't discard the colors of fully transparent pixels :slightly_smiling_face

**Comment by sfan5** [comment] 2021-03-31 11:46
It turns out we've had an engine-side solution for this all the time (more precisely since 2015):
https://github.com/minetest/minetest/blob/1e4913cd76f5d31456d04a5ce23e66d5c60060de/minetest.conf.example#L572-L577

Are there any concerns with automatically enabling this when mipmapping is enabled?

**Comment by Wuzzy2** [comment] 2021-03-31 12:46
Better question: Is there a reason why the player wants to have this setting *off* in the first place? If not, then remove the setting and force-enable.

**Closed** 2021-04-20 17:50 UTC
Labels: @ Client / Audiovisuals, Bug
