### ISSUE TITLE
Shrinking hotbar size might lead to empty hotbar selection

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#12077] opened 2022-02-16 02:50 UTC
##### Minetest version
```
5.5.0
```

##### Summary
I you shrink the hotbar size and the player's selected item is now out of range, the selected hotbar slot will be out of range, leading to all sorts of weird behavior.

The player can fix this by changing the hotbar slot manually, but it's still a bug.

##### Steps to reproduce

In MTG, activate the `luacmd` mod, then do this:

* Set hotbar slot to the 8th item
* `/lua me:hud_set_hotbar_itemcount(3)`

Expected result: The selected slot is automatically changed to one of the 3 valid slots (because I expect Minetest to always make sure the player has a valid hotbar selection at all times)
Actual result: Your hotbar has an empty selection

##### See also

#11525. This bug is similar, but not identical because that one touched the inventory list size instead.

**Comment by sfan5** [comment] 2022-02-16 16:50
duplicate of #11921

**Closed by sfan5** 2022-02-16 16:50 UTC
Labels: Unconfirmed bug
