### ISSUE TITLE
Error in function on_step after upgrade to version 5.3

### ISSUE THREAD

**Issue by PySlu** [minetest/minetest#10243] opened 2020-07-31 17:28 UTC
##### Minetest version

```
5.3.0
```

##### OS / Hardware

Operating system: Debian 10.4

##### Summary

Received the following error on a savegame which previously worked:

AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback luaentity_Step(): /usr/share/games/minetest/builtin/game/item_entity.lua:198: Collision info missing, this is caused by an out-of-date/buggy mod or game
stack traceback:
	[C]: in function 'assert'
	/usr/share/games/minetest/builtin/game/item_entity.lua:198: in function 'on_step'
	...est/games/minetest_extended/mods/default/item_entity.lua:43: in function <...est/games/minetest_extended/mods/default/item_entity.lua:42>

##### Steps to reproduce

Upgrade from version 5.2 to 5.3.

**Comment by sfan5** [comment] 2020-07-31 17:42
duplicate of #9796, which is bug in the game

If the game you have is a derivative of minetest_game it'll need this patch: https://github.com/minetest/minetest_game/commit/bd64188ee566bc31c1cd50d63f0da3328d42ab51

**Closed by sfan5** 2020-07-31 17:42 UTC
Labels: Unconfirmed bug

**Comment by PySlu** [comment] 2020-07-31 19:05
Thank you sfan5, this works!
