### ISSUE TITLE
Optimize wield item extruded 3D visual

### ISSUE THREAD

**Issue by jordan4ibanez** [minetest/minetest#11527] opened 2021-08-09 14:57 UTC
## Problem

Lots of mesh polygons can cause lag on lower end machines or even on higher end can cause low fps. The main issue is that the algorithm that builds the 3D extrusion from a 2D texture does not take into account the cell structure of the generating polygonal mesh therefore wasting a lot of resources putting in textured polygonal faces where under any normal circumstances no players will be able to see them.

## Solutions

A minor rebuild/bolt on to the existing code should suffice that detects if there is a nil, null, 100% opacity, etc face as it already does. Yet if there is a face in the neighboring instance of the current pixel then do not bother to generate faces/polygons in that location to preserve GPU resources. Here is an example of what I am referring to: 
![screenshot_20210809_105650](https://user-images.githubusercontent.com/1088750/128727498-d811fc21-076a-4363-9487-22742a56c2f9.png)

**Comment by sfan5** [comment] 2021-08-09 15:27
duplicate of #3069

**Closed by sfan5** 2021-08-09 15:27 UTC
Labels: Feature request
