### ISSUE TITLE
Performance: distance view shows grass without ground

### ISSUE THREAD

**Issue by JeanPaulLucien** [minetest/minetest#13091] opened 2022-12-28 19:11 UTC
##### Minetest version

```
5.6.1
```

##### OS / Hardware

Operating system: Windows
CPU:

GPU model:
OpenGL version:

##### Summary

Hole on the ground looks strange, yeah.
![screenshot_202212_05](https://user-images.githubusercontent.com/24779886/209859723-ec784cb8-4d1a-470c-bbd6-ca621302f16d.png)

##### Steps to reproduce
1. You need to be higher
2. Disable the fog.
3. Change distance view by - and + to search grass without ground

**Comment by y5nw** [comment] 2022-12-28 19:21
Doesn't this happen in general if you set the view distance too high without having the block generated?

**Comment by rollerozxa** [comment] 2022-12-28 19:23
You're literally looking at unloaded edges of mapblocks/chunks. Minetest has cubic chunks, that will happen if you have too low of a render distance.

**Comment by appgurueu** [comment] 2022-12-28 19:32
Not a bug, close this already. The purpose of fog is to "hide" this expected behavior, don't be surprised if you see it exposed if you disable it.

**Comment by JeanPaulLucien** [comment] 2022-12-28 19:34
@appgurueu , I suppose you just do not know how to fix.

**Comment by appgurueu** [comment] 2022-12-28 19:37
> @appgurueu , I suppose you just do not know how to fix.

Fog *is* the fix as long as there is no LoD / farmap which c55 has been working on.

**Comment by rollerozxa** [comment] 2022-12-28 19:41
This is akin to saying it's a bug that I can't see a mountain fifty metres ahead when my view range is the minimum 20.

**Closed** 2022-12-28 19:47 UTC
Labels: Unconfirmed bug, Possible close
