### ISSUE TITLE
Crash on startup (macOS Monterey 12.2, M1, ARM64)

### ISSUE THREAD

**Issue by ivxvm** [minetest/minetest#12024] opened 2022-01-31 04:35 UTC
##### Minetest version
```
% ./bin/minetest --version

Minetest 5.6.0-dev-128f635 (OSX)
Using Irrlicht 1.9.0mt4
Using Lua 5.1.5
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
```

##### OS / Hardware

```
Operating system: macOS Monterey 12.2
CPU: Apple M1
```

##### Summary

Game crashes on startup:

```
% ./bin/minetest
2022-01-31 06:24:57.159 minetest[3346:21737] *** Assertion failure in -[NSMenu initWithTitle:], NSMenu.m:366
2022-01-31 06:24:57.159 minetest[3346:21737] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: aTitle != nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001818241cc __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x00000001815757b8 objc_exception_throw + 60
	2   Foundation                          0x000000018274bc84 -[NSCalendarDate initWithCoder:] + 0
	3   AppKit                              0x00000001842f0708 -[NSMenu initWithTitle:] + 216
	4   minetest                            0x0000000100e12264 _ZN3irr16CIrrDeviceMacOSXC1ERKNS_27SIrrlichtCreationParametersE + 428
	5   minetest                            0x0000000100e091b4 createDeviceEx + 64
	6   minetest                            0x0000000100ac70ac _ZN15RenderingEngineC2EPN3irr14IEventReceiverE + 876
	7   minetest                            0x0000000100a651f8 _ZN14ClientLauncher11init_engineEv + 60
	8   minetest                            0x0000000100a64160 _ZN14ClientLauncher3runER13GameStartDataRK8Settings + 256
	9   minetest                            0x0000000100cfe35c main + 9216
	10  dyld                                0x00000001013390f4 start + 520
)
libc++abi: terminating with uncaught exception of type NSException
zsh: abort      ./bin/minetest
```

##### Steps to reproduce

```
git clone --depth 1 https://github.com/minetest/minetest.git
cd minetest
git clone --depth 1 https://github.com/minetest/minetest_game.git games/minetest_game
git clone --depth 1 https://github.com/minetest/irrlicht.git lib/irrlichtmt
cmake . -DRUN_IN_PLACE=TRUE
make -j$(nproc)
./bin/minetest
```

**Comment by ivxvm** [comment] 2022-01-31 06:01
I was able to work around this issue by using:

```
make package -j$(nproc)
```

Then using `codesign` to sign the app.
Unfortunately after rendering the menu it hangs:
nothing responds to clicks and cursor is spinning indefininitely until force quit.

**Comment by appgurueu** [comment] 2022-01-31 09:48
@Jordach

**Comment by ivxvm** [comment] 2022-01-31 11:20
Verbose output:

```
% /Applications/minetest.app/Contents/MacOS/minetest --verbose
2022-01-31 13:15:45: INFO[Main]: Using system-wide paths (NOT RUN_IN_PLACE)
2022-01-31 13:15:45: INFO[Main]: Detected share path: /Applications/minetest.app/Contents/Resources
2022-01-31 13:15:45: INFO[Main]: Detected user path: /Users/ivxvm/Library/Application Support/minetest
2022-01-31 13:15:45: INFO[Main]: Detected cache path: /Users/ivxvm/.cache/minetest
2022-01-31 13:15:45: INFO[Main]: minetest with SER_FMT_VER_HIGHEST_READ=29, BUILD_TYPE=Release
2022-01-31 13:15:45: INFO[Main]: RUN_IN_PLACE=0
2022-01-31 13:15:45: INFO[Main]: USE_CURL=1
2022-01-31 13:15:45: INFO[Main]: USE_GETTEXT=0
2022-01-31 13:15:45: INFO[Main]: USE_SOUND=1
2022-01-31 13:15:45: INFO[Main]: STATIC_SHAREDIR="minetest.app/Contents/Resources"
2022-01-31 13:15:45: VERBOSE[Main]: httpfetch_init: parallel_limit=8
2022-01-31 13:15:45: INFO[Main]: Message locale is now set to: C/UTF-8/C/C/C/C
2022-01-31 13:15:45: INFO[Main]: Searching worlds...
2022-01-31 13:15:45: INFO[Main]:   In /Users/ivxvm/Library/Application Support/minetest/worlds: 
2022-01-31 13:15:45: INFO[Main]: 0 found.
2022-01-31 13:15:45: INFO[Main]: Using default world at [/Users/ivxvm/Library/Application Support/minetest/worlds/world]
2022-01-31 13:15:45: INFO[Main]: Using default gameid [minetest]
2022-01-31 13:15:45: INFO[Main]: Audio: Global Initialized: OpenAL 1.1, using MacBook Air Speakers
2022-01-31 13:15:45: INFO[Main]: Irrlicht: Irrlicht Engine version 1.9.0mt4
2022-01-31 13:15:45: INFO[Main]: Irrlicht: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
2022-01-31 13:15:45: INFO[Main]: Irrlicht: Using renderer: OpenGL 2.1
2022-01-31 13:15:45: INFO[Main]: Irrlicht: Apple M1: Apple
2022-01-31 13:15:45: INFO[Main]: Irrlicht: OpenGL driver version is 1.2 or better.
2022-01-31 13:15:45: INFO[Main]: Irrlicht: GLSL version: 1.2
2022-01-31 13:15:45: VERBOSE[Main]: Client: Configuring general top level window properties
2022-01-31 13:15:45: INFO[Main]: Waiting for other menus
2022-01-31 13:15:45: INFO[Main]: Waited for other menus
2022-01-31 13:15:45: INFO[Main]: Audio: Initialized: OpenAL 
2022-01-31 13:15:45: INFO[Main]: GUIEngine: Initializing Lua
2022-01-31 13:15:45: VERBOSE[AsyncWorker-0]: Loading and running script from /Applications/minetest.app/Contents/Resources/builtin/init.lua
2022-01-31 13:15:45: INFO[AsyncWorker-0]: Initializing Asynchronous environment
2022-01-31 13:15:45: VERBOSE[AsyncWorker-1]: Loading and running script from /Applications/minetest.app/Contents/Resources/builtin/init.lua
2022-01-31 13:15:45: INFO[AsyncWorker-1]: Initializing Asynchronous environment
2022-01-31 13:15:45: VERBOSE[AsyncWorker-2]: Loading and running script from /Applications/minetest.app/Contents/Resources/builtin/init.lua
2022-01-31 13:15:45: INFO[AsyncWorker-2]: Initializing Asynchronous environment
2022-01-31 13:15:45: VERBOSE[AsyncWorker-3]: Loading and running script from /Applications/minetest.app/Contents/Resources/builtin/init.lua
2022-01-31 13:15:45: INFO[AsyncWorker-3]: Initializing Asynchronous environment
2022-01-31 13:15:45: INFO[Main]: SCRIPTAPI: Initialized main menu modules
2022-01-31 13:15:45: VERBOSE[Main]: Loading and running script from /Applications/minetest.app/Contents/Resources/builtin/init.lua
2022-01-31 13:15:45: INFO[Main]: Searching worlds...
2022-01-31 13:15:45: INFO[Main]:   In /Users/ivxvm/Library/Application Support/minetest/worlds: 
2022-01-31 13:15:45: INFO[Main]: 0 found.
2022-01-31 13:15:45: INFO[Main]: Audio: Error opening /Applications/minetest.app/Contents/Resources/games/minetest_game/menu/theme.0.ogg for decoding
2022-01-31 13:15:45: INFO[Main]: Audio: Error opening /Applications/minetest.app/Contents/Resources/games/minetest_game/menu/theme.1.ogg for decoding
2022-01-31 13:15:45: INFO[Main]: Audio: Error opening /Applications/minetest.app/Contents/Resources/games/minetest_game/menu/theme.2.ogg for decoding
2022-01-31 13:15:45: INFO[Main]: Audio: Error opening /Applications/minetest.app/Contents/Resources/games/minetest_game/menu/theme.3.ogg for decoding
2022-01-31 13:15:45: INFO[Main]: Audio: Error opening /Applications/minetest.app/Contents/Resources/games/minetest_game/menu/theme.4.ogg for decoding
2022-01-31 13:15:45: INFO[Main]: Audio: Error opening /Applications/minetest.app/Contents/Resources/games/minetest_game/menu/theme.5.ogg for decoding
2022-01-31 13:15:45: INFO[Main]: Audio: Error opening /Applications/minetest.app/Contents/Resources/games/minetest_game/menu/theme.6.ogg for decoding
2022-01-31 13:15:45: INFO[Main]: Audio: Error opening /Applications/minetest.app/Contents/Resources/games/minetest_game/menu/theme.7.ogg for decoding
2022-01-31 13:15:45: INFO[Main]: Audio: Error opening /Applications/minetest.app/Contents/Resources/games/minetest_game/menu/theme.8.ogg for decoding
2022-01-31 13:15:45: INFO[Main]: Audio: Error opening /Applications/minetest.app/Contents/Resources/games/minetest_game/menu/theme.9.ogg for decoding
2022-01-31 13:15:45: INFO[Main]: Audio: Error opening /Applications/minetest.app/Contents/Resources/games/minetest_game/menu/theme.ogg for decoding
2022-01-31 13:15:45: INFO[Main]: OpenALSoundManager: "/Applications/minetest.app/Contents/Resources/games/minetest_game/menu/theme" not found.
2022-01-31 13:15:45: INFO[Main]: OpenALSoundManager: "/Applications/minetest.app/Contents/Resources/games/minetest_game/menu/theme" not found.
2022-01-31 13:15:45: INFO[Main]: OpenALSoundManager: "/Applications/minetest.app/Contents/Resources/games/minetest_game/menu/theme" not found.
2022-01-31 13:15:45: INFO[Main]: OpenALSoundManager: "/Applications/minetest.app/Contents/Resources/games/minetest_game/menu/theme" not found.
2022-01-31 13:16:12: [Main]: INFO: signal_handler(): got SIGTERM, shutting down.
2022-01-31 13:16:12: INFO[Main]: Audio: Deinitializing...
2022-01-31 13:16:12: INFO[Main]: Audio: Deinitialized.
2022-01-31 13:16:12: INFO[Main]: GUIEngine: Deinitializing scripting
2022-01-31 13:16:12: INFO[Main]: Audio: Global Deinitialized.
2022-01-31 13:16:12: VERBOSE[Main]: httpfetch_cleanup: cleaning up
```

**Comment by appgurueu** [comment] 2022-01-31 11:34
Interesting. The `got SIGTERM, shutting down` is similar to what is seen on Chrome OS: #10216

I had initially suspected some kind of "parental control" software but it might be a different thing

**Comment by rubenwardy** [comment] 2022-01-31 11:36
` got SIGTERM, shutting down.` means that they've pressed the close button on the Window. The issue here is that the GUI freezes before that. I can't see any logs relevant to that

**Comment by appgurueu** [comment] 2022-01-31 11:38
> ` got SIGTERM, shutting down.` means that they've pressed the close button on the Window. The issue here is that the GUI freezes before that. I can't see any logs relevant to that

The Chrome OS issue says it closes "on startup" though, as does this issue if referring to the non-self-compiled install?

**Comment by ivxvm** [comment] 2022-01-31 11:52
Sorry for confusion, it doesn't crash like in OP message, after workaround it hangs in the main menu unresponsive (like described in the second message in this thread). SIGTERM message is printed right after I ctrl-click app on the taskbar and select "Force Quit".

**Comment by ivxvm** [comment] 2022-01-31 18:04
> `./bin/minetest` is not a supported way of running Minetest on macOS, you always have to build an app bundle. That said this should either be fixed or an error message added to have users not guessing at crashes.

Yes, but that didn't work either. It hangs in the main menu when running properly bundled version (explained in thread).

**Comment by sfan5** [comment] 2022-01-31 19:42
Closing this as a duplicate of #10170 then, we'll continue in the other issue.

**Closed by sfan5** 2022-01-31 19:42 UTC
Labels: Unconfirmed bug, macOS
