### ISSUE TITLE
Do not hardcode all liquids to wave

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5694] opened 2017-05-02 14:32 UTC
Lava shouldn't be effected by the waving shader for two reasons:

1. It doesn't makes sense that lava waves like ocean water
2. If the waving shader is active the lava is lower than normal and is not visible on the most outer nodes. Then you walk on these nodes because you think it is save and die

If I walk on the node I am pointing I will die

![screenshot_20170502_163109](https://cloud.githubusercontent.com/assets/16163058/25622474/cc4ad3e4-2f54-11e7-8352-09d38697f4a2.jpg)

**Comment by paramat** [comment] 2017-05-02 19:18
:+1: Makes sense to me.

**Comment by MarkuBu** [comment] 2017-05-02 19:44
Huh? Really? I expect that it's an engine change

**Comment by paramat** [comment] 2017-05-02 20:55
The nodedefs have 'waving = 1' which just needs removing.

**Comment by paramat** [comment] 2017-05-02 20:57
Hang on, i may be wrong.

**Comment by paramat** [comment] 2017-05-02 20:59
I thought there was a 'waving = 1' definition in the nodes as with leaves, but there doesn't seem to be, it may be hardcoded.

**Comment by paramat** [comment] 2017-05-02 21:04
https://github.com/minetest/minetest/blob/master/client/shaders/water_surface_shader/opengl_vertex.glsl#L39
Hardocoded for all liquids. There should be a 'waving = 1' added to liquid nodes instead, as with waving leaves and plants, thi swill need new material types TILE_MATERIAL_WAVING_LIQUID_TRANSPARENT and TILE_MATERIAL_WAVING_LIQUID_OPAQUE.

**Comment by paramat** [comment] 2017-05-02 21:13
Although waving water could be reconsidered, RBA was in the process of removing it and considered it buggy and not well implemented.

**Comment by paramat** [comment] 2017-05-02 21:15
Maybe river water should not wave also?

**Comment by MarkuBu** [comment] 2017-05-02 22:16
I opened a river water issue a few month ago, if I'm not wrong. Will take a look tomorrow

**Comment by bigfoot547** [comment] 2017-05-02 22:18
I just noticed something else:
![Proof!!!](https://cloud.githubusercontent.com/assets/21959175/25641723/551fe280-2f5b-11e7-84eb-d9183c7f087f.jpg)!

**Comment by juhdanad** [comment] 2017-05-02 22:22
The water surface shader is only applied to water, not to lava (see [there](https://github.com/minetest/minetest/blob/master/src/nodedef.cpp#L766)).

You should update the nodes shader instead.

**Comment by MarkuBu** [comment] 2017-05-02 22:24
That is a side effect. The shader has to lower the height that he can create waves. 

I set wave height to 0 because I want to have the effect that the water level is a little bit below the ground level because it looks better

**Comment by paramat** [comment] 2017-05-02 22:59
```
	if (is_liquid) {
		material_type = (alpha == 255) ?
			TILE_MATERIAL_LIQUID_OPAQUE : TILE_MATERIAL_LIQUID_TRANSPARENT;
		if (name == "default:water_source")
			is_water_surface = true;
	}
```
It gets worse, a subgame node is hardcoded in the engine.

**Comment by paramat** [comment] 2017-05-02 23:04
https://github.com/minetest/minetest/blob/master/client/shaders/nodes_shader/opengl_vertex.glsl#L60
Why is liquid waving code duplicated here?

**Comment by paramat** [comment] 2017-05-02 23:12
https://github.com/minetest/minetest/commit/6c98fd6658fcf7c0c676ee88f03e364c852e9f1b
" Unite nodes shaders.

Pass drawtype and material type to shaders.
Move shaders generation to startup only.
Allow assign shaders per tile.
Initial code to support water surface shader."
RBA did say that water shaders are duplicated, and was about to remove some code.

**Comment by paramat** [comment] 2017-05-02 23:15
So perhaps first we can remove that hardcoding of default:water_source so that that node is not being affected by 2 duplicate shaders?

**Comment by paramat** [comment] 2017-05-02 23:25
https://github.com/minetest/minetest/pull/3616
" Allow to set shader for a node, add special and normal texture defs for a tile
Remove hardcoding water surface shader"
This PR was unmerged.

**Comment by paramat** [comment] 2017-05-05 00:46
```
	if (is_liquid) {
		material_type = (alpha == 255) ?
			TILE_MATERIAL_LIQUID_OPAQUE : TILE_MATERIAL_LIQUID_TRANSPARENT;
		if (name == "default:water_source")
			is_water_surface = true;
	}

	// Vertex alpha is no longer supported, correct if necessary.
	correctAlpha();

	u32 tile_shader[6];
	for (u16 j = 0; j < 6; j++) {
		tile_shader[j] = shdsrc->getShader("nodes_shader",
			material_type, drawtype);
	}

	if (is_water_surface) {
		tile_shader[0] = shdsrc->getShader("water_surface_shader",
			material_type, drawtype);
	}
```
Yes, so all 6 tiles are sent to the 'nodes shader', then for 'default:water_source' only the top tile is sent to 'water surface shader', which is still a duplicate of 'nodes shader'. This must have been preparation for new water surface shader development which never happened. Obviously this hardcoding means this code fails for river water or any mod or subgame water. So we can remove this hardcoding and the water surface shader.

**Comment by paramat** [comment] 2017-05-05 18:20
PR #5704

**Comment by paramat** [comment] 2017-06-04 15:31
See #5897

**Comment by paramat** [comment] 2017-09-08 03:29
#5704 merged.

**Comment by paramat** [comment] 2019-03-22 02:10
I'll probably adopt #5897

**Comment by paramat** [comment] 2019-03-23 02:50
PR #8418

**Comment by paramat** [comment] 2019-03-27 00:20
#8418 merged.

**Closed by paramat** 2019-03-27 00:20 UTC
Labels: @ Client / Audiovisuals, Maintenance, Request / Suggestion, Shaders, Supported by core dev

**Comment by paramat** [comment] 2019-09-26 20:15
https://github.com/minetest/minetest_game/pull/2346 related and merged.
