### ISSUE TITLE
An Optional wieldItem switch animation

### ISSUE THREAD

**Issue by epCode** [minetest/minetest#10955] opened 2021-02-15 02:56 UTC
### problem
  Every single time when you change the selected item in you hot-bar, the "down, switch, up" animation occurs. For some objects 
  you need this not to happen, like when you are loading a MineClone bow, or when you are holding something that constantly 
  changes etc.

### solution
  so... Would it be possible to add an optional "change animation" when you are doing a function like: 
  `player:set_wielded_item(wielditem)`
  changes to:
  `player:set_wielded_item(wielditem, false)`
  to indicate the desire to not play that anim. (set by default to true)

**Comment by AFCMS** [comment] 2021-04-13 15:35
I support this idea

**Comment by v-rob** [comment] 2021-06-15 03:53
Duplicate of #9377

**Closed by v-rob** 2021-06-15 03:53 UTC
Labels: @ Client / Audiovisuals, @ Script API, Feature request, Supported by core dev

**Comment by AFCMS** [comment] 2021-06-15 09:07
@sfan5 please mark #9377 supported by code dev

**Comment by v-rob** [comment] 2021-06-15 22:20
> @sfan5 please mark #9377 supported by code dev

It already is (although the preview when you hover over the link doesn't seem to show it).  Seems like a bug in GitHub:

![image](https://user-images.githubusercontent.com/31123645/122130790-0503a400-cded-11eb-869e-81464f6f425d.png)

Versus:

![image](https://user-images.githubusercontent.com/31123645/122130826-1187fc80-cded-11eb-95da-74f208360dba.png)
