### ISSUE TITLE
Improve loading screen text

### ISSUE THREAD

**Issue by BruceMustache** [minetest/minetest#10214] opened 2020-07-21 12:28 UTC
## Problem

Sometimes when loading a world can be too long and I think minetest loading page doesn't gives user feedback as if you run minetest using --verbose and look at the terminal
ie: This may cause user to think minetest is not reponding or something is wrong

## Solutions

Detail more what happening in loading screen like showing what media is loading

## Alternatives

If possible would be better to load media while in game. So after some point of loading the player will enter on a basic world and can do some things while the world still loading

## Additional context

Video loading a world. If look at the GUI you can't see what is happening but at the terminal you can see which mod, mesh, item is loading:
(https://vimeo.com/user119376123/review/440301524/fd038af5de)

**Comment by SmallJoker** [comment] 2020-07-21 16:52
Link is dead. Vimeo displays a 404 Not Found page.

The loading media names could be shown in the loading screen, however almost none is shown long enough to read, which results in a very chaotic and unreadable screen. IIRC the GUI drawing and media loading happens in the same thread, hence you won't get around stutters or unresponsive phases until loading is finished.

**Comment by paramat** [comment] 2020-07-21 21:48
Duplicate of #1665 (now re-opened).

**Closed by paramat** 2020-07-21 21:48 UTC
Labels: Feature request

**Comment by BruceMustache** [comment] 2020-07-21 21:52
I can see the link

**Comment by Calinou** [comment] 2020-07-22 07:47
> What about the in-game loading?

Loading media during gameplay sounds very difficult to do correctly.

**Comment by paramat** [comment] 2020-07-23 22:48
>  If possible would be better to load media while in game. So after some point of loading the player will enter on a basic world and can do some things while the world still loading

This is not practical, the world relies on the media, so it would be a very boring and unrelated game experience before all media has loaded, it would be far preferable to just wait or go to the toilet or have a drink or something =) Besides, it would be complex and a lot of effort to code a functioning 'partial media' world.
