### ISSUE TITLE
Sky renders the graphic of the world dragging it Windows-is-getting-slower windows style

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#9816] opened 2020-05-05 08:42 UTC
##### Minetest version
```
5.2.0
```

##### OS / Hardware

Operating system: Windows 10 Home
CPU: Intel i7-6700HQ

GPU model: Intel HD Graphics 530 / NVIDIA GeForce GTX 960M (creating the issue for a friend, in the screen he sent me he has both)
OpenGL version: 4.6.0

##### Summary

This happens: https://i.imgur.com/oy59MzW.mp4

##### Steps to reproduce

Open whatever game and move the camera, having the sky in the view

**Comment by sfan5** [comment] 2020-05-05 10:23
duplicate of #9008

> GPU model: Intel HD Graphics 530 / NVIDIA GeForce GTX 960M (creating the issue for a friend, in the screen he sent me he has both)

A game will only run on either of the graphics cards at once, so which one was actually used matters.
Previous issues suggest that this is a bug with Intel Graphics, you can usually change certain apps to use the dedicated GPU in the NVIDIA Control Panel.

**Closed by sfan5** 2020-05-05 10:23 UTC
Labels: Unconfirmed bug
