### ISSUE TITLE
Camera axis relative to object rotation

### ISSUE THREAD

**Issue by APercy** [minetest/minetest#11554] opened 2021-08-18 19:18 UTC
## Problem

I need a camera that can track the rotations of an object. The idea is to create a fighter that can roll and loop in flight. The current camera does not allow me to rotate it in the longitudinal axis and it is also not able to follow the transverse rotation in 360 degrees

## Solutions

I need the camera to follow the roll movement of an aircraft, as well as the pitch throughout a looping

## Alternatives

If you cannot track an object, be allowed to rotate its Y axis, as well as unlock the X axis limit

**Comment by Zughy** [comment] 2022-05-03 22:02
Duplicate of #8552

**Closed by Zughy** 2022-05-03 22:02 UTC
Labels: @ Client / Audiovisuals, Duplicate, Feature request
