### ISSUE TITLE
5.7.0 is extremely slow on Linux

### ISSUE THREAD

**Issue by efa** [minetest/minetest#13582] opened 2023-06-11 17:49 UTC
##### Minetest version
```
5.7.0 AppImage from https://gitlab.com/minetest/minetest/-/tags/5.7.0
```

##### OS / Hardware
Operating system: LMDE5 based on Debian11
CPU: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz

GPU model: Geforce GTX850M
OpenGL version: 3.0 Mesa 20.3.5

##### Summary
frame rate is very low, 1 to 4 fps
With 5.6.1 AppImage is about 60 fps

##### Steps to reproduce
enter a world

**Comment by efa** [comment] 2023-06-11 17:54
I tested on another PC with Debian 11 and a better HW:
CPU: AMD Ryzen 5 5600G with Radeon Graphics
OpenGL: 3.1 Mesa 20.3.5

got 4 fps

**Comment by SmallJoker** [comment] 2023-06-11 18:12
Could you please compare the F6 profiler pages between the versions? It should give a rough idea what could be going on.
Does it change anything if you disable the shaders?

**Comment by efa** [comment] 2023-06-11 19:07
![MineTest5 7 0](https://github.com/minetest/minetest/assets/1578980/45ad9187-31ad-4c34-b475-c620a5dc432f)
![Minetest5 6 1](https://github.com/minetest/minetest/assets/1578980/b6f163b6-d787-41a3-9f46-cc0715311202)

**Comment by efa** [comment] 2023-06-11 19:09
![Minetest5 6 1](https://github.com/minetest/minetest/assets/1578980/6bbad21f-ba8e-497e-b4b7-6ae52f5d06d6)

**Comment by efa** [comment] 2023-06-11 19:10
I will try to recover the same shot for the PC with AMD Ryzen 5 5600G (not mine)

**Comment by efa** [comment] 2023-06-11 19:16
here below the shot with shader OFF.
I noticed the temp rise and fan goes to max speed once I enter a word with 5.7.0, not with 5.6.1

**Comment by efa** [comment] 2023-06-11 19:17
![Minetest5 7 0_shaderOff](https://github.com/minetest/minetest/assets/1578980/bd650442-34b5-4d27-8716-95c8ad028992)

**Comment by SmallJoker** [comment] 2023-06-12 18:18
For some reason this functions now take a second to execute instead of a few milliseconds:

https://github.com/minetest/minetest/blob/c91182e1b3c38cb0a983c3330db534a84aa01af2/src/client/clientmap.cpp#L254-L260

Both GPUs, the GTX850M and the Ryzen APU do support OpenGL 4.6 and should report that in the title bar. I find it strange that yours only shows OpenGL 3.0.

1. Do you get the same results when using software rendering? For example: `LIBGL_ALWAYS_SOFTWARE=1 __GLX_VENDOR_LIBRARY_NAME=mesa minetest`
2. Retry with the Minetest setting `occlusion_culler = loops` (instead of `bfs`)
3. Enable/disable shaders. Find out whether something makes a difference (although it should not)

**Comment by efa** [comment] 2023-06-12 19:39
all other suggested test settings leave with about 1500-1600 ms per frame.
occlusion_culler = loops
do the tricks, see attach below

**Comment by lhofhansl** [comment] 2023-06-13 19:44
Hmm... updateDrawList is slow when it has to trace many empty blocks. From the trace image I can see it had to visit about 9m blocks, that strikes me as very odd, especially when less than 200 blocks are actually being drawn.

@efa What is your `viewing_range` set to? Any other settings changed (like `block_send_optimize_distance` or  `server_side_occlusion_culling` on the server side)? 
Also I cannot see how many blocks are loaded (it's either on the next F6 page, or hidden by the dialog)

@x2048 FYI.

**Comment by efa** [comment] 2023-06-13 20:44
viewing_range=3850
block_send_optimize_distance=4
server_side_occlusion_culling=Enabled
(I keep all settings to default)

**Comment by efa** [comment] 2023-06-13 21:02
I take 3 shots for the 3 F6 debug log, with loops and with bfs. For bfs I cannot find the loaded blocks

**Comment by efa** [comment] 2023-06-13 21:04
Minetest_loops_1
![Minetest_loops_1](https://github.com/minetest/minetest/assets/1578980/7224d85f-c8db-4539-b060-78159ed99c46)
Minetest_loops_2
![Minetest_loops_2](https://github.com/minetest/minetest/assets/1578980/a5c06f01-8dc1-4fdf-99ba-27e3dc91cf40)
Minetest_loops_3
![Minetest_loops_3](https://github.com/minetest/minetest/assets/1578980/8df07936-1a2d-4ae0-a69d-cae0b1b4f2e5)

**Comment by savilli** [comment] 2023-06-13 21:04
Just use viewing_range = 190 and it should be fixed

**Comment by efa** [comment] 2023-06-13 21:05
Minetest_bfs_1
![Minetest_bfs_1](https://github.com/minetest/minetest/assets/1578980/02a390a0-381a-485e-8b48-800d5032cac4)
Minetest_bfs_2
![Minetest_bfs_2](https://github.com/minetest/minetest/assets/1578980/38da629f-100a-4c04-855d-cb9e426f1690)
Minetest_bfs_3
![Minetest_bfs_3](https://github.com/minetest/minetest/assets/1578980/2eed1db7-af2f-4fac-badc-190421207aa6)

**Comment by efa** [comment] 2023-06-13 21:08
OK, I just set:
occlusion_culler=bfs
viewing_range = 190
and 5.7.0 is smooth.

Take note that 5.6.1 is smooth also with viewing_range = 3850

**Comment by efa** [comment] 2023-06-13 21:26
OK, 5.6.1 does not have occlusion_culler; i suppose is always set to loops algo.
Here results with range set to 4000. Users can change the viewing range using +/- on numpad.
Minetest5.6.1_4000_1
![Minetest5 6 1_4000_1](https://github.com/minetest/minetest/assets/1578980/3238f5c2-6b78-4a27-897e-9913b7b4d4cc)
Minetest5.6.1_4000_2
![Minetest5 6 1_4000_2](https://github.com/minetest/minetest/assets/1578980/38115094-ef56-466b-85b3-563016ecb2b6)

**Comment by savilli** [comment] 2023-06-13 21:35
That's expected for `occlusion_culler = bfs`. See https://github.com/minetest/minetest/issues/13345#issuecomment-1480243370

**Comment by efa** [comment] 2023-06-13 21:38
I repeated the test with 5.7.0 and
occlusion_culler=bfs
viewing_range = 190
then increasing range using button +
I got this results:
range FPS
-600  30
-1000 25
-1400 18
-1700 10
-2000 5
-2700 1

**Comment by efa** [comment] 2023-06-13 21:45
so keeping low viewing range, with lot of near blocks I should see performance increase using bfs respect loops algo?

**Comment by sfan5** [comment] 2023-06-13 21:55
Duplicate of #13345, would have helped to mention that you use an insane view range earlier.

**Closed by sfan5** 2023-06-13 21:55 UTC
Labels: Unconfirmed bug, Performance
