### ISSUE TITLE
Some particles do not render after 6be6fb78

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#6729] opened 2017-12-02 22:49 UTC
Particles from weather mod will not render when bi/tri-filtering is disabled.

Regression was introduced by https://github.com/minetest/minetest/commit/6be6fb78a4becc9bf4e999ff5aaa3c2d75fcc428 "Do not scale texture unless necessary." @lhofhansl 

To reproduce, install and enable this weather mod from here: https://github.com/paramat/snowdrift

**Comment by paramat** [comment] 2017-12-02 22:56
Commit:
```
-			s32 scaleto = g_settings->getS32("texture_min_size");
+			const bool filter = m_setting_trilinear_filter || m_setting_bilinear_filter;
+			const s32 scaleto = filter ? g_settings->getS32("texture_min_size") : 1;
```

**Comment by Fixer-007** [comment] 2017-12-02 23:07
Rain particles are not visible.
Snow particles are rendered, but in improper way, it seems:
![16crpeb](https://user-images.githubusercontent.com/16494741/33520568-5a07e0f4-d7c6-11e7-8e27-abef488394ee.png)

**Comment by paramat** [comment] 2017-12-02 23:10
Snowflake particle https://github.com/paramat/snowdrift/blob/master/init.lua#L150
Raindrop particle https://github.com/paramat/snowdrift/blob/master/init.lua#L174
Note `size = 2.8,`

**Comment by lhofhansl** [comment] 2017-12-03 02:59
Hmm... What to do? We should scale *all* textures just because rain is weird. It seems rain relied on incidental behavior.

**Comment by paramat** [comment] 2017-12-03 03:44
Not just rain, the snowflakes are distorted too, as will be many particle textures.
The rain disappears because it is a single vertical line of pixels, textures that have more width appear distorted.
The 'size' value i'm using scales texture pixels to be equal to world pixels, so will be a much used 'size'.

**Comment by lhofhansl** [comment] 2017-12-03 07:38
But what we're saying is that texture_min_size essentially cannot be changed, since some textures rely on a specific value; 64 (and not just to avoid blurring as the documentation says).

I thought a scaling factor could be embedded directly into the textures itself...?

**Comment by lhofhansl** [comment] 2017-12-03 07:51
I can revert that patch of course, but I feel that is just hiding the problem.

**Comment by paramat** [comment] 2017-12-03 23:05
Ok i see, how about we not set `texture_min_size` not to 1 but to a larger value, the smallest value that avoids distorting particle textures?

**Comment by lhofhansl** [comment] 2017-12-05 06:56
@paramat It's not clear what value to use. It seems rain expect a re-scale to 64. Setting it to 32 (or another number) would also not be right.
1 means no scaling. I do think that a texture that needs a certain size should scale itself.

Are all particle textures of specific size? Or is there a way in the code to identify them, so that we can resize just those upon?

**Comment by paramat** [comment] 2017-12-05 07:19
> I do think that a texture that needs a certain size should scale itself.

Seems good.
I don't know the answers to your questions.

**Comment by lhofhansl** [comment] 2017-12-08 05:49
I'm going to try this out now. Perhaps there's an easy fix.

Otherwise, gents, what should we do with this?
It's not the end of the world to revert the change. The same can still be achieved by setting texture_min_size specifically.

**Comment by lhofhansl** [comment] 2017-12-08 06:00
Just testing. Snow looks fine. (filtering is off)

**Comment by lhofhansl** [comment] 2017-12-08 06:27
Nope. All fine without the texture pack as well. What's going on?

Thinking on that... A texture is mapped onto a surface. The surface determines its size, not the texture itself.
Did you both confirm that this is the issue. I'm see everything working fine.

**Comment by paramat** [comment] 2017-12-08 23:34
Will test.

**Comment by paramat** [comment] 2017-12-08 23:41
Can't reproduce on latest MT.
Fixer what are your other graphics settings?

**Comment by Fixer-007** [comment] 2017-12-09 11:58
```
anisotropic_filter = true
bilinear_filter = false
creative_mode = false
enable_damage = false
enable_waving_leaves = false
enable_waving_plants = true
fast_move = true
free_move = false
leaves_style = fancy
mainmenu_last_selected_world = 13
maintab_LAST = local
menu_last_game = minetest
mip_map = true
node_highlighting = box
server_announce = false
server_dedicated = false
trilinear_filter = false
viewing_range = 100
fps_max = 100
tone_mapping = false
mainmenu_last_selected_TP = 1
noclip = false
texture_path = 
sound_volume = 0.1
enable_shaders = false
fog_start = 0.7
enable_bumpmapping = false
enable_parallax_occlusion = false
enable_waving_water = false
generate_normalmaps = false
smooth_lighting = true
enable_local_map_saving = false
mesh_generation_interval = 5
autosave_screensize = false
enable_client_modding = true
fixed_map_seed = 
minimap_shape_round = false
world_config_selected_mod = 75
show_debug = true
fsaa = 0
specular_lighting = false
directional_shading = false
wieldview_node_tiles = false
wieldview_update_time = 2 
```

**Comment by paramat** [comment] 2017-12-10 04:24
Mihgt be anisotropic filter or mipmap. I know that mipmap has in the past made narrow detail disappear.

**Comment by lhofhansl** [comment] 2017-12-10 06:11
I tried with/without those combination. I have shaders on. Can try without them -  but I doubt it makes a difference.

**Comment by paramat** [comment] 2017-12-10 06:56
Can't reproduce with identical settings. Are you using a PR branch instead of master?

**Comment by Fixer-007** [comment] 2017-12-10 12:10
Note, I have videocard from 2005 (OGL 2.x) with beta driver from vista times, so good luck reproducing :D

**Comment by lhofhansl** [comment] 2017-12-11 06:01
OK to close this issue then?
Sorry @Fixer-007 ... The scaling of the texture really should have no effect here (it's mapped onto a surface, the scaling is just done to avoid blurriness when filtering is on).
Nor should we scale all textures (and waste a lot of graphics memory) just because some older drivers have bugs, and that only in some rare cases (like the raindrops here)

Perhaps we can add some way to overrule this optimization (I'm weary adding more config options, though)

**Comment by paramat** [comment] 2017-12-11 07:07
Fixer are you ok with enabling filters to get around this? Others may have this issue but if only one person has issues i think we may have to insist they use a workaround.
I'll close for now but can reopen if more people have issues.

**Closed by paramat** 2017-12-11 07:07 UTC
Labels: @ Client / Audiovisuals, Unconfirmed bug

**Comment by Fixer-007** [comment] 2017-12-11 15:10
I only use anisotropic filtering, bi/tri is horrible, I don't know how it renders on new videocards.
