### ISSUE TITLE
Mod manager cli/tui mode

### ISSUE THREAD

**Issue by rogilok** [minetest/minetest#12821] opened 2022-09-29 14:19 UTC
## Problem

You can only use mod manager from the graphical interface of Minetest, but you can't from command line

## Solutions

Using command line would permit to keep mod updated on servers without going to get them one by one

**Comment by rubenwardy** [comment] 2022-09-29 14:57
Duplicate of #7358

In the meantime, there's some external tools you can use. Such as https://github.com/ronoaldo/minetools

**Closed by rubenwardy** 2022-09-29 14:57 UTC
Labels: Feature request
