### ISSUE TITLE
Game textures don't overwrite core textures

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#7325] opened 2018-05-12 23:12 UTC
##### Issue type
 - Bug report

##### Minetest version
```
Minetest 0.5.0-dev-d5d248c
```

##### OS / Hardware
Operating system: macOS 10.13.4
CPU: 2,5 GHz Intel Core i5

##### Summary
All textures _but_ the engine core textures such as the minimap ones can be overridden. Make it so that core textures are overwritable too. (they are with game-wide applied texturepacks)

##### Steps to reproduce
Put a texture file in `games/game/textures` that overrwrite a core texture, for instance `player_marker.png`. Load up a world, open minimap and watch the original texture instead of the expected new one.

**Comment by SmallJoker** [comment] 2018-05-13 09:52
I cannot reproduce this issue. Does this bug also exist for you 0.4.16? Check whether you've selected the correct texture pack and whether the texture is named correctly.
![screenshot_20180513_114349](https://user-images.githubusercontent.com/1497498/39965937-189eb104-56a3-11e8-9f53-d7cedfccc80f.png)

**Comment by tacotexmex** [comment] 2018-05-14 13:58
> The issue is that the local "base" pack is handled like a regular texture pack when the texture wasn't found in the selected pack.

How to move forward?

**Comment by tacotexmex** [comment] 2018-06-02 23:12
I suspect the bug is within the PR #6032. Perhaps @red-001 can have a look?

**Comment by rubenwardy** [comment] 2022-05-04 16:13
Can't reproduce with heart.png, can reproduce with minimap_overlay_square.png. Which is weird

**Comment by grorp** [comment] 2024-02-10 20:45
Most built-in textures can be overriden correctly by the server (see also the comment by rubenwardy above). Recently, I fixed TouchScreenGUI texture overrides (#14145), so the only mentioned case that's left is minimap texture overrides.

I'm closing this as a duplicate of #3098, as that one is more specific. If there are more built-in textures that can't be overridden server-side, I think having them in separate issues would make more sense.

**Closed by grorp** 2024-02-10 20:45 UTC
Labels: Bug, @ Client / Audiovisuals, Duplicate, Textures
