### ISSUE TITLE
Mouse & keyboard on Android

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2113] opened 2015-01-12 07:40 UTC
Hi. More people connect keyboard & mouse to Android tablet (otg use).
Minetest don't support keyboard on Android.

**Comment by sapier** [comment] 2015-01-12 11:18
Low level input handling is done by irrlicht. As Irrlicht does support keyboard I'm surprised it's supposed to not work. Did you try it?

**Comment by MoNTE48** [comment] 2015-01-12 11:50
Bad mouse work and don't work change keys.
I test this now. Wait

**Comment by MoNTE48** [comment] 2015-01-12 16:30
I tested.
Keyboard:
Starting game, connected keyboard. Crash!
Connected keyboard - start game - all work. Before, i can't change keys!
Mouse:
Hmm. No crash. Camera don't work, i can press GUI button, can PRESS left key and rotate camera.
Bad...

**Comment by KodexKy** [comment] 2015-01-12 19:13
Fixed this, i'll make a PR in a few minutes after some testing.

**Comment by MoNTE48** [comment] 2015-01-12 19:36
@KodexKy ok! Wait your commit!

**Comment by est31** [comment] 2015-07-01 00:02
I can't reproduce anymore. Can this be closed?

**Comment by paramat** [comment] 2016-03-30 23:43
#2120 is merged and seems fixed.

**Closed by paramat** 2016-03-30 23:43 UTC
Labels: Android, Feature request

**Comment by farooqkz** [comment] 2023-06-23 18:40
Hello. I just tested today and the problem is not completely fixed. There seem to be keyboard support(tested with bluetooth keyboard) and mouse support for the menu(connected a mouse through OTG). But in game there is no enough support. I have to simulate touch sweep with mouse to make it work. Let me know and I can test further or record the screen.
