### ISSUE TITLE
Killing mob 💀

### ISSUE THREAD

**Issue by NSTAdventure** [minetest/minetest#12938] opened 2022-11-07 07:08 UTC
## Problem
Killing mob is really annoying because why in the world you need to tap and hold on screen to kill a mob in the minetest? 💀

## Solutions
Inspired by Minecraft allow user to Tap to kill mob instead need to tap and hold to kill mob

## Alternatives
N/A

## Additional context

**Comment by rollerozxa** [comment] 2022-11-07 07:18
duplicate of #2761

**Closed** 2022-11-07 09:14 UTC
Labels: Duplicate, Feature request

**Comment by NSTAdventure** [comment] 2022-11-07 09:17
> duplicate of #2761

Welp sorry about that :-(
