### ISSUE TITLE
Expose something like get_pointed_thing

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#4326] opened 2016-07-17 01:05 UTC
~~Add get_pointed_thing to the lua API. Could be used for collision between lines and objects/nodes (e.g. bullet collisions).~~

Add something like get_pointed_thing to the lua API, that takes a ray and gives the first thing intersected (node, object) as a pointed_thing, within a certain length.

**Comment by est31** [comment] 2016-07-17 04:59
This really is a thing that should be done by client side scripting.

**Comment by raymoo** [comment] 2016-07-17 08:01
My use-case was for something server-side. I want to create an abstraction of "point entities", points that behave sort of like entities, with movement and a step function, but aren't drawn, and have collision handling. I would use get_pointed_thing to see what they collided with in the current step, if anything.

The reason I want this is for projectiles.

**Comment by Ferk** [comment] 2016-07-17 16:57
@raymoo I think "get_pointed_thing" is client side, sent to the server to report the view of the player.

What you need is not to "expose" that, but more like implement a new server-side function that given a position and a vector returns the first colliding entity or node reached by the vector. Right?

You could actually do that in Lua too. Though maybe it'd be slower.

**Comment by raymoo** [comment] 2016-07-17 19:42
Right, though get_pointed_thing is basically that already, but on the client.

**Comment by raymoo** [comment] 2016-07-17 21:46
Updated title and issue to fit discussion

**Comment by est31** [comment] 2016-07-17 23:17
The problem is that our current get_pointed_thing implementation is O(n^3) with the distance of the selection. Its already enough that this slow implementation only affects the client. Adding it to the server would just make the problem worse.

**Comment by raymoo** [comment] 2016-07-18 08:16
It could use one of the algorithms from #4027, if it gets merged.

**Comment by stujones11** [comment] 2016-07-19 17:37
This can already be done quite efficiently from Lua using a combination of minetest.line_of_sight and some simple vector maths. See my shooter mod for example. However, it would not do any harm to add such a feature to the api.

**Comment by raymoo** [comment] 2016-07-20 00:14
I saw your shooter mod while looking for existing solutions, and I think it would work given I added something to calculate which face of a node was selected. This is probably what I would use if the API has no exact method (though probably inexact would suffice for my use case).

**Comment by stujones11** [comment] 2016-07-20 16:54
> I could use your plane collision code for this and check which face collided closer

I believe that is typically how it's done, iirc I used something similar in my micronode mod.

**Comment by juhdanad** [comment] 2016-07-22 22:41
I have started implementation, now the game is fast with 100 blocks building distance, but still doesn't support big nodeboxes (doors etc.). I hope that I will finish soon.

**Comment by beyondlimits** [comment] 2016-08-31 09:59
related: #4421

**Comment by juhdanad** [comment] 2017-07-08 08:52
#4421 is merged, only available on server side. Can this be closed?

**Closed** 2017-07-08 12:40 UTC
Labels: @ Script API, Feature request
