### ISSUE TITLE
Cloud is not rendered if darkness detection detects sky is not visible

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#6089] opened 2017-07-02 13:09 UTC
I had clouds lowered to height 40, in a big pit in mountains where I was cloud started blinking or not rendering (when noclip is disabled). Demo: https://imgur.com/a/LxY6s

@paramat says:
>clouds disappear whenever 'darkness detection' decides that sky is not visible. If you could see the sky it would be going dark at these times.

This is another downside of the current darkening sky algorithm, another is https://github.com/minetest/minetest/issues/3577

**Comment by paramat** [comment] 2017-07-02 13:55
As in #3577 this is a case of how the darkness-detection code is tuned as a balance between dark sky when above ground and bright sky when underground.
'Cloud is not rendered if darkness detection detects sky is not visible' is not an issue because this is correct behaviour, we do not want to render clouds when underground.
Not a bug, more a request for better-tuned darkness-detection code.

**Comment by paramat** [comment] 2017-07-03 11:31
So actually this is a duplicate of #3577

**Closed by paramat** 2017-07-03 11:31 UTC
Labels: @ Client / Audiovisuals, Request / Suggestion
