### ISSUE TITLE
Pressing enter key on advanced settings edit window makes edit window appear again

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4380] opened 2016-07-29 11:00 UTC
Tested in: 0.4.14.

How to reproduce it:

* Open advanced settings
* Go to any string-based setting
* Edit it by pressing the edit button
* Enter some value
* Hit the Enter key

Expected result: The window closes, saves the setting and returns you to the advanced settings window
Actual result: The window closes when you hit the enter key, but as soon you release it, you will immediately be returned to the edit window again.

**Comment by rubenwardy** [comment] 2016-07-29 12:04
#4295

**Comment by Rogier-5** [comment] 2016-07-29 12:07
This is a duplicate of #3637.

**Comment by est31** [comment] 2016-07-29 17:02
Dupe of #3637

**Closed by est31** 2016-07-29 17:02 UTC
