### ISSUE TITLE
remember password in client

### ISSUE THREAD

**Issue by cornernote** [minetest/minetest#3019] opened 2015-08-07 12:54 UTC
could the client remember my password?  it's getting painful to have to type it every time

if not everyone wants this, perhaps a checkbox to allow remembering

**Comment by ProgrammingChicken** [comment] 2015-08-07 16:24
+1, all I have to say.
I think it should be off by default and then you could turn in on minetest.conf.

**Comment by est31** [comment] 2015-08-08 06:51
I have written a [password manager](https://forum.minetest.net/viewtopic.php?f=14&t=11116) for the client, you can use it until we get native support.

For native support, the passwords should probably be encrypted, and accessible through some master password like mechanism.

**Comment by LazyJ** [comment] 2015-08-08 17:01
+1 for the check-box option whether or not to let Minetest remember the password.

+1 for encryption.

Perhaps giving Minetest better copy/paste support would help for those people who already use a stand-alone password manager so they can copy their password from their password manager and paste it into Minetest. I would like to use a different password for each server I visit. Also, by copy/pasting from my stand-alone password manager, I could use longer, more convoluted, "stronger" passwords.

**Comment by est31** [comment] 2015-08-09 10:16
The copy paste problem is [fault of irrlicht](http://sourceforge.net/p/irrlicht/bugs/435/), not ours. Otherwise, if you know a way to read the clipboard on linux X11 in C++, it would most likely be useful.

**Comment by yo-we** [comment] 2015-09-20 19:21
Certainly a feature, a moderator/administrator using a password protected account might want to use. Please consider the use case of many of our "player" users: unprotected computer accounts and already enough trouble coming from brothers/sisters/friends hacking each others password. Adding a password remember functionality can be considered security breach, because being logged into the computer (OS session not password protected or not locked on AFK) would be sufficient to start a Minetest game using the last credentials used.

**Comment by red-001** [comment] 2016-02-05 18:54
+1 a password manager would be very useful. Encryption would be nice but not vital.

**Comment by 0-afflatus** [comment] 2016-02-17 19:52
I know how to read Linux clipboards (there are 2) in Python but I'm not a C++ programmer. Surely some sort of hash table lookup wouldn't be too difficult to implement.
@yo-we that's a problem, sure, but not remembering passwords won't stop brothers/sisters/friends blatantly sharing accounts, but I suppose it might prevent them taking advantage of each others' stupidity. Off by default and bury the remember password option in advanced settings? idk

**Comment by rubenwardy** [comment] 2017-08-26 02:57
duplicate of #1566

**Closed by rubenwardy** 2017-08-26 02:57 UTC
Labels: @ Client / Audiovisuals, Feature request
