### ISSUE TITLE
Odd floating things in carpathian mapgen

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6349] opened 2017-08-30 13:57 UTC
The terraced mountains in the carpathian mapgen sometimes have these odd floating things:

![](https://i.imgur.com/KtrkxLA.png)
![](https://i.imgur.com/oldNAGm.jpg)
![](https://i.imgur.com/z2FcTQw.jpg)

Coordinates, seed and version in screenshots.

It doesn't happen always, but it's also not really rare. While this is nothing serious, it might be improved.

**Comment by paramat** [comment] 2017-08-30 17:04
Probably some kind of interaction between terracing noise and 3D noise.
Something for @vlapsley

**Comment by Fixer-007** [comment] 2017-08-30 19:49
It is quite rare phenomena, here is mine:
![default](https://user-images.githubusercontent.com/16494741/29891889-59a4b762-8dd5-11e7-93a4-e4a3b54a01a1.png)

**Comment by paramat** [comment] 2017-08-30 22:57
Wow that is weird, maybe the mapgen author will want to work on those, if they're rare i don't see a big problem.

**Comment by vlapsley** [comment] 2017-08-30 23:35
I think the problem is that 3D noise is applied twice to the terraced mountains.

The getSteps function uses two noises, one of which is the 3D noise I used to give the mountains some features like over hangs, or that cool arch in @Wuzzy2  second screenshot.

```
// Step (terraced) mountains
float step_mnt = hilliness * getSteps(n_step_mnt, fabs(mnt_var));
```

But, I had already applied the 3D noise for mountain variations in the hilliness function:
```
// Hill/Mountain height (hilliness)
float hill1 = getLerp(height1, height2, mnt_var);
float hill2 = getLerp(height3, height4, mnt_var);
float hill3 = getLerp(height3, height2, mnt_var);
float hill4 = getLerp(height1, height4, mnt_var);
float hilliness = std::fmax(std::fmin(hill1, hill2), std::fmin(hill3, hill4));
```

I'll have a play around using a different 2D noise in the getSteps function.

I think it would be ideal to remove excessive floating stone, especially that eyesore in @Fixer-007 screenshot.

**Comment by vlapsley** [comment] 2017-09-01 22:37
PR incoming.

I've removed the 3D noise from the getSteps function and hardcoded the width to 0.5 instead.
This stops the ribboning effect in @Wuzzy2 screenshots.
Alsop reduced the persistence on 3D mnt_var noise to 0.55. This gets rid of the floating blob in @Fixer-007 screenshot.

@Wuzzy2 

![](https://i.imgur.com/jLY9N4p.png)
![](https://i.imgur.com/An5gsV0.png)
![](https://i.imgur.com/2EwteMq.png)

@Fixer-007 
![](https://i.imgur.com/XByJMyJ.png)

**Comment by paramat** [comment] 2017-09-01 23:39
Maybe the blob in fixer's screenshot will look more acceptable due to the other changes?
Reducing persistence to remove a particular floating blob will not stop other floating blobs, however if you remove all floating blobs then the 3D noise will become too weak and boring. A balance is needed.

**Comment by vlapsley** [comment] 2017-09-02 00:29
The blob in fixer's screenshot becomes exactly that with persistence 0.6. A solid floating blob. Sorry, not at my computer now to screenshot it. 

What I did find is that with persistence at 0.55 the 3D features remain but are smoothed out and some floating objects removed. 

Each mountain type - hill, ridge and terrace - has the 3D noise applied to it. So when the noise for each of those mountain types is high you get those spectacular mountains with 2 to 3 times the 3D noise for some strange effects. 

I checked up on some of my favourite weird 3D spots and they still look roughly the same.

**Comment by paramat** [comment] 2017-09-02 02:30
Ok, it's up to you. I'm just concerned about this fast change compared to your months of tuning. it might be better to fix the double application of 3D noise now but leave tuning persistence to a later PR so you have more time to tune and consider it.

**Comment by paramat** [comment] 2017-09-08 02:43
#6360 merged.

**Closed by paramat** 2017-09-08 02:43 UTC
Labels: @ Mapgen, Bug, Request / Suggestion
