### ISSUE TITLE
Player does not move using WASD, mouse is very fast and spins pointing directly up or down

### ISSUE THREAD

**Issue by jcalfee** [minetest/minetest#7812] opened 2018-10-22 16:34 UTC
##### Issue type
 - Bug report

##### Minetest version
```
0.4.17.1
```

##### OS / Hardware

Operating system: debian:stretch
CPU:Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz

##### Summary
These keys do move (they do nothing):  W, A, S, D | Move

The mouse look around is very very fast and mostly just spinns on the floor or sky.  It is really impossible to use but it can look around, it feels like there are only 2 pixles worth of mouse movement to work with though.

##### Steps to reproduce

Just enter any game.

**Comment by SmallJoker** [comment] 2018-10-22 17:58
Change your mouse sensitivity setting (GUI requested in #6730 ), is a duplicate of #7343.
In my case the setting was way too low, increased it to 0.75.

What exactly is the issue with the keys? The player moves but you don't press anything? Unplug the joystick.

**Comment by jcalfee** [comment] 2018-10-22 22:05
Player does not move at all using W, A, S, or D

**Comment by rubenwardy** [comment] 2018-10-22 22:20
Do you use Wayland? What about Wayland X etc?

**Comment by jcalfee** [comment] 2018-10-22 22:31
Interesting, other keys are working so I did not really think about this being a factor ..

Looks like x11docker is using xpra:
```bash
x11docker: Xpra server command:
  xpra start :110 --use-display  --webcam=no --start-via-proxy=no -z0 --no-speaker --no-pulseaudio --daemon=no --fake-xinerama=no --notifications=no --file-transfer=off --printing=no --html=off --systemd-run=no --mdns=no --dpi 96 --clipboard

x11docker: Xpra client command:
  xpra attach :110  --webcam=no --start-via-proxy=no -z0 --no-speaker --no-pulseaudio --daemon=no --fake-xinerama=no --notifications=no --file-transfer=off --printing=no --html=off --systemd-run=no --mdns=no --dpi 96 --clipboard --window-close=shutdown
```

I had some success changing to `xephyr` ..  I'll provide more files if your interested in re-creating this in Docker..

**Comment by paramat** [comment] 2018-10-23 06:54
> mostly just spinns on the floor or sky

This has happened before to some players, it's caused by your setup or hardware, or by having a controller or joystick plugged in. It's not a MT bug.

**Comment by Calinou** [comment] 2018-10-23 07:33
This sounds similar to issues seen when playing Minetest in VirtualBox with mouse integration enabled. I don't think much can be done on our side.

**Closed** 2018-10-23 12:08 UTC
Labels: @ Client / Controls / Input, Unconfirmed bug
