### ISSUE TITLE
Games start occasionally all white or black or with exaggerated bloom

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#13190] opened 2023-02-06 05:39 UTC
Last MT built from master.
Start any game, sometimes the window is white, sometimes black, sometime bloom seems extra strong.
Just starting the game again fixes it usually.

Happens in 5-10% of starts.

**Comment by lhofhansl** [comment] 2023-02-06 05:40
@x2048 FYI.

**Comment by kilbith** [comment] 2023-02-06 13:17
Can confirm. No easy way to reproduce to supply here.

**Comment by rubenwardy** [comment] 2023-02-06 13:30
@LoneWolfHT posted this a few days ago:

![image](https://user-images.githubusercontent.com/2122943/216984169-f9eeffcd-207b-4dba-98ac-2c9772eb0d8f.png)

**Comment by NathanSalapat** [comment] 2023-02-06 13:58
I've experienced the same thing, doesn't seem to be any sure way of reproducing the issue.

**Comment by LoneWolfHT** [comment] 2023-02-06 15:31
When it happens for me it doesn't stop until I restart my client. Disabling bloom fixes it

**Comment by lhofhansl** [comment] 2023-02-07 06:23
#13151 related?

**Comment by x2048** [comment] 2023-02-08 00:14
Does disabling bloom or dynamic exposure avoid the problem?

**Comment by x2048** [comment] 2023-02-08 00:15
@lhofhansl  #13151 was fixing a similar issue due to textures being uninitialized, but there might be more with e.g. uniforms

**Comment by lhofhansl** [comment] 2023-02-08 21:53
I have dynamic exposure off, and it was still happening.

**Comment by x2048** [comment] 2023-02-09 20:51
Can someone try to repro the white screen with `enable_bloom_debug` set to true and post screenshots here?

**Comment by x2048** [comment] 2023-02-09 21:04
I have collected these cases (thanks to @kilbith):
![image](https://user-images.githubusercontent.com/4933697/217938295-4d8f9163-cfc9-482b-99a9-8148b796d7b0.png)
![image](https://user-images.githubusercontent.com/4933697/217938554-e6c8d238-edeb-4036-b6d3-8763d36b2fe8.png)
![image](https://user-images.githubusercontent.com/4933697/217938593-808be5cd-646d-4682-8a3f-417cf1bfd832.png)
![image](https://user-images.githubusercontent.com/4933697/217938632-e5b43a00-7247-40de-b587-9e5feeff7a92.png)

**Comment by kilbith** [comment] 2023-02-09 21:29
One another special case:
![Capture d’écran du 2023-02-09 20-42-05](https://user-images.githubusercontent.com/7883281/217943265-7c01eab3-66e9-4c3d-82b9-078e2203b230.png)

**Comment by Zughy** [comment] 2023-02-10 20:38
Closing, considering https://github.com/minetest/minetest/pull/13197#issuecomment-1425166521

**Closed by Zughy** 2023-02-10 20:38 UTC
Labels: Bug, @ Client / Audiovisuals, Shaders
