### ISSUE TITLE
[windows] game crash with unicode char in worldname

### ISSUE THREAD

**Issue by wwwutz** [minetest/minetest#5822] opened 2017-05-26 08:34 UTC
My 10yo daughter found this bug, so I'm reporting it on her behalf 8-)

How to reproduce:
Setup: Minetest 0.4.15, running on Windows 7/64-bit, german.

Start game, singleplayer, "new",  worldname `Gummibärchen` ( sigh ). 

![bugpic-1](https://cloud.githubusercontent.com/assets/463828/26487056/198117c0-41fe-11e7-95ae-0f4c515eca70.jpg)

Create.

![bugpic-2](https://cloud.githubusercontent.com/assets/463828/26487125/6c428ea8-41fe-11e7-8b37-93fde7b5a882.jpg)

So far so good.  "Play". click. Crash:

![bugpic-3](https://cloud.githubusercontent.com/assets/463828/26487148/82ede2a6-41fe-11e7-8e4f-ae75fe56ac96.jpg)

So it looks like we've got a filename-character encoding issue here:

![bugpic-4](https://cloud.githubusercontent.com/assets/463828/26487173/9e27d946-41fe-11e7-9b18-25d672fd4672.jpg)

anything else I could provide ?

**Comment by Zeno-** [comment] 2017-05-27 04:49
I like how you had to pretend that your daughter found it just because you named your world Gummibärchen (there was no need to be ashamed)

**Comment by Ekdohibs** [comment] 2017-08-27 11:58
As a solution, I guess encoding the world name with some encoding like in URLs should keep backwards compatibility and allow unicode characters in world names.

**Comment by rubenwardy** [comment] 2018-04-03 16:53
Duplicate of #3588

**Closed by rubenwardy** 2018-04-03 16:53 UTC
Labels: @ Startup / Config / Util, Bug, Windows
