### ISSUE TITLE
["Feature Request"] Stop crashing the entire server because "a nil value"

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#2715] opened 2015-05-22 20:23 UTC
Hi, it would be great if nil values on mods weren't fatal.
See this for example. https://github.com/VanessaE/homedecor_modpack/issues/277

One of the ways to fix that on mods is to just ignore the nil value. Why can't that be implemented on the server itself?

**Comment by PilzAdam** [comment] 2015-05-22 20:26
Duplicate of #2507.

**Closed by PilzAdam** 2015-05-22 20:26 UTC
