### ISSUE TITLE
Entities glitching inside solid nodes

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#5966] opened 2017-06-11 16:47 UTC
For some reason entities seem to be glitching inside solid nodes...  Examples of this can be seen in the soccer mod where the ball ends up embedded inside a wall at times and mobs walking through nodes they shouldnt be able to...  Physical=true is set for both.

Addition: When stepheight is set to 1.1 mobs can walk inside solid walls at the weirdest of times.

//////////
EDIT by paramat: From IRC:
14:39 tenplus1     I has issue with entity collision
14:40 tenplus1     if stepheight is set to 1.1 and it's a 2 high stone wall around entity, it can still glitch UP onto top of wall
14:41 tenplus1     seems entities can glitch up onto a block even if the one above is solid and many a mob user is complaining about this one

**Comment by Fixer-007** [comment] 2017-06-11 19:05
Dupe of https://github.com/minetest/minetest/issues/5482 ?

**Comment by stujones11** [comment] 2017-06-11 20:09
@Fixer-007 I am not sure that is the same problem, I noticed this same issue was recently reported on the forums.

@tenplus1 My best guess would be related to the stepheight and settable player collision box changes as those were not completely reverted, or more accurately the attempts at fixing them were not. I cannot quite see how that would cause this but I would suggest you begin bisecting from 5e04f1a3357a618bed6d36b6a7439279b758fc8e ;-)

**Comment by tenplus1** [comment] 2017-06-12 05:42
I'd love to start bisecting code but am no c++ programmer, I just notice players on servers having issues with entities disappearing and dying inside walls and blocks they should not be moving into.

**Comment by IhrFussel** [comment] 2017-06-12 10:27
Can confirm and it already happened back in 0.4.15-dev from May 24 AFAIK...

Tamed animals are fleeing with this glitch if the walls are only 1 node wide

Please fix it ASAP! It breaks part of the gameplay on many servers.

**Comment by tenplus1** [comment] 2017-06-12 15:11
Could this be related in anyway : https://github.com/minetest/minetest/issues/5970

**Comment by Fixer-007** [comment] 2017-06-14 19:58
While testing PR 5973 I observed this bug:
1) bunch of entities after TNT explosion scattered near walls 
2) new TNT explosion below clearly pushes some entity completely into sand

**Comment by jeremyshannon** [comment] 2018-10-22 21:45
I've been looking to find the origin of this bug in order to bisect it, but I got back to 0.4.13 and I've still got mobs glitching out through a four-block high obsidian glass wall.
 Now in order to keep going, I need to swap out mobs redo for an older version that'll work with 0.4.12, but I'm done for the afternoon, so I figured I'd post my progress in case someone else wants to take a look at this before I get back to it.
 Can anybody remember a time when mobs couldn't slip through solid nodes?

**Comment by tenplus1** [comment] 2018-10-23 06:48
@jeremyshannon - even back when simple_mobs was in use they somehow managed to escape when stepheight was set higher than 1.0

**Comment by scrain777** [comment] 2020-06-27 01:10
I've been looking at the collision code `collisionMoveSimple()` and noted several problems.  I'm planning to try tackling them, but I haven't set up a dev environment for this project yet, so it may take me a while.

1. stepbox is used to detect collisions with the ceiling when stepping up, but it is computed at time dtime instead of nearest_dtime, so is checking in the wrong location.
2. Even if stepbox were in the location of the collision, it would only check adequate clearance at the step up, not enough clearance to actually go on top of the collision box.
3. After a step up is identified, the search for additional collisions, possibly with step ups, continues along the original trajectory instead of the stepped up trajectory. That is, the entity travels through solid nodes and only remembers that when it reaches dtime it should jump up.
4. If there are multiple steps up identified, the entity is sent up the sum of them all, but clearance is only checked for each independently.
5. The bounding box used to select nodes for potential collisions may not be large enough if there are step ups and/or bouncing back from collisions.
6. If the velocity vector is not horizontal and there are multiple step ups, the amount of final step up may be less than naively calculated as the sum of the step ups.
7. If the entity is higher than the bottom of the collision box, it can step onto the collision box with a smaller step than the full height of the collision box. However, the code steps it up the full amount anyway.
8. The code is close to optimal for small velocities where the number of passes through the loop searching for collisions is small, but at higher speeds (I am thinking glider mods, for example) there will be more collision boxes (order speed cubed) to search through and the outer loop will need to be executed more times (order speed, total of order speed to the 4th tests of collision boxes). We should consider a different data structure for bounding boxes that scales better.

**Comment by TheTermos** [comment] 2020-06-27 11:16
> I've been looking at the collision code `collisionMoveSimple()` and noted several problems.

The issues mentioned in your post and in the OP should be fixed in current dev (#9764), the fixes are to come with 5.3

Possible close?

**Comment by scrain777** [comment] 2020-06-27 22:15
I have now reviewed the code on the stable-5 branch.
1. For sake of discussion, imagine entity moves forward, collides, might step up. Now the test for headroom is done before moving forward, so conceptually the motion is Step up...Move forward. However, there is no test that there will not be a new collision while moving forward from the stepped up location. Should test for headroom at nearest_dtime instead.
2. I do not see a change that would impact this.
3. I do not see a change that would impact this.
4. This appears fixed.
5. I do not see a change that would impact this.
6. This appears fixed.
7. This appears fixed.
8. I do not see a change that would impact this, but we should get correct behavior before optimizing performance.

**Comment by TheTermos** [comment] 2020-06-29 07:02
> entity moves forward, collides, might step up. Now the test for headroom is done before moving forward, so conceptually the motion is Step up...Move forward. However, there is no test that there will not be a new collision while moving forward from the stepped up location. Should test for headroom at nearest_dtime instead.

This solution actually seems quite similar to the one in 5.2-stable, and it would glitch for very similar reasons.
Try to analyze the code with the assumption stepheight is greater than movingbox height.

Step up is imo quite crappy mechanic because it involves instantaneous position shift, it works allrightish but only within reasonable parameters, so I wouldn't try too hard to make it work for extremes.
Another solution that had been considered was to limit stepheight to min(stepheight, box height), but old mob mods typically use extreme stepheight values instead of proper jumping, so that would be seen as breakage.

**Comment by scrain777** [comment] 2020-07-09 05:52
I just opened PR #10166 with unittests built around the issues I identified. In the process, I learned more about how the collision code works, and surmised more of the physics.

Current status of my numbered points:
1. [FAIL] testCollisionMoveSimple_ceiling
2. [PASS] testCollisionMoveSimple_stepuproom
3. This was based on misunderstood physics. The correct understanding seems to be that the entity steps over the obstacle and continues along the original trajectory. However, there are still problems with catching all the obstacles along the way, highlighted in [FAIL] testCollisionMoveSimple_longclimb
4. This was based on a mistake in my reading of the code. The entity does not step up for each collided node, but only to escape being engulfed in the final collided node. Essentially it is stepping over all of the earlier collisions.
5. [FAIL] testCollisionMoveSimple_longclimb; [FAIL] testCollisionMoveSimple_bouncy
6. This was based on misunderstood physics. I am actually not at all sure what the physics ought to be, so I didn't make any test cases.
7. [PASS] testCollisionMoveSimple_shortstepup

**Comment by scrain777** [comment] 2020-07-12 21:34
I just added another unittest to PR #10166 for an edge case that is failing. If an entity collides into the exact corner of a collision box while moving at an angle so that it is carried into the collision box, the collision is not detected because no face-to-face collision ever happens.

**Comment by scrain777** [comment] 2020-07-14 01:16
Is there value in a total rewrite of the collision code? It couldn't be merged anytime soon because it would require substantial testing to make sure it doesn't make game play worse in other ways. I am working on such a rewrite leveraging an inverted index data structure. Currently I am implementing the data structure and base algorithms. Will take a while.

**Comment by TheTermos** [comment] 2020-07-14 20:21
> Is there value in a total rewrite of the collision code?

I'd say yes, but only after #9346 is resolved.
All the issues you've been raising are known to me, they can happen under **extreme conditions** like those in your unit tests (which by the way are impossible for players, not sure about entities), but you must understand your proposition to use nearest_dtime would fail under **typical conditions** and create exactly the same problems as described in the OP, which by the way are now fixed.

> If an entity collides into the exact corner of a collision box while moving at an angle so that it is carried into the collision box, the collision is not detected because no face-to-face collision ever happens.

Yup, I'm out of ideas how to make it work with 32 bit precision and cleanly, but currently this case is handled by clipping recovery  which is necessary anyway because of much bigger problems due to incorrect client-server model (#9806)

@sfan5 the issues listed in the OP refer to the old code and are resolved to my knowledge, should any new issues arise, they should be well, new issues imo.

**Closed** 2020-07-14 20:40 UTC
Labels: @ Server / Client / Env., Bug
