### ISSUE TITLE
Liquids need better mechanics.

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2767] opened 2015-06-09 04:07 UTC
The flowing of liquids need to be improved. Firstly, a none source liquid node will not flow downwards, sometimes creating weird areas where lava or water are floating above air when they are not full source nodes...

**Comment by est31** [comment] 2015-06-09 14:02
@proller has had many fights about proper liquids. I guess its a design descision to have limited liquids in Minetest.

**Comment by rubenwardy** [comment] 2015-06-09 14:10
Finite liquid was added, but was then removed because it was too slow / done badly (IIRC). Proller will deny this, ofc.

Isn't the point of Minetest to be customisable fully? Then why are they making such design decisions in Minetest?

**Comment by paramat** [comment] 2015-06-09 21:46
Certainly true that water flow needs improving and is glitchy. nanepiwo is not, i think, suggesting finite liquid but is noticing how liquid spreads out on ignore nodes. This issue is probably a duplicate.

**Comment by nanepiwo** [comment] 2015-06-13 19:11
@paramat The referenced issue is only one of the issues with flowing items such as water.

**Comment by 4aiman** [comment] 2015-06-24 13:43
Finite liquids are done in FM and those are quite good ATM.

Regardless of approval or denial by @proller or @rubenwardy the fact that former has improved finite liquids a lot still stays true. He spent 2+ years on finite liquids and the speed and behaviour of those *is* impressive. 

Too bad MT can't use FM's codebase.
For that matter I don't want to return finite water in the state it was in MT - that really wasn't so great and needed some serious treatment (which it got in FM).

The problem, however, is that if a not-source liquid will "fall down" then it might get removed completely because of the absence of the source node nearby.

That being said, a bug like this should get an assigned person to fix it.

**Comment by paramat** [comment] 2015-06-28 07:58
The devs (and myself) will not want finite liquids back in any form. One effect is that any above-water-level rivers slowly drain away into the ocean, yes this can be fixed by adding infinite sources at the river top, but this all creates a huge processing load to create somethng that can be done statically with our current system. We are already struggling with a huge water processing load and cannot cope with more.

**Comment by 4aiman** [comment] 2015-06-28 11:39
So basically, we (users & devs) are in agreement that liquids need improvement.

What directions (aside from decreasing processing time) liquids improvement may go?

**Comment by C1ffisme** [comment] 2015-06-28 12:40
I could give a to-do list. I got a few ideas.

**Comment by 4aiman** [comment] 2015-06-29 08:13
Go ahead, @C1ffisme !
Maybe some of those would be considered useful (at least for adding those to 0.5 roadmap)

**Comment by asl97** [comment] 2015-06-29 08:47
don't spread on ignore node should be near the top of the list

**Comment by 4aiman** [comment] 2015-06-29 09:37
> don't spread on ignore node should be near the top of the list

Never happened to me... Water just doesn't flow horizontally to ignore.

But what *did* happen is the ```killer water``` feature.
I won't tell *how* I managed to achieve this (so this won't be made impossible).
But I *will* show everyone the consequences ;)
[Polterwater on youtube](https://youtu.be/qlPIbT__trU)

**Note:** I *do* use custom build, but I did *not* change anything liquids-related in C++.

**Comment by C1ffisme** [comment] 2015-06-29 17:10
Here is some ideas. This isn't a todo list, but just a few ideas.
* Don't spread on ignore (thanks @asl97 !)
* Add a flowing_radius setting (Notice how lava in minecraft dosen't flow as far as water)
* Make water and lava push things when they flow (Useful for conveyor belts)
* Make flowing water have a flowing_param to get how far from the source it is.
* Instead of river water, maybe add a water_color feature which would ajust the color of the texture (Saves on nodes, and you don't need to add it to your list of aliases.)
* There's more, but my brain needs time to think. I'll add suggestions as I think of them. Just keep posting comments here so I see this issue in my messages.

**Comment by asl97** [comment] 2015-06-29 20:25
@C1ffisme  Instead of a water_color feature, it should be a color feature that is able to apply to all nodes.

@4aiman custom server or client or both?

it seem like it was done using a `on_enter`/`on_step` function, that would be cool if those feature exists (for all node of course, should be done on client side)

or maybe an adm/globalstep with a flag but there wasn't any damage lag so i doubt it

**Comment by C1ffisme** [comment] 2015-06-30 00:39
@asl97 Yes, that should be added. For grass, etc. It should also be available when using get_node and set_node.

**Comment by paramat** [comment] 2015-06-30 04:27
> don't spread on ignore node

This is the important one to fix.

> Add a flowing_radius setting

We already have this =) see river water 'liquid_range'.

> Instead of river water, maybe add a water_color feature

River water actually has different properties, a flow range of 2 and is non-renewable.

**Comment by 4aiman** [comment] 2015-06-30 06:30
> Add a flowing_radius setting
Just wanted to say that ;)

> Instead of river water, maybe add a water_color feature
I'd rather have "biome_colour"  :)
There's an issue about this. Ppl seem to finally be *for* the changes.

The only thing *against* coloured water is the way it's drawn.
I've been messing up with a redwater_source for a couple of days...
It *is* a horrible sight, the water border of 2 biomes.

@asl97 
It's pure Lua - no C++ changes.
*No* methods were involved into doing that. 
The only thing which was messed up with was the definition of a water_source node. 
This behaviour is totally reproducible within *any* build compiled within last year or so, both client *or* server. 

Also, what is ```on_enter``` method?

**Comment by rubenwardy** [comment] 2015-06-30 08:51
> Also, what is on_enter method?

I guess he means a callback which triggers when a player enters a node.

**Comment by 4aiman** [comment] 2015-06-30 13:49
@rubenwardy 
Does MT have one?
I'm still using late April's build.

**Comment by rubenwardy** [comment] 2015-06-30 14:07
No. Est was talking hypothetically.

Water hurting you is probably due to drowning.

**Comment by asl97** [comment] 2015-06-30 14:21
@rubenwardy Est wasn't the one who said it

@4aiman just to clarify, when i said on_step, i mean on_step_on, something that could maybe be use in mesecons_pressureplates:pressure_plate_wood to replace the timer it is currently using.

**Comment by 4aiman** [comment] 2015-07-01 08:59
@rubenwardy 
> Water hurting you is probably due to drowning.

Nope :)

@asl97 
Ok, got it :)

```on_step_on``` would be a performance killer. Also, timer can be set to dtime>server_step.
In the worst scenario ```on_timer``` should be (*IDK whether it is really so*) as slow as the ```on_step_on``` while providing much more "abilities".

This *is* offtopic, but I'd rather vote for adding some params to ``on_timer`` like ```node``` and ```pos``` than adding one more call of a on_globalstep type.

**Comment by asl97** [comment] 2015-07-01 09:38
@4aiman it shouldn't be that much of a performance killer, there should already be some kind of check on the node being step on in the client since there is the step sound, adding another check shouldn't decrease the performance that much.

**Comment by 4aiman** [comment] 2015-07-01 09:41
> there should already be some kind of check on the node being step on

Good point, @asl97  :sunglasses:

**Comment by asl97** [comment] 2015-07-31 14:34
https://github.com/minetest/minetest/pull/2977 < don't spread on ignore fix?

**Comment by red-001** [comment] 2015-07-31 14:36
asl97 because it is.

**Comment by red-001** [comment] 2015-07-31 14:45
Could liquids be updated on chunk load?

**Comment by 4aiman** [comment] 2015-07-31 15:03
> Could liquids be updated on chunk load?

Falling nodes also need this.

**Comment by red-001** [comment] 2015-07-31 15:05
I agree
I don't think it would be hard to add.

**Comment by red-001** [comment] 2015-07-31 15:06
I will try when I have some free time.

**Comment by 4aiman** [comment] 2015-07-31 16:38
Oh, I've remembered one more thing: liquid vs liquid mechanics.

**Comment by red-001** [comment] 2015-07-31 16:42
?
what do you mean?

**Comment by 4aiman** [comment] 2015-07-31 16:57
It's to long to describe... I'd better tall how to reproduce ^_^

1. use mgv5 or mgv7
2. register 2 biomes with different water node (see paramat's thread @ minetest.net for details)
3. go to the ocean at the border of biomes with those 2 liquids
4. notice how strange is the way those get mixed due to flowing, map updating and map generation lags.

**Comment by red-001** [comment] 2015-07-31 18:36
can you just post a screenshot?

**Comment by 4aiman** [comment] 2015-07-31 20:55
I can't.
1. can't access my PC atm
2. this is something that should be viewed as a "process", not a "state".

Thus, the best way is to register a new biome...

**Comment by paramat** [comment] 2016-04-02 23:19
Updating liquids that stopped at an ungenerated mapchunk has been attempted, it's difficult.

**Comment by est31** [comment] 2016-04-03 10:30
Just don't close it just because its "difficult"

**Comment by paramat** [comment] 2016-04-04 02:37
I don't intend to,

**Comment by paramat** [comment] 2016-10-27 08:22
Liquids no longer spread out on top of ignore.
Millersman has improved liquid behaviour and is working on making stuck liquids reflow.

**Comment by paramat** [comment] 2017-03-21 20:34
@nanepiwo liquids have improved a lot now, are there any remaining issues for this thread to remain open?

> sometimes creating weird areas where lava or water are floating above air when they are not full source nodes...

Is this still happening for you, please could you post a screenshot?

**Comment by Fixer-007** [comment] 2017-03-22 00:10
Floating water is fixed, if you still see it, try getting closer to activate it - it will flow down for sure, I tested this with lots of bugged liquids and everything is working.

**Comment by paramat** [comment] 2017-03-22 00:21
Yes i now see that is what is being referred to here, closing.

**Closed by paramat** 2017-03-22 00:21 UTC
Labels: @ Server / Client / Env., Bug, Feature request, Possible close
