### ISSUE TITLE
Allow digging animation speed to be adjustable

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#12905] opened 2022-10-28 15:44 UTC
## Problem

The speed at which you dig nodes feels very slow by default. It feels as if the player has constant mining fatigue.

## Solutions

Allow the digging animation speed to be changeable in the settings. For example, `1.0` would be the default, while `2.0` would be double the default (this is about the speed at which MineCraft has the digging animation speed). The higher the digging speed, the faster the digging animation plays out.

Changing the digging animation speed should also change the frequency at which the node digging sound plays out.

## Additional context

Changing the digging animation speed should NOT affect the speed at which you break nodes, and should purely be visual and audial. I am NOT talking about the speed at which the node actually gets dug.

**Comment by Zughy** [comment] 2022-10-28 22:49
Duplicate of #9876

**Closed by Zughy** 2022-10-28 22:49 UTC
Labels: Feature request
