### ISSUE TITLE
[Feature Request] mesh hud elements

### ISSUE THREAD

**Issue by Elkien3** [minetest/minetest#8195] opened 2019-02-08 16:44 UTC
##### Issue type
 - Feature request

It would be nice for lua mods (both server and client) to be able to make their custom mesh hud elements, similar to the wielditem on the existing hud.

Ideally, it would be affected by lighting like the wielditem (perhaps with a setting to have it unlit, if someone wanted to make fancy huds) and a way to play or set animations of the item.

This would allow for precise mesh position for things like aiming down gun sights.
You can sort of see the bobbing messing up the sight position in this [video](https://www.youtube.com/watch?v=KDjWnz-iwl8). I can make another to better demonstrate it if anyone wants.

It would also be nice to animate the wielditem itself; the item would play its own animation, but it still would be effected by bobbing.

This would be used for gun reloading, and things like bows and compasses which have to change the item a few times to look animated, but you would still want the nice builtin bobbing and sway.

You can also see in the video above how unwanted the punching animation can be, so an option to disable it for certain items would be awesome as well.

It's probably too hard to implement but I think it's worth discussing.

**Comment by ClobberXD** [comment] 2019-02-09 08:07
Possible duplicate of #3551

**Closed** 2019-02-09 13:07 UTC
Labels: Duplicate

**Comment by Elkien3** [comment] 2019-02-09 15:12
(If anyone still sees this) Would you suggest I talk there about custom hud meshes and/or a way to disable wielditem movment, and/or items that are animated while in hand?

**Comment by SmallJoker** [comment] 2019-02-09 16:01
Alternative duplicate of #2811
