### ISSUE TITLE
Issues with formspec ordering

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#9103] opened 2019-11-10 15:50 UTC
`git bisect` confirmed that 5506e97ed897dde2d4820 causes at least two regressions:

- The formspec ordering is enforced regardless of the `formspec_version` (supposed to take effect only for >= 3).
- The default tooltips associated with the `item_image_button` aren't showing anymore.

You can test with `craftguide`: https://github.com/minetest-mods/craftguide

In this example, the `image` is declared before the `item_image_button` element:  https://github.com/minetest-mods/craftguide/blob/master/init.lua#L848-L856

`formspec_version` ain't specified in `craftguide` so it's assumed to be `1`. Regardless of that, `image` is drawn on top of `item_image_button`.

**Cc:** @DS-Minetest @SmallJoker

**Comment by DS-Minetest** [comment] 2019-11-10 19:21
If I understand correctly, `item_image`s should always be drawn after normal images in version < 3. The problem in the sorting function is that the `item_image`s are bound to buttons.
This might be fixable by treating `item_image_button`s like `item_image`s here:
https://github.com/minetest/minetest/blob/4d668f32a6d9a0d895a2385dec994d43bd084410/src/gui/guiFormSpecMenu.cpp#L3026-L3039
(Images drawn between button background and item image front would however still not be possible (but that's endurable I guess).)

The tooltip problem is probably caused by the `item_image` being on top of the button.
Maybe this can be fixed by giving the `item_image` `FieldSpec` the same name as the `button` `FieldSpec`:
https://github.com/minetest/minetest/blob/4d668f32a6d9a0d895a2385dec994d43bd084410/src/gui/guiFormSpecMenu.cpp#L2008-L2019
https://github.com/minetest/minetest/blob/4d668f32a6d9a0d895a2385dec994d43bd084410/src/gui/guiFormSpecMenu.cpp#L2036-L2042

**Comment by rubenwardy** [comment] 2019-11-11 18:45
This also happens on CTF with the crafting window

**Comment by SmallJoker** [comment] 2019-11-12 18:14
Old order of elements in `GUIFormSpecMenu::drawMenu()`:

1. `bgcolor`
2. `background` (+ 9)
3. `box`
4. Other elements drawn in order of use
5. `image`
6. `item_image` and `item_image_button`
7. `list`
8. `label` and `item_image_button` labels
9. Tooltip

**Closed** 2019-11-20 18:39 UTC
Labels: Blocker, Bug, Formspec, High priority
