### ISSUE TITLE
BFS occlusion culler kills FPS - Intel CPU/GPU hardware under ubuntu

### ISSUE THREAD

**Issue by gentooza** [minetest/minetest#13443] opened 2023-04-18 08:14 UTC
##### Minetest version

```
5.7.0
```

##### OS / Hardware

Operating system: Ubuntu GNU/Linux 22.04
CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz

GPU model: VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics]
OpenGL version: 4.6 (Compatibility Profile) Mesa 23.2.0-devel (git-60cfe15 2023-04-16 jammy-oibaf-ppa)

##### Summary
I've just upgraded to version 5.7.0 and now minetest is unplayable.
it's lagging and extremely slow.

(I've no fps data although)

before it was working cool, version 5.6.4?

I've just realized I'm using mesa cutting edge drivers via oibaff ppa repository :-/

###### screenshot

![by_default](https://user-images.githubusercontent.com/10772286/233036232-f35838a4-ea28-4a0c-a1cd-1def00e51192.png)

**Comment by rubenwardy** [comment] 2023-04-18 15:33
What does lagging mean? Does this mean low FPS?

Try Settings > All Settings > Search for occlusion culler > Set it to "loops". If it doesn't help, set it back to bfs.

**Comment by gentooza** [comment] 2023-04-18 16:40
hi @rubenwardy!

Yes, I mean ultralow fps [https://en.wikipedia.org/wiki/Lag_(video_games)](https://en.wikipedia.org/wiki/Lag_(video_games))

And yes! changing this parameter did the trick

Is then ok?

cheers!

**Comment by rubenwardy** [comment] 2023-04-18 16:43
@x2048  here's another user where bfs is killing performance

**Comment by gentooza** [comment] 2023-04-18 17:19
Ok! 

I'm here for testing parches por whatever you need.

Glad to help to minetest, I love the project :-D

**Comment by Desour** [comment] 2023-04-18 19:07
Please provide more information, like viewing range, fps (press f5), and screenshot of the scene.
Also, try increasing the client mesh chunksize setting.

**Comment by gentooza** [comment] 2023-04-19 09:43
sure!

added it to first post also

## by default

![by_default](https://user-images.githubusercontent.com/10772286/233035786-4e5bafbd-009b-4c70-8631-3dd1ec07a753.png)

## using mesh chunksize 5. (it's working well!)

![chunksize_5](https://user-images.githubusercontent.com/10772286/233035982-0a493463-f123-4b32-bcff-29e53a9baa24.png)

**Comment by Desour** [comment] 2023-04-19 17:27
Thanks!
Duplicate of #13345. (Maybe we should reopen that issue.)

Just out of interest, can you play with such a high view range, with mesh chunk size = 1 and loops culler, even if you loaded much terrain? (I.e. walk in one direction for a long time, then look back.) (Normally you wouldn't really get the full 4000 view range because the server didn't send you the blocks.)

**Closed** 2023-04-19 17:27 UTC
Labels: Unconfirmed bug, Performance, @ Client rendering
