### ISSUE TITLE
Terrible performance gap between 5.7 and latest master

### ISSUE THREAD

**Issue by AFCMS** [minetest/minetest#14049] opened 2023-11-27 21:21 UTC
### Minetest version

```true
Minetest 5.7.0 (Linux)
Using Irrlicht 1.9.0mt10
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"

---

Minetest 5.8.0-dev-debug-771da80bb (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1692716794
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Active renderer

OpenGL

### Irrlicht device

Both X11 and SDL

### Operating system and version

Fedora 39

### CPU model

AMD Ryzen 7 7735HS

### GPU model

NVIDIA RTX 4060 (laptop)

### OpenGL version

4.6.0

### Summary

Basically performances were good on 5.7 (coming from Fedora repositories) both on iGPU and dGPU.

At 1000 block range I easily hit 144Hz with iGPU (VSync seems enforced by drivers). With dynamic shadows and dGPU I can get get to VSync half of the time with the same viewing range.

But with my master debug builds (have tried multiple ones, reference one is latest master + latest irrlichtmt without any configuration and modifications) I am getting terrible performance with less than 20FPS with dGPU at 1000 viewing range and an almost blank config file (no modified graphical settings, even if a last gen GPU should handle fancy stuff just fine)

I can't tell where I started getting this huge performance drop since I am not really playing Minetest too much and I usually play with 500 viewing range on a 60Hz display. I discovered this because in some situations I got around 40FPS on a pretty small scene with dGPU and a reasonable render distance which should obviously not happen.

I verified that my dGPU was effectively used when I started Minetest with it (5-20% usage displayed in GNOME's mission control app).

I am pretty sure my dGPU isn't at fault (normal score on Blender benchmark, works great in multiple modern games).

I am on Wayland with NVIDIA proprietary drivers.

### Steps to reproduce

I hope I will know at some point :/

Try to see if something similar to what I described happens to you

**Comment by rubenwardy** [comment] 2023-11-27 21:30
A bisect would be very helpful

**Comment by AFCMS** [comment] 2023-11-27 21:35
> A bisect would be very helpful

Will do this.

**Comment by Montandalar** [comment] 2023-11-28 05:45
I think it's relevant that this is occurring for a Debug build though. Is performance always comparable between Debug and Release builds, or are you saying there's been a regression between a 5.7.0 Debug build and a 5.8.0-dev one?

**Comment by AFCMS** [comment] 2023-11-28 07:31
> I think it's relevant that this is occurring for a Debug build though. Is performance always comparable between Debug and Release builds, or are you saying there's been a regression between a 5.7.0 Debug build and a 5.8.0-dev one?

Performance is a little bit better with a release build but still very far from 5.7

5.7: 80 FPS
Master release: 25 FPS
Master debug: 15 FPS

(1000 viewing range, tree plain in latest MineClone2)

Problem occurs with every game, not just mcl

**Comment by lhofhansl** [comment] 2023-11-29 06:47
Hmm... Not what I'm seeing. NVidia on a laptop as well (NVIDIA GeForce GTX 1650), Linux, X11 (not Wayland). Similar performance between 5.7 and current tip.

**Comment by rollerozxa** [comment] 2023-11-29 19:39
I really hope this isn't caused due to fast faces being removed ini 5.8.0-dev.

**Comment by AFCMS** [comment] 2023-11-30 07:57
> Same exact config file? Same setting for `client_mesh_chunk`? Is the dCPU's utilization the same in both cases (you can see that with nvidia_smi or nvidia_settings)?
> 

Almost default config file for dev, without anything graphical configured. I have reset all graphical stuff for 5.7

**Comment by Zughy** [comment] 2023-11-30 10:25
Due to 5.8 being delayed for more than a month, I suggest, in the worst case scenario, to release a hotfix right after. Because we're basically waiting for OP to bisect to then investigate, and it's high unlikely that both these things are gonna take just a couple of days. Also, as @GreenXenith has been pointed out, the jam starts tomorrow, and personally I'd really like to avoid releasing MT 5.8 after the end of the jam (2023/12/22)

(Unsubscribing)

**Comment by grorp** [comment] 2023-11-30 13:43
> I don't know if this is related but high view ranges have unfairly bad performance in 5.8.0-dev. Like if you raise the view range to something high like 1000 or 2000 the framerate begins to plummet independent of if any additional mapblocks load. I don't know how the view range value would cause lag in that way so there must be something that's wrong (unlimited view range does not have the same issue)

@rollerozxa what you are describing sounds like #13345, which exists since 5.7.0-dev. If that's actually the issue you are seeing, it should be fixed if you set `occlusion_culler = loops`. Unlimited viewing range always uses the "loops" occlusion culler IIRC, so unlimited viewing range being unaffected fits into the picture.

**Comment by rollerozxa** [comment] 2023-11-30 15:01
> @rollerozxa what you are describing sounds like #13345, which exists since 5.7.0-dev. If that's actually the issue you are seeing, it should be fixed if you set `occlusion_culler = loops`. Unlimited viewing range always uses the "loops" occlusion culler IIRC, so unlimited viewing range being unaffected fits into the picture.

I see, so it's unrelated to this issue.

**Comment by lhofhansl** [comment] 2023-12-01 01:49
@rollerozxa Still a very relevant question to ask as, I removed the off-topic from your comment. (I think it's bad practice to mark comments as off-topic, unless there's a (very) good reason)

**Comment by AFCMS** [comment] 2023-12-15 09:22
I didn't get the time to bisect yet, but Fedora just updated Minetest to 5.8 and the performance drop is there (so not linked to my own build configuration).

**Comment by AFCMS** [comment] 2023-12-15 09:58
With release build from Fedora repository:
https://youtu.be/Fhf5J_v-9m0

You can see the huge drop of FPS even in non-complex scenes (view over a flat stone area, no entities).
Also the FPS drop quite a lot when moving camera fast.

The FPS I am getting with MT 5.8 can be even lower than what I get with MC 1.20 with the Complementary Unbound shaders in Ultra mode which seems definitely wrong. 

This exemple is at 60+ FPS average:
![image](https://github.com/minetest/minetest/assets/61794590/bd1d6bfe-e770-4ecb-a9e3-e5f0217688a9)

**Comment by sfan5** [comment] 2023-12-15 11:19
this is a duplicate of https://github.com/minetest/minetest/issues/13345 then

**Closed by sfan5** 2023-12-15 11:19 UTC
Labels: Unconfirmed bug, Performance, Action / change needed, Possible close

**Comment by Desour** [comment] 2023-12-16 00:38
>Also the FPS drop quite a lot when moving camera fast.

The mapblock drawlist gets regenerated whenever you move your camera too much. This is required because of frustum culling.
