### ISSUE TITLE
nodebox connects_to issue

### ISSUE THREAD

**Issue by Yzelast** [minetest/minetest#5925] opened 2017-06-05 21:12 UTC
Hi guys,  after doing some random stuff, i noticed that my old connected nodeboxes appeared with a weird texture problem, it looks that some faces are not being rendered, making the texture transparent.
![captura de tela de 2017-06-05 17 02 35](https://cloud.githubusercontent.com/assets/8459626/26803231/71002cbe-4a11-11e7-991c-5a5c017a23fc.png)

Used to work great before the 0.4.16 update...
I tried changing the size of the nodeboxes,  the start/end order, and the issue persists.

Here is the nodebox definition:
{type = "connected",
fixed = **{{-0.25,-0.125,-0.125,0.25,0.125,0.125},**
	     **{-0.125,-0.125,-0.25,0.125,0.125,0.25},**
	     **{-0.125,-0.25,-0.125,0.125,0.25,0.125}},**

connect_top    = **{-0.125,0.25,-0.125,0.125,0.5,0.125},**
connect_bottom = **{-0.125,-0.25,-0.125,0.125,-0.5,0.125},**

connect_front  = **{-0.125,-0.125,-0.25,0.125,0.125,-0.5},**
connect_back   = **{-0.125,-0.125,0.25,0.125,0.125,0.5},**

connect_left   = **{-0.25,-0.125,-0.125,-0.5,0.125,0.125},**
connect_right  = **{0.25,-0.125,-0.125,0.5,0.125,0.125}},**

**Comment by Yzelast** [comment] 2017-06-06 12:59
Some test results that may or not help:

Here is how the fixed nodebox looks:
![captura de tela de 2017-06-06 08 44 58](https://cloud.githubusercontent.com/assets/8459626/26829781/c7a3fe96-4a94-11e7-91fe-9089b55473f7.png)

The Y- and Z+ connections are working as espected.
![captura de tela de 2017-06-06 08 54 42](https://cloud.githubusercontent.com/assets/8459626/26830169/edbcff50-4a95-11e7-9e02-0222594abadf.png)

I also noticed that the selection box isn't at the right position...

**Comment by Thomas--S** [comment] 2017-06-06 14:23
For your texture problem: It seems like you didn't sort your corners correctly in the nodedef.

**Comment by Yzelast** [comment] 2017-06-06 15:19
I dont thing it's a texture issue because it worked perfectly after the 0.4.16 update.
And i forgot to mention that i tested with other textures:

with clay by example:
![captura de tela de 2017-06-06 11 18 03](https://user-images.githubusercontent.com/8459626/26836809-d71d6690-4aa9-11e7-8163-b82e67e80359.png)

**Comment by Thomas--S** [comment] 2017-06-06 15:23
It is not a texture problem, it is a nodedef problem.

Before 0.4.16, the corners were sorted automatically. Now they aren't sorted automatically anymore, so you have to sort them manually to be in the correct order.

There is also a PR for this: #5583

**Comment by nerzhul** [comment] 2017-06-06 15:29
duplicate of #5572

**Closed by nerzhul** 2017-06-06 15:29 UTC
