### ISSUE TITLE
[OSX] Resizing window makes mouse input stop

### ISSUE THREAD

**Issue by DanielHeath** [minetest/minetest#1614] opened 2014-09-08 00:39 UTC
To reproduce:

Grab binaries from https://github.com/mdoege/minetest/releases/download/20140903/minetest-osx-bin-20140903.8948907.zip .

Run the app
resize the window
click on a menu item

Expected: The menu item triggers
Actual: The menu item only triggers 1 time in ~30 clicks.

**Comment by neoascetic** [comment] 2015-03-16 10:24
In fact, by some reason button's click target shifts down on a few pixels, i. e. you should aim a few pixel above the target. I confirm the issue, it still appears. I'll try to figure how to fix it.

**Comment by torleif** [comment] 2017-01-15 07:55
This is an issue with the irrlicht engine. You can fix this by patching line 639 in CIrrDeviceMacOSX.mm file like so:

```
void CIrrDeviceMacOSX::setResize(int width, int height)
{
	// set new window size
	DeviceWidth = width;
	DeviceHeight = height;

	// update the size of the opengl rendering context
	[OGLContext update];

	// resize the driver to the inner pane size
	if (Window)
	{
		NSRect driverFrame = [Window contentRectForFrameRect:[Window frame]];
		getVideoDriver()->OnResize(core::dimension2d<u32>( (s32)driverFrame.size.width, (s32)driverFrame.size.height));
		// the problem is here - it's setting the non clamped size.
		DeviceWidth = (s32)driverFrame.size.width;
		DeviceHeight = (s32)driverFrame.size.height;
	}
	else
		getVideoDriver()->OnResize(core::dimension2d<u32>( (s32)width, (s32)height));
	if (CreationParams.WindowId && OGLContext)
		[(NSOpenGLContext *)OGLContext update];
}
```

**Comment by torleif** [comment] 2017-01-24 01:22
@neoascetic does minetest use a custom build of irrlicht? if not we'd have to get it fixed in the library.

**Comment by neoascetic** [comment] 2017-01-24 04:05
It uses pre-built Irrlicht from homebrew.

On Jan 24, 2017 03:23, "torleif" <notifications@github.com> wrote:

@neoascetic <https://github.com/neoascetic> does minetest use a custom
build of irrlicht? if not we'd have to get it fixed in the library.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/minetest/minetest/issues/1614#issuecomment-274672646>,
or mute the thread

**Comment by elrumordelaluz** [comment] 2021-03-15 13:19
Same thing happens also in Big Sur, where resizing the window changes the layout, but the input/triggers remain in wrong position.

https://user-images.githubusercontent.com/784056/111159452-68392c80-8599-11eb-8d2c-2c4c909f99fb.mp4

**Comment by sfan5** [comment] 2021-03-16 16:30
Here's a fully featured 5.5.0-dev build for macOS (x86_64) you can test: 
[minetest-5.5.0-dev-osx.zip](https://github.com/minetest/minetest/files/6150617/minetest-5.5.0-dev-osx.zip)

It'd be nice if you could provide feedback on:
* If the view is scaled down 1/4 (it shouldn't)
* If this issue still exists
* If you can reproduce #10856

**Comment by Jordach** [comment] 2021-03-16 16:40
Things that currently are broken due to window redraw not being properly called:

Formspecs; formspecs seem to retain memory of the original gui "hotzones", buttons etc. Entering fullscreen (via the green button) fixes this. Double clicking the title bar with autosave screen size then restarting minetest also fixes this.

This may be how Aqua/Quartz handles window decorations misleading irrlichtGUI.

**Comment by elrumordelaluz** [comment] 2021-03-16 17:33
Thank you @sfan5 for the preview build. 
I still noticing the resize issues (look the `buttons` hover state and the mouse pointer position).
![minetest](https://user-images.githubusercontent.com/784056/111353732-dd822b80-8685-11eb-9039-04aab95e4e2d.gif)

**Comment by Jordach** [comment] 2021-03-16 21:00
This commit should fix it: https://github.com/Jordach/irrlicht/commit/cac0fb34392a4945cdd7e85023e8fb47d5b2ab13

Here's a video on Gfy proving such:

https://gfycat.com/immaculateimpoliteabyssiniangroundhornbill

**Comment by sfan5** [comment] 2021-03-16 21:13
Fixed by https://github.com/minetest/irrlicht/commit/fa7a5dbdef06f0c997c2b059bf04a0ca1f6f8ab4

**Closed by sfan5** 2021-03-16 21:13 UTC
Labels: @ Client / Audiovisuals, Bug, Mac OS
