### ISSUE TITLE
Callbacks registered with `register_on_leaveplayer` is not invoked in singleplayer.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3235] opened 2015-10-07 19:26 UTC
Callbacks that have been registered at `minetest.register_on_leaveplayer` are not invoked in singleplayer.

Though, this event seems mostly for mulitplayer (because of the name) all other events (joinplayer, prejoinplayer, shutdown etc.) are invoked in singleplayer. And leaveplayer is the perfect place to clean up some state.

**Comment by PilzAdam** [comment] 2015-10-07 19:27
Duplicate of #420.

**Closed by PilzAdam** 2015-10-07 19:27 UTC
