### ISSUE TITLE
Support empty health/bubble bar texture in the engine

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1276] opened 2014-05-07 08:53 UTC
Do like this: https://dl.dropboxusercontent.com/s/orl51115ckqr4cs/screenshot_354602866.png
(EDIT by paramat: add linked image in cropped form)

![screenshot_354602866cropind](https://user-images.githubusercontent.com/3686677/64490828-f58b1a80-d258-11e9-8baa-d15e3d759d8a.png)

…but in the engine, where the only thing you would have to do is provide textures. How about heart_empty.png and bubble_empty.png?

**Comment by nerzhul** [comment] 2015-03-31 21:00
Duplicate with #1123

**Comment by rdococ** [comment] 2019-09-07 14:47
This doesn't seem to be a duplicate of #1123 - or, at least, #1123 went way off topic.

**Comment by rubenwardy** [comment] 2021-01-31 16:34
This is now supported by the Lua API, but the engine doesn't use it. Fixing this would be as simple as drawing empty heart textures and using them in builtin

**Comment by Wuzzy2** [comment] 2021-06-22 07:44
@rubenwardy: The reason we don't provide default "empty" health/bubble textures is due to compability reasons. If a game only has `heart.png` then the "empty" heart would fallback to the engine default which will be in a different art style and thus break the art of old games, which makes game makers very angry. Thus, no default was given. There is nothing wrong with that.

Also it is wrong that "the engine doesn't use it". All the game author needs to do is to drop `heart_gone.png` and `bubble_gone.png` into their texture folders and it's done.

Since this feature request is already fully honoured, I am closing this now.

**Closed by Wuzzy2** 2021-06-22 07:44 UTC
Labels: @ Client / Audiovisuals, Beginner Friendly, Feature request
