### ISSUE TITLE
Password gets cleared upon server list load if it was typed before load

### ISSUE THREAD

**Issue by farooqkz** [minetest/minetest#13182] opened 2023-02-03 15:15 UTC
##### Minetest version

```
Minetest 5.6.1 
```

##### OS / Hardware

Irrelevant

##### Summary
When I type my password in the password box in the "Join Game" tab before server list load, it gets cleared upon server list load.

##### Steps to reproduce

1. Open "Join Game" tab
2. Before server list loads, type something in the password box
3. Wait for the server list to load
4. You'll see what you have typed in the server list got cleared upon server list load.

**Comment by wsor4035** [comment] 2023-02-03 20:57
known issue of formspecs that they clear inputs when new ones are sent. duplicate of https://github.com/minetest/minetest/issues/12491 and https://github.com/minetest/minetest/issues/12383. related https://github.com/minetest/minetest/issues/12786

**Closed by wsor4035** 2023-02-03 20:57 UTC
Labels: Unconfirmed bug
