### ISSUE TITLE
Texture modifier for rendering text

### ISSUE THREAD

**Issue by xunto** [minetest/minetest#4540] opened 2016-09-21 12:50 UTC
I have an idea of texture modifier that'll be like [text:"text":size. It will render text to a texture. 

Most obvious usecases: signs with utf8 support, nametags that aren't shown through walls.

And also books with markdown.

**Comment by stujones11** [comment] 2016-09-21 16:26
Great idea, although the nametags thing would not so work well unless they could also emit light.

**Comment by raymoo** [comment] 2016-09-22 04:15
I support this idea, but some kind of texture recycling would need to be introduced to prevent memory leaks.

**Comment by xunto** [comment] 2016-09-22 12:21
We already have caching, don't we?

**Comment by raymoo** [comment] 2016-09-22 16:06
Yes

**Comment by xunto** [comment] 2016-09-22 19:55
@raymoo I mean "for that")

**Comment by raymoo** [comment] 2016-09-23 05:48
Caching is why we would need to recycle textures. The textures never leave memory so they take up memory until the client is disconnected, even if the texture was only there to render the preview of an edit to a book.

**Comment by stujones11** [comment] 2016-09-23 16:44
> The textures never leave memory so they take up memory until the client is disconnected.

Maybe that needs to change then? Either way, if used responsibly something like this should ultimately save memory because mods that require this functionality would no longer need to supply entire character sets as individual images.

**Comment by raymoo** [comment] 2016-09-23 18:53
>Maybe that needs to change then?
Well, that's what I was saying.

**Comment by stujones11** [comment] 2016-09-23 19:36
Sure, I get what you are saying but I guess it really depends on the implementation. Until someone actually submits a PR it is impossible to say if this would create memory leaks.

**Comment by Wuzzy2** [comment] 2017-07-25 01:54
I want this, too. UTF-8 signs are the most obvious use case. So far, all sign mods which add draw visible text on the signs only support ASCII or a restricted character set. This is obviously not good enough.

One important question to answer for this issue is which font to use. I think this can not be a font which users should be allowed to just change completely unrestricted (like the GUI font) because a font change might break all textures with rendered textures. This texture modifier should guarantee always pixel-perfect rendering.

**Comment by raymoo** [comment] 2017-07-25 02:37
@Wuzzy2 If by pixel-perfect rendering you mean nearest-neighbor texture sampling, I disagree since text is particularly prone to sampling artifacts. If you turn off filtering and look at signs that use entities for text rendering then you will see chunky letters.

**Comment by Wuzzy2** [comment] 2017-07-25 03:25
No, I mean that rendering a given text shall always yield the same result regardless of user settings. This is to ensure reliability of rendered textures and to prevent breakage. What I want is that the font must not be changable by user settings, otherwise it will be impossible to predict where a text will be rendered on other machines.
Other changes to the target texture MIGHT be okay. It depends.

But, well, texture filtering is a huge can of worms. I think the problem with this could be that all text becomes blurry and unreadable. :-(

**Comment by rubenwardy** [comment] 2017-08-26 03:35
duplicate of #1367

**Closed by rubenwardy** 2017-08-26 03:35 UTC
Labels: @ Client / Audiovisuals, @ Script API, Feature request

**Comment by michieal** [comment] 2022-11-02 07:18
@rubenwardy As one of the people working on MineClone 2, and having rewrote the signs api for it, I was wondering if you could tell me what ever became of this? and if it has been implemented, where I might find docs on using it?
Thank you in advance!!!

**Comment by rollerozxa** [comment] 2022-11-02 07:39
It has not been implemented yet, see #1367, which this issue was a duplicate of.

**Comment by michieal** [comment] 2022-11-04 06:27
Thank you!
