### ISSUE TITLE
Cloud is not rendered when player is inside in that cloud

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3576] opened 2016-01-17 00:16 UTC
Since new mapgens reach clouds easily there is an issue with absence of any fog inside actual clouds, when you walk in it, cloud just dissipaters from view. Someone said that this is related to backface culing, ok, why not just add white fog when inside with low visibility?

This will add more danger and thrill when walking in them obviously (nice example is Valleys mapgen or V7)

**Comment by est31** [comment] 2016-01-17 01:31
Yea, its a bug.

**Comment by paramat** [comment] 2016-01-18 19:55
Fog would be nice, or a subtle post effect colour. I'm guessing this wasn't done due to the effect not justifying the complexity. Clouds aren't nodes just a client-side effect, it might be complex to calculate if players are inside one of the moving cloud squares, it would mean accesing the cloud noise and compensating for cloud movement.

**Comment by est31** [comment] 2016-01-18 20:30
Meh, finding out whether you are in a cloud is not that expensive.

**Comment by Fixer-007** [comment] 2016-11-08 14:19
This should help: https://github.com/minetest/minetest/pull/4524

**Comment by bendeutsch** [comment] 2017-03-14 21:12
Yep, is planned as part of that PR, but progress is slow. Sorry :frowning_face:

**Comment by SmallJoker** [comment] 2017-07-05 13:45
Solved by #6003. However, only when `enable_fog` is set to `true` (default value).

**Comment by Fixer-007** [comment] 2017-09-19 21:44
As of d8f20d02 I can reproduce absence of cloud fog rendering bug again during exploration of carpathian mapgen:
![default](https://user-images.githubusercontent.com/16494741/30616798-20cf54fc-9d9c-11e7-8af5-94c0f2d12c32.png)

Ways to reproduce:
+ Fly in some clouds - verify that fog works
+ Then fly up to Y=300 and go back to cloud level, fog stops working when in cloud

Config:
```
anisotropic_filter = true
bilinear_filter = false
creative_mode = false
enable_damage = false
enable_waving_leaves = false
enable_waving_plants = true
fast_move = true
free_move = true
leaves_style = fancy
mainmenu_last_selected_world = 9
maintab_LAST = local
menu_last_game = minetest
mip_map = true
node_highlighting = box
server_announce = false
server_dedicated = false
trilinear_filter = false
viewing_range = 160
fps_max = 100
mg_name = carpathian
tone_mapping = false
mainmenu_last_selected_TP = 1
noclip = false
texture_path = 
sound_volume = 0.1
enable_shaders = false
fog_start = 0.7
enable_bumpmapping = false
enable_parallax_occlusion = false
enable_waving_water = false
generate_normalmaps = false
smooth_lighting = true
enable_local_map_saving = false
mesh_generation_interval = 5
autosave_screensize = false
enable_client_modding = true
fixed_map_seed = 
minimap_shape_round = false
enable_server = false
world_config_selected_mod = 16
show_debug = true
fsaa = 0
port = 30000
```

**Comment by Fixer-007** [comment] 2017-10-10 21:15
@bendeutsch 
can you look at that?

**Comment by Linuxdirk** [comment] 2019-03-08 06:07
> I can reproduce absence of cloud fog rendering bug again (found it during exploration of carpathian mapgen)

Confirmed in 5.0.0 release version.

**Comment by BluebirdGreycoat** [comment] 2020-08-16 18:37
Bump. Reproducable in latest development version, too. (5.4.0-dev-fff039318) Also see investigation by Jordach #8340

**Comment by paramat** [comment] 2020-08-16 19:51
The bug described above in https://github.com/minetest/minetest/issues/3576#issuecomment-330682814 is a duplicate of #8340 .
This issue is a feature request and the feature was added, so any bug should not have been posted here but in a new issue.
My mistake, i should not have reopened and relabelled this.

**Closed by paramat** 2020-08-16 19:51 UTC
Labels: @ Client / Audiovisuals, Feature request
