### ISSUE TITLE
New plantlike drawtype causes bad-looking symmetry

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1589] opened 2014-08-30 11:00 UTC
Place a plantlike node. Look at it from all 4 directions. 2 of these directions will look poor because of symmetry.

**Comment by sofar** [comment] 2015-12-10 07:00
I'm stunned this is open and nobody looked into the actual problem.

For reference: this is the current situation:

    http://i.imgur.com/dBLZw5t.jpg

Note the empty rows in between the grass on the left and right side of the photographs?

The issue is simple math: The plantlike mesh is drawn from a cube-sized set of vertices, and then rotated 46 degrees. That makes the horizontal length of any plant texture 1.0.

But the distance of a cube from the opposite corners horizontally is sqrt(2), not 1. So in effect the plantlike mesh needs to be scaled 1.4x upwards horizontally to remove the gap in plants.

Effectively the (X,Y,Z) size of the plantlike mesh is (0.707, 1, 0.707)

Here's how the same scene looks after the plantlike mesh size is corrected and stretched 1.4x horizontally, but not vertically: (1.4 was chosen since the plantlike mesh is rotated 44/46 degrees and not 45, and we want to avoid overlapping the textures and leave a little gap, and this factor visually accomplishes that nicely)

    http://i.imgur.com/gLK8bIn.jpg

Detail to show the actual spacing between the resulting plants:

    http://i.imgur.com/m0EcVlz.png

All it took was this patch:

```
diff --git a/src/content_mapblock.cpp b/src/content_mapblock.cpp
index 01a06b6..42a307e 100644
--- a/src/content_mapblock.cpp
+++ b/src/content_mapblock.cpp
@@ -1120,10 +1120,10 @@ void mapblock_mesh_generate_special(MeshMakeData *data,
                        {
                                video::S3DVertex vertices[4] =
                                {
-                                       video::S3DVertex(-s,-BS/2, 0, 0,0,0, c, 0,1),
-                                       video::S3DVertex( s,-BS/2, 0, 0,0,0, c, 1,1),
-                                       video::S3DVertex( s,-BS/2 + s*2,0, 0,0,0, c, 1,0),
-                                       video::S3DVertex(-s,-BS/2 + s*2,0, 0,0,0, c, 0,0),
+                                       video::S3DVertex(-s*1.4,-BS/2, 0, 0,0,0, c, 0,1),
+                                       video::S3DVertex( s*1.4,-BS/2, 0, 0,0,0, c, 1,1),
+                                       video::S3DVertex( s*1.4,-BS/2 + s*2,0, 0,0,0, c, 1,0),
+                                       video::S3DVertex(-s*1.4,-BS/2 + s*2,0, 0,0,0, c, 0,0),
                                };
                                float rotate_degree = 0;
                                if (f.param_type_2 == CPT2_DEGROTATE)
```

Now, I'm not saying to merge this, as I believe that 1.4 is likely slightly too large, or we should actually have plantlike textures scaled to 22px by 16px, otherwise you'll notice that the pixels no longer appear square.

MC avoids the texture scale issue and paints a "stretched" 16x16px texture over a 1.4x1.0 sized plantlike mesh. I haven't confirmed the actual size, and I believe MC does some extra rotation that causes plantlike items to render outside a 1x1x1 box horizontally, which may be a nice idea, at no cost.

**Comment by sofar** [comment] 2015-12-10 07:26
I made a quick default_grass_5.png that's 22x16px, here's the side-by-side comparison: before(left) and after(right).

![before-after]
(http://i.imgur.com/O6YnhMa.png)

**Comment by sofar** [comment] 2015-12-10 07:48
Adding "randomized" placing of the plantlike nodes achieves an excellent effect

```
diff --git a/src/content_mapblock.cpp b/src/content_mapblock.cpp
index 42a307e..eeaef34 100644
--- a/src/content_mapblock.cpp
+++ b/src/content_mapblock.cpp
@@ -1137,11 +1137,16 @@ void mapblock_mesh_generate_special(MeshMakeData *data,
                                                vertices[i].Pos.rotateXZBy(-44 + rotate_degree);
                                }
 
+                               float random_offset_X = BS * (0.4 * (rand() % 100) / 100.0 - 0.2);
+                               float random_offset_Z = BS * (0.4 * (rand() % 100) / 100.0 - 0.2);
                                for (int i = 0; i < 4; i++)
                                {
                                        vertices[i].Pos *= f.visual_scale;
                                        vertices[i].Pos.Y += BS/2 * (f.visual_scale - 1);
                                        vertices[i].Pos += intToFloat(p, BS);
+                                       // move to a random spot to avoid moire
+                                       vertices[i].Pos.X += random_offset_X;
+                                       vertices[i].Pos.Z += random_offset_Z;
                                }
 
                                u16 indices[] = {0, 1, 2, 2, 3, 0};
```

0.4 seems to be an appropriate scale, moving each plant between -0.2 and 0.2 around. rand() should be fast enough, I don't think this would be a bottleneck here.

It looks like this:

![randomize plant placement a bit]
(http://i.imgur.com/ngHxEjm.png)

**Comment by sofar** [comment] 2015-12-10 07:53
Getting back to the original issue - if you independently randomize the two faces of the plantlike mesh, the "looks bad" effect will greatly diminish, since now the two texture copies will always intersect at entirely different places.

**Comment by RealBadAngel** [comment] 2015-12-10 08:31
plantlike nodes can have random rotation stored in param2, just add 
paramtype2 = "degrotate" to plant def and set param2 with value 0-179 (its multiplied by 2 to cover 0-359) when placing such plant

**Comment by 0-afflatus** [comment] 2015-12-10 11:31
@sofar knowing that textures for plantlike nodes need to be scaled up is very useful. I'm not sure I want the engine to automatically sort it out however. I like the randomness of your last shot, but I know opinions vary on this, so placement options need to be do-able from Lua.

**Comment by sofar** [comment] 2015-12-10 15:19
@RealBadAngel the randomization of X,Z placement has a much better effect than varying rotation, and allows to get rid of the texture symmetry issue

**Comment by sofar** [comment] 2015-12-10 15:22
@0-afflatus the alternative is mod-side scaling, which would be a giant mess of patches to every node definition to scale it, and then patch their textures. without that node definition change and a client builtin model change, things look better already and can be further improved by only changing the texture, so it would be less work for the modders.

**Comment by paramat** [comment] 2015-12-10 19:26
@Calinou please can you explain whta you mean in the first comment? it's not clear.

Sofar, the 22x16 texture idea seems okay to me, that's the way to do it as this keeps the pixels square and the same size.

The randomisation of plantlike placement i'm opposed to for similar reasons i'm opposed to random fine-rotation in https://github.com/minetest/minetest_game/pull/290
It would be applied to all plantlike nodes, many of which will be non-plant mod nodes that do not want randomised placement.
It's extra processing in very heavily-used code, and this is not needed or essential enough to justify.
The gridlike placement of plants (just like the diagonal-only rotation) is part of the character of a voxel game, all nodes are aligned to a 3D grid just as the cubic nodes are. Randomisation is a fine idea on it's own, it looks more organic, natural and realistic, but all this is out of character for a voexel game.

**Comment by sofar** [comment] 2015-12-11 01:11
@paramat after having seen how it looks with random offsets, I would at least want to make random offset placement *configurable* for mapgen mods, so that it can be enabled for specific plant decorations. That doesn't seem awkward, wouldn't be backwards incompatible, and folks can still enjoy your old-style voxel-aligned plants aligned as they are now.

I'll certainly see if I can submit a PR with the plantlike box size change already separately, though.

**Comment by sofar** [comment] 2015-12-11 01:38
@paramat I disagree strongly that it's out of place for a voxel game if there are voxel games that do just exactly that. Obviously there must be *some* place for it, and not none.

**Comment by sofar** [comment] 2015-12-11 02:51
slightly better concept code - this keeps plants randomly placed in between map updates

I added a simple/fast pseudo random 5-bit function that creates a consistent random displacement factor for each node. If plantlike we use it. This produces natural effect in the screenshots without plants moving around when the map is updated. The plants always stay in exactly the same spot.

with a decoration flag or nodedef flag this could be enabled at mapgen time for grass and wildflowers only.

```
diff --git a/src/content_mapblock.cpp b/src/content_mapblock.cpp
index 42a307e..729e07a 100644
--- a/src/content_mapblock.cpp
+++ b/src/content_mapblock.cpp
@@ -163,6 +163,20 @@ void makeCuboid(MeshCollector *collector, const aabb3f &box,
 	}
 }
 
+static char x, a, b, c;
+static void psrng_seed() {
+	x = 5;
+	a = 7;
+	b = 13;
+	c = 3;
+}
+static char psrng_rand() {
+	x = (x + 7) & 15;
+	a = (a ^ b ^ x) & 15;
+	b = (b + a) & 15;
+	c = (c + ((b>>1) ^ a)) & 15;
+	return c;
+}
 /*
 	TODO: Fix alpha blending for special nodes
 	Currently only the last element rendered is blended correct
@@ -178,6 +192,8 @@ void mapblock_mesh_generate_special(MeshMakeData *data,
 	// 0ms
 	//TimeTaker timer("mapblock_mesh_generate_special()");
 
+	psrng_seed();
+
 	/*
 		Some settings
 	*/
@@ -196,6 +212,9 @@ void mapblock_mesh_generate_special(MeshMakeData *data,
 	{
 		v3s16 p(x,y,z);
 
+		float random_offset_X = BS * ((psrng_rand() / 16.0) * 0.4 - 0.2);
+		float random_offset_Z = BS * ((psrng_rand() / 16.0) * 0.4 - 0.2);
+
 		MapNode n = data->m_vmanip.getNodeNoEx(blockpos_nodes + p);
 		const ContentFeatures &f = nodedef->get(n);
 
@@ -1142,6 +1161,9 @@ void mapblock_mesh_generate_special(MeshMakeData *data,
 					vertices[i].Pos *= f.visual_scale;
 					vertices[i].Pos.Y += BS/2 * (f.visual_scale - 1);
 					vertices[i].Pos += intToFloat(p, BS);
+					// move to a random spot to avoid moire
+					vertices[i].Pos.X += random_offset_X;
+					vertices[i].Pos.Z += random_offset_Z;
 				}
 
 				u16 indices[] = {0, 1, 2, 2, 3, 0};
```

**Comment by sofar** [comment] 2015-12-11 02:53
btw that psrng is from http://www.electro-tech-online.com/threads/ultra-fast-pseudorandom-number-generator-for-8-bit.124249/

**Comment by kilbith** [comment] 2015-12-11 10:55
> The gridlike placement of plants [...] is part of the character of a voxel game

Someone else with a different conception and as incommodious as yours could say that diagonal crossed-planes is not part of the so-called "_character of a voxel game_" and all plants must be 4-faced like a cube...

I'm surprised that a core-dev holds such a rigid statement on a flexible engine.

**Comment by sofar** [comment] 2015-12-11 23:14
@calinou BTW, making the width of the grass texture an even number of pixels is partially to blame, the issue is gone when you make grass 17x16 pixels.

**Comment by 0-afflatus** [comment] 2015-12-12 09:51
I'm not sure I understand what you're trying to do then @sofar. I had a look at the plantlike textures in my game and AFAICS this would *only* benefit the grasses, not including even grain crops. Then it would make bottles and glasses twice as big as they are now, which is already too big, so they would need scaling down to stop their sides touching. I must be missing something. I'm worried that this would break nearly all my other plantlike textures to fix something which isn't actually broken, just not aesthetically pleasing.

@paramat I feel you're doing the same but opposite. Voxel games do not have to be grid-like and blocky - some designers will want to do everything they can to dither at voxel level. The grid-like blocky aesthetic is /your/ vision for minetest_game.

The engine should facilitate the creation of 3d worlds in much the same way as GIMP facilitates the creation of 2d images, more options, tools and filters that work are great. One-size-fits-all aesthetic changes are out of place unless they fix common issues.

**Comment by paramat** [comment] 2015-12-12 11:31
Yes it would need to be optional, but even when something is optional is still needs to be suitable and needed.

If some other voxel games randomise plant placement then that's either poor design or deliberate moving away from a voxel structure. Anyway those are other games, this is Minetest and it has a K.I.S.S. abstract character. If all voxel games did everything all other voxel games did each one would be an incoherent characterless mess of ideas. Adding something just because another game does it is not enough justification.

Minetest has always had plantlike nodes aligned to the grid and until now no-one has complained. The plantlike drawtype is ultra-simple and has a suitably ultra-simple positioning. As with random fine-rotation, random placement is over-complex, unnecessary and out of character.

RBA and a few others have an alternative approach and vision for Minetest which is completely incompatible with celeron55's (he doesn't like shaders), these ideas are rightly not being accepted and this was causing frustration for RBA, so it's good to see RBA started a fork. I think your idea for randomised placement is more suited to RBA's fork or a new fork.

I actually really appreciate your work on Minetest, you have many good ideas and quality code, but as with random rotation i know this one is unnacceptable even as an option because it is so out of character, over-complex, fancy, and unnecessary.

> could say that diagonal crossed-planes is not part of the so-called "character of a voxel game"

Yes certainly, but diagonal plantlike drawtype is part of the character of Minetest and has been for a long time.

> The grid-like blocky aesthetic is /your/ vision for minetest_game.

No, this is the character of Minetest, which attracted me to it. My opinions and tastes are actually very close to c55's.

> The engine should facilitate the creation of 3d worlds in much the same way as GIMP facilitates the creation of 2d images, more options, tools and filters that work are great.

The Minetest engine cannot and should not do everything, it has a very strong character which means many limitations, in a good way.

**Comment by kilbith** [comment] 2015-12-12 12:03
You prefer simple graphics ? Nobody prevents you to do so. But please stop trying to impose /your/ views to the whole and invoking a profound dichotomy between @RealBadAngel and @celeron55 out of your ass (who cares even ?). An engine is impersonal and not ideological.

Meshnode can be very unsuitable to a voxel game. A significant amount of users love modelizing complex shapes for Minetest.

Random placing of grasses is really not a big deal in comparison.

**Comment by paramat** [comment] 2015-12-12 12:38
I'm simply stating the character and style of the Minetest engine. I can't impose anything i'm just arguing my points. The difference of tastes and approaches between RBA and c55/hmmmm/myself is a clear fact. This engine has a strong character and many limitations, just as it should be.

**Comment by kilbith** [comment] 2015-12-12 12:40
Right, let's make the waterlilies with the same facedir then (along with the "_strong KISS character of Minetest_") ...

**Comment by kilbith** [comment] 2015-12-12 12:56
You're so masturbating about your conception of the "_simple character of Minetest_" that you did not even wanted in 1st instance to make some code optional when it was needed : https://github.com/minetest/minetest/pull/3418#issuecomment-162245277 

I could argue also that the fractal mapgen is not needed from a gaming standpoint. Your KISS conception has variable geometries when it benefits you personally or not.

**Comment by paramat** [comment] 2015-12-12 13:33
Bad argument, waterlilies have 4 90 degree rotations, that's within character.

> you did not even wanted in 1st instance to make some code optional when it was needed

That's a ridiculous thing to bring up, i was simply wrong about which implementation was best because i didn't know how to code it at that point, hmmmm pointed this out and we ended up going with the simplest and cleanest. And please don't be disgusting.

Fractal mapgen is also within character, and popular

**Comment by 0-afflatus** [comment] 2015-12-12 13:46
@kilbith such ad hominem arguments are not appropriate, can we please stick to discussing ideas relating to the OP?

**Comment by 0-afflatus** [comment] 2015-12-12 14:13
While I support the KISS approach, I think that needs to be achieved in the engine with generic flexibility. I think it's viable to add more options so long as there is a significant use case, even if that isn't within minetest_game, and a s long as it has no harmful side-effects. Being flexible enough to facilitate more baroque applications will encourage a greater variety in sub-games. However, I don't think redesigning the plantlike nodetype is going to do much to improve the game right now.

**Comment by kilbith** [comment] 2015-12-12 16:38
> The difference of tastes and approaches between RBA and c55/hmmmm/myself 

Rubbish. hmmmm attempted some [fancy stuff](http://irc.minetest.ru/minetest-dev/2015-01-19#i_4120735) on the lighting in the past (and still planning as well as on the shaders, according to his declarations). C55 made buildat which is rather fancy-looking as well.

You always find a hypocritical or untruthful strategy to give a weight to your views and obtain favors from authorities.

> i was simply wrong about which implementation was best because i didn't know how to code it at that point

You merely used the argument of "simplicity" without a single valid, technical reason — like here.

Flexibility is one of the cornerstone of Minetest. Decisions based on tastes belong more to the subgames, not an engine which aim for universality of usage. If you can't stand this diversity of tastes, then you're harming the community.

I hope you remember why a respected company like @KenneyNL left the project : for the same unprofessional reasons you're preserving here. We'll stay marginal with such prohibitive spirit.

**Comment by BlockMen** [comment] 2015-12-13 00:18
> We'll stay marginal with such prohibitive spirit.

What do you expect? What should Minetest become? IMO MT (and its forks) will always  stay marginal ...

**Comment by paramat** [comment] 2015-12-16 05:02
> You merely used the argument of "simplicity" without a single valid, technical reason

Yes and i was wrong to do so, i should have added explanation.

**Comment by cyisfor** [comment] 2016-01-03 20:50
Could we have the expanded mesh size, and leave the randomization to further discussion in another pull request?

**Comment by sofar** [comment] 2016-01-03 21:38
The mesh size can already be adjusted, so there's no need for a patch at this time.

I'll keep the random_xz patch floating around for those who wish to entertain it. IMHO it's a decent patch, but too many people are discarding it as "visually doesn't fit" even though I feel that's somewhat arbitrary (MC does that, for instance, and I think the "cornrows" are ugly when densities of plants increases), not to mention it's done client-side entirely, and optional.

**Comment by paramat** [comment] 2016-02-18 07:13
@Calinou please can you explain what you mean in the first comment? it's not clear.

**Comment by sofar** [comment] 2016-02-18 07:24
@paramat what he means is at the intersection of the 2 faces, you have column 7 of the texture on one face, and column 7 of the texture on the other face:

![]
(http://i.imgur.com/lEKuEDW.png)

(ignore the waving causing the separation here)

Note: the pixels in the center appear twice as wide as the rest of the pixels.

**Comment by paramat** [comment] 2016-03-28 11:39
That's not a problem, and i'm not sure that's what Calinou means.

**Comment by paramat** [comment] 2016-03-28 11:47
Explanation by Calinou:
"paramat, look at those screenshots, the grass is completely symmetric: https://lut.im/1GybF8HmFB/ZPbGqgdaPnUUN6ww.png | https://lut.im/RZbYPtHOd6/yB4enwXYf3yrOdoN.png 
it looks awkward like a human face that would be entirely symmetric"

**Comment by paramat** [comment] 2016-03-28 12:05
The symmetry looks good to me, especially in a voxel world full of symmetry and geometry.
Plantlike is meant to be super-simple, and needs to be as it is used so heavily. Tis issue is focussing on a tiny non-problem and suggesting comples fixes :-1:

**Comment by sofar** [comment] 2016-03-28 19:33
Just as an aside, I'm playing with a mesh option for CPT2_MESHOPTIONS (the plant fun PR thing) that would do some more mesh jiggling to likely get rid of this as well. It would be using the plantlike drawtype param2 just like the other options.

**Comment by paramat** [comment] 2016-03-29 15:35
It's really not worth fixing, 4 textures with backface culling would be complex and a large rise in render load for something barely noticeable unless you're up close and looking for it. Symmetry looks fine in a voxel world, there's a lot of symmetry around.

**Comment by sofar** [comment] 2016-03-29 15:40
It's easily fixed by jiggling the mesh without adding new textures or faces. So, it's worth fixing for some people.

**Comment by paramat** [comment] 2016-08-25 04:44
A feature of #3923 shifts tiles to reduce this symmetry.
Otherwise i can't see how this can be avoided, two identical tiles will always do this.

**Comment by paramat** [comment] 2016-10-27 08:25
#3923 is merged. @Calinou can this be closed?

**Comment by Fixer-007** [comment] 2016-10-27 12:23
It is merged but it does not randomise thing, there is still "bad-looking symmetry" :)

**Comment by paramat** [comment] 2016-10-27 22:54
I can't see any reasonable solution and it's not really a problem, voxel games have symmetry everywhere.

**Comment by paramat** [comment] 2017-09-01 23:16
@Calinou is meshoptions enough to satisfy you?

@sofar what's your idea? Is it to slightly offset so that the 2 textures intersect along the centre of a pixel column? This could be a good option for flowers as they are small and the stems look a little weird currently.

**Comment by paramat** [comment] 2017-09-01 23:34
Currently as you walk around to view a texture from the other side it's structure remains consistent, as it should do. So symmetry from 2 views is inevitable if using 1 texture.
However it could be 'solved' by optionally allowing 2 textures for plantlike.

**Comment by paramat** [comment] 2017-11-27 04:22
No response for 3 years. Meshoptions are merged and have a vertical randomisation.

**Closed by paramat** 2017-11-27 04:22 UTC
Labels: @ Client / Audiovisuals, Low priority, Possible close
