### ISSUE TITLE
keyboard touch 7 and keypad

### ISSUE THREAD

**Issue by Steamed-Punk** [minetest/minetest#10415] opened 2020-09-21 14:44 UTC
I am using an acer Aspire 6920G with linux mint 20. Minetest 5.3.0
Playing with seeds, i tried to add the number 7.

I have a USB keyboard plugged in and the Number 7 simply doesn't work. I unplugged it to use the built in laptop keyboard and it's the same result. I then plugged in a third (usb) keyboard and still no reaction from touch number 7. I have to use the top row of numbers because the numberpad on the right side of the keyboard (any keyboard) does not react in any way it is supposed to.

**Comment by rubenwardy** [comment] 2020-09-21 14:45
Which keyboard layout?

**Comment by benrob0329** [comment] 2020-09-21 14:58
Minetest seems to ignore the NumLock state, this is not new _but_ is an annoying behavior.

**Comment by sfan5** [comment] 2020-09-21 15:44
likely duplicate of #302

**Comment by Steamed-Punk** [comment] 2020-09-21 16:11
> Which keyboard layout? ie: does the top row of letters spell QWERTY, AZERTY, or something else

rubenwardy I am using an AZERTY. English dude in France. Now I'm guessing it can be solved in settings or config and not a bug.

**Comment by Steamed-Punk** [comment] 2020-09-21 16:13
> Minetest seems to ignore the NumLock state, this is not new _but_ is an annoying behavior.

I can't use the keypad on the right. have to use the top row of numbers.

**Comment by Steamed-Punk** [comment] 2020-09-21 16:14
> likely duplicate of #302

After looking I think you are correct. I did look before posting here but didn't see that. Sorry.

**Closed** 2020-09-21 16:25 UTC
Labels: @ Client / Controls / Input, Unconfirmed bug
