### ISSUE TITLE
API for changing a node's appearance

### ISSUE THREAD

**Issue by bluebear94** [minetest/minetest#2887] opened 2015-07-05 19:06 UTC
Currently, there are only a few preset ways to change a node's appearance based on its node data. I propose moving this functionality to the API.

Perhaps having `minetest.change_tile(pos, node, tiles)` and `minetest.change_nodebox(pos, node, nodebox)`, or making the tile and nodebox fields of the node definitions take functions as well as fixed values?

**Comment by est31** [comment] 2015-07-05 19:27
I guess you will like #1118.
Another way to do this would be to specify client side functions which modify the nodebox depending on the node metadata.

**Comment by bluebear94** [comment] 2015-07-07 10:13
Well, let's hope that a "snapshot" (if that kind of thing is done here) comes out with such a change so I can work on something that plans to use this functionality.

**Comment by ShadowNinja** [comment] 2015-11-12 06:45
Meta_set_nodedef is very powerfull, but it has some limitations:
  * Storage space; Currently it stores the whole itemdef in the meta.  This could be changed to just store the changed fields, but that's still quite a bit of space (eg, `{nodebox = {{0.5, 0.5, 0.5, 0, 0, 0}}}` or so when `top-front-right` or even `8` would do).
  * Updates: Say you change the mesecons nodebox.  Now you have to somehow update every mesecon on the map to give it the new nodebox.

I think the best approach would be two pronged:
  * Meta_set_nodedef for when you have to make changes to a node at one specific position. (examples: ?)
  * A "variant" option for nodes that have a limited number of variations. (eg, colored nodes, connecting nodes (mesecons, fences, technic wires...))

The variant would be stored as a node field (like `param1`) or in the nodedef.  It would be either a string (more flexible?) or a 16-bit number (more compact).

Here's a example of what an API might look like (string option):
```Lua
minetest.register_node("mymod:colored_wood", {
	...
	variants = {
		blue = {tiles = {"mymod_wood_blue"}},
		red = {tiles = {"mymod_wood_red"}},
	}
})
```

**Comment by est31** [comment] 2015-11-12 07:12
Agreed, I, too, favour a variant like approach over one where the full nodedef gets specified in the nodedef.

With client side scripting we could perhaps even have something even more flexible than what you described above, where the nodedef is returned by a function that gets the variant specifier/name/data as input. So e.g. you'd have client side code like (with the number option):
```lua
local color_name_table = ["mymod_wood_blue", "mymod_wood_red", "mymod_wood_pink"]
minetest.set_node_variant_function("mymod:colored_wood", 
	-- returns the table overriding the nodedef, nil if variant_id is invalid
	function(variant_id)
		local color_name = color_name_table[variant_id]
		if not color_name then
			return nil
		end
		return {
			tiles = {color_name}
		}
	end
)

**Comment by paramat** [comment] 2017-03-21 21:01
Duplicate of #2107

**Closed by paramat** 2017-03-21 21:01 UTC
Labels: Duplicate, Feature request
