### ISSUE TITLE
Cyrillic world name error

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#3588] opened 2016-01-18 16:44 UTC
Starting on 0.4.13 stable
I create `апм` (random cyrillic world name) world and minetest crashed:

```
2016-01-18 18:42:58: ERROR[Server]: An unhandled exception occurred: Failed to open SQLite3 database file C:\Users\monte\Desktop\minetest-0.4.13-22bc66d-pull3586-win32\bin\..\worlds\апм\map.sqlite: unable to open database file
2016-01-18 18:42:58: ERROR[Server]: In thread 2028:
2016-01-18 18:42:58: ERROR[Server]: /home/stefan/mt-build/build/minetest/minetest/src/server.cpp:73: run: A fatal error occured: Failed to open SQLite3 database file C:\Users\monte\Desktop\minetest-0.4.13-22bc66d-pull3586-win32\bin\..\worlds\апм\map.sqlite: unable to open database file
2016-01-18 18:42:58: ERROR[Server]: Debug stacks:
2016-01-18 18:42:58: ERROR[Server]: DEBUG STACK FOR THREAD 120c: 
2016-01-18 18:42:58: ERROR[Server]: #0  main
2016-01-18 18:42:58: ERROR[Server]: DEBUG STACK FOR THREAD 2028: 
2016-01-18 18:42:58: ERROR[Server]: #0  run
2016-01-18 18:42:58: ERROR[Server]: DEBUG STACK FOR THREAD 21f8: 
2016-01-18 18:42:58: ERROR[Server]: #0  run
2016-01-18 18:42:58: ERROR[Server]: DEBUG STACK FOR THREAD 2c14: 
2016-01-18 18:42:58: ERROR[Server]: #0  run
```

**Comment by kaeza** [comment] 2016-01-19 02:55
Can confirm (in my case, I used "á"):
```
2016-01-18 23:42:01: ERROR[Server]: An unhandled exception occurred: Failed to open SQLite3 database file [...]\minetest\bin\..\worlds\Ã¡\map.sqlite: unable to open database file
```

**Comment by RobertZenz** [comment] 2016-01-19 23:35
I just tried under Linux with the latest HEAD and I could create worlds with cyrillic letters just fine. So that might be Windows/NTFS specific.

**Comment by MoNTE48** [comment] 2016-01-20 00:10
Yes, this Android and Windows bug only.

**Comment by ShadowNinja** [comment] 2016-02-04 20:53
My guess as to the cause of this is that we're using the "ANSI" versions of functions like "CreateDirectory" and SQLite3 is (correctly) using the "wide" versions, so Windows thinks we're talking about two different directories.

As for Android: The representation conversion helpers are broken on Android, so we're probably using UTF-8 somewhere where the system default encoding (ISO-8859-1?) should be used, or something like that.

**Comment by rubenwardy** [comment] 2018-07-26 14:19
closing in favour of #4875

**Closed** 2021-01-29 21:43 UTC
Labels: Bug, Windows
