### ISSUE TITLE
Player gets damage despite of 'Enable Damage' is switched off.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#10233] opened 2020-07-27 14:06 UTC
##### Minetest version
Minetest 5.4.0-dev-808fa5ecb

##### Summary
The title already says about all. Any player will get damage under external impacts, despite of 'Enable Damage' checkbox is switched off in the Main Menu.

**Comment by sfan5** [comment] 2020-07-27 14:12
Can't reproduce.

Also a duplicate of #10161

**Closed by sfan5** 2020-07-27 14:12 UTC
Labels: Duplicate
