### ISSUE TITLE
Android: Gear button missing on S9+ (better GUI size algorithm needed)

### ISSUE THREAD

**Issue by codexp** [minetest/minetest#7504] opened 2018-06-29 19:53 UTC
##### Issue type

 - Bug report
 
##### Minetest version

```
0.4.17
```

##### OS / Hardware

Operating system: Android 8
CPU: Exynos 9810 

GPU model:
OpenGL version:

##### Summary

Gear button is missing in game, so all the modes like fly, noclip and fast are not available.

##### Steps to reproduce

start the game, no gear button on the right top corner

**Comment by SmallJoker** [comment] 2018-06-29 19:56
The most recent build was tested (see #7496) and this button was present in all cases. Are you sure that the game was installed properly and that it's up to date?

**Comment by rubenwardy** [comment] 2018-06-29 20:03
i can reproduce this on my S7 edge. I use a high DPI setting

**Comment by codexp** [comment] 2018-06-29 23:03
I've tried many things, nothing has helped. It is a new installation on a brand new S9+ phone (1 day old).

**Comment by srifqi** [comment] 2018-06-29 23:54
Can you provide screenshot?

**Comment by codexp** [comment] 2018-06-30 09:14
yes, also other controls overlap with inventory items grid and are too big.
is there a setting for controls size?

![missing gear button](https://user-images.githubusercontent.com/6502486/42123699-c74154cc-7c56-11e8-9a06-fb1512911d8d.jpeg)

**Comment by codexp** [comment] 2018-06-30 09:18
Display size: 6.2" Quad HD+ (2960x1440) 529 ppi

**Comment by srifqi** [comment] 2018-06-30 17:15
Touch screen GUI's button size is calculated from this:
https://github.com/minetest/minetest/blob/dd5f03731ad545f52da24825a2ee870f899f6adc/src/touchscreengui.cpp#L462-L468

Also, by this:
https://github.com/minetest/minetest/blob/dd5f03731ad545f52da24825a2ee870f899f6adc/src/porting.cpp#L851-L873

**Comment by srifqi** [comment] 2018-06-30 17:18
I'm pretty sure, this problem is caused by button size being too large. Also, how about moving the gear button down?

**Comment by stujones11** [comment] 2018-07-01 16:39
@srifqi `getDisplayDensity` is actually in `porting_android.cpp` calcDisplayDensity is only for desktop. I would suggest experimenting with the HUD scale factor in Advanced Settings > Graphics > In-Game > Advanced

**Comment by srifqi** [comment] 2018-07-01 16:45
You're right. I missed these:
https://github.com/minetest/minetest/blob/dd5f03731ad545f52da24825a2ee870f899f6adc/src/porting.h#L360-L362
https://github.com/minetest/minetest/blob/dd5f03731ad545f52da24825a2ee870f899f6adc/src/porting_android.cpp#L277-L294

**Comment by stujones11** [comment] 2018-07-01 16:58
Indeed, that simply retrieves the display density from the jni environment, the problem IMO is that this algorithm is overly simplistic and craps-out at certain dpi/resolution combinations.
https://github.com/minetest/minetest/blob/1ff15d3a46042d3432d9485249e4dc3b08dbc6ff/src/gui/touchscreengui.cpp#L492-L494
However, the HUD scale also seems too large so a setting of slightly less than 1.0 might just be enough make it playable.

**Comment by srifqi** [comment] 2018-07-02 04:40
@codexp Glad to hear that.

Still, this is a problem for Minetest. We need an algorithm to find correct size for GUI.

**Comment by MoNTE48** [comment] 2018-07-02 20:55
@codexp hi, you can try MultiCraft? https://play.google.com/store/apps/details?id=mobi.MultiCraft
If my solution works, I can do PR

**Comment by stujones11** [comment] 2018-07-03 16:48
> Still, this is a problem for Minetest. We need an algorithm to find correct size for GUI.

I completely agree, however, in this particular case I believe it is the HUD scaling at fault. Even if you were to adjust that algo so that the gear icon became visible with `hud_scaling = 1.0` the game would still be barely playable. For this reason, I think the touchscreen gui controls should have their own scale setting, independent of the HUD scale.

**Comment by MoNTE48** [comment] 2018-07-04 23:09
1) https://github.com/MultiCraftProject/MultiCraft/blob/968954a3cc8dbdb818813ecd9c8476ff94447f7d/src/defaultsettings.cpp#L410
2) You can take a look at my touchscreengui file. I have not accepted the last few Minetest commits because I find them terribly uncomfortable. But basically Stu can see my idea.
https://github.com/MultiCraftProject/MultiCraft/blob/master/src/touchscreengui.cpp

**Comment by paramat** [comment] 2018-10-08 04:07
Duplicate of #5054

**Closed by paramat** 2018-10-08 04:07 UTC
Labels: @ Client / Controls / Input, Android, Bug, Duplicate, Request / Suggestion

**Comment by paramat** [comment] 2018-10-17 07:30
Perhaps the gear button disappeared due to being too close to screen edge?

![whatsapp image 2018-10-15 at 20 46 38](https://user-images.githubusercontent.com/6502486/46973803-93ff1200-d0c2-11e8-9e2e-34b5acbcd361.jpeg)

**Comment by paramat** [comment] 2018-10-17 08:18
PR #7792

**Comment by paramat** [comment] 2018-10-19 05:54
> Hey, cool! Setting hud_scaling to 0.75 has helped and gear button has appeared!

@codexp concerning PR #7784 does GUI scaling 0.85 work for your phone?

**Comment by codexp** [comment] 2018-10-19 18:45
can't test, it's not my phone

**Comment by rubenwardy** [comment] 2018-10-19 19:01
Is there an APK available?

**Comment by paramat** [comment] 2018-10-20 05:04
codexp no problem, PR is closed now anyway so it's not important.
