### ISSUE TITLE
Hide or remove touch controls on android when physical mouse and keyboard are connected

### ISSUE THREAD

**Issue by farooqkz** [minetest/minetest#13626] opened 2023-06-24 15:40 UTC
##### Minetest version
```
5.8
```

##### OS / Hardware

Operating system: Android 10
CPU: Snapdragon 636

GPU model: Adreno 509
OpenGL version: 3.2

##### Summary

Touch controls are not removed when physical keyboard and mouse are connrcted.

##### Steps to reproduce

1. connect hardware mouse and keyboard to an Android device
2. Open Minetest and start a world
3. Keyboard is working for movements and mouse roughly works but touch controls are still there.

**Comment by rubenwardy** [comment] 2023-06-24 22:24
Duplicate of #10062

**Closed by rubenwardy** 2023-06-24 22:24 UTC
Labels: Unconfirmed bug
