### ISSUE TITLE
Allow mods to be installed via minetest (feature request)

### ISSUE THREAD

**Issue by ThomasMonroe314** [minetest/minetest#6417] opened 2017-09-15 13:05 UTC
I have noticed that for many players who aren't fluent in computer file systems and finding things on the forums it is difficult to get mods.

So I am proposing that we make a mod download system in the mods tab of the main menu working sort-of like this:
1. There is a download button in the mods tab that opens something similar to the configure window for worlds.
2. That window accesses a list of Git-Hub links for mods that can be hosted on the same server that hosts the server-list.
3. That list could be managed via a Git-Hub repo under minetest.
4. When you click to download a mod in that window it performs a git clone of the repo.
5. There could also be a update button for already downloaded mods which performs a git pull.

**Comment by zaoqi-unsafe** [comment] 2017-09-15 13:20
create another software

**Comment by rubenwardy** [comment] 2017-09-15 13:43
duplicate of #6078

**Closed by rubenwardy** 2017-09-15 13:43 UTC
