### ISSUE TITLE
rollback_check leaks memory to large sizes

### ISSUE THREAD

**Issue by neko259** [minetest/minetest#8470] opened 2019-04-13 14:35 UTC
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.1
```

##### Summary
I try to do rollback_check 2 999999

Since there is no command to find first action user, this is the best way to find who deleted some node. It gets minetest too 300M of memory to 3G that is a limit I set for the server and then lags until I have to restart it. I didn't check larger memory settings and don't know if there is some limit that will work.

**Comment by paramat** [comment] 2019-04-13 18:57
I wonder if this is a bug or expected considering the large time range entered and assuming a huge rollback log?

**Comment by neko259** [comment] 2019-04-15 07:06
@paramat rollback log for that location should not be bigger than couple dozens of lines. I clean up the database to store no more than 0.5 year of data, and I'm certain that location is not widely modified. I hope minetest does not try to load entire database and filter it manually...

Mostly rollback_check is used to find the griefer, so it would be better to add some option to get "last 10 actions on the node" which should be much faster and limited, but there is no such option now. I don't really know what to do now, maybe write a custom rollback mod that I can modify for more options.

**Comment by cheapie** [comment] 2020-04-24 02:30
How long has your rollback DB existed? There was a fix for some rollback_check performance issues way back in 2015 but it only affects worlds created since then (or that first had rollback enabled after then).

**Comment by rubenwardy** [comment] 2021-01-22 18:13
duplicate of #1846

**Closed by rubenwardy** 2021-01-22 18:13 UTC
Labels: Bug
