### ISSUE TITLE
Bad shader bumpmapping light source positioning (was: Enabling "Generate Normal Maps" darkens sides of the screen)

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#9711] opened 2020-04-19 08:20 UTC
##### Minetest version

(I've observed this a few times in `0.4.x` as well)

```
0.4.x, 5.x.x
```

##### OS / Hardware

Operating system: Ubuntu 18.04
CPU: Intel i3-8145U

GPU model: Intel HD Graphics 620
OpenGL version: OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.2.8

##### Summary

Enabling "Generate Normal Maps" shader option visibly darkens the sides of the screen, which is somewhat game-breaking to me (the darkening itself, not the shader option), as I'm already struggling to find my way around at night. ;)

##### Visual comparison

![screenshot_20200419_132245](https://user-images.githubusercontent.com/36130650/79683004-8b9e0f00-8244-11ea-8653-417afe515bba.png)
![screenshot_20200419_132302](https://user-images.githubusercontent.com/36130650/79683005-8fca2c80-8244-11ea-8845-0890821bf1bc.png)

(All other settings were left untouched for this comparison)

##### Steps to reproduce

- Enable "Shaders" and "Generate Normal Maps"
- Launch a world.
- Observe the very-noticeable darkening at the screen sides.

**Comment by ClobberXD** [comment] 2020-04-19 08:21
Some relevant IRC chatter: http://irc.minetest.net/minetest-hub/2020-04-19#i_5671614

**Comment by An0n3m0us** [comment] 2020-04-19 15:41
With only `Generate Normal Maps` enabled, I don't get this result. Here's what it looks like:
![image](https://user-images.githubusercontent.com/49789044/79692306-44bc1380-825c-11ea-9b29-ac617ad24eef.png)

But with the `Bump Mapping` option on, then I get the same result as in the OP:

![image](https://user-images.githubusercontent.com/49789044/79692330-64ebd280-825c-11ea-9613-0e2e82c184cd.png)

In addition; with `Parallax Occlusion` and `Tone Mapping`:
![image](https://user-images.githubusercontent.com/49789044/79692350-8947af00-825c-11ea-901e-5af8edb41445.png)

**Comment by paramat** [comment] 2020-04-19 21:21
This is a known issue with how the normalmap shader lighting works. There is some discussion in another issue somewhere. @lhofhansl found the lighting had a poor/buggy implementation, at the time there was an intention stated to fix this at some point.
I agree it looks really bad, i personally dislike bumpy nodes effects anyway, but this is even worse due to the weird lighting.

**Comment by paramat** [comment] 2020-04-19 21:24
Related #9241

**Comment by An0n3m0us** [comment] 2020-04-19 21:40
I'd _love_ to see the normal map lighting fixed, but unfortunately I can't code in C++ at the moment.

**Comment by HybridDog** [comment] 2020-04-20 11:30
> I'd love to see the normal map lighting fixed, but unfortunately I can't code in C++ at the moment.

You can try my [m_bumpmapping_fixes](https://github.com/HybridDog/minetest/tree/m_bumpmapping_fixes) branch where I've moved the lighting calculation to the fragment shader. It may not look very interesting because there is no view-dependent specular lighting and no actual light sources.

**Comment by Moth-Tolias** [comment] 2020-04-20 14:23
i actually quite like the aesthetics of the darkening [though i do agree that it is a bug and should therefore be fixed]. i wonder what the issue is? i'd love to know so that i can apply it intentionally, perhaps under different circumstances.

**Comment by An0n3m0us** [comment] 2020-04-20 16:44
It's like a vignette effect; and it wouldn't look too bad if it didn't affect the normal maps.

**Comment by paramat** [comment] 2020-04-20 20:46
The cause is known, the details are linked in my comment above. Part of the fix is present in #8889 
So if anyone tries to fix this, please try what lhofhansl suggests. lhofhansl seems inactive in dev recently.

**Comment by lhofhansl** [comment] 2020-06-01 02:54
I'd like to pick this up again... I just have *very* little time ATM.

**Comment by paramat** [comment] 2020-10-10 13:28
'Generate normal maps' has been removed by #10313 

However, this edge-darkening still happens when bumpmapping is enabled, for any nodes which have normalmap textures.
It is most noticeable when the normals are vertical or near-vertical, as here:

![screenshot_20201010_140321](https://user-images.githubusercontent.com/3686677/95655913-8db19e00-0b02-11eb-8a0e-9636d1bd4ef4.png)

^ Parallax occlusion and bumpmapping enabled. Edge-darkened

![screenshot_20201010_140431](https://user-images.githubusercontent.com/3686677/95655924-9c985080-0b02-11eb-8d17-952dd99359a8.png)

^ Parallax occlusion enabled, bumpmapping disabled. Normal brightness

Why this happens (as far as i know):

Bumpmapping darkens textures according to the angle between the normals (stored in the normalmap texture) and the direction of lighting from the shader light source, as shown by this bumpmapped pyramid node:

![screenshot_20201009_184439](https://user-images.githubusercontent.com/3686677/95656119-049b6680-0b04-11eb-8bf5-834acab65f15.png)

Unfortunately, the shader light source seems to be positioned relative to the player, as if it is on a pole sticking upwards and forwards out of the player's head, it moves with player view direction. So nodes in front of the player are brighter, but nodes to either side are darkened.

Obviously, nodes should instead be lit from a light source fixed in the world, to be unaffected by player position and view direction.

**Comment by paramat** [comment] 2020-10-10 15:23
Closely related discussion:
https://github.com/minetest/minetest_game/issues/2473
https://github.com/minetest/minetest/issues/9241

**Comment by paramat** [comment] 2020-10-10 18:51
Closing as the discussion here is now duplicating #9241

**Closed by paramat** 2020-10-10 18:51 UTC
Labels: Bug, Shaders
