### ISSUE TITLE
Add a debug renderer

### ISSUE THREAD

**Issue by Soupstraw** [minetest/minetest#9565] opened 2020-03-29 16:57 UTC
## Problem

I'm trying to implement an airflow simulation in my mod. It would be much easier to debug the mod if I could render some text at some points in space (e.g. air pressure indicator at each air node).
Unity engine has some built-in functions similar to what I'm imagining in its Debug class.
These debug objects would only be visible in the debug mode (F5).

## Solutions

There should be a set of functions implemented that allow modders to easily render things in-game.
Some such functions could be:

- `draw_line(p1, p2)` -- draws a line from p1 to p2 (useful for debugging raycasting)
- `draw_label(p1, text)` -- draws a floating label at point `p1` (useful for showing node metadata)
- `debug_color(color)` -- sets the color of labels/lines

## Alternatives

Right now, print debugging is the only option as far as I know. It works in some cases, but since minetest is in 3D space, it would make sense to have 3D debugging features as well.

**Comment by SmallJoker** [comment] 2020-03-29 17:22
> draw_line(p1, p2)

Duplicate of #6805

> draw_label(p1, text)

HUD API:
https://github.com/minetest/minetest/blob/9953145a4efe5d2487ec8f5edc76cf8e418b7b41/doc/lua_api.txt#L1351-L1359

> debug_color(color)

For Lua-defined text, see
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2821-L2825

**Comment by Soupstraw** [comment] 2020-03-29 17:29
Oh, waypoint is just what I'm looking for. 
Maybe it would be more clear if it were documented that it "draws a marker at the selected world position".

**Comment by SmallJoker** [comment] 2020-03-29 17:46
@Soupstraw Sorry, that's not quite what it does. In this case it's #1367 what you'd like to have. Waypoints adds uniform scaled text to the screen which is then re-positioned depending on the camera rotation. It's neither scaled nor directly drawn onto the node.

**Comment by paramat** [comment] 2020-03-29 22:21
Seems closable but feel free to continue discussion.

**Closed by paramat** 2020-03-29 22:21 UTC
Labels: @ Client / Audiovisuals, @ Script API, Feature request, Possible close
