### ISSUE TITLE
Changing Settings On The Fly

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#13346] opened 2023-03-23 11:30 UTC
## Problem

You currently have to leave the subgame you're playing in, in order to change any settings besides the volume and keys. This can get very tedious when you try adjusting any settings to your liking which are more subtle in nature.

It's even worse when joining a heavier subgame with a longer load time, or a server where you have to not only constantly retype your login credentials but also wait for all the media to load.

## Solutions

Replace the `Sound Volume` and `Change Keys` buttons with a `Settings` button. Said button will open a second menu which allows someone to not only change the volume and keys, but also allows you to change many more settings without having to constantly rejoin the game. I would try making it possible to change texture packs on the fly as well this way.

## Additional context

Take Minecraft as an example. You don't have to constantly rejoin the world you're playing in, just to toggle vsync, or to change the FOV of the player.

**Comment by rubenwardy** [comment] 2023-03-24 11:43
Duplicate of #6722

**Closed by rubenwardy** 2023-03-24 11:43 UTC
Labels: Feature request
