### ISSUE TITLE
Setting new properties on an object resets animation & other side effects

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#9129] opened 2019-11-19 11:50 UTC
When you set new visual properties on an ObjectRef, the animation is reset ~~and attached objects may blink out of existence for a frame~~ _(fixed by 10008 or 10015)_.
This happens even when the change is minor, like changing one texture in a set.
![blink](https://user-images.githubusercontent.com/42101236/69144208-14185800-0acb-11ea-95d0-77ae3a5d9290.gif)

**Comment by paramat** [comment] 2019-11-19 17:00
I can confirm this, setting any object property resets all of them, i remember discussing this when i was working on object properties a while back.
Seems to be that way because, years ago, object properties were few and rarely updated, so it was not much of a problem, but now increasingly is with increasing nunmbers of properties and more complex mod usage.
I guess, only reset a property if there has been a change to it.

**Comment by SmallJoker** [comment] 2019-11-19 19:25
Duplicate of #7781 which is a duplicate of #6572.

**Comment by paramat** [comment] 2019-11-19 20:06
Detailed discussion in #6572

**Comment by sfan5** [comment] 2020-06-10 08:07
This isn't an exact duplicate of #6572 and still not fixed, see https://github.com/minetest/minetest/issues/10017#issuecomment-641650079.

**Closed** 2020-06-11 19:12 UTC
Labels: @ Client / Audiovisuals, @ Script API, Bug
