### ISSUE TITLE
Inventory image rendering pixel imperfectness in window mode

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#11173] opened 2021-04-08 15:09 UTC
##### Minetest version
When I refer to "new minetest version":
```
Minetest 5.5.0-dev-85163b531 (Linux)
Using Irrlicht 1.9.0mt2
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR=<path to my build dir's locale>
```
When I refer to "old minetest version":
```
Minetest 5.5.0-dev-88d1fcfe2 (Linux)
```
(This is commit before https://github.com/minetest/minetest/commit/0d90ed6d921baefbb1a969df69f7b86e702e962f, since 0d90ed6 it looks like with the new version (tested).)

Irrlicht is at 4f90019dcba2ea85271d29c76aa702d73185cc2f.

##### OS / Hardware
Operating system: Linux, arch btw.
CPU: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx

GPU model: amd vega in my cpu
OpenGL version: 4.6

##### Summary

Inventoryimages aren't drawn or scaled correctly in window mode.
#11138 has changed the effect a little bit.
In fullscreen everything looks fine.

Screenshots of inventory, taken in window mode, `screen_w=1920, screen_h=1034`:
minetest version | raw | with annotations
----------------------|------|--------
old (88d1fcfe2) | ![screenshot_old](https://user-images.githubusercontent.com/7613443/114047339-eb445e80-9889-11eb-8db9-39fa23189974.png) | ![screenshot_old_marked](https://user-images.githubusercontent.com/7613443/114047349-ed0e2200-9889-11eb-894e-164440ef1c70.png)
new (85163b531) | ![screenshot_new](https://user-images.githubusercontent.com/7613443/114047317-e7184100-9889-11eb-9662-bb56750ff14a.png) | ![screenshot_new_marked](https://user-images.githubusercontent.com/7613443/114047330-e97a9b00-9889-11eb-8186-3d99aface74e.png)

(Item textures are from core base, mescons and minetest_game.)

Also, the items in hudbar _seem_ to have fewer of such issues.

Maybe related: #10733,  #1897

##### Steps to reproduce
- Look in your inventory at different items with inventoryimage (not 3D nodes).

**Comment by sfan5** [comment] 2021-04-09 16:05
With the "new" implementation that just draws 2D images this is definitely a duplicate of #2419

**Closed by sfan5** 2021-04-09 16:05 UTC
Labels: Unconfirmed bug
