### ISSUE TITLE
Liquid Option Improvements

### ISSUE THREAD

**Issue by TekhnaeRaav** [minetest/minetest#6983] opened 2018-01-28 20:32 UTC
##### Issue type

 -  Question/Feature request

I have a question: How does the game slow the player down, or have him sink when he is in a liquid? Is there a way to change the speed, like a thickness? If there is not I would highly suggest this adding this.

**Comment by TekhnaeRaav** [comment] 2018-01-28 20:45
Hmm...No way to turn off the waving of specific liquid.

I'll generalize this.

**Comment by SmallJoker** [comment] 2018-01-28 21:25
Duplicate of #401
> Also it would be nice to change player's speed according to liquid viscosity when he/she is in that liquid.

Also partial relevant: #5326

**Closed by SmallJoker** 2018-01-28 21:25 UTC
