### ISSUE TITLE
Attachments & camera lag behind by one (?) server step

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#12123] opened 2022-03-08 21:40 UTC
Be killed *while* falling (but not through fall damage). The camera will sometimes be way above the player model in 3rd person.

Attachments have similar issues, where an entity attached to a player may be unloaded as the player teleports and entities in the area the player just left are unloaded; `set_pos` should immediately set attachment positions to prevent this.

**Comment by SmallJoker** [comment] 2022-03-09 18:09
Please use two separate issues.

The attachment one is closely related to if not a duplicate of #11991, #10027.

**Comment by Zughy** [comment] 2022-05-07 22:41
Please @appgurueu open a separate issue as SmallJoker suggested. Closing here

**Closed by Zughy** 2022-05-07 22:41 UTC
Labels: Unconfirmed bug
