### ISSUE TITLE
HUD reliability issues when removing/updating close together

### ISSUE THREAD

**Issue by niansa** [minetest/minetest#9024] opened 2019-10-06 23:35 UTC
##### Minetest version

```
5.0.1
```

##### Summary

I am writing a game, but some Bug in the engine (client side, I guess) prevents me from removing a HUD with following code:
https://hastebin.com/exanafisec.lua
https://hastebin.com/amufijukac.lua
The HUD simply remains on screen, unless I put `playertools.texhud_remove()` into a `minetest.after(0.5, ...)`

##### Steps to reproduce

1. Get my game from https://git.tuxifan.ga/niansa/minetest-storybuilder/archive/03b9ccf2f4d6ed3b490dc31296e668dfa66f39e0.zip (save as games/StoryBuilder) and enable all mods listed in README.md
2. Load following world with damage enabled in singleplayer mode: https://git.tuxifan.ga/niansa/minetest-storybuilder/releases/download/0.9-beta/StoryTest.zip
3. You will fall deep and get damage, run `/cheating allow`
4. Now, run `/reloadstage` and see the loading HUD **not** disappearing

##### Note
I checked my ENTIRE code together with somebody else and found nothing wrong

**Comment by rubenwardy** [comment] 2019-10-07 04:35
Please attempt to create a minimal reproducible example, ie: the smallest amount of code to recreate this problem

**Comment by jastevenson303** [comment] 2019-10-07 04:54
If you remove the element, the ID is freed, and you really have to keep
very good track of the HUD IDs.  I've often resorted simply to changing
their text value, for example to "" in order to make them invisible.
Doesn't always work, but I'd thought I'd throw it out there just in case.

**Comment by niansa** [comment] 2019-10-07 08:29
Changing to "" seems a good idea. I'll try on my way to france!

**Comment by niansa** [comment] 2019-10-07 11:39
Nope, didn't fix it.

**Comment by SmallJoker** [comment] 2019-10-07 16:41
Packets are not guaranteed to arrive in order. Usually this does not matter, but the HUD does yet not combine & send in intervals to avoid such issues.
Very close duplicate of: #2862

**Comment by niansa** [comment] 2019-10-13 16:27
Downside of UDP :-(

**Comment by rubenwardy** [comment] 2020-05-10 15:50
This seems high priority to me? Having broken HUD reliability is pretty bad

**Comment by rubenwardy** [comment] 2020-05-10 15:52
This should be fixed by #9611

**Closed by rubenwardy** 2020-05-10 15:52 UTC
Labels: @ Network, Bug, High priority, Possible close
