### ISSUE TITLE
Using MSAA on (certain?) AMD GPUs leads to glitches on semi-transparent materials

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#10676] opened 2020-11-28 20:55 UTC
##### Minetest version
```
Minetest 5.4.0-dev-872dce502 (Linux)
```

##### OS / Hardware
Operating system: Void Linux/musl on amd64, using [Sway](https://swaywm.org) as the Wayland compositor.
GPU model: AMD Radeon RX 560 (“Radeon RX 560 Series (POLARIS11, DRM 3.39.0, 5.9.8_1-00001-g9b8d6552f90e, LLVM 11.0.0)” according to `glxinfo`)
OpenGL version: 4.6

##### Summary
If MSAA is enabled while running Minetest under XWayland (tested with Sway only), node and cloud wireframes are visible through any translucent formspec. Happens both in the main menu and in-game. Doesn’t happen on Xorg.
![screenshot_20201128_233659](https://user-images.githubusercontent.com/7352626/100525740-2d6edc80-31d4-11eb-940d-5287eb856b01.png)

##### Steps to reproduce
Start Minetest under Sway, with MSAA enabled (texture filtering doesn’t matter).

**Comment by Zughy** [comment] 2022-06-16 17:56
@numberZero can this still be reproduced?

**Comment by DragonSWDev** [comment] 2022-07-06 17:00
I can still confirm issue on Fedora 36 with Radeon RX570 and Minetest 5.5.1. In my case it happens on both Wayland and X11 sessions, after disabling antialiasing in settings issue disappears.

**Comment by sfan5** [comment] 2022-07-09 19:17
I can reproduce this on Xorg too, hence the title change.
<pre>
INFO[Main]: Irrlicht: Using renderer: OpenGL 4.6
INFO[Main]: Irrlicht: AMD Radeon RX 6500 XT (beige_goby, LLVM 14.0.6, DRM 3.46, 5.18.9-arch1-1): AMD
</pre>

**Comment by rollerozxa** [comment] 2024-02-15 17:24
https://github.com/minetest/minetest/pull/14338 getting merged made me want to check if these glitches still occur with MSAA (FSAA) and it looks to have been fixed in Mesa sometime:

![image](https://github.com/minetest/minetest/assets/60856959/7295ec2c-99df-4283-8e08-dc5a6a7c1c11)

(For comparison this is how it looked like for me two years ago or so)
![image](https://github.com/minetest/minetest/assets/60856959/72dd53a9-e2f5-4a83-9b69-79303d1305f3)

Anyone else can still reproduce the wireframe glitching on a recent version of Mesa?

**Comment by appgurueu** [comment] 2024-02-15 17:36
Currently can't reproduce either (tested with 5.8.0). `glxinfo` says `OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1` and `OpenGL renderer string: AMD Radeon Vega 8 Graphics (raven, LLVM 15.0.7, DRM 3.42, 5.15.0-94-generic)`.

**Comment by rollerozxa** [comment] 2024-02-15 17:47
Sounds like it has been fixed in Mesa then. My `glxinfo` says `OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.3.5-arch1.1` and `OpenGL renderer string: AMD Radeon RX 560 Series (radeonsi, polaris11, LLVM 16.0.6, DRM 3.57, 6.7.4-arch1-1)`. Looking at the date of my old screenshot I would have been using Mesa 21.3.5 back then.

I also use Wayland (KDE Plasma) right now, if that's relevant.

**Closed** 2024-02-23 23:12 UTC
Labels: Bug, @ Client / Audiovisuals, Upstream issue, Possible close, Shaders
