### ISSUE TITLE
Mouse wheel rotation

### ISSUE THREAD

**Issue by PavanLuca** [minetest/minetest#13516] opened 2023-05-17 17:29 UTC
## Problem

As mouse wheel rotation is inverted I was terrible when playing the first times on Capture The Flag server and now I'm not much better anyway, I keep on confusing the directions of scrolling my equipped stuff making my performance scary.

## Solutions

Add mouse wheel inversion option.

## Alternatives

Add another mouse wheel inversion option.

**Comment by Desour** [comment] 2023-05-17 18:47
There's already `keymap_hotbar_previous`/next, but one can't bind it to mouse wheel up/down.
I therefore consider this a duplicate of #10927.

**Comment by rubenwardy** [comment] 2023-05-17 19:05
#10927 is purely a GUI task, the settings to allow rebinding mouse keys already exist in minetest.conf

**Closed** 2023-05-31 05:30 UTC
Labels: Feature request, @ Client / Controls / Input

**Comment by PavanLuca** [comment] 2023-06-04 13:28
You mean that can be edited only on minetest.conf while it's not possible directly from settings?

**Comment by srifqi** [comment] 2023-06-04 14:30
The feature has been added to the `master` branch. You can compile it yourself or use the daily build to use it (or wait for the next release). The settings are in Controls -> Keyboard and Mouse.

**Comment by PavanLuca** [comment] 2023-06-04 15:11
Yeah, I checked settings again and I see that for now I can only invert vertical visual movement and mouse sensitivity. I prefer to invert mouse wheel from a setting rather than editing files, I don't want to get problems even there. So I'll wait for the new release.
