### ISSUE TITLE
Send mapblocks to players only when it's not up to date

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6431] opened 2017-09-17 17:24 UTC
Currently when you join a server and walk around, the map is loaded from the server. You can enable local map saving to get a copy of the map but the local copy is not used.

You could save the date when the mapblock was modified last and enable local map saving by default.
When you walk around, the client loads a number of mapblocks. When loading them from the server, the client could send the dates of the local copies and then for each mapblock the server either tells the client that the local copy should be used because it's up to date or it sends the up to date mapblock.

This could significantly decrease mapblock loading. If a player lives somewhere away from spawn, the map may not get changed there when he is absent. When he comes back, he could load 12 mapblocks, the dates of them are sent to the server at once and the server responds that they are up to date, then they're loaded from disk (if not already done).

Btw: Also, while asking the server for the blocks you could load the map from the local copy and show it but disallow the player to move there until the client knows that it's up to date or got the block from the server.

idea from https://forum.minetest.net/viewtopic.php?f=7&t=18000

**Comment by rubenwardy** [comment] 2017-09-17 17:49
Duplicate of #353

**Closed by rubenwardy** 2017-09-17 17:49 UTC
