### ISSUE TITLE
Possibility to assign a custom name to unlisted servers

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#12674] opened 2022-08-09 13:30 UTC
## Problem

I haven't opened MT on one of my PCs for a few weeks and now I find myself with 4 IP addresses I have no idea about what they correspond to (because they're not listed, so they appear in the format XXX.XXX.XXX.XXX:YYYYY)

## Solutions
title

**Comment by sfan5** [comment] 2022-08-09 13:38
duplicate of #9932

**Closed by sfan5** 2022-08-09 13:38 UTC
Labels: Feature request, @ Mainmenu, UI/UX
