### ISSUE TITLE
Multi-second lag in default singleplayer game

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2145] opened 2015-01-18 05:09 UTC
No extra mods except minetest-time (for the lag display), yet singleplayer is now unplayable for me.

Look at the lag in the lower right-hand corner, then at the mods at the top, then CPU useage, etc.

![screenshot from 2015-01-17 22 22 56](https://cloud.githubusercontent.com/assets/8821916/5791469/620bf6ee-9ea5-11e4-949f-9501034e015b.png)

![screenshot from 2015-01-17 22 23 19](https://cloud.githubusercontent.com/assets/8821916/5791477/de5213be-9ea5-11e4-9cc1-e5d29268b22f.png)

Screenshot taken while using a client from around August 2014, exact same mods:

![screenshot from 2015-01-17 23 45 38](https://cloud.githubusercontent.com/assets/8821916/5791480/eaaba77e-9ea5-11e4-9edc-a16a8e31fbec.png)

**Comment by Zeno-** [comment] 2015-01-18 05:35
@Wayward1 can you try adding (or changing the value if it's already there `liquid_loop_max = 10000` to your minetest.conf?

**Comment by Wayward1** [comment] 2015-01-18 05:39
I already did, per hmmmm/kwolekr's suggestion, and got no change

**Comment by Wayward1** [comment] 2015-01-21 00:45
If it helps any, for comparison, singleplayer in Freeminer works just fine: 
![screenshot from 2015-01-20 19 31 09](https://cloud.githubusercontent.com/assets/8821916/5829189/697f4d3e-a0dc-11e4-83ac-42a37d49db07.png)

**Comment by Wayward1** [comment] 2015-01-21 16:38
Just ran it through callgrind, here's the output: https://www.dropbox.com/s/988wurahjnuucud/callgrind.out.28254?dl=0

**Comment by Wayward1** [comment] 2015-01-21 17:07
Additional info: 
CPU: 2 x AMD A4-3300M APU with Radeon(tm) HD Graphics (AuthenticAMD) @ 800MHz
RAM: 4GB

**Comment by kwolekr** [comment] 2015-01-26 03:28
Hey Wayward, could you re-run valgrind, except this time with the option '--separate-threads=yes' ?
I know it's going to be excruciatingly slow but please bare with us, there aren't a whole lot of other options on how to diagnose the problem unless you'd be willing to bisect commits until you find the exact commit causing the SP lag

**Comment by Wayward1** [comment] 2015-01-26 15:58
No problem, I'll do anything to help figure this out.  Now, since Zeno's suggestion of disabling mesh caching greatly decreased my lag (from about 20+ seconds to around 5) I decided to run it through callgrind twice, once with it enabled and once disabled. I hope that helps somewhat.

With enable_mesh_cache = true:
https://www.dropbox.com/s/p2qgbzvwi8h1702/callgrind%28e_m_c%3Dt%29.tar.lzma?dl=0

With enable_mesh_cache = false:
https://www.dropbox.com/s/tywa4iup80tho11/callgrind%28e_m_c%3Df%29.tar.lzma?dl=0

**Comment by Wayward1** [comment] 2015-05-04 14:23
Possibly related to #2064?

**Comment by PilzAdam** [comment] 2015-07-21 11:53
Why is nobody doing anything about this? Every time I try to play Minetest I get annoyed by this after a few minutes. It's basically impossible to do anything in the game.

I play minetest_game without any additional mods or special minetest.conf settings.
I don't use luajit.
I have a an Intel core i7 with 8 cores @ 2.93 GHz, 4 GiB RAM and a Geforce GTX 460. These specs should be able to run a game like Minetest without 10+ seconds of lag.

**Comment by PilzAdam** [comment] 2015-07-21 11:56
Blocker label added, because this bugs makes Minetest unplayable.

**Comment by Zeno-** [comment] 2015-07-21 12:18
@PilzAdam I think because none of use have been able to reproduce?

If you experience the issue then that's awesome (in a strange way) because we need a dev who can reproduce and you obviously can.

**Comment by Wayward1** [comment] 2015-08-10 17:49
Just another example:
![screenshot_2015-08-10-11-39-41](https://cloud.githubusercontent.com/assets/8821916/9178810/9a3057ec-3f66-11e5-94bc-2a68f5cd2fe6.png)

**Comment by PilzAdam** [comment] 2015-10-26 21:24
Labels re-added because no reason was given why they were removed.

**Comment by PilzAdam** [comment] 2015-10-27 21:23
This may be to be related to the number of mapgen threads. I set the according second to 1 (previously is was 6 or 4), and I only get a lag of about half a second now (this is still unacceptable for singleplayer, but it's better than multiple seconds).

**Comment by est31** [comment] 2016-02-23 00:34
@PilzAdam sorry but I can't reproduce. Sometimes yes there is a bit of a lag, but I can't really reproduce it, so I can't really debug it either.

If you want to find the reason for the issue, feel free to work on this. But I can't really help as I can't reliably reproduce it. Nor can other devs, as it seems. Not doing any release while this bug isn't fixed is a bit unfair IMO to those players who want a release. That's why I removed the blocker label.

If you agree to work on it, we can keep the blocker label, but, as you are the only dev who can reproduce this, I'd remove it again if you can't work on it. Probably you are busy so I'd say I'll keep the label for two weeks, and then remove it if I haven't heard anything from you.

@Wayward1 you can try to bisect the issue and find out the commit that introduced the lag for you. That's the alternative pointed out by @kwolekr . Here you can read about how to do it: https://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git#Binary-Search

**Comment by paramat** [comment] 2016-02-23 14:27
I can't reproduce, i agree we should remove the blocker label soon.
And yes those who can reproduce this plese bisect.

**Comment by Wayward1** [comment] 2016-02-24 04:15
Okay, I'll try and bisect this sometime this week when I get a chance

**Comment by est31** [comment] 2016-03-09 02:32
@Wayward1 ?

**Comment by paramat** [comment] 2016-03-09 20:21
Removing labels.

**Comment by Wayward1** [comment] 2016-04-06 15:01
Sorry, I've been so busy with school and family matters lately, I'll bisect when I get a chance

**Comment by rubenwardy** [comment] 2016-04-06 15:45
Dropbox links are broken

**Comment by magicvodi** [comment] 2016-04-21 10:46
I have the same issue, the input lag is about 1 sec.
System: Arch linux, i5-3210M, integrated graphics, 8GB RAM
Minetest 0.4.13

Shall i provide additional information?

**Comment by Wayward1** [comment] 2016-04-30 04:38
@rubenwardy, that's what I get for cleaning out my dropbox without checking to see if the files are still used somewhere :P

**Comment by SmallJoker** [comment] 2017-08-01 09:35
Is this bug still present in 0.4.16? Closing soon for being possibly outdated, unless one can reproduce this bug.

**Comment by paramat** [comment] 2017-08-01 19:20
@Wayward1 @magicvodi still happening in 0.4.16?
Closing, old issue without responses, many cannot reproduce and we can re-open if it occurs again.

**Closed by paramat** 2017-08-01 19:20 UTC
Labels: Possible close, Unconfirmed bug
