### ISSUE TITLE
WASM

### ISSUE THREAD

**Issue by zaoqi-unsafe** [minetest/minetest#8436] opened 2019-04-01 04:53 UTC
##### Issue type

 
 - Feature request
 
 
##### Minetest version

```

```

##### OS / Hardware

Operating system:
CPU:

GPU model:
OpenGL version:

**Comment by benrob0329** [comment] 2019-04-01 05:22
Gonna need some kind of description here to give any kind of opinion...

**Comment by ClobberXD** [comment] 2019-04-01 06:54
Possible duplicate of #7745

**Closed** 2019-04-01 08:30 UTC
