### ISSUE TITLE
Allow using full keyboard

### ISSUE THREAD

**Issue by Niwla23** [minetest/minetest#10042] opened 2020-06-16 12:16 UTC
## Problem

You are very limited when it comes to controlling a game because you can only use the 5 keys and mouse

## Solutions

Allow full keyboard regcognisation
some event like minetest.on_key_press(key_name)

**Comment by sfan5** [comment] 2020-06-16 12:47
Please search the issue tracker before you open issues.
Duplicate of #2731, which was opened 5 years ago

**Closed by sfan5** 2020-06-16 12:47 UTC
Labels: Feature request
