### ISSUE TITLE
Dropped items slide on overhigh collisionboxes

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9295] opened 2020-01-08 19:49 UTC
##### Minetest version
```
5.1.0
```

##### Summary
If you drop an item on an overhigh collisionbox, it will slide indefinitely, until it slides off to a different node type. It's like ice but with no friction at all.

Yes, I made sure the nodes do not have the `slippery` group set.

##### Steps to reproduce
1. Place a node with an overhigh collisionbox (upper Y >= 0.5625)
2. Drop an item (`__builtin:item`) on the node

You can use `devtest` <https://git.minetest.land/Wuzzy/devtest> for testing:

* `testnodes:nodebox_overhigh` is a nodebox with upper Y = 1.0
* `testnodes:nodebox_leveled` for a leveled nodebox with height settable with the param2 tool. For the leveled nodebox, the sliding starts with `param2` at >= 68.

**Comment by SmallJoker** [comment] 2020-01-09 17:39
Duplicate of #8967

**Closed by SmallJoker** 2020-01-09 17:39 UTC
Labels: @ Builtin, Bug
