### ISSUE TITLE
Custom buttons for android

### ISSUE THREAD

**Issue by Peachzin** [minetest/minetest#12715] opened 2022-08-21 05:44 UTC
The controls that we have are fine for simple games/mods, but it's really frustrating when we have some games like mineclone or a server, that we can't use x item or do x thing because there's no button on the touchscreen for it.

The best solution for me.

I don't know anything about programing so it's just an idea. For me the best way to fix this, is to add some sort of way to costumize the ui. Being able to move the controls and that stuff. But what i really want is the ability to add new buttons, and be able to bind those buttons to whatever keyboard or mouse key you like. This for me would be perfect, but i don't know if it is too hard to make.

One alternative i have it's to just add new aux buttons, i don't know maybe 4 of them or more? And then be able to change the keybinds to whatever you want including mouse, in my head this seems easier, and it would be great too.

I would like to know what the devs thinks about this, and if they are interested or not, or maybe already have another solution.

**Comment by Zughy** [comment] 2022-08-21 10:19
Duplicate of #8541

**Closed by Zughy** 2022-08-21 10:19 UTC
Labels: Android, Request / Suggestion, @ Client / Controls / Input
