### ISSUE TITLE
Textures moving if Parallax Occlusion is active

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6582] opened 2017-11-04 18:24 UTC
Currently I play with Parallax Occlusion active and I noticed, that the textures are moving if I place a node. That irritates when building

You can see it on the right side of the picture. Sorry for the change of brightness. That's caused by the twilight

Edit: Normal mapping has to be active too. If both are active, this happens.

![parallaxocclusion](https://user-images.githubusercontent.com/16163058/32408222-b1aa2f62-c194-11e7-97d8-f97ddc501252.gif)

**Comment by paramat** [comment] 2017-11-04 19:38
Is the moving region a mapblock?
Duplicate of #6545

**Closed by paramat** 2017-11-04 19:38 UTC
Labels: @ Client / Audiovisuals, Bug, Shaders
