### ISSUE TITLE
Allow For Animated Item Textures

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#12955] opened 2022-11-12 07:52 UTC
## Problem

When you enchant an item in MineCraft, the enchanted item has this animated glint effect that wraps around the item. This does not seem possible to replicate in MineTest right now as far as I know, which would have been beneficial for MineClone 2.

## Solutions

Make it possible for animated textures to wrap around items.

## Additional context

![Enchanted_Iron_Pickaxe](https://user-images.githubusercontent.com/114245896/201464508-6cabcb35-123e-4024-828e-d34387612f00.gif)

**Comment by Desour** [comment] 2022-11-12 14:38
Duplicate of #4758.

**Closed** 2022-11-12 14:51 UTC
Labels: Duplicate, Feature request
