### ISSUE TITLE
In function ‘SRP_Result H_ns(__mpz_struct*, SRP_HashAlgorithm, const unsigned char*, size_t, const unsigned char*, uint32_t)’,

### ISSUE THREAD

**Issue by Git-Forked** [minetest/minetest#11280] opened 2021-05-21 02:04 UTC
```
In function ‘SRP_Result H_ns(__mpz_struct*, SRP_HashAlgorithm, const unsigned char*, size_t, const unsigned char*, uint32_t)’,
    inlined from ‘int calculate_x(__mpz_struct*, SRP_HashAlgorithm, const unsigned char*, size_t, const char*, const unsigned char*, size_t)’ at /home/rick/minetest/src/util/srp.cpp:455:13:
/home/rick/minetest/src/util/srp.cpp:432:8: warning: ‘void* memcpy(void*, const void*, size_t)’ forming offset [64, 4294967294] is out of the bounds [0, 64] of object ‘ucp_hash’ with type ‘unsigned char [64]’ [-Warray-bounds]
  432 |  memcpy(bin + len_n, bytes, len_bytes);
      |  ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/rick/minetest/src/util/srp.cpp: In function ‘int calculate_x(__mpz_struct*, SRP_HashAlgorithm, const unsigned char*, size_t, const char*, const unsigned char*, size_t)’:
/home/rick/minetest/src/util/srp.cpp:443:16: note: ‘ucp_hash’ declared here
  443 |  unsigned char ucp_hash[SHA512_DIGEST_LENGTH];
      |                ^~~~~~~~
```

Latest version of Minetest, error occurs during build.
Minetest still builds, but I am reporting this bug so it can be caught early, rather than cause issues later on.

```
Minetest 5.5.0-dev-4152227f1 (Linux)
Using Irrlicht 1.9.0mt2
Using LuaJIT 2.0.5
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```
PS: Feel free to rename this bug to something more suitable.

**Comment by SmallJoker** [comment] 2021-05-21 11:47
Where is the error? I can only see warnings in this report.

**Comment by Git-Forked** [comment] 2021-05-27 09:17
It must be just warnings then.

**Comment by sfan5** [comment] 2021-12-01 21:57
duplicate of #10238

**Closed by sfan5** 2021-12-01 21:57 UTC
Labels: Low priority
