### ISSUE TITLE
Performance: visible distance works wrong

### ISSUE THREAD

**Issue by JeanPaulLucien** [minetest/minetest#13088] opened 2022-12-28 17:49 UTC
##### Minetest version

```
Latest
```

##### OS / Hardware

Operating system: Windows
CPU:

##### Summary

Distance view does not work for vertical distance. If you on high building you will see ground.

##### Steps to reproduce

1. Enter the game.
2. Make minimum distance view (20 meters).
3. Put blocks under you foot to be higher.

**Comment by SmallJoker** [comment] 2022-12-28 18:08
40m above ground. Cannot reproduce your issue as of Minetest 5.7.0-dev 89e7f72c on Linux.

![grafik](https://user-images.githubusercontent.com/1497498/209854412-2d1f2ea2-a970-4538-9b38-1614591b96c5.png)

**Comment by appgurueu** [comment] 2022-12-28 19:41
Are you sure that you haven't accidentally enabled the "infinite view range" option, which would keep showing you all loaded mapblocks?

**Comment by Zughy** [comment] 2022-12-28 19:54
Considering the fact you've spammed 5 low-quality issues in not even 2 hours, I'll trust SmallJoker and appgurueu: closing

**Closed by Zughy** 2022-12-28 19:54 UTC
Labels: Unconfirmed bug
