### ISSUE TITLE
Upside down screen (Android)

### ISSUE THREAD

**Issue by AspireMint** [minetest/minetest#12871] opened 2022-10-17 19:12 UTC
##### Minetest version
Minetest 5.5.1 (official from Google Play)

##### OS / Hardware
Operating system:
Android 11

OpenGL version:
OpenGL ES-CM 1.1

##### Summary
In advanced settings, if i change undersampling to 2 or more, it will flip screen like this:

![1666032049382](https://user-images.githubusercontent.com/37676291/196261677-5a1e485c-c307-4cd0-8a9a-90aa8d393aaa.jpg)

![1666032049364](https://user-images.githubusercontent.com/37676291/196261691-6909b2bb-d998-463f-b349-d9af99f02eba.jpg)

Not that its not playable, but i preffer default screen orientation :smile:

**Comment by sfan5** [comment] 2022-10-17 19:13
duplicate of #5929 probably?

**Comment by rubenwardy** [comment] 2022-10-17 19:28
duplicate of #5929

**Closed by rubenwardy** 2022-10-17 19:28 UTC
Labels: Unconfirmed bug
