### ISSUE TITLE
crash with unified dyes

### ISSUE THREAD

**Issue by jamesreqiuem** [minetest/minetest#14553] opened 2024-04-16 18:54 UTC
Greetings. I got this crash report, and every time I try to join the server the error repeats:

```
AsyncErr: Lua: Runtime error from mod '*builtin*' in callback luaentity_Step(): /home/james/.minetest/mods/unifieddyes/api.lua:52: attempt to index local 'digger' (a nil value)
stack traceback:
	/home/james/.minetest/mods/unifieddyes/api.lua:52: in function 'on_dig'
	/usr/share/minetest/builtin/game/falling.lua:289: in function 'try_place'
	/usr/share/minetest/builtin/game/falling.lua:398: in function </usr/share/minetest/builtin/game/falling.lua:314>
```

Minetest 5.8.0
Linux Mint 20.2 Cinnamon

Can anyone help me to get out of this??

**Comment by rubenwardy** [comment] 2024-04-16 19:07
It's weird that it says global there, as diggername should be a local variable. Have you modified the mod?

https://github.com/mt-mods/unifieddyes/blob/master/api.lua#L72

**Comment by jamesreqiuem** [comment] 2024-04-16 19:12
I didn't modified it. Line 72 in my api.lua is identical to the line in your link.
The error came after I blew up an area with TNT.

**Comment by jamesreqiuem** [comment] 2024-04-16 19:19
I'm sorry, you are right. I posted the wrong crash report. The report from my openingpost was after a modification attempt. The original crash report is:

AsyncErr: Lua: Runtime error from mod '*builtin*' in callback luaentity_Step(): /home/james/.minetest/mods/unifieddyes/api.lua:52: attempt to index local 'digger' (a nil value)
stack traceback:
	/home/james/.minetest/mods/unifieddyes/api.lua:52: in function 'on_dig'
	/usr/share/minetest/builtin/game/falling.lua:289: in function 'try_place'
	/usr/share/minetest/builtin/game/falling.lua:398: in function </usr/share/minetest/builtin/game/falling.lua:314>



Sorry!

**Comment by jamesreqiuem** [comment] 2024-04-16 19:21
I edited my starting post with the correct crash report.

**Comment by rubenwardy** [comment] 2024-04-16 19:23
Cc/ @wsor4035

**Comment by wsor4035** [comment] 2024-04-16 23:05
what mods are you using? seems this issue probably should have been filed at https://github.com/mt-mods/unifieddyes/issues

**Comment by jamesreqiuem** [comment] 2024-04-17 05:14
3D Armor
Animalia
ArtDeco
Automobiles Pack
Banners
Basic Materials and items
Biofuel
Bonemeal
C Doors
File Cabinets
Castle Gates
Castle Lighting
Castle Masonry
Castle Shields
Castle Storage
Castle Tapestries
Castle Weapons
Cblocks
Cement
Church Modpack
Extended Circular Saw
Colored Blocks
Creatura
Display Modpack
Storage Drawers
Ephesus
Extra Wool Stuff
Facade
Procedural Furniture
Greek
House Windows
Hand Dryer
Home Workshop modpack
Homedecor
Interior Decor
Laptop
Laptop Extend Pack 2
Laptop PC Pack 1
LootChest Modpack
Living Room Furnitures
LWColorable
Magic Materials
Mesecons
Mobs Redo API
More Structures
More Blocks
Morelights
morelights_dim
More Ores
Mud
Multidecor
Pipeworks
Place Rotated
Plaster
Poly Decor
Simple Furniture
Solid Color Blocks
Technic Plus Beta
Unified Inventory
Unified Dyes
Vision Lib
Wheitestone
Xcompat
X-Decor-libre

**Comment by SmallJoker** [comment] 2024-04-18 17:38
Related code:
https://github.com/minetest/minetest/blob/49ce5a2de633d751080a0c97b802ae48190bf911/builtin/game/falling.lua#L282-L298

This `on_dig` call was introduced 4 years ago in 723926a995.
This issue was caused by @fluxionary in https://github.com/mt-mods/unifieddyes/commit/5af9254c3#diff-03f26099aa13de776c192ea8143fa3cac7471f1ca076626465e92821420f79d0L62

Not a Minetest issue. Closing.

**Closed by SmallJoker** 2024-04-18 17:38 UTC
Labels: Question
