### ISSUE TITLE
Add more keybindings to use for (CSM/regular) mods

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#5543] opened 2017-04-08 11:54 UTC
If you playing with mods, there is a limit keybindings that can held for control. Well, needs more keybindings to support mods, even with client side mod needs support more keybindings.

Changing keybinding with multiple buttons by holding per 1, for example: "Ctrl+H", "Y+E+S" etc. Doing to for changing keybinding with multiple buttons at same time per 1, for example "F3-G", "C-A-T" etc.

**Comment by SmallJoker** [comment] 2017-04-08 14:22
Quite similar to #4536 and #3846
But definitely a dupe of #2731

**Closed by SmallJoker** 2017-04-08 14:22 UTC
Labels: Request / Suggestion
