### ISSUE TITLE
Head Movement

### ISSUE THREAD

**Issue by DreamBoi8** [minetest/minetest#12175] opened 2022-04-05 18:52 UTC
## Problem

I can't nod.
## Solutions

I want the players head to be able to me corresponding to the direction they are look. So I could look up then down and it'd look like I'm nodding.

## Alternatives

Maybe a mod?

## Additional context

Nothing

**Comment by rollerozxa** [comment] 2022-04-05 19:01
> Maybe a mod?

Maybe a mod indeed, see: [headanim](https://content.minetest.net/packages/Lone_Wolf/headanim/)

**Comment by Zughy** [comment] 2022-04-06 15:05
Duplicate of #1800

**Comment by rubenwardy** [comment] 2022-04-06 15:10
Duplicate of https://github.com/minetest/minetest/issues/1800

**Closed by rubenwardy** 2022-04-06 15:10 UTC
Labels: Feature request
