### ISSUE TITLE
Get the player pointed thing

### ISSUE THREAD

**Issue by runsy** [minetest/minetest#9805] opened 2020-05-04 10:08 UTC
Via API (client side). The info already is there (F5)

[See the discussion](https://forum.minetest.net/viewtopic.php?f=47&t=18543&hilit=player+pointed_thing)

This would be for advanced NPC behaviours and interactions.

**Comment by sfan5** [comment] 2020-05-04 11:17
duplicate of #9587

**Closed by sfan5** 2020-05-04 11:17 UTC
Labels: Feature request
