### ISSUE TITLE
Incorrect client-side placement prediction

### ISSUE THREAD

**Issue by pofdzm** [minetest/minetest#11255] opened 2021-05-08 23:14 UTC
Minetest 5.4.1
Windows

So basically, if I fastly right-click a couple of times while placing blocks, the block dupes, for example; I can place a block 3 times.

But when I break them, only the first one I placed gives me the block back, so I cant dupe the item that way, only the block.

The bad thing is you can stand on them so while in a minigame at air it can be a bit unfair.

I only tried it on single-player Minetest, I can also send a video if needed.

**Comment by pofdzm** [comment] 2021-05-08 23:18
Btw I realized something, if you do this glitch with dirt it also dupes the item. I mean, if you do this glitch and place 2 blocks of dirt using 1 dirt, you will get 2 dirt back.

**Comment by NathanSalapat** [comment] 2021-05-09 03:06
I believe this is normally caused by network latency, odd that it's happening in singleplayer though.

**Comment by hecktest** [comment] 2021-05-24 18:09
Unfortunately, single player can lag too. It's not just latency, the main thread being blocked has the same effect.

The block duplication happens due to prediction. The client places a block locally to keep things responsive, and anticipates a response from the server to tell it whether or not the action succeeded. This is why you can usually place a block in a protected area for a split second before the server deletes it.

If the false blocks persist even _after_ the server syncs up with you, then this is a legit bug.

Since collision and physics are also client side, this allows some movement cheating by a laggy player. It's analogous to how a laggy player can dig and walk through a protected wall. It's a logical problem with prediction itself; some of it could be mitigated by the engine but it's ultimately up to the mod developer to create anticheat measures that fit their particular threat model. Functionally, this is no different from noclip and fly cheats.

The dirt duplication thing is more worrying but I just reviewed the code and it should not happen, the actual act of digging and granting the player an item happens entirely server side. (think about it, there's script hooks into this so there's nothing that the client can be trusted to predict)

To make sure, you can test this in an isolated environment - create a flat map of nothing but stone, and give yourself a known amount of dirt nodes. Mess around with the dirt nodes and then gather them up and check their count - it should be conserved no matter what, if it isn't then we've got a serious bug on our hands. There are tools such as Clumsy which can help you simulate network issues while running a LAN server.

**Comment by SmallJoker** [comment] 2021-06-05 19:58
What's to be done here? The placement prediction is necessary to provide a smoother gameplay experience, on cost of "desync" issues caused by re-sending blocks to the client for correction.

**Comment by erlehmann** [comment] 2021-12-02 13:56
The only incorrect client side prediction bug I know is ghost slabs: Basically, you can place a bottom slab on a top slab and Minetest will sometimes render the upper thing as a full node on the client that placed it, making it possible for the client to hover over the ground. I knew how to reproduce it a few months ago, but I forgot.

**Comment by Zughy** [comment] 2022-04-29 21:57
@erlehmann please consider opening a separate specific issue for that. Closing

**Closed by Zughy** 2022-04-29 21:57 UTC
Labels: Unconfirmed bug, Possible close
