### ISSUE TITLE
Light on snow is not smoothed

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5063] opened 2017-01-17 19:03 UTC
I noticed, that the light on snow is not smoothed. 

![screenshot_20170117_200253](https://cloud.githubusercontent.com/assets/16163058/22035357/f9f6ba22-dcef-11e6-8f31-501a906f3521.png)

**Comment by est31** [comment] 2017-01-17 19:06
dupe of #3735 ?

**Comment by Taose** [comment] 2017-01-17 21:04
Following the thread through looks like it's a dupe of #104.

**Comment by MarkuBu** [comment] 2017-01-17 21:43
Both closed, but still not fixed

**Comment by Fixer-007** [comment] 2017-01-17 21:52
Yes, dupe. Lots of stuff won't work with smooth lighting

**Comment by paramat** [comment] 2017-01-18 21:59
Duplicate of #104 which should not have been closed, i re-opened it.

**Closed by paramat** 2017-01-18 21:59 UTC
Labels: @ Client / Audiovisuals, Duplicate
