### ISSUE TITLE
Let mods somehow listen to key presses

### ISSUE THREAD

**Issue by PureTryOut** [minetest/minetest#4689] opened 2016-10-28 17:17 UTC
From what I understand (as sfan5 explained to me in the IRC), currently mods can't listen to keybindings since they are processed entirely server-side. Even if it would be processed client-side, an use-case wouldn't just work on Android as well.

However, I would still like to see mods have the ability to listen for key presses. In my case, I want to make it so that if a player presses the middle-mouse button (if in creative mode) when pointing at a block, the pointed block becomes the new wielded item (like Minecraft creative mode). In the case of Android I could listen to a button press on a controller, or maybe a long press on the screen somewhere. Even an extra menu option would do. However, this would need mods to be able to listen to key presses.

**Comment by sofar** [comment] 2016-10-28 19:02
That would be best written as a client-side change, I feel. Then you wouldn't have to write any mod code or mod API code to handle this, and the client just selects the right inventory slot. You'd have to account for creative/noncreative to tell the server that you've picked up an item from the creative inventory, though.

**Comment by PureTryOut** [comment] 2016-10-28 19:46
Well my case is just an example. There could be tons of mods that want to use a special button to do something, probably most of the time open some kind of inventory (for example if they're in a vehicle or not), or to get out of something (like in Minecraft: press shift to get out of a boat or minecart).

**Comment by est31** [comment] 2016-10-28 19:48
Dupe of #2731

**Closed by est31** 2016-10-28 19:48 UTC

**Comment by PureTryOut** [comment] 2016-10-28 19:56
Woops sorry, didn't see it ;)
