### ISSUE TITLE
Discovery of announce LAN Servers

### ISSUE THREAD

**Issue by xeruf** [minetest/minetest#13102] opened 2022-12-29 23:41 UTC
## Problem

I wanted to play with my friends in a local network, but we always ended up entering the IP manually as the discovery of servers did not seem to work.

## Solutions

Auto-Discovery of locally announced servers.

Maybe related to https://github.com/minetest/minetest/issues/3609

**Comment by rubenwardy** [comment] 2022-12-29 23:55
Duplicate of #10208

**Closed by rubenwardy** 2022-12-29 23:55 UTC
Labels: Feature request
