### ISSUE TITLE
Wrong (empty) polish national chars in menus

### ISSUE THREAD

**Issue by vtold** [minetest/minetest#4152] opened 2016-05-22 06:23 UTC
After upgrading from 0.4.13 to 0.4.14 suddenly disappeared any national chars in menus.
In example:
"włcz" must be "włącz"
"usu" must be "usuń"
"wiat" must be "świat"
etc.
![22 05 2016 - 08 03 41](https://cloud.githubusercontent.com/assets/19513320/15452621/60956c7c-1ff6-11e6-8440-9fafb93f9cfe.png)

**Comment by sofar** [comment] 2016-05-22 06:25
What OS is this? Did you compile 0.4.14 yourself or did you install/upgrade your OS's packages?

You may have gotten a badly configured build, somehow, perhaps?

**Comment by vtold** [comment] 2016-05-22 06:31
This is openSUSE 13.2 XFCE but issue is also on Windows 10.
There was an upgrade by zypper in openSUSE (from 0.4.13) and simply unpacking minetest.zip in Windows10.
 
W dniu 2016-05-22 08:25:55 użytkownik Auke Kok <notifications@github.com> napisał:
What OS is this? Did you compile 0.4.14 yourself or did you install/upgrade your OS's packages?
You may have gotten a badly configured build, somehow, perhaps?

**Comment by PilzAdam** [comment] 2016-05-22 13:27
Maybe freetype is not compiled in? What is the output of `minetest --version`?

**Comment by vtold** [comment] 2016-05-23 15:17
As I mentioned before, problem is at two different OS'es (openSUSE and Windows 10) and after upgrading in Linux (via zypper) from 0.4.13 to 0.4.14 (without compiling anything) polish chars disappeared suddenly.

**Comment by ShadowNinja** [comment] 2016-05-23 16:29
Can confirm.  Setting `fallback_font_path = /usr/share/fonts/TTF/DejaVuSans.ttf` in minetest.conf fixed it, so it seems it's just a matter of the symbols not being included in the default fallback font.

**Comment by vtold** [comment] 2016-05-23 17:09
For your information: in my case, right path is:
`fallback_font_path = /usr/share/fonts/truetype/DejaVuSans.ttf`

**Comment by nerzhul** [comment] 2017-05-20 14:10
Duplicate

**Comment by apienk** [comment] 2017-10-04 11:48
*Please reopen.* This issue is still present in 0.4.16 and is likely caused by a potential bug in FontEngine and insufficiency of the Droid Sans fallback font.

_Potential bug in FontEngine:_
On Polish locale the FontEngine always skips the default font and tries to load the fallback font despite the fact that `Arimo-Regular.ttf` (the default font) contains all required Polish characters.

_Fallback font insufficient:_
By philosophy, the fallback font should contain the broadest possible set of characters, so that the system loads this large asset only when necessary. However, `DroidSansFallbackFull.ttf` is missing most Eastern European glyphs. Unfortunately, there are no usable replacements for Droid Sans as a fallback because it's the only legally open source font containing both Chinese+Japanese and Extended Latin glyphs.

_Temporary workaround:_
Set fallback font to Arimo:
`fallback_font_path = /usr/share/minetest/fonts/Arimo-Regular.ttf`

_Permanent solution:_
Fix font selection in FontEngine.

**Comment by rubenwardy** [comment] 2017-10-04 12:51
I agree that Minetest needs more polish in all areas

**Comment by apienk** [comment] 2017-10-04 12:58
I agree that's probably a minor issue but we're currently trying to get school teachers interested in Minetest and this kind of deficiency is very likely to put them off. We're using the workaround for the moment, so no hurry. Thank you for the great piece of software.

**Comment by SmallJoker** [comment] 2017-10-04 13:06
So we can't blame irrlicht this time?

**Comment by gang65** [comment] 2019-03-21 22:58
It is also impacting MineTest 5.0.0

**Comment by rubenwardy** [comment] 2021-01-31 18:53
Probably fixed by encoding changes in 5.4.0

**Comment by sfan5** [comment] 2021-01-31 19:03
This was fixed at some point either by updating the font or enabling the fallback font.
Current screenshot:
![grafik](https://user-images.githubusercontent.com/1042418/106394886-63605500-63ff-11eb-8a35-0127cef9b817.png)

**Closed by sfan5** 2021-01-31 19:03 UTC
Labels: @ Translation, Possible close, Unconfirmed bug
