### ISSUE TITLE
X-Ray

### ISSUE THREAD

**Issue by TechDudie** [minetest/minetest#12868] opened 2022-10-17 01:54 UTC
##### Minetest version

```
5.6.0
```

##### OS / Hardware

Operating system: macos
CPU: intel

GPU model: I don't think i have a gpu
OpenGL version: 2.1

##### Summary

Like the title says, xray is possible. The closest issue i could find to this is #12429, but it doesn't work for me anymore, and my method of reproducing and possible fix is a little different.

##### Steps to reproduce

I use this occasionally to find enemy tunnels on Rubenwardy Capture the flag. Dig really down, lower than the anticipated y level of the enemy tunnel, light the area (plunk a torch on the 1x1 ground) and place a block above you to form a 1x1x2 enclosure. Then enter 2nd or 3rd person and slowly and carefully move your camera around. At one point, the third person camera code gets stuck in the wall and, bam, theres the enemy tunnel, surprise them. I am including an image to show you the issue at hand.
![Screen Shot 2022-10-16 at 8 53 30 PM](https://user-images.githubusercontent.com/73961295/196072728-c40fb439-3026-42d8-b383-d6afcfdae608.png)
(the enemy was too lazy to tunnel, no tunnel exists in this photo)

**Comment by TechDudie** [comment] 2022-10-17 01:56
https://github.com/minetest/minetest/issues/12429#issuecomment-1152846652

build_inside_player does not need to be set to true, so server admins can't disable this.

**Comment by Desour** [comment] 2023-03-13 14:23
Duplicate of #10841 (point 1-).
(Let's use that issue for 3rd person camera glitches, and #12429 for the bug that you can see through the world if the camera near plane is partly inside a node.)

**Closed by Desour** 2023-03-13 14:23 UTC
Labels: Unconfirmed bug, @ Client / Audiovisuals
