### ISSUE TITLE
Weblate fails to update

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#8173] opened 2019-02-04 00:21 UTC
```
Weblate could not merge upstream changes while updating the repository.

sed: -e expression #1, char 70: unterminated `s' command
sed: -e expression #1, char 70: unterminated `s' command (1)

Check the FAQ for info on how to resolve this.
```

https://hosted.weblate.org/projects/minetest/minetest/#alerts
https://docs.weblate.org/en/latest/faq.html#merge

> In other words, a 100% translation in Weblate right now does not lead to an actual 100% translation in Minetest, since Weblate is outdated atm.

@Wuzzy2

**Comment by paramat** [comment] 2019-02-09 20:19
Might be fixed by #8206

**Comment by Wuzzy2** [comment] 2019-02-09 20:35
Well, first Weblate must pull from the repo again. Nothing will happen otherwise. I believe it will update automatically.
I have no control over Weblate.

**Comment by Wuzzy2** [comment] 2019-02-14 17:52
Bug is solved.
Nerzhul updated the PO files yesterday and today Weblate managed to pull it properly. Weblate is happy again, strings are up to date. #8206 definitely fixed this.

Post mortem:
The problem was definitely in Minetest, NOT in Weblate as some people believed. The reason why Weblate failed was a regression introduced in Minetest commit 5ef9056e89855660d93c4e8d98a7dbc349c1a7eb. Namely, `fgettext("")` was called, which you should NOT do (using empty string in Gettext has a special meaning)! This caused `util/updatepo.sh` to be confused and spit out garbage PO files that had their metadata removed. Without the metadata the PO files were broken and as a result, Weblate complained. Weblate behaved absolutely correctly.

I will soon post a follow-up issue because I just noticed there are some strings in advanced settings that are not translatable for some reason. :-( But this is a different issue.

Oh, and by the way: In my experience as translator, Weblate worked always fine. If anyone wants to claim again that Weblate is “an unfinished product” or “broken” or whatever, you better have some real evidence ready before you spit out FUD and suggest we replace it with proprietary services. Thank you very much.

**Comment by rubenwardy** [comment] 2019-02-14 18:14
I've always had a good experience with Weblate.

My problem with internationalisation is a technical one related to understanding how to support UTF-8 in my programs properly, not from those tools

**Closed** 2019-02-14 18:58 UTC
Labels: @ Translation, Blocker, High priority
