### ISSUE TITLE
Stuttering/jitter affecting fps (due to mesh updates)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3602] opened 2016-01-22 21:58 UTC
**Ingame stutter/jitter** is a large instantaneous fps drop that is very visible to the eye, best observed on good PC and has pretty big impact on playability (in singleplayer - badly, in multiplayer - much less).

**Important new data**: minetest 0.2.20110602_0 and **0.2.20110618_0** appears to have no visible stutter at all on my PC, yet **0.2.20110704_0** (including 0.2.20110731_3) versions does. This is caused by removal of sleep code in this https://github.com/minetest/minetest/blob/51cf464f7450ee31e3a986b521f90cc6195bb2fb/src/client.cpp#L42

When it stutters draw time on F5 graph has spikes like that: 
>15 15 15 15 15 60 15 15 15 40 15 15 15 70 15 15 15 120 15 15... (ms) etc.

Stutter coincides with mesh generation (uploading meshes to GPU) and incoming network packets.

Relevant links:
* https://github.com/minetest/minetest/blob/51cf464f7450ee31e3a986b521f90cc6195bb2fb/src/client.cpp#L42 (removal of this sleep part caused stutter since 2011)
* http://pastebin.com/raw/D44biexY (proposed hack to remove stutter, using on my builds with sleep 15)
* https://github.com/minetest/minetest/tree/81535f6277b66c869cda7125b2aeaf99e8078b92 (0.2.20110704 tree for inspection)
* http://irc.minetest.net/minetest-dev/2017-02-17#i_4813656 (discussion with celeron55 commenting on the issue, look through this day)
* https://github.com/minetest/minetest/blob/master/src/client.cpp#L535
* https://i.imgur.com/lKkvRHs.png (drawtime with sleep in singleplayer)
* https://i.imgur.com/DBKMzn4.png (drawtime with IF-method in singleplayer, worse)
* https://imgur.com/a/bWJoe (walk in vanessa dreambuilder survival, no fix)
* https://imgur.com/a/9qd0T (walk in vanessa dreambuilder survival, with sleep 15 fix)
* https://imgur.com/ypGwowQ (excellent demo of jitter while using sofar's torch mod with wield light, https://github.com/minetest-mods/torches)
* https://imgur.com/8Zz4woj (jitter at "Just Test" 0.4.12 multiplayer server)
* https://imgur.com/erdbo5l (jitter while mining single block)
* https://imgur.com/mg7UypX (walking in mindevtest with flat mapgen)
* https://imgur.com/q1F3Uyt (stuttering in minetest 0.3.1)
* https://imgur.com/19RI6vy (stuttering in minetest 0.3.1)
* https://forum.minetest.net/viewtopic.php?f=6&t=13360
* http://irc.minetest.ru/minetest-dev/2015-12-16#i_4476116

Workarounds:
* https://github.com/minetest/minetest/pull/5270 - main workaround, use value 15 for good results **(merged into the game!)**
* http://pastebin.com/raw/D44biexY (with sleep_ms(15);) - helps a lot
* https://github.com/minetest/minetest/pull/5262 - slightly helps when used with minimal setting at 1
* https://github.com/minetest/minetest/pull/5050 - does not help
* https://github.com/gregorycu/minetest/tree/Jitter - does not help
* max_simultaneous_block_sends_server_total = 1 in minetest.conf - slightly helps

After some investigation with sleep_ms(15); it becomes evident that minetest has ~~at least two kinds~~ many kinds of stutter:
+ stutter due to mesh updates (described by this issue, "mostly fixable by sleep method", most frequent and annoying problem since 2011)
+ stutter/freeze due to kaeza's signs entity loading, visible on mainloop_other (described in https://github.com/minetest/minetest/issues/3758, it appears as small-medium stutter in singleplayer, and as very large freeze up to 1.5 sec on Vanessa's servers spawns during sign text loading, example: https://imgur.com/a/jVihx). 
+ stutter due to unknown causes, visible on mainloop_other (described in https://github.com/minetest/minetest/issues/3758)
+ stutter due to unknown causes that does not correlate much with mesh updates and mainloop_other, can be quite high, evident while using PR5270 with small amount of sleep (7a4878c engine): https://i.imgur.com/igeBgdQ.png and https://i.imgur.com/uFoRHse.png

Related: http://dev.minetest.net/profiler_graph

**Cleaned up this issue**

**Comment by kilbith** [comment] 2016-01-22 23:23
Dupe of : 
- https://github.com/minetest/minetest/issues/1404
- https://github.com/minetest/minetest/issues/2780
- https://github.com/minetest/minetest/issues/2938

**Comment by paramat** [comment] 2016-01-23 10:29
This seems to have got worse after a few months ago, perhaps it's due to the change to vertextangents? #3530 Every vertex now carries extra data whether shaders are enabled or not. RBA will hopefully be able to fix this soon.

**Comment by Fixer-007** [comment] 2016-01-23 12:14
I remember stuttering since 0.3.* :)

**Comment by Fixer-007** [comment] 2016-02-02 18:53
Hmm, looks like place for thinking is client.cpp with QueuedMeshUpdate things

**Comment by Fixer-007** [comment] 2016-02-08 17:28
In latest git in singleplayer on my small "Just Test" server copy, I've noticed that "shaders off" mode increases fps by +18%, but stutter is also much-much more serious, I did few automated tests and made graphs that demonstrate the issue.
![mt-0 4 13-b44da49-shaders-on-off](https://cloud.githubusercontent.com/assets/16494741/12893390/902c2bd2-ce99-11e5-9791-2b2ce72dc565.png)

**Comment by stujones11** [comment] 2016-02-09 20:46
This problem started around version 0.4.9ish for me, about the time of the first android port. I am not sure if that is related but it seems to have gotten progressively worse with each new release since. That said, some recent improvements in mt_game seem to have improved things a little but it's still nowhere near as smooth as it used to be.

**Comment by Fixer-007** [comment] 2016-02-15 17:14
Some examples of stutter:
+ usual one on "Just Test" multiplayer server: https://imgur.com/8Zz4woj
+ placing one block in quite environment on same server: https://i.imgur.com/erdbo5l.gif

**Comment by Fixer-007** [comment] 2016-03-13 23:12
PR #3502 contains some fixes that fix most of my stutter problems, gameplay is very smooth with it with only occasional spikes in large forests.

**Comment by Fixer-007** [comment] 2016-03-31 15:16
New commit is in the works, can't compile it right now, but it can potentially help: https://github.com/gregorycu/minetest/tree/Jitter

**Comment by Fixer-007** [comment] 2016-05-04 16:28
Another thing, you can observe it by downloading https://github.com/minetest-mods/torches it has wield light by default when you take torch in your hand, load flat mapgen, find desert, make sure everything is generated, start walking with torch, you will observe this.
Example: https://imgur.com/ypGwowQ (spikes are pretty large, from 0.007 to 0.02 or even 0.03 sec in draw time). This performance is not good at all.

**Comment by Fixer-007** [comment] 2017-02-06 21:54
On the other hand minetest 0.2.20110602 does not stutter for me, so it is nice beginning point to think :p

**Comment by paramat** [comment] 2017-02-07 19:21
I've noticed this get worse recently, possibly due to everything being smooth-shaded now, even plantlike.
When flying at speed above a landscape i can get occasional half-second freezes.
Not sure if plantlike really needed to be smooth-shaded, and it gets used in high numbers.

**Comment by Fixer-007** [comment] 2017-02-07 19:46
I did some tests of new smooth lighting (with fraps and detailed output) some time ago, it is not affecting the stutter, it stutters as before pretty much. It is different problem.

**Comment by paramat** [comment] 2017-02-07 19:55
Good i hope you're right.

**Comment by Fixer-007** [comment] 2017-02-07 19:57
Another example, farmap2.0 had a bug that reduced amount of mapblock loading, was literally stutter-free, but then celeron55 fixed it and stutter came back.

**Comment by Fixer-007** [comment] 2017-02-07 20:23
For now I tried some antijitter hacks some time ago:
https://github.com/minetest/minetest/pull/5050 - does not help
https://github.com/gregorycu/minetest/tree/Jitter - does not help

**Comment by numberZero** [comment] 2017-02-07 21:48
I confirm the bug. But the mesh generation is performed in a separate thread(s), it should not be able to do that. And it would have the same effect both in sp and mp. But at the same time it seems to do that. I suspect the reason is in some inter-thread communication, e.g. it might perform some heavy copy when it should not, or simply lock a mutex... (Also, does it drop duplicate entries from the queue? I mean, when the block is updated faster that the mesh is generated).

**Comment by paramat** [comment] 2017-02-07 22:09
Thanks good to know. I had a 1s freeze recently it was scary, never happened before.

**Comment by paramat** [comment] 2017-02-07 22:47
Fixer just saw your first results so i'm not concerned about smooth lighting affecting this issue. Thanks.

**Comment by Fixer-007** [comment] 2017-02-08 00:52
BTW, proller advertised his freeminer fork having less stutter, in 0.4.13 times I tried to compare it with "same" config and close to "same" mapgen, and indeed fraps gave me much better results, so our devs can do better for sure, there are ways for improvement :)

**Comment by Fixer-007** [comment] 2017-02-08 01:08
>Thanks good to know. I had a 1s freeze recently it was scary, never happened before.

1sec is big freeze compared to stuttering I have in minetest, that feels more like outside cause (outside process, disk i/o, not enough system ram). Typical maximum stuttering in minetest I had is in 100-200 ms range (roughly). In fact large scary multisecond freezes like that I experienced when amount of RAM was critically low, just after that windows warned me to close applications to avoid problems.

**Comment by Fixer-007** [comment] 2017-02-17 16:39
@lhofhansl 
After looking at https://github.com/minetest/minetest/commit/02006a95402c41833779e3825c44b39d600e566b I decided to add that sleep_ms(50); into current MeshUpdateThread::doUpdate() in client.cpp and stutter/jitter was **eliminated**, map loading is somewhat slower though, but I don't care.

**Comment by paramat** [comment] 2017-02-17 16:53
Interesting.

**Comment by paramat** [comment] 2017-02-17 17:04
Maybe a balanced value of sleep time should be found.

**Comment by Fixer-007** [comment] 2017-02-17 17:23
After testing on my PC sweet spot is somewhere around 15-20ms

**Comment by paramat** [comment] 2017-02-17 18:06
Might be better to make mesh processing more spread out as celeron55 suggests http://irc.minetest.net/minetest-dev/2017-02-17#i_4813972

**Comment by Fixer-007** [comment] 2017-02-17 19:02
Did a benchmark with sleep 15ms to compare with older data, fps was much higher due to slightly slower mapblocks speed load, https://i.imgur.com/F8Hqpwk.png - frame distribution is much better, much less big spikes, visually, 3 min fly above huge jungle forest was very smooth.

**Comment by numberZero** [comment] 2017-02-18 14:26
@Fixer-007 then make a PR =)

**Comment by Fixer-007** [comment] 2017-02-18 14:36
Nah, I have low experience with PRs, and some people want to look deeper into the problem, sleep 15-20 ms is just a workaround.

**Comment by numberZero** [comment] 2017-02-18 16:14
@Fixer-007 I do understand there is some deeper problem, mesh generation should not lock anything. But a workaround would be very nice.

**Comment by paramat** [comment] 2017-02-18 17:56
@lhofhansl in case it's useful for testing see #5262

**Comment by Fixer-007** [comment] 2017-02-18 18:20
@numberZero I'm not good at coding/prs, If you can, please make a PR that adds configurable sleep time, enabled by default with value 15 ms, and range from disabled=0 to 50ms.

**Comment by numberZero** [comment] 2017-02-18 18:55
@Fixer-007 Done, #5270.

**Comment by Fixer-007** [comment] 2017-03-13 21:42
@lhofhansl @numberZero 
I did another experiment, started a clean v7 world on newest engine, ```/grantme all``` and executed: ```/emergeblocks (-2000,-32,-2000) (2000,33,2000)``` and looked into ground (/emergeblocks generates new blocks in specified geometry).

I observed lots of spikes in mainloop_draw up to 58 ms or even more during process of generation, it looked like this: https://i.imgur.com/U5wImto.png (pretty few spikes in just this moment). Does this evidence help in some way?

**Comment by numberZero** [comment] 2017-03-14 17:02
Spikes in mainloop_draw... strange... @Fixer-007 was minimap enabled during the test?
BTW, I just noticed there are some problems with thread safety in minimap code: data is shared by two threads, but only one uses mutex...

**Comment by Fixer-007** [comment] 2017-03-14 19:05
Nope, I always play with minimap off.

**Comment by paramat** [comment] 2017-03-26 05:07
#5270 merged.

**Closed** 2021-03-18 12:56 UTC
Labels: @ Client / Audiovisuals, Performance, Possible close
