### ISSUE TITLE
Thicker Underwater Fog?

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#13214] opened 2023-02-17 10:06 UTC
## Problem

When you go underwater, the fog doesn't really get any thicker, allowing you to see as far as you can on land.

## Solutions

Make it so going underwater makes the fog thicker.

## Alternatives

Add the above as an optional thing instead that the subgame can customise.

## Additional context

Something similar to this already happens when you go inside a cloud, so an effect similar to that would be great.

**Comment by Desour** [comment] 2023-02-17 14:17
Duplicate of #7035.

**Closed as completed** 2023-02-17 15:18 UTC
Labels: Feature request
