### ISSUE TITLE
Minetest is choosing the wrong keyboard layout.

### ISSUE THREAD

**Issue by Anglodel** [minetest/minetest#13031] opened 2022-12-08 00:41 UTC
##### Minetest version

```
Minetest 5.6.1 (Linux)
Using Irrlicht 1.9.0mt8
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

##### OS / Hardware

**Operating system :** Arch Linux x86_64 (BTW™)
**Kernel :** 6.0.10-zen2-1-zen
**Desktop Environment :** Kde Plasma (Wayland + X11)
**CPU :** Intel i5-10400 (12) @ 4.300GHz

##### Summary

Hi,
I’m using by default a Dvorak-like keyboard for the French language, the BÉPO keyboard layout.
But two things prevent me to play :
* The natural key for me for the forward action in the game would be the accented letter `é`, as it is placed on the `w` key for a Qwerty keyboard, or the `z` for an Azerty one. Yet at the moment, Minetest does not seem to handle accented letters in its possible key-binding settings.
* So in order play the game I have to change the keyboard layout, but Minetest seems to choose the default one instead of the one used at the time of the launch. I thus have to change the default keyboard layout to azerty or Qwerty in my system settings. It’s doable, but not really a user-friendly behaviour.

##### Steps to reproduce

* Install the french BÉPO layout, and set it as the default system keyboard layout
* Launch Minetest
* Try to use, for exemple the é key (key for a**Z**erty or q**W**erty) as a keybinding
* See that it displays a blank instead of the correct letter
* Try to use this keybinding to play 
* See that it doesn’t work

**Comment by Desour** [comment] 2022-12-11 16:05
> * The natural key for me for the forward action in the game would be the accented letter `é`, as it is placed on the `w` key for a Qwerty keyboard, or the `z` for an Azerty one. Yet at the moment, Minetest does not seem to handle accented letters in its possible key-binding settings.

Yeah, we should use scancodes for the wasd thing, and generally make it possible to bind to scankeys.


------------


What are you using to configure your keyboard layout?

-------

You could try compiling with SDL (uncomment [this line](https://github.com/minetest/irrlicht/blob/1cf0f3bef04e53c08004cc1106f48fcecca7ff88/include/IrrCompileConfig.h#L48)) to see if that fixes your issues.

**Comment by Anglodel** [comment] 2023-01-06 22:26
Hi again, sorry for the late reply.

> What are you using to configure your keyboard layout?

I changed it with the Kde Plasma settings software, I do not know however how it works and what it uses under the hood.

> What are you using to configure your keyboard layout?

I don’t know how to compile a software, sorry 😅 I’ll try to figure it out and get helped, though.

**Comment by sergeykish** [comment] 2023-02-26 13:54
Reproduced on same version, Arch Linux, Wayland, Dvorak

**Minetest version**

```
Minetest 5.6.1 (Linux)
Using Irrlicht 1.9.0mt8
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

**OS / Hardware**

Operating system : Arch Linux x86_64 (BTW™)
Kernel : 6.1.12-arch1-1
Desktop Environment : Sway
CPU : Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz

default keyboard layout is `dvorak`:

```
input type:keyboard {
    xkb_layout dvorak,us
    xkb_options grp:caps_toggle,ctrl:swap_lalt_lctl,grp_led:num
}
```

`minetest` treats input as `dvorak` no matter

* switch layout before and after start with `grp`
* layout configuration change before and after start with `swaymsg input type:keyboard 'xkb_layout "us"'`

What works for me is

```
$ setxkbmap us
```

even though I do not see `minetest` in `xlsclients` output.

**Comment by sergeykish** [comment] 2023-02-26 14:13
@Desour thank you, I've tried your suggestion to uncomment `_IRR_COMPILE_WITH_SDL_DEVICE_`, on current git

```
$ minetest --version
Minetest 5.7.0-dev-2083252c0-dirty (Linux)
Using Irrlicht 1.9.0mt9
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

Controls depend on starting layout. Layout change does not affect controls, affects chat input.

`setxkbmap us` affects controls in game, chat lost layout change (`us` only). Once applied takes precedence over Sway config on subsequent runs.

**Comment by jd-develop** [comment] 2023-09-02 19:04
I have the exact same problem, I wonder when it will be fixed

**Comment by rubenwardy** [comment] 2024-08-09 15:04
closing in favor of #14940

**Closed by rubenwardy** 2024-08-09 15:05 UTC
Labels: Bug, Linux, @ Client / Controls / Input
