### ISSUE TITLE
Hiding command prompt?

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4210] opened 2016-06-10 22:34 UTC
Why do you see the command prompt it's really annoying me (it's probably confusing for beginners who just played Minetest for the first time)

**Comment by rubenwardy** [comment] 2016-06-10 23:26
If you're on Windows, it requires recompiling

**Comment by tobyplowy** [comment] 2016-06-10 23:37
@rubenwardy I have no idea what that means and I have no idea how to do it ( I think it has something to do with changing the source code into a running program but I'm not sure) in that case isn't it the work of the People who actually make the package and put it on the minetest website? ( I don't know anything about coding i'm just here to report issues)

**Comment by est31** [comment] 2016-06-11 12:14
IDK, is it a problem on Mac as well? I don't see any problems on linux.

**Comment by Fixer-007** [comment] 2016-06-11 12:15
@est31 what cmake parameter do I need to hide it?

**Comment by est31** [comment] 2016-06-11 12:21
No idea.

**Comment by tobyplowy** [comment] 2016-06-11 12:22
@est31 I do I don't know about mac I use Windows :\

**Comment by rubenwardy** [comment] 2016-06-11 13:08
Looks like it's possible to close it at runtime:

```cpp
#include <Windows.h>

int main()
{
    FreeConsole();
    //other stuff
}
```

**Comment by kahrl** [comment] 2016-06-15 21:27
@rubenwardy FreeConsole is probably not the right way to do it. It would mean that if someone starts minetest from a console, that console would get closed.

The correct way would be to change the PE subsystem from IMAGE_SUBSYSTEM_WINDOWS_CUI (3) to IMAGE_SUBSYSTEM_WINDOWS_GUI (2). This could even be done with a hex editor on the compiled .exe (in the official minetest-0.4.14 build, change the byte at offset 0xdc of minetest.exe from 3 to 2). Or when building with MinGW, passing -mwindows should do it. MSVC on the other hand requires some type of WinMain in the source code in addition to whatever option it takes, if I remember correctly.

One bad side effect of changing the subsystem would be that minetest could no longer show error messages when (for example) started with bad arguments, and in general couldn't show log messages directly, even if the user started it from a console. GUI applications never get stdout/stderr in Windows.

**Comment by Fixer-007** [comment] 2016-06-16 11:16
I swore I can remember minetest 0.4.13 was opening console only first time, but further starts it was hidden. Now it opens every time.

**Comment by tobyplowy** [comment] 2016-06-16 12:25
@Fixer-007 no on 0.4.13 the console did not close either. At least for it didn't :D

**Comment by sofar** [comment] 2016-06-17 18:41
`hide_console` on windows as a setting?

**Comment by kahrl** [comment] 2016-06-20 20:54
I just found this blog post: [How do I write a program that can be run either as a console or a GUI application?](https://blogs.msdn.microsoft.com/oldnewthing/20090101-00/?p=19643/)

The devenv.com trick (discussed [here](https://blogs.msdn.microsoft.com/junfeng/2004/02/06/how-to-make-an-application-as-both-gui-and-console-application/) and in the comments of the article above) sounds like it could work.

**Comment by Fixer-007** [comment] 2016-11-08 13:50
I think in windows command prompt should be hidden by default, it is also annoying and clatters taskbar, 99% of users don't need it. Just add option in config to show/hide that window, so you can enable it in case its needed.

I'm asking devs to consider this issue.

**Comment by tobyplowy** [comment] 2016-11-08 15:05
@Fixer-007 also you vorgot to mention that really Looks unpolished 

Another problem with it is if you minimalize it and also minimalize minetest and open minetest in full screen again it will pop up the command prompt again so you have to close it again.

**Comment by rubenwardy** [comment] 2016-11-15 02:06
As Lua errors are shown in a dialog, the console isn't needed as much. So disabling it wouldn't be a bad idea

**Comment by adrido** [comment] 2017-03-19 11:17
https://github.com/minetest/minetest/pull/5416

**Comment by SmallJoker** [comment] 2017-03-19 11:38
Duplicate of #2128. (which apparently will be closed soon enough too, because ^ )

**Closed by SmallJoker** 2017-03-19 11:38 UTC
Labels: @ Client / Audiovisuals, Request / Suggestion, Windows
