### ISSUE TITLE
Water is invisible below clouds

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8379] opened 2019-03-15 00:04 UTC
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0
```
This is not a regression, it existed before.

##### Summary
If water is behind the clouds, it is invisible.

https://satoshiupload.com/images/vcwjZTq6mB.jpg

Sorry, paramat, but the GitHub upload feature is broken without executing proprietary code.

##### Steps to reproduce
1. Fly high in the sky.
2. Look down so the water is below the clouds.

EXPECTED:
Water renders normal.

ACTUAL:
Water is invisible.

##### Related stuff
It seems likely this is related to the other depth sorting bugs like #95.

**Comment by paramat** [comment] 2019-03-15 00:32
Ah i forgot that some people can't drop images into posts, ok no problem will add it myself.

This is indeed a duplicate of #95

**Closed by paramat** 2019-03-15 00:32 UTC
Labels: @ Client / Audiovisuals, Bug, Duplicate
