### ISSUE TITLE
No indication if MT still downloads media or if it hangs

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#1665] opened 2014-09-20 01:32 UTC
We had several posts in the forum about MT "hanging" or "doesn't" working if the client connects with a server. This misconception comes from the progress bar that is shown when the client downloads all media files from the server.

Some server need to send huge amounts of data before the player joins. 50MB+ 
Depending on the connection this can take a long time (especially with slower internet connections) and while the client loads the progress bar usually shows 50% most of the time.

There should be better feedback for the user, so he/she sees that the download progresses and is in fact still going.

E.g. a small line that shows the file / object that is downloaded.

**Comment by est31** [comment] 2015-03-01 17:25
Note that this missing indication also applies for the OS. Android in fact kills the app automatically, when it hangs too much, and you try to interact with the app, but it doesn't react.

**Comment by paramat** [comment] 2017-09-10 02:39
0db73bd83effa7dbc0f28862c8157e0283d24e44 merged which may have helped.
Is this still an issue? Closing in 1 month if not.

**Comment by est31** [comment] 2017-09-10 03:31
@paramat that commit doesn't fix the bug. MT still hangs after that commit.

**Comment by HybridDog** [comment] 2017-09-10 17:53
This remembers me to plymouth. You can disable the image shown when booting ubuntu, then you see what's loaded.
In minetest you could add a setting to show lots of text (the info log) instead of clouds when loading.

**Comment by paramat** [comment] 2020-07-21 21:47
Re-open to include duplicate #10214

**Comment by BruceMustache** [comment] 2020-08-10 01:29
Also would be nice if loading screen show what it is loading
Or show a option "more details" that shows the log of loading

**Comment by rubenwardy** [comment] 2021-01-31 16:40
Can't reproduce

**Closed by rubenwardy** 2021-01-31 16:40 UTC
Labels: @ Client / Audiovisuals, Request / Suggestion
