### ISSUE TITLE
Mouse clicks are offset in non-full-screen mode

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#9155] opened 2019-11-30 12:37 UTC
##### Minetest version

https://github.com/minetest/minetest/commit/4b6bff46e14c6215828da5ca9ad2cb79aa517a6e

##### OS / Hardware

Operating system: macOS 10.15.1
model: MacBook8,1
##### Summary
Mouse clicks are offset in non-full-screen mode

##### Steps to reproduce
* build minetest using travis ci
```
language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      script:
        - ./build.sh
        - ./deploy.sh
```
build.sh:
```bash
#!/bin/sh
brew update
brew install freetype gettext irrlicht libogg libvorbis luajit
git clone --depth=1 https://github.com/minetest/minetest.git ./minetest
git clone --depth=1 https://github.com/minetest/minetest_game.git ./minetest/games/minetest_game
rm -fr ./minetest/games/minetest_game/.git
cd ./minetest
cmake . \
    -DVERSION_EXTRA="dev-$(sw_vers -productVersion)" \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_FREETYPE=TRUE \
    -DENABLE_LEVELDB=FALSE \
    -DENABLE_GETTEXT=TRUE \
    -DENABLE_REDIS=FALSE \
    -DBUILD_CLIENT=TRUE \
    -DBUILD_SERVER=FALSE \
    -DCUSTOM_GETTEXT_PATH=/usr/local/opt/gettext \
    -DCMAKE_EXE_LINKER_FLAGS="-L/usr/local/lib"
make -j2 package
cd ..
```
This bug sometimes disappears irreproducibly

**Comment by DougStoker** [comment] 2019-12-04 22:35
this bug always happens for me
macos 10.14.5
happens for any build of minetest

**Comment by rubenwardy** [comment] 2021-01-28 18:15
Duplicate of #10856, which is newer but has more detail

**Closed by rubenwardy** 2021-01-28 18:15 UTC
Labels: @ Client / Controls / Input, Bug, Mac OS
