### ISSUE TITLE
Mods menu in the main menu and official modes for convenient game

### ISSUE THREAD

**Issue by alexeysvrv** [minetest/minetest#4707] opened 2016-10-30 17:31 UTC
Guys, I suggest you to the concept of an additional menu in the main menu. It will be available for all modes of the game, and the installation will be done literally in two clicks. I also propose to make the so-called formal fashion, which is not required in a standard game, but much easier life in the simulator. Let this fashion automation or magic. This for example. And conclusions offered by the official fashion when you first start to install on the user's request

**Comment by rubenwardy** [comment] 2016-10-30 20:12
This is hard to understand.
Are you asking for a mod store?
What do you mean by formal fashion?

The mod store part of this is a duplicate of #4666  
And the problem is trying to be solved by #3289 and #4082

**Comment by alexeysvrv** [comment] 2016-10-31 04:44
I mean maintest create a modular game. The idea is this. There is a basic minimum core MTGame games, and additional function are essential to be connected via mods. Fashion propose to divide the official and user. The first time, I propose to display the Offer install some mods recommended for a comfortable game. Then, they can be set from the menu mode.
This menu mods I propose to be processed into a store where you can download, view, and delete mode. Now, you can only enable or disable them.

**Comment by kahrl** [comment] 2016-11-04 19:35
We don't usually encourage this because issues should be in English, but maybe you could explain your request again in your native language (Russian?). Then I hope that other Russian users would help out and translate the gist of it back to English.

Right now unfortunately no one seems to understand this issue. I guess "fashion" = "мо́да" -> (transliterated) "móda" -> "mods"? So "formal fashion" -> "official mods"? A mod store allowing easy installation of certain official mods? Is that correct?

If a mod store is added again, I wouldn't want it to be restricted to a small list of selected official mods; it should contain pretty much all the mods that users or server owners might typically want to install. Having only few mods was one of the problems of the old mod store, and one of the reasons it was abandoned (since it led to many users having to install mods without the help of the mod store anyway).

**Comment by alexeysvrv** [comment] 2016-11-04 20:02
@kahrl Я имею ввиду сделать магазин модов, где будут доступны все пользовательские и официальные моды(от команды Майнтест). При первом запуске игры, будут предлагаться к установке самые важные моды(допустим автоматизации и транспорта). Таким образом, мы будем иметь необходимое минимальное ядро игры(MTGame), которое будет дополняться в зависимости от предпочтений игроков. Это решит проблемы с разным лицензированием модов и легко будет устанавливаться, управлять.

I mean to make the store the mods, which will be available for all custom and official mods(from the team Maintest). When you first start the game, will be offered to install the most important mods(for example automation and transport). Thus, we will have the necessary minimum core of the game(MTGame), which will be supplemented depending on the preferences of the players. This will solve problems with different licensing mods and easy to install, manage.

**Comment by Brandedahall** [comment] 2016-11-09 08:56
He's asking for a steam workshop-like menu in Minetest, as well as asking the user if they would like to download the most popular mod at the time of starting up the game.

**Closed** 2016-11-09 13:51 UTC
Labels: Duplicate, Feature request
