### ISSUE TITLE
Allow mods to change held item textures while rightclick is held

### ISSUE THREAD

**Issue by JosephTheTank13** [minetest/minetest#8561] opened 2019-05-26 00:07 UTC
##### Issue type
 - Feature request

##### Minetest version
```
5.0.x
```
As of now if you have a bow and arrow mod, if that mod has any sort of charging up animation it looks really bad. The mod replaces the item in your hand many times during the charging so it results in the bow dropping out off screen and coming back over and over. We need some kind of api to make it so when you are holding down the right click or place button it will not replace the item, but the texture only. This would make for a much pleasanter animation. Also, as a side note: Will we be getting custom animations for on_use like for food eating animations? Like where we can create the anims our selves?
Thanks to all the devs who work on this game btw. Y’all do a great job!

**Comment by DS-Minetest** [comment] 2019-05-26 07:52
Related: #5212, #2811

**Comment by SmallJoker** [comment] 2019-05-26 08:19
Duplicate of #2811. The animation is the same for both mouse buttons.

**Closed by SmallJoker** 2019-05-26 08:19 UTC
