### ISSUE TITLE
Issues with fog.

### ISSUE THREAD

**Issue by kaeza** [minetest/minetest#1193] opened 2014-04-02 09:32 UTC
Posting this here to avoid being lost in the sands of time:

It looks like sometimes the fog gets stuck in a specific place and fails to move along with the camera.

Examples:
"Inside" the fog: https://dl.dropboxusercontent.com/u/100008207/screenshot_473120735.jpg
"Outside" the fog: https://dl.dropboxusercontent.com/u/100008207/screenshot_473401192.jpg

This started happening fairly recently. I can play the game just fine provided fog is disabled (with F3).

Currently running latest dev version, on Ubuntu 12.04. Graphics card:
```
$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 4 Series Chipset Integrated Graphics Controller (rev 03)
```

**Comment by nerzhul** [comment] 2015-03-25 13:18
This issue is old and hasn't been reported since this reporting.

can we have some updates ? @ThomasAH @kaeza ?

I'll close it on 1st april if no answer

**Comment by ThomasAH** [comment] 2015-03-25 16:17
Still the same problem with 0.4.11-217-ged04e8e (nearly 0.4.12), my workaround is "enable_fog = false" in minetest.conf

**Comment by kaeza** [comment] 2015-12-20 21:10
Haven't had this issue in a while since moving to Windows. Probably a combination of bugs in drivers and shaders?

@ThomasAH is this still a problem?

**Comment by paramat** [comment] 2016-03-27 14:33
@ThomasAH still a problem? will close in 1 month if no response.

**Comment by ThomasAH** [comment] 2016-03-28 06:23
I'll check again on the same hardware.

**Comment by ThomasAH** [comment] 2016-04-07 08:16
I tried again with the same build (0.4.11-217-ged04e8e), the same minetest.conf (just with fog enabled again) on the same hardware and the problem is solved. The only change is that I upgraded the system from Debian wheezy to Debian jessie, the newer X server seems to help.

Please close this issue.

**Comment by paramat** [comment] 2016-04-08 02:04
Thanks for testing.

**Closed by paramat** 2016-04-08 02:04 UTC
Labels: @ Client / Audiovisuals, Possible close, Unconfirmed bug
