### ISSUE TITLE
Add wayland support

### ISSUE THREAD

**Issue by Zuzuk-null** [minetest/minetest#11893] opened 2021-12-27 16:45 UTC
^^^^^^^^^^^^^^^^^^^^^

**Comment by rollerozxa** [comment] 2021-12-27 16:50
Duplicate of #9686, but SDL2 support in IrrlichtMt with
https://github.com/minetest/irrlicht/pull/85 might make this closer to a
reality than ever.

måndag 27 december 2021 skrev Daniel ***@***.***>:
> ^^^^^^^^^^^^^^^^^^^^^
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you are subscribed to this thread.<
https://ci3.googleusercontent.com/proxy/YEboACEMt8fd99xasLH4UhNbeazjmV8rVORTc5eTz9s36ytDjJ5XuYFCy3wesubYw3RdAtQe7-zshyXKEAKVjxqXjZYQGXCuWtXo09pPTqR-5USSW0Kl6CYWUQCExRR6SIh3huVnjEFOE7OG2sN2qqB76obesC_o2JefP3uWASU9zmPuZ8645n-9rbOryLyin4eP65OVPPW8Bwr63T2b1vGcwHg=s0-d-e1-ft#https://github.com/notifications/beacon/AOQJU74D2NGKYEKE6C7OPL3UTCJ3DA5CNFSM5K2UGXF2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4QHOHZVQ.gif>Message
ID: ***@***.***>

**Closed** 2021-12-27 18:21 UTC
Labels: Duplicate, Feature request
