### ISSUE TITLE
Digging Speed Modifiers

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#13068] opened 2022-12-24 08:17 UTC
## Problem

It doesn't seem possible to add conditions which slow down your digging speed.

## Solutions

Make it possible to define conditions that could slow down your digging speed.

## Additional context

For example, in Minecraft, you've got two conditions that could slow down your digging speed by 5x. Those being when you're not on the ground, and the second one being when you're underwater. If you meet both conditions at once, your digging speed slows down by 25x.

**Comment by oong819** [comment] 2022-12-24 12:41
Cracky group may help?

**Comment by fluxionary** [comment] 2022-12-25 19:30
it's certainly possible to override the capabilities of the player's hand and wielded tool on the fly, though that effect is subject to network latency. i admit, i'd rather have a simple way to give a player a general bonus/penalty to dig speed.

**Comment by fluxionary** [comment] 2022-12-25 20:03
> without very ugly hacks.

i thought i'd mention that such a thing is technically possible, but my suggestion is definitely quite hacky, and probably would result in weird issues (tools would end up w/ random metadata). i'd prefer a more direct method like what you're proposing. 

> ability to adjust the digging speed is available for every sub-game

my suggestion could work w/ arbitrary games. however, someone would still need to write the mod code. 

> Network latency is only a problem in multiplayer, right?

to be precise, in my suggestion, the "reaction time" would be a factor of both network latency and server lag. even in a single player world, if you've got a lot of machines or mobs creating lag, it'd take a moment for the player's hand/tool to have its capabilities updated.

**Comment by pandaro** [comment] 2022-12-26 00:01
Im using stack:set_tool_capabilities()

**Comment by Zughy** [comment] 2022-12-27 10:13
As @pandaro said, you can modify the hand or tools digging abilities with meta (`set_tool_capabilities`). Closing

**Closed by Zughy** 2022-12-27 10:13 UTC
Labels: Feature request

**Comment by fluxionary** [comment] 2022-12-28 21:13
i guess this is actually a dupe of #11120
