### ISSUE TITLE
Add a register_on_punch_entity()

### ISSUE THREAD

**Issue by Bebibio** [minetest/minetest#14752] opened 2024-06-13 17:37 UTC
### Problem

Currently there is no possibility to track when an entity is dead in a mod (which doesn't add this entity).
There is already a function for player but not for entity. 
Exemple: I want to know when an entity from an other mod is killed. But I can't!

### Solutions

I'm don't really know how to add this in minetest's files but it will be a function that allows you to know when an entity is punch: minetest.register_on_punch_entity

### Alternatives

No idea

**Comment by appgurueu** [comment] 2024-06-13 19:39
> Exemple: I want to know when an entity from an other mod is killed. But I can't!

You can. It's not the prettiest, but simply depending on said mod and "hooking" their entity definition to override the `on_death` callback works:

```lua
local def = minetest.registered_entities["their_mod:their_entity"]
local old_on_death = def.on_death
function def:on_death(killer, ...)
    -- do something
    return old_on_death(self, killer, ...)
end
```

This reduces this feature request to a lower priority matter of convenience.

**Comment by rubenwardy** [comment] 2024-06-13 21:25
Duplicate of #14577 (which was closed by the author)

**Closed** 2024-06-14 17:13 UTC
Labels: Feature request, Low priority
