### ISSUE TITLE
No simple way to get rid of unknown items

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5288] opened 2017-02-20 23:21 UTC
If you got an unknown item at some point (maybe because you unloaded a mod, or because of a mod error) and it is in your inventory, it is pretty annoying to get it of it.

If you attempt to throw it away, it just displays an error message, but you keep the item.
Apparently the only way to get rid of unknown items now is to use `/pulverize`.

Tested in 0.4.15. I think there should be a more intuitive way to get rid of these items.

I remember, in previous versions, unknown items were destroyed when you attempted to throw them away.

**Comment by tenplus1** [comment] 2017-02-21 08:45
Having the trashcan slot available in creative AND normal games would be an advantage for this sort of problem...  My fork of inventory plus does just that.

**Comment by Wuzzy2** [comment] 2017-02-21 12:08
There should be a reliable way to get rid of those unknown items, no matter the mod or subgames you have.
For unknown nodes placed in the world, you just dig them for 0.5 seconds and they're gone, so there is really no reason why threre is nothing similar for unknown items.

**Comment by red-001** [comment] 2017-02-21 12:12
See the discussion in #3657 and this is a duplicate of #3389.

**Closed** 2017-02-21 12:15 UTC
