### ISSUE TITLE
curl linking problem undefined reference to `idna_strerror'

### ISSUE THREAD

**Issue by mckaygerhard** [minetest/minetest#8483] opened 2019-04-22 03:01 UTC
##### Issue type
 - Build issue
 
##### Minetest version
```
0.4.17.1
also
5.0.1
```

##### OS / Hardware
Operating system: Linux
CPU: i7

##### Summary
curl linking problem undefined reference to `idna_strerror' when build separate minetsst versions

```
Linking CXX executable ../../bin/minetest
cd /home/general/Descargas/minetest/minetest-0.4.17.1+repack/obj-i486-linux-gnu/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/minetest.dir/link.txt --verbose=1
/usr/bin/c++   -DNDEBUG -Wall   -Wall -pipe -funroll-loops -O3 -ffast-math -fomit-frame-pointer    CMakeFiles/minetest.dir/client/clientlauncher.cpp.o CMakeFiles/minetest.dir/client/inputhandler.cpp.o CMakeFiles/minetest.dir/client/joystick_controller.cpp.o CMakeFiles/minetest.dir/client/tile.cpp.o CMakeFiles/minetest.dir/irrlicht_changes/static_text.cpp.o CMakeFiles/minetest.dir/network/clientopcodes.cpp.o CMakeFiles/minetest.dir/network/clientpackethandler.cpp.o CMakeFiles/minetest.dir/network/connection.cpp.o CMakeFiles/minetest.dir/network/networkpacket.cpp.o CMakeFiles/minetest.dir/network/serveropcodes.cpp.o CMakeFiles/minetest.dir/network/serverpackethandler.cpp.o CMakeFiles/minetest.dir/script/common/c_content.cpp.o CMakeFiles/minetest.dir/script/common/c_converter.cpp.o CMakeFiles/minetest.dir/script/common/c_internal.cpp.o CMakeFiles/minetest.dir/script/common/c_types.cpp.o CMakeFiles/minetest.dir/script/cpp_api/s_async.cpp.o CMakeFiles/minetest.dir/script/cpp_api/s_base.cpp.o CMakeFiles/minetest.dir/script/cpp_api/s_client.cpp.o CMakeFiles/minetest.dir/script/cpp_api/s_entity.cpp.o CMakeFiles/minetest.dir/script/cpp_api/s_env.cpp.o CMakeFiles/minetest.dir/script/cpp_api/s_inventory.cpp.o CMakeFiles/minetest.dir/script/cpp_api/s_item.cpp.o CMakeFiles/minetest.dir/script/cpp_api/s_mainmenu.cpp.o CMakeFiles/minetest.dir/script/cpp_api/s_node.cpp.o CMakeFiles/minetest.dir/script/cpp_api/s_nodemeta.cpp.o CMakeFiles/minetest.dir/script/cpp_api/s_player.cpp.o CMakeFiles/minetest.dir/script/cpp_api/s_security.cpp.o CMakeFiles/minetest.dir/script/cpp_api/s_server.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_areastore.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_base.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_camera.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_client.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_craft.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_env.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_http.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_inventory.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_item.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_itemstackmeta.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_localplayer.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_mainmenu.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_mapgen.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_metadata.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_minimap.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_nodemeta.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_nodetimer.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_noise.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_object.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_particles.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_rollback.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_server.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_settings.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_sound.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_storage.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_util.cpp.o CMakeFiles/minetest.dir/script/lua_api/l_vmanip.cpp.o CMakeFiles/minetest.dir/script/scripting_client.cpp.o CMakeFiles/minetest.dir/script/scripting_mainmenu.cpp.o CMakeFiles/minetest.dir/script/scripting_server.cpp.o CMakeFiles/minetest.dir/threading/event.cpp.o CMakeFiles/minetest.dir/threading/mutex.cpp.o CMakeFiles/minetest.dir/threading/semaphore.cpp.o CMakeFiles/minetest.dir/threading/thread.cpp.o CMakeFiles/minetest.dir/unittest/test.cpp.o CMakeFiles/minetest.dir/unittest/test_areastore.cpp.o CMakeFiles/minetest.dir/unittest/test_collision.cpp.o CMakeFiles/minetest.dir/unittest/test_compression.cpp.o CMakeFiles/minetest.dir/unittest/test_connection.cpp.o CMakeFiles/minetest.dir/unittest/test_filepath.cpp.o CMakeFiles/minetest.dir/unittest/test_inventory.cpp.o CMakeFiles/minetest.dir/unittest/test_keycode.cpp.o CMakeFiles/minetest.dir/unittest/test_map_settings_manager.cpp.o CMakeFiles/minetest.dir/unittest/test_mapnode.cpp.o CMakeFiles/minetest.dir/unittest/test_nodedef.cpp.o CMakeFiles/minetest.dir/unittest/test_noderesolver.cpp.o CMakeFiles/minetest.dir/unittest/test_noise.cpp.o CMakeFiles/minetest.dir/unittest/test_objdef.cpp.o CMakeFiles/minetest.dir/unittest/test_player.cpp.o CMakeFiles/minetest.dir/unittest/test_profiler.cpp.o CMakeFiles/minetest.dir/unittest/test_random.cpp.o CMakeFiles/minetest.dir/unittest/test_schematic.cpp.o CMakeFiles/minetest.dir/unittest/test_serialization.cpp.o CMakeFiles/minetest.dir/unittest/test_settings.cpp.o CMakeFiles/minetest.dir/unittest/test_socket.cpp.o CMakeFiles/minetest.dir/unittest/test_threading.cpp.o CMakeFiles/minetest.dir/unittest/test_utilities.cpp.o CMakeFiles/minetest.dir/unittest/test_voxelalgorithms.cpp.o CMakeFiles/minetest.dir/unittest/test_voxelmanipulator.cpp.o CMakeFiles/minetest.dir/util/areastore.cpp.o CMakeFiles/minetest.dir/util/auth.cpp.o CMakeFiles/minetest.dir/util/base64.cpp.o CMakeFiles/minetest.dir/util/directiontables.cpp.o CMakeFiles/minetest.dir/util/enriched_string.cpp.o CMakeFiles/minetest.dir/util/numeric.cpp.o CMakeFiles/minetest.dir/util/pointedthing.cpp.o CMakeFiles/minetest.dir/util/serialize.cpp.o CMakeFiles/minetest.dir/util/sha1.cpp.o CMakeFiles/minetest.dir/util/sha256.c.o CMakeFiles/minetest.dir/util/srp.cpp.o CMakeFiles/minetest.dir/util/string.cpp.o CMakeFiles/minetest.dir/util/timetaker.cpp.o CMakeFiles/minetest.dir/ban.cpp.o CMakeFiles/minetest.dir/camera.cpp.o CMakeFiles/minetest.dir/cavegen.cpp.o CMakeFiles/minetest.dir/chat.cpp.o CMakeFiles/minetest.dir/client.cpp.o CMakeFiles/minetest.dir/clientenvironment.cpp.o CMakeFiles/minetest.dir/clientiface.cpp.o CMakeFiles/minetest.dir/clientmap.cpp.o CMakeFiles/minetest.dir/clientmedia.cpp.o CMakeFiles/minetest.dir/clientobject.cpp.o CMakeFiles/minetest.dir/clouds.cpp.o CMakeFiles/minetest.dir/collision.cpp.o CMakeFiles/minetest.dir/content_abm.cpp.o CMakeFiles/minetest.dir/content_cao.cpp.o CMakeFiles/minetest.dir/content_cso.cpp.o CMakeFiles/minetest.dir/content_mapblock.cpp.o CMakeFiles/minetest.dir/content_mapnode.cpp.o CMakeFiles/minetest.dir/content_nodemeta.cpp.o CMakeFiles/minetest.dir/content_sao.cpp.o CMakeFiles/minetest.dir/convert_json.cpp.o CMakeFiles/minetest.dir/craftdef.cpp.o CMakeFiles/minetest.dir/database-dummy.cpp.o CMakeFiles/minetest.dir/database-files.cpp.o CMakeFiles/minetest.dir/database-leveldb.cpp.o CMakeFiles/minetest.dir/database-postgresql.cpp.o CMakeFiles/minetest.dir/database-redis.cpp.o CMakeFiles/minetest.dir/database-sqlite3.cpp.o CMakeFiles/minetest.dir/database.cpp.o CMakeFiles/minetest.dir/debug.cpp.o CMakeFiles/minetest.dir/defaultsettings.cpp.o CMakeFiles/minetest.dir/drawscene.cpp.o CMakeFiles/minetest.dir/dungeongen.cpp.o CMakeFiles/minetest.dir/emerge.cpp.o CMakeFiles/minetest.dir/environment.cpp.o CMakeFiles/minetest.dir/face_position_cache.cpp.o CMakeFiles/minetest.dir/filecache.cpp.o CMakeFiles/minetest.dir/filesys.cpp.o CMakeFiles/minetest.dir/fontengine.cpp.o CMakeFiles/minetest.dir/game.cpp.o CMakeFiles/minetest.dir/genericobject.cpp.o CMakeFiles/minetest.dir/gettext.cpp.o CMakeFiles/minetest.dir/guiChatConsole.cpp.o CMakeFiles/minetest.dir/guiEngine.cpp.o CMakeFiles/minetest.dir/guiFileSelectMenu.cpp.o CMakeFiles/minetest.dir/guiFormSpecMenu.cpp.o CMakeFiles/minetest.dir/guiKeyChangeMenu.cpp.o CMakeFiles/minetest.dir/guiPasswordChange.cpp.o CMakeFiles/minetest.dir/guiTable.cpp.o CMakeFiles/minetest.dir/guiVolumeChange.cpp.o CMakeFiles/minetest.dir/guiscalingfilter.cpp.o CMakeFiles/minetest.dir/httpfetch.cpp.o CMakeFiles/minetest.dir/hud.cpp.o CMakeFiles/minetest.dir/imagefilters.cpp.o CMakeFiles/minetest.dir/intlGUIEditBox.cpp.o CMakeFiles/minetest.dir/inventory.cpp.o CMakeFiles/minetest.dir/inventorymanager.cpp.o CMakeFiles/minetest.dir/itemdef.cpp.o CMakeFiles/minetest.dir/itemstackmetadata.cpp.o CMakeFiles/minetest.dir/keycode.cpp.o CMakeFiles/minetest.dir/light.cpp.o CMakeFiles/minetest.dir/localplayer.cpp.o CMakeFiles/minetest.dir/log.cpp.o CMakeFiles/minetest.dir/main.cpp.o CMakeFiles/minetest.dir/map.cpp.o CMakeFiles/minetest.dir/map_settings_manager.cpp.o CMakeFiles/minetest.dir/mapblock.cpp.o CMakeFiles/minetest.dir/mapblock_mesh.cpp.o CMakeFiles/minetest.dir/mapgen.cpp.o CMakeFiles/minetest.dir/mapgen_flat.cpp.o CMakeFiles/minetest.dir/mapgen_fractal.cpp.o CMakeFiles/minetest.dir/mapgen_singlenode.cpp.o CMakeFiles/minetest.dir/mapgen_v5.cpp.o CMakeFiles/minetest.dir/mapgen_v6.cpp.o CMakeFiles/minetest.dir/mapgen_v7.cpp.o CMakeFiles/minetest.dir/mapgen_valleys.cpp.o CMakeFiles/minetest.dir/mapnode.cpp.o CMakeFiles/minetest.dir/mapsector.cpp.o CMakeFiles/minetest.dir/mesh.cpp.o CMakeFiles/minetest.dir/mesh_generator_thread.cpp.o CMakeFiles/minetest.dir/metadata.cpp.o CMakeFiles/minetest.dir/mg_biome.cpp.o CMakeFiles/minetest.dir/mg_decoration.cpp.o CMakeFiles/minetest.dir/mg_ore.cpp.o CMakeFiles/minetest.dir/mg_schematic.cpp.o CMakeFiles/minetest.dir/minimap.cpp.o CMakeFiles/minetest.dir/mods.cpp.o CMakeFiles/minetest.dir/nameidmapping.cpp.o CMakeFiles/minetest.dir/nodedef.cpp.o CMakeFiles/minetest.dir/nodemetadata.cpp.o CMakeFiles/minetest.dir/nodetimer.cpp.o CMakeFiles/minetest.dir/noise.cpp.o CMakeFiles/minetest.dir/objdef.cpp.o CMakeFiles/minetest.dir/object_properties.cpp.o CMakeFiles/minetest.dir/particles.cpp.o CMakeFiles/minetest.dir/pathfinder.cpp.o CMakeFiles/minetest.dir/player.cpp.o CMakeFiles/minetest.dir/porting.cpp.o CMakeFiles/minetest.dir/profiler.cpp.o CMakeFiles/minetest.dir/quicktune.cpp.o CMakeFiles/minetest.dir/raycast.cpp.o CMakeFiles/minetest.dir/reflowscan.cpp.o CMakeFiles/minetest.dir/remoteplayer.cpp.o CMakeFiles/minetest.dir/rollback.cpp.o CMakeFiles/minetest.dir/rollback_interface.cpp.o CMakeFiles/minetest.dir/serialization.cpp.o CMakeFiles/minetest.dir/server.cpp.o CMakeFiles/minetest.dir/serverenvironment.cpp.o CMakeFiles/minetest.dir/serverlist.cpp.o CMakeFiles/minetest.dir/serverobject.cpp.o CMakeFiles/minetest.dir/settings.cpp.o CMakeFiles/minetest.dir/shader.cpp.o CMakeFiles/minetest.dir/sky.cpp.o CMakeFiles/minetest.dir/socket.cpp.o CMakeFiles/minetest.dir/sound.cpp.o CMakeFiles/minetest.dir/sound_openal.cpp.o CMakeFiles/minetest.dir/staticobject.cpp.o CMakeFiles/minetest.dir/subgame.cpp.o CMakeFiles/minetest.dir/terminal_chat_console.cpp.o CMakeFiles/minetest.dir/tileanimation.cpp.o CMakeFiles/minetest.dir/tool.cpp.o CMakeFiles/minetest.dir/treegen.cpp.o CMakeFiles/minetest.dir/version.cpp.o CMakeFiles/minetest.dir/voxel.cpp.o CMakeFiles/minetest.dir/voxelalgorithms.cpp.o CMakeFiles/minetest.dir/wieldmesh.cpp.o  -o ../../bin/minetest -rdynamic -lz -lIrrlicht -lGLU -lGL -lSM -lICE -lX11 -lXext -ljpeg -lbz2 -lpng -lz -lSM -lICE -lX11 -lXext -lopenal -lvorbisfile -lvorbis -logg -lsqlite3 -lluajit-5.1 -lgmp -ljsoncpp -lrt -lpthread -ldl -lXxf86vm -Wl,-Bstatic -lcurl -Wl,-Bdynamic -lfreetype cguittfont/libcguittfont.a -lcurses -lform -lpq -lleveldb -ljpeg -lbz2 -lpng -lopenal -lvorbisfile -lvorbis -logg -lsqlite3 -lluajit-5.1 -lgmp -ljsoncpp -lrt -lpthread -ldl -lXxf86vm -Wl,-Bstatic -lcurl -Wl,-Bdynamic -lcurses -lform -lpq -lleveldb -lIrrlicht -lz -lfreetype 
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-strerror.o): In function `Curl_idn_strerror':
(.text+0x6e): undefined reference to `idna_strerror'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-url.o): In function `fix_hostname':
(.text+0x17de): undefined reference to `stringprep_check_version'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-url.o): In function `fix_hostname':
(.text+0x1803): undefined reference to `idna_to_ascii_lz'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-url.o): In function `fix_hostname':
(.text+0x180b): undefined reference to `stringprep_locale_charset'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-url.o): In function `fix_hostname':
(.text+0x1847): undefined reference to `idna_to_unicode_lzlz'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-url.o): In function `fix_hostname':
(.text+0x18a6): undefined reference to `tld_check_lz'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-url.o): In function `fix_hostname':
(.text+0x18bb): undefined reference to `idn_free'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-url.o): In function `fix_hostname':
(.text+0x18c6): undefined reference to `tld_strerror'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-url.o): In function `Curl_disconnect':
(.text+0x491e): undefined reference to `idn_free'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-url.o): In function `Curl_disconnect':
(.text+0x4930): undefined reference to `idn_free'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_disconnect':
(.text+0x32): undefined reference to `RTMP_Close'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_disconnect':
(.text+0x3a): undefined reference to `RTMP_Free'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_connect':
(.text+0xf3): undefined reference to `RTMP_Connect1'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_send':
(.text+0x16a): undefined reference to `RTMP_Write'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_recv':
(.text+0x1bf): undefined reference to `RTMP_Read'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_do':
(.text+0x23c): undefined reference to `RTMP_ConnectStream'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_setup':
(.text+0x31c): undefined reference to `RTMP_Alloc'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_setup':
(.text+0x32f): undefined reference to `RTMP_Init'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_setup':
(.text+0x33f): undefined reference to `RTMP_SetBufferMS'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_setup':
(.text+0x353): undefined reference to `RTMP_SetupURL'
/usr/lib/gcc/i486-linux-gnu/4.4.5/../../../../lib/libcurl.a(libcurl_la-curl_rtmp.o): In function `rtmp_setup':
(.text+0x374): undefined reference to `RTMP_Free'
collect2: ld returned 1 exit status
```
##### Steps to reproduce
cmake configure
and then 
make
waith and jjust at linkign got the error

**Comment by mckaygerhard** [comment] 2019-04-22 03:06
after some investigations seems the `libcurl.a` must be linking using `target_link_libraries` from cmake.. but i dont know how! seems same problem as #8482 but strange due does not always got this error, only when compiling 5.0.X ..

when i try 0.4.X got only the error of issue #8482

please can provide me directions to solve it?

**Comment by mckaygerhard** [comment] 2019-04-22 03:15
revised and seem i hav proper curl detection:

```
-- Using LuaJIT provided by system.
-- Found CURL: /usr/lib/libcurl.a  
-- cURL support enabled.
-- Found GetText: /usr/include  
```

but not seems cmake use the `curl-config` output linking libs for static.. i got proper version:
```
 curl-config  --static-libs
/usr/lib/libcurl.a -lidn -lrtmp -lgcrypt -lgnutls -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -llber -lldap -lz -lrt
curl --version
curl 7.35.0 (i486-pc-linux-gnu) libcurl/7.35.0 OpenSSL/0.9.8o zlib/1.2.3.4 libidn/1.15 librtmp/2.3
```

**Comment by SmallJoker** [comment] 2019-04-22 09:15
So you're using GCC 4.4.5? Try again after updating it to version 4.9 (or higher), which is also stated as a requirement in the README.

**Comment by mckaygerhard** [comment] 2019-04-22 09:41
hey-- the curl linking proble its due the cmake trange rules.. 

after added proper linkg all problems gone:

```
CMakeLists.txt
@@ -770,6 +770,8 @@ else()
 	if(MINGW)
 		set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -mwindows")
 	endif()
+
+	SET( CMAKE_EXE_LINKER_FLAGS  "${CMAKE_EXE_LINKER_FLAGS} -lidn -lrtmp -lcom_err -llber -lz -lrt" )
 endif()
```

please give a break with micosoft like "update to lasted" responses!!!

**Comment by mckaygerhard** [comment] 2019-04-22 09:51
i do not jhave exact link flags but i suspect with `-lidn` are enought. but real problem its the not right usage of the `curl-config` utility that provides right linker flags 

and please stop to say "update to lasted" i not using windo! gcc doe snot have nothig related here, i'll explain to you @ SmallJoker  :

1. seems some of the libraryes used in mostly distros embebed the linking option and when user need a specific static link does not have it if not used right linker..
2. and about  gcc 4.4 : i compiled with duegive more optimization level with less memory rather thant gcc 7 that consumes too much ram with luajit (do you read the luajit readme for compilation???)
3. gcc 3.X does more level of optimization.. with less ram! but i cannot make compiled yet!

**Comment by mckaygerhard** [comment] 2019-04-22 09:52
i do not jhave exact link flags but i suspect with `-lidn` are enought. but real problem its the not right usage of the `curl-config` utility that provides right linker flags 

and please stop to say "update to lasted" i not using windo! gcc doe snot have nothig related here, i'll explain to you @SmallJoker >

1. seems some of the libraryes used in mostly distros embebed the linking option and when user need a specific static link does not have it if not used right linker..
2. and about  gcc 4.4 : i compiled with duegive more optimization level with less memory rather thant gcc 7 that consumes too much ram with luajit (do you read the luajit readme for compilation???)
3. gcc 3.X does more level of optimization.. with less ram! but i cannot make compiled yet!

**Comment by sfan5** [comment] 2019-04-22 21:56
duplicate of #8482

**Closed by sfan5** 2019-04-22 21:56 UTC
Labels: @ Build, Linux
