### ISSUE TITLE
Support gameplay and navigating the GUI with a keyboard or game controller

### ISSUE THREAD

**Issue by RQWorldblender** [minetest/minetest#10999] opened 2021-02-26 04:15 UTC
## Problem
Anywhere when navigating the GUI, only a mouse can be used to navigate it. Same problem appears during main gameplay; it may be possible to have a session without using a mouse, but it is impossible to rotate the camera or return to the main menu without one, for examples. By navigation, I mean switching tabs or changing button focus, for examples. A keyboard cannot be used in most places, and it looks like game controllers cannot be used natively. By supporting a keyboard or game controller for navigating the GUI, it is possible to complete more actions faster than using a mouse can. It will also open the possibility to play Minetest without a mouse connected, or even with computers set up like game consoles. 

## Solutions
I would like to navigate the GUI and possible be able to play with only a keyboard more easily, with a keyboard or a game controller. This may include changing the formspec code to handle this kind of navigation. At least make it to a point so that I may be able to play a Minetest session without having to use a mouse at all, as if it was being played on a game console. More shortcuts may have to be made in order to fully support keyboard or game controller only gameplay.

## Alternatives
SuperTuxKart switched to using SDL2 for window creation, but still uses its Irrlicht fork for rendering all of its graphics, in order to gain better game controller support (includes hotplugging). It is possible for Minetest to use SDL2 for the same purpose, but it will require rewriting the window management and related code.

## Additional context
Most GUI applications support navigating their interfaces with a keyboard, which is useful for completing actions more quickly.

With game controllers, Minecraft has versions for consoles, and it supports game controllers natively. This is the primary means of playing Minecraft on consoles; while keyboards can be used for input on all of the current-gen consoles, they generally are not supported anywhere else, unless a game supports them.

Retroarch has full support for game controllers, and it even has a core supporting Minecraft, via Craft (a server engine for Minecraft).

**Comment by rubenwardy** [comment] 2021-02-26 06:50
Duplicate of #4153

**Closed by rubenwardy** 2021-02-26 06:50 UTC
Labels: Feature request
