### ISSUE TITLE
PostgreSQL auth backend - password must be changed twice

### ISSUE THREAD

**Issue by redblade7** [minetest/minetest#10209] opened 2020-07-20 17:19 UTC
##### Minetest version

```
5.3.0
```

##### OS / Hardware

Operating system: Slackware Linux -current
CPU: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz

##### Summary
When using the PostgreSQL auth backend, the password must be changed twice in order for the change to have any effect.

##### Steps to reproduce
1. Create an account on a Minetest server using the PostgreSQL auth backend
2. Log in and change the password
3. Log out.
4. Log in using the new password - it does not work
5. Log in using the old password - it works
6. Change the password again
7. Log out
8. Log in using the new password - it works

**Comment by rubenwardy** [comment] 2020-07-20 17:20
Is this a dedicated server, or are you hosting locally?

I can reproduce this with the SQLite Auth backend when shutting down after changing the password, implying that the change isn't persisted on shutdown

**Comment by redblade7** [comment] 2020-07-20 17:22
Dedicated Minetest servers running on a VPS.

**Comment by SmallJoker** [comment] 2020-07-20 19:25
Probably duplicate of #5954

**Comment by Bastrabun** [comment] 2020-07-24 21:56
My server also runs on a VPS, MT version 5.3.0, PostgreSQL version 9.6.17

When changing the password on the first attempt, there's not the usual "Password change successful" text and the log also does not have anything on it. Here's the second attempt ("Issue10209" being the player name):

2020-07-24 23:51:42: ACTION[Server]: Issue10209 changes password

**Comment by SmallJoker** [comment] 2020-07-25 06:38
Password changing works after re-login. Duplicate of #5954.

**Closed by SmallJoker** 2020-07-25 06:38 UTC
Labels: Unconfirmed bug
