### ISSUE TITLE
Faces show as if in wireframe mode if anti-aliasing enabled

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#9072] opened 2019-10-26 02:44 UTC
##### Minetest version
```
Any self-compiled version on Linux from what I can tell
```

##### OS / Hardware

Operating system: Xubuntu 19.10
CPU: AMD Ryzen 7 2700 Eight-Core @ 16x 3.2GHz

GPU model: Radeon RX 570 Series (POLARIS10, DRM 3.33.0, 5.3.0-29-generic, LLVM 9.0.1)
OpenGL version: 4.5 (Compatibility Profile) Mesa 19.2.2

##### Summary
![image](https://user-images.githubusercontent.com/28972859/67613201-a42ee000-f75f-11e9-8ff4-fb0b3b69501c.png)

##### Steps to reproduce
* Join a world and look at a dark spot like the left half of the screenshot. Needs to be underwater.
* Join a world and press [ESC]. Look around for the effect on your screen

**Comment by NathanSalapat** [comment] 2019-10-26 03:06
Can't reproduce on Minetest 5.2.0-dev-8ee16180 [OpenGL 4.6.0] (Linux)
FYI I just compiled a few minutes before leaving this comment. :)

**Comment by clavinet** [comment] 2019-10-30 23:31
@LoneWolfHT I see the same issue when having the inventory open and on the main menu behind transparent elements (clouds are wireframes). I'm on 5.1.0 though.

**Comment by LoneWolfHT** [comment] 2019-12-25 01:35
Looks like this is a driver issue, I'm using Xubuntu 19.10 with a Radeon RX 570

**Comment by LoneWolfHT** [comment] 2020-01-30 02:52
Ok on second thought maybe not. I don't get this with the Minetest client provided by apt

**Comment by LoneWolfHT** [comment] 2020-01-30 02:55
I get this with self-compiled stable-5 and also with self-compiled 0.4.17.1

**Comment by clavinet** [comment] 2020-01-30 14:28
> Ok on second thought maybe not. I don't get this with the Minetest client provided by apt (5.1.1)
@LoneWolfHT is this on the same machine?
I see wireframes on an RX 570 (amdgpu), on a Ryzen 3500U with Vega 8 (also amdgpu driver) but _not_ on a Pentium G4500 with HD Graphics 530 (i915 driver).
All these machines are running openSUSE Tumbleweed with the same distro-provided minetest binary.

**Comment by LoneWolfHT** [comment] 2020-01-30 17:29
Same machine every time

**Comment by HybridDog** [comment] 2020-01-31 17:02
Could you test if it also happens with software rendering?

```bash
LIBGL_ALWAYS_SOFTWARE=1 ./bin/minetest
```

**Comment by LoneWolfHT** [comment] 2020-01-31 17:08
@HybridDog that fixes it

**Comment by SmallJoker** [comment] 2020-01-31 18:35
@LoneWolfHT build once with `-DOPENGL_GL_PREFERENCE=LEGACY` and once with `-DOPENGL_GL_PREFERENCE=GLVND`.
tbh I don't know what this does, but `GLVND` does not work at all on my computer.

**Comment by LoneWolfHT** [comment] 2020-01-31 18:55
@SmallJoker Still have the bug with that

**Comment by LoneWolfHT** [comment] 2020-01-31 18:56
![image](https://user-images.githubusercontent.com/28972859/73566249-3f4aec00-4418-11ea-9d83-af77dd6bcee0.png)
You might not have the packages installed for it

**Comment by HybridDog** [comment] 2020-01-31 20:21
It only happens for self-compiled versions, so maybe it's a library linking problem.
```bash
ldd bin/minetest
ldd /usr/games/minetest
```
I don't know if this helps.

**Comment by LoneWolfHT** [comment] 2020-01-31 20:41
Doesn't seem to. Anything I should look for in the text it dumps?

**Comment by SmallJoker** [comment] 2020-04-10 14:48
Reported on IRC:

```
Alpine Linux 3.1  AMD64
CPU/GPU: AMD E2-7110 APU with AMD Radeon R2 Graphics
Driver: mesa (xf86-video-ati-19.1.0-r0; mesa-dri-ati-19.2.7-r0)
OpenGL 4.5 (glvnd)
```
![grafik](https://user-images.githubusercontent.com/1497498/78999189-69243b80-7b4a-11ea-8279-6672721ecf62.png)

Could this be AMD/Radeon-related?

**Comment by LoneWolfHT** [comment] 2020-04-10 15:13
I think I just found it
If I enable anti aliasing (at 2x or 4x) I get this, but if I disable this or set it to 8x it goes back to normal again.

**Comment by sfan5** [comment] 2020-04-26 18:13
Another report on IRC: http://irc.minetest.net/minetest/2020-04-26#i_5676188

<hr />

From own testing (doesn't happen on NVIDIA) and all previous reports, this is extremely likely to be caused by changes in Mesa and/or AMD's code.

**Comment by appgurueu** [comment] 2022-02-02 17:50
Yet another report on IRC: https://irc.minetest.net/minetest/2022-02-02#i_5932318

**Comment by rollerozxa** [comment] 2022-02-02 18:06
Can reproduce on RX 560 running latest Arch Linux, both on Minetest 5.4.1, 5.5.0 and 5.6.0-dev-163d3547e. Happens on all areas where there's something semitransparent in front (like the i3 background)

![image](https://user-images.githubusercontent.com/60856959/152211917-12271e3f-c2e5-4a71-aedc-08d875ec4235.png)

**Comment by appgurueu** [comment] 2022-02-02 18:25
Can reproduce with MT 5.5 and 2x antialiasing as well. Graphics card is the integrated one of my AMD® Ryzen 5 3500U, a Radeon Vega mobile GFX. OS is Ubuntu 20.04. As roller has said, this happens with everything semitransparent, including damage flashes and other HUDs.

**Comment by sfan5** [comment] 2022-07-13 13:17
closing in favor of #10676 since that has more relevant details

**Closed by sfan5** 2022-07-13 13:17 UTC
Labels: Bug, @ Client / Audiovisuals, Upstream issue

**Comment by LoneWolfHT** [comment] 2022-07-13 13:36
I'm pretty sure I don't use anything related to Wayland
