### ISSUE TITLE
Chinese

### ISSUE THREAD

**Issue by fly19992020** [minetest/minetest#12909] opened 2022-10-30 11:37 UTC
Why can't I enter Chinese in the chat box?

**Comment by sfan5** [comment] 2022-10-30 12:19
Which Minetest version and OS are you using?

**Comment by y5nw** [comment] 2022-10-30 17:21
For record, I minetest/irrlicht#23 and minetest/minetest#11156 were X11-specific because it is the only platform I can test things on and Irrlicht did (does?) not have a dedicated backend for Wayland, as far as I remember.

**Comment by Emojigit** [comment] 2022-11-05 04:23
Copy & Paste works well on MT, so as a temporary workaround, you can copy CJKs from elsewhere and then paste it onto MT. On my OS (Arch Linux, Wayland, KDE Plasma), this works.

**Comment by y5nw** [comment] 2022-11-05 06:35
Found two issues that this is likely a duplicate of: #10634 and #302 (the latter might need to be reopened if this issue is reproducible)

> By the way, CJKs looks weird in `T`/`F10` chatroom, but looks well on the HUD. As long as the recipients have CJk fonts installed, they can see CJKs properly.

This seems to be fixed by #12867.

**Closed** 2022-11-10 19:38 UTC
Labels: Unconfirmed bug, Action / change needed, Possible close, @ Client / Controls / Input
