### ISSUE TITLE
Certificates for authentication

### ISSUE THREAD

**Issue by niansa** [minetest/minetest#13451] opened 2023-04-22 13:00 UTC
## Problem

Minetest doesn't have a global authentication. And seriously, it's better like that.

## Solutions

I think, Minetest should implement an optional authentication system using a public/private key system.
They are a whole lot more secure than passwords and allow people to potientially authenticate that the player they see on a server is actually the player they think it is.

## Alternatives

No clue. I am not an expert.

## Additional context

Look at how Mumble solved this problem :-)

**Comment by rubenwardy** [comment] 2023-04-22 13:02
Duplicate of #13267, which wasn't accepted

**Closed by rubenwardy** 2023-04-22 13:02 UTC
Labels: Feature request
