### ISSUE TITLE
Pass on Lua threading responsibility to mods

### ISSUE THREAD

**Issue by aerkiaga** [minetest/minetest#11006] opened 2021-02-28 16:03 UTC
## Problem

Multithreading is something that has been asked for many times in the past. According to Steam statistics, 85% of users have at least a 4-core processor, with over 40% already having more than 4 cores. It is, however, not a trivial feature to implement; there is a lot of state that needs to be locked and many changes that have to be made.
Still, many mods, like those implementing entirely custom mapgens, would greatly benefit from this. Any non-trivial mapgen implemented in Lua incurs a big performance cost, to the point that several creative possibilities regarding mods are simply infeasible.

## Solutions

An observation can be made here: most "simple" mods will not override map generation entirely, so they are not affected. If a mod author feels willing to more advanced intervention on world generation, then it can be presumed that they will go the extra mile to make their code more performant if they so desire.
Thus, it's reasonable to believe that the burden of designing complex performance optimizations should lie on the mod author. Assuming they will have properly optimized their code to the furthest they can, the next step would be exposing a multithreading API, one that need not be easy to use if that is in favor of simplicity and stability.
Such an API should affect the rest of the code as little as possible. To this end, access to program resources should remain single-threaded, following the current model. A simple way to accomplish this are worker threads which could be started by the main thread to operate on data and return results. Since the Lua interpreter is single-threaded, those workers would be run on separate instances, with no access to program resources other than those explicitly passed by the main thread (and presumably math functions, `PcgRandom`...).

## API details

Essentially, this approach would require ways to...
* ... create new Lua instances, hold handles to them in the main thread (they could also be created statically).
* ... pass data to them (e.g. adding variables to their environment, passing parameters).
* ... get data from them (e.g. reading from a completed job's environment, return values).
* ... start jobs on other threads.
* ... wait for job completion.
This is enough to implement multithreading in mods. For example, a mod using `minetest.register_on_generated` and then a `VoxelManip` object to create terrain could partition the area to generate in smaller regions, pass each of them to a worker instance, start the jobs and wait until all of them finish, then apply the changes to the mapchunk(s).
This can be implemented in such a way that stability and ease of development are prioritized over simplicity for mod development and performance.

**Comment by rubenwardy** [comment] 2021-02-28 16:11
See also: #3182

**Comment by rubenwardy** [comment] 2021-02-28 16:12
Duplicate of #3375

**Closed by rubenwardy** 2021-02-28 16:12 UTC
Labels: @ Script API, Feature request

**Comment by sfan5** [comment] 2021-02-28 16:18
I wouldn't say this is necessarily a duplicate or at least what's being proposed needs to be defined exactly.
This issue has a proposal for generic threading + IPC, the other issue does too (that's what LuaLanes does) but the OP gives an example where he wants different threads to all access the MT env / share objects at the same time, which is not feasible.

**Comment by sfan5** [comment] 2021-02-28 16:34
And the comment I originally wanted to write:
<hr/>

The mainmenu actually has something very similar to your proposal:
* there is a predefined amount of async workers (4)
* arbitrary functions can be ran asynchronously with a callback that returns the result
* each worker has its own Lua state and only a reduced set of the normal APIs available
* data is passed over via serialization of function arguments and results

You might want to read the source for a better impression of how that works:
https://github.com/minetest/minetest/blob/07500479191ed927ab661b3758ffcd2fd43158c5/builtin/mainmenu/async_event.lua
https://github.com/minetest/minetest/blob/07500479191ed927ab661b3758ffcd2fd43158c5/builtin/async/init.lua
https://github.com/minetest/minetest/blob/4c76239818f5159314f30883f98b977d30aaa26c/src/script/cpp_api/s_async.cpp
https://github.com/minetest/minetest/blob/3a8c37181a9bf9624f3243e8e884f12ae7692609/src/script/lua_api/l_mainmenu.cpp

> Still, many mods, like those implementing entirely custom mapgens, would greatly benefit from this. [...]
> See also: #3182

This is not directly related or rather doesn't help.
For Mapgen you want Lua to run right on the emerge thread, making its modifications only to the chunk that is currently generating and little (ideally none) IPC with any other threads.
What you don't want is mods using the `on_generated` callback to distribute work, block on the results and then write them to the map. It'd still "work" but is a poor imitation of the proper solution.

**Comment by rubenwardy** [comment] 2021-02-28 16:43
> I wouldn't say this is necessarily a duplicate or at least what's being proposed needs to be defined exactly.
> This issue has a proposal for generic threading + IPC, the other issue does too (that's what LuaLanes does) but the OP gives an example where he wants different threads to all access the MT env / share objects at the same time, which is not feasible.

They're both asking the same thing in different ways, as users often do

**Comment by sfan5** [comment] 2021-02-28 16:50
I question the usefulness of discussing this there when the OP post sets the pretenses and direction all wrong.

**Comment by rubenwardy** [comment] 2021-02-28 16:55
Well, feel free to swap the issues then, and mark the other as duplicate
