### ISSUE TITLE
random screenshot corruption

### ISSUE THREAD

**Issue by tigercoding56** [minetest/minetest#14733] opened 2024-06-07 04:35 UTC
### Minetest version

```true
minetest dev 5.9.0
```

### Irrlicht device

wayland

### Operating system and version

nyarch linux (latest)

### CPU model

i5

### GPU model

intel IGPU

### Active renderer

opengl 4

### Summary

2 screenshots i took around 40 second after one another, one corrupted one not corrupt. nothing was done to screenshots by me 
![screenshot_20240606_212938](https://github.com/minetest/minetest/assets/90169211/cfe509a6-233f-4c6e-b670-9a29f567815b)

![screenshot_20240606_213025](https://github.com/minetest/minetest/assets/90169211/64e45a40-25c3-4c1e-9b9d-85171d82e3b1)

### Steps to reproduce

just take enough screenshots on dev version , idk it eventually appears in some screenshots

**Comment by grorp** [comment] 2024-06-07 21:20
Looks like a duplicate of #13221

**Closed** 2024-06-08 00:40 UTC
Labels: Duplicate
