### ISSUE TITLE
Particles rendered for everyone on server irregardless of distance/visibility

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5667] opened 2017-04-26 23:34 UTC
**Introduction:**
Particles are rendered for everyone on server irregardless of distance/visibility, here is quick demo of the problem involving TNT explosion on vanilla game localhost server (2 clients), notice pretty big fps impact and big distance between clients on same server:
![default](https://cloud.githubusercontent.com/assets/16494741/26029996/dde2023e-384c-11e7-8537-c1eb998ccb4c.png)

**My initial edited bugreport of the problem, which was discovered on multiplayer server:**
Client: 0.4.15-dev (af96309)
Server: Hometown at 0.4.15-dev (close to latest)

Bug:
Exploding large amount of TNT (say, 30) far away from players (say 10000 blocks deep) causes big mainloop_dtime lag spike (and low fps) which was confirmed many times by several players, lag/freeze/low fps appears like this (mesh_gen_interval at 15ms):
![release](https://cloud.githubusercontent.com/assets/16494741/25461456/db4c48bc-2af1-11e7-9e63-367828e88058.png)
Explosion of >30 TNT at -10000 deep (>10000 nodes away from me):
![default](https://cloud.githubusercontent.com/assets/16494741/25461821/dcb1ef16-2af3-11e7-964f-da2b63b7f8a4.png)

Verbose debug output during explosion on my client (for last pic):
```
2017-04-27 02:44:07: INFO[Main]: Client: avg_rtt=0.172
2017-04-27 02:44:09: INFO[Main]: Client: time_of_day=18108 time_speed=72 dr=883
2017-04-27 02:44:11: VERBOSE[Main]: Saving registered mod storages.
2017-04-27 02:44:14: INFO[Main]: Client: time_of_day=18208 time_speed=72 dr=808
2017-04-27 02:44:16: VERBOSE[Main]: Saving registered mod storages.
2017-04-27 02:44:17: INFO[Main]: Client: avg_rtt=0.172
2017-04-27 02:44:19: INFO[Main]: Client: time_of_day=18308 time_speed=72 dr=728
2017-04-27 02:44:21: VERBOSE[Main]: Saving registered mod storages.
2017-04-27 02:44:24: INFO[Main]: Client: time_of_day=18408 time_speed=72 dr=651
2017-04-27 02:44:26: INFO[Main]: Client packetcounter (20):
2017-04-27 02:44:26: INFO[Main]: cmd 2 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 3 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 32 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 33 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 39 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 41 count 4
2017-04-27 02:44:26: INFO[Main]: cmd 48 count 6
2017-04-27 02:44:26: INFO[Main]: cmd 49 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 50 count 5
2017-04-27 02:44:26: INFO[Main]: cmd 51 count 5
2017-04-27 02:44:26: INFO[Main]: cmd 52 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 58 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 60 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 61 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 65 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 66 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 67 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 69 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 70 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 71 count 70
2017-04-27 02:44:26: INFO[Main]: cmd 73 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 74 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 75 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 76 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 77 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 78 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 81 count 0
2017-04-27 02:44:26: INFO[Main]: cmd 96 count 0
2017-04-27 02:44:26: VERBOSE[Main]: Saving registered mod storages.
2017-04-27 02:44:27: INFO[Main]: Client: avg_rtt=0.172
2017-04-27 02:44:29: INFO[Main]: Client: time_of_day=18508 time_speed=72 dr=581
* * * * * * * * * * * * * * * * ROUGH EXPLOSION TIME (time of exploder death) * * * * * *
2017-04-27 02:44:32: VERBOSE[Main]: Saving registered mod storages.
2017-04-27 02:44:34: INFO[Main]: Client: time_of_day=18608 time_speed=72 dr=511
2017-04-27 02:44:37: VERBOSE[Main]: Saving registered mod storages.
2017-04-27 02:44:37: INFO[Main]: Client: avg_rtt=0.172
2017-04-27 02:44:39: INFO[Main]: Client: time_of_day=18708 time_speed=72 dr=450
2017-04-27 02:44:42: VERBOSE[Main]: Saving registered mod storages.
2017-04-27 02:44:44: INFO[Main]: Client: time_of_day=18808 time_speed=72 dr=390
2017-04-27 02:44:46: INFO[Main]: Client packetcounter (20):
2017-04-27 02:44:46: INFO[Main]: cmd 2 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 3 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 32 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 33 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 39 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 41 count 4
2017-04-27 02:44:46: INFO[Main]: cmd 48 count 11
2017-04-27 02:44:46: INFO[Main]: cmd 49 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 50 count 6
2017-04-27 02:44:46: INFO[Main]: cmd 51 count 5
2017-04-27 02:44:46: INFO[Main]: cmd 52 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 58 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 60 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 61 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 65 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 66 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 67 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 69 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 70 count 85
2017-04-27 02:44:46: INFO[Main]: cmd 71 count 275
2017-04-27 02:44:46: INFO[Main]: cmd 73 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 74 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 75 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 76 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 77 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 78 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 81 count 0
2017-04-27 02:44:46: INFO[Main]: cmd 96 count 0
2017-04-27 02:44:47: INFO[Main]: Client: avg_rtt=0.172
2017-04-27 02:44:48: VERBOSE[Main]: Saving registered mod storages.
2017-04-27 02:44:49: INFO[Main]: Client: time_of_day=18908 time_speed=72 dr=336
2017-04-27 02:44:53: VERBOSE[Main]: Saving registered mod storages.
2017-04-27 02:44:54: INFO[Main]: Client: time_of_day=19008 time_speed=72 dr=296
2017-04-27 02:44:57: INFO[Main]: Client: avg_rtt=0.172
2017-04-27 02:44:58: VERBOSE[Main]: Saving registered mod storages.
2017-04-27 02:44:59: INFO[Main]: Client: time_of_day=19108 time_speed=72 dr=256
2017-04-27 02:45:04: VERBOSE[Main]: Saving registered mod storages.
2017-04-27 02:45:04: INFO[Main]: Client: time_of_day=19208 time_speed=72 dr=216
2017-04-27 02:45:06: INFO[Main]: Client packetcounter (20):
2017-04-27 02:45:06: INFO[Main]: cmd 2 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 3 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 32 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 33 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 39 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 41 count 4
2017-04-27 02:45:06: INFO[Main]: cmd 48 count 6
2017-04-27 02:45:06: INFO[Main]: cmd 49 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 50 count 5
2017-04-27 02:45:06: INFO[Main]: cmd 51 count 5
2017-04-27 02:45:06: INFO[Main]: cmd 52 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 58 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 60 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 61 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 65 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 66 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 67 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 69 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 70 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 71 count 101
2017-04-27 02:45:06: INFO[Main]: cmd 73 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 74 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 75 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 76 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 77 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 78 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 81 count 0
2017-04-27 02:45:06: INFO[Main]: cmd 96 count 0
2017-04-27 02:45:07: INFO[Main]: Client: avg_rtt=0.172
2017-04-27 02:45:09: VERBOSE[Main]: Saving registered mod storages.
2017-04-27 02:45:09: INFO[Main]: Client: time_of_day=19308 time_speed=72 dr=176
2017-04-27 02:45:14: VERBOSE[Main]: Saving registered mod storages.
2017-04-27 02:45:14: INFO[Main]: Client: time_of_day=19409 time_speed=72 dr=150
2017-04-27 02:45:17: INFO[Main]: Audio: Deinitializing...
2017-04-27 02:45:17: INFO[Main]: Audio: Deinitialized.
2017-04-27 02:45:17: INFO[Main]: ~TextureSource() 2576/3
2017-04-27 02:45:17: INFO[Main]: Irrlicht resources after cleanup:
2017-04-27 02:45:17: INFO[Main]: 	Remaining meshes   : 0
2017-04-27 02:45:17: INFO[Main]: 	Remaining textures : 3
2017-04-27 02:45:17: INFO[Main]: 		0:#DefaultFont
2017-04-27 02:45:17: INFO[Main]: 		1:TTFontGlyphPage_Arimo.Regular.13_0
2017-04-27 02:45:17: INFO[Main]: 		2:TTFontGlyphPage_Cousine.Regular.13_0
2017-04-27 02:45:17: INFO[Main]: 	Remaining materials: 74 (note: irrlicht doesn't support removing renderers)
2017-04-27 02:45:17: INFO[Main]: Waiting for other menus
2017-04-27 02:45:17: INFO[Main]: Waited for other menus
2017-04-27 02:45:17: INFO[Main]: Audio: Initializing...
2017-04-27 02:45:17: INFO[Main]: Audio: Initialized: OpenAL 1.1 ALSOFT 1.15.1, using OpenAL Soft
2017-04-27 02:45:17: INFO[Main]: GUIEngine: Initializing Lua
2017-04-27 02:45:17: VERBOSE[AsyncWorker-0]: Loading and running script from D:\Newprog\minetest\bin\..\builtin\init.lua
2017-04-27 02:45:17: VERBOSE[AsyncWorker-1]: Loading and running script from D:\Newprog\minetest\bin\..\builtin\init.lua
2017-04-27 02:45:17: INFO[AsyncWorker-0]: Initializing Asynchronous environment
2017-04-27 02:45:17: VERBOSE[AsyncWorker-2]: Loading and running script from D:\Newprog\minetest\bin\..\builtin\init.lua
2017-04-27 02:45:17: INFO[AsyncWorker-1]: Initializing Asynchronous environment
2017-04-27 02:45:17: VERBOSE[AsyncWorker-3]: Loading and running script from D:\Newprog\minetest\bin\..\builtin\init.lua
2017-04-27 02:45:17: INFO[AsyncWorker-2]: Initializing Asynchronous environment
2017-04-27 02:45:17: INFO[Main]: SCRIPTAPI: Initialized main menu modules
2017-04-27 02:45:17: VERBOSE[Main]: Loading and running script from D:\Newprog\minetest\bin\..\builtin\init.lua
2017-04-27 02:45:17: INFO[AsyncWorker-3]: Initializing Asynchronous environment
2017-04-27 02:45:17: INFO[Main]: Searching worlds...
2017-04-27 02:45:17: INFO[Main]:   In D:\Newprog\minetest\bin\..\worlds: 
2017-04-27 02:45:17: INFO[Main]: DamEvasion Home Kraydyfi Kraydyfi2011 SneakTesting 
2017-04-27 02:45:17: INFO[Main]: 5 found.
2017-04-27 02:45:17: VERBOSE[Main]: OpenALSoundManager::maintain(): 0 playing sounds, 0 sound names loaded
2017-04-27 02:45:17: INFO[Main]: Audio: Error opening D:\Newprog\minetest\bin\..\sounds\main_menu.0.ogg for decoding
2017-04-27 02:45:17: INFO[Main]: Audio: Error opening D:\Newprog\minetest\bin\..\sounds\main_menu.1.ogg for decoding
2017-04-27 02:45:17: INFO[Main]: Audio: Error opening D:\Newprog\minetest\bin\..\sounds\main_menu.2.ogg for decoding
2017-04-27 02:45:17: INFO[Main]: Audio: Error opening D:\Newprog\minetest\bin\..\sounds\main_menu.3.ogg for decoding
2017-04-27 02:45:17: INFO[Main]: Audio: Error opening D:\Newprog\minetest\bin\..\sounds\main_menu.4.ogg for decoding
2017-04-27 02:45:17: INFO[Main]: Audio: Error opening D:\Newprog\minetest\bin\..\sounds\main_menu.5.ogg for decoding
2017-04-27 02:45:17: INFO[Main]: Audio: Error opening D:\Newprog\minetest\bin\..\sounds\main_menu.6.ogg for decoding
2017-04-27 02:45:17: INFO[Main]: Audio: Error opening D:\Newprog\minetest\bin\..\sounds\main_menu.7.ogg for decoding
2017-04-27 02:45:17: INFO[Main]: Audio: Error opening D:\Newprog\minetest\bin\..\sounds\main_menu.8.ogg for decoding
2017-04-27 02:45:17: INFO[Main]: Audio: Error opening D:\Newprog\minetest\bin\..\sounds\main_menu.9.ogg for decoding
2017-04-27 02:45:17: INFO[Main]: Audio: Error opening D:\Newprog\minetest\bin\..\sounds\main_menu.ogg for decoding
2017-04-27 02:45:17: INFO[Main]: OpenALSoundManager: "main_menu" not found.
2017-04-27 02:45:19: INFO[Main]: Audio: Deinitializing...
2017-04-27 02:45:19: INFO[Main]: Audio: Deinitialized.
2017-04-27 02:45:19: INFO[Main]: GUIEngine: Deinitializing scripting
2017-04-27 02:45:19: INFO[Main]: Searching worlds...
2017-04-27 02:45:19: INFO[Main]:   In D:\Newprog\minetest\bin\..\worlds: 
2017-04-27 02:45:19: INFO[Main]: DamEvasion Home Kraydyfi Kraydyfi2011 SneakTesting 
2017-04-27 02:45:19: INFO[Main]: 5 found.
2017-04-27 02:45:19: INFO[Main]: Selected world: DamEvasion [D:\Newprog\minetest\bin\..\worlds\DamEvasion]
2017-04-27 02:45:19: VERBOSE[Main]: httpfetch_cleanup: cleaning up
```

Also potentially related to https://github.com/minetest/minetest/issues/5412

**Comment by paramat** [comment] 2017-04-26 23:39
@celeron55

**Comment by GreenXenith** [comment] 2017-04-27 03:37
Hehehe that may have been me exploding the original TNT :3

**Comment by celeron55** [comment] 2017-04-27 07:31
there's a log of network command 70 (0x46), which is TOCLIENT_SPAWN_PARTICLE. I would expect the lag to be caused by particles.

**Comment by twoelk** [comment] 2017-04-27 13:55
some years back on VanessaE's creative server when someone flushed a toilet of the homedecor mod everyone everywhere on the same server could hear the sound. Could this be similar with particles? 
Who decides how far actions of the TNT mod are considered relevant enough to send or use the information? Mod, server or client? If this is indeed an issue with particles, do other particle using mods have similar issues? How far can particle based smoke or fireworks been seen?

**Comment by Fixer-007** [comment] 2017-04-27 13:57
Sound problem is easily fixed, this one is much deeper it seems.

**Comment by numberZero** [comment] 2017-04-27 19:42
There are `max_block_send_distance` and `player_transfer_distance`. It seems to be reasonable to add `max_particle_send_distance`. That’s especially important for spawners. But for them, another solution exists: associate them with blocks, and send only when the corresponding block is sent.

**Comment by paramat** [comment] 2017-04-27 21:29
Particles should certainly be distance limited if they are not already, imagine all those weather mods with hundreds of particles constantly falling. Even a configurable fixed distance would be ok.

**Comment by numberZero** [comment] 2017-04-27 21:50
> Particles should certainly be distance limited if they are not already

They aren’t.

> configurable fixed distance would be ok.

There is a problem with fixed distance: the server still needs to check had it send that particular spawner to that particular player; otherwise, existing particle spawners won’t be visible to players coming from the far. In the approach I suggest, it can use existing mechanics for that. But I’m not sure what is simpler.

> imagine all those weather mods

Now I understand why they are **so** laggy...

**Comment by sfan5** [comment] 2017-04-28 12:04
@paramat 
weather mods should use a player-attached particle spawner instead of putting lots of spawners somewhere

Generally particles could reuse the `active_block_range` settings (would make the most sense imo)

**Comment by paramat** [comment] 2017-04-28 20:21
> weather mods should use a player-attached particle spawner instead of putting lots of spawners somewhere

They do already, i meant the effect of weather mods spawning hundreds of particles for every player on a server.

**Comment by paramat** [comment] 2017-04-28 20:24
> weather mods should use a player-attached particle spawner instead of putting lots of spawners somewhere

They do already, so maybe they are not a problem, TNT spawns particles visible to all players.

**Comment by Fixer-007** [comment] 2017-05-13 20:47
Observation: connected to Hometown, number of particles raised pretty quickly and stabilised at 200-300 for very long time (sometimes going as high as 700), I do quick restart and it suddenly goes back to 20-30 particles... this huge particle count may also be linked to my poor fps at times. Possible particle spawn/despawn problems? (my post from another issue that is potentially linked to this).

**Comment by paramat** [comment] 2017-05-13 22:59
This is high priority, imagine the unnecessary FPS drop created by all players 'seeing' all particles on a server, with particles themselves are unoptimised.

**Comment by numberZero** [comment] 2017-05-13 23:04
Warning: I’m a pyromaniac!
![screenshot_20170512_010514](https://cloud.githubusercontent.com/assets/7352626/25974687/6abe8d1e-36bb-11e7-9bef-99b352d2d71e.png)
![screenshot_20170512_010533](https://cloud.githubusercontent.com/assets/7352626/25974686/6abc8f28-36bb-11e7-9428-26a86e0c3109.png)
![screenshot_20170512_010750](https://cloud.githubusercontent.com/assets/7352626/25974688/6abf5eba-36bb-11e7-92ca-b54ce4ee325e.png)
![screenshot_20170512_010833](https://cloud.githubusercontent.com/assets/7352626/25974689/6ac1cc36-36bb-11e7-8ff7-f555ed784e51.png)

This is SP. Note that particles despawn here very quickly, as they should.

**Comment by numberZero** [comment] 2017-05-13 23:12
Read through `particles.cpp`. Well, making each and every particle a separate `SceneNode` seems overkill. Storing particles that way looks strange too, it might be `std::list<Particle>` (yes, by value). And spawners are especially weird, that’s another story. But that doesn’t explain by itself why could extra particles remain. That may be a mod-specific problem; it may be worth inspecting times set: `m_expiration`, `m_minexptime`, `m_maxexptime`, `m_time`.

**Comment by paramat** [comment] 2017-05-13 23:27
https://github.com/minetest/minetest/blob/master/src/server.cpp#L1702
Here particles are sent to all clients if 'peer_id' is not specified, there is no distance check.
"// This sucks and should be replaced by a better solution in a refactor:"

**Comment by Fixer-007** [comment] 2017-05-13 23:27
Confirmed in vanilla:
![default](https://cloud.githubusercontent.com/assets/16494741/26029996/dde2023e-384c-11e7-8537-c1eb998ccb4c.png)

**Comment by Fixer-007** [comment] 2017-05-13 23:40
@numberZero could be mod issue, hard to tell, hometown uses mobs_redo and tnt (both utilise particles).

**Comment by paramat** [comment] 2017-05-13 23:53
https://github.com/minetest/minetest/blob/master/src/server.cpp#L2077 here is sound code which shows how a distance check could be added.

**Comment by paramat** [comment] 2017-05-14 00:02
I'll try to make a PR for this soon so you can test.

**Comment by numberZero** [comment] 2017-05-14 00:16
@Fixer-007 *It seems you run XP =) Well, that was a nice system...*

The impact is of course very big, as the particles are implemented ridiculously ineffectively. Half of it is that a GPU is being spoon-fed 2 faces a time (`particles.cpp`, 130), with material change each and every time; it goes in `mainloop_draw` but not shown in the profile (it doesn’t show the `Particle::render()` at all), probably because that’s called by IrrLicht itself only. The other half, going to `mainloop_other`, is taken mostly by collision tests, and some by memory allocation/freeing (the only thing `ParticleManager::stepParticles` does by itself)

```
[12]     8.8    0.19    0.83    2202         ParticleManager::stepParticles(float) [12]
                0.01    0.82   38643/38643       Particle::step(float) [15]
...
                0.01    0.82   38643/38643       ParticleManager::stepParticles(float) [12]
[15]     7.2    0.01    0.82   38643         Particle::step(float) [15]
                0.26    0.54   19371/19464       collisionMoveSimple(Environment*, IGameDef*, float, irr::core::aabbox3d<float> const&, flo
                0.00    0.02   38642/45789       Particle::updateLight() [129]
                0.00    0.00   38642/45790       Particle::updateVertices() [618]
```
[Full profiling results](https://github.com/minetest/minetest/files/999008/profile-particles.txt)
Note: these results are for f17c9c45d, but particles haven’t changed since then.

**Comment by Fixer-007** [comment] 2017-05-14 00:19
Windows 7 sp1 with windows classic theme.

**Comment by numberZero** [comment] 2017-05-14 00:19
oh well, I though they removed that old-style look...

**Comment by Fixer-007** [comment] 2017-05-14 00:20
In windows 8, sadly :(

**Comment by paramat** [comment] 2017-05-14 01:01
#5760

**Comment by paramat** [comment] 2017-05-18 08:11
#5760 merged.
Fixing PR for particle spawners #5766

**Closed** 2017-05-20 18:31 UTC
Labels: Blocker, Bug, High priority, Performance

**Comment by paramat** [comment] 2017-05-20 18:36
#5766 merged.
