### ISSUE TITLE
Translucent blocks are not displayed translucent in inventory

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5893] opened 2017-06-03 11:56 UTC
Blocks which are normally translucent (`uses_texture_alpha`, `alpha` attributes) are displayed as fully opaque in the inventory and in the wieldhand.

Example in Minetest Game:

* Water Source
* Lava Source

This is relevant for mods which add a lot of translucent blocks, such as stained glass.

Tested in 0.4.15.

**Comment by paramat** [comment] 2017-06-03 14:06
Hmmm this may be a good thing, it makes them easier to identify.
@juhdanad

**Comment by Wuzzy2** [comment] 2017-06-03 14:34
On the downside, the item+wield images can look very different from how they look in the world:

![Screenshot](https://i.imgur.com/OOaAwxC.png)

**Comment by paramat** [comment] 2017-06-03 14:54
Ah that's not fully opaque then , as low opacity goes to zero opacity, which i agree is a problem.
Maybe all opacities should go to 255?

**Comment by Wuzzy2** [comment] 2017-06-03 15:21
Right. What MT seems to do is either full transparency or 0% transparency, but nothng in-between

**Comment by juhdanad** [comment] 2017-06-03 18:48
Translucency is currently not supported for wield items and inventory items. For plain nodes it could be implemented, but extruded meshes would need depth sorting first.

**Comment by paramat** [comment] 2017-06-03 19:01
Ok, i wouldn't bother, inventory rendering needs to be fast, translucency is not supported for many nodes in MT anyway, and liquid nodes are usually > 127 opacity.
The current behaviour seems ok to me.

**Comment by ElementW** [comment] 2017-07-07 14:46
> Inventory rendering needs to be fast

@paramat Supporting translucency wouldn't be any slower, maybe except on some software renderers; any remotely decent GL 2.0+ capable GPU has zero-overhead alpha blending capability *when you disable Z-buffer testing and writing* (which is not required for 2D GUIs). If inventory rendering is slow, alpha-blending isn't the problem, or else you'd already have tackled that problem by disabling all formspec background translucency first handedly.

> The current behaviour seems optimal to me.

You are sickeningly conservative about MT's behaviours IMO. Either MT wants to supports translucency, which it does to *some extent*, or either it doesn't and removes all non-extrema alpha channel support. What you are promoting is general inconsistency of feature support, having a *somewhat* working node translucency support while having it utterly broken in the other half of the game that is the GUI.

That behaviour is not optimal, it is inconsistent to the least, and idiotic at most.

While Irrlicht *may* be at fault for having faulty alpha support (IDK, haven't checked the source), it should be clarified whether this issue is supposed to be ever resolved or not, and if the current strange behaviour will stay because of... *feeble-mindedness*.

**Comment by paramat** [comment] 2017-07-07 15:08
> Supporting translucency wouldn't be any slower

Ok good.

> You are sickeningly conservative about MT's behaviours IMO.

It's not conservatism, that's a misperception, my reasons for my opinions are clearly stated and are not opinions held for no good reason and from nothing other than a dislike of new things. If you knew me you would know i dislike tradition and am obsessed with modernism, change and futurism.

Those who are irritated by my opinion on a certain subject just don't agree with me, the more reasonable will realise this and will discuss rationally and maybe convince me to change my mind (which i do a lot), some others will make some insult about acting purely through 'conservativism' (which for me in the UK is an insult due to the political party here that has that name).

I accept i was wrong about translucency being slower, and now i think supporting semi-translucency in the inventory is probably a good idea. So i have changed my miind.

**Comment by ElementW** [comment] 2017-07-07 15:26
@paramat Didn't mean to generalize the "conservatism" criticism, I've edited the original comment to reflect on what particular issue (this one) you seemed to be to me, even if it turns our you were misdirected.

**Comment by Fixer-007** [comment] 2017-11-03 15:45
Translucency is must have, it even affects default gameplay - go build glass tunnel underwater and enjoy your show.

**Comment by Wuzzy2** [comment] 2020-07-24 10:20
This bug can be easily observed and reproduced in `devtest`, as of 5.3.0:

* `/giveme testnodes:alpha_128`
* `/giveme testnodes:alpha_texture_128`
* `/giveme testnodes:alpha_191`
* `/giveme testnodes:alpha_texture_191`

At an `alpha` of 128 or less, the node/pixel becomes invisible in inventory and wieldhand, above that, it's fully opaque.

**Comment by SmallJoker** [comment] 2020-12-13 17:35
Duplicate of #5461, just using other alpha values.

**Closed by SmallJoker** 2020-12-13 17:35 UTC
Labels: @ Client / Audiovisuals, Bug, Low priority, Request / Suggestion
