### ISSUE TITLE
gcc warning -Warray-bounds in util/srp.cpp

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#10446] opened 2020-09-29 19:26 UTC
##### Minetest version
```
Minetest 5.4.0-dev-995d40526 (Linux)
```

##### Compiler version
```
gcc (GCC) 10.2.0
```

##### Summary

Compiler output:
```
[ 83%] Building CXX object src/CMakeFiles/minetest.dir/util/srp.cpp.o
In function 'SRP_Result H_ns(__mpz_struct*, SRP_HashAlgorithm, const unsigned char*, size_t, const unsigned char*, uint32_t)',
    inlined from 'int calculate_x(__mpz_struct*, SRP_HashAlgorithm, const unsigned char*, size_t, const char*, const unsigned char*, size_t)' at <minetest_dir>/src/util/srp.cpp:455:13:
<minetest_dir>/src/util/srp.cpp:432:8: warning: 'void* memcpy(void*, const void*, size_t)' forming offset [64, 4294967294] is out of the bounds [0, 64] of object 'ucp_hash' with type 'unsigned char [64]' [-Warray-bounds]
  432 |  memcpy(bin + len_n, bytes, len_bytes);
      |  ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<minetest_dir>/src/util/srp.cpp: In function 'int calculate_x(__mpz_struct*, SRP_HashAlgorithm, const unsigned char*, size_t, const char*, const unsigned char*, size_t)':
<minetest_dir>/src/util/srp.cpp:443:16: note: 'ucp_hash' declared here
  443 |  unsigned char ucp_hash[SHA512_DIGEST_LENGTH];
      |                ^~~~~~~~
```

See also: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Warray-bounds

<details><summary>Permalinks to code</summary>

https://github.com/minetest/minetest/blob/995d4052610b98821e1dcaf5031477de6f202bef/src/util/srp.cpp#L401-L437
https://github.com/minetest/minetest/blob/995d4052610b98821e1dcaf5031477de6f202bef/src/util/srp.cpp#L341-L359
</details>

It is possible, that `hash_length` always returns `-1`, which is always greater than the size of the array, hence the `-Warray-bounds`, I guess.

**Comment by rubenwardy** [comment] 2021-02-03 09:15
Duplicate of #10238

**Closed by rubenwardy** 2021-02-03 09:15 UTC
Labels: Unconfirmed bug
