### ISSUE TITLE
Enable node damage for LuaEntities

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9372] opened 2020-02-07 16:19 UTC
## Problem

LuaEntities don't take node damage (`damage_per_second`).

## Solutions

Add an object property called "`takes_node_damage`". If `true`, the object will take damage from nodes. If `false`, it doesn't.

To ensure backwards-compability, this property defaults to `true` for players and to `false` for LuaEntities.

As a side-effect, this implies that node damage can be disabled for players.

## Alternatives

Implementing this in Lua. However, I strongly advice against this, because this has has several downsides:

1. No client prediction/handling possible / requires an avoidable roundtrip
2. Redundant with engine implementation: You would have to replicate engine behavior exactly, which is tricky to do and there are several gotchats: When is the object “inside” the damaging node? At what times should the object be hurt? Etc.
3. Doomed to become inconsistent with engine behavior: Even if a Lua implementation manages a to make perfect replication of engine behavior, it is doomed to become inconsistent, because it's redundant. If there's a bug in the engine implementation, or a new feature is added, the Lua implementation won't benefit from it. This is especially a problem if the Lua implementation is in a mod or game.
4. Probably too difficult: Lua might not have the neccessary information for a perfect replication of engine behavior anyway

**Comment by sfan5** [comment] 2020-02-07 18:34
Do lua entities even take any other type of environmental damage?

**Comment by Wuzzy2** [comment] 2020-02-07 18:39
Not yet. ;-)

As far I know, the only damage types that LuaEntities currently recognize are `set_hp` and punches.

**Comment by paramat** [comment] 2020-02-07 22:43
Seems also a bug.
+1, but perhaps we do not need an object property, it seems all objects should obviously take damage from nodes that give damage. Is 'backwards compatibility' important here?

**Comment by rubenwardy** [comment] 2020-02-07 22:48
> +1, but perhaps we do not need an object property, it seems all objects should obviously take damage from nodes that give damage. Is 'backwards compatibility' important here?

Hard coding the behaviour is bad. Entities are server controlled, and it should be up to them whether they are affected by gravity, etc. I don't even like how health is forced on entities. I suggest some utility function which the entity can call to check for damage

**Comment by sfan5** [comment] 2020-02-08 00:00
>  I suggest some utility function which the entity can call to check for damage

I don't think that'll lead to any kind of good design.
Entities should just be able to specify whether they want to take damage.

**Comment by Wuzzy2** [comment] 2020-02-08 00:10
> Entities should just be able to specify whether they want to take damage.

Which is exactly what I suggested.

**Comment by paramat** [comment] 2020-02-12 01:09
> Entities should just be able to specify whether they want to take damage.

Yes that seems necessary.

**Comment by ClobberXD** [comment] 2020-02-13 00:59
It'd probably be nicer to have this as an `armor` group instead of an object property, IMO. This would also make sense when taking into consideration that damage can be entirely disabled by setting the `immortal` group to 1.

**Comment by Wuzzy2** [comment] 2020-02-13 02:14
The problem with armor groups is how to add them to make them work backwards-compatible with players as well. You would have to find a way to add the “node damage” armor group to players in an existing world without breaking anything.

Any implementation should work the same for both players and LuaEntities. Players and LuaEntities are already weirdly inconsistent in many aspects, we should not make it worse.

**Comment by ClobberXD** [comment] 2020-02-13 03:13
I don't have much experience working with entities, so apologies if I missed something. But I don't see how using groups would create compatibility issues, that are bypassed by using object properties. Might you be able to elaborate?

**Comment by TheTermos** [comment] 2020-02-28 13:52
This suggestion entails that built in damage system is used, if I'm not mistaken.

Thing is, the built in damage system is too specific for it's own good, and to take benefit of the proposed mechanic one would have to accept all the unbenefits that come with it.
I'm bypassing built in damage system entirely, the most popular mob mod seems to do that as well, so I think the usefulness of such a parameter would be limited.

Something like on_env_hazard callback could be more useful.

**Comment by appgurueu** [comment] 2020-12-24 13:51
This can be well done in entity `on_step` code, there is no need for an engine feature.

**Comment by appgurueu** [comment] 2024-06-10 11:25
Since it has come up again, I'd like to reiterate my stance again: I do not think this would be a step in the right direction.

As for Wuzzy's mentioned downsides:

1. As far as I'm aware, we currently don't have client prediction for node damage. I don't consider the theoretical possibility of client prediction very relevant, and even then, it would be relatively minor: The difference would be whether it takes one packet from server to client to make the entity show the "damage flash". Furthermore, my preferred (due to its better flexibility) approach of getting client prediction long-term in general would be via SSCSM.
2. No, that's the good part, you don't have to replicate legacy engine behavior. You can just roll your own behavior which is hopefully a better fit for your game.
3. Again, I see the possibility for mod implementations to diverage as a feature, because quite frankly, the engine implementation is not a good one, just one we have to keep around for backwards compatibility reasons.
4. As you can see below, this claim doesn't hold. It holds even less now that node boxes are exposed to Lua.

Here is the current engine implementation, in all its legacy glory:

https://github.com/minetest/minetest/blob/4c9be808a7222e82e04c24d927150664773ad5be/src/server/player_sao.cpp#L188-L225

What this does is:

* Look at a bunch of damage points along the Y axis, applying some arbitrary offsets. This is already a dirty hack, which only really works well for players.
* Just uses `getNode`, does not take into account collision boxes at all. Again dirty.
* Uses an arbitrary timer (1s).
* Dubious edge case handling: If the player is inside two different nodes which deal damage, only one of them will end up dealing damage, for a sufficiently large player.

To make this usable for entities (and collision boxes) more generally, you'd essentially have to completely rewrite this and parameterize at least

* Enabled/disabled
* Timer interval
* Damage points (bonus points for things like long, rotated entities)
* Perhaps other features modders might like, such as damage groups (poisoned spikes, anyone?)

At which point we're starting to implement game logic rather than being a game engine.

I think it is pretty much strictly better if modders think about how they want environmental damage for their entities to work and implement that properly. Standards can emerge that way, e.g. through mob APIs, and when they have matured, we may consider integrating them into the engine, if there is a significant benefit to doing that. I presently see no reason to implement this in C++ rather than Lua (since we don't have clientside prediction anyways).

On that note, I do not think bloating object properties further with this would be a good idea, especially considering that this currently only needs to be server-only (whereas object properties are shared with the client).

Now, we unfortunately have this feature for players and need to continue to support it, so modders should probably be able to turn it off (without outright making the player immortal or making all nodes not have damage), hence why I support a flag for this in #14179 as a "dehardcoding" effort.

I propose:

* Removing the "bug" tag. This is not a bug, it is a feature request. Our docs properly state that node damage only applies to players. While in many aspects similar, players and entities are not the same, and implementing this for entities (or even arbitrary players) requires additional consideration. My recommendation to modders would frankly be to reimplement this feature themselves entirely, even for players - which is easy enough to do - unless they are 100% happy with it as-is.
* Remove the "concept approval", since paramat is not involved anymore, unless another core dev agrees with the concept. A reconsideration is due either way.
* Perhaps most controversial: Tagging this low priority or possible close / won't implement, and possibly closing this. This may be just my opinion however.

I would appreciate other opinions on this.

**Closed** 2024-08-12 09:48 UTC
Labels: @ Server / Client / Env., @ Script API, Feature request, Possible close
