### ISSUE TITLE
Default button sound plays delayed if clicking Sound or Keybind button in singleplayer pause menu

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#13931] opened 2023-10-26 23:38 UTC
### Minetest version

```true
5.8.0-dev-2ce14ce4e
```

### Active renderer

OpenGL 4.5

### Irrlicht device

X11

### Operating system and version

Parabola

### OpenGL version

4.5

### Summary

If you have button sounds in the formspec prepend and then open the pause menu in singleplayer and then click on "Sound volume" or the keybinds button and then hit Esc, the default button sound will not play when you click the sound volume or keybinds button, but after you leave these menus.

This is a regression compared to 5.7.0.

### Steps to reproduce

1. Launch Glitch 1.2.3 in singleplayer (because this game has a default button sound in its formspec prepend)
2. Hit Esc.
3. Press the sound volume button

Expected: Button sound plays when you click on sound volume
Actual: Button sound plays when you *leave* the sound volume menu; but entering this menu is silent

You can test without Glitch. Just make sure the formspec prepend has a default button sound assigned.

**Comment by Desour** [comment] 2023-10-27 20:23
Good catch!
Can reproduce. (Had to use a longer sound though, because pause is not working correctly for new sounds (it's not instant).)

This happens because sounds are now paused while in pause menu.
Will try to fix.

**Comment by Desour** [comment] 2023-10-28 22:41
(Fixed by #13940.)

**Closed by Desour** 2023-10-28 22:41 UTC
Labels: Bug, @ Startup / Config / Util, @ Client / Audiovisuals, Sounds, Formspec, Regression
