### ISSUE TITLE
V7 rivergen removing mod nodes added in 'on_generated()'

### ISSUE THREAD

**Issue by Treer** [minetest/minetest#7379] opened 2018-05-27 15:37 UTC
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.4.16 (Windows) Using Irrlicht 1.8.4
and
Minetest 0.5.0-cf0bceb (Windows) Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```
I attempted to test it on a jan 2015 version, which predates a speculated cause, but the mod api is different/incompatible.

##### OS / Hardware

Operating system: Windows 10 x64
CPU: i7-6700k

##### Summary
Rivers in the v7 mapgen overwrite the voxelmanip buffer used by lua. In my situation this is removing nodes lua generates (replacing them with air), but it could be a buffer underrun error so might behave differently on different versions.

##### Steps to reproduce

To visualise it, I've used [a mod which draws a box from minp to maxp with the ceiling and floor partially filled by lines running in opposing directions](https://github.com/minetest/minetest/files/2042731/v7riverbug.zip). When run with a v7 mapgen, this is what happens to the box when you are over rivers:
![screenshot_20180528_002334](https://user-images.githubusercontent.com/6390507/40587341-55bee8c8-6211-11e8-8949-37de28637892.jpg)
![screenshot_20180528_002448](https://user-images.githubusercontent.com/6390507/40587342-56d9e618-6211-11e8-8256-c3a5e5d84a99.jpg)

Both the top-most and bottom-most layer of voxels are affected, but not the ones in the middle - note the pillars in the screenshots, only their top and bottom voxels are overwritten with air.

##### Speculated cause

Might this have something to do with the overgeneration code?

In line [587](https://github.com/minetest/minetest/blob/master/src/mapgen/mapgen_v7.cpp#L587), y is given an "overgeneration" range from (min.Y - 1) to (max.Y + 1), and that out-of-range value is converted to index vi on the following line, then data is assigned to that memory location on line 603.

```
	for (s16 z = node_min.Z; z <= node_max.Z; z++)
	for (s16 y = node_min.Y - 1; y <= node_max.Y + 1; y++) {
		u32 vi = vm->m_area.index(node_min.X, y, z);
		for (s16 x = node_min.X; x <= node_max.X; x++, index++, vi++) {
			⁝
			vm->m_data[vi] = (y > water_level) ? n_air : n_water;
```

I think when vm->m_area.index(node_min.X, y, z) calculates an index, it may be returning a negative value for the first run of x when y is -1, since [it doesn't do any bounds checking](https://github.com/minetest/minetest/blob/master/src/voxel.h#L268), and z starts at node_min.Z

For values of z above MinEdge.Z, the negative y index will stay within the buffer, so I'm not 100% certain this is the cause of the buffer being overwritten by the rivers, but line 603 is writing *air* to index vi, based on river noise, which is why I'm suspicious.

I don't have minetest set up to compile here so I can't provide a fix/pull-request or debug it properly. I also don't fully understand the overgeneration implementation - I see [the size of the noise buffer was increased in the y axis by 2](https://github.com/minetest/minetest/commit/d6638b4300b091275fa25c43eaee42cd6d13effe#diff-0614e0ef11aed63d542cf655af679289R81), but vi is being used here to index the voxelmanip data, and I didn't see whether  node_min.Y or node_min.Z was ever incremented to allow (node_min.Y - 1) to stay within that buffer.

**Comment by paramat** [comment] 2018-05-28 01:52
Nice visualistion. This is certainly caused by vertical overgeneration messing stuff up at mapchunk borders.
The voxelmanip actually extends 16 nodes beyond the mapchunk borders on all sides so this is not due to node_min.y - 1 or node_max.y +1 being out of bounds.
You may find that which layer of your test nodes are removed depends on whether you generate the mapchunks downwards or upwards.
Thanks for the detail i'll attend to this.

**Comment by Treer** [comment] 2018-05-28 03:42
> You may find that which layer of your test nodes are removed depends on whether you generate the mapchunks downwards or upwards.

Yes! I had noticed that it changes depending on whether you started above or below it.

**Comment by Treer** [comment] 2018-05-29 02:29
> The alternative is to move river canyon generation into the main terrain generation loop so that the existing check for 'ignore' solves this issue.

I like the sound of that as it solves the problem fully and without needing extra checks, but I realise this is quite a small edge-case problem (literally!) and there will be other considerations/misgivings you have with this path.

I think the default for nodes is 'is_ground_content = true', and in my particular case many of the blocks I use are ground blocks, but having fewer blocks erased would still be better.

Does it work if you overgenerate just the noise, and set the voxels from that, rather than overgenerate both the voxels and the noise?

Is there a way to have a lua function called after the mapgen terrain generation loop has done its thing? I assume the problem happens when generation of a neighbouring voxel space starts, so the answer would be no?

**Comment by paramat** [comment] 2018-05-29 15:36
Yes moving it into one loop may improve performance a little too, but 'is_ground_content = false' is required for any nodes placed in 'on_generated'.
River excavation must overgenerate because terrain generation does.
> Is the problem happening because generation of a neighbouring voxel space starts, so the answer would be no?

Correct.

**Comment by paramat** [comment] 2018-05-29 19:41
I think i prefer the simpler solution, at least for now, we would only need to check 'is_ground_content' for the 2 overgenerated node layers.

**Comment by paramat** [comment] 2018-05-29 21:22
PR #7388

**Comment by paramat** [comment] 2018-05-30 02:10
While testing my PR i noticed that the mod clay (being 'ground content') is still being griefed occasionally, not by rivers but by cave overgeneration.

**Closed** 2018-05-31 02:06 UTC
Labels: @ Mapgen, @ Script API, Bug

**Comment by paramat** [comment] 2018-05-31 02:08
#7388 merged.

**Comment by raymoo** [comment] 2018-09-08 15:55
Port to 0.4.*?

**Comment by CoderForTheBetter** [comment] 2018-09-09 01:26
A port to 0.4.* would be nice: [see this forum thread](https://forum.minetest.net/viewtopic.php?f=6&t=20766)

**Comment by paramat** [comment] 2018-09-09 03:27
Laballed for 0.4.18.
