### ISSUE TITLE
HUD dinamically changing

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#9844] opened 2020-05-10 15:44 UTC
## Problem

It's not possible to create an HUD and modify its parameters in the same step (although the HUD table can be edited before assigning it to the player).

For instance, if I want to create several HUDs at the same time and displaying them in a specific layout according to their total number (which can vary), I simply can't because the engine will only take the first input. As a workaround I had to create a coroutine with a time gap of 0.1, but.. I'd like to make them appear (and move them) all together

## Solutions

Make it possible (?)

**Comment by rubenwardy** [comment] 2020-05-10 15:51
Duplicate of #9024

**Closed by rubenwardy** 2020-05-10 15:51 UTC
Labels: Bug

**Comment by rubenwardy** [comment] 2020-05-10 15:52
This should be fixed by #9611, which will be in 5.3.0

**Comment by sfan5** [comment] 2020-05-10 17:51
Much closer duplicate of #2862.

**Comment by rubenwardy** [comment] 2020-05-10 18:14
ahh right
