### ISSUE TITLE
we Should add in proper Dimetions support why? 

### ISSUE THREAD

**Issue by Wbjitscool** [minetest/minetest#14925] opened 2024-08-05 11:13 UTC
### Problem

atm there is no support for other diemtions as far as i can tell

### Solutions

not sure what to put in here

### Alternatives

Well so other games can have the potential to add in their own type of dimetion's also I would like to see Minetest in the future have it's own demention at some point when ever you feel ready to add one doesn't have to be straight away but may be at some point in the future and if it dose I am curious what it will look like

### Additional context

I think it would be cool to see other different looking demotions

**Comment by rubenwardy** [comment] 2024-08-05 11:18
Duplicate of #4428

**Closed by rubenwardy** 2024-08-05 11:18 UTC
Labels: Feature request
