### ISSUE TITLE
Unit test fails

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#2231] opened 2015-01-29 17:27 UTC
```
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
18:23:46: ERROR[main]: run_tests(): 1 / 13 tests failed.
18:23:46: ERROR[main]: run_tests() aborting.
```

OS: WIndows XP SP 3
MT: Current HEAD

**Comment by C1ffisme** [comment] 2015-01-29 20:19
What exactly were you trying to do? Could you give a more detailed description of how you produced this bug?

**Comment by Zeno-** [comment] 2015-01-30 05:29
Unless something has changed, I would say it's these that are failing: https://github.com/minetest/minetest/blob/master/src/test.cpp#L281

Are you able to confirm this Krock?

**Comment by Zeno-** [comment] 2015-01-30 05:32
Duplicate of https://github.com/minetest/minetest/issues/1998

**Comment by SmallJoker** [comment] 2015-01-30 17:47
I can not confirm your thoughts but it could be possible.

Complete log: (Yes, it looks like a duplicate of #1998 )
```
18:38:52: INFO[main]: logfile = debug.txt
18:38:52: VERBOSE[main]: httpfetch_init: parallel_limit=8
18:38:52: INFO[main]: Message locale is now set to: LC_COLLATE=German_Switzerland.1252;LC_CTYPE=German_Switzerland.1252;LC_MONETARY=German_Switzerland.1252;LC_NUMERIC=C;LC_TIME=German_Switzerland.1252
18:38:52: VERBOSE[main]: ItemDefManager: registering "default:stone"
18:38:52: VERBOSE[main]: NodeDefManager: registering content id "0": name="default:stone"
18:38:52: VERBOSE[main]: ItemDefManager: registering "default:dirt_with_grass"
18:38:52: VERBOSE[main]: NodeDefManager: registering content id "1": name="default:dirt_with_grass"
18:38:52: VERBOSE[main]: ItemDefManager: registering "default:torch"
18:38:52: VERBOSE[main]: NodeDefManager: registering content id "2": name="default:torch"
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
Test (starts == true) failed: UASSERT
18:38:53: ERROR[main]: run_tests(): 1 / 13 tests failed.
18:38:53: ERROR[main]: run_tests() aborting.
```
https://github.com/minetest/minetest/blob/master/src/test.cpp#L2181 is useless in this case because log level is set to error only.

**Comment by Zeno-** [comment] 2015-01-30 18:01
The main problem, as I see it, is that the unit test is so complicated that the unit test needs a unit test

**Comment by paramat** [comment] 2016-03-31 00:15
Folded #1998 into this.

**Comment by rubenwardy** [comment] 2016-03-31 00:51
The guidelines say to keep the oldest one.
But oh well, you still need to remove the "duplicate" label.

**Comment by kaeza** [comment] 2016-04-01 07:59
As of c8ff11b (current `HEAD`; successful tests omitted for brevity):

```
Test assertion failed: readF1000(is) == 53.534f
    at .../minetest/src/unittest/test_serialization.cpp:305
[FAIL] testStreamRead - 0ms
Test assertion failed: buf.getF1000() == 53.534f
    at .../minetest/src/unittest/test_serialization.cpp:472
[FAIL] testBufReader - 0ms
Test assertion failed: starts == true
    at .../minetest/src/unittest/test_filepath.cpp:142
[FAIL] testPathStartsWith - 0ms
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Unit Test Results: FAILED
    2 / 21 failed modules (3 / 78 failed individual tests).
    Testing took 6203ms total.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```
Full log [here](https://gist.github.com/kaeza/acb8f3b5fef654c07c2905231ec8490d).

**Comment by paramat** [comment] 2016-04-01 17:59
The guidelines make sense if the older thread has more discussion, which is usually the case, however sometimes the newer thread has more discussion so it makes sense to close the older one.

**Comment by SmallJoker** [comment] 2017-05-20 13:52
Updated unittest output:
```
[PASS] testVectorStore - 8ms
[PASS] testSpatialStore - 0ms
[PASS] testSerialization - 0ms
======== Module TestAreaStore passed (0 failures / 3 tests) - 13ms
======== Testing module TestCollision
[PASS] testAxisAlignedCollision - 1ms
======== Module TestCollision passed (0 failures / 1 tests) - 3ms
======== Testing module TestCompression
[PASS] testRLECompression - 0ms
[PASS] testZlibCompression - 0ms
[PASS] testZlibLargeData - 5ms
======== Module TestCompression passed (0 failures / 3 tests) - 11ms
======== Testing module TestConnection
[PASS] testHelpers - 0ms
[PASS] testConnectSendReceive - 5208ms
======== Module TestConnection passed (0 failures / 2 tests) - 5212ms
======== Testing module TestFilePath
[PASS] testIsDirDelimiter - 0ms
Test assertion failed: starts == true
    at test_filepath.cpp:142
[FAIL] testPathStartsWith - 4ms
[PASS] testRemoveLastPathComponent - 0ms
[PASS] testRemoveLastPathComponentWithTrailingDelimiter - 0ms
[PASS] testRemoveRelativePathComponent - 0ms
======== Module TestFilePath failed (1 failures / 5 tests) - 17ms
======== Testing module TestInventory
[PASS] testSerializeDeserialize - 0ms
======== Module TestInventory passed (0 failures / 1 tests) - 3ms
======== Testing module TestKeycode
[PASS] testCreateFromString - 0ms
[PASS] testCreateFromSKeyInput - 0ms
[PASS] testCompare - 0ms
======== Module TestKeycode passed (0 failures / 3 tests) - 5ms
======== Testing module TestMapSettingsManager
[PASS] testMapSettingsManager - 9ms
[PASS] testMapMetaSaveLoad - 7ms
[PASS] testMapMetaFailures - 1ms
======== Module TestMapSettingsManager passed (0 failures / 3 tests) - 22ms
======== Testing module TestMapNode
[PASS] testNodeProperties - 0ms
======== Module TestMapNode passed (0 failures / 1 tests) - 2ms
======== Testing module TestNodeDef
[PASS] testContentFeaturesSerialization - 0ms
======== Module TestNodeDef passed (0 failures / 1 tests) - 3ms
======== Testing module TestNodeResolver
[PASS] testNodeResolving - 0ms
[PASS] testPendingResolveCancellation - 0ms
======== Module TestNodeResolver passed (0 failures / 2 tests) - 4ms
======== Testing module TestNoise
[PASS] testNoise2dPoint - 8ms
[PASS] testNoise2dBulk - 0ms
[PASS] testNoise3dPoint - 0ms
[PASS] testNoise3dBulk - 0ms
[PASS] testNoiseInvalidParams - 0ms
======== Module TestNoise passed (0 failures / 5 tests) - 19ms
======== Testing module TestObjDef
[PASS] testHandles - 1ms
[PASS] testAddGetSetClear - 0ms
======== Module TestObjDef passed (0 failures / 2 tests) - 4ms
======== Testing module TestPlayer
======== Module TestPlayer passed (0 failures / 0 tests) - 0ms
======== Testing module TestProfiler
[PASS] testProfilerAverage - 5ms
======== Module TestProfiler passed (0 failures / 1 tests) - 8ms
======== Testing module TestRandom
[PASS] testPseudoRandom - 0ms
[PASS] testPseudoRandomRange - 2ms
[PASS] testPcgRandom - 0ms
[PASS] testPcgRandomRange - 4ms
[PASS] testPcgRandomBytes - 0ms
[PASS] testPcgRandomNormalDist - 72ms
======== Module TestRandom passed (0 failures / 6 tests) - 88ms
======== Testing module TestSchematic
[PASS] testMtsSerializeDeserialize - 1ms
[PASS] testLuaTableSerialize - 0ms
[PASS] testFileSerializeDeserialize - 13ms
======== Module TestSchematic passed (0 failures / 3 tests) - 21ms
======== Testing module TestSerialization
[PASS] testSerializeString - 0ms
[PASS] testDeSerializeString - 0ms
[PASS] testSerializeWideString - 0ms
[PASS] testDeSerializeWideString - 0ms
[PASS] testSerializeLongString - 0ms
[PASS] testDeSerializeLongString - 0ms
[PASS] testSerializeJsonString - 1ms
[PASS] testSerializeHex - 0ms
Test assertion failed: readF1000(is) == 53.534f
    at test_serialization.cpp:305
[FAIL] testStreamRead - 5ms
Test assertion failed: !memcmp(&data[0], test_serialized_data, data.size())
    at test_serialization.cpp:355
[FAIL] testStreamWrite - 9ms
Test assertion failed: !memcmp(&buf[0], test_serialized_data, sizeof(test_serialized_data))
    at test_serialization.cpp:415
[FAIL] testVecPut - 8ms
[PASS] testStringLengthLimits - 55ms
Test assertion failed: buf.getF1000() == 53.534f
    at test_serialization.cpp:472
[FAIL] testBufReader - 6ms
======== Module TestSerialization failed (4 failures / 13 tests) - 115ms
======== Testing module TestSettings
Test assertion failed: os.str() == config_text_after
    at test_settings.cpp:202
[FAIL] testAllSettings - 6ms
======== Module TestSettings failed (1 failures / 1 tests) - 8ms
======== Testing module TestSocket
[PASS] testIPv4Socket - 52ms
[PASS] testIPv6Socket - 52ms
======== Module TestSocket passed (0 failures / 2 tests) - 107ms
======== Testing module TestThreading
[PASS] testStartStopWait - 381ms
[PASS] testThreadKill - 404ms
[PASS] testAtomicSemaphoreThread - 2066ms
======== Module TestThreading passed (0 failures / 3 tests) - 2858ms
======== Testing module TestUtilities
[PASS] testAngleWrapAround - 3ms
[PASS] testLowercase - 0ms
[PASS] testTrim - 0ms
[PASS] testIsYes - 0ms
[PASS] testRemoveStringEnd - 0ms
[PASS] testUrlEncode - 0ms
[PASS] testUrlDecode - 0ms
[PASS] testPadString - 0ms
[PASS] testStartsWith - 0ms
[PASS] testStrEqual - 0ms
[PASS] testStringTrim - 0ms
[PASS] testStrToIntConversion - 0ms
[PASS] testStringReplace - 0ms
[PASS] testStringAllowed - 0ms
[PASS] testAsciiPrintableHelper - 0ms
[PASS] testUTF8 - 0ms
[PASS] testRemoveEscapes - 0ms
[PASS] testWrapRows - 0ms
[PASS] testIsNumber - 0ms
[PASS] testIsPowerOfTwo - 0ms
[PASS] testMyround - 0ms
======== Module TestUtilities passed (0 failures / 21 tests) - 38ms
======== Testing module TestVoxelAlgorithms
[PASS] testPropogateSunlight - 0ms
[PASS] testClearLightAndCollectSources - 0ms
[PASS] testVoxelLineIterator - 1ms
======== Module TestVoxelAlgorithms passed (0 failures / 3 tests) - 8ms
======== Testing module TestVoxelManipulator
[PASS] testVoxelArea - 0ms
[PASS] testVoxelManipulator - 1ms
======== Module TestVoxelManipulator passed (0 failures / 2 tests) - 3ms
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Unit Test Results: FAILED
    3 / 24 failed modules (6 / 87 failed individual tests).
    Testing took 8737ms total.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by rubenwardy** [comment] 2017-08-26 02:36
travis reports all is okay, is this actually a problem?

**Comment by nerzhul** [comment] 2017-08-26 06:13
2 years after, no :)

**Closed by nerzhul** 2017-08-26 06:13 UTC
Labels: Bug, Windows
