### ISSUE TITLE
Jumping in 5.3.0 feels different than previous versions

### ISSUE THREAD

**Issue by v-rob** [minetest/minetest#10136] opened 2020-07-02 00:28 UTC
##### Minetest version
```
5.3.0 release candidate 2 (e99415e0c5ae4a89907424d0f5f9f48ab94efbfa)
```

##### OS / Hardware
Operating system: Windows 10

##### Summary
Try jumping up a steep slope around 45 degrees by holding the jump button.  In 5.2.0 and below, jumping up the slope is faster as the player kind of jumps off the edge of the node.  In 5.3.0, if you jump up the same slope, the player does not jump off the edge of the node and has to squarely land before jumping again.  Consequently, jumping is much slower.  It's easy to tell if you try it yourself, but harder to describe.

This is also easily noticeable if you aim the mouse downwards and built a tower with nodes while constantly holding the jump button.  Much slower.

I would consider this a bug because some specifically-timed jumping things, e.g. an Inside the Box thing where you have to run fast up a slope before the door closes, will not work due to the slower jumping.  Plus, it just _feels_ wrongs when you're used to moving faster.

**Comment by appgurueu** [comment] 2020-07-02 11:39
@TheTermos could this possibly be related to the collision detection changes? #9327 and #9343 - I could imagine false positive collisions leading to "faster" jumping as you could jump before actually "touching ground"...

**Comment by sfan5** [comment] 2020-07-02 12:00
Yes, it'll almost surely be those changes. The question is how severe this is and if (and how) it needs to be fixed.

**Comment by TheTermos** [comment] 2020-07-02 14:03
I wouldn't be so sure, this:

> In 5.3.0, if you jump up the same slope, the player does not jump off the edge of the node and has to squarely land before jumping again.

doesn't happen in my version with #9764 merged (#9327 and #9343 don't apply), don't know exact commit but it was downloaded on 200518.
However this does seem to happen sometimes based on timing in another version I have - 80d9e9c
Also it seems to work in 5.1.1 similar as in 80d9e9c.
Also, if it was always like that since #9764 was merged, then #9980 couldn't have happened.

Anyway, this is another 'bug gone feature' nonsense, are we really discussing this?

**Comment by hecktest** [comment] 2020-07-02 16:02
The stair glide thing is definitely much easier to pull off in 5.2 than it is in 5.3. You can still get one going in 5.3, but it's much harder to start and keep it up.

**Comment by v-rob** [comment] 2020-07-02 20:01
I'm not saying that the old behaviour should be preserved (I would prefer improvement of the code than holding on to legacy behaviour), but it has the _possibility_ to mess things up, and so I thought it deserved an issue.  In general, though, the old behaviour seems preferable.  Have you ever tried to escape someone trying to kill you in Minetest?  Speed is of the essence, and this new behaviour could quite easily be the difference between life and death.

Also, I don't think that this can be called a "bug gone feature" in that this behaviour can make sense in real life unlike e.g. a sneak ladder.  It is possible (and common if you are moving relatively fast) to skip up the edges of stair steps in real life without planting your foot squarely on the step (even if the step _is_ a yard large).

I wish I could record a GIF to show what is happening better since my description is inadequate, but I don't know any lightweight trustworthy software for GIFs.  Would be a nice feature to have built-in to Minetest.  Recommendations for something welcome, or perhaps someone else who can reproduce this could make a GIF instead.

**Comment by sfan5** [comment] 2020-07-02 20:55
> I wish I could record a GIF to show what is happening better since my description is inadequate, but I don't know any lightweight trustworthy software for GIFs

Record a video normally in OBS and cut, crop and convert it to a gif using ffmpeg. (or better: leave it as a video file and upload it somewhere else)

**Comment by paramat** [comment] 2020-07-02 22:01
Confirmed in recent 5.3.0-dev 80d9e9c1834fdc78588ffe2842766c0177227786 which is the commit TheTermos experiences the problem in. There are no collision/movement commits since then so i assume this behaviour is in latest master too.
Just build a 45 degree slope of full nodes and hold forward and jump.

This is very unfortunate and i think needs attention before release in case it can be altered. But, collision and movement code are difficult, this could take a long time or even be impossible to fix alongside recent collsion changes.
But, i agree with a 'blocker' label for now due to the importance, we could always remvoe the label later.

I am surprised this was not caught in testing (by PR author or reviewers), as a rapid and fluid climbing of a 45 degree slope of full nodes is a much liked feature of MT, and something celeron55 is rightly rather protective of and has insisted must be preserved. It is something that should always be tested (i should have tested the PRs, sorry).

The long time previous behaviour when climbing a 45 degree slope of full nodes by holding forward and jump was a rapid ascent composed of jumping towards the next ledge, catching it and immediately jumping again, at roughly 4 steps per second. The motion of the player is almost a straight diagonal trajectory.

Now in recent master, the player moves vertically upwards, then horizontally forwards along the top of the node. The climb rate is roughly halved.
The player seems to 'stick' to the slope instead of actually jumping, following a zig-zag trajectory. It feels awkward and slow compared to previous behaviour. Although in isolation, not unbearable.

This will be very unpopular, especially considering MT's vertical height and the long full node staircases used.
> Anyway, this is another 'bug gone feature' nonsense

That is an odd thing to write. Do you mean that long-term MT slope climbing behaviour was a 'bug' in your opinion? If so, that is clearly untrue, it was rapid, fluid, agile, pleasant and much appreciated.

**Comment by sfan5** [comment] 2020-07-02 22:51
> and something celeron55 is rightly rather protective of and has insisted should be preserved

I don't disagree that the mechanism is worth keeping, but where/when has he said that?

> The long time previous behaviour when climbing a 45 degree slope of full nodes by [...]

Here's an example of the fast-climbing that is nearly impossible(?) in 5.3.0-dev:
https://0x0.st/iyX8.mp4

Perhaps relaxing the conditions for `touching_ground` can reintroduce this without totally breaking everything else.

**Comment by hecktest** [comment] 2020-07-03 05:46
On the other hand, this could make people actually start using stair nodes in their mines, making all the stupid cobble somewhat more useful.

**Comment by TheTermos** [comment] 2020-07-03 13:31
> Perhaps relaxing the conditions for `touching_ground` can reintroduce this without totally breaking everything else.

No, the practice of trying to solve small issues affecting specific objects by tampering with general mechanics that are not logically related to them is breakage itself. It's for the most part responsible for the sorry state the code is currently in, it makes the code illogical, outcomes of slightest changes to the code unpredictable and probably this is the most important reason why you guys are scared crapless of merging even one liners.

This bugfeature is related to localplayer only, and localplayer.cpp happens to be all about preserving bugs and being broken, so why don't you just continue breaking that?

By the way, I think I might have found out why in my local version with #9764 fastclimbing is still possible, it's probably because I've implemented this: https://github.com/minetest/minetest/pull/9891#issuecomment-634490776 which fixes controls not affecting some moves, therefore fixing soundfart for good, probably this thing and other problems, you need this anyway because current solution is wrong, so why not just do that?

**Comment by sfan5** [comment] 2020-07-03 15:27
That works perfectly, I've created a PR: #10145

(And for the record, I know that changing `touching_ground` is a last resort workaround and if it had to be done it should only apply to localplayer.)

**Comment by TheTermos** [comment] 2020-07-03 18:39
Ok, you mentioned relaxing conditions for touching_ground and the only place to do it that comes to my mind is collision.cpp, but maybe you had something else in mind.

Anyway, what needs to be done long term: player movement should be handled server side, localplayer.cpp only handle client side prediction, and all the beloved bugfeatures killed with fire.

**Closed** 2020-07-07 17:09 UTC
Labels: Blocker, Bug

**Comment by Lejo1** [comment] 2020-07-13 12:01
Sure this is fixed?

My snap-minetest just updated and I have extactly this strange behavior of slipping up a lot faster!

**Comment by jamesalexanderstevenson** [comment] 2020-07-13 12:27
the original issue is/was fixed but it's hard to tell by the title

thetermos wants to kill beloved things with fire

lol

**Comment by sfan5** [comment] 2020-07-13 12:37
> My snap-minetest just updated and I have extactly this strange behavior of slipping up a lot faster!

The intended behaviour is that fast-climbing is <i>possible</i>.

**Comment by Lejo1** [comment] 2020-07-13 12:39
So this is a wanted behavior?
It's more like flying up a hill

**Comment by sfan5** [comment] 2020-07-13 12:53
Yes, it's how it was in 5.2.0 and before too.

**Comment by LoneWolfHT** [comment] 2020-07-13 14:28
It feels less realistic without the jumpiness

**Comment by TheTermos** [comment] 2020-07-13 17:00
The fix #10145 isn't directly related to fast climbing, it's beneficial in general as it makes player move more consistent and framerate independent. It fixes several symptoms including sound fart, and only accidentally it makes this **glitch** more consistent, only because it makes movement more consistent overall, the root cause it is elsewhere.

I can't help but notice that this escalated quickly, only recently @oilboi offered the fix for this bug (#9980) and ironically, the staff immediately embraced the bug as a beloved feature, even legends are being told how it was always supposed to be like that and the creator himself envisioned it in the beginning.
Truth is this glitch couldn't even be performed consistently as recently as 5.1.1.

I also can't help but notice that my simple one liner fix was considered potentially dangerous until it turned out it helps preserve a bug, then it got merged in no time couple of days before the stable release. 

Sorry for rambling, but I'm trying to make it clear that the staff's eagerness to protect bugs has been noted.
Again.

**Comment by LoneWolfHT** [comment] 2020-07-13 17:13
What would have to be done to make these 'protected' bugs a feature?

**Comment by sfan5** [comment] 2020-07-13 17:21
> Truth is this glitch couldn't even be performed consistently as recently as 5.1.1.

Looks pretty consistent to me: https://0x0.st/itGd.mp4

**Comment by TheTermos** [comment] 2020-07-13 20:09
> What would have to be done to make these 'protected' bugs a feature?

Maybe drop the engine act?
This kind of nonsense has no place in an engine, but if you're making say, a community driven game service then anything goes.

> Looks pretty consistent to me: https://0x0.st/itGd.mp4

Does it? I can clearly see a few stops along the way. Also don't forget the success rate depends on fps, and framerate in that clip is pretty decent. 
5.1.1 is anything but consistent on my end, sometimes it goes without a hitch several times in a row, other times I can't even start.

**Comment by paramat** [comment] 2020-07-13 22:08
> only recently @oilboi offered the fix for this bug (#9980) and ironically, the staff immediately embraced the bug as a beloved feature, even legends are being told how it was always supposed to be like that and the creator himself envisioned it in the beginning.

The rapid climbing of full node stairs may technically be a 'bug' as in a code error. However, the resulting behaviour was obviously judged by celeron55 at the time to be the correct and desirable behaviour, which is why the code was accepted that way at the time and why the behaviour remained that way for the next 9 years.

Whether it is a code error or not, it does not change the fact it is the intentional, desirable and long term MT behaviour, which players are used to and some games and worlds might depend on, and therefore should probably be preserved instead of thrown away according to your own personal preferences as someone new to MT.
> Truth is this glitch couldn't even be performed consistently as recently as 5.1.1.

Does not matter, what matters is that rapid full node stair climbing was consistent for the 8 or so years before 5.1.1.
> I also can't help but notice that my simple one liner fix was considered potentially dangerous until it turned out it helps preserve a bug, then it got merged in no time couple of days before the stable release.
Sorry for rambling, but I'm trying to make it clear that the staff's eagerness to protect bugs has been noted.
Again.

Your post has cheap attempts at misrepresenting the situation and demonising the core devs through usage of the 'bug' word.
It was merged because it preserved an intended, desirable long term and sometimes necessary behaviour, and that was what we were protecting.

**Comment by rubenwardy** [comment] 2020-07-13 22:20
I wish you'd stop talking for celeron55 without any sources whatsoever

**Comment by Lejo1** [comment] 2020-07-14 06:45
> That does not matter, what matters is that rapid full node stair climbing was consistent for the 8 or so years before 5.1.1.

Sure?
For me there is a clear change since 5.3.0! Before it seemed pretty realistic.
Now you barely fly up the hills and do no stops on each block

**Comment by LoneWolfHT** [comment] 2020-10-22 15:26
Just popping in to say I'm not really liking the new jumping behavior either. It's too consistent and jumping feels really floaty.
If there's no other way to fix this then I'll go with the slow slope ascension behavior. I feel like there should be a better way to implement this though.

**Comment by rubenwardy** [comment] 2020-10-22 15:31
I'm not happy with the current movement physics. New move should be free to be tweaked and changed to be the best it can be

**Comment by paramat** [comment] 2020-10-22 21:48
> New move should be free to be tweaked and changed to be the best it can be

Surely it is? Only 'old move' is restrained by having to preserve sneak-jump behaviour.

**Comment by LoneWolfHT** [comment] 2020-10-22 22:10
> > New move should be free to be tweaked and changed to be the best it can be
> 
> Surely it is? Only 'old move' is restrained by having to preserve sneak-jump behaviour.

I think they mean the ability to control all of the variables in physics calculations?
