### ISSUE TITLE
Potential item duplication bug

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#8311] opened 2019-03-03 21:41 UTC
> Also,there is a serious bug with the creative inventory!!!
> When we take an item from the creative inventory and place it in the player inventory by replacing an item placed present in the player inventory ,then chosen item is placed in that slot(as expected),but the player gets unplaced stack of the placed item with count equal to the stack count of the replaced item.
> 
> This is even true for tools.

![image](https://user-images.githubusercontent.com/2122943/53702258-f56b1780-3dfc-11e9-8bee-c0fc5b9523f1.png)

![image](https://user-images.githubusercontent.com/2122943/53702261-fd2abc00-3dfc-11e9-84a1-bc8757f86968.png)

**Comment by sfan5** [comment] 2019-03-03 21:47
duplicate of #8229
normal checks still apply, so no duplication potential (except in creative of course)

**Closed by sfan5** 2019-03-03 21:47 UTC
Labels: Blocker, High priority, Unconfirmed bug
