### ISSUE TITLE
Allow waypoint HUD elements without distance display

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#8141] opened 2019-01-29 15:05 UTC
I sometimes use waypoint HUDs for labeling things close to the player, where having the distance always included in the display is distracting.  I would like to be able to turn it off on a case-by-case basis when creating a HUD, i.e. have it display only content I provide and not include the distance.

**Comment by jastevenson303** [comment] 2019-01-29 16:24
Great idea!

**Comment by Wuzzy2** [comment] 2020-02-22 01:50
Why shooting this down? This is a fairly reasonable request IMO.

**Comment by LoneWolfHT** [comment] 2020-02-22 05:27
I'd like this. Not all games want to look like they're in dev mode

**Comment by MuhdNurHidayat** [comment] 2020-02-22 05:37
I'd like this as well

**Comment by benrob0329** [comment] 2020-02-22 07:28
Closing reasonable feature requests because there are a lot of open issues doesn't fix the problems causing that many issues to be open to begin with. This is especially annoying because even core-devs make new feature issues/PRs rather than attending to already open issues and requests from modders.

Why close small, useful, entirely within-scope issues like this but leave issues like #36 (which will _never_ happen, it's been 8 years, we've modded around it and argued it to death, it's not happening unless someone makes a miracle and even then it's probably not worth maintaining)?

**Comment by appgurueu** [comment] 2020-02-22 10:34
I'd like also like this.

**Comment by appgurueu** [comment] 2020-02-22 11:28
I have worked on a (very small) PR. Will submit soon.
![Bildschirmfoto von 2020-02-22 12-27-06](https://user-images.githubusercontent.com/34514239/75091538-c3534800-556e-11ea-9a67-0e619342bbf9.png)

**Comment by Wuzzy2** [comment] 2020-02-22 18:51
Conspiracy theory: Paramat intentionally shot this down to provoke a PR. ;-)

**Comment by paramat** [comment] 2020-02-22 20:27
Heh =) I am happy to see this got attention and support from a core dev.

I did not shoot it down, i am neutral on this. It was closed because it had no stated core dev support for a year.

benrob0329, you and non-core-devs do not decide what feature requests are 'reasonable', core devs do, otherwise all feature requests would stay open.
We have to clear out old unsupported feature requests because we have 400-500 of them, roughly half of all issues. The more there are the more difficult it is to manage them and stay aware of them, and the more likely it is that supported requests get buried and forgotten.
The situation is so difficult we have even considered not allowing feature requests at Github and moving them elsewhere, so that issues can be for actual issues.
Managing issues is a big task, you would think different if you had to do it.
So, there are good reasons, the core devs usually know what they are doing.
> Why close small, useful, entirely within-scope issues like this but leave issues like #36

That is supported by core devs (i just added the missing label), this was not.

**Comment by benrob0329** [comment] 2020-02-22 22:45
> benrob0329, you and non-core-devs do not decide what feature requests are 'reasonable', core devs do, otherwise all feature requests would stay open.

Straw-man argument, but ok. Considering the immediate attention once closed, the support of sfan5, and the opening of a PR in but a day's worth of time I'd say this is considered a pretty reasonable feature request :-)

> We have to clear out old unsupported feature requests because we have 400-500 of them, roughly half of all issues. The more there are the more difficult it is to manage them and stay aware of them, and the more likely it is that supported requests get buried and forgotten.

This is not nearly as old as some, and already had some support before the sudden inflow of "hey don't close that!" comments. Simply asking if this had support due to the "yeah that seems reasonable, someone should do that" nature of this issue would have probably helped, although we might not have gotten a PR out of it so maybe closing it was for the best.

> The situation is so difficult we have even considered not allowing feature requests at Github and moving them elsewhere, so that issues can be for actual issues.

That's not entirely unreasonable, but the line between brand new features, logical extensions to already existing ones, and unexpected behavior can be fuzzy and might lead to some controversy.

> That is supported by core devs (i just added the missing label), this was not.

It's also been open for almost a decade and has very little chance of actually being implemented, but I guess it does have support from a core dev.

**Comment by paramat** [comment] 2020-02-23 00:17
> Closing reasonable feature requests because there are a lot of open issues doesn't fix the problems causing that many issues to be open to begin with.

This is a misrepresentation of what is happening, if there is a genuine problem, the corresponding issue is never closed.
Feature requests are, by definition, usually optional and non-essential, so usually do not have related problems. If one goes unsupported for a very long time then it is either unsuitable or unnecessary, so there is no related problem. So keeping it open does not solve any problems.

In case i am portrayed as the 'bad guy': I have spent more time and effort then any core dev trying to get attention to old feature requests. I used to sort through all of them, bump old ones, mark them with special labels, ask regularly on IRC for core devs to go through the list the label generates.

Unfortunately it did not seem to make much difference, i think the other core devs just have very little time and seem to ignore most feature requests. I am not really complaining because this is understandable and random feature requests are lower priority then most other aspects of development. I often wonder if i should ignore most of them too, having opinions makes onesself unpopular =)

Perhaps we should remove them from Github, it is a bit much that anyone can post any random desire and we are expected to attend to and manage these and the clutter they generate.
> Considering the immediate attention once closed, the support of sfan5, and the opening of a PR in but a day's worth of time I'd say this is considered a pretty reasonable feature request

The non-core dev attention and PR are irrelevant to desirability though, whether it is desirable is decided by core devs.
> This is not nearly as old as some, and already had some support 

There is no unsupported feature request more than a year old still open. Supported ones are a different thing and are never closed unless disapproved by several core devs.
The 'support' you mention was non core dev support, so does not count in terms of official desirability.

**Comment by Wuzzy2** [comment] 2020-02-23 01:49
Except that **this particular feature request** is, in fact, reasonable (reason: The waypoint feature is very annoying since it always displays a number, if you want it, or not), non-disruptive, lightweight, has strong player/modder support AND core dev support AND a now even an actual PR attached to it.

This, and ONLY because of this I complained about the closing. I don't write complaints of this type lightly. I did not write it because I think Minetest should have an “anything goes” approach.

**Comment by benrob0329** [comment] 2020-02-24 03:59
> This is a misrepresentation of what is happening, if there is a genuine problem, the corresponding issue is never closed.

This is a misrepresentation of what I said, if I had mentioned bug reports you would be correct.

> Feature requests are, by definition, usually optional and non-essential, so usually do not have related problems.

This has nothing to do with what I said.

> If one goes unsupported for a very long time then it is either unsuitable or unnecessary, so there is no related problem. So keeping it open does not solve any problems.

Closing it does not "solve" any problems either, fixing bugs does :-)

> In case i am portrayed as the 'bad guy': I have spent more time and effort then any core dev trying to get attention to old feature requests. I used to sort through all of them, bump old ones, mark them with special labels, ask regularly on IRC for core devs to go through the list the label generates.

I'm not trying to portray you as the "bad guy", I just asked a question about why this was closed but other issues which are far more outlandish are not.

> Unfortunately it did not seem to make much difference, i think the other core devs just have very little time and seem to ignore most feature requests. I am not really complaining because this is understandable and random feature requests are lower priority then most other aspects of development. I often wonder if i should ignore most of them too.

I would appreciate a time of Minetest's development where the focus is solely on fixing reported bugs, even making some breaking changes if needed.

> The non-core dev attention and PR are irrelevant to official desirability though, whether it is desirable is decided by core devs.

So the attention of the mod and game-dev parts of the community mean nothing? The people who make content for the engine have no weight with their opinion?

**Closed** 2020-04-11 21:09 UTC
Labels: @ Script API, Feature request, Supported by core dev
