### ISSUE TITLE
liquids don't flow if another liquid is there

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#3263] opened 2015-10-17 07:56 UTC
When l build this construction, the river water doesn't flow out of it. The bug may not appear if the construction is rotated.

![screenshot_20151017_094634](https://cloud.githubusercontent.com/assets/3192173/10557640/908b27fc-74b4-11e5-8fac-3f9e04614070.png)
![screenshot_20151017_094627](https://cloud.githubusercontent.com/assets/3192173/10557642/be6f2efc-74b4-11e5-8e17-3a0664c6a79a.png)

lt's annoying because my and @VanessaE's mods which change lavacooling don't work correctly:
![screenshot_20151017_093558](https://cloud.githubusercontent.com/assets/3192173/10557650/03184c46-74b5-11e5-8c83-4d6129894aed.png)
the lava even doesn't flow down there if l rejoin

**Comment by est31** [comment] 2015-10-17 17:25
Can reproduce it for south (-Z) direction:
![screenshot_20151017_192215](https://cloud.githubusercontent.com/assets/8872119/10560228/8989314c-7504-11e5-8cf7-1906c1ddabf0.png)
For east (+X), its flows even less:
![screenshot_20151017_192235](https://cloud.githubusercontent.com/assets/8872119/10560231/b0a1ab7e-7504-11e5-9cf7-3db633a7f6a7.png)
It works for the other two directions:
![screenshot_20151017_192513](https://cloud.githubusercontent.com/assets/8872119/10560233/d26df1ea-7504-11e5-89b1-a492bb78da01.png)

**Comment by BlockMen** [comment] 2015-10-18 13:54
Dupe of #2399

**Comment by est31** [comment] 2015-10-19 01:17
Seems to be the case

**Closed by est31** 2015-10-19 01:17 UTC
Labels: bug, duplicate
