### ISSUE TITLE
Signlike drawtype not being lit smoothly across large areas

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#104] opened 2012-06-10 12:26 UTC
When using the signlike drawtype to place objects on the ceiling or walls (in this case, two separate, smoothly-tilable images), any light from sources in the room or from a window is being distributed across those tiles very coarsely.  See this screenshot for an example:

![homedecor mod screenshot showing no smooth light](http://digitalaudioconcepts.com/vanessa/hobbies/minetest/screenshots/homedecor1.png)

(Notice the ceiling "paint")

Code used to produce the ceiling covering:

``` lua
minetest.register_node('homedecor:ceiling_paint', {
    description = "Textured Ceiling Paint",
    drawtype = 'signlike',
    tile_images = { 'homedecor_ceiling_paint.png' },
    inventory_image = 'homedecor_ceiling_paint_roller.png',
    wield_image = 'homedecor_ceiling_paint_roller.png',
    sunlight_propagates = true,
    paramtype = 'light',
    walkable = false,
    groups = { snappy = 3 },
    sounds = default.node_sound_leaves_defaults(),
        selection_box = {
            type = "wallmounted",
                         --wall_top = <default>
                         --wall_bottom = <default>
                         --wall_side = <default>
                        },
})
```

**Comment by nerzhul** [comment] 2015-02-18 16:28
is this bug already present ?

**Comment by VanessaE** [comment] 2015-02-18 18:34
Still present in current git, affects some other drawtypes actually (really anything that isn't a normal cube).  Signlike was just the first one I noticed at the time this was filed.

**Comment by Fixer-007** [comment] 2016-02-18 20:54
I can confirm it, still present in git.

**Comment by paramat** [comment] 2016-02-19 08:55
Is this not just the fact certain drawtypes cannot have smooth lighting?

**Comment by stormchaser3000** [comment] 2016-02-20 17:41
paramat: voxelands has smooth lighting on nodeboxes

**Comment by everamzah** [comment] 2016-02-20 19:24
Apparently it's not just nodeboxes but also nodes that are transparent?  I'm trying to get CaveRealm's thin ice texture to be smoothly lit, but it seems that because it is transparent that I can not.

**Comment by Fixer-007** [comment] 2016-04-17 19:49
RBA said in another topic:
>This is not a bug but our lighting system. slabs, stairs, all nodeboxes, plants, rails, meshnodes, etc are using internal light of the node. solids blocks calculate that for all 6 faces. So, the effect is different for them.

>To make stairs for example have same lighting as solid nodes there should be added special drawtype that would use the same method. Code itself doesnt know whats "similar" to full sized node...
IMHO not easily fixeable, but i will think about possible solutions.

**Comment by paramat** [comment] 2016-04-17 20:32
@VanessaE seems not a bug, only cubic nodes have smooth lighting, all else uses a single light value for the whole node.

**Comment by PilzAdam** [comment] 2016-04-17 20:35
@paramat don't close this, it can be seen as a feature request to improve the lighting system.

**Comment by Fixer-007** [comment] 2016-08-08 21:51
Objection!

**Comment by paramat** [comment] 2016-11-25 06:30
Seems difficult and intensive. Smooth lighting is easy to calculate on full cubes due to their shape, calculating a consistent smooth lighting on complex nodebox shapes would be much more difficult.

**Comment by paramat** [comment] 2017-01-18 21:55
This is the original issue for lack of smooth lighting on non-cubic nodes, so should be kept open

**Comment by paramat** [comment] 2017-01-18 22:00
![f9f6ba22-dcef-11e6-8f31-501a906f3521](https://cloud.githubusercontent.com/assets/3686677/22084822/7222cee4-ddc9-11e6-9694-9c857efe4ddb.png)

**Comment by numberZero** [comment] 2017-01-21 21:06
[![new smooth lighting](http://imgur.com/SIaOP0Y.png)](http://imgur.com/SIaOP0Y)
https://github.com/numberZero/minetest/tree/dev-light-smooth
(stairs use meshes and my system support only nodeboxes yet)
Of course there are bugs, this is WIP. It even crashes sometimes... (it seems it can’t handle nodes adjacent to an unloaded area).

**Comment by numberZero** [comment] 2017-01-21 22:29
Now works for mesh nodes too:
[![smooth-stair](http://imgur.com/oHBXQg4.png)](http://imgur.com/oHBXQg4)
Note: may impact performance!
Note: crash is not fixed yet

**Comment by Fixer-007** [comment] 2017-01-22 15:46
Please YES

**Comment by numberZero** [comment] 2017-01-22 16:07
I can’t make a PR yet, it crashes( The reason is that in order to render a node it needs to access its surrounding, but it may not be available on the mapblock boundary. Now thinking how to work around that.

**Comment by MarkuBu** [comment] 2017-01-22 16:18
Great job

**Closed** 2017-01-29 02:44 UTC
Labels: @ Client / Audiovisuals, Feature request, Non-trivial

**Comment by paramat** [comment] 2017-01-29 03:21
\0/
