### ISSUE TITLE
Adding to the Lua API (wield animations)

### ISSUE THREAD

**Issue by TheMrAmazing** [minetest/minetest#10333] opened 2020-08-25 21:56 UTC
Hi,

I am working on a way to add wield animations using LUA with something like this:
 
minetest.register_wield_animation("poke", {
	duration = 0.5,
	translation = {
		add_node = {x=0,y=0,z=0},
		add_node = {x=0,y=-10,z=0},
		add_node = {x=-50,y=20,z=50},
		add_node = {x=0,y=-10,z=0},
		add_node = {x=0,y=0,z=0},
		add_index = {duration=1.0,offset=0,length=2},
		add_index = {duration=1.0,offset=2,length=2},
	},
	rotation = {
		add_node = {x=0,y=0,z=0},
		add_node = {x=0,y=0,z=90},
		add_node = {x=0,y=0,z=90},
		add_node = {x=0,y=0,z=90},
		add_node = {x=0,y=0,z=0},
		add_index = {x=1.0,y=0,z=2},
		add_index = {x=1.0,y=2,z=2},
	}
})

I've got it adding wield animations to the game (thanks to some old pull requests), but now I'm trying to figure out how to add functions to the API by tracing the register_tool function and I'm totally lost, is there some documentation on how to do this? 

P.S. Sorry if this is the wrong place to do this, this is the first open source projects I've tried to contribute to, so I don't know what the etiquette is

**Comment by pyrollo** [comment] 2020-08-27 16:47
Information flow from Server side Lua to Client graphics is:
Server Side Lua -> Server Side C++ -> Network -> Client C++ -> Graphics

Server Side Lua to C++ is made in `src/script/lua_api` directory (`l_env.cpp` for most minetest.xxx function, `l_object.cpp` for player:methods), using Lua CAPI (not so simple, you can take example on existing code).

Server C++ to network and network to client C++ are in `src/network`. If you want to do some additions, you have to know a bit about network protocol and serialization (serialize on server side, send as network packet, deserialize on client side).

For the client C++ to graphics, I don't know much.

Hope that helps (not sure).

**Comment by HybridDog** [comment] 2020-08-27 17:58
I think mesh models could be added for the wield visual, so a function which resembles [set_animation](https://github.com/minetest/minetest/blob/b262184acf34896f36b4270aba29546fc5b0e65b/doc/lua_api.txt#L6042) from ObjectRef could then be called for a wield visual.

**Comment by TheMrAmazing** [comment] 2020-09-07 18:38
I got it working! here is the pull request!
https://github.com/minetest/minetest/pull/10375

**Comment by rubenwardy** [comment] 2023-09-27 23:39
duplicate of #2811

**Closed by rubenwardy** 2023-09-27 23:39 UTC
Labels: @ Script API, Feature request
