### ISSUE TITLE
Dropped items have a lot of faces

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6720] opened 2017-11-30 19:23 UTC
I accidentally stepped into a dropped egg and was surprised that there are so many faces inside. Is this on purpose? Lots of dropped items may cause performance issues if all these faces have to be drawn

![screenshot_20171130_155806](https://user-images.githubusercontent.com/16163058/33450504-4a08157c-d60c-11e7-9d6a-6add4f514ff4.png)

**Comment by paramat** [comment] 2017-12-01 02:48
Interesting.

**Comment by MarkuBu** [comment] 2017-12-01 05:12
It looks like pixel size, yes

**Comment by raymoo** [comment] 2017-12-01 06:28
If each pixel gets its own cube then that's amazing.

**Comment by MarkuBu** [comment] 2017-12-01 07:11
I assume that this is done by irrlicht, right? And I think this is because you need to draw the border in some way. And the simplest way is to create faces for each pixel and draw the texture on it.

**Comment by Calinou** [comment] 2017-12-01 07:43
> If each pixel gets its own cube then that's amazing.

It indeed does, but I think Minecraft also does this – I'm not entirely sure, though.

**Comment by ThomasMonroe314** [comment] 2017-12-01 13:13
looks like this comes as a result of making the 2-d image 3d.

**Comment by MarkuBu** [comment] 2017-12-01 13:27
> looks like this comes as a result of making the 2-d image 3d.

I think so. And I think it is impossible to reduce this much, except to find rectangular areas with the same color and merge the meshes to one box

**Comment by Wuzzy2** [comment] 2017-12-01 16:23
Looks like extrusion gone horribly wrong. :grin:

**Comment by beyondlimits** [comment] 2017-12-01 17:10
> this is because you need to draw the border in some way

Of every pixel?

**Comment by MarkuBu** [comment] 2017-12-01 17:18
You can have items with holes. To reduce the faces you need to analyse the image

**Comment by Wuzzy2** [comment] 2017-12-01 18:36
I don't want to know what happens if you use a 128×128 texture pack. :grin:

**Comment by MarkuBu** [comment] 2017-12-01 19:00
This is an apple with 32x32px
![screenshot_20171201_195514](https://user-images.githubusercontent.com/16163058/33498451-abfa6080-d6d1-11e7-9592-0bcef40bc3e4.png)

And this is a sapling with 64x64px from outside (you can see why all these faces are necessary) and from inside
![screenshot_20171201_195732](https://user-images.githubusercontent.com/16163058/33498542-06f6d112-d6d2-11e7-9354-dcd16d0f24be.png)
![screenshot_20171201_195741](https://user-images.githubusercontent.com/16163058/33498545-087ff7d4-d6d2-11e7-891d-a88293682724.png)

**Comment by paramat** [comment] 2017-12-01 22:22
Our nodeboxes are converted into meshes, but retain inner faces, so i'm not sure there is a solution other than providing a model for every item (which most people cannot do).

**Comment by MarkuBu** [comment] 2017-12-01 22:40
The only idea I have is to only generate faces next to a transparent pixel

**Comment by paramat** [comment] 2017-12-01 23:23
Yeah, some way to convert multiple nodeboxes/pixels into a mesh with no interior faces would be good, not sure how easy. That would also help reduce interior faces of nodebox nodes.

**Comment by beyondlimits** [comment] 2017-12-02 19:19
There are two tasks to be performed:
1. Deciphering the outline shape of a pixelated image to figure out side faces is easy.
2. Triangulating the shape to figure out front faces is harder, but definitely doable.

**Comment by benrob0329** [comment] 2017-12-03 00:24
Perhaps we could get rid of the extruded part, make it a single face (then we could make the animation a bit more lively 😛 . IMO the 1px difference isn't going to make that much of a difference compared to the thousands of extra faces with high resolution textures.

**Comment by beyondlimits** [comment] 2017-12-05 07:14
labels: "Non-trivial", "Not a bug".

Seriously?

**Comment by GreenXenith** [comment] 2017-12-05 10:20
Don't know if this would help anything or if it is even possible;
Set the inside faces to transparent textures.
That way the faces are still there, but nothing is drawn (at least that's my understanding).

**Comment by Calinou** [comment] 2017-12-05 11:04
> Set the inside faces to transparent textures.
That way the faces are still there, but nothing is drawn (at least that's my understanding).

Unfortunately, graphics rendering doesn't work like that; the GPU will still have to draw them, even if they are invisible.

**Comment by ExeterDad** [comment] 2017-12-05 16:09
Do away with extruding every pixel. Use the method Stu uses with armor and stack a couple dozen copies of the same image to mimic the look of extruded without the overhead.
Just throwing that out there.

**Comment by MarkuBu** [comment] 2017-12-05 16:55
It would reduce the amount of faces if merge identical pixels to one shape and extrude this. The shape has to be rectangular. 

But complex items like the sapling on the screenshot above would still have lots of faces, so I go with @ExeterDad cause this will have the same complexity for each item

**Comment by beyondlimits** [comment] 2017-12-05 18:41
What do you mean by "identical pixels". Either there is pixel or not. Zero and one. The colors we see on front, back and side faces is just a texture.

Wait... we're using textures on those faces and not just colors, right?

**Comment by MarkuBu** [comment] 2017-12-05 19:43
I mean the same color. And yes, the models are extruded from textures

**Comment by raymoo** [comment] 2017-12-05 22:39
@MarkuBu You don't need to group pixels by color because during rendering the colors will be sampled from the texture, so it's ok if pixels of different color are part of the same quad.

**Comment by Calinou** [comment] 2017-12-05 23:33
> Do away with extruding every pixel. Use the method Stu uses with armor and stack a couple dozen copies of the same image to mimic the look of extruded without the overhead.

While this seems like a good idea, this doesn't work when you view items from the side, as you will partially see through them; you would need and infinite amount of planes to solve this.

**Comment by benrob0329** [comment] 2017-12-06 01:00
>While this seems like a good idea, this doesn't work when you view items from the side, as you will partially see through them; you would need an infinite amount of planes to solve this.

Its contently rotating, and Stu's models don't seem to have this issue.

**Comment by benrob0329** [comment] 2017-12-08 21:41
Just a note, 64x64 pixels times 6 sides per cube would make about 49,152 polygons **per dropped item**.

**Comment by HybridDog** [comment] 2017-12-10 18:39
duplicate, #3069

**Comment by ThomasMonroe314** [comment] 2017-12-16 13:30
@benrob0329 wrote:
> Just a note, 64x64 pixels times 6 sides per cube would make about 49,152 polygons per dropped item.

which would explain why it gets laggy the more items are on the ground.
Stu's idea would work if the layers were rotated slightly at random angles to fill in some of the space
kind of like a 3-d accordion.

Come to think of it, you would only really need about planes to compensate for the gap

**Comment by ExeterDad** [comment] 2017-12-16 14:19
>Stu's idea would work if the layers were rotated slightly at random angles to fill in some of the space
kind of like a 3-d accordion.

That's actually a very brilliant idea. Seeing through the stack is the issue with Stu's approach unless stacked heavily. A "accordian" would prevent this with much less.
Anyone know of a way to bypass the engine generated drops with lua so I can test with a supplied model? Tinkering with C isn't a option for me.

**Comment by NathanSalapat** [comment] 2017-12-16 14:25
@ExeterDad a very hacky way would be to just define the mesh for the objects and then throw the objects on the ground. Obviously that would only work for the objects you added the mesh too, but for testing purposes it might work.

**Comment by numberZero** [comment] 2017-12-17 18:49
@HybridDog So is this a duplicate of #3069 ? If so, why does this issue remain open instead of the older one?

**Comment by MarkuBu** [comment] 2017-12-17 19:27
I don't think it's a duplicate. It's similar, maybe related, but different problems

**Comment by HybridDog** [comment] 2017-12-17 19:29
I closed the older one because people commented that generating a mesh for each item is very inefficient. I reopened it now.
I don't know why this issue remains open after I mentioned the older one.

>  I don't think it's a duplicate. It's similar, maybe related, but different problems

Actually it should represents the same problem, on the pictures, which are taken offline, I also made screenshots with the camera inside a dropped wield item.

**Comment by numberZero** [comment] 2017-12-17 19:32
@MarkuBu Dropped items and wield items use the same mesh. Actually, entity `__builtin:item` has property `visual = "wielditem"` (see `builtin/game/item_entity.lua`)

**Comment by MarkuBu** [comment] 2017-12-17 19:40
Ah, ok. But the wield mesh is not really a problem for performance, except you have a 1024*1024 px texture pack and play online with 50 players xD

**Comment by HybridDog** [comment] 2017-12-17 20:08
Why does the player count matter?

**Comment by MarkuBu** [comment] 2017-12-17 20:13
You are right. You don't see the wield mesh from other players. Mea culpa

**Comment by paramat** [comment] 2017-12-18 10:28
How about a setting for extruded items to be a single flat face?

**Comment by numberZero** [comment] 2017-12-22 16:04
![screenshot_20171222_185229](https://user-images.githubusercontent.com/7352626/34304289-340de0ae-e74a-11e7-8544-56acad11c090.png)
That is an *apple*, nothing more =)

**Comment by HybridDog** [comment] 2019-11-06 10:01
> […] kind of like a 3-d accordion. […] https://imgur.com/coPafIs

I like this idea. However, if a thin sapling stem is shown from the side, the diagonal planes need a high angle.

> Anyone know of a way to bypass the engine generated drops with lua so I can test with a supplied model? Tinkering with C isn't a option for me.

You could make a 3D model of the accordion with blender and, in minetest, use the mesh drawtype for the dropped object with this model.

> If each pixel gets its own cube then that's amazing.

The cubes may share the same rectangle surfaces, so for a 16x16 texture you only need 2+(16+1)+(16+1) rectangles and not 16*16*4+16+16.

**Comment by rubenwardy** [comment] 2021-01-31 19:19
Duplicate of #3069

**Closed** 2021-01-31 19:18 UTC
Labels: @ Client / Audiovisuals, Not a bug, Performance, Request / Suggestion, Supported by core dev
