### ISSUE TITLE
Problem updating mods and games via the internal MT updater

### ISSUE THREAD

**Issue by Laudrin** [minetest/minetest#14890] opened 2024-07-27 10:31 UTC
### Minetest version

```true
Minetest 5.8.0 (Windows)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Windows 10 Pro 10.0.19045 Build 19045

### CPU model

Intel(R) Core(TM) i3 CPU 530  @ 2.93GHz, 2933 MHz, 2 Kern(e), 4 logische(r) Prozessor(en)

### Summary

From time to time, mods or games will not install in the internal installer (Main Menu at MT startup -> Content -> Online Content), giving an error message:

```
Fehler bei Installation von <mod/game>. Kein gültiges Spiel, Modpack oder Mod gefunden.

(Translation: Error during installation of <mod/game>. No valid game, modpack or mod found.)
```

Usually, I will go back to the game selection menu, select another game (for example Minetest Game), try again and most of the time, the mod will install. For some "stubborn" mods, I used the method described in #14682: Deleting the mod folder and installing the mod again.

Until now it was only a medium hassle, but today MT informed me about 4 available updates to my installed mods and games:
- Minetest Game
- Mobs Redo API
- Etheral NG
- Farming Redo

Formerly, all of them installed fine, today I get the error message listed above without me being able to install them via switching the game and trying again.

Additionally, for _Minetest Game_ I got the error message:

```
Fehler bei Installation von „Minetest Game“: Fehler bei der Installation von invalid als game.

(Translation: Error during installation of ‘Minetest Game’: Error during installation of invalid as game.)
```

Minetest is the last stable release, all other mods and games are up-to-date and the mentioned mods and game were the latest versions (before today).

### Steps to reproduce

As I cannot say exactly which causes this error, I'm not sure if I can provide something to reproduce the problem. If you tell me a way how to do this or which further information I should provide, I will gladly do this!

![Zwischenablage_1234](https://github.com/user-attachments/assets/7d404f34-5f7d-4706-a90e-ef025c118f9c)

**Comment by grorp** [comment] 2024-07-27 11:17
duplicate of https://github.com/minetest/minetest/issues/14518 fixed in 5.9

**Closed** 2024-07-27 11:17 UTC
Labels: Unconfirmed bug, @ Mainmenu, @ Content / PkgMgr
