### ISSUE TITLE
Object-node collision false positives

### ISSUE THREAD

**Issue by TheTermos** [minetest/minetest#9305] opened 2020-01-11 16:27 UTC
##### Minetest version
```
5.1.0
```

##### OS / Hardware
Operating system: Windows 8 Pro
CPU: i5-3230M 2.6Ghz

##### Summary
Physical objects moving near nodes randomly collide (one of velocity vector componets goes 0) even if there's nothing to collide with in the way.

This is most harmful for mob coding, because velocity has to be set every single engine step which makes code unnecessarily complex and results in redundant function calls, and even then movement looks jerky.

This is a speculation because I've  only briefly read collision.cpp, but I suspect the 'dtime allowance' concept which allows a collision to happen on negative dtime.

##### Steps to reproduce
Method 1: An object resting on a flat surface consisting of identical walkable nodes. Set_velocity so that one of horizontal components (x or z) and y are nonzero. Sometimes (roughly 10% of attempts) the object goes straight up instead (the horizontal component goes 0)

Method2: An object resting on a flat surface consisting of identical walkable nodes. Set horizontal velocity, randomly one of horizontal components goes 0 after some distance travelled.

**Comment by SmallJoker** [comment] 2020-01-11 17:41
Duplicate of #9143

Closely related: #6886 and #5330

**Closed by SmallJoker** 2020-01-11 17:41 UTC
Labels: Unconfirmed bug

**Comment by LoneWolfHT** [comment] 2020-01-11 20:50
@SmallJoker those all seem to be for players. This looks like it's only for entities

**Comment by SmallJoker** [comment] 2020-01-11 21:04
@LoneWolfHT If it doesn't work for players, it will never work for entities due to reduced distance check intervals. Same story, different use-case.

**Comment by TheTermos** [comment] 2020-01-13 13:01
@SmallJoker They might be related but I'm not so sure.

First, I were unable to reproduce #9143 
Second, I first noticed the issue back in 0.4.17
Third, #9143 is about players bumping into nodes so there are some collisions involved, my issue is about objects moving parallel to or moving away from nodes, no collisions should be happening whatsoever.

Anyway, how can you tell this is a duplicate if the other issue is labelled unconfirmed? How does this work, will all similar reports be labelled as duplicates of a hard to reproduce issue to create an unconfirmation loop?

This issue is critical, a real showstopper when it comes to entity coding, it deserves more consideration than it got imo.

**Comment by sorcerykid** [comment] 2020-01-13 13:42
Strange, I've never encountered this particular problem while developing my Avatars mod. The main collision bug I've consistently run into is the same as #6886.

In the following video, it can be seen that when entity begins jumping (esp. at 45 degree angles) then X and Z collisions are detected by the engine even though there are no vertical planes:
https://vimeo.com/316098852

**Comment by TheTermos** [comment] 2020-01-13 14:04
@sorcerykid but you have, 2:00 in the video is exactly what I was trying to describe as the first case, forgive me if i wasn't clear enough.

#6886 seems to be marked as a confirmed bug, so it's allrighty then.

**Comment by sorcerykid** [comment] 2020-01-13 14:58
Well, at least the video is very clear confirmation of the bug, so hopefully that issue will remain open and receive attention.

**Comment by TheTermos** [comment] 2020-01-13 17:02
> So it seems that SmallJoker was correct that this is a duplicate.

Yeah I'm good with that as long as the bug is confirmed.
