### ISSUE TITLE
[Android] Items under (hidden) notification bar are non-selectable.

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2735] opened 2015-05-29 04:30 UTC
Like the title says, items on formspecs cannot be pressed, or inventory items moved if they are under the location of the notification bar (hidden because Minetest goes in fullscreen)

However, there is feedback (button is depressed or inventory slot is lighter gray, but the action is not performed.

**Comment by Wayward1** [comment] 2015-05-29 14:23
I can't reproduce this

**Comment by nanepiwo** [comment] 2015-05-29 20:37
This on Android 4.4, Moto X.

**Comment by Zeno-** [comment] 2015-05-31 07:08
I cannot reproduce either.

What is the notification bar?

**Comment by nanepiwo** [comment] 2015-06-01 01:45
The notification bar is the little bar at the top of the screen that shows notifications... I'm sorry I can't explain it better.

**Comment by Wayward1** [comment] 2015-06-01 01:59
The bar at the top of the following screenshot, where "Wayward_One's Fire" is written. It's generally the same for all Android devices.

![screenshot_2015-05-31-21-56-32](https://cloud.githubusercontent.com/assets/8821916/7905107/3f6a7684-07e0-11e5-8be6-585c76908876.png)

**Comment by nanepiwo** [comment] 2015-06-01 20:31
Interestingly, if I double tap there, the formspec closes. If I doubletap elsewhere inside the formsoec, it does not. I have modified my GUI scaling.

**Comment by nanepiwo** [comment] 2015-06-08 04:13
Might be related, the second paragraph (corners non selectable) https://github.com/minetest/minetest/issues/1750

**Comment by sapier** [comment] 2015-12-17 19:47
Nanepiwo doubletapping outside of formspec is supposed to close it.
imho the android bar is not related to this at all for what I remember the minetest text label on upper end of screen may catch input events instead of menu.

**Comment by ShadowNinja** [comment] 2015-12-22 17:35
That's likely the issue: The header text or chat is eating the click.

**Comment by srifqi** [comment] 2018-06-23 16:32
I cannot reproduce either on recent master branch (Samsung Galaxy J7, Android 6.0.1).

**Comment by paramat** [comment] 2018-10-08 04:16
Please can anyone else try to reproduce this bug? If not will close.

**Closed** 2018-11-17 02:12 UTC
Labels: Android, Possible close, Unconfirmed bug
