### ISSUE TITLE
upgrade directly in minetest

### ISSUE THREAD

**Issue by wzy2006** [minetest/minetest#10189] opened 2020-07-17 08:48 UTC
## Problem
When there is a new version of minetest, I always have to download it from GitHub and replace it manually. 

This is a very troublesome thing for an ordinary user.

They also have to keep an eye on minetest's website to learn about the new version.

If they forget, they may miss the new version.

Why not upgrade directly in minetest?

## Solutions

I think minetest can have automatic updates

Through GitHub's API, it can be updated directly in minetest's settings page.

This makes minetest easier to use.

Minetest has few compatibility issues, so it can be updated directly.

**Comment by Andrey2470T** [comment] 2020-07-17 13:30
I`ve just searched out a relevant PR #7629 and like this is alive and upcoming, despite of my issue about the same to my surprising was rejected and closed #8797

**Comment by wzy2006** [comment] 2020-07-17 13:43
I think Minetest of GitHub release should provide Linux and Mac OS "RUN_ IN_ PLACE " compressed package.
Then we can upgrade it without  any compiler and the sources.

**Comment by SmallJoker** [comment] 2020-07-17 16:44
Let's not re-invent the wheel. The package manager do a very good job at dependency handling, version tracking and updating. The only concern is Windows where users still need to download the binaries and install it manually.
:-1: for this request.

**Comment by rubenwardy** [comment] 2020-07-17 17:02
On Windows, the update notifier can be changed to link to an installer as soon as we have one being built. That installer can be used to update Minetest

**Comment by paramat** [comment] 2020-07-17 22:03
Duplicate of rejected #8797

**Closed by paramat** 2020-07-17 22:03 UTC
Labels: Duplicate, Feature request, Won't add
