### ISSUE TITLE
Object crosshair misalignment

### ISSUE THREAD

**Issue by luk3yx** [minetest/minetest#11049] opened 2021-03-11 00:11 UTC
##### Minetest version

```
Minetest 5.5.0-dev-75eb28b95 (Linux)
Using Irrlicht 1.9.0mt0
```

##### OS / Hardware

Operating system: Ubuntu (because of the snap build I think it's 18.04)
CPU: Intel® Core™ i5-4570

GPU model: Intel® HD Graphics 4600
OpenGL version: 3.0

##### Summary

The crosshair appears to be misaligned by about 1px since 5.5.0-dev.

Object crosshair in 5.4.0:
![image](https://user-images.githubusercontent.com/3182651/110715854-e8465600-826a-11eb-8623-e62863974d51.png)

Object crosshair in 5.5.0-dev (the box has been added around the crosshair to make the issue stand out more):
![image](https://user-images.githubusercontent.com/3182651/110715813-d369c280-826a-11eb-96b0-96e440813f55.png)

<details>
<summary>Regular crosshair in 5.5.0-dev (fixed)</summary>

![Screenshot](https://user-images.githubusercontent.com/3182651/110715936-0f9d2300-826b-11eb-8119-cfc065ab7ad6.png)

</details>

##### Steps to reproduce

1. Open Minetest 5.5.0-dev
2. Join a world

**Comment by sfan5** [comment] 2021-03-11 00:32
Just measured a screenshot from 2017, the crosshair is indeed 10px in both directions (for a total span of 21px).
I sure hope Irrlicht 1.9 hasn't changed all line draw methods to be off-by-one because that'd be hell.

**Comment by sfan5** [comment] 2021-03-11 21:07
```cpp
		//! Draws a 2d line.
		/** In theory both start and end will be included in coloring.
		BUG: Currently hardware drivers (d3d/opengl) ignore the last pixel
		(they use the so called "diamond exit rule" for drawing lines).
		[...] */
		virtual void draw2DLine(const core::position2d<s32>& start,
					const core::position2d<s32>& end,
					SColor color=SColor(255,255,255,255)) =0;
```
uh huh

**Comment by sfan5** [comment] 2021-03-12 15:31
fixed by minetest/irrlicht@0335a52479b6bd654482ca9d559433aa95b0e00a

**Comment by luk3yx** [comment] 2021-03-27 01:46
The normal crosshair has been fixed but the object crosshair still doesn't look the way it's supposed to, should I open a new issue?

![Object crosshair](https://user-images.githubusercontent.com/3182651/112706727-1f736300-8f0b-11eb-9b2d-9644d6b30adc.png)

**Comment by sfan5** [comment] 2021-03-27 12:50
Can't reproduce, looks perfect here:
![grafik](https://user-images.githubusercontent.com/1042418/112721279-52b1f400-8f03-11eb-8b20-9ea1629f6e83.png)

**Comment by SmallJoker** [comment] 2021-04-18 14:06
Also shows correctly here.

**Comment by luk3yx** [comment] 2022-01-31 08:24
I have this issue in 5.5.0 stable (with IrrlichtMt 1.9.0mt4) as well.

**Comment by appgurueu** [comment] 2022-05-29 09:51
I believe the fix applied in https://github.com/minetest/irrlicht/commit/0335a52479b6bd654482ca9d559433aa95b0e00a should have been extended to the first pixel as well:

```c++
// Draw non-drawn last & first pixel (search for "diamond exit rule")
glDrawArrays(GL_POINTS, 0, 0);
glDrawArrays(GL_POINTS, 1, 1);
```

Drawing these additional pixels may be problematic due to alpha blending.

Alternatively, shifting the positions by 0.5 to the pixel center should work way better (& hopefully make the point drawing hack obsolete):

> Note that OpenGL coordinate space has no notion of integers, everything is a float and the "centre" of an OpenGL pixel is really at the 0.5,0.5 instead of its top-left corner. (https://stackoverflow.com/a/10041050/7185318)

The "diamond exit rule" is fine and *not equivalent* to "the last pixel is exclusive"; this is only the case if rather than to the center of the last pixel, you actually draw to one of the corners of the last pixel, which is obviously not part of the diamond. This only appears at one of the two pixels (which randomly turned out to be "the end" in the case of the normal crosshair) because that's the pixel with the higher coordinate. Here's a quick visualization:

![Bildschirmfoto von 2022-05-29 11-50-08](https://user-images.githubusercontent.com/34514239/170862110-1581871b-6497-48f9-a755-2b9c2c62c98d.png)

as you can see, the end of the line (the red pixel) is not included because the line only goes up to its top left corner, whereas the line fully crosses the start (the green pixel). Simply drawing the end doesn't fix the issue: It persists for different line directions (if start & end had been swapped).

**Comment by appgurueu** [comment] 2022-05-29 13:47
@luk3yx I can't reproduce the issue (this is hardware-dependant); could you try https://github.com/minetest/irrlicht/pull/110?

**Comment by Zughy** [comment] 2022-06-19 23:50
@luk3yx reminder to test appguru's PR

**Comment by Zughy** [comment] 2022-07-26 23:03
@luk3yx please test appuguru's PR

**Comment by appgurueu** [comment] 2022-07-27 09:32
@Zughy @luk3yx has fixed my PR, I had wrongly assumed the second argument of `gl_DrawArrays` to be an (inclusive) end index, but it is a count.

**Comment by Zughy** [comment] 2022-07-27 11:06
Great! @appgurueu can you please add a "fixes <this issue>" there so it'll be automatically closed once merged?

**Closed** 2022-10-16 21:47 UTC
Labels: Bug, @ Client / Audiovisuals
