### ISSUE TITLE
Clearance based pathfinding

### ISSUE THREAD

**Issue by ElCeejo** [minetest/minetest#10621] opened 2020-11-10 05:52 UTC
Currently the built-in pathfinder only works for finding paths with a max of 1 node clearance. When used for mobs (which is most of the current applications for the feature) this often doesn't work out, because the width of the mob can't fit through small corridors or gets caught on sharp corners.

This could be solved by having adding optional max_width and max_height parameters to minetest.find_path() so the pathfinder can cull path candidates if they are too small.

**Comment by paramat** [comment] 2020-11-10 15:17
Duplicate of parts of #6933 #5479 #2614

**Closed by paramat** 2020-11-10 15:17 UTC
Labels: Duplicate, Feature request
