### ISSUE TITLE
Dynamic texture and nodebox changes

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#2107] opened 2015-01-11 10:44 UTC

**Comment by sapier** [comment] 2015-01-11 10:51
Could you explain a little bit more in detail what you mean ? sounds like two different features?

**Comment by sfan5** [comment] 2015-01-11 13:13
Being able to change the texture and nodebox of just one node in the map from Lua,

**Comment by gravgun** [comment] 2015-01-11 15:13
> Being able to change the texture and nodebox of just one node in the map from Lua.

This would imply a more fine-grained node definition ability, which would be **really** great to have. *Id est*, one wouldn't need to register a whole node type just to have the same node look differently but identical in its functional nature.

But this raises the issue of performance and memory consumption. In the past I also had the idea of writing a tiny VM that could generate vertex info each frame, but eventually dropped it.

**Comment by TriBlade9** [comment] 2015-01-11 15:14
:+1: 
I've wanted to do this for ages, though I think modifying meshnodes/animations might be more preferable.

**Comment by sapier** [comment] 2015-01-11 15:45
If you wanna change a single nodes texture (assuming you wanna be completely free for what texture you wanna change it to) we'd have to add a new parameter to each and every node specifying it's texture.
As you're already free to do things like that for entities which are meant to do dynamic things why make nodes even more like entities?

**Comment by gravgun** [comment] 2015-01-11 16:08
@sapier, entities does not benefit from static AO, and consumes more memory, CPU time and bandwidth than dynamic-ish nodes.

**Comment by sapier** [comment] 2015-01-11 16:54
gravgun entities consume more memory because they have all of those features once we added all of them to nodes those will require same memory.

**Comment by obneq** [comment] 2015-01-17 12:45
dynamic textures are problematic, even when using the entity approach. there is no way to ever delete a texture. this is an issue for mods like signs, displays, paintings and such. Celeron says that the proper way to fix it is to add reference counting to texture usage in the client.

**Comment by gravgun** [comment] 2015-01-22 21:53
@obneq Reference counting is kinda the only way to go indeed. It'd only apply to dynamically-textured nodes/entities to avoid unnecessary overhead (hence requires said nodes/ents definitions to have a "mutable texture" flag), which could imply maintaining a texture `vector` to avoid too frequent texture allocs/frees.

**Comment by thePalindrome** [comment] 2016-02-20 00:14
Since it's been a year, has there been any progress to being able to do dynamic texture/mesh changing for individual blocks?

**Comment by rubenwardy** [comment] 2017-08-26 02:30
duplicate of #36

**Closed by rubenwardy** 2017-08-26 02:30 UTC
Labels: @ Script API, @ Server / Client / Env., Feature request
