### ISSUE TITLE
ClientEnvironment errors

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#2683] opened 2015-05-08 17:17 UTC
The client is up-to-date with current master, the server is 0.4.12-release. This showed while I did nothing particular (just walking over the lands), within 10 min of presence, but not caused a crash.

```
2015-05-08 19:05:42: ERROR[main]: ClientEnvironment::processActiveObjectMessage(): id=7144 type=101 SerializationError in processMessage(), message=""
```

```
2015-05-08 19:10:55: ERROR[main]: ClientEnvironment::processActiveObjectMessage(): id=9371 type=101 SerializationError in processMessage(), message="\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
```

**Comment by est31** [comment] 2015-05-09 17:17
I think this is a dupe of #2636. Networkpacket sent wrong lengths. Reopen if you can reproduce this with a server newer than 2923eafaca929e129ba81504676d3770cff5f681 .

**Closed by est31** 2015-05-09 17:17 UTC

**Comment by kilbith** [comment] 2015-05-09 17:30
So far, never noticed those errors with 0.4.12-dev servers.
