### ISSUE TITLE
The variable 'irrevent' is being used without being initialized

### ISSUE THREAD

**Issue by DustyBagel** [minetest/minetest#14779] opened 2024-06-25 19:39 UTC
### Minetest version

```true
Minetest 5.9.0-dev-fb6ceb266 (Windows)
Default cmake options except luajit is required.
```

### Irrlicht device

SDL

### Operating system and version

Windows 11 home version 23H2

### CPU model

intel i7-9750H

### GPU model

NVIDA GTX 1660 TI (laptop version)

### Summary

After compiling minetest, I get this error as soon as I open it. I am running a debug build.
Microsoft Visual C++ Runtime Library

Debug Error!

...

Run-TIme Check Failure (#)3 - The variable 'irrevent' is being used without being initialized.

### Steps to reproduce

Compile a debug version of minetest the way I did and run it.

**Comment by DustyBagel** [comment] 2024-06-25 19:50
The visual studio debugger seems to think that the issue is coming from line 676 in the ClrrDeviceSDL.cpp file if that helps.

**Comment by appgurueu** [comment] 2024-06-26 11:57
The line in question:

https://github.com/minetest/minetest/blob/fb6ceb2664949372a871b15be853e11a0c3f5aee/irr/src/CIrrDeviceSDL.cpp#L676

`irrevent` is not being used here - rather, a field of it is being assigned to. Are you sure that this is the correct line? Could you provide the full error message?

**Comment by DustyBagel** [comment] 2024-06-26 16:15
I'm not sure how that that would help that much but here you go.


![Screenshot 2024-06-26 105838](https://github.com/minetest/minetest/assets/150477174/153fc6e7-cb75-4c6a-ada8-198b259740c4)
![Screenshot 2024-06-26 110815](https://github.com/minetest/minetest/assets/150477174/3d228320-e63b-4e28-ab5a-3187d2e70117)

**Comment by DustyBagel** [comment] 2024-06-26 17:51
Here is the output in powershell with the trace argument in case that helps.

PS C:\minetest\bin\Debug> C:\minetest\bin\Debug\minetest.exe --trace
2024-06-26 12:49:05: [Main]: Enabling trace level debug output
2024-06-26 12:49:05: INFO[Main]: Using relative paths (RUN_IN_PLACE)
2024-06-26 12:49:05: INFO[Main]: Detected share path: C:\minetest\bin\Debug\..\..
2024-06-26 12:49:05: INFO[Main]: Detected user path: C:\minetest\bin\Debug\..\..
2024-06-26 12:49:05: INFO[Main]: Detected cache path: C:\minetest\bin\Debug\..\..\cache
2024-06-26 12:49:05: INFO[Main]: Minetest 5.9.0-dev-eae9fa4e9-dirty (Windows)
2024-06-26 12:49:05: INFO[Main]: Using LuaJIT 2.1.0-beta3
2024-06-26 12:49:05: INFO[Main]: Built by MSVC 19.39
2024-06-26 12:49:05: INFO[Main]: Running on Windows/10.0.22621 x86_64
2024-06-26 12:49:05: INFO[Main]: BUILD_TYPE=Release
2024-06-26 12:49:05: INFO[Main]: RUN_IN_PLACE=1
2024-06-26 12:49:05: INFO[Main]: USE_CURL=1
2024-06-26 12:49:05: INFO[Main]: USE_GETTEXT=0
2024-06-26 12:49:05: INFO[Main]: USE_SOUND=1
2024-06-26 12:49:05: INFO[Main]: STATIC_SHAREDIR="."
2024-06-26 12:49:05: INFO[Main]: SER_FMT_VER_HIGHEST_READ=29 LATEST_PROTOCOL_VERSION=44
2024-06-26 12:49:05: VERBOSE[Main]: httpfetch_init: parallel_limit=8
2024-06-26 12:49:05: INFO[Main]: Message locale is now set to: LC_COLLATE=English_United States.utf8;LC_CTYPE=English_United States.utf8;LC_MONETARY=English_United States.utf8;LC_NUMERIC=C;LC_TIME=English_United States.utf8
2024-06-26 12:49:05: INFO[Main]: Searching worlds...
2024-06-26 12:49:05: INFO[Main]:   In C:\minetest\bin\Debug\..\..\worlds: world1
2024-06-26 12:49:05: INFO[Main]: 1 found.
2024-06-26 12:49:05: [Main]: Automatically selecting world at [C:\minetest\bin\Debug\..\..\worlds\world1]
2024-06-26 12:49:05: INFO[Main]: Using world gameid [minetest]
2024-06-26 12:49:06: INFO[Main]: Audio: Global Initialized: OpenAL 1.1 ALSOFT 1.23.1, using OpenAL Soft
2024-06-26 12:49:06: VERBOSE[Main]: Trying video driver OpenGL
2024-06-26 12:49:06: INFO[Main]: Irrlicht: SDL initialized
2024-06-26 12:49:06: INFO[Main]: Irrlicht: SDL Version 2.30.3
2024-06-26 12:49:06: INFO[Main]: Irrlicht: Using renderer: OpenGL 4.6.0
2024-06-26 12:49:06: INFO[Main]: Irrlicht: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2: NVIDIA Corporation
2024-06-26 12:49:06: INFO[Main]: Irrlicht: OpenGL driver version is 1.2 or better.
2024-06-26 12:49:06: INFO[Main]: Irrlicht: Dedicated video memory (kB): 6291456
2024-06-26 12:49:06: INFO[Main]: Irrlicht: Total video memory (kB): 6291456
2024-06-26 12:49:06: INFO[Main]: Irrlicht: Available video memory (kB): 5274100
2024-06-26 12:49:06: INFO[Main]: Irrlicht: GLSL version: 4.6
2024-06-26 12:49:06: VERBOSE[Main]: Irrlicht: COpenGLCoreTexture: Type = 0 Size = 128x128 (128x128) ColorFormat = 3 (3) -> 0x1908 0x80e1 0x8367
2024-06-26 12:49:06: VERBOSE[Main]: Using the OpenGL video driver
2024-06-26 12:49:06: VERBOSE[Main]: Irrlicht: COpenGLCoreTexture: Type = 0 Size = 256x256 (256x256) ColorFormat = 3 (3) -> 0x1908 0x80e1 0x8367

**Comment by appgurueu** [comment] 2024-06-26 19:56
Might be a false positive, though I don't know if MSVC has these (some quick searches aren't turning any up, at least). Are you sure that the build is up to date?

**Comment by DustyBagel** [comment] 2024-06-26 20:06
Yes, I ran git fetch, reconfigured with cmake and recompiled. I am trying to do a git bisect but nothing has come up, I am beginning to think this may be something on my end, I am updating other things like visual studio community to see if that fixes it. I will let you know what I find.

**Comment by DustyBagel** [comment] 2024-06-26 22:15
I didn't find anything except I noticed that it works just fine on release builds for some reason. As for the git bisect process, every commit I try has this issue but only on debug builds, which doesn't make sense because newer commits if I remember correctly were working fine 2 weeks ago but I am not %100 sure about that. I will keep trying but if nobody else is having this issue then it is likely something on my end.

**Comment by appgurueu** [comment] 2024-06-26 22:20
> I didn't find anything except I noticed that it works just fine on release builds for some reason.

This is a debug-only check with a runtime cost, it won't be enabled in release builds (much like you wouldn't enable an address sanitizer in release builds).

> I will keep trying but if nobody else is having this issue then it is likely something on my end.

That is possible. I don't know how many people run MSVC debug builds on Windows however.

**Comment by DustyBagel** [comment] 2024-06-27 17:53
I did not find the commit that caused the issue, but I did find the problem:
https://github.com/minetest/minetest/blob/master/irr/src/CIrrDeviceSDL.cpp#L703

this line should be changed to 
`
	SEvent irrevent{};
`
So should I create a pr to fix that?

**Comment by appgurueu** [comment] 2024-07-01 12:45
I am aware that `irrevent` is not initialized there, but this should not be a problem. `irrevent` should just be written to before the respective fields are read; no reads of uninitialized data should happen.

Such a fix should work to fix your runtime error, but I don't see why we would need to zero initialize `irrevent` here. Where is this used?

**Comment by sfan5** [comment] 2024-07-01 13:46
> One bug that would've been prevented by initializing `irrevent` is #14517.

Not really, because `irrevent` is kept between iterations. So instead of uninitialized data you just get stale data.

What we can do to prevent future iterations of this bug is to move the declaration into the while loop.

**Comment by JosiahWI** [comment] 2024-07-20 12:20
I have also reproduced the issue.

## Minetest Version and Build Information

```
Minetest 5.9.0-dev-a7a719261 (Windows)
Using LuaJIT 2.1.0-beta3
Built by MSVC 19.39
Running on Windows/10.0.22621 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
STATIC_SHAREDIR="."
```

## Issue Scope

The issue is not limited to moving the mouse; it can be triggered with either a `KEYUP` or a `KEYDOWN` event as well.

```cpp
			// Make sure to only input special characters if something is in focus, as SDL_TEXTINPUT handles normal unicode already
			if (SDL_IsTextInputActive() && !keyIsKnownSpecial(key) && (SDL_event.key.keysym.mod & KMOD_CTRL) == 0)
				break;

			irrevent.EventType = irr::EET_KEY_INPUT_EVENT;
			irrevent.KeyInput.Key = key;
			
			// [ANNOTATION] MSVC sets a breakpoint on this line.
			irrevent.KeyInput.PressedDown = (SDL_event.type == SDL_KEYDOWN);
			
			irrevent.KeyInput.Shift = (SDL_event.key.keysym.mod & KMOD_SHIFT) != 0;
			irrevent.KeyInput.Control = (SDL_event.key.keysym.mod & KMOD_CTRL) != 0;
			irrevent.KeyInput.Char = findCharToPassToIrrlicht(mp.SDLKey, key,
					(SDL_event.key.keysym.mod & KMOD_NUM) != 0);
			postEventFromUser(irrevent);
```

## Analysis

In both core dumps, MSVC detects an error on the first line of code that sets the value of a 1-bit bitfield of type `bool`. I have not worked with bitfields before, and I didn't notice any obvious violation of the standard after reading https://en.cppreference.com/w/cpp/language/bit_field. The `bool` type is an integral type, and `!=` has higher precedence than `=` so the value is being assigned from a `bool` type to the bitfield. The only thing that worries me is that `true` and `false` might not be representable in one bit; they can be cast to integer values `1` and `0` respectively, but are they guaranteed to be stored that way? This still leaves a lot of questions, but I don't think it's a coincidence that in both cases, MSVC detects a problem when initializing a bit-field. Perhaps someone with a better understanding of bit-fields can check whether these assignments are well-defined and safe.

```cpp
                bool Shift : 1;
```

```cpp
                bool PressedDown : 1;
```

**Comment by JosiahWI** [comment] 2024-07-20 12:35
https://stackoverflow.com/questions/13171054/is-bool-safe-in-a-bitfield-definition

It sounds like this usage should be safe.

**Closed** 2024-07-22 14:32 UTC
Labels: Bug, @ Startup / Config / Util
