### ISSUE TITLE
ServerError: error in error handling 

### ISSUE THREAD

**Issue by yetanotherusernamebecausegithubisbugged** [minetest/minetest#1423] opened 2014-06-28 04:00 UTC
This code registers a node which upon destruction will cause "ServerError: error in error handling" error with no info about actual line and file where error had hapenned, so it could be hard to trace if you're an admin server with tons of mods installed.

    minetest.register_node(
        minetest.get_current_modname()..":servererror",
        {
            description = "ServerError Block",
            tiles       = { "default_nc_rb.png" },
            groups      = { oddly_breakable_by_hand = 3 },
            after_destruct = 
                function(pos, oldnode)
                    local a
                    a["b"] = "c"
                end,
        }
    )

Things can go even worse because in following case you might think that you have initialized the "a" variable (surprise surprise, you initialized "b")

    minetest.register_node(
        minetest.get_current_modname()..":servererror",
        {
            description = "ServerError Block",
            tiles       = { "default_nc_rb.png" },
            groups      = { oddly_breakable_by_hand = 3 },
            after_destruct = 
                function(pos, oldnode)
                    local b,
                          a = {}
                    print(a,b) -- nil table: 0xafb07b20
                    a["b"] = "c"
                end,
        }
    )

**Comment by kwolekr** [comment] 2015-08-18 02:21
This is a double-fault caused by a runtime error inside of a callback that originated from a Lua API.  It does trigger the "error in error handling" message due to a bug in LuaJIT, but this is wrapped around a LuaError and rethrown as a runtime error thanks to the script execution wrapper.  You do get a backtrace but unfortunately it's somewhat less helpful than the backtrace in the context of a regular runtime error.
Here is the more recent issue for this: https://github.com/minetest/minetest/issues/3011
Closing.

**Comment by HybridDog** [comment] 2015-08-18 08:29
at least l know now that luajit works for me
l wasn't sure because someone using luajit got a crash problem whereas it worked for me:
>local t = {"exists"}
for n,i in pairs(t) do
t[n] = nil
if not i then crash() end
break
end

**Comment by est31** [comment] 2015-08-25 01:12
Why did this get closed? Its not fixed yet..

**Comment by est31** [comment] 2015-08-25 01:13
Related to  #3024

**Comment by est31** [comment] 2015-08-25 04:49
Okay, today @kahrl has suggested a theory in irc that hopefully brought us closer to solving the problem. The current theory:

1. In the ScriptApiBase, `m_errorhandler` is set to a (then matching) position on the stack
2. C++ calls lua, lua calls C++, adding an emptied element to the "stack of stacks" `m_luastack`, C++ calls lua again
3. lua makes an innocent error
4. the lua runtime, the entry at the m_errorhandler position is read, but unfortunately, now there is no function, but something else
5. the lua runtime does the fully justified descision to raise an ERRERR

I have partially confirmed the theory, by getting a failing assert when doing `assert(lua_type(L, m_errorhandler) == LUA_TFUNCTION);` inside a function called (indirectly) by lua, like `ScriptApiNode::node_on_construct`.

For the case the theory doesn't turn out to be right, I've coded a [hack to print error stacks](https://gist.github.com/est31/e84180467a76f8badb42), as a plan B.

**Comment by est31** [comment] 2015-08-26 23:57
Fixed by 3304e1e517fb8aac008c4684e72a4b59b408414a

**Closed by est31** 2015-08-26 23:57 UTC
Labels: @ Script API, bug
