### ISSUE TITLE
Stall Glitch

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#4151] opened 2016-05-22 06:10 UTC
It seems that after a few hours Xanadu server stalls and locks up, no errors are reported, no players can connect due to major increase in lag and server looks as if it's running fine but it simply stalls ?!?!  A few other servers have been known to have this problem also with 0.4.14...  I'll be downgrading to a previous 0.4.13 dev (4826) before this glitch appeared and the only information I can provide is that my last 3 builds were 4833, 4835 and 4836 when glitch appeared.

**Comment by Fixer-007** [comment] 2016-05-22 10:36
Extreme Survival Minetest server has the same symptoms since its start in Aug 2015 with -dev builds of that time, bug persisted across all further versions. It is notoriously bad for gameplay with people and admins rage quitting.
Symptoms: It works good for 20000 sec or so with good enough lag (playable), after that surges of really big lag appear (max_lag could be 3, but actual lag can be 1-60 sec and beyound), people starting timeout, after sometime it starts working again, but worse, after some time larger lag surge appear halting everything, people time out again, it lives more, maybe up to 30000 sec, where it just stops responding at all and people slowly timeout to 0 players on servers, it is still on server list but nobody will manage to connect to it, it is in a coma, only restart solves this. It is running on i7 notebook with windows 64 if I'm not mistaken.
This is very irritating issue.

**Comment by tenplus1** [comment] 2016-05-22 14:10
Update: After using May 2nd build of minetest it stalled as well, then on the 18th April build which also stalled...  Compared both minetest.conf files from server and backup with no changes...  Why all of a sudden the OLD builds which worked fine on Xanadu are now stalling as well ???

**Comment by stujones11** [comment] 2016-05-22 15:21
> Why all of a sudden the OLD builds which worked fine on Xanadu are now stalling as well

That would suggest a mod problem to me, have you tried profiling?

**Comment by tenplus1** [comment] 2016-05-22 17:49
Nothing appears for a mod problem, but since switching server to 0.4.14 stable it seems to run ok at full load...  <fingers crossed>

**Comment by tenplus1** [comment] 2016-05-23 06:58
Update #2, Shinji was on server most of the day yesterday and stall glitch never appeared for the whole day...  As soon as he logged off from play it happened within an hour ?!?! so today he's connected as a player and idling to see if it happens while connected.

**Comment by tenplus1** [comment] 2016-05-23 15:41
Update no.3, server ran for just over 9 hours using above method and then the stall bug totally lagged server, no commands worked, signing out and trying to re-connect wouldnt work as it just timed out.

**Comment by tenplus1** [comment] 2016-05-24 20:48
We ran Xanadu in verbose mode and notices 100's of these errors appear:

VERBOSE[ConnectionReceive]: con(5/1)WARNING: ACKed packet not in outgoing queue

VERBOSE[ConnectionSend]: con(5/1)RE-SENDING timed-out RELIABLE to 73.244.117.13(t/o=0.236): from_peer_id=1, channel=0, seqnum=3827

**Comment by Fixer-007** [comment] 2016-05-24 20:53
Bingo.

**Comment by maikerumine** [comment] 2016-05-26 00:45
I can attest that this OldCoder build seems to have solved this issue, as far as it has been running on my servers.
My record time of no major lag and no lockups:  uptime 78898, max lag 0.3 19 players online.  Wow.
I am finally impressed.

**Comment by DonBatman** [comment] 2016-05-26 03:57
Can you please tell RobbieF on irc channel#minetest-project. He has. Had some issues with this.

**Comment by tenplus1** [comment] 2016-05-27 08:02
Glad to hear maikerumine, just hoping for a new build containing the patch to appear soon.

**Comment by Fixer-007** [comment] 2016-05-27 11:24
Patch is here: http://minetest.org/netfix-0.4.14.zip If some one can compile minetest with it for tenplus1, will be nice.

**Comment by 0-afflatus** [comment] 2016-05-27 21:35
I wonder if we should move the whole discussion from 3307 to here, as this seems to be the same issue. It would be really useful to test the patch on Xanadu as it hasn't fixed the problem for me, although it seems to improve lag.

**Comment by tenplus1** [comment] 2016-05-28 20:38
(21:28:01) tenplus1: could you add a failsafe to the engine that detects a stall or increased lag (can be set) then restarts or quits server
(21:28:22) Calinou: is that even possible?
(21:29:14) tenplus1: when pressing F5 it shows you server lag, so a setting (say 20 seconds) and a check to see if lag goes beyond this and then game quits
(21:29:47) tenplus1: or a nicer way is to kick everyone off server and restart it...  anything so long as it restarts
(21:30:08) tenplus1: the way it stalls I cant do anything about it... I have to wait for Shinji to manually close game and restart script
(21:30:43) tenplus1: it many not be the ideal solution, but it's a hail mary in keeping server up and active after stalling

**Comment by johnnyjoy** [comment] 2016-05-28 20:42
Assuming the AsyncRunStep is still running you could touch a file each time, and setup a script kill and restart the server when the files mtime hasn't been updated in a umber of seconds. It's a total cludge, but it might get things going in the very short term.

**Comment by 0-afflatus** [comment] 2016-05-29 17:32
@tenplus1 I'm more and more convinced (having hung out on Xanadu recently) this is a duplicate of what we've been discussing in #3307 and I have been experiencing on the Grailtest server - what I'm not clear about is whether the loop condition is causing the lag or whether lag is causing the loop condition, I'm getting ABM warnings in the log along with resending reliable warnings. There are so many variables in this and so little useful error reporting, even if I run dbg, that it hard to tell whether the netfix patch is helping or not. I think it is, but it didn't fix the problem for me.

It would be really useful to be able to compare notes with Shinji and/or yourself, as one of the biggest obstacles to fixing this is knowing what is really causing this and therefore the general reproducibility of the problem. We're both running with highly modified code, so I'm thinking it should be relevant to discount the differences and focus on the similarities. While I'm fairly convinced this is an engine issue, I think it may be being made worse by mod-induced lag.

**Comment by Wayward1** [comment] 2016-05-31 00:50
Just another confirmation, if it matters: I'm currently experiencing this as well on one of two similar test servers set up at home. It couldn't have been more than a couple of hours after I started them both. I can connect to one, but the other fills my client's debug.txt with the aforementioned "RE-SENDING timed-out RELIABLE" error. I'll try the patch once I get home.

**Comment by tenplus1** [comment] 2016-06-03 08:28
@0-afflatus - while cerain mods are optimized in Xanadu they thankfully reduce lag instead of causing it, 40 players at 0.4 lag isn't too bad...  I've been bullet-proofing many mods that use metadata incase a corrupt node doesn't contain any, also I've added a restart script to check when stall happens and kills server for it's own script to restart and keep server running when admin isn't around:

```
#!/bin/bash

while true; do

	# wait 2 mins before check
	sleep 120

	# get last access date from file
	filedate=$(date -r ~/.minetest/worlds/xanadu/env_meta.txt +%s)

	# get current time in utc
	now=$(date +%s)

	# calculate how many seconds file last accessed
	((count = now - filedate))

	# if over 3 mins then server stalled
	if [ "$count" -gt 180 ]; then

		# kill process
		TIMESTAMP=`date +%Y%m%d.%H%M`
		killall minetest
		echo ${TIMESTAMP} "minetest terminated on freeze"
	else
		echo "last accessed $count seconds ago"
	fi

done

**Comment by tenplus1** [comment] 2016-06-03 21:57
Ok, latest minetest build 4879 with patch didnt work, if anything Xanadu stalls every 4-10 minutes, so we ran server in verbose until stall and here's the debug.txt file:

**Comment by 0-afflatus** [comment] 2016-06-04 05:52
Based on my experience with the patch on Grailtest, that's what I was expecting. I have to say I'm impressed with Xanadu's lack of lag and that does kind of discount it as a cause. My hunch is that we need to look at what I'm calling the 'Bermuda triangle effect', where certain areas of the map appear to cause server hangs. I think that is a different bug, but I have a feeling that if we can understand that we may get some useful info towards fixing this. I really would like to be working on more than just a hunch.

Thanks for the kill script as it looks like that will be necessary for the time being.

**Comment by tenplus1** [comment] 2016-06-04 08:08
The specific areas that causes the stall glitch to happen were regenerated using the /deleteblocks command and does indeed stop it from happening, but... deleting a huge chunk of map each time containing player builds isnt the best option so yeah, we really need to find the cause.

**Comment by amadin** [comment] 2016-06-04 09:48
Can client 0.4.14 create stall glitch on server in theory? I ask because after rollback to 0.4.13-dev server still had stall glitch.

**Comment by tchncs** [comment] 2016-06-04 14:39
The last time i ran into this glitch was a few months ago, when i tryed to do a public message on `minetest.register_on_newplayer`. (#3563)
Maybe not helpful...but...who knows.. .

**Comment by 0-afflatus** [comment] 2016-06-05 03:59
> Apart from metadata, what else does the engine gather from nodes that may become corrupted and cause problems ?

Good question. I want to look into how protection works as these all appear to be protected areas, many, but not all with multiple owners. As we use different protection mods I'm going to have a look at how the engine deals with checking for editing rights. I'm reminded of a problem rubenwardy's chatplus mod had checking for players that were offline at the time.

**Comment by rubenwardy** [comment] 2016-06-05 12:47
I had problems a year ago with the following code causes the server to look up:

```lua
minetest.register_on_newplayer(function(player)
    minetest.chat_send_all(" has joined")
end)
```

but this has supposedly been fixed.

**Comment by 0-afflatus** [comment] 2016-06-05 16:52
> Capturetheflag, not chatplus

Hmm? It was definitely the old version of chatplus I was using, I have never played or dl'd CTF. I'm saying that this bug seems similar rather than the same. Subtle but important difference.

**Comment by rubenwardy** [comment] 2016-06-05 17:50
Oh, the issue is about capturetheflag but it's probably in chatplus as well.

**Comment by Fixer-007** [comment] 2016-06-05 19:21
Full backtrace and debug.txt available here: https://forum.minetest.net/viewtopic.php?f=10&t=8494&p=219753#p219753

**Comment by est31** [comment] 2016-06-05 20:08
I'm summarizing some knowledge collected on IRC:

* The stall glitch is reproducible if players go to certain areas in the server. They can be fixed again by invoking `/deleteblocks`, but apparently use of this command is really undesirable.
* The backtrace linked in the previous comment appears to be inside an ABM invoked on a node with the coords `{X = 324, Y = 27, Z = -1994}`, @tenplus1 has told us that there is a furnace at this place.
* Further inside the backtrace the lua code calls engine code again, `get_craft_result` with `default:desert_sand`
* @tenplus1 has told us that he has used an older version of mtgame which still used ABM, I think to retain compatibility with the hopper mod.
* Note that inside the backtrace there is `col_iter`, and its value looks really dangerous (length -16 and capacity of -17592133480497). But its normal to look that way, as its declared but not initialized yet at this point of execution.
* @tenplus1 has now updated the code to use nodetimers, apparently the stall glitch can't be reproduced.

**Comment by Fixer-007** [comment] 2016-06-05 21:59
Don't forget that stall glitch is not @tenplus1 exclusive, other servers were having stalls alike this, with somewhat different behaviours, for example, ESM was having big max_lag surges before going into coma. I think it could be in fact several bugs.

**Comment by tenplus1** [comment] 2016-06-06 05:50
Maybe we're looking at mods with "get_craft_result" problems ?

**Comment by 0-afflatus** [comment] 2016-06-06 15:26
OK, well I was planning to move to nodetimers anyway on Grailtest - I am also still using ABMs, so this analysis makes some kind of sense.

@Fixer-007 sure, but for most of the servers running MTgame the problem appears to be historical.

**Comment by est31** [comment] 2016-06-07 04:55
Still, in theory it should run bug-free with ABMs as well. Its a bug in any case.

**Comment by 0-afflatus** [comment] 2016-06-07 23:51
> it should run bug-free with ABMs

I have made one change so far, on an educated hunch. I removed all references to `catchup = false` 24 hours ago. https://github.com/0-afflatus/grailtest/commit/ff4e6505a6b632b3110af2a0b66a38470104f694
I haven't noticed any problems with furnaces, which were not using `catchup = false` in Grailtest.
As this is a case of proving the needle isn't in the haystack I'm not holding my breath ...

**Comment by 0-afflatus** [comment] 2016-06-09 23:20
So removing `catchup = false` doesn't prevent stalling, it just slows down the process somewhat. Inconclusive.

**Comment by Fixer-007** [comment] 2017-03-29 18:35
Can be closed I guess.

**Closed** 2017-04-06 22:39 UTC
Labels: @ Server / Client / Env., Bug, High priority

**Comment by Fixer-007** [comment] 2017-04-07 13:53
https://github.com/minetest/minetest/pull/4170 fixes the problem
