### ISSUE TITLE
first spawn of player underground - valleys mapgen

### ISSUE THREAD

**Issue by hunter688** [minetest/minetest#3789] opened 2016-02-26 09:36 UTC
When use for example seed: 1120531517939098268
spawned suffocated or underground.

It would need somehow to check whether the player is on the surface and move it there if necessary.

**Comment by est31** [comment] 2016-02-26 14:07
Yeah how to get spawn working with various mapgens has been an issue we have been used to improve... @paramat has done great work on this and @duane-r too.

**Comment by duane-r** [comment] 2016-02-26 15:25
I haven't managed to duplicate this, but it doesn't really surprise me. When I started the code I made the incorrect assumption that one of the calculations always added to terrain height. Now I know that it only does so most of the time. A string of bad luck will get you no legal spawn points.

However, fixing that issue will still leave the possibility that you could have a different string of bad luck and end up buried at 0,0,0 due to being refused to spawn on rivers. That's something we put in to avoid complaints about people drowning. I think getting wet would be preferable to being buried, but the method in question is fairly simple. I'd like to convert Gael de Sailly's lua function, which seems to work better, but that probably won't be a quick fix.

**Comment by duane-r** [comment] 2016-02-26 17:31
Ok, there is a minor issue in the terrainLevelAtPoint function, but the real problem is limiting spawns to under 17 altitude. That's taking an average of 450 tries on this map, as opposed to one or two without the limit. I can see that easily eating up all the allowed retries, not to mention taking a perceptible time to spawn (tiny, but noticeable).

Do we really have to stick to that low altitude?

**Comment by 0-afflatus** [comment] 2016-02-26 18:25
Surely within 31 would be more realistic

**Comment by paramat** [comment] 2016-02-26 20:05
Spawn should be successful within 1000 nodes of world centre, since the noise 'spread' of terrain height has spread 1024.
Spawn below y = 17 is generous, it used to be below y = 9 but i changed it to make spawn faster and closer to world centre.
Spawning checks out to 4000 nodes now, so if spawn fails often there may not be enough low terrain in mgvalleys, how is the balance between land and sea?

**Comment by MoNTE48** [comment] 2016-02-27 01:00
@paramat,sometimes I spawn inside the wood (mostly tested on v6). Is it possible to delay the spawn player, until you have generated all the scenery?

**Comment by paramat** [comment] 2016-02-27 01:24
Inside trees? yeah that's common, lucky we can punch wood. Not sure it's possible to check for trees during spawn, although hmmmm was considering such a check.

**Comment by C1ffisme** [comment] 2016-02-27 01:58
@MoNTE48 I can't tell you how many times this has happened to me while testing map generator noise.

**Comment by MoNTE48** [comment] 2016-02-27 02:00
@C1ffisme Haha, yes, and it's very annoying.
---
And it is impossible to make forced gineratsiyu field without trees in the mountains near the 0,0,0 optional? Yes, it's not really the random, but this is a great decision, I think.

**Comment by duane-r** [comment] 2016-02-27 02:04
Ideally, it shouldn't matter what the terrain is. It seems to me that leaving any possibility of ending up at 0,0,0 is a problem. If it gets down to that, we ought to just pick some spot that's not occupied.

Fixerol asked me once if we could make the terrain size more realistic. It's not dificult, but it turned out that the minetest spawn code couldn't handle it. For the lua, it was easy. https://forum.minetest.net/viewtopic.php?f=9&t=11430&start=225#p204782

**Comment by C1ffisme** [comment] 2016-02-27 02:05
It would be a bit fun to show what the map generator is actually doing, like on Terraria when it generates maps. But that's offtopic.

The best option is to spawn the player after map generation. Another option is to have a (optional for other subgames/people who don't like it) "starting house" which would spawn above the world, just enough to prevent being spawned underground or underwater.

**Comment by MoNTE48** [comment] 2016-02-27 02:08
@C1ffisme, Both your ideas come to me before) I just think that the house - a little silly! We can use the schematics with air 3*3 or greater

**Comment by MoNTE48** [comment] 2016-02-27 02:24
Offtop, but i set chunksize 3 and fixed dead after spawn :)

**Comment by duane-r** [comment] 2016-02-27 03:02
@paramat 

>Spawn search checks out to 4000 nodes now, so if spawn fails often there may not be enough low terrain in mgvalleys, how is the balance between land and sea? Allowing river spawns won't make much difference as their surface area is low. I recommend rewriting 'getgroundlevelatpoint' to be designed for player spawning, not for general getting ground level at a point, those functions are only used for player spawn.

I don't know how to guarantee low terrain except by flattening out the base terrain noise, which would have profound effects on the look of the terrain. Even then you'd have to deal with people changing the noise.

I'm not sure what you mean by rewriting getgroundlevelatpoint. Are you talking about the emerge function?

**Comment by duane-r** [comment] 2016-02-27 03:09
This is how terrainLevelAtPoint should work. The method we're using now will fail at least one in four times (which can't be helping).

https://github.com/minetest/minetest/compare/master...duane-r:spawn

However, this is the code I was using when I averaged 450 retries, so it's not a solution in itself.

**Comment by paramat** [comment] 2016-02-27 19:29
> I'm not sure what you mean by rewriting getgroundlevelatpoint.

I mean the getGroundLevelAtPoint() function in the mapgen, you'll see that in other mapgens that function is specialised for spawn search.

**Comment by paramat** [comment] 2016-02-27 19:32
@hunter688 when this happens look at your co-ords and see if you are at 0,0,0 or not, this is useful information.

**Comment by hunter688** [comment] 2016-02-27 19:35
oki

**Comment by paramat** [comment] 2016-02-27 19:36
> make the terrain size more realistic. It's not dificult, but it turned out that the minetest spawn code couldn't handle it

Yes that's why spawn search now searches out to 4000 nodes, to cope with mgwatershed or cutom parameters. Also, max spawn height above water is now set per mapgen, instead of 16 being used for all.

**Comment by duane-r** [comment] 2016-02-28 06:49
I've got a PR in for an improvement to terrainLevelAtPoint. However, the difference in spawn retries is truly mediocre. It went from an average of 630 to 580, on this map, in my latest series of tests. Raising the maximum altitude to 32 made almost no difference because this map's origin is in a high area (50) surrounded by mountains on three sides. The nearest low spot is about 400 meters away, which means there's zero chance of finding it in the first 400 cycles through the spawn loop.

The change I made gives an accurate ground level. However, it occurs to me that this may actually make things *worse*. It doesn't reduce retries much, and appearing on the ground may cause more collisions with decorations than appearing five or ten blocks in the air. (The existing code's errors are all higher than ground level.)

Valleys is not fundamentally well suited to altitude limits. Base ground can vary a lot (-60 to 40 is most common), but it's usually over a large distance (1024 spread). Terrain is seldom much less than base ground (most often in a river), but it can be a great deal more. In the case of this map, the nearest low ground quickly slopes into the ocean, which again is not allowed for spawns.

The lua uses a much larger initial range for spawn points, sets no maximum altitude limit, and loops until it finds a spot.

Even with the mainline code, the odds of getting stuck at origin are low, but given enough time it will happen. I haven't ever managed it except as a result of my own misguided tinkering.

Since I can't duplicate the problem, and the only errors I've spotted don't make much difference, I'm reluctant to change anything.

**Comment by duane-r** [comment] 2016-02-28 07:53
@MoNTE48

>And it is impossible to make forced generate field without trees in the mountains near the 0,0,0 optional? Yes, it's not really the random, but this is a great decision, I think.

Yes, we can! Sort of. In fact it's easy as long as you accept some possibility of failure. This is what it looks like on  hunter688's map. (Note the diamond nerd-pole in the center.) It creates a bowl-shaped depression in higher ground, without entirely destroying the variability of the terrain. You will almost always spawn near origin with this change.

![zero cool](http://duanerobertson.com/img/c-demo-90.jpg)

Of course, there are some caveats. This will probably look weird on some maps, and if it appeared in the ocean, you'd have a desert island, perhaps with no land in sight. If a mountain happens to pop up at origin, this change may not help. (I could suppress the mountain, but it would be difficult and probably more cpu-intensive than I'd like because of the relationship between base ground, terrain, and rivers.)

**Comment by MoNTE48** [comment] 2016-02-28 08:19
@duane-r, we could make a delay, for example, until you generate map 64*64 blocks not spawn player? In Minecraft map generation occurs during the download of the world. Therefore, the player always spawn very quickly and without problems.

**Comment by paramat** [comment] 2016-02-28 11:42
> make forced generate field without trees in the mountains near the 0,0,0 optional?

Nope i won't allow this, it's too artificial and breaks the gentle variation of the base ground height which is the watershed/river height structure..
Best thing to do is increase the max spawn altitude, how about 64?

**Comment by paramat** [comment] 2016-02-28 11:48
As far as i know the current spawninhg does actually emerge a mapblock and check for a column of air (see findSpawnPos), but it fails sometimes for some reason.

**Comment by MoNTE48** [comment] 2016-02-28 12:06
@paramat,  I even tried to 1024 high, it does not help much on the weak devices. spawn player is much earlier than the world will be generated

**Comment by hunter688** [comment] 2016-02-29 06:46
![mt-ug-spawn](https://cloud.githubusercontent.com/assets/1410134/13387586/8e8fd902-deb8-11e5-9eed-c5fd1aabf9d2.png)

**Comment by paramat** [comment] 2016-02-29 21:49
Useful, this shows that terrain height is being incorrectly calculated, instead of 4000 locations being unsuitable due to height.

**Comment by duane-r** [comment] 2016-03-01 01:01
@hunter688
Maybe if you link your worlds/*/world.mt and map_meta.txt I'll have better luck reproducing the problem. So far, I'm getting nothing. It can't be that unlikely if you've gotten it twice in several days.

@paramat
The problem is that the current method can't result in a location lower than terrain level. It can produce a higher one, but how would that leave you in stone? On my system, using the current codebase, at (136,-119), seed: 17998632089899323342:
surface_y: 70.577141, height: 72, terrainLevelAtPoint: 72.000000
That's the only value getSpawnLevelAtPoint has to work with. Unless the C++ code is being compiled differently for hunter688, I'm not sure what could be happening.

**Comment by paramat** [comment] 2016-03-01 04:06
Weird. Perhaps hunter688 is using Android? There have been strange mapgen issues on that.

**Comment by hunter688** [comment] 2016-03-01 04:46
Im using 64bit linux.

http://pastebin.com/NpUferq6

**Comment by duane-r** [comment] 2016-03-01 05:49
Except for creative mode and damage, that's exactly the same as mine. Needless to say, setting those didn't make any difference.

I was one commit behind your screenshot, so I merged... still no luck. I'm using Debian 64-bit. I notice that this time I got three results, two are from overscans where the bogus height is forced out of range since it's not fully generated, but they all show 72 for the actual number that spawnLevelAtPoint gets, so that still explains nothing.

*** surface_y: 70.577141, height: 72, terrainLevel: 72.000000
*** surface_y: 70.577141, height: 46, terrainLevel: 72.000000
*** surface_y: 70.577141, height: 46, terrainLevel: 72.000000

I guess you could try patching this in to see if you get the same numbers I do from the altitude routines.
```
diff --git a/src/mapgen_valleys.cpp b/src/mapgen_valleys.cpp
index f962574..8863ab7 100644
--- a/src/mapgen_valleys.cpp
+++ b/src/mapgen_valleys.cpp
@@ -644,7 +644,10 @@ int MapgenValleys::generateTerrain()
 
                        vm->m_area.add_y(em, index_data, 1);
                        index_3d += ystride;
+
                }
+                       if (x == 136 && z == -119)
+                               printf("*** surface_y: %f, height: %d, terrainLevel: %f\n", surface_y, heightmap[index_2d], terrainLevelAtPoint(x,z));
 
                // This happens if we're generating a chunk that doesn't
                // contain the terrain surface, in which case, we need
```
Then teleport to (136,80,-119) so that it will actually generate. You should get the same numbers I do, particularly the last. If you don't then you're probably getting different noise values (from the same settings), which shouldn't happen.

**Comment by paramat** [comment] 2016-03-01 18:58
@duane-r perhaps it's a good idea to increase max spawn y to water_level + 32 since mgvalleys has a large spread, not much low land and steep slopes.

**Comment by paramat** [comment] 2016-03-15 17:02
@hunter688 still a problem? Max spawn has been raised to water_level + 32.

**Comment by hunter688** [comment] 2016-03-16 06:27
with seed mentioned above (screenshot) is still same problem (latest build from git)

**Comment by paramat** [comment] 2016-12-19 06:15
>  On my system, using the current codebase, at (136,-119), seed: 17998632089899323342:
surface_y: 70.577141, height: 72, terrainLevelAtPoint: 72.000000

Testing i get this too, my feet are at 72.5.
@hunter688 is this still happening? Do you have 'fixed spawn point' set in .conf?

**Comment by hunter688** [comment] 2016-12-19 12:01
Still have issue, "fixed spawn point" see nowhere (not in example conf too).

**Comment by paramat** [comment] 2017-03-21 22:18
Can anyone else reproduce this? If not we#ll close.

**Comment by paramat** [comment] 2017-03-21 22:33
No one can reproduce this and no-one else has reported it, closing.

**Closed by paramat** 2017-03-21 22:33 UTC
Labels: @ Mapgen, Possible close, Unconfirmed bug

**Comment by paramat** [comment] 2018-10-02 23:51
See #7756 there was a bug, now fixed.

**Comment by paramat** [comment] 2019-03-14 00:32
There was an additonal spawning bug, now fixed in the rewrite.
