### ISSUE TITLE
[FEATURE] Allow bigger nodeboxes (above 1.45)

### ISSUE THREAD

**Issue by Panquesito7** [minetest/minetest#13212] opened 2023-02-17 02:18 UTC
## Problem

I was creating a node with a larger nodebox than 1.45 for triggering a callback.
However, I noticed that the collision was broken when I did that. Looks like the engine is limiting the nodebox size.

## Solutions

Support larger nodeboxes (if possible).

## Alternatives

I haven't thought of any other alternatives.

## Additional context

I tried searching for duplicate issues and didn't find any. Feel free to close if that's not the case.

**Comment by SmallJoker** [comment] 2023-02-17 07:35
Duplicate of #2612

**Closed by SmallJoker** 2023-02-17 07:35 UTC
Labels: Feature request
