### ISSUE TITLE
Fog reveals cave structure when using fake-enabled fly mode

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9608] opened 2020-04-07 14:56 UTC
##### Minetest version
```
5.2.0
```

##### Summary
If you walk into a dark cave at day time, have fly mode enabled WITHOUT having the fly privilege, the cave structure is revealed thanks to the bright fog.

##### Steps to reproduce
* Enable fly mode (WITHOUT having the fly privilege, so it's only fake-enabled!)
* Set your view range to minimum
* Walk into a dark cave at daytime

EXPECTED: Cave stays dark. ACTUAL: The fog takes the daytime fog color, revealing the cave structure.

##### Additional context

This seems to be a zombie bug, a resurrection of an older bug that was believed to be dead long time ago. Sadly, I can't find it anymore …

**Comment by SmallJoker** [comment] 2020-04-07 17:06
Does the effect disappear when you disable noclip?
If yes, blame this code:
https://github.com/minetest/minetest/blob/143a37e947d809ac68da56bac0f61cf8b5fd0d46/src/client/clientmap.cpp#L147-L152

**Comment by Wuzzy2** [comment] 2020-04-07 19:37
Yes. It only happens when both fly mode and noclip mode are active. Also, it doesn't matter if I actually have the privs or not.

So there's actually 2 bugs:
1) The game ignores if I actually have the privs, just looks at the modes
2) The fog bug that I already described

**Comment by Fixer-007** [comment] 2020-04-08 14:21
Thank you for bringing this up

**Comment by KaylebJay** [comment] 2020-04-08 19:53
Yes, this is really a sad issue. People can glitch through blocks and see into normally dark areas if they have fly enabled (where they can see just about everything that is loaded). Not too happy this is a thing :/

**Comment by paramat** [comment] 2020-04-09 21:39
Duplicate of #5939

**Closed** 2020-04-09 21:47 UTC
Labels: @ Client / Audiovisuals, Bug, Duplicate
