### ISSUE TITLE
Add Sneaking Animation and lower view

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10352] opened 2020-08-30 13:37 UTC
## Problem

When i am playing minecraft, I can sneak to reach node in a hoe(See the photo）. But if i want to do the same in minetest, I need to dig down one node.
![screenshot_20200830_213333](https://user-images.githubusercontent.com/55009343/91660480-caa07300-eb08-11ea-946b-f424c49718c3.png)

## Solutions

If minetest add a sneak animation, other players can know you are sneaking.
If add a lower view when sneaking, I can reach lower node easier.

**Comment by MoNTE48** [comment] 2020-08-30 19:23
Well, that's hardly an engine issue. This is how it works in my subgame:
https://github.com/MultiCraft/MultiCraft_game/blob/master/files/player_api/api.lua#L130

But yes, it is better to shift the height of the eyes when sneaking in the client side, the server makes this very unreliable.
https://github.com/MultiCraft/MultiCraft/commit/ca1e211f7ea137a6239dbfa930f313b99781133c#diff-25d902c24283ab8cfbac54dfa101ad31

**Comment by LoneWolfHT** [comment] 2020-08-30 19:26
A sneak and aux animation in the clientside anim prediction would be nice

**Comment by paramat** [comment] 2020-08-30 20:39
Duplicate of #2063 . A sneak animation is more of a game issue, see https://github.com/minetest/minetest_game/issues/2294

**Closed by paramat** 2020-08-30 20:39 UTC
Labels: Duplicate, Feature request
