### ISSUE TITLE
Stamina fails to work with commit 9649e47

### ISSUE THREAD

**Issue by mtango688** [minetest/minetest#6937] opened 2018-01-20 15:59 UTC
See https://github.com/minetest-mods/stamina

Today the Stamina mod exhibits some strange, unpredictable behavior, though it mostly just kills the hunger bar right after you log on.

**Comment by red-001** [comment] 2018-01-20 19:29
caused by a workaround I had to use due to #6939 , for now you should be able to use it normally if you just disable the preview mod.

**Comment by paramat** [comment] 2018-01-21 13:21
#6940 merged and fixes this.

**Closed** 2018-01-26 15:05 UTC
Labels: Bug
