### ISSUE TITLE
[CSM] Allow a server to disable all (non-essential) client-provided clientmod functions

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5974] opened 2017-06-12 19:27 UTC
Related issue #5915
Related PR #5930 my request is here https://github.com/minetest/minetest/pull/5930#issuecomment-307489355

As i understand it, some functions are essential for CSM to work, in the following i am not referring to these.
I propose that the CSM 'flavours' restrictions allow all (non-essential) CSM functions to be disabled even if they are currently not considered potentially harmful to a server, the restrictions PR currently does not seem to do this.

1. It's not easy to judge which functions are potentially harmful to a server. In the future it is likely that a function currently considered harmless will be used in a way we didn't forsee. In this situation a server will have no way to avoid the disruption and would have to wait for a PR that adds that function to those considered potentially harmful, this would take a few days.
2. Some CSM functions that are genuinely harmless towards the server still change the player's experience. Occasionally a server may wish that the players have a similar experience or not use harmless CSM for other reasons. I expect this will rarely be done though.

**Comment by nerzhul** [comment] 2017-06-12 19:33
i think this issue is useless and duplicate of #5915

**Comment by paramat** [comment] 2017-06-12 19:48
Closely related yes, but this concerns non-harmful functions.
This would get somewhat overlooked if added as a comment to the end of 5915

**Comment by nerzhul** [comment] 2017-06-12 21:10
non harmful = let them. I'm sorry but paramat you don't understand the potential of CSM and you really should study what we can do.

**Comment by paramat** [comment] 2017-06-12 22:13
"non harmful = let them" you have misunderstood then, please read:

>  In the future it is likely that a function currently considered harmless will be used in a way we didn't forsee.

> you don't understand the potential of CSM

You write that after i opened a recent issue about a big issue that was missed by you and red despite strong objections raised long before release. So i have a good understanding, in some ways better than you.

**Comment by paramat** [comment] 2017-06-13 02:11
Nerzhul please be more reasonable, last night was ridiculous with your comments here and then this in dev channel http://irc.minetest.net/minetest-dev/2017-06-12#i_4972154

> 21:54 kilbith    you're expecting paramat to write a unittest?
21:54 kilbith    lol
21:59 kilbith    he can't write one

kilbith i have not written a unittest before but i can probably learn how to. This is typical of you to use every possible opportunity to make an invalid personal attack.

**Comment by paramat** [comment] 2017-06-13 02:33
@celeron55 any opinion on this?

**Comment by dsohler** [comment] 2017-06-13 04:54
> It's not easy to judge which functions are potentially harmful to a server.

All functions that trigger any kind of action on the server are potentially harmful.

**Comment by nerzhul** [comment] 2017-06-13 05:49
it handle all sources of gameplay modification which can be owned by server owners + permits restriction on sensible function, but if you have more lua api ideas which are really problematic tell me which call, it's simple, and i add the byteflag and handler if it's justified

**Comment by dsohler** [comment] 2017-06-13 06:35
I repeat myself, but as said before: A whitelist would be a better solution.

**Comment by Lejo1** [comment] 2017-06-13 11:01
But if you have a whitelist the player just can rename the mod.

**Comment by dsohler** [comment] 2017-06-13 14:01
A functionality whitelist if course, not a function name or mod name whitelist.

**Comment by nerzhul** [comment] 2017-06-13 15:55
function whitelist = lock all players by default, it's not the usecase of CSM which is discover and do things, and server owners should lock things. Protected areas are not enabled or provided by core by default and there are many player which broke good players structures, that was not a reason to add global area with permission in core.

**Comment by dsohler** [comment] 2017-06-13 17:13
> function whitelist = lock all players by default

Lock all CSM by default. If someone wants to play around with it there is always singleplayer or hosting an own server. on public servers not owned by the player the player should not be able to execute anything without the server owner allowing it (inb4 “hacked client yadda yadda”).

**Comment by paramat** [comment] 2017-06-15 17:54
The flavours PR should disable all the potentially problematic functions by default. Just like we disable fire and TNT in multiplayer by default.

> server owners should lock things

Our approach is to set the safest option as the default to help server newbies.

>  but if you have more lua api ideas which are really problematic tell me which call, it's simple, and i add the byteflag and handler if it's justified

This misses the point, which is "In the future it is likely that a function currently considered harmless will be used in a way we didn't forsee."

> it's not the usecase of CSM which is discover and do things,

That's an example of ignoring the problems, this attitude led to a release being made with no restrictions.

**Comment by nerzhul** [comment] 2017-06-15 17:59
i think we should close one of the issue to have correct discussion thread. duplicate #5915 
It's not easy to follow thread on 2 issues, there is one PR opened to solve things discussion should be done around solution please

**Closed** 2017-06-15 18:25 UTC
Labels: @ Script API, @ Server / Client / Env., Request / Suggestion

**Comment by paramat** [comment] 2017-06-15 19:33
Yes i was about to suggest this, fine by me.
