### ISSUE TITLE
IPA (iOS) release possible?

### ISSUE THREAD

**Issue by CrocodileCroco** [minetest/minetest#12689] opened 2022-08-12 16:37 UTC
## Problem

Lot of Minetest players want to be able to play on iOS (iPhone).

I know that it is not compatible with Apple's own ToS but instead i think we could release the app as an .IPA file, that would work with devices with AltStore on it (no jailbreak necessary), or that are Jailbreaked

## Solutions

I described it in "Problem" section

## Alternatives

None

## Additional context

None

**Comment by rubenwardy** [comment] 2022-08-12 16:42
Duplicate of #12176 and #12649

**Closed by rubenwardy** 2022-08-12 16:42 UTC
Labels: Feature request

**Comment by KingBBQ** [comment] 2022-11-09 12:30
just as a tip: you can use MultiCraft instead, it connects just fine to any Minetest servers, incl. Mods. https://github.com/MultiCraft
