### ISSUE TITLE
minetest.wrap_text equivalent?

### ISSUE THREAD

**Issue by Tmanyo** [minetest/minetest#6033] opened 2017-06-23 02:57 UTC
Whenever I try to use minetest.wrap_text it does not seem to work.  It always says that I am attempting to call field 'wrap_text' (a nil value).  So I wanted to wrap my text in a formspec that I am making today and decided to write my own function.  It seems to do what minetest.wrap_text(str, limit) should do and it consumes quite a few less lines in the lua file.

**Comment by octacian** [comment] 2017-06-23 05:13
`minetest.wrap_text` is not a part of the API. It is not documented, nor has it every been to my knowledge.

**Comment by sfan5** [comment] 2017-06-23 10:42
it is part of the api: see [here](https://github.com/minetest/minetest/blob/2652d8db19fb2758de1da4c04ce169f80c87e5c7/doc/lua_api.txt#L2119)

which Minetest version are you using?

**Comment by octacian** [comment] 2017-06-23 14:07
huh, Must've been added recently. Gotta remember that rubenwardy's nice formatted API isn't always the most up-to-date. Whoops. However, according to git log, this feature wasn't really added all that recently that I see O_o. Very unclear to me, sorry.

**Comment by Tmanyo** [comment] 2017-06-23 14:23
I have tried using it before even back in 0.4.13 I think is the first time I tried using it.  It doesn't work on any version from what I can tell.

**Comment by Wuzzy2** [comment] 2017-06-26 17:33
I have tested in 0.4.16, and can confirm. I used `luacmd` to test.

Apparently the function does not obey its documentation and returns something different than promised.

Actually, it returns a *table* of strings. As if the source string has been splitted. There are no newlines. This doesn't look useful.

To test for yourself, just try to call `minetest.wrap_text` with help of the `luacmd` and experiment a bit. You will see what happens.

**Comment by SmallJoker** [comment] 2017-08-10 08:17
The issue is about that the function does not exist or doesn't work. Closing because Wuzzy2 confirmed that it works. Either your builtin code wasn't up to date or the function was overwritten with `nil` in your mod.

**Closed by SmallJoker** 2017-08-10 08:17 UTC
Labels: @ Script API, Unconfirmed bug

**Comment by Wuzzy2** [comment] 2017-08-11 03:01
Jeez. Opening a new issue because the function is obviously broken.
