### ISSUE TITLE
lighting glitch

### ISSUE THREAD

**Issue by RHRhino** [minetest/minetest#3964] opened 2016-04-05 19:13 UTC
It looks like daylight/moonlight, but at y= -1000. The light intensity changed with the time.
![screenshot_20160405_210345](https://cloud.githubusercontent.com/assets/6941454/14294531/f19cbe68-fb71-11e5-9298-a6eb12a647d2.png)
![screenshot_20160405_210353](https://cloud.githubusercontent.com/assets/6941454/14294532/f30fe022-fb71-11e5-80ef-db34f750b9d5.png)

**Comment by est31** [comment] 2016-04-05 19:23
How to reproduce?

**Comment by paramat** [comment] 2016-04-05 21:36
The exact y value of the brightest node will be helpful to know.

**Comment by Fixer-007** [comment] 2016-04-05 23:53
What minetest build/OS/videocard? Mapgen, seed, coordinates, settings? How much I need to stay to see it? Any torches?

**Comment by paramat** [comment] 2016-04-06 13:55
@RHRhino ^

**Comment by RHRhino** [comment] 2016-04-06 17:34
> How to reproduce?

Right now I didn't found a way to reproduce it. :confused: 
seed: 1047156058171512875 
coordinates: -78, 1044, 134

> The exact y value of the brightest node will be helpful to know.

I think originally it was at y=-1040, but you can change it (see screenshots below)

> Is your minetest build older than 30 Mar 2016?

No, mine is not. I'm playing with Krocks build 0.4.13-dev_MSVC, 150405 on Craigs Server. Maybe his version is outdated. @davisonio what is the server version?

> (there was light in caves bug fixed) 

I know that tall buildings have light glitches because the roof isn't loaded, so they are fully lit, but I'm mining at y=-1000, there should never be daylight, right?

**Story:** I found this bug when I was mining, because there was no torch around, but broad daylight. I wondered and was curious what happened if I change the time to night (I have that priv on the server) and recognized that it is rather connected with the day/night lighting than with normal light emitting sources (e.g. torch, lava). Placing a node e.g. cobble at its position, removes the "glitched node". I also disabled smooth lightning to make it better visible in the screenshots.
![screenshot_20160406_180420](https://cloud.githubusercontent.com/assets/6941454/14324809/b9145f3c-fc26-11e5-9a5f-6855206deaa3.png)
![screenshot_20160406_180457](https://cloud.githubusercontent.com/assets/6941454/14324810/b91c0d7c-fc26-11e5-9fb7-67b621eff81a.png)
![screenshot_20160406_180501](https://cloud.githubusercontent.com/assets/6941454/14324811/b9223ad0-fc26-11e5-9ef6-c481ecb66107.png)
![screenshot_20160406_180507](https://cloud.githubusercontent.com/assets/6941454/14324812/b926299c-fc26-11e5-8b32-cfd8c61418d3.png)
![screenshot_20160406_180513](https://cloud.githubusercontent.com/assets/6941454/14324813/b92c7176-fc26-11e5-8d51-2a65f57c977e.png)

**Comment by davisonio** [comment] 2016-04-06 17:42
> Is your minetest build older than 30 Mar 2016?
> No, mine is not. I'm playing with Krocks build 0.4.13-dev_MSVC, 150405 on Craigs Server. Maybe his version is outdated. @davisonio what is the server version?

The version is quite old, probably before February but after the start of January.

**Comment by Fixer-007** [comment] 2016-04-06 20:51
What mapgen? v7 / v6 / valleys? I will try to reproduce it again, I know there was a really rare light in caves near water bug, but it is elusive and hard to reproduce for me.

**Comment by paramat** [comment] 2016-04-07 02:04
> The version is quite old, probably before February but after the start of January.

This bug is probably the one fixed recently, which indeed was to do with the calculation of day and night lighting values. If anyone can get the commit number of the version you're using that will help.

**Comment by Fixer-007** [comment] 2016-04-07 12:36
Should be 01ae43c

**Comment by paramat** [comment] 2016-04-08 02:09
01ae43c is after the lighting bug fix. And yes it's the server version that is important.

**Comment by paramat** [comment] 2016-04-11 00:04
The light-in-caves bug was related to day/night lighting and this looks similar to that.
If this is that bug, which would mean you were using a server version between 0338c2eb91ca2ba19551aaa23bbfb46552cee9ac and 597c1d73da38ab299eb440a3429fce04da10cf05
However the server seems to be:

> The version is quite old, probably before February but after the start of January.

**Comment by Zeno-** [comment] 2016-04-11 01:58
What does the server version have to do with anything when this is a client-side unconfirmed bug?

**Comment by RHRhino** [comment] 2016-07-24 19:20
The bug is still there with after @davisonio updated the server to .14-dev  2ba8ad1 
![screenshot_20160724_211321](https://cloud.githubusercontent.com/assets/6941454/17085886/0d871966-51e4-11e6-8db7-b13f0d7ee8ad.png)

**Comment by SmallJoker** [comment] 2016-07-24 19:37
Could this be caused by a delay in the light update queue (if there's something like that)?
A very similar light bug can be produced by placing a light emitting node next to a block border on protected area. The client updates the light when a node is placed but before it's done completely it gets interrupted by the server that tells the client to remove the node again. (And "reset" the light)
The best way to test this is on a server with the spawn coordinate `0, 0, 0`. With some luck you get a 3 bright and one dark, correct lightened, mapblock.

**Comment by paramat** [comment] 2016-07-26 01:18
This could be triggered by a mod, anything that uses the engine's 'updateLighting()' can cause lighting bugs. For example placement of schematics or use of a non-mapgen-object voxelmanip.

**Comment by davisonio** [comment] 2016-09-10 14:49
In https://github.com/davisonio/craig-server_game/issues/76 @RHRhino has shown that this lighting bug seems to be caused by super glow glass from the moreblocks mod.


Super glow glass uses `light_source = 15` ([link](https://github.com/davisonio/craig-server_game/blob/master/mods/moreblocks/nodes.lua#L287)) when the maximum recommended in the [minetest docs](http://dev.minetest.net/minetest.register_node) is `14`. 

I think the bug we have here is that when you set `light_source` to more than `14` it causes the light to stay there permenantly even when you've removed the node.

**Comment by paramat** [comment] 2016-09-10 15:56
Good discovery, obviously we need to limit the light level that can be set for nodes to 14.
15 is reserved for sunlight which may explain why the light has unlimited propagation.

**Comment by Fixer-007** [comment] 2016-09-11 19:04
moreblocks needs fix?

**Comment by paramat** [comment] 2016-09-11 21:32
Perhaps we limit the light source value here? https://github.com/minetest/minetest/blob/master/builtin/game/register.lua#L120

**Comment by paramat** [comment] 2016-09-11 21:37
Now making PR.

**Comment by paramat** [comment] 2016-09-11 21:58
#4519

**Comment by paramat** [comment] 2016-09-15 04:34
#4519 just a note of maximum, is merged.

**Closed by paramat** 2016-09-15 04:34 UTC
Labels: @ Documentation, Bug

**Comment by paramat** [comment] 2016-09-17 08:38
#4523 merged.

**Comment by paramat** [comment] 2016-09-21 03:54
@RHRhino @davisonio I discovered how to fix the lighting bug, in the bright column of air place nodes in a column at least 16 nodes tall, tall enough to replace every air node lit by the bug, then mine those nodes.

**Comment by RHRhino** [comment] 2016-09-21 10:50
@paramat is this the only way to update those wrongly lit air nodes?

**Comment by paramat** [comment] 2016-09-22 03:19
Possibly not but the only one i have discovered.

**Comment by Fixer-007** [comment] 2016-09-22 11:29
@RHRhino try mapfix mod, should work.
