### ISSUE TITLE
Better controls on Android are a serious requirement.

### ISSUE THREAD

**Issue by easyaspi314** [minetest/minetest#1750] opened 2014-10-20 01:56 UTC
_(Can someone label this, I do not know how)_

On Android, the touch targets are either with the wrong hitbox, ridiculously small, too sensitive, not sensitive enough, clumsy,  or not even selectable.

 **Examples:**

On inventory screens, the extreme corners of the screen are **not touchable**. I think it might be related to the block interaction area, where you can not place/destroy blocks on the edges of the screen. This makes creative, chests, and crafting _very_ difficult.

The last hot bar slot is _not selectable_.

~~The arrow keys lack proper distinctiveness and accuracy, and I find myself going left instead of forward, causing cliff falls and more.~~

~~Those stupid jump/sneak buttons. They are impossible to use on a small screen, especially with a case. I can't sneak. And how the heck do you fly? I had to enable double-tap in minetest.conf and constantly grant myself fly. And even then, I keep accidentally (de)activating it!~~

 _Try to build a house. Or pillar jump. Or block off a stream._ That double tap has to be better. Maybe double tap, then after that, blocks instantly place until 1-2 seconds are between that. IDK how difficult that would be to enable. Also, the delay between breaking blocks is _too short_. A diamond pick is more destructive than useful, as I find myself breaking multiple blocks before I can get a chance to lift my finger. 

When there is a popup for text edit, can the keyboard request focus? If it is in an XML layout file, inside the EditText open and close you can put <requestFocus /> but from the looks of it, it might be a NDK dialog not by Java or XML. I know nothing about C++ or Lua of that is the case.

Some _Minecraft Pocket Edition_ controls would be better, as it makes it look and act more like a _native game_ rather than a klutzy emulator. I find that the unofficial Overcraft 2 seems to have a better GUI than this. (Edit: Sorry, I was not being very nice or neutral there.  :( )
//////////////////
EDIT by paramat: Deleted resolved issues.

**Comment by rubenwardy** [comment] 2016-04-05 18:36
Multicraft has a nicer UI than us :'(

**Comment by 0-afflatus** [comment] 2016-04-06 01:13
Apparently it does, but Multicraft leaves players on Minetest servers somewhat disabled due to the lack of proper right-click support. Many players would actually use a proper MT client (it is free after all) if the user experience was better and the feedback I'm getting says that it is close to Good Enough for players to start considering making the switch. I have a lot of Multicraft users on my server and I'm getting some really good feedback about what handheld users need, so I'm going to start lobbying for the necessary changes on their behalf, so I can start weaning them off onto a proper client.

**Comment by easyaspi314** [comment] 2016-04-06 01:14
+1

**Comment by MoNTE48** [comment] 2016-04-25 20:56
I would be happy to assist in this issue.

**Comment by paramat** [comment] 2017-09-21 22:26
@MoNTE48 we would very much like to have new movement controls, as many mobile users prefer a joystick control, could you help or maybe direct us to the code to use?

**Comment by paramat** [comment] 2017-09-21 23:04
Discussion http://irc.minetest.net/minetest-hub/2017-09-21#i_5084160
We are losing mobile players to often problematic apps due to bad controls.

**Comment by paramat** [comment] 2017-10-12 17:25
Does Freeminer have improved controls? We are allowed to use their code now.

**Comment by paramat** [comment] 2018-04-11 19:11
Joystick improved #7126 
Now what improvements can we make to the jump / down buttons?
I think the up / jump button should use a reversal of the down arrow, it obscures the world less and is more descriptive.
> Those stupid jump/sneak buttons. They are impossible to use on a small screen, especially with a case. I can't sneak.

@srifqi

**Comment by paramat** [comment] 2018-04-12 21:33
Thanks that really helps. The icons themselves don't necesssarily need to be taller but they should be placed higher up the screen.

**Comment by Wayward1** [comment] 2018-04-12 22:33
You're right, that could work as well.

**Comment by paramat** [comment] 2018-04-14 16:49
@srifqi

**Comment by paramat** [comment] 2018-06-20 19:01
So controls have been improved a lot, any remaining high priority control issues?
I guess lack of sprint is one #2873

**Comment by paramat** [comment] 2018-07-10 22:37
#7477 merged.

**Comment by juozaspo** [comment] 2018-07-11 05:50
@paramat cann't tell if any of the issues above is a problem, I didn't notice any or they didn't bother me much. To realy test everything the stable branch and an official app both must be updated.

**Comment by codexp** [comment] 2018-07-11 09:40
The only thing I noticed in #7477 is that the menu button is not aligned with zoom and aux button. 
It sits on the very edge by itself. Shouldn't it be in line with others and have same spacing to others?

![image](https://user-images.githubusercontent.com/6502486/42563582-e4163472-84fe-11e8-9636-a9d1c2b1ce60.png)

Also the icon is a little bit smaller.

**Comment by paramat** [comment] 2018-07-11 19:01
What concerns me about the menu and inventory buttons is they may be too close to the edge to use with a case?
I agree it would look better moved away from the edge a little so that it has the same gap from the edge as the others.
@srifqi

**Comment by juozaspo** [comment] 2018-07-11 21:23
Not sure if this is present in current master, but  I found some ui problems in current App Store build, such as some controls on right bottom side overlaping hotbar, after renaming minetest.conf.
![screenshot_20180712-001009](https://user-images.githubusercontent.com/6626242/42599822-2ae225d6-8569-11e8-88bd-56a13a07b16c.png)
Also debug information doesn't fit the screen, the font might be too large, no wrapping on edge.

**Comment by codexp** [comment] 2018-07-13 00:32
Btw left up and down buttons in 0.4.17.1 are on the actual edge of any smartphones with curved edge screen like the S9+. It is really awkward.

**Comment by paramat** [comment] 2018-07-13 01:32
codexp, maybe fixed in #7498 ?

**Comment by paramat** [comment] 2018-07-13 01:59
That seems more an issue caused by silly smartphone design. It look like the longer screen edges are actually radiused on the S9+, so i guess buttons cannot be too close to the edge?
From a review:
"My only nitpick with this curved panel is that it can sometimes be difficult to press buttons on the extreme edges of the display; on more than one occasion I had to press twice for something to register."

**Comment by rubenwardy** [comment] 2018-07-13 08:45
They're very good for watching videos

**Comment by paramat** [comment] 2018-07-14 14:16
Looks like we need top/bottom margins for Android then :)

**Comment by codexp** [comment] 2018-07-14 17:57
I'd suggest an adjustable grid layout for hud.

**Comment by paramat** [comment] 2018-08-04 16:39
This issue is attended too. There are some additional issues mentioned here but those should be split up into individual new issues.

**Closed by paramat** 2018-08-04 16:39 UTC
Labels: @ Client / Audiovisuals, @ Client / Controls / Input, Android, High priority, Request / Suggestion

**Comment by guy12345678910** [comment] 2019-10-28 17:33
How do i fly when i enable fly mode and double jump I just double jump
Tell me how to fly plzzz
