### ISSUE TITLE
Coloured lighting

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#5202] opened 2017-02-10 12:07 UTC
The title says It All I would like to have colored Lighting [I Know It's a Minecraft mod screenshot but it shows what I want very well](http://i44.tinypic.com/13z086x.png)

**Comment by juhdanad** [comment] 2017-02-10 12:52
With the current lighting model only 7 colors are implementable properly, others change their color with distance (if you want to know why, read [this](https://www.seedofandromeda.com/blogs/30-fast-flood-fill-lighting-in-a-blocky-voxel-game-pt-2) ).
The colors are: white, red, yellow, green, cyan, blue, magenta.
The reason why it is not implemented is storage (and performance). By having three color components, a node consumes 6 bytes instead of 4 (1.5x larger world files). Also the extra space is unused for nodes that do not let light through (dirt, stone). When you place a white light source, Minetest has to compute lights three times.
Further discussion about other lighting systems: http://irc.minetest.ru/minetest-dev/2016-12-30#i_4773907

**Comment by tobyplowy** [comment] 2017-02-10 13:01
@juhdanad you are the god of colour features in minetest at this point XD So if you say It's A Bad Idea It really is BAD! Thx for explaining

**Comment by Ekdohibs** [comment] 2017-02-10 13:12
@juhdanad I was reading the IRC discussion about lighting, and I was wondering: what about storing the direction each node gets its light from, and then store the complete light information at mapblock borders (where we can use more space, since there are less nodes)? Even for the case of coloured lighting, it would amount to a total of something like 8^4 (red, green, blue, sunlight), so that would still fit in two bytes (actually, 1 and a half byte) and not eat too much memory. However, I fear that even then, while increasing LIGHT_MAX will not cost too much memory, it can cause too many updates, unless we find a way to defer those of unloaded mapblocks.

**Comment by juhdanad** [comment] 2017-02-10 13:40
@tobyplowy I'm certainly not a god! And it is not a bad idea, colored lighting would be wonderful (imagine a Minetest church with stained glass windows). I don't want to discourage you, I wrote these notes to help you and anybody who wants colored lighting in finding a new, even better lighting model which is capable of storing colors. Because (in my opinion) if you really want a feature, think on how would you implement it and share your ideas with the community!

@Ekdohibs if you do not store colored sunlight, it is not possible to make stained glass realistic. Surface nodes are 33% of all nodes in a block. This means that with your implementation (but with colored sunlight) the extra light information would be 4056 bytes (current block size is 16384 bytes). This is a 1.25x increase.  If lighting is not cached at the block borders, the system still works, but you can not get the light levels of nodes unless you load all its 26 neighbor blocks.
The drawback of this reference method is that it is slow to get the light level of a node compared to the current implementation.

**Comment by tobyplowy** [comment] 2017-02-10 13:45
sadly I can't program this myself if I could I wuld already started work on it :(

**Comment by paramat** [comment] 2017-02-10 15:29
Fairly sure this is a duplicate.
I disapprove, i think colored light is fairly insignificant and does not justify the rewrite involved or the amount of mapnode data needed, there would be many more important and useful thing to do with the mapnode data, such as light range.
In most scenes you would want whiteish light, only very occasionally would coloured light be used and would not have much impact.
Let's concentrate on more important things instead of completely rewriting lighting for fancy but unessential effects. We are only just about to finally get the current lighting system working at last.

**Comment by sfan5** [comment] 2017-02-10 16:18
duplicate of #2670

**Closed** 2017-12-17 03:31 UTC
Labels: @ Client / Audiovisuals, Request / Suggestion
