### ISSUE TITLE
[0.4.13-RC] Bumpy Item Textures

### ISSUE THREAD

**Issue by WidDosMT** [minetest/minetest#3016] opened 2015-08-06 16:31 UTC
This been a issue for awhile now. since 0.4.11. But I guess will be fixed before final Build.

![screenshot_20150806_122556](https://cloud.githubusercontent.com/assets/11810887/9117273/184ffaac-3c37-11e5-8e11-897d00b0e40a.png)
![screenshot_20150806_122659](https://cloud.githubusercontent.com/assets/11810887/9117274/18532466-3c37-11e5-9e4e-b9b943f3da1d.png)

**Comment by PilzAdam** [comment] 2015-08-06 16:34
Do you have bumpmapping enabled?

**Comment by WidDosMT** [comment] 2015-08-06 16:35
No, they are off.
I think it maybe since the rendering process goes on, form the game to the other wise. Since all the blocks are fine but when use a Item this happens.

**Comment by kilbith** [comment] 2015-08-06 16:40
Dupe of https://github.com/minetest/minetest/issues/2350

**Comment by est31** [comment] 2015-08-06 23:21
Agreed, dupe of #2350.

**Closed by est31** 2015-08-06 23:21 UTC
