### ISSUE TITLE
Send current PointedThing to the server

### ISSUE THREAD

**Issue by anon55555** [minetest/minetest#10467] opened 2020-10-05 13:11 UTC
## Problem

The server can't see what is currently being pointed by a client reliably.

## Solutions

An interact action like INTERACT_POINT could be sent whenever the current pointed thing changes. Something to access this via Lua would also be added.

## Additional context

Hacks involving server side raycasting have been proposed, but they aren't 100% reliable, because of e.g. view bobbing and objects can't be pointed while digging.

**Comment by sfan5** [comment] 2020-10-05 14:39
What's the usecase here?
Also this is pretty much a duplicate of #7317 and/or #7743.

Giving CSM access to the pointed location (#9587) is much better in regards to latency, performance.

**Comment by rubenwardy** [comment] 2020-10-05 14:47
I'm not convinced that the increased accuracy makes up for the inaccuracy caused by latency. CSM should have access to the current pointed thing, and I think that there should be a method for SSM to get the pointed_thing from a raycase

**Comment by anon55555** [comment] 2020-10-05 15:33
Why is an interaction more affected by latency than the player position sent to the server.

**Comment by paramat** [comment] 2020-10-05 16:16
> An interact action like INTERACT_POINT could be sent whenever the current pointed thing changes

A problem with this is that it would happen very rapidly as the player moves the view direction around, especially in creative mode with the longer pointing range, lots of extra network traffic.

**Comment by anon55555** [comment] 2020-10-05 19:59
I did some tests in creative mode with a pointed range of 10, the pointed thing changes per second were about 5 when building, 10 when walking looking at the ground, 20 when turning fast and 30 moving in fast mode looking at the ground.

**Comment by LoneWolfHT** [comment] 2020-10-10 15:18
Try playing CTF and see how much that changes when in combat.

I have movement_speed_fast set to 100 btw.

**Comment by paramat** [comment] 2020-10-10 15:48
Yes, the suggested implementation is overkill and too intensive.

This issue is a duplicate of (closed) #7317 , please discuss there.

**Closed by paramat** 2020-10-10 15:48 UTC
Labels: @ Script API, Duplicate, Feature request
