### ISSUE TITLE
Player's direction of view pitches up slightly when clicking

### ISSUE THREAD

**Issue by sloantothebone** [minetest/minetest#2985] opened 2015-08-01 18:43 UTC
To reproduce issue:
1. Click several times somewhere outside of Minetest to make sure nothing's wrong with your mouse.
2. Open minetest and open up any world.
3. Rapidly left click or right click.

**Comment by est31** [comment] 2015-08-01 18:55
Neither me nor @VanessaE can reproduce, its likely how @VanessaE said, you moved your mouse while clicking.

**Comment by nanepiwo** [comment] 2015-08-04 19:32
I can confirm. I am using a Linux laptop with separate keys for clicking, meaning it is not likely I am scrolling as well.

**Comment by sloantothebone** [comment] 2015-08-06 05:07
Thank you for confirming, what distro and desktop environment are yu using?

**Comment by nanepiwo** [comment] 2015-08-06 14:53
Xubuntu, and XFCE.

**Comment by sloantothebone** [comment] 2015-08-06 17:22
I'm usinf ubuntu gnome so it isn't DE specific.
What version of minetest are you using? I'm using dailys

**Comment by nanepiwo** [comment] 2015-08-07 13:32
Same, though I've seen this for quite some time.

**Comment by celeron55** [comment] 2015-08-18 10:31
Post your laptop models.

**Comment by Ekdohibs** [comment] 2015-08-18 10:40
I can confirm this happens when using laptop buttons, but it doesn't happen when using the buttons of an external mouse : it is likely the laptop buttons are causing interference with the touchpad.

**Comment by JohnWayne1986** [comment] 2015-08-18 11:00
That does not happen for me, tested with laptop buttons and mouse buttons (Fujitsu E782).

**Comment by nanepiwo** [comment] 2015-08-18 11:15
@celeron55 Its a Thinkpad, though I'm not exactly sure which model.

**Comment by kilbith** [comment] 2015-08-18 11:25
@nanepiwo Run this [script](https://www.dropbox.com/s/zvumec6g8gohyjz/system-report.sh?dl=0) (`sudo bash ./system-report.sh`) and share us the HTML file located on your desktop folder.

**Comment by celeron55** [comment] 2015-08-18 11:25
So far I have tested it not to happen on Dell M6800 and Asus A75V.

**Comment by celeron55** [comment] 2015-08-18 11:28
Those who have this issue could try opening xev and seeing what kind of output the mouse makes when clicking buttons that way - and paste the output here too.

**Comment by sloantothebone** [comment] 2015-08-18 21:56
My computer is a Compaq Presario CQ57, xev pasted at
http://hastebin.com/iwodawulid

**Comment by celeron55** [comment] 2015-08-19 09:19
@sloantothebone There are zero button presses happening in what you pasted.

**Comment by nanepiwo** [comment] 2015-09-04 00:28
@celeron55 

    ButtonPress event, serial 37, synthetic NO, window 0x2000001,
    root 0x94, subw 0x0, time 2610235334, (167,7), root:(761,301),
    state 0x0, button 1, same_screen YES

    ButtonRelease event, serial 37, synthetic NO, window 0x2000001,
    root 0x94, subw 0x0, time 2610235359, (167,7), root:(761,301),
    state 0x100, button 1, same_screen YES

@kilbith 

https://gist.github.com/nanepiwo/dfe36dfbedca14e61a95

**Comment by paramat** [comment] 2017-07-08 22:05
Hardware issue so close?

**Comment by SmallJoker** [comment] 2017-08-01 09:29
Closing. This seems to be hardware-related.

**Closed by SmallJoker** 2017-08-01 09:29 UTC
Labels: Possible close, Unconfirmed bug
