### ISSUE TITLE
anti aliasing has no effect

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#8459] opened 2019-04-08 05:25 UTC
Enable shaders, mipmap and anisotropic filtering, then:

1. set antialiasing to (none). Take a screenshot
![screenshot_20190407_221539](https://user-images.githubusercontent.com/1880041/55700417-03740100-5984-11e9-8c82-ca986fee07bd.png)
2. set antialiasing to (8x). Take another screenshot
![screenshot_20190407_221556](https://user-images.githubusercontent.com/1880041/55700418-040c9780-5984-11e9-9b99-b36cdd4778ea.png)
3. Run: 
```
composite screenshot1.png screenshot2.png -compose difference diff.png
```
![diff2](https://user-images.githubusercontent.com/1880041/55700370-dde6f780-5983-11e9-87cc-e64eb2beb6f9.png)
4. Inspect the `diff` output image.

Expected outcome: various delta pixels all over the place.
Actual outcome: clouds moved, no other pixels differ

Conclusion: 8x antialiasing doesn't do anything.

**Comment by sofar** [comment] 2019-04-08 06:25
What I'm looking for is something like this instead, after I force `pp_jimenezmlaa_color=16` for instance:

![diff4](https://user-images.githubusercontent.com/1880041/55702765-6ff2fe00-598c-11e9-97ff-688d2577798f.png)

**Comment by HybridDog** [comment] 2019-04-08 10:38
FSAA works for me but I do not like it: #6860 
There's an issue about removing the setting from the main menu: #8367

**Comment by Calinou** [comment] 2019-04-08 13:05
Make sure your grpahics driver isn't forcing MSAA in all applications. (This setting generally isn't effective in newer games, but it'll often work in applications using "legacy" OpenGL versions.)

**Comment by paramat** [comment] 2019-04-08 18:41
> Changing the antialiasing setting only works when I fully restart minetest.

Maybe this is the cause?

**Comment by juozaspo** [comment] 2019-04-08 19:55
> composite screenshot1.png screenshot1.png -compose difference diff.png
Make sure you're not comparing **first** screenshot against the **same** one in the command line, look for minor differences beetween screenshots and check command output image if it's shown there, look for things like clouds appearing in different spots or similar stuff

**Comment by sofar** [comment] 2019-04-08 20:06
> Make sure you're not comparing first screenshot against the same one 

then why are the clouds showing up in the difference?

**Comment by sofar** [comment] 2019-04-08 20:07
> Make sure your graphics driver isn't forcing MSAA in all applications.

I'm using the mesa radeonsi here in this case. Note my point about `pp_jimenezmlaa_color=16` which shows that the hardware can do antialiasing properly.

**Comment by HybridDog** [comment] 2019-11-08 14:53
> Make sure your graphics driver isn't forcing MSAA in all applications.

According to wikipedia, FSAA (full-scene anti-aliasing) is the same as SSAA (super-sampling anti-aliasing): https://en.wikipedia.org/wiki/Multisample_anti-aliasing#Definition, https://en.wikipedia.org/wiki/Spatial_anti-aliasing#Super_sampling_/_full-scene_anti-aliasing.
MSAA works differently because it only affects the edges of the graphical primitives (triangles); this can bee seen in minetest:
![minetest_antialias](https://user-images.githubusercontent.com/3192173/68485538-cc2e4100-023f-11ea-97b2-a91c0211af8a.png)
Why is the setting in minetest called FSAA?

**Comment by Calinou** [comment] 2019-11-08 19:03
> Why is the setting in minetest called FSAA and not MSAA?

It was probably an oversight. Fixing it would break existing configuration files, but I guess it's a small breakage.

**Comment by paramat** [comment] 2020-08-09 01:01
> Changing the antialiasing setting only works when I fully restart minetest.

> Maybe this is the cause?

This had no response, needs checking, could be the simple cause of this.

**Comment by Calinou** [comment] 2020-08-09 13:07
I don't think Minetest supports changing MSAA at run-time. Therefore, you need to restart Minetest to apply MSAA changes.

**Comment by paramat** [comment] 2020-08-09 19:01
Thanks, this unconfirmed bug needs retesting then.

**Comment by paramat** [comment] 2020-10-06 16:01
Seems likely to be a restart issue, so closing.

**Closed by paramat** 2020-10-06 16:01 UTC
Labels: @ Client / Audiovisuals, Possible close, Testing needed, Unconfirmed bug
