### ISSUE TITLE
[feature request] text overlay on nodes

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#2704] opened 2015-05-15 06:21 UTC
VanessaE's signs_lib is a very handy mod for displaying text on signs although many in one area can become slow and buggy, so why not add a feature that allows players and mod makers to apply text to a surface easily with a specific size and colour... e.g.   minetest.add_text[pos, param2, "#RGBHello World/nHow is life?", pointsize]

**Comment by kilbith** [comment] 2015-05-15 09:33
@RealBadAngel was working on it months ago, IIRC.

**Comment by C1ffisme** [comment] 2015-05-15 20:12
I think there was another issue on this, but I can't remember where.

**Comment by 4aiman** [comment] 2015-05-20 13:02
:+1:

**Comment by Pilcrow182** [comment] 2015-05-25 02:30
I agree, I'd love to see this happen, but it seems difficult, if not impossible, to do well.

AFAIK, the way signs_lib does it is by rendering the text as a texture on a flat, untargetable entity. The reason they get buggy and slow is because entities have a tendency to slow things down, and because they sometimes unintentionally de-spawn. Putting that method into the engine might make it marginally faster but probably won't fix much, as the same problems will be there either way.

It would be much better if we could change the actual node's texture, but that would require individual nodes to be able to have unique textures and it would also require on-the-fly texture changing, which both sound like HUGE projects in my opinion...

It might relieve _some_ of the tension if we had official way to define a hover-over dialog; a box that opens when players hover over a node, but doesn't take away mouse control and disappears if the player turns away from said node. This isn't exactly a solution, though, and has the same problems as infotext; it's only be visible if a player is close enough and looking directly at the node...

Take what I say with a grain of salt though; I don't know C/C++, so my understanding of the engine may be seriously flawed...

**Comment by tenplus1** [comment] 2015-05-25 07:55
How about a text overlay node that is placed on top of another node kinda like the ladders but instead creates it's own texture with the text provided ?  The only drawback of this seems to be that it uses a whole node for text...

**Comment by VanessaE** [comment] 2015-05-27 01:19
Related:  https://github.com/minetest/minetest/issues/1367

**Comment by paramat** [comment] 2016-05-10 17:55
Duplicate of #1367

**Closed by paramat** 2016-05-10 17:55 UTC
Labels: Duplicate, Enhancement, Feature request
