### ISSUE TITLE
Item description bug

### ISSUE THREAD

**Issue by cdqwertz** [minetest/minetest#4142] opened 2016-05-19 08:01 UTC
I think the most of you know that I am working on a subgame called RPGtest. RPGtest displays the level, damage... of a tool in the item description. Since 0.4.14 is out it looks like this:

![bug](https://cloud.githubusercontent.com/assets/12814327/15386508/8614e1bc-1da8-11e6-97d5-4c8c2087df7f.png)

**Comment by Amaz1** [comment] 2016-05-19 10:51
I think that this was caused by 21079cc8ebae0bf694c1903c07bf3e1517feab99

**Comment by Zeno-** [comment] 2016-05-20 03:42
Can you please give an itemstring for an item that shows the bug? This is what I see:

![snapshot19](https://cloud.githubusercontent.com/assets/5899883/15416607/9cb6c212-1e90-11e6-875d-938e11a1f3f6.jpg)

**Comment by cdqwertz** [comment] 2016-05-20 07:43
`minetest --version
Minetest 0.4.14-dev (Linux)
Using Irrlicht 1.8.1
Build info: VER=0.4.14-dev BUILD_TYPE=Release RUN_IN_PLACE=1 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="."
`

**Comment by Zeno-** [comment] 2016-05-20 11:12
#4145

**Comment by Zeno-** [comment] 2016-05-20 14:29
88acda0

**Comment by Zeno-** [comment] 2016-07-09 07:13
This is related to irrlicht versions... perhaps there is an issue with the macro?

**Comment by Zeno-** [comment] 2016-07-09 07:17
Yes, the macro that checks the irrlicht version is incorrect. Whoops

**Comment by paramat** [comment] 2016-07-09 12:56
See #4299 for bug re-occurence.

**Comment by nerzhul** [comment] 2017-05-20 14:11
@cdqwertz is this always the case ?

**Comment by Zeno-** [comment] 2017-05-21 00:47
It's the macro for irrlicht version that needs fixing

**Comment by paramat** [comment] 2017-12-04 05:26
@cdqwertz @theraven262 more details needed, and link to code that reproduces the bug, to help us fix this.

**Comment by paramat** [comment] 2017-12-06 06:29
![screenshot_20171206_062740](https://user-images.githubusercontent.com/3686677/33647819-d281925c-da4e-11e7-952e-02cb48e873b8.png)

No bug in latest MT.

**Comment by paramat** [comment] 2017-12-06 10:17
Silly question but i'm having trouble running 'minetest --version', in what directory and game state do i enter this command?

**Comment by paramat** [comment] 2017-12-06 11:11
Thanks.

**Comment by paramat** [comment] 2017-12-18 18:37
Anyone still experiencing this?

**Comment by paramat** [comment] 2017-12-18 18:39
Is anyone experiencing this? Apparently it depends on Irrlicht version.

**Comment by paramat** [comment] 2017-12-18 18:50
Apparently this bug occurs with Irrlicht versions before 1.8.2.

**Comment by paramat** [comment] 2017-12-23 02:02
This bug has not been reproduced since MT 0.4.14, and we have merged the bugfix https://github.com/minetest/minetest/commit/8a1a9fdc24d29419422f0fb41095fd0388c4be9e since then, see PR thread #4766 
So #4302 should have been closed but wasn't.
I made #6822 to adopt it but that wasn't necessary, will close this and that.

**Closed by paramat** 2017-12-23 02:02 UTC
Labels: @ Client / Audiovisuals, Unconfirmed bug
