### ISSUE TITLE
Can't look/play (Incorrect XScreen mouse position)

### ISSUE THREAD

**Issue by nPHYN1T3** [minetest/minetest#12697] opened 2022-08-14 05:14 UTC
##### Minetest version
```
Minetest 5.6.0 (Linux)
Using Irrlicht 1.9.0mt7
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

##### OS / Hardware
Operating system: Garuda Linux
CPU: Ryzen 7 2700x
GPU0: GTX 1660
GPU1: GTX 1060

##### Summary
As soon as the game loads my character looks directly up and any attempt to move my mouse to look around just rotates around the axis direction pointing upwards.

##### Steps to reproduce
- Open Game
- Load World
- Speculate

The game worked fine before the recent update. Since the reproduction steps are kinda useless I can only speculate it's because the new game version is getting some XY data that is bunk due to my hardware config. I didn't note this above since it was noted to list GPU(s) for graphical problems my system is multi GPU and several XScreens with several monitors attached to each XScreen.

I just tried running the game on my secondary GPU and it runs correctly other than starting with my character still looking straight up. I'm guessing the game is trying to get mouse position for the other GPU/XScreen/Monitors rather than my primary GPU and the XScreen the game is running on.

**Comment by Zughy** [comment] 2022-08-14 09:59
It'd be useful to know the offender commit. Would you be so kind to do a bisect and find it?

**Comment by rubenwardy** [comment] 2022-08-14 12:48
Are you using Wayland? You need to use XWayland as well as Minetest doesn't support Wayland currently

**Comment by nPHYN1T3** [comment] 2022-08-14 12:51
X11, Wayland will not do multiGPU unless you like to waste resources and drag performance into the dirt.

What commit are you talking about? The commits that pushed it to 5.6.0?

**Comment by SwissalpS** [comment] 2022-08-14 13:09
the commit at which your minetest was built. The first six characters of the commit hash should suffice.

**Comment by nPHYN1T3** [comment] 2022-08-14 13:14
And how would I go about getting that?

Package build says 5.6.0-1 built on Aug 11th

**Comment by SwissalpS** [comment] 2022-08-14 13:21
launch minetest in terminal, often the window title has the build hash's first charachters in it.
Also `minetest --version` has that info.

**Comment by nPHYN1T3** [comment] 2022-08-14 13:22
I included minetest --version in the initial report. I don't have window titles with my WM.

**Comment by SwissalpS** [comment] 2022-08-14 13:24
well, while the devs look at it, I know of another player who complained that mouse sensitivity changed and mentioned that he had a similar behaviour. He fixed it by adjusting sensitivity in the advanced settings.

**Comment by nPHYN1T3** [comment] 2022-08-14 13:28
The sensitivity is fine on the other GPU. More so if this was about sense I'd be able to look around, just "insanely" but the input is locking looking straight up and all moving the mouse does it rotate around that axis.

**Comment by rollerozxa** [comment] 2022-08-14 16:16
> launch minetest in terminal, often the window title has the build hash's first charachters in it. Also `minetest --version` has that info.

They're using 5.6.0 stable, hence the lack of a build hash.

**Comment by auouymous** [comment] 2022-08-15 12:11
I have the same problem, the minetest window is on :0.0 and pointer warps to :0.1 (left of :0.0) when the game begins. Any movement causes the pointer to snap back to the center of :0.1 until escape is pressed to open the game menu.

bc59fcf5c5cc44ea18e93f64aca9c20be71c1b07 with irrlicht-mt-1.9.0.5 works, and 5cd7b0c6e4551fd53171fba8b30ac9f0a4e13a36 with irrlicht-mt-1.9.0.7 has the issue. I am unable to build any commits between those due to compile issues with both versions of irrlicht.

**Comment by auouymous** [comment] 2022-08-15 12:48
d631f21024bac626babe2e8eac4505210d368ffa (the commit before 71f6a5f44e0cb0e4ef57e942987ec8e76139452c) works with irrlicht-mt-1.9.0.6, so the issue is in irrlicht-mt-1.9.0.7.

**Comment by sfan5** [comment] 2022-08-15 14:59
XInput was enabled between .6 and .7, can you check whether reverting minetest/irrlicht@91edd214aa0e8a5e9192a2fc9188a19fc5bf135e fixes it?

**Comment by auouymous** [comment] 2022-08-15 20:51
https://github.com/minetest/irrlicht/commit/538c9e5cde425ecee1e802fd53344111683b60be works and https://github.com/minetest/irrlicht/commit/91edd214aa0e8a5e9192a2fc9188a19fc5bf135e causes the issue.

**Comment by sfan5** [comment] 2022-08-15 21:03
tagging @TheBrokenRail then who wrote original code

**Comment by Oblomov** [comment] 2022-08-16 09:48
The only thing that the Irrlicht change seems to do is to enable XInput2 by default so I strongly doubt it's the culprit _per se_. Manually enabling XInput2 on older Irrlicht commits is likely to cause the same issue.

**Comment by Oblomov** [comment] 2022-08-16 10:10
I've looked at the Irrlicht code and the main difference that jumps to the eye is that when using XInput2 the code uses `XIWarpPointer` whereas without it it uses `XWarpPointer` (see `source/Irrlicht/CIrrDeviceLinux.h` lines 210 and following. So this could be either Irrlicht using the wrong DeviceId for the mouse or some issues in the Xorg server itself.

**Comment by auouymous** [comment] 2022-08-16 13:55
The `DeviceId` value is correct. Running minetest on the left monitor works fine, and adding the width of the left monitor to the `x` value passed to XiWarpPointer fixes the issue with minetest running on the right monitor. So XiWarpPointer is treating both monitors as one wide monitor, even though they are independent displays which windows can't span across or move between.

https://gitlab.freedesktop.org/xorg/lib/libxi/-/issues/5 suggests it is an nvidia xinerama issue.

**Comment by nPHYN1T3** [comment] 2022-08-16 14:01
Sadly this is sounding more and more like the growing issue of assumptions being made as projects push towards Wayland or stock xrandr setups.

**Comment by Oblomov** [comment] 2022-08-18 06:07
If the bug is in the NVIDIA proprietary driver the only thing that can be done is to report it to them and hope that the fix it, because patching it Irrlicht-side by include the other screens'  offset would probably break Xinerama-enabled multi-Screen setups on vendors that can use Xorg's own drivers.

**Comment by auouymous** [comment] 2022-08-18 06:38
Seven year old issues are unlikely to be fixed, especially by nvidia, assuming it is their fault and not just xorg pointing fingers, because XWarpPointer works fine. The simplest fix is for irrlicht to read an IRRLICHT_DISABLE_XINPUT2 environment variable and force DeviceId to zero wherever it is initialized.

**Comment by Oblomov** [comment] 2022-08-18 06:49
The deviceid refers to the _input_ device, it has nothing to do with the screen selection and offset. At best with that environment variable it should toggle to the `XWarpPointer` call.

**Comment by auouymous** [comment] 2022-08-18 06:55
`DeviceId == 0` is what switches it to use XWarpPointer.

**Comment by nPHYN1T3** [comment] 2022-08-18 13:34
@Oblomov no xinerama here. This thread has been a lot of restating the previously stated. XScreens != xinerama. Xinerama can be used without nvidia as an X11 feature and an nVidia feature however that will draw everything as a single desktop which is exactly NOT what the affected users configurations are. We're using XScreens for differing reasons.

Again this sounds more like the game at some point only enumerates XScreen 0 which the co-ordinates IN the root may or may not be out of bounds. If you launch the game in the first enumerated XScreen the game is fine, if you launch in an XScreen outside the enumerated XScreen the pointer is out of bounds.

This is a problem with several Unity Games where devs will incorrectly query total screen size in one function but then window size in another. Same result where the input is then offset, or uncontrollable depending if you run the game Windowed, or full screen and depending on your XScreens layout (if they aren't symmetrical things get even "funesterer.")

**Comment by auouymous** [comment] 2022-08-18 21:12
```
    Option  "XINERAMA"  "Disable"
```

Ugh, I see xinerama while tired and think it is enabled. So if that bug only applies to xinerama then it is not the cause of this issue.

**Comment by Oblomov** [comment] 2022-08-19 06:12
@nPHYN1T3 the only programs that would be affected are those using `XIWarpPointer` so you're unlikely to see the effect (most programs use `XWarpPointer`, that doesn't seem to be affected). I will try whipping out a small test program.

Irrlicht itself does nothing special about the XScreen: it opens a connection to the diplay with `XOpenDisplay`  and gets the chosen screen number with `DefaultDisplay`, which returns whatever was set in `DISPLAY=:0.x`. All subsequent operations are done on the chosen Screen root window or in windows that are its children, so any issue with the wrong Screen being affected are server-side. The question that remains to be seen is if this is in the dix part of the server (and thus fixable, because it's FLOSS) or the ddx part of the server (which may or may not be fixable depending on which server driver is being used).

**Comment by scfarley** [comment] 2022-08-22 19:18
Playing with a little program I hobbled together in the past, it looks like `XIWarpPointer()` does move the pointer to the desired location on the correct screen, however, any motion of the pointer after that point sends it to the `:0.1` screen.  I am using the Nvidia drivers and `Xinerama` is not enabled.

I am basically running this:
```c
...
X_Dpy = XOpenDisplay(NULL));
root = XDefaultRootWindow(X_Dpy);
XQueryPointer(X_Dpy, root, &ret_root, &ret_child, &root_x, &root_y, &win_x, &win_y, &mask);
/* Allow user to move mouse then move it back after sleeping. */
sleep(4);
XIWarpPointer(X_Dpy, 2, None, ret_root, 0, 0, 0, 0, root_x, root_y);
XCloseDisplay(X_Dpy);
...
```

**Comment by auouymous** [comment] 2022-08-22 21:11
Blender reverted their switch to XiWarpPointer, mentioning a comment in the xserver code about missing multi-screen support.

https://developer.blender.org/rB165caafb99c6846e53d11c4e966990aaffc06cea

https://developer.blender.org/rB9461af299ca937ff36048f9198670eab6a6b233b

**Comment by sfan5** [comment] 2022-09-04 14:20
Does anyone want to submit a fix for this (that switches back to `XWarpPointer` in all cases)?

**Comment by auouymous** [comment] 2022-09-06 08:41
@sfan5 Are you asking for a full revert of https://github.com/minetest/irrlicht/commit/91edd214aa0e8a5e9192a2fc9188a19fc5bf135e?

**Comment by sfan5** [comment] 2022-09-06 09:22
No.

**Comment by sfan5** [comment] 2022-09-11 19:33
Interested people please test this commit https://github.com/minetest/irrlicht/commit/3447bb501c194f762f9b0d4d372735691df4a98f

**Comment by Desour** [comment] 2022-09-11 20:24
^ Actually, I recently bought a new mouse, and am using the xinput transformation matrix, and I had the spinning issues, until they disappeared after some commit. 
That being said, I can reproduce the issue with that commit, FYI.

**Comment by scfarley** [comment] 2022-09-12 02:57
> Interested people please test this commit [minetest/irrlicht@3447bb5](https://github.com/minetest/irrlicht/commit/3447bb501c194f762f9b0d4d372735691df4a98f)

That fixed it for my computer regardless of which XScreen I use.

**Comment by sfan5** [comment] 2022-09-12 07:20
@Desour I feared that might happen since a code comment mentioned this.
Maybe if there's some way to detect multi-head setups we can enable XI only if we know it's working. That'd fix both this bug and #8539 (though not the combination).

**Comment by sfan5** [comment] 2022-09-12 14:21
@Desour @scfarley please test again https://github.com/minetest/irrlicht/commit/78cd0893b4d1d128c8ba3bcbdd64adb8ed11e766

**Comment by auouymous** [comment] 2022-09-12 20:00
I don't have time to do it right now, but Xrandr.h can be used if `XScreenCount(XOpenDisplay(NULL)) > 1` to determine if the screen minetest is on is right of or below another screen. XIWarpPointer could then be used on multi-screen setups if minetest is moved to the left-most and top-most screen.

**Comment by nPHYN1T3** [comment] 2022-09-12 21:35
Who the F wants to play on the most awkward screen? lol This is why all my gaming/primary screens are center...no one wants to crank their head sideways for hours. Peripheral are for glances, short tasks, utilities...not media or gaming.

**Comment by scfarley** [comment] 2022-09-12 23:38
> please test again [minetest/irrlicht@78cd089](https://github.com/minetest/irrlicht/commit/78cd0893b4d1d128c8ba3bcbdd64adb8ed11e766)

That works for me.  Thank you.

**Comment by auouymous** [comment] 2022-09-13 00:45
It could also use Xrandr to calculate the X/Y coordinates of the current screen and add to the XIWarpPointer coordinates. Probably not any more work than finding the top-left screen and would enable xinput2 across all screens.

**Comment by nPHYN1T3** [comment] 2022-09-13 00:48
@auouymous This assumes xrandr understands which GPU the XScreens are on...and it doesn't. This will lead to just more mess for multi GPU users be it like me or various hybrid / mobile setups.

**Comment by auouymous** [comment] 2022-09-13 00:58
@nPHYN1T3 I don't know how the xinput2 transformation matrix works, or if it alters the resolution of a screen which could then throw off the computed X/Y offset. So top-left-most screen only or add environment variables and let the user figure out their own offset if they need xinput2.

**Comment by nPHYN1T3** [comment] 2022-09-13 01:04
There are already environment variables set. Open a term and echo $DISPLAY from one XScreen, then another. This does not help because things are only aware of what is shared on the same "DISPLAY" as them. This isn't about offset, this is about simply being on the wrong XScreen. Offsetting doesn't end up on the right XScreen or understand which direction that might be when things are not some simply linear +100 -100. Layouts can be very complex. Much like things are only aware of the shared DISPLAY they are on xrandr has the same limitation. It only knows what is on the GPU/XScreen from where it was called. Seems nothing just queries the root anymore.

**Comment by auouymous** [comment] 2022-09-13 01:20
@nPHYN1T3 The problem is in xorg's Xi library and will likely never be fixed because wayland is replacing it. We are simply trying to make minetest work for users who need multi-screen AND xinput2. An automatic solution would be best, but manually setting environment variables to offset the pointer would be acceptable if it was the only option.

**Comment by nPHYN1T3** [comment] 2022-09-13 01:24
Wayland isn't replacing anything for me as it breaks multigpu use cases. If the games direction is focused on Wayland this is a "won't fix" situation. I'll gladly entertain Wayland ONCE Wayland builds in GPU Segregation rather than slaving. Right now Wayland only slaves any GPU other than the primary and then dumps all the workload on that primary GPU. Straining the primary GPU and turning all the other GPU's into worthless output splitters that chew power and throw heat for no reason other than output splitting. Xrandr is the same (but with exponentially worse performance).

**Closed** 2022-09-13 06:43 UTC
Labels: Bug, Upstream issue, @ Client / Controls / Input
