### ISSUE TITLE
error while under credits tab (not loading logo)

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#2100] opened 2015-01-10 04:54 UTC
I'm using:
OS: windows 7 32-bit
Build: https://forum.minetest.net/viewtopic.php?f=42&t=9515&start=50#p167343
At commit: 56a89fd

Here is the error:
```
23:33:51: ERROR[main]: GUIFormSpecMenu::drawMenu() Draw images unable to load texture:
23:33:51: ERROR[main]: 	C:UsersThomasDownloadsminetest_releasetexturesbasepacklogo.png
23:33:51: ERROR[main]: GUIFormSpecMenu::drawMenu() Draw images unable to load texture:
23:33:51: ERROR[main]: 	C:UsersThomasDownloadsminetest_releasetexturesbasepacklogo.png
23:33:51: ERROR[main]: GUIFormSpecMenu::drawMenu() Draw images unable to load texture:
23:33:51: ERROR[main]: 	C:UsersThomasDownloadsminetest_releasetexturesbasepacklogo.png
```

**Comment by ShadowNinja** [comment] 2015-01-10 05:21
Duplicate of #2099, just with a different image.

**Comment by MT-Modder** [comment] 2015-01-10 05:22
Okay.

**Closed by ShadowNinja** 2015-01-10 05:21 UTC
Labels: @ Client / Audiovisuals, blocker, bug, duplicate, High priority
