### ISSUE TITLE
Feature: A Quit button for the main menu

### ISSUE THREAD

**Issue by mk-pmb** [minetest/minetest#10894] opened 2021-02-02 01:11 UTC
## Problem
I wanted to cleanly quit MT 5.3.0, using my pointer device.

## Solutions
I'd like a "Quit" button inside the window.

## Alternatives

* I could have clicked the window decoration's close button, but I wasn't sure whether that would exit MT "cleanly".
* We could add some kind of explanation or documentation to clarify that the window decoration's close button is a way to exit cleanly. (No we shouldn't.)
* I could have pressed a button and wait 2 seconds to switch my keyboard to the computer that runs MT, then press Escape, then press another button and again wait 2 seconds to switch my keyboard back.
* Various contraptions to send an emulated keystroke.

**Comment by rubenwardy** [comment] 2021-02-02 01:22
Duplicate of #8681

**Closed by rubenwardy** 2021-02-02 01:22 UTC
Labels: Feature request

**Comment by mk-pmb** [comment] 2021-02-02 01:27
Thanks for the pointer. I found it's also a dupe of 2426. I was too optimistic in thinking that the lack of this feature was just due to lack of inspiration.
