### ISSUE TITLE
Minetest chatroom keyboard acts strange

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#11190] opened 2021-04-14 11:14 UTC
##### Minetest version

```
Minetest 5.5.0-dev-88783679c (Linux)
Using Irrlicht 1.9.0mt2
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Ubuntu 20.04 LTS
CPU: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz

GPU model: ?
OpenGL version: ?

##### Summary

Minetest chatroom keyboard acts strange makes me hard to type commands. for example, `//unmark` becomes `//unmmrk`, etc.

**Comment by Emojigit** [comment] 2021-04-14 11:17
![圖片](https://user-images.githubusercontent.com/55009343/114701976-116c7180-9d56-11eb-89d9-21caf8704acc.png)
This is a chatroom record which the client used that strange version of minetest.

**Comment by Emojigit** [comment] 2021-04-14 12:01
![圖片](https://user-images.githubusercontent.com/55009343/114706885-251ad680-9d5c-11eb-9d06-1dae2a638772.png)
![圖片](https://user-images.githubusercontent.com/55009343/114706931-31069880-9d5c-11eb-81c8-398047249c49.png)

**Comment by sfan5** [comment] 2021-04-14 19:26
Does this happen on 5.4.1 or with 5.5.0-dev? (please test both)
We also need more information on the environment: Keyboard layout? Any IME?

**Comment by Emojigit** [comment] 2021-04-17 06:15
@sfan5 
> Does this happen on 5.4.1 or with 5.5.0-dev? (please test both)
> We also need more information on the environment: Keyboard layout? Any IME?
Keyboard layout: QWERTY
I don't know what is IME
I will compile 5.4.1 soon

**Comment by sfan5** [comment] 2021-04-17 09:08
IME -> https://en.wikipedia.org/wiki/Input_method

**Comment by Emojigit** [comment] 2021-04-17 11:32
> Does this happen on 5.4.1 or with 5.5.0-dev? (please test both)
> We also need more information on the environment: Keyboard layout? Any IME?

No problem on 5.4.1 and `5.5.0-dev-88783679c`

**Comment by Emojigit** [comment] 2021-04-17 11:33
> IME -> https://en.wikipedia.org/wiki/Input_method

English

**Comment by yw05** [comment] 2021-04-17 12:03
Regarding the IME issue: after the IME PRs got merged I noticed that the keyboard input might randomly "lock up" with Fcitx5 on ArchLinux (using Pinyin and us-altgr-intl) after some time, at least as of 52c0384bd. Currently I can reproduce it by spamming the "toggle chat console" (F10) button. However:
* While I can not enter anything or switch between keyboard layouts/imput methods after the keyboard input got "locked up", when I close the chat console (e.g. by double-clicking elsewhere) I could still move around.
* I could not reproduce this on a Debian VM without any IME (only the us-altgr-intl layout) with a106bfd45.
* I have not tested this with other IMEs yet.

**Comment by Emojigit** [comment] 2021-04-18 11:57
sometimes keyboard becomes "unavailable" on my current MT-dev version. Not tested on 5.4.1.

**Comment by Emojigit** [comment] 2021-04-18 11:58
> Sometimes keyboard becomes "unavailable" on `5.5.0-dev-88783679c`. Not tested on `5.4.1-stable`.

**Comment by yw05** [comment] 2021-04-18 18:19
@Emojigit Try this patch and see if you can reproduce the problem:
```diff
diff --git a/source/Irrlicht/CIrrDeviceLinux.cpp b/source/Irrlicht/CIrrDeviceLinux.cpp
index f482ec68e..ec3a52599 100644
--- a/source/Irrlicht/CIrrDeviceLinux.cpp
+++ b/source/Irrlicht/CIrrDeviceLinux.cpp
@@ -829,7 +829,7 @@ bool CIrrDeviceLinux::run()
 		{
 			XEvent event;
 			XNextEvent(XDisplay, &event);
-			if (acceptsIME() && XFilterEvent(&event, None))
+			if (XFilterEvent(&event, None))
 				continue;
 
 			switch (event.type)
@@ -1156,23 +1156,27 @@ bool CIrrDeviceLinux::run()
 				break;
 			} // end switch
 
-		} // end while
-
-		// Update IME information
-		if (XInputContext && GUIEnvironment)
-		{
-			gui::IGUIElement *elem = GUIEnvironment->getFocus();
-			if (elem && elem->acceptsIME())
+			// Update IME information
+			if (XInputContext && GUIEnvironment)
 			{
-				core::rect<s32> r = elem->getAbsolutePosition();
-				XPoint p;
-				p.x = (short)r.UpperLeftCorner.X;
-				p.y = (short)r.LowerRightCorner.Y;
-				XVaNestedList l = XVaCreateNestedList(0, XNSpotLocation, &p, NULL);
-				XSetICValues(XInputContext, XNPreeditAttributes, l, NULL);
-				XFree(l);
+				gui::IGUIElement *elem = GUIEnvironment->getFocus();
+				if (elem && elem->acceptsIME())
+				{
+					core::rect<s32> r = elem->getAbsolutePosition();
+					XPoint p;
+					p.x = (short)r.UpperLeftCorner.X;
+					p.y = (short)r.LowerRightCorner.Y;
+					XSetICFocus(XInputContext);
+					XVaNestedList l = XVaCreateNestedList(0, XNSpotLocation, &p, NULL);
+					XSetICValues(XInputContext, XNPreeditAttributes, l, NULL);
+					XFree(l);
+				} else {
+					XUnsetICFocus(XInputContext);
+				}
 			}
-		}
+
+		} // end while
+
 	}
 #endif //_IRR_COMPILE_WITH_X11_
 
```
Also, the `XMODIFIERS` environment variable includes the IM settings. Posting that might help as well (`echo $XMODIFIERS`)

**Comment by sfan5** [comment] 2021-04-18 19:22
> `+			if (XFilterEvent(&event, None))`

Not sure if that's a good idea.
This might need to be `if (XFilterEvent(&event, acceptsIME() ? None : XWindow))` to match pre-IME behaviour.

**Comment by yw05** [comment] 2021-04-19 08:36
I thought `None` implies the window associated with the XEvent? https://www.x.org/releases/current/doc/man/man3/XFilterEvent.3.xhtml
Also, from my interpretation, `XSetICFocus` and `XUnsetICFocus` basically sets and unsets the focus to the input context (which, I suppose, is attached to the IME).

**Comment by Emojigit** [comment] 2021-04-19 13:01
> Also, the `XMODIFIERS` environment variable includes the IM settings. Posting that might help as well (`echo $XMODIFIERS`)

```
$ echo $XMODIFIERS
@im=fcitx
```

**Comment by Emojigit** [comment] 2021-04-19 13:09
> Try this Irrlicht patch and see if you can still reproduce the problem (apparently skipping `XFilterEvent` when the IME is not used is a bad idea ...). I tested this patch with a few IMEs (including without any IME) on a Debian VM and did not notice anything in particular other than the Bopomofo (IBus) IM somehow filtering out the F10 key event.
cludes the IM settings. Posting that might help as well (`echo $XMODIFIERS`)

```
$ git apply /tmp/2
error: patch failed: source/Irrlicht/CIrrDeviceLinux.cpp:829
error: source/Irrlicht/CIrrDeviceLinux.cpp: patch does not apply
```

**Comment by Emojigit** [comment] 2021-04-19 13:16
I can successfully apply that patch after I use `--whitespace=fix`

**Comment by sfan5** [comment] 2021-04-19 14:39
@Emojigit  More importantly, can you confirm that the patch fixes it for you?

> I thought `None` implies the window associated with the XEvent? https://www.x.org/releases/current/doc/man/man3/XFilterEvent.3.xhtml

I think that too, but we determined that this somehow makes a difference when we prepared the IME PR (https://github.com/minetest/irrlicht/pull/23#discussion_r606372659).

**Comment by yw05** [comment] 2021-04-19 16:21
> > I thought `None` implies the window associated with the XEvent? https://www.x.org/releases/current/doc/man/man3/XFilterEvent.3.xhtml
> 
> I think that too, but we determined that this somehow makes a difference when we prepared the IME PR ([minetest/irrlicht#23 (comment)](https://github.com/minetest/irrlicht/pull/23#discussion_r606372659)).

I think I was a bit messed up a bit earlier, and yes, that does make a difference. However, I am not sure if that is needed because from my local tests the IME was disabled with `XUnsetICFocus` alone when the input field loses focus.

**Comment by sfan5** [comment] 2021-04-19 19:45
I determined the parameter does not make a difference and merged the original fix as:
https://github.com/minetest/irrlicht/commit/21cb990e75843d62182e82618a1e4ed7e1a9ecdf

**Closed by sfan5** 2021-04-19 19:45 UTC
Labels: @ Client / Controls / Input, Bug, Linux, Upstream issue
