### ISSUE TITLE
Feature request: Provide 2D screenshot or even 3D chunk snapshots of servers in the "Join Game" tab.

### ISSUE THREAD

**Issue by Anon7250** [minetest/minetest#13051] opened 2022-12-17 06:29 UTC
Note: I'm new. Please let me know if there is a better place to post this idea. Thank you.

## Problem

The process of finding & test-driving multiplayer servers & picking a good server to join is frustrating because you need to sign up, gain access to the server, and then discover the best parts of the server manually.

## Solutions

What if Minetest provides a "Find a Server" world in the "Join Game" tab where each server presents a chunk of their best contents, so that players can easily preview the servers and decide which server to join? (The game can take 3D screenshots of this chunk every day, and update the corresponding chunk on "Find a World" server.)

## Alternatives

Alternatively, instead of creating a single "find a server" world, and instead of a complicated chunk snapshot, we can just ask the server owners to take a 2D screenshot in game, to serve as the thumbnail for their server in the "Join Game" tab.

## Additional context

Hi, I have a random idea I've always wanted for both Minetest and Minecraft, (but it suits Minetest better):

Server discovery is hard for new players. Minetest has the "Join Game" tab. It's better than Minecraft (where you'd have to visit random websites where people/bots "vote" for the top servers).

But we can improve the "join game" tab if the game can take 2D or even 3D "screenshots" of the best parts of each server, and if players can see these screenshots without having to register for an account.

Perhaps we can even make an official "Find a World" server where each chunk features the best content from a different server. Server owners would choose a chunk to represent their server. And the game can take 3D screenshots of this chunk every day, and update the corresponding chunk on "Find a World" server.

Just an idea. I don't know how / whether it will be easy to implement.

**Comment by sfan5** [comment] 2022-12-17 10:29
related #8710

**Comment by 56independent** [comment] 2022-12-17 10:44
How would you define "best"?
I might be able to make a lazy implementation with uploading small thumbnails of the server, but i think a "taster package" would be a good idea; `join local` which takes a small section of the world around a spawnpoint and lets you move around in a very small singleplayer world to taste the game

**Comment by Anon7250** [comment] 2022-12-18 20:43
> How would you define "best"?

It'll be hard to choose the "best" overall chunk across all servers. I was hoping to keep the existing sorting order of the "Join Game" tab. But maybe we can try something new (if we have a grid of chunks from different servers, we could even have something like r/place)

From a server owner's perspective, it's up to them. They should have a choice (which chunk/snapshot to represent the server with)

**Comment by sfan5** [comment] 2022-12-20 09:25
> `join local` which takes a small section of the world around a spawnpoint and lets you move around in a very small singleplayer world to taste the game

Note that to display a chunk from a server the client would still need to download (potentially) all textures/sounds/models from the server so not much is gained over just joining it for real.

**Comment by Anon7250** [comment] 2022-12-20 19:28
Hmm that's a good point. I have not played enough Minetest servers but I'm sure each server's customization is crucial to their identities. 

I have a few naive ideas to solve this problem:

1. Try to bundle relevant custom texture/sound/model to the exported chunk in this `join local` world, and set a size limit. (And if more data is needed, first load the base map and then ask user whether they would like to download them)
2. Separate "Vanilla" chunks from modded chunks into different groups (groups are not too far away from each other but just enough so that a mod/texture/model/etc is only loaded if you visit a group of servers using those mods)
3. Have some kind of "lazy loading" block (like the lazy loading images on HTML) which would just be a fuzzy screenshot of the actual custom block, until it becoms visible on screen, and starts loading.

**Comment by rubenwardy** [comment] 2022-12-20 19:39
:-1: for complicated world previews, if servers want to show their map they can add it to their screenshot/thumbnail/banner.

Should be closed as a duplicate of #8710

**Comment by Anon7250** [comment] 2022-12-20 20:32
Yeah it's starting to sound too complicated. Please feel free to close it.

**Closed** 2022-12-21 13:14 UTC
Labels: Feature request, Possible close, @ Mainmenu
