### ISSUE TITLE
Numblock does not work in text entry fields, left/right instead of 4/5

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#1898] opened 2014-12-03 21:49 UTC
The numblock does not work correctly in entry fields. For example the "New World" window, when entering the name, then 0, 3 and 9 are working correctly on the number block, but the other keys are trying to execute their designated function, like left, right, up and down.

This happens under Ubuntu 14.04 with a US keyboard/layout.

**Comment by ngosang** [comment] 2015-01-25 21:01
It's an Irrlicht problem. I compiled minetest with Irrlicht 1.9 (development) and the problem is fixed.
http://sourceforge.net/p/irrlicht/code/HEAD/tree/trunk/

**Comment by paramat** [comment] 2016-03-30 22:57
Closing as is upstream issue and fixed in Irrlicht 1.9.

**Closed by paramat** 2016-03-30 22:57 UTC
Labels: @ Client / Audiovisuals, Bug, Upstream issue

**Comment by debagos** [comment] 2021-05-07 18:00
Soooo here we are now, with a forked Irrlicht :sweat_smile:
Is there an possibility that we will be able to use _copy&paste_ as expected in the future?

**Comment by sfan5** [comment] 2021-05-07 18:34
The bug for that is still open, it'll probably get fixed before 5.5.0 -> #7830

**Comment by debagos** [comment] 2021-05-07 18:49
Oh sorry, I confused two tabs in my browser :neutral_face:
Of course my question was meant for the #7830 issue...
