### ISSUE TITLE
Collaboration with Terasology project?

### ISSUE THREAD

**Issue by brylie** [minetest/minetest#6322] opened 2017-08-27 06:35 UTC
Continuing discussion from #6309

> Is there another voxel game engine that Minetest development could be aligned with? I.e. a fuller-developed game engine might give the game a boost in many ways, while allowing MT developers to focus on game features/mechanics.

While Minetest engine is making incremental progress with engine features, such as dynamic shadows, it may be a long and winding road to enhance the engine. There seems to be at least one other active voxel engine community, called [Terasology](http://terasology.org/), who are quite far along the road in terms of world engine development.

In what ways can our communities work together to share the best parts of our game engines/game mechanics, so our players have a great gameplay experience?

**Comment by HybridDog** [comment] 2017-08-27 07:06
In minetest performance is an issue, the game should work on old hardware and it's programmed in c++, whereas terasology requires recent hardware, has interesting graphics and is programmed in java.

In terasology there are a lot better looking object collisions (see https://github.com/minetest/minetest/issues/6076#issuecomment-312452587). Maybe they can be ported to minetest.

**Comment by paramat** [comment] 2017-08-27 13:36
If terasology devs are working in Java then it's not likely they will want to work in C++ for MT, especially since devs of both are probably already overwhelmed by their own project. I expect MT devs do not want to work in Java for Terasology, their code is difficult to work with and has been used as an example of bad coding in our own code guidelines.

Doesn't seem a realistic suggestion.
If devs of either want to work for the other project then they will do so, i don't think discussing it will have any affect.

**Comment by paramat** [comment] 2017-08-27 13:39
We are enhancing the engne and it is well developed, you're talking about fancy effects.

> In minetest performance is an issue, the game should work on old hardware and it's programmed in c++,

MT performance is quite good and it is designed to work on old hardware.

**Comment by brylie** [comment] 2017-08-27 15:37
@paramat can you think of any constructive response to the original question? E.g. what are some possibilities for collaboration? What are some ways the developers could actively learn from one another.

Your responses so far have been:
- negative
  - "Doesn't seem a realistic suggestion."
  - "No, we want to do things our own way, and alignment would be a disruptive nightmare for both games."
- dismissive
  - "i don't think discussing it will have any affect, seems a waste of time."
  - "I suggest you learn C++ (it's not difficult at all) and start working on shaders for MT."
- harshly critical
  - "their code is difficult to work with and has been used as an example of unreadable coding"
  - "MT is by far the best and most developed free open source voxel game, we all consider the others inferior (because they are)."
- speculative
  - "The other project won't want to give up their focus on non-fancy-effect aspects"
- misconstrued
  - "You're only suggesting this due to the lack of the more fancy visual effects."

If Minetest developers want to build an inclusive community, **it is important to be respectful and open to new ideas.**

**Comment by rubenwardy** [comment] 2017-08-27 15:40
Irrlicht is a 3D rendering engine, not a game engine. Minetest creates the game engine by providing sound and networking on top of it. Minetest and Terasology are incompatible, as they have different languages, architectures, rendering engines, design philosophy, and more.

> who are quite far along the road in terms of world engine development.

What does this even mean?

> since devs of both are probably already overwhelmed by their own project.

This is a valid point, however contributors may like both (@Calinou has in the past).
That's unlikely to happen though, most people wouldn't want to split their efforts.

> I expect MT devs do not want to work in Java for Terasology, their code is difficult to work with and has been used as an example of unreadable coding in our own code guidelines.

Terasology probably goes a bit too far into Java factory land, however Minetest is arguably worse in that it doesn't go far enough. It's on my road map to separate `Game` to try and get separation of concerns.

> In what ways can our communities work together to share the best parts of our game engines/game mechanics, so our players have a great gameplay experience?

This is quite vague, as is this whole issue.

**Comment by paramat** [comment] 2017-08-27 15:56
I'm being realistic, stating my opinions and stating what i see as obvious truths, if you see these as negativity that's your problem not mine.

**Comment by brylie** [comment] 2017-08-27 16:00
> In minetest performance is an issue, the game should work on old hardware

@HybridDog great point. 

We play Minetest at home with three laptops of varying capabilities. The older ones are running Ubuntu and Lubuntu, since they have limited resources, and we wouldn't want to lose the ability to run Minetest on those laptops.
It seems like there may be some leeway with the design, where more advanced features could be toggled on/off to match the hardware capabilities.

**Comment by rubenwardy** [comment] 2017-08-27 16:03
> It seems like there may be some leeway with the design, where more advanced features could be toggled on/off to match the hardware capabilities.

Agreed, it should be possible to have opt-in visual improvements on newer faster machines, whilst keeping older machines happy.

**Comment by brylie** [comment] 2017-08-27 16:06
@rubenwardy thanks for the clarifying questions.

By 'quite far along in terms of world engine development', I was simply noticing that the Terasology engine is quite well developed. I can't find a complete feature list, but it seems like Terasology and Minetest have similar ambitions in terms of terrain generation and possibly other world engine features.

> This is quite vague, as is this whole issue.

The issue is intentionally vague, or open-ended. My hope was to promote constructive discussion about how the Minetest developers might collaborate with the Terasology developers.

> Terasology probably goes a bit too far into Java factory land, however Minetest is arguably worse in that it doesn't go far enough. It's on my road map to separate Game to try and get separation of concerns.

Where can one view the Minetest roadmap?

**Comment by paramat** [comment] 2017-08-27 16:07
I'll link the MT roadmaps.

**Comment by paramat** [comment] 2017-08-27 16:09
Roadmaps:
http://c55.me/blog/?p=1491
https://forum.minetest.net/viewtopic.php?f=7&t=9177

**Comment by celeron55** [comment] 2017-08-27 16:12
I should note that some people hate paramat for always linking those roadmaps that I haven't updated literally in years. But I guess they're fine as an introduction.

**Comment by paramat** [comment] 2017-08-27 16:15
To be fair, that 'some people' is 1 person who left the project.

**Comment by celeron55** [comment] 2017-08-27 16:16
Oh, and, I think this is a good issue to have around. If nothing really comes out of it, at least we have some kind of a log for what has been suggested and thought about.

**Comment by rubenwardy** [comment] 2017-08-27 16:17
Those road maps don't really match the reality. It's probably worth stating our current direction somewhere. 

The problem is that it's currently quite chaotic in development. So as well as generalising our direction, it may be worth encouraging core devs to publish their own personal road maps / aims.

**Comment by dsohler** [comment] 2017-08-27 18:37
> and who has an obsessive hate for me anyway.

It’s not hard to hate you :smile: 

> The problem is that it's currently quite chaotic in development.

Always feels like every core dev does his own thing and rushes it into release no matter if it fully works, is useful, or is not secure.

**Comment by nerzhul** [comment] 2017-08-27 19:45
one point about the incompatibility, it's wrong, terasology can, if needed wrap minetest C++ core using JNI interfaces

**Comment by nerzhul** [comment] 2017-08-27 19:48
my own personal roadmap is to include CSM hud with @red-001 PR and NpcSAO a new SAO object purely dedicated to modders, less generic than LuaEntitySAO permitting everybody to easy have high performance SAO object with NPC, and code only IA over it

**Comment by C1ffisme** [comment] 2017-08-27 20:31
What are the details on this collaboration? Are we:

- Helping to code features into Terasology (Unlikely, they seem to have more features than us, even if you can't use them on a crappy laptop like mine...)
- Getting help from them to code features into our game (Likely to be what you want, but running on old machines seems to be one of the goals of Minetest, so I can't see this happening)
- Merging both projects into one (Very unlikely, considering both projects use two totally different programming languages, and have very different goals.)
- or Making some kind of brand collaboration for the sake of advertising? (Super unlikely, considering Minetest doesn't really have mascots or branding.)

**Comment by brylie** [comment] 2017-08-28 08:49
> terasology can, if needed wrap minetest C++ core using JNI interfaces

I am not sure what this means on a technical level, but it sounds like it might enable code sharing between the projects.

Perhaps the Terasology and Minetest projects could agree on a common API or plugin model. Then, for example, Terasology might be able to use Minetest Lua mods or Minetest might be able to hook in to Terasology rendering features (such as shaders).

**Comment by brylie** [comment] 2017-08-28 08:50
> What are the details on this collaboration?

My intuition is that the projects could lean on one another, embrace each other's strengths and augment each other's weaknesses. Terasology rendering features might be integrated into Minetest. Minetest mods might be made compatible with the Terasology engine, through a plugin API/facade.

**Comment by nerzhul** [comment] 2017-08-28 08:59
minetest has an API, terasology should implement the API java side if it wants to be compatible, we know projects have the same goal, but minetest community and modding is big, terasology is just nice :)

**Comment by brylie** [comment] 2017-08-28 09:00
As one short-term goal for this thread, we could try to reach consensus about some possible ways the projects could collaborate. Then, we (or I) could summarize those ideas in a brief document, and post an 'invitation to collaborate' on the Terasology forum or GitHub repository.

The Terasology developers could, hopefully, respond with their thoughts on the proposal.

**Comment by nerzhul** [comment] 2017-08-28 09:01
you can, but personally i think MT has many things to do before collaborating with another project which is absolutely not minetest cup of tea (java...)

**Comment by Ferk** [comment] 2017-08-28 09:51
It would be interesting if it was possible to agree on a Lua API that any voxel engine in the style of Minetest could implement (not just Terasology).

However, I feel the Lua in Minetest is very ingrained with the particularities of the engine and making it more generic would probably take away more than what it would bring. It will probably complicate development of other interesting features. Not having to go the extra step of seeking intercompatibility across engines allows the API to evolve with more freedom.

Perhaps it's better to let each engine do its own thing. If the Terasology project is actually interested in offering a Lua API similar to Minetest, they can check out Minetest for inspiration, and then if they come out with a nice design of their own API, maybe it would be interesting to support it in Minetest as well.

**Comment by nerzhul** [comment] 2017-08-28 11:47
in fact a lua api is generally very close to core engine, because it needs high performance

**Comment by C1ffisme** [comment] 2017-08-28 16:54
> My intuition is that the projects could lean on one another, embrace each other's strengths and augment each other's weaknesses.

This statement is still pretty vague, but at least you ruled out my idea of a brand deal. (Which makes no sense. They could put MESE in Terasology, sure, but that's a pretty vague reference.)

> For example, Terasology rendering features might be integrated into Minetest. Also, Minetest mods might be made compatible with the Terasology engine through a plugin API/facade.

Now this actually sounds less vague, but there are certain things that really wouldn't be plausible. Sure, being able to make new nodes, tools and items is a piece of cake, but other features like schematics or aliases might require major changes to the Terasology engine.

(Although to be fair, I don't know much about Terasology's engine or modding capabilities, seeing as I can't get it to run well on a puny little Lenovo Thinkpad T420s.)

Currently, I know of two open-source projects that are going for a Mario style of gameplay, those projects being [Supertux](http://supertux.github.io/index.html) and [Secret Maryo Chronicles (Which could be dead... Not sure.)](http://www.secretmaryo.org/), but you wouldn't really merge those two projects together, now would you? (Although a brand deal makes more sense here. :P )

**Comment by HybridDog** [comment] 2017-08-28 17:49
supertux and smc don't have mods as far as l know. But being able to load/convert supertux levels and worldmaps to smc and the other way round would work l guess.
You need to consider that minetest is a complex game with focus on creativity regarding gameplay. Converting levels between those games is like converting maps between minetest and terasology. Manually rewriting a mod for the other game is a lot easier than making APIs compatible and maintaining it, which is a huge amount of work and may sometimes significantly slow down development due to compatibility problems l think.
btw, smc is now developed as tsc, see https://github.com/Secretchronicles/TSC

**Comment by C1ffisme** [comment] 2017-08-28 19:44
@HybridDog Now converting worlds sounds like a much more reasonable idea for a collab. (As long as Minetest has a subgame with the same items, etc.)

(You wouldn't really be able to convert Supertux levels into SMC levels or vice versa, though, because I've used the level editors for both. Supertux uses a tile-based system, while SMC has chunks of ground that can be freely moved without any grid constraints. Converting SMC levels into Supertux levels would potentially lose data.)

**Comment by brylie** [comment] 2017-08-29 08:03
Here is a simple diagram of the compatibility model:

![screenshot_20170829_110321](https://user-images.githubusercontent.com/17307/29810738-af534854-8ca9-11e7-8cd4-a5d3a569b5f5.png)

Basically, the compatibility layer would allow game assets to be freely re-used in any supported Voxel game (engine).

**Comment by C1ffisme** [comment] 2017-08-29 17:11
@brylie Okay, I guess I understand a bit more what you want... Obviously, some of this is plausible (Skins are the most possible, graphics in the form of texture/resource packs are possible, AI might not work because Minetest has no AI, and Minecraft hardcodes its AI. Plugins and Mods would require either game to significantly change how it handles mods if at all.)

**Comment by brylie** [comment] 2017-08-30 06:08
> Minetest has no AI

By AI, in the context of Minetest, I think of 'mobs' or 'traders'.

**Comment by brylie** [comment] 2017-08-30 06:11
> graphics in the form of texture/resource packs are possible

Should textures and resource packs then be considered separately from rendered effects (e.g. shaders and particles)?

**Comment by paramat** [comment] 2017-08-30 18:01
> Those road maps don't really match the reality.

They do actually in fundamental approach and philosophy, what differs are some specifics, for example VAEs are not being worked on, and CSM was intended to be server-provided mods only but is currently clientside mods (unfortunately).

> The problem is that it's currently quite chaotic in development.

Not necessariy a bad thing, it's always been quite intuitive and artistic and the result is good.
People worry far too much about 'lack of direction'.

> Always feels like every core dev does his own thing

It's voluntary work, so we obviously work on what we feel like working on and what we are interested in, from these combined interests the 'direction' naturally arises.

> and rushes it into release no matter if it fully works, is useful, or is not secure.

Apart from a few inevitable mistakes, not so at all.

**Comment by brylie** [comment] 2017-08-30 20:42
Admittedly, part of the motivation for this issue was to encourage high-level thinking, planning, and coordination between developers and projects. 

Being volunteer run, and motivated by curiosity and learning are understandable. But as projects and ideas mature, architecture and coordination/collaboration become increasingly important.

**Comment by paramat** [comment] 2017-09-10 05:35
We decided to keep this open for a while, but now closing. MT devs are not interested in collaboration and there's no news of contact with Terasology.
The compatibility layer suggestion is so radical it would have to be a fork of Minetest.
Feel free to continue discussion, closing doesn't mean discussion is discouraged, we just don't want the issue being marked for attention.

**Closed by paramat** 2017-09-10 05:35 UTC
Labels: Low priority, Possible close, Request / Suggestion

**Comment by numberZero** [comment] 2017-12-28 20:20
Terasology seems to be very fancy. I’m aware of the fact paramat hates fanciness, but there are other opinions as well.
And while I do agree with paramat that direct collaboration is neither feasible nor plausible, we might be interested in Terasology’s textures (they are generally easy to adopt) and shaders (may need more work, but actually they are what makes the game look fancy). Also note that while the code is totally incompatible, algorithms aren’t, they may be ported, if necessary.

**Comment by paramat** [comment] 2017-12-28 23:00
This is not just about me so no need to focus on me here, the other devs also considered this suggestion impractical and did state their opinions, as did non devs, i just wrote more comments.
Apart from that point, numberZero i agree with you.

**Comment by ThomasMonroe314** [comment] 2017-12-29 00:06
I've played Terasology(yeah ik, I'm a traitor ;D) and the effects they have achieved with shaders is amazing.
Also collaborating with them would IMHO not bring any negative results, it may however not bring any positive results either, but I don't think it would harm anything.
This is just my opinion, treat it like a buffet, take it or leave it :)

**Comment by brylie** [comment] 2018-12-08 10:36
Hei all. I have been chatting with Terasology community/devs recently, and there seems to be some recognition that Minetest codebase is well organized and the project fills some gaps that are missing in Terasology. At least one of the project managers has expressed interest in trying to figure out how to incorporate parts of Minetest into Terasology, but nothing committal. I really think this would benefit both projects if we could combine our scarce resources and build on each others' work.
