### ISSUE TITLE
LuaEntitySAO: Add set/get_pitch

### ISSUE THREAD

**Issue by octacian** [minetest/minetest#6017] opened 2017-06-20 02:54 UTC
`set_pitch` and `get_pitch` methods for LuaEntitySAO objects would be incredibly useful. I tried to implement this myself, however, was not very successful due to having very little experience with C++.

For those of you who are skeptical of the use cases for this, here are a few off the top of my head:
* Allow item entity to make craftitems and tools appear to sit flat on the ground
* Causing entities to "lay down" without having to add specific animations

**Comment by nerzhul** [comment] 2017-06-20 06:16
why not, i think it requires a protocol update of messaging update  on SAO

**Comment by DS-Minetest** [comment] 2017-06-20 16:26
Duplicate of #2824.

**Closed** 2017-06-20 16:57 UTC
Labels: Feature request
