### ISSUE TITLE
Can't copy-paste Chinese characters into chat (both Windows & Linux)

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#5226] opened 2017-02-13 14:21 UTC

**Comment by zaoqi** [comment] 2017-02-13 14:23
I downloaded from https://launchpad.net/~minetestdevs/+archive/ubuntu/stable

**Comment by sfan5** [comment] 2017-02-13 15:01
works on desktop:
![bildschirmfoto_2017-02-13_15-57-49](https://cloud.githubusercontent.com/assets/1042418/22888337/a162ac1a-f205-11e6-8e7c-51809ca0871f.png)

on android it's a known bug:
-> #2030

**Comment by zaoqi** [comment] 2017-02-15 13:07
@sfan5 
![image](https://github.com/zaoqi/files/raw/master/%E6%88%AA%E5%9B%BE_2017-02-15_20-57-39.png)![image](https://github.com/zaoqi/files/raw/master/%E6%88%AA%E5%9B%BE_2017-02-15_21-03-47.png)
Say "你好":
![image](https://github.com/zaoqi/files/raw/master/%E6%88%AA%E5%9B%BE_2017-02-15_21-05-47.png)

**Comment by dsohler** [comment] 2017-02-27 20:15
Unicode support (and translation system) are both horribly broken (especially on Linux) in Minetest and have to be rewritten from scratch to properly have both of them.

**Comment by Hagb** [comment] 2018-07-22 14:13
Will it be fixed in 5.0.0 ? Thanks.

**Comment by MuhdNurHidayat** [comment] 2018-07-22 19:52
On some systems, input method editors also does not work in Minetest, which is why players resolve to the old way of copy-pasting text. But unfortunately, pasting doesn't work either. ¯\_(ツ)_/¯

On my side, pasting unicode text is broken on all of these:
- Minetest 0.4.17.1-stable-win64 on Windows 8.1 (paste resulted in garbage)
- Minetest 5.0.0-[9855651-win64](https://gitlab.com/minetest/minetest/pipelines/26251385/builds) on Windows 8.1 (paste resulted in garbage)
- Minetest 0.4.16-stable on Windows 10 (paste resulted in garbage)

As usual, pasting unicode into chat on Android always worked fine, tested on
- Minetest 0.4.17.2-android (0.4.17.20) on Android 6.0.1
- Minetest 0.4.16 on Android 5.1.1

The problem is only in the desktop version
- Minetest 0.4.16 on Ubuntu Jessie (paste resulted in escaped unicode sequence)

**Comment by MuhdNurHidayat** [comment] 2018-07-23 19:02
that's a font issue, it actually gets sent normally on android, just you can't see it...
change the font to something like Noto Sans CJK or other CJK fonts and you could see it...

on desktop on the other hand, you can't send the chat... it will always appear rubbish when pasting...

**Comment by Hagb** [comment] 2018-07-24 04:50
@MuhdNurHidayat
Thanks! I do that and it works! 
I also try to say text with Chinese char in a terminal of a Minetest 0.4.17.1 server, and client (Minetest 0.4.17.1 ) can receive and display the text without any trouble.
It seems that the problem is in inputting……
I guess maybe the problem can be solved by mod.

**Comment by MuhdNurHidayat** [comment] 2018-07-25 05:32
Yes, the problem is only in inputting...

For the chat, it could be temporarily solved by a mod or client-side mod.
In fact I do have client-side mod that does that [here](https://github.mnh48.com/unicodeparser/ "Unicode Parser"), but you need tool (included in release) to convert to unicode escape first -- that's how I chat in Japanese and Chinese in game when playing on Windows where I can't write nor paste the characters directly on Minetest client.

But we still need proper unicode support so that we can write on formspecs (like username, passwords, signs, searching in inventory, etc.)

There seems to be some kind of fork that's able to pass unicode on formspecs to the server because I've seen Japanese texts on signs, and by default you need to write on the sign formspecs to have it appear but none of official Minetest client seems to accept unicode on formspecs. I don't know which fork app they use but I do know the Japanese are playing on iOS.

**Comment by Hagb** [comment] 2018-07-29 08:35
@MuhdNurHidayat @sfan5
One of the problems is in `getTextFromClipboard()` of Irrlicht, which is used by Minetest to get the text of clipboard.
In GNU/Linux it will return a broken text with "\uxxxx"......

**Comment by sfan5** [comment] 2021-08-30 20:02
fixed by https://github.com/minetest/irrlicht/commit/9c4b6f25ab73c413730f9c8d35f34ef7db7e2b33 (Linux) and https://github.com/minetest/irrlicht/commit/34f1f8d089ab1f7958c874265ff37cced54d18ed (Windows)

**Closed by sfan5** 2021-08-30 20:02 UTC
Labels: Bug, @ Client / Audiovisuals, Windows, Upstream issue, Linux
