### ISSUE TITLE
minetest.encode_png uber memory leak && bad performance

### ISSUE THREAD

**Issue by jordan4ibanez** [minetest/minetest#14094] opened 2023-12-12 03:47 UTC
### Minetest version

```true
Minetest 5.9.0-dev-a98200bb4-dirty (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1693350652
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

### Active renderer

OpenGL 4.6

### Irrlicht device

X11

### Operating system and version

openSUSE Tumbleweed 20231210

### CPU model

Ryzen 5800x

### GPU model

AMD Radeon RX 6800 XT

### OpenGL version

OpenGL 4.6

### Summary

minetest.png_encoder() has an EXTREME memory leak. I have 32 GB system memory and this thing was able to crash the linux kernel by some anomaly.

It also incurs some strange performance penalty encoding a 100x100 png directly mapped from a string via uint8_t mapped chars even with the max compression.  

I have provided a video in which showcases this. I have my patch which stops the weird server step bug when you're not moving from happening. 

An explanation of what's happening in the video:

The top menu items are pBuf: Performance buffer (smaller framebuffer), 4k just doubles the scale of the performance buffer, pTex halves the texture resolution, and render = false means that the logic is still happening it's just not flushing to the texture with the png encoder.

The video: https://youtu.be/H80vlVfVZHQ?feature=shared

### Steps to reproduce

As requested, here is a minimal reproducible example. 

You jump to toggle the buffer flushing (encoding the PNG) on and off.

**WARNING: THIS MAY CRASH YOUR COMPUTER IF YOU RUN IT TOO LONG!**

```lua
minetest.register_on_joinplayer(function(player)

  -- cached functions
  local char = string.char;
  local insert = table.insert;
  local concat = table.concat;
  local random = math.random;
  local encode_png = minetest.encode_png;
  local encode_base64 = minetest.encode_base64;
  local clock = os.clock;
  local tostring = tostring;

  -- constants
  local WIDTH = 100
  local HEIGHT = 100
  -- RGBA
  local CHANNELS = 4
  local ARRAY_LENGTH = WIDTH * HEIGHT * CHANNELS
  local PLAYER_NAME = player:get_player_name()
  local BUFFER_NAME = PLAYER_NAME .. "debug"

  -- returns table with # == length
  local function preAllocate(length, fake)
    local newBuffer = {}
    -- Lua is 1 indexed
    for _ = 1,length do
      if (fake) then
        insert(newBuffer, char(random(0,255)))
      else
        insert(newBuffer, char(0))
      end
    end
    return newBuffer
  end

  -- runtime variables
  local buffer = preAllocate(ARRAY_LENGTH)
  local fakeBuffer = preAllocate(ARRAY_LENGTH, true)
  local jumpWasPressed = false
  local shouldFlushBuffer = true

  -- we need some way to compare in real time. So we jump. Van Halen would be proud
  local function mightAsWellJump()
    local hasBackAgainstRecordMachine = player:get_player_control()["jump"]
    if (hasBackAgainstRecordMachine and not jumpWasPressed) then
      shouldFlushBuffer = not shouldFlushBuffer
    end
    jumpWasPressed = hasBackAgainstRecordMachine
  end

  -- gives a random uint8_t char
  local function genChar()
    return char(random(0, 255))
  end

  -- randomizes the buffer
  local function randomizeBuffer()
    -- Lua is 1 indexed
    for i = 1,ARRAY_LENGTH do
      buffer[i] = genChar()
    end
  end

  -- now add the initial buffer
  local BUFFER_ID = player:hud_add({
    name = BUFFER_NAME,
    hud_elem_type = "image",
    position = {x=0,y=0},
    -- starts off as nothing
    text = "",
    scale = {x=1,y=1},
    alignment = {x=1,y=1},
    offset = {x=0,y=0},
    z_index = 1000
  })

  -- outputs the buffer into the hud
  local function flushBuffer()
    if (shouldFlushBuffer) then
      local SERIALIZED_BUFFER = concat(buffer)
      -- level 9 because that is giving this the highest performance
      local RAW_PNG = encode_png(WIDTH, HEIGHT, SERIALIZED_BUFFER, 9)
      local RAW_BASE64 = "[png:" .. encode_base64(RAW_PNG)
      player:hud_change(BUFFER_ID, "text", RAW_BASE64)
    else
      -- We're skipping encode_png to compare directly
      local SERIALIZED_BUFFER = concat(fakeBuffer)
      local RAW_BASE64 = "[png:" .. encode_base64(SERIALIZED_BUFFER)
      player:hud_change(BUFFER_ID, "text", "")
    end

  end

  minetest.register_globalstep(function()
    mightAsWellJump()
    local BEGIN_TIME = clock()
    randomizeBuffer()
    flushBuffer()
    local END_TIME = clock()
    -- * 1000 to convert it to milliseconds
    local TIME_TAKEN = (END_TIME - BEGIN_TIME) * 1000
    print("took: " .. tostring(TIME_TAKEN))
  end)
end)

```

**Comment by wsor4035** [comment] 2023-12-12 05:28
@jordan4ibanez could you see if https://github.com/minetest/minetest/pull/14020 happens to improve/change anything?

**Comment by rubenwardy** [comment] 2023-12-12 13:52
To be confirmed, the steps to reproduce should have a minimal reproducible example (MRE) - an init.lua file that triggers this issue

**Comment by jordan4ibanez** [comment] 2023-12-12 15:43
> To be confirmed, the steps to reproduce should have a minimal reproducible example (MRE) - an init.lua file that triggers this issue

I have added a minimal reproducible example which can be plugged into any mod anywhere

**Comment by sfan5** [comment] 2023-12-12 15:45
> `local RAW_BASE64 = "[png:" .. encode_base64(RAW_PNG)`
> `player:hud_change(BUFFER_ID, "text", RAW_BASE64)`

textures are not garbage collected, which would make this a duplicate of #11531

**Comment by rubenwardy** [comment] 2023-12-12 15:49
Yeah, as expected. If the bug no longer happens when you remove the hud_change then this is a duplicate of #11531

**Comment by jordan4ibanez** [comment] 2023-12-12 15:53
> Yeah, as expected. If the bug no longer happens when you remove the hud_change then this is a duplicate of #11531

This is true

**Closed** 2023-12-12 20:01 UTC
Labels: Unconfirmed bug, @ Script API, Duplicate
