### ISSUE TITLE
Discussion: Improve collision performance for items

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#10397] opened 2020-09-14 16:34 UTC
I made a simple mod for my son that randomly drops lit TNT from the sky,

We noticed quickly that Minetest would grinds to a halt quickly... 3-5 FPS.
Some quick profiling pointed to collisionMoveSimple for all item-drops that the TNT explosions leave around.

I do not have a specific change in mind, but I do find that collisionMoveSimple is all but "simple", it's exceedingly complex.

Perhaps this is a typical use, but are there any ideas to reduce the work for dropped items?

Maybe caching? If the item entity is not moving and the node below hasn't changed.
Perhaps dropped items can be handled special.

Or perhaps this is so special to not be worth improving... Happy to close in that case.

**Comment by rubenwardy** [comment] 2020-09-14 16:40
Duplicate of #6453

**Comment by sfan5** [comment] 2020-09-14 16:53
Does the bad performance come from the collision tests itself or from the `getObjectsInsideRadius` call?
As ruben pointed out, the latter is a known bottleneck.

**Comment by lhofhansl** [comment] 2020-09-14 16:56
Just checked... The item-entities are correctly setup to not collide with other entities (the passed collideWithObjects is false), so it is just the test with nodes that takes the time. (i.e. getObjectsInsideRadius is not called in this case)

**Comment by lhofhansl** [comment] 2020-09-14 21:17
>  Disabling collision for certain entities until a MapEditEvent is received for the residing mapblock doesn't sound too hard.

That's along the lines I was thinking about too. Might be straddling MapBlocks, so that could also get complex.

**Comment by lhofhansl** [comment] 2020-09-15 07:05
I helped my son out my making my own tnt entity with disable_drops = true.

But I'll continue thinking about this. This is clearly less efficient than it could be.

**Closed** 2021-01-31 19:00 UTC
Labels: Discussion, Performance
