### ISSUE TITLE
ANR when opening world on Android

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#12996] opened 2022-11-26 10:23 UTC
# THIS IS NOT A BUG REPORT
after https://github.com/minetest/minetest/commit/f04d4d029182d27e2557b9ea0a6a6fc39a3e17f5

i still cant open world but its now end with ANR instead of get back to home screen (Minetest menu)

![Screenshot_20221126-152331](https://user-images.githubusercontent.com/76146430/204083819-eb5086f5-4a67-4592-866f-0d639929e154.png)
(I have to rename to Minetest Beta cuz apk editor dont save apk if i dont make change)
# SORRY
if things like this should not be in issue

**Comment by TurkeyMcMac** [comment] 2022-11-26 11:48
I expect this is because https://github.com/minetest/minetest/pull/12960 has not been merged yet. Without that, there is a crash on opening a world.

**Comment by TurkeyMcMac** [comment] 2022-11-26 11:49
You could try with the APK available from here: https://github.com/TurkeyMcMac/minetest/actions/runs/3549853783

It has that PR merged, so it should work. It also prints some error messages that you should just ignore.

**Comment by oong819** [comment] 2022-11-26 11:52
> You could try with the APK available from here: https://github.com/TurkeyMcMac/minetest/actions/runs/3549853783
> 
> It has that PR merged, so it should work. It also prints some error messages that you should just ignore.

sorry cant try now i run out of device storage

**Comment by oong819** [comment] 2022-11-26 12:13
> You could try with the APK available from here: https://github.com/TurkeyMcMac/minetest/actions/runs/3549853783
> 
> It has that PR merged, so it should work. It also prints some error messages that you should just ignore.

dont work, crash with ANR

ohno i forgot to save debug log

also the bug i reported before (#12958 ) got closed due to duplicate, will this be too?

**Comment by TurkeyMcMac** [comment] 2022-11-26 12:18
I guess this is could be a separate issue, since it's an infinite loop instead of a segmentation fault. We will see if that patched APK crashes.

That other bug was a duplicate, this one seems not to be.

**Comment by oong819** [comment] 2022-11-26 12:24
> I guess this is could be a separate issue, since it's an infinite loop instead of a segmentation fault. We will see if that patched APK crashes.
> 
> That other bug was a duplicate, this one seems not to be.

i signed wrong apk file sorry if u see i say its crash

**Comment by oong819** [comment] 2022-11-28 07:58
i added a log to #12863 but seems like no one notice, if its dont get confirmed its will not be fixed =(

**Comment by TurkeyMcMac** [comment] 2022-11-28 11:14
You could leave a comment on that issue to notify people. I can't reproduce that problem on the build from https://github.com/minetest/minetest/pull/12960.

**Closed** 2022-11-30 15:50 UTC
Labels: Bug, Android
