### ISSUE TITLE
L-system use without light update, for mass usage.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#2151] opened 2015-01-18 16:32 UTC
For spawning trees (or any other structure, really) there is the `minetest.spawn_tree()` command available from the Lua API.

That function is unfortunately quite slow, which makes it hard to spawn multiple trees in rapid succession (like when writing a mapgen in Lua). As far as I could see that slowness comes from updating the light of the modified blocks everytime a tree is spawned, which of course sums up quite fast when placing a dozen or more trees. Also it is always creating a new map manipulator and reading the map data.

It would be very interesting if we would get the ability to do "mass" spawning of trees, for example by getting the possibility to either use some designated object similar to the VoxelManipulator.

```
local spawner = minetest.get_spawner()
spawner.spawn_tree(pos, myTreeDef)
-- more spawns
spawner.update_map()
```

Or some speed improvements in these functions would already help a lot.

For example, before the sunlight is propagated in `Map::updateLighting` all light is cleared from the block, that might be unnecessary as the sunlight seems to set the values of the lighting anew anyway. That is if I haven't missed an early bailout in `propagateSunlight`.

**Comment by ShadowNinja** [comment] 2015-01-18 16:59
There are two lighting update functions -- a mapgen one and a post-mapgen one.
The mapgen one has been optimized, but the post-mapgen hasn't and is still very slow.
You can see the difference by comparing the `VoxelManip`'s `update_light` and `update_map` methods.  In fact the light update was the main bottleneck for Technic's forcefield until recently when I removed the calls when not absolutely necessary (it could take over a second for fairly small (20x20x20 or so) areas).
This should be solved be speeding up the post-mapgen lighting calculations, although I can see how adding a `calc_lighting` flag to `spawn_tree` would be helpful when you're going to calculate the lighting for everything later in `update_light`.

**Comment by RobertZenz** [comment] 2015-01-18 17:02
You mean that one can tell `spawn_tree` from Lua to skip lighting and later do it manually via the VoxelManip object? Would also be solution, yes.

**Comment by gregorycu** [comment] 2015-01-19 09:05
Robert, we have some large speed improvements with regards to lighting checked in recently (since this issue was created - I know, weird coincidence). If you are able to get HEAD, you may be able to verify this has a positive impact on the performance for you.

**Comment by RobertZenz** [comment] 2015-01-19 21:15
I tried with HEAD of the moment of writing that ticket and unfortunately I'm not in front of the same PC, but here's what I measured now (on a better machine):

With commit 839c4a99 placing 304 "trees" (I put it in quotes because it really is only the axiom "TTTTT") takes ~23 seconds, with HEAD (9b89f7aa) it takes ~20 seconds. On the other machine I saw with yesterdays HEAD I saw a time of roughly ~60 seconds and even more, which is why I wrote that ticket in the first place.

Though, now that I see that I'm spawning 300 trees ~66ms per tree doesn't sound *that* bad, but summing up to a 20 second delay hurts a little. I will retry on the other machine as soon as I can (which might be the weekend) if that is of any help.

**Comment by gregorycu** [comment] 2015-01-20 05:42
Sorry, I should have been more clear, the change in question to speed things up was: db3466d

**Comment by RobertZenz** [comment] 2015-01-21 17:52
That commit was for sure in the build I originally tested with.

**Comment by gregorycu** [comment] 2015-01-21 23:06
Ok, thanks Robert. I was unsure because I checked in quite close to your issue getting raised. I'll spawn some trees myself and have a look at the performance.

You have raised a very good point with regards to holding-off the lighting update. I'll have a look at the performance in any case.

**Comment by paramat** [comment] 2015-03-10 00:07
The spawning of trees from saplings was moved to lua and is there for occasional sapling growth only, for lots of trees it's best to copy the code and make a mod that uses the voxelmanip, therefore doing the lighting calculations all at once at the end.

**Comment by PilzAdam** [comment] 2015-03-10 17:01
@paramat The tree grow functions in mintest_game use a voxelmanip.

**Comment by RobertZenz** [comment] 2015-03-10 17:47
@paramat Are you talking about that the C++ function should be changed, or that Mods should place trees using the VoxelManip object instead of using `spawn_tree`?

**Comment by paramat** [comment] 2015-03-11 03:03
PilzAdam yes i know =) but they use a voxelmanip and then update light the slow way for every individual tree, therefore slowness.
RobertZenz, i'm recommending that you write a mod instead that includes the lua code in default/trees.lua, but creates the voxelmanip once, loops the node-placing code many times for as many trees as you want, then runs the lighting update code once at the end.

**Comment by RobertZenz** [comment] 2015-03-11 07:42
@paramat Exactly.

**Comment by paramat** [comment] 2015-12-09 17:08
We now have an API to place schematics into a lua voxel manipulator (without a lighting update) https://github.com/minetest/minetest/commit/1384108f8c32f309852c1d1665a613f2a3e3fcc2 you can use the schematics from default mod.
The ability to add l-system trees using the decoration API (they get added during core mapgen before the lighting update)) is apparently intended but not done yet.

**Comment by rubenwardy** [comment] 2017-08-26 02:33
@paramat, any updates on this?

**Comment by juhdanad** [comment] 2017-08-26 21:15
#4967 changed the way how lighting is calculated, spawning trees is now faster. However, modders still might want to skip light update when spawning trees.

**Comment by paramat** [comment] 2017-08-27 14:21
What was intended was the l-system decorations added into the Biome API, but this is on the edge of my ability and i don't consider it a priority.

L-system trees are usually large (> 16 nodes high) because l-system just looks better that way, however any mapgen tree must be <= 16 nodes in height, this is why it doesn't seema priority, because any l-system structures have to be created after mapgen, for example grown instantly from saplings placed at mapgen time (as in Moretrees mod).

However an l-system function without a light update would be useful, but again for me not a priority, maybe someone else will work on this?

**Comment by juhdanad** [comment] 2017-08-27 14:57
There is `minetest.fix_light()` for updating a whole block's light after map generation, so simply disabling light update after tree generation is enough. The modder can update the blocks' light when all trees are generated. The only challenge is knowing which blocks were modified.

**Closed** 2024-12-08 19:27 UTC
Labels: @ Script API, @ Mapgen, Feature request, Concept approved
