### ISSUE TITLE
Map Layering

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#4503] opened 2016-09-06 07:39 UTC
While minecraft has separate dimensions that can be loaded during game, minetest has nothing like that at present, so I had the idea of adding map layers to make use of the -31000 to 31000 space available and allow mods to reserve a layer of this vertical space for a new dimension with it's own mapgen and decoration and maybe even skybox.

Currently the mapgen biomes will only generate when attached to the ground or a high enough mountain, so we need a forceload flag for the base biome of each layer so it can draw 2000 nodes high for example and have the other biomes for that layer attach to it's base.

This would add a much needed feature to minetest and allow modders to create some amazing realms in which to explore without the need for Lua mapgens which can be very slow indeed.  This may also allow for a proper Nether dimension to be created far below the ground with the use of the forceload flag to carve it out of the stone (hopefully with a smooth ceiling gradient flag as well :)

**Comment by duckbrain** [comment] 2016-09-06 15:56
[#4428](https://github.com/minetest/minetest/issues/4428#issuecomment-238777162) Related to or duplicate of

**Comment by raymoo** [comment] 2016-09-06 18:32
Sounds like a good idea for dimensions that are spatially related to other ones. It doesn't replace MC-like dimensions though, because some mods there require an arbitrary amount of dimensions to be available.

**Comment by tobyplowy** [comment] 2016-09-06 19:16
@tenplus1 this sounds really awesome and promising but why don't you actually add the possibility for completely New Dimensions (New World safes in the already existing World safe) the system you're going for now, seems really limited (in the amount of Dimensions you can have not in the possibilities) and will also have a lot of interfering with each other's mods ( I don't really know because I can't see the code but if it does what I think it does from what I can hear it sounds Limited)

**Comment by paramat** [comment] 2016-09-06 20:34
Well we could have both, stacking within one world is easier to do though.

> Currently the mapgen biomes will only generate when attached to the ground or a high enough mountain, so we need a forceload flag for the base biome of each layer so it can draw 2000 nodes high for example and have the other biomes for that layer attach to it's base.

Do you mean enable the standard biome system to repeat at each level?
Currently biomes will generate on any terrain at any height but you need to define biomes for the upper heights to avoid for example underwater forests in the upper realms.

**Comment by tenplus1** [comment] 2016-09-06 20:41
If the current mapgen had an option to forceload biomes at specific heights that would be enough to start the layering process instead of redesigning the whole mapgen itself, this way we could have many layered worlds/biomes without adding too many features.  As for nether biomes, the forceload would simply omit stone for air and build upon that :)

**Comment by paramat** [comment] 2016-09-06 21:30
Ok i see.

**Comment by paramat** [comment] 2016-09-06 21:30
Ok i see.

**Comment by tenplus1** [comment] 2016-09-07 06:42
Since current biomes require a base landmass to build upon this forceload idea adds that much needed landmass at a specific height so that specific height biomes can build from there as well :) it's a simple solution to a much needed feature.

**Comment by paramat** [comment] 2016-09-07 16:35
Such a fag can't be in biome definition because biomes are independent and applied after terrain generation, the reallms parameters need to be applied to initial stone terrain generation.

**Comment by paramat** [comment] 2016-09-09 06:17
> allow mods to reserve a layer of this vertical space for a new dimension with it's own mapgen and decoration and maybe even skybox.

By 'it's own mapgen' do you mean a choice of the existing core mapgens?
The existing biome API can already cope with multiple realms, and can define different biome systems dependent on height. All that's needed is the basic stone-only terrain.

> This may also allow for a proper Nether dimension to be created far below the ground with the use of the forceload flag to carve it out of the stone

This can't really be a separate core mapgen because it would make no sense on it's own. Instead this would be an optional part of a single core mapgen, and probably code shared between mapgens so that multiple mapgens can manifest the realm.

Our mapgen team (hmmmm and myself) are not keen on adding further complex mapgen APIs if not absolutely essential. We have a severe shortage of dev tiime.
I would prefer to realise stacked realms within a single mapgen, and this can be done right now without new systems (and i'm already working on stuff like this). Mods would be able to set mapgen parameters to control the options.

**Comment by tenplus1** [comment] 2016-09-09 19:45
We NEED a layered option to create alternate dimensions without the need for a slow LUA mapgen, this would be a great feature to add to the game.

**Comment by C1ffisme** [comment] 2016-09-09 20:34
Map Layering is still limited. Making a mod like Mystcraft or Galacticraft with a lot of planets in Minetest is severely limited to only so many dimensions before the dimensions are far too small for comfort. I love mining on Mars when Mars is only 1000x1000 blocks big, and the rare ores there spawn only so many times in every so many chunks.

**Comment by raymoo** [comment] 2016-09-09 20:52
I think map layering and a real dimension system would serve different purposes. If the new realm is supposed to be located spatially near or in the world, like a physical nether/hell realm or a floating islands layer, map layering makes sense because you can dig or climb to the place. Otherwise it doesn't make sense and a real dimension system should be used. What I'm afraid of with map layering is that it will become an excuse not to implement actual dimensions, but otherwise I have no problem with the idea.

**Comment by paramat** [comment] 2016-09-10 00:01
tenplus1 i totally agree, you somewhat misunderstand the implementation issues.

The request for multiple worlds is not the issue here and is somewhat offtopic, so please minimise that chatter. As i keep saying we don't have to choose between them, we can have both.

**Comment by tenplus1** [comment] 2016-09-13 06:46
This issue is solely to force load biomes at specific heights or depths for mod use.

**Comment by paramat** [comment] 2016-09-14 00:39
Biomes will always be applied at any y as long as the y limits are set.

**Comment by tenplus1** [comment] 2016-09-14 19:53
Say I wanted a biome high up in the sky around 1000 nodes to 1200 nodes, currently the only way this is possible is IF biomes slowly build upwards from ground level to 1000 which is very unlikely...  What I am asking is a forced biome at these levels without joining onto the ground at all.

**Comment by paramat** [comment] 2016-09-14 21:01
Current biomes have y max 31000 so they will automatically appear at any height whether the terrain is continuous to that height or not (try mgv7 with mountain noise 'scale = 1000' to see). To have special biomes at extreme heights just define new ones with suitable y limits. So this request may not be needed.

**Comment by tenplus1** [comment] 2016-09-15 07:43
That's no good, it would still have to be linked to the ground level biomes to work properly...  What I am asking is forced biome generation at ANY level...  If I want floatlands at 5000 high it is currently not possible... We need a way to FORCE these biomes to appear at that level without ground level changes.

**Comment by paramat** [comment] 2016-09-15 20:52
> it would still have to be linked to the ground level biomes to work properly

Nope you misunderstand.

Maybe you're talking about base terrain generation. Biomes will be applied to any terrain anywhere in the world, to create stacked realms the base terrain must be generated, but this has nothing to do with biome generation as that comes afterwards and is independent, so the flag can't be in biome definition but must be in mapgen parameters instead, i'm working on it.

**Comment by tenplus1** [comment] 2016-09-16 19:55
Ah okies, I misunderstood :P

**Comment by paramat** [comment] 2016-09-17 03:57
We can keep this open for the general discussion of stacking realms, which i very strongly support.

**Closed** 2016-10-05 21:38 UTC
Labels: @ Mapgen, Feature request
