### ISSUE TITLE
Rotating Selectionboxes for Entities

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#7652] opened 2018-08-17 08:03 UTC
##### Issue type
 - Feature request
##### Summary
It wouldn't be hard to implement that the selectionboxes of entities are rotated according to their yaw. Actually, I guess it would be sufficient if you would just rotate the player pointing direction around the entity, wouldn't it ?

**Comment by paramat** [comment] 2018-08-17 17:03
Duplicate of #7407 #1586 #3996 
See the other issues, it would be complex to implement and could greatly reduce the performance of collision detection.

**Closed by paramat** 2018-08-17 17:03 UTC
Labels: Duplicate, Feature request

**Comment by stujones11** [comment] 2018-08-17 17:40
I read this as being about the selection box, not the collision box. It may be possible to have one without the other, however, that would add more complexity to the raycasting, even more if/when entities have full rotational freedom.

**Comment by stujones11** [comment] 2018-08-17 20:48
@appgurueu You might get better traction with a feature request entitled ‘Better entity highlighting’ or some such :)
