### ISSUE TITLE
Purge usernames in auth.txt after being inactive for a long period of time.

### ISSUE THREAD

**Issue by nolsen42** [minetest/minetest#4451] opened 2016-08-17 21:02 UTC
auth.txt can become huge on a server, and some join, ping timeout or leave, and usually never come back. Or those who play the server, but suddenly goes offline forever (or for a really long time), which takes up a username that someone else could use, and space. I have an idea on how this can be done, besides simply deleting the username if it becomes inactive for too long, or "expired".

"Mark" the username as "expired" or "inactive". This way, the username isn't forever reserved for someone if they never will join the server again, or haven't been online for a long time (3 - 6 months). If the username is marked, then someone else can take it simply by choosing the username and using their own password in the server screen. When someone does, it would reset the password associated with the username, reset the privileges back to default, etc. This still gives the original owner of the inactive username a chance to login, before someone else takes it.

**Comment by est31** [comment] 2016-08-17 22:03
I've already lost logins for servers multiple times already because of server owners deleting accounts that have been offline for a while.

What should happen instead is to use a db for the player data, which can grow much better than a .txt file.

IF there is a deletion method, it should not be based solely the last left time, but also take other info into account, like how often someone logged in, or how long they've played.

**Comment by nolsen42** [comment] 2016-08-17 22:05
@est31 They may not tried my method, and only delete usernames when someone else wants them.

**Comment by est31** [comment] 2016-08-17 22:22
Well the issue was that someone can take the username if its not used for too long; so what happened was that I didn't log in for some time, and then someone else took my account because they saw my house.

**Comment by Fixer-007** [comment] 2016-08-17 23:22
Yes, database is very needed imho, for example Minetest Extreme Survival server has 70 000 player files that take LOOONG time to backup (because you get very slow speed on small files).

**Comment by xunto** [comment] 2016-08-17 23:54
But communication with database should be optional and defined in auth_handler(just like auth.txt now) because, for example, I rewrote auth_handler to use the same database website uses.

You already can do it with mod, yeah.

**Comment by est31** [comment] 2016-08-17 23:57
Yes, the current plan is to make the db entirely optional. Probably it can then either use the db backend, or the file backend with the auth handler.

**Comment by xunto** [comment] 2016-08-18 00:01
@est31 Maybe we should provide db api to lua and make auth_handler that uses this api to store player data in database. So we would have auth_hander with db backend. I just want this db backend to be customizable too.

**Comment by est31** [comment] 2016-08-18 00:43
No, that would make things more complicated than they should be. If we try to accommodate too many needs we end up with no solution as noone is capable of implementing or maintaining it.

Also a db api in lua is a neat idea, but using it would mean copying lots of potential data around. While for the auth data that wouldn't be a problem, it would mean a problem for the player metadata, as those are updated frequently.

**Comment by nolsen42** [comment] 2016-08-18 00:57
@est31 Changing it to a dB would make it harder to change the privs. Which is crucial to change when setting up a server.

**Comment by est31** [comment] 2016-08-18 01:04
@nolsen42 well the default will still be files and for advanced users there can be the db backend. There will possibly be also the option to migrate between backends.

**Comment by C1ffisme** [comment] 2016-08-20 15:20
I've left servers for a long time because I got bored of them, or bored of Minetest.

Definitely make this configurable, and let people be able to set certain players as "un-deletable", just in case they have to leave for a large amount of time. (Whether it be for religious reasons, or otherwise.)

**Comment by nolsen42** [comment] 2016-08-21 18:59
@C1ffisme How does religion have to do with minetest?

**Comment by DonBatman** [comment] 2016-08-21 20:10
There are many reasons for people to be away from minetest for extended periods. Health issues, too busy with work or school. Many religious groups do missionary work and can be away for a few weeks to a few years.

Flushing the auth file might seem good but could effect a lot of good players with good reasons to be away.

**Comment by sofar** [comment] 2016-09-07 21:37
Removing auth entries show also go in hand with deleting in-game player assets, otherwise it encourages players to log player names and attempt to re-register them to gain access to in-game items. At a minimum, player data should be removed, but realistically, in-game protected areas should be re-mapgen-ed to their initial state and protections removed.

Because of the consequence of doing this right, I'm against doing this in a fully *automated* fashion. I'd rather see an in-game command that can be used by an admin to purge the world from old player stuff that comprehensibly does this (the right way) and doesn't just do a quick hack of erasing authentication data.

**Comment by sorcerykid** [comment] 2017-01-09 19:51
Conceivably, there should be almost no limit to the number of players registered on a server. Even the 70,000 accounts on ESM server shouldn't cause a noticeable resource drain since they are not all active at once. The crux of the problem is the back-end storage mechanism. By default, Minetest relies on a flat-file format for all user privileges and hashed passwords with salts, and login timestamps, which is _extremely_ inefficient. Add to the fact, this data is then imported and exported in its entirety multiple times per minute on busy servers.

If the implementation were more efficient, then conceivably a server could have hundreds of thousands of registered players with almost no performance impact whatsoever. Before I optimized the builtin authentication handler on JT2, the server was virtually unplayable due to the immense size of the auth.txt file. Now, even with 130,000 total accounts, the server is performing better than it ever has.

**Comment by Sokomine** [comment] 2017-08-27 02:50
Players who did protect an area and build something ought not to be deleted that easily. Trouble is that indications of "player has been active once" are hard to detect automaticly. Protection mods work diffrent, placed/digged blocks need some sort of statistic in order to yield some data at all, and "placed a locked chest once" may still be too broad while leaving out players who just didn't find iron in time and just started building immediately. Perhaps a custom mod might be a better solution to this problem.
The issue with the overhead and lag caused by the authentication file on larger servers remains.

**Comment by SmallJoker** [comment] 2018-06-11 20:43
Marking as possible close because it's up to the mods to decide what should happen with the player data. For the auth mechanism there's `minetest.remove_player_auth` and for the player data `minetest.remove_player`.

**Comment by paramat** [comment] 2018-06-16 14:32
The specific request has some disapprovals. Please continue discussion in #6784 #6783 #5334 as a more general issue of what to do with auth.txt and issues of it's size.

**Closed by paramat** 2018-06-16 14:32 UTC
Labels: @ Server / Client / Env., Feature request, Possible close

**Comment by nolsen42** [comment] 2018-07-14 05:17
Wow this issue is still going, I thought it died a long time ago.
