### ISSUE TITLE
PostgreSQL: Severe performance degradation in 5.3 compared to 5.2

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#10113] opened 2020-06-27 17:28 UTC
##### Minetest version

```
Minetest 5.3.0-dev (Linux)
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=0
USE_SOUND=0
USE_CURL=1
USE_FREETYPE=0
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
```
exact commit: `7be082f9a8bb6bd46c226d7ef4c42f0fd9fe7314`

##### OS / Hardware

Operating system: `Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux` (Debian 10)
CPU: `Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz` (VPS from Contabo, https://contabo.com/?show=configurator&vserver_id=221, no add-ons)

##### Summary

Average server lag is about triple what it was under 5.2.0 using the same mod code.  Rechecked on my server (NodeCore Community World) and the lag was about 0.54 on 5.3, and 0.18 on 5.2.

##### Steps to reproduce

1. Install a non-trivial set of game, mods, world, whatever on MT 5.2.0 such that you're able to measure lag higher than dedicated_step using whatever method.
2. Upgrade to 5.3-dev.
3. Note that the lag is higher now; in some cases apparently triple.

N.B. also reported on the forums: https://forum.minetest.net/viewtopic.php?p=375866#p375866

**Comment by sfan5** [comment] 2020-06-27 18:01
Would you mind bisecting this?

**Comment by Warr1024** [comment] 2020-06-27 18:01
I'll take a shot at it; hopefully we find the problem all in one place.

I've also been advised by rubenwardy to check out gprof and see if I can profile this thing and figure out _where_ the problem is.

**Comment by SmallJoker** [comment] 2020-06-27 18:19
Could this be related to #10088?

**Comment by Warr1024** [comment] 2020-06-27 19:08
Trying to bisect locally I got a nonsensical result (646af2ef5f52cc3a04ea806d13dd2a048395da88).  I noticed some _possible_ performance loss at a few steps along the way but I didn't have a very good sampling method so I can't be sure.  I can't repro this thing on my own machine, and I don't want to have to restart the server like 8 times to track it down in situ.

**Comment by SmallJoker** [comment] 2020-06-27 20:41
@Warr1024 Are the lags due to worse mod performance, or due to networking? As long that's not known I don't think there's a better way to track down this issue. If there are scheduled restarts anyway (for backups), you could take the next binary for bisecting and troubleshoot it over several days.

**Comment by Warr1024** [comment] 2020-06-27 21:10
I can't tell whether it's networking or not, but I've been fine-tuning the lua code for this mod well into diminishing returns.  If it is network, then it must be the processing overhead from them, not the traffic itself, because I'm measuring based on globalstep dtime, not based on time to respond to a client action.

I've also gotten some advice from rubenwardy to try to reduce the number of ABMs registered with MT.  Right now there are 82, but I think I may be able to reduce them by as much as half by multiplexing.  Preliminary results from that effort show an improvement in performance, but still not enough to make a notable difference in the overall performance.

**Comment by hecktest** [comment] 2020-06-29 04:30
Isn't there some instrumentation in the server environment to at least show _where_ it has deteriorated?

**Comment by sfan5** [comment] 2020-06-29 10:08
Comparing the output of the server profiler (can be enabled using e.g. `profiler_print_interval = 30`) between 5.2 and 5.3 might give some hints.

**Comment by rubenwardy** [comment] 2020-06-30 17:53
I downloaded the world and game, and I was not able to reproduce this locally. I tried on both 5.2 and 5.3-dev, and profiled using Linux pref.

I profiled the engine, and did notice that the vast majority of process time was spent in mesh generation, so suggested that any meta be marked as private

**Comment by Warr1024** [comment] 2020-06-30 18:33
The original problem was on a dedicated server, where client mesh generation should be a non-issue, so the only way that should be the cause would be if the sending of block update packets to the clients is the cause of much lag; the lag spikes also happen about once a second, where I'm sure that the update packets are not all batched that way.

I'm going to implement the meta privatization so we can eliminate that as a factor and get a more clear picture of what's going on here, but I'll be very surprised if it's a "fix".  I apparently need to make this change for my game anyway, to cut down on unnecessary mesh rebuilding.

The fact that people are reporting this elsewhere (N.B. forum post at bottom of OP) indicates that this is not a game-specific problem, and if somebody else who runs a server and has observed this could provide instructions on how to configure to repro it that would be much appreciated.

I've also heard that it could be related to postgresql being the back-end for the dedicated server (which I do, event though the public shapshot downloads are converted to sqlite) so while I didn't think that could be the cause, it might be useful for reproducing the problem.

**Comment by Zughy** [comment] 2020-07-04 13:44
Nothing here either, tested both on 5.2.0 and on 5.3.0-dev (latest commit) with MTG


#### Comparison
| Version |  Lag after 8s | Lag after 120s  |
|---|---|---|
| 5.2.0 | 1.979 | 0.981 |
|  5.3.0-dev | 1.988 | 0.981 |

#### Game
Minetest Game

#### Mods
* (the ones contained in MTG)
* 3D Armor
* advtrains
* basic_materials
* ethereal
* magic_compass
* mesecons
* mobf_trader
* mobkit
* mobs
* mobs_animal
* moreblocks
* petz
* pipeworks
* technic
* water_life

I had a few animals spawned (2 cows, 2 sheeps, 1 panda and 1 chicken)

**Comment by Warr1024** [comment] 2020-07-06 14:47
For reference, original video linked in forum post linked in OP:

- https://www.youtube.com/watch?v=qvf_WUiC5OQ

... and a few more videos in what is apparently a de facto miniseries about this:

- https://www.youtube.com/watch?v=2ncCq6DLI64
- https://www.youtube.com/watch?v=D1HGMP5buz0
- https://www.youtube.com/watch?v=2b8D9kqOLDo

**Comment by Warr1024** [comment] 2020-07-06 16:52
I was able to successfully bisect it.  5c588f89e79e02cba392abe3d00688772321f88b is the first bad commit.

**Comment by rubenwardy** [comment] 2020-07-06 17:08
@nerzhul

**Comment by Warr1024** [comment] 2020-07-06 18:09
FYI the critical ingredient to be able to repro this seems to be at least pgsql, if not both pgsql and docker.  I run minetest and pgsql in 2 separate containers, though on the same physical machine, and they're interconnected using a virtual network established by docker-compose.

I'm running docker image `postgres:12.2-alpine` for my database server, and building MT from source on top of `linuxserver/minetest:5.2.0-ls42` using a patch based on https://github.com/pickardjoe/docker-minetest-postgres/commit/a9d6c188b1879aa86369aa262c6cf083ea4c3f4a#diff-3254677a7917c6c01f55212f86c57fbf to add in pgsql support, and pulling the source zip by commit hash now.

**Comment by Warr1024** [comment] 2020-07-06 18:14
Testing against dc6318b84aa8c079330b2adc711113f7d4b55961 plus the async pgsql patch from pandorabox (https://github.com/pandorabox-io/minetest_docker/blob/master/patches/minetest_async_pg.patch) the performance degradation is completely gone, and the game actually runs palpably smoother than it did in 5.2.0.

**Comment by BuckarooBanzay** [comment] 2020-07-06 19:44
@Warr1024 just a heads-up: that patch worked fine with `5.2.0` but i haven't tested it properly against `5.3.0` yet, there may still be problems (aside from the horrible code-quality)

**Comment by sfan5** [comment] 2020-07-06 20:01
A performant way to implement the ping mechanism would be __only__ ping when a database action fails with an exception (instead of pinging on every action).

This isn't easily doable with the current code, so unless another solution arrives I think it'd be best to revert #9665 for 5.3.0.

**Comment by nerzhul** [comment] 2020-07-07 12:18
go ahead for revert

**Comment by nerzhul** [comment] 2020-07-07 16:25
please not on modern connection pooling the select 1 can be done at any time without any performance penalty, i suspect something else, but don't block the release with my commit

**Comment by numberZero** [comment] 2020-07-07 16:53
@nerzhul But `libpq` doesn’t use connection pooling, does it?

**Comment by numberZero** [comment] 2020-07-07 17:01
BTW would TCP keepalive fix the problem you describe in #9665? (See [documentation](https://www.postgresql.org/docs/10/runtime-config-connection.html#GUC-TCP-KEEPALIVES-IDLE), [stack exchange](https://dba.stackexchange.com/questions/169127/client-application-disconnects-from-database-s-it-is-connected-to-after-10-minut))

**Closed** 2020-07-07 17:01 UTC
Labels: Blocker, Bug

**Comment by nerzhul** [comment] 2020-07-07 17:17
no tcp keepalive is not sufficient because you can have pgsql failures outside of the connection, it's why ping is needed, or maybe we should just SELECT 1 like many connection pools.
For libpq no there is no pooling

**Comment by Warr1024** [comment] 2020-07-08 12:30
What we really need is to move all potentially-disk-blocked write activity like map, modstore, player, and auth saving into a background thread.  We already keep most of this data in memory and flush it only periodically, so we don't enforce the strictest durability standards on in-game changes (i.e. it's already possible to lose several seconds worth of changes on a sudden crash) so the extra delay caused by backgrounding would probably not make a difference in reliability but could have big performance benefits.

The biggest challenge of that, aside from just the size of the code change required, is probably what happens if you push data into the write queue, then unload it from memory, but then need to reload it before it's had a chance to be flushed from the write queue.  You'd probably need to read through what's in the write queue (or have it update a shared cache) to make sure you aren't loading in the old version from disk or the remote db server directly.  That could make some of the locking stuff tricky to make sure you don't end up just stuck waiting on the writer thread anyway...

**Comment by rubenwardy** [comment] 2020-07-08 14:18
There could be a bidirectional queue allowing the background thread to acknowledge writes. The main thread would keep track of pending writes, removing the need to lock
