### ISSUE TITLE
5.0.0 Android: The reset singleplayer world function doesn't work properly, it calls /bin/rm which doesn't exist

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#7789] opened 2018-10-16 17:57 UTC
##### Issue type

 - Bug report

##### Minetest version
Minetest 5.0.0 Android builds:
- Build made by @stujones11 (https://github.com/minetest/minetest/pull/7784#issuecomment-429662776)
- Build made from commit e369eb1a9b2d65629d444fb305925e0d1b859b6f, earlier commits untested

##### OS / Hardware

Operating system: Android 7.0 on Huawei NEM-L21
CPU: HiSilicon Kirin 650 2.11 Ghz (8 cores, aarch64)

##### Summary

In minetest 5.0.0 android build (above) clicking reset singleplayer world then clicking yes to confirm does not actually reset the world. Next time world actually loads it's still the same world. 
Adding `debug_log_level = verbose` to minetest.conf shows that it's calling `/bin/rm` which doesn't exist.
```
2018-10-16 16:30:37: INFO[Main]: Removing "/storage/emulated/0/Minetest/worlds/singleplayerworld"
2018-10-16 16:30:37: VERBOSE[Main]: Executing '/bin/rm' '-rf' '/storage/emulated/0/Minetest/worlds/singleplayerworld'
2018-10-16 16:30:37: INFO[Main]: Initializing world at /storage/emulated/0/Minetest/worlds/singleplayerworld
2018-10-16 16:30:37: INFO[Main]: Searching worlds...
2018-10-16 16:30:37: INFO[Main]:   In /storage/emulated/0/Minetest/worlds: 
2018-10-16 16:30:37: INFO[Main]: singleplayerworld 
2018-10-16 16:30:37: INFO[Main]: 1 found. 
```
```
HNNEM-H:/ $ ls /bin/rm
ls: /bin/rm: No such file or directory
```
The rm binary in android is in different location compared to normal linux installation, running command `which rm` produces different output in android:
```
juozas@xubuntu:~$ which rm
/bin/rm
```
```
HNNEM-H:/ $ which rm                                                                                                                                                                           
/system/bin/rm
```
**Workaround:** Exit game, delete the world, run game again.
More details: https://github.com/minetest/minetest/pull/7784#issuecomment-430249603
##### Steps to reproduce

1. Download build by @stujones11 (e.g. download and install using adb, run `adb install -r Minetest-debug.apk`) or build one yourself from master branch (if using https://dev.minetest.net/Android follow workflow of #7797 if build fails due to errors)
2. Uninstall present build, install new one using adb or phone tools if available
3. Backup current Minetest folder by renaming it
4. Run minetest, start singleplayer, do something, exit the world
5. Try to delete the world using game interface
6. Start singleplayer again, see how same world loads

For aditional verification add `debug_log_level = verbose` to minetest.conf, repeat same, then check debug.txt to see that while attempting to delete the world game is calling a `/bin/rm` executable which doesn't exist in some of the android devices.

**Comment by stujones11** [comment] 2018-10-16 18:08
Since you mention my build specifically, I presume this problem does not exist is the official play-store release?

I can, however, confirm that the reset singleplayer world is not functional in the current dev version. I will look into it.

**Comment by juozaspo** [comment] 2018-10-16 18:16
@stujones11 play store version works fine, deleting worlds w/o any problems, dunno about any other 5.0.0 builds so there's no alternative yet.

**Comment by stujones11** [comment] 2018-10-16 18:21
@juozaspo It is highly unlikely to have anything to do with my build. We just need to find out what has changed there since the last release.

**Comment by stujones11** [comment] 2018-10-17 17:38
Well I have found out where it stopped working 9f19b7d9367c5dc2758a9d4690b091b745fc821d
Seems it does the exact opposite for android as reverting this fixes the problem for me

@numberZero ?

**Comment by juozaspo** [comment] 2018-10-17 18:33
@stujones11 the updated apk fixes the bug. World can be deleted w/o any problem. Downloaded and installed (updated) using phone interface, renamed existing Minetest folder to do the test.

**Comment by stujones11** [comment] 2018-10-17 19:20
@juozaspo Thanks, I guess that confirms that this is the cause of the regression. Ufortunately, I do not fully understand what that commit even fixes so let's hope the author has an idea how to fix this. At the worst case we could simply wrap the old code into an `#ifdef __ANDROID__` block, although there is probably a more elegant fix than that :)

**Comment by juozaspo** [comment] 2018-10-17 19:41
The better idea would be to detect where rm points to and use that. E.g. call shell (`which rm`) and use that for removing it. Or just using c/c++ file io functions or a code like before this bug's affecting change would work too.

**Comment by stujones11** [comment] 2018-10-17 19:54
> code like before this bug's affecting change would work too.

Indeed, whatever that commit fixed, did not affect android anyway. I clearly has something to do with the file-system class but I won't have time to fully investigate this myself until maybe the weekend.

**Comment by juozaspo** [comment] 2018-10-17 20:03
Calling `rm -rf` might be dangerous if world folder would be a symlink to anything arbitrary (e.g link created by some1 else), it might delete something unexpected instead of the world. Remember always to check for symlinks.

**Comment by paramat** [comment] 2018-10-18 02:32
Marked as blocker.

**Comment by numberZero** [comment] 2018-10-18 20:06
@stujones11 `l_delete_world` have been following symlinks before 9f19b7d. Correct fix would be to reimplement `RecursiveDelete` in a way similar to the old `l_delete_world`, just not following symlinks.

**Comment by stujones11** [comment] 2018-10-18 20:48
@numberZero I doubt that symlinks will ever be a problem for the average android user.

If you could make a PR to fix this I will be happy to test it.

**Comment by juozaspo** [comment] 2018-10-19 11:13
Android builds made from latest master are affected too, tested build made from e369eb1a9b2d65629d444fb305925e0d1b859b6f, still does the same thing. My build made following the solving of #7797, so I have my own build made from latest master to test.

**Comment by numberZero** [comment] 2018-10-20 22:04
@stujones11 The same function is used on desktop Linux, where symlinks are widely used. See #7201 for details.

**Comment by stujones11** [comment] 2018-11-20 19:29
I think the real issue here is the `fs::RecursiveDelete` does not work on Android since it uses `rm -rf`.

The best I could offer is to restore the old method but only for android. This would still be following symlinks, however, I am not sure it is even possible to create them on a non-rooted device. Even if it _is_ possible, they would not work on the `FAT32` sdcard filesystem.

**Comment by paramat** [comment] 2018-11-20 21:12
I agree this would be good for 5.0.0, unsure whether it should be a blocker, however is labelled 'high priority'.

**Comment by stujones11** [comment] 2018-11-21 20:01
I found a better way. It seems `rm` does exist on android, just on a slightly different path :)

**Closed** 2018-11-21 23:06 UTC
Labels: Android, Bug, High priority
