### ISSUE TITLE
When setting a bone's position all the other bones for that entity act weird

### ISSUE THREAD

**Issue by ThomasMonroe314** [minetest/minetest#6391] opened 2017-09-08 02:02 UTC
Minetest version 0.5-dev

I am attempting to set the head rotation of the player but when I do all the other bones snap to odd positions and don't play the animation that I have set to play.

Screenshot:
![screenshot_20170907_205806](https://user-images.githubusercontent.com/26969467/30192858-8ddc07d4-940f-11e7-8a87-fef0519a3121.png)
This is recreateable by adding `player:set_bone_position("Head",{x=0, y=0, z=0},{x=0, y=0, z=0})
` to ./minetest_game/player_api/api.lua:line103

I have scoured the source code of minetest for a solution, but just get terribly lost. XD

p.s. This is CalebDavis putting this forward. And as I do not have an e-mail yet, Tre and I are sharing this Git-hub account for the time being. :]

**Comment by DS-Minetest** [comment] 2017-09-08 12:41
Duplicate of https://github.com/minetest/minetest/issues/4739.

**Comment by rubenwardy** [comment] 2017-09-08 12:51
Duplicate of #4739

**Closed by rubenwardy** 2017-09-08 12:51 UTC
