### ISSUE TITLE
Android water rendering issue

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10109] opened 2020-06-27 02:15 UTC
Reported by a user, still unconfirmed

##### Minetest version
```
5.3.0-dev
```

##### OS / Hardware

Samsung S7

##### Summary

Ocean water renders correctly.

The water shown has a low alpha

Bad, current:

![image](https://user-images.githubusercontent.com/2122943/85912423-51448580-b824-11ea-986f-1a6d0060adf9.png)

Correct, 5.x:

![image](https://user-images.githubusercontent.com/2122943/85912429-573a6680-b824-11ea-8dc4-93c0964daa39.png)

**Comment by rubenwardy** [comment] 2020-06-27 02:38
Confirmed by warr1024 to occur when the alpha of a liquid is set to 64 or below

**Comment by MoNTE48** [comment] 2020-06-27 14:34
ogles1 or 2?

**Comment by sfan5** [comment] 2020-06-27 15:59
> Confirmed by warr1024 to occur when the alpha of a liquid is set to 64 or below

Sounds a lot like this issue: https://github.com/minetest/minetest/issues/10032#issuecomment-643482318

**Comment by MoNTE48** [comment] 2020-06-27 16:27
https://github.com/minetest/minetest_android_deps_binaries/commit/b2380b45ec01d040f4b0bfb515e74edd8f9f1bf0
If so, then this fix for ogles2 was premature. Although why does it work up to a certain transparency value?

**Comment by sfan5** [comment] 2020-06-27 17:06
If you set `MaterialTypeParam` to 0.5 you are telling the GPU to discard all pixels with an alpha less than 128.

**Comment by MoNTE48** [comment] 2020-06-27 17:45
Oops. Well then, resolving the issue of transparency on ES2 is more complicated.
I just applied the solution approved in PR https://github.com/minetest/minetest/pull/8005 globally.  

My solution:
1) Revert my commit AFTER 5.3 and try to solve the problem in 5.4.
2) Revert my commit NOW and release 5.3 with a broken ES2 (I saw many other problems not resolved by PR above).

**Comment by rubenwardy** [comment] 2020-06-27 18:03
I'm happy for this to be dropped from 5.3, given how close we are.

Is this a regression? The 5.2 screenshot is actually from desktop

**Comment by sfan5** [comment] 2020-06-27 18:06
Considering #6971 is from a long time ago, this _shouldn't_ be a regression. But I don't know what exactly Monte's direct patch to Irrlicht affects.

> The 5.2 screenshot is actually from desktop

This problem only ever affected GLES platforms (Android).

**Comment by rubenwardy** [comment] 2020-07-07 15:55
Confirmed to be a regression

**Comment by sfan5** [comment] 2020-07-07 16:45
Since 5.2.0 doesn't run on Android is this a regression from 5.1.0? Does it work if you compile 5.2.0 with the new Android stuff?

Reverting minetest/minetest_android_deps_binaries@b2380b4 might fix this.

**Comment by rubenwardy** [comment] 2020-07-07 17:00
It's a regression from 5.0.1, which is the last released Android version

**Comment by MoNTE48** [comment] 2020-07-07 17:02
Lol, just revert this commit. And make sure inventory images, meshes, wielditem etc. displayed without a black background instead of transparency.
(So much talk instead of just testing 🙃)

**Comment by rubenwardy** [comment] 2020-07-07 17:03
I'm compiling Android right now :D

**Comment by rubenwardy** [comment] 2020-07-07 17:03
But yeah, this is Mine_test_ not Mine_talk_, gosh

**Comment by rubenwardy** [comment] 2020-07-07 18:13
Reverting that does fix the issue, but causes the hotbar images to have a black background. Setting the value to 0.01f or 0.1f doesn't help with that

**Comment by MoNTE48** [comment] 2020-07-07 20:36
Therefore, as I said above, the best solution would be _NOT_ revert now, but to make a real fix in 5.4.
Unfortunately this is not a thing in which I understand a lot. It is unfortunate that the issues of my quick fix was found so late.

**Comment by rubenwardy** [comment] 2020-07-07 20:41
Liquid transparency could be capped to >50% on Android for 5.3.0, with that fix for hotbar backgrounds in place. This same issue may occur elsewhere, however

**Comment by MoNTE48** [comment] 2020-07-07 20:48
Well, you know better. I do not use such transparency in my game, so this temporary solution is accepted for me.

The best I can do is I have more than 10 different Android devices and enough free time. Maybe I can postpone watching TV shows.
Give the subgames/mods list or the names of the servers with which I should test Minetest and give a link to the APK with your fix. I'll see if the new series can wait 😂

**Comment by Warr1024** [comment] 2020-07-08 13:48
Liquid transparency clamping sounds fine to me, as a holdover until there's time to fix it properly.  In fact, the clamping could probably be applied for all node definitions, not just liquids.

Here's one set of steps you can use to reproduce:
- Download the NodeCore game from the Content Browser.
- Create a world.
- `/giveme nc_lux:cobble1 16` (note the exact spacing)
- Place 9 lux cobble in a 3x3 square on a flattish piece of ground.
- Place the other 7 lux cobble on top of this in an H pattern.
- Wait a few seconds, and a pale yellow fluid should start flowing out of the sides of this thing.  This is the fluid that's affected by the bug.

**Comment by rubenwardy** [comment] 2020-07-08 18:10
> Reverting that does fix the issue, but causes the hotbar images to have a black background. Setting the value to 0.01f or 0.1f doesn't help with that

Turns out that I can't reproduce this issue, the background was only black because the hotbar_selected image had a black background - this also happens on the desktop version. Does this only happen on certain test devices?

**Comment by MoNTE48** [comment] 2020-07-08 18:18
@rubenwardy when player uses ogles2

**Comment by rubenwardy** [comment] 2020-07-08 18:58
I can't reproduce in ogles2 either

If it only happens on ogles2 - which isn't recommended on Android currently - then it makes sense to revert that fix for 5.3

**Comment by MoNTE48** [comment] 2020-07-08 19:12
You can sent me latest APK (32bit) with your revert?

**Comment by rubenwardy** [comment] 2020-07-08 19:33
both here: https://github.com/rubenwardy/minetest/releases/tag/5.3.0-ignoreme

**Comment by MoNTE48** [comment] 2020-07-08 19:59
God, how can I play a game with such touch control? I almost broke my phone. Nothing, I have a lot of them.

NodeCore has no inventory - it's hard to test. But no bug with yellow fluid.

SkyFactor subgame causes instant crash applications (bravo moderator ContentDB).
Somewhere was Issue that Minetest just crash instead of showing ModError?

Mineclone2 - Inventory looks disgusting. I just can't switch pages on a small screen. By the way, Minetest will receive a DMCA from Minecraft for hosting a game using Minecraft models. I would not recommend public this game for Android.

Lord of the Test looks really cool. No issues, too.

Otherwise, this problem is probably fixed in MT5, so my Irrlicht patch is not required. Perhaps I will still find the problem somewhere in the future. Then I will create issue/PR.

**Comment by rubenwardy** [comment] 2020-07-08 20:01
> Otherwise, this problem is probably fixed in MT5, so my Irrlicht patch is not required. Perhaps I will still find the problem somewhere in the future. Then I will create issue/PR.

Ok, I can close this issue with a revert as the fix, awaiting future issues if it reoccurs

> for hosting a game using Minecraft models.

@Wuzzy2 is this true?

**Closed** 2020-07-08 20:05 UTC
Labels: @ Client / Audiovisuals, Android, Blocker, Bug

**Comment by paramat** [comment] 2020-07-08 20:23
> I can close this issue with a revert as the fix

+1
