### ISSUE TITLE
Advanced settings: Noise edit window appends a comma at the end if no checkboxes are checked

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8077] opened 2019-01-08 19:01 UTC
##### Issue type
 - Bug report

##### Minetest version
95d4ff6d1b62945decc85003a99588bb0539c45b

##### Summary
When you edit a noise setting and turn of all the checkboxes, the value string will have a trailing comma.

##### Steps to reproduce
1. Open Minetest
2. In advanced settings, reset `mgv5_np_factor` to default. This should work with any noise setting, however
3. Click the “Edit” button to open the noise window
4. Uncheck all the checkboxes!
5. Save

Expected: There is no trailing comma in the resulting setting value
Actual: There is a trailing comma in the resulting setting value

**Comment by paramat** [comment] 2019-01-09 04:13
Confirmed.

**Comment by srifqi** [comment] 2019-01-09 15:10
I thought it is intended to indicate that there is no flag. But, we can change it if it shouldn't be like that.

```diff
diff --git a/builtin/mainmenu/dlg_settings_advanced.lua b/builtin/mainmenu/dlg_settings_advanced.lua
index 4a6fcfba7..7c5d5cba3 100644
--- a/builtin/mainmenu/dlg_settings_advanced.lua
+++ b/builtin/mainmenu/dlg_settings_advanced.lua
@@ -522,8 +522,11 @@ local function get_current_np_group_as_string(setting)
                        value.seed .. ", " ..
                        value.octaves .. ", " ..
                        value.persistence .. ", " ..
-                       value.lacunarity .. ", " ..
-                       value.flags
+                       value.lacunarity
+               if value.flags ~= "" then
+                       t = t .. ", " ..
+                               value.flags
+               end
        end
        return t
 end
```

**Comment by paramat** [comment] 2019-01-19 18:49
#8089 merged.

**Closed by paramat** 2019-01-19 18:49 UTC
Labels: @ Startup / Config / Util, Bug
