### ISSUE TITLE
Spritesheet support of sprite entities stopped working with shaders enabled

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#11206] opened 2021-04-18 16:05 UTC
##### Minetest version
```
0077982fb78a8ed39a90da03c0898d12583fed64
```
aka 5.5.0-dev

##### Summary
For entities with the `sprite` entity visual, you were able to use spritesheets using `spritediv` and `initial_sprite_basepos`. This feature is now broken. If you use this, you will see the whole spritesheet instead of a single sprite.

**This is a regression compared version 5.4.1.**

##### Steps to reproduce
Spawn this entity in DevTest: `testentities:yawsprite`. You should see a dungeon master sprite that rotates based on your look angle. But instead you will see the whole spritesheet.

You can also try `testentities:armorball` for testing.

**Comment by sfan5** [comment] 2021-04-18 18:17
The root cause is that the OpenGL code incorrectly skips loading the texture matrix because it's not in the fixed pipeline state.
Someone should dig in Irrlicht history to find out when/if that was changed.

Patch that hack-fixes it + debugging info:
```diff
diff --git a/source/Irrlicht/CBillboardSceneNode.cpp b/source/Irrlicht/CBillboardSceneNode.cpp
index 9eddb98..2429498 100644
--- a/source/Irrlicht/CBillboardSceneNode.cpp
+++ b/source/Irrlicht/CBillboardSceneNode.cpp
@@ -80,7 +80,9 @@ void CBillboardSceneNode::render()
 
 	driver->setTransform(video::ETS_WORLD, core::IdentityMatrix);
 	driver->setMaterial(Buffer->Material);
+	printf("drawing billboard\n");
 	driver->drawMeshBuffer(Buffer);
+	printf("--\n");
 
 	if (DebugDataVisible & scene::EDS_BBOX)
 	{
diff --git a/source/Irrlicht/COpenGLDriver.cpp b/source/Irrlicht/COpenGLDriver.cpp
index cbbc61a..6187525 100644
--- a/source/Irrlicht/COpenGLDriver.cpp
+++ b/source/Irrlicht/COpenGLDriver.cpp
@@ -2726,7 +2726,7 @@ void COpenGLDriver::setTextureRenderStates(const SMaterial& material, bool reset
 		{
 			CacheHandler->setActiveTexture(GL_TEXTURE0 + i);
 
-			if (fixedPipeline)
+			if (1 || fixedPipeline)
 			{
 				const bool isRTT = tmpTexture->isRenderTarget();
 
@@ -2742,8 +2742,9 @@ void COpenGLDriver::setTextureRenderStates(const SMaterial& material, bool reset
 					else
 						getGLTextureMatrix(glmat, Matrices[ETS_TEXTURE_0 + i]);
 					glLoadMatrixf(glmat);
+					printf("loading tex mat %d\n", i);
 				}
-			}
+			} else printf("not loading tex mat %d\n", i);
 
 			const GLenum tmpType = tmpTexture->getOpenGLTextureType();
 
```

**Comment by sfan5** [comment] 2021-04-18 18:41
With OGLES2, `testentities:yawsprite` is stuck on the default(?) texture on my Linux/NVIDIA system while texture changes due to yaw/animation works completely fine on a Windows/Intel system.

weird

**Comment by hecktest** [comment] 2021-07-29 23:48
This will likely end up being resolved by removing the fixed path and implementing the sheet transformation in the vertex shader.

**Comment by sfan5** [comment] 2021-11-19 18:18
> Someone should dig in Irrlicht history to find out when/if that was changed.

I did this today and couldn't figure out any change that would have introduced this bug. The flow to load a texture matrix would be `COpenGLSLMaterialRenderer` -> `setBasicRenderStates` -> `setTextureRenderStates` but this hasn't changed from Irrlicht 1.8.
Doesn't matter anyway, the workaround mentioned earlier can be added to IrrlichtMt and won't have any side effects.

**Closed** 2021-11-19 18:39 UTC
Labels: Bug, Blocker, @ Client / Audiovisuals, Upstream issue

**Comment by nininik0** [comment] 2023-06-12 15:42
This happens to me, also if you disable shaders then Meshes render in fulbright! But my issue was shut down because it's "invalid"
![Screenshot_20230610-173732_Minetest](https://github.com/minetest/minetest/assets/132112852/895e91ba-4531-483e-bf08-b89ac5731874)
![Screenshot_20230610-173711_Minetest](https://github.com/minetest/minetest/assets/132112852/319e9f1d-9857-49a4-bb8a-5b1cd4dc7dbe)
![Screenshot_20230610-173650_Minetest](https://github.com/minetest/minetest/assets/132112852/4f8aeb30-4aef-4541-91b4-fdfa3997c054)
![Screenshot_20230610-173518_Minetest](https://github.com/minetest/minetest/assets/132112852/ecd6e4ec-ad36-47c2-91ed-673da4cdc5d0)
![Screenshot_20230610-173324_Minetest](https://github.com/minetest/minetest/assets/132112852/4ed16a0b-a5da-4585-bc0c-89296e8e2b32)
