### ISSUE TITLE
Setting hp_max/breath_max does not update statbar

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8208] opened 2019-02-09 21:15 UTC
##### Issue type
 - Bug report
 
##### Minetest version
```
f5bdc04ab5b47bd094ba0ced5f086e8fe6b12298
```

##### Steps to reproduce
1. Obtain `luacmd`
2. Have 20 HP
3. Set your max. HP to 100 with `/lua me:set_properties({hp_max=100})`

The rendering off 20/100 HP is supposed to differ from the rendering of 100/100 HP.
It is therefore expected that the statbar updates immediately. However, this is not the case. The statbar remains unchanged.
The statbar is only update when your actual health changes (either by healing yourself or taking damage).

**Comment by jastevenson303** [comment] 2019-02-09 22:08
yes it does.

**Comment by Wuzzy2** [comment] 2019-02-09 22:37
Weird. Are you sure? Did you follow my instructions? I just tested again, I definitely experience the bug!

To be extra sure, I even re-tested in a809f7361e8a7232b3c9ec241be5adcae96b3b2d, but the bug is still here.

**Comment by NathanSalapat** [comment] 2019-02-10 00:17
I just pulled the latest code for the engine and MTG and compiled, I can confirm the behavior @Wuzzy2 is experiencing.

**Comment by rubenwardy** [comment] 2019-02-10 03:20
This is supposedly intended behaviour, but I find it bad behaviour given that there's no examples

**Comment by SmallJoker** [comment] 2019-02-10 14:00
Fix available when the maximal HP is changed on join: #7360

**Comment by paramat** [comment] 2019-02-13 02:42
#7360 merged.

**Closed by paramat** 2019-02-13 02:42 UTC
Labels: Bug
