### ISSUE TITLE
crash as : Failed to finalize m_stmt_create: UNIQUE constraint failed: auth.name

### ISSUE THREAD

**Issue by Festus1965** [minetest/minetest#12220] opened 2022-04-25 07:24 UTC
##### Minetest version

```

```

##### OS / Hardware

...

...

##### Summary

crash server at 2022-04-24 12:47:55 with:
ERROR[Main]: Failed to finalize m_stmt_create: UNIQUE constraint failed: auth.name
ERROR[Main]: Failed to finalize m_stmt_begin: cannot start a transaction within a transaction
ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod '' in callback createAuth(): : UNIQUE constraint failed: auth.name
ERROR[Main]: stack traceback:
ERROR[Main]: 	[C]: at 0x559ca855aa40

##### Steps to reproduce

no idea

**Comment by Festus1965** [comment] 2022-04-25 07:26
or like this:

here crash as of massive logging attempt same time, same IP, same nick - to register new
2022-04-24 12:57:36: 

ERROR[Main]: Failed to finalize m_stmt_create: UNIQUE constraint failed: auth.name
ERROR[Main]: Failed to finalize m_stmt_begin: cannot start a transaction within a transaction
ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod '' in callback createAuth(): Failed to start SQLite3 transaction: cannot start a transaction within a transaction
ERROR[Main]: stack traceback:
ERROR[Main]: 	[C]: at 0x563a7a544a40

had to close new register, as I have no idea how to stop
- mod namesperip does not help
- maybe I try next restart with password server for register again

**Comment by BuckarooBanzay** [comment] 2022-04-25 08:48
duplicate of #11877

**Comment by Festus1965** [comment] 2022-04-25 11:12
a hint:

I had today another 3 attacks like this,

but with mod border 'closed' I see the login massive and IP, and have time to block it via ufw in system.
I see it, I can use IP,, and server is not crashing, but also mean no new gamer.

So a solution must not be in engine, it can be done with a mod prejoin but limit then the same IP or name login, by blocking or refuse any further from same for a minute.

**Comment by LoneWolfHT** [comment] 2022-04-25 16:29
> So a solution must not be in engine, it can be done with a mod prejoin but limit then the same IP or name login, by blocking or refuse any further from same for a minute.

Does this fix things for you?

```lua
local ratelimit = {}
local after = minetest.after
local LIMIT = 1

local function remove_entry(ip)
	ratelimit[ip] = nil
end

minetest.register_on_mods_loaded(function()
	table.insert(core.registered_on_prejoinplayers, 1, function(player, ip)
		if ratelimit[ip] then
			return "You are joining too fast, please try again"
		else
			ratelimit[ip] = true
			after(LIMIT, remove_entry, ip)
		end
	end)
end)
```

**Comment by Festus1965** [comment] 2022-04-26 00:27
guess, did a mod prejoin with it, and this code.
code is ok, server restarted well, mod active ... wait for the ...hole

**Closed** 2022-04-28 17:55 UTC
Labels: Unconfirmed bug
