### ISSUE TITLE
builtin /mods command produces no output in chat if many mods are enabled

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11813] opened 2021-12-01 19:28 UTC
##### Minetest version
1dc1305ada07da8c2a278b46a34d58af86184af9

##### Summary
I installed a lot of mods and enabled them for a world.

Then I started the game and tried the `/mods` command.

The `/mods` command produced no output in in-game chat.

The following error message was output on the console:

`ACTION[Server]: Server::ProcessData(): PacketError: what=String too long`

##### Steps to reproduce
See above.

**Comment by erlehmann** [comment] 2021-12-01 20:15
I have made a script to reproduce the issue without installing many real mods:
```
#!/bin/sh -eu
for i in $(seq 32768); do
 printf '.'
 MOD_DIR=mod_"${i}"
 mkdir -p "${MOD_DIR}"
 (
     cd "${MOD_DIR}"
     touch init.lua
     >mod.conf cat <<EOF
name = ${MOD_DIR}
description = ${i}
release = ${i}
title = ${MOD_DIR}
author = ${i}
EOF
  )
done
```

**Comment by sfan5** [comment] 2021-12-01 20:25
Root cause: #9326
not sure if this should be considered duplicate

**Comment by erlehmann** [comment] 2021-12-01 20:30
@sfan5 thx, I did not know about that! For the `/mods` command, this issue can probably be fixed in Lua easily though, if you know the maximum chat message length – just send several messages that all stay under the limit.

**Comment by ronoaldo** [comment] 2022-08-02 19:54
For the /mods command it would make sense to split the output of the command into two messages? I was wondering if /mods could show a formspec with the mod list and perhaps a few more info as well but I'm not sure if this change is too drastic.

**Comment by 56independent** [comment] 2022-12-17 09:25
```
core.register_chatcommand("mods", {
	params = "",
	description = S("List mods installed on the server"),
	privs = {},
	func = function(name, param)
		local mods = core.get_modnames()
		if #mods == 0 then
			return true, S("No mods installed.")
		else
			if #mods > 100 then
				local modsToSend = {}
				for i in #mods
					if tostring(i)[1] ~= 0 then
						modsToSend.add(mods[i])
					end
				end
			else
				return true, table.concat(core.get_modnames(), ", ")
			end
		end
	end,
})
```
I've tried to write some code to implement this check but i am unsure how to make the logic work

**Comment by JazzGlobal** [comment] 2022-12-19 16:36
This issue should be closed and labeled as duplicate. The **actual** cause is #9326 and should be corrected at that level. Fixing this via Lua would mean fixing the same problem twice. The Lua fix would also be made redundant / unnecessary if fixed correctly.

**Comment by Zughy** [comment] 2022-12-19 18:21
I agree with sfan5 and JazzGlobal, closing

**Closed by Zughy** 2022-12-19 18:21 UTC
Labels: Bug, Beginner Friendly, @ Builtin
