### ISSUE TITLE
In-game content download dialog shows truncated text on “update” button (in German)

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#13902] opened 2023-10-20 22:56 UTC
### Minetest version

```true
5.7.0-279-gb1dec37ad
```

### Active renderer

OpenGL 1.4

### Irrlicht device

X11

### Operating system and version

Debian GNU/Linux 11.7

### CPU model

Intel(R) Core(TM) Duo CPU      T2400  @ 1.83GHz

### GPU model

Intel Corporation Mobile 945GM/GMS, 943/940GML Express Integrated Graphics Controller (rev 03)

### OpenGL version

1.4

### Summary

The update button in this dialog contains truncated text, see screenshot:
![minetest-580-contentdb-fail-1](https://github.com/minetest/minetest/assets/60905/66eba2b3-6160-41d2-8c6f-8fb60af900fd)

### Steps to reproduce

1. Start Minetest in German.
2. Have a lot of outdated packages.
3. Wonder why the update button is so tiny.

**Comment by rubenwardy** [comment] 2023-12-30 16:11
duplicate of #4607

**Closed by rubenwardy** 2023-12-30 16:11 UTC
Labels: Unconfirmed bug, @ Translation, @ Content / PkgMgr, Formspec
