### ISSUE TITLE
Feature Request: add 3D-mode witch render view to use it directly in CardBoard [VR]

### ISSUE THREAD

**Issue by 6543** [minetest/minetest#9533] opened 2020-03-21 17:00 UTC
## Problem

At the moment you cant realy use MineTest for VR easely.
If we #8748 would be implemented as an optional-feature ... and if there is a 3D-mode as proposed here - It would simply be two settings + a bluetooth controler to have a working VR experience

## Proposed Render mode:
![](https://opensource.com/sites/default/files/styles/image-full-size/public/lead-images/vr.png?itok=rvpEsEK0)
(do not know how this is called so I use this image - if somebody know please write a comment)

**Comment by SmallJoker** [comment] 2020-03-21 18:13
Current existing 3D modes:
https://github.com/minetest/minetest/blob/625b1005939e76d6a5b2d241635be3b8a89eb128/builtin/settingtypes.txt#L704-L714

3D mode in the pipeline: #8475
Duplicate of: #6099

**Closed by SmallJoker** 2020-03-21 18:13 UTC
Labels: Feature request
