### ISSUE TITLE
[Question] Mod crash: attempt to index local 'digger' (a nil value)

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10210] opened 2020-07-20 23:51 UTC
##### Minetest version
Minetest 5.3.0 (Linux)
```

```

##### OS / Hardware

Operating system: Ubuntu 20.04 LTS
CPU:Intel Core i5 X4
Machine: Apple Mac Mini

#### Debug 
2020-07-21 07:43:37: ACTION[Server]: Cato places node advtrains_interlocking:tcb_node at (-7,-1,13)
2020-07-21 07:43:46: ACTION[Server]: Cato places node advtrains_interlocking:tcb_node at (-9,-1,41)
2020-07-21 07:43:52: ACTION[Server]: Cato places node advtrains_interlocking:tcb_node at (10,-1,42)
2020-07-21 07:43:58: ACTION[Server]: Cato places node advtrains_interlocking:tcb_node at (10,-1,11)
2020-07-21 07:44:16: ACTION[Server]: Cato places node advtrains_interlocking:tcb_node at (8,-1,-14)
2020-07-21 07:44:20: ACTION[Server]: Cato right-clicks object 239: LuaEntitySAO "advtrains_interlocking:tcbmarker" at (9,-1,-14)
2020-07-21 07:44:31: ACTION[Server]: Cato places node advtrains_interlocking:tcb_node at (-7,-1,-6)
2020-07-21 07:44:44: ACTION[Server]: Cato digs advtrains_interlocking:tcb_node at (-7,-1,-6)
2020-07-21 07:44:45: ACTION[Server]: player Cato (id=2, hp=10) punched LuaEntitySAO "advtrains_interlocking:tcbmarker" at (-8,-1,-6) (id=399, hp=0), damage=10
2020-07-21 07:44:47: ACTION[Server]: Cato places node advtrains_interlocking:tcb_node at (-7,-1,-9)
2020-07-21 07:44:53: ACTION[Server]: player Cato (id=2, hp=10) punched LuaEntitySAO "advtrains_interlocking:tcbmarker" at (-8,-1,13) (id=426, hp=0), damage=10
2020-07-21 07:44:57: ACTION[Server]: Cato right-clicks object 427: LuaEntitySAO "advtrains_interlocking:tcbmarker" at (-8,-1,-9)
2020-07-21 07:44:58: ACTION[Server]: Cato right-clicks object 481: LuaEntitySAO "advtrains_interlocking:tcbmarker" at (-8,-1,-9)
2020-07-21 07:44:59: ACTION[Server]: player Cato (id=2, hp=10) punched LuaEntitySAO "advtrains_interlocking:tcbmarker" at (-8,-1,-9) (id=489, hp=0), damage=10
2020-07-21 07:45:02: ACTION[Server]: Cato right-clicks object 490: LuaEntitySAO "advtrains_interlocking:tcbmarker" at (-8,-1,-9)
2020-07-21 07:45:16: ACTION[Server]: Cato places node advtrains_interlocking:tcb_node at (-9,-1,-109)
2020-07-21 07:45:28: ACTION[Server]: Cato places node advtrains_interlocking:tcb_node at (-9,-1,-171)
2020-07-21 07:45:39: ACTION[Server]: Cato places node advtrains_interlocking:tcb_node at (-9,-1,-258)
2020-07-21 07:45:48: ACTION[Server]: Cato places node advtrains_interlocking:tcb_node at (-9,-1,-352)
2020-07-21 07:46:03: ACTION[Server]: Cato places node advtrains_interlocking:tcb_node at (-9,-1,-384)
2020-07-21 07:46:11: ACTION[Server]: Cato places node advtrains_interlocking:tcb_node at (-7,-1,-412)
2020-07-21 07:46:15: ACTION[Server]: Cato places node advtrains_interlocking:tcb_node at (8,-1,-412)
2020-07-21 07:46:21: ACTION[Server]: Cato places node advtrains_interlocking:tcb_node at (8,-1,-383)
2020-07-21 07:46:32: ACTION[Main]: Server: Shutting down
2020-07-21 07:46:32: ACTION[Main]: [fishing] Server shuts down. saving trophies table
2020-07-21 07:46:33: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback luaentity_Step(): /home/minetest-pvp/.minetest/mods/multitools/init.lua:178: attempt to index local 'digger' (a nil value)
2020-07-21 07:46:33: ERROR[Main]: stack traceback:
2020-07-21 07:46:33: ERROR[Main]: 	/home/minetest-pvp/.minetest/mods/multitools/init.lua:178: in function 'handle_node_drops'
2020-07-21 07:46:33: ERROR[Main]: 	/usr/share/minetest/builtin/game/item.lua:613: in function 'on_dig'
2020-07-21 07:46:33: ERROR[Main]: 	/usr/share/minetest/builtin/game/falling.lua:248: in function 'try_place'
2020-07-21 07:46:33: ERROR[Main]: 	/usr/share/minetest/builtin/game/falling.lua:358: in function </usr/share/minetest/builtin/game/falling.lua:273>

##### Summary
This error says it is a mod error that cause by a blank mod. I don't know why.

##### Steps to reproduce
I don't know

**Comment by Emojigit** [comment] 2020-07-20 23:56
Oh My God This time in my each join, the server have error again but with no error message in `debug.txt` !

**Comment by NathanSalapat** [comment] 2020-07-21 00:01
It looks to me like the multitool mod is trying to index digger, but there is no digger.
Try removing the multitool mod and see if the error persists.

**Comment by Emojigit** [comment] 2020-07-21 00:47
Anoter error also have no mod name!
2020-07-21 08:43:03: WARNING[ConnectionSend]: con(4/1) Packet quota used up for peer_id=3, was 1024 pkts
2020-07-21 08:43:50: ACTION[Server]: Cato [1.36.117.109] joins game. List of players: Cato
2020-07-21 08:43:50: WARNING[Server]: 3d_armor: Detached armor inventory is nil [set_player_armor]
2020-07-21 08:43:53: ACTION[Main]: Server: Shutting down
2020-07-21 08:43:53: ACTION[Main]: [fishing] Server shuts down. saving trophies table
2020-07-21 08:43:53: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback luaentity_Step(): /home/minetest-pvp/.minetest/mods/ethereal/crystal.lua:228: attempt to index local 'digger' (a nil value)
2020-07-21 08:43:53: ERROR[Main]: stack traceback:
2020-07-21 08:43:53: ERROR[Main]: 	/home/minetest-pvp/.minetest/mods/ethereal/crystal.lua:228: in function 'handle_node_drops'
2020-07-21 08:43:53: ERROR[Main]: 	/usr/share/minetest/builtin/game/item.lua:613: in function 'on_dig'
2020-07-21 08:43:53: ERROR[Main]: 	/usr/share/minetest/builtin/game/falling.lua:248: in function 'try_place'
2020-07-21 08:43:53: ERROR[Main]: 	/usr/share/minetest/builtin/game/falling.lua:358: in function </usr/share/minetest/builtin/game/falling.lua:273>

**Comment by Emojigit** [comment] 2020-07-21 00:48
These two errors will show when I go to a same place.

**Comment by NathanSalapat** [comment] 2020-07-21 02:49
I wonder, do you have mobs_monsters?
I had a similar issue a while back, the lava pickaxe was at fault. Updating the lava_flan code solved that for me.

**Comment by tenplus1** [comment] 2020-07-21 05:21
The error is caused by a mod using node_dig without a player name being passed on, the ethereal crystal.lua was fixed and updated already, as for multitools mod, edit the init.lua and chance line 178 to read:

if not digger and digger:get_wielded_item():get_name() ~= "multitools:multitool_crystal" then

**Comment by appgurueu** [comment] 2020-07-21 11:24
Close this and open a PR or issue on the appropriate repo (multitools mod).

**Comment by SmallJoker** [comment] 2020-07-21 16:56
Not a Minetest issue. Please ask to re-open in case there's no mod error (but an API breakage).

**Closed by SmallJoker** 2020-07-21 16:56 UTC
Labels: Invalid, Question
