### ISSUE TITLE
Add Server List Manage buttons for favorite

### ISSUE THREAD

**Issue by IFRFSX** [minetest/minetest#10395] opened 2020-09-14 12:14 UTC
add [add]/[delete] buttons.
modify server by server/port input-bar and Try to connect.

**Comment by IFRFSX** [comment] 2020-09-14 12:22
This PR was initiated because in Minetest’s "Join Game" tab, if the ip address and port of the server were entered by the player themselves, then only the last server address is always kept in the favorite list (but if the player enters a new When customizing a remote server, the port is different from the server entered in the previous (and try to connect), then both favorites will be retained), so please add two buttons to add or delete favorite servers.

**Comment by sfan5** [comment] 2020-09-16 13:54
> if the ip address and port of the server were entered by the player themselves, then only the last server address is always kept in the favorite list

that's a bug -> #9933

**Comment by rubenwardy** [comment] 2023-09-27 22:57
duplicate of #12647  (that is better written)|

**Closed by rubenwardy** 2023-09-27 22:57 UTC
Labels: Feature request, @ Mainmenu
