### ISSUE TITLE
Jumping up a node sometimes makes you sink slowly

### ISSUE THREAD

**Issue by CampbellRossM** [minetest/minetest#6813] opened 2017-12-21 04:57 UTC
Let's say you're standing at sea level, for example: The F5 menu tells us that our Y level is 1.5. If you jump up one node, the player's Y level peaks at 2.6 (as normal), but will often fall the last tenth of a meter very slowly before reaching the final height of 2.5. It's not too noticeable if you're walking, but I find it extremely noticeable if you're standing still after the jump.

More info:
Reproducible: Most of the time
How to reproduce: Jump up one node and stop walking
OS: Windows 10
Version: 0.4.16
Game: minetest_game

I know it's not major, but I haven't been playing very long and I notice it frequently. I couldn't any mention of the issue when I searched for it, so I've decided to post it.
My guess is that an "Is_Grounded()" style check sees the block below you at the top of your jump, and keeps resetting your Y-velocity. It doesn't happen when you are falling faster because you collide with the block below you before Is_Grounded() == true.

**Comment by Ezhh** [comment] 2017-12-21 11:46
This happens with both old and new movement code, and is indeed pretty annoying. I've known about it for a long time but had assumed it must have been brought up by now.

**Comment by paramat** [comment] 2017-12-21 14:49
Duplicate of #664 which explains why it happens.

**Closed by paramat** 2017-12-21 14:49 UTC
Labels: Duplicate
