### ISSUE TITLE
Smarter fall damage

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4542] opened 2016-09-22 16:51 UTC
Imagine falling from Z=1000 down to earth, by looking up you can decrease your fall speed rapidly and avoid big damage at Z=0 since when you land on notloaded chunk you reset your fall damage to 0.

I propose to make it smarter and not to reset such damage to 0 if below block is not loaded yet, but compaund it to point of impact with solid ground. So when you look up and falling, you will occasionally stop at unloaded chunk, but your damage will be calculated and compounded each time you stop on not loaded chunk, and when you touch solid ground - total sum of damage will be applied to player killing him.

I'm thick of being god in MT avoiding fall damage, please rework it (and look into shift-fall avoiding any damage on completely flat ground that was reported somewhere here by me). This affects gameplay.

**Comment by raymoo** [comment] 2016-09-22 17:48
What if you just maintain the current velocity while being stopped by ignores?

**Comment by Calinou** [comment] 2016-09-22 18:13
> What if you just maintain the current velocity while being stopped by ignores?

That was done in 0.2_20110922 (released exactly 5 years ago, at the time of writing!) and is probably a good idea.

**Comment by paramat** [comment] 2016-09-23 07:00
Duplicate of part of #1442 
There is in-depth discussion about these ideas there so please continue there.

**Closed by paramat** 2016-09-23 07:00 UTC
Labels: Bug, Duplicate
