### ISSUE TITLE
Custom URL Scheme

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10373] opened 2020-09-07 11:39 UTC
It would be nice to have `minetest://...` links to simplify actions such as selecting a server or a package. Example routes:

* `minetest://select_server?address=&port=`: Navigates to server list & selects the server with matching address and port
* `minetest://package_info/<author>/<package>`: Shows the CDB package info for the given package. Useful for online "install" buttons.

**Comment by rubenwardy** [comment] 2020-09-07 11:47
Duplicate of #7400

**Closed by rubenwardy** 2020-09-07 11:47 UTC
Labels: Feature request
