### ISSUE TITLE
Crash if calling minetest.pointed_thing_to_face_pos and pointed_thing.above and pointed_thing.below are equal

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6643] opened 2017-11-18 20:14 UTC
Tested in MT 0.4.16.

Just call `minetest.pointed_thing_to_face_pos` with a `pointed_thing` of `type="node"`, and `above` and `below` having equal positions.

There will be crash with this error:

`ERROR: /usr/share/minetest/builtin/common/misc_helpers.lua:717: Attempt to perform arithmetic on a nil value`

Example:
`minetest.pointed_thing_to_face_pos(player, {type="node", above={x=0,y=0,z=0}, below={x=0,y=0,z=0})`

How can `above` and `below` have the same positions, you ask? Easy: Just place a node when your head is *inside* a non-`walkable` and `buildable_to` node (e.g. jungle grass). Then you will get a `pointed_thing` in which both `above` and `below` have equal positions. At least in the `on_place` function of the item you place.

In Minetest Game 0.4.16, you can reproduce this if you stand inside jungle grass, fly and noclip a bit down (so you are *inside* the same node), then place a slab *inside* that jungle grass.

**Comment by paramat** [comment] 2017-12-15 00:01
Was reported again, should be an easy fix.

**Comment by SmallJoker** [comment] 2017-12-15 08:28
@MarkuBu 
As you wrote this function - could you please check whether the next face position in the direction of view can be returned here?

**Comment by MarkuBu** [comment] 2017-12-15 08:55
If you stand inside jungle grass you can't place nodes at all because you are inside the hitbox and you point to this hitbox and not to the node the crosshair points to.

All you can do is check above and below if they are equal.

Off topic: I think anyway that the hitbox of jungle grass is too big. Every time you walk through a jungle and try to punch or dig something you often hit jungle grass first. Will open an issue soon

**Comment by MarkuBu** [comment] 2017-12-15 09:08
> Just place a node when your head is inside a non-walkable and buildable_to node (e.g. jungle grass)

To be honest I can't confirm this bug. I placed jungle grass, step inside and try to place a slab somewhere. Nothing happened.

**Comment by SmallJoker** [comment] 2017-12-15 09:35
You can reproduce it by standing inside a full node with a dry shrub or jungle grass above. That's also what Wuzzy described in the first post.
![inside shrub](https://user-images.githubusercontent.com/1497498/34035792-77f2cf7c-e183-11e7-8506-2c08fb38682b.jpg)

**Comment by MarkuBu** [comment] 2017-12-15 10:26
How can I stand in a full node in a regular game? As long as "noclip" is disabled or you "glitch" into a node somehow

However, best would be to add a check if above and below are equal. I won't try to find a solution to make such a rare and uncommon situation work.

**Comment by SmallJoker** [comment] 2017-12-15 10:30
> I won't try to find a solution to make such a rare and uncommon situation work.

https://github.com/minetest/minetest/blob/f1d2bc096573627b2bbb1aa48e856f7a76e4790a/minetest.conf.example#L19-L22
Players can crash servers by turning this setting off and placing the nodes to get this condition. Is that important enough to fix it?

**Comment by MarkuBu** [comment] 2017-12-15 10:44
I already posted a solution. Check if above and below are equal. If yes, return and do nothing.

I'm not at home and can try it myself

And I didn't develop this function. The original function was from HybridDog, if I'm not wrong. I just adopted it to make it work for this situation

**Comment by MarkuBu** [comment] 2017-12-15 13:06
Two suggestions to solve this issue:

```
function core.pointed_thing_to_face_pos(placer, pointed_thing)
	if vector.equals(pointed_thing.above, pointed_thing.under) then
		return vector.new()
	end
```

If you return vector.new() a slab or stair will be placed on top of the node the player currently stands in. The jungle grass or whatever node is on top will be replaced

instead of return a new vector yo can return `nil`. But than you need to catch the nil in init.lua from the stairs mod

```
		local finepos = minetest.pointed_thing_to_face_pos(placer, pointed_thing)
		if not finepos then
			return nil
		end
		local fpos = finepos.y % 1
```

In this case only the place sound is played, but nothing else happened.

**Comment by paramat** [comment] 2017-12-15 16:53
I prefer the first solution, to simplify the code that calls it.

**Comment by paramat** [comment] 2018-05-15 22:32
Still crashing, will fix.

**Comment by paramat** [comment] 2018-05-15 23:29
PR #7342

**Comment by paramat** [comment] 2018-05-16 19:50
#7342 merged.

**Closed by paramat** 2018-05-16 19:50 UTC
Labels: @ Builtin, Bug
