### ISSUE TITLE
The "delete world" button is way too dangerous

### ISSUE THREAD

**Issue by VULONKAAZ** [minetest/minetest#3458] opened 2015-12-15 21:04 UTC
give me back all these hours of my life this button make go up in smoke

**Comment by BlockMen** [comment] 2015-12-15 21:08
There is a conformation dialog. So you clicked at least two times wrong.

**Comment by est31** [comment] 2015-12-15 21:09
I think current behaviour is okay. File managers require also only two interactions (first press del then confirm).

**Comment by rubenwardy** [comment] 2015-12-18 19:16
Is there a cross platform way of sending to the recycle bin instead?

**Comment by VULONKAAZ** [comment] 2015-12-18 19:22
oh apparently we still can comment this issue even if it's closed

The problem with the confirmation box is that the yes button is exactly at the same place as the delete world button so if we have a too sensitive mouse and if it makes several clicks at once the confirmation box become useless

**Comment by ShadowNinja** [comment] 2015-12-18 21:10
Can confirm.  The buttons need to be moved (and the confirmation dialog should be shrunk a lot).

**Comment by sapier** [comment] 2015-12-19 03:52
this ain't a bug it behaves exactly as intended and expected. But I agree if there's a way to help ppl with broken mice or other medical intended multiclicks without causing negative sideeffects we should do it. ;-)

**Comment by ShadowNinja** [comment] 2015-12-19 04:20
@sapier: The whole point of the confirmation dialogue is to prevent accidental activation.  It fails at this objective if you aren't careful or your mouse is bad, so it's a bug.

**Comment by est31** [comment] 2015-12-19 17:45
Perhaps #3267 can be changed to fix this issue then? @SmallJoker what do you think?

**Comment by sapier** [comment] 2015-12-20 12:56
@ShadowNinja it doesn't fail works quite good for me, you can ask 20 times too if ppl always click ok it'll fail then too ;-)

**Comment by paramat** [comment] 2018-02-20 15:32
#6477 merged.

**Closed by paramat** 2018-02-20 15:32 UTC
Labels: @ Client / Audiovisuals
