### ISSUE TITLE
Icon distortion in the hotbar

### ISSUE THREAD

**Issue by CandyFiend** [minetest/minetest#9861] opened 2020-05-13 16:25 UTC
![image](https://user-images.githubusercontent.com/16528385/81838527-6dd87700-9570-11ea-903e-948036750db8.png)
I watched issues, didn’t notice anything like it.

**Comment by sfan5** [comment] 2020-05-13 16:58
That screenshot is very clearly upscaled using some "advanced" algorithm, so it is unusable to show any visual issues with icons or images.

**Comment by CandyFiend** [comment] 2020-05-13 17:03
Well then, I don’t know how to show you this. Maybe there are ideas? The bottom line is that the texture pixels are not even. The sides of the pixels are of different sizes, so it looks poor. Perhaps you should take a closer look at the bottom panel, not the inventory. Although the invetatra also has a similar effect, albeit much weaker.
Not the original textures in the screenshot are drawn by me. Size 16x16.

**Comment by sfan5** [comment] 2020-05-13 17:07
Are you referring to the hearts in the hotbar? Or the items?
I suspect this maybe a duplicate of #2419, which is about the general inability to scale images correctly in the GUI/HUD.

**Comment by CandyFiend** [comment] 2020-05-13 17:08
![image](https://user-images.githubusercontent.com/16528385/81842872-f8bc7000-9576-11ea-90c4-6df146f0d912.png)

**Comment by CandyFiend** [comment] 2020-05-13 17:10
Perhaps a duplicate, they talk about this effect.

**Comment by SmallJoker** [comment] 2020-05-13 17:15
Duplicate of #2419. Scaling is overall an issue. You could try whether disabling Windows' DPI scaling has any effect, but I doubt that.

**Closed by SmallJoker** 2020-05-13 17:15 UTC
