### ISSUE TITLE
Blending between different hardware colored nodes

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#13233] opened 2023-02-19 19:04 UTC
## Problem

Colour transitions between biomes in some games such as MineClone 2 look way too rough.

## Solutions

Add a `biome_blend` graphical setting which blends the colours of certain nodes between biomes to make colour transitions look way smoother.

## Additional context

Here are some examples of biome transitions without biome blend in Minecraft:

![No Blending Grass](https://user-images.githubusercontent.com/114245896/219969305-99b006fd-a35d-4049-920a-aa10f1c71fb5.png)
![No Blending Ocean](https://user-images.githubusercontent.com/114245896/219969310-399e5f7a-e7cb-4353-849b-b6b54999d78c.png)

Here are those same examples, but now with biome blend:

![Level 1 Blending Grass](https://user-images.githubusercontent.com/114245896/219969426-012e0a9d-b492-4aae-a50b-e3ce2180a069.png)
![Level 1 Blending Ocean](https://user-images.githubusercontent.com/114245896/219969430-1a5a72d7-5f52-4e1b-bdb7-c37ea26e8014.png)

Notice how much smoother the colour transitions look. It is way less jarring on the eyes.

**Comment by ancientmarinerdev** [comment] 2023-02-19 20:05
Here are some of the blending issues when differing water colours by biome. It's quite a sharp contrast.

![water transition](https://user-images.githubusercontent.com/114887286/219972289-d68b004a-d7b2-429b-8755-def5e6c9c09b.png)
![water colour mix](https://user-images.githubusercontent.com/114887286/219972292-e923351b-4693-476c-b7e6-7ed0337760ba.png)
![water colour 2](https://user-images.githubusercontent.com/114887286/219972293-85919fdb-b467-4e8d-96da-0bb69cff93e1.png)
![water colour 1](https://user-images.githubusercontent.com/114887286/219972296-071aaece-26bc-442f-88c7-e6b175f7609d.png)

**Comment by wsor4035** [comment] 2023-02-20 04:20
can and has been done by mods https://content.minetest.net/packages/sofar/luscious/ this should be closed

**Comment by wsor4035** [comment] 2023-02-21 00:48
also a duplicate of https://github.com/minetest/minetest/issues/2816

**Comment by Wbjitscool** [comment] 2023-02-21 08:35
I would like to see biome blending though where you can change it in the settings rather then have it as a sharp cut out where it rapidly changes that it can sometimes hurt the eye's

**Comment by Zughy** [comment] 2023-03-05 12:58
Closing in favour of #2816

**Closed by Zughy** 2023-03-05 12:58 UTC
Labels: @ Client / Audiovisuals, Feature request, Possible close
