### ISSUE TITLE
minetest.sound_play Offset

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest#6714] opened 2017-11-29 14:16 UTC
I'm looking for a way to play a sound at a particular position.  So that if `sound` is three seconds long, I can do:
```
minetest.after(0, minetest.sound_play, "sound", {offset = 1})
minetest.after(0.1, minetest.sound_play, "sound")
minetest.after(0.2, minetest.sound_play, "sound", {offset = 2})
```
Any hints for https://github.com/minetest/minetest/blob/master/src/sound_openal.cpp are appreciated.

**Comment by paramat** [comment] 2017-11-30 00:58
Don't understand, you can already play sound at a position in the world.

**Comment by BluebirdGreycoat** [comment] 2017-11-30 01:58
I believe the OP wants to be able to skip forward in the sound file starting from the beginning. So `offset=2` means to skip the first 2 seconds of the sound file.

I could be misunderstanding, but I doubt a physical position is in view here, otherwise the OP would have used `x,y,z` instead of `offset`.

**Comment by paramat** [comment] 2017-11-30 02:40
Yes i suspect that's the request.

**Comment by paramat** [comment] 2017-11-30 02:44
Duplicate of #3966

**Comment by jastevenson303** [comment] 2017-11-30 05:21
That issue was asking about a region, I am asking about an offset.

Fuck you, paramat.

**Comment by paramat** [comment] 2017-11-30 06:45
Waaat =)
A region feature includes offset, you just set the end point to the end of the sound.
We can then provide both features in one go. Please continue discussion there.

**Comment by BluebirdGreycoat** [comment] 2017-11-30 06:48
Unfortunately, I cannot find a function in the OpenAL documentation to easily stop sound after reaching a certain point in the buffer. Offset is easy though.

**Comment by BluebirdGreycoat** [comment] 2017-11-30 07:02
#6719

**Closed** 2017-11-30 09:56 UTC
Labels: @ Client / Audiovisuals, @ Script API, Feature request, Sounds

**Comment by paramat** [comment] 2017-11-30 18:32
@jastevenson303 please could you clarify what you mean by 'offset'? Do you mean a way to delay the start of the sound, or being able to start the sound at any point within the sound?

**Comment by BluebirdGreycoat** [comment] 2017-11-30 18:37
Since the start of sound can already be delayed with `minetest.after()` (if a bit laggy for some cases), I think he means to skip forward in the sound track.

**Comment by paramat** [comment] 2017-11-30 19:12
That's what i'm assuming.

**Comment by jastevenson303** [comment] 2017-12-01 13:18
I am deeply sorry for disrespecting you, paramat.  I removed my comment, but of course the damage is done.  You work very hard, and contribute so much, and are very much appreciated.

Again, I am sorry.  (This issue is silly, and I should learn to search before creating a new ticket.  Though FWIW, there is a difference between an offset and a range -- a range may include an offset, but an offset may not include a range.  I will continue any further discussion in the appropriate thread.)

**Comment by paramat** [comment] 2017-12-01 21:45
Ok thanks, i didn't take it too seriously =)

**Comment by jastevenson303** [comment] 2019-01-12 11:07
range and offset are close but not duplicates.  i would like to see an issue with a collection of these types of requests/comments.

**Comment by paramat** [comment] 2019-01-13 06:16
Issues that collect other issues are a pain to maintain and messy in practice, issues should be separate, they can always have links to other related issues.

**Comment by jastevenson303** [comment] 2019-01-13 13:19
I used to agree, but every issue I open you color-by-labels and promptly
close.  I'm not the only one, either.  Sorry, just my observation.

**Comment by paramat** [comment] 2019-01-14 14:06
LOL.
