### ISSUE TITLE
chage `lua_api.txt` to `lua_api.md`

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10539] opened 2020-10-22 08:54 UTC
## Problem

The `lua_api.txt` is markdown format, it shoud have a `.md` suffix.

## Solutions

Move `lua_api.txt` to `lua_api.md`.

**Comment by rubenwardy** [comment] 2020-10-22 09:44
Duplicate of #1919

The lua_api is in .txt because it allows linking to a specific line

**Closed by rubenwardy** 2020-10-22 09:44 UTC
Labels: Feature request
