### ISSUE TITLE
Dynamic view range depending on frame rate

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4459] opened 2016-08-21 09:24 UTC
I like to play with a higher view range and most time it works fine, but sometimes the frame rate drops below a playable value, e.g. if I walk through a huge forest and look back in the direction where I come from

My idea is to adjust the view range depending on the frame rate. I would set a minimum view frame rate and a minimum view range. The view range should never go below the minimum view range and the game should try to hold the frame rate above the minimum frame rate as long as possible

**Comment by asl97** [comment] 2016-08-21 09:36
that was how it works before, except (afaik) it didn't work that great.

https://github.com/minetest/minetest/pull/3749
https://github.com/minetest/minetest/pull/3720

**Comment by MarkuBu** [comment] 2016-08-21 10:01
Oh, didn't know that

**Comment by est31** [comment] 2016-08-21 15:22
It was there, but removed wit commit b2aabdfe074d361b69c59f7ea29a85f060330f12 .

Its a done discussion, minetest won't get dynamic viewing range.

**Comment by VanessaE** [comment] 2017-02-18 16:32
@est31 actually that has not been established.  The problem is no one has come up with a good way to do it.  User-adjustable view range just does not work well in practice.

**Comment by Zeno-** [comment] 2017-02-18 17:14
No need for close at the moment IMO.

**Comment by paramat** [comment] 2017-03-21 19:53
:-1: Yes we had this but despite being tuned many times it was a problem, many players ended up setting their min and max view ranges equal to disable it, it was also fairly complex code running in an intensively used place.

**Comment by VanessaE** [comment] 2017-03-21 21:44
As I've always said, it's better to have a feature that can be disabled when people don't like it, than to not have it at all (and thus, there's nothing for people who want it to *en*able).

**Comment by paramat** [comment] 2017-03-21 22:08
Well, it's not a case of people dislikiing it, it just didn't work however it was tuned, so in this case there's no justification for having it even as an option.

**Comment by VanessaE** [comment] 2017-03-21 22:23
I may have complained about it being buggy, but it DID work, and it was a lot better than fixed view range is, at least for me.  (insert https://xkcd.com/1172/ here :stuck_out_tongue: ).

**Comment by nerzhul** [comment] 2017-05-20 14:34
Closing the issue

**Closed by nerzhul** 2017-05-20 14:34 UTC
Labels: Feature request, Possible close

**Comment by paramat** [comment] 2017-05-20 14:54
I agree with the close.
