### ISSUE TITLE
Cant pickup cart

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#12610] opened 2022-07-29 02:41 UTC
##### Minetest version

```
Tested on 5.4.2, 5.5.0, 5.5.1
```

##### OS / Hardware

Operating system: Android 6.0.1 (API Level 23)
CPU: Mediatek MT6734

GPU model:
OpenGL version: ES 3.1

##### Summary

I  cannot pickup cart on my phone
i tried double tap when sneaking and long tap when sneaking, both dont work

video:
https://youtu.be/v-CoUqEfAsY

##### Steps to reproduce

idk

**Comment by oong819** [comment] 2022-07-29 03:47
API level 23

**Comment by oong819** [comment] 2022-07-30 05:02
now have a video

**Comment by wwar-XeStro** [comment] 2022-07-31 14:43
👀 nope you totally can.
Start long tapping before sneaking.


Start your long tap, shortly after that sneak without holding your finger you are tapping with :)


Also worthes notting that long tapping *after* starting to sneak, use aux1 or jump is impossible in android. It is also impossible to move the camera while long tapping....

**Comment by rubenwardy** [comment] 2022-08-01 12:35
duplicate of #11404

**Closed by rubenwardy** 2022-08-01 12:35 UTC
Labels: Unconfirmed bug, Android, @ Client / Controls / Input, UI/UX
