### ISSUE TITLE
Allow autoforwards to control minetest.get_player_control().up

### ISSUE THREAD

**Issue by archfan7411** [minetest/minetest#8528] opened 2019-05-12 14:41 UTC
##### Issue type

 - Feature request
 
##### Minetest version

```
5.0.1
```

##### OS / Hardware

Operating system: N/A
CPU: N/A

GPU model: N/A
OpenGL version: N/A

##### Summary

While autoforwards does indeed cause the player to walk forwards as expected, it does not play the walking animation (possibly an issue with playeranim, which I use), nor does it cause boats to go forward if the player is in one.

Therefore I assume that autoforward doesn't set minetest.get_player_controls().up, and would like to request this functionality.

##### Steps to reproduce

Simplest way to test is to enable autoforward whilst in a boat.

**Comment by DS-Minetest** [comment] 2019-05-12 16:00
Duplicate of #7805.
And there's already a PR to fix this.

**Closed** 2019-05-12 16:16 UTC
Labels: Duplicate

**Comment by archfan7411** [comment] 2019-05-12 17:34
Ah, my apologies

**Comment by paramat** [comment] 2019-05-12 19:00
No problem =) there are so many issues it's easy to duplicate one. We appreciate you reporting this.
