### ISSUE TITLE
The unicode characters crowded together on the chat prompt line.

### ISSUE THREAD

**Issue by snowyu** [minetest/minetest#12866] opened 2022-10-17 01:23 UTC
##### Minetest version
```
Minetest 5.7.0-edu-25c540025-dirty (Linux)
Using Irrlicht 1.9.0mt8
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### Summary

![mt_chat_prompt_bug](https://user-images.githubusercontent.com/327887/196069946-4eaf4251-b533-403b-9636-9d42e601247e.png)

##### Steps to reproduce

Press `T` key in game, type some unicode characters on the chat prompt line.

**Comment by sfan5** [comment] 2022-10-17 07:39
duplicate of #12200

**Closed by sfan5** 2022-10-17 07:39 UTC
Labels: Unconfirmed bug
