### ISSUE TITLE
OSX - Formspec buttons offset

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2725] opened 2015-05-27 03:35 UTC
When pressing any button (or selecting a field/text box) on a formspec, I always have to move my mouse slightly upwards. This does not happen in game for punching, digging, etc.

Minetest 0.4.12, OSX 0.9

**Comment by nanepiwo** [comment] 2015-05-28 03:47
This seems to only happen if I do shift + maximize window to increase the window size

**Comment by mdoege** [comment] 2015-06-02 12:02
Yes, if you resize the MT window while it is running apparently mouse coordinates for formspecs still refer to the old window size somehow. Resizing MT works on Linux, so I'm not sure what the problem on OS X is.

**Comment by neoascetic** [comment] 2016-11-24 21:16
Duplicate of #1614

**Closed** 2020-05-06 09:26 UTC
Labels: Bug, Formspec, Mac OS, Possible close
