### ISSUE TITLE
Crash when player randomly gets a inf value in x,y or z pos.

### ISSUE THREAD

**Issue by za267** [minetest/minetest#9473] opened 2020-03-06 21:52 UTC
##### Minetest version
```
5.0.1
```

##### OS / Hardware
Operating system: Fedora 30
CPU: KVM Intel Core Processor (Haswell, no TSX, IBRS)

##### Summary
I have a player who 'seemingly' randomly gets sent to 'inf' (infinite) in one of the x,y,z coord at various times. When this happens he has a few seconds to go back to his /home. However, if he doesn't at some point the server crashes with the following error log:

2020-03-06 16:14:31: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '*builtin*' in callback on_chat_message(): Invalid float vector dimension range 'y' (expected -2.14748e+06 < y < 2.14748e+06 got -2.14748e+06).
2020-03-06 16:14:31: ERROR[Main]: stack traceback:
2020-03-06 16:14:31: ERROR[Main]:       [C]: in function 'set_pos'
2020-03-06 16:14:31: ERROR[Main]:       /usr/local/share/minetest/builtin/game/chatcommands.lua:401: in function 'func'
2020-03-06 16:14:31: ERROR[Main]:       /usr/local/share/minetest/builtin/game/chatcommands.lua:30: in function </usr/local/share/minetest/builtin/game/chatcommands.lua:9>
2020-03-06 16:14:31: ERROR[Main]:       /usr/local/share/minetest/builtin/game/register.lua:419: in function </usr/local/share/minetest/builtin/game/register.lua:399>

##### Steps to reproduce
So far, I can't reproduce

**Comment by paramat** [comment] 2020-03-06 22:03
Duplicate of #5135

**Closed by paramat** 2020-03-06 22:03 UTC
Labels: Bug, Duplicate
