### ISSUE TITLE
Zoom loads/generates in 2 opposite directions

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6683] opened 2017-11-26 05:24 UTC
![zoom1deg2](https://user-images.githubusercontent.com/3686677/46250983-f6a7ab00-c43e-11e8-8775-5f6144ed3bc3.jpg)

^ Mgflat looking NW with zoom FOV 1 degree. Player is at centre of large blob, at 0,0.
Zoom extends NW by 2500 nodes. Backwards loading extends SE by 1000 nodes.

Immediately after spawning in a new mgflat world with decorations disabled, use a powerful zoom of 1 degree, keep your view precisely level, look in 1 fixed direction, hold 'zoom' and take some time to load in distant world until it stops loading. Then map the world.

Probably caused by ae9b1aa1774aedca8f452514d9462c281e36773a

**Comment by paramat** [comment] 2017-11-26 21:43
Please could you also fix https://github.com/minetest/minetest/pull/6539#issuecomment-346370777 in this PR?

**Comment by lhofhansl** [comment] 2017-11-30 07:05
I assume it loaded the blocks far back behind player as well... Hmm... That's not a bug per se.

You wanted that FOV hardcoded instead of deriving it from the passed FOV :)

We could do two things:
1. Reduce the back FOV from 0.1, to 0.01 (about 0.6 degree, smaller than any zoom we'd allow). That would still load the blocks behind the player and so achieve the goal. And 
2. Limit the back volume to some max distance. Perhaps min(requested distance, 80) (80 is 5 mapblocks, and should be plenty.)

**Comment by lhofhansl** [comment] 2017-11-30 08:04
@paramat Are you just standing still? You're moving backwards while you're zooming, right?
The extra blocks are only loaded when the player is moving and then only in the direction of the movement.

**Comment by lhofhansl** [comment] 2017-11-30 08:42
Looks like this has to do with small FOVs. In that case isBlockInSight does not behave correctly, it seems include blocks in both cones (even without my change).

**Comment by lhofhansl** [comment] 2017-11-30 09:03
I suspect this code: [numeric.cpp](https://github.com/minetest/minetest/blob/master/src/util/numeric.cpp#L144)

**Comment by lhofhansl** [comment] 2017-11-30 18:00
Yes. That's the cause. The extra loading goes away when I remove that part. (but it leads to other rendering glitches).

Not sure how to fix this. Could limit the effect, perhaps to the passed range.

**Comment by paramat** [comment] 2017-11-30 19:04
I was not moving backwards when zooming as far as i remember, but can test again.
Indeed this only happens with very small zoomFOV.

> The camera position is adjusted such that the center of any mapblock that is partially visible will also be in sight. The smaller the FOV, the larger the adjustment.

Ahh. It would be good to limit this since it causes a large extra load of generating and/or loading full mapchunks for 1000s of nodes behind.

**Comment by paramat** [comment] 2017-11-30 23:21
Fine by me.

**Comment by lhofhansl** [comment] 2017-12-08 06:42
Actually... The zoom is limited to 1 degree, right? In that case the max effect 1/0.0087 or 114.
I think there's nothing to do here.

Let's just close it.

**Comment by paramat** [comment] 2017-12-08 23:28
Well, it still needs fixing, it generates and loads a large amount of unnecessary world.
How about keeping the camera offset method but only loading blocks that are on the 'view direction' side of the player? Imagine a line drawn through the player position, perpendicular to view direction, only load blocks on the 'view direction' side of that line.

**Comment by paramat** [comment] 2018-04-08 19:59
I'll try to attend to this sometime.

**Comment by paramat** [comment] 2018-09-27 19:04
@lhofhansl 
> Are you just standing still? You're moving backwards while you're zooming, right?

Standing still.

**Comment by paramat** [comment] 2018-09-29 22:31
Added map to first post, 1000 nodes of back-loading when zoom FOV is 1 degree.

**Closed** 2021-11-19 20:18 UTC
Labels: Bug, @ Server / Client / Env., Possible close
