### ISSUE TITLE
No minimap button for android

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2857] opened 2015-06-30 01:32 UTC
Self-explanatory. I added the relevant lines to the minetest.conf on my tablet. I tried the same commit on my laptop, and it worked fine.

**Comment by RealBadAngel** [comment] 2015-06-30 07:29
i had no chance to test minimap on any android device yet
i will try to get one for tests

**Comment by Wayward1** [comment] 2015-06-30 11:58
Oh, I didn't realize just editing the minetest.conf wouldn't work.

**Comment by nerzhul** [comment] 2015-06-30 12:19
@RealBadAngel adding a button on the Android GUI (discrete button) is the solution to toggle minimap states

**Comment by RealBadAngel** [comment] 2015-06-30 13:24
@nerzhul as i mentioned already, i cant test such change, somebody with an android should code it

**Comment by est31** [comment] 2015-06-30 15:45
We need some good concept to not fill the screen with too much buttons, but not hide functionality in too deep menues. Also, perhaps there should be different setups between tablets (with a huge scree) and smartphones (with a small screen).

**Comment by RealBadAngel** [comment] 2015-06-30 16:23
or add a hotbat button that will show menu with less frequent used ones.

**Comment by nanepiwo** [comment] 2015-07-05 03:27
I like @est31 's idea.

**Comment by MoNTE48** [comment] 2015-11-19 23:05
If you give me the picture button, I'll do it.
The problem is that even on my Galaxy S6 Egde FPS drops from 35 to 15 enabled in the minimap. It is not optimized now and it's a bad idea!

**Comment by paramat** [comment] 2017-09-14 03:52
Anyone interested in coding this or creating the icon for MoNTE48? If not closing in 1 month.
The performance impact of minimap is an issue for some ddevices.

**Comment by paramat** [comment] 2017-09-15 03:33
@MoNTE48 do you have a commit that does this?

**Comment by paramat** [comment] 2018-04-11 19:20
Should be hidden in a menu as is not needed instantly.
@srifqi

**Comment by srifqi** [comment] 2018-04-13 02:54
I have suggestion for texture:
![minimap_btn](https://user-images.githubusercontent.com/4017302/38714427-68cb08ea-3f00-11e8-9373-bb4af9f77820.png)
^ minimap, inspired from folded map

**Comment by SmallJoker** [comment] 2018-04-18 18:56
#7240 merged.

**Closed by SmallJoker** 2018-04-18 18:56 UTC
Labels: @ Client / Controls / Input, Android, Feature request
