### ISSUE TITLE
minetest.delete_area is crashy

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3032] opened 2015-08-10 16:21 UTC
If you play around with the `minetest.delete_area` call, you will notice crashes happening.

**Comment by rubenwardy** [comment] 2015-08-11 08:29
I run a 24/7 server which utilises `minetest.delete_area` quite a lot - Capture the Flag. I'm willing to run tests, etc.

**Comment by est31** [comment] 2015-08-11 13:54
I think this is a blocker issue, because the crashiness makes `delete_area` almost unusable.

**Comment by kwolekr** [comment] 2015-08-14 04:42
I can't reproduce any crashing.  It just seems that delete_area() is very slow and blocks ServerThread while the 10,000 delete queries are being executed, so no new map is sent.
Setting sqlite_synchronous = 0 makes the reset operation very fast and the CTF mod works as it should, though.

**Comment by rubenwardy** [comment] 2015-08-14 07:35
I haven't received any more Segfaults like I reported in #2913 such as https://gist.github.com/rubenwardy/1bd7c25fdaf065677a76 and the map freezing has stopped.

kwolekr, the map being frozen was hours after the delete_areas was executed. And the f5 said that the client was receiving packets.

**Comment by est31** [comment] 2015-08-14 12:18
I'm ok with removing the blocker and high prio tags, and adding the unconfirmed label, perhaps it has been, as hmmm said, "accidentially" fixed already.

**Comment by kwolekr** [comment] 2015-08-14 19:20
I think you're referring to the bug fixed here https://github.com/minetest/minetest/commit/67997af67fbf7c95e78574f810aa322275b3eb66 (which wasn't related to any defect in delete_area(), but another part of code that had its own problems exposed)

**Comment by kwolekr** [comment] 2015-11-01 03:06
Closing this now.  If the problem ever persists again, don't hesitate to re-open the issue.

**Closed by kwolekr** 2015-11-01 03:06 UTC
Labels: @ Script API, @ Server / Client / Env., unconfirmed bug

**Comment by 0-afflatus** [comment] 2015-11-04 15:08
I did experience this. I found smaller areas to be ok but experienced crashes with larger areas. I will test again with a post Aug 1st build.
