### ISSUE TITLE
Dyanmic Shadows Shaders Fail To Compile On OGLES2

### ISSUE THREAD

**Issue by TheBrokenRail** [minetest/minetest#11572] opened 2021-08-24 20:01 UTC
##### Minetest version
```
Minetest 5.5.0-dev-ff3aa18 (Linux)
Using Irrlicht 1.9.0mt3
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware
Operating system: Ubuntu 20.04
CPU: AMD Ryzen 3700U
GPU model: AMD Radeon RX Vega 10
OpenGL version: Open GL ES 2.0

##### Summary
When dynamic shadows are enabled, the shaders fail to compile.

Log: [minetest-gles2.log](https://github.com/minetest/minetest/files/7041797/minetest-gles2.log)

##### Steps to reproduce
1. Build Minetest Using Open GL ES 2.0
2. Ensure Open GL ES 2.0 Is Being Used
3. Enable Dynamic Shadows
4. Open A World
5. Observer The Errors

**Comment by sfan5** [comment] 2021-08-24 21:05
duplicate of #11572

**Closed by sfan5** 2021-08-24 21:05 UTC
Labels: Unconfirmed bug
