### ISSUE TITLE
util/srp.cpp:432 out of bounds

### ISSUE THREAD

**Issue by TP75** [minetest/minetest#12068] opened 2022-02-12 18:42 UTC
##### Minetest version

```
5.5.0
```

##### OS / Hardware

Operating system: Debian 11.2 Bullseye
System Info: `Linux debian 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux`
CPU: x86_64

GPU model: --
OpenGL version: --

Compiler version: gcc-10 / g++ 10.2.1-6 amd64

##### Summary

Compile gets an **out of bounds warning**. However, the source was compiled successfully. 

##### Steps to reproduce

Download sources of Minetest5 5.5.0 from git repository and compile on Debian 11 Bullseye.  The source was compiled successfully on two different machines. However, an **out of bounds warning** occured during compile.

Please be aware the system environment used has no X11 Desktop installed intentionally.

Source files used:
  * https://github.com/minetest/minetest/archive/refs/tags/5.5.0.tar.gz
  * https://github.com/minetest/minetest_game/archive/refs/tags/5.5.0.tar.gz
  * https://github.com/minetest/irrlicht/archive/refs/tags/1.9.0mt4.tar.gz

Install dependencies:

```
sudo apt install libfreetype-dev libgmp-dev libjsoncpp-dev libpng-dev libjpeg-dev libxxf86vm-dev libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev libgmp-dev libjsoncpp-dev libluajit-5.1-dev libzstd-dev libspatialindex-dev libncurses-dev libpq-dev doxygen doxygen-doxyparse
```

Configure & Make:

```
cmake . -DRUN_IN_PLACE=TRUE -DBUILD_CLIENT=FALSE -DBUILD_SERVER=TRUE -DIRRLICHT_INCLUDE_DIR=../irrlicht-1.9.0mt4/include -DENABLE_LEVELDB=OFF -DENABLE_REDIS=OFF
make
```

Snippet from **make** run output:

```
[...]
[ 67%] Building CXX object src/CMakeFiles/minetestserver.dir/util/srp.cpp.o
In function ‘SRP_Result H_ns(__mpz_struct*, SRP_HashAlgorithm, const unsigned char*, size_t, const unsigned char*, uint32_t)’,
    inlined from ‘int calculate_x(__mpz_struct*, SRP_HashAlgorithm, const unsigned char*, size_t, const char*, const unsigned char*, size_t)’ at /home/xxx/Developer/Minetest5/minetest-5.5.0/src/util/srp.cpp:455:13:
/home/xxx/Developer/Minetest5/minetest-5.5.0/src/util/srp.cpp:432:8: warning: ‘void* memcpy(void*, const void*, size_t)’ forming offset [64, 4294967294] is out of the bounds [0, 64] of object ‘ucp_hash’ with type ‘unsigned char [64]’ [-Warray-bounds]
  432 |  memcpy(bin + len_n, bytes, len_bytes);
      |  ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xxx/Developer/Minetest5/minetest-5.5.0/src/util/srp.cpp: In function ‘int calculate_x(__mpz_struct*, SRP_HashAlgorithm, const unsigned char*, size_t, const char*, const unsigned char*, size_t)’:
/home/xxx/Developer/Minetest5/minetest-5.5.0/src/util/srp.cpp:443:16: note: ‘ucp_hash’ declared here
  443 |  unsigned char ucp_hash[SHA512_DIGEST_LENGTH];
      |                ^~~~~~~~
[ 68%] Building CXX object src/CMakeFiles/minetestserver.dir/util/string.cpp.o
[...]
````

Output from **cmake -LH**

```
-- *** Will build version 5.5.0 ***
-- Found Irrlicht headers: /home/xxx/Developer/Minetest5/irrlicht-1.9.0mt4/include
-- Found IrrlichtMt 
-- Using GMP provided by system.
-- Using JsonCpp provided by system.
-- Using LuaJIT provided by system.
-- cURL support enabled.
-- GetText disabled.
-- ncurses console enabled.
-- PostgreSQL backend enabled
-- PostgreSQL includes: /usr/include/postgresql
-- Prometheus client disabled.
-- SpatialIndex AreaStore backend enabled.
-- Looking for ZSTD_initCStream
-- Looking for ZSTD_initCStream - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxx/Developer/Minetest5/minetest-5.5.0
-- Cache values
// Use a blacklist to avoid known broken locales
APPLY_LOCALE_BLACKLIST:BOOL=ON

// Build client
BUILD_CLIENT:BOOL=FALSE

// Build server
BUILD_SERVER:BOOL=TRUE

// Build unittests
BUILD_UNITTESTS:BOOL=TRUE

// Choose the type of build. Options are: None Debug SemiDebug RelWithDebInfo MinSizeRel.
CMAKE_BUILD_TYPE:STRING=Release

// Install path prefix, prepended onto install directories.
CMAKE_INSTALL_PREFIX:PATH=/usr/local

// Directory to install binaries into
CUSTOM_BINDIR:STRING=

// Directory to install documentation into
CUSTOM_DOCDIR:STRING=

// Directory to install example config file into
CUSTOM_EXAMPLE_CONF_DIR:STRING=

// Directory to install icons into
CUSTOM_ICONDIR:STRING=

// Directory to install l10n files into
CUSTOM_LOCALEDIR:STRING=

// Directory to install manpages into
CUSTOM_MANDIR:STRING=

// Directory to install data files into
CUSTOM_SHAREDIR:STRING=

// Directory to install .desktop files into
CUSTOM_XDG_APPS_DIR:STRING=

// Enable cURL support for fetching media
ENABLE_CURL:BOOL=ON

// Enable ncurses console
ENABLE_CURSES:BOOL=ON

// Use GetText for internationalization
ENABLE_GETTEXT:BOOL=OFF

// Enable LevelDB backend
ENABLE_LEVELDB:BOOL=OFF

// Enable LuaJIT support
ENABLE_LUAJIT:BOOL=ON

// Enable PostgreSQL backend
ENABLE_POSTGRESQL:BOOL=ON

// Enable prometheus client support
ENABLE_PROMETHEUS:BOOL=OFF

// Enable Redis backend
ENABLE_REDIS:BOOL=OFF

// Enable sound
ENABLE_SOUND:BOOL=ON

// Enable SpatialIndex AreaStore backend
ENABLE_SPATIAL:BOOL=ON

// Use GMP from system
ENABLE_SYSTEM_GMP:BOOL=ON

// Enable using a system-wide JsonCpp
ENABLE_SYSTEM_JSONCPP:BOOL=ON

// Enable Touchscreen support
ENABLE_TOUCH:BOOL=OFF

// Path to IrrlichtMt build directory.
IRRLICHTMT_BUILD_DIR:PATH=

// Path to the directory with IrrlichtMt includes
IRRLICHT_INCLUDE_DIR:PATH=/home/xxx/Developer/Minetest5/irrlicht-1.9.0mt4/include

// The directory containing a CMake configuration file for IrrlichtMt.
IrrlichtMt_DIR:PATH=IrrlichtMt_DIR-NOTFOUND

// Require LuaJIT support
REQUIRE_LUAJIT:BOOL=OFF

// Run directly in source directory structure
RUN_IN_PLACE:BOOL=TRUE

// Path to a file.
SPATIAL_INCLUDE_DIR:PATH=/usr/include

// Path to a library.
SPATIAL_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libspatialindex.so

// Use -pg flag for g++
USE_GPROF:BOOL=FALSE

// Stuff to append to version string
VERSION_EXTRA:STRING=

// Enable -Wall for Release build
WARN_ALL:BOOL=TRUE

```

**Comment by TP75** [comment] 2022-02-12 20:18
Nevertheless this seems to be quite a clean code and no further warnings.

Good job and thanks the effort of the Minetest developers!

**Comment by SmallJoker** [comment] 2022-02-12 21:13
Duplicate of #10446 which is a duplicate of #10238

**Closed by SmallJoker** 2022-02-12 21:13 UTC
Labels: Unconfirmed bug
