### ISSUE TITLE
LUA API: set_rotation method for entities (and players?)

### ISSUE THREAD

**Issue by CoderForTheBetter** [minetest/minetest#7323] opened 2018-05-12 21:43 UTC
##### Issue type
 - Feature request

Right now all we have for setting the rotation of entities is set_yaw(radians) but a method like set_rotation({x=0, y=0, z=0}) would give a lot more flexibility for on the fly manipulation of entities (could have pitch and roll). 

As of now, if I want to give an entity any rotation, except for yaw, I have to attach it to another entity and use set_attach to give it the rotation I want (the last parameter of set_attach is local rotation). Then to update the rotation of the entity I have to repeatedly call set_attach with the new rotation, which probably has a bigger performance hit than a set_rotation method would.

Also, I'm not sure what would happen with the hitbox but I feel that should rotate as well.

I've looked at the code but can not figure out where Irrlicht actually sets the yaw of the model/entity when using the LUA method set_yaw(), I think I understand where it is implemented in the LUA part of the engine, just not the Irrlicht part. If someone can point that out maybe I can do this myself.

Thanks!

**Comment by Wuzzy2** [comment] 2018-05-12 22:38
The function should not be called `set_rotation({x=0, y=0, z=0})`.
We should have a complete set of functions instead: `set_yaw`, `set_pitch` and `set_roll`.

Duplicate of https://github.com/minetest/minetest/issues/2251.

**Comment by CoderForTheBetter** [comment] 2018-05-13 07:30
@Wuzzy2  Good idea Wuzzy, that does seem like a better/more clear way of doing things. I figured out how everything is sent from the server to the client and then where the model is updated/rotated. This is what I have so far:
[GIF](https://thumbs.gfycat.com/SameEvilGrayreefshark-size_restricted.gif)

**Comment by CoderForTheBetter** [comment] 2018-05-13 07:33
@Wuzzy2 Good idea Wuzzy. That seems like a more understandable/clear way of doing things. 
![sameevilgrayreefshark-size_restricted](https://user-images.githubusercontent.com/28787282/39964985-52756f48-565e-11e8-89e8-256ab236f611.gif)

**Comment by SmallJoker** [comment] 2018-05-13 09:11
Pitch/roll feature request: #2251
Rotatable collision/selection boxes:  #2721 and #3996

PS: It's "Lua". [This here is LUA](https://github.com/mniip/LUA).

**Closed by SmallJoker** 2018-05-13 09:11 UTC

**Comment by paramat** [comment] 2018-05-13 15:38
Impressive, experimentation with this is certainly welcome.
I'm actually not good at this area of code so can't help with technical stuff :)
