### ISSUE TITLE
HUDs need an ID property

### ISSUE THREAD

**Issue by discon-nected** [minetest/minetest#8148] opened 2019-01-31 18:44 UTC
Bug report
5.0.0-dev

I have found that calling `hud_change` fails occasionally  for some players  and crashes the hud. I decided to work around this issue by removing and adding the hud again with each hud update. Then I found a new problem, `hud_remove` occasionally fails as well, leaving the hud visible. At least it does not crash the hud entirely. However, after the next call to `remove_hud` only the newest hud is removed, which means an artifact remains from the previous unremoved hud...
![selection_180](https://user-images.githubusercontent.com/20234985/52076737-33a1cb00-25f4-11e9-9e80-74e0be79f0e0.jpg)
I have an on-screen timer which is created like this:
```
console_timer = player:hud_add({
	hud_elem_type = "text",
	position  = {x = 0.5, y = 0},
	offset    = {x = 0, y = 50},
	text      = time,
	alignment = { x = 0, y = 0 },
	scale     = { x = 100, y = 15},
	number    = 0xFFFFFF,
	})
```
I remove the timer and add again like this:
```
player:hud_remove(console_timer)
    console_timer = player:hud_add({
	hud_elem_type = "text",
	position  = {x = 0.5, y = 0},
	offset    = {x = 0, y = 50},
	text      = time,
	alignment = { x = 0, y = 0 },
	scale     = { x = 100, y = 15},
	number    = 0xFFFFFF,
	})
```
The fact that the previous hud with the same ID is not removed, the next time the script loops, means that "`console_timer`" is not a unique identifier for the hud. Multiple huds can be running at this point with the same ID, but responding independent of eachother. I think this could be the cause of `hud_remove` failing occasionally. In addition, it is the reason why the old hud does not respond to `hud_remove`. Currently we define a hud's ID with the variable name used to create them. This should be replaced with something similar to:
```
player:hud_add({
        id = unique_identifier,
	hud_elem_type = "text",
	position  = {x = 0.5, y = 0},
	offset    = {x = 0, y = 50},
	text      = time,
	alignment = { x = 0, y = 0 },
	scale     = { x = 100, y = 15},
	number    = 0xFFFFFF,
	})
```
And then remove or update like this:
`player:hud_change(unique_identifier, "text", time)`
There should never be more than one hud for a given player that exists with the same `unique_identifier`. The current method allows ambiguity and multiple instances of the same hud ID for a particular player.

Currently, if a hud with the same ID is accidentally created twice, by system error or otherwise, there is no way to control or remove the previous instance.

With the proposed method, if `hud_add` is called using the same `unique_identifier`, the previous HUD instance should be removed and replaced.

**Comment by SmallJoker** [comment] 2019-02-02 10:44
Thing is, there are already unique identifiers. The returned HUD ID is unique server-wide. Maybe it screws up due to the ID=0 and 1 which still exist, but are abandoned. -> #7348

I also found out that the packets sometimes get out of order (maybe due to UDP?), thus you sometimes cannot rely on that hud_change events are received as you would expect.

**Comment by mixrat** [comment] 2019-02-02 17:05
Run this in a loop and you get a new artifact with each iteration...
```
player:hud_remove(console_timer)
console_timer = player:hud_add({
	hud_elem_type = "text",
	position  = {x = 0.5, y = 0},
	offset    = {x = 0, y = 50},
	text      = time,
	alignment = { x = 0, y = 0 },
	scale     = { x = 100, y = 15},
	number    = 0xFFFFFF,
	})
console_timer = player:hud_add({
	hud_elem_type = "text",
	position  = {x = 0.5, y = 0},
	offset    = {x = 0, y = 50},
	text      = time,
	alignment = { x = 0, y = 0 },
	scale     = { x = 100, y = 15},
	number    = 0xFFFFFF,
	})
```
With a unique identified such as a primary index in mysql, you should never have more than one element using the ID. At the moment, there is no such enforecement. So when something like the above happens by accident, there is no way to correct it unless the player leaves and rejoins.

**Comment by mixrat** [comment] 2019-02-02 19:58
Didn't know I could get a returned ID. But why not provide the unique ID when the HUD is created? So in the example above there can only ever be 1 HUD with ID 'console' for playerX. And why would `player:hud_remove(console_timer)` work in the first place if I am not using the returned HUD ID?

**Comment by mixrat** [comment] 2019-02-02 22:09
> I also found out that the packets sometimes get out of order (maybe due to UDP?), thus you sometimes cannot rely on that hud_change events are received as you would expect.

Wouldn't this proposal fix that?

**Comment by discon-nected** [comment] 2019-03-18 19:12
**sfan5** found the issue. Evidently we broke curl-dev on our machine at some point _**and**_ failed to include the `-DENABLE_CURL=1` flag when building.

**Comment by paramat** [comment] 2020-02-22 01:36
@SmallJoker should this issue be kept open? Is there actually some kind of bug here?

**Comment by SmallJoker** [comment] 2020-02-22 10:12
I'd suggest to close this issue like here https://github.com/minetest/minetest/issues/7052#issuecomment-464439549 - unless someone can still reproduce it.

**Comment by paramat** [comment] 2020-02-25 03:16
Ok.

**Closed by paramat** 2020-02-25 03:16 UTC
Labels: Feature request, Possible close, Unconfirmed bug
