### ISSUE TITLE
Possibly expose third person view modes to lua

### ISSUE THREAD

**Issue by ExeterDad** [minetest/minetest#5364] opened 2017-03-10 14:52 UTC
I apologize for being unable to come up with a better description. I think it would be useful if modders could access the view modes normally accessed with the F7 key presses. The ability to switch camera view to see players own model without player actually having to press F7 would be very useful in cases such as skin switching mods.
player:set_eye_offset({x=0,y=0,z=0},{x=0,y=-0,z=0}) Is useful to adjust camera placement if F7 has been pressed, but I would like to see a way to toggle view modes via lua to take advantage of this.

**Comment by stujones11** [comment] 2017-03-10 17:49
Would be nice for sure though I am not sure if the server has any idea of the clients view. Maybe another candidate for CSM?

**Comment by red-001** [comment] 2017-03-21 23:51
see  #5394

**Comment by rubenwardy** [comment] 2018-04-09 20:44
duplicate of #3070

**Closed by rubenwardy** 2018-04-09 20:44 UTC
Labels: @ Script API, Feature request
