### ISSUE TITLE
Inventory local and remote acting differently?

### ISSUE THREAD

**Issue by JPRuehmann** [minetest/minetest#1322] opened 2014-05-21 12:16 UTC
I am not shure if that is a Problem of Minetest itself or The used Inventory (unified_inventory) so I post it in Both.
If I am playing on my Server (Remote) only the first nine Fields of the Inventory are working.
If I am playing Local (Singleplayer or Server) all fields are working.
It makes no difference if I enable creative or not on the server I have the creative Priv.
I am using MT 0.4.9 232 in Kubuntu 14.04 LTS

**Comment by sapier** [comment] 2015-12-29 20:02
Can you provide Information if this happens in plain inventory too?
If not I'd assume this bug to be fixed and close it due to old age in about a week.

**Comment by RobertZenz** [comment] 2016-01-17 13:26
minetest-technic/unified_inventory#10 is the issue on the unified inventory side, which was caused by a corrupted file on the server end, so this can be closed.

**Comment by nerzhul** [comment] 2017-05-20 14:21
Closing this, inventory object is exactly same on both parts.

**Closed by nerzhul** 2017-05-20 14:21 UTC
Labels: Obscure, Unconfirmed bug
