### ISSUE TITLE
A clear mission statement for Minetest is missing.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3476] opened 2015-12-21 19:19 UTC
Currently the only description of what Minetest is about, is the about text of this repository which reads:

> Minetest, an open source infinite-world block sandbox game with survival and crafting.

The README is even more vague and unprecise. There is a clear mission statement for Minetest missing.

The main reason such a statement is needed is most visible when it comes to features, especially pull requests by third parties. There seems to be quite some gap between what mod developers and what core developers think what the engine should be, and what features the engine should provide.

This gap does lead to a lot of confusion and frustration, especially when it comes to what features should be included in the engine and which not. Worst of all is that this does happen in pull requests, which means that somebody has spent considerable amount of time to improve the engine and then has to defend this improvement not based on technical feasibility or merits, but why that improvement would be a good idea in itself. Though this can always happen, and in an ideal world an issue would be opened first to discuss the exact merits of the idea, it does seem to happen unnecessarily often.

A clear and precise mission statement would provide a guideline on what features are welcome, which need to be discussed and which might not be accepted. Additionally there are no guidelines on how new contributors should start out and what they need to watch out.

What I'm requesting is:

A clear and precise mission statement, which does explain the goals of the Minetest project paired with examples what is to be achieved. Is the engine a generic voxel engine? Is it an engine for voxel based adventures or sandbox games? Is it for Minecraft clones? Is it only here to power Minetest Game? These questions must be unanimously answered, also the descriptions in the repository and in the wiki should be updated to match that statement.

Additionally a simple guide should outline what new contributors should look out for and what exact process they have to expect, what happens with their pull requests and what to do if questions arise. A rule to first open an issue for discussing additions instead if simply sending a pull request would remove quite a lot of friction and frustration, because there is hardly anything more frustrating than to have a pull request sitting around for a month, only to have to defend it again why you think this is needed in the engine.

There is already a similar document available in the dev wiki, but it definitely needs to be brought up to speed and put well visibly into the README, even if it just a link to it, that it is clear that contributors need to look at this first.

**Comment by est31** [comment] 2015-12-22 00:33
I think @celeron55 has kept it vague intentionally, and nobody really knows what minetest is all about.

But generally, I am often conservative when I see a feature proposed that adds lots of complexity, introducing even more opportunities for bugs, and cementing architecture, while most of minetest's more basic problems still remain unsolved. One of those problems would be the buggy entity support, performance related issues, missing client side scripting, the fact that we init so much of the nodedef in advance, our leaky texture cache, and more.

**Comment by est31** [comment] 2015-12-22 00:55
The rust language has a very formal process which separates implementation and proposal of features into two steps: first write an rfc, then implement it. Question is: do we want this paperwork?

**Comment by celeron55** [comment] 2015-12-27 10:19
First, consider that a mission statement does not and would not mean that "to achieve these goals we will write and accept bad design and crappy code". Having considered that, then...

I wish we would have or I could come up with a clear and precise mission statement. Due to the nature and history of Minetest 0.4, it's almost imposible.

Minetest 0.4 is a bastard evolution of 0.3 that adds a scriptable content system to some arbitrary parts due to user demand and developer interest that happened to match at one point in time. Because we neither want to make this a hardcoded game nor an universal game engine, the parts and extent are arbitrary. It is not, and has never been, guided by the needs of anyone or anything in particular, except MAYBE server owners, altough that might be stretching it.

If you're now asking how it can even manage to exist or be used by anyone, I don't have a good answer. I guess because everything else is even worse for certain needs and/or preferences that users happen to have.

One question regarding to a mission statement for the engine that really drives reluctance to miscellaneous new features is simplicity. Minetest is meant to be simple. Simplicity comes in many forms: simplicity of the engine internals, simplicity of the modding interface, and simplicity of mods itself. How much simplicity is to be sacrificed for flexibility? Is some kind of simplicity more important than the others? Can simplicity be thrown away in the name of progress?

I don't know; nobody knows. But due to this, you have to be able to explain why lessening simplicity is worth it for any feature you want to add.

One could make the argument that the modding interface should be such that anything that is not included in the engine should be addable by a mod, but that would already require the interface to be an order of magnitude larger. It's not doable or maintainable by a reasonable amount of effort in the way Minetest is designed, and it would be way more efficient to do that from scratch. My attempt in this is called Buildat, and I had to stop developing it because after two months of continuous development it was still in a practically unusable state.

Ehm... well yeah,  there's something to think about I guess.

**Comment by paramat** [comment] 2015-12-28 19:47
"What is Minetest, and what does it do to be that?"
http://c55.me/blog/?p=1491

**Comment by RobertZenz** [comment] 2016-01-06 21:08
> First, consider that a mission statement does not and would not mean that "to achieve these goals we will write and accept bad design and crappy code".

I'm aware of that, not sure what you're hinting at.

 > I wish we would have or I could come up with a clear and precise mission statement. Due to the nature and history of Minetest 0.4, it's almost imposible.

That needs some explanation to me. I fail to see how the history and current state make a future plan impossible.

 > Because we neither want to make this a hardcoded game nor an universal game engine, the parts and extent are arbitrary. It is not, and has never been, guided by the needs of anyone or anything in particular, except maybe server owners, altough that might be stretching it.

Exactly what I meant. Additionally, this seems to contribute to a lot of fragmentation in the Minetest space, fragmentation that seems unnecessary for the most part. And from that I see the project might fragment further because of this.

 > If you're now asking how it can even manage to exist or be used by anyone, I don't have a good answer.

Nah, the question is not if it can exist, because it can, the question is if the state is desirable to be uphold.

 > One question regarding to a mission statement for the engine that really drives reluctance to miscellaneous new features is simplicity. ... How much simplicity is to be sacrificed for flexibility? Is some kind of simplicity more important than the others? Can simplicity be thrown away in the name of progress?

Simplicity does not exclude flexibility, and flexibility does not exclude simplicity. But I think I understand what you mean, and these questions can be easily answered if the above questions have been answered and a direction for the project is set.

---

Well, maybe I should go back to the beginning and explain what I am seeing when looking at Minetest.

Minetest is *the only choice* I have when it comes to implement my ideas. I've been digging through engines (including experimenting writing my own, or modding Minecraft) for years while looking for a suitable one. Minetest is the only one that stood out from the mass of engines, games and oddball projects. Why? Because it's simplicity. You get the client, you start writing some Lua, bam, done. That is exactly what I was looking for, exactly what I need to implement my ideas. I've been looking at other projects since then, and none come close to this. So I owe you and the others a thanks for that, for throwing something so awesome together which allows me to simply do my thing.

Now, where does that put me? I'm a coder, I haven't even played half an hour Minetest Game or Pixture or Adventure Test or Hades or anything like that. I found Minetest and started writing code. So I'm looking at Minetest from this perspective, from the Lua API, how it bring things to life on the screen, my things. But I also see a lot of lacking functionality and missed opportunities on this end, things I can fix or workaround for the most part.

So I've started reading tickets, creating them, reading pull requests, creating them. And I find it confusing when reading through all this, through the conversations on IRC and when looking at the forks. There does not seem to be a direction for the project, which is not really an issue, but which makes it very hard, at least for me, to contribute something. Because I can never know if I'm inside of the not defined bounds or not, which makes me question if I should contribute something at all. Now, it wouldn't really be an issue if it wouldn't be for the long waits, non definite answers and the need to defend why this is a good idea *at all*. Maybe I'm just used to very tight and direct feedback loops in projects, so that might just bother me. The other side of the coin is, that if Minetest does not have the features I want, there are two possibilities, fork it or rage quit. Note that I've excluded "switch to something else", because there are no alternatives from where I sit. I do not want to contribute to even more fragmentation in this area, it is already bad enough, but I'd also rather not quit this, as it gives me a nice project to work on and for the first time in years I'm steadily working on a project.

I believe that Minetest has the potential to become a generic game engine (for Voxel Games, I mean) without too much effort and without losing much of the simplicity. It already is for the most part.

**Comment by celeron55** [comment] 2016-01-10 20:56
Thanks for the more detailed base perspective from your part; it might be more useful for my thinking than you think.

I understand that these matters can be absolutely infuriating to contributors like you, but I am slightly more powerless than I would like in sorting these out. I think my suggestion to everyone is to take it easy but complain hard; you might end up forcing some long-needed changes.

What even do other members of the core team think about a mission statement? Has anyone even considered whether it's as impossible as we tend to think?

**Comment by celeron55** [comment] 2016-01-10 22:33
Like... ehm... here's an example attempt at a mission statement:

"Minetest exists to allow any creative person to make and maintain a multiplayer first-person voxel game for anyone to play. Minetest embraces low fidelity for ease of content creation. In API design and features, Minetest prefers to be simple but self-contained. Minetest mostly defaults to Minecraft-alpha-like behavior as a familiar base to start from but it does not really matter."

That's just off the top of my head. Any input from other core devs? I mean, this surely cannot be perfect...

**Comment by est31** [comment] 2016-01-11 13:26
Well, many parts of minetest are different from minecraft, and if somebody complains "but this is different in minecraft" the reply is "minetest isn't a minecraft clone", at least from what I read in the forums. The last sentence sounds to me like you would want to have more minecraft alpha like behaviour.

But yeah, I like the part that we allow and encourage people to create games.

**Comment by RobertZenz** [comment] 2016-01-14 22:07
I'm a little bit tired, so I'm just typing what comes to mind. A word of warning, I do have my own idea about Minetest, as I said before, I believe that it can be, and for the most part already is, a simple and versatile engine. With that in mind:

"Minetest is an engine for creating and powering first-person voxel games. It's goal is to provide an easy to learn and use, but still powerful system which allows to easily and rapidly create, extend and modify voxel games."

I actually think that such a short statement is a good start. Some extensions to that can be made with something like:

"The API is designed to be simple and easy to learn but still provide all the necessary functionality to create interesting, fun and innovative voxel games."

I'd actually stay clear of two statements in those...arrrr, statements:

 1. That it is aiming to be similar to or is inspired from Minecraft. That might have been the past, but Minetest has far outgrown Minecraft, especially when it comes to mod support and ease of use.
 2. That Minetest is in some way a game of itself. Separating the engine from the game will not only clear any possible confusions between Minetest and Minetest Game, it will also remove any discussions on whether a feature or not is warranted in a voxel game.

Now this is only a rough thingy, as I said I'm tired, but what I'd suggest is something along the lines of "We create an engine, we empower you to create the voxel game *you* want". As I said, I believe Minetest is already very, very close to that statement.

**Comment by 0-afflatus** [comment] 2016-02-17 04:40
@RobertZenz I think the way to go is to draft such a mission statement and put it up for discussion. Personally I'd love you to draft it, because I am attracted to Minetest for exactly the same reasons. I would favour moving more towards being a general (but focussed) voxel game engine than MC clone, but I like what it is and the mission statement should reflect what it is as well as what it could be.

I think simplicity and flexibility go hand in hand. As a game designer I do not want to have to remove or work around unwanted features and in many cases, may not have the skills. I have managed to create the sort of game I want without even learning Lua properly. Learning how to use Lua and git properly are now priorities for me as many 3rd party mods are not that well coded. I find Minetest to be a rewarding programming environment because you get virtually tangible results. It's just (ha!) a question of finding a form of words that most of us agree on.

**Comment by RobertZenz** [comment] 2016-02-23 21:09
I've started to put my thoughts into documents, obviously this is at a very early stage and I'm not quite happy with most drafts, so I've only committed the first draft of the mission statement for now.

https://github.com/minetest/minetest/issues/3476

Feedback is obviously welcome.

**Comment by 0-afflatus** [comment] 2016-02-24 07:20
Reframe #2 into positive values, something like:
The engine itself should be flexible; making broad assumptions about possible usecases and allowing users the greatest possible control.

**Comment by est31** [comment] 2016-03-31 02:08
The contribution guide got merged, now only the mission statement is missing.

**Comment by paramat** [comment] 2017-07-08 22:37
Author seems to have left MT.
Now we just need a mission :]

**Comment by Wuzzy2** [comment] 2017-09-05 17:00
Well, I agree that having a mission statement would be good.

IMO a mission statement could be very, very simple.
Start with by writing down the obvious no-go areas; features you would never accept. This will already save a lot of tears.

Then answer some simple questions. Like these:

* How do you describe Minetest in one sentence to a total beginner?
* What is the big picture? Writing a generic engine for all types of games with voxels? Or does it only revolve around MTG? Or is it specific to a genre? Etc.
* What are the must-have features for Minetest 1.0.0?
* Who is your audience?
* Is MT for high-end graphics, or low-end?
* How important is performance?
* How much do we care about input from players/modders/server operators?
* How aggressively are we allowed to break backwards-compability at the moment? (Note we're still in alpha stage, mind you)
* How do you decide whether to implement a feature in the engine, in builtin or in a mod? There should be a clear boundary because this has been the area of many battles in the past
* What is the scope of client-sided modding? Name examples and counter-examples
* What is the scope of normal mods? What function do mods fulfil, and more importantly, what do they *not* fulfil?
* Which kind of features are desired in the Lua API?
* What security considerations do we have?
* How do we deal with cheaters?
* What are the conditions to accept a new core mapgen?
* What are the current best development practices?
* Are we allowed to add 3rd party libraries?
* …

And so on. I hope you get the idea.

**Comment by nerzhul** [comment] 2017-09-05 20:09
for me minetest should be more than just an engine, we don't have any goal to be a generic voxel engine, engine is not designed for this, it's minecraft like. It's better to have a more intelligent core engine, without game features but game high level APIs

* MT should have both high end and low end graphics, end users generally like having a terasology like game design, it sells the product.
* Performance should be important, but it's difficult to enhance it and find bottlenecks, we should find the usecases of modders and offer very high level APIs.
* backward compat should be ensured, i think a 2 years cycle is sufficient to justify a major if it's needed (here C++11 + fix very old protocol bugs, and cleanup some very old code)
* CSM miss some of the real interesting API, mod channels and HUD are part of a nice design, but modders should code and find a good usage, for example share ore data between them ?
* Security is considered, SRP auth is an example. Our protocol is not very secure, but it can be enhanced later.
* New core mapgen = good realistic mapgen for me, without any anoying calculation bugs
* For 3rd party libraries it should be justified. libpq, sqlite, hiredis are justified, it's our backends, libmysqlclient can be considered if somebody wants to use it. For me an important library to add to MT in this cycle (if i get time) is Asio, which is a production industrial grade library to manage asynchronous IO, like network, it permits to cleanup our network code and handle with nice C++11 features our network (not the MT protocol but the transport layer)

**Comment by paramat** [comment] 2017-09-05 21:39
The guide for contributing is of course a good idea.

> A clear and precise mission statement would provide a guideline on what features are welcome, which need to be discussed and which might not be accepted.

I think this is impossible to be clear and precise on, because what will be acceptable is always changing, and is of course specific to each individual situation, so specifying what is acceptable for every possibility in Minetest is impossible to do.

I think the thread author was over-concerned with 'mission' and 'direction' as many are, and was writing at a time of (i think excessive) frustration and negativity which eventually led to him leaving MT.

The already-existing roadmaps describe the philosophy of Minetest well, and the current direction and mission can be known by following dev discussion, PRs and issues. It's not surprising that devs do not feel like writng regular essays on the current direction and mission, to do so would be difficult, time consuming and the result would be out of date within weeks.

**Comment by paramat** [comment] 2017-09-05 21:53
The thread author writes:

> So I've started reading tickets, creating them, reading pull requests, creating them. And I find it confusing when reading through all this, through the conversations on IRC and when looking at the forks. There does not seem to be a direction for the project

There is.

> but which makes it very hard, at least for me, to contribute something. Because I can never know if I'm inside of the not defined bounds or not, which makes me question if I should contribute something at all.

This is unrealistic, what is acceptable will be specific to that precise situation, so cannot be documented somewhere.

**Comment by rubenwardy** [comment] 2017-12-17 21:38
We have developer roadmaps here which state each developer's view for the project: https://forum.minetest.net/viewforum.php?f=7

It would still be good to unify those and create a unified road map and mission statement

**Comment by paramat** [comment] 2017-12-18 11:36
If added it should include c55's roadmaps, which still describe the philosophy of MT better than anything.

> There seems to be quite some gap between what mod developers and what core developers think what the engine should be, and what features the engine should provide.

This makes zero sense if read carefully.
"A gap between what everyone thinks the engine should do, and what the engine should do".

> Worst of all is that this does happen in pull requests, which means that somebody has spent considerable amount of time to improve the engine and then has to defend this improvement not based on technical feasibility or merits, but why that improvement would be a good idea in itself.

Again no sense, what is wrong with a feature having to be a "good idea"? Of course it has to be a good idea, if it isn't it doesn't matter how good it is technically.

However, his actual requests are more reasonable.

I think c55's responses here are perfect and show a more relaxed and less rigid approach.

>  Is the engine a generic voxel engine? Is it an engine for voxel based adventures or sandbox games? Is it for Minecraft clones? Is it only here to power Minetest Game?

Simple, it's just one of these: an engine for voxel based adventures or sandbox games.

**Comment by Fixer-007** [comment] 2017-12-18 14:16
The problem is celeron does not direct nor participate much in the project, his notes are useful, but should not be a dogma.

**Comment by paramat** [comment] 2017-12-18 16:41
Yes it doesn't have to be dogmatic, however ...
Whether he's currently active is not particularly relevant, it is his game, he's the project leader, and we do tend to roughly follow his roadmaps (and should). They're useful because we don't really have anything else. His roadmaps are obviously the best expression of the philosophy of MT, so following them keeps MT focussed, consistent and true to it's own character.

What attracts players and devs to MT is how it is, it's philosophy and character that is still very much inline with celeron55's roadmaps, so staying fairly true to that is important.

**Comment by Wuzzy2** [comment] 2017-12-18 20:17
I strongly believe MT should not limit itself to sandbox-only. In practice, such a limitation would be rather arbitrary at this point of development anyway. Although I have no problems if MT has a certain focus and supports typical sandbox features like Creative Mode. But IMO it's always good if you can opt out.
Basically MT should not dictate the genre. This is up to subgames.

In fact, MT is already powerful enough that it allows to create great non-sandbox games.
Some examples:

* Hungry Games
* Capture The Flag
* Labyrinthus
* Inside The Box

> Any tool should be useful in the expected way, but a truly great tool lends itself to uses you never expected.

**Comment by rubenwardy** [comment] 2017-12-18 20:42
For me, Minetest is a domain-specific game engine which aims to allow you to create any kind of voxel game. Whilst this is  not true currently - there are limitations in the API - it's something I'd like to aim towards.

**Comment by paramat** [comment] 2018-06-30 18:20
> a simple guide should outline what new contributors should look out for and what exact process they have to expect, what happens with their pull requests and what to do if questions arise. A rule to first open an issue for discussing additions instead if simply sending a pull request would remove quite a lot of friction and frustration,

https://github.com/minetest/minetest/blob/master/CONTRIBUTING.md does this and now links to both of celeron55's roadmaps. So this issue is partially resolved.

Maybe these roadmaps could be copied into a document in the repo? I know this is not everything that RobertZenz is asking for but it's a start that can be added to later, and at least gives contributors something. Then these are stored in the repo instead of external websites.

**Comment by Wuzzy2** [comment] 2023-02-21 14:39
This is an old issue now. And Minetest now has an official roadmap since a few years. Does this count? If yes, I think it's safe to close this issue.

**Closed** 2023-07-31 13:39 UTC
Labels: @ Documentation, Request / Suggestion, Supported by core dev
