### ISSUE TITLE
Doesn't remember maximized window settings

### ISSUE THREAD

**Issue by xeruf** [minetest/minetest#13101] opened 2022-12-29 23:33 UTC
##### Minetest version

```
5.6.1
```

##### OS / Hardware

Operating system: Windows & Linux

##### Summary
When I start the game on WIndows, it opens windowed, even when I opened it fullscreen beforehand and it was set to remember window size (the default).

~~Furthermore, when I am about to host a server, the username input field reverts whenever I change anything (announce, select a world, etc.) which can be quite frustrating.~~ EDIT by Zughy: see first comment

Related to https://github.com/minetest/minetest/issues/6733

**Comment by Zughy** [comment] 2022-12-30 01:04
Hello, I can confirm both bugs, but I need you to open a second issue for the latter: having more problems raised in a single issue doesn't help navigation

**Comment by sfan5** [comment] 2022-12-30 09:23
Oh actually this is a duplicate of #13101

**Closed by sfan5** 2022-12-30 09:23 UTC
Labels: Bug, @ Startup / Config / Util
