### ISSUE TITLE
`get_craft_result` seems to be incredibly inefficient in certain circumstances

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest#13231] opened 2023-02-19 17:03 UTC
##### Minetest version
```
5.6.1, 5.7.0-dev-4cd6b773bb5de2594c682ae7e5793c80ad6a22e6
```

##### OS / Hardware
Operating system: linux
CPU: intel

##### Summary
some players on the your-land server noticed that certain crafting recipes caused a huge lag spike. i've traced this back to the fact that with the set of items and craft recipes, calling `minetest.get_craft_result` can take a significant fraction of a second (0.4s on my personal machine - 40 seconds for a full stack). the common feature of these recipes is that they involve a lot of `group` elements in the recipe, e.g.

```lua
minetest.register_craft({
    output="bonemeal:mulch",
    recipe={
        {"group:seed","group:seed","group:seed"},
        {"group:seed","group:seed","group:seed"},
        {"group:seed","group:seed","group:seed"}
    }
})
```

in the above example, there are 46 items in the `seed` group, but the same slowdown is observed when there are only 1 or 2 items in the group:

```lua
minetest.register_craft({
    output="farming:sunflower_oil",
    recipe={
        {"group:food_sunflower_seeds","group:food_sunflower_seeds","group:food_sunflower_seeds"},
        {"group:food_sunflower_seeds","group:food_sunflower_seeds","group:food_sunflower_seeds"},
        {"group:food_sunflower_seeds","vessels:glass_bottle","group:food_sunflower_seeds"}
    }
})
```

##### Steps to reproduce
i've dumped all the items, groups, and craft recipes from the server into the following mod:

https://github.com/fluxionary/minetest-fake_yl

this mod has no dependencies and works w/ either devtest or minetest_game. note that the item definitions only have a description and groups, to keep things smaller. notably, there are no textures.

there are several ways to test:
* use the supplied `/simulate_crafting` command to see how long it takes to craft 9 wheat seeds into 1 mulch
* spawn in items in your favorite inventory manager (e.g. sfinv or unified_inventory), and check how long it takes to craft large quantities quickly (middle-click is useful).
* use craft_all button from [unified_inventory_plus](https://github.com/bousket/unified_inventory_plus)

**Comment by Desour** [comment] 2023-02-19 18:01
Duplicate of #11224.

FYI, I'm actually currently working on a patch to fix the performance. Weirdly incidental...

**Comment by SmallJoker** [comment] 2023-02-19 19:23
Duplicate.

**Closed by SmallJoker** 2023-02-19 19:23 UTC
Labels: Unconfirmed bug

**Comment by fluxionary** [comment] 2023-02-19 20:04
> Duplicate of #11224.
> 
> FYI, I'm actually currently working on a patch to fix the performance. Weirdly incidental...

i haven't dug into the code too deeply, but is it actually the same issue? the problematic crafts for us are not necessarily shapeless, and there's no mention of what exactly is lagging in that issue. perhaps the description on the other issue could be updated?
