### ISSUE TITLE
Killing player in on_respawnplayer not working

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9826] opened 2020-05-06 16:19 UTC
##### Minetest version

```
5.2.0
```

##### Summary

Killing the player in on_respawnplayer is not always working. It often leads to a dead player (0 HP) walking around. I believe this also more or less randomly (and rarely) happens when killing a player using other means. [Video illustrating the bug.](https://www.youtube.com/watch?v=FhiYLOZx32U)

##### Steps to reproduce

```lua
minetest.register_on_mods_loaded(function()
    for i = 1, #minetest.registered_on_respawnplayers do
        minetest.registered_on_respawnplayers[i] = nil
    end
    minetest.register_on_respawnplayer(function(player)
        player:set_hp(0)
        return true
    end)
end)
```

And spam respawn. You will eventually end up alive with 0 hp.

**Comment by SmallJoker** [comment] 2020-09-27 16:52
Duplicate of #2945

**Closed by SmallJoker** 2020-09-27 16:52 UTC
Labels: Unconfirmed bug
