### ISSUE TITLE
Allow using mesh models for wielded tools and items

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4190] opened 2016-06-05 10:51 UTC
Why do we have a 2D image for the characters hands? Why not 3D here's an example of what it should look like https://www.google.be/search?q=minecraft+arm&client=tablet-android-google&biw=960&bih=600&prmd=ivn&source=lnms&tbm=isch&sa=X&ved=0ahUKEwizm9LA2JDNAhXMJsAKHc5zBF4Q_AUIBigB#imgrc=cCbe9pFkLHMSxM%3A a actual 3D renderd arm would look a lot better.
(it would be the same arm like in Minecraft)

**Comment by paramat** [comment] 2016-06-05 11:30
I guess because the hand uses the same system as wield items, which are extruded 2D textures.
This could possibly be combined with a way of customising the hand, so that a UV map can be supplied that matches the current player skin, related to #2827 #1368

**Comment by benrob0329** [comment] 2016-06-05 14:49
IMO tools and items should be able to define wielding models as well.

Maybe we could have the mod define a custom wield model with hands and animation?

**Comment by paramat** [comment] 2016-06-05 15:06
3D tools would then be too complex to create, they're extruded textures to make them easy to create.
The hand is different, a custom UV texture for it is easy to make.

**Comment by tobyplowy** [comment] 2016-06-05 15:23
@paramat now that you say that I have to think about something is it actually possible to make a custom 3D model item? Which obj files or something?

**Comment by 0-afflatus** [comment] 2016-06-05 16:56
I don't really see how this would improve the game, sorry.

**Comment by tobyplowy** [comment] 2016-06-05 17:19
@0-afflatus better visuals

**Comment by paramat** [comment] 2016-06-05 17:40
The improvement would be pixel detail on the arm side, instead of extruded edge colours.

**Comment by benrob0329** [comment] 2016-06-05 18:37
Mods like gravitygun have to very hackishly make 3D tools by actually using a node instead of a tool.

**Comment by numberZero** [comment] 2016-06-05 18:43
> aesthetically suitable for Minetest
For `minetest_game`, but not necessarily for others. Don’t forget that Minetest itself is an engine, so it should support many generic features.
As for me, both 2D and 3D wield items should be supported (I think that’s not a great problem to implement that), as extruded 2D is fine for many games (including MT_game), but some require true 3D.

**Comment by paramat** [comment] 2016-06-05 18:47
Oops i wasn't thinking about options, yeah 3D models as an option could be good.

**Comment by raymoo** [comment] 2016-06-13 08:19
If 3D models as an option is added, a custom dig(/use?) animation could be an option too.

**Comment by hunterdelyx1** [comment] 2016-06-17 20:17
Maybe wielditems should have drawtypes(visuals), just like enities(enities already have option to be draw as wielditem by the way, lol).

**Comment by juhdanad** [comment] 2016-08-03 18:31
I may be wrong but I think the player's hand is 3D.

**Comment by numberZero** [comment] 2016-08-03 21:33
@juhdanad not sure about the hand itself, but the wield items are not truly 3D now, they are extruded 2D images. Sometimes that looks poorly, especially with antialiased textures, or if you have something substantially non-flat (like a cart) in your hand

**Comment by paramat** [comment] 2016-08-03 22:02
The hand is an extruded 2D image.

**Comment by HybridDog** [comment] 2016-11-26 07:21
>The hand is an extruded 2D image.

As far as l know, extruded 2D images cause lots of lag due to all the unneeded polygons. #3069

**Comment by tobyplowy** [comment] 2016-11-26 11:19
@HybridDog If it rilly Uses polygons To render the arm i think the 3d arm is a better Option than The item instead of 50 (I'm not sure iv not counted them yet But its a Lot) polygons we only have 12

**Comment by HybridDog** [comment] 2016-11-27 07:54
A wield mesh using a 64x64 texture uses 2+(64+1)*2 = 132 polygons l think, only two of them with backface culling.

**Comment by Maxqia** [comment] 2017-01-22 02:59
There was a mod for this that took the model from the player's skin : https://forum.minetest.net/viewtopic.php?id=7286. But it only worked for one player because it registered as a item.

**Comment by paramat** [comment] 2017-09-20 17:40
Changed title to be a more general request.

**Comment by tobyplowy** [comment] 2017-09-20 17:41
@paramat ok

**Comment by tobyplowy** [comment] 2017-11-01 19:31
@paramat so will mesh model support be added for items in 0.5?

**Comment by rubenwardy** [comment] 2018-04-09 20:40
duplicate of #3551

**Closed by rubenwardy** 2018-04-09 20:40 UTC
Labels: @ Client / Audiovisuals, Feature request
