### ISSUE TITLE
Add links which can link to a Minetest server

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#11237] opened 2021-04-29 10:47 UTC
## Problem
I want to provide a link to go to my Minetest server, but it is currently impossible

## Solutions
Add a link that can go to a Minetest server. Users will enter username and password in-game after following the link.

Link example: `minetest://toyshost2.ddns.net:30010` (Which can link to C&C City Server)

**Comment by sfan5** [comment] 2021-04-29 11:14
duplicate of #7400

**Comment by rubenwardy** [comment] 2021-04-29 11:14
Duplicate of https://github.com/minetest/minetest/issues/7400

**Comment by rubenwardy** [comment] 2021-04-29 11:14
hahaha

**Closed by sfan5** 2021-04-29 11:14 UTC
Labels: Feature request
