### ISSUE TITLE
Particles don't collide with liquids

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6679] opened 2017-11-25 18:57 UTC
I'm working on a weather mod and I noticed, that particles pass through water. As a result you can see particles under water. Just disable the particle spawner if the player is under water may reduce the effect, but you can still see particles until they are all disappeared. Especially snow flakes can live a while.

I think, collision check with liquid nodes should be added

**Comment by paramat** [comment] 2017-11-25 20:01
Yes it's because liquid is not walkable. This will have to be configurable if done.

**Comment by gituser2194** [comment] 2017-11-26 03:26
Honestly, this sounds like the intended behavior. I do think that adding an exception for raindrops and snowflakes would be desirable, however. This would definitely need to be configurable per particle.

**Comment by HybridDog** [comment] 2017-11-26 16:02
Particles in minetest are still very laggy, I don't like snow and rain if it causes low fps.

**Comment by paramat** [comment] 2017-11-26 21:56
This is still valid as someone may be using few particles, and not necessarily rain or snow. No need to delay it.

**Comment by paramat** [comment] 2017-11-28 06:57
Duplicate of #4305

**Closed by paramat** 2017-11-28 06:57 UTC
Labels: Duplicate, Feature request
