### ISSUE TITLE
Auto install missing dependecies (configurable)

### ISSUE THREAD

**Issue by BruceMustache** [minetest/minetest#10284] opened 2020-08-11 02:39 UTC
## Problem

Like linux package managers install programs with all their dependencies to make it more easy to install
I think minetest should do the same with mods

## Solutions

Download dependencies along with mods while dependencies are in different location
ie: a modpack called dependencies
After removing a mod minetest loop all their dependecies and remove it if are in dependencies modpack
I think this improve end user usability

# Alternative

This can be configurable with setting like enable_auto_install_dependencies idk

**Comment by luk3yx** [comment] 2020-08-11 09:59
Possible duplicate of https://github.com/minetest/minetest/issues/8891.

**Closed** 2020-08-11 13:38 UTC
Labels: Feature request
