### ISSUE TITLE
Numpad Enter key does not work in Settings tab search (or everywhere?)

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#14170] opened 2023-12-27 10:56 UTC
Minetest 524721ee275875d4c76808bb0c9cb0ed3ccb3ac1

**Comment by SmallJoker** [comment] 2023-12-27 14:13
Return? The Enter key? Works for me on X11 non-SDL Irrlicht build.

The assumed input box in question:
![search box](https://github.com/minetest/minetest/assets/1497498/9456606e-2c8d-485e-9f77-32e77c3d3407)

**Comment by sfan5** [comment] 2023-12-27 14:44
SDL build here, and I was pressing the Numpad enter.

**Comment by Desour** [comment] 2023-12-27 15:35
Can reproduce with SDL build.
Related or duplicate of: https://github.com/minetest/irrlicht/issues/207

**Comment by debagos** [comment] 2024-01-26 17:31
For me it the Enter (not Return) key doesn't work in any input fields, not even F10 chat.
Latest MT and IrrMT SDL build.

**Comment by waxtatect** [comment] 2024-02-13 22:14
this seems to be easy fix?!
just add, "KeyMap.push_back(SKeyMap(SDLK_KP_ENTER, KEY_RETURN));" somewhere in there
https://github.com/minetest/irrlicht/blob/0dab737d602a77e98acb159ddd6bb2ac89f36cff/source/Irrlicht/CIrrDeviceSDL.cpp#L1172

also on my Windows 10 laptop, alt+f4 works fine without this, https://github.com/minetest/irrlicht/blob/0dab737d602a77e98acb159ddd6bb2ac89f36cff/source/Irrlicht/CIrrDeviceSDL.cpp#L730

**Closed** 2024-02-15 09:48 UTC
Labels: Bug, Upstream issue
