### ISSUE TITLE
Exiting a world in 5.3.0 crashes the game

### ISSUE THREAD

**Issue by v-rob** [minetest/minetest#10138] opened 2020-07-02 00:34 UTC
##### Minetest version
```
5.3.0 release candidate 2 (e99415e0c5ae4a89907424d0f5f9f48ab94efbfa)
```

##### OS / Hardware
Operating system: Windows 10

##### Summary
In 5.3.0, exiting a world in any way crashes the game.  Clicking "Exit to Menu" will show the "Shutting Down" screen, but then the game will crash.  "Exit to OS" and Alt-F4 will crash Minetest immediately.  Neither will save settings like key configurations, indicating that it crashes any way the world is exited.  Lua crashes will also crash Minetest immediately, and some will not display any error messages in `debug.txt`.

**Comment by rubenwardy** [comment] 2020-07-02 00:40
Duplicate of #10137

**Closed by rubenwardy** 2020-07-02 00:40 UTC
Labels: Unconfirmed bug

**Comment by v-rob** [comment] 2020-07-02 00:58
Gee, mine was only four minutes later.
