### ISSUE TITLE
GUI can scan for local servers

### ISSUE THREAD

**Issue by BruceMustache** [minetest/minetest#10213] opened 2020-07-21 10:37 UTC
## Problem

Currently to play minetest in local server I have to say to my friends put my IP on the address field. I think this is not user friendly
ie: I think no everyone knows to join a local server in minetest. If minetest GUI scan for that everyone will

## Solutions

GUI will also scan local servers and join them in the "join game" tab. They comes first in the list and I suggest to use different symbols for user see it's really a local server: yellow text, instead of wireless icon use Ethernet icon

**Comment by appgurueu** [comment] 2020-07-21 11:20
Duplicate of #10208

**Closed** 2020-07-21 11:55 UTC
Labels: Feature request

**Comment by BruceMustache** [comment] 2020-07-21 14:12
Oh sorry for duplicate
