### ISSUE TITLE
Player Damage Reason.

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#5971] opened 2017-06-12 16:12 UTC
Wouldn't it be nice to have a reason given each time a player is damaged, e.g.
```
player:set_hp(damage, reason)

player:punch(puncher, time_from_last_punch, tool_capabilities, direction, reason)

minetest.register_on_player_hpchange(function(player, hp_change, reason)
```
... where 'reason' is a simple text string containing something like "lava", "fire", "mob_sandmonster", "ethereal:crystal_spike" etc.

This would come in very handy for award or death messages or even stats on a players game :)

**Comment by nerzhul** [comment] 2017-06-12 17:57
better than this, punch meta can be more generic and transport more complex events

**Comment by Wuzzy2** [comment] 2017-06-12 23:17
I approve of the idea, but not neccessary with the proposed implementation.
Currently, it is very hard to impossible to learn how a player or entity was damaged or killed.
We not only need a “damage reason”, but also very often a damage source.

A freeform reason doesn't seem to be the right way unless we standardize it immediately. If not, modders will use 1000 incompatible strings and the “reason” is worth nothing.

At the very least, Minetest should provide some builtin damage types, especially those damage types caused by the engine. In particular:

* Drowning
* Fall damage
* Node damage (i.e. `damage_per_second` from the node definition)
* Punch from a player
* Punch from an entity which is not a player
* …

But there's also `set_hp` which can be totally arbitrary, so here a freeform text *might* make sense.

I think this is quite important because there are a gazillion of use cases:

* Mob which drops only a valuable item when killed with an Magic Arrow of Rainbowness, but not with the Boring Dagger of Boringness
* More detailed death messages or a death log
* Damage-related achievements/awards/points/rewards
* Much more fine-grained “reactions” when damaging a player/entity in a particualar way

**Comment by vlapsley** [comment] 2017-06-13 00:47
Nethack style death messages and leaderboard:

_Wuzzy was killed by a rat at 63,-2,128. Wuzzy had only accumulated 4 lumps of coal and 1 lump of bronze when he was horribly slain._

**Comment by raymoo** [comment] 2017-06-13 17:02
Damage sources / reasons should have some structure, even if they are freeform. Something like `pointed_thing` where there is a `type` field and other fields may be present based on that.

**Comment by tenplus1** [comment] 2017-06-20 09:38
We need something like this so we can tailor player damage checks for specific items like armor or artifacts etc.

**Comment by paramat** [comment] 2017-07-08 21:16
Related #1342

**Comment by rubenwardy** [comment] 2017-09-08 20:04
duplicate of #1342

**Closed by rubenwardy** 2017-09-08 20:04 UTC
Labels: @ Script API, Feature request
