### ISSUE TITLE
Player is getting damaged when damage is disabled.

### ISSUE THREAD

**Issue by LandonAConway** [minetest/minetest#10161] opened 2020-07-06 06:10 UTC
##### Minetest Version
Minetest 5.2.1 - 5.2.0

##### OS / Hardware
Operating system: Windows 10

##### Summary
When I'm playing any server that has the 'Enable Damage' feature disabled, the player still gets damaged regardless of where it is disabled or not. If I let mobs attack me, or I jump off a cliff, I will die even though there is supposed to be no damage. If this is intentional, then why? Just... why? I believe that a feature should do what it suggests! This is very frustrating and I have been dealing with it for a few months after updating Minetest until I finally came here. Please fix the issue.

##### Steps to reproduce
Go into Minetest, and create a server. Make sure the "Enable Damage" checkbox is NOT ticked when still in the main menu. Play the server you created, then jump off of a very high cliff and let hit ground. You will probably die even though there is supposedly no damage enabled. This is very infuriating.

**Comment by sfan5** [comment] 2020-07-06 10:05
possible duplicate of #9022, which describes buggy behavior caused by 3d_armor

**Comment by sirrobzeroone** [comment] 2020-07-24 12:26
I also ran a test 5.2.0 and 3d_armour 0.4.13 - OS Win10 - minetest 64bit

Baseline - Base game no mods run server and fly to high height and then engage gravity (turn off flying :) ) - fall and live

3d armour - Base game, only mod enabled 3d_armour 0.4.13 - fly to high height and fall and splat (death).

Other mod - Base game, only mod - mobs_redo - fly to high height and fall and live.

Not sure if this helps confirm 3d_armour as the issue.

**Closed** 2020-07-27 14:12 UTC
Labels: Possible close, Unconfirmed bug
