### ISSUE TITLE
Multiplayer server list sorting by

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#6494] opened 2017-10-04 14:52 UTC
I would like to add this feature in next version to sort server list names better in multiplayer main menu. Sorted by: Name, players, ping, creative, pvp, survival (damage enabled), etc.

**Comment by SmallJoker** [comment] 2017-10-04 14:58
Duplicate of #2568.

**Closed** 2017-10-04 15:03 UTC
Labels: Duplicate
