### ISSUE TITLE
[5.0.1] Click on "register and connect" do nothing on Linux and Android

### ISSUE THREAD

**Issue by Baal404** [minetest/minetest#8568] opened 2019-05-28 22:29 UTC
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.1
```

##### OS / Hardware
Operating system: OpenSuse Leap 15.1 / Android 7
CPU: Pentium E6700 3.2 GHz
Smartphone: Xperia F3111

##### Summary
When i click on "Register and connect" nothing happened.

##### Steps to reproduce
1 - Just select a server to connect
2 - After Minetest ask for a password to register and connect, juste click on "register and connect"
I have no mods or packs installed.

The issue happened both on my Suse distribution and my Android smartphone.

**Comment by NathanSalapat** [comment] 2019-05-28 23:03
Just for clarity, did you try this on multiple servers?

**Comment by Baal404** [comment] 2019-05-28 23:10
> Just for clarity, did you try this on multiple servers?

Yep !

**Comment by Linuxdirk** [comment] 2019-05-29 05:03
When on local testing servers (i.e. no password used) everything works, but when I registered on a public server last time after entering my password a second time to register nothing happened. After trying again the message did not come up a second time and I was able to log in normally.

**Comment by SmallJoker** [comment] 2019-12-07 15:40
Does this still happen in 5.1.0?
apk here: https://github.com/minetest/minetest/releases

**Comment by Fixer-007** [comment] 2019-12-08 22:19
What localization are you using? This problem happens when translation of that string is not up to date. I had the same problem. We need to check every localisation for this problem, or players will not be able to connect. This may be a serious bug.

**Comment by paramat** [comment] 2019-12-09 16:40
This password confirmation formspec is such a pain, it should have been reverted as i suggested a while back. We intend to rework it.
Added labels in case Fixer is correct about the cause.

**Comment by rubenwardy** [comment] 2019-12-09 16:52
I support removing it given the added value is fairly low

**Comment by SmallJoker** [comment] 2019-12-09 17:46
The only issue I can see is that probably the server list's Login/Register password does not equal to the one you entered in the confirmation GUI.

There is no message if the inputs mismatch. This dialogue was criticized often, but I think it's still useful to not accidentally register a new user with a wrong password. After all this looks like a feature request because the "do nothing on mismatch" behaviour is misleading.

**Comment by rubenwardy** [comment] 2019-12-09 18:04
> There is no message if the inputs mismatch. This dialogue was criticized often, but I think it's still useful to not accidentally register a new user with a wrong password. After all this looks like a feature request because the "do nothing on mismatch" behaviour is misleading.

The UX of it is confusing, especially the lack of an error message. Users are used to seeing "Password" and "Confirm Password", but not on different pages

**Comment by sfan5** [comment] 2020-03-26 19:54
This was fixed in a462181e5fe631b816cb67a4e2cb8a870ed71840 which was unfortunately not backported to 5.1.1 despite the possibility existing.
But the fix will be in 5.2.0.

**Closed by sfan5** 2020-03-26 19:54 UTC
Labels: @ Server / Client / Env., @ Translation, Bug
