### ISSUE TITLE
Anticheat says player moves too fast regardless of `movement_speed_fast` parameter

### ISSUE THREAD

**Issue by yetanotherusernamebecausegithubisbugged** [minetest/minetest#2356] opened 2015-02-19 18:05 UTC
I'm trying to set up the `sprint` mod on a linux server and facing this problem. Also, `movement_speed_walk` and `movement_speed_fast` are affecting actual default player speed so probably anticheat should have another separate `max_player_speed` option or allow mods to set `max_player_speed` for each player individually.

**Comment by asl97** [comment] 2015-12-01 17:59
I can confirm this.

<sub>(i was in the middle of creating an issue when i found this so i copy and paste the content of my issue, title and all, below)<sub>
____

#### Server doesn't use movement speed setting for anti cheat

if the movement is higher than the default value, it would spam `Player test moved too fast; resetting position` once the player is moving at max speed for a short while.

this is because the server only send the movement (in server.cpp) to the client but doesn't override the default setting, thus it use the default that is stated in player.cpp for the anti cheat.

tested on a local server, it affect both walk and run.

note: if the player has the fast privs, it would only happen when the player is running

**Comment by BlockMen** [comment] 2015-12-16 18:08
Fixed by 19f73e4efc14622b4d020c9d373176cd7801e37f

**Closed by BlockMen** 2015-12-16 18:08 UTC
Labels: bug
