### ISSUE TITLE
Sun render glitches at sunrise

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4195] opened 2016-06-06 22:17 UTC
Reproducing:
- go up somewhat to see horizon clearly
- set /time 4:20
- orient yourself towards +X East where Sun will rise.

You will notice abnormal blinking/z-fighting sun contour below horizon.

```
Minetest 0.4.14-xxx-d4457ef-dirty (Windows)
Using Irrlicht 1.8.1
Build info: VER=0.4.14-2060fd9-d4457ef-dirty BUILD_TYPE=Release RUN_IN_PLACE=1 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="."

Videocard: AMD/ATI HD6870, latest drivers.
```

**Comment by paramat** [comment] 2016-06-10 05:12
I can't reproduce this, it might somehow be due to your setup.

**Comment by paramat** [comment] 2017-07-08 23:02
Can anyone reproduce this?

**Comment by Fixer-007** [comment] 2017-08-12 19:52
Update
I've rechecked that bug, sky jitter seems to be ok actually (it is very probably TN-Film colours gradient problem), BUT z-fighting (?) sun contour below horizon bug still happens on 248a1a8d.
Picture:
![default](https://user-images.githubusercontent.com/16494741/29243805-e17dd516-7fb0-11e7-8983-a45d9df04b2e.png)

**Comment by paramat** [comment] 2017-08-12 20:20
The farcloudyfogthing (the haze below horizon) is drawn twice for E, W directions, maybe i'll try avoiding that double draw in case it helps.

**Comment by paramat** [comment] 2017-08-13 17:18
> The farcloudyfogthing (the haze below horizon) is drawn twice for E, W directions:

Experimented and this is correct as it is, the second time it is drawn at a different size by necessity.

**Comment by rubenwardy** [comment] 2021-01-28 19:13
Closing as code has since changed drastically

**Closed by rubenwardy** 2021-01-28 19:13 UTC
Labels: @ Client / Audiovisuals, Low priority
