### ISSUE TITLE
Workflow: Visual Studio 2019 x86 builds failing

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10343] opened 2020-08-28 21:35 UTC
```
 database-postgresql.obj : error LNK2001: unresolved external symbol _PQprepare [D:\a\minetest\minetest\src\minetest.vcxproj]
database-postgresql.obj : error LNK2001: unresolved external symbol _PQgetvalue [D:\a\minetest\minetest\src\minetest.vcxproj]
database-postgresql.obj : error LNK2001: unresolved external symbol _PQresultStatus [D:\a\minetest\minetest\src\minetest.vcxproj]
database-postgresql.obj : error LNK2001: unresolved external symbol _PQreset [D:\a\minetest\minetest\src\minetest.vcxproj]
database-postgresql.obj : error LNK2001: unresolved external symbol _PQstatus [D:\a\minetest\minetest\src\minetest.vcxproj]
database-postgresql.obj : error LNK2001: unresolved external symbol _PQserverVersion [D:\a\minetest\minetest\src\minetest.vcxproj]
database-postgresql.obj : error LNK2001: unresolved external symbol _PQerrorMessage [D:\a\minetest\minetest\src\minetest.vcxproj]
database-postgresql.obj : error LNK2001: unresolved external symbol _PQexecPrepared [D:\a\minetest\minetest\src\minetest.vcxproj]
database-postgresql.obj : error LNK2001: unresolved external symbol _PQfinish [D:\a\minetest\minetest\src\minetest.vcxproj]
database-postgresql.obj : error LNK2001: unresolved external symbol _PQresultErrorMessage [D:\a\minetest\minetest\src\minetest.vcxproj]
database-postgresql.obj : error LNK2001: unresolved external symbol _PQexec [D:\a\minetest\minetest\src\minetest.vcxproj]
database-postgresql.obj : error LNK2001: unresolved external symbol _PQgetlength [D:\a\minetest\minetest\src\minetest.vcxproj]
database-postgresql.obj : error LNK2001: unresolved external symbol _PQclear [D:\a\minetest\minetest\src\minetest.vcxproj]
database-postgresql.obj : error LNK2001: unresolved external symbol _PQconnectdb [D:\a\minetest\minetest\src\minetest.vcxproj]
database-postgresql.obj : error LNK2001: unresolved external symbol _PQntuples [D:\a\minetest\minetest\src\minetest.vcxproj]
database-postgresql.obj : error LNK2001: unresolved external symbol _PQping [D:\a\minetest\minetest\src\minetest.vcxproj]
D:\a\minetest\minetest\bin\Release\minetest.exe : fatal error LNK1120: 16 unresolved externals [D:\a\minetest\minetest\src\minetest.vcxproj]
```

**Comment by sfan5** [comment] 2020-08-28 21:37
No they don't: https://github.com/minetest/minetest/runs/1038334829

this is also a duplicate of #10048

**Closed by sfan5** 2020-08-28 21:37 UTC
Labels: Unconfirmed bug
