### ISSUE TITLE
minetest.conf csm_autodownloads = true setting and mechanism needed.

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest#6491] opened 2017-10-04 13:56 UTC
Right now we have Server-Side Mods (SSM), mod channels, and Client-Side Mods (CSM).  However, in order for this to be entirely practical for the server's needs, it must know that the client has connected with the appropriate CSM loaded.

I suggest a setting, `csm_autodownloads`, default false, that when enabled will allow the client to download the necessary CSM from the server.  The server will then know it can use mod channels to interact between SSM and CSM.

```
<+sfan5> csm is sandboxed, so servers sending lua code should not be a problem
<+Calinou> jas_: client-side mods can't be sent from server to client, that would be too insecure
```

**Comment by rubenwardy** [comment] 2017-10-04 13:58
duplicate of #5393

**Closed by rubenwardy** 2017-10-04 13:58 UTC
