### ISSUE TITLE
Add control to replace wielded item with pointed thing in Creative Mode

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6753] opened 2017-12-08 17:36 UTC
## Summary

I suggest the “Pick Item” control for Creative Mode. Pick Item is a control like any other.
If you press Pick Item (default: middle mouse button), the current item in hand will be replaced by the “item form” of the pointed thing (if there is any).
Pick Item is a no-op if you're not in Creative Mode.

Example:
If you point a cobblestone, and press Pick Item, your wielded item will be replaced with cobblestone.

## Rationale

Creative Mode will become about one billion times more convenient, since you don't have to go through the inventory as much. :wink:

### Nodes
By default, nodes will be picked by their itemstring. For most nodes, the default will work perfectly fine. The new wielded item always has the stack size of 1.

But in some cases, customization will be required for items which should never be aquired by the player.

All items can optionally set a “pick item override” attribute in their definition. This can be a string or function. The function is only possible for nodes.
If it's a string, this is the itemstring the player will obtain.
If it's a function, this function will be called with arguments `pos, node` and must return the `ItemStack` to pick. By convention, the stack size should always be 1.

This can be useful for internal items/blocks which the player must not obtain in the inventory. The idea is the same as for the `not_in_creative_mode=1` group.
Example: In Minetest Game, the 5 grass nodes (5 heights) should all give the same item if picked.

The attribute can also be set to the empty string. This has a special meaning. In this case, the item/node can NOT be picked; nothing happens if you use Pick Item on this.

### Entities

Pick items is a no-op for entities and players by default.

But entities can optionally set the itemstring to be “picked” when pick item is used on this entity. This must only affect the wielded item, the entity itself must remain unchanged.
This attribute can be a string or function.
`string` is an itemstring, as before.
The function gets `self` and must return the `ItemStack` to pick. By convention, the stack size should by 1.
If the attribute is `nil` or the empty string, using pick item is a no-op.

Behaviour for builtin entities:
* Falling node: Pick the node it represents. This must work as if the node is picked. So if the node has any overrides, they have to be respected.
* Dropped items: Pick the item this entity represents, using the function syntax. Similar to falling nodes.
* Players: No-op.

Behaviour for Minetest Game entities:
* Boat: Pick `boats:boat`
* Cart: Pick `carts:cart`

**Comment by rubenwardy** [comment] 2017-12-08 20:30
duplicate of #2730

**Closed by rubenwardy** 2017-12-08 20:30 UTC
