### ISSUE TITLE
SSH and HTTP connectivity dies when logging into certain Minetest servers 

### ISSUE THREAD

**Issue by sorcerykid** [minetest/minetest#9310] opened 2020-01-14 05:27 UTC
##### Minetest version

```
Minetest 5.0.0
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Microsoft Windows 10 Home Build 17134
CPU: Intel Core i5-7200U 2.50GHz  
Brand/Model: Dell Inspiron 13-7378 x64 

##### Summary
While logging into certain Minetest 5.x servers, the client will hang as it begins media loading and then suddenly all connections to HTTP, SSH, etc. will drop system-wide. However, my Wi-Fi indicator will show that I am still connected to the Internet. Likewise, YouTube videos will continue playing in the background. But if I try to navigate to any sites in my Web browser, it will report a timeout connecting to server. Likewise, I can still enter the command prompt and use `ping` and `tracert` and `nslookup`.  So there clearly appears to be limited connectivity just for ICMP and UDP. But higher level protocols TCP/IP protocols seem to be completely non-workable.

[Screenshot of timeout in Chrome browser](https://imgur.com/nW8HYwA)

I have tried manually disabling and re-enabling my WiFi adapter from the device control panel. That just causes the Wi-Fi menu to freeze up. I've also tried running the automated troubleshooter, but it detects no problems with my network configuration. I've even researched ways to manually reset TCP/IP in Windows, including issuing the command `netsh int ip reset`, but that does nothing.

It's very difficult to pin down whether this is a defect with my network adapter, operating system, or router. But it seems very clear that Minetest is in someway related, since no other applications effect my Internet connectivity. I am not an expert at all in networking, so I can't even begin to diagnose the problem on my own. So any suggestions on what type of logs I should post (and where to find them) would be greatly appreciated.

##### Steps to reproduce
Various servers like Must Test and IFS (IhrFussels Server) exhibit this problem. Yet for some reason, other servers like just test and VanessaE's Banananland Survival Server do not.

**Comment by sfan5** [comment] 2020-01-14 10:54
> my Wi-Fi indicator will show that I am still connected to the Internet

The indicator you are referring to typically only shows connection to a LAN, not the internet itself.
Or if it does, changes in connectivity are not instantly reflected.

> YouTube videos will continue playing in the background

YouTube buffers the video ahead for a certain duration.

> I can still enter the command prompt and use `ping`

This would be helpful to see, you could e.g. leave an endless ping running and then reproduce the problem.

> It's very difficult to pin down whether this is a defect with my network adapter, operating system, or router. 

There are some possible steps to narrow this down:
* try it over an Ethernet connection
* try it on Linux
* try while tethering Internet over your phone / in a public wifi / ...

<hr>

But before you troubleshoot I can give you the most likely explanation (<b>a guess</b>):

Your router can't cope with the amount of UDP packets Minetest sends ([such things exist](https://www.raymond.cc/blog/stop-bittorrent-from-killing-your-internet-connection/)) and stops doing its job properly while the "flood" of packets lasts.
We can't fix this (automatically) without artificially restricting the performance of networking for everyone else too, so this is a dead end.

**Comment by style-nine** [comment] 2020-01-14 14:26
Sounds like DNS problems. https://docs.microsoft.com/en-us/windows-server/networking/dns/troubleshoot/troubleshoot-dns-server

**Comment by thomasrudin** [comment] 2020-01-14 20:24
@sorcerykid does this happen only if the media gets loaded over udp or http?

> Various servers like Must Test and IFS (IhrFussels Server) exhibit this problem. Yet for some reason, other servers like just test and VanessaE's Banananland Survival Server do not.

My bet is on the udp-flood thing and that VE's servers use a http media-cache...

**Comment by SmallJoker** [comment] 2020-01-14 20:45
I had a similar problem which originated in the router that couldn't handle the packets. Decreasing the hardcoded minimal curl connections - or falling back to the non-media-server feature solved the problem.

**Comment by gpcf** [comment] 2020-02-06 22:53
I have the same problem on linuxworks server. When logged in with two clients on the same network, the network becomes unresponsive. I assume it is an issue caused by udp packets flodding the router or the computer.

**Comment by gpcf** [comment] 2020-02-06 23:26
The server log is full of these entries, confirming my suspicion that this is caused by some kind of flood due to improper handling of connection problems while sending reliable stuff:
```
2020-02-07 00:22:49: VERBOSE[ConnectionSend]: con(4/1)RE-SENDING timed-out RELIABLE to [IP redacted](t/o=0.132): from_peer_id=1, channel=0, seqnum=43466
2020-02-07 00:22:49: VERBOSE[ConnectionReceive]: con(4/1)WARNING: ACKed packet not in outgoing queue
```

Is there maybe any minetest.conf setting that could be tweaked? max_packets_per_iteration seems like a start, but it's sadly not per-player, I fear a laggy client could exhaust this.

**Comment by thomasrudin** [comment] 2020-02-07 05:44
> The server log is full of these entries, confirming my suspicion that this is caused by some kind of flood due to improper handling of connection problems while sending reliable stuff:

While i was developing the prometheus extensions for the engine i may have caught the same thing: sudden intense bursts of packet resending, most of them took a few MB/sec for a couple seconds...

**Comment by gpcf** [comment] 2020-02-07 18:42
Also happening during these events:
```
gpcf@knoblauch ~ $ ping 192.168.1.1
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
From 192.168.0.9 icmp_seq=50 Destination Host Unreachable
From 192.168.0.9 icmp_seq=52 Destination Host Unreachable
From 192.168.0.9 icmp_seq=53 Destination Host Unreachable
From 192.168.0.9 icmp_seq=97 Destination Host Unreachable
From 192.168.0.9 icmp_seq=98 Destination Host Unreachable
ping: sendmsg: No buffer space available
```

**Comment by gpcf** [comment] 2020-02-07 19:00
After lowering `max_packets_per_iteration` from 40000 to 1024 the problem seems to be much better. I hope no negative side effects will arise from this change.

**Comment by nerzhul** [comment] 2020-04-22 16:05
i don't know why we are doing support on end users bad routers, anyway closing, a solution has been found

**Closed by nerzhul** 2020-04-22 16:05 UTC
Labels: @ Network, Question
