### ISSUE TITLE
Allow use and punch buttons to be customized

### ISSUE THREAD

**Issue by Towtow10** [minetest/minetest#8853] opened 2019-08-24 04:13 UTC
## Problem
You can't customize the use and punch buttons they are currently RMB and LMB respectively, I would like to be able to switch them.

## Solutions
Add an option in the all settings control section that would allow you to change what is bound to use and punch.

**Comment by style-nine** [comment] 2019-08-24 06:54
https://github.com/minetest/minetest/issues/2361

**Comment by ClobberXD** [comment] 2019-08-24 07:47
Duplicate of #2361, and there's also a PR that implements this feature: #7924

**Comment by ClobberXD** [comment] 2019-08-24 08:46
#7924 implements this.

**Closed** 2019-08-24 09:08 UTC
Labels: Duplicate, Feature request

**Comment by jastevenson303** [comment] 2019-08-24 11:44
@ANAND why do you refer to a closed PR?

**Comment by ClobberXD** [comment] 2019-08-24 16:36
@jastevenson303 #7924 is still open. I don't understand what you mean... :confused:

**Comment by jastevenson303** [comment] 2019-08-24 18:57
Sorry my mistake.

**Comment by jastevenson303** [comment] 2019-08-25 08:42
Can it be merged?
