### ISSUE TITLE
add an form to allow game devs to create their own "main screen"

### ISSUE THREAD

**Issue by sotha1** [minetest/minetest#14219] opened 2024-01-05 22:48 UTC
### Problem

people that now know that minetest is not only the "minetest game (base game)" and it have other games now think that it still a bit minecraft-like even if you can play games that are not minecraft-like (e.g. subway miner) because in the world selection you don't have a classic main sereen and you have to 'create a 'world' to play the game and select the mapgen and the world's name. it would be interesting if subway miner can create it's own new game screen, without the player have to create a world, but just touch the screen and play.

down is some examples of how my suggestion would be used for:
![aadc8ce7a6d283528b7df76e7fd1d64c](https://github.com/minetest/minetest/assets/149703967/347d492c-21e6-42a5-bec1-cad0ecac9184)
![images](https://github.com/minetest/minetest/assets/149703967/60784705-c626-4a4d-bd2e-378eaa85f1a1)
![MainScreen](https://github.com/minetest/minetest/assets/149703967/a4f13ffe-41ef-43c6-bd59-f3fdbde04bf9)

### Solutions

allow to game devs just edit the main screen to their own games, like how it's in formspec

### Alternatives

i don't know a alternative, i still thinking that this is simple to do.

### Additional context

this is for change players mind, to remove the mask of "only-minecraft-like"

**Comment by wsor4035** [comment] 2024-01-06 04:08
duplicate of https://github.com/minetest/minetest/issues/10994 (see linked issues in that one as well)

**Closed by wsor4035** 2024-01-06 04:08 UTC
Labels: Feature request
