### ISSUE TITLE
Make chat text more contrast (?) see the screenshot

### ISSUE THREAD

**Issue by kay27** [minetest/minetest#11056] opened 2021-03-13 05:27 UTC
![image](https://user-images.githubusercontent.com/2028802/111020108-e1d7eb80-83dc-11eb-902e-ab1c141b5f15.png)

Zoomed in example is:

![image](https://user-images.githubusercontent.com/2028802/111020255-f10b6900-83dd-11eb-9fd8-db005191a8ab.png)

If the shadow would opaque black, or would has 2-3 pixels, or one additional shadow from the top, maybe the readability would be better.

**Comment by SmallJoker** [comment] 2021-03-13 07:41
Duplicate of #4650.

**Closed by SmallJoker** 2021-03-13 07:41 UTC
