### ISSUE TITLE
Allow use of all keys

### ISSUE THREAD

**Issue by MisterXtreme** [minetest/minetest#5825] opened 2017-05-26 15:36 UTC
Being able to use all key would mean less stepping on toes with the Aux/Speed/whatever It's currently-called-key, and give some variety.
Any problems with this, then please let me know. :)

**Comment by paramat** [comment] 2017-05-26 16:11
I think there is a PR somewhere that allows any key to be used, there may be an issue already too.

**Comment by XtremeHacker** [comment] 2017-05-26 16:22
OK, I'll have to try & find it.

**Comment by dsohler** [comment] 2017-05-26 16:52
> I think there is a PR somewhere that allows any key to be used

Then why isn't it merged already? :cry:

**Comment by raymoo** [comment] 2017-05-27 06:48
If we remove Android support then there would be pretty much no argument against it.

However, maybe key input should be a client-side modding thing, with mod channels being used to communicate commands to the server. This would avoid needing to send all keypresses to the server, or worse, the entire keystate (though this could be shorter than every key if you just send a list of pressed keys). Also, it would eliminate latency for operations that do not require the server to do anything, e.g. modded UI stuff. Once we have mod channels, and server-provided client mods, this plus HUD elements would be enough to have some kind of modded GUI stuff with custom controls.

Another thing: it would be really really good if the Minetest API came with something that abstracts actions from specific keys, so that it is easy for players to modify mod controls. If not, a mod could do it, but it's something that really should be in core. Mods should be able to specify a default control too, to avoid needing the player to bind "funmod:up", "funmod:left", etc. for every mod that wants to use something like the arrow keys.

**Comment by Calinou** [comment] 2017-05-27 07:22
> Another thing: it would be really really good if the Minetest API came with something that abstracts actions from specific keys, so that it is easy for players to modify mod controls.

This is extremely important, especially for users of non-QWERTY keyboard layouts.

**Comment by dsohler** [comment] 2017-05-27 08:34
> However, maybe key input should be a client-side modding thing,

I strongly disagree. Core functionality (and being able to set any function to any key, key comboination, or mouse button, or mouse-button-and-key combination IS a core functionality to me) should be done in core.

CSM should not be used as excuse to not add core functionality

**Comment by raymoo** [comment] 2017-05-27 09:25
@dsohler Sorry, what I meant is that key input should be part of the CSM API, not that it should be implemented by client mods.

**Comment by raymoo** [comment] 2017-05-27 09:27
@dsohler In fact, I don't see any nice way of implementing key input by client mods alone anyway, since it would need to somehow mess with Minetest's window to get input.

**Comment by benrob0329** [comment] 2017-12-22 15:51
Idea for a callback-based key api:

```Lua
minetest.register_key({
    name = "Sprint"
    defaultkeys = {"e", "w"}
    on_press = function(player)
        player:set_property("speed", 2.0)
    end

    on_release = function(player)
        player:set_properties("speed", 1.0)
    end
})
```

```
Client: Connect
Server: I need the keypresses for "Sprint", the default keys are e and w.
Client: "Sprint" Pressed.
Client: "Sprint" released.
```

The client should be able to remap the keys based on the name, "Sprint". This also means that if the client stores the key setting based on the name, other server' sprint will be triggered by the same keys. (The server could have a different name for it if a different keycombination is needed)

Right now the constant key-polling causes a lot of lag (more than mobs I've found), so this should help reduce that by only having the client send the key events needed by the server, sending none if not needed.

**Comment by raymoo** [comment] 2017-12-22 18:46
@benrob0329 I think there should be a separate name and description like for items, with the name having "modname:" prefixed to avoid collisions.

**Comment by paramat** [comment] 2017-12-22 22:54
I feel there may be an issue about this already, please search.

**Comment by DS-Minetest** [comment] 2017-12-31 18:29
Searched and found: #2731

**Comment by paramat** [comment] 2018-01-01 04:52
Duplicate of #2731

**Closed by paramat** 2018-01-01 04:52 UTC
Labels: @ Client / Controls / Input, Feature request
