### ISSUE TITLE
GCC 6 warning in treegen

### ISSUE THREAD

**Issue by est31** [minetest/minetest#4300] opened 2016-07-08 05:28 UTC
When compiling, GCC 6.1.1 gives the following warning in treegen:
```
In function 'void treegen::make_pine_tree(MMVManip&, v3s16, INodeDefManager*, irr::s32)':
cc1plus: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]
```

**Comment by paramat** [comment] 2016-07-09 06:17
Looking. I assume it's something to do with signed and unsigned integers?

**Comment by paramat** [comment] 2016-07-09 06:43
Looking, i can clean up the use of signed / unsigned integers which i assume is the cause.

**Comment by paramat** [comment] 2016-07-09 06:59
https://github.com/minetest/minetest/blob/master/src/treegen.cpp#L799
'dev' should be unsigned, will try this and claen up other stuff too.

**Comment by paramat** [comment] 2016-07-10 15:09
See #4308 
Can anyone test this?

**Comment by Fixer-007** [comment] 2016-07-10 15:27
GCC 4.9.2 cross-compilation was successful on that build.

**Comment by paramat** [comment] 2016-07-12 19:33
#4308 is merged.

**Closed by paramat** 2016-07-12 19:33 UTC
Labels: @ Build, @ Mapgen, Bug
