### ISSUE TITLE
Guest nicknames must die

### ISSUE THREAD

**Issue by iqualfragile** [minetest/minetest#1059] opened 2013-12-17 12:32 UTC
It seems like a lot of people would not choose a proper nickname before joining a server and according to my servers log not even choose any kind of password, they just click any server from the server list and try to join it by doubleclicking. This is not good for multiple reasons:
1. I strongly doubt that People who do not even choose a nickname will be constructive on any server
2. People with Guest\* nicknames are hardly reckognizable, therefore it gets harder to build some kind of community
3. Giving people the option to not choose any password will ultimately get some people not to do so

Sollution: minetest should tell you to choose a username and password before joining any server.

**Comment by paramat** [comment] 2016-03-27 14:10
:+1: I get a bad vibe whenever i see 'guest*****'

**Comment by rubenwardy** [comment] 2016-03-27 15:39
The guest option should be removed, definitely. It's already the standard for servers to use no_guests, so pointless anyway.

**Comment by C1ffisme** [comment] 2016-03-27 17:20
I'm not sure why this was added in the first place... And no configuration to disable it.

Although, minetest should not require a password, since it would get annoying for people who just want to play a LAN server.

**Comment by rubenwardy** [comment] 2016-03-27 18:46
> Although, minetest should not require a password, since it would get annoying for people who just want to play a LAN server.

By default it doesn't. It's configurable.

**Comment by C1ffisme** [comment] 2016-03-27 20:05
@rubenwardy Not right now, it doesn't. I just wanted to keep it that way. (Sorry, must have read something wrongly.)

**Comment by t4im** [comment] 2016-07-24 14:30
> Guest nicknames must die

### The guest is dead, long live the gu357tSfiD1fh!
By completely disallowing this guest situation,
people will just either stay away or create an even worse one.

```
qwe231
iqual123
asdjada
auw3r
doaishd
oe209384
```
And whatever the cat produces when taking control of the keyboard. :smirk_cat: 

I hardly ever check out a server, that doesn't allow me to guest-in without password the first time.
I'm too lazy to create a new password for every server i want to test and not brave enough to reuse passwords over several servers.

### Be a good host and delete your guests
Those guest-names can be better recognized automatically.
```lua
player_name:match("^Guest%d%d%d%d$")
```
You would not have to treat guest accounts like every other.
E.g. A mod could time out and delete guests after a few days or already when the guest is leaving the server.

You won't be able to force people into a proper nickname all the time anyway.
Some people just want to check out minetest or a server.
By allowing that and by giving people **more** reason to use guest names for a test-run, you could actually decrease server maintenance by e.g. reducing the need for random names. :crying_cat_face:

### Are you sure you don't want interact?
*  Softly discourage the empty name field instead of disallowing it.
  * Suggest the system-user name as a default.
  * Remember a chosen name over different servers (already done)
  * If the field is empty, open up an extra dialog explaining, that a name will be assigned and that it can't be change after without losing all your stuff on that server. But still allow to continue!
    That way you also reach those, that don't realize that the username in the server tab is not just meant for private servers, like it is in other games, but also registers an account.
* Undefault the no_guest stuff: Allow those, that intentionally want to join as a guest, to join without littering into your auth.txt, inventory files etc. or forcing them to quit minetest, before they had a look at it.

Maybe we could even prevent guest accounts from being created at all.
Everyone can check out servers yet passers-by just stay passers-by.
Where's the harm in thaata?lpi3w764a9s7d :smile_cat:

**Comment by Calinou** [comment] 2016-07-24 14:54
> Suggest the system-user name as a default.

Sounds good to me, some games already do this. However, we should ensure spaces and other disallowed characters (like special characters) are replaced with an underscore, for example.

Some people might object to this since they use their real name as system username, though. Also, is this possible on Android?

**Comment by VanessaE** [comment] 2016-07-24 14:54
On my servers, "gibberish" names are filtered out with a bit of code that @sfan5 came up with, which tries to estimate whether the name can be pronounced at all, combined with a couple of regexes that filter out names with too many digits (or all-numeric).  Between those, disallowing "Guest*" and a few others of similar type, and requiring a password, the vast majority of crap usernames have disappeared from my servers

**Comment by iqualfragile** [comment] 2016-07-24 15:20
@t4im i have to disagree with your point, at least in parts.
First of all, choosing the system user name, which often is the actual real name of a person is a heavy breach of privacy. Not a good idea.
Filling up the Auth.txt is not a problem at all, at least not computationally.
I don't really see the reason why you would not use your actually nickname for joining servers, even on test runs.
iirc minetest now does never send the actual password to the server, so just using your "default" password with the servername added will be enough.

The whole point of this issue was to filter out people who most likely won't contribute anything useful to the server. The point still stands. The majority of server administrators use a no guests mod, so it seems like the need is still there. This should still be integrated into minetest. The issue has been open for nearly 3 years now, i don't think the change is that complex.

Another issue, but that would be more of a feature request would be to maybe add a special minetest-wide visitor-account, that allows connecting and spectating servers maybe with things like fly-by-default and lower block-send priorities, but that, as stated is another issue.

**Comment by everamzah** [comment] 2016-07-24 20:05
It all seems so moot to me, and I always wonder what the fuss is all about.

I liked the points above about discouraging default names instead of disallowing them.  I think no-op is still generally best, however.  I feel this may be a modding discussion, and not an engine issue.  The issue is better named "What should the default username string be, if anything?"

**Comment by C1ffisme** [comment] 2016-07-25 16:59
What if someone has an acceptable gibberish name, like 0gb.us? (pronounced Zero Gee Bee You Es)

Mine is C1ff. (pronounced See One Eff Eff)

Not all gibberish nicknames are unpronounceable trash.

@everamzah 

> "What should the default username string be, if anything?"

We could make a username generator, which could work something like this:

**Step 1: Choose an adjective for a first name.**

Choose from one of these names:

```
dirty

yummy

slimy

awesome

cheesy

etc.
```
(Maybe these examples aren't the best, but I'm trying to think of the kind of things that a children's MMO would use.)

**Step 2: Choose a noun for the last name.**

Choose a noun from this list:

```
apple

miner

diamond

block

seed

etc.
```
**Step 3 : Put it together and add a good number:**

Put an underscore between the first and last name and add a memorable number. Lots of numbers in usernames are simply the first digit, a second digit, and then the first digit again, like 242 or 676. So a number could be made by choosing a 2 digit number, multiplying it by ten and using the first digit in the ones place. (Because some people just can't handle numbers like 616 or 666, if the random 2 digit number is 61 or 66, the number needs to be regenerated.)

So you'd get something like this:

`awesome_apple818`

That should be easy enough for someone to read.

**Comment by everamzah** [comment] 2016-07-25 17:05
It was rhetorical, and perhaps I should apologize for that.  I don't think the default username string should be anything; and if it must, I suggest "playername", as it is in other games.

If a player is unable to enter english alphabet characters into this string, that is a separate issue.

**Comment by VanessaE** [comment] 2016-07-25 17:12
Well in the case of the filter I use on my servers, nicknames that are short enough are exempted from the filter anyway - my theory was that as the names get shorter, the chances of it looking like gibberish increase unfairly.  Seems to be working okay so far.  That said, you're right that a name like @0gb-us would probably get caught up in the filter.

I do like your two-dictionary-words idea, it has merit (it's good for passwords, too, so long as it isn't "[correcthorsebatterystaple](https://xkcd.com/936/)" :stuck_out_tongue: ).

Not sure how one would actually present such choices to the user though, without encouraging them to use only the few choices first visible on-screen (players seem to have a mental block against scrolling).

**Comment by C1ffisme** [comment] 2016-07-25 17:20
> Not sure how one would actually present such choices to the user though, without encouraging them to use only the few choices first visible on-screen (players seem to have a mental block against scrolling).

I was thinking of the computer choosing randomly for the player, and then perhaps the player can edit that name after generation, right before connection to the server.

Just to make sure nobody uses the same or a similar username than anyone else, though,  we would need 25 or more adjectives and nouns.

The username should also remain in the box to put your username after disconnecting a server, to avoid people making a user, mining materials and leaving the server, never being able to join back as the same user again to get those materials.

**Comment by VanessaE** [comment] 2016-07-25 17:25
In which case, I guess it would be best to have that feature as a separate "Help me choose..." button that opens a new dialog/formspec, making it obvious what's going on.

**Comment by DonBatman** [comment] 2016-07-25 20:50
We have the option to not allow empty passwords. Why not do the same for names?

**Comment by 0-afflatus** [comment] 2016-07-25 21:15
I use the name_restrictions mod and set disallow_empty_password. We certainly should discourage the use of meaningless user names. I do like the idea of having a proper 'guest' account with settable reduced privs and a disposable auto-generated name, but that needs to be done without admin intervention, manually deleting player names is not desirable. 

I'm not keen on the idea of having spectators on my server, but if there was a built-in mechanism I might use it.

**Comment by paramat** [comment] 2017-01-22 01:06
> By completely disallowing this guest situation,
people will just either stay away or create an even worse one.

A random name is still better than guest#### and will be caught by anti-gibberish if needed.

> You won't be able to force people into a proper nickname all the time anyway.
Some people just want to check out minetest or a server.

If someone is to lazy to create a quickly improvised name they're not wanted on a server anyway.

> First of all, choosing the system user name, which often is the actual real name of a person is a heavy breach of privacy. Not a good idea.

I agree.

A name generator is over-complex, all we need to do is prompt the player to enter a name, as in #5078

**Comment by paramat** [comment] 2017-02-09 00:20
#5078 merged.

**Closed by paramat** 2017-02-09 00:20 UTC
Labels: @ Server / Client / Env., Feature request
