### ISSUE TITLE
Hotbar background incorrect when hotbar wrapped to a second line

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#9269] opened 2019-12-31 17:48 UTC
##### Minetest version\
```
Minetest 5.2.0-dev-8e63d22d (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=0
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=0
STATIC_SHAREDIR="."
```

##### OS / Hardware
Operating system:
- `Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux`
CPU:
- `Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz`

##### Summary
On very narrow screens (where the hotbar wraps to a second line) the background image is repeated vertically, but stretched horizontally instead of cropped.

##### Steps to reproduce
- Load any game that uses a background image for the hotbar (e.g. MTG).
- Shrink the window horizontally until the hotbar wraps onto a second line.

##### Expected result
If hotbar needs to be broken into 2 halves and wrapped, then the background image would also be broken into 2 halves and wrapped.

##### Actual result
hotbar background texture is repeated in its entirety and stretched, so when an 8-slot hotbar is split into 2 4-slot rows, there are 8 squashed background tiles on each of the top and bottom.  Note that the "selected" background is the correct width though.

![screenshot_20191231_124531](https://user-images.githubusercontent.com/324806/71629481-c31c7900-2bcb-11ea-9590-e2dd9eddb9ab.png)

**Comment by paramat** [comment] 2019-12-31 19:22
Is a wrapped hotbar officially supported? Seems messy, should probably be disallowed.

**Comment by Warr1024** [comment] 2019-12-31 20:11
I would also be in favor of simply removing support for splitting/wrapping the hotbar.  Users who have screens that are really that low-density can (and probably already need to) adjust their GUI scaling settings anyway.

Removing the existing attempt to support this corner case from the engine code could also simplify things.

**Comment by Bituvo** [comment] 2024-09-28 19:09
This happened to me with the dreambuilder hotbar mod.

**Comment by rubenwardy** [comment] 2024-09-29 12:24
This is a duplicate of #3970

**Closed by rubenwardy** 2024-09-29 12:24 UTC
Labels: Bug, @ Client / Audiovisuals, Low priority, Request / Suggestion
