### ISSUE TITLE
minetest is not responding when starting the server took a long time

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#9160] opened 2019-12-01 11:07 UTC
##### Minetest version

https://github.com/minetest/minetest/commit/4b6bff46e14c6215828da5ca9ad2cb79aa517a6e

##### Summary
minetest is not responding when starting the server took a long time

##### Steps to reproduce
1. Add many mods
2. `Play Game`

**Comment by SmallJoker** [comment] 2019-12-01 11:19
Duplicate of #9096

**Closed by SmallJoker** 2019-12-01 11:19 UTC
Labels: Unconfirmed bug
