### ISSUE TITLE
Increase mapgen_limit at least up to 248000

### ISSUE THREAD

**Issue by kay27** [minetest/minetest#10257] opened 2020-08-03 13:29 UTC
Hi!

Wouldn't you please increase ```mapgen_limit``` at least 8x and make it possible to set through Lua API?

Limit of 31000 is inserious nowadays. Players need more space, and developers do as well.

Minecraft is more ancient than Minetest, but has significally greater worlds. So proprietary gives more freedom. Isn't it wrong?

I need to mention here:

+ https://github.com/minetest/minetest/issues/1608
+ https://github.com/minetest/minetest/pull/2908
+ https://github.com/minetest/minetest/issues/4428
+ https://github.com/minetest/minetest/pull/5388

Thanks in advance!

P. S. To be honest I'm here by the traces of that: https://git.minetest.land/Wuzzy/MineClone2/issues/795 But I'd like not to consider that here... it's obviously not the only reason.

**Comment by sfan5** [comment] 2020-08-03 14:07
duplicate of #8660

**Closed by sfan5** 2020-08-03 14:07 UTC
Labels: Feature request

**Comment by kay27** [comment] 2020-08-03 18:09
Thanks for the answer.

Do I understand right: it won't be done because it is fine 'as is' for single-player game mode?

https://github.com/minetest/minetest/issues/8660 doesn't contain any concrete request and closed at first glance by a controversial reason:

@SmallJoker:
> You guys never seem to get tired requesting this feature although it has been discussed so many times before.
> https://forum.minetest.net/viewtopic.php?f=5&t=20333
> https://forum.minetest.net/viewtopic.php?f=3&t=18763
> https://forum.minetest.net/viewtopic.php?f=5&t=16774

Why mixing issue tracker with forum? If you don't need the feature it doesn't automatically mean that nobody need it.

> Here's a few reasons so you're not so upset about this decision:
> 
>     * Imagine teleporting to any high number coordinate. It'll become insanely complicated

Complicated what? If you play survival mode you not supposed to use teleporting by command. If you don't want to type big coordinates having teleport privilege - nobody forces do that. How typing 1-2 additional digits might be complicated?

>     * Map has to be backwards-compatible, which is barely possible with the key size we currently use

Why? Yet another 'problem 2000'? Almost every new version of Minetest platform breaks Lua projects. It doesn't mean we need to bury Minetest and stop to improve it at all.

>     * Have you ever used the entire space to build on?

Yes.

> No, you didn't, and you'll never have the time to do that because it's simply too large already to use the entire space.

If we want to have many parallel dimensions we still need to upgrade 16-bit coordinates one day. If we want to have competitive worlds for long-term multiplayer servers we need it too.

> This madness is entirely mind-based where you're upset about these limits just because the numbers appear so small.

I know this type of philosophy - 'they all mad but not me'. It might be easily vice versa.

I didn't think it's the duplicate. I have very-well-determined minimal number instead of abstract reasoning for philosophy.

@sfan5 Would you mind telling me, if I would publish a patch would you reject it with the same reason?

**Comment by sfan5** [comment] 2020-08-04 12:11
> Almost every new version of Minetest platform breaks Lua projects. 

This isn't quite accurate.
For APIs documented in lua_api.txt there will be and are no backwards-incompatible changes. If mods no longer work on a newer version (which sometimes does happen), it's because they relied on certain behaviours/circumstances that were not guaranteed.

> @sfan5 Would you mind telling me, if I would publish a patch would you reject it with the same reason?

Aside from the fact that extending the world size is a massive change to the code and it would take you a long time to implement it, a finished PR would not change the arguments surrounding the issue.
