### ISSUE TITLE
MIDI music support

### ISSUE THREAD

**Issue by MirceaKitsune** [minetest/minetest#1409] opened 2014-06-23 12:21 UTC
Followup to a discussion on IRC and a hint on the forums. I believe Minetest should add support for midi and / or mod music. There are primarily two reasons:

Firstly, this would allow adding simple music to Minetest without increased file size. Songs in ogg format are large enough to make connecting to a server take a lot of time. Midi music is very small instead, and would make music support very cheap.

Second, it would perfectly fit Minetest's theme. Like Minecraft, we use blocky voxels and x16 textures by default, which has a nice 16-bit era feel. Midi music would add to this.

**Comment by beyondlimits** [comment] 2016-06-26 18:59
> but that adds the requirement to install a huge package containing the samples (and probably a big library too)

A some kind of FM/PM synthesizer that imitates real instruments could be implemented. I can be lightweight, and sound great (possibly even better than that dirt-quality `gm.dls` that comes with Windows).

**Comment by Fixer-007** [comment] 2016-06-26 19:24
mod, xm, it, s3m is much better for my ears

**Comment by rubenwardy** [comment] 2017-08-26 01:55
duplicate of #3878

**Comment by rubenwardy** [comment] 2017-08-26 01:56
closing as other one has better discussion, imo

**Closed by rubenwardy** 2017-08-26 01:55 UTC
Labels: @ Client / Audiovisuals, Feature request
