### ISSUE TITLE
Significant FPS drop when debug info shown

### ISSUE THREAD

**Issue by Bituvo** [minetest/minetest#14064] opened 2023-12-03 19:53 UTC
### Minetest version

4be8b77

### Active renderer

OpenGL 4.5.0

### Irrlicht device

WIN32

### Operating system and version

Windows 11

### CPU model

Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz

### GPU model

NVIDIA GeForce GT 520

### Summary

When I open the debug info (where my coordinates are), my FPS drops from ~60 to ~20. This issue did not happen on 26bb397

### Steps to reproduce

Press F5.

**Comment by wsor4035** [comment] 2023-12-03 23:45
duplicate of https://github.com/minetest/minetest/issues/13990

**Closed by wsor4035** 2023-12-03 23:45 UTC
Labels: Unconfirmed bug
