### ISSUE TITLE
Possible to drag & drop items onto forbidden lists

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#4321] opened 2016-07-15 14:39 UTC
This includes the craft preview, bones, and anything really.  For example, if you have a book in a book shelf and want to replace it with a dirt node, you have only to drag & drop the dirt onto the book.  You get the book, and the bookshelf gets the dirt.

**Comment by everamzah** [comment] 2016-07-15 14:49
I very suddenly cannot reproduce that behavior, except for the craft preview, which still accepts an item only on drag & drop.

**Comment by everamzah** [comment] 2016-07-16 17:52
Perhaps I just needed more practice.  Here is a video demonstrating:
https://youtu.be/muEHE9Voe_M

**Comment by ClobberXD** [comment] 2019-01-26 15:21
I was going to file a duplicate issue if not for GitHub's related issues feature. ;)

I came across the same issue, and the issue is that the `allow_metadata_inventory_put` callback can be completely bypassed by drag-dropping or by swapping the items by clicking on the inventory item. Only the `*_metadata_inventory_take` callbacks are run, which can do nothing about the item that goes from the player's inv. slot to the node inventory. I believe the solution to this issue is to simply run the `*_metadata_inventory_put` callbacks as well, when the player swaps items in the chest.

I'll try to fix this bug.

**Comment by paramat** [comment] 2020-03-06 22:46
A fixing PR #7372 was closed as is abandoned.

**Closed** 2020-09-04 18:49 UTC
Labels: @ Client / Audiovisuals, @ Server / Client / Env., Bug
