### ISSUE TITLE
Outrageous lag caused by a full inventory

### ISSUE THREAD

**Issue by DeltaNedas** [minetest/minetest#11305] opened 2021-06-02 12:10 UTC
##### Minetest version
```
Minetest 5.5.0-dev-debug-631636f91-dirty (Linux)
Using Irrlicht 1.9.0mt2
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Debug
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
USE_FREETYPE=1
```

##### OS / Hardware
Operating system: Debian Sid
CPU: Intel Core 2 Duo P8400 (2) @ 2.267GHz

GPU model: Intel Mobile 4 Series Chipset
OpenGL version: 3.3 Core

##### Summary
When opening an **sfinv** inventory filled with bricks, draw calls rise from about 4000/frame(!) to over 18000/frame(!!!!!!)
As a result on my worst machine, my frametimes go from about 20ms to 110ms, simply by looking at bricks.
This hints at the inventory list formspec element not putting each item inside a common vertex buffer. 12000 draw calls for a handful of half-cubes (prerendered to a single icon sprite i believe) and font glyphs is simply wrong.
Not only is item rendering sluggish, but an empty sfinv inventory takes a good bit of time to render (not nearly as bad though)
I'd say most formspecs of similar complexity are like this.

Inventory list rendering seriously needs to be batched, I'd like if someone could point me to a starting point on this matter.

##### Steps to reproduce
1. `apitrace trace minetest`
2. fill inventory with bricks
3. `qapitrace minetest.trace`
4. look for the massive spike in draw calls

Inventory:
![Screenshot_19:53:38](https://user-images.githubusercontent.com/39013340/120477084-43d43b80-c3a3-11eb-89a3-caa1ec8c4205.png)

Draw call spike:
![Screenshot_11:25:02](https://user-images.githubusercontent.com/39013340/120477203-69f9db80-c3a3-11eb-8d36-40f8ab1e199c.png)

Trace file (opened inv, closed inv, opened again at the end): 
[minetest.trace.gz](https://github.com/minetest/minetest/files/6584310/minetest.trace.gz)

**Comment by DeltaNedas** [comment] 2021-06-02 12:23
extra info relating to sfinv:
- the formspec with **no** items shown takes about 4ms, not bad
![Screenshot_13:17:29](https://user-images.githubusercontent.com/39013340/120478742-15576000-c3a5-11eb-9109-a98eb9849db5.png)

- the formspec with an empty inventory but full item list on the right is half as bad as the full inventory
![Screenshot_13:17:11](https://user-images.githubusercontent.com/39013340/120478807-24d6a900-c3a5-11eb-9bb2-d9ccee90f07f.png)

- with no items theres only about **400** draw calls for the formspec, not even close to the itemstack mess.
- empty inventory, full item list takes 11k vs 18k draw calls, so it's roughly proportional to frametime cost.

so i'm thinking that while formspecs on their own are nicely optimised, it's just the inventory list rendering that thrashes performance

**Comment by SmallJoker** [comment] 2021-06-02 12:58
Duplicate of #6905

**Closed by SmallJoker** 2021-06-02 12:58 UTC
Labels: Unconfirmed bug

**Comment by sfan5** [comment] 2021-06-02 14:17
> extra info relating to sfinv:

Not sure what you meant here, sfinv is Minetest Game's inventory implementation. What you're showing in your screenshots is unified_inventory.

**Comment by sfan5** [comment] 2021-06-02 15:14
On my system I count 24975 drawcalls with bricks and 7623 without(*), which makes a difference of ~18k.
(\*) They're still showing in the hotbar.

> This hints at the inventory list formspec element not putting each item inside a common vertex buffer.

You are correct, Items are drawn individually using this method:
https://github.com/minetest/minetest/blob/e15cae9fa0f99f597f349a7ba07d149cd91cc2d8/src/client/hud.cpp#L975-L985

> I'd like if someone could point me to a starting point on this matter.

Collecting matching meshes into one buffer shouldn't be much of a problem (translation, scaling and rotation would have to be done in software), all I can think if is using the same projection matrix for all of them might not be simple.

There is a different problem though, our GUIs are drawn progressively and not "layer-for-layer" as would be helpful. This should illustrate it nicely:
![grafik](https://user-images.githubusercontent.com/1042418/120504482-76daf700-c3c4-11eb-9d3c-bc03ddbb81b4.png)
That means you can't just batch and move item drawing to another place without also worrying about drawing backgrounds and labels in the correct order.
Fortunately this is all contained inside `hud.cpp`.

**Comment by DeltaNedas** [comment] 2021-06-02 16:55
haha yeah i mixed up sfinv and unified_inventory
will take a look at hud.cpp, maybe i can untangle backgrounds -> items -> labels
