### ISSUE TITLE
Error messages when launching a world.

### ISSUE THREAD

**Issue by COMHack20** [minetest/minetest#11296] opened 2021-05-29 10:15 UTC
##### Minetest version

```
5.1.4
```

##### OS / Hardware

Operating system: Windows 10
CPU: Intel i5-3230M 2.60Hz

GPU model: Internal
OpenGL version: (latest)

##### Summary
So, every time I launch a world, it shows these error messages. https://user-images.githubusercontent.com/79156445/120066541-be3d4c80-c07f-11eb-9e65-34ab1ff807c1.png

##### Steps to reproduce
 I don't know. Tried reinstalling.

**Comment by sfan5** [comment] 2021-05-29 10:34
duplicate of #10844

**Closed by sfan5** 2021-05-29 10:34 UTC
Labels: Unconfirmed bug
