### ISSUE TITLE
Server/client camera fighting with new player:set_physics_override

### ISSUE THREAD

**Issue by jeremyshannon** [minetest/minetest#11673] opened 2021-10-04 22:48 UTC
##### Minetest version

```
Minetest 5.4.0 - 550 development as of mid-September, haven't compiled later
```

##### OS / Hardware

Operating system: Linux x64
CPU: AMD FX 8 core

##### Summary

Exile's code uses the obsolete (1,1,1) format for set_physics_override, which generates a warning, so I moved it to use the new table format. However, on multiplayer, this causes a strange bug whereby when players sleep on half-block-high beds, the camera responds to movement by jerking violently back and forth between the previous and new look directions, until the server catches up and the view settles down.  Affected players appear to be thrashing about spastically in their beds.
 Flat beds appear to be unaffected, as does singleplayer.

##### Steps to reproduce

Enter a multiplayer server with any appreciable amount of lag, build a tech:primitive_bed, and lie down in it. Then wait a moment and turn to look in another direction. Enjoy the seizure! 
I've temporarily patched this on Land of Catastrophe by reverting to the obsolete code, but it's still in the master repository. I can re-enable it on LoC if somebody needs me to.

**Comment by sfan5** [comment] 2021-10-05 08:37
The old and new `set_physics_override` implementations use the same codepaths so it doesn't seem plausible that these would cause that issue.
Do you think it would be possible to reproduce with a minimal set of mods?

**Comment by jeremyshannon** [comment] 2021-10-10 20:22
Happens in void with a basic bed setup. Attached is a 140 line mod for void which defines a bed node and allows players to lay down and get up.

 To reproduce the bug, set up a server somewhere with noticeable lag, join it and receive a bed item, place it and right click on it, then begin moving the mouse. After a moment, you will notice the camera start to jerk back and forth. Severity depends on the amount of lag; I was able to get it to noticeable levels on my local machine by joining through my VPN from Switzerland back to California. With only minimal lag it is subtle but still faintly discernable, it looks a bit like a motion blur effect then, presumably because the back-and-forth movement is so small.

 If you uncomment the alternative nodebox definition on line 123, you'll see the bug goes away, and if you change set_physics(po) to set_physics(1,1,1) on line 84, the bug also goes away.
[testbed.zip](https://github.com/minetest/minetest/files/7318172/testbed.zip)

**Comment by jeremyshannon** [comment] 2021-10-10 22:05
Oops, you're right. I was thinking of it as "the (1,1,1) format." It should be turning off move, jump and sneak.

**Comment by sfan5** [comment] 2021-10-10 22:33
This is a duplicate of #10436.
Taking a look into debug.txt would have saved me some time because the server prints lots of these:
<pre>
2021-10-11 00:27:05: ACTION[Server]: Server: player moved too fast: V=0.599998, H=0; resetting position.
2021-10-11 00:27:05: ACTION[Server]: Server: player moved too fast: V=0.599998, H=0; resetting position.
2021-10-11 00:27:05: ACTION[Server]: Server: player moved too fast: V=0.599998, H=0; resetting position.
2021-10-11 00:27:05: ACTION[Server]: Server: player moved too fast: V=0.599998, H=0; resetting position.
</pre>

Old or new `set_physics_override` format did not make a difference in the end btw.

**Closed by sfan5** 2021-10-10 22:33 UTC
Labels: Unconfirmed bug

**Comment by jeremyshannon** [comment] 2021-10-10 22:55
>Old or new set_physics_override format did not make a difference in the end btw.

I just tried with (0,0) and (0,0,0) and it absolutely does not trigger the bug, at least not in the same way that sending a table does. The LoC server's been running for a week with (0,0, 0) and the bug has been wholly unnoticeable - the debug message sometimes appears once or twice when a player  enters the bed, but then the camera works fine. With the table method, players complain they have trouble even getting out of bed due to the camera jerking around violently. This tracks with my experience, including testing it just now.

 Sorry for filing a dupe, btw. I guess I must have typoed  my search terms. I get foggy sometimes.

**Comment by sfan5** [comment] 2021-10-10 23:03
> The LoC server's been running for a week with (0,0, 0) and the bug has been wholly unnoticeable

That is equivalent to `({speed=0, jump=0, gravity=0})` which is different from what the previous code did.
This is not down to the table format but to parameters meaning different things.

> Sorry for filing a dupe, btw. I guess I must have typoed my search terms.

It's okay. The issue I linked wasn't well named at all.

**Comment by jeremyshannon** [comment] 2021-10-10 23:10
>That is equivalent to ({speed=0, jump=0, gravity=0}) which is different from what the previous code did

Well, hey, that would do it. Thanks for your time!
