### ISSUE TITLE
Need a physics handler for mods to use to avoid conflicts when changing player physics

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#9336] opened 2020-01-23 01:59 UTC
I want to be able to set player physics without worrying about breaking other mods. I could add support for the physics handler mods out there but every mod uses a different one. It would take forever to support them all, and most of them are very different from each other, so I can't really copy and paste any code either.

In https://github.com/minetest/minetest_game/issues/1909 it looks like it was decided that it would be best to do this in the engine via C++ or lua. No issue was created here and the PR for this (#7269) was closed so here's this issue

**Comment by SmallJoker** [comment] 2020-01-23 19:53
Duplicate of #7705

**Closed** 2020-01-23 19:54 UTC
Labels: Feature request
