### ISSUE TITLE
Crash on Windows builds instead of error message

### ISSUE THREAD

**Issue by beyondlimits** [minetest/minetest#3148] opened 2015-09-05 14:19 UTC
```lua
minetest.register_on_joinplayer(function(player)
	minetest.after(5, function()
		-- no worries, we still have reference to player untouched
		minetest.chat_send_player(player, "Hello there.")
	end)
end)
```

Expect message:
`"init.lua:4: bad argument #1 to 'chat_send_player' (string expected, got userdata)"`

However:
- MSVC build crashes with message `Unknown exception (Exception 0xC0000029) at 0x7737096E`;
- MinGW build causes Windows to complain, showing "Minetest has stopped working".

Minetest 0.4.13
Windows 7 Home Premium, 32-bit

**Comment by Rui914** [comment] 2015-09-05 22:39
You can try this:
```
minetest.register_on_joinplayer(function(player)
	minetest.after(5, function()
		minetest.chat_send_player(player:get_player_name(), "Hello there.")
	end)
end)
```
The first argument is the player name.

**Comment by asl97** [comment] 2015-09-05 23:20
@Rui914 not really the problem, beyondlimits said that it **crash without showing the error**

**Comment by Rui914** [comment] 2015-09-05 23:31
I thought wrong...

Error is correctly showed on Ubuntu.

**Comment by est31** [comment] 2015-09-06 01:19
Agreed, I can see the proper error being printed, on linux. So if this is a bug, it only seems to happen on windows, right.

**Comment by gregorycu** [comment] 2015-11-08 12:02
I cannot reproduce with MSVC x64.

Can we have more detail if possible?

Are you able to check master branch now?

**Comment by PilzAdam** [comment] 2015-11-08 14:07
Maybe fixed by 9269a0ecc7267822bc5ac5af95ad4977bdc94fec ?

**Comment by gregorycu** [comment] 2015-11-08 14:51
Yes. Almost certainly. Can we close this then?

**Comment by est31** [comment] 2015-11-08 17:09
If it turns out to be still present, it can be reopened.

**Closed by est31** 2015-11-08 17:09 UTC
Labels: bug, Windows
