### ISSUE TITLE
Add sound packs

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5363] opened 2017-03-10 13:05 UTC
It is possible to replace textures with texture packs, but if you want new sounds you have to replace the default files. If sounds are scattered over mods you have to replace them everywhere

I propose to add sound packs to Minetest, similar handled like texture packs.

Instead of adding a new tab to the main menu maybe rename the texture pack tab to "Media Packs"

**Comment by rubenwardy** [comment] 2017-03-10 13:14
You can replace sounds by placing sounds into the sounds folder (you may need to create it)
But there's no concept or sound packs yet

**Comment by SmallJoker** [comment] 2017-03-10 19:00
Related issue: #4093 "Texture packs should be able to change sounds"

**Comment by MarkuBu** [comment] 2017-03-10 19:05
Not really related. I don't want combinations of texture and sound packs

**Comment by paramat** [comment] 2017-09-08 04:39
Author left MT, anyone else requesting this?

**Comment by paramat** [comment] 2017-09-15 06:55
Duplicate of #4093 as that request includes 'sound packs'.

**Closed by paramat** 2017-09-15 06:55 UTC
Labels: @ Client / Audiovisuals, Possible close, Request / Suggestion, Sounds
