### ISSUE TITLE
Content Manager Doesn't Recognize Double-nested Modpack Mods

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/minetest#11415] opened 2021-07-04 15:25 UTC
##### Minetest version

```
5.4.1
```

##### OS / Hardware

Operating system: Microsoft Windows 10
CPU: Intel x86-64

##### Summary

When my custom game (built on top of `minetest_game`) is used as the base game, content manager does not recognize that `doors` is installed.

##### Steps to reproduce

1. Open content manager & select a mod to install that depends on `doors` (such as [xdecor](https://content.minetest.net/packages/jp/xdecor/)).
2. Set base game to [Antum](https://github.com/AntumMT/game-antum).

It will claim that it needs to install `doors` even thought it is [included in the Antum game](https://github.com/AntumMT/game-antum/tree/96c6229/mods/core/minetest_game/doors).

~~Other games, such as [Farlands](https://github.com/D00Med/farlands) & [Lord of the Test](https://github.com/minetest-LOTR/Lord-of-the-Test) are not affected.~~

**Comment by rubenwardy** [comment] 2021-07-04 15:32
I suspect this may be related to the mod pack in a mod pack

**Comment by AntumDeluge** [comment] 2021-07-04 15:33
Yes, I just began to wonder the same thing as it is nested in `mods/core/minetest_game`, which it is not in Farlands. In Lord of the Test, I don't even see where the `doors` mod is installed.

**Comment by rubenwardy** [comment] 2022-05-08 03:11
Duplicate of #3363

**Closed by rubenwardy** 2022-05-08 03:11 UTC
Labels: Bug, @ Content/PkgMgr
