### ISSUE TITLE
Very slow spawn on mapgen v7(Android)

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#3483] opened 2015-12-23 17:10 UTC
I very slowly spawn using mapgen v7 on Android, and very often I appear inside of a block in the creation of the world and dying. It is very annoying.
I think it is necessary to make some kind of progress bar for the first generation (or loading map) of the world (the first entry in the game after it is created), as many perceive as a gray screen hovering game.

**Comment by paramat** [comment] 2015-12-24 11:17
Try punching, sometimes you will be inside a tree trunk. Otherwise spawning buried shows that the spawn search has failed, this can happen if you are using custom noise parameters. I will soon be improving the spawn search to make it cope with our new mapgens. You can also make spawn faster and less likely to fail if you increase this setting in .conf:

#    Maximum distance above water level for player spawn.
#    Larger values result in spawn points closer to (x = 0, z = 0).
#    Smaller values may result in a suitable spawn point not being found,
#    resulting in a spawn at (0, 0, 0) possibly buried underground.
#    type: int
# vertical_spawn_range = 16

**Comment by MoNTE48** [comment] 2015-12-24 15:26
Ok, i try it.
I remove 3-4 biomes on default/mapge.lua and 100% first spawn = dead.

**Comment by paramat** [comment] 2015-12-24 16:53
Can anyone reproduce this on Android and in default mgv7?

**Comment by MoNTE48** [comment] 2015-12-24 16:55
On android with default minetest_game in v7 i only very long spawn. Dead in 20%

**Comment by MoNTE48** [comment] 2016-01-01 08:43
https://github.com/minetest/minetest/pull/3509

**Comment by paramat** [comment] 2016-01-01 16:58
3509 won't help unfortunately.

**Comment by MoNTE48** [comment] 2016-01-01 17:23
@paramat, it's a pity.

**Comment by paramat** [comment] 2016-01-03 18:19
Can anyone reproduce this?

**Comment by Wayward1** [comment] 2016-01-03 19:07
I can confirm. Tested multiple times, I consistently die upon spawning in a new v7 world; however, I myself haven't spawned inside any blocks yet.

**Comment by MoNTE48** [comment] 2016-01-03 19:31
To be precise.
The probability of death of about 95-97%.
After the death and respawn you die again with a probability of 30%

**Comment by paramat** [comment] 2016-01-04 18:44
What is the cause of death? Spawning inside a block won't harm you. What do you see on-screen, terrain or just grey?

**Comment by MoNTE48** [comment] 2016-01-04 19:03
I see a black screen for a long time, and then the area, and after a moment I died. No, I do not spawn within blocks. Often I appear 1 unit below ground.

**Comment by Wayward1** [comment] 2016-01-13 01:57
<a href="http://pastebin.com/Pr46aLpC">Here</a> is the verbose output of the debug.txt, along with a screenshot showing exactly where this particular death occurred.
![screenshot_2016-01-12-20-39-56](https://cloud.githubusercontent.com/assets/8821916/12282805/0f986c36-b96f-11e5-955d-94b15842bc91.png)

**Comment by MoNTE48** [comment] 2016-01-13 02:00
@Wayward1 , this is not full debug! I not see dead log

**Comment by Wayward1** [comment] 2016-01-13 02:02
I know, working on it

**Comment by paramat** [comment] 2016-01-13 03:21
Weird, i am bemused, our android specialist should look at this.
What happens if you disable damage first?

**Comment by Wayward1** [comment] 2016-01-13 03:46
With damage disabled, it behaves as intended.

**Comment by MoNTE48** [comment] 2016-01-15 00:28
@sapier ^^

**Comment by 0-afflatus** [comment] 2016-02-17 05:08
This probably isn't much help but I see numerous players having trouble spawning in grailtest, which uses a fixed spawn point. I guess they are mobile users. I generally assume it is a problem with their network connection. Occasionally they hang in mid-air for some time or seem to lag out as soon as they connect.

**Comment by MoNTE48** [comment] 2016-02-23 22:38
@paramat, Just a note. I found MultiCraft 1.0 version (based on the minetest - May 1, 2015 ) there is not the problem. Player spawn very quickly and have never died.

**Comment by paramat** [comment] 2016-04-03 23:22
From the verbose debug:

2016-01-12 20:39:39: VERBOSE[Server]: ServerEnvironment::addActiveObjectRaw(): Added id=1; there are now 1 active objects.
2016-01-12 20:39:39: VERBOSE[Server]: Server: Sending TOCLIENT_MOVE_PLAYER pos=(270,150,1480) pitch=0 yaw=0
2016-01-12 20:39:39: ACTION[Server]: singleplayer [127.0.0.1] joins game. 
2016-01-12 20:39:39: ACTION[Server]: singleplayer joins game. List of players: singleplayer
2016-01-12 20:39:42: WARNING[Server]: active block modifiers took 369ms (longer than 200ms)

2016-01-12 20:39:43: WARNING[Server]: active block modifiers took 433ms (longer than 200ms)
2016-01-12 20:39:44: VERBOSE[Main]: OpenALSoundManager::maintain(): 0 playing sounds, 34 sound names loaded
2016-01-12 20:39:44: ACTION[Server]: singleplayer damaged by 84 hp at (27,15,148)

2016-01-12 20:39:47: WARNING[Server]: active block modifiers took 521ms (longer than 200ms)
2016-01-12 20:39:51: WARNING[Server]: active block modifiers took 545ms (longer than 200ms)
2016-01-12 20:39:54: WARNING[Server]: active block modifiers took 319ms (longer than 200ms)
2016-01-12 20:39:58: WARNING[Server]: active block modifiers took 466ms (longer than 200ms)

**Comment by MoNTE48** [comment] 2016-04-06 01:00
https://github.com/minetest/minetest/commit/15e1dcc020ca5c64e4b5b306529e513cb2b97bef
Fixed?

**Comment by paramat** [comment] 2016-04-06 13:52
Seems to be, is it fixed for you?

**Comment by MoNTE48** [comment] 2016-04-06 14:26
@paramat, I'm sorry, I'm away from my computer right now. I can check it only a few days.

**Comment by Wayward1** [comment] 2016-04-06 14:36
I will try to check later. @paramat, Amazon Fire HD 6 running Fire OS 5.1.1

**Comment by paramat** [comment] 2016-04-08 02:02
Well, this is the same issue, and has been reported as fixed, so closing, feel free to reopen or open a new issue if the problem is still happening.

**Closed by paramat** 2016-04-08 02:02 UTC
Labels: @ Mapgen, @ Server / Client / Env., Android
