### ISSUE TITLE
Random schematics

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5195] opened 2017-02-09 16:52 UTC
It would be nice if the mapgen could select a random schematic out of a list of schematics, similar to the random sounds.

If you want to place different schematics in the same area currently you would need to register multiple decorations. But the more decorations are placed in the same area the higher the chance that decorations are placed on each other.

With a list of decorations it would be possible to generate mixed forests with 4 or more trees or you can generate a forest with one kind of tree, but with some variations.

As option a chance would be great. Each schematic can have a chance how often this schematic will be placed. I would purpose, the higher the chance value, the lower the chance to place a schematic. This makes it easier to define rare schematics within the common once (chance = 1 could be default)

Example:

```
minetest.register_decoration({
	deco_type = "schematic",
 	place_on = {"default:dirt_with_grass"},
	sidelen = 16,
	noise_params = {
		offset = 0.01,
		scale = 0.001,
 		spread = {x = 250, y = 250, z = 250},
		seed = 2,
		octaves = 3,
		persist = 0.66
	},
	biomes = {"mixed_forest"},
	y_min = 10,
	y_max = 80,
	schematic = {
		{schem = "appletree"},
		{schem = "aspentree"},
		{schem = "pinetree"},
		{schem = "oldpinetree", chance = 10}
		}
	flags = "place_center_x, place_center_z",
})

```

**Comment by paramat** [comment] 2017-02-09 17:38
Duplicate of #4485

**Closed by paramat** 2017-02-09 17:38 UTC
Labels: @ Mapgen, Request / Suggestion
