### ISSUE TITLE
get_look_yaw, set_look_yaw, get_look_pitch, set_look_pitch unable to use same values as input/output

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#2658] opened 2015-04-30 07:26 UTC
With the player object, one would expect that if one uses the output of getpos() and used it to setpos(), that the player remains in the same location. Yes?

Ok, now do player:get_look_yaw() and get_look_pitch(), and put those values back into player:set_look_yaw and set_look_pitch().

Surprise, you are now looking left i90, and down instead of up.

This makes zero sense API wise. Now mods have to do:

yaw = player:get_look_yaw() - (math.pi / 2)
pitch = 0 - player:get_look_pitch()

player:set_look_yaw(yaw)
player:set_look_pitch(pitch)

That can't be right :(

**Comment by Etzos** [comment] 2015-05-01 03:54
I've been looking into this, and I'm wondering what values exactly are *intended* to be returned by `get_look_yaw()` and `get_look_pitch()`.

I'm assuming that `get_look_yaw()` is supposed to return 0-6.3 or so with 0 being north.
However, I'm not sure what `get_look_pitch()` should be returning. Currently it's 0 looking ahead, negative looking down and positive looking up, however was it originally intended to be 0 looking down and just increasingly positive as you look up more? Based on what those are supposed to return the setting functions can be set to compensate.

**Comment by sofar** [comment] 2015-05-01 04:33
That just complicates it even further :)

**Comment by Wuzzy2** [comment] 2015-06-02 05:29
I noticed this, too. It is a really confusing and weird. It looks like a bug.
The problem is that the setter and getter functions are out of sync. What is worse is that nothing of this behavior is documented.

`set_look_yaw` seems to be consistent with the debug output mode (what “yaw” says), but `get_look_yaw` is off by approximately pi/2. So IMO it is `get_look_yaw` that needs to be changed.
And IMO `get_look_yaw` only should return values in the interval [0,2*pi).

I am unsure what to say about the pitch functions, because I don't understand the value range.

Also, the documentation of all those 4 functions is terrible by the way:

```
* `get_look_pitch()`: pitch in radians
* `get_look_yaw()`: yaw in radians (wraps around pretty randomly as of now)
* `set_look_pitch(radians)`: sets look pitch
* `set_look_yaw(radians)`: sets look yaw
```

The problem is that the precise value ranges are not mentioned here. It is also not stated whether you are allowed to wrap around (values < 0 or > 2*math.pi). The reference points (value `0`) are also missing.

Oh, and I think “(wraps around pretty randomly as of now)” speaks for itself … xD


Fixing this stuff would certainly break all mods which read or change the yaw and pitch of players. But I think it is still worth fixing, but this change needs to be communicated loudly, of course.

**Comment by MirceaKitsune** [comment] 2015-07-01 11:39
I agree that this is a problem. Last night I added code to one of my mods which sets an entity's rotation to that of a player. I was surprised to notice that getyaw and get_look_yaw return different values and the rotation was 90* higher, so I spent several minutes trying to offset it manually and correct the problem. I then saw this thread and added "- (math.pi / 2)" as suggested, which just got it working properly. I agree this is confusing and really should be changed!

**Comment by beyondlimits** [comment] 2015-07-05 17:01
2 months have passed since this issue and prior to writing this comment it is not fixed! Many of issues like this are getting covered by new ones and when this is finally found, we can't fix it because we have to keep backward compatibility with mods which were accustomed to this behavior.

The problem seems to be here: https://github.com/minetest/minetest/blob/master/src/player.h#L192

**Comment by sofar** [comment] 2015-07-07 04:17
Or fix it in a forward compatible way, where the old set_look_yaw/get_look_yaw remain broken and marked obsolete, and fixed versions have a different function name.

**Comment by obneq** [comment] 2016-06-17 07:43
> ...we can't fix it because we have to keep backward compatibility with mods which were accustomed to this behavior.

this is a sad state and bad reason for not fixing stuff. lets just fix stuff so it can be done right in the future. i for one am tired of people noticing how stupid something is in minetest and the answer is yeah, thats how we do stuff here.

**Comment by paramat** [comment] 2016-06-24 01:23
4229 is merged.

**Closed by paramat** 2016-06-24 01:23 UTC
Labels: Bug
