### ISSUE TITLE
Fix dotfiles

### ISSUE THREAD

**Issue by SoniEx2** [minetest/minetest#8151] opened 2019-01-31 22:48 UTC
##### Issue type
 - Bug report
 
##### Minetest version

```

```

##### OS / Hardware

Operating system:
CPU:

GPU model:
OpenGL version:

##### Summary
Minetest should follow XDG Base Directory, either by default or with a *documented* environment variable. This way, it can be listed on, for example, archlinux's XDG Base Directory Support page as either "supported" or "partial", which indicates the minetest team actually cares about standards and user-friendliness.

The biggest benefit of XDG Base Directory is the ability to trivially move all configs and data around. Programs that don't follow it make this task non-trivial. I for example keep my configs on a failing drive and my data on a RAID mirroring setup, but with minetest, it's impossible.

##### Steps to reproduce

1. Use minetest on linux

**Comment by Calinou** [comment] 2019-01-31 23:38
This was already requested in https://github.com/minetest/minetest/issues/5217, https://github.com/minetest/minetest/issues/864 and https://github.com/minetest/minetest/issues/395 but it was rejected.

I would personally support moving to XDG, but it might not be easy to convince everyone. Perhaps it's easier if one opens on a pull request implementing this (with migration code for supporting upgrades from an older version).

**Comment by Linuxdirk** [comment] 2019-02-01 15:10
> I would personally support moving to XDG, but it might not be easy to convince everyone

I wonder how people can be against XDG ... There is no real reason behind not supporting it. It would actually being enough having `.minetest` moved to `$XDG_CONFIG_HOME/minetest`.

**Comment by Calinou** [comment] 2019-02-01 15:23
> It would actually being enough having .minetest moved to $XDG_CONFIG_HOME/minetest.

Actually, that doesn't follow the XDG Base Directory specification. For Minetest, it would mandate that:

- user data like mods and worlds should go to `$XDG_DATA_HOME/minetest` (falling back to `$HOME/.local/share/minetest` if the variable isn't set)
- configuration files (mainly `minetest.conf`) should go to `$XDG_CONFIG_HOME/minetest` (falling back to `$HOME/.config/minetest` if the variable isn't set)
- cache/temporary files should go to `$XDG_CACHE_HOME` (falling back to `$HOME/.cache/minetest` if the variable isn't set)

**Comment by SoniEx2** [comment] 2019-02-01 15:34
Actually, I'd argue mods are a special kind of configuration file, and should go in `$XDG_CONFIG_HOME`.

**Comment by paramat** [comment] 2019-02-01 17:32
> perhaps it would be easier if one opens on a pull request implementing this

Not a good idea if XDG is disapproved, get approval first to not waste your time.
This isn't a bug.

**Comment by prozacgod** [comment] 2019-02-02 21:55
It is a bit paradoxical.  It's been my experience as well.  I think it's because code can tell the story of what is going to happen better than a conversation about that code.  It forces you to think about edge cases and how to deal with them, and then present your process for critique, often when people see an implementation, esp. one that "just works™" there's little to criticise and acceptance is a given.

**Comment by eli-schwartz** [comment] 2019-02-04 00:16
> Supporting the XDG Base Directory specification _is_ actually more work than their Windows/macOS counterparts, which typically do not have a separation between user data and configuration directories.

This is factually incorrect. Failure to follow the XDG Base Directory specification **or its OS-specific adaptations** results in software which is just as broken on macOS **and** Windows as it is on Linux.

On macOS, `XDG_CONFIG_HOME` maps to `~/Library/Preferences/`, `XDG_DATA_HOME` maps to `~/Library/Application Support/`, and `XDG_DATA_HOME` maps to `~/Library/Caches/`.

On Windows, `XDG_CONFIG_HOME` and `XDG_DATA_HOME` are not separated, as both are in `%APPDATA%`, but `XDG_CACHE_HOME` must be in `%LOCALAPPDATA%` to prevent roaming across network shares (it does not specify when you can clean it up though).

Linux of course provides separate directories for all three (just like macOS), and goes even further by allowing them to be relocated via environment variables. But I hardly see why the lack of cross-platform support for overriding `XDG_*` should cast doubt on the usefulness of a program intelligently deciding where to put files according to the well-documented, preferred OS-specific locations.

I do know it is very common for people who dislike the **work** that it involves, to make up stories about how XDG is some weird ridiculous foolish Linux thing and no one other than weird Linux people should care. Which makes this discussion bizarre when the rationale for "don't do it -- it doesn't work on Windows" is coming from a Linux user! o_O

**Comment by SpaghettiToastBook** [comment] 2019-02-05 10:31
Is there any good reason not to do this?

**Comment by paramat** [comment] 2019-04-27 02:20
Absence of a reason to not do this is not a reason to do it.
> This way, it can be listed on, for example, archlinux's XDG Base Directory Support page as either "supported" or "partial", which indicates the minetest team actually cares about standards and user-friendliness.

Obviously we currently don't ;)

The previous requests were rejected so closing.

**Closed by paramat** 2019-04-27 02:20 UTC
Labels: Controversial, Not a bug, Request / Suggestion

**Comment by SoniEx2** [comment] 2019-04-27 09:36
> The biggest benefit of XDG Base Directory is the ability to trivially move all configs and data around. Programs that don't follow it make this task non-trivial. I for example keep my configs on a failing drive and my data on a RAID mirroring setup, but with minetest, it's impossible.

Sorry that this isn't a reason to do it, I guess, even tho it is.

**Comment by Linuxdirk** [comment] 2019-04-27 14:10
@paramat Since you added “duplicate” please link to the existing issue being about the same thing.

**Comment by ClobberXD** [comment] 2019-04-27 14:11
@Linuxdirk https://github.com/minetest/minetest/issues/8151#issuecomment-459549126

**Comment by benrob0329** [comment] 2019-04-27 17:07
I would like to ask why this was rejected as "Won't add", when the only dev who has stated to be against it is @paramat, with one even commenting that he was for it.

Using standard data directories is simply sane behavior for any modern application, it makes backups easy, people often know where to look, it doesn't add extra directories to the base of my home folder, and its following standard application etiquette.

No real reasons were given not to add this, and several reason have been given from the start to add this.

**Comment by rubenwardy** [comment] 2019-04-27 18:42
It's a duplicate of https://github.com/minetest/minetest/issues/864

**Comment by paramat** [comment] 2019-04-27 21:07
benrob0329 the answer was in the post before yours https://github.com/minetest/minetest/issues/8151#issuecomment-487289266 and earlier in the thread https://github.com/minetest/minetest/issues/8151#issuecomment-459549126
