### ISSUE TITLE
Huge FPS drop on Intel GMA X4500 on Windows with shaders enabled

### ISSUE THREAD

**Issue by AbduSharif** [minetest/minetest#15473] opened 2024-11-23 15:05 UTC
### Luanti version

```true
Happens on latest stable and development versions.
```

### Operating system and version

Windows 10, Linux (With Mesa's drivers) isn't as affected as far as I remember from the last time trying with shaders enabled (I'll have to re-install to re-confirm/take a screenshot).

### GPU model

Intel GMA X4500

### Active renderer

OpenGL 2.1

### Summary

Shaders disabled:

![Before](https://github.com/user-attachments/assets/ba6582d4-7e0d-43c2-baf0-e722894edfca)

Enabled:

![After](https://github.com/user-attachments/assets/b40f75f8-c4e0-481c-a989-17367c97151e)

No, this game is perfectly playable on this IGPU, and with how configurable it is I can get more performance wether Windowed or Fullscreen...etc, normally it only ever dips under 20 FPS if its a heavily forested area.

Shared config settings:

,,,
mainmenu_last_selected_world = 3
enable_damage = false
server_announce = false
creative_mode = false
menu_last_game = minetest
show_advanced = true
autojump = true
viewing_range = 60
mip_map = true
enable_fog = false
,,,

This is not a hardware problem, this IGPU is perfectly capable of running more demaning games than this and they don't dip under 20 FPS, so condescending responses are not helpful.

I'll report progress with new updates or possible optimzations that may come to Minetest down the line or if I find a workaround.

### Steps to reproduce

Disabled shaders vs Enabled shaders with post processing disabled.

**Comment by SmallJoker** [comment] 2024-11-23 15:13
Duplicate of #15433

**Closed** 2024-11-23 15:13 UTC
Labels: Unconfirmed bug

**Comment by AbduSharif** [comment] 2024-11-26 20:43
Luanti version: 5.10.0

Irrlicht device: X11

Operating system and version: Xubuntu 24.10

Shaders enabled:
![linux_shaders](https://github.com/user-attachments/assets/8ab18152-dd55-4211-96a7-302581ca9873)

Undersampling actully lessens the impact unlike on Windows:
![linux_shaders_undersampling](https://github.com/user-attachments/assets/b3f5c553-e3f3-4751-8104-69ba5ece45df)

**Comment by AbduSharif** [comment] 2024-11-26 20:47
I didn't test (on Linux) with the dev builds yet, or do extensive testing of the upcoming optimizations yet, I'm planning on waiting for a while.

**Comment by AbduSharif** [comment] 2024-11-26 21:03
Note that are RTT time spent is infact not always at 2 or 3 but 1ms, most of the time, just reopning the world fixes that.

**Comment by AbduSharif** [comment] 2024-11-26 21:17
Note that while shaders are enabled performance (without using undersampling) can obviously go above 36 FPS (unlike what the above screenshot suggests), and it doesn't drop under 20 FPS unlike again you're in a heavily forested area, not if you use simple leaves style though (it will stay above 20 FPS in a jungle).

**Comment by AbduSharif** [comment] 2024-11-26 21:21
So long story short, Minetest is playable with this IGPU with shaders enabled on Linux, and making use of the game's configuration and your system's optimzations is useful. (I didn't even mess with any Mesa settings or game optimzation stuff or Mintest settings I didn't mention here whwn testing on Linux).

**Comment by AbduSharif** [comment] 2024-11-26 22:16
For reasearch purposes :), Minetest's Windows version on Wine also runs better on Linux, using the Mesa OpenGL Thread enviroment Variable obviously helps.

**Comment by AbduSharif** [comment] 2024-12-04 20:46
I recommend disabling compositing (on Linux, wether Fullscreen or not) when playing Minetest, you may gain a lot of FPS back, at least in the scene above with shaders enabled it increases to 45 FPS.
