### ISSUE TITLE
Flying dungeons

### ISSUE THREAD

**Issue by RealBadAngel** [minetest/minetest#2926] opened 2015-07-18 01:13 UTC
hmmm is not willing to fix that, whos gonna fix that?

**Comment by paramat** [comment] 2015-07-18 04:45
Some players love these, some do not, so i made them optional a while ago:
https://github.com/minetest/minetest/commit/ffdf8dedb74e59e39a2686a0d7da3740f4f3b2a1
https://github.com/minetest/minetest/blob/master/minetest.conf.example#L517

**Comment by est31** [comment] 2015-07-18 05:12
That option should be default off IMO.

**Comment by est31** [comment] 2015-07-18 18:24
I still think they should be default off.

**Comment by paramat** [comment] 2015-07-18 20:48
Perhaps i should have replied, it's a sensitive subject =) We had a big argument, eventually i agreed to make them optional but enabled by default for good reasons: over the years they have become a much loved, magickal and essential part of Minetest's character. If disabled players would never discover them, and many players love them. If enabled a player can then decide to disable.

But of course it's right to make them optional, some players do not appreciate them and they are unsuitable for some mods or subgames.
The setting doesn't oonlt control the floating stone rings, it also disables the complete dungeon rooms that project out of the terrain, and complete dungeons that float above the terrain, these are rare and make the most stunning bases when renovated.

![screenshot_1040956574](https://cloud.githubusercontent.com/assets/3686677/8763485/f285b302-2d95-11e5-94ba-e95125d20253.png)

Support pillars can be added if wanted, however Minetest has floating islands so floating dungeon ruins seem appropriate.

**Comment by est31** [comment] 2015-07-18 21:08
We do have floating islands? In default setup?
If we had support pillars, I would agree to it being default on, its great to have things spawn seldomly. Also, perhaps we should improve how these dungeons are "griefed", so that its not removing too much (regarding those rings). Then I think this bug is fixed.

**Comment by kilbith** [comment] 2015-07-18 21:09
I prefer disabled by default too. Why ?
- (Mossy-)cobblestone is normally an element deteriorating in underground.
- The basic shape of the structure allows to interpret that some ancient builders had to drill the surrounding stone. Architecturally, this definitely belongs as underground part.
- The mapgens (especially v5/v7) are crazy enough, and those floating structures looks messy in the virginity of the landscapes.

**Comment by RealBadAngel** [comment] 2015-07-19 00:15
![screenshot_20150719_021323](https://cloud.githubusercontent.com/assets/2177790/8764030/0032c38e-2dbc-11e5-8824-36287a93421b.png)

**Comment by paramat** [comment] 2015-07-19 00:50
Mgv6 has rare floating stone, mgv5/mgv7 have a lot of floating islands.
Because the rings have become more common recently i'm becoming more neutral about them, but would still feel bad about removing a characteristic of Minetest. Perhaps i'll see if i can find the cause of the rings, it may be possible to remove them but keep the projecting dungeons.

**Comment by Zeno-** [comment] 2015-07-19 04:12
I think we need to be careful about becoming attached to bugs and glitches, and giving them attributes such as "a characteristic of Minetest". It's a slippery slope

**Comment by paramat** [comment] 2015-07-19 18:46
> if something is "a characteristic of" or "desirable" then it should not be the side effect of a bug.

It's totally possible for a bug to result in something desirable, in art many wonderful things are results of mistakes the artist had the good sense to leave in. Fixing the bug and re-implementing the result, if possible, usually ends up in something different and rather stale, losing the original magic.

The rings are probably due to some harmless error in the use of voxelmanip indexes, i will try to find the cause, it's very unlikely there are harmful side effects with voxelmanip errors, but yes it's best to understand why these happen so we can be sure. If it's harmless then it's always best to preserve a desirable bug.

Because these rings are more common now, and i see so many when working on mapgen and flying fast, they are losing their charm for me, and i assume this will slowly happen for others too.
So here's my intention and offer of a compromise: i will try to find the cause of the rings and remove them, i can then leave 'projecting' dungeons enabled as these are much more rare and much more desirable.

**Comment by Zeno-** [comment] 2015-07-20 13:43
@paramat the key words you used are "probably due to some harmless error". Since you do not know what the error is I cannot be confident that it's harmless. Added High Priority tag. Fuck the charm and fix the bug.

**Comment by paramat** [comment] 2015-07-20 18:50
Something that has been a part of Minetest from the beginning is not high priorirty, you're just raging now =) I'm think i know what the cause is, it's to do with voxelmanip indexes and exceeding the full extent of the voxelmanip, this is indeed harmless, it only results in rings and nothing else. I have a lot of experience with the voxelmanip and indexes and have had this happen to me in my lua mapgens.

> If it's harmless then it's always best to preserve a desirable bug

Hmm well perhaps not always, sometimes. I'm describing the difference between a true artisitc approach and a cold mechanical one. If the rings are indeed harmless as i suspect, they really have no other effect, and their generation would probably be slower, different and have less character if re-implemented intentionally. Anyway this won't happen, i have already said i will try to remove them so there's no need to order me to do it.

**Comment by Zeno-** [comment] 2015-07-21 05:58
I wasn't ordering you. I was taking a stance that I think that something that is unexplainable cannot be said to be harmless. Perhaps my words were a bit strong and if so I apologise, but I do feel strongly about the essence of what I said.

**Comment by C1ffisme** [comment] 2015-07-21 18:42
You know, maybe Zeno- is right.

Why not add a setting called ```lovable_characteristics```? That way any accidents of mapgen or bugs that make minetest be minetest for some people and are bugs for others can be switched on and off. Then everybody's happy.

**Comment by RealBadAngel** [comment] 2015-07-23 02:41
maybe lovable_bugs = enable/disable ? :)

**Comment by paramat** [comment] 2015-07-24 20:05
That's cool Zeno, sorry i overreacted. I intend to get these rings removed for next release.

**Comment by paramat** [comment] 2015-08-07 11:53
I stared at the code for an hour or two and  it's not as obvious as i thought, i have no idea so far.
The rings are removed when 'enable floating dungeons = false' so we know they are generating in the ignore nodes of a neighbouring ungenerated mapchunk. They always appear flat against the mapchunk border and are slices of dungeon 1 node thick. In the case of mgv5/mgv7 which overgenerate each mapchunk up and down by 1 node vertically the horizontal rings appear at y = 49 instead of y = 48, so just above the overgenerated surface mapchunk that extends from y = -31 to y = 48.

**Comment by paramat** [comment] 2015-08-15 23:07
![screenshot_20150815_234403](https://cloud.githubusercontent.com/assets/3686677/9291128/b4e41b56-43a7-11e5-9d38-1526006d52e9.png)

A rare double ring wrapped around the mapchunk edge and flat against the mapchunk surface.
What's weird is that if this is slices of a large room the middle crossbar shouldn't be there, if these are the walls of a room they should be solid, not frames. This behaviour is seen in other examples too:

![screenshot_20150423_042211](https://cloud.githubusercontent.com/assets/3686677/9291197/70663f6a-43aa-11e5-8171-be1f07b22451.png)

Large rooms that intersect the mapchunk border seem to create a ring or arch structure if in air or water, but the wall is present within the frame if replacing solid nodes.

**Comment by C1ffisme** [comment] 2015-08-15 23:49
That double ring is cool...

**Comment by paramat** [comment] 2015-08-28 02:11
It seems the frames are actually end walls/floors/ceilings of dungeon rooms, that should be solid but appear as frames. By making complete dungeons appear i confirmed the double ring above is the ceiling and wall of a large room. The rings seem to be created when a wall/ceiliing/floor is just outside and flat against a mapchunk border.
I suspect the rings are only formed by the first room created in a dungeon, and there are some errors in the code concerning the first room, so i am now testing with these errors corrected to see the result. The double ring is removed but i need to see if protruding/complete dungeons remain.

**Comment by paramat** [comment] 2015-08-29 05:33
Hopefully now fixed, see #3118

**Closed by paramat** 2015-08-29 05:33 UTC
Labels: @ Mapgen, bug
