### ISSUE TITLE
arm issue, block placing issues

### ISSUE THREAD

**Issue by LikeGuyS** [minetest/minetest#12223] opened 2022-04-25 16:30 UTC
##### Minetest version

```
5.5.0
```

##### OS / Hardware

Operating system: Android 9
CPU: Exynos 8895

GPU model: Mali-G71 MP20
OpenGL version: OpenGL ES 3.2

##### Summary
Issue A: The arm of the player looks abnormal when it moves, as if detached of the player's body (First Person View). As seen in [this video,](https://user-images.githubusercontent.com/104377424/165132166-9cc25ff9-6d12-48b1-b725-b95f093b4c6f.mp4) the player can clearly see the bottom of the arm of the character.

Issue B: There seems to be some form of general inability to place blocks, even though you're fairly near to the location you're trying to place them in. https://youtu.be/oQUppljeOYg 

Issue C: When switching to home screen then back to the game, sometimes, a big blue gradient takes over half of the screen from the bottom of the sky.

Issue D: When leaving the game abnormally(hit home button then closing the game from apps manager) any settings you had changed will be reverted.

**Comment by rollerozxa** [comment] 2022-04-25 20:46
Issue A is not a bug with the engine but the hand of the game you're playing (MTG). Issue B is a lack of control scheme options rather than a bug (see #2761).

**Comment by LikeGuyS** [comment] 2022-04-26 17:42
> Issue A is not a bug with the engine but the hand of the game you're playing (MTG). Issue B is a lack of control scheme options rather than a bug (see #2761).

The issue with the hand is that it looks detached from the body. For comparison, check minecraft's First Person View's hand. Intact and doesn't detach from the bottom.

For issue B, tapping twice to place a block shouldn't be the default, but rather tapping just once, as many players are used to the tap-once to place blocks.

**Comment by Zughy** [comment] 2022-05-08 23:29
Hello, thank you for the issue. Since A is not an issue and B is a duplicate, please open two different issues about C and D, to help us keep things in order. Closing here

**Closed by Zughy** 2022-05-08 23:29 UTC
Labels: Unconfirmed bug, Android
