### ISSUE TITLE
Keybinds in formspec

### ISSUE THREAD

**Issue by MineWitherMC** [minetest/minetest#7451] opened 2018-06-15 08:28 UTC
Probably it is duplicate, however, I couldn't find the 1st issue, so I'm posting this here.

##### Issue type
 - Feature request

##### Summary
Currently, we can catch `key_up` and `key_down` presses in forms. It would be nice to catch other keys. Also a way to catch right-clicks and probably mousewheel would be useful.

##### Usage
* Using Shift in advanced, button-driven crafting table
* I have a research book mod which is scrollable using `key_up` and `key_down`. Adding `key_left` and `key_right` would be incredibly useful
* Something like NEI (think of Unified Inventory) where you can press `R` when hovering over item to view its recipes - will also require a way to get cursor coordinates which is probably a bit more difficult than the two first "trivial" examples
* Search on input, without having to press enter/button

**Comment by SmallJoker** [comment] 2018-06-15 10:42
Similar to #7238 where it's about a callback for mouse down & shift pressed. What you're requesting is the level below it: register any key presses (including mouse).
IMO it should be limited the regular keys for navigation in drop-down lists and writeable text areas. Formspecs can get too difficult to use with many different options - same reason why #7238 was closed.
However, I wonder how you got the keys to work since #6353 states that it's currently broken.

**Comment by MineWitherMC** [comment] 2018-06-15 10:45
Presses of `key_up` and `key_down` are actually passed to `on_receive_fields` (because of scrollbars IIRC). Strange enough, but `key_left` and `key_right` aren't.

**Comment by SmallJoker** [comment] 2018-06-15 10:56
`key_up` and `key_down` are used to trigger updates when another item is selected in a table or in a dropdown menu. Using them outside of these formspec elements is surely not why these fields were added, also because these fields are nowhere documented. (neither is `quit`)

**Comment by sorcerykid** [comment] 2018-07-30 10:43
It seems like this would be better suited for when formspecs support [dynamic elements](https://forum.minetest.net/viewtopic.php?p=305630#p305630). Right now with all elements being static, it requires resending the formspec in its entirety with every change.

If a list were populated in response to a user-typing into a text field (a-la Google search), that could prove very inefficient. I imagine the network latency for some clients would make it virtually unusable (add to the fact, I believe the field focus would be lost).

However, I really LOVE like the idea of passing key-states during _existing_ events, maybe as a fourth argument to the on_player_receive_fields( ) callback. This would permit secondary actions for buttons, drop-downs, textlists, etc. And I suspect it would be easier to implement as well. Just some thoughts.

**Comment by rubenwardy** [comment] 2018-07-30 10:45
You can capture textural key events by using an invisible text field - ie: size being (0,0) - however it'll only submit when there is an event, and you can't use it with any other fields

**Comment by sorcerykid** [comment] 2018-07-30 10:50
Ah, I didn't realize that. Undocumented feature apparently :)

But does that provide information of keys being pressed specifically at the time of the event, or is it just logging all the keystrokes during the lifetime of the formspec?

**Comment by rubenwardy** [comment] 2018-07-30 10:51
The latter, unfortunately

**Comment by paramat** [comment] 2019-09-02 23:08
@SmallJoker @rubenwardy do you support this request? I can't tell.

**Comment by rubenwardy** [comment] 2020-05-06 09:24
Duplicate of #6768

**Closed by rubenwardy** 2020-05-06 09:24 UTC
Labels: @ Client / Controls / Input, @ Script API, Feature request, Formspec
