### ISSUE TITLE
UI is fixed to bottom left at 1/4 size

### ISSUE THREAD

**Issue by jasikpark** [minetest/minetest#10855] opened 2021-01-23 04:25 UTC
##### Minetest version

```
5.3.0
```

##### OS / Hardware

Operating system: macOS 11.1
CPU: Intel i5

GPU model: 
OpenGL version:

##### Summary

When initially opening the game, the menu UI is rendered in the bottom left at 1/4 size. At first I was really confused (I still am), but I figured out that the mouse input was being rendered normally - you can see it in the video.

https://user-images.githubusercontent.com/10626596/105568663-c3b90d80-5d00-11eb-8e38-e2ee1d73c394.mov

##### Steps to reproduce

Launch the game that was installed via `brew install minetest`

**Comment by rubenwardy** [comment] 2021-01-23 04:27
Duplicate of #10654

**Closed by rubenwardy** 2021-01-23 04:27 UTC
Labels: Unconfirmed bug
