### ISSUE TITLE
Areas where there are a lot of caves and tunnels underground harm FPS (improve occlusion culling)

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#4553] opened 2016-09-27 01:48 UTC
Hi everyone. I believe this is a bug know by some people already and I was surprised to see that yet nobody had reported it.

Basically, in areas where we have a complex network of tunnels underground for example, the client will experience a huge framerate drop.

On my own server for instance, at spawn the FPS can get as low as 6 FPS whereas around 100 nodes away from spawn, in areas that don't have underground tunnels but do have buildings, signs and homedecor the FPS can reach 30+ FPS.

I believe this might be caused partially by the way the engine works, making a block full of caves heavier to render than one without. But I don't understand why. I wonder if there is any fix or work around for this issue.

**Comment by paramat** [comment] 2016-09-27 12:20
There's a related issue somewhere, the caves are not actually occlusion culled.

**Comment by Megaf** [comment] 2016-09-28 12:23
@paramat This? https://github.com/minetest/minetest/issues/2307

**Comment by paramat** [comment] 2016-09-28 14:32
No it's to do with how MT does occlusion culling, i think someone rendered everything as wireframe and saw that caves were still present, it might be in a PR.

**Comment by Fixer-007** [comment] 2016-09-28 19:08
Those are probably within the same mapblock (16*16*16), culling works on mapblock level iirc.

**Comment by Megaf** [comment] 2016-09-29 00:30
> ￼ paramat added the Non-trivial label 9 hours ago

Oh no, not that label!
So, could maybe reducing the size of mapblock be a workaround? (On new servers, since we can't change that after the world was created).

**Comment by paramat** [comment] 2016-09-29 01:50
We can't change mapblock size, it's so fundamental.
The proper fix is to rewrite how MT does occlusion culling, a big job that may never be done.
Much of this issue may be due to low-power hardware you may be using. Forests have complex meshes too that must have a similar effect, but are not so easy to cull.

**Comment by paramat** [comment] 2016-09-29 17:05
I'm not even sure that culling can be improved, i can't remember the last discussion.

**Comment by rubenwardy** [comment] 2016-09-30 21:56
I remember reading an article about how someone decided how to cull caves in a voxel environment, but I forget the link name. It's was posted on the forum ages ago

**Comment by Megaf** [comment] 2016-10-01 22:43
@rubenwardy This? https://forum.minetest.net/viewtopic.php?f=7&t=10156

**Comment by rubenwardy** [comment] 2016-10-02 01:04
That's it

**Comment by Fixer-007** [comment] 2016-10-29 16:21
done by minecraft portable edition developers...

**Comment by paramat** [comment] 2016-10-29 16:41
That method may improve culling eficiency, but at what cost? it has to do flood fills for every mapblock.

**Comment by Fixer-007** [comment] 2016-11-04 21:41
This may improve the situation: https://github.com/minetest/minetest/pull/4724

**Comment by lhofhansl** [comment] 2016-11-04 22:27
Oh yeah in caves it should reduce the number of blocks fetched from the server from d^3 = 8*r^3 to 4/3*pi*r^3 ~ 4.2*r^3 (so almost by 2)... Plus the culling improvements it does.
(I need to validate these number experimentally)

**Comment by Megaf** [comment] 2017-09-24 10:19
Folks, any new update on solving this?
@paramat @rubenwardy @est31

**Comment by paramat** [comment] 2017-09-24 11:57
@lhofhansl has made culling improvements and is still thinking about further ones, see his PRs and issues.
What's your experience with 0.4.16 or latest code? Perhaps it's possible your low FPS at spawn is partly due to other aspects like signs or whatever.

**Comment by paramat** [comment] 2017-09-24 12:50
I think this issue is out of date because we have had some changes to occlusion culling, please do some new tests, especially with no mods to rule out other effects, and using wireframe mode.

A vague request for better occlusion culling performance is not really worth an issue, we are always trying to improve it, but if you find something that seems unexpected that is useful as an issue.

**Comment by Megaf** [comment] 2017-09-26 01:16
@paramat Just tested .14 vs .16.
Using system GMP and LuaJIT and Irrlicht downloaded from their websites.
Not FPS difference at all at my servers spawn.
20 FPS at spawn. Spikes of 200 FPS elsewhere.

**Comment by raymoo** [comment] 2017-09-26 01:49
@Megaf Have you checked in wireframe mode how many tunnels have been culled? If it's at spawn, the lag could be caused by other things since players will place a lot of things there.

**Comment by lhofhansl** [comment] 2017-09-26 07:05
The server side occlusion culling I added would not help with this - it would only reduce the number of blocks that the server needs to send. Before the change the client would occlude these blocks away, now the server does not send them.

Can you look at the output of F6 and report the "blocks in range"? I'd be curious how big that number is on your case.

**Comment by lhofhansl** [comment] 2017-09-26 07:13
I had some attempt to improve the _accuracy_ of occlusion culling (which be used both server and client side), but that had cause a bunch of side-effects.

Minecraft uses a version of flood-filling rather than the ray-tracing type approach we're using here. The flood filling can be perfectly accurate, but it needs pretty sophisticated caching or it will be too slow.

**Comment by paramat** [comment] 2017-09-26 13:51
> Not FPS difference at all at my servers spawn.
20 FPS at spawn. Spikes of 200 FPS elsewhere.

Ok, but as i explained this doesn't mean much, the low FPS could be due to other causes. If there is any bug in occlusion culling you need to test more carefully by disabling all mods to rule out other effects.

> Basically, in areas where we have a complex network of tunnels underground for example, the client will experience a huge framerate drop.
I believe this might be caused partially by the way the engine works, making a block full of caves heavier to render than one without. But I don't understand why. I wonder if there is any fix or work around for this issue.

Essentially this is expected, there is no evidence of a bug, and there is no fix or workaround apart from ongoing efforts to improve occlusion culling.

So until there is evidence of a bug, an issue for 'better performance' is somewhat pointless.
Do comment here if something strange does arise and we can reopen it.

**Closed by paramat** 2017-09-26 13:51 UTC
Labels: @ Client / Audiovisuals, Non-trivial, Performance, Request / Suggestion

**Comment by HybridDog** [comment] 2017-09-26 14:00
What's the occlusion culling mechanism in Terasology?

**Comment by raymoo** [comment] 2017-09-26 17:11
@HybridDog Maybe it would be better to ask the Terasology community?

**Comment by HybridDog** [comment] 2017-09-27 16:45
How about this: https://publikationen.uni-tuebingen.de/xmlui/bitstream/handle/10900/48886/pdf/dissertation.pdf?sequence=1

**Comment by raymoo** [comment] 2017-09-27 17:45
Probably better to use a voxel-specific algorithm such as https://procworld.blogspot.com/2015/08/voxel-occlusion.html
