### ISSUE TITLE
Decoration bug at y=47/48 in Valleys mapgen

### ISSUE THREAD

**Issue by vlapsley** [minetest/minetest#5125] opened 2017-01-28 10:34 UTC
In valleys mapgen, decorations using _minetest.register_decoration_ don't always get placed at y=47/48. See screenshot.

<img width="1680" alt="decoration_bug" src="https://cloud.githubusercontent.com/assets/8357901/22395907/c6346276-e59f-11e6-8c9e-915d19d584f2.png">

I have created a simple biome and decoration mod for vanilla Minetest_Game showing this bug I have in Valleys mapgen.

```
minetest.clear_registered_biomes()
minetest.clear_registered_decorations()

minetest.register_biome({
	name =              "grassland",
	node_top =          "default:dirt_with_grass",
	depth_top =         1,
	node_filler =       "default:dirt",
	depth_filler =      3,
	node_stone =        "default:stone",
	node_river_water =  "default:river_water_source",
	node_riverbed =     "default:gravel",
	depth_riverbed =    1,
	y_min =             1,
	y_max =             31000,
	heat_point =        50,
	humidity_point =    50,
})

-- Grass
local function register_grass_decoration(offset, scale, length)
	minetest.register_decoration({
		deco_type =     "simple",
		place_on =      {"default:dirt_with_grass"},
		sidelen =       80,
		fill_ratio =    0.9,
		biomes =        {"grassland"},
		y_min =         1,
		y_max =         31000,
		decoration =    "default:grass_"..length,
	})
end

register_grass_decoration(-0.015,  0.18, 5)
register_grass_decoration(-0.0075, 0.15, 4)
register_grass_decoration(0,       0.12, 3)
register_grass_decoration(0.03,    0.09, 2)
register_grass_decoration(0.06,    0.06, 1)
```

OS: MacOS 10.12 Sierra
Minetest: 0.4.15 and 0.4.14

**Comment by sfan5** [comment] 2017-01-28 10:36
@paramat

**Comment by vlapsley** [comment] 2017-01-28 10:41
Doing further testing I get the same issue at y=127/128

**Comment by RHRhino** [comment] 2017-01-28 11:38
@vlapsley Seems to occur at the chunk/mapblock borders every 80 nodes. (first mapblock is from y= -32 to +48) => y=48+n*80

**Comment by paramat** [comment] 2017-01-28 20:16
Will investigate.

**Comment by paramat** [comment] 2017-01-28 23:11
Do you get this bug in other non-mgv6 mapgens?

**Comment by paramat** [comment] 2017-01-28 23:26
This bug happens in mgvalleys even without your mod.
I'll defer to the author @duane-r

**Comment by vlapsley** [comment] 2017-01-28 23:43
Can't find the bug in mg7. 

I understand the bug is present without my mod. I made that to clearly illustrate the problem and try to replicate in mg7. 

Nodes placed with the voxelmanipulator are ok. Haven't tried schematics yet.

**Comment by duane-r** [comment] 2017-01-29 00:16
I've been trying to catch this bug for a long time. I think it's causing big sheets of sand and rock in my cave decorations too. So far, I've no clue how to fix it. I'll keep looking though.

**Comment by paramat** [comment] 2017-01-29 03:16
@duane-r i see that you do not 'updateHeightmap' in 'makeChunk', instead you set the heightmap in 'generateTerrain', is this necessary?
Then you have:
```
		// This happens if we're generating a chunk that doesn't
		// contain the terrain surface, in which case, we need
		// to set heightmap to a value outside of the chunk,
		// to avoid confusing lua mods that use heightmap.
		if (heightmap[index_2d] == -MAX_MAP_GENERATION_LIMIT) {
			s16 surface_y_int = myround(surface_y);
			if (surface_y_int > node_max.Y + 1 || surface_y_int < node_min.Y - 1) {
				// If surface_y is outside the chunk, it's good enough.
				heightmap[index_2d] = surface_y_int;
			} else {
				// If the ground is outside of this chunk, but surface_y
				// is within the chunk, give a value outside.
				heightmap[index_2d] = node_min.Y - 2;
			}
		}
```
Is this necessary?
I suspect one or both of these are the reason.

**Comment by paramat** [comment] 2017-01-29 03:26
Decorations are placed at the heightmap value, if the heightmap value is wrong the required surface node will not be detected and no decoration will be placed.

**Comment by duane-r** [comment] 2017-01-29 03:35
Unfortunately, valleys doesn't generate the height directly from the noise. It has to run a loop to compare the 3D noise values to the terrain. Then the actual height sometimes ends up being in another chunk altogether (even though the initial noise values are in this chunk). I've never figured out how to make that work like the other mapgens without just dropping the 3D noise which gives valleys its character.

I only have a weak understanding of the theory behind this. Gael de Sailly was working way over my head when he developed it. I just ported his code to C.

However, this may not be the problem I was looking at, because I correct the heightmap in my lua mapgens. Even so, I sometimes end up with oddly generated chunk boundaries.

**Comment by duane-r** [comment] 2017-01-29 03:43
generateTerrain is called long before placeAllDecos, so the order of the code isn't the problem. I'll try returning -MAX_MAP_GENERATION_LIMIT in all cases outside the chunk, but I seem to recall that causing problems elsewhere...

**Comment by paramat** [comment] 2017-01-29 04:06
The heightmap is for the highest walkable node _within the present chunk_, whether there is more stone above in another chunk is irrelevant and that out-of-chunk value should not be inserted into the heightmap.
I can't see how this can't just call 'updateHeightmap' after the basic stone terrain has been generated.

**Comment by paramat** [comment] 2017-01-29 04:09
That block of code for the sake of mods seems pointless, unless there is an in-mapgen need for it.

**Comment by paramat** [comment] 2017-01-29 04:14
> Unfortunately, valleys doesn't generate the height directly from the noise. It has to run a loop to compare the 3D noise values to the terrain.

This is how mgv5, mgv7 and other mapgens work too, any mapgen with 3D noise works this way.

**Comment by duane-r** [comment] 2017-01-29 04:18
Well, removing that whole section of code has no effect on the problem.

**Comment by paramat** [comment] 2017-01-29 04:20
Ok, but still, it's wrong use of heightmap and should be removed, unless it's necessary for the mapgen itself.

**Comment by duane-r** [comment] 2017-01-29 04:28
Ok. Running updateHeightMap doesn't seem to have any effect either.

**Comment by duane-r** [comment] 2017-01-29 04:48
No, I'm wrong. I was looking at a shallow cave. Now that I've turned caves off, I see that running updateHeightMap does fix the decorations. However, now I get a layer of grassy earth in the snow.

http://duanerobertson.com/img/grassy-problem-01.jpg

**Comment by duane-r** [comment] 2017-01-29 05:03
I think the biome issue is separate, though more obvious after the heightmap is fixed.

**Comment by paramat** [comment] 2017-01-29 05:17
Thanks, interesting.

**Comment by paramat** [comment] 2017-01-29 05:26
Soometime i need to get my head around this mapgen code and possibly simplify it.

**Comment by paramat** [comment] 2017-01-30 17:06
Oops i was wrong:
> you set the heightmap in 'generateTerrain', is this necessary?

It is because the heightmap value is used immediately after the y-loop within generateTerrain, so i have an idea, will try.

**Comment by paramat** [comment] 2017-01-31 09:30
Kwolekr did a lot of work on mgvalleys here https://github.com/minetest/minetest/pull/4135/files#diff-1257c51e7822e6071317c35f9e0531ae perhaps you could try a version just before this to see if the original bug is present? Or maybe you know if it was present before this commit?

**Comment by paramat** [comment] 2017-01-31 09:42
I've noticed a probably unrelated error in mgvalleys that occured when kwolekr made those big changes.

See https://github.com/minetest/minetest/blob/master/src/mapgen_valleys.cpp#L241
```
	// Generate noise maps and base terrain height.
	calculateNoise();

	// Generate biome noises.  Note this must be executed strictly before
	// generateTerrain, because generateTerrain depends on intermediate
	// biome-related noises.
	m_bgen->calcBiomeNoise(node_min);
```
calculateNoise comes before calcBiomeNoise, but in calculateNoise we have:
```
	float heat_offset = 0.f;
	float humidity_scale = 1.f;

	// Altitude chill tends to reduce the average heat.
	if (use_altitude_chill)
		heat_offset = 5.f;

	// River humidity tends to increase the humidity range.
	if (humid_rivers) {
		humidity_scale = 0.8f;
	}

	for (s32 index = 0; index < csize.X * csize.Z; index++) {
		m_bgen->heatmap[index] += heat_offset;
		m_bgen->humidmap[index] *= humidity_scale;
	}
```
This alters the heat and humidty maps, but those maps are NULL here because they are calculated in calcBiomeNoise, so these alterations fail.
The fix is to swap the order, this alters the biomes a little because everything is warmed by 5, but it should match how mgvalleys was before kwolekr's changes.

**Comment by paramat** [comment] 2017-01-31 10:35
I tested mgvvalleys before kwolekr's commit and it also has this bug, i tried some changes to try and fix the bug with no success. So this issue bug is not caused by kwolekr's commit.

**Comment by paramat** [comment] 2017-02-01 15:15
#5148 merged.

**Closed by paramat** 2017-02-01 15:15 UTC
Labels: @ Mapgen
