### ISSUE TITLE
Checkboxes are too small in 4K/UHD

### ISSUE THREAD

**Issue by sirrobzeroone** [minetest/minetest#13665] opened 2023-07-16 00:55 UTC
##### Minetest version
5.7 Stable

##### OS / Hardware
Operating system: Win10
Screen UHD: 3840x2160p
OS Forces scaling to 200% but I force set this to100% but ended up with tinier out of scale checkboxes

##### Summary
Affects both MT main menu and formspec. Checkboxes are rendered about 50% to small when using UHD res - assuming standard of checkboxs should be about the same hieght as text. 

##### Steps to reproduce
Open MT on a UHD device on Win10, Creative mode, Enable Damage, Host server appear small:

Edit: Thought a more actual size image could help illustrate:
![tiny_cb_main_menu_more actual size](https://github.com/minetest/minetest/assets/44497598/7e067c23-3fcb-4c41-8922-c1939f356e24)
![tiny_cb_main_menu](https://github.com/minetest/minetest/assets/44497598/48d2239d-6f75-4147-876d-155a224288c6)

Add Checkbox as formspec elment and they are likewise smaller than expected:
![tiny_cb_formspec](https://github.com/minetest/minetest/assets/44497598/41a94052-a5de-40a3-ae7c-18f076523150)

**Comment by SmallJoker** [comment] 2023-07-16 10:47
This is an issue in upstream Irrlicht as well: https://sourceforge.net/p/irrlicht/code/HEAD/tree/trunk/source/Irrlicht/CGUICheckBox.cpp#l149

This should either be fixed in upstream Irrlicht or in IrrlichtMt:

https://github.com/minetest/irrlicht/blob/b249e4523d9e0b8d7e607131685de34d8c48cd6b/source/Irrlicht/CGUICheckBox.cpp#L147

**Comment by sfan5** [comment] 2023-07-16 10:57
Easy reproducer:
`./bin/minetest --config <(echo gui_scaling=0.5)`

**Comment by SmallJoker** [comment] 2023-07-16 12:11
Correction. This is fixable in Minetest because Irrlicht skins can be created and modified:

https://github.com/minetest/minetest/blob/206198431309fb00ff717f3ebd5e7c0af3de59dd/src/client/clientlauncher.cpp#L147-L149

It should be easy to adapt this factor to make use of the display density for non-touchscreens as well.

**Comment by sfan5** [comment] 2023-07-16 12:14
Manually adjusting some sizes looks like a hack to be honest, the GUI should be able to work with the sizes it is given.

**Comment by rubenwardy** [comment] 2023-07-16 12:46
We maintain Irrlicht now, if the fix is better done in irrlichtmt it should be done there

**Closed** 2023-07-17 18:46 UTC
Labels: Bug, Upstream issue, Formspec
