### ISSUE TITLE
Make param1 store natural light separately from artificial light

### ISSUE THREAD

**Issue by ryvnf** [minetest/minetest#13689] opened 2023-07-25 16:43 UTC
## Problems

Currently in `param1`  the upper 4 bits stores _max(natural light, artificial light)_ and the lower 4 bits stores _artificial light_. I assume the reason for this is that it makes the lighting propagation more efficient in some instances.

This decision does however lead to some problems and limitations.

#### 1. Makes get_natural_light very complicated and inefficient

One problem is that the API function to get the natural light level is incredibly complicated (see [this](https://github.com/minetest/minetest/blob/master/src/serverenvironment.cpp#L1125-L1208) and [this](https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_env.cpp#L389-L426)). If the natural light was stored separately it would just be a simple bit shift and return. In addition to requiring an algorithm which is unnecessarily complicated and hard to understand, it is probably also inefficient for mods which use `get_natural_light` frequently .

#### 2. Causes limitations for the graphics

Splitting the light levels would open up possibilities for making the graphics of Minetest look nicer.

Something which makes the graphics of Minecraft look better is that natural light has a different color from artificial light. It uses a lightmap which is a 16x16 texture file which is indexed on one axis for natural light and the other for artificial light. See this picture file of a lightmap to know what I mean:

![lightmap](https://github.com/minetest/minetest/assets/11559411/d8f2325f-0972-4366-a3f2-10c3f6c00647)

I think this would allow the graphics of Minetest to improve significantly. One could for example have a lightmap be configurable as a texture for mods which would greatly increase the possibility of people making games make them look unique. If the lightmap was settable for specific players it could also be used to implement effects like blinding players or improved night vision. One could also implement effects like natural light becoming red during the sunset and blue during the night which would probably look very nice.

The point is that changing param1 to store natural light separately from artificial light opens up a lot of ways in which the graphics of Minetest can be improved. Currently the graphics looks kind of dull since all lighting is just a white color while in real life different light sources have different colors.

## Solution

I propose that Minetest change the param1 to be

1. The upper 4 bits are only natural light
2. The lower 4 bits are only artificial light

### Considerations

This would introduce a couple of potential backwards incompatibilities:

1. It would make the light propagation for old nodes to not work correctly.
2. Depending on how the lighting for clients are rendered it will also be incompatible with old clients. If the rendered light level of blocks is determined by _max(upper 4 bits, lower 4 bits)_ then it should be backwards compatible. But if it is only _upper 4 bits_ then a node with 0 natural light and 15 artificial light would be rendered as completely black.

(1) would be solvable by adding a server side setting to enable the new lighting system for new worlds and keep the old lighting system for old worlds. (2) would probably not be solvable if it is an issue (I have not looked at the code so I do not know if it would be a problem).

If (2) is not an issue, then I think the best approach would be to implement this in a future 5.X.X version with a world specific setting to enable it on new worlds. New worlds would use the new lighting system by default and old worlds would use the old lighting system.

If (2) is an issue, then I think this is something which needs to be considered for Minetest 6.0.0.

**Comment by rubenwardy** [comment] 2023-07-25 17:19
Duplicate of #5155

**Closed by rubenwardy** 2023-07-25 17:19 UTC
Labels: Feature request
