### ISSUE TITLE
Touch Screen Support on desktop platform

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10532] opened 2020-10-21 11:43 UTC
## Problem

I can't use my touch screen to control minetest now

## Solutions
Add these:
1. If you are using the touch screen to control, the game act like mobile (that have touch screen support and virtual joystick)
2. Compile opction to disable touch screen support

**Comment by sfan5** [comment] 2020-10-21 14:38
Marked upstream issue since this depends on Irrlicht exposing stuff like `EET_TOUCH_INPUT_EVENT` (currently only exists in the GLES port).

**Comment by SmallJoker** [comment] 2020-10-21 16:05
Duplicate of #1798
Closely related: #10062

**Closed by SmallJoker** 2020-10-21 16:05 UTC
Labels: Feature request, Upstream issue
