### ISSUE TITLE
Failed unit test in many correct PRs

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3853] opened 2016-03-14 02:59 UTC
Often there is a failed unit test with this output:
```
======== Testing module TestThreading
Test assertion failed: thread_retval == thread
    at test_threading.cpp:107
[FAIL] testStartStopWait - 79ms
[PASS] testThreadKill - 403ms
[PASS] testAtomicSemaphoreThread - 9ms
======== Module TestThreading failed (1 failures / 3 tests) - 491ms
```
Even on PRs which are obviously fine.
It's always: Travis, fourth build (#****.4), clang, UNIX
@nerzhul @kwolekr

**Comment by est31** [comment] 2016-03-14 04:03
Dupe of #3786

**Closed by est31** 2016-03-14 04:03 UTC
Labels: @ Build
