### ISSUE TITLE
VoxelManip bug in not generated mapchunks

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#5408] opened 2017-03-17 08:49 UTC
This may be caused by bulk lighthing improvement.
![screenshot_20170316_211505](https://cloud.githubusercontent.com/assets/3192173/24016843/f933e6fc-0a8d-11e7-9a34-bfa68599b545.png)

You can reproduce the bug with usual worldedit and newest minetest:
* //teleport 1000 0 1000
⇒ map there becomes generated
* //pos1
* //teleport 1000 1000 1000
⇒ there map is generated too
* //pos2
* //set wood
* //set cobble
* rejoin (restart) now
* explore the not generated map

The bug appears in not generated mapblocks. The 1x1 pillar correctly consists of cobble at the ends, where the map is generated. The other parts of the pillar, after restarting the server, consist of wood, and sometimes air.
Without restarting or in already generated map the bug doesn't appear.

tested before https://github.com/minetest/minetest/commit/d5a97e00eaac54def16fb53b68cfed7300af0854

**Comment by paramat** [comment] 2017-03-17 13:05
Could you try to reproduce with a build before the bulk lighting PR? I suspect that isn't the cause.
A 1000 node pillar would require 63 mapblocks loaded which is not excessive, that's less than a mapchunk, so this is not overloading vm volume.

**Comment by paramat** [comment] 2017-03-17 13:57
Could be a WorldEdit bug, i'll try to reproduce using my own code.

**Comment by paramat** [comment] 2017-03-17 14:24
I used my own lvm code to make a 1000 high column, in a new world with only the ends of the column being generated mapchunks. There was a gap from 96 to 223, both mapblock borders.

**Comment by paramat** [comment] 2017-03-17 14:29
2nd attempt worked ok.

**Comment by paramat** [comment] 2017-03-17 14:46
4th attempt: This time only generated the lower mapchunk at the lower end of the column, a gap from 128 to 144, both are mapblock borders.

**Comment by HybridDog** [comment] 2017-03-17 15:15
> Is this your fork of WorldEdit?

l made the pillar with original WorldEdit.

**Comment by paramat** [comment] 2017-03-17 15:27
Another attempt: Gaps from 192 to 223, 338 to 365, 419 to 436, 442 to 460, 539 to 670, 685 to 689, 720 to 733, 754 to 944.

**Comment by juhdanad** [comment] 2017-03-17 22:32
I discovered two things:

If you modify worldedit/common.lua to place air or stone instead of ignore, nodes are placed correctly. This means that the problem is with writing ignore nodes to the map.

If you place stone to ungenerated area, the mapgen will decorate it.

**Comment by HybridDog** [comment] 2017-03-18 08:38
If you use get_data(), the nodes in not generated chunks are also ignore, aren't they?

**Comment by paramat** [comment] 2017-03-18 13:43
> If you use get_data(), the nodes in not generated chunks are also ignore, aren't they?

Mostly, apart from overgenerated structures like large caves, dungeons, trees.
I suggest changing WorldEdit to use vm:get_data() to see if things improve, but then the bugs i discovered will remain.

**Comment by paramat** [comment] 2017-03-18 13:46
> This means that the problem is with writing ignore nodes to the map.

I investigated this, 'vm:write_to_map()' will not write if the node is 'ignore', which is why WorldEdit initialises the emerged volume with ignore instead of world nodes.

**Comment by bigfoot547** [comment] 2017-03-26 03:18
I did this in a desert biome and the stone in the middle became desert stone!

**Comment by paramat** [comment] 2017-03-26 04:05
Interesting, the biome API code must have changed it to the defined biome stone.

**Comment by HybridDog** [comment] 2017-03-26 10:21
There's that field in a node definition which indicates whether caves can remove the node…

**Comment by paramat** [comment] 2017-09-24 05:32
Fixed by d5a97e00eaac54def16fb53b68cfed7300af0854 ?

**Comment by HybridDog** [comment] 2017-09-24 07:33
I've just tested it.
l could reproduce it with daily minetest ppa version (Sep 18 2017 16:17:10)
I could not reproduce it with the latest git version (0.5.0-dev-bd6b9035)

**Comment by paramat** [comment] 2017-09-24 07:45
Seems fixed, please comment if it isn't.

**Closed by paramat** 2017-09-24 07:45 UTC
Labels: @ Server / Client / Env., Bug
