### ISSUE TITLE
Possibility to attach obj to node.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#7735] opened 2018-09-19 17:06 UTC
##### Issue type

 - Feature request

And here is a other request that i`m awaiting from the minetest devs: what about adding a possibility to attach obj to node?

**Comment by DS-Minetest** [comment] 2018-09-19 17:13
So, make the object unmovable and remove (or disattach?) it when the node is removed?

**Comment by paramat** [comment] 2018-09-19 18:43
This is not clear. Nodes are fixed in position, so you just place the object at the node's position, no need for attachment.

**Comment by rubenwardy** [comment] 2018-09-19 22:01
Duplicate of #6963

**Closed by rubenwardy** 2018-09-19 22:01 UTC

**Comment by raymoo** [comment] 2018-09-26 19:53
I don't think this is a duplicate. I think #6963 is about having a node represent or be part of a node, and that this issue is about attaching an independent object to a node (temporarily).

**Comment by paramat** [comment] 2018-09-26 21:06
We're not sure because the request is so vague. Andrey2470T please explain what you are requesting.

**Comment by paramat** [comment] 2018-09-26 21:10
From IRC:
> Andrey01 	e.g. player wants to sit the chair. How can he do it??
Andrey01 	well, then i need to write a code to do it, if something would be like obj:attach_to_node(nodename, pos) it would take less a code and it would be simpler

That's not justified, when you position a player somehow to a node there are many aspects to set and this should be done by writing code to do it. Any function would end up having too many parameters and be too complex.

**Comment by paramat** [comment] 2018-11-16 23:04
Not a duplicate because #6963 actually makes some sense and is valid :D
