### ISSUE TITLE
client_lua_api.txt refers to minetest.setting_get but doesn't exist

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest#8579] opened 2019-06-05 10:59 UTC
https://github.com/minetest/minetest/blob/master/doc/client_lua_api.txt#L104 shows minetest.setting_get and setting_getbool, but these don't exist.

**Comment by DS-Minetest** [comment] 2019-06-05 11:27
`client_lua_api.txt` is outdated in various points.

**Comment by Linuxdirk** [comment] 2019-06-05 12:45
Yes, it's outdated but since 0.4.17 no-one seems to really work on anything CSM-related.

Try `minetest.settings:get` and `minetest.settings:get_bool` instead.

**Comment by jastevenson303** [comment] 2019-06-05 17:07
There is no minetest.settings in CSM, @Linuxdirk

**Comment by DS-Minetest** [comment] 2019-06-05 20:21
Ah, this is a duplicate of #5454.

**Comment by jastevenson303** [comment] 2019-06-06 01:19
It's not really a duplicate, @smalljoker.

The other ticket, which is closed, is a feature request.

This ticket is for something the documentation is referencing that is not present.

https://github.com/minetest/minetest/blob/master/doc/client_lua_api.txt#L104 says that minetest.setting_get exists, but it does not exist.

**Comment by Linuxdirk** [comment] 2019-06-06 13:49
Yes, not a duplicate at all but more like a documentation issue. The linked issue is dead due to inactivity and uncertain future of CSM.

**Comment by SmallJoker** [comment] 2019-06-06 16:44
From #5454:
> l noticed that minetest.setting_get doesn't work.

Well, it still does not work, except that now the function does not exist at all any more. Opening since the other issue was closed and the situation changed a bit.

**Comment by paramat** [comment] 2019-06-06 18:22
If anyone makes a PR to remove those liones i'll merge it immediately.

**Closed** 2019-09-08 16:43 UTC
Labels: @ Client Script API, @ Documentation, Bug
