### ISSUE TITLE
Receiving/updating map chunks creates huge CPU usage

### ISSUE THREAD

**Issue by ElementW** [minetest/minetest#3561] opened 2016-01-13 22:08 UTC
Digging and also placing nodes (i.e. updating) creates high and relatively long-lasting and intensive CPU spikes, not causing slowdowns but high CPU heat-up. In the same fashion, moving around in an already-generated world and loading/receiving map chunks (vanilla LAN server) ends up in ~75% CPU hog on the client.

![CPU Graph](http://i.imgur.com/lK9M6Xg.png)

Graph obtained with the Multiload XFCE plug-in, 350 ms update interval. Brown is IOWait, Red is kernel time, Blue is userspace time. 16 iron ore nodes were dug with a diamond pickaxe.
The spikes are seemingly caused by new map chunks display (changing head orientation).

**Comment by RobertZenz** [comment] 2016-01-13 23:48
Maybe related with #3166?

**Comment by est31** [comment] 2016-01-13 23:56
@RobertZenz I don't think so. 3166 is about heavily modded games, and happens in mapblocks that are already loaded. What @gravgun seems to complain about is mesh generation lag, deflate overhead or something.

**Comment by paramat** [comment] 2016-01-14 02:00
Not necessarily a bug, apparently every time the crack animation moves to a new frame there is a mesh update for the whole block, making a good case for not using the crack animation. Also removing or adding nodes causes lighting updates.
Likewise CPU use when loading blocks may also not be a bug but just how Minetest is.
If it has got worse since 6 months ago it might be due to the vertextangents commit, every vertex now has more information stored, there is more memory use, even with shaders disabled #3530

**Comment by est31** [comment] 2016-01-14 08:39
@paramat you can play the networked multiplayer release if you want, its small and simple as you like it.

**Comment by Fixer-007** [comment] 2016-01-14 22:58
I've noticed that problem too.

**Comment by RealBadAngel** [comment] 2016-01-15 02:16
Solution to it was made quite long time ago but was rejected.
Ive simply dropped the cracks animation and replaced  it with particles and tweaking highlighting halo.
No mapblock mesh updates were needed then (and thats the reason for such spikes)

**Comment by paramat** [comment] 2016-01-15 03:34
est31 =P

I support the option of disabling the crack animation.

**Comment by HybridDog** [comment] 2016-07-18 08:49
l thought the crack animation, like the selection box, is put into a free mesh…

When l load a few chunks in singleplayer mode and then press r to activate full viewing range, minetest freezes and l need to kill it from terminal.

**Comment by Fixer-007** [comment] 2016-07-18 11:51
Any way to make it render as separate mesh overlayed on top of target block?

**Comment by ElementW** [comment] 2016-07-18 16:52
@Fixer-007 Which is the most sensible and logical thing to do, that isn't done.

**Comment by nerzhul** [comment] 2020-04-11 16:23
i think this one can be closed. the engine has changes many and we don't have the mod context.
@ElementW if you can reproduce now on the 5.2 it can be fine, especially with a vanilla minetest_game

**Comment by paramat** [comment] 2020-04-11 21:11
I agree, closing.

**Closed by paramat** 2020-04-11 21:11 UTC
Labels: Performance, Possible close

**Comment by ElementW** [comment] 2020-04-13 09:13
The situation is indeed much better, as can be seen on the graph below (relative to 100% use of my 2virt×2phys core Intel 3317U), with the central span being digging, surrounded by idling.
Git revisions: minetest/minetest@6cf15cf872cc9ce76990d83d380ca3c4b7485eb1, minetest/minetest_game@36b2bcb5f3379cfc28b74974ce74e965821d1493
![Screenshot_2020-04-13_11-07-21](https://user-images.githubusercontent.com/396420/79108976-b802e880-7d77-11ea-9df8-e6301cfcfed4.png)

**Comment by paramat** [comment] 2020-04-14 20:06
Thanks for the retest.
