### ISSUE TITLE
Easier to change langauge

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#12619] opened 2022-07-31 14:02 UTC
## Problem
 if a player dont know English play the game first time, its hard to change the langauge

## Solutions
Make a button with visual icon that lead to langauge change screen

## Alternatives
replace setting tab text to icon

## Additional context

i think the game should replace some text to icon so anyone can easily interact

**Comment by rubenwardy** [comment] 2022-07-31 14:10
Hi, thanks for the suggestion

Closing as it's a duplicate of #9141

**Closed by rubenwardy** 2022-07-31 14:10 UTC
Labels: Feature request
