### ISSUE TITLE
Model texture is rendered white

### ISSUE THREAD

**Issue by BeverlyCode** [minetest/minetest#13423] opened 2023-04-12 16:18 UTC
All versions.

Bug in entity rendering system. Causes only textures on entities to be full black, white, or use a random texture. Noticeable in Brachiosaurus from Paleotest in most instances, or mob entities in Livingfloatlands.

This is not limited to mobkit or mobs_redo, it can effect any entity. The bug is reproducible but the effects are random, doesn't always show up for everyone.

I have tested the same b3d models as meshnodes and the bug only appears when the models are loaded as entities.

Confirmed by GreenXenith: https://discord.com/channels/369122544273588224/369137254641303560/1089982985291452506

**Comment by SmallJoker** [comment] 2023-04-12 16:26
Please do not delete the entire issue template next time and use it as a guide.

* How can this be reproduced? Preferably include a screenshot to visualize your problem.
* Which OS, architecture, GPU model, driver?

**Comment by Niklp09** [comment] 2023-04-12 16:57
_EDIT: The content you're referring to in the link is not visible by the public, hence suboptimal._

GreenXenith's message
> Brach on jurassic park server, android (mt 5.5.1)
![grafik](https://user-images.githubusercontent.com/89982526/231528755-fe39937b-955c-4c78-866c-97e5b40b0577.png)

**Comment by fluxionary** [comment] 2023-04-15 22:37
i'm pretty sure this is a bug in paleotest, CalebJ from Tunnelers' Abyss fixed it at some point, but doesn't remember how. i installed paleotest in a fairly basic world, and spawned a few brachiosaurs, which were pure white. most mobs on most other servers are fine for me.

**Comment by fluxionary** [comment] 2023-04-15 22:41
actually, something similar seems to have been reported previously: https://github.com/ElCeejo/paleotest/issues/8

**Comment by runsy** [comment] 2023-05-14 11:26
Petz has not that bug. I belive is a mod error.

**Comment by runsy** [comment] 2023-05-14 20:27
> I believe you have not read this entire thread. It is not a mod error. It is very plausible there are mods that do not incur this problem, but that alone does not deduce it to being a "mod error", please refrain from making this claim without hard evidence.

After many years of experience I will tell you, those errors can be due to functions that change textures, for example a bad use of object:set_properties. From another mod or from another mod, it is very common in callbacks.

It is very easy to check, enter the model in PETZ. I am 100% sure there will be no problem.

**Comment by runsy** [comment] 2023-05-15 13:06
send me the b3b

**Comment by fluxionary** [comment] 2023-05-16 21:59
so far, the only instance of this that has been demonstrated is with paleotest, which is *definitely a bug w/ the paleotest brachiosaurus* because it's been fixed on Tunnelers' Abyss (though the fix is not available, AGPL anyone?). 

as no problem can be demonstrated w/ petz, this should be closed.

**Comment by fluxionary** [comment] 2023-05-17 02:25
> This should not be closed because I am telling you I have tested this, unless you can provide contradictory evidence.

my evidence is that you haven't provided any way to replicate this issue w/ petz. 

> There is no proof Tunnelers' Abyss has actually fixed this problem at the moment this is just a claim you are making. 

you can join the server, track down the admins, and get them to show you some dinosaurs.

**Comment by fluxionary** [comment] 2023-05-17 02:27
> the .x model I uploaded in my prior response.

i don't even know what to do w/ that? that's not a format minetest understands?

**Comment by fluxionary** [comment] 2023-05-17 02:29
> Having made no tests, what is this?

i'm an admin on the most popular minetest server that runs petz, with an easy system to report bugs. *thousands* of issues have been opened. if this was a common problem, i guarantee you, i would have heard about it.

**Comment by fluxionary** [comment] 2023-05-17 02:33
> I've never asked Petz to do anything? This is posted as a minetest issue?

... i'm embarrassed, i didn't notice which forum this was on.

**Comment by SmallJoker** [comment] 2023-05-18 09:58
This looks optically the same as https://github.com/minetest/minetest/pull/9374#issuecomment-586707737 but it was fixed during the process.
I can confirm that `/spawnentity paleotest:brachiosaurus` from paleotest sometimes results in incorrectly rendered textures. This does not depend on shaders, e.g. `enable_shaders = false` makes no difference.

Have you yet checked whether the texture normals are correct? Aside from that it might be worthwhile to valgrind for uninitialized variables.

**Comment by sfan5** [comment] 2024-08-02 15:49
Needs re-testing.

**Closed** 2024-09-05 13:22 UTC
Labels: Bug, Action / change needed, Possible close, @ Client rendering
