### ISSUE TITLE
Texture filtering regressions (biilinear and trilinear filtering broken, anisotropic filtering results inconsistent depending on GPU)

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#14007] opened 2023-11-17 11:56 UTC
### Minetest version

```true
aa912e90a769e4bb7578b83955389af0892dd361
```

### Active renderer

OpenGL 1.4

### Irrlicht device

X11

### Operating system and version

Debian 11.8

### CPU model

Intel(R) Core(TM) Duo CPU      T2400  @ 1.83GHz

### GPU model

Intel Corporation Mobile 945GM/GMS, 943/940GML Express Integrated Graphics Controller (rev 03)

### OpenGL version

1.4

### Summary

Since #13683, bilinear and trilinear filtering options seem to not do anything for node texture rendering when textures are being upscaled. At the same time, anisotropic filtering can still blur upscaled node textures depending on GPU (it certainly does on Intel GPUs). I did not expect that from a commit that claims to “clean up settings” to do this.

This is a major regression in art style and functionality, as it affects low-resolution textures (almost all textures in Minetest) and games that have a mix of textures with different resolutions (e.g. MineClone2, Mineclonia, everything that has `xmaps` or `xcam` installed, everything where a texture pack does not cover all textures etc. pp.).

**Edit:** See here for comparison screenshots: https://github.com/minetest/minetest/issues/14007#issuecomment-1817489184

### Steps to reproduce

You need the oddly sized checkerboard test nodes from this PR of mine: https://github.com/minetest/minetest/pull/13955

I have made them available separately: <https://git.minetest.land/erlehmann/oddly_sized_checkerboard_testnodes_2>

Always compare between:

a) A version of Minetest before commit https://github.com/minetest/minetest/commit/72ef90885d5030bf6f7f9dd60a475339bde9a929.
b) A version of Minetest at commit https://github.com/minetest/minetest/commit/72ef90885d5030bf6f7f9dd60a475339bde9a929

1.  Compare how checkerboard test nodes with the same tiling look without filtering. They should look the same across all versions.
1. Compare how checkerboard test nodes with the same tiling look with bilinear filtering. They should look filtered before https://github.com/minetest/minetest/commit/72ef90885d5030bf6f7f9dd60a475339bde9a929 and unfiltered in https://github.com/minetest/minetest/commit/72ef90885d5030bf6f7f9dd60a475339bde9a929 .
2. Compare how checkerboard test nodes with the same tiling look with trilinear filtering. They should look filtered before https://github.com/minetest/minetest/commit/72ef90885d5030bf6f7f9dd60a475339bde9a929 and unfiltered in https://github.com/minetest/minetest/commit/72ef90885d5030bf6f7f9dd60a475339bde9a929 .
3. Compare how checkerboard test nodes with the same tiling look with anisotropic filtering: They should look blurred in https://github.com/minetest/minetest/commit/72ef90885d5030bf6f7f9dd60a475339bde9a929 even if bilinear filtering is turned off if you have an Intel GPU.

**Comment by erlehmann** [comment] 2023-11-17 11:58
I have a fix that reverts https://github.com/minetest/minetest/pull/13683: See https://github.com/minetest/minetest/pull/14006 and https://github.com/minetest/irrlicht/pull/254 for the code.

**Please add this to the 5.8.0 Milestone.**

**Comment by sfan5** [comment] 2023-11-17 13:36
To be clear: the feature we are talking about is the one that turns all (low-res) textures blurry along with blending artifacts as in the image below?
![grafik](https://github.com/minetest/minetest/assets/1042418/7df7c96e-bf77-4506-9780-3bbab3d2b4ee)

Is this considered desirable? If not, what am I missing?
Can you maybe show the art style regression this causes in e.g. MineClone2?

**Comment by erlehmann** [comment] 2023-11-17 14:29
Turning filtering on makes textures have a much more smoother look. The blending artifacts give it a comic-style outline, but I must admit I did not think of them when complaining about visual regressions. We hopefully agree that the filtering situation needs work after Minetest 5.8.0. The discussion what is *desirable* should be a post-release-thing too IMO, as it opens an entire can of worms (e.g. Minetest would have to commit to gamma-correct rendering or provide it as an option to get rid of some blending artifacts).

I am not sure how desirable people find filtering-when-upscaling, but a) IIRC this look needed to be explicitly turned on b) people did turn it on all the time to get this look, as I have seen in screenshots over many years c) IIRC @rollerozxa complained on IRC about the blurryness being gone.

Below I have rendered the same scene with the dungeonsoup texture pack. Keep in mind this is literally the *smallest* difference with default settings + bilinear filtering as the texture pack is 32×32 and only gets upscaled to 64×64.

![minetest-textures-dungeonsoup-unfiltered](https://github.com/minetest/minetest/assets/60905/55909ee1-2bac-4974-ac1d-1462ece4293a)
![minetest-textures-dungeonsoup-filtered](https://github.com/minetest/minetest/assets/60905/22123055-bb37-4432-a72c-5240a18b3bce)

**Comment by erlehmann** [comment] 2023-11-17 14:36
I noticed that the outline artifacts are much less noticeable with the smaller 16×16 default textures:

![minetest-textures-default-unfiltered](https://github.com/minetest/minetest/assets/60905/dd252967-7469-40d8-aaef-a1f4ef523835)
![minetest-textures-default-filtered-bilinear](https://github.com/minetest/minetest/assets/60905/565b1bbd-16dc-4132-949c-b80e38dbc82c)

**Comment by erlehmann** [comment] 2023-11-17 15:40
> The argument I was hoping to make is that the blurriness and blending artifacts are a bug and need not to be preserved.

The blurriness is definitely intentional on the part of users.

The blending artifacts, isn't that a botched texture optimization, throwing away transparent pixels?

I may not understand this well, but that botched optimization is what `texture_clean_transparent` tries to fix … or not?

**Comment by Desour** [comment] 2023-11-17 15:40
You don't need checkerboard nodes to see the effects of bilinar filtering.

>Since https://github.com/minetest/minetest/pull/13683, bilinear and trilinear filtering options seem to not do anything for node texture rendering.

Can't reproduce. I can see clearly see a difference, at least with anisotropic filter off.

<details><summary>screenshots for comparison</summary>

no mipmapping or texture filtering:
![nomip](https://github.com/minetest/minetest/assets/7613443/0b54496e-a485-4d88-b7a7-772e02e148fa)

mipmapping:
![mip](https://github.com/minetest/minetest/assets/7613443/29707a6b-a453-4418-9cc4-2f9ccdecb6e3)

mipmapping + bilinear filter:
![mip_bilin](https://github.com/minetest/minetest/assets/7613443/a2386096-f766-4fae-ae5f-913fac07974a)

mipmapping + trilinear filter (bilin+trilin setting):
![mip_bilin_trilin](https://github.com/minetest/minetest/assets/7613443/67ba65da-6ea0-47ad-8a74-2431cadaa43f)

mipmapping + trilinear filter + anisotropic filter:
![mip_bilin_trilin_aniso](https://github.com/minetest/minetest/assets/7613443/ad8ed8e5-29f9-4644-b257-b3d9a9fb1a86)

mipmapping + anisotropic filter (what I usually use):
![mip_aniso](https://github.com/minetest/minetest/assets/7613443/ce7d84e2-7e8d-4f19-bf9c-4eba9c218f06)


</details>

>Also, anisotropic filtering blurs node textures depending on GPU (it certainly does on Intel GPUs).

FYI, the mesa software renderer (`LIBGL_ALWAYS_SOFTWARE=true minetest`) also seems to do bilinear filtering on anisotropic filter.

We could also just change the description of anisotropic filtering to inform users that the blurriness is not intended.
In the long term, if there's no other workaround, it probably makes sense to add texture upscaling as an option for affected gpus, so that they can also have halfway proper anisotropic filtering.

>I did not expect that from a commit that claims to “clean up settings” to do this.

We usually don't put all useful information in commit descriptions. You need to look up the PRs and issues.

**Comment by erlehmann** [comment] 2023-11-17 15:56
> Can't reproduce. I can see clearly see a difference

Right, I should fix that description. It only stopped working when upscaling textures I think.

> In the long term, if there's no other workaround, it probably makes sense to add texture upscaling as an option for affected gpus, so that they can also have halfway proper anisotropic filtering.

Sure, but in the short term, “make work like it did before” is a perfectly fine way to solve a regression shortly before release IMO.

Btw, if I understand it correctly, specific combinations of filtering/scaling options are more-or-less meaningless as-is and at best understood as “quality hints” by vendors. So right now questions about reproducibility and rendering intent make as much sense to me as “if I add 1 to INT_MAX in my C++ program, what is the result on an x86 CPU” does … i.e. the answer may not necessarily be undefined, but can probably not be inferred by “what is Mesa doing”.

> We usually don't put all useful information in commit descriptions.

Thanks. I did not know that it was intentional – I just thought some people are lazy or bad at writing commit messages.

**Comment by rollerozxa** [comment] 2023-11-17 15:57
> > We hopefully agree that the filtering situation needs work after Minetest 5.8.0. The discussion what is desirable should be a post-release-thing too IMO
> 
> Well, not really. The argument I was hoping to make is that the blurriness and blending artifacts are a bug and need not to be preserved.

"Blurriness" is a feature for high-res photorealistic textures to make sharp pixel edges less visible. Please do not assume that every Minetest game uses low-res pixelated textures.

The dark edges on transparent textures that would bleed into opaque parts used to be fixed or at least mitigated by `texture_clean_transparent`. Unsure where that setting went though.

**Comment by erlehmann** [comment] 2023-11-17 15:59
> The dark edges on transparent textures that would bleed into opaque parts used to be fixed or at least mitigated by `texture_clean_transparent`. Unsure where that setting went though.

Still there as of aa912e90a769e4bb7578b83955389af0892dd361 – though I am not sure if it does anything. I will test.

**Comment by erlehmann** [comment] 2023-11-17 16:06
@rollerozxa @sfan5 the `texture_clean_transparent` setting definitely removes those ugly edges:

![minetest-texture_clean_transparent_false](https://github.com/minetest/minetest/assets/60905/13adc63b-e06f-4969-8bea-bf370e7ff92e)
![minetest-texture_clean_transparent_true](https://github.com/minetest/minetest/assets/60905/f38c7259-299d-4eca-b694-afc32642bcfe)

**Comment by rollerozxa** [comment] 2023-11-17 16:23
> **Edit:** I think it is only needed if texture optimization was botched, though that seems to be the case with a lot of textures.

Optimisers (or image editors directly, if e.g. GIMP's "Save colour values from transparent pixels" export setting is disabled) usually discard the colour values of fully transparent pixels, and `optipng` generally likes to do this if you do not pass `-nc` ("no colour reduction") to it. This is especially bad with leaf textures whose transparent pixels become opaque with a setting, but for other textures featuring transparency you shouldn't have to worry about this (and you won't have to, when the clean transparent filter is enabled ^^). See the description for the setting:

> Filtered textures can blend RGB values with fully-transparent neighbors, which PNG optimizers usually discard, often resulting in dark or light edges to transparent textures. Apply a filter to clean that up at texture load time.

**Comment by erlehmann** [comment] 2023-11-17 16:34
> > **Edit:** I think it is only needed if texture optimization was botched, though that seems to be the case with a lot of textures.
> 
> Optimisers (or image editors directly, if e.g. GIMP's "Save colour values from transparent pixels" export setting is disabled) usually discard the colour values of fully transparent pixels, and `optipng` generally likes to do this if you do not pass `-nc` ("no colour reduction") to it.

Yeah, these artifacts make sense if e.g. RGBA( R, G, B, 0 ) is converted to RGBA( 0, 0, 0, 0 ), i.e. transparent black.

**Comment by Desour** [comment] 2023-11-17 16:41
>"Blurriness" is a feature for high-res photorealistic textures to make sharp pixel edges less visible. Please do not assume that every Minetest game uses low-res pixelated textures.

Yep, but that shouldn't be a client setting, as already said in #13108.

>Since https://github.com/minetest/minetest/pull/13683, bilinear and trilinear filtering options seem to not do anything for node texture rendering when textures are being upscaled.

Which is an intended change, not just "seem to". Why do you act as if something accidentally broke? It's as if you didn't read the relevant issue and PR comments *at all*.

Bilinear upscaling via client setting is an intentionally removed feature (or bug), if you want it back that's a feature request, imo.

**Comment by erlehmann** [comment] 2023-11-17 17:28
> […] that shouldn't be a client setting, as already said in https://github.com/minetest/minetest/issues/13108.

Literally every Minetest user who ever used the filtering settings disagrees with that assertion, by way of their actions.

Btw, as someone who draws textures for MInetest from time to time for their own mods and some others I also disagree.

> Bilinear upscaling via client setting is an intentionally removed feature […], if you want it back that's a feature request, imo.

We could certainly discuss if it is a good idea to break graphics settings that have worked quite well for a really long time.

What is undeniable though is that the way this was done also resulted in *most likely* unintentional rendering changes.
The current solution was not tested enough. the problems solved by upscaling likely badly understood in the first place.

There is a release coming up – IMO it is a bad idea to leave the filtering settings stay in the current/broken state.

**Comment by jeremyshannon** [comment] 2023-11-17 17:35
> It's as if you didn't read the relevant issue and PR comments _at all_.
> 
> Bilinear upscaling via client setting is an intentionally removed feature (or bug), if you want it back that's a feature request, imo.

I read the comments, and grorp specifically mentioned this might be needed in the future:
>It's true that some games made with Minetest may want to enable bilinear filtering on magnification as a part of their (non-pixel art) style, but that's something for another PR.

**Comment by sfan5** [comment] 2023-11-17 18:08
> I may not understand this well, but that last thing is what the setting `texture_clean_transparent` tries to fix … or not?

Last time I worked on that feature it was only enabled for the sake of making textures look better with mipmapping.
As I see you've found out it just seems to be disabled for ansio and enabling it would fix the edges.

> We usually don't put all useful information in commit descriptions. You need to look up the PRs and issues.

FWIW it's considered good git practice to keep commits as coherent, atomic units and describe contents in detail. We're just pretty relaxed about it.

> "Blurriness" is a feature for high-res photorealistic textures to make sharp pixel edges less visible. Please do not assume that every Minetest game uses low-res pixelated textures.

Yes, and as it is currently we still use bilinear to downscale high-res textures.
It's just not used for pixel art anymore, getting rid of the unintentional blurriness.

> Still there as of aa912e9 – though I am not sure if it does anything. I will test.

The setting was removed, so no it doesn't do anything.

> Literally every Minetest user who ever used the filtering settings disagrees with that assertion, by way of their actions.

So we *are* at the point where this is considered a feature and intentional.

Btw the direction Minetest should generally be moving in is that the user has *less* choice about invasive graphics settings.
If a game author wants to make his textures blurry he should, but it shouldn't be up to the user. (I think this is what Desour is arguing)

**Comment by erlehmann** [comment] 2023-11-17 18:32
> If a game author wants to make his textures blurry he should, but it shouldn't be up to the user. (I think this is what Desour is arguing)

Even if I was agreeing with that (which I do not), the current state disallowes even saying (or setting the setting via code) “enable filtering with my textures to make them look better” because the facility to actually do that filtering has been ripped out and *there is no dedicated setting for texture pack authors* as far as I know. Did I miss such a setting somehow? (If not, this looks awfully like following the Minetest tradition of deprecating/breaking stuff without a proper replacement once in a while.)

Btw, the anisotropic filtering regression alone would be a good reason for me to revert and try again after releasing Minetest 5.8.0. I don't care if Intel or Mesa or IrrlichtMt or the author of the patch is at fault – this used to work and now it does not and that was most certainly *not* intended, but an oversight (as IIRC there is no consistent look that can be achieved that way at all).

**Comment by Desour** [comment] 2023-11-17 19:43
My standpoint:

The bilinear filtering caused by anisotropic filtering on some platforms is an issue. This should be fixed before release, either by reverting the texture min size removal, or at least by changing the anisotropic filter setting description.

Bilinear magnification on the other hand is imo not required to be restored.

**Comment by Warr1024** [comment] 2023-11-17 22:27
Before:
- Players had a few options to choose from (linear or nearest, with some combinations of mipmapping and anisotropy).  None of the options were necessarily ideal, but there was at least some choice.
- Creators had no control.

Now:
- Players have no control.
- Creators have no control.

Regardless of to whom we want to give the control, this looks like a step in the wrong direction.

I think, at least as a fallback or something (even if we don't want it to be the ultimate UX) we should at least let players just configure the blending options that are available to the engine, e.g. nearest vs linear for upscaling, nearest, linear, linear_mip_nearest, linear_mip_linear, etc for downscaling, whatever anisotropic options the GL API offers, etc.  A lot of the behavior of these options is hardware-dependent anyway, and users will need the ability to override defaults for compatibility and accessibility needs.

**Comment by Zughy** [comment] 2023-11-18 09:18
Agree with core devs: as an artist, modder and server admin, texture blurring shluldn't be a client choice and it can also be game breaking (e.g. a node displaying a text or an icon on it, becoming unreadable). If blurring is wanted, it should be introduced as a creator choice (server-side? Idk), since, how hightlighted by Warr, creators never had a choice.

I'm unsubscribing because I feel like this is yet the umpteenth wearing discussion and I'd like to preserve my mental health. Do not tag me please, just wanted to add my two cents

**Comment by erlehmann** [comment] 2023-11-18 11:59
> texture blurring shluldn't be a client choice and it can also be game breaking (e.g. a node displaying a text or an icon on it, becoming unreadable)

Zughy is probably wrong here and I guess never investigated the effects that both the broken and the unbroken bilinear filtering have in Minetest. The difference is not between “normal” and “everything blurry” but between a render that treats texture pixels as squares (the “traditional” pixel art look) and one that treats them as point samples that require interpolation (i.e. the other ”traditional” thing). None of that is arguably more “correct”, unless we are talking about physical pixels (that are most often not squares AFAIK) or scaling and filtering (which we are, haha).

**Blurring to the point of unrecognizability can not happen if this is fixed, because textures are upscaled before filtering.**

Here are two screenshots made with my branch on which I fixed the filter regressions without and with filtering:
![minetest-text-unfiltered](https://github.com/minetest/minetest/assets/60905/66f0bede-b76d-41da-a741-a137bf896eb3)
![minetest-text-filtered](https://github.com/minetest/minetest/assets/60905/7f68e248-530d-4ccf-adb3-b81f1dbec704)

And here is the current state if I turn on anisotropic filtering:
![minetest-text-filtered-broken](https://github.com/minetest/minetest/assets/60905/65aaf93f-daaf-4079-930b-616a91852683)

**Comment by NathanSalapat** [comment] 2023-11-18 15:14
I would be inclined to think that this should be made a server/game/mod choice. Seeing as how shadows were treated in that, it would follow suite to make other graphics options the same way, for good or for bad.
After all allowing people to turn on blurring could break a game, just like letting a player turn on shadows could break a game. Just saying.

**Comment by Warr1024** [comment] 2023-11-19 01:44
To clarify: I have only very minor concerns about the fact that linear UPSCALING is not available anymore; I actually prefer the "crisp" look, for the games I'm involved with, and texture_min_size and such were always hacks to make it look more crisp with linear scaling enabled.

However, the loss of linear DOWNSCALING is pretty bad.  At minimum, it ruins the quality of screenshots, and with high enough contrast in textures, it can even become noticeable and very distracting during normal play.

**My settings, everything tuned up to the "max" possible:**

![image](https://github.com/minetest/minetest/assets/324806/59749bbe-4c58-43b0-9e98-d22dfddf6749)

**Screenshot in 5.8.** Moire patterns visible along the right and bottom of this screenshot.  Mipmapping and trilinear *downscaling* should have been sufficient to prevent that, but are apparently broken.

![image](https://github.com/minetest/minetest/assets/324806/90d184b8-c7b0-4c2b-bbfa-966886693782)

**Same scene in 5.7.**  Note that the moire patterns are gone; this is how this scene is supposed to look.

![image](https://github.com/minetest/minetest/assets/324806/bd46d0ed-f1c1-4bbb-ac02-0add690a8296)

**Comment by Desour** [comment] 2023-11-19 11:08
Interesting. I haven't been able to reproduce this though.

It looks rather to me that the texture min size is hindering the antialiasing.

Screenshots (using checkerboard png test nodes from devtest):
<details>

Mip + bilin + trilin + aniso 5.7:
![allon_5_7](https://github.com/minetest/minetest/assets/7613443/2c21ea25-4b6f-4302-a799-4cb5691ce5a6)

Mip + bilin + trilin + aniso 5.8:
![allon_5_8](https://github.com/minetest/minetest/assets/7613443/822d4315-98d4-4fcf-8428-cb6eb976128b)

Mip + aniso 5.8:
![aniso_5_7](https://github.com/minetest/minetest/assets/7613443/6a2edbb3-6486-44fd-90d3-6be1de63c0ca)

Mip + aniso 5.7:
![aniso_5_8](https://github.com/minetest/minetest/assets/7613443/f8a63bb6-0b04-4f59-84fa-9669a285866f)

</details>

(GPU: AMD vega 8)

**Closed** 2023-11-29 20:09 UTC
Labels: Bug, Blocker, @ Client / Audiovisuals
