### ISSUE TITLE
Keypress from dead keys ignored

### ISSUE THREAD

**Issue by yw05** [minetest/minetest#11053] opened 2021-03-11 13:44 UTC
##### Minetest version
```
Minetest 5.5.0-dev-75eb28b95 (Linux)
Using Irrlicht 1.9.0mt0
Using LuaJIT 2.0.5
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=0
USE_FREETYPE=0
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware
Operating system: Arch Linux
CPU: Intel(R) Core(TM) i5-3337U

##### Summary
Older versions of Minetest (e.g. 5.4.0) did not handle dead keys correctly. The corresponding diacritic marks were typed onto the screen (e.g. `^a` instead of `â`). The current dev version appears to completely ignore dead keys in input boxes (e.g. `a` instead of `^a` or `â`)

##### Steps to reproduce
* Switch to a keyboard layout with dead keys
* Use any input field
* In the input field, hit a dead key and a letter which can normally be used with the diacritic mark.

**Comment by SmallJoker** [comment] 2021-03-11 13:47
Dupe of #6573

**Closed by SmallJoker** 2021-03-11 13:47 UTC
Labels: Unconfirmed bug

**Comment by yw05** [comment] 2021-03-11 13:52
Should I note the different behavior on that thread then?
