### ISSUE TITLE
Problems on servers since "Tool specific pointing and blocking pointable type" (5958714) but works in singleplay

### ISSUE THREAD

**Issue by blaboing** [minetest/minetest#14299] opened 2024-01-23 20:53 UTC
### Minetest version

```true
Minetest 5.9.0-dev-5958714
```

### Operating system and version

Win10

### Summary

[#5958714](https://github.com/minetest/minetest/commit/59587143091a150ac496b20c2cddab9352c6d3fe) works fine in singleplayer but has problems on public servers(tested YourLand 5.7.0, WunderWelt 5.8.0, Archtec 5.8.0).
For most things I don´t get a selectionbox at all. strangely some stuff that shouldnt be pointable are with that commit, for example wielded light source nodes.

### Steps to reproduce

use 5.9.0-dev-5958714 on one of the public servers

**Comment by appgurueu** [comment] 2024-01-23 21:13
Can reproduce. I believe this is due to "older" servers sending the `pointable` bool as u8 (0 = false, 1 = true), but the new enum has 0 = POINTABLE and 1 = POINTABLE_NOT. This completely breaks the game so is high priority.

Note to self & other core devs: We should test more outside of devtest singleplayer. It might be good to have a dedicated "tester" team to not have regression testing eat even more of the already scarce review time.

**Comment by appgurueu** [comment] 2024-01-23 21:17
Here's my proposed fix: https://gist.github.com/appgurueu/daaf1cf647fcd89d531287339d3b4e9f

**Comment by Sokomine** [comment] 2024-01-23 22:04
While testers are in general good to have, perhaps a dedicated team isn't necessary. Most of the time the latest dev version works just fine.

In this case it didn't. But was noted very soon by those of us who play on servers and taken care of quickly. So all fine.

The patch from [appgurueu](https://github.com/appgurueu) fixes the issue for me.

**Comment by appgurueu** [comment] 2024-01-23 22:31
Fixed in https://github.com/minetest/minetest/commit/6a2eb4da07aef285bdd1a0f609b98f74f1990835.

**Closed by appgurueu** 2024-01-23 22:31 UTC
Labels: Bug, High priority, Regression
