### ISSUE TITLE
Extend hardware colorting somehwere else

### ISSUE THREAD

**Issue by LandonAConway** [minetest/minetest#10950] opened 2021-02-14 01:56 UTC
## Problem

Move harware colonization somewhere else. If wanted to create nodes that can rotate or use another type of paramtype2, I cannot. This is extreemely uncreative and annoying. Isn't there some way to extend this? I know you can only do 8 colors if you want to rotate the node and use color but there needs to be the option to do more than that without registering a bunch of nodes for more colors.

## Solutions

Create param3 and paramtype3 or something.

Orrr... extend the paramtype2 for rotation and colors at the same time to use palettes that can use 256 colors (16x16 image palettes) instead of only 8 colors.

## Additional context
Why do I need 256 colors? Why not? Is creativity a bad thing?

If your argument for not adding this feature is "why do you need 256 colors?", then why did you create the ability to have this many colors for a normal node in the first place? You should have only made it 8 colors, or should have made the colorwallmounted also 256 colors.

If I could change this and submit a pull request I would but I don't know how to use c++, and I dont want to learn it just to make this possible.

I didn't spend much time writing this or putting much of my coding knowledge of the API this becuase I'm frustrated. My apologies.

**Comment by SmallJoker** [comment] 2021-02-14 12:20
Duplicate of #6979, #6663

**Closed by SmallJoker** 2021-02-14 12:20 UTC
Labels: Feature request
