### ISSUE TITLE
Multiple worlds in one server

### ISSUE THREAD

**Issue by FlameFireling** [minetest/minetest#7523] opened 2018-07-01 17:35 UTC
##### Issue type

 - Feature request
 
##### Minetest version

```

```

##### OS / Hardware

Operating system:
CPU:

GPU model:
OpenGL version:

##### Summary
Multiple worlds in one server like: you have worlds you can teleport to from the main server world and the server owner creates new ones in real-time

**Comment by rubenwardy** [comment] 2018-07-01 17:41
Duplicate of #4428

**Closed by rubenwardy** 2018-07-01 17:41 UTC

**Comment by Emojigit** [comment] 2020-12-10 08:41
I think this is a better solution then #4428
