### ISSUE TITLE
Torches can be placed underwater

### ISSUE THREAD

**Issue by Diplomousie** [minetest/minetest#2656] opened 2015-04-28 01:19 UTC
Using version 0.4.12 for Windows 7 (32-bit)  I found that I was able to put torches underwater.  

![screenshot_847254964](https://cloud.githubusercontent.com/assets/12144964/7361224/135a578a-ed23-11e4-8cd2-3bae296b0515.png)

**Comment by RHRhino** [comment] 2015-04-28 06:37
Hi Diplomousie! 
Yes this was always possible - this is not a bug, just a missing feature. I think I already saw a mod in the forum which stops this behaviour, but I can't find it right now. This issue should also be posted in minetest_game instead of minetest (=engine). 

I also think this has already be discussed a while ago - wasn't it the problem, that changing this behaviour would break existing maps? I can't remember it ... -.-

**Comment by proller** [comment] 2015-04-28 10:02
fixed in freeminer ;)

**Comment by rubenwardy** [comment] 2015-04-28 10:41
This should probably be on minetest/minetest_game issues.

**Comment by PilzAdam** [comment] 2015-04-28 11:02
Duplicate of #47.

**Closed by PilzAdam** 2015-04-28 11:02 UTC
