### ISSUE TITLE
Android 7.0: Media processing very slow during world load, packet quota errors shown in debug.txt

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#10649] opened 2020-11-19 19:01 UTC
##### Minetest version

```
5.3.0 (from Play Store)
```

##### OS / Hardware

Operating system: Android 7.0 (Huawei Honor 7 Lite, Model NEM-L21)
CPU: HiSilicon Kirin 650

##### Summary

During the first game load, the media data processing is very slow, errors about packed quota shown in debug.txt. It might take several minutes some times. Any subsequent  game load works fine. After clearing app cache and restarting the game the issue repeats again. Screenshot:
![Screenshot_20201119-203909](https://user-images.githubusercontent.com/6626242/99710081-c9983580-2aa8-11eb-8d5f-9bf6d0d104fe.png)

<details>
<summary>debug.txt contents</summary>

```


-------------
  Separator
-------------

2020-11-19 20:26:04: ACTION[Main]: World at [/storage/emulated/0/Minetest/worlds/Test]
2020-11-19 20:26:04: ACTION[Main]: Server for gameid="minetest" listening on 0.0.0.0:57177.
2020-11-19 20:26:07: WARNING[ConnectionSend]: con(60/1) Packet quota used up for peer_id=2, was 5 pkts
2020-11-19 20:26:07: WARNING[ConnectionSend]: con(60/1) Packet quota used up for peer_id=2, was 5 pkts
2020-11-19 20:26:07: WARNING[ConnectionSend]: con(60/1) Packet quota used up for peer_id=2, was 5 pkts
2020-11-19 20:26:08: WARNING[ConnectionSend]: con(60/1) Packet quota used up for peer_id=2, was 19 pkts
2020-11-19 20:28:56: WARNING[Main]: Irrlicht: Could not create ITexture, texture needs to have a non-empty name.
2020-11-19 20:28:59: ACTION[Server]: singleplayer [127.0.0.1] joins game. List of players: singleplayer
2020-11-19 20:29:06: ACTION[Main]: Server: Shutting down


-------------
  Separator
-------------

2020-11-19 20:31:01: [Main]: Automatically selecting world at [/storage/emulated/0/Minetest/worlds/Test]
2020-11-19 20:31:03: ACTION[Main]: World at [/storage/emulated/0/Minetest/worlds/Test]
2020-11-19 20:31:03: ACTION[Main]: Server for gameid="minetest" listening on 0.0.0.0:64054.
2020-11-19 20:31:06: WARNING[Main]: Irrlicht: Could not create ITexture, texture needs to have a non-empty name.
2020-11-19 20:31:06: ACTION[Server]: singleplayer [127.0.0.1] joins game. List of players: singleplayer
2020-11-19 20:32:11: ACTION[Main]: Server: Shutting down


-------------
  Separator
-------------

2020-11-19 20:35:44: [Main]: Automatically selecting world at [/storage/emulated/0/Minetest/worlds/Test]
2020-11-19 20:35:47: ACTION[Main]: World at [/storage/emulated/0/Minetest/worlds/Test]
2020-11-19 20:35:47: ACTION[Main]: Server for gameid="minetest" listening on 0.0.0.0:55162.
2020-11-19 20:35:50: WARNING[Main]: Irrlicht: Could not create ITexture, texture needs to have a non-empty name.
2020-11-19 20:35:50: ACTION[Server]: singleplayer [127.0.0.1] joins game. List of players: singleplayer
2020-11-19 20:35:59: ACTION[Main]: Server: Shutting down


-------------
  Separator
-------------

2020-11-19 20:36:42: ACTION[Main]: World at [/storage/emulated/0/Minetest/worlds/World]
2020-11-19 20:36:42: ACTION[Main]: Server for gameid="minetest" listening on 0.0.0.0:57908.
2020-11-19 20:36:45: WARNING[Main]: Irrlicht: Could not create ITexture, texture needs to have a non-empty name.
2020-11-19 20:36:45: ACTION[Server]: singleplayer [127.0.0.1] joins game. List of players: singleplayer
2020-11-19 20:37:12: ACTION[Main]: Server: Shutting down


-------------
  Separator
-------------

2020-11-19 20:38:33: ACTION[Main]: World at [/storage/emulated/0/Minetest/worlds/World]
2020-11-19 20:38:33: ACTION[Main]: Server for gameid="minetest" listening on 0.0.0.0:51556.
2020-11-19 20:38:36: WARNING[ConnectionSend]: con(78/1) Packet quota used up for peer_id=2, was 5 pkts
2020-11-19 20:38:36: WARNING[ConnectionSend]: con(78/1) Packet quota used up for peer_id=2, was 5 pkts
2020-11-19 20:38:37: WARNING[ConnectionSend]: con(78/1) Packet quota used up for peer_id=2, was 5 pkts
2020-11-19 20:38:37: WARNING[ConnectionSend]: con(78/1) Packet quota used up for peer_id=2, was 5 pkts
2020-11-19 20:41:11: WARNING[Main]: Irrlicht: Could not create ITexture, texture needs to have a non-empty name.
2020-11-19 20:41:13: ACTION[Server]: singleplayer [127.0.0.1] joins game. List of players: singleplayer
2020-11-19 20:41:48: ACTION[Main]: Server: Shutting down
```

</details>

##### Steps to reproduce

1. Install minetest from Google Play Store if not already installed
2. (Optionally) Clear game data and delete/rename Minetest folder if it exist, also minetest app data must be cleared if the folder was deleted, otherwise the game would fail to start.
3. Launch the game, confirm permissions asked
4. Create a new world or use existing one, start a game using selected world
5. Notice how slow game loads, hangs during media phase
6. After game finish load, exit to os, close app window using android task managed, restart game, world should load ok.
7. Exit game again, close window using the task manager, clear minetest cache using android tools, restart game, world loading slow again

**Comment by sfan5** [comment] 2020-11-19 19:08
duplicate of #9107

**Closed by sfan5** 2020-11-19 19:08 UTC
Labels: Unconfirmed bug
