### ISSUE TITLE
Perlin noise: Fix and improve documentation of when world seed is added to noiseparams seed

### ISSUE THREAD

**Issue by pyrollo** [minetest/minetest#9651] opened 2020-04-12 16:07 UTC
##### Minetest version
```
Minetest 5.3.0-dev-6cf15cf8-dirty (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/local/share/minetest"
```

##### Summary
When using `minetest.get_perlin_map`, world seed is added to noise param seed as told in lua_api.txt:
```
When used in mapgen this is actually a 'seed offset', it is added to the
'world seed' to create the seed used by the noise, to ensure the noise has a
different pattern in different worlds.
```

When using `PerlinNoiseMap` this addition is not done.

Sample code to test the difference:

```
local np = {scale = 1, spread = {x = 16, y = 16, z = 16}, seed = 57347, octaves = 2, persist = 0.5, }

minetest.register_on_generated(function()
	print(PerlinNoiseMap(np, { x=1, y=1 }):get_2d_map_flat({ x=0, y=0 })[1])
	print(minetest.get_perlin_map(np, { x=1, y=1 }):get_2d_map_flat({ x=0, y=0 })[1])
end)
```
This prints out to the console result of the same noise, on the same position. Results are different.

This should be either fixed or documented. I don't know if there is a good use case for PerlinNoise not using world seed. Following line is in `ModApiEnvMod::l_get_perlin` (l_env.cpp) but not in `LuaPerlinNoise::create_object` (l_noise.cpp):

```params.seed += (int)env->getServerMap().getSeed();```

**Comment by An0n3m0us** [comment] 2020-04-14 17:57
Confirmed on `5.3.0-dev-7e21b3c-dirty`

Got different results for each of the print commands, like the OP says. Example:
```
-1.1739890575409
0.51084488630295
```

On another world:
```
-1.1739890575409
-0.23597431182861
```

On a third world:
```
-1.1739890575409
-0.58920812606812
```

I used the same mapgen for each world; `v7`

Notice that `print(PerlinNoiseMap(np, { x=1, y=1 }):get_2d_map_flat({ x=0, y=0 })[1])` prints the same value for each of the worlds. I don't know much about how noise works, so I'm not sure if it's supposed to the same or not.

**Comment by paramat** [comment] 2020-04-14 19:39
2 noisemap functions, one adding world seed, the other not doing so, is intentional. So i think this is a documentation issue.

Single noise calls have 2 versions, where 'seed' in the noiseparams is interpreted as a 'seeddiff' in one version, as hinted by 'seed' and 'seeddiff':
https://github.com/minetest/minetest/blob/62c62f382984bd1a6f5cd7c6edb00453ff758f9b/doc/lua_api.txt#L6206-L6213
Noisemap functions also have 2 versions, where 'seed' in the noiseparams is interpreted as a 'seeddiff' in one version.
https://github.com/minetest/minetest/blob/62c62f382984bd1a6f5cd7c6edb00453ff758f9b/doc/lua_api.txt#L6220-L6226

So my documentation:
https://github.com/minetest/minetest/blob/62c62f382984bd1a6f5cd7c6edb00453ff758f9b/doc/lua_api.txt#L3253-L3255
Needs updating to make clear that in some noise functions the seed will be interpreted as absolute, in other noise functions, as a value added to world seed.

**Comment by paramat** [comment] 2020-04-14 21:39
> Notice that print(PerlinNoiseMap(np, { x=1, y=1 }):get_2d_map_flat({ x=0, y=0 })[1]) prints the same value for each of the worlds. I don't know much about how noise works, so I'm not sure if it's supposed to be the same or not.

This is correct behaviour, as world seed is not being added to the user-specified seed value.

**Comment by paramat** [comment] 2020-04-14 22:08
Hmm this is interesting ...
https://github.com/minetest/minetest/blob/2d5bd3bf794672285cfc796edebab2f672f2cab0/src/script/lua_api/l_env.cpp#L938-L981
In `minetest.get_perlin()`, noiseparams are read, then world seed is added to the user-specified seed.
But in `minetest.get_perlin_map()`, noiseparams are read, but then seed is set to world seed, the user-specified seed is ignored.
Both are 'world-specific noise', but one is not 'user-specified-seed-specific'. I wonder why, i might look into this.
To late to change it now though, as it would break all Lua mapgen worlds.

**Comment by paramat** [comment] 2020-04-14 22:33
Answer is ... it has just always been this way =) Maybe hmmmm had a good reason.
Lua perlin noise was added in https://github.com/minetest/minetest/commit/5608f12f9b4e77936436048abf01b4d7edc74871
Lua perlin noise map was added in https://github.com/minetest/minetest/commit/75fe948bf7a0dc455b5bf86d818ecac2f67d226c

**Comment by pyrollo** [comment] 2020-04-14 23:27
So there are actually three different behaviors? I agree this should not be changed because of damage it could cause but it is very disappointing to have an inconsistent API. This could be changed on a major version if there is a TODO list to remind it.

**Comment by pyrollo** [comment] 2020-04-15 11:15
> But in `minetest.get_perlin_map()`, noiseparams are read, but then seed is set to world seed, the user-specified seed is ignored.

I'm not sure for this one, it looks like seeds are added later, user seed is passed through noise param and map seed through function argument. To be verified.

**Comment by paramat** [comment] 2020-04-15 17:59
> it looks like seeds are added later, user seed is passed through noise param and map seed through function argument.

Looking at the code again this seems possibly correct. The noise code is complex, i am still trying to trace through it correctly =)

**Comment by pyrollo** [comment] 2020-04-16 16:51
Some extra undocumented stuff (IFAIK) : get_perlin returns nil at load time.

**Comment by paramat** [comment] 2020-04-16 17:01
Traced through code now, i will document the below soon:

Point noise
-----------

PerlinNoise(seed, octaves, persistence, spread)
PerlinNoise(noiseparams)

Effective seed is noiseparams value.

minetest.get_perlin(seeddiff, octaves, persistence, spread)
minetest.get_perlin(noiseparams)

Effective seed is noiseparams value plus world seed.

Noise map
---------

PerlinNoiseMap(noiseparams, size)

Effective seed is noiseparams seed.

minetest.get_perlin_map(noiseparams, size)

Effective seed is noiseparams seed plus world seed.

**Comment by sfan5** [comment] 2020-04-16 17:13
If that is the case, this looks like entirely intended behaviour to me.

The `minetest.*` functions retrieve a noise object relating to the current map, the constructors create an independent object.

**Comment by paramat** [comment] 2020-04-16 17:19
Yes, this is simply unclear and misleading documentation, partly my fault.
Later i might also document if world seed is added for the uses of noise by ores and decorations.

**Comment by paramat** [comment] 2020-04-16 20:04
PR #9693

**Closed** 2020-04-17 08:24 UTC
Labels: @ Documentation, @ Mapgen, Documentation missing / error
