### ISSUE TITLE
Android Client: Function Like Desktop when Mouse is Detected

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/minetest#11275] opened 2021-05-18 18:32 UTC
## Problem

Using a mouse with the Android version is very cumbersome as it still functions like a touch app. Mouse click events are handled the same as touch events.

## Solutions

When an attached mouse is detected (bluetooth or USB), it would be nice if the client functioned just like Desktop versions. Client should capture mouse for movement & show crosshair/target. Left/Right clicks should be handled as `use` & `place` events instead of touches.

In addition, when a keyboard is detected, some of the displayed icons could be removed as keyboard on Android functions very similar to Desktop.

**Comment by Extex101** [comment] 2021-05-27 02:48
I think having a setting would be simpler

**Comment by AntumDeluge** [comment] 2021-05-27 05:25
> I think having a setting would be simpler

Good idea.

**Comment by AntumDeluge** [comment] 2021-05-30 14:21
Related: #10062 (perhaps duplicate?)

**Comment by TheBrokenRail** [comment] 2021-11-01 17:09
This is easier said than done because right now, touchscreen-mode is a compile time choice. To allow changing mode at runtime, you would have move all touchscreen code to depend on a runtime property rather than a macro.

**Comment by jfrederickson** [comment] 2021-12-08 05:02
@TheBrokenRail As a user, that would be nice for more than just Android. I have a Librem 5 and PinePhone and it'd be nice to be able to use the touchscreen controls when undocked on those, but switch to keyboard/mouse controls when docked to an external display. The Android version of Minecraft handles this very well - the moment you start using a mouse/keyboard, it switches to mouse/keyboard mode, and the moment you touch the touchscreen the touch controls pop up onscreen.

I know this is easier said than done, and I know Minetest has significantly less dev resources than Minecraft. But especially for some of the more recent dockable Linux and Android devices, this would be very nice. Devices having only a single input style (whether touchscreen or keyboard/mouse) is becoming less true over time.

**Comment by rubenwardy** [comment] 2022-09-19 17:08
Duplicate of #10062

**Closed by rubenwardy** 2022-09-19 17:08 UTC
Labels: Feature request, Android, @ Client / Controls / Input, Supported by core dev
