### ISSUE TITLE
Games are able to write into global minetest.conf and screw up other games

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#11943] opened 2022-01-08 22:43 UTC
##### Minetest version
```
5.4.0
```

##### Summary
Assume a clean `minetest.conf`, fresh install. Now: If a singleplayer game changes settings with `minetest.settings:set*`, the GLOBAL `minetest.conf` is affected. So this means if you launch game A that changes setting B, and then launch game C that does NOT change setting B (but instead assumes the default value is used), then game C will still have the changed version of setting B, although this is not what game C or the user asked for.

More concrete example: Hades Revisited. It needs to set various mapgen settings for the world, like `water_level = -5`. Now if you launch Hades Revisited, `water_level = -5` is written into `minetest.conf`, so if you launch Minetest Game afterwards (which does not touch `water_level` but is instead built on the assumption the default `water_level` is used, you start with `water_level = -5` instead of the default one, which causes awkward beaches. This is not MTG's fault, it is not MTG's job to fix the global `minetest.conf` that got screwed with by a different game.

Sadly, the player now has to manually repair the "damage" that Hades Revisited caused. This must be done every single time after Hades Revisited was started. This is very frustrating.

There is another problem in that the `minetest.conf` gets more and more polluted with questionable settings over time, without the user's intervention.

As the main developer of Hades Revisited, I really wish I would not have to use `minetest.settings:set*` but I don't know a better way how to set settings without touching the global config.

Now this is just one example, but there are many other games that set settings at runtime liberally, thus constantly screwing with the GLOBAL `minetest.conf` all the time. If I would be very strict as a developer, I would have to avoid setting any settings at runtime ever, but this is obviously not a solution. It is important for many games to force-set certain settings. Common examples include `time_speed` and `enable_damage`.

### The true problem?

I believe the true problem is that Minetest aggressively overwrites your `minetest.conf` when it shouldn't do so. When one game sets a setting, it should not affect other games at all.

Maybe one possible solution to this would be an option for games to set settings temporarily. This means, the setting is only valid for one session and the game must explicitly set it on launch. Maybe this should even be the default behavior because I really can't see a strong reason for games messing with the global `minetest.conf` at all.

Maybe the current behavior is just a bug. My memory is blurry, but I believe a few versions ago, Minetest did not behave like that and did not aggressively write into `minetest.conf`. But I might be mistaken.

**Comment by rubenwardy** [comment] 2022-01-08 22:46
I think the solution to this is #6966 

`minetest.settings:set*`  should only write into world settings, it shouldn't be possible to set global settings and break other games

**Comment by sfan5** [comment] 2022-01-08 23:43
> It needs to set various mapgen settings for the world, like `water_level = -5`. Now if you launch Hades Revisited, `water_level = -5` is written into `minetest.conf`

This is in fact a bug, see #11351 (which has been fixed).
If you want to talk about other global settings games have to set please make that clear. This problem does not exist for mapgen settings.

> As the main developer of Hades Revisited, I really wish I would not have to use `minetest.settings:set*` but I don't know a better way how to set settings without touching the global config.

Which settings are that? The example you named uses `set_mapgen_setting` in your code, which does not suffer from this problem (exception: broken in 5.4, see above).

**Comment by Wuzzy2** [comment] 2022-01-09 16:23
Another setting is `time_speed`, it's a common use case for non-sandbox games (like those from the Game Jam) to want a static daytime with `time_speed 0`. If you set this with `minetest.settings:set()`, it is written into `minetest.conf`.

**Comment by Wuzzy2** [comment] 2022-05-02 13:31
This bug does no longer occur, seems like #11351 fixed it.

**Comment by sfan5** [comment] 2022-05-02 15:43
Well games *can* still mess with user settings by calling `minetest.settings:set()` and setting `time_speed` is still a valid usecase.
The current best practice is to put them into the `minetest.conf` shipped with the game and perhaps warn the user if they don't match the expected value.

**Comment by Wuzzy2** [comment] 2022-05-02 16:27
Does `set()` also save things in `minetest.conf`? Not according to Minetest. So this is fine.

The problem was when games not only temporarily overwrite settings, but the setting changes survive after game shutdown because they were saved in a file. But again, this seems to have stopped. This was what the issue was about.

**Comment by sfan5** [comment] 2022-05-02 16:31
`minetest.settings:set()` will save changes in minetest.conf, yes.

**Comment by Wuzzy2** [comment] 2022-05-02 23:45
Oh.

**Comment by rubenwardy** [comment] 2022-05-03 00:07
I think with that issue fixed, this is now effectively a duplicate of #6966

> I think the solution to this is #6966
> 
> `minetest.settings:set*` should only write into world settings, it shouldn't be possible to set global settings and break other games

**Comment by rubenwardy** [comment] 2022-10-14 09:28
Duplicate of #6966

**Closed by rubenwardy** 2022-10-14 09:28 UTC
Labels: Bug, @ Script API
