### ISSUE TITLE
Add a "reserved slot" system for multiplayer servers

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#4927] opened 2016-12-18 16:50 UTC
There should be a reserved slot system for multiplayer servers, so that administrators, moderators or "VIP" players can join a server even if it's full.

What about adding a `max_reserved_slots` setting that does that? A privilege like `join_reserved` could be used for this (perhaps a better name can be found).

The minetest.conf setting would probably work like this:

- If set to -1, there is no limit on the number of reserved slots.
- If set to 0, reserved slots are disabled. This can be useful to temporarily disable the mechanism, without revoking the `join_reserved` privilege of all players that have it.
- If set to a value above 0, then N reserved slots will be available depending on the number entered.

Lastly, the number of reserved slots should not be counted towards the "max. players" column of the server list, so that users don't try to join servers that look non-full, but are actually full (this is currently a problem with all "reserved slot" mods).

**Comment by IhrFussel** [comment] 2016-12-18 16:57
That sounds like a very good idea.

Admins and moderators for example should always be able to join the server no matter how full it is.

**Comment by rubenwardy** [comment] 2016-12-18 18:23
Admins and moderators can already join the server no matter how full it is - however it's not a reserved slot system

**Comment by dsohler** [comment] 2016-12-18 22:03
> Admins and moderators can already join the server no matter how full it is

As far as I understand that is for “important players” that are not admins or moderators.

**Comment by Zeno-** [comment] 2016-12-19 05:55
What is an admin if not someone with "server" and/or "privs"?

**Comment by DS-Minetest** [comment] 2016-12-20 16:09
the server owner should decide who is contained in the “important players” list
but in this times there are so many _unneeded_ players that the admin/owner knows who is important but doesnt want to give those players such _mighty_ privs
it would be good if there was another priv for that thats checked instead of `server`, `ban` or `privs`, `password`

**Comment by raymoo** [comment] 2016-12-21 13:41
Would allow server operators to sell reserved slots as a microtransaction.

**Comment by dsohler** [comment] 2016-12-21 13:49
I'd keep the privilege short and neutral as the the other privileges. Maybe simply `vip`. And then validate if the user is either admin (`server` and `privs`) or a "VIP" user and let the user log in regardless of available slots.

**Comment by DS-Minetest** [comment] 2016-12-21 14:12
vip would be a good name because it means that these players are more important than the others

**Comment by rubenwardy** [comment] 2016-12-21 14:44
It's not a descriptive name. I also think this should be done by a mod which reserves a  few user slots

**Comment by dsohler** [comment] 2016-12-21 15:29
> It's not a descriptive name.

Yeah, but `server` is? "VIP" is commonly used and everyone who does not live unter a rock knows it's meaning.

> I also think this should be done by a mod which reserves a few user slots

Why?

**Comment by rubenwardy** [comment] 2016-12-21 16:25
Nobody will know what it means as a privilege. Even if so, it's a bad priv as it describes the player or their rank rather than what their privilege performs. Server isn't a good name, but you can sort of derive that it's server utilities like set and shutdown. So a better name would be userlimit_bypass. If that were to be added it should be the only priv checked, which would break backwards compatibility

If you're going to allow normal users to jump the queue, then it should use a reserved slot system rather than disabling the check - it's still useful to limit players for quality. I'd much rather such a system be done in builtin or a mod - makes it easier for operators to extend

**Comment by raymoo** [comment] 2016-12-22 01:08
>queue

Taken literally, this is another nice feature idea

**Comment by dsohler** [comment] 2016-12-22 08:04
> Even if so, it's a bad priv as it describes the player or their rank rather than what their privilege performs

Okay, that's understandable to have permissions describe what they're for. So let's call it `userlimit_bypass` or `bypass_userlimit` or `bypass_queue` (if MT had one).

But then be consequent with naming and rename `server` (describing a service or device) to `manage_server` (descriptive name) and `privs` to `manage_privileges` and so on (and use the current name as alias for the new name to not break backwards compatibility but mark them as deprecated.)

But I still don't get why all privileges are in core but this one privilege should not be in core.

**Comment by rubenwardy** [comment] 2016-12-22 13:04
Most of the privileges you mentioned there are in builtin

**Comment by dsohler** [comment] 2016-12-22 14:08
You said "I also think this should be done by a mod". And I asked why it should be done by a mod and not "in the core" (i.e. like the other privileges). If "builtin" is one of the standard mods that are used to provide MT's base functionality then yes, it should be done there.

**Comment by jdc843** [comment] 2016-12-27 02:07
I have the reserved_slots_enhanced mod [WIP] in use on the Cash's World server.
This mod is based on what Lag the admin of the now-defunct JustTest server used on his server.
I have given a few players this priv. Some I wanted to always be able to connect and some that timed out while we were doing things together and couldn't log in again because of a full player load.
While this mod works as intended, other players can type /privs playername to see that someone has that priv. This very often causes jealousy problems. Especially when I forgot to revoke the priv after we are finished whatever we were doing.

I want to suggest that if the reserved_slot ability is placed into the main server code that you also consider adding this feature:
Allow players that time out to be given priority for logging back in again. Give them a short amount of time to be able to log in again before they lose their priority 'priv'. Make this time configurable in the game's conf file.

If I had this system, the jealousy problems would be reduced.

**Comment by sorcerykid** [comment] 2017-01-09 17:56
I favour the addition of a privilege for this purpose. However, I believe that there needs to be standardization to the naming scheme. Either privileges should be verbose or they should be terse. We have privileges with names that are misleading (i.e. shout), that are ambiguous (i.e. basic_privs), and that are lengthy, albeit restrictive (i.e. protection_bypass). Personally speaking, I prefer names to be as succinct as possible since privileges are only of concern to administrators. They should be meaningful and memorable, but not overly descriptive so as to limit extensibility. As well, shorter privilege names are easier to type and they consume less space in the auth database. Just some considerations.

**Comment by nerzhul** [comment] 2017-01-09 18:35
in fact we can do better for mods i think, why not replace the mentioned call with priv with a setting containing a privilege list allowed to bypass ? this permits everybody to have its own priv system

**Comment by ShadowNinja** [comment] 2017-01-13 07:00
You could make this just call Lua and let builtin handle it.

**Comment by garywhite207** [comment] 2017-01-26 23:30
I think a priv should be made to do this, not adding a .conf setting, or else it would end up like @raymoo mentioned

**Comment by Ezhh** [comment] 2017-09-01 19:54
I would really like to see something for this that is not dependant on a player having moderator/admin level privs. It is a HUGE and ongoing issue on one of my servers.

**Comment by paramat** [comment] 2017-09-01 21:13
I'd support this, server owners are suffering, increasingly so due to the number of mobile players, we need to give more powers to them, this would mean quality players who are not necessarily admin or moderators can be given preference.

**Comment by nerzhul** [comment] 2017-09-02 10:26
I'm for it too , implementation should be easy

**Comment by SmallJoker** [comment] 2017-10-19 18:20
Added in #6369.

**Closed by SmallJoker** 2017-10-19 18:20 UTC
Labels: @ Server / Client / Env., Feature request
