### ISSUE TITLE
common folder for schematics

### ISSUE THREAD

**Issue by Ygarr** [minetest/minetest#12748] opened 2022-09-06 17:30 UTC
Usually folder for .mts .we schems is “worlds/<my_world>/schems”

Can there be common, global  folder for using(import+export) in any world? E.G. For not to duplicate schems files in each world.

**Comment by MrRar** [comment] 2022-09-07 18:48
Maybe make it just a general global user data folder.

**Comment by appgurueu** [comment] 2022-09-09 13:09
The answer is yesn't. WorldEdit could write to its modpath (with some limitations) or an outside path (for which it'd have to request an insecure environment).

Where WorldEdit stores schematics is unrelated to Minetest though; it concerns only the [WorldEdit](https://github.com/Uberi/Minetest-WorldEdit) mod.

**Comment by rollerozxa** [comment] 2022-09-09 13:40
Really what should be added would be a world-independent mod data folder for each mod to put their own files into.

**Comment by rubenwardy** [comment] 2022-09-09 13:56
Duplicate of #4821

**Closed by rubenwardy** 2022-09-09 13:56 UTC
Labels: @ Startup / Config / Util, Feature request

**Comment by MrRar** [comment] 2022-09-09 14:46
> Really what should be added would be a world-independent mod data folder for each mod to put their own files into.

Sometimes different mods work with the same files. For example schematics are used by different mods.

**Comment by rubenwardy** [comment] 2022-09-09 15:40
> > Really what should be added would be a world-independent mod data folder for each mod to put their own files into.
> 
> Sometimes different mods work with the same files. For example schematics are used by different mods.

In this case, one of the mods can expose an API

**Comment by MrRar** [comment] 2022-09-09 16:28
> > Sometimes different mods work with the same files. For example schematics are used by different mods.
> 
> In this case, one of the mods can expose an API

Then all the other mods will have to depend on this one mod. Maybe some users don't want the schematic storing mod. But I guess you could have a dummy mod that does nothing but store schematics.
