### ISSUE TITLE
Dungeons generator: rooms are often intersects

### ISSUE THREAD

**Issue by alek13** [minetest/minetest#14331] opened 2024-01-31 14:09 UTC
### Minetest version

```true
Minetest 5.8.0 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
```

### Operating system and version

Kubuntu 23.10

### Summary

It s often, when generating dungeons, their rooms intersects. This looks very ugly
![image](https://github.com/minetest/minetest/assets/1972329/6d95b75e-e511-4052-bf10-b76e89cabf24)

It will be better if  there is an additional node (wall/floor/ceil) between the rooms.

### Steps to reproduce

1. Create new world & ensure that dungeons generation flag for world is on.
2. In game: `/grantme fly,fast,noclip` 
3. Fly to underground & find dungeons

**Comment by v-rob** [comment] 2024-02-09 20:37
This is a very difficult problem to solve from a technical point of view.  Sometimes, two dungeons will generate on top of each other, causing even more mayhem.

However, given that even normal dungeons have haphazard room/passage layouts, I am of the opinion that self-intersecting dungeons should not be considered a bug any more than intersecting caves are a bug.

**Comment by alek13** [comment] 2024-02-17 16:57
Why? Just only because it's difficult to solve ?
Maybe it's difficult to solve, maybe it's not the first priority (maybe it's very very low priority), but it's a bug!

**Comment by v-rob** [comment] 2024-02-17 18:52
> but it's a bug

Arguably, it's not a bug, as I said previously.

Moreover, "difficult to solve" might be an understatement.  Given how the dungeon code works (pseudo-random numbers choose the direction of passages and rooms), it is more correct to say "impossible without a complete rewrite".  And even then, it's hard to tell how unacceptably complex/potentially slow the rewritten code may be.

In general, I am opposed to doing much of anything with dungeons.  They're the sort of thing that shouldn't be hardcoded into the engine at all, but provided via mods.  We have to keep them for backwards compatibility, but we don't want to go complicating the code for them.

**Comment by appgurueu** [comment] 2024-02-18 12:04
Bug or not, I agree that this is definitely low-priority and non-trivial, and likely in conclusion "won't fix / implement". Mapgen needs to be fast and backwards-compatible, which complicates this. This would have to be behind a new mapgen flag or similar.

I agree that design-wise, it would be better to let mods generate their own dungeons as they see fit. This should be facilitated by the [recent addition of multi-threaded mapgen by sfan5](https://github.com/minetest/minetest/commit/3cac17d23e2e0bfe74f1f627a4e206fec981fa4a).

**Comment by SmallJoker** [comment] 2024-02-19 18:19
FWIW: There's already a mechanism to reserve dungeon-generated mapblocks within the VManip:
https://github.com/minetest/minetest/blob/4acbd5916262196ce090a81123c8803d9c54b396/src/mapgen/dungeongen.cpp#L282-L303

It just happens that most of the room generator functions do not check the space ahead of time to avoid collisions.

**Closed** 2024-06-05 18:50 UTC
Labels: Unconfirmed bug, Won't fix, Non-trivial, @ Mapgen, Low priority, Possible close
