### ISSUE TITLE
Glass invisible if viewed through other glass

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#4208] opened 2016-06-10 15:47 UTC
If you view homedecor:stained_glass through homedecor:window_plain you the stained glass is not rendered.

Tested with .14-dev (current commit), .14-stable and .13-dev (not sure which commit, someone on the server helped).
Images:

![screenshot_20160610_173920](https://cloud.githubusercontent.com/assets/1377943/15970086/2c7ac97c-2f33-11e6-9c97-2ccec6c6efe6.png)
![screenshot_20160610_173924](https://cloud.githubusercontent.com/assets/1377943/15970085/2c7a9966-2f33-11e6-8213-e079900b08af.png)
![screenshot_20160610_173931](https://cloud.githubusercontent.com/assets/1377943/15970084/2c7aa866-2f33-11e6-9f3a-34a79a1e9f44.png)

**Comment by Thomas--S** [comment] 2016-06-10 17:43
This is the famous `use_texture_alpha = true` bug.

**Comment by Fixer-007** [comment] 2016-06-10 18:13
Famous bug needs famous bugfixer.

**Comment by paramat** [comment] 2016-06-10 19:28
Another duplicate of #95 
Modders shouldn't be using translucency.

**Closed by paramat** 2016-06-10 19:28 UTC
Labels: @ Client / Audiovisuals, Duplicate
