### ISSUE TITLE
Minetest.apk build failure

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#4005] opened 2016-04-18 03:01 UTC
For a while now, all my attempts to build the Minetest apk have met with this error: http://paste.ubuntu.com/15906887/. Also, here is the config.log file referenced within: 
[config.log.txt](https://github.com/minetest/minetest/files/223006/config.log.txt).

I have followed the instructions on the dev wiki exactly, on not only my main OS (Linux Mint 17.3 x64) but several VMs as well. (On a somewhat related note, it may be worth noting that I have to manually search for and install both the libgd2-xpm and ia32-libs-multiarch packages, as apt-get returns no results.) Have there been any recent changes not reflected on the wiki, or is there something else I may be missing?

**Comment by nerzhul** [comment] 2016-04-18 09:23
@Wayward1 didn't notice this problem in my APK build, but i'm using Curl 7.48.0

**Comment by paramat** [comment] 2016-04-20 01:04
Blocker for release?

**Comment by Zeno-** [comment] 2016-04-20 02:45
I cannot build on Ubuntu unless I revert 096a01f ... so either the documentation needs updating or it should be fixed or it should be reverted before release

**Comment by Zeno-** [comment] 2016-04-20 04:10
Works on Fedora 21 and 23

I wonder if Ubuntu and Debian are somehow using the wrong Android NDK version (i.e. because it adds a newer version of the toolchains to $PATH and it's using the wrong compiler)?

**Comment by nerzhul** [comment] 2016-04-20 06:52
@Zeno- if you find the dependency problem could be good. Yes blocker for me for release

**Comment by nerzhul** [comment] 2016-04-20 06:53
Please note i don't have problems with building curl 7.48.0 for Android.

**Comment by Wayward1** [comment] 2016-04-20 13:19
It still fails for me with cURL 7.48.0

**Comment by Zeno-** [comment] 2016-04-21 02:52
Have comments from this issue been deleted?

**Comment by Wayward1** [comment] 2016-04-21 04:00
Nope, not to my knowledge. I recieve notifications for each comment

**Comment by est31** [comment] 2016-04-21 14:06
@Wayward1 can you perhaps try to bisect? If its a regression, it can be easily found that way.

**Comment by Zeno-** [comment] 2016-04-21 14:42
@est31 Warr bisected it but I don't know why his comments are not here anymore :/

**Comment by Warr1024** [comment] 2016-04-21 17:22
On Debian 8 (Linux 3.16.0-4-amd64 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux):

I **was not** able to get it to build, using either NDK r10d or r10e, and was getting the same error as above ("cannot run C compiled programs" in the curl dependency).

I bisected, and found the problem commit to be 096a01ffef032a11239bd97e548a9ebb3c6add4a.  I **was** able to get it to build, using either NDK r10d or r10e, after reverting that one commit.

**Comment by est31** [comment] 2016-04-22 01:53
I've split up 096a01ffef032a11239bd97e548a9ebb3c6add4a into four smaller commits in this branch: https://github.com/est31/minetest/commits/4005-testing

@Warr1024 has tested the commits, and the [update openssl commit](https://github.com/est31/minetest/commit/45db0547898293e92f0a2369d813b69e4c362026) is the first one that doesn't build anymore.

**Comment by paramat** [comment] 2016-04-23 20:58
@MoNTE48 are you able to help with this?

**Comment by MoNTE48** [comment] 2016-04-23 20:59
sudo apt-get install m4

**Comment by Wayward1** [comment] 2016-04-24 02:35
That's already installed, assuming everyone else followed the instructions on the wiki.

**Comment by est31** [comment] 2016-04-24 03:23
@Wayward1  can you test whether the last commit fixes the bug:
https://github.com/est31/minetest/commits/master

**Comment by MoNTE48** [comment] 2016-04-24 04:05
Strange. Please, make clean_all && make openssl and write error, I want to know which package is missing on your system.

**Comment by Wayward1** [comment] 2016-04-24 22:14
@MoNTE48: http://paste.ubuntu.com/16041389/

@est31 nope, it gives this error: http://paste.ubuntu.com/16041332/

**Comment by MoNTE48** [comment] 2016-04-24 22:17
Fuck... 
pls, make clean_all && make gmp && make openssl

**Comment by Wayward1** [comment] 2016-04-24 22:43
@MoNTE48: http://paste.ubuntu.com/16041738/

**Comment by MoNTE48** [comment] 2016-04-24 22:46
@Wayward1, "creating ../libssl.a" = build success.
make release -j4 and you get apk

**Comment by MoNTE48** [comment] 2016-04-24 22:50
@est31, https://github.com/MultiCraftProject/MultiCraft/blob/master/build/android/Makefile#L306
:) 
This is a mistake of the one who added gmp. This is your bug https://github.com/minetest/minetest/commit/181f7baa453c58d4070de7196fd74663110946a8

**Comment by Wayward1** [comment] 2016-04-24 23:20
Cool, it indeed built successfully :D

**Comment by MoNTE48** [comment] 2016-04-24 23:31
Have you spent on a solution to this stuff seven days. Guys, I'm really sorry for you. 
@Wayward1, a word of advice, when you use the -j *, reading logs becomes a pain.

**Comment by paramat** [comment] 2016-04-25 03:38
^ @est31 
MoNTE thanks much appreciated.

**Comment by Wayward1** [comment] 2016-04-25 04:00
Yes, thank you MoNTE48 :)

**Comment by paramat** [comment] 2016-04-25 04:06
What's the fix then? Don't understand.

**Comment by paramat** [comment] 2016-04-25 06:15
@MoNTE48 how do we fix this?

**Comment by MoNTE48** [comment] 2016-04-25 06:34
@paramat, I'm glad I could help. :) I wrote the above link to line in multicraft, where correction

**Comment by MoNTE48** [comment] 2016-04-25 12:08
https://github.com/minetest/minetest/pull/4033

**Comment by paramat** [comment] 2016-04-25 13:11
@Wayward1 could you test?

**Comment by Wayward1** [comment] 2016-04-25 13:25
@paramat, will do

**Comment by paramat** [comment] 2016-04-26 09:25
#4033 is merged.

**Closed by paramat** 2016-04-26 09:25 UTC
Labels: @ Build, Android, Bug
