### ISSUE TITLE
Doesn't build on debian jessie

### ISSUE THREAD

**Issue by jkozak** [minetest/minetest#7681] opened 2018-08-27 12:33 UTC
##### Issue type

 - Build issue
 
##### Minetest version

```
v5.0.0-dev
34f940dccae53ac62177d2555c63688fce90519d
```

##### OS / Hardware

Operating system: linux debian jessie
CPU:  i5

GPU model:
OpenGL version:

##### Summary

Build fails

```
CMakeFiles/minetest.dir/convert_json.cpp.o: In function `fetchJsonValue(std::string const&, std::vector<std::string, std::allocator<std::string> >*)':
/home/val/minetest/src/convert_json.cpp:(.text+0x14f): undefined reference to `Json::Value::Value(Json::Value&&)'
CMakeFiles/minetest.dir/serverlist.cpp.o: In function `ServerList::deleteEntry(Json::Value const&)':
/home/val/minetest/src/serverlist.cpp:(.text+0x1c27): undefined reference to `Json::Value::Value(Json::Value&&)'
CMakeFiles/minetest.dir/serverlist.cpp.o: In function `ServerList::sendAnnounce(ServerList::AnnounceAction, unsigned short, std::vector<std::string, std::allocator<std::string> > const&, double, unsigned int, float, std::string const&, std::string const&, std::vector<ModSpec, std::allocator<ModSpec> > const&, bool)':
/home/val/minetest/src/serverlist.cpp:(.text+0x37f2): undefined reference to `Json::Value::append(Json::Value&&)'
/home/val/minetest/src/serverlist.cpp:(.text+0x3b92): undefined reference to `Json::Value::append(Json::Value&&)'
CMakeFiles/minetest.dir/serverlist.cpp.o: In function `void std::vector<Json::Value, std::allocator<Json::Value> >::_M_insert_aux<Json::Value>(__gnu_cxx::__normal_iterator<Json::Value*, std::vector<Json::Value, std::allocator<Json::Value> > >, Json::Value&&)':
/home/val/minetest/src/serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x33): undefined reference to `Json::Value::Value(Json::Value&&)'
/home/val/minetest/src/serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x7e): undefined reference to `Json::Value::Value(Json::Value&&)'
/home/val/minetest/src/serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0xb2): undefined reference to `Json::Value::Value(Json::Value&&)'
/home/val/minetest/src/serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIJS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x170): undefined reference to `Json::Value::Value(Json::Value&&)'
CMakeFiles/minetest.dir/serverlist.cpp.o: In function `void std::vector<Json::Value, std::allocator<Json::Value> >::_M_insert_aux<Json::Value const&>(__gnu_cxx::__normal_iterator<Json::Value*, std::vector<Json::Value, std::allocator<Json::Value> > >, Json::Value const&)':
/home/val/minetest/src/serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIJRKS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIJRKS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x33): undefined reference to `Json::Value::Value(Json::Value&&)'
CMakeFiles/minetest.dir/serverlist.cpp.o:/home/val/minetest/src/serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIJRKS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIJRKS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x7e): more undefined references to `Json::Value::Value(Json::Value&&)' follow
clang: error: linker command failed with exit code 1 (use -v to see invocation)
src/CMakeFiles/minetest.dir/build.make:6625: recipe for target 'bin/minetest' failed
make[2]: *** [bin/minetest] Error 1
CMakeFiles/Makefile2:262: recipe for target 'src/CMakeFiles/minetest.dir/all' failed
make[1]: *** [src/CMakeFiles/minetest.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

[make-minetest-jessie.txt](https://github.com/minetest/minetest/files/2323837/make-minetest-jessie.txt)

**Comment by jkozak** [comment] 2018-08-27 12:37
I hve tried using the compier default (gcc 4.9), and clang 3.5; also the built-in jsoncpp and the system version.  None of these build.

**Comment by rubenwardy** [comment] 2018-08-27 12:55
Added error message to main post, please do that in future

Try

cmake . -DENABLE_SYSTEM_JSONCPP=1

**Comment by jkozak** [comment] 2018-08-27 13:14
Using system `libjsoncpp` (version 1.7.4-3) build fails differently 

```
/home/val/minetest/src/content/mods.cpp: In member function ‘bool ModMetadata::load(const string&)’:
/home/val/minetest/src/content/mods.cpp:447:2: error: ‘CharReaderBuilder’ is not a member of ‘Json’
  Json::CharReaderBuilder builder;
  ^
/home/val/minetest/src/content/mods.cpp:448:2: error: ‘builder’ was not declared in this scope
  builder.settings_["collectComments"] = false;
  ^
/home/val/minetest/src/content/mods.cpp:451:7: error: ‘parseFromStream’ is not a member of ‘Json’
  if (!Json::parseFromStream(builder, is, &root, &errs)) {
       ^
src/CMakeFiles/minetest.dir/build.make:491: recipe for target 'src/CMakeFiles/minetest.dir/content/mods.cpp.o' failed
make[2]: *** [src/CMakeFiles/minetest.dir/content/mods.cpp.o] Error 1
```

**Comment by SmallJoker** [comment] 2018-08-27 13:57
Main report is a duplicate of #6381

**Comment by SmallJoker** [comment] 2018-08-27 14:03
Main report is a duplicate of #4306, #6381 (open) and #6567. Second is a duplicate of https://github.com/minetest/minetest/issues/4306#issuecomment-340230036
Please ensure that you've also installed `libjsoncpp-dev` when building with the system library.

**Closed by SmallJoker** 2018-08-27 14:03 UTC
