### ISSUE TITLE
Content DB: Updating things, version number

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8146] opened 2019-01-30 17:51 UTC
##### Issue type
- Missing feature, I guess?
 
##### Minetest version
5.0.0-dev
d9f5ff42a1c309fde9637aed99f696c499561ddb

##### Summary
The problem I have with the content panel is that the version number is not shown. It is impossible to see for the user whether the user is on the latest version or if the current version is outdated.

Also, “updating” is not directly possible. It seems you have to uninstall and re-install. But this doesn't solve the problem of the version number, because you still don't see whether you're on latest stable.

This is crucial for things that update frequently. MineClone 2, for example, often updated weekly in 2018.

##### Suggestion
Show the version number of all things. Both the current installed one, and the latest available one.
Also, add an update button. This button is a shorthand for “install the latest version and replace the currently installed one”.

**Comment by rubenwardy** [comment] 2019-01-30 17:53
> Also, “updating” is not directly possible. It seems you have to uninstall and re-install. But this doesn't solve the problem of the version number, because you still don't see whether you're on latest stable.

An update button is shown when there is an update

**Comment by LoneWolfHT** [comment] 2019-01-31 03:32
> An update button is shown when there is an update

But you have to search for the mod to realize there's an update for it.
Maybe add 'Updates' to the dropdown which shows 'All packages' in the screenshot?
![image](https://user-images.githubusercontent.com/28972859/52028874-9d6f8700-24c5-11e9-983f-dc3459a43884.png)

**Comment by ClobberXD** [comment] 2019-01-31 10:06
I agree, it's possible to see the update button only when we come across the mod in the content store. I suggest to at least list the installed mods first, and maybe also notify the user on startup about available updates.

**Comment by nerzhul** [comment] 2019-01-31 13:48
having the version somewhere in the title can be nice :)

**Comment by swedneck** [comment] 2019-02-03 20:43
`Mod Name by Author (version)`
feels like a good syntax to me

**Comment by rubenwardy** [comment] 2020-04-30 21:37
Duplicate of #7369

**Closed** 2020-04-30 21:37 UTC
Labels: @ Content/PkgMgr, Feature request, Supported by core dev
