### ISSUE TITLE
add_velocity() causes a no-log-crash if entity exceeds limit

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#10058] opened 2020-06-18 17:02 UTC
##### Minetest version
5.3-dev

##### OS / Hardware

Operating system: Windows 10
CPU: Ryzen 3200 G

##### Summary
add_velocity() causes no log crash if an entity exceeds a certain velocity, I can't tell what this number is in the vector because the game won't print the velocity when crashing.

##### Steps to reproduce
Make an entity go really fast using add_velocity()

**Comment by SmallJoker** [comment] 2020-06-18 18:42
`1E40`:
```
2020-06-18 20:40:11: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'lab' in callback environment_Step(): Invalid float vector dimension range 'x' (expected -2.14748e+06 < x < 2.14748e+06 got inf).
2020-06-18 20:40:11: ERROR[Main]: stack traceback:
2020-06-18 20:40:11: ERROR[Main]: 	[C]: in function 'set_velocity'
```
`1E10`:
```
2020-06-18 20:41:40: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'lab' in callback environment_Step(): Invalid float vector dimension range 'x' (expected -2.14748e+06 < x < 2.14748e+06 got 1e+10).
2020-06-18 20:41:40: ERROR[Main]: stack traceback:
2020-06-18 20:41:40: ERROR[Main]: 	[C]: in function 'set_velocity'
```
`1E6` works. No crashes. Cannot reproduce.

**Comment by SmallJoker** [comment] 2020-09-27 16:42
Please provide a sample code to reproduce this issue.
Close in 1 month and wait for further reports.

**Comment by rubenwardy** [comment] 2020-10-31 18:21
closing as not reproduced

**Closed** 2020-10-31 18:21 UTC
Labels: Possible close, Unconfirmed bug
