### ISSUE TITLE
Using Zstandard for mapblock compression?

### ISSUE THREAD

**Issue by est31** [minetest/minetest#4495] opened 2016-09-02 11:54 UTC
https://github.com/facebook/zstd

We could train zstd for minetest, or use multiple dictionaries per map.

**Comment by Rogier-5** [comment] 2016-09-02 15:49
Thumbs up for replacing zlib !

Speed tests I did for minetestmapper a while ago showed that about 50% (IIRC) of the running time was actually spent in zlib code, decompressing map data...

As the comparison table on the zstd page shows about 25% worse compression for lz4, but with the benefit of a 2-3 times speed increase, I'd welcome an implementation that allows different compression algorithms to be used, so that depending on CPU speed, disk speed and disk size, a server operator can choose for faster or for more compact compression. The actual algorithm that was used should obviously be encoded in a block's data. 

At the same time, instead of only compressing the node data, *all* of the block's data could be compressed. IIRC, one important reason LevelDB databases are often smaller, is that LevelDB uses snappy to compress all data it stores.

**Comment by SmallJoker** [comment] 2016-09-02 17:24
The compression ratio is not much better compared to zlib but for the same ratio it is able to process much more data, that's very nice. I am not sure about the compatibility with our supported OS' but it looks well maintained there.

**Comment by sofar** [comment] 2016-09-02 21:52
I'm suspicious of zstandard's licensing at first, their example code isn't even licensed properly, so you can't even use their example code freely.

I would wait and see in a year or so if this is actually taking off anywhere....

**Comment by sfan5** [comment] 2016-09-19 19:01
If we're going the <i>new shiny stuff™</i> route, we should also consider https://github.com/google/brotli.

**Comment by Megaf** [comment] 2016-10-04 08:50
Why not LZMA then http://www.7-zip.org/sdk.html
Very efficient, huge compression rates and they are adjustable.

**Comment by kahrl** [comment] 2016-10-04 09:07
For the Germans amongst us, here's a relevant blog post: http://blog.fefe.de/?ts=a90c6783

**Comment by sfan5** [comment] 2016-10-04 13:44
Here's a testing branch with brotli support: https://github.com/sfan5/minetest/tree/brotli
All you need is [libbrotli](https://github.com/bagder/libbrotli) ([AUR](https://aur.archlinux.org/packages/libbrotli-git)) and it will automatically compress new worlds with brotli.

**Do not use this branch with your existing worlds, they will become unreadable to a "normal" Minetest.**

**Comment by est31** [comment] 2016-10-04 14:42
Nice work, @sfan5 !

I would prefer zstd over brotli, as it seems to be better, unless its proven to perform worse for our use case.

One problem for both brotli and zstd will be however that we'd have to discontinue support for older distros (like ubuntu 12.04, the one @PilzAdam uses) which don't have the library. Both [brotli](http://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=brotli&searchon=names) and [zstd](http://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=zstd&searchon=names) only first appear in ubuntu 16.04.

Its the same issue as for C++11, all over again :(

Although one could argue that its much much easier to install or download + compile a new library than installing a totally new C++ compiler.

**Comment by sfan5** [comment] 2016-10-04 15:23
@est31
> One problem for both brotli and zstd will be however that we'd have to discontinue support for older distros

Actually *lib*brotli isn't in any package repositories right now afaik, brotli doesn't have an official API (yet). zstd does so we wouldn't have that problem.

**Comment by nerzhul** [comment] 2016-10-04 15:26
i prefer lz4 than zlib, it's very fast and i already have a working version in my own version :). lz4 is cpu free

**Comment by est31** [comment] 2016-10-04 17:26
Bundling might be an idea, yeah.

**Comment by Megaf** [comment] 2016-10-04 18:01
We already bundle jsoncpp, lua, gmp and maybe other things too.

**Comment by nerzhul** [comment] 2016-10-04 18:14
lz4 bundling is easy, 3 files.

**Comment by Megaf** [comment] 2016-10-04 18:58
Sounds good to me, and you guys know how much I like removing things from the core and complaining about too much stuff that Minetest has. but I do like the idea of lz4 being bundled and used by default.
On a side note, would it be possible to port a world from gzip to lz4 back and forth?

**Comment by sfan5** [comment] 2016-10-04 19:53
@est31 @nerzhul 

Benchmark on real data(VanessaE's MG_World) comparing zlib and brotli:

map.sqlite with zlib: 820.3 MB
map.sqlite with brotli: 718.3 MB
&nbsp;&nbsp;reduction: 12.4 %

Here's the steps I took to compare:
```
1) Download and extract MG_World.tar.bz2 from http://daconcepts.com/vanessa/hobbies/minetest.html
2) ./minetestserver --world ./MG_World --migrate sqlite3
3) sqlite3 ./MG_World/map.sqlite 'VACUUM;'
4) du -h ./MG_World/map.sqlite # note down value (zlib) [ 820,3 MB ]
5) ./minetestserver --world ./MG_World --recompress
6) sqlite3 ./MG_World/map.sqlite 'VACUUM;'
7) du -h ./MG_World/map.sqlite # note down value (brotli) [ 718,3 MB ]
```

**Comment by nerzhul** [comment] 2016-10-04 20:05
World size is not very important , but performance

**Comment by sfan5** [comment] 2016-10-04 20:38
@nerzhul 
I chose compression quality 6 (same as zlib's default, but that's not important) because it made the compression unittest take exactly the same duration.

Which means that while performance should be about the same while the world is smaller.

**Comment by Ferk** [comment] 2016-10-04 20:44
@sfan5 is it be possible for you to check the duration for the decompression too? I suspect there's a lot more decompression than compression going on

**Comment by Megaf** [comment] 2016-10-04 20:52
We have to compare those against lz4 now. 
And for me the most important thing should be lower cpu usage/time. Size is secondary.
I will be very happy if the world doesnt get any larger.

**Comment by nerzhul** [comment] 2016-10-04 21:50
@sfan5 noted. I think you should benchmark various mapblock serialization times

**Comment by sfan5** [comment] 2016-10-04 21:54
@Ferk @nerzhul 

```
2016-10-04 23:48:34: ACTION[Main]: ### zlib ###
2016-10-04 23:48:34: ACTION[Main]: Total decompression CPU time:     82.5919s
2016-10-04 23:48:34: ACTION[Main]: Decompression CPU time per block: 0.0315857ms
2016-10-04 23:48:34: ACTION[Main]: Decompression speed (inaccurate): 8181.29 KB/s
2016-10-04 23:48:34: ACTION[Main]: ############
2016-10-04 23:53:30: ACTION[Main]: ## brotli ##
2016-10-04 23:53:30: ACTION[Main]: Total decompression CPU time:     77.9433s
2016-10-04 23:53:30: ACTION[Main]: Decompression CPU time per block: 0.0298079ms
2016-10-04 23:53:30: ACTION[Main]: Decompression speed (inaccurate): 7491.29 KB/s
2016-10-04 23:53:30: ACTION[Main]: ############
```

(please don't mind the decompression speed given, it's calculated over whole MapBlocks instead of just the compressed data)

**Comment by est31** [comment] 2016-10-07 01:13
I've ran the test for my [zstd branch](https://github.com/est31/minetest/tree/zstd). (not the most recent commit, but the commit called "unittest") and got in fact an increase in space required (944148 K with the zlib compression, and 1062140 K with the zstd compression, an increase by 12%). Note that I didn't use a dictionary, while brotli has a hardcoded dictionary, and for the minetest use case a dictionary would be really useful I think, as it perfectly matches the dictionary use case (few KB of data). So there is certainly room for improvement.

The decompression time however is really really great.

For zstd:
```
############
Total decompression CPU time:     19.0198s
Decompression CPU time per block: 7.27373us
Decompression speed:              30393 KB/s
############
```

For zlib:
```
############
Total decompression CPU time:     72.0594s
Decompression CPU time per block: 27.5577us
Decompression speed:              7037.76 KB/s
############
```

A bit odd was that when I rewrote the code to use the streaming API, it suddenly got horribly slow (20x decrease). The benchmarks are from using the non streaming API.

**Comment by sfan5** [comment] 2016-10-07 07:40
> I got in fact an increase in space required. Note that I didn't use a dictionary [...], and for the minetest use case a dictionary would be really useful I think

Brotli supports dictionaries too, I agree that we should try that approach. We might need/want different dicts for block data vs. metadata too.

The problem however is that **every** application that wants to read the Minetest's data needs the same dictionary and we can't ever change the dict. Unless we add dictionary versioning which would also require that applications keep with dict updates done in Minetest.

> A bit odd was that when I rewrote the code to use the streaming API, it suddenly got horribly slow (20x decrease). The benchmarks are from using the non streaming API.

The numbers from using the non-streaming API don't matter, to compare we need the benchmark while using the final design (streaming API).

**Comment by sfan5** [comment] 2016-10-07 12:09
So I did all of the benchmarks again with some improvements I made to the statistics it outputs:

map.sqlite zlib: `820.3 MiB`
map.sqlite brotli: `719.4 MiB` (`12.3%` smaller)

`--recompress`:
```
2016-10-07 13:51:16: ACTION[Main]: ############
2016-10-07 13:51:16: ACTION[Main]: Recompressed blocks:            2614854
2016-10-07 13:51:16: ACTION[Main]: Total data (uncomp.):           4008 MB
2016-10-07 13:51:16: ACTION[Main]: Total compression CPU time:     388.206s
2016-10-07 13:51:16: ACTION[Main]: Compression CPU time per block: 148.462us
2016-10-07 13:51:16: ACTION[Main]: Compression speed:              10573.3 KB/s
2016-10-07 13:51:16: ACTION[Main]: ############
```

Decompression benchmark:
```
2016-10-07 14:05:19: ACTION[Main]: ### zlib ###
2016-10-07 14:05:19: ACTION[Main]: Total blocks:                     2614854
2016-10-07 14:05:19: ACTION[Main]: Total data (comp.):               495 MB
2016-10-07 14:05:19: ACTION[Main]: Total decompression CPU time:     83.7842s
2016-10-07 14:05:19: ACTION[Main]: Decompression CPU time per block: 32.0416us
2016-10-07 14:05:19: ACTION[Main]: Decompression speed:              6052.89 KB/s
2016-10-07 14:05:19: ACTION[Main]: ############
2016-10-07 14:01:56: ACTION[Main]: ## brotli ##
2016-10-07 14:01:56: ACTION[Main]: Total blocks:                     2614854
2016-10-07 14:01:56: ACTION[Main]: Total data (comp.):               406 MB
2016-10-07 14:01:56: ACTION[Main]: Total decompression CPU time:     79.2955s
2016-10-07 14:01:56: ACTION[Main]: Decompression CPU time per block: 30.325us
2016-10-07 14:01:56: ACTION[Main]: Decompression speed:              5246.44 KB/s
2016-10-07 14:01:56: ACTION[Main]: ############

```

**Comment by Fixer-007** [comment] 2016-10-07 13:13
I wonder how faster unpacking will affect stuttering ingame.

**Comment by est31** [comment] 2016-10-09 00:20
> The numbers from using the non-streaming API don't matter, to compare we need the benchmark while using the final design (streaming API).

Yes, only the final design should matter, which is the streaming API one way or another. However, the non streaming API shouldn't be slower that much, meaning that there is either a bug in zstd, or in the code to use it. So the only numbers matter when/if that bug has been removed.

**Comment by sfan5** [comment] 2016-10-09 13:13
@est31 

The slowness with using the streaming API might be caused by the need to call `unget()` on the input stream a lot of times to put unused data back. That wouldn't be easily fixed though.

**Comment by est31** [comment] 2016-10-09 19:47
@sfan5 I don't use any unget on the input stream at all, read the code.

**Comment by sfan5** [comment] 2016-10-13 15:23
@est31 Benchmark results for zstd (with the settings est provided):

map.sqlite zstd: `924.6 MiB` (`12.7%` <b>bigger</b>)

`--recompress`:
```
2016-10-13 17:10:43: ACTION[Main]: ############
2016-10-13 17:10:43: ACTION[Main]: Recompressed blocks:            2614854
2016-10-13 17:10:43: ACTION[Main]: Total data (uncomp.):           4008 MB
2016-10-13 17:10:43: ACTION[Main]: Total compression CPU time:     116.124s
2016-10-13 17:10:43: ACTION[Main]: Compression CPU time per block: 44.4092us
2016-10-13 17:10:43: ACTION[Main]: Compression speed:              35346.9 KB/s
2016-10-13 17:10:43: ACTION[Main]: ############
```

Decompression benchmark:
```
2016-10-13 17:15:57: ACTION[Main]: ############
2016-10-13 17:15:57: ACTION[Main]: Total blocks:                     2614854
2016-10-13 17:15:57: ACTION[Main]: Total data (comp.):               576 MB
2016-10-13 17:15:57: ACTION[Main]: Total decompression CPU time:     34.0404s
2016-10-13 17:15:57: ACTION[Main]: Decompression CPU time per block: 13.0181us
2016-10-13 17:15:57: ACTION[Main]: Decompression speed:              17342.6 KB/s
2016-10-13 17:15:57: ACTION[Main]: ############
```

**Comment by Rogier-5** [comment] 2016-10-20 09:51
I did some speed tests, so far for a relatively small world (1k blocks), with different compression settings per algorithm, and created a few graphs.

In the process, I merged sfan5's and est31's trees, and I added snappy and lz4 support as well. I also had to port to a newer version of libbrotli.

My tree is at https://github.com/Rogier-5/minetest/tree/compression. It includes the scripts to re-run the tests. See README.recompress.

I don't know why, but the performance of zstd was abysmal on my system. See the graphs. Above level 7, performance keeps getting worse.

The X axis shows the compression level (or acceleration for lz4).

The series lz4-c is plotted against the upper x-axis

![plot-recompress-comp_blocktime](https://cloud.githubusercontent.com/assets/6202053/19553953/b40a030e-96b6-11e6-949a-3dae44006b8b.png)
![plot-decompress-block_size](https://cloud.githubusercontent.com/assets/6202053/19553952/b402a104-96b6-11e6-8d6f-5da21f57a704.png)
![plot-decompress-comp_blocktime](https://cloud.githubusercontent.com/assets/6202053/19553954/b40bfcf4-96b6-11e6-8608-52c2e12253d9.png)

**Comment by Rogier-5** [comment] 2016-10-20 13:27
I added tests without compression. The block 'compression' speed is slightly better than for snappy and lz4. However, the total elapsed time is worse, undoublty caused by additional disk IO time.

![plot-recompress-comp_blocktime](https://cloud.githubusercontent.com/assets/6202053/19561388/d0aa3552-96d8-11e6-8055-15c8e141a66f.png)
![plot-recompress-time_elapsed](https://cloud.githubusercontent.com/assets/6202053/19561389/d0af3732-96d8-11e6-860a-cc68c2135936.png)

**Comment by Rogier-5** [comment] 2016-10-20 16:59
I finished running tests on a world with 21k blocks, and the results are roughly the same. I suppose results may be different on other systems (my system is quite old, but I do have an SSD).

The best option may be to implement support for several compression algorithms, and allow the user to configure the most suitable one. From my tests (i.e. on my system), brotli (level 5) is a good choice for database size, while lz4 is good for both compression and decompression speed. Zlib (level 3, or 4) may be a suitable compromise (i.e. default) candidate...

More user-friendly configuration values may be desirable as well. E.g. `compression = {zlib|zstd|brotli|(etc...)|default|speed|size}` ...

Keeping the '--recompress' command-line option might be a good idea as well. From time to time, users could even optimize the database to a high compression setting, while using a faster setting while running the server. Alternatively, there could be a background process that does this, like `/clearobjects`.

Regarding the subject of dictionaries: different dictionaries can be implemented as different compression algorithms, or by storing an additional u8 identifying the dictionary that was used. If a new, improved dictionary is added, it is much the same as adding a new compression algorithm: older servers can't read newer databases, unless the new server was configured to use the older dictionary or compression algorithm.

Of course, the dictionary(/ies) could also be stored in a table in the database itself, allowing full forward compatibility wrt dictionary improvements.

**Comment by est31** [comment] 2016-10-20 18:30
> More user-friendly configuration values may be desirable as well.

I don't think so. The only thing exposed to the user should be the compression factor, that's it. I don't think we should compress with multiple algorithms other than for legacy client purposes.

> Keeping the '--recompress' command-line option might be a good idea as well.

Yes, `--recompress` would be quite useful to have on master, but it should be rewritten to be less a hack (it shouldn't load all the lua stuff for example).

Regarding dictionaries, I think it would be hard to come up with an algorithm to classify which dictionary to compress a given mapblock with, so we should rather only compress to one dictionary at a time. With "dictionary" I mean a full set of dictionaries for each type of data compression is used for, so one dictionary for metadata, one for node data, etc. Also, coming up with a dictionary needs lots of data, so its better done offline. I propose we integrate dictionary management into the `--recompress` command, so we make it do:

1. go through the map, decompress every block, and build a dictionary with those data.
2. store that generated dictionary in the dictionary table.
2. iterate the map a second time, but now actually recompress it with the dictionary we have now generated.
3. delete the old dictionary from the dictionary table

That algorithm can be made robust towards premature ctrl+c by storing a parity flag inside the mapblock that points to one of the up to two dictionaries used. In step 1 we could check whether there are two dictionaries in the map, and then to prevent a third dictionary from being created recompress with the later dictionary in step 3, skipping step 2.

**Comment by Rogier-5** [comment] 2016-10-20 19:43
I have stumbled upon a performance improvement for zstd compression. The speedup is large: 30% reduction in compression time at compression levels 1 and 2, and 50% reduction at levels 3 to 7. See the latest commit on my branch. The patch itself is a quick hack. It will need some polishing before it's fit for release.

I read in the zstd docs that the (de)compression stream object can be reused, so I tried that, using c++11 thread local storage, so I enabled c++11 as well. I haven't investigated whether it is one or the other that makes the difference...

**Comment by est31** [comment] 2016-10-20 20:04
@Rogier-5 awesome! can you update the diagrams?

**Comment by est31** [comment] 2016-10-20 20:10
(this is one of the things that can be made optionally depend on C++11, so use the faster version if c++11 is enabled, continue to use the slow version if not)

**Comment by Rogier-5** [comment] 2016-10-21 06:37
@est31: I did some more investigation using perf and strace, and it turns out the `malloc` library is actually the culprit! It will repeatedly `munmap()` a `free()d` 5MB area of memory, only to `mmap()` it again on the subsequent `malloc()` in the zstd code. The original code even `mmap()ed` and `munmap()ed` 2 areas of 5MB and one of 2MB for every compression operation... Every time again, at least one of the 5MB areas is zeroed with `memset()`. How's that for a way to avoid having to turn on the heater when it's cold :-)

One would have thought `malloc()` was smarter than that (and apply some hysteresis). It may even be considered a bug.

Anyway, this can be fixed (workaround-style: the real problem is obviously with malloc and/or zstd) by using `mallopt()`. See my latest commit, and the graphs below. The total compression time reduction is now  closer to 90% for levels 3 and up.

Comparison graphs for zstd (original code, initial patch, and final code):

![plot-recompress-comp_blocktime](https://cloud.githubusercontent.com/assets/6202053/19588203/6e392dd8-9764-11e6-93fe-921410b050d2.png)

New compression graphs (including a few more zstd levels):

![plot-recompress-comp_blocktime](https://cloud.githubusercontent.com/assets/6202053/19588207/7b8381be-9764-11e6-8e88-bad4afc5f409.png)
![plot-decompress-block_size](https://cloud.githubusercontent.com/assets/6202053/19588218/853eeb94-9764-11e6-8738-8db608984707.png)
![plot-decompress-comp_blocktime](https://cloud.githubusercontent.com/assets/6202053/19588219/85472192-9764-11e6-9767-5121901314d8.png)

It can be seen that in spite of the significant additional compression effort at higher levels, much further reduction is not achieved. The reason is most probably that even at lower levels, much of the data is already compressed from 16KB down to an amount ranging from 20 to at most a few 100 bytes. There simply isn't much more redundancy to squeeze out.

**Comment by Megaf** [comment] 2017-05-03 19:47
Why was this just closed?

**Comment by ShadowNinja** [comment] 2017-05-04 17:14
Note that you should also take a look at #3946 if this is implemented.  You might be able to get better performance by compressing the whole mapblock instead of compressing several sections separately and there are a number of other improvements to be made if you're going to break the serialization format.

**Comment by Fixer-007** [comment] 2017-09-18 14:01
Zstd support (comp and decomp) included in newest linux 4.14 https://lkml.org/lkml/2017/6/29/816

**Comment by nerzhul** [comment] 2017-09-18 14:47
zstd will be supported for ZFS and LZ4 was choosen too

**Comment by Megaf** [comment] 2017-09-19 12:05
Linux Kernel people say LZO is the fastest.

**Comment by Reedych** [comment] 2017-11-17 16:59
So, what do we select?

**Comment by sofar** [comment] 2017-11-18 02:23
On my server, the OS provides AVX512 accelerated zlib libraries, so I strongly prefer to stay on zlib.

There are also negative implications: Alternative compression algorithms are NOT backwards compatible with old releases and should be non-default to begin with. Maps will break and it may be impossible to make downloadable player maps that are widely supported by older clients.

All the talk about "oh the kernel has FOO support" is nonsense because that support IS NOT EXPORTED TO USER SPACE. It won't do minetest any good that your kernel has zstd. Minetest can't use it. You will need to rely on a completely different implementation for user space, and that will probably lack things like decent parallelism and AVX512 acceleration, and therefore lag in performance compared to ... zlib.

**Comment by sfan5** [comment] 2017-11-18 13:07
> AVX512 accelerated 

:thinking: :thinking: :thinking: https://blog.cloudflare.com/on-the-dangers-of-intels-frequency-scaling/

> Alternative compression algorithms are NOT backwards compatible with old releases

That's a fair point but exactly why we should be looking to switch now (if we ever plan to).

> it may be impossible to make downloadable player maps that are widely supported by older clients

It's certainly possible to write a tool that deserialized maps in <current format> and serializes them again in a format understood e.g. by 0.4.16, this could also be integrated into Minetest itself (similar to `--migrate`).

> like decent parallelism and [...]

Since we're mostly compressing 12k bytes at once I doubt threading has much effect (if it is used at all).
Benchmarks comparing how well Intel's zlib does compared to brotli/zstd would be a good idea.

**Comment by nerzhul** [comment] 2017-11-18 13:25
And it's pure Intel, arm and AMD cpu doesn't benefit from that.No need to convert the whole map, just add format version to 1 for legacy mapblocks and write new mapblocks using zstd when written or loaded

**Comment by sofar** [comment] 2017-11-24 07:18
Many Intel optimizations also benefit AMD. Check out the various performance tests that phoronix has run on AMD's threadripper platform where they compare ClearLinux against non-specifically Intel optimized distros - you can decide for yourself based on the data whether "pure intel" (a complete misnomer) is such a bad thing for the competition. Article link because you're lazy: https://www.phoronix.com/scan.php?page=article&item=tr1950x-7900x-3os&num=2

**Comment by Reedych** [comment] 2017-11-24 10:51
I stay on using zlib. It is stable and many processors has optimizations for it.

**Comment by clavinet** [comment] 2019-03-24 23:46
> I stay on using zlib. It is stable and many processors has optimizations for it.
What optimizations exactly? And zstd is faster than zlib in any case, as seen from countless benchmarks.

**Comment by nerzhul** [comment] 2019-03-25 06:27
no processor has optimization for a such algorithm, zlib and zstd has optimisations for processors.

**Comment by paramat** [comment] 2019-03-25 21:13
Is there any core dev support for this?

**Comment by sofar** [comment] 2019-03-25 21:17
Zstd is faster and equal in size or better than gzip, and in my work projects we are actively implementing zstd compression.

So yes, it would have my support.

**Comment by clavinet** [comment] 2019-03-25 21:29
It also has multithreading support built in which speeds up compression even more at absolutely no loss of compression ratio from my tests at least.

**Comment by sofar** [comment] 2019-03-25 21:50
>It also has multithreading support built in which speeds up compression

Minetest should already multithread mapblocks saves, but this isn't as much of a factor of importance IMHO

>even more at absolutely no loss of compression ratio from my tests at
>least.

As I already stated. The biggest point is that it's faster to compress to the same size (and decompress too)

**Comment by Baigle** [comment] 2021-03-18 00:44
I took the liberty of documenting my #engine post from the Discord server so it isn't lost in an endless sea of comments.

Zstandard can perform significantly better than _almost any other option_ with training. This [YouTube video](https://www.youtube.com/watch?v=jl9ncLcMlVY) by Stanford Research Talks highlights a number of gains by using an unmutable, locked and always memory-loaded custom dictionary for referencing small and large data. They claim that the compression ratio can be improved by 3.5x to 10x, the compression speed by 3.6x over baseline, and decompression speed by 5.4x over baseline when using these features.

Alternative compression/decompression algorithms can be discovered by keeping up-to-date on [encode.su](https://encode.su/), the [Hutter Challenge](http://prize.hutter1.net/) [groups](https://groups.google.com/g/hutter-prize) and [Matthew Mahoney](http://www.mattmahoney.net/dc/text.html)'s ranking page, and on the [GDCC](https://globalcompetition.compression.ru/#leaderboards) (ru). Many algorithms based off of L-STM, Transformer/Few-shot learning, and Attention Matrices may work better in the future when these are more stable and developed.

**Comment by sfan5** [comment] 2021-09-24 10:47
Done in #10788

**Closed by sfan5** 2021-09-24 10:47 UTC
Labels: Protocol bump, @ Server / Client / Env., Supported by core dev

**Comment by Megaf** [comment] 2021-09-25 12:22
Glad it was done! Thanks!
