### ISSUE TITLE
Enabled mod is auto-disabled when closing the Configure World dialog, when mod is installed multiple times

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#9785] opened 2020-05-01 02:37 UTC
##### Minetest version

```
5.3.0-dev-83099fb9
```

##### Summary

I noticed this yesterday when I was trying to test a PR with the `itemframes` mod. I enabled the mod, and closed the Configure dialog. But I couldn't see the registered items of that mod, so I quit the game and re-opened the Configure dialog - the mod was disabled. I noticed that the mod gets automatically disabled when the dialog is closed.

I don't see anything useful in debug.txt, so I'm unable to provide more information.

Note: I am still able to enable the mod by manually editing `world.mt`

##### Steps to reproduce

- Download and install the [`itemframes`](https://notabug.org/TenPlus1/itemframes) mod.
- Enable the `itemframes` mod via the Configure World dialog.
- Press "Save" and re-open the Configure World dialog.
- Observe that the mod is disabled.

**Comment by LoneWolfHT** [comment] 2020-05-01 02:59
Do you have homedecor in your mods folder? IIRC that may cause problems

**Comment by rubenwardy** [comment] 2020-05-01 03:08
This happens when a mod is installed multiple times

**Comment by ClobberXD** [comment] 2020-05-01 05:38
I do have homedecor, but it's disabled.

I installed `itemframes` by manually downloading the mod's git repo from notabug. This is the first time I installed this mod. However, I do have the `frame` mod installed (another mod that provides item frames, IIRC), but I have left it disabled.

**Comment by LoneWolfHT** [comment] 2020-05-01 15:32
Try deleting homedecor and seeing if that works

**Comment by ClobberXD** [comment] 2020-05-01 15:38
Deleting `homedecor_modpack` (installed via CDB) fixes the issue. Worth mentioning: I did have two copies of homedecor installed until a couple of months ago - one from CDB, and another outdated, direct download. Might this be related, @rubenwardy?

Is this report still a valid bug, btw?

**Comment by paramat** [comment] 2020-05-02 01:21
I think there may be an existing issue or a closely related issue, perhaps you could search?
If there is not, the title of this issue needs changing.

**Comment by ClobberXD** [comment] 2020-05-02 02:18
@paramat I wasn't able to find any similarly worded issues, but there could possible be ones with different title. Regarding changing the title, I assume it's because the title sounds a little misleading (*all* mods are disabled when closing the dialog). Fixed, if that's the case. Let me know if it still needs improvement.

**Comment by paramat** [comment] 2020-08-10 02:01
> This happens when a mod is installed multiple times

> Deleting homedecor_modpack (installed via CDB) fixes the issue

**Comment by paramat** [comment] 2020-08-10 02:05
Duplicate of #9045

**Closed by paramat** 2020-08-10 02:05 UTC
Labels: Bug, Low priority
