### ISSUE TITLE
Make heads movable when character is looking around.

### ISSUE THREAD

**Issue by UltimateNate** [minetest/minetest#2716] opened 2015-05-23 01:01 UTC
I noticed that when you look around, your head doesn't move at all, and it is always appears to be to looking forward by 3rd person view or by others.

**Comment by paramat** [comment] 2015-05-23 01:07
We need new devs so someone can work on this, i would love this for Minetest.

**Comment by Rui914** [comment] 2015-05-23 06:47
https://forum.minetest.net/viewtopic.php?f=9&t=12189
Please see this Mod.

**Comment by kilbith** [comment] 2015-05-23 09:32
That'd be possible maybe if the articulated bone for the head followed the player's yaw.

**Comment by tenplus1** [comment] 2015-05-23 19:44
+1

**Comment by C1ffisme** [comment] 2015-05-23 22:04
I see two options:
* Add that mod to Minetest Game and make bone movement faster... OR
* Make the head a different entity altogether and change it's pitch and yaw accordingly.
Although, there might be more...

**Comment by Rui914** [comment] 2015-05-23 22:55
Also, PilzAdam was created this code.
https://github.com/PilzAdam/nodetopia/blob/master/mods/models/init.lua

**Comment by ExeterDad** [comment] 2015-05-24 04:18
Rui914's mod is awesome. But the animations are lua controlled. The models included animations aren't used. There is no sitting animation, nor does the body sway. If it would only control the head movements it would be perfect. 
If I'm not mistaken, it isn't possible currently as irrlichts animation blending bug. Not sure if that's the correct term? Or at least not possible in the version of irrlicht Minetest is coded for.
I believe @MirceaKitsune can shed some light on this? #2372

**Comment by Rui914** [comment] 2015-05-24 08:11
https://forum.minetest.net/viewtopic.php?f=6&t=11189
This bug.

**Comment by paramat** [comment] 2015-05-24 19:55
See comments here http://irc.minetest.ru/minetest-dev/2015-05-23#i_4260719 from 01:08 onwards.

**Comment by nanepiwo** [comment] 2015-05-27 04:07
This might be of interest, but concerns another body part. It is a modification to the engine, and is not lua. https://forum.minetest.net/viewtopic.php?id=3977

**Comment by C1ffisme** [comment] 2015-05-27 17:04
That sounds like a good idea, being able to sit down...

**Comment by nanepiwo** [comment] 2015-05-28 00:10
I know that sitting down IS possible on the Landrush server with a /sit command, but I don't know which mod causes it...

**Comment by est31** [comment] 2015-11-20 23:45
Dupe of #1800.

**Closed by est31** 2015-11-20 23:45 UTC
Labels: feature request

**Comment by tobyplowy** [comment] 2016-10-26 15:52
@paramat this really needs to be continued :/ player animations suck at the moment
