### ISSUE TITLE
Main menu music significantly slows down startup

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7139] opened 2018-03-17 08:23 UTC
##### Issue type

 - Bug report
 
##### Minetest version
```
Minetest 0.5.0-dev (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=None
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
```

##### OS / Hardware

Operating system: Lubuntu 17.10
CPU: intel

##### Summary

When using main menu music, starting minetest takes a lot more time. This makes using it very inconvenient because every time when starting minetest you need to wait for the music to load.
I think the music loading shouldn't block anything.

##### Steps to reproduce

I've added one 3.5 MiB ogg file as main_menu.0 to the sounds folder, executed `time minetest` and hold the Esc key to make minetest quit immediately after starting. It took about 0.79 seconds. Without the music file it took at max about 0.42 seconds.

**Comment by paramat** [comment] 2018-03-17 20:36
Do you mean it delays the appearence of the main menu and clouds? I would agree that the music file should be loaded after everything is visible.

**Comment by HybridDog** [comment] 2018-03-18 07:54
> Do you mean it delays the appearence of the main menu and clouds?

Yes, l do. l don't know if it also happens when leaving the game back to main menu.

**Comment by paramat** [comment] 2018-03-23 07:38
Related to this, do we yet have a way for a game to provide a music track for the main menu? I know menu music is possible but i seem to remember it is not supplied by the game as it should be.
Mentioning it as this should be attended to if this issue is.

**Comment by nerzhul** [comment] 2018-03-23 07:40
I don't know how currently we manage music, but i tend to say it should be a separated thread in the client to prevent those lags ingame

**Comment by paramat** [comment] 2018-09-22 00:45
Menu music needs rework, it should be provided by the games, music for the engine makes no sense (see threads about menu music).

**Comment by Zughy** [comment] 2022-07-04 21:06
It seems the same root cause of #10603. Closing here

**Closed by Zughy** 2022-07-04 21:06 UTC
Labels: @ Startup / Config / Util, Performance, Request / Suggestion, Sounds, @ Mainmenu, Supported by core dev
