### ISSUE TITLE
Alpha texture for inventory items

### ISSUE THREAD

**Issue by nininik0** [minetest/minetest#14699] opened 2024-05-25 00:44 UTC
### Minetest version

```true
5.8.0
All ver
```

### Operating system and version

Dosent matter

### Summary

There is a problem with alpha rendering in inventory_image.
If an item, or block, has a certain transparency then it will be INVISIBLE in inventory, or very opaque
![Screenshot_20240523-164032_Minetest](https://github.com/minetest/minetest/assets/132112852/dee9396f-f563-4d10-a255-2030ed678f3b)
![Screenshot_20240523-163730_Minetest](https://github.com/minetest/minetest/assets/132112852/6175ca75-9447-4e47-a89b-f17d1fe17c38)

### Steps to reproduce

This affects everything in inventory.
Some code: also use the texture below for testing. Or use the default water texture for opaque test.
`minetest.register_node(":ugx:softblueglass", {
	description = ("soft blue glass"),
	drawtype = "glasslike",
  sunlight_propagates = true,
   use_texture_alpha = true,
  paramtype = "light",
	tiles = { "softblueglass.png" },

	groups = { cracky = 1 },
})
![softblueglass](https://github.com/minetest/minetest/assets/132112852/e34d8924-0cf8-4644-880e-2c5d3dc25a36)
`

**Comment by sfan5** [comment] 2024-05-25 07:58
duplicate of #5461

**Closed by sfan5** 2024-05-25 07:58 UTC
Labels: Unconfirmed bug
