### ISSUE TITLE
Bundle Repixture game with next release

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#8935] opened 2019-09-15 11:40 UTC
![Screenshot of Repixture](https://satoshiupload.com/images/aXwxM6mYr4.png)

## Problem

We all want more exposure to good existing Minetest games. MTG isn’t enough, which has already been discussed. 

## Solutions

Let’s try and publish the newly refreshed [Repixture](https://forum.minetest.net/viewtopic.php?f=50&t=23235) game with next release. It’s an actual game and it shows much more of what Minetest is capable of than MTG does.

## Additional context
 
This is of course only applicable if the game has a 1.0 release ready by then. Otherwise the target should be the upcoming MT release after it has reached 1.0.

**Comment by SmallJoker** [comment] 2019-09-15 11:51
Same but different request #3949

**Comment by rubenwardy** [comment] 2019-09-15 14:19
Last time I viewed Pixture, it was buggy and flawed in UI/UX. If Pixture Revival fixes this, then it could be a good candidate

**Comment by tacotexmex** [comment] 2019-09-15 15:25
Same here, but Revival brings great improvements in that area.

**Comment by LoneWolfHT** [comment] 2019-09-15 15:37
Started Pixture Revival yesterday. So far I haven't found any bugs that haven't been fixed. And it's been quite fun :+1:

**Comment by paramat** [comment] 2019-09-15 17:01
I also thought this could potentially be bundled (but have not tested it).
But then, i generally feel it would be good to look at many games and assess them for bundling. I would like there to be less focus and pressure on MTG =)
Keep in mind that it may not be possible to guarantee maintenance of non-MTG games, authors can move on and core devs do not have time to maintain such games. Only a very few games can be guaranteed in that way.

**Comment by Wuzzy2** [comment] 2019-09-15 18:23
Thank you! Fun fact, this was basically the main reason why I even revived Pixture. This, and I personally just liked Pixture. ^^

I think Pixture Revival is now very close to a 1.0 release. More testing is always appreciated! ^^

Note Pixture Revival is a project to bring back Pixture back to life, with focus on: 5.0.0 compability, fixing bugs, improving usability. Gameplay will mostly not be touched, also not the content. Think of it as “Pixture on basic life support”, and not as “Continuation of Pixture”.

So the maintenence of Pixture Revival would basically revolve on fixing any (currently) unknown bugs, and updating stuff every few months (when a new MT release is out with deprecations and stuff). So, pretty basic stuff.

The biggest UX problem in Pixture was crafting, which completely ruined the game. This has been fixed, among many other issues.

I originally wanted to change the name back to “Pixture”, but thanks to Content DB policy, I'm afraid the name “Pixture” is taken forever, so I guess I'm stuck with the name “Pixture Revival” for now … :-(

Note the name “Pixture Revival” is only a project name, I really should change the name soon.

**Comment by jastevenson303** [comment] 2019-09-16 08:46
Repixture is a very catchy name, and I wish you the best in having it
become the first game bundled with Minetest beside MTG/Minimal.

**Comment by AKryukov92** [comment] 2019-09-16 11:10
Could someone add link to revived version of pixture?

**Comment by tacotexmex** [comment] 2019-09-16 12:03
> Could someone add link to revived version of pixture?

[First post ☝️](#issue-493727392)

**Comment by Wuzzy2** [comment] 2019-09-23 19:28
So, I have thought about this a big.

Maintaining a default game, even a simple one, is a huge responsibility. I don't know if I can take it.
I'm also not sure how you think about how the release model would work.
Definitely, a model like MTG's, that is, synced with MT releases, is not going to work. That would be way too slow and players would be stuck way behind the current state of Repixture and missing out on important bugfixes for months. Also note there's now only one week until feature freeze left. Even if I release 1.0.0 right now, I'd feel that will be just a very hastily cobbled-together release, of which I feel very uneasy of. Sadly.

This thread also leaves important questions unanswered:

* How to ship updates to the players?
* How would it integrate with Linux distro package managers? When Repixture is in the system folder, i'd be annoying for players to update to the latest version via Content DB
* What to do when I jump ship?
* Would that just make Repixture the new “promoted for free” game that gets all the free attention, with all other games being ignored?

Frankly, after a bit of thinking, I rather have no default game in Minetest. Instead, I'd like to have a better homepage with the high-quality games being showcased properly, like on www.solarus-games.org. Minetest isn't just about *one game*. It's about multiple games.

https://forum.minetest.net/viewtopic.php?f=3&t=23357

**Comment by sfan5** [comment] 2019-09-23 20:21
Yes, maintaining a default game binds you to a lot of constraints and other things the engine itself goes through.

Or in detail:

> Definitely, a model like MTG's, that is, synced with MT releases, is not going to work.

It has to. Dynamically updating from CDB is not viable currently and is complicated anyway when Linux distros ship a certain version of a game in `/usr/share` where you couldn't just update the files.

> way too slow and players would be stuck way behind the current state of Repixture

Such is life when you ship stable releases.

> missing out on important bugfixes for months

If a shipped game has game-breaking/major bugs, a point release can be done to ship a fixed version.
This is the same we'd do and [have done](https://github.com/minetest/minetest_game/compare/5.0.0...5.0.1) for minetest_game.

> * How to ship updates to the players?

You will be bound by the same release schedule as Minetest and minetest_game.
You won't<b>[1]</b> be able to ship any new versions to users for 6 months (between releases) with <i>very</i> rare exceptions (see above).

> * How would it integrate with Linux distro package managers?

It would be installed in the system folder just like minetest_game, just as you've said.

> * What to do when I jump ship?

If a game becomes unmaintained, it will not be shipped with the next major release of Minetest.
This can be made more pleasant for users by introducing a deprecation period where the game is maintained to the bare minimum (by the coredevs) to give users time to find a replacement / continuation of the to-be-deprecated game.

> * Would that just make Repixture the new “promoted for free” game that gets all the free attention, with all other games being ignored?

It woudn't be <i>the</i> new "promoted for free" game, since minetest_game still exists.
But yes, any game that is shipped with MT will receive a lot of free attention. The issue of other games being "ignored" can only be solved by making CDB more accessible.

<hr>
<b>[1]</b>
The "lack of updates" problem could be remediated by doing point release(s) twice as often as usually (so, 3 months after a full release) where the same engine (+ minimal fixes) is shipped with a newer version of the default games.

Though I don't know if other coredevs are interested in this solution and willing to handle the workload.

**Comment by sfan5** [comment] 2019-09-23 20:26
That said, I'd be positive to trying this approach (game bound to MT releases) with Repixture and seeing if it works out. Provided you think Repixture is in a state where it can be shipped as a default game for 5.1, of course.

**Comment by benrob0329** [comment] 2019-09-23 21:30
I feel like the CDB needs to be improved to the point where it can auto-install some base content that is updated seperately from the engine. We have this official content distribution system, why don't we make use of it?

**Comment by TumeniNodes** [comment] 2019-09-23 22:59
I played with Repixture a little and it's ok... the one thing I will mention is, that I honestly do not feel the current texture pack it uses will be attractive to most end users... and I am not referring to the few who are part of the forum/github|lab etc. community.
But that is just my own opinion and perspective

What is a plus
It has villages and villagers, some basic mobs

Mind you I played it in creative mode, but will try it with actual game mode on soon

**Comment by Wuzzy2** [comment] 2019-09-24 13:48
OK, I see now where you're coming from. So you'd like to add Repixture as an “experiment” and see how it turns out? Anyway, you certainly don't need my approval for bundling Repixture.
This sounds like a short-term solution then. It's still better than the current situation, as long Repixture doesn't go up in flames. The true long-term solution would be a real, but this is off-topic here.

Note that I suspect the maintenence of Repixture will be rather low. It all depends how much breakage future Minetest releases will cause. I probably just overreacted a bit …
I also don't plan to drop Repixture for a while. I will likely pick it up every now and then, especially when a Minetest release is imminent, which is not so often.

If you are so serious about bundling Repixture, you could all help playtesting and look for bugs, especially crashes. I would likely be less nervous about releasing v1.0.0 then.
Many players already helped me find a lot of bugs, but it would be great if one or two core devs look at it.

*Speaking of bugs*: If I run Repixture 0.5.0 in MT 5.1.0-dev right now, the inventory formspec looks a little buggy … It has a strange gray background that wasn't there before. Inventory looks OK in MT 5.0.1, however.
Did I maybe find a regression in Minetest here? :-) This should be investigated.

Apart from that, Repixture seems to work fine in -dev.

Note I do think Repixture is rather stable now. I have not heard of crashes for a while now.

Finally, you should all know that Repixure has a mod called “`default`”. Please be warned.

Frankly, I think it still sucks that “official” games must be synced with MT releases. It feels especially wrong now that we have the Content DB that allows to ship updates much faster. The way how you want to handle default games just completely bypasses the Content DB. I 100% agree with benrob: If we have this great Content DB, why not use it?

Even a “point release” in Minetest, as you call it, can take a while to actually get out and I know you all will be very mad at me if a crasher forces you to make a point release.

But yeah, if you still think it's neccessary to try out, feel free to. I will and can not stop you. Minetest is your child, not mine.

**Comment by sfan5** [comment] 2019-09-24 14:59
> Anyway, you certainly don't need my approval for bundling Repixture.

I know, but bundling a game by default requires appropriate coordination and it needs to be clear that the game won't become unmaintained for the forseeable future.
So this is not something the codedevs would just decide without consulting the game's author.

**Comment by DS-Minetest** [comment] 2019-09-24 15:00
>the inventory formspec looks a little buggy … It has a strange gray background that wasn't there before.

Maybe the non-fullscreen background color isn't made invisible (see also #8716).

**Comment by AKryukov92** [comment] 2019-09-24 21:32
> Definitely, a model like MTG's, that is, synced with MT releases, is not going to work. That would be way too slow and players would be stuck way behind the current state of Repixture and missing out on important bugfixes for months. 

I think you are overestimating the pace of development after 1.0.0. It should be feature complete and those features should be extensively tested. If you write down feature list then it will be possible to do finite amount of testing to prove that it works as intended.
Development after 1.0.0 should not overhaul the game. Few cool features per release will be enough.

> How to ship updates to the players?

It depends of type of updates. If you add some feature, then you can just add mod to ContentDB. In next release of MT you could add most popular mods for Repixture with the game. I assume that they should be tested too.
If you made bugfix, then yeah. You should wait for the next MT release. As temporary solution, you can publish fixed version of the game to ContentDB too. Though this occasion should be rare.

> What to do when I jump ship?

Say goodbye. But before you do that, you should bother to find next maintainer. I thought this process is known for you as long as you are involved with MT. Stay open to PRs, Review them by yourself. Then choose most committee and ask him to review other PRs.

> Would that just make Repixture the new “promoted for free” game that gets all the free attention, with all other games being ignored?

I think that Repixture should not be the only candidate to be bundled. It is up to authors of the games to suggest their games. Then maintainers of MT will decide whether they include one "best" game or all ready for publishing.
This way, promotion of the game will not be free. It will be deserved by your hard work.

**Comment by tacotexmex** [comment] 2019-09-24 21:57
I’ve joined the nobundler movement and thus I’ve changed my stance and do not support bundling of any game.

Instead, I believe that the best course of action is that the in-game ContentDB browser should be further developed to be able to bring good exposure to the cDB games.

**Comment by Fixer-007** [comment] 2019-09-27 19:39
I'm against unbundling, minetest should ship with reasonly good game by default included in a package, user should not be a foss terrorist, it has to work out of the box.

**Comment by paramat** [comment] 2019-09-28 18:17
>  Also note there's now only one week until feature freeze left. Even if I release 1.0.0 right now, I'd feel that will be just a very hastily cobbled-together release, of which I feel very uneasy of.

So it seems wrong to bundle it with 5.1.0, especially as there is so much uncertainty in this thread.

**Comment by paramat** [comment] 2019-09-29 19:02
Feel free to continue discussion but closing because Wuzzy2 no longer supports games being bundled with MT, and we can't bundle repixture without a reasonable guarantee of maintainence, coordination with, and support of, the game author.

The general issue of finding games to bundle with MT is already covered in #3949

**Closed by paramat** 2019-09-29 19:02 UTC
Labels: Feature request
