### ISSUE TITLE
on_player_jump input handler and such

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#9626] opened 2020-04-10 12:14 UTC
## Problem

In order to listen for a jump, `minetest.get_player_control` must be executed via Lua through `minetest.register_globalstep`. There is no builtin function such as `minetest.on_player_jump`
If Minetest is an engine, it should at the very least have some basic inputs listener, without going through all the beforementioned process at the modding level

## Solutions

1) Implement a `minetest.on_player_jump(function(player))` or

2) Implement a more generic input handler such as `minetest.on_button_down(function(player, button))` and `minetest.on_button_up(function(player,button))`. It'd be very helpful for a modder, opening up to several possibilities of customisation

## Additional info
I know no C++ so I couldn't really write down any code, but I can learn if needed

**Comment by SmallJoker** [comment] 2020-04-10 19:35
If this issue is about user inputs: duplicate of #8058
If it's about collision detection: duplicate of #3918

**Closed by SmallJoker** 2020-04-10 19:35 UTC
Labels: Feature request
