### ISSUE TITLE
Smooth lighting bug

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6574] opened 2017-10-31 09:43 UTC
I often noticed a bug like this

![screenshot_20171031_103827](https://user-images.githubusercontent.com/16163058/32217311-e63c9e10-be27-11e7-9a5d-6a8ca495cf3b.png)

It seems to be on a mapblock border and I can remove it e.g. by placing a torch. I have shaders on with tone mapping and smooth lightning.

**Comment by DS-Minetest** [comment] 2017-10-31 12:17
>I can remove it e.g. by placing a torch.

For me punching works, too.

**Comment by Calinou** [comment] 2017-10-31 16:52
I've seen that one lots of times, I think it was there even back in 2011, when I began playing Minetest.

**Comment by Fixer-007** [comment] 2017-10-31 17:06
What exactly is the problem? I don't see it, I suspect what you mean, but I don't see it.

**Comment by rubenwardy** [comment] 2017-10-31 17:07
> What exactly is the problem? I don't see it, I suspect what you mean, but I don't see it.

There's a line where the blocks on the left are darker than those on the right in the pit

**Comment by HybridDog** [comment] 2017-10-31 17:29
Could you give the seed and coordinates?

**Comment by MarkuBu** [comment] 2017-10-31 18:57
This bug appears randomly. You can't reproduce it just by use the same seed and coordinate

**Comment by Fixer-007** [comment] 2017-10-31 19:20
>There's a line where the blocks on the left are darker than those on the right in the pit

Oh i recognise it now, this seems like extreme case, most of the time it is just a small whitish blob on some mapblock edges, after punching or rewalking it goes away.

**Comment by paramat** [comment] 2017-11-01 00:20
That's extreme, i haven't seen that but i have noticed small errors at mapblock NorthWest corners:

![screenshot_20171021_072132](https://user-images.githubusercontent.com/3686677/32254702-69d0d3b4-be9a-11e7-8b50-370ed1244942.png)

**Comment by jastevenson303** [comment] 2017-11-01 14:18
October 11th
![screenshot_20171011_203213](https://user-images.githubusercontent.com/23448162/32279030-ddee4d6e-beed-11e7-9875-1e03fad69b80.png)

October 31st
![screenshot_20171031_211328](https://user-images.githubusercontent.com/23448162/32279061-f6c22cf2-beed-11e7-816e-d0ee767f9dd7.png)
^
The second one was taken in a far away place, newly generated.

**Comment by numberZero** [comment] 2017-11-05 00:25
That’s either mapgen or meshgen fault.

> after punching or rewalking it goes away

Almost certainly that’s meshgen-related problem. I think the mapblock mesh is generated without the data from the adjacent blocks, so they are interpreted as `CONTENT_IGNORE` that doesn’t propagate light and thus causes ambient occlusion. Normally mesh is regenerated when surrounding blocks become available (to render e.g. rails and connected nodeboxes properly), but sometimes that may not happen, causing weird mesh bugs. Punching forces mesh regeneration (to add the crack), thus fixing it.

**Comment by MarkuBu** [comment] 2017-11-05 15:16
This appears after I dig sand nodes. I didn't place any light sources or anything else. Just remove some nodes

![screenshot_20171105_160246](https://user-images.githubusercontent.com/16163058/32416025-ed42c5da-c242-11e7-9616-b831f8f93caa.png)

And this appears after I dug some more nodes at the same position

![screenshot_20171105_160539](https://user-images.githubusercontent.com/16163058/32416059-44ab6322-c243-11e7-8863-1a96dded0a54.png)

And this happens after I placed nodes and dig again. So I can reproduce this issue at this position

![screenshot_20171105_160854](https://user-images.githubusercontent.com/16163058/32416103-d3aff79a-c243-11e7-9c5f-a1bc141a312a.png)

I moved 16 nodes to the north and dug two nodes, and than I moved 16 nodes to the west and dug again two nodes. Both holes looks like this

![screenshot_20171105_161234](https://user-images.githubusercontent.com/16163058/32416127-4e43eb2e-c244-11e7-878d-52a29606bf66.png)

But everything in between looks normal.

**Comment by Fixer-007** [comment] 2017-11-05 16:59
This happens on mapblock chunks, I've already posted this long ago.

**Comment by paramat** [comment] 2017-11-06 05:55
You mean on mapblock borders, 'chunks' will confuse.

**Comment by azekillDIABLO** [comment] 2017-11-06 16:09
@MarkuBu Yeah, already happened in that case, but never on mapgen (except with moretrees)

**Comment by MarkuBu** [comment] 2017-11-06 16:12
The screenshot in the first post happens on mapgen. I came around the corner and bam, there it was. And I don't have moretrees installed at all.

I saw this before, but it's very rare

**Comment by paramat** [comment] 2017-11-06 16:25
![screenshot_20171106_160834](https://user-images.githubusercontent.com/3686677/32451546-f7da460e-c30e-11e7-8338-f9a9839a1ea7.png)

I found this in undisturbed terrain, bug disappeared when a node was dug (lighting update).

**Comment by numberZero** [comment] 2017-11-06 17:33
*This* is how broken lighting looks like:
![screenshot_20171106_202340](https://user-images.githubusercontent.com/7352626/32454685-035c1b02-c331-11e7-92bb-0268358575d9.png)
You may notice a sharp line. But it disappeared after client restart:
![screenshot_20171106_202400](https://user-images.githubusercontent.com/7352626/32454686-03866d80-c331-11e7-8d1b-747132ecede7.png)
![screenshot_20171106_202411](https://user-images.githubusercontent.com/7352626/32454687-03aac932-c331-11e7-869f-2de85767ce50.png)
Note that the lighting is still heavily broken here. There is still a mix of `air` and `ignore` with lighting of 0 or 15 (both banks). But no sharp edges anymore.

**Comment by MarkuBu** [comment] 2017-11-06 20:27
Never have seen that before, and I play on this map for a while. But on this plane I noticed this bug the first time when I made a little bit terraforming. But it wasn't that big and it "moved" while I was digging. It doesn't disappear

![screenshot_20171106_211747](https://user-images.githubusercontent.com/16163058/32462136-9e4b1d64-c338-11e7-9f36-cdafd0363fb6.png)

And after a restart the bug moved

![screenshot_20171106_212344](https://user-images.githubusercontent.com/16163058/32462229-f95532ee-c338-11e7-8484-49041de19f8e.png)

And it seems that this error appears at a specific height. This plane is at y=31

**Comment by paramat** [comment] 2017-11-08 10:22
y = 31 is a mapblock border.

**Comment by HybridDog** [comment] 2017-11-11 07:40
I guess https://github.com/minetest/minetest/commit/2cf9014160085303cda333334784ac4938edc086 excavated this bug.
I can reproduce it and noticed that the dark stripe is on the corner of the previously loaded mapblock.
I assume you can make ignore sunlight_propagates but then the bug is just hidden: there would be brightness where ambience occlusion should make it dark.
I guess a simple but inefficient solution would be calculating smooth light for 18x18x18 nodes. 

Otoh the bug only appears on the mapblock border (air in the block above, dirt with grass in the block below)

**Comment by MarkuBu** [comment] 2017-11-11 08:24
I already saw this under water, no air, no dirt with grass

**Comment by numberZero** [comment] 2017-11-11 09:24
> I guess a simple but inefficient solution would be calculating smooth light for 18x18x18 nodes. 

If you mean passing 18×18×18 nodes to the mesh generator, that’s done
already; actually 3×3×3 mapblocks are passed normally (according to
comments in the code, that’s faster than copying only some nodes). That
is used to draw rails, connected nodeboxes, etc. correctly. Even solid
node drawing uses that, as it needs to know whether to draw faces on the
mapblock border.

**Comment by numberZero** [comment] 2017-11-11 09:26
I am not sure, but I think the actual problem is in the meshgen thread
mapblock cache, so that it doesn’t get updated sometimes. Maybe there is
some synchronization problem.

**Comment by HybridDog** [comment] 2017-11-11 17:58
![_compressed_screenshot_20171111_173803 png_](https://user-images.githubusercontent.com/3192173/32692088-42f19b22-c712-11e7-827c-0064b80c9381.jpg)

**Comment by numberZero** [comment] 2017-11-11 19:12
![screenshot_20171111_220109](https://user-images.githubusercontent.com/7352626/32692648-da28f232-c72c-11e7-93ad-11f042237c43.png)
There might be rails one node higher, but that layer was replaced by air.
After restart that looks normally (except of heavily broken lighting, but that’s intended):
![screenshot_20171111_220137](https://user-images.githubusercontent.com/7352626/32692649-da5e28f8-c72c-11e7-92e0-5fb73c3f237b.png)

**Comment by HybridDog** [comment] 2017-11-12 08:29
Yes, I just tested it. The bug indeed is not caused by a smooth lighting bug, I assume thanks to the commit I mentioned earlier more failures appear now.
The bug happens on the diagonal between a mapblock and the upper left (not the direct neighbour that is) one. I only needed to place the rails in y=31 in the one mapblock, then place the rails in y=32 in the other mapblock, no restarting required.
![_compressed_screenshot_20171112_091750 png_](https://user-images.githubusercontent.com/3192173/32697197-e3c51906-c78b-11e7-8ba2-1a9f775d9be5.jpg)
![_compressed_screenshot_20171112_091818 png_](https://user-images.githubusercontent.com/3192173/32697199-e9323040-c78b-11e7-985f-44b22990c640.jpg)
When punching the rails, the bug disappears.
It doesn't happen to the direct neighbour:
![_compressed_screenshot_20171112_091715 png_](https://user-images.githubusercontent.com/3192173/32697207-fbee0466-c78b-11e7-8043-7ae29647719a.jpg)

**Comment by paramat** [comment] 2017-11-14 01:02
I've noticed that the mapblocks of the generated terrain has a dark border which is the dark line of this bug, maybe this bug is this dark border not disappearing?

![screenshot_20171114_005651](https://user-images.githubusercontent.com/3686677/32757411-3d799c1e-c8d7-11e7-85cc-7ed634b66360.png)

As these dark lines disappear they sometimes leave behind dark triangles on mapblock corners (that i mentioned above):

![screenshot_20171114_005912](https://user-images.githubusercontent.com/3686677/32757426-52681876-c8d7-11e7-91e8-986689428a21.png)

**Comment by paramat** [comment] 2017-11-14 01:10
In mgflat setting ground level to y = 15 (mapblock border) the lines get much worse and i can confirm these are the dark lines at generated terrain edge sometimes not disappearing.

![screenshot_20171114_010855](https://user-images.githubusercontent.com/3686677/32757693-a6480bee-c8d8-11e7-9bdd-3932d2b632ca.png)

**Comment by paramat** [comment] 2017-11-14 01:32
Does not occur with smooth lighting disabled.

**Comment by paramat** [comment] 2017-11-14 03:05
Confirmed dark edges and this bug are caused by 2cf9014160085303cda333334784ac4938edc086

**Comment by numberZero** [comment] 2017-11-14 14:25
> Confirmed dark edges and this bug are caused by 2cf9014

@paramat This bug is not caused but revealed by 2cf9014.

**Comment by HybridDog** [comment] 2017-11-17 19:39
This isn't a smooth lighting bug but a mapblock border bug, the issue title should be changed.
And it has been there even in 2011 (see Calinou's comment).

**Comment by paramat** [comment] 2017-11-17 22:21
It's unlikely the same issue as 6 years ago, especially since lighting calculations have changed so much.
@juhdanad

**Comment by juhdanad** [comment] 2017-11-19 22:10
If the bug is not present without smooth lighting, the light values in the map block are correct. But I can say nothing about nodes around the block when its mesh is drawn.

**Comment by paramat** [comment] 2017-12-09 09:01
> And it has been there even in 2011 (see Calinou's comment).

We would have noticed it before now if it's a long running bug.

> I am not sure, but I think the actual problem is in the meshgen thread mapblock cache, so that it doesn’t get updated sometimes. Maybe there is some synchronization problem.

@DTA7 Since this may be difficult and take time to fix, and is visually ugly and irritating, i think we need a simple temporary way to disable your commit https://github.com/minetest/minetest/commit/2cf9014160085303cda333334784ac4938edc086 that uncovered this, not a revert but a minimum amount of code that disables your commit and removes these lines.
Please could you make a PR to do this?

**Comment by numberZero** [comment] 2017-12-09 19:25
The reason appears to be stupidly simple. addUpdateMeshTask* functions add up to 6 neighbors. That’s enough for proper solid node drawing. But not for new smooth lighting.

**Comment by paramat** [comment] 2017-12-10 04:02
Ok good i hope so, please could you work on a bugfix? It's much more important than code cleanups (which are very welcome of course).

**Comment by HybridDog** [comment] 2017-12-10 11:01
https://github.com/minetest/minetest/blob/master/src/client.cpp#L1501

**Comment by numberZero** [comment] 2017-12-10 12:43
@paramat I can, of course. I started to clean the code now just because I found some try-catch sections around non-throwing code in these addUpdateMeshTask* functions.

**Comment by paramat** [comment] 2017-12-10 13:53
Thanks.

**Comment by paramat** [comment] 2018-01-12 06:00
#6838 merged.

**Closed by paramat** 2018-01-12 06:00 UTC
Labels: @ Client / Audiovisuals, @ Mapgen, Blocker, Bug, High priority, Obscure
