### ISSUE TITLE
Unable to enter a 7 in the "Server address / Port" text field in Play Online tab

### ISSUE THREAD

**Issue by rthijs** [minetest/minetest#11781] opened 2021-11-20 10:38 UTC
I am unable to enter a "7" in the "Server address / Port" text field in Play Online tab.

System: Raspberry Pi 3B+ running fully updated and upgraded (as of today: 2021-11-20) Raspbian OS 3.6 January 2021

Locale settings:

Language: nl (Dutch)
Country: Belgium
Character Set: UTF-8

Keyboard:
Model: Generic 105-key PC (intl.)
Layout: Belgian
Variant: Belgian

![keyboard](https://user-images.githubusercontent.com/16205691/142723226-d748e789-a44c-46a2-83cc-7b4c3e8daf97.png)

```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.63-v7+ minetest/minetest_game#1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux
```

I have reproduced this for Minetest version 0.4.17.1 as that was in the repository. I had the same issue two weeks ago on version 5.4.1 installed as a snap or a flatpak. I could not confirm today on the snap and flatpak as they won't run anymore (they did on 13th of november 2021 and had the same issue).

Also reproducable on a Raspberry Pi 4.

```
pi@raspberrypi:~ $ sudo apt install minetest
Pakketlijsten worden ingelezen... Klaar
Boom van vereisten wordt opgebouwd       
De statusinformatie wordt gelezen... Klaar
De volgende extra pakketten zullen geïnstalleerd worden:
  fonts-croscore libirrlicht1.8 libjsoncpp1 libleveldb1d libpq5 minetest-data
Voorgestelde pakketten:
  fonts-crosextra-caladea fonts-crosextra-carlito minetest-mod-moreblocks
  minetest-mod-moreores minetest-mod-pipeworks minetest-server
De volgende NIEUWE pakketten zullen geïnstalleerd worden:
  fonts-croscore libirrlicht1.8 libjsoncpp1 libleveldb1d libpq5 minetest
  minetest-data
0 opgewaardeerd, 7 nieuw geïnstalleerd, 0 te verwijderen en 0 niet opgewaardeerd.
Er moeten 156 kB/8.758 kB aan archieven opgehaald worden.
Na deze bewerking zal er 28,5 MB extra schijfruimte gebruikt worden.
Wilt u doorgaan? [J/n] 
Ophalen:1 http://mirror.nl.leaseweb.net/raspbian/raspbian buster/main armhf libpq5 armhf 11.14-0+deb10u1 [156 kB]
156 kB opgehaald in 0s (324 kB/s)
Voorheen niet geselecteerd pakket fonts-croscore wordt geselecteerd.
(Database wordt ingelezen ... 98860 bestanden en mappen momenteel geïnstalleerd.)
Uitpakken van .../0-fonts-croscore_20181227-1_all.deb wordt voorbereid...
Bezig met uitpakken van fonts-croscore (20181227-1) ...
Voorheen niet geselecteerd pakket libirrlicht1.8:armhf wordt geselecteerd.
Uitpakken van .../1-libirrlicht1.8_1.8.4+dfsg1-1.1_armhf.deb wordt voorbereid...
Bezig met uitpakken van libirrlicht1.8:armhf (1.8.4+dfsg1-1.1) ...
Voorheen niet geselecteerd pakket libleveldb1d:armhf wordt geselecteerd.
Uitpakken van .../2-libleveldb1d_1.20-2.1_armhf.deb wordt voorbereid...
Bezig met uitpakken van libleveldb1d:armhf (1.20-2.1) ...
Voorheen niet geselecteerd pakket libpq5:armhf wordt geselecteerd.
Uitpakken van .../3-libpq5_11.14-0+deb10u1_armhf.deb wordt voorbereid...
Bezig met uitpakken van libpq5:armhf (11.14-0+deb10u1) ...
Voorheen niet geselecteerd pakket minetest-data wordt geselecteerd.
Uitpakken van .../4-minetest-data_0.4.17.1+repack-1_all.deb wordt voorbereid...
Bezig met uitpakken van minetest-data (0.4.17.1+repack-1) ...
Voorheen niet geselecteerd pakket libjsoncpp1:armhf wordt geselecteerd.
Uitpakken van .../5-libjsoncpp1_1.7.4-3_armhf.deb wordt voorbereid...
Bezig met uitpakken van libjsoncpp1:armhf (1.7.4-3) ...
Voorheen niet geselecteerd pakket minetest wordt geselecteerd.
Uitpakken van .../6-minetest_0.4.17.1+repack-1+b1_armhf.deb wordt voorbereid...
Bezig met uitpakken van minetest (0.4.17.1+repack-1+b1) ...
Instellen van libleveldb1d:armhf (1.20-2.1) ...
Instellen van libpq5:armhf (11.14-0+deb10u1) ...
![minetestPlayOnline](https://user-images.githubusercontent.com/16205691/142723087-48acecba-45b2-4a27-bf24-574b4153b44d.png)

Instellen van libirrlicht1.8:armhf (1.8.4+dfsg1-1.1) ...
Instellen van fonts-croscore (20181227-1) ...
Instellen van libjsoncpp1:armhf (1.7.4-3) ...
Instellen van minetest-data (0.4.17.1+repack-1) ...
Instellen van minetest (0.4.17.1+repack-1+b1) ...
Bezig met afhandelen van triggers voor fontconfig (2.13.1-2) ...
Bezig met afhandelen van triggers voor desktop-file-utils (0.23-4) ...
Bezig met afhandelen van triggers voor mime-support (3.62) ...
Bezig met afhandelen van triggers voor hicolor-icon-theme (0.17-2) ...
Bezig met afhandelen van triggers voor gnome-menus (3.31.4-3) ...
Bezig met afhandelen van triggers voor libc-bin (2.28-10+rpt2+rpi1) ...
Bezig met afhandelen van triggers voor man-db (2.8.5-2) ...
pi@raspberrypi:~ $ 
```

Running Minetest and entering the sequence "71234567890" in the "Server address / Port" text field gives "123456890" as a result.

![minetestPlayOnline](https://user-images.githubusercontent.com/16205691/142723206-73398ecf-d334-4f9e-9b2a-cfc740f0a38f.png)

I got this output in the console:

```
pi@raspberrypi:~ $ minetest
2021-11-20 10:51:31: [Main]: Automatically selecting world at [/home/pi/.minetest/worlds/RoelTest]
Loaded texture: /usr/share/games/minetest/games/minetest_game/menu/header.png
Loaded texture: /usr/share/games/minetest/games/minetest_game/menu/icon.png
Loaded texture: /usr/share/games/minetest/games/minimal/menu/icon.png
Loaded texture: /usr/share/games/minetest/textures/base/pack/blank.png
Loaded texture: /usr/share/games/minetest/textures/base/pack/server_flags_favorite.png
Loaded texture: /usr/share/games/minetest/textures/base/pack/server_ping_4.png
Loaded texture: /usr/share/games/minetest/textures/base/pack/server_ping_3.png
Loaded texture: /usr/share/games/minetest/textures/base/pack/server_ping_2.png
Loaded texture: /usr/share/games/minetest/textures/base/pack/server_ping_1.png
Loaded texture: /usr/share/games/minetest/textures/base/pack/server_flags_creative.png
Loaded texture: /usr/share/games/minetest/textures/base/pack/server_flags_damage.png
Loaded texture: /usr/share/games/minetest/textures/base/pack/server_flags_pvp.png
Could not find EKEY_CODE, using orig. X11 keycode instead: 16
Could not find EKEY_CODE, using orig. X11 keycode instead: 16
EKEY_CODE is 0, using orig. X11 keycode instead: 10
EKEY_CODE is 0, using orig. X11 keycode instead: 10
Could not find EKEY_CODE, using orig. X11 keycode instead: 11
Could not find EKEY_CODE, using orig. X11 keycode instead: 11
EKEY_CODE is 0, using orig. X11 keycode instead: 12
EKEY_CODE is 0, using orig. X11 keycode instead: 12
EKEY_CODE is 0, using orig. X11 keycode instead: 14
EKEY_CODE is 0, using orig. X11 keycode instead: 14
EKEY_CODE is 0, using orig. X11 keycode instead: 15
EKEY_CODE is 0, using orig. X11 keycode instead: 15
Could not find EKEY_CODE, using orig. X11 keycode instead: 16
Could not find EKEY_CODE, using orig. X11 keycode instead: 16
EKEY_CODE is 0, using orig. X11 keycode instead: 17
EKEY_CODE is 0, using orig. X11 keycode instead: 17
Could not find EKEY_CODE, using orig. X11 keycode instead: 18
Could not find EKEY_CODE, using orig. X11 keycode instead: 18
Could not find EKEY_CODE, using orig. X11 keycode instead: 19
Could not find EKEY_CODE, using orig. X11 keycode instead: 19
```

As a workaround it is possible to copy a 7 from somewhere to the clipboard and past it in the textfield.

**Comment by SmallJoker** [comment] 2021-11-20 13:56
Duplicate of #302. Fixed in version 5.5.0-dev.

**Closed by SmallJoker** 2021-11-20 13:56 UTC
