### ISSUE TITLE
Pointer overflow in src/util/srp.cpp (Secure Remote Password 6a implementation)

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11808] opened 2021-12-01 17:18 UTC
##### Minetest version
Commit 1dc1305ada07da8c2a278b46a34d58af86184af9

##### OS / Hardware
Operating system: Debian GNU/Linux
CPU: Intel(R) Core(TM) Duo CPU      T2400  @ 1.83GHz

##### Summary
During a build, I get the output:

```
In function ‘SRP_Result H_ns(__mpz_struct*, SRP_HashAlgorithm, const unsigned char*, size_t, const unsigned char*, uint32_t)’,
    inlined from ‘int calculate_x(__mpz_struct*, SRP_HashAlgorithm, const unsigned char*, size_t, const char*, const unsigned char*, size_t)’ at src/util/srp.cpp:455:13:
src/util/srp.cpp:432:8: warning: ‘void* memcpy(void*, const void*, size_t)’ pointer overflow between offset [0, 2147483647] and size [4294967295, 2147483647] [-Warray-bounds]
  memcpy(bin + len_n, bytes, len_bytes);
  ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/util/srp.cpp:432:8: warning: ‘void* memcpy(void*, const void*, size_t)’ specified size 4294967295 exceeds maximum object size 2147483647 [-Wstringop-overflow=]
```

##### Steps to reproduce
1. Build commit 1dc1305ada07da8c2a278b46a34d58af86184af9.
2. Wait and see.

**Comment by sfan5** [comment] 2021-12-01 21:32
duplicate of #11808

**Closed by sfan5** 2021-12-01 21:32 UTC
Labels: Unconfirmed bug, Low priority, Possible close
