### ISSUE TITLE
Fix ^[mask texture modifier

### ISSUE THREAD

**Issue by mruncreative** [minetest/minetest#14796] opened 2024-06-30 00:09 UTC
### Minetest version

```true
5.8
```

### Operating system and version

all

### Summary

Mods assume that texture1.png^[mask:texture2.png scales texture2.png to the size of texture1.png before masking.
This can be seen in Mobs Monsters. An egg mask from the mod is overlayed onto a texture from MTG. A 128x128 texture pack is used.
![mesemonster](https://github.com/minetest/minetest/assets/67873653/0c9e6bc2-d759-47fb-97a9-5a99503e570e)

While the scaling can be done by mods, it is quite cumbersome:
```
local function mask_escape(str)
	return str:gsub("%^%[", "\\%^\\%["):gsub(":", "\\:")
end
"texture1.png^[mask:"..mask_escape("((texture1.png^[opacity:0)^texture2.png)"),
```
I wish for this to be fixed in 5.9. Shouldn't be hard as most other texture modifiers already use scaling.

A resolution-independent alternative to combine and resize would also be appreciated.

Mods shouldn't care about texture size because they run on the server and don't know anything about it and shouldn't make any assumptions about it. That's what I've been told on the Minetest IRC when I naively asked about how to get a texture's resolution. So stick to your dogma.

### Steps to reproduce

`texture1.png^[mask:texture2.png`

**Comment by appgurueu** [comment] 2024-07-01 20:03
As I wrote on IRC, my thoughts:

* This is not a bug. Nobody is guaranteeing `[mask` to do any resizing. It's not unreasonable for it not to.
* A change in the behavior of `[mask` would need to be well justified. In particular, it would need to be ensured that the extent of the breakage is very limited.
* As you've seen already, mods can already do the rescaling themselves. So there is a workaround. As for this being cumbersome: A texture modifier DSL might help with that. I might look into getting such a DSL merged in the engine for convenience. Otherwise, just write your own or pick one of the few around (modlib has one, as does nodecore and advtrains).
* If both the base and the mask are upscaled, this isn't a problem. Why don't you simply add a texture for the base?
* Unless everything is exactly divisible, it is not clear what interpolation to use for scaling. Nearest neighbor would make the most sense but really, masks only make sense with exact values.

As for resolution-dependence more generally: I agree that there is a problem here, some texture modifiers like `[combine` effectively require modders to make assumptions about resolutions. But properly fixing this is very much nontrivial and I wish not to bloat texture modifiers further. The long-term solution towards being more of a game engine would be to enable client mods - which would know textures - to combine textures as they see fit.

As for the "dogma", yes mods should *try* to be resolution independent. They may still require certain resolutions for certain textures, that is inevitable with how many of our texture modifiers currently work.

**Comment by mruncreative** [comment] 2024-07-02 07:41
> If both the base and the mask are upscaled, this isn't a problem. Why don't you simply add a texture for the base?

In this case I might do that but I was also working on another mod where my mask is fixed resolution, is applied to MTG textures and isn't supposed to require any texture pack support. And I don't see why texture packs of resolutions other than x16 deserve to be treated worse than others.

I don't see how doing the correct thing easily is bloat and unimportant and using some lazy hack is supposed to be the better option.

> Unless everything is exactly divisible, it is not clear what interpolation to use for scaling.
Nearest neighbour like all the other texture modifiers. Most textures are square and texture packs resolutions usually multiples of 16.

>A change in the behavior of [mask would need to be well justified. In particular, it would need to be ensured that the extent of the breakage is very limited.

Some mods that use mask
3d_armor/wieldview/get_texture.lua
maidroid_ng/maidroid/tools/capture_rod.lua
everness/nodes_farming.lua
everness/mod_support_x_obsidianmese.lua
animalia/mobs/horse.lua
mobs/api.lua
Looking at the output of grep, I don't think any of them would break if scaling was added.

**Comment by v-rob** [comment] 2024-09-28 18:46
If I recall correctly, `^` didn't use to scale both sides. I seem to recall partially complete texture packs where the dirt texture was some big size like 32x32, but the dirt with grass texture overlayed on top was still 16x16, and hence it was just overlayed over the top right fourth of the dirt texture. Changing that was technically a breaking change. I would be in favor of such a change for `[mask` as well, since the current behavior is not useful to anyone.

**Closed** 2024-10-04 08:44 UTC
Labels: @ Script API, Feature request, @ Client rendering

**Comment by nininik0** [comment] 2024-11-15 00:43
Can confirm. Here is the textures used for SOME of the spawneggs:
![gigabat](https://github.com/user-attachments/assets/55377965-2a3c-45fa-89d9-be26800af440)
![r](https://github.com/user-attachments/assets/71399e2a-1271-4cd4-b320-8ffa6509fd00)
![statue_form_old](https://github.com/user-attachments/assets/daf8b149-7b70-4ffd-b099-8a066736ee2d)
![stoneskin_old](https://github.com/user-attachments/assets/bf66be1f-9efc-4dbb-81b4-1e028e288a25)
![unded](https://github.com/user-attachments/assets/1f91877e-3d1b-4859-8afd-b5836e64396a)
![z1](https://github.com/user-attachments/assets/7747dd68-9e7c-4298-b8a2-44fc0620b1c0)
