### ISSUE TITLE
Worldpack, go from a world to another with Lua API

### ISSUE THREAD

**Issue by rdelaage** [minetest/minetest#10558] opened 2020-10-25 18:19 UTC
## Problem

Today there is no solution to go from a world to another unless you leave your game and go back to the main menu. Then only solution to have multiple "dimensions" is to make each dimension in a specific height range of the world, but only one of these dimensions can have access to the sky and you can't add a lot of dimensions because of the height limit.

## Solutions

You could introduce worldpack. It will be a folder of world with independent parts and some shared resources. Let me explain the concept. You open a worldpack for the first time and you are on the main world and from this world you can travel to an other world by crossing a portal or submitting a command for example. A mod can ask to travel from a world to an other with an API method. The blocks, entities, ... in each world are independents. However you can share informations between world such as players informations (inventories, nicknames, ...) we can imagine symbolic links for example to share this content or a system to copy each change in a world for this content to the other world.

We could imagine other features with this system, such as hubs in servers and if we change of server the game can display a warning for security reasons.

## Alternatives

My first idea was to modify the structure of the world folder but I realized that it was very complex and could break compatibilty with older version.

I think my solutions can work and is less complex, it can solve the issues for dimensions and can permit a lot of cool stuff.

**Comment by Desour** [comment] 2020-10-25 19:26
Related: #4428

**Comment by hecktest** [comment] 2020-10-26 10:07
Better to just support multiple world instances on the same server and DB, because that is a prerequisite for doing voxel entities properly.

**Comment by 0-afflatus** [comment] 2020-10-26 17:15
Being able to teleport to parallel worlds would be very cool.

**Comment by Teashrock** [comment] 2020-10-28 05:22
I'm trying to implement this to 5.3.0 sources from time to time. But I can't say that it's done, neither will it be done at all.

**Comment by EliasFleckenstein03** [comment] 2021-01-26 07:58
You can use a Proxy to connect multiple servers together. There are two WIP proxies that do that:
https://github.com/andrewvy/knot
https://github.com/HimbeerserverDE/multiserver

**Comment by AFCMS** [comment] 2021-03-15 10:23
> You can use a Proxy to connect multiple servers together. There are two WIP proxies that do that:
> https://github.com/andrewvy/knot
> https://github.com/HimbeerserverDE/multiserver

Can these proxies sync inventories and player meta?

**Comment by HimbeerserverDE** [comment] 2021-03-19 06:53
My proxy can read and modify inventories, but it doesn’t have a plugin API yet. It does support cross-server communication which can be used to exchange serialized inventories or metadata with other MT servers that are also behind the proxy.

**Comment by Zughy** [comment] 2022-05-04 14:12
Duplicate of #4428

**Closed by Zughy** 2022-05-04 14:12 UTC
Labels: Duplicate, Feature request
