### ISSUE TITLE
Allow overriding tool capabilities through player ref

### ISSUE THREAD

**Issue by pandaro** [minetest/minetest#5634] opened 2017-04-21 16:57 UTC
As  previously referred to https://github.com/minetest/minetest/pull/5612 i will ask this feature:
The capability of override tools capabilities through something referred to a player.
with an example:
This pick in my hand works differently from the same pick in your hand.
i don't know if the best way is using:
- attribute back-end;
- player's hand override;
- other system;
And i don't know if it is possible at all.
Thanks

**Comment by HybridDog** [comment] 2017-04-22 14:38
You could use item metadata.

**Comment by dsohler** [comment] 2017-04-22 18:20
What would the metadata look like for “This pick in my hand works differently from the same pick in your hand.” where “me” and “you” are not hardcoded, random players.

**Comment by pandaro** [comment] 2017-04-22 18:48
@HybridDog 

> You could use item metadata.

yes but i think is painful rewrite metadata whenever a tool change player

@dsohler 

> What would the metadata look like for “This pick in my hand works differently from the same pick in your hand.” where “me” and “you” are not hardcoded, random players.

This was an example. 
with another example, i hope better explained:
I am a professional in cutting wood, my name is "player 1". I have an ax, i can cut a tree in 3 shots.
Now i drop my ax and another player, called "player2", collects it from the ground and uses it for cut a tree, but "player2" is not a professional woodcutter, so he need 6 shots to cut the tree.
In order to do this using metadata tools overriding the process seem to be hard.
If overwriting features of a tool were possible from the player itself, it would greatly reduce the steps needed to make a difference in the use of a tool by two players.

I hope I have been able to explain what I mean in my poor English

**Comment by HybridDog** [comment] 2017-04-22 20:16
pandaro, such a behaviour is very annoying in my experience. When changing servers you need to "collect experience" again from the beginning no matter how much real experience you have. l'd prefer something more realistic/replicable: The digging time of tools could depend on the way you use them, e.g. the axe is most efficient (lowest digging time) if the camera position is near the trunk (not too near) and you look diagonally on the trunk side pointing the right face.

**Comment by pandaro** [comment] 2017-04-23 05:33
@HybridDog 
I clearly perceive irony even if you did not say it openly, simply, if you did not care or did not agree, you could:
Do not answer or say that you did not like it.
The sarcasm, it seems to me time lost in these cases.

**Comment by HybridDog** [comment] 2017-04-23 07:37
Sorry.
By overriding tool capabilities, do you mean changing the capabilities of specific tools (e.g. wooden pick) or changing capabilities of a type of tool (e.g. picks)?

**Comment by pandaro** [comment] 2017-04-23 07:47
> Sorry.

No problem, You are usually an honest person, maybe I misunderstood you.

i mean only a specific tool, exactly the one in the hand of one player, not all the picks, not all the wooden picks but my wooden pick the i use right now.

**Comment by raymoo** [comment] 2017-04-23 09:30
You said you wanted to avoid setting the meta of an item every time a different player holds it, but with your suggestion you would have to set the meta of a player every time they get an item that you want to be affected by your suggestion.

**Comment by pandaro** [comment] 2017-04-23 09:52
> You said you wanted to avoid setting the meta of an item every time a different player holds it, but with your suggestion you would have to set the meta of a player every time they get an item that you want to be affected by your suggestion.

This is a real problem that i not have considerate... You suppose to use at this scope the metadata from empty hand? another approach can be use data from player:get_attribute(), if this is possible, i can have multiple data for each types of tool used. In this manner i need to set attribute only one time, when a player use this tool for the first time, and no more. 
Anyway, this was only a suggest inspired from [](https://github.com/minetest/minetest/pull/5612), If this need a lot of work, or is useless, feel free to close this issues or leave it open in case someone think is a good add-on.
Thanks

**Comment by raymoo** [comment] 2017-04-23 17:10
I feel like what you want would be done better using hooks that don't exist yet. Such as a client-side "calculate_tool_capabilities" callback for tool definitions that gets called whenever the player tries to dig something.

**Comment by pandaro** [comment] 2017-04-23 19:17
I feel like it has disturbed a discussion between professionals. If there is nothing interesting about what I suggested closing the discussion and ending there.
With respect, Stephen

**Comment by rubenwardy** [comment] 2018-04-09 19:48
per-item possible with set_tool_caps
per-player a duplicate of #5465

**Closed** 2018-04-09 19:47 UTC
