### ISSUE TITLE
Windows: "Could not create OpenGL driver" despite game working before on same version

### ISSUE THREAD

**Issue by TouhouJevil** [minetest/minetest#10907] opened 2021-02-03 17:49 UTC
##### Minetest version
```
Minetest 5.3.0
```

##### OS / Hardware

Operating system: Windows 8.1
CPU: i don't know

GPU model: i don't know
OpenGL version: OpenGL 1.1.0

##### Summary

The game used to run normal (with 5.3.0) but now it crashes super fast whenever i open it and the debug.txt file says

```
-------------
  Separator
-------------

2021-02-03 14:34:55: ERROR[Main]: Irrlicht: Cannot create a GL rendering context.
2021-02-03 14:34:55: ERROR[Main]: Irrlicht: Could not create OpenGL driver.
```

##### Steps to reproduce
Opening the game.

**Comment by sfan5** [comment] 2021-02-03 18:11
> OpenGL version: OpenGL 1.1.0

This implies you don't have a graphics driver installed. (Microsoft's fallback driver only supports 1.1)
You can try to find out which graphics card you have in the Device Manager and see if you can grab the correct drivers for it.

**Comment by rubenwardy** [comment] 2021-02-03 18:14
When it last ran, they used 1.1.0:

![image](https://user-images.githubusercontent.com/2122943/106790563-a7e03080-664b-11eb-8abc-501cca9328f8.png)

**Comment by rubenwardy** [comment] 2021-02-03 18:36
Attempting to specify `video_driver = direct3d8` results in 

```
-------------
  Separator
-------------

2021-02-03 15:32:36: ERROR[Main]: Invalid video_driver specified; defaulting to opengl
2021-02-03 15:32:36: ERROR[Main]: Irrlicht: Cannot create a GL rendering context.
2021-02-03 15:32:36: ERROR[Main]: Irrlicht: Could not create OpenGL driver.
``

**Comment by sfan5** [comment] 2021-02-03 18:45
I don't think our Irrlicht is built with that, try `direct3d9`.

**Comment by rubenwardy** [comment] 2021-02-03 19:21
Using `direct3d9` works.

Despite this being a workaround, I suggest closing this issue as the problem is fairly obscure

**Comment by DeltaNedas** [comment] 2021-02-12 02:26
surely GPU drivers aren't an outrageous requirement?

**Comment by SmallJoker** [comment] 2021-02-12 09:32
> (Does Settings support \r\n properly? Is a missing newline a problem?)

@rubenwardy Yes, that's stripped by `trim` in `parseConfigObject`.

I am sure that the graphics driver is either a wrong one or not properly installed. Even graphics cards from 2003 (FX 5200 for example) support at least OpenGL 1.4.
This is a PBKAC, not Minetest's fault.

**Closed by SmallJoker** 2021-02-12 09:32 UTC
Labels: Possible close, Unconfirmed bug
