### ISSUE TITLE
Entities appear again with some latency after restarting a world.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#10884] opened 2021-01-30 11:11 UTC
##### Minetest version
```
Minetest-5.4.0-dev-5e6df0e7b and below

```

##### Summary
I suppose this is already historical bug in Minetest because it is caused in 5.0.x and 0.4.x versions. If any entity is spawned in the singleplayer mode and the player leaves the world and then restart it, that spawned entity will appear again, but with some latency (around 2-3 seconds).

Why is an entity unable to appear immediately?

**Comment by Zughy** [comment] 2022-04-27 08:04
I can confirm in 5.5.0 as well, it happens all the time with the spawned boats I use to test my mods (from MTG)

**Comment by sfan5** [comment] 2022-05-26 19:44
This is because block activation is only done every so much seconds:
https://github.com/minetest/minetest/blob/8b74257bf3cbb54e78614ac6aaaba79adf75cc8e/minetest.conf.example#L1604-L1606

**Comment by lhofhansl** [comment] 2022-11-02 22:28
@sfan5 I find that the commit you linked does not work. It only tries once, and blocks that get loaded the first time are still not immediately activated when they are emerged.

What I find works well is to add a divider for the wanted_interval that starts at (say) 10 and decremented down by 1 on each server step, until it reaches 1. Now in the beginning the server is running more often for a bit and slowly slowing it down to final interval. With that I find that the player does not start fall when attached to a flying entity.
Could also imagine doing it for a time (maybe 10s) and decrementing by dtime on each server step.
I'll file a PR when I get to it.

**Comment by sfan5** [comment] 2022-11-02 22:56
The commit does absolutely work, it just doesn't fix this issue: https://github.com/minetest/minetest/pull/12378#issuecomment-1140111364

The divisor idea sounds simple and usable, though you'd want it to happen on player join and not on server start.
A "real" fix for this would be to remember selected-but-not-activated blocks and activate them instantly once they are loaded. Not sure if you need an emerge callback for this but I bet there's a good place where such code could live.

**Comment by lhofhansl** [comment] 2022-11-03 05:18
Something like this (would rename the member of course, but you get the gist)... Downside is that the server would be doing a flurry of work each time a player joins.
```
diff --git a/src/serverenvironment.cpp b/src/serverenvironment.cpp
index f893064de..905d44a02 100644
--- a/src/serverenvironment.cpp
+++ b/src/serverenvironment.cpp
@@ -634,7 +634,7 @@ PlayerSAO *ServerEnvironment::loadPlayer(RemotePlayer *player, bool *new_player,
 	addActiveObject(playersao);
 
 	// Update active blocks asap so objects in those blocks appear on the client
-	m_force_update_active_blocks = true;
+	m_force_update_active_blocks = 10;
 
 	return playersao;
 }
@@ -1342,8 +1342,7 @@ void ServerEnvironment::step(float dtime)
 	/*
 		Manage active block list
 	*/
-	if (m_active_blocks_mgmt_interval.step(dtime, m_cache_active_block_mgmt_interval) ||
-		m_force_update_active_blocks) {
+	if (m_active_blocks_mgmt_interval.step(dtime, m_cache_active_block_mgmt_interval / m_force_update_active_blocks)) {
 		ScopeProfiler sp(g_profiler, "ServerEnv: update active blocks", SPT_AVG);
 
 		/*
@@ -1412,8 +1411,10 @@ void ServerEnvironment::step(float dtime)
 
 		// Some blocks may be removed again by the code above so do this here
 		m_active_block_gauge->set(m_active_blocks.size());
+
+		if (m_force_update_active_blocks > 1)
+			--m_force_update_active_blocks;
 	}
-	m_force_update_active_blocks = false;
 
 	/*
 		Mess around in active blocks
diff --git a/src/serverenvironment.h b/src/serverenvironment.h
index 2ecd55ce8..a4b877335 100644
--- a/src/serverenvironment.h
+++ b/src/serverenvironment.h
@@ -462,7 +462,7 @@ class ServerEnvironment final : public Environment
 	IntervalLimiter m_object_management_interval;
 	// List of active blocks
 	ActiveBlockList m_active_blocks;
-	bool m_force_update_active_blocks = false;
+	int m_force_update_active_blocks = 1;
 	IntervalLimiter m_active_blocks_mgmt_interval;
 	IntervalLimiter m_active_block_modifier_interval;
 	IntervalLimiter m_active_blocks_nodemetadata_interval;
```

**Comment by lhofhansl** [comment] 2022-11-06 00:58
#12925
#12927

**Closed** 2022-11-10 23:25 UTC
Labels: Bug, @ Server / Client / Env.
