### ISSUE TITLE
Falling in liquids doesn't take viscosity into account for half a node

### ISSUE THREAD

**Issue by Lemente** [minetest/minetest#12684] opened 2022-08-10 20:05 UTC
##### Minetest version

```
5.6
```

##### OS / Hardware
Operating system: Windows 10

##### Summary
when you fall into a viscous liquid, like lava, viscosity seems ignored for the top half of the node, even with almost no initial speed
But once you are in the lava, if you swim almost at the top, just before your feet reach the surface, you will sink slowly, as expected

this makes viscous liquids 

##### Steps to reproduce
throw yourself into lava o_o
try with extreme viscosity values

**Comment by Zughy** [comment] 2022-08-10 20:43
Mmm.. I don't know, it seems pretty realistic to me (?)

**Comment by Lemente** [comment] 2022-08-11 00:32
Maybe it is a game design decision.
Though to me the behavior looks unexpected because of the lack of initial speed.
Swimming to just above the liquid surface will make you instantly sink half the node, while swimming just below it will make you sink according to viscosity.

![minetest_aLDlFdxTLo](https://user-images.githubusercontent.com/27686967/184039491-89f324a0-73af-4c28-bfa7-41ff33a1e391.gif)

After doing some research, it appears that the current behavior kinda ressembles the behavior of "sheer thinning fluids". Liquids that become more liquid/less viscous the more force is applied to them. Like ketchup and ... lava.
But even if it was done one purpose, I would argue that it is very crude anyway, and doesn't seem to adapt to the liquids viscosity.

Because of this sudden drop, it is impossible to make very viscous liquids you can walk on, like quicksand or tar. The viscosity is also limited to 7, which is quite far from the most viscous liquid we can imagine.

I guess this could be turned into a feature request for better viscosity for liquids, including non-newtonian fluids. This would allow for more realistic lava, and allow for quicksands. And probably other real or fictional fluids. And walking on custard.
It could even take fall damage into account, so falling from too high would kill you the moment you touch the surface of the liquid. It would also have to differentiate between the moment you are walking, and the moment you are swimming. Which I guess would depend on how deep you are in based of the viscosity. You would also be slowed down by trying to walk on it, but much less than swimming in it.

Anyway, I'll let you decide what to do with the original issue!
thanks

**Comment by Lemente** [comment] 2022-08-11 11:53
New info, in the .conf, parameter ```movement_liquid_sink``` says ```Negative values will cause you to rise instead.```

But when using a negative value, we still fall half a node before rising. And once we reach the top, we fall again.

Similar issue with ```movement_liquid_fluidity = 0.001```

**Comment by Zughy** [comment] 2022-08-11 12:12
Putting a "Question" label so that core devs can speak out about what the correct behaviour should be. Thank you for your in-depth reports :)

**Comment by Zughy** [comment] 2022-08-14 12:43
Also, related: #6123

**Comment by Wuzzy2** [comment] 2022-08-14 13:24
All of you are wrong.

Here is the REAL bug report:

* If a player moves through a `move_resistance` or `liquid_move_physics` node with their upper body half only ("head") (rather than their lower body half ("feet")), they are not slowed down

This is a bug, and I can prove it.

## Overview

This bug actually is only partially related to liquids. It affects both `liquid_move_physics` and `move_resistance`. So things like cobwebs (that use `move_resistance`) are affected as well. **To understand the problem, it is very important to stop thinking of “liquid nodes” here**, this term is not exactly useful since the liquid properties have been all decoupled now. Is a “liquid node” the rendering? The physics? The liquid spread? Everything together? Games can specify each liquid-related property separately now, so we should treat them as separate.

For proper analysis, **we must look at the specific node properties that affect player physics. These are `move_resistance` and `liquid_move_physics`**. IIRC, both of these use the same code to check if the player is affected.

Therefore, the claim that this is entirely a "liquid" problem is wrong. It goes deeper.
To test this properly, we also have to completely ignore stuff like liquid flow as this will generate new nodes that just interfere with testing.

## How to reproduce

To test, just place a few such nodes with `move_resistance` or `liquid_move_physics` in the air (make sure they do NOT spawn nodes like flowing liquids!), so that they float above the ground, with 1 air block separating it from the ground. When you walk through it normally, you are not slowed down at all.

1. In DevTest, use `testnodes:move_resistance7`  and `testnodes:move_resistance_liquidlike7` (a `move_resistance` node with `liquid_move_physics` enabled.
2. Walk through them, so that your "head" is in the test nodes, but your feet walks through air
3. Now place them actually on the floor and walk through them again. Your "head" must now be in air, but your "feet" are in the test nodes
4. Note the difference.

Only those on the floor slow you down, but not when you walk through them with your "head".

The first node is a `move_resistance` node (like a cobweb). The 2nd node is behaves like "classic" liquids but is stripped down to the point to use liquid player movement physics only to get rid of side effects like flowing. This is analogous to e.g. MTG lava source.

In contrast, if you do this test but with nodes that hurt you by `damage_per_second`, they deal damage no matter if they are in your "head" or your "feet".

You can easily reproduce this in MTG as well:

1. Place a field of papyrus (one node high)
2. Place water sources on top of all papyrus nodes
3. Walk through the papyrus and note your speed and compare it with a "full" water pool

This is completely analogous to the DevTest test, it's just that MTG needs the papyrus to prevent the water to flow downwards.

## Why this is a bug

Note that `move_resistance` alone is not directly liquid-related (think of cobwebs) which is why I clearly state this is a bug. Obviously, we *do* *at least* want `move_resistance` to work also when the player is only with their "head" in it, there are no excuses like "Newtonian liquids" or similar here.

Note this behavior is very, very old, long before the liquids got decoupled. You can reproduce this bug in 0.4.17 if you use "floating liquids". I could swear I already posted an issue but I can't find it. \*shrug\*

## How to fix?

I'm not sure. First of all, I think 100% the raw `move_resistance` should be fixed, i.e. that the physics kick in no matter with which body part the player is touching it. It should probably work like `damage_per_second` which also does damage if you only touch it with the upper half of your collision box, maybe the same code for collision/overlap detection can be used?

As for `liquid_move_physics`, I think it would also be better if it would be fixed as well. It just feels wrong that a floating liquid completely ignores you if you walk through it with your upper body part only. I don't really see a justification, it seems unintended. I also don't really see a good real-world use case for this. So probably just fix this as well. Note that floating nodes with liquid move physics are NOT an esoteric thought experiment, they are easy to make even in MTG. You can make water "float" by putting e.g. papyrus below it, or signs, etc. Same for MCL2 and many similar games that allow similar weird tricks.

But as a compromise, there could be a setting to bring the "head ignore" movement physics back. But I'm not really convinced this is needed, I like to hear an use case for this first.

**Comment by Wuzzy2** [comment] 2022-08-14 13:36
Also, the liquid sinking speed has *nothing* to do with this issue. The problem is when Minetest considers a player to be "inside" a node with `move_resistance` / `liquid_move_physics` (and thus, affected by such physics). Currently, this is only the case when the player is in with their "feet", but not with their "head". Thus, when a player is only touching the node with the "head", the liquid sinking speed does not kick in either.

I suggest to consider the player to be affected by `move_resistance` / `liquid_move_physics` when *either* "head" or "feet" (or both) are touching the node, similar to how `damage_per_second` does it.

Oh, one clarification is still necessary: In case the player is in multiple nodes with different `move_resistances` at once, the highest value shall "win". This is just because it seems to be the simplest and most pragmatic solution, better to not over-complicate this with averaging, etc.

**Comment by Zughy** [comment] 2022-08-16 00:47
@Wuzzy2 would you please be so kind to open a generic issue about your report (and close this one)?

**Comment by Wuzzy2** [comment] 2022-08-17 09:08
Hmm, I could *swear* I have posted something like this before. Let me first check before I post a dupe …

Thanks for reminding tho.

**Comment by Wuzzy2** [comment] 2022-09-24 01:16
New issue here: #12808

**Comment by rudzik8** [comment] 2022-09-24 08:14
> New issue here: <link>

can we now close this one as a duplicate?

**Comment by Wuzzy2** [comment] 2022-09-24 10:32
Closing as duplicate of #12808.

**Closed by Wuzzy2** 2022-09-24 10:32 UTC
Labels: Bug, @ Server / Client / Env., Duplicate
