### ISSUE TITLE
Minetest 5.1.0 [Main Menu] (Not Responding) Windows 10

### ISSUE THREAD

**Issue by FullTimeLinux** [minetest/minetest#9096] opened 2019-11-09 04:54 UTC
##### Minetest version
Minetest 5.1.0

##### OS / Hardware

Operating system: Windows 10
CPU: 64bit Intel

GPU model:
OpenGL version:

##### Summary
When connecting to pandorabox server minetest is unresponsive [EDIT by paramat: for 3 mins] when attempting to load media. See image. 

##### Steps to reproduce

1. boot minetest
2. connect to pandorabox
3. watch as minetest hangs at media 0%
![minetestNotResponding](https://user-images.githubusercontent.com/43261056/68523158-f3f2c880-0282-11ea-8cf2-19cbcafb918a.png)

**Comment by SmallJoker** [comment] 2019-11-09 08:30
Is it temporary or does Minetest hang forever?

**Comment by FullTimeLinux** [comment] 2019-11-09 21:56
it is temporary, and it happens exactly when the progress bar gets to Media. I timed how long it took to connect and it was 2 minutes and 50 seconds.

**Comment by LoneWolfHT** [comment] 2019-11-09 23:41
This happens with all Minetest versions AFAIK. I had this back when I used Windows (7)

**Comment by srifqi** [comment] 2019-11-10 23:30
The amount of mods installed on Pandorabox server (298 mods) may cause the lag.

**Comment by LoneWolfHT** [comment] 2019-11-10 23:40
> The amount of mods installed on Pandorabox server (298 mods) may cause the lag.

I'm pretty sure all that would do is increase the amount of time it wouldn't respond for. More mods usually just means it'll take longer to load media

**Comment by FullTimeLinux** [comment] 2019-11-11 22:12
I'm going to take some time and run an experiment on how long it takes to connect. Please don't close this issue.

**Comment by theolodger** [comment] 2020-07-16 06:41
i personally get the freeze at 92% media, and it stays for a lot longer than 2 minutes...

**Comment by BruceMustache** [comment] 2020-08-06 21:02
I can reproduce that on 2 laptops

**Comment by paramat** [comment] 2020-08-09 01:32
> Is it temporary or does Minetest hang forever?

> it is temporary, and it happens exactly when the progress bar gets to Media. I timed how long it took to connect and it was 2 minutes and 50 seconds.

> The amount of mods installed on Pandorabox server (298 mods) may cause the lag.

So surely this is expected, downloading large amounts of media, for which 3 mins is not surprising?
Pandorabox has homedecor and all the big mods, nuff said.
Issue title is misleading.
Close?

**Comment by paramat** [comment] 2020-08-09 01:39
Duplicate of #1665 

> My minetest window freezes while it loads the media.

> Thats because you use Windows.

**Closed by paramat** 2020-08-09 01:39 UTC
Labels: Possible close, Unconfirmed bug

**Comment by BruceMustache** [comment] 2020-08-10 01:27
The clouds aren't animated in some parts of loading
Maybe fixing this can make minetest windows stopping hanging
I think minetest should support bugs of all OS
