### ISSUE TITLE
Ungraceful failure when audio is not detected

### ISSUE THREAD

**Issue by ExeVirus** [minetest/minetest#8851] opened 2019-08-23 22:25 UTC
When windows 7 has all sound devices disabled (long story), and you start minetest.exe normally, this error message pops up:

![image](https://user-images.githubusercontent.com/44562154/63626823-ca56c900-c5d2-11e9-9f68-96c62f96f928.png)

Which is about as useful as just saying "error". Google doesn't help with the issue and my "diagnostics" of restarting my computer doesn't automatically enable the audio drivers, so normal people would just assume the game doesn't work on their computer or reinstall, and become very frustrated in either case.

I don't know if we are in control of this error message, but perhaps we could put a warning somewhere the general public would see it?

**Comment by sfan5** [comment] 2019-08-24 08:51
duplicate of #7250

**Closed by sfan5** 2019-08-24 08:51 UTC
