### ISSUE TITLE
Let me move the config dir

### ISSUE THREAD

**Issue by SoniEx2** [minetest/minetest#8491] opened 2019-04-27 09:36 UTC
##### Issue type

 - Feature request
 
##### Minetest version

```

```

##### OS / Hardware

Operating system:
CPU:

GPU model:
OpenGL version:

**Comment by SmallJoker** [comment] 2019-04-27 10:49
Edit your text and (ask to or) re-open this issue afterwards.
Not enough information, closing.

**Comment by SoniEx2** [comment] 2019-04-27 10:52
Let me move all the things: configs, saves, etc to whatever places I want.

like XDG but without XDG. (or with XDG if you wanna be kind)

**Comment by SoniEx2** [comment] 2019-04-28 01:18
I'm on firefox, github is just crap.

**Comment by paramat** [comment] 2019-04-28 01:20
Your descriptions are sloppy and unclear, 'Let me move ...' can mean either:
Let me make a PR to move dirs to where i think they should be.
Or:
Add a feature that allows users to move dirs to wherever they want.

From https://github.com/minetest/minetest/issues/8492#issuecomment-487310568 it seems the latter:

> in any case, being able to move the dirs means I can also use different dirs (i.e. "profiles") if I want to, without having to reinstall and stuff.
a thing I made (unrelated to minetest) uses XDG ( https://cybre.tech/SoniEx2/ganarchy/src/branch/master/ganarchy.py ) and I have to use the XDG variables all the time because it can only handle one project at a time but I have multiple projects I wanna keep track of so I use different XDG locations for the different projects.

Never mind your personal benefit, how would this benefit all MT users?

> like XDG but without XDG.

From #8151 : 
> The biggest benefit of XDG Base Directory is the ability to trivially move all configs and data around.

How is this request significantly different from #8151 which has just been closed as a duplicate of earlier requests that were rejected?
It seems you have now opened 3 duplicate requests for XDG despite it being rejected.
You should probably have replied in #8151 instead since this is so similar.

Doesn't the rejection of XDG also cover whay you are now requesting?

I'm using Firefox too with no problems.

**Comment by SoniEx2** [comment] 2019-04-28 01:32
the basic idea is that we don't have profiles unless you spawn a whole nother OS user.

I'd like to have profiles without spawning a whole nother OS user. makes sense? XDG lets you have that.

**Comment by paramat** [comment] 2019-04-28 03:21
I can't judge if this is a valid non-duplicate request (i'm understandably sceptical) so i'll reopen it for other core devs to consider.

**Closed** 2020-04-10 00:02 UTC
Labels: No core dev support long term, Request / Suggestion
