### ISSUE TITLE
Player visual `sprite`, `upright_sprite` or `cube` disappears when near a light source and shaders are disabled

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#12944] opened 2022-11-08 17:00 UTC
##### Minetest version
```
5.6.1
```

##### OS / Hardware
Operating system: GNU/Linux

##### Summary
If the player has a visual of type `sprite`, `upright_sprite` or `cube`, shaders are disabled and the player is near a light source, the player visual disappears.

##### Steps to reproduce
1. Start with default Minetest config
2. Disable shaders
3. Start DevTest
4. Switch the camera so you see yourself
5. Place a light source
6. Go near the light source

(For testing other visuals)
7. From the Chest of Everything, give yourself the Object Property Editor
8. Grant yourself `server`
9. Punch with your new tool in the air
10. In the list, edit "visual" to `"sprite"`, `"cube"` or another visual you like to test

In all cases your visual shuold be visible at all times no matter if you are near or far from the light source.
However, once you have approached the light source, your visual becomes invisible. If you go away from the light source again, you become visible again.
In my tests, the 3 visuals I tested make no difference. The `"mesh"` visual appears to work fine, however.

**Comment by fluxionary** [comment] 2022-11-08 18:11
at some point i noticed that the text of signs (upright sprite) didn't show up if i disabled shaders, but i never dug into the exact parameters that triggered that behavior. thanks for reporting this.

**Comment by Wuzzy2** [comment] 2022-11-08 20:30
Update: Apparently this is not limited to the player. It also occurs to regular entities with the same visuals as reported above.

To test this, just spawn `testentities:cube`, `testentities:sprite` and `testentities:upright_sprite` near a light source in DevTest.

**Comment by Warr1024** [comment] 2022-11-22 17:19
Same problem as #12853; should probably be merged with that.

**Comment by SmallJoker** [comment] 2022-11-22 17:24
Duplicate of #12853.

**Closed by SmallJoker** 2022-11-22 17:24 UTC
Labels: Unconfirmed bug, @ Client / Audiovisuals
