### ISSUE TITLE
White stripes when fsaa is enabled

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6860] opened 2017-12-30 14:04 UTC
When using fsaa (here 2x), there's no proper edge between two polygons of nodebox nodes:
![screenshot_20171230_150038](https://user-images.githubusercontent.com/3192173/34454764-9628a2be-ed72-11e7-92e8-c947c018333f.png)

Without fsaa there's no white stripe:
![screenshot_20171230_150123](https://user-images.githubusercontent.com/3192173/34454766-99e850a2-ed72-11e7-9982-567afa1af83e.png)

As numberZero wrote, this happens because the neighbouring texel is used by fsaa. If it is transparent, the edge becomes half-transparent after blending.

**Comment by sfan5** [comment] 2017-12-30 14:13
Can confirm, NVIDIA gpu here.

**Comment by sofar** [comment] 2018-01-04 21:52
Confirmed as well.

**Comment by numberZero** [comment] 2019-01-06 19:30
The reason is probably rounding error, just like in #4912. Unlike solid nodes, however, nodeboxes have inexact vertex coordinates as they use `rotate*` functions all the time. Enabling FSAA increases rendering resolution effectively, which in this case makes the gaps visible. Note that they aren’t white but pink, i.e. blended; that means they are less than 1 pixel wide.

**Comment by numberZero** [comment] 2019-01-07 14:22
@HybridDog Is the node in your post really a nodebox? It looks more like a nodebox-styled mesh node.

**Comment by numberZero** [comment] 2019-01-07 14:37
@HybridDog What’s the node in your post?

**Comment by HybridDog** [comment] 2019-01-09 19:53
The node is from that mod: https://github.com/hybriddog/riesenpilz

The vertices of the top and side polygons are the same, so shouldn't they also have the same rounding error in the end?

**Comment by numberZero** [comment] 2019-01-09 21:50
Not a bug. Your (side) texture has transparent border, and the stripes 
result from blending with that border. But as `use_texture_alpha` is 
disabled, the edge is sharp; it’s at α=0.5 (after blending).

**Comment by HybridDog** [comment] 2019-01-11 15:36
Thanks for your explanation. If I add an almost fully transparent black background, the borders are black because of disabled use_texture_alpha:
![screenshot_20190111_162353](https://user-images.githubusercontent.com/3192173/51042757-60e2f680-15bd-11e9-8cfd-bef29ad706c1.png)

I think this is a bug because it affects every node:
![screenshot_20190111_163236](https://user-images.githubusercontent.com/3192173/51043292-a653f380-15be-11e9-81bf-9e69d801dd42.png)
In comparison to other games, minetest doesn't use linear or cubic interpolation for textures.
Is it possible to stretch the textures by an extremely small value so that fsaa does not use the neighbouring texel on corners?

**Comment by HybridDog** [comment] 2019-01-18 07:06
> […] but that actually makes the stripes visible just like FSAA does […]

You're right, I haven't thought about texels used for interpolation.

> Maybe, but you’d better just pad your textures.

This only affects my nodes. I think that without interpolation and certain textures (see the previous screenshot), FSAA makes the corners look worse, which defeats its purpose.

**Comment by numberZero** [comment] 2019-01-19 19:54
> I think the problem is a bug because it affects every node (see the white stripe next to the black area):

See also the *black* stripe next to the white area. The problem here is *exactly* the same: blending with a wrong texel; this time, that’s the opposite edge of the texture. Try placing several nodes in a row, edges should look clear between them.

Also note that with filtering instead of FSAA, such node wouldn’t look nice at all as the stripes would be blended with each other. But there is an option to disable texture repeating in one or both dimensions, that should help.

> Is it possible to stretch the textures by an extremely small value so that fsaa does not use the neighbouring texel on corners?

Okay, that might be reasonable, iff filtering is disabled. With filters, such scaling could break smoothness. But I just noticed one tiny detail that probably can’t be fixed in any better way: gray pixels at the black stripe’s end. These are from the bottom part of the bricks texture. But disabling tiling would break the look with filtering&hi-res textures, so that should be fixed in some other way. Naturally, I’d like to disable tiling automatically when filters are disabled, but that would help full nodes only.

There is still a problem of *how* to stretch the textures. I’ll try to find a sane method for nodeboxes (meshes are expected to have good texture coordinates already)

**Comment by HybridDog** [comment] 2019-01-20 10:47
> I’ll try to find a sane method for nodeboxes

Thanks, maybe removing/adding a very small value to those variables makes them stretch.
https://github.com/minetest/minetest/blob/9512c2986e2d5b8388860a51cce2a75f37e67bf6/src/client/mesh.cpp#L474-L480

**Comment by HybridDog** [comment] 2019-01-20 13:03
https://github.com/HybridDog/minetest/commit/63b70243b084a7b1cd805678a5a6f9998343ff2b#diff-15a21807c0c1462b310d02ab1a16763b
![2019-01-20-135509_1920x1056_scrot](https://user-images.githubusercontent.com/3192173/51439509-d3d62680-1cbb-11e9-9add-53e8c4b80ec0.png)
When stretching the textures another problem appears: The texels in concave corners are moved too, see the ring around the mushroom stem.

**Closed** 2021-04-18 15:09 UTC
Labels: @ Client / Audiovisuals, Bug
