### ISSUE TITLE
only load textures as needed

### ISSUE THREAD

**Issue by DI3HARD139** [minetest/minetest#6464] opened 2017-09-26 00:28 UTC
Is there a way to allow Minetest to load textures when they are needed rather than loading them all at once? Specifically when high res texture packs are being used?

**Comment by raymoo** [comment] 2017-09-26 01:02
No, unless someone implements the feature. How much memory does such a texture pack use?

**Comment by rubenwardy** [comment] 2017-09-26 01:17
Duplicate of #3528

**Comment by raymoo** [comment] 2017-09-26 01:19
I don't think this is a duplicate of the other, since the other one asks for being able to send new / updated textures to the client, but this issue asks for the client to automatically unload textures that are not currently needed, to save memory.

**Comment by dsohler** [comment] 2017-09-28 09:06
> Duplicate of #3528

Not even close.

**Comment by paramat** [comment] 2017-09-28 15:20
See #3528 the idea has a problem due to the time to send the texture to a client (especially for large texture files) causing lag in that texture appearing.

> load textures when they are needed rather than loading them all at once

You mean rather than sending textures to the client before entering a world? I know that media download can be slow, but that time is not in-game time so is not a problem, you can go and do something else while waiting, your suggestion would mean textures not appearing immediately while in-game, which would be much worse, unacceptable in fact, especially for high res textures.

>  this issue asks for the client to automatically unload textures that are not currently needed, to save memory.

How do you know that? the description does not imply that at all.

**Comment by paramat** [comment] 2017-09-28 16:51
@DI3HARD139 could you confirm what you are requesting? I'm assuming you request an option for all textures to be sent from server to client in-game the first time they are needed, instead of all at once during 'media download' before a game session? I assume this is to reduce the wait during 'media download'?

**Comment by raymoo** [comment] 2017-09-28 17:44
@paramat The issue description is wanting, but he explained in in more detail in IRC. The issue is ram/vram usage, so one way to solve it would be to download all textures to disk and then keep in memory the necessary ones.

**Comment by paramat** [comment] 2017-09-28 18:25
Ok, was the discussion in a logged channel? If so please link.

**Comment by paramat** [comment] 2017-09-28 18:55
> one way to solve it would be to download all textures to disk and then keep in memory the necessary ones.

That;s no solution either, if textures are not in RAM then they take time to fetch, either from the server or from a harddisk. It's impossible to know ahead of time what textures will be needed, so there will always be a delay before the texture is loaded. Also, it's possible a single scene in MT will contain most or all textures, so a spike of RAM use as high as before is unavoidable.

Essentially, if a player is low on RAM they simply shouldn't use a very high-res texture pack (and MT is designed to use modeate to low resolution packs). A complex system of load on demand is not justified.

**Closed by paramat** 2017-09-28 18:55 UTC
Labels: @ Client / Audiovisuals, Feature request, Non-trivial, Possible close
