### ISSUE TITLE
Tabs not clicking in main menu on MacOS

### ISSUE THREAD

**Issue by jacobgonzales20** [minetest/minetest#9911] opened 2020-05-22 02:01 UTC
The tabs in the main menu of minetest aren't clicking properly on macOS Catalina. Minetest is version 5.2.0, MacOS Catalina is version 10.15.4.

Issue:
When i launch minetest and click the settings tab it doesn't click, the only way to click the tabs is to close the game again and hover over the tabs for 1-3 seconds then click the letters in the box.

**Comment by SmallJoker** [comment] 2020-05-22 09:43
Relevant code:
https://github.com/minetest/minetest/blob/1bcdc2d7e9d91f21cd9be2836b777c5088313fa8/src/gui/guiFormSpecMenu.cpp#L2092-L2099

Is this a new issue? Since when does it occur?
Is it fixed in a 5.3.0-dev build? (if you can test that)

**Comment by jacobgonzales20** [comment] 2020-05-22 16:49
It started according on the first install of the game 2 days ago, and yes it’s a new issue and I’m not able to install the dev build as it’s a friends computer not mine. What I was thinking it could be to is it’s a Mac book air so idk if it has enough system resources when the game first launches, like maybe when you launch the game it takes a bit for assets to load but it’s weird cause the game plays fine when in game.

**Comment by rubenwardy** [comment] 2021-01-28 18:14
Reopening other issue, duplicate of #10856

**Closed by rubenwardy** 2021-01-28 18:14 UTC
Labels: Formspec, Mac OS, Unconfirmed bug
