### ISSUE TITLE
(Another) Possible memory leak

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2653] opened 2015-04-26 01:26 UTC
After playing for about 10-20 minutes, I noticed the gameplay was becoming erratic, starting to freeze every few seconds. I checked the system monitor, and there it was- almost all of my 4GB of memory was taken up by Minetest. I noticed this on a recent build, then tested it on the latest git, and got the same result.
![screenshot from 2015-04-25 20 23 22](https://cloud.githubusercontent.com/assets/8821916/7335471/18721138-eb91-11e4-90aa-c182cfff6496.png)
And right after closing Minetest:
![screenshot from 2015-04-25 20 23 38](https://cloud.githubusercontent.com/assets/8821916/7335480/6af2871c-eb91-11e4-9f16-d2b19d191431.png)
Again, with a newer build:
![screenshot from 2015-04-25 21 10 00](https://cloud.githubusercontent.com/assets/8821916/7335482/8856bc06-eb91-11e4-8c7c-c3f244d7f385.png)
And again, after closing:
![screenshot from 2015-04-25 21 10 20](https://cloud.githubusercontent.com/assets/8821916/7335485/a9497f34-eb91-11e4-94f6-dea8e0feced1.png)
And this is soon after joining:
![screenshot from 2015-04-25 21 16 51](https://cloud.githubusercontent.com/assets/8821916/7335486/c2ac64fa-eb91-11e4-8b2b-b4165a8edb75.png)

**Comment by Wayward1** [comment] 2015-04-26 13:26
Callgrind logs will be provided soon

**Comment by est31** [comment] 2015-04-26 14:13
What are the mods?

**Comment by kilbith** [comment] 2015-04-26 15:09
Duplicate of https://github.com/minetest/minetest/issues/2045 (another specific-less, non-correlative mem. leak report)...

**Comment by Wayward1** [comment] 2015-04-26 15:18
Oops, I was under the impression that one had been fixed...

**Comment by Wayward1** [comment] 2015-04-26 15:20
Spacific-less? Non-correlative?

**Comment by est31** [comment] 2015-04-26 16:27
Memory leaks are hard to find @kilbith.

**Comment by Wayward1** [comment] 2015-04-26 17:00
@est31, in answer to your reply, I was playing on a server, and I always have enable_mesh_caching = false

**Comment by tenplus1** [comment] 2015-04-30 16:10
I wonder if this could be the problem on Xanadu server causing SEGFAULT errors every half an hour or so...  no warning, no error apart a Segmentation Fault...

**Comment by est31** [comment] 2015-04-30 18:26
The only way leaks can cause segfaults is when memory runs out.

**Comment by tenplus1** [comment] 2015-04-30 18:58
The server has 4gb memory and minetest hardly uses 1gb...

**Comment by est31** [comment] 2015-04-30 19:19
Then your crashes aren't caused by this bug.

**Comment by paramat** [comment] 2015-07-08 00:14
Confirmed, when flying fast and generating map my memory use rises at 0.6GB per minute.

**Comment by paramat** [comment] 2015-07-08 02:37
In latest dev ba15c98e4d5d7f4bc515e351d6af1a084d46092e

Mgv7, no mods, no shaders, no minimap, flying fast generating new map, view range 128, 0.6GB per minute.
Mgv6, no mods, no shaders, no minimap, flying fast generating new map, view range 128, 0.7GB per minute.
Mgv5, no mods, no shaders, no minimap, flying fast generating new map, view range 128, 0.5GB per minute.
Only rises when generating new terrain.
Only removed when exiting game, exiting to menu and restarting any world or deleting world or starting a new world does not lower memory usage.

**Comment by kilbith** [comment] 2015-07-08 11:44
There's certainly a leak, but this isn't recent.

Flying over the world constantly increases the memory usage as long you have some free RAM. Returning back to the menu does not clear-out the RAM footprint. Minetest eats RAM modules as chocolate bars.

Of course the label [blocker] is appropriate here.

**Comment by paramat** [comment] 2015-07-08 15:51
Yes, i'm bisecting and it's even present in 0.4.10 stable, hard to believe it's gone unfixed for so long.

**Comment by paramat** [comment] 2015-07-09 17:01
I may be wrong about this being due to generating new terrain, it could be due to client loading world and/or creating meshes.

**Comment by paramat** [comment] 2015-07-09 22:15
Now i'm getting occasional drops in memory use when exiting to menu, the amount of the drop is inconsistent between tests, but never seems to be a complete deletion of world data.
I was wrong about this being due to generating new terrain, flying over a pre-generated world has the same behaviour.

**Comment by kilbith** [comment] 2015-07-09 22:40
In Minecraft, flying over the maps keep the RAM usage low and pretty stable. This isn't inherent to the voxel generation.

**Comment by paramat** [comment] 2015-07-10 02:10
As an experiment, in latest 0.4.12dev i set 'client unload unused data timeout' to 60s, generate a large amount of terrain then stopped and stared at the ground for a few minutes to see if memory use would start to fall again, it did not.

**Comment by paramat** [comment] 2015-07-17 22:55
Inconsistent results again. In latest i repeat the above test with timeout at 30s, memory use rises to roughly 500MB and stabilises, but never falls, i thought it would fall after 30s when i stop travelling. This time most memory is cleared when returning to the menu.

**Comment by kilbith** [comment] 2015-07-17 23:11
If you stay immobile on the ground unsurprisingly the RAM usage don't increase. I still confirm the endless leak on flying over new terrains and the absence of clear-out on returning to the menu.

It should never rise unlimitedly like that, no matter if the terrain is new or not.

**Comment by nerzhul** [comment] 2015-07-18 06:57
@kilbith as i said on IRC, RAM usage increase because minetest keep all loaded mapblocks in memory, even if you didn't see it on your screen. We should have a mechanism to unload too far mapblocks. Also this should permit to unload those non seen mapblocks from server.

**Comment by est31** [comment] 2015-07-18 07:22
Agreed, either unload them based on how far they are, or based on how much memory the user makes available.

**Comment by paramat** [comment] 2015-07-18 13:27
> We should have a mechanism to unload too far mapblocks.

I thought 'client unload unused data timeout' did this, if not, i agree to clearing distant blocks from memory.

**Comment by Zeno-** [comment] 2015-07-20 13:39
@paramat please include the output from massif

**Comment by VanessaE** [comment] 2015-08-07 15:41
Unload mapblocks based on some multiplication of both how far they are and how old they are.

**Comment by est31** [comment] 2015-08-10 17:40
@paramat @VanessaE, everybody else, can you reproduce the bug with setting `client_unload_unused_data_timeout = 10` ?

**Comment by paramat** [comment] 2015-08-11 18:06
> I think the blocks are only removed from the map, not irrlicht itself, but prove me wrong

This seems possible, with a short 'timeout' i noticed mapblock meshes were being removed from view, but memory use was not falling as expected.

**Comment by est31** [comment] 2015-08-13 05:58
#3033

**Comment by est31** [comment] 2015-08-13 05:59
Note that 3033 most likely didn't fix the "sometimes the RAM doesnt decline if you go to main menu" bug.

**Closed by est31** 2015-08-13 05:58 UTC
Labels: bug
