### ISSUE TITLE
Possible to sneak jump upwards through solid nodes

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest#4311] opened 2016-07-12 19:13 UTC
https://youtu.be/iNlXsGm5FO0?t=25m10s

**Comment by Fixer-007** [comment] 2016-07-12 23:58
Can confirm.

**Comment by raymoo** [comment] 2016-07-16 06:28
I do this often

**Comment by est31** [comment] 2016-07-16 06:32
Dupe of #3045.

**Closed by est31** 2016-07-16 06:32 UTC
Labels: Bug
