### ISSUE TITLE
Adjustable Liquid Source Height

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#13167] opened 2023-01-22 13:38 UTC
## Problem

Liquid source nodes in Minetest are a full node high, which makes it always feel like the liquid is about to overflow.

## Solutions

Change the height of liquid source nodes in Minetest to not be a full node high. About (14 + ¼) pixels in height would look great.

## Alternatives

Make it possible for subgames themselves to define the height of liquid source nodes.

## Additional context

This is a screenshot of the water source node in Minetest:

![Minetest Water](https://user-images.githubusercontent.com/114245896/213918075-d2a4e8c6-75b4-4da5-8276-315a688e1c93.png)

This is a screenshot of the water source block in Minecraft:

![Minecraft Water](https://user-images.githubusercontent.com/114245896/213917880-707af9fc-9cb9-4120-b246-ee18a68518db.png)

Notice how in Minecraft, the water source block is about (14 + ¼) pixels high, which feels more natural than the 16 pixel height that the water source nodes in Minetest currently use.

**Comment by hlqkj** [comment] 2023-01-22 14:03
But what about the water source nodes which are below the surface ones?

**Comment by Zughy** [comment] 2023-01-23 00:38
Duplicate of #5427

**Closed by Zughy** 2023-01-23 00:38 UTC
Labels: Feature request

**Comment by rubenwardy** [comment] 2023-01-23 14:37
We're likely to require shaders to play Minetest in the future. Shaders are a required part of a modern pipeline, they're not just for fancy effects.

The non-shader version caused lots of bugs and issues that made maintenance harder, so it was removed.

Now, there is an argument for having a lower water source height without waving water

**Comment by hlqkj** [comment] 2023-01-24 07:59
> The problem I have with this solution is that I want a solution that makes the lower liquid source height visible for everybody, and not just me. A way to have this visible on the subgame's side, basically.

This would be ideal indeed, especially since the average player won’t even know there is such a feature, or how to enable it: having to turn something on and then set its “intensity” to zero is deeply counter-intuitive! On the contrary, one would expect to have a normal, flat water if using `water_wave_height = 0.0` with the shader enabled.

> We're likely to require shaders to play Minetest in the future. Shaders are a required part of a modern pipeline, they're not just for fancy effects.

If that’s true perhaps having a different set of defaults for the shaders enable settings could be considered?!

Again, an average (new) player who doesn’t know what a shader is would have a better first catch on the minetest engine capabilities, rather than seeing its “backwards compatibility mode”.
