### ISSUE TITLE
Wrong lighting

### ISSUE THREAD

**Issue by bvs23bkv33** [minetest/minetest#10018] opened 2020-06-09 18:31 UTC
5.3.0-dev-3ad5388c
Debian 10
Celeron G4920
GPU UHD Graphics 610 (Coffeelake 2x6 GT1)
OpenGL 3.0

subj:

![Знімок з 2020-06-09 21-21-32](https://user-images.githubusercontent.com/7599687/84186057-9765bf00-aa98-11ea-980d-dca53503c034.png)

**Comment by LoneWolfHT** [comment] 2020-06-09 18:33
Does `/fixlight here 50` do anything?

**Comment by bvs23bkv33** [comment] 2020-06-09 18:38
nope
![Знімок з 2020-06-09 21-37-41](https://user-images.githubusercontent.com/7599687/84186636-7f426f80-aa99-11ea-86d5-681e43a76ccd.png)

**Comment by KaylebJay** [comment] 2020-06-09 23:40
Wow, that lighting looks really strange. And somehow familiar ... :thinking:

**Comment by paramat** [comment] 2020-06-10 00:36
How was that strange terrain created? Taht could be the cause. You are deep underground on a completely flat area, that does not happen in standard mapgen. Did you use Worldedit?

**Comment by KaylebJay** [comment] 2020-06-10 03:56
Looks like this was made with technic_worldgen, at very least.

**Comment by bvs23bkv33** [comment] 2020-06-10 05:09
yes, technic mod is installed, but this is normal cave, with seed and coordinates you can find the place

**Comment by An0n3m0us** [comment] 2020-06-10 09:48
Confirmed:
Here's a GIF demonstrating 4 different lighting/shader configurations:
![x](https://user-images.githubusercontent.com/49789044/84253454-dc750a00-ab07-11ea-8a63-0e3a21d15672.gif)

**Comment by sfan5** [comment] 2020-06-10 10:45
As a next step it'd be nice if someone could find out if this is a regression and if yes, which commit caused it.

**Comment by An0n3m0us** [comment] 2020-06-10 10:47
I just tested in 5.0.1 (the oldest version I have), and I still see the same results as above.

**Comment by bvs23bkv33** [comment] 2020-06-11 06:23
You need to rotate selection

**Comment by hecktest** [comment] 2020-06-11 07:56
This is a minetest light:
![14](https://user-images.githubusercontent.com/42101236/84359782-69cc6300-abc9-11ea-8a92-a1364f053853.png)
And this is what happens when you place them diagonally:
![stacked](https://user-images.githubusercontent.com/42101236/84359870-8c5e7c00-abc9-11ea-9c6d-761e8cb94c2f.png)
This happens because minetest uses flood fill to spread light.

**Comment by bvs23bkv33** [comment] 2020-06-11 10:50
Lightning on right corner and left corner of every square differs, right corner is more bright even when it is situated to the right from torches

**Comment by hecktest** [comment] 2020-06-11 18:28
That is an optical illusion too, created by the dark and bright spots on the texture. Try replacing the texture with a single color, the difference will be gone.
Can somebody close this already?

**Comment by bvs23bkv33** [comment] 2020-06-11 18:42
I beleive that right corner is more bright while being farther from torch, which is wrong, so nothing to close yet

**Comment by jastevenson303** [comment] 2020-06-11 19:52
:thumbsdown: low priority

**Comment by hecktest** [comment] 2020-06-11 20:37
Have you tested it with a flat texture?

**Comment by An0n3m0us** [comment] 2020-06-11 20:50
This is what I get when using a pink texture:
![image](https://user-images.githubusercontent.com/49789044/84437844-8f8b5380-ac2d-11ea-9c0c-62846b8e21ea.png)

**Comment by bvs23bkv33** [comment] 2020-06-11 20:56
Original screenshot has view in direction +x+z, is this true for last one? If not than this is just texture problem

**Comment by hecktest** [comment] 2020-06-11 21:01
You can even trace the squares with a sampled color to verify that they're identical.
![color](https://user-images.githubusercontent.com/42101236/84438829-74bddc80-ac37-11ea-9ac8-18e17cb253b8.png)

**Comment by bvs23bkv33** [comment] 2020-06-11 21:06
I will need to mirror right part of my screen to compare it to left, but i have no access to that device now and will not have for another two weeks

**Comment by jastevenson303** [comment] 2020-06-11 21:49
Bullshit, Ivan.  I call bullshit.

**Comment by paramat** [comment] 2020-06-12 01:42
@jastevenson303 i deleted your earlier post, the intent was obvious. Please stop the sarcastic or snide one-line shitposting.

**Comment by paramat** [comment] 2020-06-12 01:44
> This is what I get when using a pink texture:

The flat area you are using is not wide enough to clearly show any bug.

The screenshot in the first post seems to show inconsistent lighting either side of that diagonal line, i do not think it is an illusion.

**Comment by hecktest** [comment] 2020-06-12 02:21
It is an illusion caused by a bias in the texture. There's a dark spot in one of the corners, and it adds a bit of a gradient one way, making one side look smoother than the other. This is why the pink stone screenshot does not show it.

**Comment by An0n3m0us** [comment] 2020-06-12 08:37
> Paramat: The flat area you are using is not wide enough to clearly show any bug.

Ah okay. I'll expand the area and try again with the pink texture.

> hecktest: To verify it, just rotate the default_stone texture 180 degrees.

I'll try this too.

**Comment by An0n3m0us** [comment] 2020-06-12 08:58
Normal:
![test1](https://user-images.githubusercontent.com/49789044/84484786-25a59500-ac93-11ea-99b9-9dc4330afd6e.png)

Texture rotated 180 degrees:
![test2](https://user-images.githubusercontent.com/49789044/84484788-26d6c200-ac93-11ea-93fd-efcbe65eb767.png)

Pink texture:
![test3](https://user-images.githubusercontent.com/49789044/84484789-276f5880-ac93-11ea-9b18-3852e46493c7.png)

**Comment by bvs23bkv33** [comment] 2020-06-12 09:14
> It is an illusion caused by a bias in the texture.
Looks like it is

**Comment by SmallJoker** [comment] 2020-06-12 16:33
Light in Minetest does not spread in an uniform circle. Changing this to a circular shape is a non-trivial task and might not be worth the effort.

Human sensor reception bug. Cannot fix.

**Closed by SmallJoker** 2020-06-12 16:33 UTC
Labels: Unconfirmed bug
