### ISSUE TITLE
Player can jump through the ceiling with shift+jump

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#3400] opened 2015-11-24 14:24 UTC
Conditions : 

- The ceiling is 4 nodes above the node where you jump on.
- A node must be placed at (Y+2, Z+1) relative to the node position where you jump on.
- Jumping with shift+jump (higher jump).

-> Player goes through the ceiling.

Video : https://vid.me/RaQ5

**Comment by est31** [comment] 2015-11-25 00:41
Dupe of #3045

**Closed by est31** 2015-11-25 00:41 UTC
