### ISSUE TITLE
Add a launcher like minecraft's launcher

### ISSUE THREAD

**Issue by OguzY4** [minetest/minetest#13817] opened 2023-09-16 20:15 UTC
### Problem

It is a pain to update a program manually.

### Solutions

Add a Minecraft-like launcher.

### Alternatives

Please add it.

**Comment by NathanSalapat** [comment] 2023-09-16 20:40
What platform are you using where it's a pain to manually update Minetest?

**Comment by wsor4035** [comment] 2023-09-16 21:01
see https://forum.minetest.net/viewtopic.php?f=14&t=28624 / https://github.com/minetest-world/mtlauncher for a third party solution

**Comment by OguzY4** [comment] 2023-09-16 21:06
Well, i use windows, but i think that a launcher is always better than
updating manually.

16 Eyl 2023 Cmt 23:40 tarihinde Nathan Salapat ***@***.***>
şunu yazdı:

**Comment by SmallJoker** [comment] 2023-09-17 06:42
There already are semi-automated update programs for Windows which I have found very convenient.
For example, a script for [Chocolatey](https://chocolatey.org/) and/or [Winget](https://github.com/microsoft/winget-pkgs) could be provided so that package updates can be automated along with many others that you already got installed.

**Comment by hlqkj** [comment] 2023-09-20 16:58
@SmallJoker, this has been aroud for sometime now: https://developer.microsoft.com/en-us/microsoft-store/.

I Don't know if it's technically possible, or how hard it would be... Just dropping it here for reference.

**Comment by rubenwardy** [comment] 2023-09-27 22:31
Hi, this feature has been requested before and marked as Won't Add. See previous issues for arguments

Duplicate of #10817, #7102, #4917

**Closed by rubenwardy** 2023-09-27 22:31 UTC
Labels: Feature request, Windows
