### ISSUE TITLE
change request: change the default font

### ISSUE THREAD

**Issue by IniKiwi** [minetest/minetest#13542] opened 2023-05-29 12:07 UTC
## Problem

I thought that the police used them weren't three beautiful
## Solutions

change the font to put a more appropriate one.

## Example
ProFont https://tobiasjung.name/profont/index.php?fs=18&pf=on
![image](https://github.com/minetest/minetest/assets/99270745/a08d3326-e066-4c3a-bc6b-e8f9e6462510)
![image](https://github.com/minetest/minetest/assets/99270745/ff669cba-3ebf-464c-b298-906c02eb7b96)
![image](https://github.com/minetest/minetest/assets/99270745/010eb800-fa2c-47e3-8ebf-4b99b3814abf)
![image](https://github.com/minetest/minetest/assets/99270745/6d39679f-e9ac-4167-9010-43e31aa4c484)

**Comment by SmallJoker** [comment] 2023-05-29 13:34
Duplicate of #11518 and #11455

**Closed by SmallJoker** 2023-05-29 13:34 UTC
Labels: Feature request
