### ISSUE TITLE
[Feature Request] on_hp_change callback

### ISSUE THREAD

**Issue by LeMagnesium** [minetest/minetest#2631] opened 2015-04-16 21:36 UTC
Hello,
Minetest has, at the moment, many callback functions, such as `on_playerdie` or `on_generates` . However, there is no way you can run a function when a player gets hurt, or healed. `on_item_eat` could do it, in some way, but : 
a) you're not sure your function will be ran (see #2615)
b) You can see when a player regenerates his health, not the moment they are hurt, and you can't predict it properly if the subgame or mods used provide a way to regenerates your health without eating (such as hunger mod).

I don't really know if it's possible to code, I think it is, but I don't know how complicated it would be. It should take at least as argument the hp_change (negative for hurt, positive for healing), maybe the object which caused the change if any (but this is only useful when hurt, and can be done with on_punch() in some way).

**Comment by TeTpaAka** [comment] 2015-05-28 19:16
The code itself isn't problematic. The Problem is more, how the callback should behave. I came up with three possible solutions, but I don't know which one would be the best.

1. like player_on_punch.
This would work acceptable as long as there is only one function that manipulates the damage or there are only functions that log the damage. If there is more there is one function manipulating the damage, you would get damaged multiple times. Plus the logging functions would in fact log a wrong amount of damage.

2. a single function that gets overridden and returns the actual damage.
This would work with multiple manipulators but the logging functions could still get wrong damage amounts. Also, the register functions works different than for all other callbacks.

3. two separate lists of functions
First, a list of manipulators gets called that alter the amount of damage. Then, the list of loggers is called, that get the actual damage and don't alter the amount.
I have no idea, what impact this would have on performance. Also, the register functions works different than for all other callbacks.

Can someone help me out on this?

**Comment by LeMagnesium** [comment] 2015-05-29 16:19
The third behavior seems, for me, to be the nicest, because it's actually the issue many callbacks have. You can't distinguish between functions which will log or do something in reaction to an action and the functions which will modify what created or was modified before the action. Having to have one function is painful for mods that want to use this callback to log or modify, but are combined with another mod using the callback, there would be kind of a conflict. The conflicts also exists when callbacks override and return, because the following ones, even logging ones, are ignored, and might be important.

**Comment by TeTpaAka** [comment] 2015-05-30 15:05
Can you test this: https://github.com/TeTpaAka/minetest/tree/hp_change3 ?
I don't want to open a pull request right now, because I'm not sure if this is the right approach. Maybe I should make it like the first option to integrate it seamlessly in the rest of the engine.

**Comment by LeMagnesium** [comment] 2015-05-31 18:17
This works fine, except maybe that if the setter function doesn't return a new value for hp, it crashes without saying so (where other callbacks do warn you).
Otherwise, it's perfect, and exactly what is needed.
About the first behavior, the only problem with it are function skipped. As I detailed in #2615 , if the manipulating function returns, then any function after it is skipped. Knowing that there is no way to know in which order they will be executed, the third behavior is still the best one. (I even think other callbacks should work like this, as `player_on_punch`, but it is another topic)

**Comment by TeTpaAka** [comment] 2015-05-31 20:47
So, what should it do? Crash with an appropriate error message saying you have to return a number or assuming, nil = 0?
And it isn't true that player_on_punch skips remaining functions. This is only an implementation detail of some functions, like on_item_eat. https://github.com/minetest/minetest/blob/master/builtin/game/item.lua#L361-L366 It could be changed by moving the return value out of the loop.
For other functions, it has to be changed in the C code from OR_SC or AND_SC to OR or AND. (SC stands for short circuit)

**Comment by LeMagnesium** [comment] 2015-06-01 17:38
Then, we have two choices here : 
 - Make all callbacks execute all functions even if one of them has returned true/itemstack (change their Lua/C(++) code.
 - Let things as they are now, and keep getting function weirdly unexecuted sometimes depending on the loading order of the mods.

And, I (personnally) think you should crash with an appropriate error message with setter callbacks.As far as I remember that's what a function which has to return a value (like `can_dig`) do when it doesn't return any correct value.

**Comment by TeTpaAka** [comment] 2015-06-01 18:17
Pull request: https://github.com/minetest/minetest/pull/2751
Though I doubt it goes in like this.

**Comment by TeTpaAka** [comment] 2015-07-17 15:22
Can you close the issue?

**Closed** 2015-07-17 18:50 UTC
Labels: @ Server / Client / Env., feature request
