### ISSUE TITLE
on_punchplayer doesn't take on_hp_change into account?

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#10498] opened 2020-10-14 03:15 UTC
##### Minetest version

```
Minetest 5.4.0-dev-0aaf4dd50
```

##### Summary
In the CTF code I increased the damage dealt by certain players when using swords in PvP. I did this with `minetest.register_on_player_hpchange()`

But after that CTF, which detects kills via `minetest.register_on_punchplayer`, wouldn't detect kills when that additional damage was the difference between death and life

##### Steps to reproduce
* `minetest.register_on_punchplayer` and print the damage dealt every time the function you pass is called
* `minetest.register_on_player_hpchange()` and double the damage dealt. Also print the new damage you are dealing
* Notice the difference

**Comment by sfan5** [comment] 2020-10-14 07:49
duplicate of #10377

**Closed by sfan5** 2020-10-14 07:49 UTC
Labels: Unconfirmed bug

**Comment by LoneWolfHT** [comment] 2020-10-14 13:59
Oh, looked like that one was about a different issue

**Comment by LoneWolfHT** [comment] 2020-10-14 13:59
Oh, looked like that one was about a different issue
