### ISSUE TITLE
Minetest starts a game on login

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4344] opened 2016-07-23 11:09 UTC
Minetest always starts a game, if Minetest is the active app, if I log in from lock screen.

To make it more clear, if I start Minetest to the menu (not a game) and leave my PC, than the lock screen becomes active. If I log in to the desktop, Minetest starts the current selected game automatically

This happens with Ubuntu 14.04 and 16.04. Didn't test it with other desktops

**Comment by est31** [comment] 2016-07-23 11:31
Probably because you press enter when logging in. There is not much minetest can do about it.

**Comment by MarkuBu** [comment] 2016-07-23 11:55
But then it should have also an effect in other programs, if the enter pressed event in the lock screen passes through the apps.

for example there should be a newline in an editor if I log in and the editor is the active window. 

Minetest is the only software with this effect

**Comment by GReaperEx** [comment] 2016-07-23 14:21
Let me get this straight:
Input leaks through the login screen to the minetest window, and you say that it isn't a bug...

**Comment by est31** [comment] 2016-07-23 14:34
@GReaperEx nothing leaks through, its just the user pressing enter too long. Or the computer being too fast, whatever.

The way to "solve" this would be to introduce input delay, requiring enter to be pressed for a certain amount of time, but this would cause problems as well.

**Comment by t4im** [comment] 2016-07-23 14:35
@MarkuBu does it happen for other GL applications, too?

**Comment by Rogier-5** [comment] 2016-07-23 14:50
You could test if there's a difference between:
- hitting the enter key very briefly
- pressing the enter key, keeping it pressed a short while, and then releasing it.

If it makes a different, then it is an irrlicht bug, which has sloppy handling of key press and release events. This is also what causes the problems mentioned in issue #3637.

**Comment by DonBatman** [comment] 2016-07-23 16:33
I can confirm that a short press does not start game but a longer press does start a game.

I am running Ubuntu 16.04

**Comment by MarkuBu** [comment] 2016-07-23 16:42
How long is "longer"? If I log in I press enter "normal"

**Comment by Rogier-5** [comment] 2016-07-23 17:14
@DonBatman Then it is the same bug, or one that is very similar to #3637. Nevertheless, the question remains why the screen locker does not consume the key-release event before unlocking the screen... IMNO (in my naive opinion :-), it ought to...

@MarkuBu Difficult to tell. Probably also depends on your system, etc. Try one or a few seconds for 'longer', and hit it as briefly as you can (probably about 100 milliseconds) for  'short'. "normal" is very personal. Your normal might just be a few milliseconds too long, whereas another person's normal might be just the necessary few milliseconds shorter...

You can use `xev` to time your keypresses. If I'm correct, the time it reports has millisecond-resolution.

**Comment by paramat** [comment] 2016-07-24 17:18
Confirmed, if i start Minetest from terminal and hold enter too long it goes straight into the currently selected world.

**Comment by paramat** [comment] 2017-09-08 05:09
As noted a solution may cause problems. Closing in 1 month unless there is good reason to keep open.

**Comment by raymoo** [comment] 2017-09-08 19:06
A different solution could be to ignore enter presses for the first frame or two, since that is when irrlicht would send the unwanted keypress. It shouldn't affect user experience since human reaction times are typically more than 10 frames at 60FPS.

**Comment by paramat** [comment] 2017-11-27 05:13
I'm not sure this is even worth working on, very minor problem in a rare situation, i find i can avoid it with a quick press.
:-1: 
Anyone else think this needs working on? If not, close.

**Comment by MarkuBu** [comment] 2017-11-27 06:00
Just to clarify: I NEVER hit enter that long, that the keyboard sends characters in autorepeat. It's not my personal behavior that causes this issue. And Minetest is the only program that ever react after a login in any way. So there must be some kind of issue in Minetest (maybe Irrlicht) that causes this issue. 

If there would be an additional CR send after login I would have lots of issues with text editors too

But since I updated my OS to Ubuntu 17.10 the problem is gone. I assume it has something to do with LightDM or Unity. Both are not used anymore since Ubuntu 17.10

However, there must be an issue inside of Minetest, that causes this behavior in combination with Unity or LightDM

**Comment by paramat** [comment] 2017-11-27 06:04
Somehow i suspect it isn't autorepeat that does it, because it seems to happen on a much shorter press than the autorepeat delay.

**Closed** 2017-11-27 06:06 UTC
Labels: @ Startup / Config / Util, Low priority, Non-trivial, Possible close, Request / Suggestion
