### ISSUE TITLE
Broken rendering on windows

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#6472] opened 2017-09-27 20:28 UTC
A Windows user (0.4.16) on my test server encountered graphical artifacts that look like this:
![46b97813e03f4f82860001084679d8cf265b00cebd4d1a7aa5a580a7df4ffea0](https://user-images.githubusercontent.com/5734399/30936077-89e565a8-a387-11e7-94da-020368a54916.png)
![55c9a31fd5b55b09bf474e19b9cad5281949a7e4bea9d76b7fcf9163bef94b81](https://user-images.githubusercontent.com/5734399/30936075-89e32900-a387-11e7-861c-b0844f65b461.png)

Is this a known issue? Apparently it happens for them on any server.

**Comment by sfan5** [comment] 2017-09-27 20:38
Looks like Irrlicht's software renderer to me.
(not a bug)

**Comment by Fixer-007** [comment] 2017-09-27 21:01
3-7 fps...

**Comment by raymoo** [comment] 2017-09-27 21:12
What would cause irrlicht to fall back to software rendering? He says that it was working before.

**Comment by SmallJoker** [comment] 2017-09-28 08:12
I bet there were some manual settings modifications, as there's no explicit call to a setting-setter function for `video_driver` in the game.

**Comment by paramat** [comment] 2017-11-27 05:35
Closing for reasons given.

**Closed by paramat** 2017-11-27 05:35 UTC
Labels: @ Client / Audiovisuals, Not a bug, Possible close
