### ISSUE TITLE
CSM mod sending design

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#7043] opened 2018-02-16 07:00 UTC
##### Issue type

- Discussion about developing a feature
 
##### Minetest version

```
5.1.0-dev
```

##### Summary

CSM mod sending is a highly anticipated feature.

This issue aims to coordinate the dev effort to produce this feature by discussing technically on the CSM mod transport.
As stated on IRC, all non related topic or aggressive topic will be deleted unceremoniously.

When someone has proposals on the design, don't hesitate to add 👍 or 👎  on the proposal and argue

### CSM Mod sending

Here are the points we should solve before developping the solution. I will aggregate the discussion and resolution points here.

#### CSM Mod storage on servers
How CSM mods are represented on server side disks

* CSM mods are in a configured folder (see minetest.conf)

#### CSM Mod serialization
How to serialize mod, which components are embedded in the serialization

* Serialization is done on server startup and kept in memory
* Hash files (maybe hash the lua mod package itself too)

#### CSM Mod transport
How transport the mod on network

* Transport is done using regular protocol

#### CSM Mod loading
How mod is deserialized and loaded to client Lua state

##### Collected interesting features

* [ ] Transport mods serialized and packages across network to be loaded by the client
* [ ] Feature level (Optional, Recommended, Required): this permits client to control which SPCM feature he wants to enable or not on its client
* [ ] Mods signature (requires contentdb + curl/openssl by default)

##### Moderation on this topic

Only discussion about features to implement to have the minimum SPCM are allowed here. Politics or non constructive comments will be dropped.

cc @minetest/engine @red-001

**Comment by nerzhul** [comment] 2018-02-16 07:05
For the mod storage on servers i propose to add a dedicated and configurable folder where mods are stored on disk like they were on client

**Comment by nerzhul** [comment] 2018-02-16 07:06
For mod serialization, we serialize the folder files as-is in a tar like archive and compress them.

**Comment by nerzhul** [comment] 2018-02-16 07:07
To increase speed maybe generate the serialized version in a temporary folder. If used, then add a command to regenerate the archives, as not using it permit to change mod code at runtime (but required a client restart)

**Comment by paramat** [comment] 2018-02-16 07:10
Non-design discussion can take place in #5393 to save this thread from being swamped by that.

**Comment by 4w** [comment] 2018-02-16 14:10
> How transport the mod on network

What about a signing the archive and transport it over a secure connection using TLS?

**Comment by sofar** [comment] 2018-02-16 17:48
Hash checking in exactly the way that media hashes are checked is sufficient already. 

Adding TLS as a protocol overhead should be done to the entire game content network, not just one small part of it. This is interesting, but not currently needed.

**Comment by sofar** [comment] 2018-02-16 17:51
To prevent changing csm mods while the server is loading, the checksums should be calculated at startup.

I think we can just keep the csm data in memory. If you're worried about memory usage, people are abusing csm to load way too much code :).  Storing it in memory in serialized+compressed form should help.

**Comment by sofar** [comment] 2018-02-16 17:52
For now, maybe just keep csm in memory on the server side, and optimize later in case memory consumption is problematic?

**Comment by nerzhul** [comment] 2018-02-18 21:37
What is a CSM server send mod ? How it's represented on disk. it's the main problem we got here.

**Comment by nerzhul** [comment] 2018-02-18 21:49
I opened a PR about this feature now. I will work on it slowly

**Comment by raymoo** [comment] 2018-02-18 23:43
@nerzhul I think it should be possible for server-sent CSM to be part of a server mod, in case the functionality in the CSM and the server code rely on each other in some way.

**Comment by sofar** [comment] 2018-02-18 23:53
@raymoo this is why I gested to have a `minetest.register_csm(blob)` API function call that loads the data into the server. We want CSM mods to be explicit about loading code and only allow this when the server is in the `INIT` stage. Reading all the files from disk in a folder seems such an easy way for mayhem to happen.

**Comment by sofar** [comment] 2018-02-18 23:58
@nerzhul if we have an explicit API where CSM code blobs need to be registered, we somewhat defer the problem of storage to a mod. The mod could just embed strings, or the mod could use `io.open()` etc. to read a blob from disk. The simplest way to write and load a csm file thus would become:

```
minetest.register_csm("print(\"hello, world.\")")
```

As for client side, I wouldn't even bother to store the csm on disk unless some csm debug option is set. The media loading code should handle storing the content by hash value in the cache folder already. Perhaps we can print out the hash if the verbose logging options are set so that people can find the lua files in their media cache if they desire.

**Comment by red-001** [comment] 2018-02-19 17:03
I would prefer if CSM code that is embedded in server-sided mods would be loaded from a subfolder of the main mod (e.g. `CSM` or `client`), just seems cleaner to me. It should also allow using similar code for stand allow CSM mods and embedded mods.

**Comment by red-001** [comment] 2018-02-19 17:03
I would prefer if CSM code that is embedded in server-sided mods would be loaded from a subfolder of the main mod (e.g. `CSM` or `client`), just seems cleaner to me. It should also allow using similar code for standalone CSM mods and embedded mods.

**Comment by paramat** [comment] 2018-02-20 16:44
#6951 needs deciding on.

**Comment by nerzhul** [comment] 2018-02-20 17:32
:+1: for @red-001 
sending raw and ugly data is not maintainable over time. Also a CSM mod is not a print it's generally callback registrations

**Comment by sofar** [comment] 2018-02-20 17:44
@nerzhul obviously it's not just a `print`. I was giving an example.

**Comment by paramat** [comment] 2018-06-20 18:51
I suggest this should not be a 5.0.0 milestone as i very much doubt it will be done in time and shouldn't delay 5.0.0.

**Comment by paramat** [comment] 2018-12-21 02:09
> Feature level (Optional, Recommended, Required): this permits client to control which SPCM feature he wants to enable or not on its client

Discussing with sofar on IRC, we prefer the client accepts all-or-nothing.

I'm thinking the client can, of course, reject SSCSM using a client-side setting, but it seems the server needs to know this, so that it can refuse clients that reject SSCSM, because use of SSCSM will often be essential on a server.
So the client will accept all SSCSM mods, each fully functional, or none.
////////////////

Importantly, although the way CSM has been implemented is a little different from this plan, please can we stay as close as possible to the original plan? https://dev.minetest.net/Client_scripting_plans

**Comment by raymoo** [comment] 2018-12-21 19:33
I don't think it's necessary to let the server know tye cliemt is rejecting CSMs as long as the client rejects the connection. A ,modified cliemt would be able to lie about running CSM anyway.

**Comment by jastevenson303** [comment] 2018-12-21 23:06
And depending on the design, they'd likely know anyway.  I'm thinking about a server running a game and expecting the client to send mod channel data, but not receiving it.

**Comment by paramat** [comment] 2018-12-22 00:58
Good point, thanks.

**Comment by sofar** [comment] 2018-12-22 04:40
> I'm thinking about a server running a game and expecting the client to send mod channel data, but not receiving it.

The client could just fake it and send data, but not modify the game experience. All you'd need to do is stub out internal C calls to things that actually do the visual bits.

Note: I don't see a reason at all to implement some sort of verification at all. If the player wants to have a better experience by disabling it, let them. If they want to have a worse game experience by disabling it, let them, too. There are ample ways for the server to detect clients who refuse to run csms, the engine doesn't need any special feature or code. From a security perspective, it's much more important to pay attention to e.g. strict input checking and resource management.

**Comment by paramat** [comment] 2018-12-22 06:14
I think there should be dedicated support for this as it's important, some servers will require the players to use SSCSM as it will be part of the server experience.

**Comment by sofar** [comment] 2018-12-22 07:09
> To clarify: I wasn't suggesting players should accept SSCSM, only that servers should be able to reject such players if they wish.

I agree with that, but it takes very little to implement this: mod channels plus a "ping" by a client already achieves this, and would be 3 lines of spcsm and a few lines of server side checking. In other words, is is effectively already implemented in the core.

**Comment by paramat** [comment] 2018-12-22 07:39
Ok, best i stay neutral on this for now :)

**Comment by paramat** [comment] 2019-06-11 01:04
Now 2 years since CSM was released into stable MT.

Nerzhul has stated he will work on this soon, however he will need a lot of help and i get the feeling no other core devs have time for SSCSM. The number of active core devs, and the time they have for MT, is very low recently.

I honestly can't see SSCSM being worked on unless core dev time for MT rises significantly.
In the meantime i think any other CSM work is pointless, as CSM is only worth having together with SSCSM, and the chance of SSCSM being implemented currently seems less than 50%.

My honest gut feeling is that SSCSM will never happen, and CSM will be completely removed after we've waited another 1-2 years of no progress because no-one has time.
I am going to admit my honest gut feeling that it seems best for the future of MT to not have any CSM, to be simpler, with less security headaches, to better match the reduced amount of core dev time.

**Comment by jastevenson303** [comment] 2019-06-11 19:31
That's the spirit!

**Comment by DS-Minetest** [comment] 2019-06-11 20:41
> That's the spirit!

No, it's not irrlicht's fault that sscsm is not there yet.

Anyway, I'm still looking forward in having sscsm some day. Imho there are too many possibilities that come with sscsm to just give up. I would be glad if I can help in some way developing sscsm.

**Comment by jastevenson303** [comment] 2019-06-12 00:05
Me too!  I just made a mod that does sprinting using CSM (to check key presses) with SSM (to apply the physics changes).  https://forum.minetest.net/viewtopic.php?f=53&t=22683

(I was being sarcastic/tricky when I said "that's the spirit.")

**Comment by DS-Minetest** [comment] 2019-06-20 22:29
Some things to consider:
- `builtin` has to be sent from the server, too.
Should the common folder been sent, too? Should `builtin` have special privileges here?
- Crash messages have to be sent back to the server if both want that.
Paths should not include any folder structures from the client. (How are the error messages generated anyway if the corresponding code is not saved in a file?)
- I highly prefer per ssm csm (https://github.com/minetest/minetest/issues/7043#issuecomment-366752053) over all csms being in one folder.
If there has to be an extra sscsm, there can be a ssm with empty `init.lua`.
- There should probably a setting for the maximal memory from one server for media + all sscsms + everything else. If only the memory usage of one sscsm is limited, the server can provide hundreds of csms to circumvent this.

**Comment by rubenwardy** [comment] 2019-06-20 22:34
The main thing that concerns me about this is security. Given our lack of developer hours, I'm worried that the implementation would be half-baked

**Comment by DS-Minetest** [comment] 2019-06-20 23:23
I don't think that players are able to or should have the responsibility to check for signatures. Humans want to play and will accept anything taking the risks.

Instead of signatures there should probably rather be a very secure environment.
- Using much ram or cpu power shouldn't be prohibited. If a sscsm does in order to be evil, the user can just kill minetest.
- Writing on persistent client memory shouldn't be possible over a certain limit defined by a setting. (The same limit as in the fourth dot [before](https://github.com/minetest/minetest/issues/7043#issuecomment-504222455).)
- Writing and reading from/to memory has to be limited to certain directories. Best just allow things like `minetest.get_worldstorage`.
- Writing to memory has to be limited in speed as ssds can be harmed with too much writing afaik.
- Anything else harming the hardware must be prohibited.
- Printing and loging should be counted to the memory consumption as it's saved in `debug.txt`.
- Also `dofile` and `require` and co. should not be able to access anything outside of the csm.
- It is totally ok if a csm causes a crash.
The sandbox doesn't have to be as restricted and save as the one for mesecons luacontroller and co.
- Sscsms should also not be able to find any folder structures as strings or something as they could send it to the server and co.. Many users use their real name somewhere and co..
- `debug.*` might have something evil, idk.
- `io.*` should be probably forbidden. The csm should have other ways to do such things.
- `os.execute`, `os.remove`, `os.rename` and possibly some other `os.*` functions should be forbidden.
- `package.*` contains paths. It should maybe be forbidden.
- string and table helpers and coroutines are probably ok.

**Comment by rubenwardy** [comment] 2019-06-20 23:30
> I don't think that players are able to or should have the responsibility to check for signatures. Humans want to play and will accept anything taking the risks.

Signatures would be automatic, and just used to show the author of a mod if that ever happens.

> Instead of signatures there should probably rather be a very secure environment.

Yeah, this is much better

**Comment by DS-Minetest** [comment] 2019-06-21 10:46
Another good thing about using a secure environment instead of signatures is that you don't have to fear that the signature might be faked or that the sent sscsm is manipulated on its way to the server as such a manipulator would be as untrustworthy as the server itself.

If sscsms are per ssm (which I think would be good), should they share the same dependencies with their corresponding ssm?
If so, do sscsms even need an own `mod.conf`?
If they don't share dependencies, it would be hard to decide whether the sscsm should be loaded if the ssm is missing dependencies and vice-versa.

The sscsm loading order should probably be given by the server.

**Comment by raymoo** [comment] 2019-06-21 17:16
An SSCSM should probably only be loaded if it's corresponding SSM is loaded. Just consider the CSM a component of the server mod.

**Comment by rubenwardy** [comment] 2019-06-21 17:21
Yeah, it's simplest to use the ssm load order too

**Comment by DS-Minetest** [comment] 2019-07-13 21:43
FYI, I'm implementing a bit for the file sending.
See https://github.com/DS-Minetest/minetest/tree/sscsm_1.
The file sending basically already works. The files and folders are saved in cache/sscsm. Loading the mods from there with lua should be easy.
However, I still have to fix things, remove garbage, compress and add some missing things (like the disk space limit setting).

**Comment by paramat** [comment] 2019-07-13 23:35
Good to see a little progress.

> I think that reviewing CSMs in some form of central location isn't viable,

I agree. No-one has time to do so anyway.
I wasn't impressed when i learned that CSMs would have to be verified, and therefore could only be provided by the CDB, that made me think 'this isn't worth it'.
I hope we can avoid that.

**Comment by ClobberXD** [comment] 2019-07-14 01:56
I'm really glad to see progress on this front. Thanks for your work, @DS-Minetest! :)

**Comment by DS-Minetest** [comment] 2019-07-14 21:16
Compressing is done now, too.
Now only correct error handling and deallocating is missing, I think. And I fear little and big endian.

**Comment by DS-Minetest** [comment] 2019-08-01 11:43
An easy way to hold sscsms in ram for the client could be writing them to `/dev/sha`. (However, I don't know if this is the correct way and if this is really that easy or not.) Is there a folder like this for other systems than linux (eg. windows), too?

If sscsms are cached in a folder by the client, there have to be multiple folders. It is possible that minetest is started twice with the same sscsm path, there shouldn't be conflicts in such situations.

If minetest is started in singleplayer, sscsms can simply be loaded without being sent. This means that sscsm for singleplayer can already be implemented easily. (There should be a setting to send mods even if it's singleplayer mode, for testing.)

**Comment by sofar** [comment] 2019-08-02 05:22
There's almost no benefit I think to implementing `dofile` in sscsm mods. If you're sending 3 files, you might as well just send 1 large file. It also would help with securing the sandbox, since it takes an attack vector away if it's not there.

**Comment by DS-Minetest** [comment] 2019-08-02 11:14
Cramming everything into one file sounds horrible.
And if ssm and sscsm should share a codebase, they could both dofile a file in `mod/client/`.

**Comment by sofar** [comment] 2019-08-03 00:38
I feel that *security* is more important than *keeping files short*. You can't have *short files* without `dofile` and taking away `dofile` *drastically* improves security.

Second, you do not *require* sscsm `dofile` support to make it work. I'm asking you to do *less* coding and you get *more secure* code for free.

If later, after mod devs use it for a few months and everyone hates is, AND if people doctor out the problems of making `dofile` properly limited ... yeah then it's reasonable to consider it and I would have no objections to an incremental PR.

**Comment by rubenwardy** [comment] 2019-08-03 09:13
Dofile has already been implemented for the client using a virtual filesystem. It could just be disabled

**Comment by osjc** [comment] 2019-08-10 16:20
> I think it's only Lua files in a flat folder and we call init.lua, everybody agree ?

There are subdirectories for textures, sounds and models (meshes etc). Some mods may have other subdirectories for mod specific data. But that is unlikely to be the case for a client side mod. On the other hand, textures, sounds and models are far more likely in a CSM than on server side mod.

So it is not a "flat folder" but AFAIK everything else in that question is correct.

**Comment by hecktest** [comment] 2019-11-25 06:01
Monolithic client side scripts without dofile are not an issue; a server can concat a bunch of smaller files during its init to produce the monolithic form. Perhaps this should be automated with a function in builtin.

**Comment by rubenwardy** [comment] 2020-04-30 18:14
This is still my position: https://github.com/minetest/minetest/issues/7043#issuecomment-504223589

SSCSM should be done from `mods/mymod/client/init.lua` which are sent over some mechanism (the existing media sending one is fine).

There's also #7041 which is a prerequisite to this

**Comment by celeron55** [comment] 2020-04-30 20:35
I as well would like to see a `mods/mymod/client/init.lua` style hierarchy. Then one doesn't need to care which mod is client side and which is not, and whether a server side mod needs a companying client side mod or not, or vice versa. It's just a mod like anything else and the system will handle all the details.

This way, in addition to being easier for users, the modder can control both ends of the networking between the server and the client portion of a mod and there's no need for difficult to maintain versioned interfaces between SSM and CSM.

The downside of this is that many mods will probably make their SSCSM part mandatory for them to work. I'm not sure what the user acceptance for this will be.

**Comment by hecktest** [comment] 2020-05-01 10:15
>     * What to do about proprietary scripts? I highly suggest forbidding proprietary code to be sent at least from servers on the public server list. This will make it much easier to deal with. This could be done by the server declaring a license for each script.

Why do you care? This benefits no one, except those who would fork the engine, take someone's mod, rebrand it, strip the licenses, put up his own master server, and offer it all to clueless people with freemium bolted onto it. By offering them client side code on a silver platter, in addition to easily extractable assets, you're doing half the work for them already..3
Do you block all nonfree scripts in your browser? I highly doubt it.
If you still insist on doing this in the name of freedom, end the farce and rebrand the project as GPL so that nobody wastes their time with it.
License for each script? Do you actually want to click through dozens of EULAs every time a server is updated? Mad, this is just mad. Permission prompts for apps are already annoying, EULAs are annoying, do not multiply those.
*one* optional consent page (including rules and policies) per server is enough, weave it into the "confirm registration" prompt.

On topic remarks:
- sandbox with setfenv on a blank table with a whitelist __index
- expose: minetest, loaded mods, math, string, 
- do not expose: ffi, io, os
- have a setting for exposing debug, allow by default on localhost
- reject luajit bytecode, it can't be sanitized
- allow the server executing shared code from /*/client/
- offer local storage per server, allow a setting that blocks local storage
- virtualize all local storage via a magic table, defer writes to minimize wear
- lua errors are fine, hard crashes are not, they're very bad
- anything that could go wrong in your browser's JS could happen here/
- find a way to build on windows with ASLR enabled
- nobody will pay attention to hashes or certs
- nobody will study the code they download from servers for safety reasons

**Comment by ClobberXD** [comment] 2020-05-01 13:00
> one optional consent page (including rules and policies) per server is enough,

I like this idea! :+1:

**Comment by rubenwardy** [comment] 2020-05-01 14:04
> Why do you care?

Because it makes the licensing easier, and non-free software should never become the norm in Minetest 

> ..except those who would fork the engine, take someone's mod, rebrand it, strip the licenses, put up his own master server, and offer it all to clueless people with freemium bolted onto it. By offering them client side code on a silver platter, in addition to easily extractable assets, you're doing half the work for them already.

So, the Minetest engine already?

>  License for each script? Do you actually want to click through dozens of EULAs every time a server is updated? Mad, this is just mad. Permission prompts for apps are already annoying, EULAs are annoying, do not multiply those.

This would not be shown to the user as separate screens. Having a license per script is _required_ to ensure that the author has licensed the script properly.

> one optional consent page (including rules and policies) per server is enough

This is actually what I was intending.

> nobody will pay attention to hashes or certs

They don't need to, the client will. Those things are _required_ in order to show the mod name and author

**Comment by sofar** [comment] 2020-05-01 19:37
> What to do about proprietary scripts? I highly suggest forbidding proprietary code to be sent at least from servers on the public server list. This will make it much easier to deal with. This could be done by the server declaring a license for each script.

That's a policy decision that shouldn't affect the technical design.

A technical implementation COULD provide a mechanism for players(not the serverlist) to enforce OSS SSCSM. That would be nice. Filtering the serverlist assumes the servers are playing fair (unlikely, if they end up being filtered). So doing this in the client seems a better approach. If there the server is lying about licensing, they are effectively releasing their code as OSS to players. If they're not, players can decide for themselves to join or leave.

**Comment by nerzhul** [comment] 2020-05-02 05:27
i'm not sure mod code is tied to minetest code in terms of licensing, it's not like if you are doing proprietary python, javascript and PHP over a FOSS language VM, no ?

**Comment by rubenwardy** [comment] 2023-10-08 15:10
Not been any discussion here for a while, closing as duplicate of https://github.com/minetest/minetest/issues/5393

**Closed by rubenwardy** 2023-10-08 15:10 UTC
Labels: @ Server / Client / Env., @ Client Script API, Discussion
