### ISSUE TITLE
CLI invocation of server segfaults, GUI doesn't

### ISSUE THREAD

**Issue by yetiinabox** [minetest/minetest#12742] opened 2022-09-04 21:33 UTC
##### Minetest version

```
5.6.0
```

##### OS / Hardware

Operating system: Raspbian Debian bullseye
CPU: Raspi 4B 

GPU model:
OpenGL version:

##### Summary

Serving a world using Whynot or DreamBuilder from a server, using the GUI over XWindows works; serving the same world from the CLI crashes. 

##### Steps to reproduce

Log into a Raspi server using an X windows session. Launch minetest, and use the XWindowns GUI to create a new world (test_world) and share it (run the minetest server from the GUI): no problem. Other clients can log in; it is stable.

Quit the GUI. From the CLI on the same server, launch the same world using a command such as 
% minetest --worldname test_world --server

This server process will almost always (at least 90% of the time) segfault while loading, and if not, will crash with a segfault soon after. However, it does not segfault at the same place each time; it is possible to run the same command ten times and have the server process crash three times at one point, three times at another, and four times at a third. 

This problem does not seem to occur using the vanilla Minetest game, but it does happen using either Whynot or Dreambuilder with no further mods. 

GDB simply reports a segfault: 

Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.
0x0000007ff4a26f38 in ?? ()

The segfault can occur a different locations.

**Comment by savilli** [comment] 2022-09-04 22:30
Can you provide a backtrace?

**Comment by yetiinabox** [comment] 2022-09-05 17:25
Here's what it gave me - not much help!

```
Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.
0x0000007ff801e80c in ?? ()
(gdb) bt
#0  0x0000007ff801e80c in ?? ()
#1  0xfffd807ff49e9048 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by savilli** [comment] 2022-09-05 17:35
It looks like a LuaJIT bug.
Try to recompile minetest without LuaJIT or with the latest LuaJIT version.

**Comment by yetiinabox** [comment] 2022-09-05 19:25
On the basis of earlier comments elsewhere, when I first encountered this problem I removed the Debian-installed version of LuaJIT and built the latest version. LuaJIT is version 2.10.-beta3 . That didn't change the behaviour. I'll  deinstall that and recompile with the included LuaJIT and let you know how it goes - on the Raspi it takes w while to compile. Thanks for the help.

**Comment by savilli** [comment] 2022-09-05 19:53
2.1.0-beta3 doesn't necessarily mean the latest version. With what LuaJIT commit did you build?

**Comment by yetiinabox** [comment] 2022-09-05 20:18
Sorry, I hadn't looked carefully at your instructions. I'm recompiling now without LuaJIT altogether; we'll see how that goes. 

However, the version of LuaJIT I was running was the most recent available from github. That was the version that was crashing before.
 ```
% git branch -a
* v2.1
  remotes/origin/HEAD -> origin/v2.1
  remotes/origin/master
  remotes/origin/v2.0
  remotes/origin/v2.1
```
Thanks again. It might be tomorrow before I can report back.

**Comment by sfan5** [comment] 2022-09-05 20:56
As important as the precise version here would be recompile Minetest (and perhaps luajit too) with debug information enabled.

**Comment by savilli** [comment] 2022-09-05 21:13
Well, if it doesn't crash without LuaJIT, I would honestly just close it with Upstream issue. No need for debug build for that XD.
From my experience, the only way to debug LuaJIT is to have a reliable reproduction method.

**Comment by yetiinabox** [comment] 2022-09-05 22:06
I've recompiled without LuaJIT and it's working so far.

Is there a difference in the way in which LuaJIT is called between the GUI version of minetest and the CLI version? That should be the key to this.  Minetest didn't crash when I used the GUI to run a server; it only crashed when I called it from the CLI using the --server argument.

@sfan5 - I did recompile minetest with debug enabled, but it didn't give any new information on the crash. Whatever this is is likely to affect others running minetest on a Raspberry Pi, although  haven't seen anyone else report this.

**Comment by sfan5** [comment] 2022-09-06 07:21
> Is there a difference in the way in which LuaJIT is called between the GUI version of minetest and the CLI version?

There isn't.
Of course if this is a bug in low-level code (like LuaJIT has plenty) then it's very much possible for the bug to depend on totally unrelated circumstances/coincidences.

**Closed** 2022-10-05 08:10 UTC
Labels: Obscure, Unconfirmed bug, Upstream issue, Possible close
