### ISSUE TITLE
`minetest.[de]compress`: Expose `zstd`

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#12512] opened 2022-07-05 09:40 UTC
## Problem

Zstd is not exposed as a compression method despite Minetest being compiled with it. This way modders compressing their data lose out on the advantages Zstd brings over Zlib (more efficient compression both in terms of size & speed).

## Solutions

Expose zstd to `minetest.[de]compress`. Support & document `method = "zstd"`.

## Alternatives

Using `require` to use other Zstd wrapper libraries.

## Additional context

`minetest.[de]compress` was deliberately written with forwards compatibility in mind (hence why it takes a `method` parameter despite there being only one method).

**Comment by erlehmann** [comment] 2022-07-17 20:53
> This way modders compressing their data lose out on the advantages Zstd brings over Zlib (more efficient compression both in terms of size & speed).

I tried to investigate how much better Zstd is than Zlib/deflate for mod development and found the following things:

1. Zstd is primarly optimized for speed of decompression. Regardless of the compression level of the compressed data, Zstd will always decompress at least as fast as Zlib. I have never had speed of decompresison as an issue in mod coding, but I was under the impression that Zstd is faster at compression – which is, unfortunately, generally not true (see point 5).

2. Zstd with default compression level seems to aim to produce output that is about as well compressed as Zlib (actually a bit worse, see next point) at about 2 to 3 times the speed. This is by design – Zstd offers a wide range of compression options that can be tuned, but the design goal for the default compression level is “within a few percentage points of what Zlib would have created”.

3. Zstd with default settings and without a dictionary in my tests compressed a ~100kb text sample about 5% worse than Zlib.. This was surprising, but such things are known to the Zstd developers and WONTFIX because there exists a special mode for “small” files (see point 4).

4. For small payloads (i,e. anything measured in kilobytes and not in megabytes), Zstd can be used with a predefined dictionary. Think 100s of text files or compression of HTTP headers. Zstd absolutely outperforms Zlib by a lot when given such a dictionary.

5. At higher compression levels, Zstd takes a lot more time to compress the input and uses a lot more memory. For the ~100kb HTML example, both Zstd and Zlib can compress it about as well in <0.01s (with Zstd slightly worse, as mentioned). For a ~7% improvement in compression ratio over Zlib, this operation can take >0.25s and for a ~13% in compression ratio, the operation can take >1s. This seems like a huge API footgun to me, at least in synchronous code.

To me, it seems that you can not have both much faster and much better compression than Zlib at the same time by using Zstd – unless your input data is larger than many times the Zlib window size (32 kilobytes or so?).

So basically, as a mod developer wanting to compress smaller payloads you can choose between:

1. slightly-faster-than-Zlib and slightly-worse-compressed-than-Zlib compression using Zstd defaults

2. using a pre-trained dictionary for much-better-than-Zlib compression if your input data fits the dictionary

3. definitely-much-slower-than-Zlib and possibly-much-better-than-Zlib compresison using higher Zstd compression evels

If Zstd support is addad, it should probably come with a note that Zstd is unlikely to beat Zlib both encoding speed and size for inputs below 4 megabytes or so (to be determined, please do your own tests), unless the user provides a pre-trained dictionary.

@appgurueu what do you plan to use Zstd for? I use `minetest.compress()` mainly to compress item meta and bitmap data. Have you benchmarked Zstd for your use case? If so, which compression level are you using and what was your test data?

**Closed** 2022-09-28 13:06 UTC
Labels: @ Script API, Feature request, Supported by core dev
