### ISSUE TITLE
Improve minetest packaging and make it non-techie friendly

### ISSUE THREAD

**Issue by mercorii** [minetest/minetest#9972] opened 2020-05-31 13:06 UTC
## Problem

Looking at the downloads page, minetest's target audience seems to be developers and core users.

* Windows installation requires knowledge about zips
* mac installation requires knowledge about brew
* linux installation requires knowledge of command line tools, and many of the links lead to old versions of the application

On the positive side, getting the game on android is as easy as it should be.

### Core problems

1. Getting to play minetest should require no knowledge about the underlying operating systems.
2. It should be easy for the user to obtain the latest version of the application

Regular computer users know very little about things that developers and core users consider easy or even trivial, such as file systems and folders.

## Solutions

1. Make the current download methods secondary methods
2. introduce easier way to obtain the latest version of the game on all platforms.

Getting to play the game should be as easy as possible. (Likewise, installing mods and games should require no knowledge about the file system.)

### Windows

Create both:

1. one-click installer 
2. single click portable executable

### Mac

1. Create an app or pkg

### Linux

1. create official snap via [snapcraft](https://snapcraft.io/)

Snap doesn't work on all distributions, but it's supported on ubuntu where the users with least technical experience and knowledge live in the linuxland. The more skilled ones will know how to obtain the game for their own distribution via the current methods.

## Alternatives

Ship it with steam, or via other app stores.

## Additional context

Recent description about [problems regular users are facing](http://www.pxtl.ca/2020/05/05/minetest-birthday/) when trying to install minetest. 

(You might want to disregard the comparisons to minecraft in the text. Regardless of those, the post makes a good point on the problems faced when trying to get non-techies to install the game.)

**Comment by rubenwardy** [comment] 2020-05-31 13:07
Duplicate of #3596

**Closed** 2020-05-31 13:08 UTC
Labels: Feature request

**Comment by mercorii** [comment] 2020-05-31 13:09
My github issue search-fu appears to have failed with this one.
