### ISSUE TITLE
Profiler error caused by recent statbars commit

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8237] opened 2019-02-16 03:00 UTC
Backtrace:
```
2019-02-16 03:04:53: ACTION[Main]: Server: Shutting down
2019-02-16 03:04:53: ERROR[Main]: ModError: Runtime error from mod '*builtin*' in callback 
on_mods_loaded(): ...ocal/share/minetest/builtin/profiler/instrumentation.lua:64: attempt t
o concatenate field 'mod' (a nil value)
2019-02-16 03:04:53: ERROR[Main]: stack traceback:
2019-02-16 03:04:53: ERROR[Main]:       ...ocal/share/minetest/builtin/profiler/instrumenta
tion.lua:64: in function 'generate_name'
2019-02-16 03:04:53: ERROR[Main]:       ...ocal/share/minetest/builtin/profiler/instrumenta
tion.lua:93: in function 'instrument'
2019-02-16 03:04:53: ERROR[Main]:       ...ocal/share/minetest/builtin/profiler/instrumenta
tion.lua:133: in function 'register_on_joinplayer'
2019-02-16 03:04:53: ERROR[Main]:       /usr/local/share/minetest/builtin/game/statbars.lua
:168: in function </usr/local/share/minetest/builtin/game/statbars.lua:167>
2019-02-16 03:04:53: ERROR[Main]:       /usr/local/share/minetest/builtin/game/register.lua
:419: in function </usr/local/share/minetest/builtin/game/register.lua:399>
```
Fixed by reverting https://github.com/minetest/minetest/commit/eea1fdaf2574fec38316527cfc463ff2427c5775 (according to p_gimeno).
IRC discussion http://irc.minetest.net/minetest-dev/2019-02-16#i_5496336

02:02 VanessaE   2019-02-16 03:00:59: ERROR[Main]: ModError: Runtime error from mod '*builtin*' in callback on_mods_loaded(): ...ocal/share/minetest/builtin/profiler/instrumentation.lua:64: attempt to concatenate field 'mod' (a nil value)
02:02 VanessaE   um???
02:05 p_gimeno   is there a traceback?
02:05 VanessaE   yes
02:05 p_gimeno   that'd be useful
02:05 VanessaE   https://pastebin.ubuntu.com/p/cn9NfDCTsP/
02:06 VanessaE   disabling the profiler by the config is enough to let it start.
02:07 p_gimeno   thanks, looking
02:07 p_gimeno   5.0.0?
02:07 VanessaE   mmhmm
02:07 VanessaE   master HEAD pulled half an hour ago.
02:08 VanessaE   (actually, an hour and a half ago)
02:09 p_gimeno   reproduced here
02:17 p_gimeno   hm, core.get_current_modname() is returning nil at some point, and that's causing a crash
02:23 paramat    ah perhaps stabar changes related
02:24 paramat    https://github.com/minetest/minetest/commit/eea1fdaf2574fec38316527cfc463ff2427c5775
02:30 p_gimeno   seems so
02:33 paramat    i'll make an issue
02:33 paramat    one for smalljoker
02:34 p_gimeno   it's fixed by reverting that, so it's definitely related
02:35 paramat    thanks
02:41 paramat    p_gimeno did you reproduce it just with mtg and no optional mods?
02:49 p_gimeno   that's right, just turning on the profiler
02:50 rubenwardy Looks like it's the last change
02:50 rubenwardy I suggest adding a nil check for it
02:50 rubenwardy It's because something is registered when no more is active
02:50 p_gimeno   rubenwardy: tried adding a nil check, that isn't enough
02:50 rubenwardy In register on mods loaded
02:51 p_gimeno   ah

@SmallJoker

**Comment by random-geek** [comment] 2019-02-16 04:43
The issue is here:

```diff
- core.register_on_joinplayer(update_builtin_statbars)
+ -- Append "update_builtin_statbars" as late as possible
+ -- This ensures that the HUD is hidden when the flags are updated in this callback
+ core.register_on_mods_loaded(function()
+ 	core.register_on_joinplayer(update_builtin_statbars)
+ end)
  core.register_on_leaveplayer(cleanup_builtin_statbars)
  core.register_playerevent(player_event_handler)
```

**Comment by pauloue** [comment] 2019-02-16 06:46
It's easily fixed by checking the return value of `core.get_current_modname` in the profiler.

But the way it's ensured that `update_builtin_statbars` is called after HUD flags are set seem hacky. Maybe `player:hud_set_flags` can do the update?

**Closed** 2019-02-16 20:06 UTC
Labels: Blocker, Bug, High priority
