### ISSUE TITLE
Subfolders for texture packs

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4464] opened 2016-08-25 07:28 UTC
It would be helpful if texturepacks support subfolders. It would be easyer to organize textures if they are placed in subfolders like plants, items, wood, stone and so on. Just load subfolders recursive

**Comment by red-001** [comment] 2016-08-25 15:12
should user be able to disable only parts of the texture pack in the main menu or should this just serve to make editing texture packs easier?

**Comment by MarkuBu** [comment] 2016-08-25 16:44
It should be just easier to maintain texture packs. No additional functions

**Comment by tobyplowy** [comment] 2016-08-26 11:49
I don't think that would make it easier that would just make it a bigger struggle and I know because I make texture packs what the sub folders should be used for it's things like blocks, items, gui, and mobs, if they ever make it to the base game,

**Comment by red-001** [comment] 2016-08-26 17:54
see #4468

**Comment by paramat** [comment] 2017-09-14 03:39
Duplicate of #2821

**Closed by paramat** 2017-09-14 03:39 UTC
Labels: @ Startup / Config / Util, Duplicate, Feature request

**Comment by paramat** [comment] 2017-11-17 19:37
#6412 merged.
