### ISSUE TITLE
Problems updating minetest on windows - make an installer or add an autoupdater

### ISSUE THREAD

**Issue by Destroyinator69420** [minetest/minetest#13632] opened 2023-06-25 19:20 UTC
## Problem

When a new stable version of minetest is released, it causes problems with updating on windows. I am very frustrated having to manually update the game by deleting the folder, unzipping the new version and then copying back in my save files from the recycle bin. There has to be a better way. 

## Solutions

The most obvious solution to this would be an installer. The installer would extract the game files to C:\Users\Appdata\Roaming\Minetest. It would then make a start menu and desktop shortcut and leave a log file of the installation. If a new version of Minetest is released, you run the new installer. The new installer will check to see if C:\Users\Appdata\Roaming\Minetest is occupied, if it is, it will read the log file to see whether or not it needs to update the game. If true, it will then overwrite the old game files while leaving the save files intact.

## Alternatives

Minetest could be compiled so that the game files are installed to C:\Program Files\Minetest and the save data is stored in C:\Users\Appdata\Roaming\Minetest. The other option would be to add some form of auto updating functionality to minetest. One excellent option for this would be WinGUP, which is used in notepad++ with great success. It is available at https://github.com/gup4win/wingup.

## Additional context

Updating minetest is not much of an issue on linux since it is available as a flatpak, a snap or from the package manager.

**Comment by rubenwardy** [comment] 2023-06-25 19:34
Thanks for the suggestion

This is a duplicate of #9166 though

**Comment by rubenwardy** [comment] 2023-06-25 19:35
Thanks for the suggestion

This is a duplicate of https://github.com/minetest/minetest/issues/9166 though

**Closed by rubenwardy** 2023-06-25 19:35 UTC
Labels: Feature request
