### ISSUE TITLE
Players can spawn in deep hole from which they can't escape

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8370] opened 2019-03-13 07:27 UTC
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0
```
and before.

##### Summary
Sometimes Minetest might spawn you in a very unfair position where the terrain around you is so steep that you're essentially in a “hole” with nothing else around you. It's hard, or even impossible to get out.

Normally, you can escape via nerd-poling, so pro players know what to do. But if you're very unlucky, you also spawn in a stone-only biome, or a biome with no hand-diggable nodes. In this case, it's basically game over, the only option you have is to delete the world and try again.

Imagine this would happen to a new player. The chance of an insta-rage-quit in such a situation is very high!

##### Screenshot

![Xp1PL6Tusy](https://user-images.githubusercontent.com/3686677/54317835-3e308680-45dc-11e9-825b-6362ce6c69b5.png)

Seed: 4312102082791182882
Coords: -89,20,4
Mapgen: V7
Mapgen settings: All defaults

In this biome I spawned in a “sunflower plains” biome in MineClone 2 and the player could still use the dirt to nerdpole out of the hole. This particular hole is reeaaaaally deep, over 100 nodes! But it could easily have been a stone-only biome.

##### Ideas
I don't really have any good ones, this is not trivial to solve.

Maybe make Minetest avoid extremely steep hills or “erratic” terrain as the spawn point and prefer flat areas. But no idea how and if that would actually work.

I have no idea if a mod-based solution would be feasible or even possible, it seems some deep mapgen knowledge is required to solve this problem.

##### Steps to reproduce
* Use valleys mapgen, default settings, seed 4312102082791182882 (also see screenshot)
* Spawn
* Look where you spawn

Close to the world origin, there are lot of holes as shown in the screenshot.

I also noticed a similar problem in v7 mapgen, since it might generate huge cliffs.

**Comment by Wuzzy2** [comment] 2019-03-13 07:33
Oops. My fault. The mapgen in the screenshot was actually v7, not valleys.

**Comment by paramat** [comment] 2019-03-13 22:03
This happens to me too occasionally. Usually there is surface material to collect and a way out, but in some games there won't be. On world start a player can just start a new world, but on respawn is a problem. Difficult issue.

**Comment by paramat** [comment] 2019-03-14 00:15
PR #8374

**Comment by paramat** [comment] 2019-03-22 04:00
It was a good issue to discuss, but now that i have experimented with a fix and thought about this more i now have the opinion that this isn't worth doing, in Mapgen V7 or in mapgens generally.
* This is only an issue in singleplayer, a server will have set a spawn point or chosen a seed that causes a good engine/game-chosen spawn point.
In singleplayer, in the rare event of being in a hole with no way out, a player can try a new seed.
If having escaped a hole and then respawning in the same hole and somehow the second time not having enough loose material available to escape (rare), or not having prepared for a respawn in the same place, a player can cheat themselves out of the hole if the only alternative is to abandon a valuable world.
* In many games there is often enough loose material around to escape the hole, so unescapable holes are fairly rare.
* Such a spawn is, firstly, highly amusing, i love it when it happens to me, and secondly, an interesting strategic challenge to gather loose material to pillar-up, to reach more loose material, to pillar-up more, and choosing a route to escape.
* Mapgens have other ways of causing an unfriendly spawn, for an example, a tiny island in the middle of a vast ocean. There will be no end to the types of bad spawns, so no end to the extra code needed to avoid these. It's better to not start going in this direction for mapgens, especially when a singleplayer can just try a different seed instead.
* Some games may be such that spawning in a hole is not a problem, so the degree to which the engine dictates what type of spawn is suitable should be minimised.
* Such a spawn is not a problem in creative mode.
* For Mapgen V7 specifically, there is no way to detect a small hole surrounded by cliffs, the only solution is to spawn the player on the higher terrain in cliff areas. But because high altitude spawns are not allowed, this then stops spawns occuring in cliff areas, which is 1/3rd of land area.
So not only is there more calculation involved, more spawn point checks are needed to find a suitable spawn point. When a player is spawned there can be up to 1000s of these spawn point checks.
The spawn point is then likely to be further from world centre, and with custom mapgen parameters, more likely to fail and bury the player at (0,0,0).
* Avoiding cliff areas makes Mapgen V7 spawn locations much less interesting.

**Comment by Wuzzy2** [comment] 2019-03-22 09:12
> Mapgens have other ways of causing an unfriendly spawn, for an example, a tiny island in the middle of a vast ocean. There will be no end to the types of bad spawns, so no end to the extra code needed to avoid these. It's better to not start going in this direction for mapgens, especially when a singleplayer can just try a different seed instead.

Poor argument as those are just slightly annoying spawns, not truly impossible spawns. Islands are also MUCH easier as swimming is cheap (you just hold the jump key). I do not care about islands, frankly. I pointed out ONE specific spawn that is possibly an “impossible spawn”. If the spawn would not be possibly impossible, I would not have posted this issue.

I am not aware of other impossible spawns (except for obvious bugs that bury you inside land, if they still exist), so I see no reason to deal with any other spawn problem for now.

> In singleplayer, in the rare event of being in a hole with no way out, a player can try a new seed.
If having escaped a hole and then respawning in the same hole and somehow the second time not having enough loose material available to escape (rare), or not having prepared for a respawn in the same place, a player can cheat themselves out of the hole if the only alternative is to abandon a valuable world.

:-1: Boo! That's exactly what to avoid. If the player is forced to cheat, that's a failure of the game. This is just a terrible excuse to sidestep the issue.

Yes, the issue is obviously quite rare, I never claimed it was common, but it does exist and when it occurs, it can be frustrating for newbies.

> Such a spawn is, firstly, highly amusing, i love it when it happens to me, and secondly, an interesting strategic challenge to gather loose material to pillar-up, to reach more loose material, to pillar-up more, and choosing a route to escape.

That depends on the game. Yes, it CAN be interesting for pro players. But it's not amusing if you're in a stone-only biome and you're a total newbie.
Besides, you are just trying to dictate your idea of your game to all other games here, so that's another weak argument here.

> Some games may be such that spawning in a hole is not a problem, so the degree to which the engine dictates what type of spawn is suitable should be minimised, otherwise this is forced in situations where it is not needed.

FINALLY a good argument! However, this doesn't change the fact that there are real games that DO have a real problem with “hole spawns”. So I would not be happy in rejecting the issue altogether.

I agree that not all games would actually want this. So I have a compromise: How about a mapgen setting that turns the “hole avoiding algorithm” on/off? Defaulting to “off”. Maybe make it a setting that is available from the game only, if possible. Because as a global setting, it would be too annoying to use.

> For Mapgen V7 specifically, there is no way to detect a small hole surrounded by cliffs, the only solution is to spawn the player on the higher terrain in cliff areas. But because high altitude spawns are not allowed, this then stops spawns occuring in cliff areas, which is 1/3rd of land area.
So not only is there more calculation involved, more spawn point checks are needed to find a suitable spawn point. When a player is spawned there can be up to 1000s of these spawn point checks.
The spawn point is then likely to be further from world centre, and with custom mapgen parameters, more likely to fail and bury the player at (0,0,0).

Ouch, so this seems indeed a problem. Do you have evidence for this? Also, are you seeing this more of a problem in finding a spawn position at all or more of a performance problem?

But assuming you're right:

Who says your PR can be the only possible solution?

First of all, I find it interesting that high altitude spawns are forbidden: First of all, it's not that it cannot be changed. Second of all, isn't this a kind of “arbitrary mapgen restriction that is too specific to games”? ;-) Maybe allow games to disable or at least relax the restriction (still should prevent Floatland area, of course).

I have a different idea: Restrict player spawn to “less erratic” terrain, i.e. terrain where the height differences are not so extreme. I noticed that newbies can have a very hard time in navigating mountainous terrain, even if it's not the “hole”. It's more like the hole is the absolute extreme case.
I have real world first-hand experience from a playtester, so I'm not just imagining this.

Again, as an optional setting. Because I know not all games would want this.

The more I think about it, the more I notice that “spawning” is a science in itself, and there isn't a one-size-fits-it-all solution. With that I can agree with you. It could be a help for games to give them more control over spawning in general. Like letting them pick one of multiple spawning algorithms (that have to be invented first). Algorithm A might be good for creative games, but not for survival games, while algorithm B is made for survival. But this is something to discuss elsewhere, probably.

About 1000s of spawn point checks: Is this a performance problem? Player spawns are thankfully rather rare, but still! Does Minetest do some kind of caching, to remember good spawn points (instead of re-running the full algorithm every single time)?

About burying the player at 0,0,0:
This seems like an emergency fallback, but I think even that one could be a bit smarter:
Can this be prevented by simply looking at the heightmap and picking the highest land position at X=0, Z=0, but ignoring other checks such as altitude? An above-water spawn should also be permitted because a buried spawn is the worst. If the ocean is made out of lava, well, then the player is out of luck again. :-( So my idea is not perfect either.
I mean, logically speaking, there is always land *somewhere* at X=0 and Z=0, except in singlenode maybe.

**Comment by Warr1024** [comment] 2019-03-24 20:29
Based on what paramat is saying, it seems like the implication is that this issue should be resolved by the game, not the engine.  Not only can the engine not safely make assumptions about what is or is not a "problematic" spawn for any given game, but the engine should not _impose_ those assumptions on other games.

**Comment by paramat** [comment] 2019-03-24 21:29
> That's exactly what to avoid. If the player is forced to cheat, that's a failure of the game.

Yes i want to avoid cheating too. However note i explained that it would be extremely rare to respawn in such a hole without a way out, as there was a way out the first time, and the player might realise that respawn will occur in the hole, so they might prepare for that.
> I am not aware of other impossible spawns (except for obvious bugs that bury you inside land, if they still exist), so I see no reason to deal with any other spawn problem for now.

I was writing generally and the argument is based on considering the future, i wrote:
> There will be no end to the types of bad spawns, so no end to the extra code needed to avoid these. It's better to not start going in this direction for mapgens, especially when a singleplayer can just try a different seed instead.

> you are just trying to dictate your idea of your game to all other games here

No, i'm not describing escape from a hole as intended gameplay.
> How about a mapgen setting that turns the “hole avoiding algorithm” on/off?

No because all that code is still needed, and i've explained that impossible spawns aren't a problem: just try a different seed, *as players already do when starting a new world*.
> Who says your PR can be the only possible solution?

Me, because i understand V7 and noise better than anyone. It's logically the only solution.
> I find it interesting that high altitude spawns are forbidden: First of all, it's not that it cannot be changed.

High altitude spawns are avoided because they cause impossible spawns, like on a pillar or a floating island with deadly drops. I'd quite like to remove the low altitude restriction too but it is actually far more effective and simpler than hole avoidance. I agree it should probably be optional, i may do that.
> Like letting them pick one of multiple spawning algorithms

This is even more complex, the spawn-finding code in a mapgen is already almost as big as the terrain generation code.
> About 1000s of spawn point checks: Is this a performance problem?

Not currently, but you are suggesting making the checks more complex and having more checks.
> About burying the player at 0,0,0:
This seems like an emergency fallback, but I think even that one could be a bit smarter:
Can this be prevented by simply looking at the heightmap

The player is positioned before mapgen starts, so the heightmap doesn't exist, this is the only erason we have terrain level prediction code.

**Comment by Wuzzy2** [comment] 2019-03-25 07:23
> Based on what paramat is saying, it seems like the implication is that this issue should be resolved by the game, not the engine..

But how? The game first has to know if a player has landed in a hole. That's a huge problem! The only thing I could think of for now is iterating through a huge amount of nodes and then *somehow* determining whether spawn is a “hole”. We can probably come up with an algorithm, but it will be inefficient as hell.
I can't think of an efficient (!!!) solution on the game level.

Note I do not propose to force the “hole avoiding algorithm” (if it exists) upon all games.

Paramat, why did you ignore my suggestion about avoiding “erratic” terrain?

> High altitude spawns are avoided because they cause impossible spawns, like on a pillar or a floating island with deadly drops. I'd quite like to remove the low altitude restriction too but it is actually far more effective and simpler than hole avoidance. I agree it should probably be optional, i may do that.

Cool.

**Comment by ClobberXD** [comment] 2019-03-25 07:32
> The player is positioned before mapgen starts, so the heightmap doesn't exist, this is the only erason we have terrain level prediction code.

Is it possible to generate only one chunk that covers `(0,0,0)`, and then check if the player can be spawned? If the player can't be spawned anywhere on that chunk (which should be very rare, if I understand correctly) an adjacent chunk in a random direction should be generated, and this check run again. Would this actually be more noticeably efficient than terrain level prediction code?

**Comment by paramat** [comment] 2019-03-28 19:34
ClobberXD that would be far too intensive. Currently each spawn position tested only does the mapgen calculations for a single node column (1/6400 of a mapchunk). Spawning requires 100s -1000s of tested positions, extending as far as 4000 nodes from world centre, to find a suitable position.
> If the player can't be spawned anywhere on that chunk (which should be very rare, if I understand correctly)

It's very common that spawn can't happen within a mapchunk: it's often ocean or land above y = 16, even in the more normal mapgens with non-customised parameters. Now imagine custom parameters or mapgens that create oceans 1000s of nodes across.

Avoiding erratic terrain is inefficient because that does not necessarily correspond to impossible spawns. Also my arguments apply to that too.

**Comment by ClobberXD** [comment] 2019-03-29 01:05
Wow I underestimated the intensity of this feature. Thanks for the clarification. :)

**Closed** 2020-02-12 23:36 UTC
Labels: @ Mapgen, Low priority, Non-trivial, Request / Suggestion, Won't add

**Comment by Fixer-007** [comment] 2020-02-14 12:36
I see some dirt on that picture, digging it may help escaping. Rare cases like this may actually be desirable for hardcore survival players.
