### ISSUE TITLE
V7 Mapgen not working properly.

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#3591] opened 2016-01-21 01:44 UTC
This.
![screenshot_20160120_193833](https://cloud.githubusercontent.com/assets/9893266/12468995/df39f826-bfad-11e5-9502-2ed8837cfeac.png)
![screenshot_20160120_193835](https://cloud.githubusercontent.com/assets/9893266/12468997/e0d95a5a-bfad-11e5-93bd-7b42142448fd.png)
![screenshot_20160120_193843](https://cloud.githubusercontent.com/assets/9893266/12468999/e1e56290-bfad-11e5-88b4-6b39c10bb68d.png)
I can submit my mapgen code if requested, although I imagine this isn't caused by mapgen aliases, ores or biomes.

EDIT : /deleteblocks seems to work on these... But I'm not sure how they got there in the first place. This world only existed for a few minutes.

EDIT 2: It happens again when creating a world with the same seed.
![screenshot_20160120_194716](https://cloud.githubusercontent.com/assets/9893266/12469115/c04ada9c-bfae-11e5-9773-74ebe4168bef.png)

**Comment by paramat** [comment] 2016-01-22 10:26
Weird, what configuration are you using, any mapgen aliases, custom ores/biomes/decorations?
I'll test the seed. The shadows on the ice are weird too.

**Comment by C1ffisme** [comment] 2016-01-22 23:52
> any mapgen aliases, custom ores/biomes/decorations

Yeah, I am. It's a subgame I'm making.

It happens in v6 too, so it's probably ores, since my biomes/decorations do not register on v6. I'll make a gist real quick...

**Comment by C1ffisme** [comment] 2016-01-22 23:54
https://gist.github.com/C1ffisme/a95bf3520b7c780c90ad

Here is the mapgen code, but not the registry. I can give that too if you need it.

**Comment by paramat** [comment] 2016-01-23 10:59
Thanks, i can't see a problem. You can remove 'mapgen air' as no mapgen needs this and i have just removed it from MTGame.

**Comment by C1ffisme** [comment] 2016-01-23 18:46
![screenshot_20160123_123752](https://cloud.githubusercontent.com/assets/9893266/12532001/29150e28-c1ce-11e5-966d-0b8bd92d7836.png)

It happens in every mapgen with the seed '87'.

Noticably, the weird chunks are affected by the biome:

![screenshot_20160123_124422](https://cloud.githubusercontent.com/assets/9893266/12532031/3eaa0e22-c1cf-11e5-9cbc-174716281718.png)

**Comment by C1ffisme** [comment] 2016-01-24 20:33
I have isolated it to this line:

```minetest.register_alias("mapgen_mossycobble", "mapgen:limestone")```

**Comment by paramat** [comment] 2016-01-25 13:59
Ok thanks, super weird bug.

**Comment by paramat** [comment] 2016-01-27 23:04
Since it's due to your subgame i'll close this, but i'm still interested how this happens.

**Closed by paramat** 2016-01-27 23:04 UTC
Labels: @ Mapgen

**Comment by C1ffisme** [comment] 2016-01-28 23:13
@paramat It seems that it is caused by dungeongen, since that is the only mapgen that uses `mapgen_cobble` and `mapgen_mossycobble`

**Comment by 0-afflatus** [comment] 2016-02-17 08:52
This is the weirdest mapgen bug I've seen. If /deleteblocks works it does suggest that this is a side-effect rather than directly a problem with your mapgen. It reminds me of the v7 bug caused by moretrees. Other than that I'm clueless. Fascinating captain.
