### ISSUE TITLE
GamePad Bluetooth controller 

### ISSUE THREAD

**Issue by Pierochr** [minetest/minetest#15127] opened 2024-09-06 16:52 UTC
### Problem

I can't find a way on rocknix ex jelos to configure minetest with external Bluetooth gamepad

### Solutions

Can't play , can't associate gamepad external Bluetooth 

### Alternatives

Only way is to play with console x55

**Comment by rubenwardy** [comment] 2024-09-06 17:05
Duplicate of #4153 

See this link for a work around for now: https://wiki.minetest.net/Gamepads

**Closed by rubenwardy** 2024-09-06 17:05 UTC
Labels: Feature request
