### ISSUE TITLE
Lighting bug with light-emitting liquids

### ISSUE THREAD

**Issue by Ekdohibs** [minetest/minetest#2823] opened 2015-06-24 15:10 UTC
After removal of a light-emitting liquid, there are sometimes nodes that still stay lit while there is no light source.

To reproduce:
- go to a place with no light
- dig a 2x1 hole; the hole should be in the north/south direction
- place a lava block in one of the nodes of the hole, and wait for it to spread
- remove the lava block with a bucket (do not replace it with another node)
- result:

![screenshot_20150624_170702](https://cloud.githubusercontent.com/assets/2923554/8333573/e542f0d4-1a93-11e5-8f6f-9cc6b27b21fa.png)

**Comment by est31** [comment] 2015-06-24 15:50
Can't reproduce

**Comment by est31** [comment] 2015-06-24 15:54
Perhaps its because its at a mapblock border? your z coordinate sais 47.7. 48 == 16 * 3

**Comment by est31** [comment] 2015-06-24 15:56
Yes, I can confirm it at a mapblock border

**Comment by est31** [comment] 2015-06-24 15:59
Also, its a server bug, not in client prediction. Its still there at re-login.

**Comment by est31** [comment] 2015-07-23 05:50
I've thought it was an easy bug, seems it needs more work, removing it from the milestone as its not critical.

**Comment by C1ffisme** [comment] 2015-07-24 01:29
I had a similar bug in the older versions of minetest, but instead of staying light, it was strangely dark once lava disappeared.

**Comment by paramat** [comment] 2016-04-02 23:54
Might be worth retesting as mapgen lighting calculation has become more robust.

**Comment by Ekdohibs** [comment] 2016-05-04 11:45
I can confirm the bug is still present.

**Comment by PilzAdam** [comment] 2016-05-04 12:25
Reminds me of this: ecb024af641065f152ce71ac13cde8b357394d0f

I can confirm that this happens in current master.

**Comment by paramat** [comment] 2016-05-04 15:15
UpdateLighting has issues, this may be another one.
Fixer has found these bugs at block borders around lavacooling mountains on servers.

**Comment by Fixer-007** [comment] 2016-05-04 15:57
Yes, if you are interested to see it, go to "No rules" server, I asked admin not to fix it yet. I also had this bug randomly when I dealt with huge amounts of lava.

**Comment by paramat** [comment] 2016-10-27 08:30
Maybe fixed by #4655 ?

**Comment by Fixer-007** [comment] 2016-10-27 16:02
I tried to reproduce it with PR4655 on 6eb6e75 on mapgen7 and only thing I seen is this:
![1](https://cloud.githubusercontent.com/assets/16494741/19774995/9580e9f4-9c77-11e6-8052-076304fa9b8f.png)
![2](https://cloud.githubusercontent.com/assets/16494741/19774994/956230a4-9c77-11e6-9c58-c45ac1a0d179.png)

Holes coordinates: 
-111 x 64 (lava source)
-111 x 65

Looks like ghost lighting in corner of mapblock. Can you check it?

**Comment by juhdanad** [comment] 2016-10-27 20:58
I don't know what causes this. I also see the light, but the light values of the lighting node and its 26 neighbors is zero both on the client (tested with `printf()`) and the server (when you quit and play again, you can't see the light).
I think this bug is in the block mesh generating code.

**Comment by paramat** [comment] 2017-03-11 02:43
Does #4682 fix this?

**Comment by juhdanad** [comment] 2017-03-11 15:21
Yes, #4682 fixed this. What Fixer found there https://github.com/minetest/minetest/issues/2823#issuecomment-256689445 is a small bug in mesh generation, but lighting is correct. If you use non-smooth lighting, you should see no issues with lava.

**Comment by sofar** [comment] 2017-03-12 07:53
I'll close it for now. I threw lots of lava and removed it with a bucket, and it all came out fine.

**Closed by sofar** 2017-03-12 07:53 UTC
Labels: @ Server / Client / Env., Bug
