### ISSUE TITLE
GUI : Text goes out of the buttons when resizing the window

### ISSUE THREAD

**Issue by freerig** [minetest/minetest#13748] opened 2023-08-22 09:18 UTC
##### Minetest version 5.7.0

Read the title.
![image](https://github.com/minetest/minetest/assets/98414804/21f3abee-ed0f-41d2-9208-c52fc80c0c2a)
![image](https://github.com/minetest/minetest/assets/98414804/baa0734d-19e6-4dad-82d9-c2b2da1d3d62)
![image](https://github.com/minetest/minetest/assets/98414804/de7330c4-7be9-4bac-bba1-47325c73ecf5)
(in the about page: )
![image](https://github.com/minetest/minetest/assets/98414804/2ecdda9b-7806-42fc-ae84-f09b81435078)

**Comment by sfan5** [comment] 2023-09-11 18:38
An issue this obvious as probably been reported before so if someone finds the duplicate feel free to link it here.

**Comment by SmallJoker** [comment] 2023-09-11 18:59
The same issue was reported for ContentDB in specific: #7408.
Labels and checkboxes do not have an option two wrap text. Minetest's GUI layouting system is not really made for adapting to such large scaling changes. This one of the major points in #6527, thus I would consider this issue a duplicate of the general replacement plans.

**Comment by grorp** [comment] 2024-05-09 20:59
Also see #4607

**Comment by SmallJoker** [comment] 2024-05-11 14:11
Would this be an acceptable solution: downscale the font size when the window gets too small. There is no way to make the text fit either way.

Perhaps the same technique could be applied to buttons when the text becomes too long.

**Comment by grorp** [comment] 2024-05-11 14:32
Before attempting to scale the text down, an attempt to scale the menu up should be made. The mainmenu formspec currently only uses a small fraction of the available space if you have a small window. See #14037 .

**Comment by grorp** [comment] 2024-09-06 12:33
The general problem has been fixed (as much as reasonably possible with formspecs) by #14840, so closing this issue. A formspec replacement shouldn't have this issue.

Specific problem cases in the mainmenu (e.g. a specific button being too small for its text/translations) can be reported and fixed separately.

**Closed by grorp** 2024-09-06 12:33 UTC
Labels: Bug, @ Client / Audiovisuals, Formspec, UI/UX
