### ISSUE TITLE
Sunrise always visible through skybox

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#9547] opened 2020-03-25 13:27 UTC
Example code:
```Lua
minetest.register_on_joinplayer(function(player)
	player:set_sky({
		type = "skybox",
		textures = {
			"default_stone.png",
			"default_stone.png",
			"default_stone.png",
			"default_stone.png",
			"default_stone.png",
			"default_stone.png",
		},
	})
end)
```

Any time of the day:
![A7yRYVL](https://user-images.githubusercontent.com/7883281/77541209-9e6f2f00-6ea4-11ea-9e6b-47fe4c48fb7a.png)

**Comment by pyrollo** [comment] 2020-03-25 13:42
This can be solved issuing a : 
```	player:set_sun({
		sunrise_visible = false,
	})
```

But a similar problem persist using a sky type `plain`, the horizon and fog at horizon stuff is missing so the bottom part of sky is not masked.

**Comment by kilbith** [comment] 2020-03-25 13:45
`sunrise_visible = false` only solves the issue partially as it makes it invisible _permanently_. For a `skybox` type that would make sense as it's not supposed to show the sun, that's the reason why the sunrise should be made invisible by default for that type.

**Comment by pyrollo** [comment] 2020-03-25 13:48
An example using plain green sky:
![screenshot_20200325_144401](https://user-images.githubusercontent.com/13189280/77542895-2c4c1980-6ea7-11ea-95dc-978317733fed.png)


Tried to show "cloudy fog thing blended with skycolor" and "cloudy fog thing below all horizons" in sky.cpp but had serious color issues (default sky color used for fog and horizon during day).

**Comment by pyrollo** [comment] 2020-03-25 14:11
Ok, after some tests, my opinion is that `plain` sky type should be deprecated and `regular` sky type should be used instead, with `sky_color`. Works much better.

**Comment by paramat** [comment] 2020-03-25 16:59
The sunrise texture being visible by default is intentional (as i mentioned when you last reported this on IRC), and was discussed by Jordach and me in the PR. So is not a bug.

All elements have bools so disabling it is currently needed in certain sky modes. Perhaps we could set the default value to false in certain modes as i have suggested before? Seems to me that it will usually not be wanted in skybox and plain modes.
@Jordach 
> sunrise_visible = false only solves the issue partially as it makes it invisible permanently.

Please can you clarify this, why 'partially'? Do you mean that skybox and plain modes should have a horizon that masks the sunrise texture?
If so, the big problem with this proposal is that the horizon would then mask everything, making skybox mode much less flexible and unusable for space games.
> For a skybox type that would make sense as it's not supposed to show the sun

The skybox mode is supposed to show the sun, it is drawn in front of the skybox textures.

I think everything is fine as it is except: We could set the default of the sunrise texture bool to false in skybox and plain modes.

**Comment by Wuzzy2** [comment] 2020-03-28 20:29
Note that this is a regression. So it's a bug (sorry).
In 5.1.1, the skybox sky type did not render sun or sunrise at all.

When a game developed in 5.1.1 now gets played in 5.2.0, this means the sunrise will appear out of nowhere. It requires manual intervention from the game author to fix this (this is bad).

So, the default behavior should be identical to 5.1.1, for maximum backwards-compability.

> We could set the default of the sunrise texture bool to false in skybox and plain modes.

Yeah, I think this will do the trick.

**Comment by Wuzzy2** [comment] 2020-03-28 20:36
Oh, it seems I was wrong about this being a regression. Old behavior is, in fact, preserved with the old function syntax. So, no surprise sunrise. So then it's not really a bug …

**Comment by paramat** [comment] 2020-04-01 19:48
Wuzzy2 yes i thought that too and retested, the old call still hides the sunrise texture.

So, is it desirable to other core devs to change the default value of the bool? If so this should be done now before release to avoid a change to the API later.
Therefore marking as a blocker, as it might be one.

**Comment by rubenwardy** [comment] 2020-04-01 19:58
I think the set sky API is much simpler if the default don't change depending on type, so I'd prefer the current behaviour

**Comment by paramat** [comment] 2020-04-01 21:31
Heh i just came back to express exactly that =) i realised that the default needs to be true for regular sky, setting the default to false for the other types is messy. So i also think the behaviour is fine as it is. I seem to remember i was fine with it in the review too.
Removed 'blocker' label.

**Closed** 2020-04-01 22:50 UTC
Labels: @ Client / Audiovisuals, Not a bug, Possible close, Request / Suggestion
