### ISSUE TITLE
CMake cmd fails to generate Makefile on compiling Minetest-5.5.0-dev.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#11500] opened 2021-07-30 18:39 UTC
##### Minetest version
```
Minetest-5.5.0-dev-1e2b638
```

##### Summary
CMake can not generate Makefile and terminates with a following error as if there is no IrrlichtMt enabled:
`
    *** Will build version 5.5.0-dev ***
  CMake Error at CMakeLists.txt:78 (message):
  IrrlichtMt is required to build the client, but it was not found.

  The Minetest team has forked Irrlicht to make their own customizations.  It
  can be found here: https://github.com/minetest/irrlicht
`

However, I compiled IrrlichtMt at commit 6c78f18 succesfully and directed paths to the executable and include folder:
`
$ cmake . -DRUN_IN_PLACE=1 -DIRRLICHT_LIBRARY=/home/andrey/irrlicht_mt/lib/Linux/libIrrlichtMt.so -DIRRLICHT_INCLUDE_DIR=/home/andrey/irrlicht_mt/include
`
Why can it not generate the Makefile?

**Comment by sfan5** [comment] 2021-07-30 18:42
duplicate of #11497

**Closed by sfan5** 2021-07-30 18:42 UTC
Labels: Unconfirmed bug
