### ISSUE TITLE
Some keys don't work properly on non-QWERTY keyboards

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#302] opened 2012-11-25 09:39 UTC
See the title. As I also can't paste stuff in the address bar (#373), I have to switch to QWERTY temporarily to be able to write "7" in a field...

To be more accurate, the keyboard layout I'm using is French "alternate".

**2014-08-15:** the bug is still here.

**Comment by nerzhul** [comment] 2015-02-12 10:52
Confirmed. I use a proper azerty

**Comment by est31** [comment] 2015-06-11 12:02
Can somebody try this bug with irrlicht 1.9?

**Comment by nerzhul** [comment] 2015-06-11 12:09
As i remember this is a bug in irrlicht and this is fixed in irrlicht 1.9 . Some other games have the same problem

**Comment by est31** [comment] 2015-06-11 12:12
Input in irrlicht < 1.9 is horrible.

**Comment by nerzhul** [comment] 2015-06-16 11:26
:+1:

**Comment by paramat** [comment] 2016-03-27 13:35
See http://irc.minetest.ru/minetest-dev/2016-03-27#i_4566799
"yes #302 works will irrlicht 1.9-dev i can confirm, but recent MT development workaround on console break some things"

**Comment by ObaniGemini** [comment] 2016-03-27 16:29
"7" character problem was solved by removing the chat formspec. "7" is not writtable in formspecs in Minetest.

**Comment by paramat** [comment] 2016-08-22 00:20
@Calinou can this be closed since it's an upstream issue? Or is this useful to keep open?

**Comment by est31** [comment] 2016-08-22 00:25
I think its useful to track issues that are not fixed in the latest upstream release, and to keep them open. There wasn't a 1.9 release yet of irrlicht, so it should be kept open.

**Comment by paramat** [comment] 2016-08-22 00:35
Ok.

**Comment by nerzhul** [comment] 2017-03-15 14:44
Closing this issue as it's an upstream issue, we cannot fix it, having it in backlog doesn't matter

**Comment by GilDev** [comment] 2017-08-07 23:27
Hi, so this issue from 2012 still cannot be fixed? How can we play then?
Doesn't work for Azerty nor Bépo.

**Comment by Fixer-007** [comment] 2017-08-08 14:18
Compiling minetest with irrlicht 1.9-dev should help.

**Comment by JLuc** [comment] 2018-03-29 10:16
Same issue happens with latest minetest 0.5 daily builds. No way to type 7 in the IP input and no way to copy'n'paste in that input neither.

This report is closed because issue is "upstream" but what project and where exactly is related upstream report ?

**Comment by nerzhul** [comment] 2018-03-29 10:40
@JLuc is your irrlicht version up to date ?

**Comment by nerzhul** [comment] 2018-03-29 10:40
i think we should backport some irrlicht 1.9 parts on keyboards if needed

**Comment by JLuc** [comment] 2018-03-30 05:58
Ubuntu 17.10 uses Irrlicht 1.8.4 
I guess many linuxes wont use the latest irrlicht versions neither.

**Comment by M1dgard** [comment] 2018-05-27 00:01
> Ubuntu 17.10 uses Irrlicht 1.8.4
I guess many linuxes wont use the latest irrlicht versions neither.

On the project [downloads page](http://irrlicht.sourceforge.net/?page_id=10), it says 1.9 is still *unstable* and *probably broken*. So packaging 1.8.4 seems quite sensible.

**Comment by JLuc** [comment] 2018-05-27 07:47
How about keeping 1.8.4 AND backporting some irrlicht 1.9 parts on keyboard (quoting nerzhul) ?

**Comment by nerzhul** [comment] 2018-05-27 14:03
i think the @JLuc can be an idea, but we should find which interface and commits are to be backported

**Comment by MuhdNurHidayat** [comment] 2019-01-10 12:55
> How about keeping 1.8.4 AND backporting some irrlicht 1.9 parts on keyboard (quoting nerzhul) ?

Can someone do this, then make PR?

**Comment by JLuc** [comment] 2019-01-10 20:57
libIrrlicht is still 1.8.4 on Ubuntu 18.04 and it seems the same on ubuntu 18.10 ( https://www.ubuntuupdates.org/pm/libirrlicht-dev )

Of course some day it will eventualy migrate to 1.9... and 2... and 3...

**Comment by cronvel** [comment] 2019-11-14 09:27
I just upgraded to Minetest 5.1, switched from the Fedora repo to Flatpak, but the keyboard issue are still there.

Fedora 31 and french keyboard here: I can't write a '7' and there are many many other issues: keypad '5' is detected as 'home', just like keypad '7', '*' is detected as '3', and so on... I don't know what is the version of Irrlicht that comes with the flatpak package.

**Comment by paramat** [comment] 2019-11-14 22:40
Reopen to consider:
> How about keeping 1.8.4 AND backporting some irrlicht 1.9 parts on keyboard (quoting nerzhul) ?

**Comment by piecubed** [comment] 2019-11-26 20:10
Its broken for QWERTY keyboards connected to a mac as well.  Left shift doesn't work.

**Comment by daretmavi** [comment] 2020-03-14 11:09
It still present on my Laptop Asus Aspire V13 (Kde Neon).
In Menu 4 and 7 can not be used and in game 4 is acting like "Enter".
Setting correct resolution means using CTRL-C + CTRL-V from another place.

**Comment by oleastre** [comment] 2020-05-12 21:33
I did the exercise to backport the irrlicht 1.9 linux keyboard handling code to 1.8.4, and I even added some tricks learned from SDL concerning number keys on azerty keyboards.
Here is the patch; use it as you which ;)
[irrlicht-1.8-backport-i18n-key-input-for-X11.patch.txt](https://github.com/minetest/minetest/files/4618545/irrlicht-1.8-backport-i18n-key-input-for-X11.patch.txt)
I also have a fedora copr build of irrlicht and minetest 5.0.2 with that patch applied.

**Comment by nerzhul** [comment] 2020-05-15 06:35
again, this show that the 1.8.4 is broken and we need to integrate irrlicht to fix bug asap as irrlicht didn't release in years... @sfan5 i really think i will try to embed irrlicht in our build setup to permit patching it for our needs/bugs

**Comment by sfan5** [comment] 2020-05-15 08:50
Embedding the entirety of Irrlicht in the engine would be a bit much, but maybe we have to get creative with solutions to swap-out individual parts of Irrlicht.

**Comment by nerzhul** [comment] 2020-05-15 08:54
i agree but as i see with @oleastre it's exactly the same problem i have with the wayland porting: it's in the Cblah.cpp files which are not exposed and not overwriteable because the devices are locked in the engine and when you take the device you gather big part of irrlicht. I may try in my wayland PR to extract the whole Linux device but it sounds crazy as it extract other irrlicht engine parts

**Comment by oleastre** [comment] 2020-05-15 10:45
In that kind of situation with external libraries that do not match their expected standards, some projects just propose to replace the library with their own forked and patched version, while keeping backward compatibility for distribution that do not allow libraries embedding (but when the fork solves many issues, exceptions are easy to get).
And from the keyboard handling code point of view, I think it would make sense for irrlicht to just use SDL2 as the interface with the OS and concentrate on the engine added value instead of reinventing the wheel. There is a lot of things already done to abstract the lowlevel stuff in SDL, it's a pitty to not use it. I know, it's a new dependency to add, but it could solve many problems.

**Comment by rubenwardy** [comment] 2020-05-15 16:22
Using SDL would be great, and would make doing things like add gamepad support much easier

**Comment by nerzhul** [comment] 2020-05-15 16:39
yes it can be but it's 2 deps with opengl support and major rewrite, for a such case consider godot instead of SDL especially for 3D support then.

**Comment by rubenwardy** [comment] 2020-05-15 16:52
You can use SDL alongside Irrlicht, just to provide input.

Switching to Godot would require throwing away all of our code. If you wanted to replace Irrlicht with SDL, then you'd rewrite any Irrlicht code to use raw OpenGL instead

**Comment by nerzhul** [comment] 2020-05-15 17:18
maybe we can try to re-architecture minetest by:
1. first include irrlicht in source tree with our addition & drop useless parts
2. add our needs (wayland rendering, whatever)
3. sdl binding if it's not too heavy to replace irrlicht key bindings

if it's a possible proposal plan i'm fine.
Currently i'm working on include irrlicht in our source tree for my wayland renderer, but that can be outside of the PR scope

**Comment by nerzhul** [comment] 2020-05-15 20:20
i have a nearly ready and easy irrlicht import ready. Should publish a PR this weekend, that will help to fix problems inside it

**Comment by oleastre** [comment] 2020-05-15 21:59
I mentioned SDL because there is already a Irricht SDL device alongside the Linux one, see:
https://sourceforge.net/p/irrlicht/code/HEAD/tree/trunk/source/Irrlicht/CIrrDeviceSDL.cpp
I think it's not updated for SDL2, but if you have a Irrlicht fork, then it's doable to do the port. 
I can give a bit of time to do that.

**Comment by nerzhul** [comment] 2020-05-16 08:33
#9879 here is the proposal PR, i need to fix windows build

**Comment by nerzhul** [comment] 2020-05-18 06:50
@oleastre i tried your patch but it doesn't work. it compiled but i'm unable to use accents or the pad num properly

**Comment by oleastre** [comment] 2020-05-18 07:04
I only back-ported the code and added some bits to correctly handle numbers. 
My tests with the irrlicht `examples/05.UserInterface/` allows me to enter accents on a French keyboard, but do not allow me to use dead keys. 
And I did not tested accents in minetest, but only numbers. So there is maybe a slight difference between the exemple and minetest entries

**Comment by oleastre** [comment] 2020-05-18 07:34
Just tested the numpad in the example and indeed it's not working neither. 
Really the patch is just a backport of what exists in irrlicht 1.9. And what is there is disappointing, it was supposed to solves keyboard problems, but does not seem to solve that much. 
I'll try the irrlicht SDL backend later this week to see if this improves things. But I suspect I'll have to port it to SDL2.

**Comment by nerzhul** [comment] 2020-05-28 17:56
it seems to be a debugger issue, but honestly no difference on my key with or without the patch. the `è` char on azerty works in game console but not in the inputs, very very strange

**Comment by oleastre** [comment] 2020-05-28 21:27
My main goal was to get the numbers working on my azerty keyboard. Now, I can try to move the patch forward, or try to get the SDL driver working. 
IS you mintest + vendored irrlicht branch working ?

**Comment by numberZero** [comment] 2020-08-29 22:06
Note that accented characters may be represented by one or several code points: either pre-composed, or separate base character and the accent(s). The patch posted here passes only the first code point, discarding anything remaining.

So, is there any library/engine/framework that gets Unicode input right? (By "right" I mean supporting Russian, Czech, Chinese and Korean at least, and the numpad of course ;)

**Comment by Pevernow** [comment] 2020-08-30 01:28
At present, the temporary solution is to install the Unicode parser into the ”clientmod" and fill in the Unicode code of the string

I wrote a little software for it. Will help it work better

https://github.com/Pevernow/Unicoder

**Comment by imre84** [comment] 2021-02-20 21:44
would an xev output like this help resolving the issue?

KeyPress event, serial 34, synthetic NO, window 0x2800001,
    root 0x7a6, subw 0x0, time 32823650, (1421,521), root:(1531,623),
    state 0x0, keycode 34 (keysym 0x1f5, odoubleacute), same_screen YES,
    XLookupString gives 2 bytes: (c5 91) "ő"
    XmbLookupString gives 2 bytes: (c5 91) "ő"
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x2800001,
    root 0x7a6, subw 0x0, time 32823746, (1421,521), root:(1531,623),
    state 0x0, keycode 34 (keysym 0x1f5, odoubleacute), same_screen YES,
    XLookupString gives 2 bytes: (c5 91) "ő"
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x2800001,
    root 0x7a6, subw 0x0, time 32824850, (1421,521), root:(1531,623),
    state 0x0, keycode 35 (keysym 0xfa, uacute), same_screen YES,
    XLookupString gives 2 bytes: (c3 ba) "ú"
    XmbLookupString gives 2 bytes: (c3 ba) "ú"
    XFilterEvent returns: False

**Comment by ronoaldo** [comment] 2021-02-22 17:48
To add more info to the issue, it also happens with QWERTY keyboard layout with "dead keys", used to support languages like Brazilian Portuguese.

When I try to type in a search for "algodão" in creative inventory, the input is interpreted as "algod~ao" instead, with the following message pinted to stdout/stderr:

```
Could not find EKEY_CODE, using orig. X11 keycode instead: 48
```

**Comment by sfan5** [comment] 2021-03-24 19:23
fixed by https://github.com/minetest/irrlicht/commit/7f0e0a57b8e54b3e1bff7a0606a1a376a50c36a8
Note that this does not fix dead keys.

**Closed by sfan5** 2021-03-24 19:23 UTC
Labels: @ Client / Controls / Input, Bug, Linux, Upstream issue

**Comment by ronoaldo** [comment] 2021-03-25 14:27
Should I open an issue for dead keys or is there one already?

Em qua, 24 de mar de 2021 16:23, sfan5 ***@***.***> escreveu:

**Comment by sfan5** [comment] 2021-03-25 15:17
There was one for it already and I fixed dead key handling (on Linux) 4 hours ago.

**Comment by quarthex** [comment] 2021-04-17 17:48
I had to add the following lines in order to register bindings for my bépo keymap.

```diff
index fac077f0f..bfd0b4094 100644
--- a/src/client/keycode.cpp
+++ b/src/client/keycode.cpp
@@ -240,6 +240,9 @@ static const struct table_key table[] = {
        DEFINEKEY5("]")
        DEFINEKEY5("^")
        DEFINEKEY5("_")
+
+       { .Name = "é", .Key = irr::KEY_KEY_CODES_COUNT, .Char = L'é', .LangName = "é" },
+       { .Name = "è", .Key = irr::KEY_KEY_CODES_COUNT, .Char = L'è', .LangName = "è" },
 };
 
 #undef N_
```

**Comment by PetiAPocok** [comment] 2021-11-15 18:45
For me the ú and ő doesn't work. (While the rest of the accented characters that I use ( á é í ö ü ó ű ) works properly.)
