### ISSUE TITLE
Formspec requests: Themes. Suitable button style. Button feedback

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#5810] opened 2017-05-24 04:06 UTC
Okay, I know that this is the engine, and not the feature-filled, colorful Minetest Game, but hear me out. (These are also mostly minor nitpicks, just as a warning.)

When I click a button in most games, I'll get audio feedback from it. Either a "click" or even a satisfying "ca-chunk". GUIs in Minetest don't do that, they just silently preform the action they do when you press them. This makes clicking through a menu feel slightly eerie, or just boring at the very least.

Most games will have decorative backgrounds behind their buttons, [(Something I failed miserably at...)](https://github.com/minetest/minetest_game/pull/444) but Minetest has a transparent black background. (Minetest Game has an opaque one.) This is acceptable, but it could use some improvement.

Lastly, buttons look bland, and don't really fit the style of a pixely, blocky game:

![Again, Github can't process this file correctly, so I have to use CubeUpload.](http://u.cubeupload.com/C1ff/screenshot2017052322.png)

(I'd also complain about the text not really being centered, or some other positioning things, but a lot of that has to do with my font and GUI scale settings. And some of it is just difficult to fix.)

Again, these are some minor issues that just make the game look a little ugly to me.

**Comment by dsohler** [comment] 2017-05-24 20:53
Formspecs are completely messed up and the code should be rewritten completely. Problem: figuratively none of the most influential devs cares about the look and feel of them.

**Comment by Calinou** [comment] 2017-05-24 21:49
Audio feedback for the UI is nice, but the sounds should carefully be picked as to not be annoying. It should also be able to be turned off easily.

I'm quite sure Minetest uses the default or mostly-default Irrlicht UI styles, it is possible to customize them to an extent, but it might not be easy.

**Comment by tobyplowy** [comment] 2017-05-25 01:31
@C1ffisme this will be closed very soon (or ignored) like Every other attempt to improve the ui of minetest
You're just going to have to accept it just like me the ui looks bad and unappealing it won't change
It's sad but it is the truth

**Comment by tobyplowy** [comment] 2017-05-25 01:44
In my opinion the ui looks bad and unappealing (This Is Not An Attack It's just my opinion) also we can't customise the ui with texture packs apart from the trash icon and background but not the slots those stay black or gray (another problem with ui Textures is that it stretches the image and it looks ugly even with mods unless you have the perfect screen size) 32x32 textures for items are also a problem look at this issue to understand what I'm talking about https://github.com/SummerFields/Summerfields-Minetest/issues/82

also i like the idea of sounds it gives more impact to clicking the buttons :)

**Comment by paramat** [comment] 2017-05-25 06:41
> When I click a button in most games, I'll get audio feedback from it. Either a "click" or a satisfying "ca-chunk". GUIs in Minetest don't do that, they just silently preform the action they do when you press them. This makes clicking through a menu feel slightly eerie, or just boring at the very least.

Performing the action is the feedback.
If 'most games' do something that is not alone a good reason to do that thing. Most of those games may be doing that thing because 'most other games do it' and not for any good reason.
My mouse goes click, that's enough clicking for me, don't need more.
If it feels eerie then you are just used to other games, it's not an actual problem.
Clicking buttons in a menu is not meant to be exciting, who expects excitement from a menu button press?

It is now possible to alter the colour and opacity of GUI backgrounds, not sure if any image can be used, i guess that would be your request here. The decision whehter to use a decorative image would be down to the subgame not the engine.

The buttons use the font set, there is a PR for button images inMTGame, but that has resizing issues that distort the images.

**Comment by dsohler** [comment] 2017-05-25 07:20
> If 'most games' do something that is not alone a good reason to do that thing.

Like it or not: optical or audible feedback from a menu button press is expected behavior. If it's missing it feels incomplete or wrong for most people except you.

**Comment by rubenwardy** [comment] 2017-05-25 10:33
> Performing the action is the feedback.
If 'most games' do something that is not alone a good reason to do that thing. Most of those games may be doing that thing because 'most other games do it' and not for any good reason.
My mouse goes click, that's enough clicking for me, don't need more.
If it feels eerie then you are just used to other games, it's not an actual problem.
Clicking buttons in a menu is not meant to be exciting, who expects excitement from a menu button press?

Please keep to things other than UI :)

**Comment by paramat** [comment] 2017-05-25 11:37
Visual feedback would be best.
Expected behaviour is not necessarily right behaviour.
@rubenwardy  you  can't ell devs to not comment on certain areas of MT, you are entitled to comment on mapgen and i would not stop you.

**Comment by paramat** [comment] 2017-05-25 11:59
> If it's missing it feels incomplete or wrong

It just feels different, if the feature is not actually necessary then there is no problem.

**Comment by kilbith** [comment] 2017-05-25 13:31
> @rubenwardy you can't ask a dev to not comment on a certain area of MT just because you disagree with their opinion

Your opinion is just noise because, as usual, you can't just shut up regarding topics you don't know shit about and you have no experience in GUI designing.

Take rubenwardy's comment as an advice because people will end up not listening you anymore.

**Comment by paramat** [comment] 2017-05-25 14:20
I suspected you might comment, as you suggested this during your day of foul-mounthed, abusive and threatening personal attacks.
So by this logic it seems most devs should stop commenting on mapgen.

**Comment by paramat** [comment] 2017-05-25 14:24
Part of my comment was unreasonable, feedback is useful to know your mouse click has actually worked.
Sound may not be best, as many have sound off, or might be listening to music.
If the click sound is similar to the sound of the mouse the 2 might be confused.

**Comment by kilbith** [comment] 2017-05-25 14:42
> I suspected you might comment, as you suggested this during your day of foul-mounthed, abusive and threatening personal attacks.

You'd be surprised how many people think the same things about you. It's just I have the balls big enough to express them publicly.

**Comment by dsohler** [comment] 2017-05-25 16:31
> Expected behaviour is not necessarily the best behaviour

There is no such thing as "best behavior".

There are only *expected behavior* (what the majority of users expects because most software behaves like this when performing the action), *desired behavior* (how an individual user thinks what the best behavior would be when performing an action), and *intended behavior* (how the author of the software wants the software to behave when performing an action).

**Comment by C1ffisme** [comment] 2017-05-25 17:02
@paramat @kilbith Please don't start this again. If you want to act mature, then don't start a flame war.

**Comment by nerzhul** [comment] 2017-05-25 19:49
i think @kilbith is the minetest @poettering haha

**Comment by C1ffisme** [comment] 2017-05-25 19:54
@nerzhul That's a story I have not yet heard about...

But as morbidly curious as I am, let's try and keep on topic.

**Comment by hunter688** [comment] 2017-05-29 10:48
I think gui is not so ugly, but too big: #3903

**Comment by tacotexmex** [comment] 2017-05-29 14:42
Getting back on topic, I second that formspec design should be made more configurable. In my mod gmc_extras I tried to override the global `default.gui_slots` variable in Minetest Game with some success, but

1. This only applied to player inventory, not chests, furnaces etc.
2. More than one piece of code competed for setting this variable, making the style pop back and forth from default to custom.

My point here is that slot colors and such _is_ already somewhat customizable, at least in theory. No one seems to have thought of that while writing Minetest Game however. 

Things I'd like to see in a formspec code upgrade is 

- element roundness
- pixel scale multiplier (2px border instead of those pesky 1px ones)
- a handy pixel icon font included by default, with icons for the most common interactions

**Comment by masrourmouad** [comment] 2017-05-29 17:02
it it possible to change the color of the gui

**Comment by azekillDIABLO** [comment] 2017-07-10 13:29
Adding sound to the menu shouldn't be hard, as minetest already support backgrond music in menu!

> for the one who don't know, create `minetest/sounds/main_menu.ogg` to have music :)

**Comment by C1ffisme** [comment] 2017-07-10 15:22
> Getting back on topic, I second that formspec design should be made more configurable.

Configurability is great, but I think the higher priority should be having a formspec design that looks and feels any good at all.

Also, related: #3818

**Comment by tobyplowy** [comment] 2017-07-10 15:48
> Configurability is great, but I think the higher priority should be having a formspec design that looks and feels any good at all.

I agree!
But being able to edit the GUI (all of it) with texturepacks wuld be amazing!

**Comment by rubenwardy** [comment] 2017-10-12 17:31
duplicate: #1399

**Comment by C1ffisme** [comment] 2017-10-13 03:58
@rubenwardy That's not the same. That issue is about improving the API that defines formspecs in mods and in builtin, mine is about improving how that code lays out it's GUIs, and improving on their look.

**Comment by dsohler** [comment] 2017-10-13 06:21
> duplicate: #1399

Not even close.

**Comment by rubenwardy** [comment] 2017-10-13 09:12
I don't think this is going to be solved without a formspecs replacement, so they are the same issue

**Comment by SmallJoker** [comment] 2017-10-13 09:16
@rubenwardy but yet, additional functions like sounds when pressing a button or buttons that scale the image well are features that don't depend on the API in the first line. Surely, a new API would make it easier to correct the positioning and scaling issues.

**Comment by C1ffisme** [comment] 2017-10-13 16:30
@rubenwardy Actually, all of these are things that can be done with functionality that already exists in the engine (Although sounds would have to be played server-side, which isn't preferable) but I would prefer that most of these design choices be implemented in the Vanilla interface, especially the builtin stuff that isn't customizable by subgames or mods.

**Comment by paramat** [comment] 2017-10-13 16:51
This is close to a duplicate, but this issue could be for buttons with feedback and theming, stuff not mentioned in #1399

**Comment by jordan4ibanez** [comment] 2017-11-11 05:33
If this is closed I will lose all respect for the minetest dev team.

**Comment by jastevenson303** [comment] 2017-11-11 08:23
There's button feedback with on_receive_fields.  Upon receiving fields, a
sound could be played.

**Comment by numberZero** [comment] 2017-11-11 09:18
`on_receive_fields`? Seriously? It is server-side. Such use is correct
in the sense that if you hear the sound, the server actually knows the
button was clicked. But client-side feedback is correct in the sense
that if you hear the sound, the client actually sent the event to the
server, so that it will receive it sooner or later (if these messages
are reliable, of course, I don't remember are they).

**Comment by jastevenson303** [comment] 2017-11-11 09:35
So this issue is requesting client-side auditory feedback?

My apologies, I do find this issue vague and possibly too general.

**Comment by rubenwardy** [comment] 2019-03-15 20:28
Partially fixed by #8383

**Comment by paramat** [comment] 2019-09-08 16:55
#8916 adds button feedback and closes this issue.

**Comment by rubenwardy** [comment] 2020-02-02 17:51
I consider this fixed by #8916. I think audio feedback should be discussed in a seperate issue

**Closed by rubenwardy** 2020-02-02 17:51 UTC
Labels: @ Client / Audiovisuals, Request / Suggestion, Supported by core dev
