### ISSUE TITLE
Can't Open World

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#12958] opened 2022-11-13 09:04 UTC
##### Minetest version

```
Idk but version code is 40
```

##### OS / Hardware

Operating system: Android 6.0.1 (lv23)
CPU: ARMv7

GPU model: Mali
OpenGL version: ES 3.1

##### Summary

Opening a world will stop in "Creating Client"
##### Steps to reproduce

instal latest Minetest Android workflow ARMv7 (16:02 13/11/2022 UTC+7)

Open a world or join a server

video:

https://user-images.githubusercontent.com/76146430/201514055-df76639f-6b8d-450f-8bc2-cc289b06c187.mp4

Edit by Zughy: logcat from #12962

```
---------------------------- PROCESS STARTED (31443) for package net.minetest.minetest ----------------------------
2022-11-13 18:12:53.346 31443-31443 NetworkSecurityConfig   net.minetest.minetest                D  No Network Security Config specified, using platform default
2022-11-13 18:12:53.347 31443-31443 NetworkSecurityConfig   net.minetest.minetest                D  No Network Security Config specified, using platform default
2022-11-13 18:12:53.549 31443-31443 netest.minetes          net.minetest.minetest                W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2022-11-13 18:12:53.550 31443-31443 netest.minetes          net.minetest.minetest                W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2022-11-13 18:12:53.858 31443-31443 linker                  net.minetest.minetest                W  Warning: "/data/app/~~7RtIP4J3aOoJfNOnmNfSLQ==/net.minetest.minetest-tEyEU17rYYXXP9gzPPt8rQ==/lib/arm64/libc++_shared.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
2022-11-13 18:12:53.919 31443-31443 threaded_app            net.minetest.minetest                V  Creating: 0xb400007063556a50
2022-11-13 18:12:53.920 31443-31477 threaded_app            net.minetest.minetest                V  Config: mcc=310 mnc=260 lang=en cnt=US orien=2 touch=3 dens=288 keys=1 nav=1 keysHid=3 navHid=0 sdk=30 size=2 long=2 modetype=1 modenight=2
2022-11-13 18:12:53.937 31443-31443 threaded_app            net.minetest.minetest                V  Start: 0xb400007063556a50
2022-11-13 18:12:53.938 31443-31477 Minetest                net.minetest.minetest                I  2022-11-13 18:12:53: [Main]: Automatically selecting world at [/storage/emulated/0/Android/data/net.minetest.minetest/files/Minetest/worlds/Test]
2022-11-13 18:12:53.939 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Initializing library v1.21.1-unknown UNKNOWN
2022-11-13 18:12:53.939 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Supported backends: opensl, null
2022-11-13 18:12:53.939 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Loading config /etc/openal/alsoft.conf...
2022-11-13 18:12:53.939 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Loading config /etc/xdg/alsoft.conf...
2022-11-13 18:12:53.939 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Got binary: /system/bin, app_process64
2022-11-13 18:12:53.939 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Loading config /system/bin/alsoft.conf...
2022-11-13 18:12:53.939 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key disable-cpu-exts not found
2022-11-13 18:12:53.939 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Extensions: +NEON
2022-11-13 18:12:53.939 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key rt-prio not found
2022-11-13 18:12:53.939 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key resampler not found
2022-11-13 18:12:53.939 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key trap-al-error not found
2022-11-13 18:12:53.939 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key trap-alc-error not found
2022-11-13 18:12:53.940 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key reverb/boost not found
2022-11-13 18:12:53.940 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key drivers not found
2022-11-13 18:12:53.940 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Initialized backend "opensl"
2022-11-13 18:12:53.940 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Added "opensl" for playback
2022-11-13 18:12:53.940 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Added "opensl" for capture
2022-11-13 18:12:53.940 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key excludefx not found
2022-11-13 18:12:53.940 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key default-reverb not found
2022-11-13 18:12:53.941 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key channels not found
2022-11-13 18:12:53.941 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key sample-type not found
2022-11-13 18:12:53.941 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key frequency not found
2022-11-13 18:12:53.941 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key period_size not found
2022-11-13 18:12:53.941 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key periods not found
2022-11-13 18:12:53.941 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key sources not found
2022-11-13 18:12:53.941 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key slots not found
2022-11-13 18:12:53.941 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key sends not found
2022-11-13 18:12:53.941 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key ambi-format not found
2022-11-13 18:12:53.941 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Created device 0xb400007183576270, "OpenSL"
2022-11-13 18:12:53.941 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key hrtf not found
2022-11-13 18:12:53.941 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Pre-reset: Stereo, Float32, 44100hz, 882 / 2646 buffer
2022-11-13 18:12:53.950 31443-31477 netest.minetes          net.minetest.minetest                D  PlayerBase::PlayerBase()
2022-11-13 18:12:53.950 31443-31477 netest.minetes          net.minetest.minetest                D  TrackPlayerBase::TrackPlayerBase()
2022-11-13 18:12:53.950 31443-31477 libOpenSLES             net.minetest.minetest                I  Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
2022-11-13 18:12:53.960 31443-31477 AudioTrack              net.minetest.minetest                D  createTrack_l(): RelativeVolumeFeature, mStreamType 3, streamType 3, attributes: usage=0 content=0 flags=0x0 tags=[], percentage=1.000000 clientId=91
2022-11-13 18:12:53.961 31443-31477 AudioTrack              net.minetest.minetest                D  createTrack_l(0): AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 1772
2022-11-13 18:12:53.961 31443-31477 AudioTrack              net.minetest.minetest                D  createTrack_l: RelativeVolumeFeature, mRelativePercentage:1.000000
2022-11-13 18:12:53.963 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Post-reset: Stereo, Int16, 44100hz, 882 / 2646 buffer
2022-11-13 18:12:53.963 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key stereo-mode not found
2022-11-13 18:12:53.963 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key cf_level not found
2022-11-13 18:12:53.963 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key stereo-encoding not found
2022-11-13 18:12:53.963 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Stereo rendering
2022-11-13 18:12:53.963 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Channel config, Main: 3, Real: 2
2022-11-13 18:12:53.963 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Allocating 5 channels, 20480 bytes
2022-11-13 18:12:53.963 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Enabling single-band first-order ambisonic decoder
2022-11-13 18:12:53.963 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Max sources: 256 (255 + 1), effect slots: 64, sends: 2
2022-11-13 18:12:53.963 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key dither not found
2022-11-13 18:12:53.963 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key dither-depth not found
2022-11-13 18:12:53.964 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Dithering enabled (16-bit, 32768)
2022-11-13 18:12:53.964 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key output-limiter not found
2022-11-13 18:12:53.964 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Output limiter enabled, -0.0005dB limit
2022-11-13 18:12:53.964 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Fixed device latency: 997732ns
2022-11-13 18:12:53.965 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Increasing allocated voices to 256
2022-11-13 18:12:53.966 31443-31480 openal                  net.minetest.minetest                E  [ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
2022-11-13 18:12:53.967 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Key volume-adjust not found
2022-11-13 18:12:53.967 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Created context 0xb4000070935475f0
2022-11-13 18:12:53.971 31443-31477 threaded_app            net.minetest.minetest                V  activityState=10
2022-11-13 18:12:53.973 31443-31443 threaded_app            net.minetest.minetest                V  Resume: 0xb400007063556a50
2022-11-13 18:12:53.974 31443-31477 threaded_app            net.minetest.minetest                V  activityState=11
2022-11-13 18:12:53.995 31443-31443 threaded_app            net.minetest.minetest                V  InputQueueCreated: 0xb400007063556a50 -- 0xb400007073579e90
2022-11-13 18:12:53.996 31443-31477 threaded_app            net.minetest.minetest                V  APP_CMD_INPUT_CHANGED
2022-11-13 18:12:53.996 31443-31477 threaded_app            net.minetest.minetest                V  Attaching input queue to looper
2022-11-13 18:12:54.028 31443-31443 threaded_app            net.minetest.minetest                V  NativeWindowCreated: 0xb400007063556a50 -- 0xb4000071235606d0
2022-11-13 18:12:54.028 31443-31477 threaded_app            net.minetest.minetest                V  APP_CMD_INIT_WINDOW
2022-11-13 18:12:54.029 31443-31443 threaded_app            net.minetest.minetest                V  NativeWindowResized: 0xb400007063556a50 -- 0xb4000071235606d0
2022-11-13 18:12:54.030 31443-31443 threaded_app            net.minetest.minetest                V  ContentRectChanged: l=0,t=0,r=1600,b=720
2022-11-13 18:12:54.033 31443-31443 threaded_app            net.minetest.minetest                V  NativeWindowRedrawNeeded: 0xb400007063556a50 -- 0xb4000071235606d0
2022-11-13 18:12:54.038 31443-31477 AdrenoGLES-0            net.minetest.minetest                I  QUALCOMM build                   : 704ecd9a2b, Ib3f3e69395
                                                                                                    Build Date                       : 12/29/20
                                                                                                    OpenGL ES Shader Compiler Version: EV031.32.02.06
                                                                                                    Local Branch                     : 
                                                                                                    Remote Branch                    : 
                                                                                                    Remote Branch                    : 
                                                                                                    Reconstruct Branch               : 
2022-11-13 18:12:54.038 31443-31477 AdrenoGLES-0            net.minetest.minetest                I  Build Config                     : S P 10.0.7 AArch64
2022-11-13 18:12:54.038 31443-31477 AdrenoGLES-0            net.minetest.minetest                I  Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2022-11-13 18:12:54.073 31443-31443 threaded_app            net.minetest.minetest                V  NativeWindowRedrawNeeded: 0xb400007063556a50 -- 0xb4000071235606d0
2022-11-13 18:12:54.078 31443-31443 threaded_app            net.minetest.minetest                V  WindowFocusChanged: 0xb400007063556a50 -- 1
2022-11-13 18:12:54.146 31443-31477 AdrenoGLES-0            net.minetest.minetest                I  PFP: 0x016ee190, ME: 0x00000000
2022-11-13 18:12:54.322 31443-31477 Adreno-UNKNOWN          net.minetest.minetest                E  <glTexParameteriv:151>: GL_INVALID_ENUM
2022-11-13 18:12:59.624 31443-31477 threaded_app            net.minetest.minetest                V  New input event: type=2
2022-11-13 18:12:59.625 31443-31477 threaded_app            net.minetest.minetest                V  New input event: type=2
2022-11-13 18:12:59.695 31443-31477 threaded_app            net.minetest.minetest                V  New input event: type=2
2022-11-13 18:12:59.695 31443-31477 threaded_app            net.minetest.minetest                V  New input event: type=2
2022-11-13 18:13:00.407 31443-31477 threaded_app            net.minetest.minetest                V  New input event: type=2
2022-11-13 18:13:00.460 31443-31477 threaded_app            net.minetest.minetest                V  New input event: type=2
2022-11-13 18:13:01.518 31443-31477 Minetest                net.minetest.minetest                W  2022-11-13 18:13:01: ACTION[Main]: World at [/storage/emulated/0/Android/data/net.minetest.minetest/files/Minetest/worlds/Test]
2022-11-13 18:13:01.518 31443-31477 Minetest                net.minetest.minetest                W  2022-11-13 18:13:01: ACTION[Main]: Server for gameid="minetest" listening on 0.0.0.0:63975.
2022-11-13 18:13:01.571 31443-31477 Minetest                net.minetest.minetest                W  2022-11-13 18:13:01: ACTION[Main]: Server: Shutting down
2022-11-13 18:13:02.000 31443-31477 netest.minetes          net.minetest.minetest                D  PlayerBase::stop() from IPlayer
2022-11-13 18:13:02.000 31443-31477 AudioTrack              net.minetest.minetest                D  stop(711): called with 354564 frames delivered
2022-11-13 18:13:02.001 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Freeing context 0xb4000070935475f0
2022-11-13 18:13:02.001 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Freed 1 context property object
2022-11-13 18:13:02.001 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Freed 0 AuxiliaryEffectSlot property objects
2022-11-13 18:13:02.001 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Freed 0 voice property objects
2022-11-13 18:13:02.001 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Freed 1 listener property object
2022-11-13 18:13:02.002 31443-31477 openal                  net.minetest.minetest                D  [ALSOFT] (II) Freeing device 0xb400007183576270
2022-11-13 18:13:02.002 31443-31477 AudioTrack              net.minetest.minetest                D  ~AudioTrack(): RelativeVolumeFeature mSessionId:6777, clientId:91
2022-11-13 18:13:02.006 31443-31477 Minetest                net.minetest.minetest                E  2022-11-13 18:13:02: ERROR[Main]: Uncaught exception in main thread: 
2022-11-13 18:13:02.062 31443-31443 threaded_app            net.minetest.minetest                V  Pause: 0xb400007063556a50
---------------------------- PROCESS ENDED (31443) for package net.minetest.minetest ----------------------------
2022-11-13 18:13:02.287 31443-31477 BpBinder                net.minetest.minetest                I  onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
2022-11-13 18:13:02.287 31443-31477 BpBinder                net.minetest.minetest                I  onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
2022-11-13 18:13:02.296 31443-31477 BpBinder                net.minetest.minetest                I  onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
```

**Comment by Anonymous1231-dev** [comment] 2022-11-14 09:34
I face the same ploblem.

**Comment by MisterE123** [comment] 2022-11-17 23:18
This very well could be the same bug as in https://github.com/minetest/minetest/issues/12962
However, there are slight differences as described in that issue. Anyone tackling this bug (It should be tackled before the next release because it makes Minetest useless on android) should probably look at few other details in that issue as well.

**Comment by oong819** [comment] 2022-11-24 15:57
> This very well could be the same bug as in #12962 However, there are slight differences as described in that issue. Anyone tackling this bug (It should be tackled before the next release because it makes Minetest useless on android) should probably look at few other details in that issue as well.
> 
> If a potential fix is made, feel free to ping me to test it on Android 11

probally fixed? in this comment someome tested a pr on a smartphone with Android 6.0.1 (same as mine), im not tested yet

**Comment by TurkeyMcMac** [comment] 2022-11-24 17:11
Could you set "debug_log_level" to "trace" in the settings? Then could you try opening a world again and show the resulting log?

**Comment by AbduSharif** [comment] 2022-11-24 17:22
This isn't fixed.

**Comment by oong819** [comment] 2022-11-24 17:32
> Could you set "debug_log_level" to "trace" in the settings? Then could you try opening a world again and show the resulting log?

ok but probally tommorow i need to sleep now and sign the apk so annoying sorry

**Comment by TurkeyMcMac** [comment] 2022-11-24 21:42
Here is a section of `debug.txt`:

<details>
<summary><code>debug.txt</code></summary>
<pre>
2022-11-24 16:25:24: ACTION[Main]: World at [.../worlds/world1]
2022-11-24 16:25:24: ACTION[Main]: Server for gameid="labyrinth" listening on 0.0.0.0:64982.
2022-11-24 16:25:24: INFO[Main]: SourceImageCache::getOrLoad(): Loading path ".../textures/base/pack/joystick_off.png"
2022-11-24 16:25:24: INFO[Main]: SourceImageCache::getOrLoad(): Loading path ".../textures/base/pack/joystick_bg.png"
2022-11-24 16:25:24: INFO[Main]: SourceImageCache::getOrLoad(): Loading path ".../textures/base/pack/joystick_center.png"
2022-11-24 16:25:24: INFO[Main]: SourceImageCache::getOrLoad(): Loading path ".../textures/base/pack/jump_btn.png"
2022-11-24 16:25:24: INFO[Main]: SourceImageCache::getOrLoad(): Loading path ".../textures/base/pack/down.png"
2022-11-24 16:25:24: INFO[Main]: SourceImageCache::getOrLoad(): Loading path ".../textures/base/pack/zoom.png"
2022-11-24 16:25:24: INFO[Main]: SourceImageCache::getOrLoad(): Loading path ".../textures/base/pack/aux1_btn.png"
2022-11-24 16:25:24: INFO[Main]: SourceImageCache::getOrLoad(): Loading path ".../textures/base/pack/gear_icon.png"
2022-11-24 16:25:24: INFO[Main]: SourceImageCache::getOrLoad(): Loading path ".../textures/base/pack/fly_btn.png"
2022-11-24 16:25:24: INFO[Main]: SourceImageCache::getOrLoad(): Loading path ".../textures/base/pack/noclip_btn.png"
2022-11-24 16:25:24: INFO[Main]: SourceImageCache::getOrLoad(): Loading path ".../textures/base/pack/fast_btn.png"
2022-11-24 16:25:24: INFO[Main]: SourceImageCache::getOrLoad(): Loading path ".../textures/base/pack/debug_btn.png"
2022-11-24 16:25:24: INFO[Main]: SourceImageCache::getOrLoad(): Loading path ".../textures/base/pack/camera_btn.png"
2022-11-24 16:25:24: INFO[Main]: Audio: Deinitializing...
2022-11-24 16:25:24: INFO[Main]: Audio: Deinitialized.
2022-11-24 16:25:24: INFO[Main]: Server: Saving players
2022-11-24 16:25:24: INFO[Main]: Server: Kicking players
2022-11-24 16:25:24: ACTION[Main]: Server: Shutting down
2022-11-24 16:25:24: INFO[Main]: Executing shutdown hooks
2022-11-24 16:25:24: INFO[Main]: Server: Saving environment metadata
2022-11-24 16:25:24: INFO[Main]: Server: Stopping and waiting threads
2022-11-24 16:25:24: INFO[Main]: Server: Threads stopped
2022-11-24 16:25:24: VERBOSE[Main]: virtual ServerMap::~ServerMap()
2022-11-24 16:25:24: INFO[Main]: ServerMap: Saved map to .../worlds/world1
2022-11-24 16:25:24: INFO[Main]: BanManager: saving to .../worlds/world1/ipban.txt
2022-11-24 16:25:24: INFO[Main]: Server: Deinitializing scripting
2022-11-24 16:25:24: INFO[Main]: ~TextureSource() before cleanup: 19 after: 4
2022-11-24 16:25:24: ERROR[Main]: Some exception: ""
</pre>
</details>

This makes it seems like the error occurs after loading `camera_btn.png` and before loading `rangeview_btn.png` (the next image in the sequence, see `src/gui/touchscreengui.cpp`.)

**Comment by TurkeyMcMac** [comment] 2022-11-25 12:19
I just applied this patch and now the world opens successfully:

```patch
commit c430f092645b1c58c3dd64e65a507975db84026a
Author: Jude Melton-Houghton <jwmhjwmh@gmail.com>
Date:   Fri Nov 25 07:02:42 2022 -0500

    Try removing camera_btn and later

diff --git a/src/gui/touchscreengui.cpp b/src/gui/touchscreengui.cpp
index 70f1c5163..140014bb7 100644
--- a/src/gui/touchscreengui.cpp
+++ b/src/gui/touchscreengui.cpp
@@ -542,9 +542,11 @@ void TouchScreenGUI::init(ISimpleTextureSource *tsrc)
 	m_settingsbar.addButton(noclip_id,  L"noclip",    "noclip_btn.png");
 	m_settingsbar.addButton(fast_id,    L"fast",      "fast_btn.png");
 	m_settingsbar.addButton(debug_id,   L"debug",     "debug_btn.png");
+#if 0
 	m_settingsbar.addButton(camera_id,  L"camera",    "camera_btn.png");
 	m_settingsbar.addButton(range_id,   L"rangeview", "rangeview_btn.png");
 	m_settingsbar.addButton(minimap_id, L"minimap",   "minimap_btn.png");
+#endif
 
 	// Chat is shown by default, so chat_hide_btn.png is shown first.
 	m_settingsbar.addToggleButton(toggle_chat_id, L"togglechat",
```

You can download the patched APK here: https://github.com/TurkeyMcMac/minetest/actions/runs/3547781361

**Comment by TurkeyMcMac** [comment] 2022-11-25 13:16
I believe the bug was caused by 59601eb9229032f8126f9ff11598faf25357ca44.

**Comment by sfan5** [comment] 2022-11-25 13:16
that's #12792

**Comment by TurkeyMcMac** [comment] 2022-11-25 13:30
I think this is a duplicate then.

**Comment by TurkeyMcMac** [comment] 2022-11-25 13:43
Duplicate of https://github.com/minetest/minetest/issues/12792.

**Closed by TurkeyMcMac** 2022-11-25 13:43 UTC
Labels: Bug, Duplicate, Android, Possible close, @ Mainmenu, Regression
