### ISSUE TITLE
Try to do more computing with GPU (Such as lighting, moving, borders and so on)

### ISSUE THREAD

**Issue by Pevernow** [minetest/minetest#10442] opened 2020-09-29 01:27 UTC
## Problem

My computer CPU is Intel i5-2410m

This CPU is bad. Even if the line of sight is set to 60 and the frame rate upper limit is 25, the CPU temperature will rise to more than 90 degrees.

But it has a working GPU (NVIDIA GT 540M) that uses less than 20% each time

## Solutions

If we can use glsl to move more computation to GPU,

Maybe it will make the game run more smoothly

**Comment by Pevernow** [comment] 2020-09-29 01:30
Minetest was originally created for low-end computers

But now it can't run smoothly on low-end computers (25 FPS, 60 view range)

Minecraft 1.7 can keep 30fps running on my computer

But minetest 5.3.0 can't keep the speed of 30fps

**Comment by LoneWolfHT** [comment] 2020-09-29 03:07
I've heard complaints about the speed of latest Minetest versions. May have just been a bad GPU though

**Comment by SmallJoker** [comment] 2020-09-29 17:42
-- you already reported this issue for the same system #9439 --

This is pretty strange. I can reach 12 FPS with a laptop that has a cpubenchmark.net score of 1/5th of yours. 60 FPS should be well within reach, given the drivers are correctly set up and the system is cooled properly.
If you're using Linux, you could also try to compare the proprietary and nouveau drivers - usually former results in slightly better performance, though.

_Comparable system:_
Core2 Duo E8500, GTX 550 Ti
https://www.cpubenchmark.net/compare/Intel-i5-2410M-vs-Intel-Core2-Duo-E8500/796vs5
https://www.videocardbenchmark.net/compare/GeForce-GT-540M-vs-GeForce-GTX-550-Ti/27vs16
-> 134 FPS, 80 view range, shaders on, raw mapgen landscape
-> 41 FPS, 80 view range, shaders on, "Blocky Survival" server spawn
The graphics card is better, though according to your statement this should not matter.

**Comment by paramat** [comment] 2020-09-29 18:07
See the other issue, especially this comment https://github.com/minetest/minetest/issues/9439#issuecomment-593068316
> This issue seems to be about a particular machine which should perform way better than it actually does.
[...]
Closing because this performance issue is only one particular machine which should be well capable reaching 60 FPS using the default settings.

The fact that MC runs much better for you than MT also indicates some problem unique to you. If this is the case, you are basing your request on your personal situation, not a general one, so it is not really a justified request.
If this is indeed a recent severe drop in MT perfomance then it should be attended to in a different issue, moving stuff to GPU (which is very non-trivial to do) is not the solution to that.
Generally, MT is reported to work well on lower power devices.

Perhaps you have some non-shader settings set wrongly, or are using insanely intensive mods in singleplayer or very large numbers of them.
Have you tried just running MTG with no added mods, as asked in the other issue?

This issue should probably be closed in a few days.

**Comment by Pevernow** [comment] 2020-09-30 00:59
I played on a server.

No Lua code should be executed on the client

But the CPU utilization is still very high

It's only possible that there's something wrong with the rendered code

**Comment by Pevernow** [comment] 2020-09-30 01:02
> -- you already reported this issue for the same system #9439 --
> 
> This is pretty strange. I can reach 12 FPS with a laptop that has a cpubenchmark.net score of 1/5th of yours. 60 FPS should be well within reach, given the drivers are correctly set up and the system is cooled properly.
> If you're using Linux, you could also try to compare the proprietary and nouveau drivers - usually former results in slightly better performance, though.
> 
> _Comparable system:_
> Core2 Duo E8500, GTX 550 Ti
> https://www.cpubenchmark.net/compare/Intel-i5-2410M-vs-Intel-Core2-Duo-E8500/796vs5
> https://www.videocardbenchmark.net/compare/GeForce-GT-540M-vs-GeForce-GTX-550-Ti/27vs16
> -> 134 FPS, 80 view range, shaders on, raw mapgen landscape
> -> 41 FPS, 80 view range, shaders on, "Blocky Survival" server spawn
> The graphics card is better, though according to your statement this should not matter.

What I use is a laptop

It may not heat well

Does minetest support laptops badly?

**Comment by lhofhansl** [comment] 2020-10-04 21:54
Despite the multiple issues filed for the same problem - there is a problem here.

It has bothered me quite a lot that mods with Lua code can easily reduce the FPS to 10 or less, for example many ABMs or Entities (collision detection, etc) can cause that. The rendering of the scene should be completely decoupled from the Lua code. When Lua code is slow, ABMs and Entities should slow down, but not the rendering of the scene.
(I can usually get a few 100 FPS on my machine.)

I've tried to address some of this by adding (or smoothing) various time budgets to the Lua code (mostly the ABM handler), but that's a bit like putting lipstick on a pig :)

Perhaps Lua code can output its map changes to a queue (and all in a separate thread) and we play the queue from the main thread, same for Entities, etc. It's not simple... But I fear we'll never fix this unless we make some more radical changes.
The main obstacle to multi-threaded Lua is the lack of locking in the Map code. It's very hard to retrofit - I think the Freeminer folks tried.

(This particular issue might just be an old computer, and, frankly, at some point we should just require and expect some minimally modern machine - but that does not mean there are not issues we should address that even slow down fast machines.)

Just my $0.02.

**Comment by rubenwardy** [comment] 2020-10-04 21:59
ABMs run on the server, rendering runs on the client. If Lua is slowing down the client that much, there's something wrong

**Comment by lhofhansl** [comment] 2020-10-04 22:39
You are right of course. It seems I was confused. :(

The collision code runs on client and server, though. I suppose that's the main culprit then.

**Comment by paramat** [comment] 2020-10-06 14:17
> I played on a server.

Please test unmodded MTG, as suggested, to see if that makes a difference.
> What I use is a laptop
It may not heat well
Does minetest support laptops badly?

MT can run fine on low power devices as long as you configure it correctly. Laptops are not necessarily low power devices.

Closing as vague, the performance problem is unconfirmed and probably a user-specific situation.
The GPU request is therefore foundationless.

**Closed by paramat** 2020-10-06 14:17 UTC
Labels: Duplicate, Performance, Possible close, Request / Suggestion
