### ISSUE TITLE
Error related to entities pos = nil

### ISSUE THREAD

**Issue by darnuria** [minetest/minetest#9723] opened 2020-04-21 18:43 UTC
First thanks for the game :)

##### Minetest version

Version affected: compiled on Ubuntu 18.04 g++ 8.4.0 
sha 338195ff250bd7552ef8167348de2eb05e421c29

Version non affected 5.2.0-stable

##### OS / Hardware

CPU: Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz

##### Summary

When using some mod or games like mineclone2 I got an error related to entities

I wrote an issue on mineclone bug tracker but it affected other mods with entity and was not present in 5.2.0 so I wrote a bug here.

##### Steps to reproduce

- Compile master mindtest
- launch the game
-  add minclone2 from content browser
- select it create world interact with entity like falling gravel or water droplet may trigger without player interraction.

The bug is reproducible on multiple world creation.

##### Logs and attempt to find the bug

```
2020-04-19 23:07:47: ACTION[Main]: hb.register_hudbar: health
2020-04-19 23:07:47: ACTION[Main]: hb.register_hudbar: breath
2020-04-19 23:07:47: ACTION[Main]: hb.register_hudbar: hunger
2020-04-19 23:07:47: ACTION[Main]: [doc] doc.mt opened.
2020-04-19 23:07:47: ACTION[Main]: [doc] doc.mt successfully read.
2020-04-19 23:07:47: ACTION[Main]: hb.register_hudbar: armor
2020-04-19 23:07:47: ACTION[Main]: [mcl_weather] Weather restored.
2020-04-19 23:07:47: ACTION[Main]: [mcl_skins] Mod initialized with 1 custom skin(s)
        .__               __                   __   
  _____ |__| ____   _____/  |_  ____   _______/  |_ 
 /     \|  |/    \_/ __ \   __\/ __ \ /  ___/\   __\
|  Y Y  \  |   |  \  ___/|  | \  ___/ \___ \  |  |  
|__|_|  /__|___|  /\___  >__|  \___  >____  > |__|  
      \/        \/     \/          \/     \/        
2020-04-19 23:07:50: ACTION[Main]: World at [/home/darnuria/Games/minetest/bin/../worlds/test3]
2020-04-19 23:07:50: ACTION[Main]: Server for gameid="mineclone2" listening on 0.0.0.0:59276.
2020-04-19 23:07:55: ACTION[Server]: singleplayer [127.0.0.1] joins game. List of players: singleplayer
2020-04-19 23:07:55: ACTION[Server]: [mcl_skins] Player skin for singleplayer set to skin #1
2020-04-19 23:07:58: ACTION[Server]: singleplayer places node mcl_core:gravel at (8,-7,-35)
2020-04-19 23:08:00: ACTION[Server]: singleplayer digs mcl_core:gravel at (8,-7,-35)
2020-04-19 23:08:00: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'mcl_void_damage' in callback environment_Step(): ...in/../games/mineclone2/mods/CORE/mcl_worlds/init.lua:8: attempt to index local 'pos' (a nil value)
2020-04-19 23:08:00: ERROR[Main]: stack traceback:
2020-04-19 23:08:00: ERROR[Main]: 	...in/../games/mineclone2/mods/CORE/mcl_worlds/init.lua:8: in function 'is_in_void'
2020-04-19 23:08:00: ERROR[Main]: 	...mineclone2/mods/ENVIRONMENT/mcl_void_damage/init.lua:13: in function '?'
2020-04-19 23:08:00: ERROR[Main]: 	...uria/Games/minetest/bin/../builtin/game/register.lua:429: in function <...uria/Games/minetest/bin/../builtin/game/register.lua:413>
2020-04-19 23:08:00: ERROR[Main]: stack traceback:
2020-04-19 23:08:00: ACTION[Server]: [doc] Wrote player data into /home/darnuria/Games/minetest/bin/../worlds/test3/doc.mt.
2020-04-19 23:08:00: ACTION[Server]: singleplayer leaves game. List of players: 
2020-04-19 23:08:00: WARNING[Server]: ScriptApiBase::objectrefGetOrCreate(): Pushing ObjectRef to removed/deactivated object, this is probably a bug.
2020-04-19 23:08:01: ACTION[Main]: Server: Shutting down
2020-04-19 23:08:01: ACTION[Main]: [doc] Server shuts down. Player data is about to be saved.
```
[mineclone2/mods/CORE/mcl_worlds/init.lua#L8](https://git.minetest.land/Wuzzy/MineClone2/src/branch/master/mods/CORE/mcl_worlds/init.lua#L8)
[mineclone2/mods/ENVIRONMENT/mcl_void_damage/init.lua#L12](https://git.minetest.land/Wuzzy/MineClone2/src/branch/master/mods/ENVIRONMENT/mcl_void_damage/init.lua#L12)
[minetest/builtin/game/register.lua#429](https://github.com/minetest/minetest/blob/master/builtin/game/register.lua#L429)

It may help I added some print debugging to trace the problem (I am not a lua develloper sorry if there is better way to do) in [mineclone2/mods/ENVIRONMENT/mcl_void_damage/init.lua#L12](https://git.minetest.land/Wuzzy/MineClone2/src/branch/master/mods/ENVIRONMENT/mcl_void_damage/init.lua#L12)

```lua
minetest.register_globalstep(function(dtime)
	voidtimer = voidtimer + dtime
	if voidtimer > 0.5 then
		voidtimer = 0
		local objs = minetest.object_refs
		local enable_damage = minetest.settings:get_bool("enable_damage")
		for id, obj in pairs(objs) do
			print(string.format("ID:<%s> obj: ", id))
			print(obj)
			print(obj:get_entity_name())
			local pos = obj:get_pos()
            ...
```

If useful two log of the run and the last entity before the crash:
```
ID:<1> obj: 
userdata: 0x7fbd3bf30df8

ID:<1> obj: 
userdata: 0x7fbd3bf30df8

ID:<1> obj: 
userdata: 0x7fbd3bf30df8

ID:<1> obj: 
userdata: 0x7fbd3bf30df8

ID:<1> obj: 
userdata: 0x7fbd3bf30df8

ID:<1> obj: 
userdata: 0x7fbd3bf30df8

ID:<1> obj: 
userdata: 0x7fbd3bf30df8

ID:<1> obj: 
userdata: 0x7fbd3bf30df8

ID:<1> obj: 
userdata: 0x7fbd3bf30df8

ID:<2> obj: 
userdata: 0x7fbcfee20818
mcl_minecarts:minecart
ID:<1> obj: 
userdata: 0x7fbd3bf30df8

ID:<1> obj: 
userdata: 0x7fbd3bf30df8

ID:<1> obj: 
userdata: 0x7fbd3bf30df8

ID:<3> obj: 
userdata: 0x7fbcff0c7d98
mcl_mobspawners:doll
ID:<1> obj: 
userdata: 0x7fbd3bf30df8

ID:<1> obj: 
userdata: 0x7fbd3bf30df8

2020-04-19 23:00:42: ACTION[Server]: singleplayer digs mcl_flowers:poppy at (-19,21,-26)
ID:<1> obj: 
userdata: 0x7fbd3bf30df8

ID:<2> obj: 
userdata: 0x7fbd0c1d0ad8
__builtin:item
ID:<5> obj: 
userdata: 0x7fbd463bb908
mcl_mobspawners:doll
ID:<1> obj: 
userdata: 0x7fbd3bf30df8

ID:<2> obj: 
userdata: 0x7fbd0c1d0ad8
```
```
//// way before crash ////
ID:<8> obj: 
userdata: 0x7fc60440eb58
drippingwater:drop_water
[....]
/// Right before the crash ///
ID:<8> obj: 
userdata: 0x7fc60440eb58

/// Crash ///
```

```
ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<2> obj: 
userdata: 0x7fc604af70c8
drippingwater:drop_water
ID:<3> obj: 
userdata: 0x7fc6046577f8
drippingwater:drop_water
ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<2> obj: 
userdata: 0x7fc604af70c8
drippingwater:drop_water
ID:<3> obj: 
userdata: 0x7fc6046577f8
drippingwater:drop_water
ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<2> obj: 
userdata: 0x7fc604af70c8
drippingwater:drop_water
ID:<3> obj: 
userdata: 0x7fc6046577f8
drippingwater:drop_water
ID:<4> obj: 
userdata: 0x7fc5a76be708
mcl_minecarts:minecart
ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<2> obj: 
userdata: 0x7fc604af70c8
drippingwater:drop_water
ID:<3> obj: 
userdata: 0x7fc6046577f8
drippingwater:drop_water
ID:<4> obj: 
userdata: 0x7fc604230a88
drippingwater:drop_water
ID:<5> obj: 
userdata: 0x7fc60424ad38
drippingwater:drop_water
ID:<6> obj: 
userdata: 0x7fc604270438
drippingwater:drop_water
ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<2> obj: 
userdata: 0x7fc604af70c8
drippingwater:drop_water
ID:<3> obj: 
userdata: 0x7fc6046577f8
drippingwater:drop_water
ID:<4> obj: 
userdata: 0x7fc604230a88
drippingwater:drop_water
ID:<5> obj: 
userdata: 0x7fc60424ad38
drippingwater:drop_water
ID:<6> obj: 
userdata: 0x7fc604270438
drippingwater:drop_water
ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<2> obj: 
userdata: 0x7fc604af70c8
drippingwater:drop_water
ID:<3> obj: 
userdata: 0x7fc6046577f8
drippingwater:drop_water
ID:<4> obj: 
userdata: 0x7fc604230a88
drippingwater:drop_water
ID:<5> obj: 
userdata: 0x7fc60424ad38
drippingwater:drop_water
ID:<6> obj: 
userdata: 0x7fc604270438
drippingwater:drop_water
ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<2> obj: 
userdata: 0x7fc604af70c8
drippingwater:drop_water
ID:<3> obj: 
userdata: 0x7fc6046577f8
drippingwater:drop_water
ID:<4> obj: 
userdata: 0x7fc604230a88
drippingwater:drop_water
ID:<5> obj: 
userdata: 0x7fc60424ad38
drippingwater:drop_water
ID:<6> obj: 
userdata: 0x7fc604270438
drippingwater:drop_water
ID:<7> obj: 
userdata: 0x7fc604657728
drippingwater:drop_water
ID:<8> obj: 
userdata: 0x7fc60440eb58
drippingwater:drop_water
ID:<9> obj: 
userdata: 0x7fc604422dc8
drippingwater:drop_water
ID:<10> obj: 
userdata: 0x7fc604424ba8
drippingwater:drop_water
ID:<11> obj: 
userdata: 0x7fc604448928
drippingwater:drop_water
ID:<12> obj: 
userdata: 0x7fc60444ab38
drippingwater:drop_water
ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<2> obj: 
userdata: 0x7fc604af70c8
drippingwater:drop_water
ID:<3> obj: 
userdata: 0x7fc6046577f8
drippingwater:drop_water
ID:<4> obj: 
userdata: 0x7fc604230a88
drippingwater:drop_water
ID:<5> obj: 
userdata: 0x7fc60424ad38
drippingwater:drop_water
ID:<6> obj: 
userdata: 0x7fc604270438
drippingwater:drop_water
ID:<7> obj: 
userdata: 0x7fc604657728
drippingwater:drop_water
ID:<8> obj: 
userdata: 0x7fc60440eb58
drippingwater:drop_water
ID:<9> obj: 
userdata: 0x7fc604422dc8
drippingwater:drop_water
ID:<10> obj: 
userdata: 0x7fc604424ba8
drippingwater:drop_water
ID:<11> obj: 
userdata: 0x7fc604448928
drippingwater:drop_water
ID:<12> obj: 
userdata: 0x7fc60444ab38
drippingwater:drop_water
ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<2> obj: 
userdata: 0x7fc604af70c8
drippingwater:drop_water
ID:<3> obj: 
userdata: 0x7fc6046577f8
drippingwater:drop_water
ID:<4> obj: 
userdata: 0x7fc604230a88
drippingwater:drop_water
ID:<5> obj: 
userdata: 0x7fc60424ad38
drippingwater:drop_water
ID:<6> obj: 
userdata: 0x7fc604270438
drippingwater:drop_water
ID:<7> obj: 
userdata: 0x7fc604657728
drippingwater:drop_water
ID:<8> obj: 
userdata: 0x7fc60440eb58
drippingwater:drop_water
ID:<9> obj: 
userdata: 0x7fc604422dc8
drippingwater:drop_water
ID:<10> obj: 
userdata: 0x7fc604424ba8
drippingwater:drop_water
ID:<11> obj: 
userdata: 0x7fc604448928
drippingwater:drop_water
ID:<12> obj: 
userdata: 0x7fc60444ab38
drippingwater:drop_water
ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<2> obj: 
userdata: 0x7fc604af70c8
drippingwater:drop_water
ID:<3> obj: 
userdata: 0x7fc6046577f8
drippingwater:drop_water
ID:<4> obj: 
userdata: 0x7fc604230a88
drippingwater:drop_water
ID:<5> obj: 
userdata: 0x7fc60424ad38
drippingwater:drop_water
ID:<6> obj: 
userdata: 0x7fc604270438
drippingwater:drop_water
ID:<7> obj: 
userdata: 0x7fc604657728
drippingwater:drop_water
ID:<8> obj: 
userdata: 0x7fc60440eb58
drippingwater:drop_water
ID:<9> obj: 
userdata: 0x7fc604422dc8
drippingwater:drop_water
ID:<10> obj: 
userdata: 0x7fc604424ba8
drippingwater:drop_water
ID:<11> obj: 
userdata: 0x7fc604448928
drippingwater:drop_water
ID:<12> obj: 
userdata: 0x7fc60444ab38
drippingwater:drop_water
ID:<13> obj: 
userdata: 0x7fc6041c91c8
drippingwater:drop_water
ID:<14> obj: 
userdata: 0x7fc6046ae658
drippingwater:drop_water
ID:<15> obj: 
userdata: 0x7fc60469b0f8
drippingwater:drop_water
ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<2> obj: 
userdata: 0x7fc604af70c8
drippingwater:drop_water
ID:<3> obj: 
userdata: 0x7fc6046577f8
drippingwater:drop_water
ID:<4> obj: 
userdata: 0x7fc604230a88
drippingwater:drop_water
ID:<5> obj: 
userdata: 0x7fc60424ad38
drippingwater:drop_water
ID:<6> obj: 
userdata: 0x7fc604270438
drippingwater:drop_water
ID:<7> obj: 
userdata: 0x7fc604657728
drippingwater:drop_water
ID:<8> obj: 
userdata: 0x7fc60440eb58
drippingwater:drop_water
ID:<10> obj: 
userdata: 0x7fc604424ba8
drippingwater:drop_water
ID:<11> obj: 
userdata: 0x7fc604448928
drippingwater:drop_water
ID:<12> obj: 
userdata: 0x7fc60444ab38
drippingwater:drop_water
ID:<13> obj: 
userdata: 0x7fc6041c91c8
drippingwater:drop_water
ID:<14> obj: 
userdata: 0x7fc6046ae658
drippingwater:drop_water
ID:<15> obj: 
userdata: 0x7fc60469b0f8
drippingwater:drop_water
ID:<16> obj: 
userdata: 0x7fc5956eb5b8
mcl_mobspawners:doll
ID:<17> obj: 
userdata: 0x7fc5a62c58e8
mcl_mobspawners:doll
ID:<18> obj: 
userdata: 0x7fc5a65ba978
mcl_mobspawners:doll
ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<2> obj: 
userdata: 0x7fc604af70c8
drippingwater:drop_water
ID:<3> obj: 
userdata: 0x7fc6046577f8
drippingwater:drop_water
ID:<4> obj: 
userdata: 0x7fc604230a88
drippingwater:drop_water
ID:<5> obj: 
userdata: 0x7fc60424ad38
drippingwater:drop_water
ID:<6> obj: 
userdata: 0x7fc604270438
drippingwater:drop_water
ID:<7> obj: 
userdata: 0x7fc604657728
drippingwater:drop_water
ID:<8> obj: 
userdata: 0x7fc60440eb58
drippingwater:drop_water
ID:<10> obj: 
userdata: 0x7fc604424ba8
drippingwater:drop_water
ID:<11> obj: 
userdata: 0x7fc604448928
drippingwater:drop_water
ID:<12> obj: 
userdata: 0x7fc60444ab38
drippingwater:drop_water
ID:<13> obj: 
userdata: 0x7fc6041c91c8
drippingwater:drop_water
ID:<14> obj: 
userdata: 0x7fc6046ae658
drippingwater:drop_water
ID:<15> obj: 
userdata: 0x7fc60469b0f8
drippingwater:drop_water
ID:<16> obj: 
userdata: 0x7fc5956eb5b8
mcl_mobspawners:doll
ID:<17> obj: 
userdata: 0x7fc5a62c58e8
mcl_mobspawners:doll
ID:<18> obj: 
userdata: 0x7fc5a65ba978
mcl_mobspawners:doll
ID:<19> obj: 
userdata: 0x7fc59575d038
mcl_mobspawners:doll
ID:<1> obj: 
userdata: 0x7fc604bd83a8

ID:<2> obj: 
userdata: 0x7fc604af70c8
drippingwater:drop_water
ID:<3> obj: 
userdata: 0x7fc6046577f8
drippingwater:drop_water
ID:<4> obj: 
userdata: 0x7fc604230a88
drippingwater:drop_water
ID:<5> obj: 
userdata: 0x7fc60424ad38
drippingwater:drop_water
ID:<6> obj: 
userdata: 0x7fc604270438
drippingwater:drop_water
ID:<7> obj: 
userdata: 0x7fc604657728
drippingwater:drop_water
ID:<8> obj: 
userdata: 0x7fc60440eb58
```

**Comment by sfan5** [comment] 2020-04-21 18:54
duplicate of #9528

This is a bug in `mcl_void_damage`:
It iterates the (undocumented) `minetest.object_refs` table and just assumes that every object reference is valid.

**Closed by sfan5** 2020-04-21 18:54 UTC
Labels: Unconfirmed bug

**Comment by darnuria** [comment] 2020-04-22 12:18
Hi Thanks for your time! I will forward that in mineclone2 bugtracker.
