### ISSUE TITLE
Show `/mods` Command result in a formspec

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10367] opened 2020-09-05 04:10 UTC
## Problem

 This is what you can see if you server have a lot of mods:
![screenshot_20200905_120511](https://user-images.githubusercontent.com/55009343/92297266-212a0900-ef70-11ea-9f56-a5f955b6dd16.png)
This will make my client lag and make i cant see anything.

## Solutions

Put mods info in a formspec, that include mod technical name, `name` in `mod.conf`, and description.

Also put mods in group, group can be modpack.

**Comment by Zughy** [comment] 2020-09-05 08:50
I'd add the version too

**Comment by Emojigit** [comment] 2020-09-05 08:57
I think the formspec can be like `/help` page.

**Comment by hecktest** [comment] 2020-09-05 16:57
workaround: uninstall homedecor :]

**Comment by Emojigit** [comment] 2020-09-06 00:03
> workaround: uninstall homedecor :]

I think after I uninstall homedecor, the /mods still spam half of chatroom.

Second, uninstall home decor on my server is impossible because a lot of buildings use it.

**Comment by Andrey2470T** [comment] 2020-09-06 06:47
> workaround: uninstall homedecor :]
>
... and also at least a half of the mods :)

**Comment by xenonca** [comment] 2020-09-16 12:14
Duplicate of #9563 I guess :P

**Comment by pyrollo** [comment] 2020-09-16 12:53
Closed as duplicate of #9563 (thanks Xenonca :) )

**Closed by pyrollo** 2020-09-16 12:53 UTC
Labels: Duplicate, Feature request
