### ISSUE TITLE
Glitching into blocks when jumping up since 908e762

### ISSUE THREAD

**Issue by style-nine** [minetest/minetest#9351] opened 2020-02-01 18:34 UTC
##### Minetest version

```
908e762 ("Collision temporary fix for issue #6886", 2020-01-27)
```

##### OS / Hardware

Operating system: Ubuntu 18.04
CPU: AMD FX-6300

GPU model:
OpenGL version:

##### Summary

It's relatively easy to glitch into a block, since the latest collision fix.

##### Steps to reproduce

Create a new MTG world, and try climbing up a hill. You can usually glitch into a block pretty easily by going up a 45-degree angle hill quickly.
![screenshot](https://user-images.githubusercontent.com/41269111/73597198-8825a200-44f7-11ea-8d15-188d5f02c432.jpg)

**Comment by sfan5** [comment] 2020-02-01 20:21
Some more description or perhaps a video would be nice.
I couldn't reproduce it from your description.

**Comment by style-nine** [comment] 2020-02-01 23:31
Don't expect it to work after ten seconds. You have to play with it for a minute or so, but just from playing the game normally, I can see it happen many times in a single session of just exploring.

**Comment by style-nine** [comment] 2020-02-01 23:39
I think it mainly happens when you hit the side of blocks and then jump. You don't tend to glitch into the higher block if you jump before hitting it.

**Comment by style-nine** [comment] 2020-02-02 03:00
Another thing I've noticed that may be related is that when you sleep in a bed, you glitch through the bed. That one should be way easier to test.

**Comment by style-nine** [comment] 2020-02-02 12:08
I've tested this several more times, and it's definitely something to do with 908e762. The glitch with the bed is 100% reliable on my system. You slowly sink into the object that you glitch into, so there's really no missing it.

**Comment by sorcerykid** [comment] 2020-02-02 17:18
Good catch. Ping @TheTermos to take a closer look at https://github.com/minetest/minetest/pull/9327

**Comment by TheTermos** [comment] 2020-02-02 19:09
**The bed:** My guess is the fix exposed an MTG bug. When player goes to sleep position is set so the player collisionbox intersects with the bed node box. The old code would prevent player from falling through due to false back in time collision which is otherwise harmful. 
Notice it only happens when going to sleep which resets player position, you can't glitch through the bed by jumping on it.

**Glitch into a block:** Can't say, couldn't reproduce it no matter how hard I tried doing exactly what the description says, possibly unrelated.

**Comment by LoneWolfHT** [comment] 2020-02-02 20:11
Horrible GIF, hopefully you can get the idea though. I'm holding sneak while jumping

![Glitch2](https://user-images.githubusercontent.com/28972859/73614451-034c8e00-45b4-11ea-81f5-44230711d15c.gif)

**Comment by TheTermos** [comment] 2020-02-02 21:47
@LoneWolfHT This looks like a different issue, I couldn't reproduce it either, but I think this could always happen on slow/busy machines, probably related to 'stepheight'. I believe I know why it glitches and am planning to improve it in #9343.

How are you able to climb 2 nodes, some kind of sneak glitch again?

**Comment by benrob0329** [comment] 2020-02-02 22:08
Clipping through the edge of a node is nothing new, it can happen if you hit it at just the right angle. Its usually fairly rare and easy to break out of though, so a change in that would be new.

**Comment by LoneWolfHT** [comment] 2020-02-02 22:23
Guess the GIF was too little. I've made an example video: https://youtu.be/h873ktUSXjw

**Comment by style-nine** [comment] 2020-02-02 23:26
Clipping into a stair node is nothing new, but the frequency of it happening with this fix is like 100x higher.

**Comment by LoneWolfHT** [comment] 2020-02-03 00:10
> Create a new MTG world, and try climbing up a hill. You can usually glitch into a block pretty easily by going up a 45-degree angle hill **quickly.**

I am able to reproduce this with the mentioned PR. Using fast move and running up a hill with it

**Comment by GreenXenith** [comment] 2020-02-03 00:14
> but I think this could always happen on slow/busy machines

I can reproduce both style-nine's bug and LoneWolfHT's on a very not-slow machine.

Both bugs are definitely new, I cant reproduce them in 5.1.1.

For style-nine's bug: Make a wall like this
![image](https://user-images.githubusercontent.com/24834740/73617722-a6160400-45d6-11ea-8037-0f5cac6e1528.png)
and run up or at it, and stop half way.
A **key** thing to note is you should wait for a second, as you will slowly sink through the top and fall in. Once you clip in, if you don't do a complete jump, you can stay clipped into the node and it will reproduce the slow-falling.

For LoneWolfHT's bug: Set up a small 'L' shape with 3 nodes and shift+jump into the corner of the top node. 4 out of 5 times I can clip into it.

**Comment by Fixer-007** [comment] 2020-02-03 00:31
Can reproduce by using that method in a pic above ^

**Comment by paramat** [comment] 2020-02-03 00:40
I think 908e76247922d4adf879b3996c4f75bdbb4e536d should be reverted, as fundamental changes to collision are likely to cause unforseen bugs to pop up a few weeks later, and we will soon be releasing 5.2.0. Better to wait until after and have a full release cycle to test.

Also consider that 908e76247922d4adf879b3996c4f75bdbb4e536d was a 'temporary fix' that #9343 also implements, so it seems better to just merge the real thing #9343 after release.

**Comment by paramat** [comment] 2020-02-03 00:55
I just glitched into that partial pyramid structure shown above  without even jumping, just creeping along the edges will do it.

![screenshot_20200203_004913](https://user-images.githubusercontent.com/3686677/73618367-35470a00-461f-11ea-8431-a6ffb775c099.png)

Also, simply placing a node close in front of you on a flat surface allows you to walk into it.

![screenshot_20200203_005136](https://user-images.githubusercontent.com/3686677/73618409-72130100-461f-11ea-9f7f-1ecc9584027e.png)

I also easily reproduced the glitching into the partial pyramid structure, just walk into and against one of the corners, facing diagonally, and jump once, you will walk right into the node.

These bugs are far worse than what it fixes, this commit needs to be reverted.

**Comment by TheTermos** [comment] 2020-02-03 08:18
Yup, could reproduce both.

> I think [908e762](https://github.com/minetest/minetest/commit/908e76247922d4adf879b3996c4f75bdbb4e536d) should be reverted, as fundamental changes to collision are likely to cause unforseen bugs to pop up a few weeks later, and we will soon be releasing 5.2.0. 

Looks like it should, but this was no fundamental change, just one parameter tweak. Turns out the old algorithm needs a huge margin of error, but maybe not a whopping quarter a node? How soon is 5.2.0, maybe there's time for another round with a different value?

**Comment by TheTermos** [comment] 2020-02-03 11:37
So if anyone feels like testing, I increased the d in https://github.com/TheTermos/minetest/tree/collision-temporary-fix-%236886
So far it seems to resolve the pyramid and the sneak glitch.

The bed issue is an MTG bug in beds/functions.lua in function lay_down near 95
`local p = {x = bed_pos.x + dir.x / 2, y = bed_pos.y, z = bed_pos.z + dir.z / 2}`
player pos.y is set to node center, fancy bed nodebox height is less than 0.5, so it works ok, but simple bed is higher so player is placed inside the node.

**Comment by sorcerykid** [comment] 2020-02-03 15:03
@TheTermos have you noticed this same bug cropping up with entities, or only with players? Like if you throw a bunch of __builtin_items onto that pyramid structure above, do they sink in too?

If entities are immune, then perhaps it may be possible to adapt the collision function to check the type of object being passed to it? If it's a ServerActiveObject, then it can use your new value, otherwise it defaults to the former value.

**Comment by TheTermos** [comment] 2020-02-03 16:19
> @TheTermos have you noticed this same bug cropping up with entities, or only with players? Like if you throw a bunch of __builtin_items onto that pyramid structure above, do they sink in too?

No I'm afraid entities are affected as well, all of them players, saos and caos use the exact same code.
If you threw a bunch of items onto the pyramid they would't sink, but only because there are special conditions that have to be met for this glitch to occur, which is perfect edge alignment that's extremely unlikely to happen unless a box is sliding between two nodes onto the third.

This is an inherent flaw of AxisAllignedCollision(), it can't detect edge aligned collisions whatsoever, so this is quite literally an edge case ;)
That's why I left the d nonzero, sadly I were too optimistic and set it too small. Please do try the new version, all it does is increase the d from 0.01f to 0.1f, no problems so far on my end.

**Comment by paramat** [comment] 2020-02-03 21:03
> How soon is 5.2.0, maybe there's time for another round with a different value?

5.2.0 was initially intended for Jan or Feb, however it takes a few weeks to prepare for a feature freeze, maybe a few weeks from now?
Fine to test with another value, but i still think this commit was too risky soon before a release.
Thanks for the MTG bed issue, i will attend to that.

**Comment by paramat** [comment] 2020-02-03 21:07
Although ... since the player must visually rest against the bed, it is inevitable that the player collisionbox will intersect the bed, so perhaps the fix is to make the simple bed collisionbox much lower?

**Comment by TheTermos** [comment] 2020-02-03 22:13
I get the concern, but this is an one liner changing just one parameter, and as such is easily reversible any time. Probably it's worth another shot even if it gets reverted again because of more issues with code that grew to rely on backwards collisions, at least we'll know what we're up against.

**Comment by LoneWolfHT** [comment] 2020-02-03 22:45
@TheTermos Your fix fixes the sneak glitch but not the pyramid one. I have to set `d` to `0.7f` to fix that

**Comment by TheTermos** [comment] 2020-02-04 11:58
@LoneWolfHT I couldn't reproduce the pyramid with d set to 0.1, but I know it's theoretically possible even with the old value of 2.7 given the right numbers. Thanks, you saved me the trouble of making a new PR.

Could you try and reproduce the pyramid with #9343? - that one actually modifies the algorithm in attempt to make diagonal edge collisions less likely.

**Comment by paramat** [comment] 2020-02-04 18:00
> is easily reversible any time.

Yes, we could revert it, or a new value, just before feature freeze. Lets see how testing other values progresses.

**Comment by TheTermos** [comment] 2020-02-04 20:04
> > is easily reversible any time.
> 
> Yes, we could revert it, or a new value, just before feature freeze. Lets see how testing other values progresses.

Thanks, I submitted #9365. It uses d= 0.3f which translates to 3 world centimeters, quite large already.

**Comment by sfan5** [comment] 2020-02-04 22:22
Reproduced this bug today by accident and it is indeed very obvious:
![bug](https://user-images.githubusercontent.com/1042418/73792726-2ee29a80-47a5-11ea-9343-e5c647c3cb63.gif)

**Comment by paramat** [comment] 2020-02-06 02:05
Above i reported:
> Also, simply placing a node close in front of you on a flat surface allows you to walk into it.

This may actually be an existing bug in the 'place node where you stand' feature. I need to retest but it is possible to place a node where you stand and walk into that node while facing certain directions: NW N NE E SE.

**Comment by An0n3m0us** [comment] 2020-02-09 14:06
Occurs when jumping and placing or partially breaking nodes:

![test](https://user-images.githubusercontent.com/49789044/74103591-2b546800-4b45-11ea-89ed-a59467c69b4e.gif)

**Comment by TheTermos** [comment] 2020-02-09 17:12
@An0n3m0us This one I could reproduce even in 5.1.*

This is inherent to old collision detection, things like that are bound to happen when a node is placed so it intersects with player's box.
#9343 should prevent this particular glitch (still allowing placing stuff so boxes intersect isn't a great idea)

**Comment by An0n3m0us** [comment] 2020-02-26 15:41
It's suddenly got worse; I just updated to the latest Minetest dev and this happens:
https://my.pcloud.com/publink/show?code=XZy4jDkZYg20WnJln98oUlPl1tiqoX29EXuX

**Comment by sfan5** [comment] 2020-02-26 15:57
#9327 was merged, should this happen again this issue can be reopened and we need to reconsider.

**Closed by sfan5** 2020-02-26 15:57 UTC
Labels: Bug, High priority
