### ISSUE TITLE
Screen is buggy for me

### ISSUE THREAD

**Issue by Flopky** [minetest/minetest#9506] opened 2020-03-11 19:13 UTC
##### Minetest version

```
5.1.1 
```

##### OS / Hardware

Operating system:Windows 10
CPU:

GPU model:
OpenGL version:4.6.0

##### Summary

So i was playing and once i joined i found my screen is buggy i will show u an image of what i  mean https://imgur.com/a/e32LIsX

##### Steps to reproduce

I just opened the game and this what happened i hope u can find a solution.

**Comment by appgurueu** [comment] 2020-03-11 19:58
@Flopky you can directly include the image on GitHub.
![Flopky's Screenshot](https://user-images.githubusercontent.com/34514239/76458577-09b3fe00-63db-11ea-9b6b-9c1d0dc9b6b2.png)

**Comment by Flopky** [comment] 2020-03-11 20:14
> @Flopky you can directly include the image on GitHub.
> ![Flopky's Screenshot](https://user-images.githubusercontent.com/34514239/76458577-09b3fe00-63db-11ea-9b6b-9c1d0dc9b6b2.png)yeah but do u knoe how to fix?

**Comment by Desour** [comment] 2020-03-11 20:21
Probably related: #9008

**Comment by Flopky** [comment] 2020-03-11 20:27
> Probably related: #9008

There is no fix for multiplayer.

**Comment by sfan5** [comment] 2020-03-11 20:29
duplicate of #9008

**Closed by sfan5** 2020-03-11 20:29 UTC
Labels: Unconfirmed bug
