### ISSUE TITLE
auth.txt Corruption

### ISSUE THREAD

**Issue by Ezhh** [minetest/minetest#6576] opened 2017-11-01 19:50 UTC
Both Vanessa and myself have experienced the auth.txt file corrupting (apparently fully deleted with only new entries for that day present). This has been observed on three of Vanessa's worlds and one of mine, all running 0.4.16 (not current dev).

**Comment by BluebirdGreycoat** [comment] 2017-11-01 20:29
Do you have any details on what triggers this problem? In over a year I have never once had auth.txt corruption, but that may have something to do with the cleaning script I run weekly.

**Comment by Ezhh** [comment] 2017-11-01 21:08
I assumed it was related to the size of auth.txt (I had forgotten to clean it for a while); however, this does not seem to have been the case for Vanessa. 

It has only happened to me once in approaching two years, but this is something that only needs to happen once on a busy server for it to be a concern.

**Comment by rubenwardy** [comment] 2017-11-01 21:17
semi-related: #5334

**Comment by Fixer-007** [comment] 2017-11-01 22:00
What about sqlizing it?

**Comment by paramat** [comment] 2017-11-02 02:56
Yes we should implement sauth mod in MT, sofar and Ezhh are both using it successfully.

**Comment by rubenwardy** [comment] 2017-11-02 03:03
> sofar and Ezhh are both using it successfully.

I'm also using it, it works reliably (no crashes)

**Comment by ExeterDad** [comment] 2017-11-02 09:59
Our auth.txt has been cleaned nightly and even still it contains 57k records and slowly grows. sauth has been recently set up and immediate results.
I do have to point out an obvious con that will be a showstopper for some is ` local _sql = ie.require("lsqlite3")` (lua module) and mod security is needed.

**Comment by VanessaE** [comment] 2017-11-02 19:05
Frankly, I find the notion of using a separate, outside-of-Minetest process for the auth database not only grating, but also confusing.  Minetest should have this stuff built-in and in-use automatically, if auth.txt is so bad.  But that raises a question:  why can't Minetest use a flat text file efficiently?  It's not like 1MB worth of plain text (for example) is really all that much.

Fix the root problem, don't just shuffle the data off to some other method, or it's just going to become a problem again some time later.

**Comment by paramat** [comment] 2017-11-02 20:08
In the discussion linked above the implementation of auth.txt handling is described as bad, that may be the cause (hopefully).

**Comment by ExeterDad** [comment] 2017-11-04 16:23
We're having the expected busy weekend. Our sauth.sqlite has 58,178 records as I'm intentionally not cleaning it.  At a time with 51 players, and players coming and going at a fairly steady pace, there does not seem to be any related lag spikes that we experienced before. 
I'm not saying the sauth mod needs to be included in core because of a external module, but I feel moving towards a database for the auth.txt with a native Minetest connection is something we need to seriously consider, and sooner rather than later.
The "in your face" performance boost is very clear to the server and the client.

**Closed** 2017-11-08 15:14 UTC
Labels: @ Server / Client / Env., Bug, High priority
