### ISSUE TITLE
Color light

### ISSUE THREAD

**Issue by paulevsGitch** [minetest/minetest#9034] opened 2019-10-10 08:56 UTC
Color light is not the most important feature but it can make players constructions more interesting and make possible various beautiful color effects such as light green fireflies or red lava.

The concept of simple color light algorithm was introduced in Seed of Andromeda (now project closed), it can be done in such way:
- light is stored in 2 unsigned bytes, using 5 bits per color (32 possible values) or 4 bits per color (16 possible values).
- Each light channel has same mechanics of spreading, as a current light algorithm;
- Light source nodes can store their color in param2, that also can be used for different colors per one node;
- Additional - transparent nodes can store color of refraction in param2, that allow to have color shadow. Mechanics of such shadows is simple multiplication between light passing through a node and shadow color;
- Light value for mod using can be calculated as a max value for red, green and blue channels.

Seed of Andromeda articles:
[Part one (light)](https://www.seedofandromeda.com/blogs/29-fast-flood-fill-lighting-in-a-blocky-voxel-game-pt-1)
[Part two (shadows)](https://www.seedofandromeda.com/blogs/30-fast-flood-fill-lighting-in-a-blocky-voxel-game-pt-2)

**Comment by rubenwardy** [comment] 2019-10-10 09:03
Duplicate of https://github.com/minetest/minetest/issues/2670

We'd appreciate it if you searched for existing issues before opening one

**Closed** 2019-10-10 09:02 UTC
Labels: Feature request
