### ISSUE TITLE
High DPI cutting off texts

### ISSUE THREAD

**Issue by neuhaus** [minetest/minetest#4529] opened 2016-09-18 09:38 UTC
When I increase the DPI to 163dpi (matching my 3840x2160 27" monitor), the text gets cut off pretty much everywhere.

Also when setting DPI to 163 and the resolution to 3840x2160 and fullscreen, the window is apparently larger than I can see (it is not centered).

Something weird is going on...

(0.4.14 on Windows 10)

**Comment by neuhaus** [comment] 2016-10-12 12:25
If you need screenshots etc please let me know

**Comment by everamzah** [comment] 2016-10-12 13:50
try `xrandr --dpi 163`, for some reason minetest honors this?

**Comment by neuhaus** [comment] 2016-10-12 13:53
(I did this on Windows 10)

**Comment by sfan5** [comment] 2020-04-10 15:11
reverse duplicate of #8371
closing this too

**Closed by sfan5** 2020-04-10 15:11 UTC
Labels: @ Client / Audiovisuals

**Comment by neuhaus** [comment] 2020-04-10 22:07
Lame. Closing this issue will not make the bug go away...

**Comment by sfan5** [comment] 2020-04-10 22:26
Sure sounds the same to me especially with the issue title.
Or is this issue supposed to be "chosen font size is too big on high-dpi systems"?
