### ISSUE TITLE
Transperent nodes with `use_texture_alpha = true` invisible when looking from underwater

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4179] opened 2016-05-31 15:16 UTC
Quoting Tenplus1:

>ANY node that is registered with use_texture_alpha = true in it's definition, place it down, then view from underwater... it disappears

To test it download https://github.com/tenplus1/cblocks (coloured blocks mod) and place some coloured glass above water.

Looking at example transperent coloured glass above water:
![](https://i.imgur.com/YvMYHbW.png)
Looking from below water, it dissapears from view, glass is above water:
![](https://i.imgur.com/7dr27rD.png)
Funnily enough, if I add same blocks underwater, I can see both now:
https://i.imgur.com/H2fqmr5.png

Also, visibility of blocks below water depends on height above water:
1) https://i.imgur.com/ukuFTPw.png (higher)
2) https://i.imgur.com/BYnsmey.png (lower)

**Comment by Wayward1** [comment] 2016-05-31 15:44
Possibly a duplicate of/related to #95?

**Comment by est31** [comment] 2016-05-31 20:12
Edited the issue to directly add two images to the issue description. All are too much, but two make people see the bug immediately.

**Comment by paramat** [comment] 2016-05-31 20:34
Duplicate of #95 
Will close soon.

**Closed** 2016-05-31 20:41 UTC
Labels: @ Client / Audiovisuals, Bug, Duplicate
