### ISSUE TITLE
Crash on tab_multiplayer.lua and tab_online.lua: Favourites duplicate

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#4729] opened 2016-11-05 02:33 UTC
Happened loading the multiplayer menu after logging out from a server:

```
2016-11-04 19:31:57: ERROR[Main]: GUIEngine: execution of menu script failed: Failed to load and run script from /home/sofar/git/minetest/bin/../builtin/init.lua:
2016-11-04 19:31:57: ERROR[Main]: ...git/minetest/bin/../builtin/mainmenu/tab_multiplayer.lua:68: attempt to index a nil value
2016-11-04 19:31:57: ERROR[Main]: stack traceback:
2016-11-04 19:31:57: ERROR[Main]: 	...git/minetest/bin/../builtin/mainmenu/tab_multiplayer.lua:68: in function 'get_formspec'
2016-11-04 19:31:57: ERROR[Main]: 	/home/sofar/git/minetest/bin/../builtin/fstk/tabview.lua:74: in function 'get_formspec'
2016-11-04 19:31:57: ERROR[Main]: 	/home/sofar/git/minetest/bin/../builtin/fstk/ui.lua:107: in function 'update'
2016-11-04 19:31:57: ERROR[Main]: 	/home/sofar/git/minetest/bin/../builtin/mainmenu/init.lua:164: in function 'init_globals'
2016-11-04 19:31:57: ERROR[Main]: 	/home/sofar/git/minetest/bin/../builtin/mainmenu/init.lua:169: in main chunk
2016-11-04 19:31:57: ERROR[Main]: 	[C]: in function 'dofile'
2016-11-04 19:31:57: ERROR[Main]: 	/home/sofar/git/minetest/bin/../builtin/init.lua:44: in main chunk
2016-11-04 19:31:57: ERROR[Main]: No future without mainmenu
```
Aborted (core dumped)

**Comment by rubenwardy** [comment] 2016-11-23 18:10
I can't reproduce this, can you?

If so: https://github.com/rubenwardy/minetest/commit/e4b1cea87d798bf2395198eb2edd2365c0dbd52f

**Comment by sofar** [comment] 2016-11-26 19:24
2016-11-26 11:21:42: ERROR[Main]: GUIEngine: execution of menu script failed: Failed to load and run script from /home/sofar/git/minetest/bin/../builtin/init.lua:
2016-11-26 11:21:42: ERROR[Main]: ...git/minetest/bin/../builtin/mainmenu/tab_multiplayer.lua:68: attempt to index a nil value

Hard crash every time I start the game

**Comment by sofar** [comment] 2016-11-26 19:29
I seem to have multiple duplicates in the stored favorites:

```
[server]

127.0.0.1
30000


[server]

127.0.0.1
30000


```

**Comment by sofar** [comment] 2016-11-26 19:30
Deleting the duplicates removes the problem, but the code should make sure the crash doesn't happen

**Comment by paramat** [comment] 2018-12-30 06:44
Blocker for 5.0.0?

**Comment by SmallJoker** [comment] 2018-12-30 08:31
Nobody but sofar reported that they have this issue here. Thus, it can also be fixed in a later release (although the PR exists and is simple).

**Closed** 2019-11-08 21:18 UTC
Labels: @ Mainmenu, Beginner Friendly, Bug
