### ISSUE TITLE
Allow custom types in minetest.register_craft

### ISSUE THREAD

**Issue by KristopherKram** [minetest/minetest#1111] opened 2014-01-21 02:28 UTC
Custom types should be allowed in minetest.register_craft. Mods like technic and others have to work around this by creating custom code instead of easily creating a custom type. Example of a custom code work around is here: https://github.com/minetest-technic/technic/blob/master/technic/machines/register/grinder_recipes.lua .

**Comment by rubenwardy** [comment] 2017-08-10 23:42
Duplicate of #1079

**Closed** 2017-08-10 23:42 UTC
Labels: @ Script API, Duplicate, Feature request
