### ISSUE TITLE
Allow more complex texture modifiers

### ISSUE THREAD

**Issue by Aurailus** [minetest/minetest#6821] opened 2017-12-22 22:48 UTC
Hi Minetest Devs. I have a really weird problem. I'm making a dynamic texture generation library in MT, using the texture modifiers, and I have a really weird bug that I believe is an engine issue. Here is my mod code:
```
tc = {}

local function split(pString, pPattern)
   local Table = {}
   local fpat = "(.-)" .. pPattern
   local last_end = 1
   local s, e, cap = pString:find(fpat, 1)
   while s do
      if s ~= 1 or cap ~= "" then
     table.insert(Table,cap)
      end
      last_end = e+1
      s, e, cap = pString:find(fpat, last_end)
   end
   if last_end <= #pString then
      cap = pString:sub(last_end)
      table.insert(Table, cap)
   end
   return Table
end

function tc.genCol(cStr)
	if #cStr == 1 then cStr = cStr .. cStr .. cStr end
	return "(tc_.png\\^[colorize\\:#" .. cStr .. ")"
end

local function genImg(data)
	local stime = minetest.get_us_time()
	print("Starting texture generation.")

	local width = #split(data[1], "\|")
	local str = "[combine:" .. width .. "x" .. #data 
	--Set width and height
	
	for i = 1, #data do
		local row = split(data[i], "\|")
		for j = 1, #row do
			--Color pixels
			str = str .. ":"..(j-1)..","..(i-1).."="..tc.genCol(row[j])
		end
	end

	print("Generated " .. width .. "x" .. #data .. " texture in " .. (minetest.get_us_time() - stime) .. " microseconds")
	return str
end

minetest.register_node('tc:test_node', {
	drawtype = "normal",
	tiles = {
		genImg({
			"0|0|0|0|5|5|5|5|9|9|9|9|C|C|C|C|",
			"5|5|5|5|9|9|9|9|C|C|C|C|0|0|0|0|",
			"9|9|9|9|C|C|C|C|0|0|0|0|5|5|5|5|",
			"C|C|C|C|0|0|0|0|5|5|5|5|9|9|9|9|",
		})
	},
	description = "Test Node"
})

minetest.register_node('tc:test_node_2', {
	drawtype = "normal",
	tiles = {
		genImg({"e8e7c5|e8e7c5|e8e7c5|e6dfba|e6dfba|e6dfba|dfdcaf|c7b68a|eff0cf|eff0cf|e8eac6|e8eac6|e8e7c5|e8e7c5|e8e7c5|e7e3bc|",
"ddd6ac|ddd6ac|ddd6ac|ddd6ac|ddd6ac|d8d0a7|d8d0a7|cabd94|e6dfba|d5ca9d|d5ca9d|cab98a|d1c194|d6cca1|ddd6ac|d5ca9d|",
"d1c599|d1c399|d5ca9d|d5ca9d|dad1a7|d4cc9e|d4c596|c7b68a|dedab3|d8d0a7|dfd9af|dedab3|e5ddb6|d4c596|c8ba8b|d1c399|",
"bfaf7f|bfa57f|bfa57f|bfa57f|bfaf7f|bfaa7f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|",
"dad3aa|dfd9af|c8ba8b|e6dfba|dfd5af|d5ca9d|d1c194|d5ca9d|d5ca9d|ddd6ac|dad1a7|d0c39f|dfddaf|e2deb4|e5ddb6|dfdcaf|",
"d4c89e|ccbd8c|d0c18d|d1c194|d5ca9d|dedab3|dedab3|dedab3|ddd6ac|ddd6ac|d5ca9d|cabc94|dad3aa|d1c394|d1c599|d1c394|",
"d4cc9e|d1c599|cfc294|d5ca9d|d5ca9d|d5ca9d|d4c596|d4c596|d4cc9e|d3c59a|d4c596|c7b68a|cabd8a|cab98a|c8ba8b|ccbe8c|",
"bfaf7f|bfa57f|bfa57f|bfaf7f|bfaf7f|bfaa7f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfaf7f|bfaf7f|",
"d9d1a3|c7b68a|ecf0d1|eaefcb|ecefcb|ecefcb|e8e8c5|e8e8c5|e6e5bd|e6e5bd|e6e1ba|dfd8af|d6caa1|ddd6ac|dfdaaf|d8d0a7|",
"cfc394|cabd94|e6dfba|ddd6ac|d8d0a7|ddd6ac|ddd6ac|d5ca9d|d4c89e|d1c194|d0c18d|d1c599|dfd8af|dfd8af|cfc294|d1c599|",
"ccc18c|cabd94|d5ca9d|dacfa7|ddd6ac|dad1a7|d8d0a7|d5ca9d|dfd9af|e6e1ba|ddd8ac|dacfa7|d3c59a|d1c599|d9cca3|cfc294|",
"bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfaf7f|bfaf7f|bfaf7f|bfaf7f|bfa57f|bfa57f|bfaf7f|",
"e6dfba|e6dfba|e2deb4|e2deb4|dfd9af|d4cc9e|cabd94|dfd8af|dfd9af|dfd9af|dfd9af|dfd8af|dedcb3|dfd8af|d9cca3|dddaac|",
"d1c194|d5ca9d|ddd6ac|ddd6ac|ddd6ac|d5ca9d|cabd94|dfd8af|d9d1a3|d3c59a|d4c89e|d6cca1|d9cfa3|dfd8af|dfdcaf|d6cca1|",
"e6dfba|ded6b3|dfd4af|d4c596|d4c596|d5ca9d|c7b68a|d9cfa3|cfc394|cfc294|d1c599|cfc294|cfc294|cab98a|d4c596|d5ca9d|",
"bfa57f|bfa57f|bfa57f|bfaf7f|bfaf7f|bfaa7f|bfaa7f|bfaf7f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfa57f|bfaf7f|bfaf7f|",})
	},
	description = "Test Node"
})

minetest.register_node('tc:test_node_3', {
	drawtype = "normal",
	tiles = {
		genImg({"3d3021|2b231a|392e1f|403529|584939|504234|4e4032|43382b|584939|40352a|524435|514335|393025|362d21|3d3021|3d3021|",
"3f3323|493d2e|64533e|9d7959|9d7959|a78563|9d7959|a78563|ae8d70|a78563|ae8d70|9d7959|9d7959|605144|382f23|2d241a|",
"463a24|6e6047|9d7959|a78563|7f6449|745b42|7d6145|816447|7d6145|7d6145|745b42|83684d|ae8d70|9d7959|5c4d3e|392e1f|",
"403529|9d7959|a78563|83664d|795f45|896f55|9f7d5b|a78563|a78563|8e6d50|886d52|745b42|7c6146|9e7e5d|9d7959|403529|",
"584939|9d7959|83684d|745b42|927558|9d7959|7a5f44|6c553e|785d42|7a6148|977455|8f7357|745b42|82674c|9d7959|584939|",
"504234|9d7959|745b42|876c51|9d7959|7b5d43|8a6c54|a78563|9d7959|886b52|765a42|9d7959|846a50|745b42|a08266|504234|",
"4e4032|a78563|7d6145|9d7959|87674b|886b52|9d7959|8a6a4e|8e6e52|a68462|8a6d54|7a6148|977455|745b42|9a7b5b|4e4032|",
"43382b|ae8d70|7d6145|a78563|795e43|9d7959|8a6a4e|a78563|917053|86664a|9f7a59|816447|a78563|745b42|a78563|43382b|",
"584939|8e6d50|816447|9d7959|816447|a78563|8d6d51|927354|9d7959|7a5f44|9d7959|745b42|a78563|745b42|9d7959|584939|",
"40352a|8e6d50|7d6145|a78563|7d6349|886b52|9d7959|86684a|7a5f44|a68462|886b52|785f46|9d7959|816447|9d7959|40352a|",
"524435|9d7959|7c6044|8c7258|9d7959|7f6147|866950|a78563|9d7959|866950|7d6047|9d7959|826950|745b42|a78563|524435|",
"514335|9d7959|83684d|745b42|927558|a07f5e|7a6148|816447|745b42|7a6148|9d7959|8c7258|745b42|896f55|9d7959|514335|",
"393025|9d7959|a78563|7b6147|745b42|886d52|9d7959|a78563|9d7959|9d7959|826950|745b42|7d6349|ae8d70|9d7959|393025|",
"392e1f|524233|a78563|ae8d70|83684d|745b42|816447|816447|7d6145|7d6145|745b42|866b50|a78563|9d7959|57483a|332a1d|",
"2b231a|332a1d|514132|9d7959|9d7959|a78563|a78563|ae8d70|ae8d70|a78563|a78563|9d7959|9d7959|55483e|3b3227|3d3021|",
"3d3021|3d3021|332a1d|403529|584939|504234|4e4032|43382b|584939|40352a|524435|514335|393025|392e1f|292219|3d3021|",})
	},
	description = "Test Node"
})
```

The above code works fine and generates the textures, but if I try to make textures bigger then 17*17 the game freezes on Node Definitions. I have a serializer for PNG files at [this link](https://themtbox.net/tools/serializeImage.php) If you'd like to try yourself. 

I belive this issue has to do with the recursion in the Tile.cpp class filling up the stack, but I'm not sure, I'm not very experienced in C++. Thank you for your time.

**Comment by Aurailus** [comment] 2017-12-22 22:51
Sorry, I should have left a preview of the actual returned string. Here it is:

```
[combine:16x16:0,0=(tc_.png\\^[colorize\\:#3d3021):1,0=(tc_.png\\^[colorize\\:#2b231a):2,0=(tc_.png\\^[colorize\\:#392e1f):3,0=(tc_.png\\^[colorize\\:#403529):4,0=(tc_.png\\^[colorize\\:#584939):5,0=(tc_.png\\^[colorize\\:#504234):6,0=(tc_.png\\^[colorize\\:#4e4032):7,0=(tc_.png\\^[colorize\\:#43382b):8,0=(tc_.png\\^[colorize\\:#584939):9,0=(tc_.png\\^[colorize\\:#40352a):10,0=(tc_.png\\^[colorize\\:#524435):11,0=(tc_.png\\^[colorize\\:#514335):12,0=(tc_.png\\^[colorize\\:#393025):13,0=(tc_.png\\^[colorize\\:#362d21):14,0=(tc_.png\\^[colorize\\:#3d3021):15,0=(tc_.png\\^[colorize\\:#3d3021):0,1=(tc_.png\\^[colorize\\:#3f3323):1,1=(tc_.png\\^[colorize\\:#493d2e):2,1=(tc_.png\\^[colorize\\:#64533e):3,1=(tc_.png\\^[colorize\\:#9d7959):4,1=(tc_.png\\^[colorize\\:#9d7959):5,1=(tc_.png\\^[colorize\\:#a78563):6,1=(tc_.png\\^[colorize\\:#9d7959):7,1=(tc_.png\\^[colorize\\:#a78563):8,1=(tc_.png\\^[colorize\\:#ae8d70):9,1=(tc_.png\\^[colorize\\:#a78563):10,1=(tc_.png\\^[colorize\\:#ae8d70):11,1=(tc_.png\\^[colorize\\:#9d7959):12,1=(tc_.png\\^[colorize\\:#9d7959):13,1=(tc_.png\\^[colorize\\:#605144):14,1=(tc_.png\\^[colorize\\:#382f23):15,1=(tc_.png\\^[colorize\\:#2d241a):0,2=(tc_.png\\^[colorize\\:#463a24):1,2=(tc_.png\\^[colorize\\:#6e6047):2,2=(tc_.png\\^[colorize\\:#9d7959):3,2=(tc_.png\\^[colorize\\:#a78563):4,2=(tc_.png\\^[colorize\\:#7f6449):5,2=(tc_.png\\^[colorize\\:#745b42):6,2=(tc_.png\\^[colorize\\:#7d6145):7,2=(tc_.png\\^[colorize\\:#816447):8,2=(tc_.png\\^[colorize\\:#7d6145):9,2=(tc_.png\\^[colorize\\:#7d6145):10,2=(tc_.png\\^[colorize\\:#745b42):11,2=(tc_.png\\^[colorize\\:#83684d):12,2=(tc_.png\\^[colorize\\:#ae8d70):13,2=(tc_.png\\^[colorize\\:#9d7959):14,2=(tc_.png\\^[colorize\\:#5c4d3e):15,2=(tc_.png\\^[colorize\\:#392e1f):0,3=(tc_.png\\^[colorize\\:#403529):1,3=(tc_.png\\^[colorize\\:#9d7959):2,3=(tc_.png\\^[colorize\\:#a78563):3,3=(tc_.png\\^[colorize\\:#83664d):4,3=(tc_.png\\^[colorize\\:#795f45):5,3=(tc_.png\\^[colorize\\:#896f55):6,3=(tc_.png\\^[colorize\\:#9f7d5b):7,3=(tc_.png\\^[colorize\\:#a78563):8,3=(tc_.png\\^[colorize\\:#a78563):9,3=(tc_.png\\^[colorize\\:#8e6d50):10,3=(tc_.png\\^[colorize\\:#886d52):11,3=(tc_.png\\^[colorize\\:#745b42):12,3=(tc_.png\\^[colorize\\:#7c6146):13,3=(tc_.png\\^[colorize\\:#9e7e5d):14,3=(tc_.png\\^[colorize\\:#9d7959):15,3=(tc_.png\\^[colorize\\:#403529):0,4=(tc_.png\\^[colorize\\:#584939):1,4=(tc_.png\\^[colorize\\:#9d7959):2,4=(tc_.png\\^[colorize\\:#83684d):3,4=(tc_.png\\^[colorize\\:#745b42):4,4=(tc_.png\\^[colorize\\:#927558):5,4=(tc_.png\\^[colorize\\:#9d7959):6,4=(tc_.png\\^[colorize\\:#7a5f44):7,4=(tc_.png\\^[colorize\\:#6c553e):8,4=(tc_.png\\^[colorize\\:#785d42):9,4=(tc_.png\\^[colorize\\:#7a6148):10,4=(tc_.png\\^[colorize\\:#977455):11,4=(tc_.png\\^[colorize\\:#8f7357):12,4=(tc_.png\\^[colorize\\:#745b42):13,4=(tc_.png\\^[colorize\\:#82674c):14,4=(tc_.png\\^[colorize\\:#9d7959):15,4=(tc_.png\\^[colorize\\:#584939):0,5=(tc_.png\\^[colorize\\:#504234):1,5=(tc_.png\\^[colorize\\:#9d7959):2,5=(tc_.png\\^[colorize\\:#745b42):3,5=(tc_.png\\^[colorize\\:#876c51):4,5=(tc_.png\\^[colorize\\:#9d7959):5,5=(tc_.png\\^[colorize\\:#7b5d43):6,5=(tc_.png\\^[colorize\\:#8a6c54):7,5=(tc_.png\\^[colorize\\:#a78563):8,5=(tc_.png\\^[colorize\\:#9d7959):9,5=(tc_.png\\^[colorize\\:#886b52):10,5=(tc_.png\\^[colorize\\:#765a42):11,5=(tc_.png\\^[colorize\\:#9d7959):12,5=(tc_.png\\^[colorize\\:#846a50):13,5=(tc_.png\\^[colorize\\:#745b42):14,5=(tc_.png\\^[colorize\\:#a08266):15,5=(tc_.png\\^[colorize\\:#504234):0,6=(tc_.png\\^[colorize\\:#4e4032):1,6=(tc_.png\\^[colorize\\:#a78563):2,6=(tc_.png\\^[colorize\\:#7d6145):3,6=(tc_.png\\^[colorize\\:#9d7959):4,6=(tc_.png\\^[colorize\\:#87674b):5,6=(tc_.png\\^[colorize\\:#886b52):6,6=(tc_.png\\^[colorize\\:#9d7959):7,6=(tc_.png\\^[colorize\\:#8a6a4e):8,6=(tc_.png\\^[colorize\\:#8e6e52):9,6=(tc_.png\\^[colorize\\:#a68462):10,6=(tc_.png\\^[colorize\\:#8a6d54):11,6=(tc_.png\\^[colorize\\:#7a6148):12,6=(tc_.png\\^[colorize\\:#977455):13,6=(tc_.png\\^[colorize\\:#745b42):14,6=(tc_.png\\^[colorize\\:#9a7b5b):15,6=(tc_.png\\^[colorize\\:#4e4032):0,7=(tc_.png\\^[colorize\\:#43382b):1,7=(tc_.png\\^[colorize\\:#ae8d70):2,7=(tc_.png\\^[colorize\\:#7d6145):3,7=(tc_.png\\^[colorize\\:#a78563):4,7=(tc_.png\\^[colorize\\:#795e43):5,7=(tc_.png\\^[colorize\\:#9d7959):6,7=(tc_.png\\^[colorize\\:#8a6a4e):7,7=(tc_.png\\^[colorize\\:#a78563):8,7=(tc_.png\\^[colorize\\:#917053):9,7=(tc_.png\\^[colorize\\:#86664a):10,7=(tc_.png\\^[colorize\\:#9f7a59):11,7=(tc_.png\\^[colorize\\:#816447):12,7=(tc_.png\\^[colorize\\:#a78563):13,7=(tc_.png\\^[colorize\\:#745b42):14,7=(tc_.png\\^[colorize\\:#a78563):15,7=(tc_.png\\^[colorize\\:#43382b):0,8=(tc_.png\\^[colorize\\:#584939):1,8=(tc_.png\\^[colorize\\:#8e6d50):2,8=(tc_.png\\^[colorize\\:#816447):3,8=(tc_.png\\^[colorize\\:#9d7959):4,8=(tc_.png\\^[colorize\\:#816447):5,8=(tc_.png\\^[colorize\\:#a78563):6,8=(tc_.png\\^[colorize\\:#8d6d51):7,8=(tc_.png\\^[colorize\\:#927354):8,8=(tc_.png\\^[colorize\\:#9d7959):9,8=(tc_.png\\^[colorize\\:#7a5f44):10,8=(tc_.png\\^[colorize\\:#9d7959):11,8=(tc_.png\\^[colorize\\:#745b42):12,8=(tc_.png\\^[colorize\\:#a78563):13,8=(tc_.png\\^[colorize\\:#745b42):14,8=(tc_.png\\^[colorize\\:#9d7959):15,8=(tc_.png\\^[colorize\\:#584939):0,9=(tc_.png\\^[colorize\\:#40352a):1,9=(tc_.png\\^[colorize\\:#8e6d50):2,9=(tc_.png\\^[colorize\\:#7d6145):3,9=(tc_.png\\^[colorize\\:#a78563):4,9=(tc_.png\\^[colorize\\:#7d6349):5,9=(tc_.png\\^[colorize\\:#886b52):6,9=(tc_.png\\^[colorize\\:#9d7959):7,9=(tc_.png\\^[colorize\\:#86684a):8,9=(tc_.png\\^[colorize\\:#7a5f44):9,9=(tc_.png\\^[colorize\\:#a68462):10,9=(tc_.png\\^[colorize\\:#886b52):11,9=(tc_.png\\^[colorize\\:#785f46):12,9=(tc_.png\\^[colorize\\:#9d7959):13,9=(tc_.png\\^[colorize\\:#816447):14,9=(tc_.png\\^[colorize\\:#9d7959):15,9=(tc_.png\\^[colorize\\:#40352a):0,10=(tc_.png\\^[colorize\\:#524435):1,10=(tc_.png\\^[colorize\\:#9d7959):2,10=(tc_.png\\^[colorize\\:#7c6044):3,10=(tc_.png\\^[colorize\\:#8c7258):4,10=(tc_.png\\^[colorize\\:#9d7959):5,10=(tc_.png\\^[colorize\\:#7f6147):6,10=(tc_.png\\^[colorize\\:#866950):7,10=(tc_.png\\^[colorize\\:#a78563):8,10=(tc_.png\\^[colorize\\:#9d7959):9,10=(tc_.png\\^[colorize\\:#866950):10,10=(tc_.png\\^[colorize\\:#7d6047):11,10=(tc_.png\\^[colorize\\:#9d7959):12,10=(tc_.png\\^[colorize\\:#826950):13,10=(tc_.png\\^[colorize\\:#745b42):14,10=(tc_.png\\^[colorize\\:#a78563):15,10=(tc_.png\\^[colorize\\:#524435):0,11=(tc_.png\\^[colorize\\:#514335):1,11=(tc_.png\\^[colorize\\:#9d7959):2,11=(tc_.png\\^[colorize\\:#83684d):3,11=(tc_.png\\^[colorize\\:#745b42):4,11=(tc_.png\\^[colorize\\:#927558):5,11=(tc_.png\\^[colorize\\:#a07f5e):6,11=(tc_.png\\^[colorize\\:#7a6148):7,11=(tc_.png\\^[colorize\\:#816447):8,11=(tc_.png\\^[colorize\\:#745b42):9,11=(tc_.png\\^[colorize\\:#7a6148):10,11=(tc_.png\\^[colorize\\:#9d7959):11,11=(tc_.png\\^[colorize\\:#8c7258):12,11=(tc_.png\\^[colorize\\:#745b42):13,11=(tc_.png\\^[colorize\\:#896f55):14,11=(tc_.png\\^[colorize\\:#9d7959):15,11=(tc_.png\\^[colorize\\:#514335):0,12=(tc_.png\\^[colorize\\:#393025):1,12=(tc_.png\\^[colorize\\:#9d7959):2,12=(tc_.png\\^[colorize\\:#a78563):3,12=(tc_.png\\^[colorize\\:#7b6147):4,12=(tc_.png\\^[colorize\\:#745b42):5,12=(tc_.png\\^[colorize\\:#886d52):6,12=(tc_.png\\^[colorize\\:#9d7959):7,12=(tc_.png\\^[colorize\\:#a78563):8,12=(tc_.png\\^[colorize\\:#9d7959):9,12=(tc_.png\\^[colorize\\:#9d7959):10,12=(tc_.png\\^[colorize\\:#826950):11,12=(tc_.png\\^[colorize\\:#745b42):12,12=(tc_.png\\^[colorize\\:#7d6349):13,12=(tc_.png\\^[colorize\\:#ae8d70):14,12=(tc_.png\\^[colorize\\:#9d7959):15,12=(tc_.png\\^[colorize\\:#393025):0,13=(tc_.png\\^[colorize\\:#392e1f):1,13=(tc_.png\\^[colorize\\:#524233):2,13=(tc_.png\\^[colorize\\:#a78563):3,13=(tc_.png\\^[colorize\\:#ae8d70):4,13=(tc_.png\\^[colorize\\:#83684d):5,13=(tc_.png\\^[colorize\\:#745b42):6,13=(tc_.png\\^[colorize\\:#816447):7,13=(tc_.png\\^[colorize\\:#816447):8,13=(tc_.png\\^[colorize\\:#7d6145):9,13=(tc_.png\\^[colorize\\:#7d6145):10,13=(tc_.png\\^[colorize\\:#745b42):11,13=(tc_.png\\^[colorize\\:#866b50):12,13=(tc_.png\\^[colorize\\:#a78563):13,13=(tc_.png\\^[colorize\\:#9d7959):14,13=(tc_.png\\^[colorize\\:#57483a):15,13=(tc_.png\\^[colorize\\:#332a1d):0,14=(tc_.png\\^[colorize\\:#2b231a):1,14=(tc_.png\\^[colorize\\:#332a1d):2,14=(tc_.png\\^[colorize\\:#514132):3,14=(tc_.png\\^[colorize\\:#9d7959):4,14=(tc_.png\\^[colorize\\:#9d7959):5,14=(tc_.png\\^[colorize\\:#a78563):6,14=(tc_.png\\^[colorize\\:#a78563):7,14=(tc_.png\\^[colorize\\:#ae8d70):8,14=(tc_.png\\^[colorize\\:#ae8d70):9,14=(tc_.png\\^[colorize\\:#a78563):10,14=(tc_.png\\^[colorize\\:#a78563):11,14=(tc_.png\\^[colorize\\:#9d7959):12,14=(tc_.png\\^[colorize\\:#9d7959):13,14=(tc_.png\\^[colorize\\:#55483e):14,14=(tc_.png\\^[colorize\\:#3b3227):15,14=(tc_.png\\^[colorize\\:#3d3021):0,15=(tc_.png\\^[colorize\\:#3d3021):1,15=(tc_.png\\^[colorize\\:#3d3021):2,15=(tc_.png\\^[colorize\\:#332a1d):3,15=(tc_.png\\^[colorize\\:#403529):4,15=(tc_.png\\^[colorize\\:#584939):5,15=(tc_.png\\^[colorize\\:#504234):6,15=(tc_.png\\^[colorize\\:#4e4032):7,15=(tc_.png\\^[colorize\\:#43382b):8,15=(tc_.png\\^[colorize\\:#584939):9,15=(tc_.png\\^[colorize\\:#40352a):10,15=(tc_.png\\^[colorize\\:#524435):11,15=(tc_.png\\^[colorize\\:#514335):12,15=(tc_.png\\^[colorize\\:#393025):13,15=(tc_.png\\^[colorize\\:#392e1f):14,15=(tc_.png\\^[colorize\\:#292219):15,15=(tc_.png\\^[colorize\\:#3d3021)
```

**Comment by sfan5** [comment] 2017-12-23 14:03
Sounds like the engine is just unable to cope with that many texture modifiers, especially as every single intermediate result will be cached.

**Comment by 4w** [comment] 2017-12-23 22:36
> I'm doubting whether this is a useful/common usecase

But it is still a bug.

**Comment by Aurailus** [comment] 2017-12-23 22:38
This allows the dynamic generation of textures. It could completely change the modding scene for minetest, and enable things like custom skins at runtime, and more.  I don't think it's very significant.

**Comment by SmallJoker** [comment] 2017-12-24 09:09
@4w Sometimes there are technical limitations which can indicate that it may be time for a better solution. 

Using a combiner operation for each pixel produces a massive overhead. If you send a regular 16x16 PNG texture, it requires about 350 bytes of sent data (combiner method above is 9.2 KiB, ~27 times more). A new modifier that takes binary data (we have libpng to convert bitmaps) solves the problem if it's due the recursion. The binary data could be assigned to a temporary file name to make re-use in the same texture modifier string possible.

**Comment by Aurailus** [comment] 2017-12-24 09:47
@SmallJoker I agree. Its high-time that minetest gets proper support for dynamically generated textures. Until then, I'll probably just modify the player_api mod to accept multiple smaller textures :/

**Comment by raymoo** [comment] 2018-01-03 02:04
It's an interesting idea to put the entire image data in the texture string. It still has the problem that the client will cache every dynamically-generated texture forever. Maybe there should be a separate cache for entity textures that is reference counted with how many entities are using each texture?

I'm not sure how inventories currently work, but maybe it would be possible to share this cache with items, with only items currently in-inventory contributing references.

**Comment by paramat** [comment] 2018-01-04 02:48
There was another issue about heavy use of texture modifiers overloading MT, looking ..

**Comment by Aurailus** [comment] 2018-01-04 06:43
That would be great. Thanks @paramat

**Comment by paramat** [comment] 2018-12-27 02:39
Any core dev support for the suggested solution? (i'm neutral).

**Comment by SmallJoker** [comment] 2018-12-27 18:31
@paramat Yes. A way to encode PNG files would also allow mods to implement their own texture modifiers. Surely that would require some more API functions to process files (and to convert them to byte arrays aka c strings).

**Comment by GreenXenith** [comment] 2019-07-27 17:20
> A way to encode PNG files

Not that it matters, but my [skinmaker](https://github.com/GreenXenith/skinmaker) mod encodes/decodes PNG images. In Lua (so not as fast as cpp but still).
The mod also uses the same method as Auailus's, but on entities, which allows for much more modifiers (up to 65535 bytes in size - serialize max for entities). Formspecs can display even more than that.
I'm not saying this method is *good* by any means, i'm just noting other details.

**Comment by hecktest** [comment] 2020-06-02 17:39
Bump; this is a very bad bottleneck. Text signposts cause a lot of lag on servers that have them. All those ^[combines are **very** wasteful, causing the client to freeze for up to a second to generate a block with a bunch of signs. (The biggest overhead comes from the network message size.) It's a major contributor to the lagtown problem.
Having efficient custom images would reduce the footprint of the current hacks, and allow all sorts of dynamic and user made content.
I once made an experimental build with a ^[raw texmod, encoding an indexed bitmap in a deflated base64 blob. It was fast enough to even push a skybox in real time:
![farbox2](https://user-images.githubusercontent.com/42101236/83550151-ac75a780-a506-11ea-80d1-51dbf932370e.png)

However, there were two issues with it:
- Minetest never collects generated textures. The client will eventually run out of memory.
- The data would sometimes be corrupt, even causing crashes. Cause unknown.
If a coredev is willing to work with me on this, I'll revive it.

**Comment by rubenwardy** [comment] 2020-06-02 17:44
See #9961

**Comment by hecktest** [comment] 2020-06-02 17:45
That's nice, but what about ephemeral assets that shouldn't ever be cached or even be referred to by name? I think both approaches could co-exist.

**Comment by Zughy** [comment] 2022-05-05 12:29
Duplicate of #11829 (which is more recent, but also cleaner), closing

**Closed by Zughy** 2022-05-05 12:29 UTC
Labels: Duplicate, Feature request, Textures, Supported by core dev
