### ISSUE TITLE
Wheat doesn't grow

### ISSUE THREAD

**Issue by biowaste** [minetest/minetest#5191] opened 2017-02-08 17:04 UTC
Hey guys, I don't know if anybody reported this or it is just my problem, but it seems like that wheat in basic farming mod is not growing in 0.4.15. I tried to run the server on the second machine and still nothing. Same with tree samples. Any Idea ?

**Comment by paramat** [comment] 2017-02-08 17:09
This is a game issue so should be in https://github.com/minetest/minetest_game/issues
However, crops now use timers, so you have to wait a while before the first one grows.
Also, what's the light level? they need to be under open sky or have very bright light (default:meselamp as edge-neighbour, torches are not bright enough).

**Comment by biowaste** [comment] 2017-02-08 17:15
I had the server on like for an hour to see if it grows. I placed it everywhere, on the soil, wet soil - everytime on sunlight where are no trees. Maybe some bug with Timers ?

**Comment by paramat** [comment] 2017-02-08 17:18
Hm weird.

**Comment by dsohler** [comment] 2017-02-08 19:04
After around 5 minutes after planting them all wheat seeds in my testing field started to convert into the actual wheat plant. After around 7-8 Minutes all seeds were converted and around 2 minutes later they started to grow VERY slowly.

Tested on a local server started from the client’s “Server” tab.

![screenshot_20170208_200509](https://cloud.githubusercontent.com/assets/1668792/22752646/93437486-ee39-11e6-9c0b-f2a33d4ed2fc.png)

**Comment by biowaste** [comment] 2017-02-08 21:30
Weird, I can still see only seeds laying on the ground. I'll take some pics too (btw, I also tried to turn off all the mods, still nothing)

**Comment by sofar** [comment] 2017-02-08 21:41
Can't reproduce, growing just fine for me. Unsure as to what is wrong with your build. Please try an entirely new world as well.

**Comment by tenplus1** [comment] 2017-02-09 09:01
Make sure light levels are sufficient for wheat to grow.

**Comment by sofar** [comment] 2017-02-09 21:46
You can confirm a nodetimer is running on a node with the `inspector` mod (https://github.com/minetest-mods/inspector). Use the inspector tool on a node and you get various raw data from the node, including nodemeta and nodetimer data. If a timer is running on the node, it will show it.

**Comment by biowaste** [comment] 2017-02-09 22:08
![svetlo](https://cloud.githubusercontent.com/assets/25643316/22805026/ee38f8ba-ef1b-11e6-971d-fb83acc1a22e.png)



So I used the inspector mod. It shows that seeds have no light, but as u can see, it happens on sunlight too. No matter where I place it. I use build from Debian jessie backports and other machine has Linux Mint. Never happened on 0.4.14

**Comment by Fixer-007** [comment] 2017-02-09 22:19
Inspector mod has last commit as "Light: may not work.", if you want to be sure about light, install worldedit and use //inspect on     to inspect a node by clicking, it will show its light level.

**Comment by paramat** [comment] 2017-03-21 22:29
Can't be reproduced and is a MTGame issue, closing.

**Closed by paramat** 2017-03-21 22:29 UTC
Labels: Possible close, Unconfirmed bug
