### ISSUE TITLE
Spinning frustum on Xwayland

### ISSUE THREAD

**Issue by 29jm** [minetest/minetest#1763] opened 2014-10-23 14:12 UTC
When I run the minimal developpement test in a Gnome on Wayland session, my mouse movements are persistent: I move my mouse to the right -> I spin very fast to the right until I move my mouse to the left.

System: Archlinux, up-to-date
Gnome 3.14 on Wayland

**Comment by est31** [comment] 2015-11-20 01:49
This bug on the fedora tracker: https://bugzilla.redhat.com/show_bug.cgi?id=1277165

Wayland still discusses about how to resolve this, see the second post in the linked bug report.

And once wayland is there, we might need to implement that API. But until then, its an upstream bug.

**Comment by est31** [comment] 2015-11-20 19:42
Well, it seems we won't be able to implement the API, because as it seems there is no desire from wayland to pass it through on XWayland, e.g. with a custom X extension. So we completely are in upstream's hands on this. Either they find some way to get it working on XWayland, which will be inferior, as they somehow have to detect the application's desire to lock the pointer, or they won't fix it for XWayland applications.

The only two things that we could do:

1. We find some other way to modify the frustrum than with pointer locking, and detect that we run on XWayland. One method would be to look for xrandr names.

2. We run our very own XWayland X server, just for minetest, and patch it to extend it with pointer locking APIs

3. We find some way to talk with wayland directly.

**Comment by est31** [comment] 2016-05-02 02:10
There has been some progress since the last time I looked at it:

* Native wayland applications [will get confinement and locking APIs](https://bugzilla.gnome.org/show_bug.cgi?id=744104). This is of limited interest for us, as we are no native Wayland application, but still something good. [Landed in Wayland 1.10](https://fedoraproject.org/wiki/Wayland_features#relative.2Flocking_pointer_confinement).

* The issue is being worked on for X11 based applications [as well](https://lists.x.org/archives/xorg-devel/2016-April/049351.html). So it looks like upstream will fix it. Thanks to @jadahl for this in advance!

So I'd suggest we should go with:

4. Wait for upstream to fix it, not doing a workaround as that is overly complex.

**Comment by est31** [comment] 2016-08-20 13:58
This bug on fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1277165

**Comment by est31** [comment] 2016-10-16 11:06
The bug may have been fixed by upstream in the Xorg 1.19 release, at least if you can believe [this commit message](https://cgit.freedesktop.org/xorg/xserver/commit/?id=a6e85e6330adcdcbcd939c0963daaecc96d41a2a).

Can anyone with Xorg 1.19 confirm this?

Note the compositor needs to implement it as well. mutter does it since some time already ([at least I think so?](https://bugzilla.gnome.org/show_bug.cgi?id=744104)), but weston only from version [1.12 and up](https://lists.freedesktop.org/archives/wayland-devel/2016-September/031123.html), and KWin [doesn't seem to support it](https://community.kde.org/Plasma/5.8_Errata).

**Comment by nerzhul** [comment] 2016-10-16 16:32
the bug needs an improvement for old applications and this fix will be release in a future release. Use X11 atm for irrlicht games

**Comment by est31** [comment] 2016-10-27 00:26
I've heard from a source that kwin has got pointer confinement and relative pointer events implemented as of ~3 weeks ago, and will ship in 5.9.

**Comment by est31** [comment] 2016-10-27 03:23
So, I've installed fedora rawhide 26 now, with Xorg 1.19 and all that, and tried whether the pointer warp simulation would work... turns out it doesn't give a convincing gameplay experience. So unless I did something wrong, this doesn't work (yet).

**Comment by jadahl** [comment] 2016-10-27 04:35
What exactly is the issue? I just installed Minetest and except for some unrelated graphics glitch, the walking around part (mouse look), which I assume this issue is about, worked just fine.

**Comment by nerzhul** [comment] 2016-10-27 05:45
This issue is not a minetest issue but should be fixed in a future XWayland release

**Comment by est31** [comment] 2016-10-27 20:17
On an updated fedora 25 beta box, I can confirm that mouse look on wayland is working now, making minetest playable.

It isn't perfect though, as when I move the mouse fast in circles, I see that its jumpy, while on X11 the movement is much smoother. Probably the values get updated for Xwayland's warping simulation less often than the FPS rate (right now we warp at every frame AFAIK). Also, just as the patches by @jadahl said, it seems that moving the cursor too fast to the right or to the left will make the cursor leave the window, which is a bit bad when playing minetest not in full screen. Probably this problem gets more serious the lower the framerate is.

But these things are minor bugs, and the main one (spinning frustum) can be considered fixed now, at least on fedora 25.

Great work @jadahl for adding the warp simulation. It would be great if you could fix those two issues as well.

**Closed by est31** 2016-10-27 20:17 UTC
Labels: @ Client / Audiovisuals, Bug, Upstream issue

**Comment by jadahl** [comment] 2016-10-28 01:24
With jumpy, could this simply be worse performance? Worse performance than on plain X should be expected right now.

About the pointer leaving the window if you move the mouse too fast, that sounds like a bug, thanks.
