### ISSUE TITLE
Invisible vertical faces of liquids

### ISSUE THREAD

**Issue by RichardTry** [minetest/minetest#10604] opened 2020-11-05 17:30 UTC
##### Minetest version
```
Minetest 5.3.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/games/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

##### OS / Hardware
Operating system: Debian 10
CPU: AMD Ryzen 3 2200G with Radeon Vega Graphics

##### Summary
OpenGL version: 4.6

##### Summary
Vertical faces of liquids are not visible from the inside:

![screenshot_20201105_203611](https://user-images.githubusercontent.com/16964020/98276196-ad739f00-1fa6-11eb-9a6b-f47cacf1822e.png)
![screenshot_20201105_202212](https://user-images.githubusercontent.com/16964020/98275222-76e95480-1fa5-11eb-8836-9c8ab930c10d.png)

Suspect that this was done to be able to see far away inside the liquid, but it looks weird.

**Comment by paramat** [comment] 2020-11-05 17:57
This is a MTG issue and a duplicate of https://github.com/minetest/minetest_game/issues/2560
It is intentionally chosen to be this way in MTG, it is not an engine bug.

**Closed by paramat** 2020-11-05 17:57 UTC
Labels: Duplicate
