### ISSUE TITLE
Minetest client memory leak

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5740] opened 2017-05-09 19:44 UTC
While playing on Hometown* multiplayer server I've noticed steady increase in memory usage.

To confirm that I found a spot (194 13.5 -374 yaw 39.5) on my base to observe big chunk of surrounding area with v_range 160 and afked it for many hours with very little activity around me.

Results:
Minetest client (de028fc) steadily eats about 100-200+ mb/hr of memory on my Win7sp1 pc.

Mem usage:
20:40 - 0.9 gb
22:17 - 1.2 gb
22:32 - 1.3 gb
23:00 - 1.4 gb
Now active exploring
at ~23:10 mem peak near 2.6gb
and back to afk spot on my base
at ~23:20 unloaded back to 2gb
continue leaking
23:45 - 2.2gb
00:36 - 2.3gb

I'm running those **CSM** mods:
+ chat6 (https://github.com/cheapie/chat6)
+ inspect (https://github.com/bigfoot547/csm-inspect)
+ oredetect (https://github.com/DS-Minetest/oredetect)

Graph from process explorer (win 7), time span is about 1hr 30 minutes, first graph starts somewhere in beginning of 21:00:
![default](https://cloud.githubusercontent.com/assets/16494741/25869436/f9fcbf1e-3508-11e7-8e68-58efab02668e.png)
continuation
![1](https://cloud.githubusercontent.com/assets/16494741/25873017/797aff6a-3515-11e7-9a0b-33820e5a50f7.png)
continuation 2
![2](https://cloud.githubusercontent.com/assets/16494741/25873023/7d342a8c-3515-11e7-9e19-a1f26038d7bf.png)

AFK spot view (notice some animated nodes):
![default](https://cloud.githubusercontent.com/assets/16494741/25871651/f615322a-3510-11e7-9e09-ed7fc6350ec7.png)

* 0.4.15-dev, homedecor, mobs_redo, but without technic or mesecons

Config:
```
anisotropic_filter = true
bilinear_filter = false
creative_mode = false
enable_damage = true
enable_waving_leaves = true
enable_waving_plants = true
fast_move = true
free_move = false
leaves_style = fancy
mainmenu_last_selected_world = 5
maintab_LAST = multiplayer
menu_last_game = minetest
mip_map = true
node_highlighting = box
server_announce = false
server_dedicated = false
trilinear_filter = false
viewing_range = 160
fps_max = 100
address = hometownserver.com
remote_port = 30000
mg_name = v6
tone_mapping = false
mainmenu_last_selected_TP = 1
noclip = false
texture_path = 
sound_volume = 0.68
enable_shaders = false
fog_start = 0.7
enable_bumpmapping = false
enable_parallax_occlusion = false
enable_waving_water = false
generate_normalmaps = false
smooth_lighting = true
world_config_selected_mod = 4
fixed_map_seed = 
enable_local_map_saving = false
minimap_shape_round = true
mesh_generation_interval = 15
port = 30000
fsaa = 0
enable_client_modding = true
time_speed = 1
wieldview_node_tiles = false
wieldview_update_time = 2
autosave_screensize = false 
```

**Comment by Zeno-** [comment] 2017-05-10 09:23
Is that a leak? massif (although you need linux) showed no leaks last I checked. But I'll check again

**Comment by nerzhul** [comment] 2017-05-10 21:42
@Zeno- yeah i don't see any links with valgrind last time i checked, maybe having the server and position can help ?

**Comment by Fixer-007** [comment] 2017-05-11 11:16
You can connect to that server and come to that coordinates, I will open a door for you.

**Comment by ExeterDad** [comment] 2017-05-11 12:43
@Fixer-007 You still running any of those client side mods?

**Comment by Fixer-007** [comment] 2017-05-11 14:29
Yes

**Comment by Fixer-007** [comment] 2017-05-17 22:39
Did another play on Hometown, ended up with over 3Gb of used memory by the process, exited to the main menu, and... memory usage stuck at 3GB, it simply does not unload nor fluctuate (I waited for over 20 minutes without any luck).

**Comment by paramat** [comment] 2017-05-18 00:33
Something to do with https://github.com/minetest/minetest/commit/582ee15d8e861efb9cc843963a95c087dae91bcc ? Fixer confirms server has that commit.

**Comment by ExeterDad** [comment] 2017-05-18 03:31
@Fixer-007 
minetest_0.4.15-dev-20170517_amd64.deb
commit 9b5effffbb0599f85014b53c3fd025b6a8222e02

Just built it and will be live at restart (1H, 30M from now)
And it's debug

**Comment by nerzhul** [comment] 2017-05-18 05:32
@paramat 582ee15 is only for client and only remove the leak when leaving world, there is no leak there

**Comment by paramat** [comment] 2017-05-18 05:33
Ok, thought so.

**Comment by Zeno-** [comment] 2017-05-18 06:10
Trying to collect some massif data now (connected to that server)

**Comment by Zeno-** [comment] 2017-05-18 06:40
Confirmed
![snapshot132](https://cloud.githubusercontent.com/assets/5899883/26189557/9efed5a2-3be8-11e7-8813-9c7f02d73748.png)

**Comment by Zeno-** [comment] 2017-05-18 07:07
Joining server and doing *nothing at all*, just standing at the join location

![snapshot134](https://cloud.githubusercontent.com/assets/5899883/26190362/60d06080-3bec-11e7-9730-4ea33817c544.png)

**Comment by paramat** [comment] 2017-05-18 07:15
^ These are both the mapblock mesh data caches?

**Comment by nerzhul** [comment] 2017-05-18 08:05
@Zeno- i think you should wait for some hours, here the consumed memory is not very huge

**Comment by Zeno-** [comment] 2017-05-18 09:50
I can do that
But, the division by a denominator > 1.0 in the line I mentioned in chat kind of worries me

**Comment by paramat** [comment] 2017-05-18 10:05
Yeah i looked but do not understand it yet.

**Comment by GreenXenith** [comment] 2017-05-18 14:44
Lagging horribly today. Seems to be getting worse.

**Comment by Fixer-007** [comment] 2017-05-18 15:01
He probably runs debug build under gdb, that's why so slow.

**Comment by ExeterDad** [comment] 2017-05-18 16:37
I just ditched the debug for release. No gdb at all. debug.txt well over a gig in 10 hours. Release didn't help. The debug.txt is flooded with 
WARNING[Server]: WARNING: minetest.setting_* functions are deprecated.  Use methods on the minetest.settings object.
Up to roughly a hundred times a second.
Unrelated but this may affect your test results @Fixer-007 and @Zeno-

**Comment by paramat** [comment] 2017-05-19 06:19
> WARNING[Server]: WARNING: minetest.setting_* functions are deprecated. Use methods on the minetest.settings object.

Harmless but annoying.

**Comment by nerzhul** [comment] 2017-05-20 06:16
It's now fixed, thanks @Zeno-

**Closed by nerzhul** 2017-05-20 06:16 UTC
Labels: Blocker, Bug

**Comment by Fixer-007** [comment] 2017-05-21 12:59
I did some limited testing, mem usage seems to be within norm now. Big thanks to everyone involved.
