### ISSUE TITLE
Hide navigation bar on devices with an on-screen navigation bar

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2736] opened 2015-05-29 04:33 UTC
Please hide the menu keys (home button, back button, etc.) on devices that support this (have on-screen menu buttons.) This will intensify the fullscreen effect and give more room for Minetest on the screen...

**Comment by Wayward1** [comment] 2015-05-29 14:27
Yes, please. I would very much enjoy having the entire screen devoted to Minetest.

Example:
![screenshot_2015-05-23-22-21-37](https://cloud.githubusercontent.com/assets/8821916/7884593/00db3420-05ed-11e5-8a65-85499324c8d0.png)

**Comment by est31** [comment] 2015-05-29 15:37
Interesting, this doesn't happen on my device.

**Comment by nanepiwo** [comment] 2015-05-30 03:13
On my device, the menu keys are actually shown as usual. 
![screenshot_2015-05-29-23-12-52](https://cloud.githubusercontent.com/assets/10261530/7895399/46e0fb92-0658-11e5-98f1-994d30991ea8.png)

**Comment by Wayward1** [comment] 2015-05-30 03:24
Same here, until it auto hides.
![screenshot_2015-05-29-23-20-01](https://cloud.githubusercontent.com/assets/8821916/7895413/6eb31f6e-0659-11e5-9eff-6e916e1c3fbd.png)


But then Minetest doesn't compensate.

**Comment by nanepiwo** [comment] 2015-05-30 03:51
Mine don't autohide, or I've been so busy playing I haven't noticed :D

**Comment by nanepiwo** [comment] 2015-05-30 03:55
I found this, may be useful, though I haven't checked the current code. https://developer.android.com/reference/android/view/View.html#SYSTEM_UI_FLAG_HIDE_NAVIGATION

**Comment by MoNTE48** [comment] 2015-11-19 23:11
Either option does not work for me. Buttons can be hidden when you start NativeActivity, but if I pull them one time, they will no longer be hidden and the screen of the game will be located under the buttons and will not be available. It seems to me, Minetest is not able to change the resolution for Android during operation.

**Comment by KarlHegbloom** [comment] 2015-12-08 16:13
Boom Beach and Clash of Clans hide the menu bar,  I can drag it onscreen,  and it hides again. Maybe yous can contact them and find out how they did it?

**Comment by rubenwardy** [comment] 2015-12-08 18:36
They wouldn't respond.

**Comment by KarlHegbloom** [comment] 2015-12-08 18:41
Seriously? I just suggested it not that long ago like only an hour or two?
Have you tried to contact them previously?

**Comment by rubenwardy** [comment] 2015-12-08 18:52
They're a proprietary company with thousands of clients - why would they take the time to answer a request from an open source project? You could try asking a developer personally, but I still doubt they'd answer.

At a guess they probably look for swipe downs and then cause it show themselves: http://developer.android.com/training/system-ui/status.html

**Comment by KarlHegbloom** [comment] 2015-12-10 21:47
I sent them a message and the person who replied had misunderstood me. I
sent a response making it clear that I was asking for one of their software
developers to come and help us. We'll see if they do. I bet that they like
Minetest just as much as we do.

**Comment by MoNTE48** [comment] 2016-04-25 20:50
I did it in MultiCraft. It was quite difficult (fuck eyed definition screen resolution), but it now works perfectly. Only for Android 4.4+

**Comment by KarlHegbloom** [comment] 2016-04-25 22:05
Please share the secret.

**Comment by MoNTE48** [comment] 2016-04-25 22:12
There are no secrets, it's LGPL https://github.com/MultiCraftProject/MultiCraft/tree/master/build/android/src/mobi/MultiCraft

**Comment by est31** [comment] 2016-04-25 22:12
But the wrong version :) We need @MoNTE48 to agree before it can be merged into minetest.

**Comment by MoNTE48** [comment] 2016-04-25 22:17
@est31, I know. I was asked what is the secret, I said. Nobody asked me to add my implementation in minetest yet.

**Comment by DonBatman** [comment] 2016-04-25 22:47
@MoNTE48 Could you please add it to minetest?

**Comment by MoNTE48** [comment] 2016-04-25 22:55
@DonBatman, you see, the problem is that the Java part of minetest is ... full by shit. In MultiCraft all of this code has been completely rewritten, and I have no desire to go back and try to combine my code with java code Minetest.
The ideal would be to transfer all my java code in Minetest, but I do not see that developers Minetest were on my side. At the same time sapier not interested in continuing the work now.

**Comment by KarlHegbloom** [comment] 2016-04-25 23:26
Can you please point out the specific piece of code that makes the on
screen controls hide while playing? At least there will be then a reference
to it in this mail archive in case somebody has time someday to port it
in... it would be best if somebody who already knows a lot about it could
do it. I bet it is a simple enough feature that an experienced developer
can fix it in a short work sprint.

**Comment by KarlHegbloom** [comment] 2016-04-25 23:29
Ok, it's obvious. MainActivity.java, makeFullscreen. It's simple,  right? Is all it takes setting those flags?

**Comment by MoNTE48** [comment] 2016-04-25 23:32
Yes, but you'll need to set it several times in different files (for example, after entering text or after the abolition of the text)

**Comment by ShadowNinja** [comment] 2016-08-03 23:24
As Wayward1 pointed out, this is fixed by a commit in #4046: aba5bccb5147e6dc9356fcd94421426915e289b7

**Comment by paramat** [comment] 2017-09-13 03:51
ShadowNinja is absent so is anyone interested in applying that commit?
If not closing in 1 month.

**Comment by Wayward1** [comment] 2018-02-19 19:55
I've successfully applied that commit here: https://github.com/Wayward1/minetest/blob/immersive-mode/build/android/src/main/java/net.minetest.minetest/MtNativeActivity.java. I've tested it and it works as intended, although once the bar is hidden the text inputs don't adjust correctly, causing any touch events to take place below the intended target, where the intended target actually was before the bar was hidden. I'm assuming this is due to Minetest not being able to change resolution on Android after starting as MoNTE48 [mentioned](https://github.com/minetest/minetest/issues/2736#issuecomment-158229530) above.

**Comment by stujones11** [comment] 2018-07-04 20:52
I do have an idea how to fix this, I just need to figure out where screen resize is handled. AFAIK, Irrlicht does not provide any events for this so it must be polled from somewhere in the main rendering loop.

**Comment by MoNTE48** [comment] 2018-07-04 20:56
@stujones11 please, look my code
https://github.com/MultiCraftProject/MultiCraft/blob/master/build/android/src/main/java/mobi/MultiCraft/GameActivity.java#L34
https://github.com/MultiCraftProject/MultiCraft/blob/master/build/android/src/main/java/mobi/MultiCraft/GameActivity.java#L38
https://github.com/MultiCraftProject/MultiCraft/blob/master/build/android/src/main/java/mobi/MultiCraft/GameActivity.java#L46
https://github.com/MultiCraftProject/MultiCraft/blob/master/build/android/src/main/java/mobi/MultiCraft/GameActivity.java#L62

**Comment by paramat** [comment] 2018-12-03 02:50
Done by #7820

**Closed by paramat** 2018-12-03 02:50 UTC
Labels: Android, Feature request
