### ISSUE TITLE
Inventory list: inv:set_list() not working anymore according to docs

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#13490] opened 2023-05-10 02:26 UTC
##### Obligatory Minetest version

```
Minetest 5.8.0-dev-65692ad1b (Linux)
```

##### OS / Hardware

Operating system: 6.2.6-76060206-generic
CPU: dunno, why?

##### Summary

Use of `inv:set_list("listname", {})` inside `on_metadata_inventory_take` causes error from Lua:

```
Runtime error from mod 'bleh' in callback nodemeta_inventory_OnTake(): InventoryList 'whatev' is currently in use and cannot be deleted or resized.
```

This is a problem, because the docs for `inv:set_list()` state:

```
set full list (size will not change)
```

There's a mod running on my server which expected `inv:set_list()` to do what it *used* to do a couple Minetest versions ago: that is, to set all (or just most) of the itemstacks in a list at once, without changing its size. (IIRC, I think Minetest would clear out the bits of the inventory list not present in the method's table argument, in the case that the table contained too few elements to fill the whole list?)

##### Pedantic steps to reproduce

```
minetest.register_node("invlist:test", {
  description = "Test",
  tiles = {"default_stone.png"},

  on_construct = function(pos)
    local formspec =
      "size[8,2]" ..
      "list[context;test;0,0;8,1;]"..
      "list[current_player;main;0,1;8,1;]"

    local meta = minetest.get_meta(pos)
    meta:set_string("formspec", formspec)

    local inv = meta:get_inventory()
    inv:set_size("test", 5)
    inv:set_stack("test", 5, "default:mese")
  end,

  on_metadata_inventory_take = function(pos, listname, index, stack, player)
    local meta = minetest.get_meta(pos)
    local inv = meta:get_inventory()
    inv:set_list("test", {"default:wood", "default:stick"})
    
    -- It doesn't work even if the number of entries is exactly right >:(
    inv:set_list("test", {"default:wood", "default:stick", "default:apple", "default:chest", "default:tree"})
  end,
})
```

**Comment by sfan5** [comment] 2023-05-10 07:19
dup #13465

**Comment by BluebirdGreycoat** [comment] 2023-05-10 12:25
How is this a dup? The mentioned issue (#13465) was already closed with a merged solution, but I encountered this bug with the latest git pull.

**Comment by Desour** [comment] 2023-05-10 13:07
https://github.com/minetest/minetest/issues/13465 is similar, but it was fixed by allowing resizing in more situations (i.e. if it's the destination in a listring operation).
The non-resizing `set_list()` can, and should still be made to work though.

**Comment by sfan5** [comment] 2023-05-10 13:56
> but I encountered this bug with the latest git pull.

I admit I didn't check the commit hash and assumed that we'd already fixed this entirely.

**Comment by SmallJoker** [comment] 2023-10-15 15:13
Cannot reproduce in current master, either due to #13497 or follow-up PRs.

**Closed by SmallJoker** 2023-10-15 15:13 UTC
Labels: Bug, @ Script API, Regression
