### ISSUE TITLE
Light passes solid nodes

### ISSUE THREAD

**Issue by dsohler** [minetest/minetest#6429] opened 2017-09-17 07:20 UTC
As previously discussed in #5233 light leaks through the edge of solid nodes.

![screenshot_20170215_234138](https://cloud.githubusercontent.com/assets/1668792/22998671/103fce0a-f3d8-11e6-8f17-977d6e210e52.png)
![screenshot_20170215_234141](https://cloud.githubusercontent.com/assets/1668792/22998670/103dee8c-f3d8-11e6-9619-7ca2f7c4c685.png)
![screenshot_20170215_234156](https://cloud.githubusercontent.com/assets/1668792/22998672/10446fc8-f3d8-11e6-9b29-445d01fee896.png)

**Comment by paramat** [comment] 2017-09-18 10:30
In a 'real world' sense there would likely be a narrow gap where the edges of cubes meet, so some light bleed through looks ok to me, although of course it's too bright.
In a mathematical sense the cubes are infinitely thin along the edge where they meet, so it's not a very solid construction and more nodes should be added if a player wants a solid light-impassable construction.
Players need to think of this as 'light passing an infinitely-thin long edge' instead of 'light passing through solid nodes'.

This is probably non-trivial to fix as it probably results from how smooth lighting is calculated from vertices @juhdanad

**Comment by juhdanad** [comment] 2017-09-18 19:44
@paramat it is possible to fix this. You just have to check if no blocks block the light of the neighbor block.

**Comment by Megaf** [comment] 2017-09-18 21:30
Not a bug, it's a feature.
And it is also great for mining to spot lava lakes ahead/above you.
Also great to when you are sculpting a hill or something you can prevent digging the wall.

Anyway, me and my players use this "light leak" as a great tool and we've been doing so for 6+ years.

**Comment by dsohler** [comment] 2017-09-19 19:15
No, this is not a feature. And you know that it is not a feature. Trying to be funny doesn’t help anyone to solve the bug.

So, back on topic. Yes, it is directly linked top smoothed lighting. Here’ß the non-smoothed results.

![1](https://user-images.githubusercontent.com/1668792/30610723-672926b6-9d7f-11e7-979f-c61abb8216d5.png)
![2](https://user-images.githubusercontent.com/1668792/30610724-672ddd8c-9d7f-11e7-8d45-8d1842088aed.jpg)

So light is properly rendered (or not rendered outside). The analogy of the infinitely thin edge does not apply.

**Comment by HybridDog** [comment] 2017-09-20 12:06
There's a similar problem, which doesn't appear naturally in minetest. If you set the light of a node to full brightness (14) and the light next to the node to complete darkness (0, night), the dark node becomes smooth lighted so much that you can't see that the dark node is dark. Without smooth lighting you get a sharp edge.

**Comment by Ezhh** [comment] 2017-09-20 12:31
To me, the node corners meeting up are not a solid structure, so I never thought of them as being something that should block light in full (basically what paramat has said above). If you want a solid diagonal wall, you can add another node there - that's the point light should stop going through. (Stairs can be used to create nice diagonals and I would say a double layer of stairs used for that should not let light through... I'm not sure if it does.)

Changing this would also damage quite a few builds on my servers. I've seen it used time and time again to get nice lighting which creates an atmosphere visible lights can't easily produce. It would be a pity to lose this creativity.

**Comment by dsohler** [comment] 2017-09-20 12:41
> Stairs can be used to create nice diagonals and I would say a double layer of stairs used for that should not let light through... 

Actually a double layer of stairs basically does not affect light at all (no difference if smoothed lighting or the non-smoothed lighting).

![screenshot_20170920_144328](https://user-images.githubusercontent.com/1668792/30644076-7ae045bc-9e11-11e7-9492-1a9d69e8f61b.png)
![screenshot_20170920_144356](https://user-images.githubusercontent.com/1668792/30644077-7ae45b66-9e11-11e7-95de-0c82a1bf64cb.png)

**Comment by Ezhh** [comment] 2017-09-20 12:54
Would be nice if a double layer would stop the light, though at the same time it's such a small issue that it would depend how much is needed to achieve it. 

From discussion I was involved in on IRC about this:
Using a 2D grid for simplicity, for me at least you'd need to account for 8 nodes to totally ring a lightsource, not 4, which is what this issue would aim for, because you don't generally skip the joining corners when building a real container and then expect it to keep anything in.

So I'd have no objections to a double layer of nodes on a diagonal blocking light, but I feel the example in the initial post isn't something that should stop all light - it's simply not a solid structure.

**Comment by dsohler** [comment] 2017-09-20 13:23
See #3554 for that.

**Comment by rubenwardy** [comment] 2017-09-20 13:58
I don't think light escaping through diagonals is a bug necessarily.

However, nodeboxes being required to let light pass even if there's no visible route is. It should be possible to make a nodebox which doesn't let light pass, or in the case of stairs determine which way it can let light pass relative to face dir.

**Comment by paramat** [comment] 2017-09-20 14:58
juhdanad wrote:
> it is possible to fix this. You just have to check if no blocks block the light of the neighbor block.

Ok, but the extra checks slow down smooth lighting even more, it's already intensive, so it would have to be an option, especially since many like the effect. 

dsohler
Correct it was very probably not intended.
> So, back on topic. Yes, it is directly linked top smoothed lighting. Here’s the non-smoothed results.
So light is properly rendered

'Properly' is subjective, i find that looks more weird then light escaping.
Without smooth lighting light does not escape simply due to how non-smooth lighting works. Both behaviours were left as they are for simplicity and because both are reasonable and neither is a big issue.

Ezhh
> Would be nice if a double layer would stop the light,

Maybe we'll fix the other issue, which is higher priority.

**Comment by HybridDog** [comment] 2017-09-20 16:16
> The extra checks slow down smooth lighting even more, it's already intensive

You could cache the calculated lighting.

**Comment by dsohler** [comment] 2017-09-20 16:53
> 'Properly' is subjective,

If a light source is encased in solid nodes then the light should not leak out depending on what light type setting you use.

As long as this is not consistend I say it is a bug.

**Comment by benrob0329** [comment] 2017-09-21 00:51
I agree with @Megaf, light leak is not necessarily a bug, and users (including myself) use it to light things indirectly. Removing it would break quite a few builds, and make lighting things that much harder.

**Comment by jastevenson303** [comment] 2017-09-21 06:16
Count me as one who does not like this, even though I use it to avoid lava and find mese_crystals.  Solid nodes should be dark on the dark side.  Unless they're cheese blocks, but that's different.

**Comment by raymoo** [comment] 2017-09-21 19:44
Have we accidentally implemented subsurface scattering?

**Comment by paramat** [comment] 2017-09-22 03:48
Yes good point about consistency.
To be clear i'm happy for no light leak to be made an option for smooth lighting.

**Comment by benrob0329** [comment] 2017-09-24 03:56
@paramat I'm not, that introduces an inconsistency in the lighting engine of the game **which could change how structures and the world look and act**. This isn't a fancy shading effect, this is basic functionality.

**Comment by paramat** [comment] 2017-09-24 04:48
I did say 'option' and i would insist default disabled. The inconsistency is light leak changing between smooth and non-smooth lighting. However i still think such an option is not high priority.

**Comment by DS-Minetest** [comment] 2017-09-25 15:19
Btw this also happens with darkness.
<details><summary>Example</summary>

```
x = a solid node
o = the camera
l = air with much light
d = dark air

dxxxx
xlllx
xlolx
```
The left edge is darker than the right one.</details>

**Comment by raymoo** [comment] 2017-09-25 18:50
@DS-Minetest Maybe this is how Minetest implements AO? Someone should put out a whitepaper.

**Comment by paramat** [comment] 2017-10-10 19:05
#6490 merged.

**Closed by paramat** 2017-10-10 19:05 UTC
Labels: @ Client / Audiovisuals, Bug, Request / Suggestion
