### ISSUE TITLE
No damage in the fall

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#3858] opened 2016-03-14 16:19 UTC
If, during the fall, press and hold Left Shift, I do not get damage. Tested in single player.

**Comment by C1ffisme** [comment] 2016-03-14 16:24
I think this is a dupe.

**Comment by Fixer-007** [comment] 2016-03-14 17:29
Probably dupe, it is known.

**Comment by est31** [comment] 2016-03-15 07:20
Dupe of #3667

**Closed by est31** 2016-03-15 07:20 UTC
