### ISSUE TITLE
Reshowing formspec prevents receiving events

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10126] opened 2020-06-30 17:11 UTC
##### Minetest version
```
5.2.0
5.3-dev
```

##### Summary
Formspecs which are reshown using `minetest.show_formspec` don't receive events (button presses).

##### Steps to reproduce
Register a form and reshow it (e.g. show it inside a globalstep). Register a corresponding `on_receive_fields` function. Notice that even if pressing a button, the button field is not sent.

**Comment by SmallJoker** [comment] 2020-06-30 18:00
For whatever reason you could possibly run into this issue - please check that the mouse button is also released in the same formspec. Also enable the profiler to figure out whether the client is just laggy due to re-building formspecs nonstop.
Just don't do this.

**Comment by v-rob** [comment] 2020-08-19 04:37
Can't reproduce.  Might be the same internal issue as #10201.

**Comment by SmallJoker** [comment] 2020-08-19 16:38
No reply from the author for longer than a month. Closing.

**Closed by SmallJoker** 2020-08-19 16:38 UTC
Labels: Formspec, Unconfirmed bug
