### ISSUE TITLE
Defining Crack Animation Per Node

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#13349] opened 2023-03-25 12:58 UTC
## Problem

When you dig a node in Minetest, the crack animation that appears on said node is always `crack_anylength.png`.

This isn't very customisable, and the most you can do is just change the crack animation texture itself to look different. You can't really do anything more than that.

## Solutions

Add a `crack_animation` definition to nodes, where one can define textures to be used as the crack animation that appears on said node when you try to dig it.

It would work in a similar manner to how the normal tile definitions of the node work. If nothing is defined in this field, the fallback animation becomes `crack_anylength.png` on all sides.

It would also be a bonus if one could define a separate crack animation for each side of a node, for extra customisability. Another bonus would be allowing overriding this definition in `override.txt`.

## Additional context

For instance, I could then apply a more "splintery" crack animation when you try to break wood, or a more "cracky" crack animation when trying to break stone.

This could have other uses as well, such as allowing someone to fetch a crack animation from a tilesheet, instead of being forced to use a separate texture for this.

**Comment by GoodClover** [comment] 2023-03-25 18:45
Different animations for tool-node combinations would be nice too.
Generalising, some way to set it dynamically from the many digging callbacks the API can scattered around.

**Comment by GoodClover** [comment] 2023-03-25 18:49
Looks like we're a duplicate of #3540
Related may be #11362

**Comment by SmallJoker** [comment] 2023-03-26 20:01
Regardless on detailed descriptions, #3540 came earlier and has a longer discussion history. Hence closing this as duplicate.

**Closed by SmallJoker** 2023-03-26 20:01 UTC
Labels: @ Script API, @ Client / Audiovisuals, Feature request

**Comment by GoodClover** [comment] 2023-03-27 07:18
If you're closing as duplicate then at least reopen the other issue.
