### ISSUE TITLE
proxy configuration ?

### ISSUE THREAD

**Issue by AFCMS** [minetest/minetest#9664] opened 2020-04-14 09:46 UTC
It would be nice to be able to define a proxy server for internet access in the settings panel. This would be useful for connecting to a game server.

**Comment by BuckarooBanzay** [comment] 2020-04-16 05:48
> It would be nice to be able to define a proxy server for internet access in the settings panel. This would be useful for connecting to a game server.

The main game traffic is exchanged as UDP, are there even proxies that support that?

**Comment by sfan5** [comment] 2020-04-16 09:56
This is a duplicate of #7740

**Closed by sfan5** 2020-04-16 09:56 UTC
Labels: Feature request

**Comment by track044** [comment] 2021-01-23 04:40
https://github.com/minetest/minetest/issues/7740#issuecomment-765864399

**Comment by track044** [comment] 2021-01-23 05:34
https://github.com/minetest/minetest/issues/7740#issuecomment-765868328
Try this.
