### ISSUE TITLE
glasslike vs. glasslike_framed backface inconsistency and Z fighting

### ISSUE THREAD

**Issue by Ezhh** [minetest/minetest#7823] opened 2018-10-29 20:54 UTC
##### Issue type
 - Bug report

##### Minetest version
Current stable and dev

##### Summary

This is really two issues rolled into one:

~1. When placing a glasslike_framed node against another node, you get Z fighting for the visible backface of the glasslike_framed node.~ EDIT by paramat: Fixed.
2. When using the glasslike drawtype you don't see the back face, whereas for glasslike_framed you do. Why do we have this inconsistency? 

Comparison of drawtypes;
![glassyframe](https://user-images.githubusercontent.com/7035183/47679102-4eab0c00-dbbb-11e8-8a4f-f3c2f50c3598.png)

glasslike_framed backface flickering (sorry if it's a bit hard to see, but it should be possible to make out some parts of the texture switching between visible and not as the camera moves):
![glassupanddown](https://user-images.githubusercontent.com/7035183/47679455-34bdf900-dbbc-11e8-88f3-d9ac45309453.gif)

**Comment by paramat** [comment] 2018-10-29 21:17
@numberZero 
I agree that there should be backface culling for the 'detail' textures of glasslike_framed (not the frame obviously, as that is likely impossible to hide).
The lack of backface culling combined with a face being rendered when against a node causes the z-fighting, a bit like how water used to z-fight with a nodebox face until recently.

**Comment by paramat** [comment] 2018-10-29 21:34
I'm guessing it is this way because the frame around a backface is visible so someone made the 'detail' visible too.

**Comment by Ezhh** [comment] 2018-10-29 21:59
Even the frame being visible by itself is inconsistent with the glasslike drawtype. This is not just about whether the detail texture is visible. Look at my first screenshot more closely.

**Comment by paramat** [comment] 2018-10-29 23:11
Yes. I suspect that the frame cannot be hidden easily because many of the frame faces are front faces not backfaces. I expect users many like seeing the full frame, hiding it may be unpopular. Being a frame around glass, seeing all the frame makes some sense too.

**Comment by paramat** [comment] 2018-10-30 02:09
https://github.com/minetest/minetest/blob/88ba1c70d33cfeb09b73e46d720099083925c805/src/content_mapblock.cpp#L694
Interestingly the glass faces are inset a little compared to a normal cube, maybe an attempt to avoid z-fighting?:
https://github.com/minetest/minetest/blob/88ba1c70d33cfeb09b73e46d720099083925c805/src/content_mapblock.cpp#L721
https://github.com/minetest/minetest/blob/88ba1c70d33cfeb09b73e46d720099083925c805/src/content_mapblock.cpp#L738
Altering that `0.003` might remove the z-fighting.

**Comment by paramat** [comment] 2018-10-30 03:17
Ha just found an undocumented feature:

![screenshot_20181030_031546](https://user-images.githubusercontent.com/3686677/47693615-4621f800-dbf2-11e8-8734-a551e658c860.png)

From looking at the code:
https://github.com/minetest/minetest/blob/88ba1c70d33cfeb09b73e46d720099083925c805/src/content_mapblock.cpp#L701

**Comment by paramat** [comment] 2018-10-30 03:31
In older versions of MT the code was:
```
			if (tiles[1].texture && tiles[2].texture && tiles[3].texture) {
				glass_tiles[0] = tiles[2];
				glass_tiles[1] = tiles[3];
				glass_tiles[2] = tiles[1];
				glass_tiles[3] = tiles[1];
				glass_tiles[4] = tiles[1];
				glass_tiles[5] = tiles[1];
			} else {
				for (i = 0; i < 6; i++)
					glass_tiles[i] = tiles[1];
			}
```
Tiles 2 and 3 (if provided) were used for top and bottom.

**Comment by paramat** [comment] 2018-10-30 03:36
![screenshot_20181030_033535](https://user-images.githubusercontent.com/3686677/47694277-eed15700-dbf4-11e8-89ab-a438a26fa493.png)

That's better, will fix and document.

**Comment by Ezhh** [comment] 2018-10-30 08:42
> I think the flicker you see is due to using alpha for your glass, alpha is known to cause flicker.
> So there's no bug in issue 1.

This bug is present on glass without alpha as well. This is NOT an alpha related bug.

**Comment by paramat** [comment] 2018-10-31 06:49
Ok thanks for the correction.

**Comment by paramat** [comment] 2018-10-31 07:30
Seen it, only happens with basic shaders enabled, which is why i didn't see it before.

**Comment by paramat** [comment] 2018-10-31 07:43
Confirmed that the value of `g` affects this, with `g = a - 0.001;` the glass faces glitch easily:

![screenshot_20181031_074146](https://user-images.githubusercontent.com/3686677/47773041-a2634580-dce0-11e8-945d-f71cccc311db.png)

**Comment by paramat** [comment] 2018-10-31 10:12
#7826 merged.

**Comment by VanessaE** [comment] 2018-10-31 15:59
Don't forget to fix these glitches in 0.4.x, also, please.

**Comment by paramat** [comment] 2018-10-31 16:45
I expect for 0.4.18 we will go through all bugfixes since 0.4.17.1 and apply them.

**Comment by numberZero** [comment] 2018-10-31 18:16
Am I right the bug remaining here is
> Confirmed that adding 'backface_culling = true' to the 'default_glass_detail.png' tile does not backface cull.

? I see the probably cause: `drawAutoLightedCuboid(glass_faces[face]);` (line 801). It draws an entire cuboid for each node face! I don’t remember how could that happen, should be fixed.

**Comment by paramat** [comment] 2018-11-01 09:46
numberZero yes that is the remaining bug.
I did see 'draw cuboid' called for each face and now realise how weird that is. I'll see if i can fix that.

**Comment by paramat** [comment] 2018-11-01 11:01
The old code seemed to do the same:
https://github.com/minetest/minetest/blob/231ac33d34dfaaddf292c5f31b1eae43eeefba2d/src/content_mapblock.cpp#L974

**Comment by paramat** [comment] 2018-11-01 11:41
Ah! It works when smooth lighting is used.

**Comment by paramat** [comment] 2018-11-01 12:15
PR #7823

**Comment by numberZero** [comment] 2018-11-01 21:18
^ PR #7828, I suppose =)

**Comment by paramat** [comment] 2018-11-15 18:47
#7828 merged.

**Closed by paramat** 2018-11-15 18:47 UTC
Labels: @ Client / Audiovisuals, Bug, Request / Suggestion
