### ISSUE TITLE
Relief Mapping causes floor waves

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#9243] opened 2019-12-24 17:17 UTC
##### Minetest version
```
Minetest 5.2.0-dev-37f771a9-dirty (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/local/share/minetest"
```

##### OS / Hardware
Operating system: linux
CPU: intel

GPU model: intel
OpenGL version: 4.5

##### Summary

I think that Parallax Occlusion in Relief Mapping mode (the default mode) does not work well together with fastfaces:
![fast](https://user-images.githubusercontent.com/3192173/71370717-0e70cf00-25af-11ea-8ac6-182ba4c85588.jpg)
![fast_w](https://user-images.githubusercontent.com/3192173/71370718-0e70cf00-25af-11ea-8583-7546283fbacb.jpg)
![nofast](https://user-images.githubusercontent.com/3192173/71370719-0f096580-25af-11ea-8d1c-908cbb4ae460.jpg)
![nofast_w](https://user-images.githubusercontent.com/3192173/71370720-0f096580-25af-11ea-8e2d-97a6ed9aa548.jpg)

If you place a single node, the 3D surface looks fine, but when there is a fastfaces stripe, it looks distorted.
If you strafe along the stripe direction, it looks like the floor is slowly going up and down.

##### Steps to reproduce

Enable Parallax Occlusion, set parallax_occlusion_scale to 0.3, use this texture pack: https://github.com/HybridDog/HybridTP, and place bricks.
The bricks should look protruded as shown on the screenshots above.

**Comment by SmallJoker** [comment] 2019-12-24 20:01
Duplicate of #6694 ?

**Comment by HybridDog** [comment] 2019-12-25 10:09
> Duplicate of #6694 ?

No, that issue is about the `scale` field in the tile definition. This one is about textures repeated via fastfaces and the distorted Relief Mapping. Nonetheless, the bugs are probably related to each other.

**Comment by Warr1024** [comment] 2020-01-01 03:30
Is this related to the "jiggling textures" bug?  This screencap was sent by one of my players.  The changing light levels nearby cause the mapblock geometry to change (since light falloff is baked into textures) which causes textures to shift.  You can see the same effect when you start digging a node, as the introduction of the crack texture also changes the block tessellation.

![demo](https://user-images.githubusercontent.com/324806/71637856-2b477b00-2c1d-11ea-9364-82f06209fdab.gif)

**Comment by HybridDog** [comment] 2020-01-01 11:46
> Is this related to the "jiggling textures" bug?

Yes it is. When neighbouring nodes have different light values, fastfaces are not used at those positions:
![2020-01-01-124146_974x615_scrot](https://user-images.githubusercontent.com/3192173/71640954-70f35a80-2c94-11ea-9960-00f78e8ea614.png)
![2020-01-01-124148_974x615_scrot](https://user-images.githubusercontent.com/3192173/71640955-73ee4b00-2c94-11ea-8cdf-2ebe58875f8e.png)

**Comment by hecktest** [comment] 2020-01-11 08:38
I've had something like this happen in another project of mine, the problem was malformed tangent space and varying texel density. Accounting for those things in the meshgen and the shader should fix it. There's no inherent reason why parallax occlusion should not work on arbitrary geometry.

**Comment by SmallJoker** [comment] 2021-01-16 08:44
Parallax occlusion removed, see #10479.

**Closed by SmallJoker** 2021-01-16 08:44 UTC
Labels: @ Client / Audiovisuals, Shaders, Unconfirmed bug
