### ISSUE TITLE
hidden CMD [feature request]

### ISSUE THREAD

**Issue by DanHolli123** [minetest/minetest#4989] opened 2017-01-04 00:26 UTC
It would be nice to have a command line or config option to hide the command prompt in windows as it is another window to mess with when using alt-tab
or if there were an entirely different executable as I'm also trying to get the steam overlay to work with it too

**Comment by rubenwardy** [comment] 2017-01-04 01:05
Duplicate of #4210

**Closed by rubenwardy** 2017-01-04 01:05 UTC
