### ISSUE TITLE
Unit test fails: SIGFPE (divide by zero?!)

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#4910] opened 2016-12-14 18:59 UTC
```
======== Testing module TestRandom
[PASS] testPseudoRandom - 0ms
[PASS] testPseudoRandomRange - 1ms
[PASS] testPcgRandom - 0ms

Thread 1 "minetest" received signal SIGFPE, Arithmetic exception.
0x00000000008a54d2 in PcgRandom::range (bound=0, this=0x7fffffffcab0) at /home/ahkok/git/minetest/src/noise.cpp:102
102		u32 threshold = -bound % bound;
```

Code in question says `-bound % bound` but `bound=0` which is illegal.

This most certainly needs to pass for 0.4.15.

**Comment by sofar** [comment] 2016-12-14 19:04
@est31 #3027

**Comment by est31** [comment] 2016-12-14 19:17
Why did it suddenly start failing? There is something fishy going on here...

@kwolekr do you have any ideas? noise.cpp is your domain...

**Comment by sfan5** [comment] 2016-12-14 19:58
duplicate of #4810

Also it's just the unittests, everything else seems to work fine

**Closed by sfan5** 2016-12-14 19:58 UTC
Labels: Bug, High priority, Testing
