### ISSUE TITLE
Game-provided menu music

### ISSUE THREAD

**Issue by benrob0329** [minetest/minetest#8596] opened 2019-06-13 05:27 UTC
##### Issue type
 - Feature request
 
##### Minetest version

```
5.0.1
```

##### Summary
We have main menu music, but it's for the engine and isn't used. This has been mentioned several times but not put into it's own issue yet afaik.

Relevant code seems to be here https://github.com/minetest/minetest/blob/6cb6aea969032e43395ddbad09233e7e20830909/src/gui/guiEngine.cpp#L100

**Comment by DS-Minetest** [comment] 2019-06-13 11:38
(Nobody uses this anyway, as the starting time increases massively.)

Imo subgame specific main menu music shouldn't replace the general main menu music.

**Comment by benrob0329** [comment] 2019-06-13 17:54
But no one uses main menu music, heck I don't think most people even know it exists.

**Comment by LoneWolfHT** [comment] 2019-06-13 18:09
> But no one uses main menu music, heck I don't think most people even know it exists. If people haven't used general menu music up until this point, I don't see why maintaining compatibility with it is important.

I didn't know it existed. But I might use it if I knew where to put the music

Subgame-specific music is supported too? :open_mouth:

**Comment by paramat** [comment] 2019-06-13 18:48
:+1: good issue.

As discussed a while ago with RBA who wanted MT engine music (which was a silly idea):

The engine cannot have music because all content is provided by games.
Every game requires different music.
The engine cannot have music because it is completely neutral and characterless.
The main menu, rightly, has backgrounds provided by the currently selected game, so should also have music provided the same way.
When MT starts it instantly presents game content, there is no time for the engine to present content.
The idea of the engine having music comes from misunderstanding the engine as some sort of game.

If anyone uses the current folder for music, that should be moved to a game, there are no compatibility issues because mods and games currently can't contain music. So i suggest removing the engine sounds folder.

**Comment by DS-Minetest** [comment] 2019-06-13 20:32
Blank minetest does have sort of a "character", there are clouds in the background and a bright blue sky. If it had no character, everything would have to be completely transparent so that you see your dektop background. Also it wouldn't be so nice if it was impossible to set a music for other tabs than singleplayer.
Anyway, #7139 should have a much higher priority.
And isn't this a duplicate of  #7867?

**Comment by Linuxdirk** [comment] 2019-06-13 20:56
> When MT starts it instantly presents game content (menu backgrounds), there is no time for the engine to present content.

No games installed but still clouds in the background.

![s](https://user-images.githubusercontent.com/46120351/59466564-e4836680-8e2d-11e9-822f-f7111b34fc7a.jpg)

> The engine cannot have music because it is completely neutral and characterless.

Well, it provides a default background when there are no games available. Why shouldn’t it provide default menu music when there are no games available?

**Comment by paramat** [comment] 2019-06-14 00:01
Some good points.
I didn't realise the game menu background doesn't appear in tabs other than 'start game', some of my points are therefore wrong.

However, i don't agree that the engine can have music, we've gone through this argument before at great length with RBA and it's impossible to choose anything, it's very different to visuals so it can't be paralleled. If there are no games i think there should be no music.
So perhaps game music is only played in the 'Start Game'? However i'd also be fine with it being played in all tabs.

**Comment by paramat** [comment] 2019-06-14 00:05
Not sure if a duplicate of #7867 as that may be for in-game music only.

**Comment by paramat** [comment] 2019-06-14 00:42
People's taste in music is very fussy and individual. Whatever you chose, 50% would dislike it, 45% would be 'meh' and 5% would like it.

So there are some things to consider:
Which tabs it is played in?
As game content it would be downloaded as you connect to a server, so it may need to be handled differently.
I'll change the issue title to be more general.

**Comment by benrob0329** [comment] 2019-06-14 03:16
I think that if game-specific music is cut off when switching tabs, that it should fade in and out so as not to cause a sudden change in volume or tone.

**Comment by jastevenson303** [comment] 2019-06-14 16:45
It should be a startup sound (oneshot), not a whole song (loop).

I like the fade in/out suggestion in case it is a loop though.
minetest.fade_sound might work, maybe.

**Comment by benrob0329** [comment] 2019-06-15 00:27
Let's not over complicate this and try to make game-writers have to break and split and make music themselves. Most will be doing well to use premade music for things like this.

**Comment by jastevenson303** [comment] 2019-06-15 01:18
My point is that it doesn't have to be a whole song.  It can be a single sound that plays upon the game's selection.  (An example is when selecting a title on the 3DS' main menu.)
>Let's not over complicate this and try to make game-writers have to break and split and make music themselves.

I don't expect game creators to break and split and make music themselves.  It does sound like a fun exercise though, and something a group of game creators could do together.

**Comment by TumeniNodes** [comment] 2019-06-29 02:22
I don't really care about music for the menu system... I'm much more concerned about adding clickity, clackity sounds when hitting buttons, etc..
This to me _that_ is far more important and desired for a menu system.
Music should be focused on for during play (and subtly playing in the background) (just my own opinion)

**Comment by rubenwardy** [comment] 2022-05-15 14:01
Implemented by #11241

**Closed by rubenwardy** 2022-05-15 14:01 UTC
Labels: @ Client / Audiovisuals, Sounds, @ Mainmenu, Supported by core dev
