### ISSUE TITLE
Line Break in Description

### ISSUE THREAD

**Issue by RonnyBarthmann** [minetest/minetest#6506] opened 2017-10-07 10:22 UTC
There no Char to add Line Break in the Server Description

**Comment by SmallJoker** [comment] 2017-10-07 10:39
Dupe of #5392

**Closed by SmallJoker** 2017-10-07 10:39 UTC
Labels: Duplicate

**Comment by sfan5** [comment] 2017-10-07 10:48
This is not necessarily a duplicate because this might need explicit support in the mainmenu and/or serverlist.

**Comment by SmallJoker** [comment] 2017-10-07 11:16
The server description is shown in a `textarea[` which should support the new line character, once it is supported in the configuration.
Adding a special character to force new lines while not being able to use multiple lines in the settings file sounds wrong to me.

**Comment by RonnyBarthmann** [comment] 2017-10-07 16:21
if i write
`server_description = [[
line1
line2
line3
]]`

only `[[` is showed in the Serverlist

**Comment by DS-Minetest** [comment] 2017-10-08 11:34
@RonnyBarthmann `server_description = line1\nline2\nline3`
