### ISSUE TITLE
player:set_properties() rests the animation

### ISSUE THREAD

**Issue by theFox6** [minetest/minetest#7781] opened 2018-10-13 06:29 UTC
##### Issue type
 - Bug report

##### Minetest version
```
Minetest 5.0.0-dev-23cc373c-dirty
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware
Operating system: Debian Linux
CPU: Intel I5
OpenGL version: 3.0 Mesa 13.0.6

##### Summary
I call set_properties({glow=14}) on a player every global step. This causes the animations of the player to break. They seem to be started from the beginning every time set_properties is called.

##### Steps to reproduce
https://github.com/theFox6/useful_contraptions/blob/e4f357b2ab602e49a68eb51bc6966837b2b05707/torch_light.lua#L15

**Comment by SmallJoker** [comment] 2018-10-13 12:03
Duplicate of #6572. Same root cause: not checking whether the model name has changed.

**Closed by SmallJoker** 2018-10-13 12:03 UTC
