### ISSUE TITLE
[Solved] Display issue. Screen won't rotate landscape properly.

### ISSUE THREAD

**Issue by Innomen** [minetest/minetest#8326] opened 2019-03-06 01:21 UTC
Solved, delete folder and reinstall, APP intended for use only in landscape.

##### Issue type

 - Bug report

##### Minetest version

```
5.0.0
```

##### OS / Hardware

Operating system: Android 8.1
CPU: ? Moto g5 plus

GPU model:
OpenGL version:

##### Summary
The menus are crushed in portrait mode, and the entire screen is crushed in landscape.

##### Steps to reproduce
Installing 5.0.0 APK from here:
https://github.com/minetest/minetest/releases

Launch game, (error 1) rotate screen (error 2.)

![screenshot_20190305-201250](https://user-images.githubusercontent.com/134324/53848889-08f4ba80-3f84-11e9-9cc7-6648e20256d5.png)
![screenshot_20190305-201227](https://user-images.githubusercontent.com/134324/53848891-08f4ba80-3f84-11e9-989e-b82eb165fa2f.png)

Previous reports:
https://www.reddit.com/r/Minetest/comments/ah3cl1/anyone_else_having_trouble_playing_this_in/
https://github.com/minetest/minetest/issues/7965

**Comment by paramat** [comment] 2019-03-06 02:36
@stujones11

**Comment by paramat** [comment] 2019-03-06 02:40
@Innomen does this only happen in the main menu?

**Comment by Innomen** [comment] 2019-03-06 02:44
No it's in the main game too, the touch overlay is wrong also when the game is actually running, the movement disc isn't where it's rendered.

![screenshot_20190305-214259](https://user-images.githubusercontent.com/134324/53852361-c89b3980-3f8f-11e9-8fb9-501b5229da83.png)

**Comment by paramat** [comment] 2019-03-06 03:10
Brightness and contrast boosted version of the above:

![bcboost](https://user-images.githubusercontent.com/3686677/53853434-55a8b780-3fbd-11e9-82cd-3f048dc5635b.png)

**Comment by pauloue** [comment] 2019-03-06 03:22
I cannot reproduce with the Play Store beta version. The screen does not rotate to portrait mode. Also I'm using the same phone with the same Android version.

**Comment by Innomen** [comment] 2019-03-06 04:31
Does "not" rotate? Mine rotates but doesn't like it hehe. I should have caught that something was persisting and considered the contents of a folder being a problem. This did help.

Some progress was made but there is still a very similar issue. Landscape mode on the main menu is repaired.

![screenshot_20190305-232901](https://user-images.githubusercontent.com/134324/53856130-b70d5e00-3f9e-11e9-970e-c27d0701d5d2.png)
![screenshot_20190305-232840](https://user-images.githubusercontent.com/134324/53856131-b70d5e00-3f9e-11e9-9239-cc884ea3c8d6.png)
![screenshot_20190305-232710](https://user-images.githubusercontent.com/134324/53856132-b70d5e00-3f9e-11e9-9887-4b219f070485.png)

**Comment by nerzhul** [comment] 2019-03-06 06:36
minetest doesn't rotate in portrait mode, it is fixed in landscape mode, it's strange your phone permit it

**Comment by Innomen** [comment] 2019-03-06 06:56
Oh XD Well, then I guess everything is fixed hehe. I have tap'n'turn installed, maybe that's the reason? https://f-droid.org/en/packages/com.gabm.screenrotationcontrol/

**Comment by nerzhul** [comment] 2019-03-06 06:59
it is i think. mt doesn't permit rotate, if you force yes MT should be bad :)

**Closed** 2019-03-06 07:42 UTC
Labels: Android, Bug
