### ISSUE TITLE
Allowing to change maximum health/breath for players

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2246] opened 2015-02-02 16:31 UTC
Hi! This is a feature request. I request that the _maximum_ health and breath for players can be changed. Currently, both are fixed.

Details are here:
https://forum.minetest.net/viewtopic.php?f=5&t=10347

**Comment by MT-Modder** [comment] 2015-02-02 16:47
:+1: 
Kind of related: https://github.com/minetest/minetest/issues/1972

**Comment by Kalabasa** [comment] 2015-02-02 18:39
:+1:

**Comment by rubenwardy** [comment] 2015-04-20 18:50
I like how Terraria does this. http://terraria.gamepedia.com/Health

> New characters begin with 5 red hearts, or 100 health. Maximum health can be increased using Life Crystals, which add a single red heart each to the health meter permanently, increasing maximum health by 20 each. This can be done until the health meter reaches 20 red hearts (400 health).

**Comment by PilzAdam** [comment] 2015-04-20 18:59
Additionally, a way to multiply all engine-based damage (falling etc.) would be needed, so that e.g. a 100 hp based system can be used by games.

**Comment by 4aiman** [comment] 2015-05-15 13:46
Couldn't this be done lua-side?
Just disable the in-built HP HUD and heal everyone continuously.
Then use your own mechanics to track users HP and draw your own HP bars.
Once a player reaches 0 HP (in your mechanics) - stop healing him and /kill him.
Time_since_last_punch may become somewhat more inaccurate, but running a server on low-end software isn't of the greatest-kind-of-ideas. ;)

At least that's what I would've done if I wanted such a feature.

**Comment by wilkgr76** [comment] 2016-05-17 00:44
@4aiman If something does 20+ damage at once, I think it would still kill the player (I think; please correct me if I'm wrong)

**Comment by C1ffisme** [comment] 2016-05-17 01:05
I agree with @PilzAdam . If you made a game similar to TerraFirmaCraft, and started launching yourself off cliffs, you would only feel miniscule amounts of damage. (Unless you used V7 mapgen, then you might have a bit more trouble.)

It's the same thing with drowning too, although subgames can change things like lava. (I'm not sure if drowning is customizable or not, though.)

**Comment by wilkgr76** [comment] 2016-05-17 01:18
@C1ffisme Think it is.

**Comment by nerzhul** [comment] 2016-05-17 10:32
@4aiman it's a little bit hacky. But we should remove this static stats module to have a dynamic stat storage synced between client and server with custom values

**Comment by rubenwardy** [comment] 2017-08-26 02:39
#1972

**Comment by rubenwardy** [comment] 2017-08-26 02:39
duplicate of #1972

**Closed by rubenwardy** 2017-08-26 02:39 UTC
Labels: @ Server / Client / Env., Feature request, Low priority
