### ISSUE TITLE
Liquid refuses to flow on top of other liquid to +X direction

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5802] opened 2017-05-23 05:46 UTC
If you have a liquid, and in the +X direction of that block is air, the liquid refuses to flow towards +X if below that air block there is a liquid block of a different type.

Illustration with compass:

![Example showing missing liquid flow to -X](https://i.imgur.com/3WVG5vb.png)

This example uses water and river water from Minetest Game. It is the same if I swap their positions. The top liquid never flows.

Proof that this the liquid flow on top of another liquid works in all directions but one:
![Screenshot showing the bug that the liquid refuses to flow into +X](https://i.imgur.com/pTiUuU2.png)

How to reproduce:
* Replicate the glass structure in the 1st screenshot, keep the compass in mind and use debug mode to learn the correct orientation
* First place the bottom liquid, then the top one

According to my tests, this seems independent of subgames. Rotating above build into any other direction makes the top liquid flow.

It doesn't make a difference if either of the liquid is flowing or source:

![Second example of the bug](https://i.imgur.com/ESb6FTw.png)

Tested in: 0.4.15

Probably related bug: https://github.com/minetest/minetest/issues/2399

**Comment by C1ffisme** [comment] 2017-05-23 15:23
I think #2399 is the same bug, actually...

**Comment by Wuzzy2** [comment] 2017-05-23 15:37
I'm not so sure about this. #2399 is more concerned about vertical falling liquids which refuse to flow into _any_ direction when in this special “tower” formation shown at these screenshots in #2399.

In this issue, the liquid refuses to flow to one particular direction (+X).

**Comment by Fixer-007** [comment] 2017-05-23 16:15
>In my issue, the liquid refuses to flow to one particular direction (+X).

I think I've seen this somewhere.

**Comment by Fixer-007** [comment] 2017-05-23 16:49
https://github.com/minetest/minetest/issues/3263 mentions the same problem, it was marked as dupe, so this is a dupe of #2399

**Comment by nerzhul** [comment] 2017-05-23 18:01
duplicates #2399

**Comment by paramat** [comment] 2017-05-23 18:01
This, #3263 and 2399 are closely related issues, same general bug but different examples, best to combine them all in one place.
So this is a semi-duplicate, could you add these posts to that?

**Comment by paramat** [comment] 2019-08-10 18:37
Actually this is not exactly the same as the other issues, so reopening to not lose important bug information..

**Closed** 2020-06-20 21:10 UTC
Labels: Bug
