### ISSUE TITLE
MacOS tab buttons don't respond

### ISSUE THREAD

**Issue by jasikpark** [minetest/minetest#10856] opened 2021-01-23 04:39 UTC
##### Minetest version

```
5.4.0--dev-10.3.6-2f6393f49
```

##### OS / Hardware

Operating system: macOS 11.1
CPU: Intel i5

GPU model:
OpenGL version:

##### Summary

When trying to join a server, I cannot click on many of the menu buttons, the only menu buttons that were slightly responsive were Start Game and Settings, and those required several clicks to get a response.

https://user-images.githubusercontent.com/10626596/105568879-89e90680-5d02-11eb-87ab-ae2e7cf1ae7e.mov

##### Steps to reproduce

Open game, click menu buttons.

This might be related to #10654 since they menu works fine if I do not resize the window, but once I resize the window to fit my screen, the buttons are non responsive.

**Comment by SmallJoker** [comment] 2021-01-23 07:55
Duplicate of #9911

**Comment by rubenwardy** [comment] 2021-01-28 18:14
This has more info than the other issues

**Comment by sfan5** [comment] 2021-05-25 18:47
Does this happen with 5.5.0-dev?

**Comment by SmallJoker** [comment] 2021-07-21 16:08
There weren't many changes in Minetest, but IrrlichtMt.
@jasikpark Would you please be so nice to re-test this bug on 5.5.0-dev? Otherwise I'll go ahead with closing this issue due to lack of user feedback.

**Comment by jasikpark** [comment] 2021-07-21 17:35
Ah, I suppose I can.

**Comment by jasikpark** [comment] 2021-07-21 18:04
Where do I find the download for that? I've forgotten where I got it before and can't find it in Releases.

**Comment by SmallJoker** [comment] 2021-07-21 18:42
@jasikpark I hope these here will work for you: https://forum.minetest.net/viewtopic.php?f=42&t=26521

**Comment by jasikpark** [comment] 2021-07-21 18:53
It works! Both in initial menu size and resized to fit my full screen, nice :) 

Some feedback that belongs in new issues:
- I wish I could turn the resolution down, since I assume it's rendering at full macOS Retina - I don't have external graphics so my fps was terrible, it'd be nice to have something like [retiNO](https://www.curseforge.com/minecraft/mc-mods/retino) built in that will allow limiting the resolution on mac.
- It'd be nice to be able to leave the game after you die (without respawning), instead of only having an option to respawn.

Shadows are cool tho :)

**Comment by sfan5** [comment] 2021-07-21 19:12
Just for confirmation by "It works!" you mean that the tab buttons issue is no longer present?

**Comment by jasikpark** [comment] 2021-07-21 19:34
Yes! The buttons work correctly

**Closed** 2021-07-21 20:04 UTC
Labels: @ Client / Audiovisuals, Bug, Possible close, macOS

**Comment by SmallJoker** [comment] 2021-07-21 20:43
This is not related in any way to the issue but here's some answers @jasikpark 

> I wish I could turn the resolution down

Undersampling: https://github.com/minetest/minetest/blob/master/minetest.conf.example#L600-L605
And specify the DPI manually if everything's too small: https://github.com/minetest/minetest/blob/master/minetest.conf.example#L1122-L1124

> It'd be nice to be able to leave the game after you die (without respawning), instead of only having an option to respawn.

First time hearing that. Just click ESC twice after each other, if your keyboard has such a key.
