### ISSUE TITLE
Travelnets for cross-server use.

### ISSUE THREAD

**Issue by BeverlyCode** [minetest/minetest#13884] opened 2023-10-11 09:04 UTC
### Problem

If I am a server owner, I own multiple servers, it would be great to unify them with a cross-server Travelnet mod (?Worldnet).

### Solutions

Suppose I could as a server owner configure in a mod config file what servers a user could select from for their "Worldnet" when placed.

It would require that the client implements a way for the server to tell it to reconnect to a new IP address and port, repositioning the player could be passed across by the client to the server on reconnect so then the server can decide if that is valid, maybe some signed pub/priv key system is needed here, so if the coordinates supplied by the client are not signed by your server networks private key then it will be ignored as a fraudulent attempt to teleport on connect.

### Alternatives

Just this one solution, a seamless way for clients to hop between servers and player positions on those servers, a list of servers which is controlled, curated, by the server admin.

### Additional context

This would be a real game changer for server admins, it would really help to Unify multiple servers.

With login we can't really keep the old login around to retry on the new connect so just pop a login & register input when they change server, it's better than nothing.

**Comment by rubenwardy** [comment] 2023-10-11 09:23
Duplicate of #5813

**Closed by rubenwardy** 2023-10-11 09:23 UTC
Labels: Feature request
