### ISSUE TITLE
Ability to reconfigure core/server sockets at runtime

### ISSUE THREAD

**Issue by SoniEx2** [minetest/minetest#12475] opened 2022-06-25 17:07 UTC
## Problem

A clear and concise description of what the problem is.
ie: Why is this needed?
Ex. I'm always frustrated when [...]

There's no run-time "open to LAN"/"open to tailscale" feature.

## Solutions

There should be an API to reconfigure core/server sockets at runtime, so that "open to LAN"/etc can be provided by a trusted mod.

## Alternatives

There's really no practical alternative way of implementing this.

## Additional context

N/A

**Comment by Zughy** [comment] 2022-06-25 18:29
Duplicate of #10120 ?

**Comment by SoniEx2** [comment] 2022-06-25 18:49
No, this is for reconfiguring *the* server socket.

The one used to join the game.

**Comment by rubenwardy** [comment] 2022-06-25 19:10
This seems a lot like an [XY problem](https://en.wikipedia.org/wiki/XY_problem), and isn't something that should be added to the modding API. It's dangerous, complicated, and out-of-scope. Which socket the server binds to is very much a server admin / IT thing, not a mod thing.

Access to the server socket wouldn't allow you to implement Open to LAN, as singleplayer mode is a bit more than just sockets - there's also the singleplayer username. Also, **"Host Server" is Minetest's equivalent of "Open to LAN".**

If you wanted to implement Open to LAN in a mod, you could require the player to use Host server and then enforce singleplayer in your mod when your Open to LAN option is disabled.

If you have a more complicated use case, then it would be better to make a program that wraps Minetest to implement it

**Comment by SoniEx2** [comment] 2022-06-25 19:13
It should be possible to open to LAN at runtime.

And also, it should be possible for a locally-installed (trusted) mod to open to "LAN" and configure proxies at runtime. At that point, it's no longer "open to LAN" but "open to friends", who can be anywhere, and it can use any service to do the proxying.

**Comment by appgurueu** [comment] 2022-06-26 10:42
> It should be possible to open to LAN at runtime.

But *why*? What's the issue with restarting the server when you want to host a server? NTM mods probably expecting `minetest.is_singleplayer()` to return the same value across a session. I don't see this feature being worth the effort.

**Comment by SoniEx2** [comment] 2022-06-26 14:13
Because being able to do it at runtime is more flexible. Not everyone wants to have to restart their game just to do a socket()/bind() dance again.

**Comment by appgurueu** [comment] 2022-06-26 14:30
> Because being able to do it at runtime is more flexible. Not everyone wants to have to restart their game just to do a socket()/bind() dance again.

There even [is a proxy](https://github.com/HimbeerserverDE/mt-multiserver-proxy). Use that if you don't want to restart at all cost. This feature isn't worth implementing.

**Comment by SoniEx2** [comment] 2022-06-26 14:37
Speaking as a player: "Open to..." at runtime feels better than having to restart.

**Comment by rubenwardy** [comment] 2022-06-26 15:23
I'm taking SmallJoker's thumbs up as support, so closing this issue as Won't Add. See https://github.com/minetest/minetest/issues/12475#issuecomment-1166346109 for reasons

This issue isn't directly about an Open to LAN option, it's about mod control over the network sockets. An issue about Open to LAN could be considered - I think it would be low priority though as you can just click host server. There are things that would improve UX much more like UPnP service detection and URIs to join servers

**Closed** 2022-06-26 15:23 UTC
Labels: Won't add, @ Script API, @ Network, Feature request, Possible close

**Comment by SoniEx2** [comment] 2022-06-26 15:34
Hmm... Sure.
