### ISSUE TITLE
Better player animations

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4672] opened 2016-10-26 15:22 UTC
For example If You look Around Your Head will move in that Direction instead of your Whole body
I think crouching should shange the animation as well
Also if someone holds a block or item you can't see it on the other players hand

**Comment by Wayward1** [comment] 2016-10-26 15:31
Duplicate of #2716 and #1800

**Closed** 2016-10-26 15:48 UTC

**Comment by tobyplowy** [comment] 2016-10-26 15:51
@Wayward1 Sorry I searched but i cudent find Any :/

**Comment by Wayward1** [comment] 2016-10-27 00:07
No problem :)

**Comment by tobyplowy** [comment] 2016-10-27 09:44
@Wayward1 is there also already an issue about players not Holding items in third person?

**Comment by Wayward1** [comment] 2016-10-27 12:36
It looks like PR #2827 may involve that, but I haven't seen an issue that specifically involves 3D wield items.
