### ISSUE TITLE
Android version on Chromebook ignoring keybinds

### ISSUE THREAD

**Issue by PonyFlare** [minetest/minetest#12198] opened 2022-04-15 02:23 UTC
I installed minetest onto my Chromebook via F-Droid
Trying to play the game, keyboard input is ignored - specifically WASD for movement, though I haven't tested beyond that.
The game does display the on-screen touch screen joystick but given my Chromebook is not a touchscreen device despite running Android games, this feature is not very useful. I *can* use it with my mouse, but that's awkward at best.
The change keys menu allows me to set any keys I want, but they remain ignored in-game.

**Comment by rubenwardy** [comment] 2022-04-15 02:32
Duplicate of #10062

Thanks for the report though

**Closed by rubenwardy** 2022-04-15 02:32 UTC
Labels: Feature request, Android, @ Client / Controls / Input
