### ISSUE TITLE
entering blocks on android without noClip

### ISSUE THREAD

**Issue by sotha1** [minetest/minetest#14189] opened 2023-12-30 14:43 UTC
https://github.com/minetest/minetest_game/assets/149703967/2530a583-bba4-4abc-8b4f-eeb626438832

how you can see, when i walk a bit outside the block above me and i put a block on the floor of it, i can enter it (without noClip activated)

**Comment by SmallJoker** [comment] 2023-12-30 18:38
Did you - by any chance - change the following setting?

https://github.com/minetest/minetest/blob/431444ba9f6a57b8105adcaeed9451fd77605fc5/builtin/settingtypes.txt#L98-L100

In the main menu, turn off the checkbox `Controls` -> `General` -> `Build inside player`. You cannot enter the nodes again once you're on the outside. The same effect occurs when another player places nodes in place where you stand.

**Comment by sotha1** [comment] 2024-01-01 20:36
> Did you - by any chance - change the following setting?
> 
> https://github.com/minetest/minetest/blob/431444ba9f6a57b8105adcaeed9451fd77605fc5/builtin/settingtypes.txt#L98-L100
> 
> In the main menu, turn off the checkbox `Controls` -> `General` -> `Build inside player`. You cannot enter the nodes again once you're on the outside. The same effect occurs when another player places nodes in place where you stand.

no, it wasn't activated

**Comment by sotha1** [comment] 2024-01-01 21:26
> Did you - by any chance - change the following setting?
> 
> https://github.com/minetest/minetest/blob/431444ba9f6a57b8105adcaeed9451fd77605fc5/builtin/settingtypes.txt#L98-L100
> 
> In the main menu, turn off the checkbox `Controls` -> `General` -> `Build inside player`. You cannot enter the nodes again once you're on the outside. The same effect occurs when another player places nodes in place where you stand.

apparently the bug is because of the snow mat, because i tested it in grass (at the same states) and the player doesn't enter the block

**Comment by grorp** [comment] 2024-01-01 21:32
This seems to be the bug that will be fixed #14068.

**Comment by grorp** [comment] 2024-01-01 21:34
Duplicate of #9625

**Closed by grorp** 2024-01-01 21:34 UTC
Labels: Unconfirmed bug, @ Server / Client / Env., Action / change needed
