### ISSUE TITLE
Minetest has not been updated on FDroid

### ISSUE THREAD

**Issue by Doomsdayrs** [minetest/minetest#12509] opened 2022-07-04 15:39 UTC
as the title says, the application has not been updated.

There was a PR that was meant to fix it, but it seems no one ever looked back.

[FDroid](https://f-droid.org/en/packages/net.minetest.minetest/)

**Comment by rubenwardy** [comment] 2022-07-04 15:40
Duplicate of #9839, this is not our responsibility. We don't maintain or recommend the use of FDroid

**Closed by rubenwardy** 2022-07-04 15:40 UTC
Labels: Unconfirmed bug

**Comment by Doomsdayrs** [comment] 2022-07-04 15:43
> Duplicate of #9839, this is not our responsibility. We don't maintain the F-Droid app, F-Droid does
> 
> See the upstream issue: https://gitlab.com/fdroid/fdroiddata/-/issues/2116

Thank you for pointing me in the right direction, I'll see if I can fix it
