### ISSUE TITLE
macOS install has small visible game area and misaligns mouse to buttons

### ISSUE THREAD

**Issue by sirnewton01** [minetest/minetest#11536] opened 2021-08-14 12:39 UTC
##### Minetest version
```
Minetest 5.4.0 (OSX)
Using Irrlicht 1.8.4
Using LuaJIT 2.0.5
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
```

##### OS / Hardware
Operating system: macOS 11.5.2 (Big Sur)
CPU: x86_64

GPU model: Intel Iris Pro 1536 MB
OpenGL version: Unknown

##### Summary
When launching minetest on macOS the active region of the game appears at about 1/4 or 1/8 of the size of the window instead of occupying the entire window. This might be fine except the mouse is misaligned and so one has to guess where to click on the buttons. Note that this version of minetest was installed using homebrew.

See the attached screenshot:
<img width="972" alt="Screen Shot 2021-08-14 at 8 30 50 AM" src="https://user-images.githubusercontent.com/3670311/129446586-65426ff1-48a2-46eb-9eec-63f2b79e8ded.png">

##### Steps to reproduce
1) Start the game
2) Attempt to join a network game by clicking on one and clicking play
3) Notice that the screen is very small and it's very difficult to click on the buttons

**Comment by SmallJoker** [comment] 2021-08-14 14:08
Duplicate of #10654. Use a recent 5.5.0-dev build.

**Closed by SmallJoker** 2021-08-14 14:08 UTC
Labels: Unconfirmed bug
