### ISSUE TITLE
Protocol bug when a server is hard working.

### ISSUE THREAD

**Issue by Lejo1** [minetest/minetest#7403] opened 2018-06-03 09:04 UTC
##### Issue type
 - Bug report
 
##### Minetest version
0.4.17-dev/0.4.16/0.4.15

##### Summary
Sometimes when my server is hard working like on a server restart, it shows this message if you try to connect. This message appears not after the server has started fully.
This can also happen if you place a mtschem or something else.

`ERROR[Main]: Connection failure: init packet not recognized by server.
ERROR[Main]: Most likely the server uses an old protocol version (<v25).
ERROR[Main]: Please ask the server owner to update to 0.4.13 or later.
ERROR[Main]: To still connect to the server in the meantime,
ERROR[Main]: you can enable the 'send_pre_v25_init' setting by editing minetest.conf,
ERROR[Main]: or by enabling the 'Client -> Network -> Support older Servers'
ERROR[Main]: entry in the advanced settings menu.`

But my server is 0.4.17-dev/0.4.16/0.4.15 not 0.4.12 or older.

##### Steps to reproduce
Start a little server and place a very big mtschem, then try to connect.

**Comment by sfan5** [comment] 2018-06-03 09:48
The error message is just a guess, it gets shown whenever the server does not respond to our init packet.
There's not much that can be done to fix this, as there is no way to differentiate between a dead server and a server that doesn't understand our protocol.

**Comment by orwell96** [comment] 2018-06-04 14:12
But it would be convenient if that error message would be changed.

**Comment by numberZero** [comment] 2018-06-09 22:38
I confirm the bug, it happens often on laggy servers. The reason is the weird network handling. There is a dedicated thread that accepts connections, but doesn’t send even the protocol version. That is handled by the main server thread (the same that runs `async` server step). Moreover, both server step and message handling lock the environment mutex, so mere separation won’t let them work concurrently.

**Comment by red-001** [comment] 2018-06-21 11:07
duplicate of #5691

**Closed** 2018-06-21 11:09 UTC
Labels: Non-trivial, Request / Suggestion
