### ISSUE TITLE
Decorations are buried 1 node deep into the ground

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6375] opened 2017-09-04 21:32 UTC
Decorations of type “schematic” are a bit strange. You'd normally expect they'll be simply placed on top of the ground while they are actually buried 1 node deep into the ground. You can notice this easily when `force_place` is set (e.g. for trees), and for decorations which are exactly 1 node high.

This sound either like a bug to me, or at least it's not documented.

**Comment by paramat** [comment] 2017-09-05 21:10
It's not a bug and is very useful, if 1 node higher then there is no option to have them penetrate by 1 node, this way we have the option. Working with decorations i often wish i could set them to penetrate deeper, maybe i'll add a setting for it.
Schematic decorations are mostly used for trees, and a tree sitting on top of the ground is weird and not expected (stop thinking about Minecraft or mgv6), it's much more suitable, and less awkward-looking, to have at least 1 node of root.

It could be documented yes, i'll treat this as a request for documentation.

**Comment by Wuzzy2** [comment] 2017-09-06 06:49
A setting to change the Y offset would be very useful.
And yes, this should be documented.

**Comment by paramat** [comment] 2017-09-06 17:23
Many times i have wanted Y offset too, i'll code it.

**Comment by paramat** [comment] 2017-09-06 21:35
PR #6385

**Comment by paramat** [comment] 2017-09-10 00:35
#6385 merged.

**Closed by paramat** 2017-09-10 00:35 UTC
Labels: @ Documentation, @ Mapgen, @ Script API, Request / Suggestion
