### ISSUE TITLE
Strings are corrupted after updating to MacOS Sonoma 15.4

### ISSUE THREAD

**Issue by Pixel-Peter** [minetest/minetest#14731] opened 2024-06-06 11:21 UTC
### Minetest version

```true
Minetest 5.7.0 (OSX)
Using Irrlicht 1.9.0mt10
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
STATIC_LOCALEDIR="minetest.app/Contents/Resources/locale"
```

### Irrlicht device

X11

### Operating system and version

MacOS Sonoma 14.5

### CPU model

Apple M1 Pro

### Summary

<img width="1512" alt="Bildschirmfoto 2024-06-06 um 13 05 45" src="https://github.com/minetest/minetest/assets/78911783/077f83fc-6527-473c-a202-a03fde8be9e0">
What happened?
After updating my OS from 14.3 to MacOS Sonoma 14.5 there will be no string correctly displayed. My language-settings of my OS are German. But this shouldn't be an issue. It is something with the UTF-8 conversion, but as there are no issues with other applications there might the root cause somewhere in the minetest-code.

What should happen:
Strings shall be correctly displayed.

### Steps to reproduce

See summary

**Comment by Pixel-Peter** [comment] 2024-06-06 11:22
<img width="1510" alt="Bildschirmfoto 2024-06-06 um 13 21 55" src="https://github.com/minetest/minetest/assets/78911783/20efd1dc-96a5-4d63-909c-beb050a06bfe">

**Comment by sfan5** [comment] 2024-06-06 11:38
duplicate of #14463

**Closed by sfan5** 2024-06-06 11:38 UTC
Labels: Unconfirmed bug
