### ISSUE TITLE
`^glow:10` style texture modifier

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#10009] opened 2020-06-08 05:22 UTC
## Problem

Right now the only way that entities can create specific parts of their texture to glow is by setting another object that is identical to the entity and attaching it to the original entity. It would be extremely useful if we could individually layer on a glow texture modifier so that we can create custom parts of entities that glow in the dark.

## Solutions

Implement a ````texture.png^(texture2.png^glow:10)```` style texture mod which disables part of the entities light calculation on the parts of it that are set to glow.

**Comment by appgurueu** [comment] 2020-06-08 08:15
Fairly nontrivial and out of scope for texture modifiers, which return RGBA images: there is no "glow" channel or material in a texture yet, and texture modifiers are not material modifiers.

The proper solution would be a Material API, this can't really be achieved / is not worth achieving using a texture modifier.

**Comment by ClobberXD** [comment] 2020-06-08 10:32
Related: #8854

**Comment by SmallJoker** [comment] 2020-06-08 18:27
Texture modifiers are solely for textures. Anything else, like modifying node or object behaviour (light is one of them) does not follow any sane logic.

**Comment by paramat** [comment] 2020-06-09 00:53
Perhaps this request should be added to #8854 as a request for entity glowmaps?
Also see #9075 
Entity glowmaps is a dupicate of #9495 which seems to be a duplicate of #9075
So i think this can be discussed in one of the other issues.

**Closed by paramat** 2020-06-09 00:53 UTC
Labels: Duplicate, Feature request
