### ISSUE TITLE
Sound Muffling

### ISSUE THREAD

**Issue by TechDudie** [minetest/minetest#11164] opened 2021-04-03 19:16 UTC
## Problem

I was startled by a zombie moaning underground when I was above ground a few blocks up in MineClone2 

## Solutions

Add sound muffling for certain nodes see https://sciencing.com/objects-absorb-sound-8140985.html

**Comment by Desour** [comment] 2021-04-03 19:42
:+1: For nice sound effects.
(OpenAL can do such things, I think, see https://www.openal.org/documentation/ and http://zhang.su/seal/EffectsExtensionGuide.pdf.)

**Comment by AFCMS** [comment] 2021-04-05 14:51
:+1: I would love this feature to be implemented! It would be very useful.

**Comment by rubenwardy** [comment] 2022-05-04 18:36
Duplicate of https://github.com/minetest/minetest/issues/11164

**Closed by rubenwardy** 2022-05-04 18:36 UTC
Labels: @ Script API, Feature request, Sounds
