### ISSUE TITLE
Add screen_width, screen_height and platform to get_player_information

### ISSUE THREAD

**Issue by Bastrabun** [minetest/minetest#10393] opened 2020-09-14 07:07 UTC
## Problem

To adjust your mod to smaller, wider, whatever screens and other client limitations (or features?), a modmaker needs to get more information about the properties of the client.

## Solutions

Add 

```
screen_width
screen_height
platform

```

and probably some other useful client information to the get_player_information table.

Platform would indicate the operation system, like "android" or even "android10" or "linux". 

## Additional context

Platform probably runs into the same issues as the version_string https://github.com/minetest/minetest/issues/10368

**Comment by anon55555** [comment] 2020-09-14 08:46
Window size would be better than screen size. And I think it would be better to just say if it is touch controlled or keyboard/mouse controlled.

**Comment by Bastrabun** [comment] 2020-09-14 08:56
True, replace "screen_" by "window_"

**Comment by SmallJoker** [comment] 2020-09-14 17:13
Screen sizes (neither in pixel nor meters) won't help if the client uses a high DPI or font size setting. Both of these problems could be addressed by figuring out, how many lines/columns of text you can fit on the screen.
I also like @anon55555's input: mods should not distinguish between operating systems or whatsoever. Only the input method matters.

**Comment by paramat** [comment] 2020-09-14 20:30
Getting platform has already been disapproved twice, see #10368 (and that was your issue, you should not requesting it again when it has been disapproved twice and very recently in one of your own issues) but a different approach is suggested and supported there (incrementing formspec/protocol numbers each release).

#7658 disapproves the rest of this request and explains why, there is too much stuff that varies for game window size to be of any use. Compensating for everything would be very complex.
So :-1: (again).

The requests here are already disapproved elsewhere so closing.

**Closed by paramat** 2020-09-14 20:30 UTC
Labels: @ Script API, Feature request

**Comment by Bastrabun** [comment] 2020-09-15 05:27
What do you do when he operating system DOES matter? Like when a client connects with an old version and you'd like to give them detailed instructions on where to download, brew or get their hands on a current client version?

I honestly don't understand why you are making it harder or in some cases impossible for modmakers or server owners to make the experience for players better??

To me, not only the input method or the protocol version matters!

**Comment by sfan5** [comment] 2020-09-15 09:53
> Getting platform has already been disapproved three times,

More like one or two depending how you count.
#7799 is a direct duplicate of this platform part of this issue.
#4367 directly suggests banning a certain platform so isn't quite the same.
#6114 is different since goes much further and suggests some kind of DRM.

> Especially since formspecs do not allow for screen fit resizing or any other modern way of generating an appealing experience for users.

It's true that this is an issue, but this would better be solved by improving formspecs.

In the meantime exposing the screen size would be useful so mods can adjust their UIs as appropriate.
What exactly is exposed must be carefully chosen however so that it's meaningful (maybe DPI-adjusted window size?)

> I also didn't open this issue for fun or to annoy someone, but because I need it to properly make what I want.

What do you plan to make that
* requires exact knowledge of the platform (touchscreen vs. mouse input doesn't suffice)
* can not be replaced with a simpler approach ("go to minetest.net/download" instead of OS-specific instructions)

?

**Comment by Bastrabun** [comment] 2020-09-15 21:03
> > Especially since formspecs do not allow for screen fit resizing or any other modern way of generating an appealing experience for users.

> It's true that this is an issue, but this would better be solved by improving formspecs.

Although I did not come up with another use case but formspecs yet, I might find one in the future and bite myself in the **** when I requested window_size for formspecs only. I figured it might be easier and would not hurt to have the information available when something other than formspec crops up. But currently you are right: It's formspecs for me, not much more.

> What do you plan to make that
> 
> - requires exact knowledge of the platform (touchscreen vs. mouse input doesn't suffice)
> - can not be replaced with a simpler approach ("go to minetest.net/download" instead of OS-specific instructions)

Touchscreen and mouse input aren't mutually exclusive, since bluetooth mice for android devices and Windows touchscreen laptops. Detecting which environment the user is on helps me make better ingame instructions on how to use things - especially mobile is much different, I'd like to adjust HUD, formspecs, fighting mechanics and some quest-related stuff, eg jump'n'run-like/parcour episodes, which are bonkers on mobile. I fail them often enough on my gaming PC let alone my android device. Also, when the mobile folks break protection (which occasionally happens to me by accident on android) I'd like to not hurt them as much as the PC players ;) Among other uses, the mobile players already are severely outmatched on their equipment. Or when a mobile user won't be able to rightclick AND leftclick at the same time. Or .... I guess you know much better than me what else there is that makes it useful to know what the other person sees and can or cannot do.

Linux and Windows is not so much different and I have no clue about MacOS, but still I'd like to give people instructions according to their environment. That's what all other games also do. Also, mobile has a good chance of connecting via some data plan or high latency connection. Those who pay for traffic usually aren't happy when they are forceloaded a part of a city during a quest. (I'm not sure if I can make it, but if I can, I'd like to make use of speech synthesis, which requires me to send files to players. Also not cool on data plans.)

Also, since I plan to make cheat protection that defends against flying without fly and noclipping without noclip, I'd like to go more lean on players that have a bad latency, because I suspect they might just accidentally lag themselves into the red alert of my cheat protection. This can already be detected by the player information, it has RTT, but I'd like to know before the connection shows their hiccup.

Detecting a potentially bad connection by guessing the platform is not exact, since a Windows Laptop may connect using a cellphone as a modem, but you get the point.

It was suggested that I make a settings-page where a user can override the automatically detected values - that's a good idea, but I'd have to make profiles since users may want to switch devices. Also, some users may find it strange that in 2020 they need to set their screen resolution or platform to get a good experience. I'd like to keep it as automatic as possible. Such settings needed to reside in the Inventory or behind a chatcommand, since I cannot make use of the menu behind the Esc key, where I'd have chosen to have a settings button.

It was also suggested to me that I make my formspecs as window-size agnostic as possible. While that *is* possible sometimes, I'd still like to decide for myself where and how I display formspecs to a user. And I'd like to have that option when it is *not possible to make formspecs less than fullscreen with no padding or background color or other trickery.

**Comment by Jordach** [comment] 2020-10-19 03:21
Here's something you don't often see: display underscan. Or how certain LCD panels (such as those overly expensive 4K panels) often are actually scaling up the input image to hide bezels.

Competant game developers usually have a GUI positioning tool that allows the user to set the valid corners of the display which aren't either overscanned or underscanned.

Allowing mods to best configure the HUD for certain device types is the best possible thing. About 30% of the display on phones are lost due to thumbs on the screen. And are usually extremely high in DPI resulting in cramped visuals or resulting in too small elements. Having a relative way to detect specific operating systems is even better; as rejection of certain clients such as mobile do not input certain controls when placing or digging. See #10438 for details. This would also to allow a more optimised way of setting control schemes, such as using sneak and place/right mouse where AUX1 is more difficult to press.

Suggestion for core developers, actually attempt at writing a game that is:

1. A non survival sandbox game.
2. Use non standard controls.
3. Do it without making patches for the engine.
4. Test it on non-standard resolutions, devices, gamepads etc.
5. Try and make a game using only Minetest entities and see how it works out.

This is the kind of problem that plauges people who create content for the engine, but are constantly denied consideration by overly-conservative developers who are afraid of trying something new and potentially breaking. Compatibility should be within +-2 minor patches. Not 12. 5.0 is already a mess due to Multicraft, outdated Android, outdated F-Droid and users with the DF Client.

**Comment by sorcerykid** [comment] 2021-04-22 19:27
I think that DPI, gui scaling, and operating system should be made available at bare minimum. That information never changes in the course of gameplay, so it could be sent to the client as part of the TOSERVER_CLIENT_READY message. There doesn't appear to be any extraordinary technical hurdles to this part of the request.

Indeed, it comes down once again to a few core developers deliberating how they think games should be properly designed. Instead of affording full creative freedom to game designers, the core developers act as gatekeepers by restricting powerful feature-sets like these only because of the small potential for bad design decisions by inexperienced programmers.

I'm willing to bet that Unity 3D, Unreal Engine, and all the other modern game engines provide information about the end-user's display capabilities. It would certainly be nice if Minetest could take a similar "hands off" approach, and finally give  game designers and modders some of the features that they keep asking for repeatedly. Just my two-cents :)
