### ISSUE TITLE
[Android] Minetest dir doesn't get removed when deinstalling the app

### ISSUE THREAD

**Issue by z0rti** [minetest/minetest#11221] opened 2021-04-21 19:45 UTC
I noticed that after deinstalling the Minetest App (on Android 10) the minetest dir where e.g. minetest.conf lives
are still there.
So if the conf would contain wrong settings, deinstall/reinstall would'nt work.
(Of course if you know that and where it is you could install a file browser app and remove it manually)

**Comment by AbduSharif** [comment] 2021-05-18 16:13
There are players who don't want to remove it.
I want to let thefodler stay where it is with all my mods and worlds and texture packs and games to not have to r-download them or move them when reinstalling Minetest.
The config file problem should be solved without removing the Minetest folder.

**Comment by rubenwardy** [comment] 2021-05-18 18:03
We will have to fix this within the next year or two, before Android starts requiring a target version of 30.

From Android SDK 30, you can no longer write directly to the user folder (="external directory"). Instead, you must use scoped storage. In our case, that will be an app folder

**Comment by AbduSharif** [comment] 2021-05-19 16:07
Wait, why would they do that? Doesn't apps already ask if a user wants to let an app use internal storage or not? Or maybe they mean the SD card?

**Comment by rubenwardy** [comment] 2021-05-19 16:12
> Doesn't apps already ask if a user wants to let an app use internal storage or no

This is correct. This request is deprecated and no longer works when using a target version of 30

> Wait, why would they do that

Apps now request the ability to access more granular resources. For example, they may request the ability to read/write images in the phone's gallery

**Comment by AbduSharif** [comment] 2021-05-19 16:35
I see, so it's for extended "user privacy", I guess now alot of apps that may target SDK 30 will have alot to rework and rethink :(

**Comment by sfan5** [comment] 2021-05-25 19:09
duplicate of #2097

**Closed by sfan5** 2021-05-25 19:09 UTC
Labels: Android, Bug
