### ISSUE TITLE
Keep the Play Store version updated

### ISSUE THREAD

**Issue by LikeGuyS** [minetest/minetest#12224] opened 2022-04-25 16:41 UTC
## Problem

[Minetest, on the playstore, is still on the version 5.4.2](https://play.google.com/store/apps/details?id=net.minetest.minetest) 

## Solutions

Keep it updated.

**Comment by rubenwardy** [comment] 2022-04-25 17:29
The 5.5.0 release was cancelled for Android because a huge uptick in crashes. We don't have a good way of getting crash information currently, so it's super hard to debug

**Comment by rubenwardy** [comment] 2022-05-15 14:18
Duplicate of #12062 should be fixed soon

**Closed** 2022-05-15 14:18 UTC
Labels: @ Build, Android, Request / Suggestion
