### ISSUE TITLE
Replace "plantlike_rooted" with "fillable = true"

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7836] opened 2018-11-03 21:33 UTC
##### Issue type

 - Feature request
 Minetest has needed the ability to fill things with liquid for a long time
![screenshot_2018-11-03-14-01-46-1](https://user-images.githubusercontent.com/33675971/47957382-dd2fdc80-df71-11e8-8e55-e06b87f2784d.png)

And I love that you've implemented it. 

But only in plantlike?

Why not, instead of "plantlike_rooted" why not have fillable = true
Like what if we want liquid to fill other drawtypes
![screenshot_2018-11-03-14-05-38-1](https://user-images.githubusercontent.com/33675971/47957413-6fd07b80-df72-11e8-9132-52e15493b4ae.png)
So please change it from rooted to fillable would be used like so
```
minetest.register_node("mymod:node", {
    drawtype = "nodebox",
    tiles = {"default_glass.png"},
    fillable = true,
    node_box = {
            type = "fixed",
            fixed = {
               {-0.25,-0.5,0.25,0.25,0.5,-0.25}
           }
     }
})
```

**Comment by DS-Minetest** [comment] 2018-11-04 12:32
Plantlike_rooted nodes can't be filled with water. They are placed in the ground of lakes and have faces that go out of the full node box, I think.
Related: #3074, #4869, #5381 and #5748

**Comment by paramat** [comment] 2018-11-04 19:53
DS-Minetest is correct, see the linked issues.
The only way to do this for a node is for the node to be a combination of a full cube plus an extension that extends into water. it can't be generally applied to all nodes like nodeboxes.
You can do this in a mod by defining a special nodebox, read #3074 especially https://github.com/minetest/minetest/issues/3074#issuecomment-296842452 onwards.

So this feature request is impossible, and somewhat a duplicate of #3074

**Closed by paramat** 2018-11-04 19:53 UTC
Labels: @ Client / Audiovisuals, Feature request

**Comment by rubenwardy** [comment] 2018-11-04 19:58
This can be implemented for all drawtypes by not placing the water edges next to such a node, and checking surrounding nodes to see if a top surface should be added. So it's theorectically possible to do this in no more checks than firelike requires. That being said, this isn't my part of the engine

**Comment by Fixer-007** [comment] 2018-11-04 19:59
****craft also implemented this, looks so much nicer, but then again, someone should tackle z-sorting too.

**Comment by paramat** [comment] 2018-11-04 20:28
We could possibly reopen #3074 if necessary.
