### ISSUE TITLE
Remove some deprecated Lua API features for 5.0.0

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7786] opened 2018-10-14 13:04 UTC
##### Issue type
 - Feature request
 
##### Summary
Since 5.0.0 is coming, what do you think about actually removing some old deprecated Lua API functions?

Depreated functions:

* `luaEntitySAO:get_look_pitch()` (broken)
* `luaEntitySAO:get_look_yaw()` (broken)
* `luaEntitySAO:set_look_pitch()` (broken)
* `luaEntitySAO:set_look_yaw()` (broken)
* `itemstack:get_metadata()`
* `itemstack:set_metadata()`
* `minetest.get_mapgen_params()`
* `minetest.set_mapgen_params()`
* `luaEntitySAO:get_entity_name()`

Alias functions:

* `minetest.get_node_group()`
* `minetest.add_particle`, `minetest.add_particlespawner` with non-table argument list

Deprecated symbols:

* `minetest.env`

Inventory stuff:

* `invsize[]` formspec element
* `current_name` inventory list

I don't suggest to actually remove ALL deprecated things, but maybe at least the oldest and most broken ones. I leave it open to discussion which things should be removed in the end.

I suggest to remove at least the pitch/yaw functions because of their brokenness.

**Comment by SmallJoker** [comment] 2018-10-14 14:13
I disagree with removing any of those, but all of them must be marked as deprecated (i.e. log a warning on use). Modders would not like this change, but we can assume that the following functions are no longer relevant in our modding API: (about 7 years old)
https://github.com/minetest/minetest/blob/b6adb7f09e4375f145c3ddb592527c1dd0b026a2/builtin/game/deprecated.lua#L6-L24
Removing `minetest.env` would also be great, but there are simply too many mods around which use these functions.

**Comment by Wuzzy2** [comment] 2018-10-14 19:44
And what about all the other stuff? What do you think about the broken pitch/yaw functions?

**Comment by Ryan-Nolan** [comment] 2018-11-14 11:23
i think worrying about existing mods use of depreciated functions/methods when releasing a new major version of the minetest engine should not be a concern for core devs... its a breaking change version for a reason. I think its more important just to be clear to mod developers what breaking changes are being made and when they are being enforced... Now would probably be a good opportunity to force mod developers to update there mods.... maybe even have a week or 2 period of no breaking changes just before release to give mod developers time to catch up?

**Comment by Ferk** [comment] 2018-11-14 11:59
Are those really deprecated? Which announcement deprecates them?

You cannot really say that something is deprecated if there's no warning or list indicating it is deprecated. Being old and undesirable does not make something automatically deprecated, the disapproval needs to be expressed in some way. Publicly so, if it's a public API.

The closest thing to a list of deprecated methods I've found is this: https://dev.minetest.net/Category:Proposed_Deletions
Which only includes the settings_* methods, and those are missing from the list of this issue.

I'd agree with SmallJoker about marking any method that's really unsupported as deprecated and display warnings when used to discourage their use by new mods and help old mods to locate and fix the use of deprecated methods.

**Comment by rubenwardy** [comment] 2018-11-14 12:20
I think that endpoints which had a deprecation warning in 0.4.x and aren't used much can be removed.

This includes minetest.env, but doesn't include minetest.setting_*.

**Comment by Ryan-Nolan** [comment] 2018-11-14 12:41
I dont disagree with what anyone is saying above, Im expressing ideas. I think core devs have enought to deal with without having to worry about mod devs not updating their code. but on the flip side i think mod devs need a clear way of knowing what is and what is not depreciated without having to go through commit logs or find out when they have already coded much of it in the logs..  #my2cents :/

**Comment by Ryan-Nolan** [comment] 2018-11-14 12:43
Also... i think when something is marked as depreciated... it should be logged as to which version it will be removed..  it might encourage mod devs to act faster?

**Comment by Wuzzy2** [comment] 2018-11-14 13:03
I still think it's not good to intentionally continue to keep known broken functions in the API. If not even their brokenness and the upcoming 5.0.0 release is enough justification to remove these functions, they will likely stick around forever, polluting the Lua API.

**Comment by paramat** [comment] 2018-11-14 20:36
> worrying about existing mods use of depreciated functions/methods when releasing a new major version of the minetest engine should not be a concern for core devs... its a breaking change version for a reason

We should be concerned about breaking mods because this 'breaking release' does not mean 'breaking mods', it's only breaking network compatibility.
Modders are already complaining about the amount of breakage already caused by 5.0, some are resisting moving to 5.0 due to this. It's best to avoid adding significantly to the breakage.
However i think it is worth breaking a very few mods that are very out of date when it comes to deprecation, so it depends on the time of the deprecation (at least 3 years back maybe?).

I change my mind about 'minetest.env', that was a long time ago and even lazy me hasn't really got any mods left using that.
So how about we do this strictly according to date of deprecation?
> maybe at least the oldest and most broken ones
I agree.

**Comment by Wuzzy2** [comment] 2020-04-30 12:31
Is this issue still relevant?

**Comment by rubenwardy** [comment] 2020-04-30 12:40
unfortunately not

**Closed by rubenwardy** 2020-04-30 12:40 UTC
Labels: Low priority, Request / Suggestion, Supported by core dev
