### ISSUE TITLE
Global callback to know when an entity dies

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#15037] opened 2024-08-22 16:33 UTC
### Problem

In my quests mod, I need to check when a specific entity dies by the hand of a player - no matter the tool in their hands. The entity varies according to the quest (e.g. it might be from an external mod), so I need a global callback to know when an entity dies. There I can check if there is a quest going on for that player, if it's one about killing an entity and if it's the entity needed by the quest

### Solutions

Implement something like `minetest.register_on_entity_death` or `minetest.register_on_entity_hpchange`

### Alternatives

`minetest.register_on_punchentity`

**Comment by rubenwardy** [comment] 2024-08-22 16:39
Duplicate of #14577

**Comment by rubenwardy** [comment] 2024-08-22 16:40
Related to #14752

**Comment by Zughy** [comment] 2024-08-22 16:41
> Fyi this is already possible by overriding on_death in the entity

Yup, it's a workaround, but a clean implementation would be better

**Closed** 2024-08-22 19:10 UTC
Labels: @ Script API, Feature request
