### ISSUE TITLE
Improve formspec

### ISSUE THREAD

**Issue by BruceMustache** [minetest/minetest#10267] opened 2020-08-06 19:06 UTC
## Problem

Currently formspec limit developers to do something more beautiful in a graphical way
As far as I know I have problem with fullscreen design for minetest main menu (#6733) and colored text (https://github.com/minetest-mods/mesecons/issues/518)
ie: With a more general GUI tool we can make graphical interfaces more beautiful

## Solutions

* Add support for fullscreen design
* Text customization (change foreground, background, size, font, ...)
Discuss in this issue how to improve formspec

## Alternatives

Use another GUI tool while still support formspec for old compability
Here are some alternatives: http://lua-users.org/wiki/GraphicalUserInterfaceToolkits
What about GTK or Qt?

Another alternative is use js, html and css. I don't if it is a good idea because it use another language instead of lua

## Additional context

Related: #9358

**Comment by SmallJoker** [comment] 2020-08-06 19:23
See also: #6527
> Add support for fullscreen design
See also: #8630

> Text customization 
This already exists. `minetest.colorize` and `style[]`.

This issue is too vague. Please clarify what _exactly_ you would like to have improved.

**Comment by rubenwardy** [comment] 2020-08-06 19:27
Duplicate of #6527

**Closed** 2020-08-06 19:26 UTC
Labels: Feature request, Possible close

**Comment by v-rob** [comment] 2020-08-06 20:18
I intend to make fullscreen formspecs with CSS-like units like `%`, but much refactoring is necessary beforehand.
