### ISSUE TITLE
Canceling: No player for peer_id when too many objects on the map

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest#4067] opened 2016-05-01 15:06 UTC
```
2016-05-01 16:52:43: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=210 disconnecting peer!
```

Hi, we had big trouble with messages like above.
The temporaly fix was a `/clearobjects`.
The problems:
- It takes hours on our map
- every player will lose the mobs on farms for example

Maybe there is a way to handle this?
As you see in the timestamp, we slowly go back to this issue... :(

**Comment by kahrl** [comment] 2016-05-01 22:17
Doesn't fix the second bullet point, but to speed up `/clearobjects` you could try: `/clearobjects quick`

**Comment by tchncs** [comment] 2016-05-02 07:33
What is the difference between regular an quick? Only loaded chunks?

**Comment by kahrl** [comment] 2016-05-02 09:37
`/clearobjects quick` deletes objects in active mapblocks; for all other mapblocks, the objects are deleted the next time that mapblock is activated. So the in-game effect should be the same as with regular `/clearobjects`, but quick mode doesn't have to load every mapblock. A downside of quick mode is that the world size doesn't shrink much.

**Comment by Fixer-007** [comment] 2016-05-28 21:21
This issue was also reported by IhrFussel on irc.
Ubuntu 14.04 64-bit AMD and version 0.4.13-dev compiled 2-3 weeks ago

**Comment by 00c** [comment] 2016-05-29 16:08
Same happen on my server, what could cause too many objects?
some days a go i run /clearobjects took some hours.

> 2016-05-29 17:33:48: ERROR[Server]: ServerEnv: Trying to store id=279 statically but block (60,-1936,-26) already contains 37542 objects. Forcing delete.
> 2016-05-29 17:33:48: ERROR[Server]: ServerEnv: Trying to store id=280 statically but block (60,-1936,-26) already contains 37542 objects. Forcing delete.
> 2016-05-29 17:33:48: ERROR[Server]: ServerEnv: Trying to store id=281 statically but block (60,-1936,-26) already contains 37542 objects. Forcing delete.
> 2016-05-29 17:33:49: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=3032 disconnecting peer!
> 2016-05-29 17:33:49: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=3084 disconnecting peer!
> 2016-05-29 17:33:49: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=3227 disconnecting peer!
> 2016-05-29 17:33:49: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=3261 disconnecting peer!
> 2016-05-29 17:33:49: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=3201 disconnecting peer!
> 2016-05-29 17:33:49: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=3261 disconnecting peer!
> 2016-05-29 17:33:49: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=3261 disconnecting peer!
> 2016-05-29 17:33:49: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=2764 disconnecting peer!
> 2016-05-29 17:33:49: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=3275 disconnecting peer!
> 2016-05-29 17:33:49: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=3275 disconnecting peer!
> 2016-05-29 17:33:49: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=2626 disconnecting peer!
> 2016-05-29 17:33:49: ACTION[Server]: Server: User hotboy at 24.182.100.81 supplied wrong (SRP) password from address 24.182.100.81.
> 2016-05-29 17:33:49: ACTION[Server]: Server: User James at 172.56.11.104 supplied wrong (SRP) password from address 172.56.11.104.
> 2016-05-29 17:33:50: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=2685 disconnecting peer!

**Comment by tchncs** [comment] 2016-06-29 21:34
Anyone here? It is still an issue!
As a workaround we use worldedit now for clearing in specific areas.
BUT, it seems like the force delete from minetest has **no effect**, except the peer disconnects.
This really should be fixed. 
The baddest part is, that often areas be affected on our server, where nothing noticable is.
Often just a stone building with some torches, thats all.
And much air.
I really dont know how to figure out where the problem is, in areas like this.

**Comment by Fixer-007** [comment] 2016-06-29 23:55
With this bug some players can't connect to the server? Correct?

**Comment by Rogier-5** [comment] 2016-06-30 07:22
> 2016-05-29 17:33:48: ERROR[Server]: ServerEnv: Trying to store id=279 statically but block (60,-1936,-26) already contains 37542 objects. Forcing delete.
> 2016-05-29 17:33:48: ERROR[Server]: ServerEnv: Trying to store id=280 statically but block (60,-1936,-26) already contains 37542 objects. Forcing delete.
> 2016-05-29 17:33:48: ERROR[Server]: ServerEnv: Trying to store id=281 statically but block (60,-1936,-26) already contains 37542 objects. Forcing delete.

I've never seen the messages about `no player for peer_id`, but at least the messages above look (exactly) like bug #4217.

Do note (in case you didn't know) that the coordinates are not world coordinates, but map-block coordinates. The offending block in the messages above is at (or rather just *below*) the bottom of the world.

Worldedit could work (not tested by me), or you can solve this by using `/deleteblocks` on the offending blocks. From what I tested, that works. Compute the map coordinates of the offending block by multiplying each of the block coordinates by 16.

If you use sqlite, you can use the following command to determine if there might be more blocks with such large numbers of objects. It shows relatively large blocks in the database with their size. If the blocks are very large, they _might_ also contain a large numbers of entities.
```
sqlite3 map.sqlite 'select pos,length(data) from blocks where length(data)>10000;'
```
In one test, I got a block of size `1112235` which contained `199920` objects, so about 5 bytes per object, but ymmv of course.

One way to reproduce this problem, is to drop items at the bottom of the world and wait some time without moving too far away. The longer you wait, the more objects. Presumably, you could also  drop items over the far edge of the world. And having mobs fall down might also work (not tested).

**Comment by tchncs** [comment] 2016-06-30 08:37
> With this bug some players can't connect to the server? Correct?

Depending on where they join. An affected chunk can cause this.
I noticed the peer disconnects after several floods of Forcing delete errors.

Since it seems unable to really forcing delete the objects, its will affect more and more players with peer disconnects. Horrible.

And no, we're using ssdb - for minetest its redis.

@Rogier-5 you tell us to delete buildings because of this? o.O

**Comment by Rogier-5** [comment] 2016-06-30 09:20
> you tell us to delete buildings because of this?

@tchncs: I don't think that would be necessary. However, until the real cause of the problem is known, or until somebody can reproduce the problem, and then reliably fix it, nobody can tell what should be done to fix the problem, and whether deleting buildings might be necessary.
However, if you are sure the area where your building is causes the problem, I'd suggest making a safe copy or backup of your database, then save your building and a large enough surrounding area using worldedit, delete the mapblocks, and restore the area using worldedit. That might remove the problem. If it doesn't, or if you messed up, restore the backup and try again, or try something different.

**However**, before you do this, do note that the problem I was referring to:

> 2016-05-29 17:33:48: ERROR[Server]: ServerEnv: Trying to store id=279 statically but block (60,-1936,-26) already contains 37542 objects. Forcing delete.

affects an area of the map *below* the world (map block 60,-1936,-26 is below y=-30913 !). You can't build there. At all. So deleting that block should not affect any builds. I don't know if that solves the problem with the messages like:

> 2016-05-29 17:33:49: ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=3261 disconnecting peer!

as I never saw such messages myself, and I don't know what might cause them.

And let me reiterate: before you start deleting blocks, be sure to make a backup of the database, and keep the backup until you *know* that the world is OK after editing.

If you save a building using worldedit, then before modifying your world, try and load the building again in a temporary world or so, so that you know it can be restored before you delete the original.

**Comment by tchncs** [comment] 2016-06-30 09:26
Guess @00c is a lucky guy in this case since i have this in "real" areas.
I noticed yesterday an affected area completely somewhere else caused by an autominer built with mesecons+pipeworks. This was something odd. The miner was at -10000, the affected chunk was at -16. o.O

**Comment by Rogier-5** [comment] 2016-06-30 11:23
That's odd indeed...
Of course, your problem might be a different one. Do you also get messages like these:

>2016-05-29 17:33:48: ERROR[Server]: ServerEnv: Trying to store id=279 statically but block 60,-1936,-26) already contains 37542 objects. Forcing delete.

for the same block at -16 ?

If so, then maybe some mod is creating entities (mobs, or items) there and not cleaning them up. Or maybe the autominer is buggy, and (occasionally) drops its entities somewhere else...

---------------

Assuming that this is caused by too many entities, you might hack minetest to print a list of entities in a block, or I could give you a (crude) patch to minetestmapper, that I have lying around, that dumps a list of entities in every mapblock it processes. That might give you some clues as to who or what is responsible for the problem...

**Comment by tchncs** [comment] 2017-01-20 21:31
Hey partypeople, the issue is still there. :(
After a too many objects error, it just kickes the players.

`ServerEnv: Trying to store id = 49316 statically but block (25,2,19) already contains 2048 objects. Forcing delete. -> Server::ProcessData(): Canceling: No player for peer_id=2386 disconnecting peer!`

The worst part currently is, that the affected area seems to not containd many objects, i only deleted 8 with worldedit.

**Comment by nerzhul** [comment] 2017-01-21 09:24
@tchncs i think the fix is to not delete player objects

**Comment by tchncs** [comment] 2017-01-21 09:35
Thank you, @nerzhul :)

**Closed** 2017-01-21 09:41 UTC
Labels: Bug
