### ISSUE TITLE
Lighting Glitches with Pine Needles.

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#3145] opened 2015-09-04 00:10 UTC
There seems to be light coming out of the corner, but there isn't any light producing node and it is night.
![screenshot_2511103808](https://cloud.githubusercontent.com/assets/10261530/9673899/c5a165b4-5277-11e5-93cc-650da4d16917.png)
![screenshot_2511112295](https://cloud.githubusercontent.com/assets/10261530/9673900/c5a20e9c-5277-11e5-9ee5-271b4ffcd190.png)

**Comment by Wayward1** [comment] 2015-09-04 05:54
I can't reproduce this. Does it happen with naturally generated pine needles, manually placed, or both? Also, how often?

**Comment by paramat** [comment] 2015-09-14 04:29
Minetest has occasional lighting bugs, so how often this happens is the issue.

**Comment by paramat** [comment] 2016-04-03 00:55
@nanepiwo Does this happen regularly? Also, mapgen lighting has been improved recently.

**Comment by est31** [comment] 2016-04-13 13:47
Yeah lets close this it cant be reproduced

**Closed by est31** 2016-04-13 13:47 UTC
Labels: Unconfirmed bug
