### ISSUE TITLE
screen freeze, permissions, max fps

### ISSUE THREAD

**Issue by LikeGuyS** [minetest/minetest#12225] opened 2022-04-25 16:54 UTC
## Problem

Problem A: When mining, the screen gets frozen.

Problem B: Players are plagued by the need to use /grantme each time they create a new world and wish to fly, change the time etc. which is extremely unpractical.

Problem C: The default max FPS is 30, which some new players might not notice is the default, and so they'll think the game is too laggy that it can barely run at 30.

## Solutions

Solution to A: Instead of freezing the screen, decrease the speed in which players can move the screen. Many players like me are used to this behavior that is in many games, including minecraft.

Solution to B: Give the creator of the world all permissions from the get-go since there is no point to restrict that.

Solution to C: Make the max FPS depending on the device's capacities.

**Comment by rollerozxa** [comment] 2022-04-26 07:59
Why do you keep throwing random miscellaneous stuff into one issue? Problem B is a feature not a bug, do `/grantme all` if you want all privileges in a world. Problem C is a duplicate of #12009. Problem A is solved in PR #7865 although it has not been merged yet.

**Closed** 2022-04-26 17:37 UTC
Labels: Android
