### ISSUE TITLE
The game crashes when i go beyone certain coordinates.

### ISSUE THREAD

**Issue by Herobrine-alpha** [minetest/minetest#12132] opened 2022-03-14 18:49 UTC
##### Minetest version

```
minetest-5.4.0-dev-10.13.6-osx.zip
```

##### OS / Hardware

Operating system: macOS monterey 12.2.1
CPU: M1 chip

GPU model M1 chip
OpenGL version: i dont know 

##### Steps to reproduce

Translated Report (Full Report Below)

```
Process:               minetest [3812]
Path:                  /private/var/folders/*/minetest.app/Contents/MacOS/minetest
Identifier:            net.minetest.minetest
Version:               ???
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-03-15 00:19:18.6228 +0530
OS Version:            macOS 12.2.1 (21D62)
Report Version:        12
Anonymous UUID:        18562227-A8B6-5044-ACA6-5EF0CFD19DB8

Sleep/Wake UUID:       D90B708E-7CD0-4F88-A72A-B3ADB4859D3E

Time Awake Since Boot: 53000 seconds
Time Since Wake:       6238 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0xe83dd817c1d93a69 -> 0x00005817c1d93a69 (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0xe83dd817c1d93a69
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [3812]

VM Region Info: 0x5817c1d93a69 is not in any region.  Bytes after previous region: 96378023393898  Bytes before following region: 8694056535447
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  ...(unallocated)
--->  GAP OF 0x5f9000000000 BYTES
      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-/rwx SM=PRV  

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   minetest                      	       0x1028eba2c irr::video::COpenGLDriver::setActiveTexture(unsigned int, irr::video::ITexture const*) + 108
1   minetest                      	       0x1028ed822 irr::video::COpenGLDriver::setMaterial(irr::video::SMaterial const&) + 130
2   minetest                      	       0x1023916d2 ClientMap::renderMap(irr::video::IVideoDriver*, int) + 562
3   minetest                      	       0x10274fbf2 irr::scene::CSceneManager::drawAll() + 1858
4   minetest                      	       0x1023f44fe RenderingCore::draw3D() + 22
5   minetest                      	       0x1023f60ee RenderingCorePlain::drawAll() + 14
6   minetest                      	       0x1023b5dff Game::updateFrame(ProfilerGraph*, RunStats*, float, CameraOrientation const&) + 2313
7   minetest                      	       0x1023b33ae Game::run() + 1402
8   minetest                      	       0x1023c4074 the_game(bool*, InputHandler*, GameStartData const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, ChatBackend&, bool*) + 116
9   minetest                      	       0x10238b5e3 ClientLauncher::run(GameStartData&, Settings const&) + 2893
10  minetest                      	       0x1026743ae main + 10610
11  dyld                          	       0x202f0e4fe start + 462

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffde88e4 0x7ff7ffde4000 + 18660
1   runtime                       	    0x7ff7ffdf5928 0x7ff7ffde4000 + 71976
2   runtime                       	    0x7ff7ffdf70a4 0x7ff7ffde4000 + 77988

Thread 2:
0   runtime                       	    0x7ff7ffe06814 0x7ff7ffde4000 + 141332

Thread 3:
0   runtime                       	    0x7ff7ffe06814 0x7ff7ffde4000 + 141332

Thread 4:: com.apple.NSEventThread
0   ???                           	    0x7ff89fbfe940 ???
1   libsystem_kernel.dylib        	    0x7ff80f631aba mach_msg_trap + 10
2   CoreFoundation                	    0x7ff80f734df1 __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff80f7334af __CFRunLoopRun + 1329
4   CoreFoundation                	    0x7ff80f7328a9 CFRunLoopRunSpecific + 567
5   AppKit                        	    0x7ff8121f6fd8 _NSEventThread + 132
6   libsystem_pthread.dylib       	    0x7ff80f66e4f4 _pthread_start + 125
7   libsystem_pthread.dylib       	    0x7ff80f66a00f thread_start + 15

Thread 5:
0   runtime                       	    0x7ff7ffe06814 0x7ff7ffde4000 + 141332

Thread 6:
0   runtime                       	    0x7ff7ffe06814 0x7ff7ffde4000 + 141332

Thread 7:
0   runtime                       	    0x7ff7ffe06814 0x7ff7ffde4000 + 141332

Thread 8:: ConnectionSend
0   ???                           	    0x7ff89fbfe940 ???
1   libsystem_kernel.dylib        	    0x7ff80f631b0e semaphore_timedwait_trap + 10
2   minetest                      	       0x1024e877c con::ConnectionSendThread::run() + 360
3   minetest                      	       0x1025864b8 Thread::threadProc(Thread*) + 82
4   minetest                      	       0x1025866dc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*), Thread*> >(void*) + 44
5   libsystem_pthread.dylib       	    0x7ff80f66e4f4 _pthread_start + 125
6   libsystem_pthread.dylib       	    0x7ff80f66a00f thread_start + 15

Thread 9:: ConnectionReceive
0   ???                           	    0x7ff89fbfe940 ???
1   libsystem_kernel.dylib        	    0x7ff80f639e4a __select + 10
2   minetest                      	       0x10250361d UDPSocket::Receive(Address&, void*, int) + 51
3   minetest                      	       0x1024eda14 con::ConnectionReceiveThread::receive(SharedBuffer<unsigned char>&, bool&) + 326
4   minetest                      	       0x1024ed78b con::ConnectionReceiveThread::run() + 297
5   minetest                      	       0x1025864b8 Thread::threadProc(Thread*) + 82
6   minetest                      	       0x1025866dc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*), Thread*> >(void*) + 44
7   libsystem_pthread.dylib       	    0x7ff80f66e4f4 _pthread_start + 125
8   libsystem_pthread.dylib       	    0x7ff80f66a00f thread_start + 15

Thread 10:: MinimapUpdate
0   ???                           	    0x7ff89fbfe940 ???
1   libsystem_kernel.dylib        	    0x7ff80f631af6 semaphore_wait_trap + 10
2   minetest                      	       0x1025864b8 Thread::threadProc(Thread*) + 82
3   minetest                      	       0x1025866dc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*), Thread*> >(void*) + 44
4   libsystem_pthread.dylib       	    0x7ff80f66e4f4 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff80f66a00f thread_start + 15

Thread 11:: MeshUpdate
0   ???                           	    0x7ff89fbfe940 ???
1   libsystem_kernel.dylib        	    0x7ff80f631af6 semaphore_wait_trap + 10
2   minetest                      	       0x1025864b8 Thread::threadProc(Thread*) + 82
3   minetest                      	       0x1025866dc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*), Thread*> >(void*) + 44
4   libsystem_pthread.dylib       	    0x7ff80f66e4f4 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff80f66a00f thread_start + 15


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000002  rbx: 0x0000000000000002  rcx: 0x0000000000000012  rdx: 0x0000000000040000
  rdi: 0x0000600003ffd4a0  rsi: 0x0000000000040000  rbp: 0x0000000309327a20  rsp: 0x0000000309327a00
   r8: 0x000095248dffbe40   r9: 0x0000000000000040  r10: 0x00000000000007fb  r11: 0x0000000000000100
  r12: 0xe83dd817c1d93a69  r13: 0x00006000075c1ff0  r14: 0x0000000000000001  r15: 0x00007fd478031e00
  rip: 0x00000001028eba2c  rfl: 0x0000000000000283
 tmp0: 0x000000000000012d tmp1: 0x00000001028eba18 tmp2: 0x00000001036fb464


Binary Images:
       0x102368000 -        0x102b7efff net.minetest.minetest (*) <eb83b92d-8467-3eee-b7ba-00483cebb29d> /private/var/folders/*/minetest.app/Contents/MacOS/minetest
       0x202f09000 -        0x202f74fff dyld (*) <7de33963-bbc5-3996-ba6e-f1d562c17c95> /usr/lib/dyld
    0x7ff7ffde4000 -     0x7ff7ffe13fff runtime (*) <faca02c7-0a4c-3629-a746-55ddcfee9116> /usr/libexec/rosetta/runtime
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff80f631000 -     0x7ff80f667fff libsystem_kernel.dylib (*) <c1d58a50-5a4d-3bcb-a1fc-ec0902ce34d3> /usr/lib/system/libsystem_kernel.dylib
    0x7ff80f6b5000 -     0x7ff80fbb5fff com.apple.CoreFoundation (6.9) <1d1db08b-810c-316e-b9d9-eecdff8ee6e3> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff81204a000 -     0x7ff812edbfff com.apple.AppKit (6.9) <9d3ab204-4858-3120-b002-5c38b02edec4> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7ff80f668000 -     0x7ff80f673fff libsystem_pthread.dylib (*) <ee564342-d8f2-396d-b642-40092cf34d82> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=948.8M resident=0K(0%) swapped_out_or_unallocated=948.8M(100%)
Writable regions: Total=2.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=2.3G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                 2176K        4 
CG image                            32K        8 
ColorSync                          224K       25 
CoreAnimation                      144K       11 
CoreGraphics                        12K        2 
CoreUI image data                  348K        6 
Foundation                          16K        1 
Kernel Alloc Once                    8K        1 
MALLOC                             1.3G      147 
MALLOC guard page                  192K        9 
MALLOC_LARGE (reserved)           10.2M        1         reserved VM address space (unallocated)
MALLOC_MEDIUM (reserved)         744.0M        7         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           128.0M        1         reserved VM address space (unallocated)
OpenGL GLSL                        256K        3 
Rosetta Arena                     4096K        2 
Rosetta Generic                   1128K      279 
Rosetta IndirectBranch            1024K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack               220K       22 
Rosetta Thread Context             220K       22 
STACK GUARD                         20K        5 
Stack                             13.1M       11 
Stack Guard                       56.0M        6 
VM_ALLOCATE                       19.3M      358 
VM_ALLOCATE (reserved)              80K       13         reserved VM address space (unallocated)
__DATA                            19.9M      338 
__DATA_CONST                      12.0M      184 
__DATA_DIRTY                       545K      101 
__FONT_DATA                          4K        1 
__GLSLBUILTINS                    5176K        1 
__LINKEDIT                       704.2M       29 
__OBJC_RO                         81.8M        1 
__OBJC_RW                         3136K        2 
__TEXT                           244.6M      353 
__UNICODE                          588K        1 
mapped file                        5.0G      456 
shared memory                      820K       18 
unshared pmap                     8992K        6 
===========                     =======  ======= 
TOTAL                              8.5G     2441 
TOTAL, minus reserved VM space     7.6G     2441 



-----------
Full Report
-----------

{"app_name":"minetest","timestamp":"2022-03-15 00:19:18.00 +0530","app_version":"","slice_uuid":"eb83b92d-8467-3eee-b7ba-00483cebb29d","build_version":"","platform":1,"bundleID":"net.minetest.minetest","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.2.1 (21D62)","incident_id":"F48A184E-3163-4648-8AE1-3C7776C6CEEA","name":"minetest"}
{
  "uptime" : 53000,
  "procLaunch" : "2022-03-15 00:18:51.2242 +0530",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "procStartAbsTime" : 1275763033218,
  "coalitionID" : 961,
  "osVersion" : {
    "train" : "macOS 12.2.1",
    "build" : "21D62",
    "releaseType" : "User"
  },
  "captureTime" : "2022-03-15 00:19:18.6228 +0530",
  "incident" : "F48A184E-3163-4648-8AE1-3C7776C6CEEA",
  "bug_type" : "309",
  "pid" : 3812,
  "procExitAbsTime" : 1276420378306,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "minetest",
  "procPath" : "\/private\/var\/folders\/*\/minetest.app\/Contents\/MacOS\/minetest",
  "bundleInfo" : {"CFBundleIdentifier":"net.minetest.minetest"},
  "storeInfo" : {"deviceIdentifierForVendor":"35623BA2-B999-5892-AA13-E1EFFFA190D7","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "net.minetest.minetest",
  "crashReporterKey" : "18562227-A8B6-5044-ACA6-5EF0CFD19DB8",
  "wakeTime" : 6238,
  "sleepWakeUUID" : "D90B708E-7CD0-4F88-A72A-B3ADB4859D3E",
  "sip" : "enabled",
  "vmRegionInfo" : "0x5817c1d93a69 is not in any region.  Bytes after previous region: 96378023393898  Bytes before following region: 8694056535447\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      commpage (reserved)        1000000000-7000000000   [384.0G] ---\/--- SM=NUL  ...(unallocated)\n--->  GAP OF 0x5f9000000000 BYTES\n      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-\/rwx SM=PRV  ",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0xe83dd817c1d93a69","rawCodes":[1,-1711974686782834071],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0xe83dd817c1d93a69 -> 0x00005817c1d93a69 (possible pointer authentication failure)"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":3812},
  "vmregioninfo" : "0x5817c1d93a69 is not in any region.  Bytes after previous region: 96378023393898  Bytes before following region: 8694056535447\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      commpage (reserved)        1000000000-7000000000   [384.0G] ---\/--- SM=NUL  ...(unallocated)\n--->  GAP OF 0x5f9000000000 BYTES\n      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-\/rwx SM=PRV  ",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":258023,"threadState":{"r13":{"value":105553239744496},"rflags":{"value":643},"rax":{"value":2},"rosetta":{"tmp2":{"value":4352619620},"tmp1":{"value":4337875480},"tmp0":{"value":301}},"r14":{"value":1},"rsi":{"value":262144},"r8":{"value":163984233709120},"rdx":{"value":262144},"r10":{"value":2043},"r9":{"value":64},"r15":{"value":140550523264512},"rbx":{"value":2},"r11":{"value":256},"rip":{"value":4337875500},"rbp":{"value":13039204896},"rsp":{"value":13039204864},"r12":{"value":16734769386926717545},"rcx":{"value":18},"flavor":"x86_THREAD_STATE","rdi":{"value":105553183364256}},"queue":"com.apple.main-thread","frames":[{"imageOffset":5782060,"symbol":"irr::video::COpenGLDriver::setActiveTexture(unsigned int, irr::video::ITexture const*)","symbolLocation":108,"imageIndex":0},{"imageOffset":5789730,"symbol":"irr::video::COpenGLDriver::setMaterial(irr::video::SMaterial const&)","symbolLocation":130,"imageIndex":0},{"imageOffset":169682,"symbol":"ClientMap::renderMap(irr::video::IVideoDriver*, int)","symbolLocation":562,"imageIndex":0},{"imageOffset":4094962,"symbol":"irr::scene::CSceneManager::drawAll()","symbolLocation":1858,"imageIndex":0},{"imageOffset":574718,"symbol":"RenderingCore::draw3D()","symbolLocation":22,"imageIndex":0},{"imageOffset":581870,"symbol":"RenderingCorePlain::drawAll()","symbolLocation":14,"imageIndex":0},{"imageOffset":318975,"symbol":"Game::updateFrame(ProfilerGraph*, RunStats*, float, CameraOrientation const&)","symbolLocation":2313,"imageIndex":0},{"imageOffset":308142,"symbol":"Game::run()","symbolLocation":1402,"imageIndex":0},{"imageOffset":376948,"symbol":"the_game(bool*, InputHandler*, GameStartData const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, ChatBackend&, bool*)","symbolLocation":116,"imageIndex":0},{"imageOffset":144867,"symbol":"ClientLauncher::run(GameStartData&, Settings const&)","symbolLocation":2893,"imageIndex":0},{"imageOffset":3195822,"symbol":"main","symbolLocation":10610,"imageIndex":0},{"imageOffset":21758,"symbol":"start","symbolLocation":462,"imageIndex":1}]},{"id":258042,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18660,"imageIndex":2},{"imageOffset":71976,"imageIndex":2},{"imageOffset":77988,"imageIndex":2}]},{"id":258069,"frames":[{"imageOffset":141332,"imageIndex":2}]},{"id":258074,"frames":[{"imageOffset":141332,"imageIndex":2}]},{"id":258106,"name":"com.apple.NSEventThread","frames":[{"imageOffset":140705808771392,"imageIndex":3},{"imageOffset":2746,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":4},{"imageOffset":523761,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":5},{"imageOffset":517295,"symbol":"__CFRunLoopRun","symbolLocation":1329,"imageIndex":5},{"imageOffset":514217,"symbol":"CFRunLoopRunSpecific","symbolLocation":567,"imageIndex":5},{"imageOffset":1757144,"symbol":"_NSEventThread","symbolLocation":132,"imageIndex":6},{"imageOffset":25844,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":8207,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]},{"id":258144,"frames":[{"imageOffset":141332,"imageIndex":2}]},{"id":258145,"frames":[{"imageOffset":141332,"imageIndex":2}]},{"id":258146,"frames":[{"imageOffset":141332,"imageIndex":2}]},{"id":258175,"name":"ConnectionSend","frames":[{"imageOffset":140705808771392,"imageIndex":3},{"imageOffset":2830,"symbol":"semaphore_timedwait_trap","symbolLocation":10,"imageIndex":4},{"imageOffset":1574780,"symbol":"con::ConnectionSendThread::run()","symbolLocation":360,"imageIndex":0},{"imageOffset":2221240,"symbol":"Thread::threadProc(Thread*)","symbolLocation":82,"imageIndex":0},{"imageOffset":2221788,"symbol":"void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*), Thread*> >(void*)","symbolLocation":44,"imageIndex":0},{"imageOffset":25844,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":8207,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]},{"id":258176,"name":"ConnectionReceive","frames":[{"imageOffset":140705808771392,"imageIndex":3},{"imageOffset":36426,"symbol":"__select","symbolLocation":10,"imageIndex":4},{"imageOffset":1685021,"symbol":"UDPSocket::Receive(Address&, void*, int)","symbolLocation":51,"imageIndex":0},{"imageOffset":1595924,"symbol":"con::ConnectionReceiveThread::receive(SharedBuffer<unsigned char>&, bool&)","symbolLocation":326,"imageIndex":0},{"imageOffset":1595275,"symbol":"con::ConnectionReceiveThread::run()","symbolLocation":297,"imageIndex":0},{"imageOffset":2221240,"symbol":"Thread::threadProc(Thread*)","symbolLocation":82,"imageIndex":0},{"imageOffset":2221788,"symbol":"void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*), Thread*> >(void*)","symbolLocation":44,"imageIndex":0},{"imageOffset":25844,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":8207,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]},{"id":258178,"name":"MinimapUpdate","frames":[{"imageOffset":140705808771392,"imageIndex":3},{"imageOffset":2806,"symbol":"semaphore_wait_trap","symbolLocation":10,"imageIndex":4},{"imageOffset":2221240,"symbol":"Thread::threadProc(Thread*)","symbolLocation":82,"imageIndex":0},{"imageOffset":2221788,"symbol":"void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*), Thread*> >(void*)","symbolLocation":44,"imageIndex":0},{"imageOffset":25844,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":8207,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]},{"id":258245,"name":"MeshUpdate","frames":[{"imageOffset":140705808771392,"imageIndex":3},{"imageOffset":2806,"symbol":"semaphore_wait_trap","symbolLocation":10,"imageIndex":4},{"imageOffset":2221240,"symbol":"Thread::threadProc(Thread*)","symbolLocation":82,"imageIndex":0},{"imageOffset":2221788,"symbol":"void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(Thread*), Thread*> >(void*)","symbolLocation":44,"imageIndex":0},{"imageOffset":25844,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":7},{"imageOffset":8207,"symbol":"thread_start","symbolLocation":15,"imageIndex":7}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4332093440,
    "CFBundleIdentifier" : "net.minetest.minetest",
    "size" : 8482816,
    "uuid" : "eb83b92d-8467-3eee-b7ba-00483cebb29d",
    "path" : "\/private\/var\/folders\/*\/minetest.app\/Contents\/MacOS\/minetest",
    "name" : "minetest"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8639254528,
    "size" : 442368,
    "uuid" : "7de33963-bbc5-3996-ba6e-f1d562c17c95",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703126405120,
    "size" : 196608,
    "uuid" : "faca02c7-0a4c-3629-a746-55ddcfee9116",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703386767360,
    "size" : 225280,
    "uuid" : "c1d58a50-5a4d-3bcb-a1fc-ec0902ce34d3",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703387308032,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5246976,
    "uuid" : "1d1db08b-810c-316e-b9d9-eecdff8ee6e3",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1856.107"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703430909952,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15278080,
    "uuid" : "9d3ab204-4858-3120-b002-5c38b02edec4",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.30.116"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703386992640,
    "size" : 49152,
    "uuid" : "ee564342-d8f2-396d-b642-40092cf34d82",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 140703383748608,
  "size" : 15218196480,
  "uuid" : "5c9ff5db-8827-329a-8a37-2483935a9ea1"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=948.8M resident=0K(0%) swapped_out_or_unallocated=948.8M(100%)\nWritable regions: Total=2.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=2.3G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               384K        3 \nActivity Tracing                   256K        1 \nCG backing stores                 2176K        4 \nCG image                            32K        8 \nColorSync                          224K       25 \nCoreAnimation                      144K       11 \nCoreGraphics                        12K        2 \nCoreUI image data                  348K        6 \nFoundation                          16K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                             1.3G      147 \nMALLOC guard page                  192K        9 \nMALLOC_LARGE (reserved)           10.2M        1         reserved VM address space (unallocated)\nMALLOC_MEDIUM (reserved)         744.0M        7         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           128.0M        1         reserved VM address space (unallocated)\nOpenGL GLSL                        256K        3 \nRosetta Arena                     4096K        2 \nRosetta Generic                   1128K      279 \nRosetta IndirectBranch            1024K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack               220K       22 \nRosetta Thread Context             220K       22 \nSTACK GUARD                         20K        5 \nStack                             13.1M       11 \nStack Guard                       56.0M        6 \nVM_ALLOCATE                       19.3M      358 \nVM_ALLOCATE (reserved)              80K       13         reserved VM address space (unallocated)\n__DATA                            19.9M      338 \n__DATA_CONST                      12.0M      184 \n__DATA_DIRTY                       545K      101 \n__FONT_DATA                          4K        1 \n__GLSLBUILTINS                    5176K        1 \n__LINKEDIT                       704.2M       29 \n__OBJC_RO                         81.8M        1 \n__OBJC_RW                         3136K        2 \n__TEXT                           244.6M      353 \n__UNICODE                          588K        1 \nmapped file                        5.0G      456 \nshared memory                      820K       18 \nunshared pmap                     8992K        6 \n===========                     =======  ======= \nTOTAL                              8.5G     2441 \nTOTAL, minus reserved VM space     7.6G     2441 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61fb0e87c773c43cde3bb80e"
      },
      "deploymentId" : 240000303
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000119
    },
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 240000027
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "622657ce37186c771d5404ad"
      },
      "deploymentId" : 240000414
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000274
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookAir10,1, BootROM 7429.81.3, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Oct 26 2021 16:10:41 version 18.20.310.15.7.8.120 FWID 01-5d6c3867
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB Receiver
USB Device: USB31Bus
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.
```

**Comment by SmallJoker** [comment] 2022-03-14 21:13
Duplicate of #11142. Either uninitialized pointer or some weird shit going on Irrlicht?

**Closed by SmallJoker** 2022-03-14 21:13 UTC
Labels: Unconfirmed bug

**Comment by sfan5** [comment] 2022-03-14 21:17
Also retest this with 5.5, 5.4 is old and unsupported.
