### ISSUE TITLE
Remove air stepheight

### ISSUE THREAD

**Issue by Yepoleb** [minetest/minetest#3397] opened 2015-11-22 18:31 UTC
Being able to climb blocks in the air creates weird glitches when jumping on blocks. This is how it currently looks:

![minetest_jump1_cut](https://cloud.githubusercontent.com/assets/5777580/11325418/affdc2e2-914d-11e5-8ec2-7615c88a450e.png)

When the player gets near the edge, he gets teleported up a small distance and can instantly jump again. The teleport causes a quick jump in the view and looks a bit like lagging. This is how i think it should be:

![minetest_jump2_cut](https://cloud.githubusercontent.com/assets/5777580/11325422/b50dd56a-914d-11e5-8623-6e1f1d31d0ec.png)

It feels much smoother and doesn't create any jumps in the view. To achieve this, I changed the stepheight switch to `touching_ground ? (BS*0.6) : 0.0`, set `movement_speed_jump` to 7.45 and applied #3347. A jump speed of 7.45 is about 1.25 nodes, which is the same for Minecraft.

**Comment by est31** [comment] 2015-11-23 14:03
Nice graphs. Idk is this a dupe of #132 ?

**Comment by Yepoleb** [comment] 2015-11-23 23:03
Thanks, I made them with matplotlib. This issue is not a dupe of #132, but the same bug can also cause the opposite effect, where you can jump on the edge of a node, without standing on it. I applied the fix to make sure the result can be reproduced reliably.

**Comment by Calinou** [comment] 2015-11-24 06:12
Note that this probably has side effectson gameplay. For instance, you can't walk (with or without fast mode) on "dotted bridges", ie. a bridge where only half of the nodes are placed (to save nodes), see diagram below (side view):

```
O
O ->
X_X_X_X_X_
```

**Comment by 0-afflatus** [comment] 2015-11-24 11:34
If this means the player has to jump single node gaps, that would be a big change in behaviour. How would it affect parkour?

**Comment by Yepoleb** [comment] 2015-11-25 05:13
Forgot to mention that I also changed the jump speed for balance, it's fixed now. I think dotted bridges shouldn't behave like normal bridges. If saving a few nodes is that important to you, having to use the jump key is a fair trade-off in my opinion. They're really ugly anyway, why would anyone build them with something that's worth collecting? Single node gaps weren't noticeable before, so there was probably no reason to use them as parkour elements.

**Comment by paramat** [comment] 2015-11-25 05:55
More importantly would it disable the ability to pass over air nodes without falling when walking along a steep diagonal slope?

**Comment by Yepoleb** [comment] 2015-11-25 13:55
Yes, it would break diagonal slopes for walking. Crouching still works and jumping can be used as a workaround, which could be seen as a trade-off for building a proper path. If you really don't want to cause any side effects, we could increase the collision radius of the player to allow these things, which is the proper way of doing it.

> There may be good reason for how it is

That's the worst argument against changing something.

> and the current behaviour is not really a problem.

Have you tried the fix? I can't play without it anymore.

**Comment by 0-afflatus** [comment] 2015-11-25 14:53
> If you really don't want to cause any side effects, we could increase the collision radius of the player to allow these things, which is the proper way of doing it.

Would that not break passing through single-node shafts? I know we're not specifically concerned with reality, but it should be possible to walk a 1m gap **and** pass though it.
I'll reserve judgement until I've had a chance to properly test.

**Comment by Yepoleb** [comment] 2015-11-25 15:20
I'd just use the already existing crouching mechanics (without the slowdown of course), they work as intended.

**Comment by paramat** [comment] 2015-11-26 13:21
Well what i mean is there may be side effects we haven't thought of, @celeron55 any comments?

**Comment by paramat** [comment] 2015-11-26 14:02
Being able to catch the edge of a node and make a rapid re-jump is good, does your change prevent running fast up a flight of stairs in a rapid series of re-jumps? I've not noticed any unpleasant teleportation upwards so this doesn't seem much of a problem.

**Comment by paramat** [comment] 2015-11-28 13:37
> When the player gets near the edge, he gets teleported up a small distance and can instantly jump again

As far as i know this is fine-tuned to enable the climbing of a 45 degree slope of full nodes fast in a rapid series of re-jumps, an almost continuous upwards motion. Your changes would seem to make this a slower climb where each jump is a jump-and-fall, also there may be more hitting-of-head on the ceiling of a dungeon staircase (of full nodes).

A year or two ago player motion was changed which broke the fast climb feature, the changes were reverted a while after. As far as i know jump speed has been tuned so that the player will just hit the edge of the node to trigger stepheight to in turn enable an instant re-jump.

The 'teleporting up' of the player is no different to what happens when the player automatically climbs a half-node rise, so this is a normal and acceptable behaviour. Although the upwards motion is instant for player co-ordinates we have camera-smoothing which is there to smooth-out these instant movements due to stepheight.

**Comment by 0-afflatus** [comment] 2015-11-29 11:53
In short, if it ain't broke :-1:

**Comment by Yepoleb** [comment] 2015-11-29 20:31
If you want to keep around bugs because it's convenient to the player, that's your decision. I'm not going to play a game which feels so unfinished and broken. Small communities are better anyway, so keep doing what you do.

**Comment by 0-afflatus** [comment] 2015-11-29 21:44
I have not noticed this problem myself and read nothing in this thread that confirms this is a bug. That doesn't mean it isn't a bug, but I would like more information as to why you think it is broken. There are also concerns about potential side-effects, which need addressing. If you think your change will improve the game, then you need to argue the case for it better. My opinion is not as important as that of the core devs and it is them you need to convince. A couple of negative comments does not constitute an outright rejection, I know it can be frustrating, but please be patient.

**Comment by Yepoleb** [comment] 2015-12-01 03:49
Climbing a 45° slope of full nodes rapidly is a bad feature in my opinion. If the player has to jump that high, it should be slow. There's still the option to place stairs, which again adds some balance to the game.

Teleporting up is indeed not a problem when walking up stairs, because that's the way everyone expects it to be. This is not the case for jumping up blocks. I don't know any other game which has an air step height.

I know my changes will break stuff, but they're not just pulled out of my head. It's the way all other games do it, especially Minecraft.

**Comment by paramat** [comment] 2015-12-01 20:33
If it's possible to step-up half a node when climbing a slab, then it seems acceptable to step-up a smaller distance when just missing the edge of a node.

> Climbing a 45° slope of full nodes rapidly is a bad feature in my opinion

Well this was disabled before for a while and then reverted, celeron55 insists this feature remains as it is a long-running intended feature, the devs agree. The discussion was that as Minetest has a huge world height there will be a lot more vertical travel and jumping, mostly in places without half-node stairs. Minecraft-type jumping would make these long climbing journeys slow and painful for the hands. Upcoming mapgens have mountains up to y = 1000, there will also hopefully be stacked realms, some of which will be accessible by climbing towers or mountains 1500 nodes high.

**Comment by est31** [comment] 2015-12-01 23:34
Yeah, we aren't minecraft with +127 height limit. Let's close this.

**Closed by est31** 2015-12-01 23:34 UTC
Labels: @ Client / Audiovisuals, not a bug, won't add
