### ISSUE TITLE
Red Sun When sun.png is Used

### ISSUE THREAD

**Issue by LazyJ** [minetest/minetest#2527] opened 2015-03-22 16:46 UTC
**Minetest Engine:**   61f2d0c
**Minetest_Game:**   [9eb952] (https://github.com/minetest/minetest_game/commit/9eb9502209b33bed33a36fb3db2ab4a59716fe5b)
**Rendering:**   OpenGL *(Ubuntu 14.10, nVidia)*
**Texturing/Filters:**   None/Bi-Linear/Tri-Liniear, and Mipmap & Aniso
**Shaders:**   On, off, and combinations.

The sun is red when sun.png is used. It doesn't matter what the image is.

I tried RealBadAngel's "Haven" texture pack, VanessaE's most recent "HDX-512" and "HDX-64" texture packs and they all had red suns.

Then I *copied and renamed* the "moon.png" to "sun.png" just to see if it was a problem with the png file itself - it still displayed red in Minetest.

I even made my own sun.png - a green circle with GIMP, but that turned out black in Minetest.

I toggled through different combinations of texturing, filtering, and shaders settings - still a red sun.

I loaded the test world in to Minetest 0.4.12-stable and tried the various sun.pngs there and they all displayed normally.

The night time moon.png is displayed normally in both the recent dev release, 61f2d0c, and the stable release.

Below are screenshots of the "moon-sun" sun.png displaying red in the dev release, 61f2d0c, and displaying white (normal) in the stable release, and one of the night time moon.png in 61f2d0c. *(I flew up above the clouds to take the screenshots because the clouds kept blocking the sun/moon.)*

**Red "Moon-Sun" - Dev Version**
![A red moon graphic during the day in place of the sun graphic.](http://i.imgur.com/mPAUOr3.png)

**Normal Colored (White) "Moon-Sun" - Stable Version**
![A moon graphic during the day in place of the sun graphic.](http://i.imgur.com/U5LdtPv.png)

**Normal Colored (White), Night Time Moon - Both Stable and Dev Versions**
![A moon graphic during the night.](http://i.imgur.com/qOWnMU9.png)

**Comment by C1ffisme** [comment] 2015-03-22 21:57
Interesting. I wonder if there is anything wrong with specifically the sun code that isn't in the moon code.

**Comment by est31** [comment] 2015-03-23 01:51
@LazyJ, if you have time, could you, trough testing, find out, whether the problem is in the engine or `minetest_game` (first setting one to 0.4.12, then the other), and then [bisect](http://git-scm.com/book/tr/v2/Git-Tools-Debugging-with-Git#Binary-Search) that repo?

**Comment by proller** [comment] 2015-03-23 05:00
why still no tag "already fixed in freeminer" ?

**Comment by LazyJ** [comment] 2015-03-23 05:24
@est31, I found the commit that creates the red sun: 2015_03_21, 837a2e1

**Setup**
* Tested in the same minetest_game in differnet engine commits.
* Tested in the minimal game from each engine.
* On - shaders, bumpmaping, parallax occlusion, waving water, waving leaves, waving plants
* Off - generate normalmaps
* Texturing: bilinear filter, mipmap + aniso. filter
* Rendering: OpneGL
* On - smooth lighting, enable particles, 3d clouds, fancy trees, connected glass, node highlighting.
* Off - opaque water
* GUI scale factor: 1.0

**Minetest Engine Commit:** 2015_03_21, 837a2e1 - red sun
**Minimal Game:** - red sun
**Minetest_Game Commit:**   2015_03_21, [9eb9502](https://github.com/minetest/minetest_game/commit/9eb9502209b33bed33a36fb3db2ab4a59716fe5b) - red sun


**Minetest Engine Commit:** 2015_03_21, 709f4a5 - white sun
**Minimal Game:** - white sun
**Minetest_Game Commit:**   2015_03_21, [9eb9502](https://github.com/minetest/minetest_game/commit/9eb9502209b33bed33a36fb3db2ab4a59716fe5b) - white sun

**Comment by Zeno-** [comment] 2015-03-23 07:05
commit 6cf7c89236d6b222f53ca9c8d681d6cde656bea1

**Closed by Zeno-** 2015-03-23 07:05 UTC
