### ISSUE TITLE
Missing 'item_image_button' documentation.

### ISSUE THREAD

**Issue by Skamiz** [minetest/minetest#12787] opened 2022-09-20 09:23 UTC
##### Summary
The Lua API fails to mention that 'item_image_button' inherits styling information from 'image_button'.
Relevant API part: https://github.com/minetest/minetest/blob/5.6.0/doc/lua_api.txt#L3000

##### Steps to reproduce
Add this somewhere:
`minetest.register_on_joinplayer(function(player, last_login)
	minetest.after(1, player.set_formspec_prepend, player, "style_type[image_button;bgimg=default_stone.png]")
end)`
Start MTG and observe the Recipe page.
![image](https://user-images.githubusercontent.com/48406239/191220441-55c2b880-183c-457c-8eec-1b2010bc2b18.png)
See that 'item_image_button' are also affected by the styling.

**Comment by Zughy** [comment] 2022-11-23 14:08
Can't reproduce neither on 5.6.1 nor on latest master. I've tried with different texture packs, RPG16 included. Same result, closing

**Closed by Zughy** 2022-11-23 14:08 UTC
Labels: Unconfirmed bug, @ Documentation, Trivial, Beginner Friendly, Formspec
