### ISSUE TITLE
“Halo” node highlighting does not update after replacing block

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5931] opened 2017-06-06 11:21 UTC
How to reproduce:

* Enabe “halo”-type node highlighting
* Place small plants with a small selection box and with `buildable_to=true` somewhere (Minetest Game examples: grass, jungle grass, blue geranium)
* Hold any full-cube block, like dirt, stone, sand, etc.
* Point to any of these plants and build the block so it gets replaced
* Do not move the mouse, look closely at the resulting selection box

Bug:
The node highlighting is not updated after you placed the block. It should display the new selection box of the full-cube block, but instead you still have the selection box as if the plant would still be there.

Tested in: 7786521f151b6006656768fdd308f1d7e1635645

**Comment by Ezhh** [comment] 2018-04-03 17:39
Still an issue, but it only appears to happen if you target the side of the node you replace. I can't duplicate when targeting the top.

**Comment by rubenwardy** [comment] 2018-05-14 11:41
duplicate of #3873

**Closed by rubenwardy** 2018-05-14 11:41 UTC
Labels: @ Client / Audiovisuals, Bug
