### ISSUE TITLE
Allow texture packs to change the size of the sun/moon

### ISSUE THREAD

**Issue by dsohler** [minetest/minetest#6732] opened 2017-12-04 03:01 UTC
Currently (0.4.16) sun and moon are always the same size regardless of the width and height of `sun.png` and `moon.png`.

* [moon in 64x64 pixels](https://user-images.githubusercontent.com/1668792/33534128-e708fb48-d8a5-11e7-8f20-08920cb6c431.png)
* [moon in 1024x1024 pixels](https://user-images.githubusercontent.com/1668792/33534129-e722bccc-d8a5-11e7-9579-239513a9a0cd.png)
* [sun in 64x64 pixels](https://user-images.githubusercontent.com/1668792/33534130-e73d3746-d8a5-11e7-9b1e-c06d21d95bea.png)
* [sun in 1024x1024 pixels](https://user-images.githubusercontent.com/1668792/33534131-e75684bc-d8a5-11e7-844c-ab6553f5e218.png)

Moon and sun should scale according to the images used for them like the crosshair does (just for reference: the crosshair [in 64x64 pixels](https://user-images.githubusercontent.com/1668792/33534394-5dec03da-d8a7-11e7-9fe1-8e1ccc041f95.png) and [in 1024x1024 pixels](https://user-images.githubusercontent.com/1668792/33534395-5e0445d0-d8a7-11e7-9bc7-d38eb2582b0f.png))

**Comment by ThomasMonroe314** [comment] 2017-12-04 12:54
I don't think you can compare the sun and moon with the crosshair, because the sun is in the 3D world while the crosshair is in the HUD.

I don't think this is a good idea because lets say you wanted an HD txpk, the sun and moon would be HUGE.

But yes, you should at least be able to control the scale.

**Comment by dsohler** [comment] 2017-12-04 14:46
> I don't think you can compare the sun and moon with the crosshair, because the sun is in the 3D world while the crosshair is in the HUD.

As far as I can tell sun and moon aren’t *in the 3D world* but are skybox decorations. But you are right. the crosshair is in the HUD. But that wasn’t my point there. I just wanted to point out that scaling something based on image size is already done.

> I don't think this is a good idea because lets say you wanted an HD txpk, the sun and moon would be HUGE.

Depends on what the texture pack artists do.

If they change the image size of the moon for example to be more detailed and appear a little larger as it does now I don’t think that would be that bad (see [this mock-up GIF animation](https://user-images.githubusercontent.com/1668792/33558265-b968e9a0-d909-11e7-8c45-ed7549ed3c6e.gif) using an artistic drawing of a shattered moon).

**Comment by tobyplowy** [comment] 2017-12-04 23:24
Ok First Of All I Really Want Is this Would Be super useful 

BUT what if I want to have a really high resolution texture but don't want the sun/moon to be big
Or what if I want a very big sun/moon but I whant to use a small texture

Basically what I wanna say is I think it's a bad Idea to bace The scale of the moon/sun on the Texture resolution 

Maybe a new command can be added to override.txt?
Like moon scale (insert number for size here)
And sun scale (insert number for size here)

**Comment by GreenXenith** [comment] 2017-12-05 09:49
just use sun_64.png or sun_32.png etc...
Game can find the number after _ and scale it accordingly.

**Comment by dsohler** [comment] 2017-12-05 22:34
> just use sun_64.png or sun_32.png etc...
> Game can find the number after _ and scale it accordingly.

What version? I tried with 850 (the actual resolution of the image I’m using) and with 32 and 64. In all cases the default texture was shown. This applies to the moon and the sun texture as well.

~~~~
$ minetest --version
Minetest 0.4.16 (Linux)
Using Irrlicht 1.8.4
Build info: VER=0.4.16 BUILD_TYPE=Release RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/share/minetest"
~~~~

**Comment by GreenXenith** [comment] 2017-12-05 22:35
> What version? I tried with 850 (the actual resolution of the image I’m using) and with 32 and 64. In all cases the default texture was shown. This applies to the moon and the sun texture as well.

My bad, I should have clarified better. Read edit.

**Comment by dsohler** [comment] 2017-12-05 22:42
Ah, okay :smile: 

Too bad none of the devs seem to care.

**Comment by dsohler** [comment] 2017-12-07 23:17
@rubenwardy Of course, thanks for :-1: my 100% correct statement. The issue is almost a week old now and wasn’t even classified yet. I give a shit on your opinion. Could you please just ignore me? Thanks.

**Comment by Flairieve** [comment] 2017-12-08 20:00
@dsohler The developers do care! If they didn't care then why are they still working on the game? They do care about the community and the players that surround the community! 

They might of not picked up this suggestion yet probably because they are working on very major parts of the game right now! Some players might like suggestion this or not. You just need patience and wait until they decide if your suggestion is good or not!

**Comment by dsohler** [comment] 2017-12-08 20:09
> they are working on very major parts of the game right now!

Like feature requests for the sound API or a generic “discussion issue” on the main menu that are already labeled properly and were created after this issue? Sure. :rofl:

**Comment by Flairieve** [comment] 2017-12-08 20:11
@dsohler Look at the projects tab to see what they are currently doing for Minetest 5.0!

**Comment by dsohler** [comment] 2017-12-08 20:12
@Flairieve Look at the issues tab to see what they have labeled after this issue!

**Comment by Flairieve** [comment] 2017-12-08 20:20
@dsohler Hey look a label see they do care! You just need to have patience!

**Comment by dsohler** [comment] 2017-12-08 20:28
A useless label to troll me, I know. Useless first degree because Github labels aren’t meant for trolling and useless second degree because the issue was never filed as bug.

But you know what? Fuck it. It’ll never be implemented because I submitted this issue and 3/4 devs active on Github dislike me. But that is okay.

**Comment by Flairieve** [comment] 2017-12-08 20:36
@dsohler They wouldn't hate you if you didn't say the "developers were careless" about their game!

**Comment by dsohler** [comment] 2017-12-08 20:39
Whatever.

If they want they can re-open this issue.

I don’t care anymore.

**Comment by Flairieve** [comment] 2017-12-08 20:42
@dsohler You can say sorry to them and they might not hate you anymore! 😃

**Comment by Calinou** [comment] 2017-12-08 20:59
As this cannot be specified in the image files themselves, texture packs would have to include some configuration file (e.g. `texture_pack.conf`) which would include information such as sun/moon size, optional speed overrides for animated textures.

In case this is desired, a separate issue should be opened for this.

**Comment by dsohler** [comment] 2017-12-08 21:14
Since it won’t be fair to anyone else to close this absolutely valid feature request issue I reopen it but likely will unsubscribe in a few days because I know this won’t be implemented ever.

> texture packs would have to include some configuration file (e.g. `texture_pack.conf`)

This seems to be a reasonable good idea. So TP artists can create what they want and have a section in `texture_pack.conf` to scale sun and moon and set animation speed et al.

**Comment by paramat** [comment] 2017-12-08 23:51
Good idea, and yes seems a parameter for size is best, perhaps read from texture name as suggested.
In the longer term we are keen for more control over sun and moon, for example allowing them to appear in front of a custom skybox. So further sky APIs are likely and they would possibly then control sun/moon size.

**Comment by paramat** [comment] 2017-12-09 10:10
Related #6128 altering sun and moon is probably best done in a mod with an API, not by texture pack as now. Texture size would be specified here.
Related #1997

**Comment by paramat** [comment] 2018-11-17 04:59
So, issue is valid, but changing the appearence of sun and moon from a texture pack seems a bad idea in the first place, so i feel this would somewhat be unjustified effort in the wrong direction. I would prefer we take the approach of #6128 
> The issue is almost a week old now and wasn’t even classified yet.

Sorry i missed this, i usually classify all issues within 2 days. However, mistakes happen and too much of a big thing was made of this.

The level of unpleasantness from the author means that although the issue is valid i am closing this, if someone else would like this feature please open a new issue that is bearable to read.

**Closed by paramat** 2018-11-17 04:59 UTC
Labels: @ Client / Audiovisuals, Core dev consideration needed, Feature request

**Comment by GreenXenith** [comment] 2018-11-17 05:02
> changing the appearence of sun and moon from a texture pack seems a bad idea 

Besides, the `set_sky` PRs by Jordach will hopefully provide this function anyway.
