### ISSUE TITLE
Reconsider Android support for 0.5.0 (next release after 0.4.16)

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5812] opened 2017-05-25 07:01 UTC
Copied from IRC:

///////////////////
EDIT: Some of these advantages would not happen, as explained later. So i'm not so sure about this now, there may be other actions we can do to improve the Android app issues.
//////////////////

I think we should drop android support, we're halfway to that already.
Then the apps have to work for their money instead of just copying our code.
It would also reduce our workload.
The apps would continue but would have to do their own android code, this would weed out the lazy ones and leave the more serious commited ones, like Multicraft.

I made a post on the forum 11 months ago asking for new devs to help with android code, nothing has come of that.
This would actually help android players as their choice of apps is narrowed to higher quality ones.
and hopefully narrowed to the ones less likely to have adds and payment scams.
0.5.0 is next release so a good time to do this.

So it has been at least a year now with android being neglected by devs and hoping someone would appear to maintain it, long enough. i remember a year ago we talked about possibly dropping android but waiting until we had spent some time waiting for an enthusiastic android dev to appear, or for sapier to return.
We could perhaps team up with a particularly good app and declare it the 'officially recommended' one
maybe multicraft, the author has helped out here a few times.

**Comment by nerzhul** [comment] 2017-05-25 10:24
This is a solution to cut android support making minetest less used over android for a time. I don't know if it's possible to add a clause on Android support to protect us against rogue apps which makes money over us.

**Comment by Fixer-007** [comment] 2017-05-25 10:30
What is wrong with current android official build? I would like to have it instead of using ad infested garbage.

**Comment by nerzhul** [comment] 2017-05-25 10:49
the problem is the ad infested guys which polute and mask our real and proper build. Maybe i should use bounty source to promote minetest on play store ?

**Comment by paramat** [comment] 2017-05-25 12:09
Most android users use Multicraft or other non-official apps, it wouldn't make much difference to Android usage, just make the authors of the apps work harder, and weed out the worst ones.

**Comment by est31** [comment] 2017-05-25 13:13
I'm not sure what's your goal with this, but you won't prevent people from creating android ports of minetest.

**Comment by NathanSalapat** [comment] 2017-05-25 13:17
@est31 the goal is to stop people from being able to just copy code they didn't write and add ads to it and make money off of the efforts of our devs, while making users endure ads, or pay to get privs.

**Comment by paramat** [comment] 2017-05-25 13:31
> but you won't prevent people from creating android ports of minetest.

I know, i stated this in the first post, and the goals are stated too.

**Comment by est31** [comment] 2017-05-25 14:25
Even if Minetest itself stops supporting Android, all the advantage is gone if Multicraft or any other compatible fork of minetest updates to 0.5.0. Multicraft will have to release the source code due to copyleft, so the cheap scammers would get a base to do their admob/payment modifications on.

**Comment by paramat** [comment] 2017-05-25 14:33
I see, just one app would have to work more then, and it wouldn't improve the quality of apps generally.

What remains is less workload for us.

**Comment by octacian** [comment] 2017-05-25 15:28
What needs to be done currently to maintain the Android build? I'd personally be happy to help, although I don't have much time, however, I'm not at all familiar with C++ or the Android port itself.

**Comment by paramat** [comment] 2017-05-25 15:32
It would need C++ ability.

**Comment by nerzhul** [comment] 2017-05-25 15:34
the android port is maintained but i has no real android app quality, the master formspec is not very user friendly and the port requires real communication and promotion to users

**Comment by rubenwardy** [comment] 2017-05-25 15:35
> What needs to be done currently to maintain the Android build?

Here's a good start: https://github.com/minetest/minetest/issues?q=is%3Aopen+is%3Aissue+label%3AAndroid

**Comment by rubenwardy** [comment] 2017-05-25 19:42
http://irc.minetest.net/minetest/2017-05-25#i_4940504

**Comment by Fixer-007** [comment] 2017-05-25 19:57
Side note: you sure there will be 0.5 after 0.4.16? Where that was discussed? What is planned?

**Comment by rubenwardy** [comment] 2017-05-25 20:06
> Side note: you sure there will be 0.5 after 0.4.16? Where was that discussed? What is planned?

Originally this release was supposed to be 0.5 due to CSM and map breakages, but @nerzhul wanted a release before then

**Comment by nerzhul** [comment] 2017-05-25 20:07
It will be done yes. We switch to C++11 it's a breaking change, and some of us have breaking changes to add. I think i will rewrite the whole network stack which is not very good and have some side effects, especially on slow clients, we need to continue CSM and add some interesting features like mod channels, better formspec integration client side etc...

**Comment by nerzhul** [comment] 2017-05-25 20:08
@rubenwardy we started to write some contracts with end users, especially the two years protocol support on a major release, refactor project enhancing code, team, be more agile, less slow and dead...

**Comment by IhrFussel** [comment] 2017-05-25 20:16
Okay so since my discussion in IRC was already linked to this issue I will just confirm here that I find this idea to be WRONG in many ways...

1. Players will be FORCED to switch to 3rd party apps that most likely contain ads, inapp purchases and maybe malicious code

2. Server owners will NOT be able to help ANYONE on phone anymore since EVERYONE now have to choose a different app (right now at least a MINORITY of the players still uses the official app and server owners can explain to them the UI / controls)

3. I don't believe you that maintaining the Android app is THAT costly that you need to drop it, period. There are VERY FEW engine changes (as far as I read commits) that actually REQUIRE a modification of an Android-specific file.

**Comment by octacian** [comment] 2017-05-25 23:22
I have to agree with @IhrFussel, dropping Android support is not the way to go. When I first saw the news post about looking for someone to maintain the Android app, I considered putting in some effort myself but quickly dropped the idea because I don't know much C++ at all, so I just left it be with the assumption that someone else would volunteer. However, with the current status, I am beginning to reconsider. Though I'm not sure how much I would be able to do at first considering skill and time limitations, I'm planning on finding myself a working Android device again and putting in some effort, even if it means learning C++ entirely (I've wanted to for a while now). I've been relatively interested in the Android port for quite a bit but always thought someone else would step in to take care of it. So, assuming that I'm able to find an Android device in the near future (yes, I've considered emulators), I'll see what I can do :D

**Comment by nerzhul** [comment] 2017-05-26 05:34
the first android problem requires Lua skills, it's to require the menu which is desktop centric. Second it needs to have better controls

**Comment by matt8fr** [comment] 2017-05-26 08:42
I am only a player but what I can tell you is that, on our server, almost all android player uses unofficial client park: more visible on play-store
The controls are better.

**Comment by Wuzzy2** [comment] 2017-05-26 15:22
> Then the apps have to work for their money instead of just copying our code.

This is an incredibly stupid and selfish rationale there. As if “copying our code” is something inherently evil. Isn't this kind of thinking against the whole spirit of free software? You almost sound like a proprietary software vendor.

> rogue apps which makes money over us.

This is just envy. And “making money” is not even against the Minetest license nor against the spirit of free software. So what's your point?

Also, the problem is not Android, the problem is proprietary software. Also, I doubt dropping support for political reasons will change anything. The existing Android ports are not going to disappear overnight only because you dropped official support. Why should they?

> It would also reduce our workload.

Is the dev time required for the Android port really so high that it is a pain to maintain? (that's a honest question)



> Side note: you sure there will be 0.5 after 0.4.16? Where was that discussed? What is planned?

Umm, are you seriously asking for a _justification for a freaking version number_? xD

**Comment by nerzhul** [comment] 2017-05-26 16:00
don't mismatch who tell what in the previous comment, it's not the same guy :)

the point is we take many time to maintain minetest and i don't like guys who just rename minetest and add ads to make money, it's ridiculous and just selfish.

**Comment by paramat** [comment] 2017-05-26 16:25
I added an edit to my first post, est31 has explained how many of the advantages i stated will not happen, so i am now somewhat neutral about this. it may be better to keep it despite being not very good. Perhaps there are actions we can take to impprove the Android app situation too, like maing it more difficult to create a scam app full of adds.

By the way, 'LordFingle' expressed an interest in helping out with Android, and he has experience with the app.

**Comment by paramat** [comment] 2017-05-26 16:30
0.5.0 for next release is fairly agreed. We have CSM, a new light curve, smooth-shaded nodeboxes, and a new default mapgen plus a variety of alternative mapgens. 0.4.0 coincided with server side modding and mgv6 being the new default mapgen

**Comment by IhrFussel** [comment] 2017-05-27 05:45
@matt8fr Just because the majority accepts to install ad infested software with paywall for better controls doesn't mean that there should NOT be an ad-free version without paywall anymore.

**Comment by paramat** [comment] 2017-05-27 21:34
I contacted LordFingle and he may be able to help out, so hopefully we can manage to maintain the Android app.
Perhaps this thread can be closed in a while? I don't support dropping Android anymore.

**Comment by nerzhul** [comment] 2017-06-03 19:32
closing, it will be supported, C++11 needs a little bit support on build, but will be fixed later in the dev cycle

**Closed by nerzhul** 2017-06-03 19:32 UTC
Labels: Android, Possible close, Request / Suggestion
