### ISSUE TITLE
Bottom of the world weirdness

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2702] opened 2015-05-14 22:24 UTC
The bottom of the world (located at Y=-30912) behaves really weird.
It looks like an endless abyss and the background color constantly changes the color if you change your viewing angle.

Players can walk on it, but can't build on it.

But strangely, items, falling nodes can pass the bottom without problems.
This is problematic especially for falling nodes, because they don't seem to become normal nodes again. It also appears that falling nodes and items are stuck a couple of node lengths below the “bottom” and don't fall any further. I think the biggest problem here is that this stuff does not get deleted (or not deleted fast enough? Not sure).

What do you think about this? I have not really a good idea on how to change this.

**Comment by Pilcrow182** [comment] 2015-05-15 06:40
I had some issues with this myself, while doing some mod programming, but it doesn't just affect the bottom of the world; falling nodes fall through any unloaded chunk, if they are somehow updated. I think the culprit is "ignore" itself; ignore is not walkable or pointable.
Walkable, I think, controls weather a falling node can fall, and obviously a player can't build on something they can't point at...
This has been like this for a very long time though. Honestly, I think it may have been intentional?

**Comment by LeMagnesium** [comment] 2015-05-15 09:32
> Walkable, I think, controls weather a falling node can fall

You're perfectly right.
It would need to be fixed in the lua builtin. While checking for a non-walkable node, it should at the same time check whether or not the node below is ignore. The problem would however be that, let's say a sand node, would fall an be stopped at the borders of an unloaded chunck, but when it's loaded, it won't fall unless someone build near it.

**Comment by kilbith** [comment] 2015-05-15 11:52
I support the idea to cover the bottom hard limit with a layer of bedrock or such.

**Comment by C1ffisme** [comment] 2015-05-15 19:58
We could leave it like that, considering the bottom of the world is supposed to be broken-physics-like.

Okay, fine. Make a bedrock. Why not make it out of ```default:cloud``` since we don't have any use for them at the moment?

**Comment by LeMagnesium** [comment] 2015-05-15 22:20
@C1ffisme , clouds are really supposed to be in the sky, but knowing they have no actual use... Why not, but we could add another node called `default:bedrock` and place it at (*,-30129,*).

**Comment by Pilcrow182** [comment] 2015-05-16 02:45
Personally, I'd prefer if we just changed ignore to walkable (and possibly pointable?), rather than having a bedrock'd limit. That way, if something changes in the engine and it becomes possible to go below y=-30129, old worlds aren't hard-limited to the old border...

The one problem with that is, as LeMagnesium pointed out, sand nodes and such wouldn't fall after a chunk under it is loaded, unless an update is manually triggered. I wonder if it would be possible to make chunk-loading trigger updates to all the nodes next to the newly-loaded chunk's edges... That would probably make land generation too slow, though...

To be honest, I think falling nodes could do with some kind of update-triggering abm. That would fix the annoying sand overhangs caused by the cavegen, as well as make 'floating' sand fall on its own, without player intervention...

**Comment by Wuzzy2** [comment] 2015-05-16 04:43
Are you sure with the bedrock idea? Remember this is Minetest talk, not Minetest Game talk. I am not happy with the idea of hardcoding bedrock into the engine.

Also, there may be reasons why a subgame does not want any bedrock. SkyTest, for example. This subgame might (!) want to try a different way on how to handle the world bottom.

The real question is if you want to keep it “broken” so that subgames are supposed to “fix” it or if you want to fix it in the engine somehow.

**Comment by paramat** [comment] 2015-05-16 19:28
> the background color constantly changes the color if you change your viewing angle.

That's due to how sky darkness is varied according to what is in the player's field of vision. Not really a problem as the world base is supposed to be a strange place :)

> cover the bottom hard limit with a layer of bedrock or such.

Nope, void should be void and remain the empty space of "ignore", some singlenode mods (entirely floatland mods or space mods) will create a mostly air world where a layer of nodes at world base would not be suitable.

Some way of dealing with large numbers of stuck items may be good though, but then these may already be cleared out after a time limit and not be a problem, i don't know the item code so don't know.

**Comment by C1ffisme** [comment] 2015-05-16 21:33
@Wuzzy We could create a mg_flag called ```bedrocklayer``` which could be removed when we don't want it.

@Pilcrow182 You could use an ABM to remove it when the time comes...

**Comment by paramat** [comment] 2015-05-18 22:09
An optional base layer is more of a mod thing, easily and quickly added with the luavoxelmanip.

**Comment by Pilcrow182** [comment] 2015-05-19 02:02
Agreed, paramat, but something really does need to be done to prevent falling nodes from falling through ignore, since that affects unloaded chunks as well as the bottom of the world...

**Comment by tenplus1** [comment] 2015-05-19 20:12
A change in the latest daily has been added to stop dropped items from falling through unloaded chunks and I'm sure the falling.lua will receive the same attention soon enough...

**Comment by paramat** [comment] 2015-06-28 05:11
The biome api of mgv5/mgv7 has now been extended down to world base. Because it can replace stone with any node of choice you can use it to place bedrock at any depth by defining a bedrock biome between chosen ymin/ymax. Note that underground biomes are only calculated once per mapchunk column, at column top, so underground biomes have a vertical resolution of the thickness of a mapchunk, so you will only be able to create bedrock in 80 node thick layers.

**Comment by paramat** [comment] 2015-06-28 13:12
Looks like falling.lua still needs to be edited to stop falling nodes passing through ignore.

**Comment by Wuzzy2** [comment] 2015-06-28 21:56
About `falling.lua`:
It would be even more consistent to directly read from the setting `movement_gravity`.

There is a mod (`falling_extras`) which implements this:

https://forum.minetest.net/viewtopic.php?f=9&t=12244

What do you think about this mod? Would it be a feasible addtion to (core) Minetest?

**Comment by paramat** [comment] 2015-06-29 00:53
Thanks this makes me realise all hardcoded gravities should read from the custom gravity currenttly set, for moon mods etc.

**Comment by Wuzzy2** [comment] 2015-06-30 01:23
TenPlus1 claims (https://forum.minetest.net/viewtopic.php?f=5&t=12571#p183088) that the issue of entities falling through the bottom has been fixed for about 2 weeks (https://forum.minetest.net/viewtopic.php?f=5&t=12571#p183138). However, I can not reproduce this as of 29dda9f356042c403b3b7da1d717d32b45c9b6de (master branch).
What do other people say about this?
If it has actually been fixed already, then where is the commit responsible for this? o_O

**Comment by paramat** [comment] 2015-06-30 03:52
I just tested latest 0.4.12dev.
Dropped items fall through world base (y = -30912) and stop 16 nodes lower, they can only be retreived by flying down.
Falling nodes have varying behaviour. Mostly they will fall through world base and stop at 16 nodes lower, but as stay as entities that cannot be dug or retreived. Sometimes they will not drop if placed at world base. Also, if a falling node is placed above a stable node, then the stable node is removed, the falling node will fall and stop at world base and return to being a node.

TenPlus1's commit for item entites is here https://github.com/minetest/minetest/commit/be18bd6a8cafdc2c452da39dd8cc428d8dbf62e6
The relevant file is here https://github.com/minetest/minetest/blob/master/builtin/game/item_entity.lua

**Comment by paramat** [comment] 2015-06-30 04:13
Making ignore walkable is little better, dropped items drop to 1 node below world base and slide around, they can be chased and picked up again. Falling nodes will often fall to 1 node below world base, but remain as immortal entites that cannot be dug.

**Comment by VanessaE** [comment] 2015-06-30 05:58
I support the idea of a default mod to supply bedrock down there, but that aside, why exactly ARE falling node entities immortal and non-pointable?

**Comment by Wuzzy2** [comment] 2015-06-30 15:58
This thing starts to become WAY more weird now:
First TenPlus1 writes this:

> Hrm, ok this is strange... creating a fresh v6 world and dropping gravel or sand into the void has them drop all the way down, but... creating a new v7 world and doing the same has them stop above the void and return to being nodes... ?!?!?!?!
> 
> Turns out my builtin_item mod (https://github.com/tenplus1/builtin_item) only stopped dropped items from doing this, not falling objects... Why would this be mapgen specific ???

https://forum.minetest.net/viewtopic.php?f=5&t=12571&view=unread#p183191

I have tried to reproduce this in 91f95fd4df82645e23a9734795d11ec9b8e522f8.
In v6, the stuff reliably dropped down as predicted.

Then I tried this in mapgen v7, position (27, -30910, -8), seed 1146112778174042475. This is the place of a natural cave.
Here I noticed something strange:

*some* of the placed gravel is actually stopped by the border, but *some* of the gravel isn't. It looks like that gravel placed near the cave walls is more likely to be stopped then gravel dropped above the center of the hole. It is almost *as if* the cave would invisibly continue down there, with some invisible stones being there, and some invisible air. ;-)
Just try it for yourselves and place gravel all over the place in that cave (also at the cave top to make it drop).

Also, when placing gravel (in v7) at a place which I have dug free manually, gravel seems to be always stopped.

What the …?

**Comment by paramat** [comment] 2015-07-01 03:00
I should have mentioned my results above were in a mgv7 tunnel, i had similar varying behaviour.
The variation between mapgen may be because the tunnels of mgv5/v7 are generated differently to the tunnels of mgv6, they overgenerate downwards by only 1 node. Large caves of all mapgen and mgv6 tunnels overgenerate by a larger amount. We may be experiencing effects caused by the overgenerating cave interacting with the void, which may be why the cave seems to continue down into the void somehow.

For now i'll adjust the lower limit of gravel ore to a mapchunk or so higher.

**Comment by wilkgr76** [comment] 2015-10-12 22:57
The thing with the bedrock idea, is that unbreakable nodes can be destroyed by PilzAdam's TNT mod.

**Comment by Wuzzy2** [comment] 2015-10-16 20:21
Well, that's a problem with PilzAdam's mod, then. Ask PilzAdam to fix it.

**Comment by Wuzzy2** [comment] 2016-12-22 22:52
I have put some more reasearch into this issue using Minetest 0.4.14:

Apparently entities or objects in general (except players, normally) can pass through the world borders just fine.

This causes many unexpected things:

* You can drop items off the edge
* You can drop items 
* Minetest Game: Boats fall off the ocean (https://github.com/minetest/minetest_game/issues/1469)
* Probably all custom entities will also behave in weird/unexpected ways

Some interesting observations: When I use the flying carpet from the mod `flying_carpet`, I can fly through the edge, but I'm stopped at ca. Z=-30927 or Z=-30928 (not sure). Compare this to the actual edge at Z=-30912. The difference is, interestingly, 15 or 16.

If I use a boat from Minetest Game at the bottom to fall off, I fall down to Y=-30928. The difference is again 16. I can reproduce the dropped item observation from paramat.
(How to fall off? Simple: Place some water first, then put it on the water and ride with the boat into the abyss.)

So it looks like we have a clasic off-by-one bug here. :-)

Another interesting observation: Items fall off the bottom in when the air at the bottom came from the cave generator. If you have dug the hole above bottom yourselves, neither the boat nor items will fall through.

I hope this helps fixing some entity-related problems. :-)

**Comment by paramat** [comment] 2017-05-31 03:45
Partially fixed by #5856

**Closed** 2017-06-03 17:57 UTC
Labels: @ Server / Client / Env., Bug

**Comment by paramat** [comment] 2017-06-03 18:12
#5889 merged.

**Comment by Wuzzy2** [comment] 2017-06-03 23:38
Things still left unfixed:

> the background color constantly changes the color if you change your viewing angle.

> Players can walk on it, but can't build on it.

Not sure if the latter is intended.

**Comment by HybridDog** [comment] 2017-06-04 09:45
> Not sure if the latter is intended.

No, you don't need to waste space by explicitly adding code to make that place convenient.

**Comment by paramat** [comment] 2017-06-04 15:39
> Things still left unfixed:
    the background color constantly changes the color if you change your viewing angle.
    Players can walk on it, but can't build on it.

The first is the auto darkness detection code altering the skybox, the same issue as sky going dark when near a cliff or mountain, there is an issue for trying to tune and improve that already.

The second is expected behaviour, it is 'ignore' so players can't pass through it, but also can't build against it. A non-issue.
The world edge being weird is expected and interesting.
