### ISSUE TITLE
player:get_look_yaw and player:set_look_yaw not consistent.

### ISSUE THREAD

**Issue by beyondlimits** [minetest/minetest#2879] opened 2015-07-04 13:06 UTC
`player:get_look_yaw()` produces different value than was used to `player:set_look_yaw()`.

Proof: doing `player:set_look_yaw(player:get_look_yaw())` causes player to rotate left 90 degrees instead of looking at the same point.

**Comment by TeTpaAka** [comment] 2015-07-04 15:03
Duplicate of #2658

**Comment by est31** [comment] 2015-07-10 17:41
@TeTpaAka is right, dupe of #2658.

**Closed by est31** 2015-07-10 17:42 UTC
