### ISSUE TITLE
Trusted mods: Show formspec as environment is requested

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11129] opened 2021-03-27 13:51 UTC
## Problem

Currently, trusted mods require to be added to certain lists (`secure.trusted_mods/secure.trusted_http_mods`). This is not at all user-friendly and hinders the usage of trusted mods by inexperienced users.

## Solutions

As a mod loads and *requests* an insecure environment / HTTP API table, display a dialog to the user whether they want to add said trusted mods / trusted HTTP mods.

## Alternatives

Improve the settings dialog. In terms of UX still inferior however.

**Comment by sfan5** [comment] 2021-03-27 14:50
Not sure if dialog is such a good idea. There could just be a checkbox in the Content tab (+ dialog to make sure the user understands) instead.

**Comment by SmallJoker** [comment] 2021-03-27 17:50
Low priority at best. There are only a few mods that actually require either of those, and those that come to my mind (irc, skinsdb) are only used on servers which would not have a GUI anyway.

**Comment by appgurueu** [comment] 2021-03-27 17:55
> There are only a few mods that actually require either of those

Because mods have preferred to work around this, for example by using files for storage instead of a proper DB, in order to keep things simple for their users, leading to more work for the mod devs and issues with persistence and performance.

**Comment by SmallJoker** [comment] 2021-03-27 18:11
> for example by using files for storage instead of a proper DB

This only indicates that Minetest needs a better storage method which can be accessed without shooting holes into the mod security (i.e. mod exceptions). In that case it's a duplicate of #10371.

**Comment by appgurueu** [comment] 2021-03-27 18:46
Another example: [Loria](https://content.minetest.net/packages/siegment/loria/):

> WARNING: Electricity mod requires access to insecure functions in order to work. Please add the electricity mod to your secure.trusted_mods. Insecure functions provide native (fast) complex numbers and arrays, which are necessary for MNA solver used in electricity mod.

It's not only about database access. It's about plenty of libraries, plenty of things which are a pain to find / reimplement in plain Lua, some of which simply require a lower level language for performance. `os.execute` is also currently the only way to achieve multiprocessing. Trusting mods should be made easier for users, without leading them to compromise the security of their systems.

**Comment by red-001** [comment] 2021-03-27 19:40
Seems like something that would just encourage users to click through the warning.

**Closed** 2021-04-18 14:20 UTC
Labels: Feature request, Won't add

**Comment by sorcerykid** [comment] 2021-04-19 14:42
I can sort of see some merits in having this. It would make the process of installation more streamlined for such mods. But like SmallJoker, pointed out, a lot of servers don't have GUI. So would need to be some other solution that doesn't rely on user-interaction at server-startup.
