### ISSUE TITLE
Player is glowing on OpenGL 3

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#15140] opened 2024-09-09 16:20 UTC
Switch video driver to `opengl3`.

Play Minetest Game, view yourself in third person at night: You're glowing.

Now switch drivers to `opengl` and restart, you're not glowing anymore.

#### Additional context

Bisected 5.9.0 to latest master, it was not introduced in that range.

This kind of issue typically happens when shader materials (which are hackily stored in the material type enum) aren't used properly.

<sub>The temptation to name this issue "I'm glowing" was hard to resist.</sub>

**Comment by sfan5** [comment] 2024-09-09 16:32
I bet this is a duplicate but I can't find the original issue.

**Comment by appgurueu** [comment] 2024-09-09 17:10
> Does shaders on/off make a difference?

Yes, the issue only appears with shaders disabled.

Arguably we might want to consider requiring shaders to be enabled for the modern OGL 3 pipeline.

**Comment by grorp** [comment] 2024-09-11 16:08
duplicate of #13511

**Closed** 2024-09-11 16:08 UTC
Labels: Bug, Low priority, @ Client rendering
