### ISSUE TITLE
water_life crocodiles appear neon on MT 5.8.0 using Arch

### ISSUE THREAD

**Issue by rewired-X** [minetest/minetest#14174] opened 2023-12-27 23:50 UTC
### Minetest version

```true
Minetest 5.8.0 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1702233742
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Operating system and version

Arch Linux

### CPU model
Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz, 3101 Mhz, 4 Core(s), 4 Logical Processor(s)

### GPU model

AMD Radeon RX550/550 Series

### OpenGL version

4.6

### Summary

Recently, when I updated MT on Arch Linux to 5.8.0 (including minetest-common, that was updated as part of a full system upgrade), water_life crocodiles now appear neon at night. Joining the same server using 5.8.0 on Windows, however, does not show this discrepancy. I suspect that MT is having issues, so I come to here.
Only graphics setting that is different is I have trilinear filtering, which does not affect crocs in are they neon or not.

### Steps to reproduce
Edit: I guess I better add one more step.
Get onto Linux (Arch preferably)
Boot up a singleplayer world w/ water_life installed (MT 5.8.0)
Wait until night (I cannot get crocs to become neon during daytime)
See if crocs are neon
![Screenshot_20231221_184303](https://github.com/minetest/minetest/assets/150751430/9adc5ed0-8211-43fd-80cb-2662b44e79f1)

**Comment by Desour** [comment] 2024-01-03 18:32
Can't reproduce.
* Installed this `water_life`: https://github.com/berengma/water_life (Found via Krock's mod search, wasn't on contentdb, and also no longer on forum.)
* Created a mtg world.
* Spawned croc with: `/spawnentity water_life:croc`
* Made night with: `/time 0`
* Croc wasn't bright.
* Tried again with empty settings. Same result.

**Comment by rewired-X** [comment] 2024-01-04 00:02
After reinstalling minetest twice, this seems to have fixed itself. Maybe something didn't install right the first time?
Anyways, will close this. Thanks for at least testing this though!
![Screenshot_20240103_190121](https://github.com/minetest/minetest/assets/150751430/f8fec77c-b0c4-4339-9167-47ab495e28f3)

**Comment by fluxionary** [comment] 2024-01-04 01:35
my guess is that if re-installation fixed it, the problem might have been that the shaders were somehow the wrong version. i think i had something similar happen to me a few years ago, when sharing the shader folder between two different releases. maybe `minetest --version` should emit some sort of checksum of the active shader code?

**Comment by fluxionary** [comment] 2024-01-13 04:59
i can't re-open this, but it might need to be re-opened. i can replicate this on my machine just by disabling shaders, as can several other players on your-land. i'm unsure whether this is an engine issue or a water_life issue though.

**Comment by SmallJoker** [comment] 2024-01-13 07:39
@fluxionary Please collect the following information from the affected users:

 * Operating System
 * Graphics card used
 * Driver version (optional)
 * Reported OpenGL version (optional)

Without that, it is difficult to narrow down where the issue comes from, especially when no developer can reproduce it.

**Comment by fluxionary** [comment] 2024-01-13 22:24
we figured out this actually *was* a water_life issue. the client got the following warning:

```
WARNING[Main]: GenericCAO::addToScene(): Model water_life_crocodile.b3d loaded with 9 mesh buffers but only 1 texture(s) specified, this is deprecated.
```

once that was fixed in water_life, the crocs appear normal.

**Comment by fluxionary** [comment] 2024-01-13 22:30
in case it's judged to still be relevant:

>     * Minetest version

```
minetest --version
Minetest 5.8.0 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1702233742
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

>     * Operating System

```
Linux nail 6.6.8-2-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Dec 21 16:21:45 UTC 2023 x86_64 GNU/Linux
```

>     * Graphics card used

```
01:00.0 VGA compatible controller: NVIDIA Corporation TU117GLM [Quadro T2000 Mobile / Max-Q] (rev a1)
```

>     * Driver version (optional)

```
Name            : linux515-nvidia
Version         : 545.29.06-7
Description     : NVIDIA drivers for linux
```

>     * Reported OpenGL version (optional)

```
OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.1.9-manjaro1.1
```

**Closed** 2024-01-14 11:25 UTC
Labels: Not a bug, @ Client rendering
