### ISSUE TITLE
CSM: Ability to inject from server-side mod

### ISSUE THREAD

**Issue by jogag** [minetest/minetest#3440] opened 2015-12-09 12:57 UTC
Mods should be able to work both server-side and client-side.
Mobs, entities, mesecons, HUDs and other laggy things should be processed by a client if a player is near them and then sent to server just if needed (e.g. there's another player near that).
The client side feature could be used by adding a `client` folder inside mods with the scripts that should be sent to clients like media files.
Then servers can trigger functions in client-side files, e.g:

``` lua
-- Server (init.lua)
function feedback(player,param) -- player param always passed
  print("Received from "..player..": "..dump(param))
end
local arg = "example" -- parameter to send
minetest.call_client_function_all("something", arg) -- to all players
minetest.call_client_function_player("jogag", "something", arg) -- to one player
minetest.call_client_function_player({"jogag","someone"}, "something", arg) -- to some players
-- Clients (client/init.lua)
function something(param)
  minetest.show_chat_message("From server: "..dump(param)) -- implementing some client API?
  minetest.call_server_function("feedback",param)
end
```

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=28979384)](https://www.bountysource.com/issues/28979384-client-side-lua-scripting?utm_source=28979384&utm_medium=shield&utm_campaign=ISSUE_BADGE)

- [x] Client side Lua environment
- [ ] Server mods can define Lua scripts to run on the client
- [ ] Custom client side prediction:
    - [ ] players
    - [ ] entities
- [ ] Better GUI
- [ ] Better HUD
- [ ] Keybinding

**Comment by paramat** [comment] 2015-12-09 16:56
Celeron55 might be working on this soon.

**Comment by ShadowNinja** [comment] 2015-12-09 23:03
This has already been on the TODO list for a long time and is mentioned in #2370.
kwoleker has touched on it and celeron55 has considered working on it.
I don't think this issue is useful right now.

**Comment by neoascetic** [comment] 2016-03-12 11:03
This issue is useful because of:
- I want to put a bounty on it through Bountysource
- it may be place for discussion for this particular feature

Personally, I think that client-side scripting will be a huge improvement for Minetest because it will improve mods quality, responsiveness for clients and performance of servers (by moving non-critical stuff, such as environment effects) to client side.

**Comment by neoascetic** [comment] 2016-03-14 13:19
Let's start with small: [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=28979384)](https://www.bountysource.com/issues/28979384-client-side-lua-scripting?utm_source=28979384&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by duckbrain** [comment] 2016-06-22 16:10
I'm pretty interested in this feature. I see it as one of the main things that could make Minetest seem much more responsive by allowing mods to do their own client side prediction. I may try to tackle this issue, but I really don't know what I'm getting myself into here. :smile: 

I am envisioning a duplicate of the mod API that would run on the client side and update the client's rendering of game state. API calls would immediately update the client and then the server could resolve differences later on network communication. This is likely to cause a rubberbanding effect, so the client is going to need to track its state if it is not already do so. I think storing these files in a `client` directory is fine. The server-side mod could still access these files, so they could share Lua. 

As I understand it, this will require the following:

- [ ] Create a duplicate GameScripting (ClientScripting) class for the client and create a different implementation for each of the API calls to immediately update the client, API calls that don't make sense on the client could simply be no-ops
- [ ] Create a mechanism to have the client scripts be sent across the network stream as the game connection initializes. This should also probably be cached as well.
- [ ] Start the `client/init.php` file in a limited Lua sandbox.
- [ ] Create additional APIs on the client and server to implement the fantastical other features desired.

I'm using the [Wiki page on the subject](http://dev.minetest.net/Client_scripting_plans) as a reference as well. This seems like a huge undertaking and any help/advice would be appreciated.

**Comment by neoascetic** [comment] 2016-07-02 09:38
To make it round, I've put additional $15 on bounty. C'mon, someone, implement this feature!

**Comment by duckbrain** [comment] 2016-07-02 14:25
The issue I'm running into right now is getting the code transferred to the client. There is a media transfer that was hoping could be used to transfer the lua files, but unless I'm missing something, I can't see how the client can tell what mod they came from when using this. This is needed if you are going to have more than one mod with client-side scripting. The benefit of using what is already there for media, is that the clients can ignore files they don't understand, and servers that don't send the media won't affect clients that might use it (compatibility with older clients/servers).

The other solution, is adding something new to the stream on init. I'm still needing to get my bearings in this code base to be able to do that effectively and safely.

**Comment by raymoo** [comment] 2016-08-01 18:53
@duckbrain In the wiki article, it suggests having the mod name be sent with the events that get sent between the server and client. So there is no need to keep track of which mod a client script came from, because if it needs to communicate with its mod, presumably it includes its modname in the script and uses it in minetest.register_event and minetest.raise_event.

**Comment by rubenwardy** [comment] 2016-08-01 20:00
This is a feature that would make many more things possible. Client side modding should be designed for client side prediction and user interface.

If it help, I've put $15 on it

**Comment by duckbrain** [comment] 2016-08-02 20:39
@raymoo If the client can't tell which mod it came from, it won't be able to handle includes inside the scripts, you will have one file per mod. This would be simpler for sure, but will make complex client-side mods more difficult to manage. 

This would also mean that it is impossible to set up a duplicate API allowing more code reuse by moving the files into the client directory and including them. The benefit I see to this, is that _much_ of the client-side prediction could happen if the client and server can follow the same paths of logic. Theoretically the client would get the same result as the server, and if there is a conflict, the server would override. This of course would require an entirely duplicated API on the client side to process the same way.

The messaging on the other hand would allow mod developers to implement a client-side prediction themselves, but may require more work on the modders' side, but would be more flexible.

@rubenwardy I can't say I've given a terrible amount of thought on the user interface parts, but that's something mod developers could address too if the API is there, I can see a real benefit there as well. :smile:

**Comment by raymoo** [comment] 2016-08-02 21:57
By includes do you mean things like dofile?

**Comment by rubenwardy** [comment] 2016-08-02 22:06
client-side scripts won't be allowed to access the real filesystem. Instead I imagine they'd use a virtual filesystem to load other scripts from and save temporary data

**Comment by raymoo** [comment] 2016-08-02 22:09
@rubenwardy Ok, I see.

**Comment by raymoo** [comment] 2016-09-11 20:31
Has there been any progress since last time?

**Comment by duckbrain** [comment] 2016-09-12 14:02
Progress is slow and not very steady, but it's getting closer.

The scripts are sent with the other media, and stored in memory. It will then run each of the init.php files for each client mod. The only thing they can do right now is print to the client's console and include lua from their filesystem (bad). I was last working on getting the security sandbox to load files from the cache when running on the Client.

You can also see my work [on my fork](https://github.com/duckbrain/minetest/tree/feature/client-mods). My commit history is a little messy, I will be definitely squashing commits before submitting a pull request.

**Comment by sofar** [comment] 2016-09-12 22:57
@duckbrain You've mentioned `init.php` twice now, do you mean `init.lua` ?

**Comment by duckbrain** [comment] 2016-09-13 00:35
@sofar Haha, yes. Too much of my real-life job. I've fixed that. I don't think we need a PHP engine in Minetest.

**Comment by nerzhul** [comment] 2017-01-21 20:02
#5088 is now the official PR for doing this. @duckbrain is huge, but there is some wrong things in it. and many code duplication.

This PR used an official minetest branch i will try to keep close to master branch, but which needs rebase and squash sometimes.
Everybody is free to open a PR against client_side_modding branch to help us to create this API

**Comment by neoascetic** [comment] 2017-01-25 10:05
Since there is some progress on the issue I've put additional $10 to the bounty and there is whole ONE HUNDRED BUCKS on the issue! I hope someone will get them!

**Comment by neoascetic** [comment] 2017-01-25 10:41
Hey @nerzhul why did you close the story? This isn't implemented yet and we want bounties to be payed-out (see [this comment](https://github.com/minetest/minetest/issues/3440#issuecomment-195716145)).

**Comment by rubenwardy** [comment] 2017-01-25 11:25
It's not been merged yet

**Comment by nerzhul** [comment] 2017-01-25 11:37
@neoascetic this PR will not be merged, as #5088 supersede it. don't keep it opened.

**Comment by neoascetic** [comment] 2017-01-25 11:38
This isn't PR, this is an issue

**Comment by nerzhul** [comment] 2017-01-25 11:39
oh sorry, i mismatched with an existing PR

**Comment by PureTryOut** [comment] 2017-01-30 15:41
I see keybinding is in this issue. I know it's controversial, mostly regarding mobile support, but can this please be added to #5088 as well? It will allow mods to add a huge range of exciting, potential, features.

**Comment by nerzhul** [comment] 2017-01-30 15:44
@PureTryOut please report your needs on 5088 not here

**Comment by PureTryOut** [comment] 2017-03-27 10:57
Seeing client-side scripting is now merged (#5088), I guess this issue can be closed?

**Comment by rubenwardy** [comment] 2017-03-27 11:10
We still need to let subgames specify mods, as the point of this issue is lag reduction

**Comment by nerzhul** [comment] 2017-03-27 12:13
Exact, i think we can close this issue, as all remaining points are discussed in the roadmap 2 PR

**Comment by neoascetic** [comment] 2017-03-27 16:32
This **must not** be closed until there is client-server mods communication. There is bounty for the issue and I don't money to be paid out only when there is ability to write mods distributed between server and client with ability to communicate.

**Comment by nerzhul** [comment] 2017-03-27 17:01
Please reaffect bounty on another issue or pr then.

**Comment by neoascetic** [comment] 2017-03-27 17:33
Well, this issue ask for client-server communication in its first message,
so until it is implemented I don't think it is OK to close it either.
Furthermore, there is no way to move the bounty to other issue AFAIK
(because money belong to several peoples).

On Mar 27, 2017 20:02, "Loïc Blot" <notifications@github.com> wrote:

Please reaffect bounty on another issue or pr then.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/minetest/minetest/issues/3440#issuecomment-289516825>,
or mute the thread

**Comment by PureTryOut** [comment] 2017-03-28 06:09
I guess I misunderstood the original question then. It does make sense to have some sort of communication between client and server mods, and it's probably preferable to only have parts of a mod that need to be client-side, actually be client-side and the rest still server-side. I guess right now a mod is either entirely client-side or entirely server-side?

My mistake, apologies.

**Comment by nerzhul** [comment] 2017-03-28 06:23
at first it's not necessary to have client <-> server communication as we don't have finished yet to implement client side interesting features and touch the limits of pure CSM. Also we will have mod channel between clients which be part of roadmap 3 i think, permitting better social integration between mods without any server processing (except message routing)

**Comment by neoascetic** [comment] 2017-03-28 09:28
Okay, @nerzhul, I don't know... could you claim a bounty at [Bountysource](https://www.bountysource.com/issues/28979384-client-side-lua-scripting) then? Because we cannot re-attach it to a different issue.

**Comment by nerzhul** [comment] 2017-03-28 09:35
@neoascetic i like the bounty ideas, but for CSM do you think it should be given to persons who will develop client <-> or persons who have inited, maintained and added many lua calls to permit CSM to works before making mod sended to server reality ? There is a hard link between them, and i think this bounty should be redistributed or given to minetest hosters to pay their servers

**Comment by neoascetic** [comment] 2017-03-28 09:58
So @gregorycu, @eidy, @rubenwardy and, of course, @celeron55, what do you think? I guess Bountysource should be disabled for the project then because we could have troubles like that in the future.

**Comment by eidy** [comment] 2017-03-29 00:13
By "project", is @neoascetic refering to just CSM, or all of MT?  I want to encourage people to develop MT.  However I do understand the difficulty when multiple people contribute toward the change.  (which is something we also want to encourage).  

I think that the bounty should be offered to be split equally amongst ALL who contributed the change, no matter how small.  Each person should then be given the option to decline their share.

Hopefully most will decline, leaving the bounty to those who worked hardest and need it most.  La la la.

Is this possible?

**Comment by neoascetic** [comment] 2017-03-29 05:18
I am not sure if it is possible with Bountysource, probably not.

**Comment by rubenwardy** [comment] 2017-03-29 07:38
A mediator could always do this

**Comment by neoascetic** [comment] 2017-04-29 14:39
@nerzhul could you please claim the bounty on bountrysource?

**Comment by rubenwardy** [comment] 2017-04-29 14:45
We still don't have proper server mod sending yet, which is what the issue asked for.

This probably should have been left open

**Comment by neoascetic** [comment] 2017-04-29 14:47
There is a bunch of work to have this implemented, and a lot of PRs, so I guess bounty either should go to first man who started the shit (@nerzhul) or no one at all.

**Comment by nerzhul** [comment] 2017-04-29 15:02
@neoascetic how can that be claimed ? i added to aborted not because bounty, but it's not the main issue.

**Comment by nerzhul** [comment] 2017-04-29 15:04
also the real goal of this pr is not reached, but we have the first part, if for your it's okay to claim the bounty okay, i can take it and redistribute between red-001 which does many PR, celeron, sfan5 for infrastructure and me for the project startup + management

**Comment by nerzhul** [comment] 2017-04-29 15:10
Lua scripting client side is now a reality, and more than expected !

**Closed** 2017-04-29 15:10 UTC
Labels: Bounty, Feature request, Non-trivial

**Comment by rubenwardy** [comment] 2017-04-29 15:15
:tada:

**Comment by Kimapr** [comment] 2020-06-17 15:15
Why is this closed and moved to **Done**? We don't have server sent client side modding, which is described in the title
> CSM: Ability to inject from server-side mod

**Comment by rubenwardy** [comment] 2020-06-17 16:45
Yeah, I regret awarding the bounty and letting this be closed
