### ISSUE TITLE
Optional dependencies being overridden/turned into hard dependencies

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#8601] opened 2019-06-15 13:37 UTC
This issue is very similar to #3136
(very nearly a duplicate, in fact, but that one's old, and long since closed)

Using 5.0.1-release, singleplayer

Consider this example dependency tree:

Mod A hard depends on mod C.  
B hard depends on D, optional-depends on F
C depends on nothing
D optional-depends on E
E hard depends on F

Now disable mod F.  Let's say you're doing this to test a feature in B that changes behavior depending on the presence of F.

In this case, E of course doesn't load, but D won't load either, because now the engine treats it as if it *hard-depends* on E, contrary to its `depends.txt`/`mod.conf`.  This causes B not to load as well, since it needs D.

So while one expects A, B, C, and D to load in this example, only A and C get loaded, thus preventing the modder from doing the test they wanted (to check B's behavior without F).

OK, now try it in a real setup:

* Download Dreambuilder
* Create a new world,
* Enable the whole modpack in that world's config
* Now disable just `mesecons` (the one base mod from that project), leaving everything else enabled
* Start the world.
* Many mods that should have loaded won't, for example `homedecor_lighting` (it has a number of dependencies, but mesecons is strictly optional)

Now, go back into the world config and disable all of the `mesecons*` mods (there are about 30, all grouped together), then save and start the world.  You'll find that many of the items that should have loaded the first time work now, even though you were turning things *off* in the config.

It's as though hard dependencies propagate upwards through the dependency tree once a mod can't be satisfied, overriding cases where mods are explicitly set to be optional.

**Comment by SmallJoker** [comment] 2019-06-15 14:25
Ignoring mod A and B, since they are independent.
```
+---------------+     +---------------+
|       B       |     |       B       |
+---+-------+---+     +---+-------+---+
    |       |             |       |
    |       V             |       V
    | +-------+           | +-------+
    | |   D   |           | |   D   |
    | +-----+-+           | +-----+-+
    |       |             |       |
    |      ?V?            |      ?V?
    | +-------+           | +xxxxxxx+
    | |   E   |           | x   E   x
    | +-----+-+           | +xxxxxxx+
    |       |             |       |
   ?V?      V            ?V?      V
+---+-----------+     +xxxxxxxxxxxxxxx+
|       F       |     x       F       x
+---------------+     +xxxxxxxxxxxxxxx+
```
There are no recursive elements, so in terms of logic the mod loading must be capable of resolving the priorities there correctly.

**Comment by VanessaE** [comment] 2019-06-15 15:38
If I read that graph correctly, the right side is what I'd have expected, but not what happens in practice.

**Comment by SmallJoker** [comment] 2019-12-07 15:36
@VanessaE Do you know whether #8603 would fix this particular issue? Sadly I don't remember whether one of our conversation months ago were about this problem.

I can re-open the PR if you'd like to have this issue fixed. Apparently it's a very rare edge cases because there aren't any other reports.

**Comment by VanessaE** [comment] 2019-12-07 15:54
I'm afraid I don't remember the conversatio anymore.

**Comment by VanessaE** [comment] 2019-12-07 15:56
I really don't know if that PR would do it, and I don't remember the content of any relevant conversations either. :confused:

**Comment by VanessaE** [comment] 2020-08-18 21:37
Still a problem at commit cfaef5b1cfc8ec7463a2e8aec420bfc3a434f9c1.

**Comment by SmallJoker** [comment] 2020-08-19 16:41
Would you please be so nice and try to construct a modpack containing dummy/empty mods that cause this issue?
I saw the instructions in the first post, but I'm not sure whether dependencies of any of those mods already changed. Having an independent test setup would be very helpful to have.

**Comment by VanessaE** [comment] 2020-08-19 16:52
@SmallJoker download Dreambuilder, then as @rubenwardy suggested on the homedecor repo, create a new mod (I suppose the name doesn't matter) with an empty `init.lua`, and a `mod.conf` with the following single line:

```
depends = building_blocks, computer, fake_fire, homedecor_3d_extras, homedecor_bathroom, homedecor_bedroom, homedecor_books, homedecor_climate_control, homedecor_clocks, homedecor_cobweb, homedecor_common, homedecor_doors_and_gates, homedecor_electrical, homedecor_electronics, homedecor_exterior, homedecor_fences, homedecor_foyer, homedecor_furniture, homedecor_furniture_medieval, homedecor_gastronomy, homedecor_kitchen, homedecor_laundry, homedecor_lighting, homedecor_misc, homedecor_office, homedecor_pictures_and_paintings, homedecor_roofing, homedecor_seating, homedecor_tables, homedecor_trash_cans, homedecor_wardrobe, homedecor_windows_and_treatments, inbox, itemframes, lavalamp, plasmascreen
```

That way you get a real world example, and it's not like DB is all that big (if you don't already have it :smile: ).

**Comment by SmallJoker** [comment] 2020-08-19 17:34
Works for me. Created a "depends_on_all" mod using your line above. Works. List of loaded mods reported by the (singleplayer) server:
```
basic_materials, beds, binoculars, boats, bones, bucket, building_blocks, butterflies, carts, computer, creative, default, depends_on_all, doors, dungeon_loot, dye, env_sounds, fake_fire, farming, fire, fireflies, flowers, game_commands, give_initial_stuff, homedecor_3d_extras, homedecor_bathroom, homedecor_bedroom, homedecor_books, homedecor_climate_control, homedecor_clocks, homedecor_cobweb, homedecor_common, homedecor_doors_and_gates, homedecor_electrical, homedecor_electronics, homedecor_exterior, homedecor_fences, homedecor_foyer, homedecor_furniture, homedecor_furniture_medieval, homedecor_gastronomy, homedecor_kitchen, homedecor_laundry, homedecor_lighting, homedecor_misc, homedecor_office, homedecor_pictures_and_paintings, homedecor_roofing, homedecor_seating, homedecor_tables, homedecor_trash_cans, homedecor_wardrobe, homedecor_windows_and_treatments, inbox, itemframes, lavalamp, map, plasmascreen, player_api, screwdriver, sethome, sfinv, spawn, stairs, tnt, unifieddyes, vessels, walls, weather, wool, xpanes
```

**Comment by VanessaE** [comment] 2020-08-19 17:43
That's strange, when I tried it with cfaef5b, it blew up.

**Comment by VanessaE** [comment] 2020-08-19 17:45
That's strange, when I tried it with cfaef5b, it blew up.

It might be be because some mod in the tree still opt-depends on the old `homedecor`, which is what I named the test mod.

**Comment by IceDragon200** [comment] 2020-10-12 11:59
Following rubenwardy's suggestion and posting my description of the problem here.

Snippet from my logs:

```
ERROR[Main]: mod "yatm_autotest" has unsatisfied dependencies:  "yatm_mesecon_locks" "yatm_mesecon_hubs" "yatm_item_teleporters" "yatm_item_ducts" "yatm_fluid_pipe_valves" "
yatm_spacetime" "yatm_mesecon_buttons"
ERROR[Main]: mod "yatm_codex_entries" has unsatisfied dependencies:  "yatm_fluid_teleporters" "yatm_fluid_pipe_valves" "yatm_item_teleporters" "yatm_item_ducts"
ERROR[Main]: mod "yatm_data_to_mesecon" has unsatisfied dependencies:  "mesecons"
ERROR[Main]: mod "yatm_fluid_pipe_valves" has unsatisfied dependencies:  "mesecons"
ERROR[Main]: mod "yatm_fluid_teleporters" has unsatisfied dependencies:  "yatm_spacetime"
ERROR[Main]: mod "yatm_item_ducts" has unsatisfied dependencies:  "yatm_spacetime"
ERROR[Main]: mod "yatm_item_teleporters" has unsatisfied dependencies:  "yatm_spacetime"
ERROR[Main]: mod "yatm_mesecon_buttons" has unsatisfied dependencies:  "mesecons"
ERROR[Main]: mod "yatm_mesecon_card_readers" has unsatisfied dependencies:  "mesecons"
ERROR[Main]: mod "yatm_mesecon_hubs" has unsatisfied dependencies:  "mesecons"
ERROR[Main]: mod "yatm_mesecon_locks" has unsatisfied dependencies:  "mesecons"
ERROR[Main]: mod "yatm_mesecon_sequencer" has unsatisfied dependencies:  "mesecons"
ERROR[Main]: mod "yatm_spacetime" has unsatisfied dependencies:  "mesecons"
```

As shown in the logs: some mods have unsatisfied dependencies on mesecons causing a cascading failure, that much is expected as the mods are currently be reworked to remove those hard dependencies.

However, in the case of [yatm_autotest](https://github.com/IceDragon200/mt-yatm/blob/master/yatm_autotest/mod.conf#L3) and [yatm_codex_entries](https://github.com/IceDragon200/mt-yatm/blob/master/yatm_codex_entries/mod.conf#L4), all of the specified dependencies are _optional_.

Here is the mod.conf for reference (in case the links change slightly):

```
name = yatm_codex_entries
description = Provides entries and demos for YATM mods
depends = yatm_core,yatm_codex
optional_depends = yatm_armoury,yatm_armoury_icbm,yatm_data_logic,yatm_data_network,yatm_data_noteblock,yatm_drones,yatm_dscs,yatm_energy_storage,yatm_energy_storage_array,yatm_fluid_pipe_valves,yatm_fluid_pipes,yatm_fluid_teleporters,yatm_foundry,yatm_frames,yatm_item_ducts,yatm_item_teleporters,yatm_mail
```

The expected behaviour is any 'optional' dependency, even if it fails it's own dependencies should not affect another mod that has it optional. 

##### Steps to reproduce

I wouldn't suggest using my mods as a test, there is a lot of undocumented setup required (foundation stuff).

I've tried it with a minimal test case:

__Base mod__

```
name = mod_base
```

__First optional mod with a hard dependency on mod_missing__

```
name = mod_a
depends = mod_base,mod_missing
```

__Second optional mod__

```
name = mod_b
depends = mod_base
```

__Last or the top-level mod that optionally depends on mod_a and mod_b__

```
name = mod_top
depends = mod_base
optional_depends = mod_a,mod_b
```

Expected behaviour:

* `mod_base` loads
* `mod_a` fails to load with unsatisfied dependencies 'mod_missing'
* `mod_b` loads
* `mod_top` loads (with `mod_b` and without `mod_a`)

Actual behaviour:

* `mod_base` loads
* `mod_a` fails to load
* `mod_b` loads
* `mod_top` fails to load with unsatisfied dependencies `mod_a`

**Comment by SmallJoker** [comment] 2021-07-10 08:52
There's one more interesting case: ([reported here](https://github.com/minetest-mods/unified_inventory/issues/177))

 * Mod A soft-depends on mod B
 * Mod B hard-depends on another mod which is not enabled
 * Mod A fails to load because mod B failed to load (turned into a hard-dependency)

How to test: MineClone2 game + unified_inventory

#8603 passes this test (after adding all hard-dependencies), but not #10486

**Comment by IceDragon200** [comment] 2021-07-10 16:06
@SmallJoker I've answered your comment in my PR, I would like your input on it

**Comment by appgurueu** [comment] 2022-01-12 15:00
> This issue is very similar to #3136 (very nearly a duplicate, in fact, but that one's old, and long since closed)
> 
> Using 5.0.1-release, singleplayer
> 
> Consider this example dependency tree:
> 
> Mod A hard depends on mod C. B hard depends on D, optional-depends on F C depends on nothing D optional-depends on E E hard depends on F
> 
> Now disable mod F. Let's say you're doing this to test a feature in B that changes behavior depending on the presence of F.
> 
> In this case, E of course doesn't load, but D won't load either, because now the engine treats it as if it _hard-depends_ on E, contrary to its `depends.txt`/`mod.conf`. This causes B not to load as well, since it needs D.

This should be solved by forcing the user to disable D as well if F is to be disabled by throwing a "missing dependency" error.

**Comment by appgurueu** [comment] 2022-01-12 15:56
Not a bug according to the docs:

> * `optional_depends`: A comma separated list of optional dependencies. Like a dependency, but no error if the mod doesn't exist.

If "existence" is understood as "installed" (which includes "installed but disabled"), the dependency is treated like a hard dependency. This is documented and expected behavior apparently. It might still be worth changing, but technically it renders this issue a feature request.

**Comment by Df458** [comment] 2022-01-12 22:21
> If "existence" is understood as "installed" (which includes "installed but disabled"), the dependency is treated like a hard dependency. This is documented and expected behavior apparently. It might still be worth changing, but technically it renders this issue a feature request.

Forgive me if I've misinterpreted your comment, but you seem to be implying that the "correct behavior" is that simply downloading a mod converts it into a hard dependency. That _is_ one way you could technically read the sentence in lua_api.txt, but that's not the current behavior (and I suspect it never was) and it also makes absolutely no sense. If that's actually what you're suggesting, I wholeheartedly disagree.

Personally, I think enabled optional deps failing to load due to their hard deps is acceptable. That's a sensible behavior that a normal user would probably expect. But if installing an optional dep was all it took to create a hard dep, it would have a huge negative impact on UX. With a behavior like that in place, clicking the wrong install button the content tab could break your existing worlds for no clear reason. Moreover, I'm fairly certain _this isn't expected behavior by anyone_. Just about every optional dep I've seen in my day was added to bridge compatibility between mods without requiring both mods to be enabled.

To me this looks like a case of poor wording being taken far too literally, without concern for how that literal reading would work in practice.

**Comment by rubenwardy** [comment] 2022-01-12 22:39
If you enable a mod, it shouldn't be silently disabled by Minetest - if there's any issues with dependencies, it should show an error instead.

That would mean that the situation outlined in this issue would show an error, and the user would need to disable mod E.

Optional dependencies should only be considered options when reading mods from the world. Once you start resolving dependencies, any optional dependencies that are installed and enabled should be dealt with the same as a hard dependency

**Comment by rubenwardy** [comment] 2022-04-24 14:57
### Proposal

I think that mods being implicitly disabled when they have unfulfilled dependencies should be deprecated in 5.6.0.

In 5.7.0, we should throw a hard error when a mod doesn't have a fulfilled dependency, or if there's cycles. This will allow the algorithm to be greatly simplified. In the case given in the issue, Minetest will show an error and return to the menu - the user would need to disable mod E. The Config Mods menu should also show errors such as cycles by highlighting mods red

**Comment by IceDragon200** [comment] 2022-04-24 15:23
@rubenwardy Not sure if this would be the right place, but I'd like to see a search field in the mods config as well, sometimes it's hard to sift through hundreds of mods looking for that specific one, and maybe the ability to 'pin' certain mods as favourites, also formal support for version numbers outside of the mod database

**Comment by rubenwardy** [comment] 2022-04-24 15:25
yeah that would certainly be good

**Comment by rubenwardy** [comment] 2022-04-24 21:16
This was discussed in today's dev meeting, and we've decided to resolve this issue with #12217

**Closed** 2022-04-24 21:16 UTC
Labels: Bug
