### ISSUE TITLE
Content store does not retrieve any packages

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7447] opened 2018-06-14 05:44 UTC
##### Issue type

 - Bug report
 
##### Minetest version

```
0.5.0-dev-9a1d3584
```

##### Operating system
Ubuntu 18.04 LTS

##### Summary

Here are the relevant error messages returned:
```
ERROR[Main]: https://content.minetest.net/packages/ not found (Timeout was reached) (response code 200)
ERROR[Main]: Invalid JSON download
```

- Content store tends to work fine on the first run after PC startup.
- Problem starts when MT is closed and reopened, and persists in the subsequent runs.

![image](https://user-images.githubusercontent.com/36130650/41393481-a8983116-6fc3-11e8-905c-8166fcd7a301.png)

**Comment by rubenwardy** [comment] 2018-06-14 10:06
Issue is due to  https://github.com/minetest/contentdv

**Comment by ClobberXD** [comment] 2018-06-27 11:01
Thanks for re-opening.

### Observations:
- Content store tends to work fine on the first run after PC startup.
- Problem starts in the second run and persists in the subsequent runs.

**Comment by NinjaSpectre** [comment] 2018-06-27 22:42
I have encountered this as well, in my case it is when I was disconnected from the internet.  The problem in this scenario is that no packages are ever found (I would assume the same for a timeout) so `#store.packages = 0`. 
https://github.com/minetest/minetest/blob/e36af6f9692993def310cc48ab5c2f65fb0f0267/builtin/mainmenu/dlg_contentstore.lua#L369
This line would then read as `for i=0, 0 do` which in LUA will execute once, but there are no packages to work with.  To remedy this I enclosed this particular for loop inside `if #store.packages > 0 then`

Somewhat related I also encountered an issue with this line regarding the showing of screen shots.
https://github.com/minetest/minetest/blob/e36af6f9692993def310cc48ab5c2f65fb0f0267/builtin/mainmenu/dlg_contentstore.lua#L377
Changing it to `formspec[#formspec + 1] = core.formspec_escape(get_screenshot(package))` resolved that.

**Comment by ClobberXD** [comment] 2018-06-28 01:43
> I have encountered this as well, in my case it is when I was disconnected from the internet

That's expected, but in my case, the connection was working just fine...

> This line would then read as for i=0, 0 do which in LUA will execute once, but there are no packages to work with.

Again, I think that's intended, did you experience any issues here?

> Somewhat related I also encountered an issue with this line regarding the showing of screen shots.

What exactly is the issue you're facing here? If adding `core.formspec_escape` fixes that, please also make a PR with that fix.

**Comment by NinjaSpectre** [comment] 2018-07-05 21:54
Sorry, I didn't realize there was an [issue open](https://github.com/minetest/minetest/issues/7435) already for the screen shots.
I provided these fixes (work for me anyways) in a hope that someone would find them useful, so go ahead and submit if they are a valid solution.  I honestly don't know enough about this project to say if my suggestions will cause problems elsewhere or not.
In the case where no packages are retrieved a stack trace ends up being shown to the user, so I believe that got overlooked.  I don't know enough about formspecs but perhaps a warning could be shown instead saying "No packages could be found on the Content Store".

**Comment by TumeniNodes** [comment] 2018-08-01 23:51
having the same problem now. At one time it worked fine but now, it is not.
was a PR put up? If so can someone mention it here

**Comment by ClobberXD** [comment] 2018-08-02 02:08
Not yet, unfortunately. Will work on it asap.

Thanks for the reminder :)

**Comment by ClobberXD** [comment] 2018-08-03 10:00
Just noticed while grepping: `dlg_contentstore.lua` logs an error `Invalid JSON download` right after the first error.

**Comment by rubenwardy** [comment] 2018-08-03 10:16
The proper fix for this is to add pagination support. Adding proper error messages is also fine to have as well, though

**Comment by ClobberXD** [comment] 2018-08-03 10:28
How would pagination fix this issue? I thought the problem lies in the package-fetching code...

**Comment by rubenwardy** [comment] 2018-08-03 10:53
Adding pagination of the end point would mean that only a few packages would be collected at a time

**Comment by ClobberXD** [comment] 2018-08-03 11:09
Ah... it should fetch page-by-page? So the issue is basically about MT not being able to handle the large amount of data returned?

**Comment by rubenwardy** [comment] 2018-08-03 11:28
It would fetch maybe 50 packages at a time

**Comment by ClobberXD** [comment] 2018-08-03 11:43
Got a different error this time:
```
ERROR[Main]: https://content.minetest.net/api/packages/?type=mod&type=game&type=txp&protocol_version=36 not found (Timeout was reached) (response code 0)
ERROR[Main]: Invalid JSON download
```

**Comment by ClobberXD** [comment] 2018-08-03 16:05
#7612 

@TumeniNodes

**Comment by paramat** [comment] 2018-09-23 19:27
Bump, needs attention.

**Comment by ClobberXD** [comment] 2018-09-30 10:07
Related: #7635

**Comment by paramat** [comment] 2018-11-13 02:35
@ClobberXD 
> Problem starts in the second run and persists in the subsequent runs.

What do you mean by 'run'? Running MT or each attempt to connect to contentstore?

**Comment by ClobberXD** [comment] 2018-11-14 02:39
@paramat: The trend explained in the first post has been inverted, sort of. Now, no packages are retrieved in the first run, but packages are consistently retrieved in every other run. This is quite mysterious, as #7612 changes nothing related to the package retrieval. However, I suggest that this issue remains open until packages are retrieved correctly, **every single time**.

**Comment by paramat** [comment] 2018-11-14 03:12
I agree.
Can't reproduce the bug yet.

**Comment by ClobberXD** [comment] 2018-11-14 03:33
Many people can't reproduce this bug. I'm starting to think that the geographical location might have a role in this. I don't know how, though...

**Comment by rubenwardy** [comment] 2018-11-14 03:39
It's because the download takes more than 2 seconds for you, because of how far you are away from the server and the quality of your Internet.

I think the best fix here is probably to download the packages as a file, like you would a ZIP file. It's not a long term or nice solution, but it's simpler to implement.

Pros:

* Easy to implement
* Less code, more reliable

Cons:

* No packages will be shown until all the data is downloaded. The alternative to this is to use pagination, which would load say 10 packages at a time, allowing Minetest to show packages almost immediately without having to wait.

**Comment by ClobberXD** [comment] 2018-11-14 03:51
It does take ~3-4 seconds for me, _if and only if_ I get that error, which is currently on the first run after PC startup. All the subsequent runs manage to retrieve the packages without the timeout error. I assume this'll get worse with increasing number of packages. Pagination seems to be the ideal long-term solution though, the zip-file technique is just a workaround.

**Comment by paramat** [comment] 2018-11-14 04:43
Rubenwardy's file download suggestion seems okay for 5.0 release because it will at least work, i don't think a perfect content store implementation is a requirement for 5.0.
Then after release move to pagination before the CDB gets particularly large.

**Closed** 2018-12-11 04:43 UTC
Labels: @ Content/PkgMgr, @ Mainmenu, Blocker, Bug, High priority
