### ISSUE TITLE
Improve gamepad and mouse compatibility

### ISSUE THREAD

**Issue by bydariogamer** [minetest/minetest#10297] opened 2020-08-19 16:39 UTC
It is really hard, almost imposible, to control actions that require being fast and acurate with the mobile version of Minetest. Android is clearly not the best option to play this kind of game, but mobile users should have the option to plug their mouse or joysticks and have a better control experience. I know there are many issues about gamepads, but none offers solutions:
For the joystick, it is possible to read directly its input so at least dpad press is converted to arrow keys press or the virtual joystick movement. It is a quick solution that doesn't involve many resources. The normal buttons can be remapped in the key settings of the game or with any other keymapper for Android.
About mouse, isn't it possible to detect cursor position and change the angle of view when mouse moves? It is exactly what happens in PC and an option to enable this setting would be fantastic.
Aditionally, there should be an option to fix a cross pointer in the center of the screen for shooting (it is almost imposible to shoot in mobile because the bullet goes straigh to the center of the screen although you were pressing somewhere else)
(Thanks for your time)

**Comment by SmallJoker** [comment] 2020-08-19 16:49
Gamepad changes requested here: #4153
Improved joystick mechanics: #10031 (cannot merge yet)

> About mouse, isn't it possible to detect cursor position and change the angle of view when mouse moves?

I think you're talking about a Bluetooth or OTG-USB mouse. Android support was horrible in 5.1.0, became better in 5.2.0 but still needs improvements. The current priorities for those who care about Android is to keep it at least usable on new devices/SDKs. PRs are welcome.

Duplicate of #7645 (point 2).
Further OTG problems (keyboard): #8879

**Closed by SmallJoker** 2020-08-19 16:49 UTC
Labels: Feature request
