### ISSUE TITLE
Nodes with metadata are not setting

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest#3821] opened 2016-03-06 21:26 UTC
If you place a node with some metadata, like a chest or furnace, it seems that the node is constructed like any other.  No formspec or infotext is apparent, so you cannot open a chest for example.  Sometimes if you leave the server and come back, or go to another area and come back, or just wait a long enough time, the error seems to correct itself.

In my testing I have used the same version of client/server, and have not done any testing on singleplayer mode.

Since this issue came to my attention, I have been reverting this commit: https://github.com/minetest/minetest/commit/e17fbb31d6db3e6d2d9b68f5793ad8b2146f7bcc which seems to fix the problem for me.  I was waiting to see if anyone else had this problem before I posted an issue.  I see now on IRC a user named ssieb was also having this problem.

**Comment by est31** [comment] 2016-03-06 21:29
Two server owners are reporting this, and the bug is serious enough, so I think its worth to be a blocker.

**Comment by PilzAdam** [comment] 2016-03-06 23:25
I noticed this (or a similar) bug over a year ago.

**Comment by kilbith** [comment] 2016-03-07 10:39
> I noticed this (or a similar) bug over a year ago.

I did too, and I work alot with node metadatas. It's not recent at all.

**Comment by ssieb** [comment] 2016-03-07 16:28
I reverted that commit on my server and I haven't been able to reproduce this problem since.

However, that seems odd if others have been seeing it for a long time since that is a recent commit.  I suspect that there is an underlying issue and that change just made it much easier to trigger.  Even with that commit in, sometimes the objects did work when placed.

One very useful test would be to try (with this commit in) to have two people in the same place.  One places a furnace that doesn't work and the other person tries to access it.  I was in this situation, but I can't remember if I tried to access the furnace before the other person reconnected.  It definitely worked after, even though I didn't leave the area.

**Comment by yyt16384** [comment] 2016-03-08 11:07
I just did a quick test and it seems that #3713 fixes this. Can anyone else test with that PR?

**Comment by everamzah** [comment] 2016-03-08 12:51
Tested and can confirm #3713 fixes this.

**Comment by est31** [comment] 2016-03-08 15:22
Cool.

**Comment by 0-afflatus** [comment] 2016-03-08 23:23
Ah I think I have experienced this. I don't understand how to reproduce it as it happens very occasionally - if I dig the chest and replace it is often fine again.

**Comment by est31** [comment] 2016-03-12 23:10
Fixed by 089f9bbe817debc5c30f1d845170909f638c9642

**Closed by est31** 2016-03-12 23:10 UTC
Labels: @ Server / Client / Env., Blocker, Bug, High priority

**Comment by kilbith** [comment] 2016-03-12 23:23
Just tested, indeed this fixes the metas setting very correctly :+1:
