### ISSUE TITLE
Opening the chest when almost dead leaves the player in a bugged state

### ISSUE THREAD

**Issue by andrenete** [minetest/minetest#10746] opened 2020-12-23 23:05 UTC
Minetest version: `5.3.0`
Operating system: `Ubuntu 20.10`
CPU: `Intel Core i5-1035G1`

##### Summary
If the player opens the chest when he is almost dead AND if the chest inventory appears *after* the death notification, the player will still be "alive" and able to move, but will not be able to interact with the environment and the mapblocks will not load.

`/killme` will fix the problem, but it is unclear why the player is not automatically respawned in this case.

##### Steps to reproduce
Can be achieved by opening a chest when falling off a cliff / drowning. The important thing here is that the inventory should appear after the death notification, effectively "overriding" it.

Video demonstration:

https://user-images.githubusercontent.com/22382143/103042630-4bd5b700-458b-11eb-8748-c3293027686c.mp4

**Comment by hecktest** [comment] 2020-12-23 23:10
Ah, the joys of hardcoded death mechanics.

**Comment by andrenete** [comment] 2020-12-23 23:32
Also, I'm not sure if this is relevant to *this* bug, but if you just leave the chest inventory open and then die, the chest will still be displayed as open after respawn. In this case, you don't even have to wait for notification to appear, and it is even more likely to happen in real game.

https://user-images.githubusercontent.com/22382143/103044052-1e3f3c80-4590-11eb-9eed-5dcbb3bac743.mp4

**Comment by Zughy** [comment] 2020-12-24 00:17
It seems the same behaviour of #7879

**Comment by andrenete** [comment] 2020-12-24 00:41
So, if I understand correctly, the death event should set a lock that disallows other formspec events from happening, and removes the lock after the player presses the respawn button?

**Comment by SmallJoker** [comment] 2020-12-24 12:49
This is a general issue where formspecs are overwritten by a new one, without sending the `"quit"` field of the old one. I think the best solution here would be to handle these cases server-side by passing the field to the script API when there are changes (new formspec, death).

**Comment by sfan5** [comment] 2020-12-24 13:03
closing as duplicate of #7879

**Closed by sfan5** 2020-12-24 13:03 UTC
Labels: Unconfirmed bug
