### ISSUE TITLE
Some error i don't understand

### ISSUE THREAD

**Issue by phobos56** [minetest/minetest#5356] opened 2017-03-07 11:32 UTC
I'm using Minetest 0.4.15 , and i have often this error. My server works but crash sometimes

>ERROR[Main]: ServerError: Lua: OOM error from mod 'technic_worldgen' in callback environment_OnGenerated(): not enough memory
 ERROR[Main]: Current Lua memory usage: 60 MB

> WARNING[Main]: Irrlicht: PNG warning: iCCP: cHRM chunk does not match sRGB
 WARNING[Main]: Irrlicht: PNG warning: iCCP: known incorrect sRGB profile

> ERROR[Main]: Client: Cannot create image from data of file "inventory_sorter_wand_amount.png"
 ERROR[Main]: Client: Cannot create image from data of file "inventory_sorter_wand_wear.png"
 ERROR[Main]: Client: Cannot create image from data of file "inventory_sorter_wand_wise.png"

Help me !

**Comment by dsohler** [comment] 2017-03-07 17:02
> not enough memory

What are you running the server on?

**Comment by SmallJoker** [comment] 2017-03-07 17:05
Duplicate of #2988

**Comment by Fixer-007** [comment] 2017-03-07 22:47
You are using windows, and luajit can have annoying out of memory errors here with heavy mods (which is technic), here is solution: https://kitsunemimi.pw/tmp/minetest-0.4.15-noluajit-win64.7z (it is minetest with lua, that should not give you those OOM errors, but it will run somewhat slower. Some people report that they rarely see luajit OOM errors on linux.

**Comment by est31** [comment] 2017-03-08 00:32
As @SmallJoker says, its a dupe of #2988

**Closed by est31** 2017-03-08 00:32 UTC

**Comment by phobos56** [comment] 2017-03-08 09:04
Thank you , i try  that !
