### ISSUE TITLE
"Open User Data Directory" button opens binary/DLLs directory on Windows

### ISSUE THREAD

**Issue by swagtoy** [minetest/minetest#15153] opened 2024-09-12 05:49 UTC
### Minetest version

```true
5.9.0
```

### Irrlicht device

WIN32

### Operating system and version

Windows 11 The latest

### CPU model

Fast

### GPU model

Okay

### Active renderer

OpenGL 4.6.0

### Summary

Pressing the "Open User Data Directory" button shows the directory containing the games binary. You need to go up the parent directory to access the games folder.

Low priority Not a big deal. If someone can reproduce would appreciate it.

### Steps to reproduce

1. Press the "Open User Data Directory" button
2. End up where the binary is (and its dll's and stuff)

**Comment by Zughy** [comment] 2024-09-12 07:00
Duplicate of #12631

**Closed by Zughy** 2024-09-12 07:00 UTC
Labels: Unconfirmed bug

**Comment by swagtoy** [comment] 2024-09-12 07:06
Thx
