### ISSUE TITLE
Game minimap textures are ignored by Minetest

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10625] opened 2020-11-12 16:09 UTC
##### Minetest version
```
5.3..
```

##### Summary
If you place a custom minimap texture (see `doc/texture_packs.txt`) into your game, it doesn't work. You will still see the default minimap textures.

##### Steps to reproduce
1. Place some minimap textures like `minimap_overlay_square.png` or `player_marker.png` into any mod of a game
2. Start the game
3. Activate the minimap

**Comment by SmallJoker** [comment] 2020-11-12 18:03
Duplicate of #7325

**Closed by SmallJoker** 2020-11-12 18:03 UTC
Labels: Unconfirmed bug
