### ISSUE TITLE
More and better controls for android

### ISSUE THREAD

**Issue by wwar-XeStro** [minetest/minetest#10843] opened 2021-01-21 14:13 UTC
## Problem

playing on phones is hard and needs more and better controls

To make playing on phones easier, allow users to access more features and to lower the difference between playing on a PC  and playing on phone...

Adding a new button (that works as left-click)  instead of tapping will make it easier to play the game with more features, faster interacting and better on PvP and PvE.

Add a setting to switch between that new button and tap.

Add a crosshair and a section to change pitch move, view range and full chat

**Comment by Zughy** [comment] 2022-05-08 23:49
For the tap, duplicate of #2761. For the rest, it's pretty similar to #11404 and the more recent #12227. Furthermore, I can't rename issues and right now they all basically have the same title. Closing here

**Closed by Zughy** 2022-05-08 23:49 UTC
Labels: Feature request, Android, @ Client / Controls / Input
