### ISSUE TITLE
Huge pauses when deallocating memory

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#14015] opened 2023-11-19 06:50 UTC
### Minetest version

```
5.7.0
```

### Summary

Minetest takes insane amounts of time to free various objects. This is observed in (I think) both client and server environments, but can be more readily observed on the client as it can straight up freeze the main thread and make the window unresponsive. The unloads cause massive amounts of lag and are responsible for "lag storms" that can take the program even minutes to recover from. Client and server lag spikes of 30+ seconds are not unheard of. These usually happen during "unload unused data" cycles on both the client and the server. 

One other place it happens is when the game session is being shut down and is probably the cause of #13518

I've observed performance graphs of the process during each of these events, and have noticed some odd things they have in common:

Before any memory is freed, a lot of it is allocated. This happens even during shutdown, which means this isn't just new data being created, but data structures being allocated as part of the cleanup process. These allocations take more time than the actual release and sometimes outweigh the size of the memory being freed. They are also blocking whatever other work is happening. The deallocation process is single threaded and makes one CPU grind at 100% while others wait. (I'm aware this could just be the heap itself, but that means the heap is a mess)

These alloc-dealloc cycles are performed in batches of decreasing size and increasing speed, resembling an evaporating black hole. The memory graph during a shutdown is this slightly unbalanced triangle wave that slowly tends towards zero. The frequency of the cycles and speed of deallocations increases as the amount of held memory decreases.

In general this is not what you'd expect. During shutdown especially, you kind of assume that closing a session would involve just forgetting about all the state at once after saving what must be saved.

I have ruled out map saves as a cause of any of this; the map save is instantaneous and the amount of data involved is orders of magnitude smaller than what we have here. I doubt it's an irrlicht problem either because servers can also suffer lag storms.

My guesses, in no particular order:
- Something is iterated over and possibly (accidentally?) copied during the collection process
- C++ destructors are causing unexpected, sub-optimal behavior
- We're allocating too little at a time (a mapblock without meta is only 16K)
- The heap is badly fragmented and just takes a long time to deal with (the cure would be allocating more at a time)
- Iterating two levels of dictionaries to free every individual mapblock in a two-level loop, where blocks are allocated one mapblock at a time including the padding on both ends of the buffer. This can't possibly be fast. (the memory nightmare that is MapBlock deserves an issue of its own, but it could also be the sole cause of this one)
- STL containers could be doing something weird here, in at least one implementation

Some graphs:
![image](https://github.com/minetest/minetest/assets/42101236/437991db-9b12-47cc-8d64-9e3174b5244b)

### Steps to reproduce

Disable the client block limit so that you can rake up a lot of RAM for blocks. Load blocks until at over 6 GB. Attempt returning to the menu, see that it takes forever or at least longer than it should. Process's RAM history should be a strange sawtooth or triangle wave.

**Comment by hecktest** [comment] 2023-11-19 10:47
Some notes regarding the MapBlock class and the horrible memory layout that could be causing this, as well as possible improvements:
- MapBlock data array is co-located with junk metadata in a single struct, most likely SIMD-unaligned
- The other MapBlock fields are very redundant and wasteful; some of those could exist as huge bitmaps (just one bitmap for all the booleans), others could be completely inferred from other data and deleted. Some are caches and pointers for other code. The MapBlock struct seems like it's trying to satisfy too many parts of code at once, each of which could probably work with a bitmap or structure maintained specifically for it.
- The interleaving of metadata with the buffer makes the struct size extend past 16K, resulting in extra memory pages being committed; I suspect the heap looks like swiss cheese because of it
- MapBlocks are allocated individually using `new`, probably with no spatial relation to one another address-wise
- The lack of alignment on block data prevents efficient vectorization; you cannot use an instruction like `movaps` on unaligned data. Older CPUs suffer more from this.
- Blitting a VoxelManip from and back to mapblocks - are we really broadcasting all this data to every mapblock that a chunk intersects? (yes we are.) That's 216 different memory offsets that each need 16 kB individually, with a ton of trash around them. A prefetch hint would help, but keeping the data close together, aligned and uniform would help even more.
- A map contains sector hashmaps which in turn are mapblock hashmaps. Two STL containers must be indexed to retrieve or free a block.
- MapSector being a vertical pillar stinks, one of these must be loaded for every XZ location that a player sees. Why isn't it a 16x16x16 megablock instead?
- Why isn't virtual memory being used instead of hashmaps? 64-bit processors have been around for 20 years. Blocks are page-aligned.
- Representing the world as four levels of nested 16x16x16 blocks would be a lot cleaner - think about it, offsets within those would just be obtained by masking and shifting the appropriate nibble in the coordinate. Data at the first two levels should just be allocated in one uncommitted virtual buffer at a time. (which would be 64M virtual per megablock; commit depending on usage - making 512M (128 nodes range, 2x2x2 megablocks) a minimum requirement,  and 1728M (3x3x3, 512 ) the most a 32-bit client can handle, leaving 300 (more than enough) for the rest) - note that this memory would only be allocated and uncommitted parts of the process address space, physical ram can be smaller.

**Comment by sfan5** [comment] 2023-11-19 11:46
I have some more thoughts I'll add later but my test result first:

I just had a 6 GB game session and teardown took a whole 3 seconds.
The flame graph reveals that 16% of time was spent in `free`:
![grafik](https://github.com/minetest/minetest/assets/1042418/8e9e32ec-4901-4303-9161-09eac895b014)

I have seen this situation in other projects and I suspect that Microsoft's C runtime is very slow to deallocate large amounts of objects.
This can also serve as an explanation why nobody looked into many possible optimizations like you mentioned: most of us use Linux.

**Comment by Desour** [comment] 2023-11-19 12:43
I've also tried to reproduce on linux. A 3 GB session (for which I already had too fly around quite long, is there a faster way?) also just took about 3 seconds to quit. (Didn't take profiling data.)

The potential optimizations mentioned by hecktest are of course fun and interesting (I've also thought about most of these myself), but they're not really fruitful without benchmarking and profiling.

If the microsoft heap is too slow, we could consider using C++17's pool allocators (see e.g. `std::pmr::unsynchronized_pool_resource`).

**Comment by hecktest** [comment] 2023-11-19 13:24
What is the official windows release built with? MinGW by any chance?

So I've stepped through what's happening and yes, the program spends an awful amount of time in ntdll.dll during the `delete` (internally just a `free()`). The object being deleted is of course a MapBlock. (I was wrong about it not being contiguous with other blocks, but that probably doesn't help much.)

From what I'm reading here and there, the culprit might be msvcrt.dll which is an ancient and unmaintained version of the C runtime, and only kept around for compat, yet for whatever reason the libstdc++ that Minetest ships with links exactly to that. Perhaps there's a way to compile this with a less naive malloc.
![image](https://github.com/minetest/minetest/assets/42101236/91d39066-f8f8-4c09-b9f5-d817799f7b96)

I'll try compiling with clang if I can find the time to fix my scripts; clang links a more recent CRT.

**Comment by sfan5** [comment] 2023-11-19 13:46
> What is the official windows release built with? MinGW by any chance?

Yep, MinGW gcc with msvcrt.
The next version of MinGW in fact makes UCRT the default but we can of course upgrade our toolchain earlier (I planned to do so anyway).

> Perhaps there's a way to compile this with a less naive malloc.

Another alternative here would be [mimalloc](https://github.com/microsoft/mimalloc/) which is even developed by MS.

<hr>

> If the microsoft heap is too slow, we could consider using C++17's pool allocators

Indeed, I wanted to suggest that too.
Putting all mapblocks in a pool is relatively easy to do and should have caching benefits without relying on implemention details (the OS allocator).

**Comment by sfan5** [comment] 2023-11-19 14:40
> * MapBlock data array is co-located with junk metadata in a single struct, most likely SIMD-unaligned

> * The lack of alignment on block data prevents efficient vectorization

You are correct, it's only aligned by 4. I couldn't conclusively test whether there even is any potential for gcc to automatically vectorize code working with map data.

For example gcc refused to vectorize either of these no matter what I did:

```c++

#include "mapblock.h"

#pragma GCC push_options
#pragma GCC optimize ("O3")
#pragma GCC optimize ("tree-vectorize") 

bool test_function(MapBlock *block)
{
	for (u32 i = 0; i < MapBlock::nodecount; i++) {
		if (block->getData()[i].getContent() == CONTENT_AIR)
			return true;
	}
	return false;
}

bool test_function2(u16 *buffer) // hypothetical situation where MapNode is split apart
{
	for (u32 i = 0; i < MapBlock::nodecount; i++) {
		if (buffer[i] == CONTENT_AIR)
			return true;
	}
	return false;
}

#pragma GCC pop_options
```
(and this isn't even a good example because we usually iterate x/y/z individually)

> The other MapBlock fields are very redundant and wasteful

I agree the `contents` unordered set is not optimal but I don't think you want to use 4096 bytes just to toggle like 10 bits in it.
The actual structure for storing the content cache could probably better be a vector.
Others, not sure. But the order of members definitely needs a cleanup.

> The interleaving of metadata with the buffer makes the struct size extend past 16K
 
Node data actually [used to be](https://github.com/minetest/minetest/blob/426b5d3149f5fe510322a26cc8e67ba6de08d4a6/src/mapblock.h#L619) separate from the metadata.
I think nobody thought about performance/fragmentation implications when this was changed (I don't even remember when).

> MapBlocks are allocated individually using new

Since we're C++17 now we can use a memory pool via [pmr](https://en.cppreference.com/w/cpp/memory#Memory_resources_.28since_C.2B.2B17.29). Sounds like a good idea to me.

> Blitting a VoxelManip from and back to mapblocks - are we really broadcasting all this data to every mapblock that a chunk intersects?

MapChunks being 5x5x5 MapBlocks is only used during mapgen. Voxelmanips should be working at a mapblock granularity.

> A map contains sector hashmaps which in turn are mapblock hashmaps. Two STL containers must be indexed to retrieve or free a block.

We had the idea to use a flat map before: #10656
turns out `MapSector` is a good for performance

> MapSector being a vertical pillar stinks, one of these must be loaded for every XZ location that a player sees. Why isn't it a 16x16x16 megablock instead?

I mean optimizing for vertical access doesn't seem to bad.

> Why isn't virtual memory being used instead of hashmaps? 64-bit processors have been around for 20 years. Blocks are page-aligned.

This is a novel idea but I think we can get 90% of the performance using the other ideas without having to worry about 32-bit or other fringe platforms (does WebAssembly have virtual memory?).

**Comment by hecktest** [comment] 2023-11-20 01:55
> I couldn't conclusively test whether there even is any potential for gcc to automatically vectorize code working with map data

I don't know about auto vectorization, but you couldn't even do it manually with a buffer embedded like this. Allocating it separately would fix this, as is the case with VoxelManip.

> I don't think you want to use 4096 bytes just to toggle like 10 bits in it.

No, by bitmaps I meant things like per-mapblock booleans being stored together in bitmaps aggregating several blocks at a time. Compilers will often just give each boolean a whole u64, and code checking for flags like that usually wants to check them in bulk to decide whether to run or skip a certain operation, and the check could be vectorized if a bitmap is used. You could store up to 256 blocks with a single bit compare and reduce. The skipped iterations add up, and the cache is happy because it doesn't have to load all that interleaved data. Code that checks a single boolean in an array (or worse, hashmap) of structs is just slow.

![image](https://github.com/minetest/minetest/assets/42101236/7f0f1525-b507-4fc2-9cb1-239fc2f7fc57)

> MapChunks being 5x5x5 MapBlocks is only used during mapgen. Voxelmanips should be working at a mapblock granularity.

I was definitely able to create bigger voxelmanips outside of the mapgen and treat them as contiguous areas, so all voxelmanips seem to work the same way. Every time a blit from or to the map is performed, the data is probably moved in very inefficient ways, just for the alignment issues alone.

> turns out MapSector is a good for performance

Could it be due to the dependent code doing something it shouldn't, like relying on this structure for spatial information (query blocks within area, view frustum, etc) - when this is a job for an actual space subdivision structure, such as an octree?

> does WebAssembly have virtual memory?

It's complicated, but a short answer is yes. 32-bit is also no cause for worry, I've calculated this in the post above; there's nothing wrong with pre-reserving address space for all the blocks the machine is physically capable of handling, in a program whose job is mostly handling blocks. But consider that you can always fall back from a sparse array to a hashmap with little change in the surrounding code.

**Comment by lhofhansl** [comment] 2023-11-24 18:55
Related: #13545 and #13518

**Comment by lhofhansl** [comment] 2023-12-08 23:49
@hecktest Any chance to retest with #14086?

Not sure it will help, but it does avoid a bunch of small heap allocations.

**Comment by lhofhansl** [comment] 2023-12-12 03:58
> The actual structure for storing the content cache could probably better be a vector.

I added the content cache some time back to avoid expensive ABM calculations. My apologies.
It's needs to be a set (or otherwise be deduped) as that is its entire point.
A bitset would need to store 2^16 bits. Could group multiple blocks as @hecktest suggest, but that'd be ugly as not all blocks in a group are loaded, etc.
As the content cache stores 64 bytes max, could sort-unique-erase in it, or search each time.

> We had the idea to use a flat map before: https://github.com/minetest/minetest/pull/10656
turns out MapSector is a good for performance

yeah. I tried. )
That said - and only somewhat related - I see many loops that loop over x, y, z, in that order, and get a block/node inside the loop. In order to make most use of MapSectors, we should always use x,z,y, or z,x,y as loop order.

**Comment by sfan5** [comment] 2023-12-12 12:13
> It needs to be a set (or otherwise be deduped) as that is its entire point.

Sure, my point is that a linear search should be faster than going through some tree (`std::set`) or indexing a hashtable (`std::unordered_set`) *for small quantities*.

**Comment by celeron55** [comment] 2023-12-16 12:04
> turns out MapSector is a good for performance

It seems people have been and still are totally blind to the fact that MapSector contains a cache for the last used MapBlock in the sector. THAT is what brings in the performance. This is some of the very early skunkwork I did to make Map perform reasonably.

I don't have much to say about anything else mentioned here other than that there are likely many many little optimizations that can be done that will sum up to a considerable performance boost. It's a good effort.

**Comment by sfan5** [comment] 2023-12-20 20:23
based on feedback from https://github.com/minetest/minetest/pull/14127#issuecomment-1864920271 I'm marking this as possible close.

**Closed** 2024-01-22 22:46 UTC
Labels: Bug, @ Server / Client / Env., Windows, Performance, Possible close
