### ISSUE TITLE
Allow Multiple Nodes To Occupy The Same Space

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#13045] opened 2022-12-14 16:07 UTC
## Problem

It's currently impossible to have multiple nodes occupy the same space without some ugly and/or hacky workarounds.

## Solutions

Make it possible for multiple nodes to occupy the same space.

## Additional context

One way that this could be useful, is if you want to have a node that has multiple layers that you need to break through to reach the centre.

Another way this could be used is to have sand fill up an entire room, without leaving weird pockets of air in between furniture.

Or maybe you want to hide a fossil inside a dirt node, which reveals itself after you have dug up the dirt.

Or this could also make it possible to have waterlogged nodes as in Minecraft 1.13 and onward, which would allow for creating structures underwater that don't look weird when you utilise anything that is not a full node in size.

**Comment by SmallJoker** [comment] 2022-12-14 19:25
Minetest is a voxel-based game. This means that there's one voxel per unit. Logically there is no way to fit two nodes into the same coordinate.

Suggested alternative: register a bunch of nodes, each with an additional layer which is then removed by node replacement upon digging. Alternatively use objects which can be spawned anywhere.

**Comment by alerikaisattera** [comment] 2022-12-15 13:11
> Then how does Minecraft do it since the 1.13 update with waterlogged things? That is actually what I would love to be focussed on the most. The other things I mentioned are just a bonus that might become possible if this feature idea happens.

By using blockstates

**Comment by TurkeyMcMac** [comment] 2022-12-15 13:12
There seems to be precedent for declaring this a duplicate of https://github.com/minetest/minetest/issues/3074.

**Closed by TurkeyMcMac** 2022-12-15 13:12 UTC
Labels: Feature request

**Comment by TurkeyMcMac** [comment] 2022-12-15 14:19
Allowing multiple nodes per position was mentioned there: https://github.com/minetest/minetest/issues/3074#issuecomment-766153815

**Comment by TurkeyMcMac** [comment] 2022-12-15 15:09
Yes, this feature probably won't be added soon, unless someone takes it upon themself to implement it.

**Comment by PavanLuca** [comment] 2023-05-08 17:47
I see seaweed occupying more nodes since I played a new map on CTF. It can't be hit on its half top part though. If seaweed can stay on more nodes why not even other decorations? Grass and flowers remove water node, but I'd like that even ladders do the same as seaweed do because some players use this thing to survive drowning on water and lethal burns on lava.

**Comment by sfence** [comment] 2023-12-19 19:38
@FossFanatic Maybe, this #14103 can take your attention.
