### ISSUE TITLE
build failed with xcode11.2.1 and xcode10.3

### ISSUE THREAD

**Issue by tsao-chi** [minetest/minetest#9201] opened 2019-12-14 17:36 UTC
##### Minetest version
https://github.com/minetest/minetest/commit/8e63d22d6472b61477f804dc5b00705650f90409

##### Log

```
[ 23%] Building CXX object src/CMakeFiles/minetest.dir/client/clientlauncher.cpp.o

/tmp/WORKSPACE/minetest/src/client/camera.cpp:165:32/tmp/WORKSPACE/minetest/src/client/clientenvironment.cpp:232:32: error: member access into incomplete type 'MtEventManager'

                                m_client->getEventManager()->put(new SimpleTriggerEvent(MtEvent::VIEW_BOBBING_STEP));

                                                           ^

/tmp/WORKSPACE/minetest/src/client/client.h:57:7: note: forward declaration of 'MtEventManager'

class MtEventManager;

      ^

/tmp/WORKSPACE/minetest/src/client/camera.cpp:183:32: error: member access into incomplete type 'MtEventManager'

                                m_client->getEventManager()->put(new SimpleTriggerEvent(MtEvent::CAMERA_PUNCH_LEFT));

                                                           ^

/tmp/WORKSPACE/minetest/src/client/client.h:57:7: note: forward declaration of 'MtEventManager'

class MtEventManager;

      ^

/tmp/WORKSPACE/minetest/src/client/camera.cpp:185:32: error: member access into incomplete type 'MtEventManager'

                                m_client->getEventManager()->put(new SimpleTriggerEvent(MtEvent::CAMERA_PUNCH_RIGHT));

                                                           ^

/tmp/WORKSPACE/minetest/src/client/client.h:57:7: note: forward declaration of 'MtEventManager'

class MtEventManager;

      ^

: error: member access into incomplete type 'MtEventManager'

                                m_client->getEventManager()->put(

                                                           ^

/tmp/WORKSPACE/minetest/src/client/client.h:57:7: note: forward declaration of 'MtEventManager'

class MtEventManager;

      ^

3 errors generated.

make[2]: *** [src/CMakeFiles/minetest.dir/client/camera.cpp.o] Error 1

make[2]: *** Waiting for unfinished jobs....

1 error generated.

make[2]: *** [src/CMakeFiles/minetest.dir/client/clientenvironment.cpp.o] Error 1

make[1]: *** [src/CMakeFiles/minetest.dir/all] Error 2

make: *** [all] Error 2
```

**Comment by SmallJoker** [comment] 2019-12-14 17:45
MtEventManager is defined here:
https://github.com/minetest/minetest/blob/b298b0339c79db7f5b3873e73ff9ea0130f05a8a/src/event.h#L63

Included here:
https://github.com/minetest/minetest/blob/8e63d22d6472b61477f804dc5b00705650f90409/src/client/clientenvironment.cpp#L28

I don't see any issue. Are you sure that there are no local changes?

**Comment by tsao-chi** [comment] 2019-12-14 18:05
yes.

**Comment by tsao-chi** [comment] 2019-12-14 18:24
https://travis-ci.com/tsao-chi/minetest/jobs/267288051

**Comment by tsao-chi** [comment] 2019-12-14 18:29
https://travis-ci.com/tsao-chi/minetest/jobs/267288051#L320

**Comment by lattejed** [comment] 2019-12-26 08:22
FYI, I've just encountered this using `cmake -G Xcode` to create a project for Xcode 10.2.1

**Comment by sfan5** [comment] 2020-01-22 21:58
duplicate of #9201

**Closed by sfan5** 2020-01-22 21:58 UTC
Labels: Bug, Duplicate
