### ISSUE TITLE
Add a hotkey to toggle fullscreen mode

### ISSUE THREAD

**Issue by BruceMustache** [minetest/minetest#10146] opened 2020-07-03 15:43 UTC
## Problem

Can't toggle fullscreen mode rapidly using hotkey without using system wide or restarting Minetest

ie: I think it's good to players focus in games with fullscreen and when they want to see something in OS they can just press F11 (for example) see what they want and back to fullscreen

Ex. In a laptop I use linux Mint that support fullscreen toggling by the window manager while in another computer using puppy linux the window manager (jwm) don't have a cleared way to set a hotkey for toggling fullscreen mode in a window

## Solutions

Add a configurable hotkey to toggle fullscreen mode

**Comment by paramat** [comment] 2020-07-03 19:10
Possibly a duplicate of #4921 which discusses a game fullscreen ability.

**Comment by paramat** [comment] 2020-07-03 19:16
Related #4921

**Comment by BruceMustache** [comment] 2020-07-07 16:38
Oh sorry. I don't see this

**Closed** 2020-07-07 16:38 UTC
Labels: Feature request
