### ISSUE TITLE
Overflowing button labels are cut off

### ISSUE THREAD

**Issue by alrito28** [minetest/minetest#14633] opened 2024-05-09 20:00 UTC
### Problem

Hi,
there's a writing bug in French at the level of the buttons in the menus, but I think it may depend on the screen size.
![Screenshot_20240509_212759](https://github.com/minetest/minetest/assets/100717534/8e299bf5-b837-4169-94c9-d9f965075ac8)
![Screenshot_20240509_212902](https://github.com/minetest/minetest/assets/100717534/aaff75b0-4c85-4527-9726-003c8e7761c1)
![Screenshot_20240509_213008](https://github.com/minetest/minetest/assets/100717534/ccbab2c2-1478-4e1a-88f0-9559fa146b60)

### Solutions

Maybe increase the size of the menu frame a bit to make it fit perfectly, to be seen :)

### Alternatives

I don't have another

**Comment by appgurueu** [comment] 2024-05-09 20:34
German translations tend to have the same issue. I feel there should already be an open issue for this, but I can't seem to find it.

Cheap workarounds involve shortening translations or widening GUI elements. I don't think this is really feasible long-term, and it is certainly not feasible to expect modders to do this kind of thing, taking all the variables (language, screen size, font, font size, etc.) into account.

IMO a proper alternative solution would be to scale down (or wrap) button text to make it fit.

A more long-term solution would be having much more dynamic layouts where buttons may grow and shrink depending on the size of the text they contain.

**Comment by grorp** [comment] 2024-05-09 20:43
Duplicate of #4607

**Closed** 2024-05-09 22:09 UTC
Labels: Bug, Formspec

**Comment by alrito28** [comment] 2024-06-13 12:16
Hello,

I've made an overdraft, I have two PCs with two different screens. Well, when I'm at 1920x1080, it doesn't crop, but when I'm at 1366x768, it does crop.

**Comment by appgurueu** [comment] 2024-06-13 15:15
Yes, when your screen is smaller, the chances that something overflows are bigger...
