### ISSUE TITLE
Add double-click inventory moving

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#2207] opened 2015-01-25 21:27 UTC
This would be a very welcome feature. It's especially useful when the stack_max is 1 and you're crafting something.

**Comment by cheapie** [comment] 2015-02-07 15:55
What are you wanting double-clicking to do?

**Comment by MT-Modder** [comment] 2015-02-07 20:52
For example, if you double clicked an item in your inventory while looking in a chest the item is moved to the first available slot in the chest. Another example, if your in your own inventory and double clicked an item it's moved to the first available crafting slot.

**Comment by cheapie** [comment] 2015-02-10 21:53
In that case, I believe this is a duplicate of #1311 and #521.

**Comment by MT-Modder** [comment] 2015-02-10 23:09
Thanks cheapie, didn't know those existed.

**Closed** 2015-02-10 23:09 UTC
Labels: @ Client / Audiovisuals, feature request, Low priority
