### ISSUE TITLE
Minetest doesn't start android 10

### ISSUE THREAD

**Issue by SeBarosanul** [minetest/minetest#10001] opened 2020-06-06 13:46 UTC
##### Minetest version

```

```

##### OS / Hardware

Operating system: Android 10
CPU: Exynos 9820 

GPU model:
OpenGL version:

##### Summary
On first launch, a loading screen appears. Once the bar reaches 100%, the game crashes and reopens, and the same thing happens, making it impossible to get into the game and very hard to exit the game.

##### Steps to reproduce
1. Open F-Droid
2. Download Minetest
3. Open it

**Comment by SmallJoker** [comment] 2020-06-06 13:55
Duplicate of #9413.

Please try a build from here: https://minetest.rubenwardy.com/android/

**Closed by SmallJoker** 2020-06-06 13:55 UTC
Labels: Unconfirmed bug
