### ISSUE TITLE
Remove Minetest Game as a default game

### ISSUE THREAD

**Issue by 56independent** [minetest/minetest#13410] opened 2023-04-10 08:43 UTC
## Problem

(from a [contentDB review](https://content.minetest.net/threads/4609/)

Minetest game is a perfectly fine game, just like Development Test or Dreambuilder game. It works well, has few bugs, and is the perfect base to build on. I use it a lot and i love it.

It provides a good base for mods, for gameplay, and many other things.

However, the circumstances surrounding it are what makes it bad; it is often treated as a "default" game when it provides little. How many potential developers saw Minetest and went "ahh nah it's just a hobbyist project with too few blocks"? How many potential modders, core developers, experts with free time, and testers were discouraged by seeing this game? Definately me at first with 8 years of age, thinking Minetest was useless and was not as cool as other thins at the time.

Minetest on its own is not good enough and projects the wrong image.

Until we can finally move Minetest Game from "default" position, we will never see just how incomplete and gameplay-less it is. It is one of the oldest games and might as well have died of old age had it not been propped up by the engine.

Removing it from README is a good start.

## Solutions
I'd like to see other games included to show the true diversity of Minetest in the Readme; yearly game reccomendations voted on by majority poll of the community.

Currently:

> Download Minetest Game (otherwise only the "Development Test" game is available) using Git:

When it might as well be:

> Download a game when you have finished compiling;  many can be found at [ContentDB](https://content.minetest.net/packages/?type=game), but we reccomend Minetest Game, first poll result, second poll result, or third poll result.

**Comment by sfan5** [comment] 2023-04-10 12:26
Almost nobody reads the README (e.g. it's not even included in Windows or Android builds) so this would be a placebo measure at most.
Our long term plan is to stop shipping MTG by default and lead users to downloading a game from CDB on first launch.

**Comment by 56independent** [comment] 2023-04-10 12:30
> nobody reads the README (e.g. it's not even included in Windows or Android builds) so this would be a placebo measure at most. 

Yeah, i guess i am one of the few people who likes to compile and be on the bleeding edge and push forwards.

> Our long term plan is to stop shipping MTG by default and lead users to downloading a game from CDB on first launch.

Good idea! I should have put that as the issue title instead, silly me.

**Comment by rubenwardy** [comment] 2023-04-10 13:27
Duplicate of #9509

**Closed by rubenwardy** 2023-04-10 13:27 UTC
Labels: Request / Suggestion, Possible close
