### ISSUE TITLE
Add Minetest to the Valve Steam game store

### ISSUE THREAD

**Issue by heylix** [minetest/minetest#13619] opened 2023-06-22 06:23 UTC
## Problem

Children and people who are used to installing stuff from app stores [can't find Minetest in the Steam store](https://store.steampowered.com/search/?term=minetest):

![Screenshot of the Steam store page with an empty result list](https://github.com/minetest/minetest/assets/36211486/3c6e59b1-7c0a-49df-af01-563b569d9770)

## Solutions

Publish to the Steam store.

## Alternatives

Current downloads on the main page.

## Additional context

Many, many small users aged <<12 mainly install "apps" on their devices and I found while teaching them, that they often don't understand the concept of a program, a download or sometimes even typing on a keyboard. Apparently in schools they mainly use apps and touch. That shouldn't be seen as disrespecting them, but rather as an accessibility issue.

Minetest is already available on Android in the F-Droid store and you're planning to release to the Microsoft store (#12605), so that's a plus. But IMHO it should be distributed to the main gaming platforms, starting with Steam, maybe continuing with Epic Games Store and even the less "mainstream" itch.io.

**Comment by wsor4035** [comment] 2023-06-22 23:10
duplicate of https://github.com/minetest/minetest/issues/9028

**Closed** 2023-06-22 23:10 UTC
Labels: Duplicate, Feature request
