### ISSUE TITLE
Optional dependencies failing mod because of the optional's hard dependencies

### ISSUE THREAD

**Issue by IceDragon200** [minetest/minetest#10482] opened 2020-10-12 06:35 UTC
##### Minetest version

```
Minetest 5.4.0-dev-debug-b2f3f6638 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

##### OS / Hardware
Operating system: `Linux 5.8.5-arch1-1 #1 SMP PREEMPT x86_64 GNU/Linux (Arch Linux)`
CPU: `Intel i7-2710QE`

GPU model: N/A
OpenGL version: N/A (not a graphics issue)

##### Summary

Not sure if it's the same problem as #8601

Snippet from my logs:

```
ERROR[Main]: mod "yatm_autotest" has unsatisfied dependencies:  "yatm_mesecon_locks" "yatm_mesecon_hubs" "yatm_item_teleporters" "yatm_item_ducts" "yatm_fluid_pipe_valves" "
yatm_spacetime" "yatm_mesecon_buttons"
ERROR[Main]: mod "yatm_codex_entries" has unsatisfied dependencies:  "yatm_fluid_teleporters" "yatm_fluid_pipe_valves" "yatm_item_teleporters" "yatm_item_ducts"
ERROR[Main]: mod "yatm_data_to_mesecon" has unsatisfied dependencies:  "mesecons"
ERROR[Main]: mod "yatm_fluid_pipe_valves" has unsatisfied dependencies:  "mesecons"
ERROR[Main]: mod "yatm_fluid_teleporters" has unsatisfied dependencies:  "yatm_spacetime"
ERROR[Main]: mod "yatm_item_ducts" has unsatisfied dependencies:  "yatm_spacetime"
ERROR[Main]: mod "yatm_item_teleporters" has unsatisfied dependencies:  "yatm_spacetime"
ERROR[Main]: mod "yatm_mesecon_buttons" has unsatisfied dependencies:  "mesecons"
ERROR[Main]: mod "yatm_mesecon_card_readers" has unsatisfied dependencies:  "mesecons"
ERROR[Main]: mod "yatm_mesecon_hubs" has unsatisfied dependencies:  "mesecons"
ERROR[Main]: mod "yatm_mesecon_locks" has unsatisfied dependencies:  "mesecons"
ERROR[Main]: mod "yatm_mesecon_sequencer" has unsatisfied dependencies:  "mesecons"
ERROR[Main]: mod "yatm_spacetime" has unsatisfied dependencies:  "mesecons"
```

As shown in the logs: some mods have unsatisfied dependencies on mesecons causing a cascading failure, that much is expected as the mods are currently be reworked to remove those hard dependencies.

However, in the case of [yatm_autotest](https://github.com/IceDragon200/mt-yatm/blob/master/yatm_autotest/mod.conf#L3) and [yatm_codex_entries](https://github.com/IceDragon200/mt-yatm/blob/master/yatm_codex_entries/mod.conf#L4), all of the specified dependencies are _optional_.

Here is the mod.conf for reference (in case the links change slightly):

```
name = yatm_codex_entries
description = Provides entries and demos for YATM mods
depends = yatm_core,yatm_codex
optional_depends = yatm_armoury,yatm_armoury_icbm,yatm_data_logic,yatm_data_network,yatm_data_noteblock,yatm_drones,yatm_dscs,yatm_energy_storage,yatm_energy_storage_array,yatm_fluid_pipe_valves,yatm_fluid_pipes,yatm_fluid_teleporters,yatm_foundry,yatm_frames,yatm_item_ducts,yatm_item_teleporters,yatm_mail
```

The expected behaviour is any 'optional' dependency, even if it fails it's own dependencies should not affect another mod that has it optional. 

##### Steps to reproduce

I wouldn't suggest using my mods as a test, there is a lot of undocumented setup required (foundation stuff).

I've tried it with a minimal test case:

__Base mod__

```
name = mod_base
```

__First optional mod with a hard dependency on mod_missing__

```
name = mod_a
depends = mod_base,mod_missing
```

__Second optional mod__

```
name = mod_b
depends = mod_base
```

__Last or the top-level mod that optionally depends on mod_a and mod_b__

```
name = mod_top
depends = mod_base
optional_depends = mod_a,mod_b
```

Expected behaviour:

* `mod_base` loads
* `mod_a` fails to load with unsatisfied dependencies 'mod_missing'
* `mod_b` loads
* `mod_top` loads (with `mod_b` and without `mod_a`)

Actual behaviour:

* `mod_base` loads
* `mod_a` fails to load
* `mod_b` loads
* `mod_top` fails to load with unsatisfied dependencies `mod_a`

**Comment by rubenwardy** [comment] 2020-10-12 09:14
Duplicate of #8601 

I like your description though, maybe past it there too?

**Closed by rubenwardy** 2020-10-12 09:14 UTC
Labels: Unconfirmed bug
