### ISSUE TITLE
4k laptop screen support for 2020 

### ISSUE THREAD

**Issue by masterleo** [minetest/minetest#9273] opened 2020-01-01 13:37 UTC
## Problem
When I play I can not use the HUD or the menu bars or the inventory menu. 
![Screenshot from 2020-01-01 14-02-40](https://user-images.githubusercontent.com/8157302/71641974-4b6e4d00-2ca4-11ea-9c49-3d7c9ef3e668.png)
![Screenshot from 2020-01-01 14-06-28](https://user-images.githubusercontent.com/8157302/71641975-4b6e4d00-2ca4-11ea-940b-2d48a094dd3e.png)

## Solutions

I would like the menus and all the things displayed on 4K screens have the same size as on 1080p screens.

## Alternatives

play with this weird display on things on the screen. Barly usable by the way. 

## Additional contex 
I  play  on a thinkpad x1 extreme laptop with a 4k oled screen

**Comment by masterleo** [comment] 2020-01-01 13:39
I am available to compile and test some new minetest packages if you need help with testing.

**Comment by NathanSalapat** [comment] 2020-01-01 14:24
![screenshot_20200101_081828](https://user-images.githubusercontent.com/8930456/71642332-578be780-2c6f-11ea-8964-374ba1fa23b8.png)
I play on a 2K monitor and have never seen the chest problem.
Even if I span Minetest across both of my desktop's I don't have the problem, which makes me think you have something funky going on that's not standard behavior
![screenshot_20200101_081935](https://user-images.githubusercontent.com/8930456/71642347-8609c280-2c6f-11ea-9260-2b6ae3bf6859.png)
The hotbar and hud elements do stay the same size regardless of the screen size/resolution, but that can already be changed by going to settings/all settings/graphics/in-game/advanced/hud_scaling. Alternatively you can just search HUD and change the hud_scaling factor from one to 2, or larger if desired.
What are the mods you are using? and what version of Minetest?

**Comment by SmallJoker** [comment] 2020-01-01 15:45
Duplicate of #7603

Your GUI scaling factor is probably too high.

**Closed by SmallJoker** 2020-01-01 15:45 UTC
Labels: Feature request
