### ISSUE TITLE
add "on_collision" callbacks for entities

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5458] opened 2017-03-26 16:59 UTC
I propose to add two functions for entities

- on_entity_collision()
If two entities collide the callback from both entities is called with a reference to the other entity

- on_node_collision()
this callback is called every time an entity hits a new node. So if an entity doesn't moves over the surface this callback wouldn't be called. If an entity enters a new node or hits a node in front the callback is called with the pos of the node

I think this would be very useful for mods like bows and arrows or for mobs

**Comment by paramat** [comment] 2017-09-08 04:35
Author has left MT, anyone else requesting this? Close in 1 month if not.

**Comment by DS-Minetest** [comment] 2017-09-08 12:24
It would be very useful if it can be done without much lag.

**Comment by rubenwardy** [comment] 2017-09-08 12:25
this would be a nice feature, especially if done in a way that players can also use it. A few mods, eg: mesecons, currently use on_globalstep to detect if a player is stepping on a node.

**Comment by raymoo** [comment] 2017-09-08 18:47
@rubenwardy 
I think the overhead of using `on_globalstep` for that purpose is not very high, *provided* all "stepping" handlers are dispatched to by a single globalstep (ideally a central mod that allows registering these handlers, but one globalstep per mod that wants the behavior would be ok in my opinion).

**Comment by Wuzzy2** [comment] 2017-09-09 16:19
This is very important for anything dynamic. There is an almost infinite number of use cases for this, some examples were posted before.

**Comment by SmallJoker** [comment] 2017-09-10 09:52
Related issues:

- on_entity_collision()
Duplicate, requested in #3918, `on_collide` for entity

- on_node_collision()
Opposite direction, for nodes, but relies on the same code area: #247, `on_walk_over()`

**Comment by xunto** [comment] 2017-11-06 06:03
Obviously this callback should be there, I looked through some "archery" mods and all of them check collision using on_step callback, some of them even itterate over collision boxes to check collisions, while obviously this work already done in core (physical = true and collide_with_objects = true). I tried tracking speed changes with physical = true to notice collisions but it's look a little bit hacky.

**Comment by paramat** [comment] 2017-11-08 10:19
@SmallJoker is working on a bows mod that uses raycast to detect objects on the shoot line.

**Comment by MarkuBu** [comment] 2017-11-08 12:41
Well, that might work, but I think that doesn't help for many other use cases. Arrows are small objects. A raycast may work. How many rays do you want to cast if you have bigger objects?

**Comment by paramat** [comment] 2017-11-08 14:48
Yes, i was just replying to xunto's usecase.

**Comment by xunto** [comment] 2017-11-08 17:33
@paramat Hmm, maybe I should try it. Even though I've already written collision check in lua for my spellcasting mod.

**Comment by SmallJoker** [comment] 2017-11-08 19:44
@paramat Please note that raycast does not handle collisions (walkable and collision box values) and is more suitable to get a pointed thing with a direction and position given. For bigger objects, each collision box edge would have to be cast, which seems to be more hacky than simply using the `physical` attribute in combination with the velocity it had before colliding.

**Comment by rubenwardy** [comment] 2018-04-09 20:43
duplicate of #3918

**Closed by rubenwardy** 2018-04-09 20:43 UTC
Labels: @ Server / Client / Env., Feature request
