### ISSUE TITLE
how to set minetest to use proxy without crash

### ISSUE THREAD

**Issue by PowerOlive** [minetest/minetest#8490] opened 2019-04-27 09:28 UTC
i am tired of
typing
zsh/ proxychains minetest
into my terminal

**Comment by PowerOlive** [comment] 2019-04-27 09:29
i mean socks5

**Comment by PowerOlive** [comment] 2019-04-27 09:29
i've tried the curl

**Comment by ClobberXD** [comment] 2019-04-27 09:43
While not a duplicate of #8136, this discussion can be continued there.

**Comment by SmallJoker** [comment] 2019-04-27 11:49
If you're tired typing, create a starter or script for it.

**Closed by SmallJoker** 2019-04-27 11:49 UTC
