### ISSUE TITLE
[Request] luasocket

### ISSUE THREAD

**Issue by arpruss** [minetest/minetest#3301] opened 2015-10-28 14:30 UTC
Luasocket is useful for mods. For instance, my RaspberryJamMod which emulates the Raspberry PI Python API for Minecraft uses it heavily. Another mod I've seen uses it for timing. And I could imagine mods using it to pull resources from the Internet. However, luasocket requires a binary .so / .dll library to be included with the mod, and that requires mod developers to distribute multiple versions of the mod for multiple platforms. It would be a lot better if luasocket was simply included in the lua library included with Minetest (requiring the insecure environment of course), as then mods could use it without including a binary of it.

**Comment by est31** [comment] 2015-10-28 21:06
Dupe of #3103

**Closed by est31** 2015-10-28 21:06 UTC
