### ISSUE TITLE
significant FPS drop with 5.10-dev compared to 5.9.0 release

### ISSUE THREAD

**Issue by superfloh247** [minetest/minetest#15103] opened 2024-09-01 15:20 UTC
### Minetest version

```true
5.10-dev latest master as of now

Minetest 5.10.0-dev-8972c80 (OSX)
Using LuaJIT 2.1.1724512491
Built by Clang 18.1
Running on Darwin/23.5.0 arm64
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
STATIC_LOCALEDIR="minetest.app/Contents/Resources/locale"
```

### Irrlicht device

OSX

### Operating system and version

OSX 14.5

### CPU model

apple M1pro

### GPU model

apple M1pro

### Active renderer

OpenGL 2.1

### Summary

significant FPS drop, I think in areas with lots of transparent nodes / nodes with transparent holes

minetest.conf:
```
mg_name = flat
creative_mode = false
fixed_map_seed = 240780
mainmenu_last_selected_world = 14
enable_damage = false
menu_last_game = minetest
remote_port = 30000
address = wunderwelt.one
name = Flo
maintab_LAST = local
world_config_selected_mod = 162
screen_h = 916
screen_w = 1512
mute_sound = true
free_move = true
fast_move = false
pitch_move = false
sound_volume = 0
enable_fog = true
viewing_range = 400
main_menu_technical_settings = true
fps_max_unfocused = 25
mgv7_spflags = caverns,floatlands,ridges,mountains
wieldview_update_time = 2
wieldview_node_tiles = false
minimap_shape_round = true
connected_glass = true
noclip = true
node_highlighting = box
leaves_style = fancy
#enable_waving_leaves = true
enable_waving_plants = true
tone_mapping = true
enable_clouds = true
enable_3d_clouds = true
performance_tradeoffs = true
mgflat_spflags = lakes,hills,caverns
server_announce = false
enable_waving_water = true
shadow_levels = 3
enable_dynamic_shadows = true
enable_server = false
port = 30001
shadow_map_texture_size = 2048
shadow_map_max_distance = 140
shadow_map_texture_32bit = true
shadow_filters = 1
autojump = false
doubletap_jump = false
keymap_cmd_local = KEY_PERIOD
keymap_increase_viewing_range_min = KEY_PLUS
keymap_rangeselect = KEY_KEY_R
aux1_descends = false
keymap_decrease_viewing_range_min = KEY_MINUS
enable_bloom = true
enable_bloom_debug = false
inventory_items_animations = true
saturation = 1
enable_mesh_cache = true
fps_max = 60
vsync = true
#client_mapblock_limit = -1
occlusion_culler = loops
show_technical_names = true
enable_local_map_saving = false
keymap_toggle_block_bounds = KEY_F7
enable_hotbar_mouse_wheel = false
enable_auto_exposure = true
enable_vbo = true
show_advanced = true
desynchronize_mapblock_texture_animation = true
#enable_volumetric_lighting = true
client_mapblock_limit = -1
client_mesh_chunk = 4
#hud_scaling = 1.51
tooltip_append_itemname = true
enable_volumetric_lighting = true
enable_ipv6 = false
repeat_dig_time = 0.15
repeat_place_time = 0.15
translucent_liquids = true
enable_node_specular = true
enable_water_reflections = true
soft_clouds = true
enable_translucent_foliage = true
mob_chance_multiplier = 100.0
mobs_spawn_chance = 1.0
mob_log_spawn = true
```

mt 5.10-dev

![screenshot_20240901_165910](https://github.com/user-attachments/assets/10b0862d-62bb-4466-8e22-553e9920aa1e)
![screenshot_20240901_165908](https://github.com/user-attachments/assets/c650446b-7a36-46a7-8b07-6ffc00952c15)
![screenshot_20240901_165907](https://github.com/user-attachments/assets/29bfa42f-8bb2-496e-b1b1-ccd342b276ac)

same position 5.8.0 release tag

![screenshot_20240901_171136](https://github.com/user-attachments/assets/cbe5f91a-6cde-499c-83c1-919cdd76ad18)
![screenshot_20240901_171134](https://github.com/user-attachments/assets/c9ef96fa-4174-4088-8adf-7c471f5a9f3c)
![screenshot_20240901_171132](https://github.com/user-attachments/assets/841c32d7-cb2b-4429-baef-dbbb393a3c5b)

### Steps to reproduce

go into areas with transparent nodes with 5.10-dev

**Comment by SmallJoker** [comment] 2024-09-01 15:24
This appears to be a duplicate of #14993 but with different good/bad Minetest versions.

**Comment by sfan5** [comment] 2024-09-01 15:24
You seem to have somewhat different graphics settings.
Judging by the GUI scaling you're also using SDL2 in one but not the other screenshot.
Please try to narrow it down further by testing 5.9.0.

**Comment by superfloh247** [comment] 2024-09-01 15:33
5.9.0 release tag

looks OK, I updated the issue title to 5.9.0 vs. 5.10-dev

Minetest 5.9.0 (OSX)
Using LuaJIT 2.1.1724512491
Built by Clang 18.1
Running on Darwin/23.5.0 arm64
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
STATIC_LOCALEDIR="minetest.app/Contents/Resources/locale"

OpenGL 2.1 / Renderer OSX

![screenshot_20240901_173233](https://github.com/user-attachments/assets/7f8fa460-511d-4015-a5a2-d1362e6b33ae)
![screenshot_20240901_173231](https://github.com/user-attachments/assets/ae497942-6e9f-4067-94b6-9b194da24865)
![screenshot_20240901_173230](https://github.com/user-attachments/assets/36756eb3-74c8-45c3-8bc1-19814b8a700d)

**Comment by superfloh247** [comment] 2024-09-01 15:38
I already tried

`transparency_sorting_distance = 0`

but this did not help at all with 5.10-dev

**Comment by sfan5** [comment] 2024-09-01 15:43
thanks.
to be sure, the driver is `OSX` in both cases?
that narrows it down to roughly any of the commits here after Aug 11th <https://github.com/minetest/minetest/commits/master/src/client> which is not that many.

can you bisect this?

**Comment by Desour** [comment] 2024-09-01 15:45
> I already tried
> 
> `transparency_sorting_distance = 0`
> 
> but this did not help at all with 5.10-dev


Try with #15101.

**Comment by superfloh247** [comment] 2024-09-01 16:08
with #15101 and transparency_sorting_distance = 0

around 55FPS :-D 

Minetest 5.10.0-dev-5ce9cf0 (OSX)
Using LuaJIT 2.1.1724512491
Built by Clang 18.1
Running on Darwin/23.5.0 arm64
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
STATIC_LOCALEDIR="minetest.app/Contents/Resources/locale"

> to be sure, the driver is `OSX` in both cases?

yes, I build with -DUSE_SDL2=FALSE

**Comment by sfan5** [comment] 2024-09-01 16:13
:+1:
bisecting is still useful so we can find out which commit broke(?) transparency sorting performance

**Comment by superfloh247** [comment] 2024-09-01 16:16
I have no idea about he inner workings of minetest, but this one looks like it has something to do with the topic #15046

**Comment by Desour** [comment] 2024-09-01 16:19
Transparency sorting causing rendering performance issues is not new (here's the issue: #12900), but before #15046 transparency sorting was incorrectly off in most blocks if `client_mesh_chunk`>1.

**Comment by sfan5** [comment] 2024-09-02 16:17
Don't forget to bisect.

**Comment by superfloh247** [comment] 2024-09-11 17:17
#15101 fixed it and https://github.com/minetest/minetest/commit/47e4c33a505baec177d3a6a3e8e3d234b549c08d broke it again, down to 30'ish FPS

**Comment by sfan5** [comment] 2024-09-12 10:55
That doesn't make sense to me.
#15101 only takes effect with `transparency_sorting_distance = 0`
and 47e4c33a505baec177d3a6a3e8e3d234b549c08d is a pure refactor with no (intended) observable changes

**Closed** 2024-10-10 23:05 UTC
Labels: Bug, Performance, Action / change needed, @ Client rendering, Regression
