### ISSUE TITLE
/deleteblocks causes map blackouts

### ISSUE THREAD

**Issue by 0-afflatus** [minetest/minetest#3839] opened 2016-03-11 15:00 UTC
using `/deleteblocks` to repair mapgen anomalies appears to be deleting the light completely in those areas. I'll provide a screenshot if necessary, but I think this is pretty self-explanatory.
This is a major bug IMO.

**Comment by paramat** [comment] 2016-03-11 19:42
Screenshot might be useful, please include the border of the dark area too. Also which mapgen?

**Comment by 0-afflatus** [comment] 2016-03-12 12:12
mgv7
![screenshot_20160312_103248](https://cloud.githubusercontent.com/assets/7130479/13722873/85951956-e84b-11e5-8ece-d57b35148dca.png)
![screenshot_20160312_110843](https://cloud.githubusercontent.com/assets/7130479/13722878/94742a02-e84b-11e5-8357-093303dc46cd.png)
![screenshot_20160312_104434](https://cloud.githubusercontent.com/assets/7130479/13722881/a14e8ed4-e84b-11e5-88ae-c5bf0270a1cc.png)
![screenshot_20160312_103932](https://cloud.githubusercontent.com/assets/7130479/13722883/a94fbdec-e84b-11e5-8f20-abcf7460ec30.png)

**Comment by 0-afflatus** [comment] 2016-03-13 19:34
Ice ...

![screenshot_20160313_192138](https://cloud.githubusercontent.com/assets/7130479/13730823/7c587268-e952-11e5-9f44-afbca2e6243b.png)
![screenshot_20160313_193013](https://cloud.githubusercontent.com/assets/7130479/13730824/7c5baf32-e952-11e5-8840-0f4b9f270303.png)
![screenshot_20160313_193127](https://cloud.githubusercontent.com/assets/7130479/13730822/7c58284e-e952-11e5-9df2-a59b28c4f9af.png)

**Comment by paramat** [comment] 2016-03-14 03:40
Does it happen in mgv6?
Running any mods or subgames? best disable them all.

**Comment by Fixer-007** [comment] 2016-03-14 19:35
I see moretrees here :}

**Comment by paramat** [comment] 2016-03-15 07:07
Moretrees doesn't tend to cause shadows that big and over ocean. I'll check the deleteblocks code, see if it uses 'update lighting'. Please try without any mods enabled, and try in mgv6 too.

**Comment by 0-afflatus** [comment] 2016-03-18 14:47
This is proving to be really difficult to debug.

This is a mapgen bug - specific to grailtest in _multiplayer_ mode. If you take a brief glance at https://github.com/0-afflatus/grailtest and particularly https://github.com/0-afflatus/grailtest/blob/master/mods/default/mapgen.lua you'll see how difficult it would be to strip it down.

@Fixer-007 if you look at the screenshots, it's pretty obviously not caused by moretrees. As this is happening in dry treeless biomes equally. The lightbugs triggered by moretrees only occur in small patches and are easily `/mapfix`-able.

This only happens in multiplayer AFAICS - singleplayer works as expected.
In multiplayer **all** new areas (using various recent -dev versions) are generating without light. It's not just a patch it is the whole mapblock. If I do a `/deleblocks here` on an old (lit) mapblock, lightbugs are introduced. This can be fixed using `/mapfix`, but it's happening over such wide areas that it's almost impossible to make any headway (we have 5 players on the case right now)

I'm really sorry, but setting up a multiplayer server running mgv6 or any other mapgen is more work that I can handle right now - there are only so many hours in the day. From the lack of other responses, I guess that this doesn't happen in minetest_game at all. This is the best I can come up with after a solid week of investigation. I will persevere with getting some information you can work on @paramat

**Comment by paramat** [comment] 2016-03-19 13:53
Weird. Don't bother trying in mgv6 since that's complex.

**Comment by paramat** [comment] 2016-03-19 14:14
I looked through grailtest, all i can suggest is removing the 'biomelib' 'moretrees' 'plantlife' mods to see if they are the cause.

**Comment by 0-afflatus** [comment] 2016-03-20 18:23
I am working on this. So far I can report that mgv6 doesn't have this problem even with VanessaE's mods enabled. As I'm sure you're aware testing mapgen is slow and laborious, finding time for this whilst  running a server is not easy. I will test without these mods, but I'm afraid this will take a few days more ...

**Comment by paramat** [comment] 2016-03-21 04:23
Yes the overgeneration used in other mapgens seems to make lighting bugs worse.

**Comment by paramat** [comment] 2017-07-08 22:25
@0-afflatus still occuring? We have had many lighting improvements recently.

**Comment by nerzhul** [comment] 2020-04-15 09:42
can we have a confirmation on this issue ? else we may close the issue as it's 3 years old and we did some light fixes between

**Closed** 2020-07-24 01:33 UTC
Labels: @ Mapgen, Unconfirmed bug

**Comment by 0-afflatus** [comment] 2020-10-24 20:26
I've been away for 3 years, just catching up ...
I stopped using 'biomelib' 'moretrees' and 'plantlife' mods and haven't encountered lighting bugs since.
I also gave up trying to run a server or develop anything, so the above is kind of meaningless.
I seem to be working on games again.

**Comment by paramat** [comment] 2020-10-24 21:47
Thanks, i appreciate the update.
