### ISSUE TITLE
Entities stuck in walls

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5482] opened 2017-03-29 18:44 UTC
Typical usecase is blowing up few TNTs, you end up with entities stuck/immersed into walls, hardly visible, black coloured. You can still grab them, BUT you don't know what you grab and there is no text because of other bug. This is another gameplay problem for TNT users of minetest_game. Here are some examples:
![kek2](https://cloud.githubusercontent.com/assets/16494741/24470775/c2a0703e-14c8-11e7-89b8-660a13ea44b9.png) ![kek4](https://cloud.githubusercontent.com/assets/16494741/24470774/c29f51c2-14c8-11e7-9760-31fe97bac5de.png)
![kek3](https://cloud.githubusercontent.com/assets/16494741/24470776/c2a11ab6-14c8-11e7-9382-fcef5e7a4b66.png)
Promoting: https://github.com/minetest/minetest/issues/5297

**THIS IS NOT FINE**

**Comment by tenplus1** [comment] 2017-03-30 07:12
My fork of builtin mod stops this by squeezing trapped items into the closest available airblock:  github.com/tenplus1/builtin_item

**Comment by dsohler** [comment] 2017-03-31 23:40
Why is this a bug, but the other issue basing on the exact same problem is a low-priority suggestion?

#5483

**Comment by paramat** [comment] 2017-04-01 02:56
It's not identical, here entities may be cimpletely inside walls and not detectable, which is a problem, the other issue the entities are visible and easily picked up by digging the node around them.

**Comment by paramat** [comment] 2017-04-01 03:05
Related https://github.com/minetest/minetest_game/issues/483
See last comment https://github.com/minetest/minetest_game/issues/483#issuecomment-187564783

**Comment by Fixer-007** [comment] 2017-04-01 10:20
>are these objects ever deep inside walls?

This is maximum deepness they go I think.

**Comment by C1ffisme** [comment] 2017-04-06 03:00
I believe Minecraft fixes this purely by moving the dropped item out of blocks. It first checks in the four cardinal directions, and if there is a block in the way of each of those, it just moves upwards until it isn't in a block or can pop out in a cardinal direction.

**Comment by DTA7** [comment] 2017-09-17 20:03
For TNT the problem is that the collision detection is simply turned off for lying items on non-slippery nodes, as mentioned in #5973:
https://github.com/minetest/minetest/blob/27144b471678b30156ad3383fb8d26a5bd9b66cb/builtin/game/item_entity.lua#L151
https://github.com/minetest/minetest/blob/27144b471678b30156ad3383fb8d26a5bd9b66cb/builtin/game/item_entity.lua#L158-L159
If I set
`obj:set_properties({physical = true})`
in the TNT mod (which I think simply changes the velocity and not the item entity position), this glitch doesn't seem to occur anymore.
It also does works to test for
`vel.x ~= 0 and vel.y ~= 0 and vel.z ~=0`
instead of only `vel.y`.

**Comment by SmallJoker** [comment] 2020-01-11 17:41
Fixed by #8885

There are still some (literal) edge cases where it doesn't work but for now it's good enough.

**Closed by SmallJoker** 2020-01-11 17:41 UTC
Labels: Bug, Request / Suggestion
