### ISSUE TITLE
Can't sneak dig on android

### ISSUE THREAD

**Issue by zing269** [minetest/minetest#8022] opened 2018-12-27 13:30 UTC
##### Issue type
 - Bug report
 
##### Minetest version
```
Stu's android build b8b33a6
```

##### OS / Hardware
Operating system: android 4.4.4
CPU: intel atom

##### Summary
Tried to use bell07's woodcutting mod which requires you to hold sneak while cutting the first tree node. With android the dig action never happens while holding sneak.

**Comment by stujones11** [comment] 2018-12-27 16:36
I can confirm that is impossible to dig while pressing sneak or any other 'repeat' key for that matter. This would appear to be by design.
https://github.com/minetest/minetest/blob/f12d374956c6227a073fc955c398757f9a7166bd/src/gui/touchscreengui.cpp#L1194-L1196
This code was originally introduced by sapier here: 083d19b3fc8f60468e124c801296c13b66c41abc It seems that the intention was to prevent accidental digging while moving around, however, many users have complained about this limitation, too. Either way, I think this was the wrong way to fix this.

**Comment by zing269** [comment] 2018-12-28 01:37
It works fine for me.

I didn't have any issues with digging while moving at normal speed. Of course you are moving slowly while sneaking and you do linger on a node long enough to trigger the dig action. I'd say go with options 2 or 3.

**Comment by stujones11** [comment] 2018-12-28 16:02
> It works fine for me.

I don't have any problems with accidental digging (while moving) but clearly the author had reason to add this at the time. Option 2 is a bit of a hack really because 'sneak' can also be downward movement.

I would personally favour a combination of 1 & 3, that is we include an option but have digging while moving enabled by default.

**Comment by stujones11** [comment] 2018-12-29 20:57
> Actually I can't dig while moving even with that code removed

I is usually not possible to actually dig anything since the 'touch target' is constantly moving, however, it is still possible to trigger the dig animation sequence and also protection violations if this happens in a protected area.

Also bear in mind that left-click is also 'punch' for players and other game entities. A common complaint is being unable to defend against mobs while moving, this a clear disadvantage for mobile players in a PVE survival game.

**Comment by paramat** [comment] 2018-12-29 22:08
I think just remove the code, no option for now, can add one later if absolutely necessary but there doesn't seem much need yet and extra settings need a good reason.
Because 5.0.0 is meant to sort out Android i think this should be merged for 5.0.0, i will +1 it.

**Comment by zing269** [comment] 2018-12-29 22:10
The behavior seems to be more complex than I first thought. If I start moving first and then touch the screen to move the view point then the digging action does not happen as long as the second finger remains touching the screen even if I stop moving or if I lift the joystick finger. The reverse always digs.

**Comment by paramat** [comment] 2018-12-29 22:12
> The reverse always digs

Can you clarify? What situation causes an unintended dig?

**Comment by paramat** [comment] 2018-12-29 22:19
Found discussion in logs http://irc.minetest.net/minetest-dev/2015-01-05#i_4095296 onwards.

**Comment by zing269** [comment] 2018-12-29 23:09
>Can you clarify? What situation causes an unintended dig?

I was wrong, the order of the touch doesn't matter, it seems to be related to turning. As long as you turn a bit when you first start moving or are turning before you start to move then the digging doesn't happen. If you only move in a straight line then you will dig and won't be able to turn.

**Comment by stujones11** [comment] 2018-12-30 14:47
@paramat thanks for finding the original discussion, I can vaguely remember this now. Had it been anyone else I'd have a tendency to agree with you but since this was added on the request of celeron55, I would be reluctant to simply remove it without leaving an option.

However, if you are happy to this, it is just a matter of nuking those few lines I highlighted here https://github.com/minetest/minetest/issues/8022#issuecomment-450186373

**Comment by paramat** [comment] 2018-12-31 00:04
Well =) c55 can be wrong, and we've confirmed this isn't a problem and is the wrong approach.
So, i'll make a PR.

**Comment by paramat** [comment] 2018-12-31 09:31
Actually, since the issue depends on device, i'll wait for more testing, a setting for this may be necessary.

**Comment by jastevenson303** [comment] 2018-12-31 12:57
Is it related to "multitouch" or whatever it's called?  On some cheaper, or older, devices, you can only press in one or two spots at a time.  I noticed on newer or more capable devices, one can touch three or more spots at once.

**Comment by stujones11** [comment] 2018-12-31 16:48
This has never really been an issue for me, even on my oldest device so I suspect it more down to understanding and familiarity with the controls. If you leave your finger in the same spot for too long you _will_ start digging, that's just how it works.

**Comment by wwar-XeStro** [comment] 2022-02-13 20:52
Digging/hitting is what makes the settings terrible, the user can not use sneak or sprint or move the camera while digging or hitting which makes it hard to control... can check #11404 for further issues.

**Comment by Zughy** [comment] 2022-06-19 23:47
Duplikcate of #11404, I'll keep the other open as more generic

**Closed by Zughy** 2022-06-19 23:47 UTC
Labels: Bug, Android, Request / Suggestion, @ Client / Controls / Input
