### ISSUE TITLE
Android: bad GUI scalling / poor use of available touch screen

### ISSUE THREAD

**Issue by LikeGuyS** [minetest/minetest#12227] opened 2022-04-25 17:37 UTC
## Problem & Solution

Dialogs are a real mess on touch devices. 
![SmartSelect_20220425-202526_Video Player](https://user-images.githubusercontent.com/104377424/165141434-52996199-8c96-40a2-8d2a-83ba504a6272.jpg)
As you see in this picture, the dialog takes 60% of the screen. It should be taking at-least 90% of the screen. Why? I myself have a 5inch-ish screen and have middle sized fingers and still couldn't manage to accurately hit buttons. Most people have a phone that is 10-20% narrower than mine and surely have bigger fingers.

I mean.. look at [this video..](https://user-images.githubusercontent.com/104377424/165142334-ab4f7e18-c405-44f4-bc90-36dcbec0d400.mp4) in the first few seconds, you can see the player hitting the "+ Controls" button multiple times, expecting it to open just after one hit. Imagine the frustration. Then, the player discovers that hitting "Search" opens the menu of the select option (+ Controls), then the player tries to close the menu by hitting 'search' again but fails. Then, he tries to scroll down to see the settings inside +Controls but the slider is too quick it almost takes him to the bottom of the dialog. By now you might of seen just how counter-intuitive the dialogs are in the game.

**Comment by rubenwardy** [comment] 2022-05-08 23:54
Issue A:  Duplicate of #10110

Issue B: Valid new issue, should be titled smth like "Android: Improve show tooltips gesture"

Issue C: surely an issue for this exists

**Comment by rubenwardy** [comment] 2022-05-09 00:01
Ok, edited issue to just be about GUI scaling

What was issue A is now tracked by #10110 and issue B is #12298

**Comment by Zughy** [comment] 2023-04-14 12:24
issue C is #10554

**Closed by Zughy** 2023-04-14 12:24 UTC
Labels: Android, Request / Suggestion, @ Client / Controls / Input, Formspec, UI/UX
