### ISSUE TITLE
Android - Difficulty without connected physical keyboard 

### ISSUE THREAD

**Issue by Raj9039852537** [minetest/minetest#12598] opened 2022-07-27 15:54 UTC
##### Minetest version

```
5.5.1
```

##### OS / Hardware

Operating system:android
CPU:arm8

GPU model:
OpenGL version:

##### Steps to reproduce

On android phones keyboard only pop up when click on text field and if there is no physical keyboard connected it is impossible to even open inventory. (Crafting screen)

it would be nice to add some kind of on screen element that would help in keyboard popup.

**Comment by rubenwardy** [comment] 2022-07-27 15:57
To open the crafting screen, you need to top the onscreen button. Click the triple dots on the left, and then click the grid icon (3x3 boxes)

**Comment by Raj9039852537** [comment] 2022-07-27 16:04
Found the button just now in screenshot. It is hidden below the notch.
Can i change its position somehow

**Comment by rubenwardy** [comment] 2022-07-27 16:05
Unfortunately, there's no way to do that currently

That makes this issue a duplicate of #10110

**Closed by rubenwardy** 2022-07-27 16:05 UTC
Labels: Unconfirmed bug, Duplicate, Possible close

**Comment by Unacceptium** [comment] 2023-10-28 07:29
#13229 would 100% solve this
