### ISSUE TITLE
hmm... the logo in the menus could use some work...

### ISSUE THREAD

**Issue by SaiPanneerselvam** [minetest/minetest#15428] opened 2024-11-13 00:49 UTC
Ah, new version of minete~ sorry, LUANTI! wow, 5.10.0 is released! 
But wait. What is _that_?
![image](https://github.com/user-attachments/assets/6c58fcf8-dc4e-4029-820b-44db46c3a965)
"Luonti" Why does the luanti logo look like the editor only had 5 seconds to type it?

**Comment by Sneglium** [comment] 2024-11-13 01:10
Probably because they did, I think it's just text in a free font that was then saved as an image. Minetest has never had good branding and you shouldn't expect Luanti to, either

**Comment by SaiPanneerselvam** [comment] 2024-11-13 01:13
yeah, but i didnt expect it to be THIS bad. If minetest/luanti doesnt change, I want to make a logo (LOL)
(Imagine if this was the permanent logo)

**Comment by SwissalpS** [comment] 2024-11-13 01:24
awaiting your PR with a professional and breathtaking permanent logo.

**Comment by appgurueu** [comment] 2024-11-13 01:42
> The luanti logo SUX. :(

Oh no. Anyways.

>  "Luonti" Why does the luanti logo look like the editor only had 5 seconds to type it?

It does not. In fact there was some bikeshedding about this, but at the end of the day it was still mainly influenced by people with a programming background. Our logo is *supposed* to be bland to an extent, by the way; we're a platform, not a game.

> If minetest/luanti doesnt change, I want to make a logo (LOL)

It is not set in stone. It is just waiting for someone in the community with graphic design experience to make a proper banner. From what I heard there would be someone willing to volunteer, but they haven't found time yet. If you want to volunteer yourself, sure, have a go at it.

**Comment by SaiPanneerselvam** [comment] 2024-11-13 01:44
Nice! I'll try and see if  I have time.

**Comment by SaiPanneerselvam** [comment] 2024-11-13 13:14
Made the PR! #15430

**Comment by nininik0** [comment] 2024-11-14 04:57
Wait so I can make luanti be stone if I have time?

**Comment by Wuzzy2** [comment] 2024-11-14 13:13
I completely agree the current text logo is very disappointing and should be replaced. This issue is completely valid.

My criticisms of the current text logo:

* It looks much worse than the old Minetest stone logo
* It looks rushed (just a font with a shadow)
* Somewhat inconsistent kerning at the "t" and "i"
* Poor font choice. This font was probably made for very small resolutions because it uses a low pixel count. You can clearly see this at the letters "a" and "u" which have bad legibility. The "a" looks almost like an "o". This is not a good choice for a text logo which is displayed at a large size
* It looks generic and boring. The text logo is completely forgettable
* It fails to draw any connection to a voxel game engine. The logo just doesn’t "fit" in my opinion

And no, I don't buy the "it's supposed to look bland" argument. That's just an excuse. There are *many* flaws with the current text logo. Just because Luanti wants to be neutral doesn't mean it should be stripped of *any* graphical design.

I admit, I'm not a pro artist, but I believe I know at least a *little* bit to recognize *some* problems.

I think the old Minetest stone logo was clearly superior (although not perfect). But Luanti doesn't want stone because it wants to distance itself from Minetest Game. This is a legitimate concern but unfortunately has led to a bad logo (for now).

I don’t have any suggestions or requests for a *new* text logo because I honestly don’t even have an idea. I leave this one to more skilled artists.

@nininik0: No. Stone logo was rejected. I posted one myself, based on Minetest Game text logo. Luanti wants to distance itself from Minetest Game as far as possible.

----

PS: Please stop telling people "Trollolo draw a better one" when those people have zero art skills. This isn't helping.

**Comment by appgurueu** [comment] 2024-11-14 16:59
> This issue is completely valid.

In case it wasn't clear, I agree that it's valid (though I took an issue with the initial tone, but that has since been resolved).

(That said, as a layperson I personally don't think that the current logo is that bad, it looks okay too me, though I agree that the "a" looking like an "o" is a bit problematic. I do hope we get a better one, because it could be a lot better than just okay.)

> And no, I don't buy the "it's supposed to look bland" argument. That's just an excuse.

It wasn't intended that way. "Neutral" would have been a better choice of words. We can't lean too much into any particular game's style is what I'm trying to say (especially since they offered to try themselves at making a new banner). This should be a banner for voxel games more abstractly, which I imagine to be a bit hard to capture while still making it appealing.

> I leave this one to more skilled artists.

I agree 100%

> PS: Please stop telling people "Trollolo draw a better one" when those people have zero art skills. This isn't helping.

I suggested they try themselves because I genuinely had no idea what their art skills would be like. There are plenty of talented people on the internet, professionals and experienced hobbyists alike.
They at least seemed to think that they could produce a better banner, so it seemed worth giving them a shot. I did not expect it to turn out (subjectively) worse, but that isn't much of a problem tbh: We don't have to go with their suggestion.

**Comment by SmallJoker** [comment] 2024-11-14 17:16
Please either open a forum post to propose and judge logo designs - or convert one of the issues here into a place to submit designs and vote for favourites. If the current logo happens to win, we would at least have a solid basis to close change requests.

Please keep in mind that any proposed logo should be CC-BY-SA or more permissive. CC-NC, CC-ND or missing licenses are not acceptable.

**Comment by SaiPanneerselvam** [comment] 2024-11-19 13:35
I also agree that this existing logo is **too** bland. If Luanti wants to 'live up' to minetest in any way, it shouldn't look like a random person made this game in 5 days and was in a rush to release it.
Here is a logo wsor worked on. It is licensed.
![image](https://github.com/user-attachments/assets/ed185739-48ee-46d5-9816-9866118034ac)
Here is some message saying it is licensed:
![image](https://github.com/user-attachments/assets/13f6e234-f1ec-4557-ae9b-d762dfe40daf)

#### Personal Opinion:
1. I didn't even expect that the name would actually be changed
2. From what I have seen, I don't see that **anyone** actually asked for the word "Luanti" (correct me if i am wrong)
3. I thought Minetest was fine and thriving before it got changed to Luanti
4.

**Comment by SaiPanneerselvam** [comment] 2024-12-17 01:24
Hello?  (issue might be STALE....)

**Comment by nininik0** [comment] 2024-12-17 16:25
Wow, the issue is already quite moldy. I got an idea, why not make luanti logo in the colors of the menu or server icons?

**Comment by siliconsniffer** [comment] 2024-12-20 09:47
I really like the logo suggested above but I doubt that it will look good in the current main menu as the sky as the background might be too bright. As I am not 100% certain though, maybe Sumi could put it in there and send a screenshot?

**Comment by SaiPanneerselvam** [comment] 2024-12-20 23:26
![image](https://github.com/user-attachments/assets/46b312ff-2466-4631-9804-2f0f0bccc3ae)
This is what SUMI said. (harsh answer, if u ask me)

**Comment by appgurueu** [comment] 2024-12-23 15:15
Closing this in favor of the more focused #15590.

**Closed by appgurueu** 2024-12-23 15:15 UTC
Labels: @ Client / Audiovisuals, Duplicate, Feature request, @ Mainmenu, UI/UX, @ Meta
