### ISSUE TITLE
Add ability to rebind gamepads

### ISSUE THREAD

**Issue by alrito28** [minetest/minetest#14496] opened 2024-03-26 21:11 UTC
Hello,

I don't know how to program, but I'd like to propose two drawings of what could be the interface for adjusting a joystick. When a peripheral is connected, it would be automatically detected and adjusted.
[DrawGamepadMinetest.pdf](https://github.com/minetest/minetest.github.io/files/14764707/DrawGamepadMinetest.pdf)

**Comment by rubenwardy** [comment] 2024-03-26 21:13
Hi, thanks the suggestion! The design is very helpful

This is a duplicate of this issue however: #4153

**Closed by rubenwardy** 2024-03-26 21:13 UTC

**Comment by alrito28** [comment] 2024-05-09 20:13
Hi,

I have downloaded the development version “minetest 5.9.0-dev”. I don't want to put pressure on you, but did you take note of my drawing? :)
