### ISSUE TITLE
Settings translations for mods and games

### ISSUE THREAD

**Issue by EGYT5453** [minetest/minetest#13925] opened 2023-10-26 11:14 UTC
### Problem

I noticed that there seems to be no way to translate game settings ("Content: Games".) The only setting that is translated is "Creative mode".

![Screenshot_20231026_125703](https://github.com/minetest/minetest/assets/113429882/23e8b9ef-5089-46fe-b59c-805ba04bc7a9)

Is it possible to add the option to translate the settings?

### Solutions

The .po / .mo / .tr file that is included in the games?

![Screenshot_20231026_134144](https://github.com/minetest/minetest/assets/113429882/f585c8f6-0390-4461-8863-0b46951d4174)

(concept)

### Alternatives

Do nothing (not the best alternative)

### Additional context

I plan to make video(s) in Ukrainian about FLOSS games, including Minetest. But the Ukrainian translation of MTG is questionable at least (see https://github.com/minetest/minetest_game/issues/3063), and the Ukrainian translation of Minetest is half missing (743 strings out of 1355, 54%)!
It's bad when there is no translation, but it's even worse when the translation is bad, so I decided to help with the translation into Ukrainian.

**Comment by grorp** [comment] 2023-11-01 20:22
Duplicate of #9070.

**Closed by grorp** 2023-11-01 20:22 UTC
Labels: @ Script API, Feature request, @ Translation
