### ISSUE TITLE
The image will cover on the last image, and keep a strange image on the background

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10242] opened 2020-07-30 11:22 UTC
##### Minetest version

```
Minetest 5.3.0 (Windows)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Windows 10
CPU:Intel(R) Core(TM) i7-6500 CPU @ 2.50GHz
2.60GHz

GPU model: Intel(R) HD Graphics 520
OpenGL version: 4.4.0

##### Summary
The image will cover on the last image, and keep a strange image on the background.

##### Steps to reproduce
I Don't Know

**Comment by Emojigit** [comment] 2020-07-30 11:24
https://ibb.co/N9XrFsp

**Comment by sfan5** [comment] 2020-07-30 12:13
sounds like a duplicate of #9008, which is a bug in Intel drivers

**Closed** 2020-07-31 11:25 UTC
Labels: Unconfirmed bug
