### ISSUE TITLE
Custom formspec in on_joinplayer() callback overrides respawn formspec

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#6251] opened 2017-08-15 18:21 UTC
When players die for some reason, leave the game without respawning and next time join the server again and the server is configured to display a formspec on_joinplayer() then the respawn formspec is gone until the players die again.

This behavior causes the players to THINK that they are alive ingame when in reality they're still dead and get no message about it.

The debug.txt spams "anticheat: [playername] tried to interact while dead;ignoring"

Setting the player HP on_joinplayer() fixes this but the engine should properly handle it instead.

**Comment by nerzhul** [comment] 2017-08-15 18:25
send death formspec when hp is zero sounds to be the bugfix

**Comment by rubenwardy** [comment] 2022-07-15 00:19
duplicate of #11523

closing as that one has more info

**Closed by rubenwardy** 2022-07-15 00:19 UTC
Labels: Bug, @ Client / Audiovisuals, Formspec, UI/UX
