### ISSUE TITLE
LevelDB crashes with recent MinGW-w64

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#4510] opened 2016-09-08 23:33 UTC
debug.txt empty
test on Windows 10
VS build work

@sfan5, please, confirm?

**Comment by sfan5** [comment] 2016-09-10 08:38
tested 403dada85a1e75859573a26ed54a72caa693da91 on windows 8.1 and works

Windows 10 specific issue?

**Comment by MoNTE48** [comment] 2016-09-10 20:16
@sfan5 Please, send me your build.

**Comment by sfan5** [comment] 2016-09-10 22:00
It's this one: 

https://minetest.kitsunemimi.pw/builds/win64/minetest-0.4.14-403dada-win64.7z

**Comment by MoNTE48** [comment] 2016-09-10 22:33
@sfan5 ok, mystic. Your build work with my leveldb worlds, but... I format my SSD, install Ubuntu 15.10,
sudo su -
apt update && apt upgrade && apt install git mingw-w64 build-essential libirrlicht-dev cmake libbz2-dev libpng-dev libjpeg-dev libxxf86vm-dev libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev libgmp-dev libjsoncpp-dev 
clone master minetest, cd to buildbot folder and start ./buildwin64.sh here
Next, i copy libstdc++-6 and libgcc_s_seh-1 dll's, create leveldb world, start game on Win10 x64, open leveldb world and get game crash.
In my debug.txt

-------------
  Separator
-------------

**Comment by sfan5** [comment] 2016-09-11 09:54
Seems to be caused by differing versions of mingw/gcc, I use my own MinGW-W64 (gcc version 4.8.1).

**Comment by MoNTE48** [comment] 2016-09-11 10:06
@sfan5, I found the problem. I copied leveldb dll from your build and put in my. Now everything works fine.

**Comment by MoNTE48** [comment] 2016-09-11 13:43
Lol, @sfan5. Leveldb dll on your server is broken! This is not my problem

**Comment by sfan5** [comment] 2016-09-11 15:39
My builds use the exact same leveldb as the on my server.

**Comment by MoNTE48** [comment] 2016-09-11 15:46
Hmm, no. dll on server is 660 kb, your dll - a few MB.




воскресенье, 11 сентября 2016 г., 18:39 +0300 от sfan5  <notifications@github.com>:

**Comment by sfan5** [comment] 2016-09-11 15:57
No.

The DLL on the server is 660 KB, the DLL in the build is 306 KB.
The size difference is caused by stripping the DLL.

**Comment by MoNTE48** [comment] 2016-09-11 20:20
@sfan5 i download this https://github.com/bygreencn/levelDB-MinGW-Python-0193/blob/master/leveldb-0.193/leveldb.dll , rename to libleveldb.dll and put in my build. And leveldb working!!!

**Comment by MoNTE48** [comment] 2016-09-13 15:39
@sfan5 The problem is not solved yet, can you open issue?

**Comment by sfan5** [comment] 2016-09-21 16:39
Fixed now that I've upgraded leveldb?

**Comment by MoNTE48** [comment] 2016-09-21 21:12
No, it did not help. Perhaps I should install some additional dependency or I use an incompatible version of MinGW-w64?

**Comment by SmallJoker** [comment] 2018-04-04 13:53
@MoNTE48 After 1.5 years, is this still an issue?

**Comment by paramat** [comment] 2018-10-09 04:19
@MoNTE48 @sfan5 close issue?

**Closed** 2018-10-09 07:52 UTC
Labels: @ Build, Possible close, Unconfirmed bug, Windows
