### ISSUE TITLE
Idea: add 'ropes' 

### ISSUE THREAD

**Issue by D00Med** [minetest/minetest#5722] opened 2017-05-07 22:16 UTC
It would be useful if textured ropes/cables/cords could be created connecting 'position A' to 'position B' (or perhaps 'object A' to 'object B'), similar to how they do in a certain other game. The effect would stay in place if either object moved, for example: a leash between a mob and a player.

**Comment by tobyplowy** [comment] 2017-05-07 22:21
This is a nice feature for ropes and for a fishing line :)

Also @Wuzzy2 will need this for his subgame

**Comment by C1ffisme** [comment] 2017-05-08 01:55
Would this be displayed in the world, on the player's GUI, or both? (Actually, now that I think about it, displaying from two locations in the world would probably save time.)

Also, I feel like pointing out that this could make a Minetest version of [Immersive Engineering](https://mods.curse.com/mc-mods/minecraft/231951-immersive-engineering#t1:description) a reality.

(The Curse page doesn't have any screenshots, You might have to look somewhere else to find those.)

**Comment by DS-Minetest** [comment] 2017-05-08 13:24
(Laser beams would also need this.)

**Comment by raymoo** [comment] 2017-05-08 21:40
Related? #3693

**Comment by raymoo** [comment] 2017-05-08 21:41
Also I think Immersive Engineering should already be possible, since (as far as I can tell) the cables don't move around. You could draw a rope as an entity and rotate it so that its endpoints are at the cable attachments.

**Comment by C1ffisme** [comment] 2017-05-09 02:27
@raymoo You might have to figure out how to draw the rope as an entity in the first place, though. Especially with different lengths, which means less or more bend in the cable.

**Comment by raymoo** [comment] 2017-05-09 04:33
The screenshots I've seen of IE suggest that they ignore that and just scale the cables so that the ends are in the right place. This does have the side effect of causing more rope = less bend, but this doesn't require a specific feature and might be unrealistic for linger lengths. Anyway making such accurate ropes isn't necessary to create a mod that largely feels like IE. Bendy ropes is not that important for the mod, and I wouldn't consider it a deal breaker if I was writing an IE-like.

More important is being able to make multi-node machines, which I feel is possible to do already in modspace.

**Comment by bendeutsch** [comment] 2017-05-09 04:54
> (Laser beams would also need this.)

And bolts of lightning. Just add a "jaggedy" draw type !-)

**Comment by nerzhul** [comment] 2017-05-09 09:51
i think it's more a minetest_game issue than minetest no, @paramat ?

**Comment by rubenwardy** [comment] 2017-05-09 11:27
No, this is an engine issue. It's about the ability to draw cables without relying on hacks

**Comment by tobyplowy** [comment] 2017-05-09 11:37
@rubenwardy correct

**Comment by raymoo** [comment] 2017-05-09 14:33
There's also no hack that will constrain a rope to be drawn between two entities if the entities move.

**Comment by D00Med** [comment] 2017-05-09 20:56
Using an entity isn't particularly good, because they can be cleared and have a lot of un-necessary properties.

**Comment by nerzhul** [comment] 2017-05-09 21:44
CSM is for modding, i don't think a rope is a client side mod, it's just a visual client side

**Comment by raymoo** [comment] 2017-05-09 22:28
I mean that you could hack in a rope with visual prediction using client side entities

**Comment by paramat** [comment] 2017-05-10 01:15
Yes i misunderstood at first, this is for dynamic ropes strung between moving objects, like a player having an animal on a leash.

**Comment by D00Med** [comment] 2017-05-10 01:44
Yes, I will try to make it more clear

**Comment by tobyplowy** [comment] 2017-06-26 15:09
is this going to be added?
its needed for farlands

**Comment by LunaSquee** [comment] 2018-05-16 10:28
I would also really love this feature

**Comment by Ferk** [comment] 2018-05-16 12:26
It's not very clear how this would work, though.
Is it really just a visual effect? What happens when the 2 objects get further apart?

Would both objects be forced to stay within distance? 
- If they don't... does the rope simply expand infinitely or would it just disappear removing the effect as if it was broken?
- If they do.. can one of them drag the other? can any of them drag the other or is it asymmetrical?

I think this is more complex than it might seem.

**Comment by paramat** [comment] 2018-09-03 10:14
1 year bump for core dev opinons.

**Comment by Ezhh** [comment] 2018-09-04 23:35
I'd love to see this added.

**Comment by paramat** [comment] 2018-09-05 04:51
I consider you core dev :)

**Comment by rubenwardy** [comment] 2021-01-28 20:14
Duplicate of #10593 (which has a bounty)

**Closed by rubenwardy** 2021-01-28 20:14 UTC
Labels: @ Client / Audiovisuals, @ Script API, Feature request
