### ISSUE TITLE
hud_set_hotbar_itemcount() in Minetest Game produces graphics glitch

### ISSUE THREAD

**Issue by yamanq** [minetest/minetest#2923] opened 2015-07-17 18:46 UTC
To reproduce this issue:
1. Create a mod with files init.lua and depends.txt
2. "default" for depends.txt
3. For init.lua, use:
minetest.override_item("default:dirt", {
	on_use = function(itemstack, user, pointed_thing)
		user:hud_set_hotbar_itemcount(5)
	end
})
4. New game (Minetest Game) + enable mod
5. Left-Click with dirt in hand
6. Graphics Glitch

Example:

Before Left-Click
![screenshot_20150717_144243](https://cloud.githubusercontent.com/assets/8166212/8754581/803ca43a-2c92-11e5-8364-7523ff3916de.png)

After Left-Click
![screenshot_20150717_144246](https://cloud.githubusercontent.com/assets/8166212/8754585/8d373e52-2c92-11e5-8b99-0e69317aa589.png)

**Comment by TeTpaAka** [comment] 2015-07-17 19:09
This is expected behaviour. If you want to change the itemcount of the hotbar you have to give it a new image. This image is provided by minetest_game and only fits for the default amount of items.

**Comment by est31** [comment] 2015-07-17 19:22
Agreed. Adding a generic method to manage the images more generically (e.g. by supplying an image for a single slot and drawing it multiple times) would be great, but this is not what the issue is about, closing.

**Closed by est31** 2015-07-17 19:22 UTC
