### ISSUE TITLE
The OLD behavior for policy CMP0025 will be removed from a future version of CMake.

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10931] opened 2021-02-07 23:41 UTC
##### Minetest version

```
5.4.0-dev-857dbcd57
```

##### OS / Hardware

Operating system: Linux Lubuntu 20.04 LTS
CPU: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz

##### Summary
```
$ cmake . -DRUN_IN_PLACE=1 
CMake Deprecation Warning at CMakeLists.txt:3 (cmake_policy):
  The OLD behavior for policy CMP0025 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- *** Will build version 5.4.0-dev ***
-- Using GMP provided by system.
-- Using bundled JSONCPP library.
-- Found LuaJIT: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so (found version "") 
-- Using LuaJIT provided by system.
-- cURL support enabled.
-- GetText enabled; locales found: ar;be;bg;ca;cs;da;de;dv;el;eo;es;et;eu;fi;fr;gd;gl;he;hi;hu;id;it;ja;jbo;kk;kn;ko;ky;lt;lv;ms;ms_Arab;nb;nl;nn;pl;pt;pt_BR;ro;ru;sk;sl;sr_Cyrl;sr_Latn;sv;sw;th;tr;uk;vi;zh_CN;zh_TW
-- Sound enabled.
-- Freetype enabled.
-- ncurses console enabled.
-- Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY PostgreSQL_INCLUDE_DIR PostgreSQL_TYPE_INCLUDE_DIR) 
-- PostgreSQL not found!
-- LevelDB not found!
-- Redis not found!
-- Prometheus client disabled.
-- SpatialIndex not found!
-- Locale blacklist applied; Locales used: be;bg;ca;cs;da;de;dv;el;eo;es;et;eu;fi;fr;gd;gl;hi;hu;id;it;ja;jbo;kk;kn;ko;lt;lv;ms;nb;nl;nn;pl;pt;pt_BR;ro;ru;sk;sl;sr_Cyrl;sr_Latn;sv;sw;tr;uk;vi;zh_CN;zh_TW
-- Performing Test IS_AARCH64
-- Performing Test IS_AARCH64 - Failed
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/username/minetest
```

**Comment by sfan5** [comment] 2021-02-08 09:23
duplicate of #10889

**Closed by sfan5** 2021-02-08 09:23 UTC
Labels: Unconfirmed bug
