### ISSUE TITLE
Player gets detached from object when leaving server

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#3836] opened 2016-03-10 20:18 UTC
I am not sure if this is a Minetest Game or Minetest issue, but I post it here because I think this is an engine problem (correct me if I'm wrong).

In Minetest Game, if you sit on a boat, then disconnect, then reconnect again, you spawn detached from the boat. I have seen similar behaviour in `carts` by PilzAdam.

**Comment by stujones11** [comment] 2016-03-10 20:26
This has been reported #3681

**Comment by est31** [comment] 2016-03-10 21:48
Not quite, its a different bug, no?

**Comment by Wuzzy2** [comment] 2016-03-11 01:03
Uh, oh. I think stujones11 just opened a huge can of worms here …
It seems attached entities are just messed up as soon as it involves players who have the audacity to leave the server while being attached. ;-)
The real question is, what *should* Minetest do?
If you keep the object but detach the player, it becomes available for other players to attach to while the 1st player is gone.
If we want to attach the player again when reconnecting, does this also mean the player may spawn in a different position if the entity has moved?
Questions over questions …
I am sure there are probably other questions which need to be answered.
And I can't quite think of a sane solution to all this right now. :-(

One possible idea which does not sound too crazy to me would be to remove both player AND the attaching entity. For simple vehicles like a boat, this makes sense since we might consider the boat to be “owned”. If the player joins again, simply add both entity and player—correctly attached, of course.
Then again, this raises the question what to do with vehicles with multiple players in it? :-/

Maybe Minetest needs to handle attached entities entirely differently

**Comment by tenplus1** [comment] 2016-03-11 08:00
If a player leaves the server then detaching them from a vehicle is the right choice, leaving it available to anyone else to use...  If the player is so concerned with their vehicle then they can detach manually and pick it up before signing off.

**Comment by paramat** [comment] 2016-03-11 08:06
Seems correct behaviour to me.

**Comment by 0-afflatus** [comment] 2016-03-15 00:12
I'm with tenplus1 on this. I can't see it as a bug.
I can understand why you don't like this behaviour @Wuzzy2 but as you say - can of worms.

**Comment by wilkgr76** [comment] 2016-04-12 11:02
@Wuzzy2 And if another player removed the entity that they were riding...

**Comment by paramat** [comment] 2016-04-12 23:05
This seems a nightmare of issues, it's best we leave behaviour as it is, please can we close this?

**Comment by wilkgr76** [comment] 2016-04-12 23:06
@paramat lol, yes

**Comment by Wuzzy2** [comment] 2016-04-13 01:23
Sigh. Alright, alright. Then just officially declare it as intentional behaviour. But I ask you to put this information at least into `lua_api.txt` or something.

**Comment by est31** [comment] 2016-04-13 13:46
No, it should stay open. Why is it a nightmare?

**Comment by paramat** [comment] 2016-04-13 22:09
See comment 5. Seems almost impossible to solve, complex and not needed.
If a player leaves a server they may never come back, why would we reserve a vehicle for such a player? We would need to track the vehicle constantly in case the player returns.
So yes it's a nightmare of complexity, even according to the author, and not needed.

**Comment by DonBatman** [comment] 2016-04-14 00:19
What would happen if the player never returned.

**Comment by paramat** [comment] 2016-04-14 01:10
I'm ok with a line added to documentation in the 'attach' section, could you make a PR for this?

**Comment by paramat** [comment] 2017-09-15 04:30
Ok i'll make a documentation PR, then i'll close this.

**Comment by paramat** [comment] 2017-09-15 05:52
Most see this as expected behaviour. Wuzzy since you're the only person who requests documentation of this you can make a PR, i will +1 it and merge it as trivial, it'll take you 5 mins. No point keeping this issue open.

**Closed by paramat** 2017-09-15 05:52 UTC
Labels: @ Documentation, @ Server / Client / Env., Not a bug, Request / Suggestion
