### ISSUE TITLE
When mining stone got cobble

### ISSUE THREAD

**Issue by Ygarr** [minetest/minetest#11340] opened 2021-06-12 07:54 UTC
##### Minetest version
5.4.1, 5.5.0 for Windows

After breaking node default:stone - got in inventory default:cobble. It can be considered as feature but not convenient. So need to choose stone in list by hand manually. 

Also solution can be to add "F" button to add material in inventory as in Minecraft without breaking node

**Comment by hlqkj** [comment] 2021-06-12 08:19
It isn't considered as a feature. It *is* a feature... A feature of `minetest_game` to be precise, so you should post your _feature request_ (not bug report!) in it's own repository: https://github.com/minetest/minetest_game.

**Comment by sfan5** [comment] 2021-06-12 09:48
duplicate of #9781

**Closed by sfan5** 2021-06-12 09:48 UTC
Labels: Unconfirmed bug
