### ISSUE TITLE
Possibility to retrieve the length of an audio file

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#14022] opened 2023-11-20 17:22 UTC
### Problem

I'm working on a sound library and I have no way to know how long a track is. I have to ask modders to manually put the value as I don't wanna work on an .ogg decoder just for that (nor I have enough knowledge to do so).  

Music Player Daemon on CDB does the same: https://notabug.org/orwell/mpd/src/master/songs.txt

### Solutions

A way to expose the length of an audio file to the API. I don't know if it should be an util function just for that or a function that returns audio files info in general

### Alternatives

See above

**Comment by Zughy** [comment] 2023-11-20 17:23
cc @Desour

**Comment by rubenwardy** [comment] 2023-11-20 18:15
This is not possible to do server side if you have support for sound packs or resource/media packs. See #11936 .

So you'd either need to ask the client, or you'd need to add APIs that allowed relative/percentage based times. Or you could scale timings - if the original sound is 60s long and the replacement is 30s, all absolute times are x0.5

**Comment by Desour** [comment] 2023-11-20 19:52
Duplicate of #12375.

If it's fine that you have to pass in a file path, as opposed to a sound name, this is doable (by adding libvorbisfile also to the server dependencies, which should be fine).

>Minetest already supports replacement sounds in `sounds/`

It's just fallback sounds, not replacement sounds.

**Closed by Desour** 2023-11-20 19:52 UTC
Labels: @ Script API, Feature request, Sounds
