### ISSUE TITLE
Minimap code and behaviour problems

### ISSUE THREAD

**Issue by est31** [minetest/minetest#2844] opened 2015-06-27 12:43 UTC
Just a list to not forget
- [x] we do busy listen inside the minimapupdate thread (_Introduced 100% CPU regression, solved by [1]_)
- [x] the update queue uses vector internally, make it list (_solved by [1]_)
- [x] position updates slow --> I tried to move the texture, without success (_Turns out to be not present on release builds, therefore ok_)
- [x] m_queue and m_blocks_cache of MinimapUpdateThread are public. Rename or make them private. (_m_queue is private with [1], m_blocks_cache with [3] and [4]_)
- [x] MinimapUpdateQueue isn't needed. We should use std::deque, and manage the mutex ourselves (doable as its private now). This can be part of a larger cleanup, including the meshupdatethread (and its own private queue), with one common superclass. _There is UpdateThread now with [2], its questionable whether its worth to unify the queues too therefore marking this as done._
- [ ] There is an older bug in minetest @VanessaE calls [main mesh thread lag](https://irc.minetest.net/minetest-dev/2015-06-27#i_4300890), which greatly affects the responsiveness of the minimap. Perhaps it should be fixed.

Points @kwolekr suggested:
- [ ] A better scanning strategy would be more performant
- [ ] Surface scanning should be done in the minimap thread, not the mesh update thread
- [x] Only the left shift key can be used to change the shape. _Sneaking doesn't work with right shift either, so acceptable_
- [ ] The buffers have constant size
- [x] Mapper keeps a pointer to the player only to update the yaw. A design like setPos() would be better 

Commits addressing issues:
[1] 420125debd3d010fcd3e7738c43f25c8f407ab63
[2] 29dda9f356042c403b3b7da1d717d32b45c9b6de
[3] b160f8dfe7e3bf8176e3f9f64dc2d9a9868d7fce
[4] 9e3e6dc5ec8ea63d65c635fcac0c80e0cd0e666d

**Comment by RealBadAngel** [comment] 2015-06-27 12:50
1) and 2) Whats so wrong with std::vector?
3) dont forget that full scan in surface mode 1 means scanning of 8,5kk of nodes, it simply has to take the time.
3) they have to be public, i will rename them.

**Comment by est31** [comment] 2015-06-27 12:55
std::vector is optimized for data structures which don't change much over time, where we read more than change the structure. As advantage over list, it allows fast random access. As disadvantage, it copies every element if you remove at the start (or if you add at the start). For a FIFO structure you either have to add or remove at the start. But we don't need random access, only the features of list. Also, iterate over the list with an iterator.

3: we need to find a texture based solution then, that smoothes out the transition phase

**Comment by est31** [comment] 2015-06-27 13:04
For 1: use JEvents, and signal() if you ad to the queue, and wait() in the for loop instead of the ms wait call, you only have to think of stopping the thread which you can do by manually signalling.

**Comment by RealBadAngel** [comment] 2015-06-27 13:08
if (data->map_invalidated) {
			if (data->mode != MINIMAP_MODE_OFF) {
				u32 start_ms = porting::getTimeMs();
				getMap(data->pos, data->map_size, data->scan_height, data->radar);
				u32 end_ms = porting::getTimeMs();
				dstream<<"Time taken (ms): "<<end_ms-start_ms<<std::endl;
				data->map_invalidated = false;
			}
		}

**Comment by RealBadAngel** [comment] 2015-06-27 13:09
Tell me times reported. On my box its 13-14ms, so i can run minimap at circa 77 FPS

**Comment by est31** [comment] 2015-06-27 13:21
Between 257 and 463 ms

**Comment by RealBadAngel** [comment] 2015-06-27 13:43
holy shit. thats impossible

**Comment by kilbith** [comment] 2015-06-27 13:56
With an old **Intel Celeron 900** (single core) : http://pastie.org/10261678 (average : 193 ms).

**Comment by est31** [comment] 2015-06-27 14:16
I kept it running for a couple of time and got an average of 427 ms with the commit 0b6b87154503f35d1d1cfd55c4352ff24efed4bb

**Comment by TeTpaAka** [comment] 2015-06-27 16:28
I get average 392 ms with 299 samples.
Intel Core i5 CPU 750 with 2.67GHz, 4 Cores.

**Comment by TeTpaAka** [comment] 2015-06-27 17:24
Previous test was a debug build.
As release, there is 29,5 ms with 316 samples

**Comment by est31** [comment] 2015-06-27 18:23
@VanessaE do you have entered a bug report for the main mesh thread lag? I could link it above.

**Comment by est31** [comment] 2015-06-27 18:29
As I see the minimap is transparent, perhaps make the alpha configurable?

**Comment by VanessaE** [comment] 2015-06-27 20:25
I have not reported the mesh gen lag as an official bug because I cannot confirm the mesh gen as the cause, however @Zeno- has reported the same via IRC in the past.

**Comment by kwolekr** [comment] 2015-07-08 05:17
The minimap could use additional improvements as well.

Scanning for the surface *actually* takes place inside the MeshUpdateThread (why????!).  Then the surface "pixels" found are stored in a map with a 3d coordinate key, creating the totally artificial need to scan downward inside the mapper mapblock cache.  Then, these lookups are repeated 256 times per mapblock because getMinimapPixel() works on a single node at a time instead of in batch, for whichever reason.
This is *hideously* inefficient design.  The same end result can be achieved by storing MinimapPixels directly in a 2d array.

In total, we need to fix the following:
- Scanning/rescanning strategy (by far the most WTF part of the minimap)
- The fact that surface scanning is actually performed in the mesh update thread
- Double scan height.  Why is this not a single integer??
- The minimap's internal buffers are statically sized
- The right shift key does not change the minimap shape

**Comment by numberZero** [comment] 2017-02-22 22:44
Some profile results (FPS is around 8–10, that’s my old Athlon...):
```
  %   cumulative   self              self     total           
 time   seconds   seconds    calls   s/call   s/call  name    
 34.80     16.23    16.23 15088085     0.00     0.00  MinimapUpdateThread::getMinimapPixel(irr::core::vector3d<short>, short, short*)
 10.81     21.27     5.04  9872745     0.00     0.00  MeshCollector::append(TileSpec const&, irr::video::S3DVertex const*, unsigned int, un
  6.50     24.30     3.03 87622863     0.00     0.00  getTileInfo(MeshMakeData*, irr::core::vector3d<short> const&, irr::core::vector3d<sho
  5.53     26.88     2.58  9792517     0.00     0.00  getSmoothLight(irr::core::vector3d<short>, irr::core::vector3d<short>, MeshMakeData*)
  2.72     28.15     1.27 21037448     0.00     0.00  encode_light_and_color(unsigned short, irr::video::SColor const&, unsigned char)
  2.21     29.18     1.03     7144     0.00     0.00  mapblock_mesh_generate_special(MeshMakeData*, MeshCollector&)
  2.12     30.17     0.99 16413264     0.00     0.00  applyShadeFactor(irr::video::SColor&, float)
```
WTF? Why does `MinimapUpdateThread::getMinimapPixel` eat 1/3 CPU?

Here is another part:
```
[2]     83.2    0.01   38.79       2         UpdateThread::run() [2]
                0.02   22.28     244/244         MeshUpdateThread::doUpdate() [3]
                0.00   16.49    1938/1938        MinimapUpdateThread::doUpdate() [5]
```
So, all the stuff `MeshUpdateThread` does takes only slightly more CPU time than what `MinimapUpdateThread` does. How can the minimap be *so* heavy?

Note: during profiling, I simply fly and walk around, in a just generated world (server is in another process so not mentioned in the profile).

**Comment by numberZero** [comment] 2017-02-23 13:38
#5294 

> The same end result can be achieved by storing MinimapPixels directly in a 2d array.

@kwolekr, not for radar mode, neither for floatlands (they would obscure the minimap once the client sees them).

**Comment by paramat** [comment] 2017-02-24 00:30
@numberZero does #5294 address kwolekr's points?

**Comment by paramat** [comment] 2017-03-11 02:28
#5294 merged.

**Comment by Fixer-007** [comment] 2019-02-10 00:06
Minimap still causes extreme stutter in latest git 5.0, this topic was resurfaced here on irc: http://irc.minetest.net/minetest-dev/2019-02-09#i_5492708

Some screenshots:
https://i.imgur.com/5DtwVnX.png / i5-3450, intel hd2500, vrange 160
https://i.imgur.com/6dxOQvM.png / zoom-in of stutter
https://i.imgur.com/f5v19Rt.png / same, but ingame
https://a.uguu.se/dd01Sb7onCfT_screenshot_20190210_002820.png / screenshot by @hecks

**Comment by paramat** [comment] 2019-02-10 00:44
Reopened.

**Comment by Fixer-007** [comment] 2019-02-10 00:50
Minimap still causes extreme stutter in latest git 5.0, this topic was resurfaced here on irc: http://irc.minetest.net/minetest-dev/2019-02-09#i_5492708

Some screenshots:
https://i.imgur.com/5DtwVnX.png / i5-3450, intel hd2500, vrange 160
https://i.imgur.com/6dxOQvM.png / zoom-in of stutter
https://i.imgur.com/f5v19Rt.png / same, but ingame
https://a.uguu.se/dd01Sb7onCfT_screenshot_20190210_002820.png / screenshot by hecks

**Comment by Minetest-One** [comment] 2019-03-12 12:40
Is that issue here also including, that under now 5.1.0-dev I still cant see proper position of other gamer in minimap ?
It is wrong postition if I see some

**Comment by Zughy** [comment] 2020-12-21 22:22
@pyrollo have your minimap commit solved any of these points? Just asking

**Closed** 2022-05-16 23:12 UTC
Labels: Bug, Performance, Possible close
