### ISSUE TITLE
Client crashes when connecting to server [0.5.0-dev]

### ISSUE THREAD

**Issue by raoul32** [minetest/minetest#6968] opened 2018-01-26 04:57 UTC
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.5.0-dev (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=None
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1

```

##### OS / Hardware

Operating system: Ubuntu 17.10
CPU: Intel Q8300

GPU model: nvidia GT730
OpenGL version: 4.5.0

##### Summary
Whenever i try to play on some servers (many of them but not all), my client crashes just after connecting. My character spawns for a couple seconds then the game window closes.
Some servers are unaffected so it may be a mod issue.

##### Steps to reproduce

I've been using minetest 0.5.0-dev for a while without problem, the crashes started to occur a few days ago (a week tops). I tried to delete ~/.minetest directory and reinstall minetest to no avail.
Crash occurs any time i try and connect to some servers.

```
2018-01-26 05:32:05: WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
2018-01-26 05:32:05: WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
2018-01-26 05:32:05: WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
2018-01-26 05:32:06: WARNING[Main]: Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
2018-01-26 05:32:14: WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
2018-01-26 05:32:14: ERROR[Main]: generateImage(): Could not load image "yum_vanilla_icecream_block.png" while building texture; Creating a dummy image
2018-01-26 05:32:14: ERROR[Main]: generateImage(): Could not load image "yum_vanilla_icecream_block.png" while building texture; Creating a dummy image
2018-01-26 05:32:15: ERROR[Main]: generateImage(): Could not load image "darkage_marble_tile.png" while building texture; Creating a dummy image
2018-01-26 05:32:15: ERROR[Main]: generateImage(): Could not load image "darkage_marble_tile.png" while building texture; Creating a dummy image
2018-01-26 05:32:18: ERROR[Main]: generateImage(): Could not load image "moretrees_acacia_wood.png" while building texture; Creating a dummy image
2018-01-26 05:32:18: ERROR[Main]: generateImage(): Could not load image "moretrees_acacia_wood.png" while building texture; Creating a dummy image
2018-01-26 05:32:18: ERROR[Main]: generateImage(): Could not load image "mv_technic_machine_bottom.png" while building texture; Creating a dummy image
2018-01-26 05:32:18: ERROR[Main]: generateImage(): Could not load image "mv_technic_machine_bottom.png" while building texture; Creating a dummy image
2018-01-26 05:32:19: ERROR[Main]: generateImage(): Could not load image "hv_technic_machine_bottom.png" while building texture; Creating a dummy image
2018-01-26 05:32:19: ERROR[Main]: generateImage(): Could not load image "hv_technic_machine_bottom.png" while building texture; Creating a dummy image
2018-01-26 05:32:20: WARNING[Main]: TextureSource::getPalette(): the specified palette image "unifieddyes_palette_extended.png" is larger than 256 pixels, using the first 256.
2018-01-26 05:32:48: ERROR[Main]: generateImage(): Could not load image "hiking_illuminated_pole_sign_bottom_.png" while building texture; Creating a dummy image
2018-01-26 05:32:50: WARNING[Main]: Client side mods are disabled by configuration.
2018-01-26 05:32:50: ERROR[Main]: In thread 7f1d8667cd80:
2018-01-26 05:32:50: ERROR[Main]: /build/minetest-vNgBwG/minetest-201801241734/src/game.cpp:a26: void Game::handleClientEvent_HudAdd(ClientEvent*, CameraOrientation*): An engine assumption 'new_id == id' failed.
```

**Comment by nerzhul** [comment] 2018-01-26 06:27
sounds to be server side HUD synchronisation problem, did you try on another server ?

**Comment by raoul32** [comment] 2018-01-26 06:28
Yeah, among 10 servers running 0.5.0 available, three or four are spared by the bug. All other servers crash with the same error message.

**Comment by sfan5** [comment] 2018-01-26 11:48
@red-001 isn't this your code?

**Comment by red-001** [comment] 2018-01-26 12:36
technically a duplicate of #6937 but this one describes the bug better.

**Closed** 2018-01-26 15:05 UTC
Labels: @ Client / Audiovisuals, @ Script API, Unconfirmed bug
