### ISSUE TITLE
move "You died." to Server

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#7083] opened 2018-02-27 14:43 UTC
"You died.": https://github.com/minetest/minetest/blob/master/builtin/client/init.lua
Client mods can cheat easily.

**Comment by SmallJoker** [comment] 2018-02-27 15:49
Duplicate of #6736 and related to #6925

**Closed by SmallJoker** 2018-02-27 15:49 UTC

**Comment by sfan5** [comment] 2018-02-27 17:00
FYI: Anticheat will prevent you from interacting with the world until you respawn.
