### ISSUE TITLE
Resize ingame names, depending on distance

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#1513] opened 2014-07-23 15:32 UTC

**Comment by nerzhul** [comment] 2015-02-12 18:31
Because it's a duplicate of #1627 and this request is older i close it.
Thanks for your report;

**Comment by rubenwardy** [comment] 2015-02-12 18:38
It makes sense to close the newer request.

**Comment by nerzhul** [comment] 2015-02-12 18:47
oops, i inverted, you are right.

**Comment by C1ffisme** [comment] 2015-02-12 20:27
Maybe an API for names would be nice. I would like to see some methods of disguising or hiding your name.

**Comment by indriApollo** [comment] 2015-02-12 21:59
And a way to easily display text or even an image above the players head

**Comment by ProgrammingChicken** [comment] 2015-08-06 16:09
@C1ffisme and @indriApollo
This is what you might be looking for
https://github.com/minetest/minetest/issues/1345

**Comment by paramat** [comment] 2016-03-28 11:17
#1627 contains this, so folding this into that.

**Closed by paramat** 2016-03-28 11:17 UTC
Labels: @ Client / Audiovisuals, Feature request
