### ISSUE TITLE
Crack animation visible to other players

### ISSUE THREAD

**Issue by bigfoot547** [minetest/minetest#4791] opened 2016-11-18 19:14 UTC
Node cracking is client-side and other clients can't see it.
Is there any way to fix/change this?

**Comment by paramat** [comment] 2016-11-18 19:56
See the issue with cracks explained in #4745 , for this reason it is not a good idea, the cracks are feedback for the digger so there's no need for others to see it.

**Comment by paramat** [comment] 2017-04-25 21:02
We already have an issue where crack frames update the mesh for the whole mapblock, 5 times for every node dug, now imagine you are seeing the cracks of multiple players digging, the problem is multiplied, and for no good reason. Obviously we cannot do this. It would also be complex and a lot of work to send cracks to other players.

**Comment by rubenwardy** [comment] 2018-04-09 19:45
I don't see this as particularly important although it could be nice to have (if done well).

Closing for now, but this could become a better idea in future once networking and such is improved

**Closed by rubenwardy** 2018-04-09 19:45 UTC
Labels: @ Client / Audiovisuals, Feature request

**Comment by paramat** [comment] 2018-04-10 02:10
No core dev interest, unnecessary and would multiply mesh updates and affect performance, so i don't think 'PRs may be accepted' is a suitable label.
