### ISSUE TITLE
Bypass allow_metadata_inventory_put and on_metadata_inventory_put

### ISSUE THREAD

**Issue by pithydon** [minetest/minetest#4816] opened 2016-11-29 02:12 UTC
While playing like a baby with my [babycrafter] mod I found I could place a square in the triangle spot by...
* Place the triangle in the triangle spot.
* Place the square on the triangle.
* Place the triangle on the square.
* Place the square in the triangle spot.

Note: no in between steps, eg placing an item in an empty inventory spot.

You can also place apples in the shape sorter.
on_metadata_inventory_put gives an error if a random item is placed, but no error is given.

I think this is a minetest bug because you can also place apples in a book shelf.

[babycrafter]: https://github.com/pithydon/babycrafter

**Comment by cheapie** [comment] 2016-11-29 05:12
I can't seem to reproduce this using moreblocks' circular saw, which does check on_metadata_inventory_move as well. Is your mod checking stuff on move?

**Comment by pithydon** [comment] 2016-11-29 15:35
My mods allow_metadata_inventory_move just returns 0.
I can't reproduce it with the circular saw either.
You should try it with the book shelf.

**Comment by Thomas--S** [comment] 2016-11-30 05:03
I can confirm that sometimes you can bypass on_metadata_* . This happened to me while testing some workshop nodes.

**Comment by sfan5** [comment] 2017-04-09 18:25
duplicate of #4321

**Closed by sfan5** 2017-04-09 18:25 UTC
