### ISSUE TITLE
Allow Unicode in chat console or formspec

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10358] opened 2020-09-01 07:01 UTC
## Problem

I am a chinese player, and i want to type unicode in chat or sign, but it is impossible now.

## Solutions

Enable fuff unicode support in formspec and chatroom

**Comment by sfan5** [comment] 2020-09-01 11:43
duplicate of #5226 and #302

**Closed by sfan5** 2020-09-01 11:43 UTC
Labels: Feature request
