### ISSUE TITLE
Entities with collisionboxes.

### ISSUE THREAD

**Issue by NewbProgrammer101** [minetest/minetest#6847] opened 2017-12-26 17:46 UTC
An entity should have a collisionbox that perfectly fits the model. This issue is against the cubic and rectangular prism collisionboxes that we currently have.

**Comment by NewbProgrammer101** [comment] 2017-12-26 17:49
Another reference is my comments at the near bottom in https://github.com/minetest/minetest_game/issues/1667

**Comment by paramat** [comment] 2017-12-26 18:04
Duplicate of #3996

**Closed by paramat** 2017-12-26 18:04 UTC
Labels: Duplicate
