### ISSUE TITLE
Windows (Stupid OS) not detect sqlite3

### ISSUE THREAD

**Issue by acterhd** [minetest/minetest#4880] opened 2016-12-10 15:33 UTC
I tried all methods. All dirs. But CMake in Windows can't detect sqlite3. Yes, with Linux no problems with compilation! And with OS-X have no problems. And tried set these variables, but CMAKE force delete these variables. 

```
CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find SQLite3 (missing: SQLITE3_LIBRARY SQLITE3_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindSQLite3.cmake:8 (find_package_handle_standard_args)
  src/CMakeLists.txt:255 (find_package)
```

**Comment by sfan5** [comment] 2016-12-10 15:41
What values did you set the variables to? Did you use cmake from the command line or the GUI?

**Comment by acterhd** [comment] 2016-12-10 16:04
GUI I something solved with Advanced. But... SQLite unresolved, some "__imp_" unresolved when compiling... Yes, I handy added libs.

**Comment by acterhd** [comment] 2016-12-10 18:04
Oh Windows... I can't gen world

**Comment by SmallJoker** [comment] 2016-12-11 10:24
If you're using MSVC:

Compile SQLite3 with the flags `/MT /O2 /Ob2 /D NDEBUG` to solve these linker errors.
To fix the problem with built in Lua, open the file `your_bin_dir\src\lua\build\lua.vcxproj` and replace all occurrences of `MultiThreadedDLL` to `MultiThreaded`. Thanks to BlockMen who told me about this some years ago.

**Comment by acterhd** [comment] 2016-12-11 10:52
I tried, but have another problem. In "Release" world generation crash client, "Debug" works.

**Comment by adrido** [comment] 2016-12-11 18:31
This isn't a Windows Issue. I think Its caused by a  wrong configured CMake script.
Duplicate of this: https://github.com/minetest/minetest/issues/4697

**Closed** 2016-12-11 21:15 UTC
Labels: @ Build, Windows
