### ISSUE TITLE
Callbacks For Jumps

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#13334] opened 2023-03-17 16:09 UTC
## Problem

There is currently no way to do some sort of callback every time something jumps. One has to rely on hacky workarounds which have the possibility to miss some jumps, or detect false jumps.

## Solutions

Add an `on_jump` callback, which gets called every time something jumps, such as a player.

**Comment by rubenwardy** [comment] 2023-03-24 11:48
Duplicate of #8058

**Closed by rubenwardy** 2023-03-24 11:48 UTC
Labels: @ Script API, Feature request
