### ISSUE TITLE
huge error shouldn't be printed in game

### ISSUE THREAD

**Issue by asl97** [minetest/minetest#1218] opened 2014-04-11 20:21 UTC
[kwolekr commented](https://github.com/minetest/minetest/issues/1218#issuecomment-204912690):

> FWIW the specific "issue" of the huge error being printed has been "fixed" since last July by 5006ce8
> 
> This issue is being kept open because the actual problem, i.e. the bug causing the huge error message, has never been solved.

---

original issue:
don't get me wrong but an error message which block the whole screen is bad
it might even scare away people who are trying out minetest
![screenshot_1382107759](https://cloud.githubusercontent.com/assets/4752645/2684224/fb2ae62e-c1b4-11e3-979b-490ae848c3c0.png)

**Comment by 4aiman** [comment] 2015-05-18 06:40
Sorry if I will make an impression of being irritated, I'm not. 
But labeling this issue with a "low-priority bug" label is moving in a wrong direction.

Low-priority? Seriously?
A bug that hinders fun and make users to turn their backs on Minetest is less needed than a new (new for MT, of course) paranoid authentication hashing algo? (#1943)
(I agree with other high-priority bugs, though. )

I was told many times that MT is an engine. That includes IRC and talking to Celeron55 and other devs. So could you tell me, please... why the engine logs it's errors into the game?
Not only that, but it also lets db and multimedia engines (level db and Irrlicht, duh ;) to clutter the screen with their error messages.

To my mind, ANY error should go to the terminal window/std out.
Devs DO know where to find and how to use that.
General public should NOT see even a single least-important error message in chat.

Minetest still clutters the screen with leveldb messages (cannot save block), missing textures messages, invalid character conversion messages, "failed to update listener" messages, "not allowing to place CONTENT_IGNORE" messages, etc, etc.

I don't think that's a low priority bug.

**Comment by cheapie** [comment] 2015-05-18 12:27
The low-priority label was removed in December.

On the other hand, since these messages slow the game down so much when they're printed in the chat, I have my local copy patched to not show them there. It seems to work fine.

**Comment by 4aiman** [comment] 2015-05-18 13:55
I saw it was removed. That's why I wrote my message: this isn't even low priority bug. Which means it's priority is VERY low...
It would be nice if you send a pull-request, cheapie.

**Comment by nanepiwo** [comment] 2015-05-18 23:14
I agree that error messages and even warnings should only be typed to terminal/debug. However, if something such as creating a dummy image for default:door_wood isn't typed to chat, some people would be very confused upon seeing their wonderful entrance to their home replaced by a colorful dummy image...

However, I personally think that there should be an options in settings to disable chat errors and warnings, and they should be disabled by default. Even an option for the config file would be fine, since most people who need error messages in chat know how to edit the config :)

**Comment by 4aiman** [comment] 2015-05-19 06:03
@nanepiwo 
Having a disabled by default option is a splendid idea!

Why:
I can provide some messages of some players which (the messages) will prove that even when you actually tell ppl what to do, they don't want to read even the shortest chat message.

So, notifying them about dummy texture isn't necessary. In fact, they run around  screaming "What has happened to my perfect [insert colour name here] [insert node name here]? How to get it back?" And when you tell them to calm down and ask to re-login after 2 minutes (so you can fix the missing texture issue) they do NOT want to log off because.... well, "I can't do it, something has happened to my house! I need to rebuild it!!! Please, Please!! Don't stop server!!" 

Those, who know why that is so will just ignore it and report of a missing texture. 

But those messages above are sane. More frequently I get "What's happened?" or "aimen!!" or "Me lost my stuff!" or "Eating!!!!"...

I doubt it would do any good to provide any error messages.

**Comment by Zeno-** [comment] 2015-05-19 07:08
I've been removing low priority labels (but not on bugs) because it's useless. There should be "bug", "high priority" and "blocker". That's it. The main reason I remove low priority labels is because **everything** gets that label making it effectively pointless.

**Comment by Zeno-** [comment] 2015-05-19 07:13
The "unconfirmed bug" label isn't really appropriate but it's better than nothing I guess. "Needs to be reproduced" or something similar would be better.

**Comment by nerzhul** [comment] 2015-05-19 12:22
@Zeno- is this really a bug ? It's only an enhancement, this is the correct behaviour but not the user friendly behaviour

**Comment by cheapie** [comment] 2015-05-19 12:31
Well, seeing as how showing a huge serialization error in-game causes an FPS drop to something like 0.1-5 FPS depending on the length - often making the game so slow that I have no choice but to kill and restart it - there's definitely something that can be described as a bug somewhere. Either it's the text overlay being slow, or the whole filling the screen with text thing.

Now, if you don't want to hide the errors entirely, maybe something like this in the chat would work:

A serialization error occurred. Check <log filename> for details.

**Comment by nerzhul** [comment] 2015-05-19 12:40
This is not so simple :)

**Comment by Zeno-** [comment] 2015-05-19 12:43
I'm not sure if it's a bug or not. Hence one of the reasons for me saying the label "unconfirmed bug" really isn't appropriate.

**Comment by nanepiwo** [comment] 2015-05-19 19:41
I believe this should be split into a bug and enhancement. Bug for the serialization error, and enhancement for the not sending errors to chat.

**Comment by nanepiwo** [comment] 2015-05-19 19:43
And also as a note, on Android tapping a formspec with three fingers leads to some warnings in chat which I believe shouldn't be output to chat. Similarly for errors when taking screenshots ()

**Comment by jmf** [comment] 2015-05-20 08:32
It could be a solution to put chat only into chat and put error messages into a seperate log, that can accessed with some key combination. Maybe the F-10 console could do that.

**Comment by 4aiman** [comment] 2015-05-20 08:39
:+1: for splitting the issue into two.
:+1: for splitting chat from anything else.
:-1: for F-10. F10 console is the only way to type non-latin characters in Linux. 
AFAIK F11 and F12 aren't "taken". Why not use those?

**Comment by 4Evergreen4** [comment] 2015-05-20 11:59
@4aiman F12 is used for screenshot by default.

**Comment by 4aiman** [comment] 2015-05-20 13:00
@4Evergreen4 
Oh.. Is that so? Totally forgot that I've changed the keys...

Well then, what about F11 or F9?

**Comment by nanepiwo** [comment] 2015-05-25 22:07
@4aiman changing the F keys would confuse people who haven't changed the defaults, especially those who update Minetest through the master branch daily...

**Comment by asl97** [comment] 2015-05-25 22:54
@nanepiwo i think he is talking about currently unused key, i don't see how adding a new hotkey to unused would cause any confusion

i don't seem to be able to reproduce it locally anymore through the `chainsaw down a HUGH oak forest` method, maybe it cause by the lag or maybe it been fixed already.

also, i don't play much anymore, it be great if someone who could somehow get a screenshot of it happening on minetest 0.4.12

**Comment by nanepiwo** [comment] 2015-05-25 23:01
Try adding a mod with a node without a texture, such as https://github.com/ShadowNinja/bell :)

**Comment by asl97** [comment] 2015-05-25 23:08
@nanepiwo a texture error is different from a SerializationError if you are talking about that

**Comment by nanepiwo** [comment] 2015-05-26 01:00
@asi97 As I said earlier, this is two errors: The serialization error
itself and the idea of not placing this and other errors in chat.

**Comment by cheapie** [comment] 2015-05-26 04:43
@asl97 It seems to not happen locally, only over the Internet. Packet corruption, maybe?

**Comment by 4aiman** [comment] 2015-05-26 06:14
@nanepiwo,  I *was* talking about a new F key, just like @asl97 have said.

On the topic:
I think @cheapie may be right.
Recently (for 2 or 3 weeks) MT seems to not receive all packets sometimes. 
Or least so it seems ;)
It looks like MT thinks that a player has timed out (while he/she is not) and tries to emerge him/her again.

For 2 or 3 times while playing "online" (separate local server and a client, connected to 127.0.0.1) I got the "failed to update listener" error and then MT "teleported" me to the static_spawnpoint - much like it does upon emerging player. 

It always happened when some nodebox node was near.

After that I had to re-login, since MT stopped to receive my position and blocked any interaction with entities. Nodes interaction worked great, though. As well as the chat. But I couldn't craft anything.

Don't know, whether ^ that is related at all...

**Comment by cheapie** [comment] 2015-05-26 13:10
So, I guess that means that we still have two problems here:

* Network is unreliable for some reason
* Errors are dumped into chat

**Comment by est31** [comment] 2015-06-25 14:16
Errors belong into chat, where else? Would you want to step into a car that doesn't tell its owner it has problems (e.g. overheated engine)?

**Comment by cheapie** [comment] 2015-06-25 16:59
Well, if you want to use that analogy, most cars just turn on a warning light if something like that happens, while MT's current behavior is to start flashing the entire windshield at you and slam on the brakes.

**Comment by est31** [comment] 2015-06-25 17:01
I like car analogies.

**Comment by 4aiman** [comment] 2015-06-25 19:39
Yay!!! :+1: to the cars analogies :smiley: 

While there are many "reconfigurabilities" already, I still think that ```chat<<error``` should be optional.
Why not let the engine to use smth similar to debug_level as a setting for in-chat errors logging?
- 0 would mean that NO errors will spam the chat.
- 1 would allow only errors
- 2 = warnings
- 3 = any info (e.g. ```/someone uses /teleport chat command``` or ```X sets the time to Y```)

**Comment by nanepiwo** [comment] 2015-06-26 17:43
@4aiman +1 However, i do not think option 3 will work because the server does not send such information to the clients, however it should be possible for a client to ignore messages that are sent by the server and not by players.

**Comment by 4aiman** [comment] 2015-06-27 13:12
@nanepiwo 
by ```3``` I meant messages like ```You died``` or ```The time is set to X```. 
(Why didn't I give a proper example earlier?)

**Comment by nanepiwo** [comment] 2015-06-27 15:34
"The time is sent to X" is sent by the server, not the client, if I'm not mistaken. However, there should be a separate option in the conf to disable client death messages.

**Comment by asl97** [comment] 2015-06-27 18:53
#thatgraemeguy posted this image on the irc:
![](http://i.imgur.com/qvKW99P.png)

quote:
```
anyone know what that error message is all about? get this from time to time and FPS drops to 0 and I pretty much have to quit.
```

**Comment by asl97** [comment] 2015-07-01 07:10
maybe this issue should be split into `printing error` and `serialization error (probably cause by entity)`.

serialization error on singlepleyer: http://irc.minetest.ru/minetest-dev/2015-07-01#i_4304836
reproduce by @VanessaE and @est31

**Comment by kwolekr** [comment] 2015-07-14 02:57
Perhaps there should be a logging level (or boolean option for any log level??) to display the message in game chat.  I agree that errors should not be printed by default.
We should wait for ShadowNinja's logging refactor before adding anything more to logging, though.

**Comment by est31** [comment] 2015-07-14 04:33
We print errors because they inform about something important going wrong. Omitting them is bad IMO. Perhaps we should however somehow rate-limit them.

**Comment by cheapie** [comment] 2015-07-14 16:37
These errors generally occur one or two at a time, and just one is enough to bring the frame rate below 1 FPS if it's big enough.

I still think that it should say in the chat that there *was* a serialization error, but not dump the entire packet there like it does now.

**Comment by paramat** [comment] 2016-03-27 14:37
Erm is the error size limited now?

**Comment by est31** [comment] 2016-03-28 09:03
@paramat only for very specific kinds of errors.

To the people demanding that we remove any error messages from the servers (this issue report seems to be partially about this), i don't think that's a good idea. If the server has a mod or internal error that is caused by a bug, then the players deserve to know that there was a bug.

**Comment by 0-afflatus** [comment] 2016-03-28 09:44
If you are going to print errors to chat, players should have the option to enable / disable error reporting in chat. It looks bad to the new player however useful and informative the info may be.
I'd sooner it was just logged.

**Comment by VanessaE** [comment] 2016-03-28 14:04
Frankly, errors shouldn't be printed into the chat at all - end users do NOT need to see that stuff.  Filter the error for unprintable chars and print it to the controlling terminal, log the raw version to debug.txt, where developers who need the errors can find them, and move on.

**Comment by cheapie** [comment] 2016-03-28 14:07
Maybe only show errors in chat if debugging information (F5) is on?

**Comment by VanessaE** [comment] 2016-03-28 15:47
Nah, I'd say no because I'm sure a lot of people use F5 just to get their coords or look direction.

**Comment by est31** [comment] 2016-03-28 15:51
Do you people really think its better to delete objects in the whole mapblock because there are too much without any indication of what happened to the players, than with a message? Yes, it would be best if it almost never happened, but still silently failing is worse than failing with an error msg IMO.

**Comment by 4aiman** [comment] 2016-03-28 16:54
It's been almost  2 years now. Just add an option to control error->chat processing.
Server owners  will decide on their own. Singleplayers too.
I doubt that 2 years of argument was easier to achieve than adding 1-2 options to control client/server errors. :-1:

**Comment by VanessaE** [comment] 2016-03-28 18:52
No one's saying that it should "fail" without a message - just that it doesn't belong in chat.  Besides which, why - in a working, correct implementation - would players be affected at all by deleting objects, aside from wondering why all the *objects* disappeared?

**Comment by Fixer-007** [comment] 2016-04-01 16:42
Yes, I'm tired of errors in my chat, i'm not an owner of the server, owner/admin should get them in chat and in debug imo.

**Comment by kwolekr** [comment] 2016-04-03 08:18
FWIW the specific "issue" of the huge error being printed has been "fixed" since last July by https://github.com/minetest/minetest/commit/5006ce82609b2260f191b132f2dabcfdb06d6e20

This issue is being kept open because the actual problem, i.e. the bug causing the huge error message, has never been solved.

**Comment by 0-afflatus** [comment] 2016-04-05 18:30
@est31 @VanessaE 
sorry to bump this in an OT way - I just got feedback from one of my main players who currently uses multicraft that they would switch to the MT android client if it were not for these errors, which are meaningless to players. I will open a separate issue for this.

**Comment by paramat** [comment] 2016-10-19 22:45
Related #2941

**Comment by est31** [comment] 2016-10-19 22:47
Printing errors into chat is no bug. Better open a bug report about the actual behaviour.

**Comment by nerzhul** [comment] 2017-03-15 14:48
Closing, refering to @est31 comment

**Closed by nerzhul** 2017-03-15 14:48 UTC
Labels: @ Client / Audiovisuals, @ Network, @ Server / Client / Env., Not a bug, Possible close

**Comment by paramat** [comment] 2017-03-15 17:54
Move discussion to #2941 as requested here https://github.com/minetest/minetest/issues/2941#issuecomment-123756686
