### ISSUE TITLE
"physical" property of item entities

### ISSUE THREAD

**Issue by DTA7** [minetest/minetest#6433] opened 2017-09-18 02:00 UTC
Entities have a property "[physical](https://github.com/minetest/minetest/blob/27144b471678b30156ad3383fb8d26a5bd9b66cb/doc/lua_api.txt#L4110)" which is barely documented and decides whether collision detection is performed for the entity.
The collision detection is done before on_step of the entity is called, see [content_sao.cpp](https://github.com/minetest/minetest/blob/27144b471678b30156ad3383fb8d26a5bd9b66cb/src/content_sao.cpp#L339-L394).

For item entities, this is a problem, because [item_entity.lua](https://github.com/minetest/minetest/blob/27144b471678b30156ad3383fb8d26a5bd9b66cb/builtin/game/item_entity.lua#L151) sets the physical property afterwards, so if the velocity is changed before the collision detection, as happens with the TNT mod from minetest_game, the physical property is false and the item can move inside nodes (this happens very consistently).
See also #5482.
This can be solved by executing the on_step functions before (could be problematic elsewhere), or by setting the physical property directly after the velocity change, but according to celeron55 requiring the mod to do so is not intended.

Always performing the collision detection does not change much for items, as it is not performed if the entity is not moving, but it needs to be disabled for carts ([cart_entity.lua](https://github.com/minetest/minetest_game/blob/4ccafd15187cf70d06d68ad3931912a3c3c4b4f5/mods/carts/cart_entity.lua#L2)), where physical=true is set.

Additionaly, the code in [item_entity.lua](https://github.com/minetest/minetest/blob/27144b471678b30156ad3383fb8d26a5bd9b66cb/builtin/game/item_entity.lua#L151) is incomplete, because items are stopped immediately if the node it is on is not defined (wanted that way), if it is walkable and not slippery or if the y-component of the velocity is zero, regardless of the x- and z-components.

I could not reproduce #5966, which could also be caused by only checking for the y direction.
#5973 and #5297 are unrelated, I think.

So it probably would be best to set physical=true for items unconditionally, because, as mentioned, [collisionMoveSimple](https://github.com/minetest/minetest/blob/27144b471678b30156ad3383fb8d26a5bd9b66cb/src/collision.cpp#L242-L244) already skips the detection if the entity is not moving, and to stop (or decelerate if on a slippery node) them like before.

**Comment by paramat** [comment] 2017-09-18 06:04
Seems to me that https://github.com/minetest/minetest/blob/master/builtin/game/item_entity.lua#L151
`local is_physical = (def and not def.walkable) or vel.y ~= 0` should include checks for vel.x/z ~= 0 also. But that causes unwanted behaviour.
Discussion http://irc.minetest.net/minetest-dev/2017-09-17#i_5080586 onwards and http://irc.minetest.net/minetest-dev/2017-09-18#i_5080743 onwards.

**Comment by paramat** [comment] 2017-09-18 08:28
> So it probably would be best to set physical=true for items unconditionally

I'm not keen on this, there can be hundreds or thousands of entities, having them always using collision checks would be a little intensive.
I suggest starting with line 151:
`local is_physical = (def and not def.walkable) or vel.y ~= 0 or vel.x ~= 0 or vel.z ~= 0`
which seems needed, and then working from that while keeping entities non-physical if not moving.

**Comment by DTA7** [comment] 2017-09-18 12:15
Should itemstacks merge on slippery nodes? And if they do, should the combined stack be moving if a new item is thrown at it?

**Comment by SmallJoker** [comment] 2017-09-18 17:24
The main reason for switching the physical setting of the item_entity is the performance.
> Always performing the collision detection does not change much for items, as it is not performed if the entity is not moving [...]

If they are "not moving", the gravity still pushes them down, having the effect of doing a rather expensive collision check in each server step. The check itself isn't that slow but multiplying this by the amount of activated items and the server step in (most likely) a single thread does indeed have an effect.

What came in my mind of fixing the items glitching into solid nodes bug is setting the acceleration to (0,0,0). This would [skip the calculations](https://github.com/minetest/minetest/blob/d8f20d0/src/collision.cpp#L243) as long it's not moving at all.

I agree that the item_entity code looks quite complicated, but it was designed to be as fast as possible to not have a noticeable impact on servers.

**Comment by DTA7** [comment] 2017-09-18 18:29
Yes, I know the acceleration has to be (0,0,0) too, that's what I meant be "not moving", but it is set to (0,0,0) as well in [item_entity.lua](https://github.com/minetest/minetest/blob/27144b471678b30156ad3383fb8d26a5bd9b66cb/builtin/game/item_entity.lua#L187-L192) if is_physical = false, so the extra check would not be needed for items.
Did I miss something here?
Could you take a look at e317ae39edef9a23ce9f450c80e1f6b4dac4a780? I changed the points which were mentioned (and renamed physical_state, which is only defined for item entities, to moving_state), but I'm unsure what the behaviour on slippery nodes should be like.

**Comment by paramat** [comment] 2017-09-19 06:13
> Should itemstacks merge on slippery nodes?

Ideally yes, or is this problematic?
What's the current behaviour?

> And if they do, should the combined stack be moving if a new item is thrown at it?

I think keeping the combined stack stationary is ok if it makes things simpler.

**Comment by DTA7** [comment] 2017-09-19 12:32
Before, they would only merge if the physical state or the slippery state changed and they were not too fast on a slippery node.
Now, they could also merge because the moving state changed when they were thrown, but I changed it to the old behaviour.

**Comment by raymoo** [comment] 2017-09-20 17:38
Maybe all the ObjectRef methods should be overridable by entity definitions.

**Comment by DTA7** [comment] 2017-09-20 19:31
What do you mean?

**Comment by raymoo** [comment] 2017-09-20 20:26
An entity definition could (for example) define `set_velocity`, and provide custom functionality. There would need to be a way to access the original implementations, though.

**Comment by DTA7** [comment] 2017-09-20 23:07
So the item entity could have set physical to true in set_velocity?

**Comment by raymoo** [comment] 2017-09-20 23:26
@DTA7 Yes.

**Comment by DTA7** [comment] 2017-09-21 00:09
I don't think that would be beneficial here, because the collision detection is always turned on, but not being performed if the velocity and acceleration are zero, so it would not make much sense to toggle it additionally depending on whether the item is moving.

**Comment by raymoo** [comment] 2017-09-21 01:56
But you said
>This can be solved by executing the on_step functions before (could be problematic elsewhere), or by setting the physical property directly after the velocity change, but according to celeron55 requiring the mod to do so is not intended.

Wouldn't overriding `set_velocity` to set physical to true effectively make all mods set the physical property directly after the velocity change?

**Comment by DTA7** [comment] 2017-09-21 02:23
What do you mean by overriding? For item entities?
In the pull request, only the behaviour of item entities is changed, not of other entities.

**Comment by raymoo** [comment] 2017-09-21 05:12
@DTA7 I mean for item entities, yes. But it would be a feature other entity definitions could use too.

**Comment by Ferk** [comment] 2017-09-21 12:12
> collisionMoveSimple already skips the detection if the entity is not moving

But other objects will collide with it if it's physical.

I think it is intended for "resting" items to be able to be walked through and don't get pushed back by players moving against them.

**Comment by celeron55** [comment] 2017-11-06 12:45
My opinion is that the engine should be optimized enough for items to be able to always be physical. It's pobably already the case, but I haven't tested. If it isn't, it should be made so. All of these things are just stupid workarounds for a slow engine.

**Comment by paramat** [comment] 2017-11-06 13:57
#6444 merged.

**Closed by paramat** 2017-11-06 13:57 UTC
Labels: Maintenance, Request / Suggestion
