### ISSUE TITLE
Footstep sound is not played on 1 node wide snow

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5121] opened 2017-01-26 15:11 UTC
I noticed that the snow sound is not played on one node wide snow. The sound of the neighbor node will be played. Snow has to be two nodes wide to be played correctly

See video

https://youtu.be/oiiiFlaYjUE

**Comment by paramat** [comment] 2017-01-27 12:31
What are you walking on here? is it snow slab on dirt-with-snow, and the other is snowblocks?

**Comment by MarkuBu** [comment] 2017-01-27 12:50
As you can see in the video the sound changes if I pass the center of the snow node. If I walk on the left side, ice sound is played, if I walk on the right side, stone sound is played. I don't know, which node is below the snow. I can take a look if I am back home.

But you can also see that the sound is played correctly after login, then I walked on stone and then the wrong sounds are played

**Comment by paramat** [comment] 2017-01-27 12:57
Ok just watched the video, it's snow slab sound weirdness, this was due to be looked at anyway.
it might be a good test to put a third type of node under the snow slab to see if that is ever played or if it's always a node to the side.

**Comment by MarkuBu** [comment] 2017-01-27 13:05
Below the snow slabs is sand. 

This issue only appears if the snow slab row has a width of 1.

**Comment by paramat** [comment] 2017-01-27 13:47
Wow weird.

**Comment by paramat** [comment] 2017-02-09 18:16
Here's the code i can find.
Footsteps for objects: other players and mobs https://github.com/minetest/minetest/blob/master/src/content_cao.cpp#L1198
Footsteps for player https://github.com/minetest/minetest/blob/master/src/game.cpp#L3527
That calls `LocalPlayer::getStandingNodePos()` https://github.com/minetest/minetest/blob/master/src/localplayer.cpp#L651
Note that gets the node a full 10 irrlicht units (1 BS) below player position, perhaps too much?

**Comment by paramat** [comment] 2017-02-09 18:33
Note that elsewhere in localplayer the node below the player is defined as 0.05 BS below `position` https://github.com/minetest/minetest/blob/master/src/localplayer.cpp#L263 see line 266.
And here is defined as 0.5 BS below `position` https://github.com/minetest/minetest/blob/master/src/localplayer.cpp#L396

**Comment by paramat** [comment] 2017-02-09 18:49
I'm guessing this code was written befire nodeboxes existed, so we may be able to adjust these offsets to get the correct footstep sound.

**Comment by paramat** [comment] 2017-02-09 19:22
I'll make a PR to experiment.

**Comment by paramat** [comment] 2017-02-09 20:40
Just realised:
```
v3s16 LocalPlayer::getStandingNodePos()
{
	if(m_sneak_node_exists)
		return m_sneak_node;
	return floatToInt(getPosition() - v3f(0, BS, 0), BS);
}
```
Note if 'sneak node exists' it's footstep sound is chosen, this is i guess to ensure footstep sounds even when hanging off the edge of a node.
Sneak node detection involves horizontal offsets so this my be causing the bug of this issue. When the player is on a slab nodebox maybe sneak search is activated somehow and the footstep is played for nodes to one side.

**Comment by MarkuBu** [comment] 2017-02-09 20:47
I always want to open an issue to turn off footstep sounds while sneaking, because... The player is sneaking

**Comment by paramat** [comment] 2017-02-09 20:51
Yeah, my PR might actually stop footsteps when hanging off the edge of a node, maybe we can eventually stop footsteps when sneaking for the player and other players.

**Comment by paramat** [comment] 2017-02-09 21:27
> But you can also see that the sound is played correctly after login, then I walked on stone and then the wrong sounds are played

This is probably because on login there is no 'sneak node' set, then once you walk on a node to the side that gets stored as the 'sneak node' and it's sound is played.
In my experimental branch i add another function that doesn't use the sneak node at all https://github.com/paramat/minetest/tree/posfootstep

**Comment by paramat** [comment] 2017-02-09 22:06
I can confirm the bug. Notice if you jump the footstep returns to snow until you touch a node to either side again, the sneak node is being reset when you jump.

**Comment by paramat** [comment] 2017-02-09 22:27
PR #5199 
Then in a later commit we can stop footsteps when sneaking.

**Comment by paramat** [comment] 2017-02-10 02:37
`Game::updateSound()` https://github.com/minetest/minetest/blob/master/src/game.cpp#L3527
This updates what sound is to be played for a footstep.
When falling there is no 'sneak node' so this code:
```
v3s16 LocalPlayer::getStandingNodePos()
{
	if(m_sneak_node_exists)
		return m_sneak_node;
	return floatToInt(getPosition() - v3f(0, BS, 0), BS);
}
```
uses `return floatToInt(getPosition() - v3f(0, BS, 0), BS);`

The reason the detection point is set so far below the player is that when falling the player moves fast and the update of the footstep sound may not happen in time, resulting in an "air" footstep. The detection point is moved downwards to increase the chance of detecting ground and updating the footstep sound in time.
This was set to 1 BS because classic Minetest had no nodeboxes so this worked.
Now this is of course unnacceptable and needs to be set to a distance thinner than a 1/16th nodebox.

**Comment by MarkuBu** [comment] 2017-02-10 05:39
:+1:

What does BS mean?

**Comment by paramat** [comment] 2017-02-10 17:41
Hehe 'Block Size' equal to 10, the size of a node in Irrlicht units. Note that player and object positions are in units 10 times smaller than nodes, they are in Irrlicht units (fundamental position unit of Irrlicht 3D engine).

**Comment by paramat** [comment] 2017-02-12 02:02
#5199 merged.

**Closed by paramat** 2017-02-12 02:02 UTC
Labels: @ Client / Audiovisuals, Bug, Sounds
