### ISSUE TITLE
filter contentdb mod list by if the mods are upgradable

### ISSUE THREAD

**Issue by programmerjake** [minetest/minetest#13994] opened 2023-11-14 00:51 UTC
### Problem

I like to look through the list of mods that will be upgraded before installing upgrades, since sometimes I have local changes to some mods and don't want to change them or because I want to know which mods I should look at to see what's new. Currently, if I'm using the contentdb page built into minetest, I have to manually search through the mods I have installed to look for any upgradable mods, which is annoying.

### Solutions

Add a way to filter by upgradability, or sort by publish date of latest available upgrade.

### Alternatives

look on contentdb website, but matching that up to minetest's mod list is annoying

**Comment by rubenwardy** [comment] 2023-11-14 01:11
Thanks for the suggestion

Duplicate of #11155, this was fixed and is due to be released in 5.8.0.

ContentDB will now show updateable things first in the list, allowing you to browse through them. There is also a [ContentDB redesign](https://github.com/minetest/minetest/pull/13820) in progress that will add a filter for updateable things

**Closed by rubenwardy** 2023-11-14 01:11 UTC
Labels: Feature request
