### ISSUE TITLE
Many Lua C functions are missing type checks

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#1794] opened 2014-11-02 19:30 UTC
Instead of throwing an error and returning to main menu, some function calls crash Minetest entirely (lack of proper error handling).

``` Lua
-- Gray screen
minetest.add_entity()
minetest.add_item()
minetest.add_node()
minetest.add_node_level()
minetest.add_particle(1,2)
minetest.add_particlespawner(1,2)
minetest.check_single_for_falling()
minetest.create_schematic('',{},{},'')
minetest.delete_area()
minetest.dig_node()
-- cut here - gave up checking all of them
minetest.show_formspec(name, 'test', 'list[inventory_location;list_name;0,0;8,8;]')
-- cut here as well

error()
```

EDIT2: List might be outdated. Please modify/notify.

**Comment by beyondlimits** [comment] 2018-07-21 20:10
Bump! I hit this issue over and over. What is this? We're doing it amateur way but "PRs are welcome"?

**Comment by nerzhul** [comment] 2018-07-22 11:29
i agree with @SmallJoker original command and @beyondlimits . We can enforce type checks on many parts. The new Lua serialization C++11 API i introduce force the type check. We should migrate to it by parts. @beyondlimits do you have an example ?

**Comment by beyondlimits** [comment] 2018-07-22 13:07
https://www.lua.org/manual/5.1/manual.html - all the `luaL_check*` functions.

Example (yeah, some of the functions do argument type check): https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_server.cpp#L85

**Comment by Zughy** [comment] 2022-08-10 10:51
I've checked every function in OP post and they throw an error as intended (I've had to use #12445 because LuaError messages are currently broken). I think it's masochist combing the whole API to find some missing check, so, considering my previous PRs and the fact that the ones listed don't cause any gray screen, I'll close this

**Closed by Zughy** 2022-08-10 10:51 UTC
Labels: Bug, @ Script API, Maintenance
