### ISSUE TITLE
Clicking shader checkbox makes sub-entries “jump around”

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4107] opened 2016-05-11 02:33 UTC
Last-minute-before-release bug report. ;-)

If you click “shader” in settings menu, the sub-entries (other checkboxes) tend to “jump” around. Doesn't look nice.

Tested in: 5d9b6aaa03fb326073b1d70645a5c08f10b7e461

**Comment by Fixer-007** [comment] 2016-05-11 22:55
Confirm, I also seen that just after merger of standard settings back into game and I think it was mentioned somewhere.

**Comment by paramat** [comment] 2017-07-08 22:53
Is this fixed now? I seem to remember a PR.

**Comment by octacian** [comment] 2017-07-08 23:35
Yes, this is kinda fixed after #5820. In concept, it's fixed, however, due to formspec weirdness, items will still seemingly jump around at times. Again though, any jumping around is now just caused by a formspec bug and not by the way the code for the tab was written. Could be closed IMO.

**Closed** 2017-07-09 09:18 UTC
Labels: @ Client / Audiovisuals, Bug
