### ISSUE TITLE
Minetest/-server Installation does not create files neither with apt nor docker

### ISSUE THREAD

**Issue by Sedrowow** [minetest/minetest#13324] opened 2023-03-14 13:01 UTC
##### Minetest version

```
Tried ,latest docker, latest available apt (no version defined while installing so i assume latest)
```

##### OS / Hardware

Operating system:
CPU: cant define but its a quad core with 4ghz (i use a remote linux system (debian)

GPU model:
OpenGL version:

##### Summary

Can't use minetest nor the server version. It doesn't create files. It prints out no errors and no warnings. But it makes a desktop link (in xfce4) that wont work (says no such file or directory ( i can confirm that because i checked every place (after apt and docker create) for possible locations (also used some programs for looking everywhere (sudo) and didn't found anything). Even after docker the volumes were created and there were some minetest similar directories, but weirdly with no files containing. Minetest -server has the same issues (the command isn't working or registered like the nornal minetest)

Strangely "docker run minetest" (i shortened a bit here, but wrote it fully as required in the terminal) creates a instance, but non persistent files...

Hope i provided enough information so it possible gets resolved and thanks in advance for any help i'll get
##### Steps to reproduce

1. Installation of usual minetest per apt
2. Run the Desktop link
3. Expected: minetest opens; got: error printing out no sucvh filen or directory 
4.  run command "minetest". Terminal respond no such command

Next thing i tried
1. Sudo docker create -v /home/minetest/data/:/var/lib/minetest/ -v /home/minetest/conf/:/etc/minetest/ registry.gitlab.com/minetest/minetest/server:master
2. Terminal prints no errors or warnings
3. Docker directories empty nor a /home/minetest

Last thing i tried
1. Sudo apt install minetest-server
2. No errosrs or warnings
3. Run minetestserver with response: no such command
4. Check files if they exist, but they didn't

Everything of these 3 trials i did 3 times.

P.s. i checked 30 minuet's issues but wasn't lucky hope it isn't duplicate

**Comment by Zughy** [comment] 2023-10-06 20:53
It looks like the issue is in the distro itself. It doesn't seem to be a Minetest bug, closing

**Closed by Zughy** 2023-10-06 20:53 UTC
Labels: Unconfirmed bug, @ Build, Question
