### ISSUE TITLE
Shadow and water light bugs

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest#3455] opened 2015-12-13 18:54 UTC
Hi, our server has a problem with light and sometimes also waterbugs.
Thats not only shadows, like on an closed issue here, its also light.
The most problem ist, that the [Mapfix](https://forum.minetest.net/viewtopic.php?f=9&t=10662&p=201614#p201614) Mod only fix water and shadows, not light-lightbugs.
Also ```/deleteblocks``` doesn't help!

Sadly i deleted some needed screenshots for this issue :'(

...Waterbugs mean, that i found an hole that looks like a roof(!) into the water.
...Shadowbugs are sometimes larger than one chunk and will be bigger (sometimes) if you try to fix them with some light source.

And here screenshots of the unfixable lightbugs:
![screenshot_20151213_195024](https://cloud.githubusercontent.com/assets/10698140/11808389/9c853f9e-a320-11e5-8d8f-7905d133c8ae.png)
![screenshot_20151213_195034](https://cloud.githubusercontent.com/assets/10698140/11808400/a75d7cd8-a320-11e5-830c-0c17c69765b5.png)
![screenshot_20151213_124922](https://cloud.githubusercontent.com/assets/10698140/11808411/b42a91b2-a320-11e5-9438-c646818411c7.png)

**Comment by tchncs** [comment] 2015-12-15 10:37
![screenshot_20151215_113122](https://cloud.githubusercontent.com/assets/10698140/11808307/fc3a851c-a31f-11e5-8c6c-e17867ea9d17.png)
This one, below, was first 100% black, than some transparence was added on the most parts, but the shadow was only to fix with the mapfixmod i wrote from.
![screenshot_20151215_000433](https://cloud.githubusercontent.com/assets/10698140/11808308/fc3c0fae-a31f-11e5-8348-b334029ae670.png)

**Comment by paramat** [comment] 2015-12-16 04:43
Are you using moretrees mod? Even in mgv6 it sometimes creates these shadow bugs, including the subtle shadoes in water.
I've never seen those night-time patches of light before, might also be due to moretrees.
Moretrees needs to use a different method and grow trees from saplings using an ABM a few seconds after mapgen, i've discussed this with VanessaE.

**Comment by tchncs** [comment] 2015-12-16 09:19
Wah. but i cant transform the hole map to v7 now :o 
(of course its possible to cut the buildings out, but this may can difficult to find them all)

I have to say that its also happens sometimes on older areas beside active players.
Oh, wait, maybe because growing saplings from moretrees?

I really need a solution, its hard and also will be very very shameful to disable this mod.
Also i have to explain our players what da heck happened there all few days.
Also again i have *no* solution for that lightbugs! 
One of them is inside the harbor from one player...the big one! :(

Did you know how its possible to update the mapfix mod maybe?
To temporally fix this lightbugs?

**Comment by paramat** [comment] 2015-12-18 01:32
> Wah. but i cant transform the hole map to v7 now :o 

In mgv7 the shadow bugs caused by moretrees are much much worse, so best stay with mgv6.
Apparently moretrees has a built-in option to place trees as saplings that grow soon after mapgen, try to enable that.
Growing a sapling (either default or a moretrees sapling) in an old area does sometimes cause a shadow bug, again this is due to the engine's 'updateLighting'.

**Comment by RHRhino** [comment] 2016-03-11 11:32
@tchncs Have you checked your node defenitions for water and water_source? Could it be that they heve `is_ground_content = true`, then those underwater lightnings/ light patches occur, because of the air which is generated in water for caves.

**Comment by 0-afflatus** [comment] 2016-03-11 15:01
using /deleteblocks makes matter much worse. #3839

**Comment by paramat** [comment] 2016-03-11 19:47
> Oh, wait, maybe because growing saplings from moretrees?

Yes apparently growing moretrees saplings does create lighting bugs, especially in water.
So using the moretrees option of placing all trees as saplings still results in lighting bugs.

**Comment by tchncs** [comment] 2016-03-12 15:36
@RHRhino how do i do this on the most elegant way?

**Comment by 0-afflatus** [comment] 2016-03-15 01:23
> using the moretrees option of placing all trees as saplings still results in lighting bugs.

It does, for much the same reasons.

**Comment by paramat** [comment] 2016-06-01 21:25
Closing as duplicate of #3421 please continue discussion there.

**Closed by paramat** 2016-06-01 21:25 UTC
Labels: @ Mapgen, @ Server / Client / Env., Bug, Duplicate
