### ISSUE TITLE
Using shift key creates space in chat

### ISSUE THREAD

**Issue by davisonio** [minetest/minetest#5700] opened 2017-05-03 20:07 UTC
By using the shift key in the chat e.g. to access `:` and `_` characters - it creates a space in the chat which makes it much harder to type.

For example here's where I'm trying to type `/giveme default:pick_wood` and `/time 6:00`. Spaces are created in the middle of the message making it hard to type.

![may-03-2017 21-02-22](https://cloud.githubusercontent.com/assets/5341072/25679161/304f3962-3044-11e7-9e60-1edaa5f73c40.gif)

Using macOS Sierra with the latest development version of Minetest.

**Comment by sofar** [comment] 2017-05-04 04:31
Likely MacOSX specific, I can't repro on Linux.

**Comment by pithydon** [comment] 2017-05-04 17:13
This bug applies to older mac osx versions and minetest 0.4.15 as well.

**Comment by kaeza** [comment] 2017-05-05 01:04
There's also an user on Vanessa's survival server who has the same problem.

FWIW, it seems this "space" character is actually ASCII code 16.

**Comment by est31** [comment] 2017-05-13 08:23
dupe of #4531 ?

**Comment by davisonio** [comment] 2017-05-13 09:29
yes and of #4057 looks like.

This bug really needs to be addressed. has been in lots of stable versions and a problem for over a year.

**Comment by nerzhul** [comment] 2017-05-13 11:56
Closed in favor of other PR

**Closed by nerzhul** 2017-05-13 11:56 UTC
Labels: Bug, OSX
