### ISSUE TITLE
SAO Breakage (Affects Lua API)

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#9528] opened 2020-03-20 17:54 UTC
Having recently `git pull`ed my server to latest HEAD, I noticed that its been subjected to multiple crashes all involving SAOs.

Functions like `get_velocity()`, `get_yaw()`, etc. now seem to return `nil` a lot, rather than valid tables/values. This has broken a lot of things, especially the `mobs_redo` mod. Pretty much anything to do with entities, actually.

I've reset my server back to 4eb3baa51ed95d7661bbeecbbdf040d51ac32187 (February 1, 2020), prior to `git pull`, in the hope that this fixes the problem. I'll know for sure if the crashes don't happen again for a day or two.

Looking around in the commit log after that point, I found that SAOs were updated: 91eef646a59575bd9ae792e257bb6ad12fafc0b1

It seems that `getluaobject` is now much more strict about returning NULL ....

**Comment by sfan5** [comment] 2020-03-20 19:46
> This has broken a lot of things, especially the `mobs_redo` mod.

The code in Mobs Redo has been querying and modifying entities after deleting them. There is no reason for that to work, but it did in the past.
This has been fixed in mobs_redo [in the meantime](https://notabug.org/TenPlus1/mobs_redo/commit/ad5b444b657b5f7b9b7fe56a2ccb381eb2392b6e).

> Pretty much anything to do with entities, actually.

I'm interested to hear any breakage with mods that aren't mods_redo.

see also the discussion in #9390

**Comment by LoneWolfHT** [comment] 2020-03-20 19:56
The End is broken by this
`/mods/items/weapons/weapon_api/proc.lua:99` causes a crash when fighting the monsters in the game

**Comment by sfan5** [comment] 2020-03-20 20:40
The code [there](https://notabug.org/NetherEran/The_End/src/master/mods/items/weapons/weapon_api/proc.lua#L104) assumes the entity still exists so it can check whether the mob died after punching. Easily fixed by checking if `get_luaentity()` returns nil.

**Comment by BluebirdGreycoat** [comment] 2020-03-20 23:10
Regarding the discussion in #9390, I have always assumed that `self.object:remove()` just set a flag on the object so that it would be removed once the `on_step`, etc. callback returned. I feel like the API document used to say this but I can't point to the relevant commit.

One of the broken mods is `itemburn`, which works by overriding the builtin item definition and overriding the `on_step` method. The custom method calls the builtin function before running its own logic. Obviously, the builtin method can call `self.object:remove()`, which causes code like this to break.

Is there a `self.object:is_valid()` method I can call to see if the objref is still valid in cases like these?

**Comment by sfan5** [comment] 2020-03-21 11:48
> Is there a self.object:is_valid() method I can call to see if the objref is still valid in cases like these?

Not directly, but you can check `get_luaentity() ~= nil` to see if the entity has not been removed.

**Comment by FreeLikeGNU** [comment] 2020-04-11 16:54
Attempting to check `get_luaentity() ~= nil` threw an error:

> AsyncErr: ServerThread::run Lua: Runtime error from mod 'goblins' in callback luaentity_Step(): ...e/rachael/dev/minetest/bin/../mods/mobs_redo/api.lua:990: attempt to call global 'get_luaentity' (a nil value)

**Comment by rubenwardy** [comment] 2020-04-11 16:58
get_luaentity() is an ObjectRef function. You want to do   `self.object:get_luaentity()` from a entity def

**Comment by FreeLikeGNU** [comment] 2020-04-11 17:25
thank you!

**Comment by gpcf** [comment] 2020-04-13 23:14
also affected: walkways mod and myArcade pacmine ghosts

**Comment by gpcf** [comment] 2020-04-13 23:17
Traceback from myArcade:
```
2020-04-14 01:15:43: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'pacmine' in callback luaentity_Step(): ...inetest-server/.minetest/mods/myArcade/pacmine/ghost.lua:39: bad argument #1 to 'sin' (number expected, got nil)
2020-04-14 01:15:43: ERROR[Main]: stack traceback:
2020-04-14 01:15:43: ERROR[Main]:       [C]: in function 'sin'
2020-04-14 01:15:43: ERROR[Main]:       ...inetest-server/.minetest/mods/myArcade/pacmine/ghost.lua:39: in function 'set_velocity'
2020-04-14 01:15:43: ERROR[Main]:       ...inetest-server/.minetest/mods/myArcade/pacmine/ghost.lua:126: in function <...inetest-server/.minetest/mods/myArcade/pacmine/ghost.lua:42>
```

**Comment by gpcf** [comment] 2020-04-13 23:30
I can confirm that in myArcade it's caused by poor coding and trying to reuse dead entities.

**Comment by hecktest** [comment] 2020-06-02 15:30
Throwing a meaningful error ("Trying to get the velocity of a deleted object") instead of dumping nil would make it a lot easier to catch those bugs.

**Comment by paramat** [comment] 2020-07-02 23:54
^ Perhaps we should do this, as it will be a common error?

**Comment by rubenwardy** [comment] 2021-01-08 15:34
closing as there's been a few releases with this. Really, this situation should be avoided in the future

**Closed by rubenwardy** 2021-01-08 15:34 UTC
Labels: @ Script API, Possible close, Question
