### ISSUE TITLE
Add multiple server lists

### ISSUE THREAD

**Issue by Xeno333** [minetest/minetest#15050] opened 2024-08-24 23:48 UTC
### Problem

There is only one server list, this miss-represents ping time in some parts of the world, and it makes minetest public servers centralized, which seems to go against the idea of free for everyone and fully customisable.

### Solutions

Client side: Add a sellection box for "Official" serverlists and a "custom" for third-party server-lists.
Server side: Add a setting "anounce_to" that is a list of adresses to anounce the server to.

This will allow for "Europian server list" "North Amarican server list", etc.

This would allow server lists to be able to more clearly represent ping time to users.

### Alternatives

None

**Comment by Zughy** [comment] 2024-08-25 10:34
Duplicate of #14246

**Closed by Zughy** 2024-08-25 10:34 UTC
Labels: Feature request
