### ISSUE TITLE
Android: Very slow world loading times

### ISSUE THREAD

**Issue by Atssen** [minetest/minetest#11118] opened 2021-03-24 20:34 UTC
Probably everybody know minetest's mobile optimisation is bad. So i open this for make a better optimisation

**Comment by SmallJoker** [comment] 2021-03-25 07:00
Please narrow down what exactly is bad:

 * Gameplay/controls
 * User interface
 * Speed -> do mod profiling and analyze that

Marking as "Possible close" because this issue contains (as of now) no precise request.

**Comment by Adnan1091** [comment] 2021-03-26 20:01
The mobile optimization is terrible. I'm not sure if it has anything to do with the engine (irrlicht). It's still terrible at handling mods, so there's an immediate fps drop and stutter. Minetest should be able to handle mods better.

**Comment by NathanSalapat** [comment] 2021-03-27 01:26
What mods are you using? Maybe it's an issue more so with those than with Minetest itself.

**Comment by Adnan1091** [comment] 2021-03-27 10:22
Nope,the mods i use are commonly from minetest mods team which they make good mods.I think they optimize them.Other than that i use mobkit,mob_core mobs,smoke and tree capatitor mod.

**Comment by Atssen** [comment] 2021-03-27 13:46
I generall use one or two mod and they not big

**Comment by Atssen** [comment] 2021-03-27 13:48
And i use a Samsung galaxy Tab so i don't use a bad device

**Comment by Atssen** [comment] 2021-03-27 13:50
I asked this in minetest discord and creators of minetest already know this but they say they not have time for this. So i open this.

**Comment by Atssen** [comment] 2021-03-27 13:56
World loading is generally take nearly 10 minute in my device. And in game sometimes game crash and lag.

**Comment by NathanSalapat** [comment] 2021-03-27 15:22
Using the smoke mod on mobile. Wonder if that could possible be the problem. That aside you really still haven't given us much to work with. Does it take nearly ten minutes to load MTG without any mods?
Check and make sure that you don't have any other apps running. Chances are the device just doesn't have enough ram or free space to run Minetest well.

Disclaimer; I have a computer and never use Minetest on a phone/tablet.

**Comment by Adnan1091** [comment] 2021-03-27 16:12
Tested only with smoke mod and haven't experiences any difference.The minetest or irrlicht is the problem for optimization then.

**Comment by SmallJoker** [comment] 2021-03-27 18:21
Please update to 5.4.0. There were a few changes that might have affected the media loading on world join. If the problem persists using a 5.4.0 client, try the following

1. Create a new world using the same mods, and re-create this performance issue
2. Disable all additional mods and rejoin
3. Is the issue gone now? If yes, proceed like so:
4. Enable one mod, and join the world again
5. Repeat until the performance issue appears
6. Now you know the "bad mod" that causes the issue

Alternatively you can profile your existing world like so:

1. Main menu -> Settings -> All settings
2. `profiler.load` -> Search
3. Activate the setting `Load the game profiler`
4. Join your game and wait a minute to collect statistics in the background
5. Run the command `/profiler save`
6. Close Minetest and locate the file `profile-????.txt` within your world's folder (location is printed to chat)
7. Upload the file or check it on your own. It should contain information about which mod performed worst.

**Comment by SmallJoker** [comment] 2021-03-27 18:26
This might also be a duplicate of #9107. To narrow that down, remove the old `debug.txt` file and change the setting `debug_log_level` to `verbose`. Investigate the newly generated `debug.txt` output afterwards, and change the setting value back to `action`.

**Comment by Atssen** [comment] 2021-03-28 05:21
But I see this issue also in servers and servers not include any engaged mod. But I open servers in nearly 10 minute and they are generally crash. I can only play for 3-5 minute

**Comment by Atssen** [comment] 2021-03-29 21:15
Am i close this issue because nobody say a thing.

**Comment by NathanSalapat** [comment] 2021-03-30 00:27
Again I don't use mobile, but sounds like you don't have enough ram.

**Comment by Adnan1091** [comment] 2021-03-30 11:41
This issue is just being ignored.It  have to be solved.Or else,people will continue to open these kind of issues on git.

**Comment by minecraftchest1** [comment] 2021-06-04 00:24
I justed on my Samsung a10e with minetest game, 5 second load time with no mods.

**Comment by minecraftchest1** [comment] 2021-06-04 00:29
Same device with mineclone2 and the mods in the attached screenshot, 38 second load time. I also got the errors in the other screenshot, but I don't know if that is related.

**Comment by minecraftchest1** [comment] 2021-06-04 00:33
Same device, only mineclone2 on a new world with default settings gives 37 second load time.

**Comment by minecraftchest1** [comment] 2021-06-04 00:41
Tried profiling, but got a permission error. ![Screenshot_20210603-193951_Minetest.jpg](https://user-images.githubusercontent.com/42992675/120728965-9e54c100-c4a3-11eb-9554-26882f50fabb.jpg)

**Comment by rubenwardy** [comment] 2021-06-16 12:42
The slow world loading is a known issue, it's #9107

**Comment by sfan5** [comment] 2021-06-16 15:35
Is this on armeabi-v7a? Although there is nothing preventing it from occurring there we haven't had any reports of it.

**Comment by rubenwardy** [comment] 2021-06-17 17:06
This sounds exactly like the arm64 issue, so if I were to guess then I'd say they're using that. Remember that the play store version has both 32 and 64bit versions, and will prefer 64bit over 32bit

**Comment by Atssen** [comment] 2021-06-21 05:07
![Screenshot_20210621_080717.jpg](https://user-images.githubusercontent.com/79864885/122709830-bc723d80-d267-11eb-85a1-02487d68bbfd.jpg)

**Comment by Atssen** [comment] 2021-06-21 05:07
![Screenshot_20210621_080709.jpg](https://user-images.githubusercontent.com/79864885/122709844-c5fba580-d267-11eb-80f1-75a43ecbdf85.jpg)

**Comment by Atssen** [comment] 2021-06-21 05:08
İ finally found my phone's system specs

**Comment by Atssen** [comment] 2021-06-21 05:10
Also it is Android 10

**Closed** 2021-09-24 10:37 UTC
Labels: Android, Possible close

**Comment by Atssen** [comment] 2021-09-24 14:01
![Screenshot_20210621_080717.jpg](https://user-images.githubusercontent.com/79864885/134687263-d5d69e5a-0c08-47b3-ad66-74553e72e212.jpg)

**Comment by Adnan1091** [comment] 2021-09-25 08:39
Why it is closed?Is it fixed?

**Comment by Atssen** [comment] 2021-09-25 10:26
Yes, probably. I tried scoped android minetest and now i can run minetest without crash.

**Comment by Adnan1091** [comment] 2021-09-25 19:13
Sonunda.

**Comment by Atssen** [comment] 2021-09-25 19:44
> Sonunda.

Şeyy.. bu türkçe bir repo değil ve turk olduğumu nerden bildin?
(Not important)
