### ISSUE TITLE
Being able to use custom 3D models for items

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#5062] opened 2017-01-17 16:48 UTC
The title says it all I basically want to have the possibility to use custom 3D models for tools/craft items
 (I know there is a trick for this by usung a block but I'm not interested in that)

**Comment by stujones11** [comment] 2017-01-17 19:06
It is already possible for nodes, that is the 'trick'. I guess it should not be difficult to extend that support to tool/craft items and fully support that idea.

**Comment by tobyplowy** [comment] 2017-01-17 20:44
@stujones11 yes That's The Spirit!

**Comment by Taose** [comment] 2017-01-17 21:06
When you say custom 3d models? 

Do you mean something like...an actual spheroid apple?

**Comment by tobyplowy** [comment] 2017-01-17 21:20
@Taose it's a 3d model you can do with 3D Models What You Want
(so yes If someone programs this that will be possible)

**Comment by D00Med** [comment] 2017-01-18 20:39
I would also like this, although like stujones11 said, the node trick can be used for this

**Comment by stujones11** [comment] 2017-01-20 18:13
The main disadvantage of that trick is that a tool item cannot take wear in the conventional manner.

**Comment by octacian** [comment] 2017-01-20 19:41
I'd like to see this too. @jordan4ibanez recently made a mod that used an actual 3D model for the hand using the node trick. But, there's another disadvantage. Aside from not being able to take wear, when you right click, Minetest will place the node. So yeah, 3D models for items would be really useful as 3D hands would then be much easier to make and would function more smoothly.

**Comment by tobyplowy** [comment] 2017-01-20 19:49
@octacian yes I saw that video and I was already thinking about making this issue a while ago but never got around to it and that video was the final straw for me (why has no one reported this already?)

**Comment by D00Med** [comment] 2017-01-20 20:18
>right click, Minetest will place the node

Can't that be replaced with a function though?(like one that does nothing)

**Comment by tobyplowy** [comment] 2017-01-20 20:20
@D00Med try to stay on topic please :D

**Comment by D00Med** [comment] 2017-01-20 20:23
? that's on topic xD

**Comment by tobyplowy** [comment] 2017-01-20 20:25
@D00Med yes but I'm asking for models for items Not for the block trick XD

**Comment by Wuzzy2** [comment] 2017-01-21 13:20
Yes, this is a very good idea. It should obviously not only affect the image in the inventory, but also when dropped on the ground or wielded in the hand. Best of all, if all 3 cases can be manually overwritten by the modder for maximum flexibility.

I think the 3D model could be done in a similar manner like nodes? E.g. possible would be full cube, flat image (what we currently have), nodebox, mesh. I think some standard types should be supported for convenience; I would hate to be forced to use a mesh just for a simple cube.

**Comment by sofar** [comment] 2017-01-24 22:14
I suppose this would be a `wield_mesh` instead of a `wield_image`. If the node itself already is a mesh node, it could just use textures and mesh of that, but you still would have to specify size and rotation.

If the item is not a node, but a tool or a craftitem, you would have to specify attachment vectors (size, rotation, location) and tiles.

So to do this as generic as possible, it would be a significant extension of the API.

**Comment by stujones11** [comment] 2017-01-25 22:21
I was thinking more on the lines of giving items an optional `visual` and `mesh` property but I'm easy.

>  you would have to specify attachment vectors (size, rotation, location) and tiles.

That is probably not such a bad idea if we ever want to properly support visible hand-wielded items.

**Comment by tobyplowy** [comment] 2017-01-29 00:35
@paramat @Fixer-007 @tenplus1 can you guys please take a look at this

**Comment by tobyplowy** [comment] 2017-01-29 00:40
@paramat @Fixer-007 @tenplus1 can you guys please take a look at this

**Comment by rubenwardy** [comment] 2017-08-26 03:44
duplicate of #3551

**Closed by rubenwardy** 2017-08-26 03:44 UTC
Labels: Request / Suggestion
