### ISSUE TITLE
Slippery nodes are no longer slippery

### ISSUE THREAD

**Issue by grorp** [minetest/minetest#15375] opened 2024-11-03 10:16 UTC
### Luanti version

5.10.0-dev

### Summary

Slippery nodes are no longer slippery. Bisected to cb6c8eb2f013edfe127ce18f760c432aee5aba01.

### Steps to reproduce

Walk on ice in Minetest Game.

**Comment by Zughy** [comment] 2024-11-03 10:40
Isn't this the same as #15196 ? Or is it just worse now?

**Comment by grorp** [comment] 2024-11-03 11:15
#15196 is older than the regression commit I identified, so not a duplicate (but could still be the same underlying issue or something)

**Comment by SmallJoker** [comment] 2024-11-03 11:47
How to reproduce / test:

![image](https://github.com/user-attachments/assets/5a325077-4955-4d9a-9e24-82f3e66ec86e)

```Lua
local function make_slippery(name, howmuch)
	assert(type(howmuch) == "number")
	local def = core.registered_nodes[name]
	def.groups.slippery = howmuch
	minetest.override_item(name, {
		groups = def.groups
	})
end


make_slippery("default:dirt_with_grass", 4)
make_slippery("default:sand", 3)

core.register_chatcommand("pushz", {
	func = function(name)
		local player = core.get_player_by_name(name)
		local yaw = player:get_look_horizontal() * 180 / math.pi
		local v = 10
		if yaw > 360 - 45 or yaw < 45 then
			player:add_velocity({x = 0, y = 0, z = v})
		elseif yaw < 180 - 45 then
			player:add_velocity({x = -v, y = 0, z = 0})
		elseif yaw < 180 + 45 then
			player:add_velocity({x = 0, y = 0, z = -v})
		else
			player:add_velocity({x = v, y = 0, z = 0})
		end

	end
})
```

1. `default:sand` and `default:dirt_with_grass` line
2. Walk to the cobblestone stopper
3. F5 for position information
4. Look into movement direction
5. `/pushz`
6. Calculate the distance travelled (pos_new - pos_old)

**Comment by SmallJoker** [comment] 2024-11-03 12:06
Root of the problem:

https://github.com/minetest/minetest/blob/e952a0807b85e089eaa320cfeb09e33816d141ed/src/collision.cpp#L547-L554

`is_collision` is always `false`, resulting in `m_standing_node` never being assigned unless sneaking. Turns out sneaking does indeed get the slippery effect back.

**Comment by appgurueu** [comment] 2024-11-03 15:34
I may try to fix this by doing a proper collision time calculation taking acceleration into account, reverting the original PR, but still fixing the issue it addressed in a mathematically correct way. I've done that for you in my https://github.com/appgurueu/minetest/tree/contentdb-url-bugfix branch, but it seems I can't force push to this branch since edits by maintainers aren't allowed. (A simple PR won't work either, since this is a rebase.)

**Comment by kno10** [comment] 2024-11-05 09:25
I would assume this is #15196, just more frequently happening now with the improved collisions code.

Might be related to this condition (predating cb6c8eb2):
https://github.com/minetest/minetest/blob/e952a0807b85e089eaa320cfeb09e33816d141ed/src/collision.cpp#L548-L549

The new collision code may more frequently trigger this condition: it recognizes the collision with the floor is instant, and hence the velocity is unchanged. But slippery likely relies on this kind of collision detection.

**Comment by kno10** [comment] 2024-11-05 10:06
Slippery handling may also be affected by #15235.

Consider standing halfway on a solid and on a slippery node. You probably want to have slippery when you are slightly more on one side, and non slippery when slightly more on the other side. Right now, it may well be that the node with the lower coordinate may win, not the closer node.

On the other hand, consider standing on a slippery cliff edge - even when you are already over the edge, and you have air underneath, it is still the collision node that should affect movement.

**Closed** 2024-11-10 12:20 UTC
Labels: Bug, Blocker, @ Server / Client / Env., Regression
