### ISSUE TITLE
Block already contains x number of object error.

### ISSUE THREAD

**Issue by za267** [minetest/minetest#8564] opened 2019-05-26 15:22 UTC
##### Issue type
 - Bug report

 
##### Minetest version
```
5.1.0
```

##### OS / Hardware

Operating system: Fedora 29 on Virtualbox
CPU: Intel i7-4790

##### Summary
Getting an error in the logs: 
```
WARNING[Server]: ServerEnv: Trying to store id = 0 statically but block (-26,3,-105) already contains 3709 objects
```
I really have no idea how that is getting in there, or even what it means.  I've done a bit of quick research on this and found this issue: https://github.com/minetest-mods/digilines/issues/50 but it doesn't seem to be related.

The block at that location does not appear to 'exist' in terms of  it having ever been placed, dug, or any such action.

##### Steps to reproduce
Unknown as of yet.

**Comment by SmallJoker** [comment] 2019-05-26 15:37
Duplicate of #8428 #1231 and #194

Increase the setting `max_objects_per_block` if you're sure it's not a mod bug. This feature prevents your map from storing insane amounts of entities.

**Closed by SmallJoker** 2019-05-26 15:37 UTC
