### ISSUE TITLE
let the server check and fix the brightness of areas and stuck liquids

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest#3772] opened 2016-02-23 11:04 UTC
Hi, since the real popular moretrees mod by @VanessaE causes lightbugs on mapgen or sapling grow (#3455), i think its a good idea to add a mechanism to check loaded areas of their brighness level and fix if necessary.

Our server for example had generated a bunch part of the map to have an clean cut after switching the mapgen to v7. Now i have to fly around an fix all the damn lightbugs, every second chunk.
(There is a [small mod](https://forum.minetest.net/viewtopic.php?f=9&t=10662&p=201614) out there)

![screenshot_20160223_120923](https://cloud.githubusercontent.com/assets/10698140/13249746/522fdca0-da26-11e5-93f1-249c4d2218ac.png)

![screenshot_20160223_121727](https://cloud.githubusercontent.com/assets/10698140/13249954/75425f78-da27-11e5-9b9b-0e3fdb6adb8b.png)

A feature like that would be nice...best regards :)

**Comment by everamzah** [comment] 2016-02-23 11:27
Default Minetest Game does this also.

**Comment by paramat** [comment] 2016-02-23 14:21
It might be good to have a way to re-trigger the lighting calculation for a mapchunk, but then this can be done by a mod using voxelmanip and 'calc_lighting', it will be fast.
The lighting bugs of moretrees in mgv7 etc is the fault of the mod, it should not be using l-system tree generation during mapgen. Instead use the mod option to place all trees as saplings.

**Comment by VanessaE** [comment] 2016-02-23 14:49
As @tchncs stated, it's apparently happening with sapling-based trees also, which means it's an ABM that's spawning the tree, and thus it's happening OUTSIDE of the on-generated callback.

Broken engine lighting is NOT a fault of the mod!  If the engine can't handle a spawn_tree() call without screwing up, it's the engine's fault, especially if the problem can be reproduced with vanilla minetest_game as @everamzah said.  Nevermind that it doesn't happen at all with mapgen v6.

**Comment by paramat** [comment] 2016-02-23 15:08
Yes, the engine's 'update lighting' sometimes causes lighting bugs when schematics are spawned, this needs attention.
Vanessa what i mean is, it's the mod's fault because it is triggering 'update lighting' in l-system at mapgen time, i agree this should be more robust and needs fixing but 'update lighting' is designed for use after mapgen.
Ideally l-system sould have a variant without lighting calculations for use during mapgen, but the trees would be limited to 16 nodes above the mapchunk.

**Comment by VanessaE** [comment] 2016-02-23 15:43
Again, this is NOT triggering during mapgen.  It's triggering sapling growth during an ABM.

**Comment by tchncs** [comment] 2016-02-23 16:05
And i dont think its low-prio. 
Player dislike it, and be sad about it and the admins have to come to fix it. 
(if the admins found a solution like the mod i linked).
And its not just in v7, its in v6 also like the linked issue shows.
Its a full time job to check out the map and maybe fresh generated parts from players for shadowoceans and its surely doesnt make someone fun!

**Comment by paramat** [comment] 2016-02-24 00:11
Vanessa i know it's happening on sapling growth:
> the engine's 'update lighting' sometimes causes lighting bugs when schematics are spawned

Moretrees spawns l-system trees very soon after mapgen i know, but it's soon enough that the mapchunk above has not yet been generated, this is the cause of the shadows, along with the non-mgv6 mapgens having 1 up 1 down overgeneration.

tchncs, use the Moretrees option to place trees as saplings that grow later, this should help.

**Comment by tchncs** [comment] 2016-02-26 11:16
> tchncs, use the Moretrees option to place trees as saplings that grow later, this should help.

I will try, but its too late for a very very big area because we generated a big world to switch the mapgen after that.

![](https://files.illuna-minetest.tk/mapshots/daily_small.jpg)

**Comment by tchncs** [comment] 2016-02-26 11:34
Maybe i understood something wrong, but, i enabled the option and saw youngtrees...i believe there growed into big trees and produced the shadows also.

**Comment by 0-afflatus** [comment] 2016-02-26 12:15
I don't think this should be regarded as a feature request. The lighting issue is a bug, this may not be the right way to fix it (neither is it a low priority for many of us). Update_lighting should wait until the mapchunk, schematics and / or l-system decorations are loaded or something similar. 

BTW /mapfix is usable by players, so it doesn't require admins to do all of it. At the moment this is our best workaround.

**Comment by paramat** [comment] 2016-02-26 20:28
> The mod linked to has the right idea, for speed it could be an item with 'on use' that automatically sets minp maxp to the mapchunk corners, then just fly into the mapchunk and use the item.

This is the best thing to do.

This is low priority because:
It is caused by a mod, the mod should detect mgv7 and automatically switch to placing saplings.
There is a way to fix shadows using a mod which will be fast, almost as fast as an engine fix.
Shadow bugs caused by growing saplings are already marked as high priority to fix.

**Comment by 0-afflatus** [comment] 2016-02-27 16:09
OK, I'm with you.
This idea is hacky anyway.

**Comment by ShadowNinja** [comment] 2016-02-27 16:26
Shouldn't L-system trees just use the mapgen lighting function if they're running during mapgen?  If not, perhaps there should be an after_generated function for this so you don't have to place saplings with node timers or something like that.

**Comment by paramat** [comment] 2016-02-27 19:55
> Shouldn't L-system trees just use the mapgen lighting function if they're running during mapgen?

We could have a variation of l-system that has no lighting update, run this multiple times in a mod's on-gen functtion, then do one big lighting update.

There were plans to add l-system trees to the decoration API, however because this uses the mapgen voxelmanip no tree can exceed 16 nodes in height otherwise it gets chopped at mapchunk top + 16 nodes.
Perhaps ideally we use a non-mapgen-object voxelmanip in a mod's on'gen function, add multiple l-system trees to that, then do a sinlge calc_lighitng on that voxelmanip.

**Comment by Fixer-007** [comment] 2016-03-02 20:26
let the server check and fix the brightness of areas** and stuck liquids** :)

**Comment by paramat** [comment] 2016-03-03 19:42
We are already working on updating stuck liquids in other issues.
This can be left open for a while for the discussion but remember that the original request ..
> add a mechanism to check loaded areas of their brighness level and fix if necessary.

.. is impossible. There's no way to logically decide whether lighting is correct, only a human can decide that.

**Closed** 2016-03-04 06:42 UTC
Labels: can't fix, feature request

**Comment by paramat** [comment] 2016-03-04 19:17
VanessaE > wtf are you thinking, paramat?  if you can't fix that bug then find someone who can.
(of course I refer to the root problem, not tchncs' idea)

I'm referring to this, which is impossible:
> add a mechanism to check loaded areas of their brighness level and fix if necessary.

**Comment by PilzAdam** [comment] 2016-03-05 15:47
@paramat can you also open a new issue for the shadow bugs that appear when placing schematics in ABMs / placing L-system trees? This is rather high priority, since it happens in vanilla minetest_game.
