### ISSUE TITLE
Water column blinking (rendering)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3603] opened 2016-01-22 22:02 UTC
Any area that have water columns above ground has random water blinking issues in a lot of circumstances. Reasons unknown. Bug is very notorious and annoying. Please fix!

**Comment by est31** [comment] 2016-01-23 00:50
dupe of #1404

**Closed by est31** 2016-01-23 00:50 UTC

**Comment by 0-afflatus** [comment] 2016-02-17 07:05
All semi transparent nodes have blinking issues. It's well known.
