### ISSUE TITLE
get_bone_position change the bones

### ISSUE THREAD

**Issue by runsy** [minetest/minetest#9870] opened 2020-05-15 21:11 UTC
Two issues:

- This instruction to get the bone position & rotation, causes changing then :-D

Also if:
```
bone_pos, bone_rot= get_bone_position
set_bone_position(bone_pos, bone_rot)
```

It causes issues too.

##### Minetest version
v5.3-dev

##### OS / Hardware
Linux

##### Steps to reproduce
`position, rotation = self.object:get_bone_position("bone")`

**Comment by oilboi** [comment] 2020-05-15 23:18
I can confirm this bug as I have to do this https://github.com/oilboi/Crafter/blob/master/mods/mob/init.lua#L38 for all mobs

**Comment by oilboi** [comment] 2020-05-15 23:18
get_bone_position by default simply returns {x=0,y=0,z=0} and then resets the position to the base of t he model's bone position, breaking it completely

**Comment by KaylebJay** [comment] 2020-05-15 23:43
Can confirm this also with my testing function for rotation of mob heads.

**Comment by runsy** [comment] 2020-05-15 23:50
So, please put high priority to this :-)

**Comment by sfan5** [comment] 2020-05-16 09:31
duplicate of #9445

**Closed by sfan5** 2020-05-16 09:31 UTC
Labels: Unconfirmed bug
