### ISSUE TITLE
Mods: Improve error messages on circular dependencies / cycles

### ISSUE THREAD

**Issue by debagos** [minetest/minetest#9977] opened 2020-06-01 19:01 UTC
Hi :)
##### Minetest version

```
5.0.0 - 5.5.0-dev
```
##### The problem

https://github.com/minetest/minetest/blob/42a9b45c21ad407689950e3a4c90cb3894142260/src/content/mods.cpp#L336
The `resolveDependencies()` function here can't handle circular dependencies.
##### Steps to reproduce

Create two new mods called **mod_1** and **mod_2**. Add `optional_depends = mod_2` to the first _mod.conf_ and `optional_depends = mod_1` to the second _mod.conf_. None of the new mods will get executed (despite that the dependencies are optional!), as well as any other mod that depends (even just optional depends) on one of these two mods.
You will get error messages like:

> ERROR[Main]: mod "mod_1" has unsatisfied dependencies:  "mod_2"
>ERROR[Main]: mod "mod_2" has unsatisfied dependencies:  "mod_1"
##### Summary
Honestly, I have no idea how to fix this issue and I'm aware that this is super hard to fix, probably even unfixable. But, a warning about circular references would be nice instead of failing completely and creating an unmet dependencies hell.

Greetings.

**Comment by SmallJoker** [comment] 2020-06-01 19:23
Relevant https://github.com/minetest-mods/moreblocks/issues/155

Problem here is that optional and hard dependencies are handled the same way. Mods expect that its dependencies are always loaded afterwards - which is currently sometimes not feasible.

**Comment by rubenwardy** [comment] 2022-05-08 03:15
Duplicate of #3330

**Closed by rubenwardy** 2022-05-08 03:15 UTC
Labels: Feature request, @ Content/PkgMgr
