### ISSUE TITLE
Bottom of sky box should be fog colored

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#4744] opened 2016-11-06 16:17 UTC
Fly high or looking down from a mountain the bottom of the sky box is revealed and rather than fog it is sky colored.

![screenshot_20161106_081638](https://cloud.githubusercontent.com/assets/446130/20039459/22e65346-a3f9-11e6-955a-1d61eecfc0e2.png)

Looking at the code in sky.cpp I do not see any place where the bottom pane is drawn, so I assume it is not actually drawn and just happens to be default color and it just looks like a square before the fog box we draw on the sides.

**Comment by Wuzzy2** [comment] 2016-11-07 11:49
Yes, I can confirm this, this has been a bug since … ever? :D 
I dislike it very much, too, it makes the skybox visible. :-(

**Comment by paramat** [comment] 2016-11-07 12:38
I guess it's from mgv6 days when that was never seen.

**Comment by paramat** [comment] 2016-11-08 15:34
#4747 merged.

**Closed by paramat** 2016-11-08 15:34 UTC
Labels: @ Client / Audiovisuals, Feature request
