### ISSUE TITLE
Air bubbles not showing up under water

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest#3901] opened 2016-03-22 12:56 UTC
With enable_damage = true, and a player under water, the air bubbles are not showing up and no suffocation is occurring.  A player is able to stay underwater indefinitely.

**Comment by everamzah** [comment] 2016-03-22 12:56
![screenshot_20160322_085200](https://cloud.githubusercontent.com/assets/1761623/13952284/f7810c4c-f00b-11e5-9810-907653a53b39.png)

**Comment by PilzAdam** [comment] 2016-03-22 16:58
Marked as blocker because a very visible feature is broken.

**Comment by ssieb** [comment] 2016-03-22 18:42
This is intermittent.  I haven't been able to determine what causes it, but I think taking damage or eating something makes the bubbles happen again.

**Comment by ObaniGemini** [comment] 2016-03-22 18:59
Yes, this happened a month ago too to @Fixer-007 and we could experience the same bug

**Comment by kilbith** [comment] 2016-03-22 19:19
Indeed, something is broken with the bubbles. Example here when I'm on the ground (keeping stuck with 3 bubbles) : 

![screenshot_20160322_201728](https://cloud.githubusercontent.com/assets/7883281/13964695/484aaee4-f06b-11e5-88cb-6c071c57ac74.png)

Some way to reproduce : get out of the water with e.g. 1 bubble remaining, then leave the game right after that, re-connect. It will regain 2-3 bubbles then sticking with bubbles in HUD all the time.

Also : sometimes the bubbles show up when I'm underwater, sometimes not...

**Comment by C1ffisme** [comment] 2016-03-22 19:39
I have had a bug like this occur to me before, but I can still drown even if the bubbles do not show.

**Comment by Kinokoio** [comment] 2016-03-25 03:58
I another use case for this bug. It occurs every time damage is enabled. This could be either at in-game or when entering a world where damage was disabled or it was just created. Only after taking damage the drowning feature will have effect. I build an entire house and left the character three hours to check the bug.

Making the character take a 0 damage when damage is enabled may be a workaround. I'll check it out.

**Comment by paramat** [comment] 2016-03-25 05:07
We had a long running problem with damage a while ago, this may be related.

**Comment by Kinokoio** [comment] 2016-03-25 05:32
I am testing for other test cases. I tested it using 2 instances of the same application over the loopback interface. Only the host is immune to drowning when this happens. All the guests behave correctly. 

There were times where the host spawned underground, though.

**Comment by paramat** [comment] 2016-03-25 06:06
There were some damage fixes here by Zeno https://github.com/minetest/minetest/commit/c552d293fa340a1484d0b918b3341d7d141e7931

**Comment by paramat** [comment] 2016-03-25 06:12
here's the issue for the damage bug https://github.com/minetest/minetest/issues/2501
Was fixed around 10th July by kwolekr https://github.com/minetest/minetest/commit/1a1774a1051790ef85b1bd8b047ac45a3676b5d6

**Comment by kilbith** [comment] 2016-03-25 09:04
The damage flash and drowning are completely different stuff. The drowning worked just fine in 0.4.13-stable.

**Comment by kwolekr** [comment] 2016-04-11 07:31
I can't reproduce the issue using the method @kilbith described.

**Comment by paramat** [comment] 2016-04-11 07:45
Can't reproduce even when trying the various methods of reproduction.

**Comment by Fixer-007** [comment] 2016-04-11 12:53
Try this way: find 0.4.12 server, connect to it, _avoid any damage_, find water, sink down, if bubbles still appear, do logout, relogin and observe again. I was able to reproduce that few weeks ago, but target server was updated since then.

**Comment by kilbith** [comment] 2016-04-11 13:54
I've had a long and hard moment trying to reproduce the bug again, without success. Seems self-fixed now.

**Comment by kwolekr** [comment] 2016-04-11 16:12
Or, like Fixer-007 just mentioned, it might be caused by a protocol incompatibility between differing client and server versions we weren't aware of.

**Comment by paramat** [comment] 2016-04-11 22:04
@everamzah were you connecting to an old server to reproduce this? or an up to date server or singleplayer?

**Comment by everamzah** [comment] 2016-04-11 23:44
@paramat I was using `minetestserver` and `minetest --go --address 127.0.0.1`

I just did a quick test on 3b43e7e and bubbles appear A-OK.  I will try again with a fresh HEAD and on different computers/OS versions, but nonetheless it seems repaired.

**Comment by paramat** [comment] 2016-04-12 23:08
Possibly no longer a blocker.

**Comment by nerzhul** [comment] 2016-04-13 15:55
don't seem to be a block because it occurs rarely, not everytime

**Comment by paramat** [comment] 2016-04-15 04:38
Possibly not a milestone either.

**Comment by paramat** [comment] 2016-04-17 21:27
Removed from milestone.

**Comment by Wuzzy2** [comment] 2016-07-29 10:57
I think this bug is probably fixed by now, I have not seen it at all in 0.4.14.

**Closed** 2016-07-29 13:01 UTC
Labels: Unconfirmed bug
