### ISSUE TITLE
Items can be thrown through nodes

### ISSUE THREAD

**Issue by jmf** [minetest/minetest#802] opened 2013-07-02 12:26 UTC
Items can be thrown through nodes if the player is standing in front of them.
To repeat this behaviour, place a wall somewhere and throw an inventory item with "Q". 
The item will cross the wall and come out on the other side.
This behaviour has also been experienced with doors. When using mesecons and metal doors, this can be a problem when making oneway doors. People could simply throw items through the door or walls on the switch.

**Comment by est31** [comment] 2015-06-30 15:59
As #773 is merged, can we apply @PilzAdam 's patch?

**Comment by est31** [comment] 2015-07-23 04:27
It needs a proper fix IMO which checks for air at the given position, and falls back to the current player's position. Its natural that items spawn not inside nodes.

**Comment by DS-Minetest** [comment] 2016-11-06 19:36
isnt this issue already fixed?
you cant throw items trough nodes anymore

**Comment by paramat** [comment] 2016-11-07 12:42
Maybe you have to be pressed up against the wall firsst?

**Comment by Fixer-007** [comment] 2016-11-07 17:25
I was pressed up against it, also tried with steel door... can't reproduce.

**Comment by paramat** [comment] 2016-11-07 17:28
Thanks, closing.

**Closed by paramat** 2016-11-07 17:28 UTC
Labels: @ Server / Client / Env., Bug, Possible close
