### ISSUE TITLE
Android build issues

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#6588] opened 2017-11-05 01:23 UTC
I had to make changes as found on my [android-1](https://github.com/rubenwardy/minetest/tree/android-1) branch.

Here is my local.properties

```
ndk.dir = /home/ruben/Android/Sdk/ndk-bundle/toolchains/
sdk.dir = /home/ruben/Android/Sdk/
```

The SDK and NDK was downloaded using Android Studio. This worked before iirc.

Here is my current progress:

```
export NDEBUG=;                                                            \
export BUILD_TYPE=debug;                                                   \
make apk
make[1]: Entering directory '/home/ruben/dev/minetest/build/android'
nothing to be done for freetype
nothing to be done for irrlicht
changed /home/ruben/dev/minetest/.idea/workspace.xml
assets changed, refreshing...
make[2]: Entering directory '/home/ruben/dev/minetest/build/android'
make[2]: Leaving directory '/home/ruben/dev/minetest/build/android'
cp: cannot stat '/home/ruben/dev/minetest/README.txt': No such file or directory
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/pack/pack-861ae1812935b26978e8b5ed5da880f0b8f74e0f.pack': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/pack/pack-861ae1812935b26978e8b5ed5da880f0b8f74e0f.idx': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/pack/pack-433f9be3e24c59d4b48d828c3a93180da81bf3d3.pack': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/pack/pack-433f9be3e24c59d4b48d828c3a93180da81bf3d3.idx': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/pack/pack-8b7bc4791eb2d6d67c27885bf1d67207a99b428f.pack': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/pack/pack-8b7bc4791eb2d6d67c27885bf1d67207a99b428f.idx': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/pack/pack-689ea7acda7cf7c5d5485394ce8210ede56707d4.pack': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/pack/pack-689ea7acda7cf7c5d5485394ce8210ede56707d4.idx': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/6c/18a6a3b9b994c645c5295e6b4d90d1bfe4609b': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/6c/cb5872a13f78e9d7b04a2277c0bc110164251c': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/6c/b174f60bfeaa1452faa203482332ea90cc6837': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/8f/bd5a54380d989589edef301acadd350c193b77': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/8f/2e67869fba6b48d260544e1585729a21ddd968': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/8f/1f3760f03fd25ca9912020ae607d7849cc425b': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/37/541cf3242e98b3245d1ceb63aec6293d5c34fd': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/37/f03212dd6f894587f26679fa50603c2dd5136b': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/37/a2c3a72f1d9410f64c21bb7369fb8a7b6d1ec9': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/37/3f3c8fb2ff9bc94956a9c8385a5b29f237c9d9': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/dc/e7537a762e89c64d783cdea5416e0be4b359c3': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/dc/0655fb95d8735c8a1022bc6c151c994e463f90': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/dc/e630da845c83f594e3545facd713ce15797c01': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/dc/68f1bd25c288b5102cd7c4d442acbcc6e2f6ac': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/dc/b8ba078012ec0f4f4f1564983dbb9c73d58581': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/74/abb6806220f38bac6a84eb14b35c82934b8d60': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/74/ed63f46ba8c86de1b30c53c2d9f8947a0cdd34': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/40/ed77185e68ac5de835055b98910a632fee0318': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/a1/d35f3d69dbed8cd9ce317a11f2bd2f7c816c75': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/c2/f3c99cad9c9a5c090ab76e653fa6b90b08215c': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/c2/e50ac919a2c92eb9c8aa66a65ef9d1cf3ecda2': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/c2/3e8706d4598379af24a88f9955161c7a5b2a54': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/48/baf1acb5ddc332a9441095e53dcba9e5bc2fd2': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/48/25448846ad01587c585f68c8cd5f48901620f0': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/48/052b6954f703b1445d0d8e5cd56246afc41587': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/88/6537ef50a6def0927676f1e1a7932c506fd6a6': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/88/1cb02989a44be41b1679d23ea4a243aa2d8bf1': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/88/17d1c6963b06a1a269c0f8fad7dfe53732f15c': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/e5/189760b385313aae8f8f3340bb93330cf99b81': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/e5/cfbba0ca7a648340eda3c77787b89da01ff9f6': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/1d/5bc15f9adc6fc05d401ebc66822685b50447e3': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/30/1d9719929bafbb3ee6063ba89a77a9437f59ea': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/0d/e96b1238d25580480e04dc5c87340b66715a92': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/0d/1a29e918f527ef85074c4d46e5a3164c70420d': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/0d/e336b14a5cc3098bd807b36556524d428b9141': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/0d/e8dbaadab1aa5df299ec4da7588e7abcb60761': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/7a/627ca14cfa61eb5ce0ca552d59b80f89895749': Permission denied
cp: cannot create regular file '/home/ruben/dev/minetest/build/android/src/main/assets/Minetest/games/minetest_game/.git/objects/7a/70cb3c7115f9c6040a018f6e52dec2a750918a': Permission denied
find: ‘./Minetest/games/minetest_game/.git’: No such file or directory
changed timestamp for iconv detected building...
/bin/sh: 17: /home/ruben/Android/Sdk/ndk-bundle/toolchains//build/tools/make-standalone-toolchain.sh: not found
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make sets $(MAKE)... (cached) yes
checking for arm-linux-gcc... arm-linux-androideabi-gcc
checking whether the C compiler works... no
configure: error: in `/home/ruben/dev/minetest/build/android/deps/libiconv':
configure: error: C compiler cannot create executables
See `config.log' for more details
Makefile:466: recipe for target '/home/ruben/dev/minetest/build/android/deps/libiconv//lib/.libs/libiconv.so' failed
make[1]: *** [/home/ruben/dev/minetest/build/android/deps/libiconv//lib/.libs/libiconv.so] Error 1
make[1]: Leaving directory '/home/ruben/dev/minetest/build/android'
Makefile:160: recipe for target 'debug' failed
make: *** [debug] Error 2
```

**Comment by stujones11** [comment] 2017-11-05 16:59
Does `config.log' contain any more details?

**Comment by paramat** [comment] 2017-11-06 05:43
Now i know why MoNTE48 stated that C++11 'broke android' and why MultiCraft won't be updating to 0.5.0. So it seems none of the android forks will be updating either.
Is there a way we can use this situation to our advantage by making it so that only the official MT app can update to 0.5.0?

**Comment by sfan5** [comment] 2017-11-06 08:19
iconv build failures are not related to c++11
c++11 works just fine for native code with gcc ([example](https://github.com/mpv-android/mpv-android/blob/mpv-android-2017-09-20/app/src/main/jni/Android.mk#L53)) and even if not you can always use clang
(gcc is deprecated in the NDK anyway)

**Comment by stujones11** [comment] 2017-11-10 21:04
Did anyone get iconv to build yet, I had a go myself and got past the compiler issue by targeting android-14 (minimum supported by latest NDK). I'm now getting undefined reference errors to `stdout` and friends, looks to be a gcc issue as @sfan5 rightly points points out.

**Comment by sfan5** [comment] 2017-11-11 00:07
you need a wrapper for `arm-linux-androideabi-gcc` ([like this](https://github.com/mpv-android/buildscripts/blob/master/download.sh#L77)) or use an NDK older than r15x

**Comment by stujones11** [comment] 2017-11-11 18:33
I actually did try adding `-D__ANDROID_API__=14` to the CFLAGS but still get the same error. I will try creating a wrapper, I have seen that suggested for openssl which will likely be the next problem.

@sfan5 it would be nice if you create a similar build system for minetest ;-) nice project btw.

**Comment by stujones11** [comment] 2017-11-12 18:09
Some progress, it turns out that add `-D__ANDROID_API__=14` does fix the unified headers problem, however, it seems necessary to use `make_standalone_toolchain.py` with the `--unified-headers` option. With a few other minor tweaks I have successfully build all of the deps.

Now it seems the is a problem building minetest itself
```
jni/../jni/src/client/tile.h: At global scope:
jni/../jni/src/client/tile.h:156:59: error: 'irr::video::IVideoDriver' has not been declared
 video::IImage * Align2Npot2(video::IImage * image, video::IVideoDriver* driver);
```
Any ideas?

**Comment by stujones11** [comment] 2017-11-15 20:40
PR #6628

**Comment by paramat** [comment] 2017-12-04 02:31
#6628 merged but seems there is still some work to be done, so keeping open for now.

**Comment by SmallJoker** [comment] 2018-04-04 14:00
@rubenwardy Is this issue still persistent after #6796 ?

**Comment by nerzhul** [comment] 2018-06-03 20:43
the problem is present in 0.4.17 release. I will push a patch to stable-0.4

**Closed** 2018-06-07 16:59 UTC
Labels: Android, Blocker, Question, Unconfirmed bug
