### ISSUE TITLE
LuaError messages for wrong custom types are not called

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#12681] opened 2022-08-10 01:41 UTC
##### Minetest version
```
5.7-dev
```

##### OS / Hardware

Operating system: Pop!_OS
CPU: i7

##### Summary
I was testing #1794 and I've noticed how functions calling macros in `c_converter.cpp` such as `CHECK_TYPE` don't throw the indicated error message. Instead:
```
AsyncErr: Lua: Unknown error from mod 'test' in callback environment_Step(): <no description>
```

##### Steps to reproduce
Try one of the functions in #1794 such as `minetest.add_entity()`

**Comment by TurkeyMcMac** [comment] 2022-08-10 02:21
Are you using the bundled Lua? If so, the bug is probably caused by https://github.com/minetest/minetest/pull/11683. You could test to see if the bug is fixed by https://github.com/minetest/minetest/pull/12445.

**Comment by Zughy** [comment] 2022-08-10 10:44
@TurkeyMcMac I can confirm that it works as it should with your PR (thank you for your contributions!). Would you be so kind to link this issue in the PR? I don't have enough permissions

**Closed** 2022-09-26 11:23 UTC
Labels: Bug, @ Script API, Maintenance
