### ISSUE TITLE
[Request] Right click function for Items

### ISSUE THREAD

**Issue by Rui914** [minetest/minetest#2841] opened 2015-06-27 05:33 UTC
The on_place is right-click operation, but it doesn't work without point to node.
I want to have right-click function without point to node.

For example, it can use to mode change by right-click in tool.

**Comment by est31** [comment] 2015-07-14 07:38
No closing reason given

**Comment by thePalindrome** [comment] 2015-11-17 04:14
This should be fixed quite soon, in the meantime refer to #1548

**Comment by est31** [comment] 2015-11-17 04:27
Ah, I see it is a dupe of #1548.

**Closed by est31** 2015-11-17 04:27 UTC
Labels: feature request
