### ISSUE TITLE
run-unittests incomplete

### ISSUE THREAD

**Issue by waxtatect** [minetest/minetest#13597] opened 2023-06-15 12:33 UTC
##### Minetest version

```
5.7.0
```

##### OS / Hardware

Operating system: Windows
CPU: i7

GPU model:
OpenGL version:

##### Summary

Unit tests stops at some point, i tested different versions in 64 bits, last one with complete results was 5.5.1
Output with 5.7.0:
<details>

```
======== Testing module TestVoxelManipulator
[PASS] testVoxelArea - 0ms
[PASS] testVoxelManipulator - 0ms
======== Module TestVoxelManipulator passed (0 failures / 2 tests) - 0ms
======== Testing module TestVoxelArea
[PASS] test_addarea - 0ms
[PASS] test_pad - 0ms
[PASS] test_extent - 0ms
[PASS] test_volume - 0ms
[PASS] test_contains_voxelarea - 0ms
[PASS] test_contains_point - 0ms
[PASS] test_contains_i - 0ms
[PASS] test_equal - 0ms
[PASS] test_plus - 0ms
[PASS] test_minor - 0ms
[PASS] test_index_xyz_all_pos - 0ms
[PASS] test_index_xyz_x_neg - 0ms
[PASS] test_index_xyz_y_neg - 0ms
[PASS] test_index_xyz_z_neg - 0ms
[PASS] test_index_xyz_xy_neg - 0ms
[PASS] test_index_xyz_xz_neg - 0ms
[PASS] test_index_xyz_yz_neg - 0ms
[PASS] test_index_xyz_all_neg - 0ms
[PASS] test_index_v3s16_all_pos - 0ms
[PASS] test_index_v3s16_x_neg - 0ms
[PASS] test_index_v3s16_y_neg - 0ms
[PASS] test_index_v3s16_z_neg - 0ms
[PASS] test_index_v3s16_xy_neg - 0ms
[PASS] test_index_v3s16_xz_neg - 0ms
[PASS] test_index_v3s16_yz_neg - 0ms
[PASS] test_index_v3s16_all_neg - 0ms
[PASS] test_add_x - 0ms
[PASS] test_add_y - 0ms
[PASS] test_add_z - 0ms
[PASS] test_add_p - 0ms
======== Module TestVoxelArea passed (0 failures / 30 tests) - 1ms
======== Testing module TestVoxelAlgorithms
[PASS] testVoxelLineIterator - 0ms
[PASS] testLighting - 34ms
======== Module TestVoxelAlgorithms passed (0 failures / 2 tests) - 34ms
======== Testing module TestUtilities
[PASS] testAngleWrapAround - 0ms
[PASS] testWrapDegrees_0_360_v3f - 973ms
Test assertion failed: lowercase("eeeeeeaaaaaaaaaaaààààà") == "eeeeeeaaaaaaaaaaaààààà"
    at test_utilities.cpp:182
[FAIL] testLowercase - 0ms
[PASS] testTrim - 0ms
[PASS] testIsYes - 0ms
[PASS] testRemoveStringEnd - 0ms
[PASS] testUrlEncode - 0ms
[PASS] testUrlDecode - 0ms
[PASS] testPadString - 0ms
[PASS] testStartsWith - 0ms
[PASS] testStrEqual - 0ms
[PASS] testStrToIntConversion - 0ms
[PASS] testStringReplace - 0ms
[PASS] testStringAllowed - 0ms
[PASS] testAsciiPrintableHelper - 0ms
[PASS] testUTF8 - 0ms
[PASS] testRemoveEscapes - 0ms
[PASS] testWrapRows - 0ms
[PASS] testEnrichedString - 0ms
[PASS] testIsNumber - 0ms
[PASS] testIsPowerOfTwo - 0ms
[PASS] testMyround - 0ms
[PASS] testStringJoin - 0ms
[PASS] testEulerConversion - 0ms
[PASS] testBase64 - 0ms
[PASS] testSanitizeDirName - 0ms
======== Module TestUtilities failed (1 failures / 26 tests) - 974ms
======== Testing module TestThreading
[PASS] testStartStopWait - 380ms
[PASS] testAtomicSemaphoreThread - 22ms
======== Module TestThreading passed (0 failures / 2 tests) - 402ms
======== Testing module TestSocket
[PASS] testIPv4Socket - 203ms
[PASS] testIPv6Socket - 51ms
======== Module TestSocket passed (0 failures / 2 tests) - 254ms
======== Testing module TestSettings
[PASS] testAllSettings - 0ms
[PASS] testDefaults - 1ms
[PASS] testFlagDesc - 0ms
======== Module TestSettings passed (0 failures / 3 tests) - 1ms
======== Testing module TestServerModManager
Test assertion failed: world_config.updateConfigFile(path.c_str()) == true
    at test_servermodmanager.cpp:109
    actual  : 0
    expected: 1
[FAIL] testCreation - 1ms
[PASS] testIsConsistent - 1ms
Test assertion failed: sm.getMods().empty() == true
    at test_servermodmanager.cpp:117
    actual  : 0
    expected: 1
[FAIL] testGetModsWrongDir - 2ms
[PASS] testUnsatisfiedMods - 1ms
Test assertion failed: default_found == true
    at test_servermodmanager.cpp:152
    actual  : 0
    expected: 1
[FAIL] testGetMods - 2ms
Test assertion failed: sm.getModSpec("basenodes") != NULL
    at test_servermodmanager.cpp:160
[FAIL] testGetModspec - 1ms
Test assertion failed: result.empty() == true
    at test_servermodmanager.cpp:168
    actual  : 0
    expected: 1
[FAIL] testGetModNamesWrongDir - 2ms
Test assertion failed: std::find(result.begin(), result.end(), "basenodes") != result.end()
    at test_servermodmanager.cpp:177
[FAIL] testGetModNames - 1ms
Test assertion failed: result.empty() == true
    at test_servermodmanager.cpp:185
    actual  : 0
    expected: 1
[FAIL] testGetModMediaPathsWrongDir - 36ms
```
</details>
With Windows 7, it ends by a crash with exception code c0000005, while on Windows 11 just nothing happens

##### Steps to reproduce

open command line, then start unittests,
with "minetest --run-unittests" (with "minetest --run-unittests 2> 1.txt" to save the output)

**Comment by SmallJoker** [comment] 2023-06-16 18:28
I did reproduce the failures of the 64-bit Minetest build but not the crash (using Wine 8.9). At least the fails can be explained by the paths that are "hardcoded" into the binary:
https://github.com/minetest/minetest/blob/edcbfa31c9eb636edca2ed8b10eace8e003a0a08/src/unittest/CMakeLists.txt#L50-L53

For `RUN_IN_PLACE=1` binaries this variable should be relative. This is broken at least since 6c184947c3.

**Comment by sfan5** [comment] 2023-06-16 18:42
Did you try this with a non-release build? The release build is set to only run a window and not bind the console (windows makes this a choice), which could interfere here.

**Comment by waxtatect** [comment] 2023-06-17 10:47
I only used release versions, how else run tests than through console?

**Comment by JosiahWI** [comment] 2023-06-18 13:30
It would be good to have a way to verify the correctness of release builds - issues such as undefined behavior could be revealed only when optimization is enabled. It would also be easy to accidentally build in release mode and not notice that some tests didn't run. Perhaps we can add a warning to alert us when that happens?

**Comment by Zughy** [comment] 2023-10-07 20:45
Windows 7 has reached its EOL so it's not supported by Minetest anymore. On Windows 10 unittests work (with the issue pointed out by SmallJoker, but that's for a separate issue). Closing

**Closed by Zughy** 2023-10-07 20:45 UTC
Labels: Unconfirmed bug, @ Build, Windows

**Comment by waxtatect** [comment] 2023-10-09 11:12
(i suppose that means it wont work properly on Windows 11 either then, as i mentioned in the first message, it just does nothing on Windows 11, yet i understand that not an issue that important)
