### ISSUE TITLE
View spins around zenith in Linux since 2060fd9c

### ISSUE THREAD

**Issue by dfelinto** [minetest/minetest#4261] opened 2016-06-29 19:02 UTC
In Windows I don't have this problem.

I'm in a Ubuntu station with no Joystick in the machine.

Error introduced in revision: 2060fd9cbe587d7e8ffe0cecdd67925f13a56c05

**Comment by dfelinto** [comment] 2016-06-29 19:17
The problem is directly related to the joystick. If I set "enable_joystick" to false things work fine. But this is enabled by default.

**Comment by dfelinto** [comment] 2016-06-29 19:20
Ubuntu 14.04.4 running with KDE

**Comment by xunto** [comment] 2016-06-29 19:27
#4221 related

**Comment by t4im** [comment] 2016-06-29 19:28
I can confirm. Unless deactivated, minetest accesses `/dev/input/js0` and spins around in game. No Joystick present here. But if access to `/dev/input/js0` is prohibited, the game behaves.

**Comment by Fixer-007** [comment] 2016-06-29 19:57
@est31 @sofar

**Comment by est31** [comment] 2016-06-30 00:59
@t4im @dfelinto  why do you have a `/dev/input/js0` device the first place? What is it about? Is it a placeholder like the /dev/sd{b,c,d} stuff used to be? Maybe the sensor is builtin to the device linux is running on? This was the case for 4221 at least.

If not, this is most probably an upstream bug.

Either way, seems the best option is to disable the option by default.

**Comment by sofar** [comment] 2016-06-30 04:26
@est31 in Linux, many audio cards have a builtin joystick driver. If they're running an older mobo with external sound card, it likely has a joystick port in which case this port is always present.

It would be good to figure out what the actual values for each axis are - can @t4im and @dfelinto run jstest?

**Comment by duckbrain** [comment] 2016-06-30 17:28
Maybe we could calibrate the joystick on init. Use the initial state of the joystick as zero and use all positions from then as relative. Normally these non-joysticks are not going to move their reported axes. This would mean that if your joystick is not at zero when you start the game, it would be offset, but I think that this is fairly normal behavior. I know some consoles do this, such as the GameCube.

**Comment by t4im** [comment] 2016-06-30 17:58
@est31 Seems in my case it's a Microsoft keyboard :flushed:¹, that is messing up my Linux.
Probably that zoom slider-button thingy on it, that is registered as joystick.

[1] If you're telling anyone, that i'm using a ms product, i'm gonna deny it!

**Comment by paramat** [comment] 2016-07-04 13:16
@est31 Seeing how many players have this problem can we please disable the joystick setting by default? at least until this is fixed.

**Comment by paramat** [comment] 2016-07-04 13:30
Duplicate of #4221

**Closed** 2016-07-04 19:00 UTC
Labels: @ Client / Audiovisuals, Bug, Duplicate

**Comment by rubenwardy** [comment] 2017-04-03 22:36
Would someone that has this problem be able to run `jstest-gtk` and tell me the name of the joystick? In the list it's the first line

![](http://3.bp.blogspot.com/-gAALurV3xr4/VBIda20ccAI/AAAAAAAAGFk/HLbK-zdgpEI/s1600/jstest.png)

ie: it's "Mad Catz Xbox 360 Controller" in the above image.
