### ISSUE TITLE
Water lighting bug

### ISSUE THREAD

**Issue by juhdanad** [minetest/minetest#4658] opened 2016-10-23 18:26 UTC
If you dig a one-node wide pit in the ground and cover it with glass (see on the image), there is sunlight in the pit. When you place water on the glass then remove it, the light will disappear.
If you let water flow onto the glass, the nodes under the water will have sunlight, even if a water source is generated on the glass.
![minetest_water](https://cloud.githubusercontent.com/assets/20600448/19628482/df2aec9c-995e-11e6-8771-2c01a7c9905c.png)

**Comment by Fixer-007** [comment] 2016-10-23 19:04
Wait, when I cover it with water source, it will darken the pit, and if I remove it - it is light again. Right now I test your pr 4655, will look into vanilla later.

It is not surprising, since liquids and lighting = :skull_and_crossbones:  Search issues some more for this insanity like writing HI with water on water....

**Comment by paramat** [comment] 2016-10-24 21:50
There's a related bug, placing water source into water will darken the water very slightly.

**Comment by Wuzzy2** [comment] 2016-10-29 23:47
Wait, what? How is this a bug? I thought this is intended behaviour.
Water has `propagates_sunlight=false` while glass has it on `true`.

Light goes through both, but for water, sunlight becomes darker for each node.

**Comment by paramat** [comment] 2016-10-30 04:01
#4655 is merged, does that fix this?

**Comment by juhdanad** [comment] 2016-10-30 15:08
@Wuzzy2 It was a bug because the shadow did not disappear when there was no water on the glass.

**Comment by paramat** [comment] 2016-10-31 01:15
Fixed by #4655

**Closed by paramat** 2016-10-31 01:15 UTC
Labels: Bug
