### ISSUE TITLE
Upside-down stairs, slaps, etc. should have “upside-down textures”, too

### ISSUE THREAD

**Issue by dsohler** [minetest/minetest#5222] opened 2017-02-12 18:52 UTC
When placing stairs and slaps, etc. upside-down (i.e. aiming for a block above and placing the node) they’re upside-down which is absolutely fine.

Unfortunately their texture seems not to be altered to match the regular textures (default textures).

![1](https://cloud.githubusercontent.com/assets/1668792/22864987/484d39ec-f15b-11e6-8099-42516d3aa87e.png)

![screenshot_20170212_194145](https://cloud.githubusercontent.com/assets/1668792/22864988/484e337e-f15b-11e6-91d7-b02d1c0de01e.png)

Here’s another example (top row: stone bricks, middle row: regular stair, upside-down stair, regular stair, bottom row: stone bricks, all seen from behind).

![screenshot_20170212_194614](https://cloud.githubusercontent.com/assets/1668792/22865024/f597baaa-f15b-11e6-9ed1-d0e202652105.png)

The best thing would be, rotating the texture upside-down, too. This would result in properly aligned textures.

**Comment by paramat** [comment] 2017-02-12 20:04
This would have to be an option to not rotate a texture when the nodebox shape is rotated.

**Comment by numberZero** [comment] 2017-02-12 20:06
@paramat That would be an option to *rotate* the texture in the opposite direction to compensate nodebox rotation. But that may look weird for nodes like stone bricks, although should be fine for e.g. stone.

**Comment by dsohler** [comment] 2017-02-12 20:12
You’re both right :smile: 

Either don’t rotate the texture when rotating the nodebox or rotate the texture in the opposite direction after rotating the nodebox.

In both cases the texture would stay properly aligned according the textures of not rotated nodes resulting in a much cleaner look.

**Comment by Fixer-007** [comment] 2017-02-12 20:27
Dupe of this https://github.com/minetest/minetest_game/issues/1211

**Comment by paramat** [comment] 2018-09-20 00:26
World aligned textures is now added.

**Closed by paramat** 2018-09-20 00:26 UTC
Labels: @ Client / Audiovisuals, Feature request

**Comment by Ezhh** [comment] 2018-09-20 13:38
I somehow never noticed world-aligned textures before. The changes to stairs/slabs are in many cases going to completely break builds where people have relied on the ability to adjust texture direction to create specific effects. It might help with the one issue (the originally identified one) but really doesn't look good in other ways and removes a chance for players to use creative ideas when building.

**Comment by 12Me21** [comment] 2018-09-20 17:51
This should definitely be added to all slabs, stairs, partial blocks, etc.
First in the default stairs mod, and then hopefully other mods like moreblocks will introduce the fix as well.

**Comment by paramat** [comment] 2018-09-20 17:55
It was :) that's the problem.

**Comment by 12Me21** [comment] 2018-09-20 18:11
Ah, I never checked.
I think that the best solution for people who want rotated textures (if it's really such a problem) would be to add new nodes that have the sideways/upside down textures, because for most purposes, the world aligned textures look better.
Or even a flag in param2 that controls the texture orientation...
