### ISSUE TITLE
Holding the Jump key on a bouncy block makes you jump too high

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1552] opened 2014-08-09 07:37 UTC
**doc/lua_api.txt:**
`- bouncy: value is bounce speed in percent`

*Test with [this mod](https://forum.minetest.net/viewtopic.php?f=11&t=9891).*

If you hold the space bar while jumping on a trampoline, regardless of its strength, you'll jump very high (sometimes hundreds of meters). This is believed to be broken by MirceaKistune's physics changes back in late 2012-early 2013.

This can't be prevented since disable_jump doesn't work, see #1551.

**Comment by Miner59** [comment] 2015-06-30 17:46
Hi.
What I think what causes the problem is that bouncing is handled two times for a player. First in localplayer.cpp then I think in another file, where bouncing of all objects and luaentities is handled.
I compiled myself a version where the code which handles bouncing and jumping in localplayer.cpp is commented out and bouncing seems to work flawless now in minetest. 
I tested with jumping mod and it worked exactly as it should work with this changes.

Here is what I commented out, you find it in localplayer.cpp, line 321 and following:


	/*
		Report collisions
	*/
//	bool bouncy_jump = false;
	// Dont report if flying
	if(collision_info && !(g_settings->getBool("free_move") && fly_allowed)) {
		for(size_t i=0; i<result.collisions.size(); i++) {
			const CollisionInfo &info = result.collisions[i];
			collision_info->push_back(info);
//			if(info.new_speed.Y - info.old_speed.Y > 0.1*BS &&
//					info.bouncy)
//				bouncy_jump = true;
		}
	}

//	if(bouncy_jump && control.jump){
//		m_speed.Y += movement_speed_jump*BS;
//		touching_ground = false;
//		MtEvent *e = new SimpleTriggerEvent("PlayerJump");
//		m_gamedef->event()->put(e);
//	}


I hope a developer can check this and finally fix this bug.

**Comment by kwolekr** [comment] 2015-07-05 18:13
Jumping on nodeboxes has been fixed for a while now.  That being said, removing the bouncy jump code does produce the correct behavior with the trampoline mod - that is, jumping is disabled on the trampoline because the trampoline node has the disable_jump=1 group.  Removing the disable_jump group causes the trampoline node to behave normally in regard to jumping.
However, the *expected* behavior is for the player to bounce somewhat higher when jumping, but not 120 nodes high.

I would argue that the correct fix here would be to add a speed modifier on jumping if the node being jumped on is in the bouncy group, remove the bouncy_jump code as this PR already does, and then remove disable_jump from trampoline mods.

**Comment by Miner59** [comment] 2015-07-07 04:15
Hello kwolekr,
It seems to be a slight misunderstanding, maybe your version of jumping mod doesn't work right.

I think disable_jump was just added in calinou's version as a workaround to avoid the buggy insane high jumps on trampolines.

Better try the original mod written by jeija, look here: https://github.com/Jeija/minetest-mod-jumping

With this mod enabled, you can write "/giveme jumping:trampoline1" for a weak bouncing trampoline or "/giveme jumping:trampoline6" for a trampoline where you can bounce very high.

With trampoline6 you can still reach insane heights, but just after several jumps where you always gain more speed so you bounce back higher everytime.
But I think it's just expected behavior. 

I tried to code something, so you jump higher if you press jump, but I wasn't successful. I just ended in behaviour similar to before me PR.

To test a block with disable_jump group use "jumping:cushion".
When I tested it still allowed me to jump standing on it, so I needed gregorys small fix, so that it worked correctly.

**Comment by Wuzzy2** [comment] 2015-08-24 17:12
Can we close this issue now? The changelog says that bouncy blocks are fixed.

I have tested Calinou's mod (but I removed disable_jump) and it seems to work.

**Finally!**

**Comment by Wuzzy2** [comment] 2016-03-12 00:49
Ummmm, why is this issue still open?

**Closed** 2016-03-13 00:39 UTC
Labels: @ Server / Client / Env., Bug
