### ISSUE TITLE
Mod Errors on Mac

### ISSUE THREAD

**Issue by AnonomousAccount** [minetest/minetest#15389] opened 2024-11-05 22:46 UTC
### Luanti version

```true
Luanti 5.8 and 5.9 (directly from the downloads page)
```

### Operating system and version

MacBook Air, Sonoma 14.2.1

### CPU model

Apple M2

### Summary

Some mods seem to randomly throw an error and cause a world not to load.
Here's what I know:
- Has happened on both Capture the Flag and Voxel Libre games
- Two VL worlds with no additional mods installed, one opens with no error, and the other loads but immediately shuts down with the error message `Runtime error from mod '??' in callback ??(): <no description>`
- All Capture the Flag worlds cause the error pictured here: 
![screenshot](https://github.com/user-attachments/assets/d946ab75-e2e0-4ad9-a9dc-9da781da3178)

- Minetest 5.6 does **not** have these errors and loads the world perfectly fine, while 5.8 and 5.9 are problematic

I have tried reinstalling both games

These errors just started appearing a few weeks ago, I do not know what triggered them.

### Steps to reproduce

No idea, as of now

**Comment by sfan5** [comment] 2024-11-05 23:11
Please provide a complete debug.txt file showing the error.

> All Capture the Flag worlds cause the error pictured here: https://discord.com/channels/369122544273588224/369137254641303560/1303409753157799956

this is useless to us, please re-upload the screenshot to github. or better: copy the text contents.

**Comment by sfence** [comment] 2024-11-06 05:08
I have seen something like this. It is probably caused by a missing dependency in a `mod.conf` file.

We do a random reorder of mods before dependency resolving.

**Comment by appgurueu** [comment] 2024-11-06 11:22
I've fetched the image from Discord and edited the post.

Note that this is a Lua error without a non-string error message raised *inside the `add_entity` C function*, so in our code, which is extremely odd. Neither we nor any Lua implementation ever does this to my knowledge. I am inclined to suspect platform-specific Lua implementation bugs here.

> I have seen something like this. It is probably caused by a missing dependency in a `mod.conf` file.
> We do a random reorder of mods before dependency resolving.

I don't think this is what happening here.
`random_mod_load_order` is `false` by default.

**Comment by sfence** [comment] 2024-11-06 15:26
How often does it occur? I have tested both games on 5.8, 5.9, 5.9.1 and 5.10 RC and no problem found.

**Closed** 2024-12-07 14:12 UTC
Labels: Unconfirmed bug, macOS, Action / change needed

**Comment by AnonomousAccount** [comment] 2024-12-07 23:23
UPDATE (SOLVED)
I had accidentally set `depricated_lua_api_handling` to `error`. Returning it to `log` fixed the problem.

**Comment by appgurueu** [comment] 2024-12-08 01:11
That's good to know, thanks. There might very well still be a bug here, because the error message shouldn't be cryptic like that. But that's lower priority. I looked around in the code for a bit and there doesn't seem to be an obvious explanation for such a cryptic error message unfortunately.
