### ISSUE TITLE
Receiving generated textures often fails in 5.5-dev, regression from 5.4.1

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11997] opened 2022-01-28 11:33 UTC
##### Minetest version
commit 22f0c66abbd0

##### OS / Hardware
Operating system: Debian GNU/Linux
CPU: x86_64

##### Summary
With MineClone5 from ContentDB, creating a map (right click using a map item) often (7 out of 8 cases) fails in 5.5-dev.

It never fails in 5.4.1. Looks like another one of these API rug-pulls to me that happen literally all the time.

(You know, where the API changes all the time and then the mod authors are blamed.)

##### Steps to reproduce
1. Download MIneClone5 from ContentDB.
2. Join a world, ideally in creative mode, on Linux (or change TGA file writing mode to `wb` on Windows to fix a bug in MineClone5).
3. Get a stash of 64 map items from the creative inventory.
4. Right click 8 times in quick succession.
5. Verify that you got 8 map items in your hotbar.
6. Switch to each map item and notice that a few of the generated textures do not load and Minetest shows an error message.
7. Look in the `mcl_maps` folder in the worlds folder and verify that all textures are indeed valid TGA pictures.
8. Exit the world and enter it again.
9. Verify that all map items show a colored heightmap texture near the player hand (in first person).

##### Log
```
2022-01-28 11:57:06: VERBOSE[Server]: allocateDynamicMediaCallback() = 1049717176
2022-01-28 11:57:06: VERBOSE[Server]: Server: d0a3c582bb36f3996b5960524d2f794d56291f11 is mcl_maps_map_texture_16.tga
2022-01-28 11:57:06: INFO[Server]: collisionMoveSimple: maximum step interval exceeded, lost movement details!
2022-01-28 11:57:06: INFO[Emerge-0]: initialEmerge: area: (-288,-128,32)(-177,-17,143)=112x112x112=1404928 (5MB)
2022-01-28 11:57:06: VERBOSE[Main]: Server pushes media file "mcl_maps_map_texture_16.tga" to be fetched (cached=0)
2022-01-28 11:57:06: VERBOSE[Main]: FileCache: File not found in cache: /tmp/minetest/bin/../cache/media/d0a3c582bb36f3996b5960524d2f794d56291f11
2022-01-28 11:57:06: INFO[Main]: Client: Sending media request list to server (1 files, packet size 31)
2022-01-28 11:57:06: INFO[Main]: GenericCAO: properties updated but expiring visuals not necessary
2022-01-28 11:57:06: INFO[Main]: GenericCAO: properties updated but expiring visuals not necessary
2022-01-28 11:57:06: INFO[Main]: GenericCAO: properties updated but expiring visuals not necessary
2022-01-28 11:57:06: INFO[Server]: Sending 1 files to singleplayer
2022-01-28 11:57:06: VERBOSE[Server]: TOSERVER_REQUEST_MEDIA: requested file(s)
2022-01-28 11:57:06: VERBOSE[Server]:   mcl_maps_map_texture_16.tga
2022-01-28 11:57:06: VERBOSE[Server]: Server::sendRequestedMedia(): Sending files to client
2022-01-28 11:57:06: VERBOSE[Server]: Server::sendRequestedMedia(): bunch 0/2 files=1 size=31933
2022-01-28 11:57:06: VERBOSE[Server]: Server::sendRequestedMedia(): bunch 1/2 files=0 size=8
2022-01-28 11:57:06: INFO[Main]: Adding "mcl_maps_map_background.png" to combined (0,0)
2022-01-28 11:57:06: INFO[Main]: Adding "mcl_maps_map_texture_16.tga" to combined (6,6)
2022-01-28 11:57:06: INFO[Main]: SourceImageCache::getOrLoad(): No path found for "mcl_maps_map_texture_16.tga"
2022-01-28 11:57:06: ERROR[Main]: generateImage(): Could not load image "mcl_maps_map_texture_16.tga" while building texture; Creating a dummy image
2022-01-28 11:57:06: INFO[Main]: Client: Received files: bunch 0/2 files=1 size=31933
2022-01-28 11:57:06: VERBOSE[Main]: Client: Loaded received media: d0a3c582bb36f3996b5960524d2f794d56291f11 "mcl_maps_map_texture_16.tga"
2022-01-28 11:57:06: INFO[Main]: Client: Received files: bunch 1/2 files=0 size=8
```

**Comment by appgurueu** [comment] 2022-01-28 11:41
The breaking change here is that [5.3.0](https://github.com/minetest/minetest/blob/5.3.0/doc/lua_api.txt#L5233-L5236) neither had a callback nor was marked as experimental; the docs explicitly guaranteed that media is ready-for-use right after calling it. Later versions (5.4.1, dynamic_add_media v2) introduced a callback instead, which is preferable as it's non-blocking. This means that mods relying on this documented behavior may now break due to a race condition, as they try to use the media before it's available.

The only proper solution unfortunately is a busywait until all players have received the media if the callback is omitted.

**Comment by erlehmann** [comment] 2022-01-28 11:43
@appgurueu can you explain why exactly this breaks without the callback after 5.4.1, but not in 5.4.1?

**Comment by appgurueu** [comment] 2022-01-28 11:44
> @appgurueu can you explain why exactly this breaks without the callback after 5.4.1, but not in 5.4.1?

I'm pretty sure the callback in 5.4.1 was merely a "dummy" callback to ease the transition.

**Comment by appgurueu** [comment] 2022-01-28 11:46
The issue title is misleading BTW. The textures are very well received - it's just that they are used before being received due to the breaking API change I have outlined. sfan5's stance:

```
<sfan5> this api was deprecated in 5.4.0 specifically because it was obvious that it's not viable to keep
<sfan5> and with 5.5 the deprecation period has ended and the old usage no longer works
```

**Comment by erlehmann** [comment] 2022-01-28 11:53
The Minetest API rug-pulling situation reminds me of the *HItchhiker's Guide to the Galaxy*:

> “But the plans were on display…”
> “On display? I eventually had to go down to the cellar to find them.”
> “That’s the display department.”
> “With a flashlight.”
> “Ah, well, the lights had probably gone.”
> “So had the stairs.”
> “But look, you found the notice, didn’t you?”
> “Yes,” said Arthur, “yes I did. It was on display in the bottom of a locked filing cabinet stuck in a disused lavatory with a sign on the door saying ‘Beware of the Leopard.”

**Comment by sfan5** [comment] 2022-01-28 11:53
I assume (you didn't link to the relevant code) that Mineclone5 uses `dynamic_add_media` without a callback. This usage was deprecated in 5.4.0 and obsoleted (= stopped working) in 5.5.0.
Again, there was a <b>deprecated period</b> and if a mod author has failed to act upon the warnings this is neither a "breaking change" nor a "rug-pull".

**Closed by sfan5** 2022-01-28 11:53 UTC
Labels: Unconfirmed bug

**Comment by sfan5** [comment] 2022-01-28 15:48
By the way, I checked and confirmed that dynamic_add_media on 5.5 errors when you do not provide a callback:
`2022-01-28 16:42:35: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'test2' in callback on_chat_message(): [...]/init.lua:283: bad argument #2 to 'dynamic_add_media' (function expected, got no value)`
This must mean that Mineclone5 provides a callback but does not use it correctly, moving this issue even further from being an engine bug.
