### ISSUE TITLE
Fix HW buffer release (10501) in Irrlicht

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#11203] opened 2021-04-17 01:32 UTC
With our own fork of Irrlicht #10501 can be fixed there instead of the hack.

Not sure I'll get to that any time soon, filing here to remember (or for someone to pick up)

**Comment by sfan5** [comment] 2021-04-17 09:04
technically a duplicate of #11040 but doesn't hurt to track separately I guess.

**Comment by lhofhansl** [comment] 2021-04-18 21:01
Sorry missed the other one. Happy to close this one.

**Comment by SmallJoker** [comment] 2021-07-21 16:12
Closing because #11040 is a better overview for a maintenance PR.

**Closed by SmallJoker** 2021-07-21 16:12 UTC
Labels: @ Client / Audiovisuals, Maintenance
