### ISSUE TITLE
Question: current status of pathfinding

### ISSUE THREAD

**Issue by Rick-W-Storm** [minetest/minetest#11802] opened 2021-11-30 22:01 UTC
I've been playing on a large community-organized MT server with version 4.5.1 lately.

I've noticed the combat being quite boring and plaid.
(flying) mobs won't find you, some mobs don't seem to pay attention at all and those who do just walk in the general direction of the player without changing path when the player moves. They seem stiff and unchallenging.

I'm not sure if this issue is already discussed on the issue tracker so feel free to link to the appropriate issue and close this one off.

What's the current development state of mob path finding or are there perhaps some server configs which need to be enabled to enable engaging mob pathfinding or perhaps the pathfinding of some mod-provided entities are somehow worse than the default?

**Comment by Zughy** [comment] 2022-05-04 14:33
Hello, please ask such questions in the pathfinder issue (#5479), in the forum or in one of the MT communities (https://www.minetest.net/get-involved/).

Duplicate of #5479

**Closed by Zughy** 2022-05-04 14:33 UTC
Labels: Duplicate, Question
