### ISSUE TITLE
Progress bar isn't shown correctly on Windows

### ISSUE THREAD

**Issue by farooghkz** [minetest/minetest#5983] opened 2017-06-14 06:50 UTC
When I wanted to connect to a server, I saw this:
![mt_progress_bar](https://user-images.githubusercontent.com/15038218/27118869-8d78dc3c-50f2-11e7-9b5a-7a5e55bed393.PNG)
Settings were not changed. I am using `minetest-0.4.16-win32-mingw` with Windows 7 32-bit. debug.txt 
attached.
[debug.txt](https://github.com/minetest/minetest/files/1073725/debug.txt)

**Comment by kilbith** [comment] 2017-06-14 09:28
Duplicate of https://github.com/minetest/minetest/issues/5911.
Upgrade your hardware.

**Comment by red-001** [comment] 2017-06-14 10:28
how is telling people to update hardware a solution? Just add a fallback that is used instead on old hardware.

**Closed** 2017-06-14 11:03 UTC

**Comment by nerzhul** [comment] 2017-06-14 12:33
i should backport the fix from android code it think (if portable)

**Comment by MuhdNurHidayat** [comment] 2017-06-27 20:57
> Upgrade your hardware.
Seriously, don't ask others to upgrade hardware. Some of hardware can't be upgraded as easy as software upgrade, it could possibly create other failure or incompability between hardwares _unless you're expert in computer hardwares and you perfectly know what you do without refering to howtos and tutorials_ .

Like red-001 said, fallback for old hardware is what needed.

**Comment by SmallJoker** [comment] 2017-06-28 15:32
@MuhdNurHidayat 
Even low-end laptops from 2007 should offer OpenGL >= 2.0, which is already sufficient for very basic shaders and textures with (almost) any resolution.
The fallback we have is called custom texture packs. You can even overwrite `progress_bar.png` and `progress_bar_bg.png` in the base/pack directory to apply it for all texture packs. Any power of two dimension texture will do it.

This is just a minor style issue, which underlying problem we can't solve. It would be something different if the game wasn't playable on older hardware anymore.

**Comment by farooghkz** [comment] 2017-06-29 04:08
Happily I can play Minetest because it was someone else's computer and I would never use that computer to play Minetest because FPS was 1 and so slow...

**Comment by MuhdNurHidayat** [comment] 2017-06-29 04:28
I'm just refering to the hardware, it's still playable on older hardware (as pointed by SmallJoker) so don't just write "upgrade hardware" as solution for something minor.

---
I know that feeling of 1 FPS ~~though I'm playing on Android phone~~ ...

I get 1 FPS when playing in certain heavy server which uses automation everywhere including automated train service (advtrains) and some kind of auto digging machine (?!)...
