### ISSUE TITLE
Leveled nodeboxes work without paramtype2="leveled"

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6913] opened 2018-01-14 17:57 UTC
The snow mod uses a leveled nodebox for the snow node (https://github.com/Splizard/minetest-mod-snow/pull/31). It works although paramtype2 is not set to "leveled" in the nodedef.
l guess the difference between paramtype2 set or not is that other mods can easily find out whether nodes' param2 is used for leveled.
I think minetest should give a warning if a mod uses leveled nodeboxes while paramtype2 is not "leveled".

**Comment by paramat** [comment] 2018-01-15 08:55
@numberZero

**Comment by numberZero** [comment] 2018-01-15 18:50
There are many similar errors. For example:
1. Some code treats `param1` as light value, not checking is that true.
2. Nodeboxes without `node_box` field are weird, sometimes behaving as solid nodes.
3. Liquid (drawtype) nodes `assert` that they are liquid sources. (Assertions are checked in debug builds only.)

**Comment by paramat** [comment] 2018-12-06 02:34
According to the code, if paramtype2 is not "leveled" for a type "leveled" nodebox then the level is set to 0:
https://github.com/minetest/minetest/blob/b298b0339c79db7f5b3873e73ff9ea0130f05a8a/src/mapnode.cpp#L261
Calls this:
https://github.com/minetest/minetest/blob/b298b0339c79db7f5b3873e73ff9ea0130f05a8a/src/mapnode.cpp#L614

**Comment by paramat** [comment] 2018-12-06 02:51
Not a bug, the level can be set by a nodedef insread of param2:
https://github.com/minetest/minetest/blob/56f22bfa5c22a89db968cf2dfc4d070b5f0e6520/doc/lua_api.txt#L5931
```
        leveled = 16,
        -- Only valid for "nodebox" drawtype with 'type = "leveled"'.
        -- Allows defining the nodebox height without using param2.
```

**Comment by HybridDog** [comment] 2018-12-06 12:47
> According to the code, if paramtype2 is not "leveled" for a type "leveled" nodebox then the level is set to 0

No, param2 is used even when paramtype2 is not "leveled", I tested it.
https://github.com/minetest/minetest/blob/b298b0339c79db7f5b3873e73ff9ea0130f05a8a/src/mapnode.cpp#L614-L621

I think that this code could be changed to use param2 only if paramtype2 is "leveled":
```C++
	if (f.leveled || f.param_type_2 == CPT2_LEVELED) {
		u8 level = getParam2() & LEVELED_MASK;
		if (level && f.param_type_2 == CPT2_LEVELED)
			return level;
		if (f.leveled > LEVELED_MAX)
		 	return LEVELED_MAX;
		return f.leveled; //default
}
```


> Not a bug, the level can be set by a nodedef instead of param2

That's a fixed level, paramtype2 doesn't need to be "leveled" in this case.

**Comment by paramat** [comment] 2018-12-06 23:10
Sorry, looks like you are right, re-opened.

**Comment by HybridDog** [comment] 2018-12-09 19:18
> Is it intentional that minetest.set_node_level(pos, 0) destroys the node even if it’s not a liquid?

I doubt it.
https://github.com/minetest/minetest/blob/98a72b9d458f3108d4a4bef4f0ad78f46baee2c4/doc/lua_api.txt#L4080-L4082
It should give an error instead when this happens in my opinion.

**Comment by paramat** [comment] 2018-12-10 01:04
Seems correct behaviour to me, if level is 0 it doesn't exist so should be 'removed'.

**Comment by numberZero** [comment] 2018-12-10 21:18
But if param2 level is 0, default level is used instead which may be
nonzero.

**Comment by paramat** [comment] 2018-12-11 03:12
Sorry, misunderstood. What do you mean by 'destroys the node'? Visually disappears or is actually 'removed'.

**Comment by numberZero** [comment] 2018-12-11 19:47
Replaced by air (at mapnode.cpp:629). Note that param2 is not changed in
that case; moreover, lighting is not recalculated as well, so it would
break in the case of non-sunlight-propagating node under direct
sunlight. It will also break for liquids with different lighting params
for source and flowing nodes as these are interchanged in some cases but
lighting is never updated.

**Closed** 2018-12-11 23:02 UTC
Labels: Bug
