### ISSUE TITLE
Error message when you click in "Select World:"-box while your worlds folder is empty

### ISSUE THREAD

**Issue by Miner59** [minetest/minetest#2688] opened 2015-05-10 19:29 UTC
Hi,
builtin lua code is not checking for nil correctly in some situations, which leads to the following error messages appearing when you click inside the world selection box while your "worlds" folder is empty.

1st case: singleplayer tab:

2015-05-10 21:02:38: ERROR[main]: MAINMENU ERROR: ...test-master/bin/../builtin/mainmenu/tab_singleplayer.lua:111: attempt to index a nil value
2015-05-10 21:02:38: ERROR[main]: stack traceback:
2015-05-10 21:02:38: ERROR[main]:   ...test-master/bin/../builtin/mainmenu/tab_singleplayer.lua:111: in function 'handle_buttons'
2015-05-10 21:02:38: ERROR[main]:   /media/disk/minetest-master/bin/../builtin/fstk/ui.lua:118: in function 'handle_buttons'
2015-05-10 21:02:38: ERROR[main]:   /media/disk/minetest-master/bin/../builtin/fstk/ui.lua:155: in function </media/disk/minetest-master/bin/../builtin/fstk/ui.lua:148>

2nd case: server tab:

2015-05-10 21:28:24: ERROR[main]: MAINMENU ERROR: ...k/minetest-master/bin/../builtin/mainmenu/tab_server.lua:73: attempt to index a nil value
2015-05-10 21:28:24: ERROR[main]: stack traceback:
2015-05-10 21:28:24: ERROR[main]:   ...k/minetest-master/bin/../builtin/mainmenu/tab_server.lua:73: in function 'handle_buttons'
2015-05-10 21:28:24: ERROR[main]:   /media/disk/minetest-master/bin/../builtin/fstk/ui.lua:118: in function 'handle_buttons'
2015-05-10 21:28:24: ERROR[main]:   /media/disk/minetest-master/bin/../builtin/fstk/ui.lua:155: in function </media/disk/minetest-master/bin/../builtin/fstk/ui.lua:148>

**Comment by kilbith** [comment] 2015-05-10 20:15
Duplicate of https://github.com/minetest/minetest/issues/2548

**Comment by est31** [comment] 2015-05-11 14:35
No, its no duplicate.

**Comment by sfan5** [comment] 2017-11-26 16:46
can't reproduce

**Closed by sfan5** 2017-11-26 16:46 UTC
Labels: @ Client / Audiovisuals, Bug
