### ISSUE TITLE
Mouse lock not always disabled after focus leave

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#3619] opened 2016-01-26 19:12 UTC
So sometimes, but not always, Minetest misses that it lost the focus and continues to grab the mouse. 

This problem persists at least since the last stable. It may even appeared earlier.

I made [a video](https://vid.me/JVHv) of it. The version running is the newest possible dev version (e52ebda8b2273bbd80573838d6dbafb31ee2cd2b).

The DE is gnome-shell in version 3.18.1 and the WM is mutter (3.18.2) although this behaviour can also be observed in Debian Jessie with 3.14. But this is not really relevant as this is a client bug, according to #gnome-shell @gimpnet.

**Comment by red-001** [comment] 2016-01-27 00:13
This a duplicate of  #3507.

**Comment by est31** [comment] 2016-01-27 00:33
Yup, seems 3507 got reproduced on linux as well.

Can you remember how you switched windows? Seems like minetest still thinks its the only active window.

**Closed by est31** 2016-01-27 00:33 UTC
