### ISSUE TITLE
Android: loading bar too little

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#5599] opened 2017-04-16 07:49 UTC
The android bar is too little on Android we should change its size

![screenshot_2017-04-16-09-41-16](https://cloud.githubusercontent.com/assets/119752/25069731/04c470ea-228a-11e7-8f02-02d6ee827ba4.png)

**Comment by kilbith** [comment] 2017-04-16 09:38
Duplicate of https://github.com/minetest/minetest/issues/5403

**Closed** 2017-04-16 09:39 UTC
Labels: Android, Bug
