### ISSUE TITLE
string too long on /profiler print crashes server

### ISSUE THREAD

**Issue by Bastrabun** [minetest/minetest#10246] opened 2020-07-31 18:41 UTC
##### Minetest version

```
5.3.0
```

##### OS / Hardware
Operating system: Debian 10
CPU: Intel(R) Core(TM) i7 CPU 950 @ 3.07GHz

##### Summary
When I have a mod-heavy server and use the chatcommand /profiler print, I want the profiler to send me a chatmessage with the profiler information. The more mods, the longer the message, until the "string is too long". In this case I expect the profiler to send me two messages (preferred) or just say in chat that I need to specify which part of the profiler information I wish to access. I do NOT want the profiler to crash the server.

##### Steps to reproduce

1. Have a bazillion mods installed
2. Use chatcommand /profiler print
=> Crash with 

```
2020-07-31 20:34:07: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '*builtin*' in callback on_chat_message(): String too long
2020-07-31 20:34:07: ERROR[Main]: stack traceback:
2020-07-31 20:34:07: ERROR[Main]: 	[C]: in function 'chat_send_player'
2020-07-31 20:34:07: ERROR[Main]: 	/home/mt-test/5.3.0/test/bin/../builtin/game/chat.lua:71: in function </home/mt-test/5.3.0/test/bin/../builtin/game/chat.lua:48>
2020-07-31 20:34:07: ERROR[Main]: 	/home/mt-test/5.3.0/test/bin/../builtin/game/register.lua:429: in function </home/mt-test/5.3.0/test/bin/../builtin/game/register.lua:413>
```

**Comment by SmallJoker** [comment] 2020-07-31 19:37
Network limitation. The chat message has a maximal length of 2 bytes (65535 characters).
"long strings" can be sent too (4 bytes), but that's sadly not the default. Needs protocol bump to fix this.

As a workaround, please split the chat message after - say - every 10th new line, or display it in a formspec so that copy&paste is possible.

**Comment by Zughy** [comment] 2020-12-16 22:06
Duplicate of #9326. I suggest to close this, as the other one is more generic

**Closed** 2020-12-17 14:35 UTC
Labels: @ Network, Bug, Request / Suggestion
