### ISSUE TITLE
Create a launcher for Minetest to try the latest from master without need for compiling each time

### ISSUE THREAD

**Issue by farooqkz** [minetest/minetest#15048] opened 2024-08-24 20:14 UTC
### Problem

There are many testers, including myself, who wish to use minetest master to test things. The current solution is `git pull` on the already cloned repo and do a build. This not only needs the user/tester to have some technical knowledge but also enough time and computation power to compile things.

### Solutions

 - Create a CI/CD jobs to compile minetest from master for different Operating Systems.
 - Create a minimal launcher to download the artifacts alongside the CHANGELOG and launch it. There could be multiple artifacts with multiple compile time options
 - Maybe also provide a similar way for the users to test PRs?

### Alternatives

An alternative linux specific solution would be providing nightly builds via flatpak/flathub. The advantage's that you won't have to write a launcher. But then users of OS X, BSDs and Windows will be empty handed.

### Additional context

I got the idea from Veloren. They already have a launcher. Maybe you could fork their launcher instead of writing one from scratch?

**Comment by SmallJoker** [comment] 2024-08-24 20:22
Duplicate of https://github.com/minetest/minetest/issues/13817, https://github.com/minetest/minetest/issues/10817, https://github.com/minetest/minetest/issues/7102, https://github.com/minetest/minetest/issues/4917

Feel free to propose a simple script to aid the development process, but the concept of a launcher (as a whole) has been rejected multiple times.

See also: https://github.com/minetest/minetest/issues/9166

**Closed** 2024-08-24 23:56 UTC
Labels: Duplicate, Feature request
