### ISSUE TITLE
Minetest Flatpak won't launch on Fedora Silverblue 36

### ISSUE THREAD

**Issue by rashidi77** [minetest/minetest#12467] opened 2022-06-21 16:57 UTC
##### Minetest version

```
5.5.1
```

##### OS / Hardware

Operating system: Fedora Silverblue 36 
CPU: Intel i5 650 (x86_64)

GPU model: Intel Integrated Graphics 
OpenGL version: 2.1

##### Summary

I used to play Minetest from Flathub on Fedora Silverblue. From last month, it stopped working. I don't know what triggered the issue. I tried reinstalling and resetting the flatpak permissions. It didn't help. Here is the terminal output : 
```
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  0 ()
  Serial number of failed request:  758
  Current serial number in output stream:  758
```

##### Steps to reproduce

1. Login in Fedora Silverblue 36 (Gnome Wayland session)
2. Open Software, download Minetest from Flathub (or use the terminal to download it.)
3. Try to launch Minetest.
4. Try launching it from the terminal using the following command : 
```
flatpak run net.minetest.Minetest
```

**Comment by rubenwardy** [comment] 2022-06-24 12:12
Hi, what does `glxinfo -B` in a terminal show?

**Comment by rashidi77** [comment] 2022-06-26 07:01
> Hi, what does `glxinfo -B` in a terminal show?

It says :
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics (ILK) (0x42)
    Version: 22.1.1
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics (ILK)
OpenGL version string: 2.1 Mesa 22.1.1
OpenGL shading language version string: 1.20

OpenGL ES profile version string: OpenGL ES 2.0 Mesa 22.1.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16

```

**Comment by Vertixty** [comment] 2022-07-02 00:51
type this after you open minetest in terminal `export MESA_GL_VERSION_OVERRIDE=4.5`

**Comment by sfan5** [comment] 2022-07-07 17:34
Another report including reproduction steps: https://irc.minetest.net/minetest/2022-07-07#i_5992261

**Comment by sfan5** [comment] 2022-07-08 08:53
closing in favor of #12518 since that has more details

**Closed by sfan5** 2022-07-08 08:53 UTC
Labels: Bug, @ Startup / Config / Util, Linux
