### ISSUE TITLE
Updating F-Droid version - crash after world is loaded

### ISSUE THREAD

**Issue by licaon-kter** [minetest/minetest#12724] opened 2022-08-24 16:51 UTC
Can anyone take a look at the recipe and the APK?

Ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11612

**Comment by sfan5** [comment] 2022-08-24 16:55
There is probably nothing wrong with your build, instead this is a duplicate of #12658.
You can fix this by building Irrlicht from revision minetest/irrlicht@f0766c845f85c2f467843f20cf811c62cd2402c7

**Comment by licaon-kter** [comment] 2022-08-24 16:59
Ah, ok, ping @linsui

**Closed** 2022-08-24 23:50 UTC
Labels: Android, Question

**Comment by linsui** [comment] 2022-08-25 02:18
Build with minetest_android_deps master and got another error https://gitlab.com/linsui/fdroiddata/-/jobs/2931303238. Do I need to build with also minetest master?

**Comment by sfan5** [comment] 2022-08-25 07:41
You would have to cherry-pick #12700 too.

**Comment by linsui** [comment] 2022-08-25 07:47
Thanks! Unfornatuly F-Droid doesn't have a cherry-pick method... I'll enable x86 build in the next version.

**Comment by linsui** [comment] 2022-08-25 07:49
Ah, it also fixes the crash... I'll apply the patch manully.

**Comment by rubenwardy** [comment] 2022-08-25 09:10
> You would have to cherry-pick #12700 too.

Did you link to the wrong one? The error is in arm, not x86

**Comment by linsui** [comment] 2022-08-25 09:14
Yes, it works, thanks!

**Comment by licaon-kter** [comment] 2022-08-25 09:15
Confirmed working fine both locally and network server.
