### ISSUE TITLE
minetest.settings:get() and minetest.settings:get_bool() must return default values (if any) from settingtypes.txt instead of nil

### ISSUE THREAD

**Issue by aa6** [minetest/minetest#8558] opened 2019-05-24 20:57 UTC
##### Issue type
 - Feature request
 
##### Minetest version
```
5.0.0
```

##### OS / Hardware
Operating system: Linux
CPU: Intel(R) Celeron(R) CPU G530 @ 2.40GHz

##### Summary
As of 5.0.0, while option value is not set by player manually, settings interface will show default value from `settingtypes.txt` but `minetest.settings:get()` and `minetest.settings:get_bool()` will return nil.

```
-- Value is NOT set by player through the settings interface.
print(minetest.settings:get("mymod.untouched_value")) -- Will print "nil".
-- Value is set by player through the settings interface.
print(minetest.settings:get("mymod.touched_value")) -- Will print actual value.
```

That means one can't simply rely on default value from `settingtypes.txt` and this code could result in ModError:

```
local delay = minetest.settings:get("mymod.delay")
minetest.after(delay, foobar)
```

I believe this behavior is bad and should be changed because:

1. It requires unnecessary duplication of default values in both `settingtypes.txt` and code.
2. It requires unnecessary excess checks code that makes mod code more complicated.
3. This behavior is not obvious and discourages (especially junior) mod makers from making mods.

##### Steps to reproduce
1. Create mod `mymod` with `init.lua`:
```
local test = minetest.settings:get("mymod.hello_world") / 42
print(test)
```
and `settingtypes.txt`:
```
# While not set by player, will return nil.
mymod.hello_world (Hello) float 1
```
2. Try to run this mod, get error.
3. Set mymod.hello_world value through settings to 2
4. Try to run this mod, get no errors.

**Comment by srifqi** [comment] 2019-05-24 21:15
The ability to get default value for a setting is added about two years ago (9526c686997285700f500b975a9d971c3ca0a188) and is not exposed to Modding API.
https://github.com/minetest/minetest/blob/b917ea4723fb0fe976486602a456c8dd41eab7ef/src/settings.h#L131-L135

**Comment by pauloue** [comment] 2019-05-24 23:25
Already reported at https://github.com/minetest/minetest/issues/6711.
I was planning on working on this soon.

@srifqi there's still no way to load `m_defaults` with the values in `settingtypes.txt`. `Settings:get` already falls back to the default value if it's in `m_defaults` so the default value is correctly returned for settings defined in `defaultsettings.cpp`.

**Comment by rubenwardy** [comment] 2019-05-24 23:51
Duplicate of #6711

**Closed** 2019-05-24 23:50 UTC

**Comment by srifqi** [comment] 2019-05-25 05:20
@pauloue Oh, seems like I missed it. Thank you for the info.
