### ISSUE TITLE
0.4.17 server crash

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#7419] opened 2018-06-06 19:23 UTC
##### Issue type

 - Bug report
 
##### Minetest version

```
0.4.17
```

##### OS / Hardware

Operating system: Xubuntu 17.10
CPU: Intel Core i5

GPU model: Intel
OpenGL version: 3.3

##### Summary
Server runs for a few minutes then crashes with the following text:

ERROR[Server]: In thread 7fd4e89fb700:
/build/minetest-mVfF6Z/minetest-0.4.17/src/script/common/c_internal.cpp:b8: void log_deprecated(lua_State*, const string&): A fatal error occured: lua_getstack() failed

##### Steps to reproduce
Simply run server, wait and it happens every few minutes.

**Comment by SmallJoker** [comment] 2018-06-06 19:32
Fixed in 0.5.0-dev https://github.com/minetest/minetest/commit/a1598e1b83e2#diff-4e3f0a64f234ea624dbf1b329eb56bd9R157
Originally introduced with 813d819 (looks like it got backported)

**Comment by garywhite207** [comment] 2018-06-06 22:09
Every time I log onto a 0.4.17 server using a 0.4.17 client, the server crashes. It appears that it's most likely server-end because it wasn't having this issue when I was using 0.4.16 client just a few hours ago.

**Comment by SmallJoker** [comment] 2018-06-07 07:56
> Every time I log onto a 0.4.17 server using a 0.4.17 client, the server crashes.

None of the four 0.4.17 (stable) servers from the server list I joined did crash afterwards, so your statement seems to be limited to one server only. Without the crash log from the server it's impossible to tell whether it's the same log_deprecated crash issue.

**Comment by SmallJoker** [comment] 2018-06-07 16:50
Duplicate of #6798

**Comment by rubenwardy** [comment] 2018-06-07 16:50
Duplicate of #6798

**Comment by paramat** [comment] 2018-06-08 21:14
If this is a duplicate of #6798 and was fixed in 0.5dev why is #6798 still open?
Also, this should perhaps stay open as it is valid for 0.4.17.1.

**Comment by paramat** [comment] 2018-06-08 22:20
Ok #6798 is re-opened for this bug in 0.4.17.

**Closed by paramat** 2018-06-08 22:20 UTC
Labels: Bug, Duplicate, High priority
