### ISSUE TITLE
Underground decorations

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#3871] opened 2016-03-17 15:11 UTC
I don't know how difficult this would be but I had this idea of using schematics for ores. It's probably not the first time this was thought of. What do you guys think? Is it possible? Practical? Maybe it'll be faster than using `minetest.place_schematic` within  `minetest.register_on_generated`?

**Comment by C1ffisme** [comment] 2016-03-17 15:45
@MT-Modder That is actually not a bad idea. You could also make things like dungeons using this feature.

**Comment by paramat** [comment] 2016-03-17 20:26
Not really needed enough to add to the engine, best a mod thing.
:-1:

**Comment by C1ffisme** [comment] 2016-03-17 21:46
@paramat What @MT-Modder is suggesting is basically the ability to place structure underground. How is that not needed enough in the engine?

**Comment by paramat** [comment] 2016-03-18 06:26
It's not needed for current mapgen, but might become needed in future.
Sorry for my -1, removed, although i still think it's not much needed.
I need to consider this more.

**Comment by MT-Modder** [comment] 2016-03-18 12:07
@paramat I agree with you it's not needed, because we have to tools to do it now, but if there is a significant speed boost, not to mention it being more modder friendly, I'd like the devs to at least consider adding it. And of course if it happens to be slower then throw this idea in the trash because no one wants that. :smile:

**Comment by ShadowNinja** [comment] 2016-03-19 09:34
This is already planned -- but as an extension to the decoration API instead.

**Comment by MT-Modder** [comment] 2016-03-19 12:57
Makes sense... Do you have any links with that info? I'm just curious.

**Comment by paramat** [comment] 2016-03-19 15:22
ShadowNinja is it? all i know is that l-system tree generation was intended to be added to the decoration API.
Speedwise i think schematic ores will be either similar in speed to what we have or slightly slower. Hmmmm coded our ore types and i assume they are fast due to being specialised towards what they do.
Possible, practical and faster than using lua? yes. But not much needed. Mapgen engine stuff tends to be kept to a minimum and are for things that are very much needed.

**Comment by 0-afflatus** [comment] 2016-03-20 18:25
usecase?

**Comment by C1ffisme** [comment] 2016-03-20 18:27
@0-afflatus Some treasure room buried underground, a type of dungeon, etc. Let's not ask the usecase of something, but lets provide it so that people can use it.

**Comment by 0-afflatus** [comment] 2016-03-20 20:20
> Some treasure room buried underground, a type of dungeon

That's dungeongen surely?
I always ask questions if I don't understand something. That's how I learn.

**Comment by C1ffisme** [comment] 2016-03-21 02:06
@0-afflatus DungeonGen makes structures that work okay, but they don't really contain any kind of treasure, and there isn't a way to make treasure appear in one. Also, the dungeons are randomly generated in one specific way, so if you want it to look the same each time or to be just one room / made out of a different material / etc, then you are out of luck.

Example usecase for this:

![screenshot_20160320_210511](https://cloud.githubusercontent.com/assets/9893266/13909353/7a462082-eedf-11e5-9181-a7f8ca8e4742.png)

(This is a 'buried library' with a hole cut in the ceiling and walls to show the inside. Maybe some kind of super spellbook / essential crafting instructions are inside the bookshelves?)

**Comment by paramat** [comment] 2016-03-21 04:39
My comments are for schematic ores. More useful would be a general way to place schematics underground, this would be done by altering the decoschematic code, which currently only acts at heightmap level.

**Comment by MT-Modder** [comment] 2016-03-21 14:43
That seems like the easiest and most reasonable way.

**Comment by C1ffisme** [comment] 2016-03-21 16:50
@paramat Okay.

**Comment by MT-Modder** [comment] 2016-05-02 22:26
@paramat 
Any news for this yet?
Just curious.

**Comment by paramat** [comment] 2016-05-03 17:50
> Let's not ask the usecase of something,

A use is exactly what is needed. The decoration code is simple and only covers essential heavily-used features of mapgen: plants and trees on the surface. Placing schematics underground is a specialised usecase so best left to mods. I still can't think of an essential usecase, only specialised ones. We won't want to make decoration code more complex for rarely-used specialised uses.

Placing schematics in dungeons is best done in dungeongen, because the decoration code places schematics with random organic placement, this would be useless in a dungeon where a schematic needs to be aligned with walls and doors etc.

:-1:

**Comment by C1ffisme** [comment] 2016-05-03 23:20
Responses in _italic_.

> A use is exactly what is needed. The decoration code is simple and only covers essential heavily-used features of mapgen. *I didn't say that a use wasn't needed, only that dev's should not immediately assume that something has no use whatsoever.* 

Placing schematics in dungeons is best done in dungeongen, because the decoration code places schematics with random organic placement, this would be useless in a dungeon where a schematic needs to be aligned with walls and doors etc. *I didn't say I wanted to place things in dungeons, that library was meant to be a structure on it's own. But a feature to do this would be nice.*

However it's possible that decoration code might change to allow placing decorations in caves and tunnels, this would also be able to place on the cobble of dungeons, but only randomly-placed. *Placing in caves and tunnels is a bit limited, you might be in V7 Mapgen and not see a cave for hours.*

**Comment by sofar** [comment] 2016-05-04 03:11
@C1ffisme you can easily quote by putting ```>``` in front of the quoted text. that's far better readable than italics.

**Comment by C1ffisme** [comment] 2016-05-04 14:22
@sofar I did that. My responses are in _italics_, and the whole thing is 
> quoted.

Here, I'll make it a bit _**easier to read.**_

**Comment by sofar** [comment] 2016-05-04 14:42
@C1ffisme 

> @sofar I did that. My responses are in italics, and the whole thing is _yes, but you shouldn't put your reply on the same line as the quote_

**Comment by C1ffisme** [comment] 2016-05-05 17:18
@sofar Do we have any kind of comment edicate?

You know what? I give up. This is getting really offtopic.

**Comment by paramat** [comment] 2016-05-05 18:03
> I didn't say that a use wasn't needed

"Let's not ask the usecase of something,"

> dev's should not immediately assume that something has no use whatsoever.

I didn't, it's a case of whether it's needed enough for core.

> I didn't say I wanted to place things in dungeons

"DungeonGen makes structures that work okay, but they don't really contain any kind of treasure, and there isn't a way to make treasure appear in one"

> Placing in caves and tunnels is a bit limited, you might be in V7 Mapgen and not see a cave for hours.

There's a cave or tunnel every 96 nodes on average. Hmmmm is keen on the idea of allowing decorations in caves, but of course this means cave floor only, not at a chosen co-ordinate underground.

**Comment by MT-Modder** [comment] 2016-05-05 23:48
@paramat Although I love the idea of adding DungeonGen decorations it's not really what I'm requesting.

I don't want to add decorations to dungeons. I just want to generate schematics underground in a more straight forward way. Just as you said:

> My comments are for schematic ores. More useful would be a general way to place schematics underground, this would be done by altering the decoschematic code, which currently only acts at heightmap level.

**Comment by DonBatman** [comment] 2016-05-06 00:09
I would love to see this happen. Right now I use register_ore to add blocks and an abm to make the block place a schematic.

**Comment by C1ffisme** [comment] 2016-05-06 01:15
> > I didn't say that a use wasn't needed

> "Let's not ask the usecase of something,"

Yes. Let us (the developers, not the whole minetest community) not ask for big, specific usecases of a feature which at first glance seems pointless and useless.

> > Placing in caves and tunnels is a bit limited, you might be in V7 Mapgen and not see a cave for hours.

> There's a tunnel every 96 nodes on average, and 1 large cave per mapchunk. Hmmmm is keen on the idea of allowing decorations in caves, but of course this means cave floor only, not at a chosen co-ordinate underground. This may be the closest we get to this feature request. It would enable placing underground rooms intersecting with tunnels, and enable structures placed in large caves, so would be useful.

96 nodes is a lot (of waiting) when you have a stone pickaxe.

Placing things on cave floors is a nice idea, but pretty limited. A better solution is to make a certain ore that spawns whatever you need when air is above it. (And if air isn't above it, it just turns into normal stone.)

**Comment by 0-afflatus** [comment] 2016-05-08 21:43
@C1ffisme a use case or user story is pretty much essential for code design. Without one I would have no idea where to start or have any idea whether the completed code was fit for purpose. Use cases provide a kind of mental hygiene for programmers, they help prevent feature creep and bloating. Asking for a use case does not imply criticism of the idea, it actually suggests that someone is thinking about how to code it.

**Comment by C1ffisme** [comment] 2016-05-09 14:24
@0-afflatus Yeah, you are right.

The only problem is that often people will assume that a feature has no use at all, and later on someone may have wanted that feature.

It's often best to just build features that allow more customization, rather than making a specific feature for each usecase. Example : Rather than having decoration spawning for on the ground, under the ground, and in the water, allow the user to specify his own area to spawn a decoration anywhere, so that he can spawn it in the air too.

**Comment by DonBatman** [comment] 2016-05-09 14:34
Use cases would be things like placing treasure rooms, unique structures like statues or wells, stalagmites and stalactites, underground villages, mob buildings alien space crafts, dinosaur bones, hermit houses, etc.

**Comment by MT-Modder** [comment] 2016-05-09 14:49
@DonBatman Nice!

It would also allow for custom ore shapes. (If you'd want to use decoration API instead of ore API)

**Comment by paramat** [comment] 2017-03-21 20:17
I intend to add underground decorations, simple and schematic.

**Comment by CasimirKaPazi** [comment] 2017-05-13 12:24
By now for decorations, schematics work under water (corals for example), while simple decorations do not.

**Comment by paramat** [comment] 2017-05-13 14:31
Simple decorations should work underwater, could you link your code that fails?

**Comment by CasimirKaPazi** [comment] 2017-05-14 15:37
minetest.register_decoration({
		deco_type = "simple",
		place_on = {"default:sand"},
		sidelen = 16,
		noise_params = {
			offset = -0.15,
			scale = 0.1,
			spread = {x = 100, y = 100, z = 100},
			seed = 7013,
			octaves = 3,
			persist = 1,
		},
		y_min = -64,
		y_max = -2,
		decoration = "default:coral_orange",
		height = 1,
		height_max = 3,
	})

	minetest.register_decoration({
		deco_type = "schematic",
		place_on = {"default:sand", "default:dirt", "default:dirt_with_grass"},
		noise_params = {
			offset = -0.15,
			scale = 0.1,
			spread = {x = 100, y = 100, z = 100},
			seed = 7013,
			octaves = 3,
			persist = 1,
		},
		y_min = -64,
		y_max = -2,
		schematic = minetest.get_modpath("coral") .. "/schematics/corals.mts",
		flags = "place_center_x, place_center_z",
		rotation = "random",
	})

To see if the decorations get generated at all I increased the height and the noise values. [Here](http://screenshot.ru/upload/images/2017/05/14/coral3fd48.png).

**Comment by paramat** [comment] 2017-05-15 01:37
Confirmed bug, please could you open a new issue for this?

**Comment by paramat** [comment] 2017-05-15 01:49
```
        flags = "liquid_surface, force_placement",
    --  ^ Flags for all decoration types.
    --  ^ "liquid_surface": Instead of placement on the highest solid surface
    --  ^ in a mapchunk column, placement is on the highest liquid surface.
    --  ^ Placement is disabled if solid nodes are found above the liquid surface.
    --  ^ "force_placement": Nodes other than "air" and "ignore" are replaced by the decoration.
```
Use a 'force placement' flag.

**Comment by CasimirKaPazi** [comment] 2017-05-16 21:23
Okay, thanks.

But still schematics work without that flag, so there is *some* inconsistency that should be fixed.

**Comment by paramat** [comment] 2017-05-16 21:39
That's because that schematic uses per-node force-place https://github.com/minetest-mods/saveschems/blob/master/init.lua#L967 as most schematics do. The 'force-place' flag is more general and applies to all the non-zero probability nodes of the schematic.

**Comment by paramat** [comment] 2017-10-11 02:06
Changing title to be for general underground decorations, which i am working on.

**Comment by paramat** [comment] 2017-10-29 12:14
#6519 merged.

**Closed by paramat** 2017-10-29 12:14 UTC
Labels: @ Mapgen, Feature request
