### ISSUE TITLE
Add checkAndLoad  if texture isn't present at loadTime, or minetest.refresh...Cache().

### ISSUE THREAD

**Issue by Nyarg** [minetest/minetest#5614] opened 2017-04-19 14:02 UTC
May be it's more easy for implement in code than #2887 and #2107 ( and #36 ).
For example engine will check unexisted on loadTime texture each time when player set node or mapgen start new chunk session.

**Comment by rubenwardy** [comment] 2018-05-14 11:11
duplicate of #3528

**Closed by rubenwardy** 2018-05-14 11:11 UTC
Labels: Feature request
