### ISSUE TITLE
Server-side node cracks

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7755] opened 2018-09-28 20:09 UTC
##### Issue type

 - Feature request

##### Summary

On servers in Minetest you came tell if a node is being broken before it breaks

My idea is making the node breaking cracks not client-side, so all can see the cracks
##### Steps to reproduce
Go on a server and watch someone break a block

**Comment by SmallJoker** [comment] 2018-09-28 20:19
Duplicate of #4791

**Closed by SmallJoker** 2018-09-28 20:19 UTC
Labels: Duplicate
