### ISSUE TITLE
Ability to crouch and sprint

### ISSUE THREAD

**Issue by AlanReviews** [minetest/minetest#10691] opened 2020-12-03 19:26 UTC
## Problem
Can we have the ability to crouch and sprint in Minetest?

## Solutions
Crouching where a player moves closer to the ground. Sprint can be helpful for running from one place to another quickly.

## Alternatives
One alternative I considered is Minecraft

**Comment by SmallJoker** [comment] 2020-12-03 19:59
Sprint: W + E, check for `fast` privilege and whether it's enabled (configure hotkeys)

Crouching: either duplicate of #2063, or can be implemented using mods. No need to hardcode this into Minetest.

**Closed by SmallJoker** 2020-12-03 19:59 UTC
Labels: Feature request

**Comment by domsson** [comment] 2022-07-02 09:33
Too bad this was closed - `fast` privilege is nothing like what one would expect from sprinting. Sprinting is therefore not yet implemented.
