### ISSUE TITLE
Strange light calculation issues

### ISSUE THREAD

**Issue by sapier** [minetest/minetest#3430] opened 2015-12-06 18:30 UTC
For some reason light calculation causes way to big "dark" areas.

![ays9xvp](https://cloud.githubusercontent.com/assets/3686677/15726583/8b3d326a-2849-11e6-8993-a2a6c995b833.jpg)

Debian 8.2
Irrlicht 1.8.1

**Comment by paramat** [comment] 2015-12-06 19:19
Have saplings been grown here or schematics spawned? Both of those sometimes cause shadows due to their use of 'updateLighting' which needs improvement.

**Comment by MoNTE48** [comment] 2015-12-06 23:27
I is going to v7 when high in the sky floating island that I can not see because of the short draw. It is very annoying.

**Comment by MoNTE48** [comment] 2015-12-07 19:34
https://github.com/minetest/minetest/commit/49073ba2c34dfd8e286865ed2d108a4ec1eb3e3c

**Comment by sapier** [comment] 2015-12-07 20:41
Yes the trees in front of the house as well as those within the fence grew from saplings ... are you telling me there's a 100% chance of broken lighting if you use saplings? ;-)

**Comment by 0-afflatus** [comment] 2015-12-08 13:57
I think the chance is relative to the size of tree relative to the mapchunk. This causes up to 30% broken tree shadows using moretrees. Minetest has so many lighting issues, I'm just getting used to using mapfix.
Also #2759

**Comment by paramat** [comment] 2015-12-09 16:53
The moretrees shadows are a different issue, caused by using l-system generation during mapgen.
Not 100%, but if many saplings grow at once it can cause shadows, 'unfortunately' we have ABM catch-up for saplings which means returning to an area can cause many to grow at once.

L-system trees, spawing of schematics after mapgen, and the LVM 'vm:update_map()' all use the engine 'updateLighting()' which sometimes causes shadows in all those uses.

**Comment by paramat** [comment] 2017-03-11 02:47
#4967 merged.

**Closed by paramat** 2017-03-11 02:47 UTC
Labels: @ Server / Client / Env., Bug
