### ISSUE TITLE
File browser crashes app

### ISSUE THREAD

**Issue by Unexian** [minetest/minetest#14718] opened 2024-05-31 17:21 UTC
### Minetest version

```true
Minetest 5.8.0 (Windows)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Irrlicht device

WIN32

### Operating system and version

Win11 home 22H2 22621.3593

### CPU model

Intel core 11G i5-1135G7 2.4GHz

### Active renderer

OpenGL 4.6.0

### Summary

When I try to open the browse menu in font selection, the app crashes.

### Steps to reproduce

Go to settings -> advanced and open the font browser

**Comment by SmallJoker** [comment] 2024-05-31 17:30
Already fixed. Duplicate of #14381.

**Closed by SmallJoker** 2024-05-31 17:30 UTC
Labels: Unconfirmed bug
