### ISSUE TITLE
Perfomance: LOD and mipmap

### ISSUE THREAD

**Issue by JeanPaulLucien** [minetest/minetest#13087] opened 2022-12-28 17:40 UTC
## Problem

Bad optimization and perfomans. No LOD.

## Solutions

Add LOD.

I suggest next levels:
0-20 blocks: original.
21-60 blocks: 80% size.
60-120 blocks: 40% size.
120-180 blocks: 20% size.
181+ blocks: median color of block texture.

**Comment by rollerozxa** [comment] 2022-12-28 17:51
Farmesh, I suppose.

**Comment by JeanPaulLucien** [comment] 2022-12-28 17:54
@FossFanatic I'm not sure about mipmap. I have not found textures in game files for LOD or mipmap.

**Comment by JeanPaulLucien** [comment] 2022-12-28 17:54
@FossFanatic I'm not sure about mipmap. I have not found textures in game files for LOD or mipmap.

**Comment by JeanPaulLucien** [comment] 2022-12-28 18:05
> You should not have changed your title. Mipmapping is already in the game and available in the settings.

But no textures for mipmap. Textures should be in game files, not generated in real-time. Mipmap without textures is not mipmap.   I gets 60 FPS in Minetest and high load of my system. Like in Crysis with high graphic settings.

**Comment by rollerozxa** [comment] 2022-12-28 18:09
> But no textures for mipmap. Textures should be in game files, not generated in real-time.

No, real-time mipmapping is still mipmapping.

**Comment by JeanPaulLucien** [comment] 2022-12-28 18:12
I checked. Mipmap does not work.

**Comment by Desour** [comment] 2022-12-28 19:22
* Mipmapping gives you no performance benefit if you use small textures anyway. It's used to avoid certain aliasing effects.
* Mipmaps are auto-generated, when the texture is loaded into opengl or so.
  Storing them in files could allow the modder to use a different scaling algorithm, but that's not really a thing to be done by modders.
* In general, there's lower hanging fruit than adding LOD for mesh data, i.e. reducing the number of draw calls.
* Farmeshes are not a new thing. => duplicate

**Comment by SmallJoker** [comment] 2022-12-28 19:26
Duplicate of #6607

Low quality issue. It neither states a clear request or does it describe a bug with reproduction steps, hence marked for closing.

**Closed** 2022-12-28 19:51 UTC
Labels: Feature request, Possible close
