### ISSUE TITLE
Irrlicht 1.9 ogles and drawscene.cpp

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#3646] opened 2016-02-04 01:35 UTC
```
[armeabi-v7a] Compile++ thumb: minetest <= drawscene.cpp
jni/../jni/src/drawscene.cpp: In function 'void draw_anaglyph_3d_mode(Camera&, bool, Hud&, std::vector<irr::core::aabbox3d<float> >, irr::video::IVideoDriver*, irr::scene::ISceneManager*, bool, Client&, irr::gui::IGUIEnvironment*)':
jni/../jni/src/drawscene.cpp:78:70: warning: 'bool irr::video::IVideoDriver::beginScene(bool, bool, irr::video::SColor, const irr::video::SExposedVideoData&, irr::core::rect<int>*)' is deprecated (declared at deps/irrlicht/include/IVideoDriver.h:254) [-Wdeprecated-declarations]
  driver->beginScene( true, true, irr::video::SColor(0, 200, 200, 255));
                                                                      ^
jni/../jni/src/drawscene.cpp:107:23: warning: 'void irr::video::IVideoDriver::clearZBuffer()' is deprecated (declared at deps/irrlicht/include/IVideoDriver.h:1417) [-Wdeprecated-declarations]
  driver->clearZBuffer();
                       ^
jni/../jni/src/drawscene.cpp: In function 'irr::video::ITexture* draw_image(const v2u32&, paralax_sign, const matrix4&, const vector3df&, bool, irr::video::IVideoDriver*, Camera&, irr::scene::ISceneManager*, Hud&, std::vector<irr::core::aabbox3d<float> >&, bool, Client&, irr::gui::IGUIEnvironment*, irr::video::SColor)':
jni/../jni/src/drawscene.cpp:173:65: warning: 'bool irr::video::IVideoDriver::setRenderTarget(irr::video::ITexture*, bool, bool, irr::video::SColor)' is deprecated (declared at deps/irrlicht/include/IVideoDriver.h:626) [-Wdeprecated-declarations]
      skycolor.getRed(), skycolor.getGreen(), skycolor.getBlue()));
                                                                 ^
jni/../jni/src/drawscene.cpp:183:23: warning: 'void irr::video::IVideoDriver::clearZBuffer()' is deprecated (declared at deps/irrlicht/include/IVideoDriver.h:1417) [-Wdeprecated-declarations]
  driver->clearZBuffer();
                       ^
jni/../jni/src/drawscene.cpp:203:65: warning: 'bool irr::video::IVideoDriver::setRenderTarget(irr::video::ITexture*, bool, bool, irr::video::SColor)' is deprecated (declared at deps/irrlicht/include/IVideoDriver.h:626) [-Wdeprecated-declarations]
      skycolor.getRed(), skycolor.getGreen(), skycolor.getBlue()));
                                                                 ^
jni/../jni/src/drawscene.cpp: In function 'irr::video::ITexture* draw_hud(irr::video::IVideoDriver*, const v2u32&, bool, Hud&, Client&, bool, irr::video::SColor, irr::gui::IGUIEnvironment*, Camera&)':
jni/../jni/src/drawscene.cpp:215:33: warning: 'bool irr::video::IVideoDriver::setRenderTarget(irr::video::ITexture*, bool, bool, irr::video::SColor)' is deprecated (declared at deps/irrlicht/include/IVideoDriver.h:626) [-Wdeprecated-declarations]
    irr::video::SColor(255,0,0,0));
                                 ^
jni/../jni/src/drawscene.cpp:229:65: warning: 'bool irr::video::IVideoDriver::setRenderTarget(irr::video::ITexture*, bool, bool, irr::video::SColor)' is deprecated (declared at deps/irrlicht/include/IVideoDriver.h:626) [-Wdeprecated-declarations]
      skycolor.getRed(), skycolor.getGreen(), skycolor.getBlue()));
                                                                 ^
jni/../jni/src/drawscene.cpp: In function 'void draw_interlaced_3d_mode(Camera&, bool, Hud&, std::vector<irr::core::aabbox3d<float> >, irr::video::IVideoDriver*, irr::scene::ISceneManager*, const v2u32&, bool, Client&, irr::gui::IGUIEnvironment*, irr::video::SColor)':
jni/../jni/src/drawscene.cpp:263:23: warning: 'void irr::video::IVideoDriver::clearZBuffer()' is deprecated (declared at deps/irrlicht/include/IVideoDriver.h:1417) [-Wdeprecated-declarations]
  driver->clearZBuffer();
                       ^
jni/../jni/src/drawscene.cpp: In function 'void draw_pageflip_3d_mode(Camera&, bool, Hud&, std::vector<irr::core::aabbox3d<float> >, irr::video::IVideoDriver*, irr::scene::ISceneManager*, const v2u32&, bool, Client&, irr::gui::IGUIEnvironment*, irr::video::SColor)':
jni/../jni/src/drawscene.cpp:424:60: error: no matching function for call to 'irr::video::IVideoDriver::setRenderTarget(irr::video::E_RENDER_TARGET)'
  driver->setRenderTarget(irr::video::ERT_STEREO_LEFT_BUFFER);
                                                            ^
jni/../jni/src/drawscene.cpp:424:60: note: candidates are:
In file included from deps/irrlicht/include/IrrlichtDevice.h:10:0,
                 from jni/../jni/src/irrlichttypes_extrabloated.h:28,
                 from jni/../jni/src/camera.h:23,
                 from jni/../jni/src/drawscene.h:23,
                 from jni/../jni/src/drawscene.cpp:20:
deps/irrlicht/include/IVideoDriver.h:620:16: note: virtual bool irr::video::IVideoDriver::setRenderTarget(irr::video::ITexture*, irr::u16, irr::video::SColor, irr::f32, irr::u8)
   virtual bool setRenderTarget(ITexture* texture, u16 clearFlag=ECBF_COLOR|ECBF_DEPTH, SColor clearColor = SColor(255,0,0,0),
                ^
deps/irrlicht/include/IVideoDriver.h:620:16: note:   no known conversion for argument 1 from 'irr::video::E_RENDER_TARGET' to 'irr::video::ITexture*'
deps/irrlicht/include/IVideoDriver.h:626:25: note: bool irr::video::IVideoDriver::setRenderTarget(irr::video::ITexture*, bool, bool, irr::video::SColor)
   _IRR_DEPRECATED_ bool setRenderTarget(ITexture* texture, bool clearBackBuffer, bool clearZBuffer, SColor color = SColor(255,0,0,0))
                         ^
deps/irrlicht/include/IVideoDriver.h:626:25: note:   candidate expects 4 arguments, 1 provided
jni/../jni/src/drawscene.cpp:434:71: warning: 'bool irr::video::IVideoDriver::beginScene(bool, bool, irr::video::SColor, const irr::video::SExposedVideoData&, irr::core::rect<int>*)' is deprecated (declared at deps/irrlicht/include/IVideoDriver.h:254) [-Wdeprecated-declarations]
  driver->beginScene(true, true, irr::video::SColor(200, 200, 200, 255));
                                                                       ^
jni/../jni/src/drawscene.cpp:453:61: error: no matching function for call to 'irr::video::IVideoDriver::setRenderTarget(irr::video::E_RENDER_TARGET)'
  driver->setRenderTarget(irr::video::ERT_STEREO_RIGHT_BUFFER);
                                                             ^
jni/../jni/src/drawscene.cpp:453:61: note: candidates are:
In file included from deps/irrlicht/include/IrrlichtDevice.h:10:0,
                 from jni/../jni/src/irrlichttypes_extrabloated.h:28,
                 from jni/../jni/src/camera.h:23,
                 from jni/../jni/src/drawscene.h:23,
                 from jni/../jni/src/drawscene.cpp:20:
deps/irrlicht/include/IVideoDriver.h:620:16: note: virtual bool irr::video::IVideoDriver::setRenderTarget(irr::video::ITexture*, irr::u16, irr::video::SColor, irr::f32, irr::u8)
   virtual bool setRenderTarget(ITexture* texture, u16 clearFlag=ECBF_COLOR|ECBF_DEPTH, SColor clearColor = SColor(255,0,0,0),
                ^
deps/irrlicht/include/IVideoDriver.h:620:16: note:   no known conversion for argument 1 from 'irr::video::E_RENDER_TARGET' to 'irr::video::ITexture*'
deps/irrlicht/include/IVideoDriver.h:626:25: note: bool irr::video::IVideoDriver::setRenderTarget(irr::video::ITexture*, bool, bool, irr::video::SColor)
   _IRR_DEPRECATED_ bool setRenderTarget(ITexture* texture, bool clearBackBuffer, bool clearZBuffer, SColor color = SColor(255,0,0,0))
                         ^
deps/irrlicht/include/IVideoDriver.h:626:25: note:   candidate expects 4 arguments, 1 provided
jni/../jni/src/drawscene.cpp:463:71: warning: 'bool irr::video::IVideoDriver::beginScene(bool, bool, irr::video::SColor, const irr::video::SExposedVideoData&, irr::core::rect<int>*)' is deprecated (declared at deps/irrlicht/include/IVideoDriver.h:254) [-Wdeprecated-declarations]
  driver->beginScene(true, true, irr::video::SColor(200, 200, 200, 255));
                                                                       ^
jni/../jni/src/drawscene.cpp: In function 'void draw_load_screen(const wstring&, irr::IrrlichtDevice*, irr::gui::IGUIEnvironment*, float, int, bool)':
jni/../jni/src/drawscene.cpp:606:67: warning: 'bool irr::video::IVideoDriver::beginScene(bool, bool, irr::video::SColor, const irr::video::SExposedVideoData&, irr::core::rect<int>*)' is deprecated (declared at deps/irrlicht/include/IVideoDriver.h:254) [-Wdeprecated-declarations]
   driver->beginScene(true, true, video::SColor(255, 140, 186, 250));
                                                                   ^
jni/../jni/src/drawscene.cpp:610:61: warning: 'bool irr::video::IVideoDriver::beginScene(bool, bool, irr::video::SColor, const irr::video::SExposedVideoData&, irr::core::rect<int>*)' is deprecated (declared at deps/irrlicht/include/IVideoDriver.h:254) [-Wdeprecated-declarations]
   driver->beginScene(true, true, video::SColor(255, 0, 0, 0));
                                                             ^
make[2]: *** [obj/local/armeabi-v7a/objs/minetest/jni/src/drawscene.o] Error 1
```

**Comment by est31** [comment] 2016-02-04 12:04
So @MoNTE48 you changed the irrlicht revision, which is fixed in the android makefile? I don't think its a bug (neither ours nor theirs) then, irrlicht 1.9 isn't stable and its very likely that it breaks. Once we update the revision in the makefile, this issue has to be addressed, yes, but that's something the person who makes the updating change to ensure.

**Comment by MoNTE48** [comment] 2016-02-04 12:10
@est31, yes.Yes, but you can not hurry - a new Irrlicht works very bad :)

**Comment by neoascetic** [comment] 2016-02-05 11:57
@est31 I have no clue. If the issue is invalid - why use label? Why don't simply close the issue?

**Closed** 2016-02-05 13:22 UTC
Labels: @ Build, Invalid

**Comment by MoNTE48** [comment] 2016-02-25 12:12
@est31 est, it breaks compatibility with Irrlicht 1.9! Why leave the error, which would be difficult to fix in the future? If I revert that commit, I can make all successful!
