### ISSUE TITLE
Strange glitches when player sneak-jumps

### ISSUE THREAD

**Issue by KaylebJay** [minetest/minetest#9945] opened 2020-05-27 00:20 UTC
##### Minetest version
Minetest 5.2.0-stable

##### OS / Hardware
Operating system: Linux

##### Summary
When the player is holding sneak, weird glitches and climbing many nodes can happen. For example, I can climb a two block 'step' or even walk on the side of a vertical wall.

##### Steps to reproduce
Create a two block step. Hold sneak and jump on it carefully, it might require some practice.
For the vertical wall glitch, make a wall and jump on it (using shift + fast mode is probably easiest). If you do it right, you can glitch and get 'stuck' in the wall, even though you should be falling.
If this is a duplicate, apologies.

**Comment by sfan5** [comment] 2020-05-27 09:29
5.3.0 has had numerous changes/fixes to collision detection, please reproduce it with that.

**Comment by KaylebJay** [comment] 2020-05-27 15:12
Will try now.

**Comment by KaylebJay** [comment] 2020-05-27 15:27
Both work on minetest 5.3 though its harder to trigger. I can successfully glitch into a vertical block by using sneak and get stuck there. 
![screenshot_20200527_092500](https://user-images.githubusercontent.com/44441970/83040137-2a641b00-9ffc-11ea-84d0-b28dbc6e0504.png)
Once you are glitched in like this, you can't move at all until you release sneak. You can, however, trigger the walking animation by pressing forward.

**Comment by jastevenson303** [comment] 2020-05-27 15:29
I cannot reproduce this with sneak_glitch=false and new_move=true

I use this feature a lot, and swap between new_move and old_move
constantly.  Everything currently seems to be alright.  I updated Minetest
yesterday, but I will continue to test.

**Comment by KaylebJay** [comment] 2020-05-27 16:20
sneak_glitch=false - oh. If sneak_glitch is true, is this literally a 'feature' of that setting?

**Comment by jastevenson303** [comment] 2020-05-27 16:29
It used to be a bug that everyone had.  It was taken out, and later
re-implemented as a feature players must opt into.  I made a mod called
SuperSprint! which utilizes this feature.

**Comment by paramat** [comment] 2020-05-27 18:58
@KaylebJay are you testing in singleplayer with MTG and no added mods?
The 2 relevant settings are 'new move' and 'sneak glitch':
```
* `set_physics_override(override_table)`
    * `override_table` is a table with the following fields:
        * `speed`: multiplier to default walking speed value (default: `1`)
        * `jump`: multiplier to default jump value (default: `1`)
        * `gravity`: multiplier to default gravity value (default: `1`)
        * `sneak`: whether player can sneak (default: `true`)
        * `sneak_glitch`: whether player can use the new move code replications
          of the old sneak side-effects: sneak ladders and 2 node sneak jump
          (default: `false`)
        * `new_move`: use new move/sneak code. When `false` the exact old code
          is used for the specific old sneak behaviour (default: `true`)
```
They are both physics overrides set by the server, so it is important to know whether you are using a game or mod, or are on a server, that might set these to non-default values.

Odd glitches when holding sneak are very common throughout MT history.
The much liked classic 'sneak ladder' and '2 node sneak-jump' behaviours were originally bugs, but players became used to them so are now considered features to preserve.

Now in the 'new movement code' we already have new sneak related glitches occuring. They are very difficult to solve, if one is solved often it causes another one to pop up.

Related issues #7725 #5861 #5438

**Comment by KaylebJay** [comment] 2020-05-28 02:29
Correct, MTG and no added mods or minetest.conf settings for the test.

The two node sneak jump is OK, I use that bug too ;)
I think sneak glitching should be disabled by default.

**Comment by jastevenson303** [comment] 2020-05-28 03:29
I suggest you update your minetest to a fresh install and clear out any mods.  Sneak jumping is off by default, and the only way to jump two nodes high is if you have a mod enabling it.

**Comment by KaylebJay** [comment] 2020-05-28 03:35
There aren't any mods. I'm on the newest commit ;) 
I can't jump two blocks without another block being on the side. What I can do, is glitch into a block and get stuck there.

**Comment by jastevenson303** [comment] 2020-05-28 11:41
Those are called stairs, when two blocks vertical blocks are adjacent to
one block.

**Comment by paramat** [comment] 2020-05-28 17:41
> I think sneak glitching should be disabled by default.

The 'sneak_glitch' physics override is disabled by default.

**Comment by KaylebJay** [comment] 2020-05-28 22:09
> Update: Here's a video I just recorded trying to replicate what you say occurs.  I am not seeing it.

Try jumping using fast mode and while holding down sneak onto a vertical wall of blocks. It takes a few tries but by releasing and pressing sneak you can 'glitch' into the wall - you're not inside, you're just stuck outside. Releasing sneak would make you fall.

**Comment by jastevenson303** [comment] 2020-05-29 02:07
Should I keep movement_speed_fast at its default setting of 20?

**Comment by KaylebJay** [comment] 2020-05-29 13:50
Yeah. All defaults.

**Comment by paramat** [comment] 2020-05-29 18:10
> I can't jump two blocks without another block being on the side (EDIT: without sneak jumping)

This wording is confusing, you have stated in the first post that the glitch occurs when sneak-jumping.
Surely you mean: you can jump up 2 nodes if there is a block on the side by sneak-jumping.

**Comment by KaylebJay** [comment] 2020-05-30 13:21
Yeah.

**Comment by paramat** [comment] 2020-05-30 20:51
Ok thanks, sounds like the player is sneak-latching onto the side block on the way up, allowing a 2 node jump. This is similar to the 'sneak ladder' glitch in old movement code.

**Comment by jastevenson303** [comment] 2020-05-30 21:39
no it's not

**Comment by paramat** [comment] 2020-05-30 23:50
I agree, it is not particualrly similar =)

**Comment by KaylebJay** [comment] 2020-05-31 04:48
Definitely, it is glitching onto the side block.

**Comment by Zughy** [comment] 2022-08-04 00:33
can't reproduce, closing

**Closed by Zughy** 2022-08-04 00:33 UTC
Labels: Unconfirmed bug, @ Server / Client / Env.
