### ISSUE TITLE
Create Android dependency building scripts

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10529] opened 2020-10-20 14:07 UTC
The deps for Android are currently binaries in a repo. This is not good for maintenance, and also means that Minetest cannot be updated on F-Droid.

Dependencies should be built using scripts in some way. Either with gradle locally (and cached), or as part of a GitHub Pipeline to make the dependencies available as a download

**Comment by sfan5** [comment] 2020-10-20 14:27
I think it's enough if the deps *can* be built manually, I don't think this should happen during the normal build process.

**Comment by rubenwardy** [comment] 2020-10-20 14:29
Having a GitHub pipeline to create binaries is enough to do that, F-Droid can then run the scripts in that pipeline

**Comment by sfan5** [comment] 2020-10-20 14:39
In that case the scripts here need to be wired up differently: https://github.com/minetest/minetest_android_deps_binaries/blob/master/Android/Build/Makefile

(Actually, they should be thrown away and rewritten not to be a terrible mess.)

**Comment by ronoaldo** [comment] 2020-11-25 16:32
This is marked as high priority. The repository Android/Build/Makefile is quite large but seems to already download and build dependencies, right? The idea is to trigger the pipeline to run that Build and perform a release for each of them in the same repo? Or would it work to set the sources as submodules (if they are all git) and run a single build?

**Comment by rubenwardy** [comment] 2021-02-17 02:13
> This is marked as high priority. The repository Android/Build/Makefile is quite large but seems to already download and build dependencies, right? The idea is to trigger the pipeline to run that Build and perform a release for each of them in the same repo? Or would it work to set the sources as submodules (if they are all git) and run a single build?

I've created a repo for this: https://github.com/minetest/minetest_android_deps

It has a GitHub pipeline to build and then artifact the dependencies as a tagged release `latest`. F-Droid can then use the Makefile there to build manually. So far, I'm having issues on my own computer and there are still deps not added from what I can see

**Closed** 2022-04-15 02:30 UTC
Labels: Feature request, Android, High priority

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-04-15 15:12
@rubenwardy, why close this? Your potential solution during the future does not negate this problem. Consequently, please reopen it until the problem is remediated.

**Comment by rubenwardy** [comment] 2022-04-15 16:19
This issue has been resolved as Minetest now uses the scripts in this repo: https://github.com/minetest/minetest_android_deps

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2022-04-15 16:28
@rubenwardy, I am thankful.
