### ISSUE TITLE
Stack splitting equally by shift click

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5374] opened 2017-03-11 20:55 UTC
I saw a really nice feature in Minecraft I really want to see in Minetest too.

For example, if you want to make a lot of fences and you have a stack of 60 sticks, hold down a key, maybe sneak, and place the stack in the first slot. Than click on the next slot and the stack will be splittet between the slots. If you click on the third slot all sticks get splittet between all 3 slots, so each slot has 20 sticks. 

Watch this Video from the position. Maybe pause the video and set playback speed to 0.25

https://youtu.be/EtZ7ZwMyPz8?t=248

**Comment by tobyplowy** [comment] 2017-03-11 23:35
@MarkuBu no just hold in left click and drag it across the slots (that's how MC does it)

**Comment by Fixer-007** [comment] 2017-03-12 00:00
Those kinds of tricks improve crafting a lot, I seen this in many lets plays.

**Comment by dsohler** [comment] 2017-03-12 13:41
Wasn’t it that it currently is impossible because the way how *formspecs* are implemented and it would need major engine changes to add it and thus likely not happen anytime soon?

**Comment by rubenwardy** [comment] 2017-03-12 13:43
> Wasn’t it that it currently is impossible because the way how formspecs are implemented and it would need major engine changes to add it and thus likely not happen anytime soon?

I don't think so

**Comment by dsohler** [comment] 2017-03-13 07:55
Unfortunately I can't find it right now but I'm sure there are/were issues why this can't be added in an easy way.

**Comment by sorcerykid** [comment] 2017-03-14 17:37
Why does it necessarily even have to involve clicking? On my server I'm developing a new crafting grid formspec that uses "macro" inventory slots that arrange stacks of items into the crafting grid automatically.

For example, dropping a stack of 99 wood into the "slab" macro (which is depicted as three horizontal dots) would evenly divide the wood as [33] [33] [33] into the top row of the crafting grid. No excessive clicking necessary.

So far I have macros defined for blocks, slabs, stairs, square, helmet, leggings, chestplate, and boots.

**Comment by Avamander** [comment] 2017-03-18 21:53
The way MC currently has solved this seems to be intuitive and something people are accustomed to. I feel this feature should be implemented without trying to add some quirks to it (unless it's again, a subgame).

**Comment by paramat** [comment] 2018-09-19 01:53
Duplicate of #2963 (closed)

**Closed** 2023-06-05 10:00 UTC
Labels: Feature request, @ Client / Controls / Input, Formspec
