### ISSUE TITLE
Mesh is reloaded when set_properties is called

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6572] opened 2017-10-30 06:34 UTC
Every time I open a form (inventory, chest, chat...) I got "Load mesh: ..." messages on the console. 

Is that a bug or an intent?

**Comment by paramat** [comment] 2017-10-30 10:20
I've just noticed this too when using a sfinv tab, every 3s. It seems to have started recently.

**Comment by MarkuBu** [comment] 2017-10-30 10:51
It get's worse if you have mobs redo installed.

**Comment by DS-Minetest** [comment] 2017-10-30 11:58
(I'm not sure whether the new title is better since `character.b3d` comes from minetest_game.)

**Comment by paramat** [comment] 2017-10-30 14:47
Good point, to clarify this message happens in MTGame, the mesh name will be different in other situations.

Testing:
This does not happen in minimal subgame.
It still happens in MTGame if creative and sfinv are removed.

**Comment by paramat** [comment] 2017-10-30 15:02
Ok it's binoculars mod, so my fault and a MTGame issue.

**Comment by paramat** [comment] 2017-10-30 15:14
Binoculars used in minimal subgame does not cause the bug, so possibly an intereaction with another MTGame mod? Maybe sfinv? @rubenwardy

**Comment by paramat** [comment] 2017-10-30 15:41
Changing the 'set property' action to a change of collisionbox also causes the bug:
```
function binoculars.update_player_property(player)
	local creative_enabled =
		(creative and creative.is_enabled_for(player:get_player_name())) or
		creative_mode_cache

	if creative_enabled or
			player:get_inventory():contains_item("main", "binoculars:binoculars") then
		player:set_properties({collisionbox = {-0.3, 0.0, -0.3, 0.3, 1.77, 0.3}})
	else
		player:set_properties({collisionbox = {-0.3, 0.0, -0.3, 0.3, 1.77, 0.3}})
	end
end
```
It seems to be any use of 'set properties' reloads the mesh if a formspec is open.
Maybe https://github.com/minetest/minetest/blob/610ea6f21629933be3b38c2b5fce53a35c5aac3a/src/content_cao.cpp#L1241

**Comment by paramat** [comment] 2017-10-30 16:39
Ugh, i've just confirmed that even without a formspec open the player animation is reset every time 'set properties' is used, so the binoculars mod does this every 5s. I will have to edit the mod to not do this.

**Comment by paramat** [comment] 2017-10-30 17:11
Confirmed in debug.txt, mesh is reloaded every 5s even if formspec is not open.
Look for 
```
2017-10-30 17:07:19: INFO[Main]: GenericCAO::addToScene(): mesh
2017-10-30 17:07:19: INFO[Main]: Irrlicht: Loaded mesh: character.b3d
```
```
2017-10-30 17:07:19: INFO[Main]: GenericCAO::addToScene(): mesh
2017-10-30 17:07:19: INFO[Main]: Irrlicht: Loaded mesh: character.b3d
2017-10-30 17:07:21: INFO[Main]: Client: time_of_day=6726 time_speed=8 dr=1000
2017-10-30 17:07:22: INFO[Server]: Saving registered mod storages.
2017-10-30 17:07:22: INFO[Server]: ServerMap: Written: 4 block files, 3355 blocks in memory.
2017-10-30 17:07:22: INFO[Server]: ServerMap: Blocks modified by: 
2017-10-30 17:07:22: INFO[Server]:   setNodeNoCheck: - - - - - - - - - - - - - 4
2017-10-30 17:07:24: INFO[Main]: GenericCAO::addToScene(): mesh
2017-10-30 17:07:24: INFO[Main]: Irrlicht: Loaded mesh: character.b3d
2017-10-30 17:07:25: INFO[Server]: ServerMap: Unloaded 136 blocks from memory, of which 0 were written, 3219 blocks in memory.
2017-10-30 17:07:26: INFO[Server]: Players:
2017-10-30 17:07:26: INFO[Server]: * singleplayer	RemoteClient 2: m_blocks_sent.size()=2808, m_blocks_sending.size()=0, m_nearest_unsent_d=0, m_excess_gotblocks=0
2017-10-30 17:07:26: INFO[Main]: Client: avg_rtt=0.001
2017-10-30 17:07:26: INFO[Main]: Client: time_of_day=6738 time_speed=8 dr=1000
2017-10-30 17:07:27: INFO[Server]: Saving registered mod storages.
2017-10-30 17:07:28: INFO[Server]: ServerMap: Written: 3 block files, 3219 blocks in memory.
2017-10-30 17:07:28: INFO[Server]: ServerMap: Blocks modified by: 
2017-10-30 17:07:28: INFO[Server]:   setNodeNoCheck: - - - - - - - - - - - - - 3
2017-10-30 17:07:28: INFO[Server]: ServerMap: Unloaded 492 blocks from memory, of which 0 were written, 2727 blocks in memory.
2017-10-30 17:07:29: INFO[Main]: GenericCAO::addToScene(): mesh
2017-10-30 17:07:29: INFO[Main]: Irrlicht: Loaded mesh: character.b3d
2017-10-30 17:07:31: INFO[Server]: ServerMap: Unloaded 1037 blocks from memory, of which 0 were written, 1690 blocks in memory.
2017-10-30 17:07:31: INFO[Main]: Client: time_of_day=6749 time_speed=8 dr=1000
2017-10-30 17:07:32: INFO[Server]: Saving registered mod storages.
2017-10-30 17:07:33: INFO[Server]: ServerMap: Written: 1 block files, 1690 blocks in memory.
2017-10-30 17:07:33: INFO[Server]: ServerMap: Blocks modified by: 
2017-10-30 17:07:33: INFO[Server]:   setNodeNoCheck: - - - - - - - - - - - - - 1
2017-10-30 17:07:33: INFO[Main]: GenericCAO::addToScene(): mesh
2017-10-30 17:07:33: INFO[Main]: Irrlicht: Loaded mesh: character.b3d
```

**Comment by paramat** [comment] 2017-10-30 17:19
Maybe here
https://github.com/minetest/minetest/blob/610ea6f21629933be3b38c2b5fce53a35c5aac3a/src/content_cao.cpp#L1235
we need a new 'cmd' type for 'set properties' that does not reset visuals?

**Comment by MarkuBu** [comment] 2017-10-30 17:19
Are you sure that this is caused by Binoculars mod? I get the same issue in Minetest 0.4.16 and the farlands subgame. Or is this caused by an old mobs redo version?

But there is not only character.b3d loaded, but any active mob

**Comment by paramat** [comment] 2017-10-30 17:22
In vanilla MTGame only the binoculars mod causes it as far as i know, but maybe another MTGame mod can cause it. Any mod that uses 'player:set_properties' will trigger it.
In 0.4.16 were you using any non-vanilla mods?

**Comment by paramat** [comment] 2017-10-30 17:37
`2017-10-30 17:07:19: INFO[Main]: Irrlicht: Loaded mesh: character.b3d`
The loading of the mesh is an irrlicht operation so we may not be able to stop the messages.

**Comment by MarkuBu** [comment] 2017-10-30 17:40
It's the farlands subgame, so yes, a lot of non-vanilla mods.

But why should cause player:set_properties the load of any other active entity?

**Comment by MarkuBu** [comment] 2017-10-30 17:42
> but all object properties are together in one lump, resetting any of them resets the mesh.

Ok, got it

**Comment by paramat** [comment] 2017-10-30 18:12
Because
https://github.com/minetest/minetest/blob/610ea6f21629933be3b38c2b5fce53a35c5aac3a/src/content_cao.cpp#L1241
Setting any single property causes that conditional block of code to happen, which resets lots of things and 'expires the visuals'.

So the issue is that 'set properties' was originally meant to be used once on player join, so everything was grouped and reset together, which was no issue. But now we are using player object properties for allowing zoom etc. in-game so it all being reset together is becoming unoptimal.

Maybe i'll add a new 'command' for `GenericCAO::processMessage()` for object properties that do not affect visuals, called 'GENERIC_CMD_SET_PROPERTIES_NON_VISUAL' or something.

**Comment by SmallJoker** [comment] 2017-10-30 18:14
Well, here's an attempt to fix it using a check whether it's the same mesh - which is of course never happening, as the mesh is re-created each time:
```
 	else if(m_prop.visual == "mesh") {
 		infostream<<"GenericCAO::addToScene(): mesh"<<std::endl;
 		scene::IAnimatedMesh *mesh = m_client->getMesh(m_prop.mesh);
-		if(mesh)
-		{
-			m_animated_meshnode = RenderingEngine::get_scene_manager()->
-				addAnimatedMeshSceneNode(mesh, NULL);
-			m_animated_meshnode->grab();
-			mesh->drop(); // The scene node took hold of it
-			m_animated_meshnode->animateJoints(); // Needed for some animations
+		if (mesh) {
+			scene::IAnimatedMeshSceneNode *node =
+				RenderingEngine::get_scene_manager()->
+					addAnimatedMeshSceneNode(mesh, NULL);
+
+			if (!m_animated_meshnode ||
+					m_animated_meshnode->getMesh() != mesh) {
+
+				if (m_animated_meshnode)
+					delete m_animated_meshnode;
+				std::cout << "not same" << std::endl;
+				m_animated_meshnode = node;
+				m_animated_meshnode->grab();
+				mesh->drop(); // The scene node took hold of it
+				m_animated_meshnode->animateJoints(); // Needed for some animations
+
+				m_animated_meshnode->setMaterialFlag(video::EMF_LIGHTING, false);
+				m_animated_meshnode->setMaterialFlag(video::EMF_BILINEAR_FILTER, false);
+				m_animated_meshnode->setMaterialType(video::EMT_TRANSPARENT_ALPHA_CHANNEL_REF);
+				m_animated_meshnode->setMaterialFlag(video::EMF_FOG_ENABLE, true);
+			}
+
 			m_animated_meshnode->setScale(v3f(m_prop.visual_size.X,
 					m_prop.visual_size.Y,
 					m_prop.visual_size.X));
@@ -581,14 +596,11 @@ void GenericCAO::addToScene(ITextureSource *tsrc)
 			if (m_is_player)
 				backface_culling = false;
 
-			m_animated_meshnode->setMaterialFlag(video::EMF_LIGHTING, false);
-			m_animated_meshnode->setMaterialFlag(video::EMF_BILINEAR_FILTER, false);
-			m_animated_meshnode->setMaterialType(video::EMT_TRANSPARENT_ALPHA_CHANNEL_REF);
-			m_animated_meshnode->setMaterialFlag(video::EMF_FOG_ENABLE, true);
 			m_animated_meshnode->setMaterialFlag(video::EMF_BACK_FACE_CULLING, backface_culling);
+		} else {
+			errorstream << "GenericCAO::addToScene(): Could not load mesh "
+					<< m_prop.mesh << std::endl;
 		}
-		else
-			errorstream<<"GenericCAO::addToScene(): Could not load mesh "<<m_prop.mesh<<std::endl;
 	} else if (m_prop.visual == "wielditem") {
 		ItemStack item;
 		infostream << "GenericCAO::addToScene(): wielditem" << std::endl;
```

**Comment by paramat** [comment] 2017-10-30 20:13
MTGame PR https://github.com/minetest/minetest_game/pull/1930

**Comment by rubenwardy** [comment] 2017-10-30 20:27
I suggest deprecating set_hud_flags and adding set_flags instead. All hud flags then have `hud_` appended to them. So:

```lua
player:set_flags({
    can_zoom = true,
    hud_hotbar = true,
    hud_minimap = false
})
```

**Comment by paramat** [comment] 2017-10-30 21:09
Allowing zoom using HUD flags was my initial intention. However i am now intending to set a per-player zoom FOV value #6561  so a true/false flag won't work.

**Comment by paramat** [comment] 2017-11-03 16:31
https://github.com/minetest/minetest_game/pull/1930 merged which will help, but the issue remains why this message is only printed when formspec is open, when a mesh is loaded.

**Comment by azekillDIABLO** [comment] 2017-11-12 15:44
During mila developpment I had a lot of these alongside `Error: UV map missing` while using mod_redos model... Is it related? Because it slows the game from about 10 fps sometimes.

**Comment by paramat** [comment] 2020-06-10 00:31
Bug still seems present according to https://github.com/minetest/minetest/issues/10017#issuecomment-641650079

**Comment by sfan5** [comment] 2020-06-10 08:06
The reason #9935 is marked as fixing this is because it fixes the mesh being reloaded when it's not _necessary_, the animation is still reset when it is reloaded however.

Unnecessary reloads were the initial bug reported here(since `can_zoom` does not affect visuals).
The animation reset is better described by #9129 or #7781.

**Closed by sfan5** 2020-06-10 08:06 UTC
Labels: @ Client / Audiovisuals, @ Script API, Bug
