### ISSUE TITLE
No walking animation when autoforwards is enabled.

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8209] opened 2019-02-09 21:18 UTC
##### Issue type
 - Bug report
 
##### Minetest version
```
f5bdc04ab5b47bd094ba0ced5f086e8fe6b12298
```

##### Summary
If you enable autoforwards, the player walk animation is not used. Instead, you see a player character who moves forward but stands sill. This looks hilarious.

I have no idea if this issue belongs to Minetest or Minetest Game.

##### Steps to reproduce
1. Use any game with animated player model, like Minetest Game.
2. Enable autoforwards
3. Change camera so you can see yourselves

**Comment by DS-Minetest** [comment] 2019-02-09 22:07
Duplicate of #7805

**Closed** 2019-02-09 22:38 UTC
