### ISSUE TITLE
Vector graphics in formspecs

### ISSUE THREAD

**Issue by rdococ** [minetest/minetest#8720] opened 2019-07-28 20:32 UTC
As far as I can tell, there isn't an easy way to draw simple vector graphics in formspecs, which would be very useful for the purposes of visualization and graphics.

At the bare minimum, I'd like to see the ability to draw arbitrary, colored triangles on formspecs, and everything else could be handled by a server-side mod.

**Comment by DS-Minetest** [comment] 2019-07-28 21:03
Duplicate of #2419.

(Imo svgs in guis and hud would indeed be nice.)

**Comment by paramat** [comment] 2019-07-28 22:21
Not really a duplicate, just related.

**Comment by raymoo** [comment] 2019-08-10 11:16
This was rejected in #8087

**Comment by raymoo** [comment] 2019-08-10 11:30
Well technically that would be a subset of this issue, but if this issue is desirable then the other one shouldn't be labelled "won't add", because a feature satisfying this one would satisfy the other one.

**Comment by v-rob** [comment] 2019-08-13 04:47
Well, Irrlicht has http://irrlicht.sourceforge.net/docu/classirr_1_1video_1_1_i_video_driver.html#a34845920167c68578a78f842af54d140 which appears to be a way to draw polygons and suchlike, filled and not, and a formspec element isn't too hard to make.  I might work on it after I get some of my other formspec PRs merged.

**Comment by raymoo** [comment] 2019-08-14 04:05
The rejection in #8087 is not based on the feasibility of such a feature, but on the element coordinates of formspecs being difficult to use.

**Comment by v-rob** [comment] 2019-08-14 20:11
With the advent of `real_coordinates`, this is no longer a problem.  So either this issue should be left open, or this should be closed and the other reopened because there is no longer anything barring this from being made.

**Comment by raymoo** [comment] 2019-08-17 00:33
I brought that up in the other issue but it didn't seem to matter.

**Comment by paramat** [comment] 2019-08-18 19:01
> The rejection in #8087 is not based on the feasibility of such a feature, but on the element coordinates of formspecs being difficult to use.

2 of the disapprovals had nothing to do with coordinates so still apply.

**Closed by paramat** 2019-08-18 19:01 UTC
Labels: Feature request, Formspec, Possible close
