### ISSUE TITLE
[Android] Show up a window with error message when it causes.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#9281] opened 2020-01-03 17:20 UTC
It will just terminate the app if it occurs without the immediate showing the dark window with an error message as on the desktop version. The single way is to look through the debug.txt.

**Comment by SmallJoker** [comment] 2020-01-03 18:18
What kind of error messages? Server-sent ACCESS_DENIED messages are shown to the client.
If your issue is about the grey screen you'd get on desktop: duplicate of #4482.

**Comment by Andrey2470T** [comment] 2020-01-03 18:31
It happens with any kind of error. And is 'ACCESS_DENIED' a parameter in minetest.conf or what?

**Closed** 2020-08-06 09:45 UTC
Labels: Feature request
