### ISSUE TITLE
Gennotify Events Cannot Be Retrieved Twice

### ISSUE THREAD

**Issue by duane-r** [minetest/minetest#6590] opened 2017-11-05 15:43 UTC
If you attempt to retrieve gennotify events after another mod has retrieved any, you'll get an empty table. This is really noticeable now that the dungeon_loot mod is retrieving dungeon and temple parameters. No other mod can get any gennotify data back now, since they'll always run after the game's mods.

I tried setting peek in the getEvents call, which lets other mods get the data, but unfortunately, nothing ever clears the events from there on. They need to be cleared after a chunk is generated, but given how multiprocessing and overgeneration work, I'm not sure how that could happen.

**Comment by paramat** [comment] 2017-11-06 05:52
The gennotify entries should ideally be cleared after every 'on generated' function has been run and before the next mapchunk is generated. This is how i expected the behaviour to be.

**Comment by duane-r** [comment] 2017-11-06 08:25
The only way I can see this working is if you select one caller as special and wait until her next call to clear the events. I did basically the same thing here, not really expecting it to work. It seems that the requests are always kept in the same order, so everyone gets data back (frequently several times, but that was happening before):

https://github.com/duane-r/booty/blob/master/init.lua#L30

The booty mod calls with the self_flag parameter, which triggers a new call to the original get_mapgen_object, replacing the old data. Everyone who calls normally gets a copy of the data. That way you don't have to try to decide when the chunk is finished.

**Comment by paramat** [comment] 2018-02-25 15:36
Confirmed, you cannot do `minetest.get_mapgen_object("gennotify")` twice.

I found a workaround that is to call that once in the initial mod that runs in a subgame and make it global to be accessed by any mod that runs after. Mods can still do `minetest.set_gen_notify()` individually and in any order. Maybe something temporary for MTG?

**Comment by poikilos** [comment] 2018-02-28 15:59
I'm not sure if you have an easy way to test the issue yet, but I posted [a seed and some locations](https://forum.minetest.net/viewtopic.php?f=11&t=13857&start=25#p312645) on the forum thread for spawners for testing this issue with that mod. The locations show where you should see pyramids and/or spawners but don't, even with the mod's settings.txt set properly (SaKeL believes this issue is the cause for those things not being generated).

**Comment by paramat** [comment] 2018-03-01 03:46
Yes that forum issue is due to dungeon loot being added to MTG.

**Comment by paramat** [comment] 2018-03-02 12:14
> I tried setting peek in the getEvents call, which lets other mods get the data, but unfortunately, nothing ever clears the events from there on. They need to be cleared after a chunk is generated, but given how multiprocessing and overgeneration work, I'm not sure how that could happen.

How about we add a separate API that clears the events, then do not clear the events in `getEvents()`? The clearing can then be done manually in the first registered on_generate function (i assume in the first loaded mod).

**Comment by paramat** [comment] 2018-03-02 12:33
And of course add a 'GenerateNotifier' destructor to clear the events on shutdown.

**Comment by paramat** [comment] 2018-03-02 13:26
I propose that `m_notify_events.clear()` is removed from `GenerateNotifier::getEvents()`, made a separate function, and called after all 'on generated' functions at
https://github.com/minetest/minetest/blob/20a85d76d94c9c5c7fbe198c3d0e1fbee97a485f/src/emerge.cpp#L587
or
https://github.com/minetest/minetest/blob/20a85d76d94c9c5c7fbe198c3d0e1fbee97a485f/src/script/cpp_api/s_env.cpp#L42

**Comment by paramat** [comment] 2018-03-02 13:41
WIP branch https://github.com/paramat/minetest/tree/gennotify

**Comment by paramat** [comment] 2018-03-02 18:22
PR #7091

**Comment by paramat** [comment] 2018-03-03 23:08
#7091 merged.

**Closed by paramat** 2018-03-03 23:08 UTC
Labels: @ Mapgen, @ Script API, Bug
