### ISSUE TITLE
Add voronoi for lua

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4500] opened 2016-09-05 13:13 UTC
Minetest supports Perlin Noise for Lua, but not for Voronoi. It would be helpful if Lua can use Voronoi diagrams too

**Comment by sofar** [comment] 2016-09-07 19:01
Voronoi diagrams are nothing but a visual representation of "nearest neighbor" relations in a 2D plane (and could even be 3D or more dimensional).

I suggest closing this. This request doesn't make any sense, it seems.

**Comment by MarkuBu** [comment] 2016-09-07 19:45
Please search for informations for what voronoi can be used for. I give you one example

http://gamedevelopment.tutsplus.com/tutorials/how-to-use-voronoi-diagrams-to-control-ai--gamedev-11778

It can be also used for mapgen and other stuff. I don't ask for useless features

**Comment by sofar** [comment] 2016-09-07 20:06
But you're not asking for something concrete (e.g. a new function that does X or Y based on input Z).

Voronoi is a *graph type*.

Minetests biomes are defined as a parameter of Humidity(generated for each position by perlin noise) and Temperature(generated for each position by perlin noise) centerpoints, and the mapgen code uses a nearest neighbor algorithm to determine what biome should be applied to each position.

So if you're asking to use voronoi-type points on a map and have minetest's mapgen using it to determine biomes, then that is exactly how the current mapgen code works.

Yes, Voronoi diagrams are great. We already use them to construct and discuss new biomes, etc..

Barring any concrete feature requests, this issue still does not request any feature which is coherent, useful or actually implementable.

**Comment by MarkuBu** [comment] 2016-09-07 20:13
Then I'm sorry being inaccurate.

> So if you're asking to use voronoi-type points on a map and have minetest's mapgen using it to determine biomes, then that is exactly how the current mapgen code works.

That's what I mean.

**Comment by sofar** [comment] 2016-09-07 20:20
Start looking at this:

https://github.com/minetest/minetest_game/blob/master/mods/default/mapgen.lua#L400

Notice the `humidity` and `temperature` values. These define the centerpoints in the voronoi diagram for each biome.

This is entirely moddable. Any mod can insert new biomes. Also subgames can create entirely new biomes in this fashion.

**Comment by MarkuBu** [comment] 2016-09-07 20:49
I know that voronoi diagrams are used for biomes. But I want them to use for other things too

I want to be able to create my own map with feature points

**Comment by sofar** [comment] 2016-09-07 21:09
You can write your own mapgen code in lua already. It's been done too, just look at the `mg` mapgen for instance. (https://github.com/minetest-mods/mg)

**Comment by MarkuBu** [comment] 2016-09-07 21:35
Well, it's already there. All we need is a lua API. And it would be faster

**Closed** 2016-09-07 21:43 UTC
Labels: @ Script API, Feature request

**Comment by sofar** [comment] 2016-09-07 21:50
What exactly do you want lua to expose?

**Comment by sofar** [comment] 2016-09-08 19:39
Drilling down to the core of that particular aspect, you're describing "a nearest neighbor search algorithm". Your inputs would be (a) a set of feature points [ (x,y,z), (x,y,z), (x,y,z), .....] and (b) a single point (x,y,z) of interest. ((x,y,z) could also be (temp, humidity) of course, but any dimension would work).

Once you know the "set" and the "thing to search" you have virtually no way to optimize the search space, so the solution that mapgen uses (as far as I can see) is the simplest approach: calculate distances for each entry in the set to the target, and pick the nearest one.

You can do all of this in Lua, already. I don't see anything bad about doing the nearest neighbor search in lua either - if all your data is in lua already, you won't take much of a penalty to do the searching in lua either (mostly just vector.length() calculations I estimate).

If you want to optimize this in C, it doesn't make any sense to keep the map data in lua, and you'd get little benefit unless the data is actually in C. But the problem is that there's no way from lua to attach random bits of data to an active mapblock, so that wouldn't work unless you change the way the minetest mapblock would work, and I see no reason to allow this either.

What remains is to write it all in C, which would work if you're just doing mapgen, and nothing to the mapblocks after the mapgen is complete (and discard all data).

Looking back, I still am not convinced you understand what programmatically lies behind a voronoi diagram. All it is is:

```
-- example feature points
map = {
    { t = 30, h = 30, b = "taiga" },
    { t = 50, h = 30, b = "grassland" },
    { t = 30, h = 50, b = "boreal forest" },
}

function find_biome_for(h, t)
    local nearest
    local dist
    for _, v in pairs(map) do
        local len = ((v.t - t) * (v.t - t)) + ((v.h - h) * (v.h - h))
        if not dist or len < dist then
            dist = len
            nearest = v.b
        end
    end
    return nearest
end

-- example use
find_biome_for(41, 39)
```

Prints out "boreal forest" for me.

There really isn't anything more to Voronoi diagrams. It's not some magic code that makes this O(1) or anything, it's brutally simple and boring, even.
