### ISSUE TITLE
PostgreSQL auth case sensitive?

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10976] opened 2021-02-19 13:52 UTC
> if usernames are already case-insensitive, then my database is inconsistent after conversion.
> i converted it from auth.txt to postgresql and now i have Test and test inside as before, so i thought it is still not case insensitive.
this should be blocked by database and server.

_Originally posted by @codeandfix in https://github.com/minetest/minetest/issues/10964#issuecomment-780897882_

**Comment by codeandfix** [comment] 2021-02-20 16:47
no i deleted "test" and kept "Test" to remove the inconsistency. but for now i miss player numer 3 as it is not filled up.
maybe i better should have used the delete player command ingame instead of manipulating database.
minetest seems to not fill up the player number 3.
will this cause trouble, too? or will dublicates be removed automatically later, if this is fixed?

**Comment by rubenwardy** [comment] 2022-01-28 12:50
I see nothing in AuthDatabasePostgreSQL that makes names case insensitive.

The following constraint could be added to prevent this:

```sql
ALTER TABLE auth ADD CONSTRAINT name_unique UNIQUE (LOWER(name));
```

There's also `collation="NOCASE"`, which would treat `test` and `Test` as the same row

Either of these would ensure data correctness, but would cause crashes if the server lets invalid logins get this far. And added constraints failing on migration is a common issue

**Comment by Zughy** [comment] 2022-04-29 21:51
Closing due to no reproduction

**Closed by Zughy** 2022-04-29 21:51 UTC
Labels: Unconfirmed bug, Possible close
