### ISSUE TITLE
settings don't save on android when closing app via "Recents" screen

### ISSUE THREAD

**Issue by sotha1** [minetest/minetest#14229] opened 2024-01-08 14:09 UTC
### Minetest version

```true
Minetest 5.8.0
irrlicht device: ANDROID
openGL ES 3.2 build
```

### Active renderer

openGL ES 3.2 build

### Irrlicht device

ANDROID

### Operating system and version

android 9

### CPU model

MediaTek MT6739 1.5 GHz 2gb ram

### GPU model

integrated

### OpenGL version

3.2 build

### Summary

when i open my minetest settings and change any option and close the game, and open it again it doesn't save the changes

https://github.com/minetest/minetest/assets/149703967/1f137ce0-4ef1-48a5-a83e-c60afb065559

### Steps to reproduce

first download minetest from https://www.minetest.net/downloads/
all the three sources (f-droid, play store and the directly "download the apk" ) have the bug (i tested it in them all)
![Captura de tela de 2024-01-08 11-10-49](https://github.com/minetest/minetest/assets/149703967/a9da2b15-525f-44e3-b49b-f3a1fa5581fc)
(remembering that i downloaded the apk from my phone directly)
download it on your device
open the game and try to change any setting, after close the game and re-open it

**Comment by sotha1** [comment] 2024-01-08 14:27
edit: i tried to downloaded it from f-droid and play store and the bug still hapenning

**Comment by srifqi** [comment] 2024-01-09 10:00
What will happen if you tried to press the Back button to close Minetest instead of killing it from recent application list?

**Comment by sotha1** [comment] 2024-01-09 15:29
> What will happen if you tried to press the Back button to close Minetest instead of killing it from recent application list?

the game still working in background, so it keep saved

**Comment by tetsuo55** [comment] 2024-01-10 10:34
What it looks like to me is that minetest saves the settings to storage on exit and not when closing the settings dialogue.

When minetest crashes or is force closed the changed settings are lost, I can confirm.

The fix would be to save the settings to storage when closing the settings menu

**Comment by Unacceptium** [comment] 2024-01-16 16:30
i known this for so long. workaround: set your setting and join a singleplayer world. for some reason it forces to save. NOT working with contentDB flags.

**Comment by sotha1** [comment] 2024-01-17 02:57
I saw that clicking on "exit o.s" playing a world instead of closing directly through the recent section works, so I suggest creating a button in the main menu to be able to exit the game or automatically create a dialog when you press the "back" button asking if you really want to exit, then it automatically saves the settings ( (of course, this whole suggestion is in vain if it is possible to do something that automatically saves the game when exiting without needing a dialog box or buttons)

**Comment by Unacceptium** [comment] 2024-01-17 06:12
@sotha1 full agree!

**Comment by grorp** [comment] 2024-01-17 07:58
> creating a button in the main menu to be able to exit the game

That probably wouldn't stop people from closing Minetest via the "Recents" screen and losing their setting changes.

> automatically create a dialog when you press the "back" button asking if you really want to exit, then it automatically saves the settings

That wouldn't help, using the back button in the mainmenu already quits Minetest and saves the settings.

**Comment by Unacceptium** [comment] 2024-01-17 08:57
MT makes the bqck qnd recent buttons hide. why not do this instead?
-2 click instead of 2 swipe
-most games do like this
when in game it actually look similar so..
![Screenshot_20240117_093551](https://github.com/minetest/minetest/assets/145642963/7e708da2-3d6e-475a-ac31-f91b42b6eb5e)
![Screenshot_20240117_093551 (1)](https://github.com/minetest/minetest/assets/145642963/14f03e69-98fd-4daa-9d46-bfde3c7fded3)
idea from a lot of MT text wich likes to go out of its borders.

**Comment by sotha1** [comment] 2024-01-17 13:41
> That's possible, but it probably wouldn't stop people from closing Minetest via the "Recents" screen and losing their setting changes.

i know that, but if mt warn players that exiting without the action of pressing a button or accepting a dialog box will not save the game (or maybe people only realize this over time) They will have to get used to doing that anyway to avoid losing their game data.

**Comment by srifqi** [comment] 2024-01-19 12:00
Removing application from [the Recents screen](https://developer.android.com/guide/components/activities/recents?hl=en) is the same as terminating/ending the process. It skips saving configuration/settings which is called when exiting normally (closing the window or pressing <kbd>Esc</kbd> or Back button in the main menu).

https://github.com/minetest/minetest/blob/49ce5a2de633d751080a0c97b802ae48190bf911/src/main.cpp#L272-L274

https://github.com/minetest/minetest/blob/49ce5a2de633d751080a0c97b802ae48190bf911/src/client/clientlauncher.cpp#L249-L254

**Summary for Android version**

| Action | Configuration is saved |
|--------|:----------------------:|
| Pressing Back button in the main menu | ✅ Yes |
| Pressing Exit to OS in the (in-game) pause menu | ✅ Yes |
| Removing Minetest from the Recents screen while Minetest is still running/playing | ❌ No |

**Closed** 2024-01-23 20:33 UTC
Labels: Bug, Android, High priority, @ Mainmenu
