### ISSUE TITLE
Settings button is in a different place and no longer has a label

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#13900] opened 2023-10-20 22:08 UTC
### Summary

It took me a long time to find the settings button in the development version of Minetest.

I finally figured out that the settings tab is now hidden behind an unlabeled button that shows two gray circles. If this button is hovered with the mouse cursor, it shows a popup that says that it is for settings.

With this, Minetest takes a step back into the horrible UX of 1990s web design (or 2010s GNOME). I know that this type of information hiding – like the burger menu – is absolutely bad UX. It even has a name: Mystery meat navigation. See https://en.wikipedia.org/wiki/Mystery_meat_navigation for details.

> Mystery meat navigation (also known as MMN) is a form of web navigation user interface whereby the target of each link is not visible until the user points their cursor at it. Such interfaces lack a user-centered design, emphasizing aesthetic appearance, white space, and the concealment of information over practicality and functionality.

The Nielsen Norman Group (user interface experts) has some opinions on this: https://www.nngroup.com/articles/icon-usability/

> **Icon labels should be visible at all times**, without any interaction from the user. For navigation icons, labels are particularly critical. Don’t rely on hover to reveal text labels: not only does it increase the interaction cost, but it also fails to translate well on touch devices.

There is enough space in the interface to actually label that button, which would also make it a bigger click target (like it previously was).

### Steps to reproduce

1. Tell a user not accustomed to the new interface to start Minetest.
2. Ask them to find the Settings dialog for Minetest.
3. Curse the bad 1990s UX.

**Comment by rubenwardy** [comment] 2023-10-20 23:50
Unfortunately, buttons do not support both an icon and a label (as the label is always centered). So the options are to:

1. Go with just a text button
2. Go with a composite button (image[] + label[] + button[])
3. Leave as is

The main reason I avoided going with a text-only button is because translations can require a lot of space and, unlike the tabheader, the settings button does not scroll

**Comment by NathanSalapat** [comment] 2023-10-21 00:23
Those two 'grey circles' are gears. Pretty standard to use gears as a configuration icon. Although maybe using a higher resolution icon, so it's more obviously gears, could be helpful.

**Comment by Desour** [comment] 2023-10-26 21:54
I'm also having troubles getting used to the new settings button. It's at a different place than before, it's not spelled out anymore, it's at a different place than all the other submenus, and the icon is not flashy.
I expect these issues to be fixed in future iterations of the mainmenu, so I don't care too much. But for the current release, it might make sense to restore the ugly tab plus button thing, for a better user experience. I'm not sure though.

(Offtopic: @erlehmann The issue description is - as always - too aggressive. It sounds like you accuse others of being complete morons that want to make things worse on purpose. Even if you think that's true, assume you might be wrong. There's no reason to be so unfriendly, and it won't help you.)

**Comment by Zughy** [comment] 2023-11-22 20:13
Considering that:
1. being in a different place is not a bug
2. the main menu is so bad UX-wise and it's going under a soft-transitioned overhauling (#6733), and it won't be one (probably temporary) button to ruin the whole experience

Closing

**Closed by Zughy** 2023-11-22 20:13 UTC
Labels: Unconfirmed bug, @ Mainmenu, UI/UX

**Comment by appgurueu** [comment] 2024-03-03 17:52
While I like the settings icon on its own, I think the current interface is more confusing than the previous interface: The settings button looks unlike other buttons, is placed away from other buttons, and is unlabeled. This is suboptimal for discoverability. The "ugly" tab was better in that regard.

> But for the current release, it might make sense to restore the ugly tab plus button thing, for a better user experience. I'm not sure though.

I think we should reconsider this for 5.9, if no redesigns happen. We could bring the gears back once we have a consistent redesign for the tabs at least.

We should also genuinely consider testing on "fresh" users. I know that the gears threw me off, but I'm a long-time user who expects the settings (tab) at a certain place.

**Comment by rubenwardy** [comment] 2024-03-03 18:02
It doesn't help that the icon doesn't look like a standard settings icon either. I support replacing it with a text button

**Comment by appgurueu** [comment] 2024-03-03 20:49
> We should also genuinely consider testing on "fresh" users.

Coincidentally, someone I was talking to on Discord decided to install Minetest today. Excerpts from the conversation:

> Me: mouse sensitivity? that's in settings  
> can you try to find settings yourself? i'm interested in determining how discoverable it is

Their reaction:

![Screenshot from 2024-03-03 21-46-29](https://github.com/minetest/minetest/assets/34514239/ad595f38-3ea4-42b5-9b08-16a116a26613)

(another thing that seems to cause a bit of confusion: we should perhaps rename New -> New World)
