### ISSUE TITLE
Server shutdown is potentially confusing for players

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2833] opened 2015-06-26 00:57 UTC
Currently, the server shutdown is poorly communicated to the users.

All they see is a chat message saying “Server shutdown”. The player still stays in the world, but of course shortly after all actions to the world would be meaningless. The player is in some kind of “ghost world” where he/she can still move around but not make any changes.
IMO this is pretty confusing and also useless to let the players stay in this “ghost world”.
The player may also miss the message and even be mislead into thinking that something is wrong with the server, but actually, it was just a regular shutdown. This could happen if a player was afk for a while.

What needs to be changed IMO:
* Add an extra packet in the network protocol specifically used to communicate to the clients that the server *has (almost) just been* shutdown, so the clients could react to this. (Note: I don't know the inner workings of the network code in Minetest, so forgive me if my suggestion makes not 100% sense; but I hope you get the idea here).
* As soon the “shutdown packet” arrived, the client should throw the player out of the world back into the main menu with a message saying “The server has been shut down.”.

**Comment by asl97** [comment] 2015-06-26 01:00
minetest.register_on_shutdown(function_to_kick_all_players_with_message)

**Comment by Wuzzy2** [comment] 2015-06-26 01:05
Yes, there is already a mod which does exactly this. But, frankly, this should not be in the responsibility of mod and subgame makers to do so. This is one of the features you would always want, regardless of mod or subgame. Therefore, the engine should be changed.

Even if we put this into builtin it would be bad usability because the message would say that you have been “kicked”, which sounds bad and is misleading.

**Comment by asl97** [comment] 2015-06-26 01:10
related: https://github.com/minetest/minetest/issues/1288

**Comment by nanepiwo** [comment] 2015-06-26 17:47
Why does the client not check if the server timed out, but the server checks if clients have timed out?

**Comment by Wuzzy2** [comment] 2015-06-26 18:30
@nanepiwo: Huh? Who said that?

**Comment by est31** [comment] 2015-06-27 09:38
What @nanepiwo said is true, there is no check. Yea, general situation is that the server does far more validations and so on than the client does. This needs improvement.

To the issue of this report: I'm undecided about this.

**Comment by Wuzzy2** [comment] 2015-06-27 13:51
How can this be controversial?
All network-enabled games I know (except Minetest) throw the player out when the server shuts down or the connection has been lost for good. There is little reason to keep the player in the world, especially because everything the player does will be lost anyways. So why should we decide to keep the old confusing and inconsistent behaviour?

I thought this was pretty obvious.

**Comment by AndrejIT** [comment] 2015-06-29 17:24
“ghost world” can be considered not a bug but a feature.
But client should show something like "No connection" message.

**Comment by Wuzzy2** [comment] 2015-06-29 19:08
> “ghost world” can be considered not a bug but a feature.

By whom? And why? What would be the possible use-case?

**Comment by AndrejIT** [comment] 2015-06-29 19:54
Explore area, otherwise unavailable, for example protected by protection mod.
I just mean, that staying in disconnected world is not a big issue, as long as you are informed by bold red "No connection" message. At least for those, who understands this message...

**Comment by asl97** [comment] 2015-06-29 21:10
@AndrejIT that can be done using the `enable_local_map_saving` setting

**Comment by est31** [comment] 2015-08-01 19:46
Since recent changes, we kick players on shutdown, and server owners even can display a "reconnect" button. Closing.

**Closed by est31** 2015-08-01 19:46 UTC
