### ISSUE TITLE
Mod API: database 

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#5103] opened 2017-01-23 08:39 UTC
I require a usable database API that allows me to create a custom DB (sqlite preferred, but if it's mysql or postgresql backended that's fine).

The db should sit in the world folder when created.

- I will open the DB at init time from my mod.
- After that I'll run the usual queries on it (insert, replace, etc.)
- At close time I'll attempt to close the db.

For now, I'm using lsqlite3 (through luarocks) but this isn't portable or usable by ordinary players, and mods like `datastorage` are not reliable nor can they handle large data sets.

A mod-specific DB API would solve this problem and provide a performant solution that would allow lots of data to be properly and securely storaged.

**Comment by nerzhul** [comment] 2017-01-23 08:45
It should support postgresql as we support the two relational DB backends
We can have our own connectors using Lua API

**Comment by sorcerykid** [comment] 2017-01-26 01:56
This would be a welcome addition. A fully database-driven approach for storage could also allow phasing out of flat-text files altogether.

**Comment by Ryan-Nolan** [comment] 2017-01-26 21:22
ive been asking and promoting this idea for a long while.... I fully support this idea and Hope someone withthe right know how implements it. i currently use a central mod to store data in an organised way but it would be much more effeicent it it was implemented as a prper database
+1 from me

**Comment by rubenwardy** [comment] 2017-08-26 03:45
duplicate of #3374

**Closed by rubenwardy** 2017-08-26 03:45 UTC
Labels: @ Script API, Feature request, Non-trivial
