### ISSUE TITLE
weird touch controls

### ISSUE THREAD

**Issue by erfty125** [minetest/minetest#13054] opened 2022-12-18 10:40 UTC
## Problem

minetest has weird touch controls so i cant play.

## Solutions

fully rework touch controls , add attack(and secondary attack)button , moving joystick zone , looking zone and etc also add changing touch buttons position.

## Alternatives

you can add just touch.cfg with settings of all buttons

## Additional context
touch buttons settings in xash
https://user-images.githubusercontent.com/98973867/208293702-85e4f816-1ea3-4f36-817c-b557871297b4.mp4

**Comment by SmallJoker** [comment] 2022-12-18 19:38
Please propose a better layout that works for you so that it can be compared with the existing one. An interactive editor to customize the button placement would take longer to implement, considering that there's only a few people actually caring about the Android build.

**Comment by Zughy** [comment] 2022-12-19 18:24
Duplicate of #8541

**Closed** 2022-12-19 18:25 UTC
Labels: Duplicate, Feature request
