### ISSUE TITLE
Setting Nodes data depending on variables/parameters.

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#3320] opened 2015-10-31 15:55 UTC
Currently, to do something with many nodes, you need to define every single different type. You could have a mod like mesecons where you need a bunch of nodes for each connection, or like wool where you have several colors and you need a node for each one of them.

In minecraft, however, wool is one node. All wool is just one node, but colored by a data value. Why can't minetest do this? This would save on server load time, as well as node count. We can do this with entities right now. Inside entity code, you can set the texture and model of the mob.

Without this:
![without](https://cloud.githubusercontent.com/assets/9893266/10864499/d17361da-7fbd-11e5-9b4f-b531dc8b6990.png)
Total number of nodes : 4

With this:
![with](https://cloud.githubusercontent.com/assets/9893266/10864502/dd5d38e0-7fbd-11e5-8cb7-b145831b245b.png)
Total number of nodes : 1

**Comment by rubenwardy** [comment] 2015-10-31 17:26
Duplicate of #2887 which is solved by #1118

**Closed** 2015-10-31 17:48 UTC
Labels: duplicate, feature request

**Comment by C1ffisme** [comment] 2015-10-31 21:32
I think we need a database for common ideas and their feature request issues, so that we don't make a thousand duplicates. People can look at the database and figure out where the request issue is.

**Comment by PilzAdam** [comment] 2015-10-31 21:34
@C1ffisme what you are talking about is done in this issue tracker.

**Comment by C1ffisme** [comment] 2015-10-31 21:35
I'm talking about a page with a table with descriptions written in plain english, and then in the second collumn a link to that issue.

**Comment by rubenwardy** [comment] 2015-10-31 21:49
like https://github.com/minetest/minetest/issues

**Comment by C1ffisme** [comment] 2015-11-01 14:18
Not all of the descriptions are in plain English. A searcher should be able to search many different versions of a sentence in case the sentence in their mind isn't the same as the actual issue.

**Comment by rubenwardy** [comment] 2015-11-01 15:35
you don't search sentences, you search keywords. For example "appearance", it's the second option: https://github.com/minetest/minetest/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+appearance

**Comment by rubenwardy** [comment] 2015-11-01 15:37
you don't search sentences, you search keywords. For example "appearance", it's the second option: https://github.com/minetest/minetest/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+appearance
or even https://github.com/minetest/minetest/issues?utf8=%E2%9C%93&q=is%3Aopen+change+node+data

We accept that duplicates will be made. Don't feel embarrassed. It's why we close and label them.

**Comment by C1ffisme** [comment] 2015-11-02 19:11
I'm not embarrassed, just leaving a suggestion. :wink:
