### ISSUE TITLE
Open links from the chat.

### ISSUE THREAD

**Issue by Tomracer** [minetest/minetest#8872] opened 2019-08-29 13:25 UTC
## request

Open links from the chat or  copy them .... It can be annoying to tap this always.

That's been a long time, a crack point with me. Because I often want to share pictures of buildings with other players :

That you could copy synonymous chat cutouts or highlights special links on the left and it could just open by clicking.

I'm sorry for the bad english translation from me: /

## Alternatives

Unfortunately, I have no sample codes / mods that I could imagine ... but I would be happy if this would be implemented

**Comment by SmallJoker** [comment] 2019-08-29 16:41
Duplicate of #4752, #7830, #1312.

**Closed by SmallJoker** 2019-08-29 16:41 UTC
Labels: Feature request

**Comment by paramat** [comment] 2019-08-29 16:45
In #1312 the core devs preferred copying from chat to links in chat (i certainly do), so this issue is covered by #7830

**Comment by Tomracer** [comment] 2019-08-29 19:10
Ah,ok...sry when I didn't saw this requests.....
