### ISSUE TITLE
Enabling fullscreen setting disables second monitor on Ubuntu 20.04

### ISSUE THREAD

**Issue by brylie** [minetest/minetest#11284] opened 2021-05-22 08:10 UTC
## Minetest version

```
Minetest 5.4.1 (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="/share/minetest"
STATIC_LOCALEDIR="/share/locale"
```

## OS / Hardware

Operating system: Ubutntu 20.04
CPU: 4x i5-7400 @ 3.00GHz

GPU model: NVIDIA GeForce GTX 1060 3GB
OpenGL version: 4.6.0 NVIDIA 460.73.01

## Summary
When I enable the fullscreen setting in Minetest settings, my second monitor gets disabled. I am unable to re-enable the second monitor despite unplugging and plugging it in, rebooting, and viewing the system display properties.

The second display was working correctly before enabling the  `fullscreen` setting in Minetest.

## Steps to reproduce
1. install Minetest from Snap store on Ubuntu
2. launch the game
3. open settings
4. search for "fullscreen"
5. enable the fullscreen setting

**Comment by brylie** [comment] 2021-05-22 08:12
xrandr shows my second monitor as being connected, but it remains blank and is not visible in the system display configuration.

```
$ xrandr
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
DVI-D-0 disconnected (normal left inverted right x axis y axis)
HDMI-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 521mm x 293mm
   1920x1080     60.00*+  71.91    59.94    50.00  
   1680x1050     59.95  
   1600x900      60.00  
   1440x900      59.89  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      70.07    60.00  
   800x600       72.19    60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       72.81    59.94  
HDMI-1 connected (normal left inverted right x axis y axis)
   1920x1080     60.00 +  59.94    50.00    50.00  
   1680x1050     59.95  
   1600x900      60.00  
   1440x900      59.89  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       59.94  
```

**Comment by brylie** [comment] 2021-05-22 08:14
Despite both displays being plugged in, there is only one display listed in my hardware:

```
$ sudo lshw -C display
  *-display                 
       description: VGA compatible controller
       product: GP106 [GeForce GTX 1060 3GB]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:137 memory:de000000-deffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff ioport:e000(size=128) memory:c0000-dffff
```

**Comment by brylie** [comment] 2021-05-22 08:17
I am able to restore the second monitor by pressing `Windows` + `p`.

However, it is strange that Minetest would disable my second monitor. Perhaps I am misunderstanding, but my expectation is that Minetest would go fullscreen on only one monitor, as is possible in other games.

**Comment by sfan5** [comment] 2021-05-22 08:51
Duplicate of #4921, this is known to be broken.
If your window manager supports it you can use Alt+F11.

**Closed by sfan5** 2021-05-22 08:51 UTC
Labels: Unconfirmed bug
