### ISSUE TITLE
Strange effects with dead players (server-client position mismatch)

### ISSUE THREAD

**Issue by PilzAdam** [minetest/minetest#244] opened 2012-09-08 11:39 UTC
When a player dies he can still fall down if a node under him is removed. The position shouldnt change.
Also the lua functions can find the player and add items to his inventory. This is strange when using my item_drop mod, because the player can pick up items when hes dead. The lua function get_objects_inside_radius(pos, radius) shouldnt return dead players.
/////////////
EDIT by paramat: Primary issue is https://github.com/minetest/minetest/issues/244#issuecomment-269078730

**Comment by nerzhul** [comment] 2015-02-11 13:32
Can you confirmed it's fixed ?

**Comment by PilzAdam** [comment] 2015-02-11 15:05
@nerzhul Not at all. Why do you ask this? I don't know of any attempt to fix this.

**Comment by nerzhul** [comment] 2015-02-11 15:10
it's a 2 years old bug, it might have been fixed by many code movements :)

**Comment by lisacvuk** [comment] 2016-04-29 16:12
I think this is fixed. I have not noticed it in game.

**Comment by paramat** [comment] 2016-08-22 00:15
Can anyone confirm fixed or still present?

**Comment by Fixer-007** [comment] 2016-08-22 13:14
So I went into "JT II" server and jumped on flying block, I logined with other name and killed him (bones appeared), than removed the block, bones were still hanging properly... BUT... when I switched to killed player he fell down from his original position (below bone) with death message on screen.

So I think bug is probably not fixed.

**Comment by paramat** [comment] 2016-08-22 19:22
Thanks.

**Comment by bigfoot547** [comment] 2016-12-23 23:41
Related: #4732

**Comment by sfan5** [comment] 2016-12-24 10:28
When the player dies the client does not freeze movement and keeps sending movement packets to the server.
The server however ignores these because the player is dead.

**Comment by nerzhul** [comment] 2016-12-24 10:29
@sfan5 maybe we should also prevent sending those packets to server if not needed as client knows we are dead

**Comment by Fixer-007** [comment] 2016-12-24 13:19
related? https://github.com/minetest/minetest/issues/3565

**Comment by red-001** [comment] 2017-02-17 13:41
related: #4231

**Comment by rubenwardy** [comment] 2017-08-10 23:28
Personally, I think that mods should take this into account by checking if the player is dead.

**Comment by raymoo** [comment] 2017-08-11 05:15
I remember it used to be that dead players didn't fall, but then someone submitted a PR making them fall.

**Comment by jastevenson303** [comment] 2017-08-11 09:06
What even is this issue?

**Comment by paramat** [comment] 2017-12-31 06:30
> When a player dies he can still fall down if a node under him is removed. The position shouldn't change.
Also the lua functions can find the player and add items to his inventory.

These seem low priority issues. I would expect a dead player body to fall if removing a node beneath.
Adding items to a dead player's inventory seems reasonable in some situations too.

Close?

**Comment by raymoo** [comment] 2017-12-31 09:30
I think now players on the server (and viewed by clients) don't fall, but on the dead player's client, the player appears to fall. IIRC there is a separate issue for this mismatch.

**Comment by jastevenson303** [comment] 2018-01-01 10:48
In my experience the inventory doesn't go to the "body", it goes in the bones.

**Comment by paramat** [comment] 2018-12-30 07:36
I'm folding this into #4231 as this issue is very old, rather confusing and behaviour has likely changed.

**Closed by paramat** 2018-12-30 07:36 UTC
Labels: @ Script API, Bug, Request / Suggestion
