### ISSUE TITLE
MapGen scripting starves out other Lua scripts (entities, active blocks, etc)

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#10800] opened 2021-01-12 18:20 UTC
Latest Minetest version.

You can try this with something like MineClone2, which has very sophisticated on_generated Lua scripting.
Start with a fresh world, as the world is loading check the profiler and see how most of the time is in "after mapgen make chunk", and notice how any action on the game is sluggish (chopping some wood for example).

I'm not quite sure what the right way out of this is. on_generated is a triggered from the emerge thread(s). It starves other scripting because it is done under the "global" environment lock. Reducing that granularity to some subset of the map would certainly help - but that's tricky to add after the fact.

**Comment by sfan5** [comment] 2021-01-12 18:56
This is pretty much impossible to fix after the fact without breaking existing stuff.

A better variant of `on_generated` should be added that runs in a separate Lua environment (on the emerge thread of course). As a consequence of this it can only have access to limited APIs and will only be able to interact with the "main" Lua environment through message queues (to be added too?).

**Comment by lhofhansl** [comment] 2021-01-13 00:10
I like that and I agree.

Another path I'm pondering is a Lua functions that get to emit what should change on the map, and then the changes are queued and after the Lua script finished the change would be a applied to the map (under the lock).
Or yet another idea is that on_generate_2 get access only to a copy of the generated mapchunk, makes changes, and then the changes are merged back under lock.

It's probably hard to contain. What if the script does stuff to Entities and those entities do stuff to the map. Possible, but probably tricky.

**Comment by lhofhansl** [comment] 2021-01-13 01:22
Actually this might be a case for reducing the generate emerge queue size again.
(I doubled it with #10616)

**Comment by sfan5** [comment] 2021-01-13 13:05
> (Edit: I guess that's what you mean with "message" queues)

No, that would be generic IPC.

The new callbacks would only have access to the chunk that is currently under generation by that emerge thread. Since that does not require holding the env lock you can just let Lua do whatever it wants for however long it wants.

>  It's probably hard to contain. What if the script does stuff to Entities and [...].

Maybe my description wasn't clear enough but this is one of the important points.
`on_generated_2` callbacks would run in an isolated Lua environment, with no access to:
* global variables defined in the usual mod environment
* entities
* players
* other parts of the map

This is what makes this new callback idea safe and why it can never be backwards-compatible.

**Comment by lhofhansl** [comment] 2021-01-17 21:49
So perhaps `on_generated_2` would get a VoxelManip as parameter and that's it.
All calls are allowed except `read_from_map` and `write_to_map`.

`on_generated_2` returns a boolean, if true the calling Emerge thread would perform `write_to_map()` (under lock), if false no action is taken.

The registered function still needs to remember its closure from the environment it was created in, or it would awkward to do anything useful. So perhaps just as a `ServerMapGenScripting` object will just `environment_on_genertated_2`

**Comment by rubenwardy** [comment] 2021-02-17 12:16
duplicate of #3182

**Closed by rubenwardy** 2021-02-17 12:16 UTC
Labels: Bug
