### ISSUE TITLE
public private keypair based server authentication

### ISSUE THREAD

**Issue by JasonTable** [minetest/minetest#13456] opened 2023-04-23 15:11 UTC
## Problem

impersonation. anyone can use any name. and impersonate for example, the dev team members and make it look like they like icky gross things.

## Solutions

make some kind of public and private keypair thing to verify users are who they say they are when you start minetest, the pair is created if it doesn't exist already. the key is also verified by the server list some how and the server list can contain the keys for the devs. that way it could be made so if a dev member is actually on someones server and the key matches, a green checkmark or something is placed by the name. so if there is no checkmark you know they are fake!! maybe even a red X is placed by the name if the name matches a dev member but the key does not match the dev's real key

## Alternatives

#13455

## Additional context

nope. no additional context because i wanna keep on topic.

**Comment by sfan5** [comment] 2023-04-23 15:30
You want to introduce a hardcoded "verified user" system with the associated crypto all to prevent pranks on the dev team?

**Comment by rollerozxa** [comment] 2023-04-23 16:06
...centralised authentication? uh, bad idea. also I wasn't exactly *upset* about being impersonated (I found it humourous more than anything). but I initially falsely assumed it to be some ploy by the owner to boost server stats, rather than another disgruntled user

**Comment by rubenwardy** [comment] 2023-04-23 16:11
I've had the idea of having a centralised authentication system (alongside the current system) using certificates to reduce some of the issues with centralised authentication systems (ie: availability), but it's not a popular suggestion

**Comment by Desour** [comment] 2023-04-23 16:38
Duplicate of #13451, just with the difference that this request explicitly states that the public key / certificate auth is optional.

I wouldn't be against a semi-centralized optional system for client auth, but it's low priority for me.

One issue is that names should not be reserved by anyone but well-known community members, which is hard to define.

Something sane that we could do is make a friend-list (similar to server list) that includes public keys of players:
* On first client start, minetest generates a certificate and private key for the player.
* On connect to server, the client sends the certificate and auths the player. This is just for showing the server that the player is the owner of the certificate, not for authing on the server (otherwise names could be blocked).
* The server broadcasts (the fingerprints of) its clients' certificates to the public serverlist, and also to all connected clients.
* A player can add another player to their friend-list. This adds the name and certificate (if existent).
* This player can now see on their server list when the other player is on a server.
* The certificate fingerprints can additionally be distributed in other ways, like some field in the forums account.
* There are also more use-cases for the certificate, like tracking achievements and similar over multiple servers of the same owner.

Anyway, as said, this is low priority for me.

**Closed** 2023-04-26 19:33 UTC
Labels: Feature request, Possible close
