### ISSUE TITLE
Allow passing a scale to `set_attach`

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#13801] opened 2023-09-12 22:05 UTC
### Problem

See [this reply on the Minetest forum](https://forum.minetest.net/viewtopic.php?p=428724#p428724).

Attachment transformations (translation, rotation, scale) are all relative to the parent. Thus entities with a visual size != (1, 1, 1) will scale attached entities, which is usually undesirable. This can be addressed by scaling models, but that only works well if there is no dynamic scaling of models in the game. (It's also made more awkward by the 10x blocksize multiplier.) Thus modders have to inversely scale child objects (typically riding players) instead - an ugly hack which needs to (inefficiently) modify the `visual_size` property, which of course interferes with other mods. 

### Solutions

Attachments already allow passing a relative translation and rotation, but for some reason scaling seems to have been forgotten about. I propose allowing to pass an optional relative scale as well, which would cleanly solve this issue: Simply pass `vector.divide(vector.new(1, 1, 1), parent:get_properties().visual_size)` (using the deprecated Schur quotient - arguably undoing scaling is about the only application of it I'm aware of) as relative scale to undo the parent's scaling. If not passed, the relative scale would default to `vector.new(1, 1, 1)`. `get_attach` would also return this scale.

Now the signature of `set_attach(parent[, bone, position, rotation, forced_visible, scale])` (and `get_rotation` returning all of these) would become somewhat dirty at this point. We should consider adding a new function and deprecating the old one, or switching this function to a single table parameter format and deprecating the current format.

### Alternatives

* Scale models to need no scaling (limited to static scales)
* Set player / child properties, leave compatibility layers up to mods (doesn't seem to have worked - mods are incompatible)
* Use a proxy entity to undo the scaling (wasteful, complex, but only requires one of two conflicting mods to adapt)

The docs should probably also be updated to elaborate on this.

### Additional context

I don't like issue forms very much. They force me to write stuff like this sentence or else they will insert useless "no response" text. I could edit this out now, but I'm leaving it here for entertainment purposes.

**Comment by erlehmann** [comment] 2023-09-13 13:00
I have seen enough bugs of the type “changing gender while in a boat makes the player a giant” that I think handling this in the engine is a *very* good idea.

**Comment by rubenwardy** [comment] 2023-09-14 23:44
My suggestion to fix this issue is to split scale into two forms - a transform scale (that applies to children) and a visual scale (that applies only to the current object). You'd use the latter case to make your mesh 10x bigger without effecting children

To implement this:

- Add get/set_scale, similar to pos and rotation
- Deprecate visual_size, aliasing it to get/set_scale
- Add a new object property for just that object

**Comment by rubenwardy** [comment] 2023-09-14 23:49
Duplicate of #10986

**Closed by rubenwardy** 2023-09-14 23:49 UTC
Labels: @ Script API, Feature request
