### ISSUE TITLE
serialize.h error quite vague.

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#3295] opened 2015-10-26 09:43 UTC
On occasion people have been getting the following server error with no clue as to what was causing it:
```
minetest: /build/minetest-xOOHPg/minetest-0.4.13/src/util/serialize.h:265: void writeF1000(irr::u8*, irr::f32): Assertion `i >= ((float)(s32)((-0x7FFFFFFF - 1) / 1000.0f)) && i <= ((float)(s32)((0x7FFFFFFF) / 1000.0f))' failed.
```
...if as was stated on forums the error is caused when a LuaEntity contains a value which is either >= 2147483.648 or <= -2147483.648, would it not be clearer if the actual entity name was displayed alongside the error message giving a clue as to the cause of the crash.

**Comment by est31** [comment] 2015-10-26 16:04
Some people can see this as dupe of #3023. At least it is related.

**Comment by C1ffisme** [comment] 2015-10-26 18:14
I've had this several times myself while testing my own mobs. It happens with entities whenever a value gets above a really high number. Check if there's some loop that increases a value, but doesn't stop it.

**Comment by tenplus1** [comment] 2015-10-27 13:29
This forum page has a few backtraces using gdb:

https://forum.minetest.net/viewtopic.php?f=6&t=13194

**Comment by est31** [comment] 2015-10-27 16:38
Okay, the first error was due to a player being out of bounds, the second error was due to an entity being out of bounds. If I get time I'll try to fix the bug.

**Comment by C1ffisme** [comment] 2015-10-27 16:47
Try checking loops. For example, if a value just keeps getting added to, but not ever subtracted from. For example:
```
on_step = function(self,dtime)
    self.value  = self.value + 1
end
```
Not saying that this code is just going to appear in your face, but you get the gist.

**Comment by tenplus1** [comment] 2015-10-27 18:42
est31: I have a check for out of bounds entities that removed them to stop any trouble.
C1ffisme: self.timer is the only value that does this and has a limit before entity is removed, will triple check everything though inc. boats and cart mods.

**Comment by ShadowNinja** [comment] 2015-10-27 23:08
#3023

**Closed by ShadowNinja** 2015-10-27 23:08 UTC
Labels: duplicate, feature request
