### ISSUE TITLE
on_collide for entity

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#3918] opened 2016-03-26 14:12 UTC
##### Summary
Currently, almost node collision implementation is using `minetest.get_objects_inside_radius` in ABM or globalstep, that way has a bit of delay. The same is true of entity. And no way to define an behavior when particles collide. 
The purposes of the API are providing easy way to define collidion behavior instead of ABM and globalstep, and making particles more expressive.

The problem is these may cause performance decrement, so it can be only fire once. Among them, calling the function of particles may possibly stop the game.

##### `on_collide(pos, object, collided_face or direction)` (node definition)
when the object collides with the node..
Use-case: pressure plate, mine, teleporter

##### `on_collide_with_node(pos, collided_face or direction)`, `on_collide_with_entity(pos, object, direction)` (particle definition and particle spawner definition)
when the particle collides with the node or the entity.
Use-case: play sound of drops of water, use particle as the bullet, rebounding particles

##### `on_collide(self, object, direction)` (entity definition)
when two objects collide with each other.
Use-case: soccer ball, bullet, pushing out mobs

**Comment by C1ffisme** [comment] 2016-03-26 15:23
A bit more of a description might be nice...

**Comment by kilbith** [comment] 2016-03-26 15:47
@sofar has had this idea. Could be very useful for e.g. pressure plates.

**Comment by stujones11** [comment] 2016-03-26 17:32
+1 The idea is not new but I don't see any open issue for it. Here are a few more suggestions https://forum.minetest.net/viewtopic.php?f=5&t=11080

Also see @sapier's comments on #1182

**Comment by Ferk** [comment] 2016-03-26 19:02
+1 I've asked for this before too.
But I was told that the collisions are calculated client side, so it won't be trivial to have a server-side lua API for it.

**Comment by sofar** [comment] 2016-03-26 19:09
Particles are entirely client side, the server doesn't even know they exist.

But entities are server-side: the server does *move* the entity every step, and can calculate collisions (and does!) and adding a callback would be possible, but possibly expensive.

If implented, it would likely have to be "armed" so that it can only fire once, and not generate thousands of collisions if it gets stuck.

**Comment by stujones11** [comment] 2016-03-26 19:48
I think the problem would be not generating thousands of callbacks _until_ the entity gets stuck. The callback should simply not fire at all if the object is not moving. The 'arming' could be done automatically so that on_collide would only get called again once the collision condition has been negated.

**Comment by kilbith** [comment] 2016-03-26 20:04
> Particles are entirely client side

Particle spawners are server-side.

**Comment by sofar** [comment] 2016-03-26 20:39
> Particle spawners are server-side

Yes, but the server has no idea where the particles that are spawned by the client from a particle spawner go.

**Comment by MarkuBu** [comment] 2016-06-30 18:40
I don't think that Rui914 means particles. I think he means LuaEntitySAO like mobs. A collision callback in lua would be nice

**Comment by 0-afflatus** [comment] 2016-07-08 23:51
> A collision callback in lua would be nice

It would be very useful.

**Comment by paramat** [comment] 2018-05-04 21:32
Not enough information from author, if someone has a request for this please open a new issue with some description.

**Comment by ClobberXD** [comment] 2018-09-01 06:30
It'd be great to supplement this with callbacks that would run on particle collisions.

**Comment by ClobberXD** [comment] 2018-09-01 06:41
##### Use-cases for particle collision callbacks
- Make gun-firing more realistic by dealing damage only when the bullet (`particle`) collides with the player / entity.
- Simulating the firing mechanism of a shotgun - multiple pellets (`particle_spawner`) explode in the approximate direction of shooter; damage is dealt to only those players / entities hit by the resultant pellets (`particles`)

**Comment by paramat** [comment] 2018-09-01 08:06
Sorry i closed this, i know that the author cannot write English, and the details were added by others.

**Comment by Rui-Minetest** [comment] 2018-09-01 15:32
@paramat I am sorry to have troubled you. I wrote the details about this (in poor English), but I probably have no time to reply, so I close this issue.


##### Summary
Currently, almost node collision implementation is using `minetest.get_objects_inside_radius` in ABM or globalstep, that way has a bit of delay. The same is true of entity. And no way to define an behavior when particles collide. 
The purposes of the API are providing easy way to define collidion behavior instead of ABM and globalstep, and making particles more expressive.

The problem is these may cause performance decrement, so it can be only fire once. Among them, calling the function of particles may possibly stop the game.

#### API and use-case
##### `on_collide(pos, object, collided_face or direction)` (node definition)
when the object collides with the node..
Use-case: pressure plate, mine, teleporter

##### `on_collide_with_node(pos, collided_face or direction)`, `on_collide_with_entity(pos, object, direction)` (particle definition and particle spawner definition)
when the particle collides with the node or the entity.
Use-case: play sound of drops of water, use particle as the bullet, rebounding particles

##### `on_collide(self, object, direction)` (entity definition)
when two objects collide with each other.
Use-case: soccer ball, bullet, pushing out mobs

**Comment by HybridDog** [comment] 2018-09-02 08:15
> Among them, calling the function of particles may possibly stop the game.

Do you mean that when two particles collide with a node at the same time, the first on_collide_with_node is executed but then when the second one should be executed, the particle already flew far away?

**Comment by Rui-Minetest** [comment] 2018-09-02 12:13
My explanation was insufficient. Too many particles will call the function many times, so the game may possibly be stopped.

**Comment by hecktest** [comment] 2019-11-25 05:21
I need this too.
In addition, I would like to see the following functions:
- ObjectRef:sweep_check(delta)
Returns all colliders that this object would touch, if the object was moved by [delta], continuously.
If irrlicht doesn't have such a feature, implementing this would involve creating a convex solid that contains the box at both positions, and checking the collision against that.
- ObjectRef:get_touching()
Returns six booleans that tell us which sides of the object's AABB are touching something solid. This would make "grounding" a lot easier and more robust.
- minetest.collide_aabb( min, max )
Returns all objects clipped by the provided bounding box.
- minetest.collide_box( { min, max }, pos, rot )
Returns all objects clipped by this box. (not axis aligned)
- minetest.collide_sphere( pos, radius )
Same as above, with a sphere
- minetest.collide_convex( { planes } )
SAT collision check using an arbitrary solid. You can approximate any convex primitive (cones, cylinders, etc.) with this.

**Comment by rubenwardy** [comment] 2019-11-25 10:35
This particle collision detection request should be considered out of scope for this issue.

I support adding a callback for this

(Btw, the best way to currently detect entity collision is by detecting velocity changes)

**Comment by v-rob** [comment] 2019-11-26 03:09
It seems to me that there should also be an `on_collide_with_node` for entities.

**Comment by hecktest** [comment] 2019-11-26 10:54
A separate event for nodes is not necessary.
Ideally, the collision would be represented by a structure similar to pointed_thing:
type = "node" or "object"
ref = node or ObjectRef
point = vector, approximate contact point
normal = normal of the other surface
velocity = collider's relative velocity to us (force would be better, but MT has no concept of mass)

**Comment by rubenwardy** [comment] 2019-11-26 11:32
Pointed thing is the best structure, it already has normals and types

**Comment by hecktest** [comment] 2019-11-26 22:26
Oh, it does have normals now. That'll work.

**Comment by sfan5** [comment] 2020-04-14 15:13
#9668 provides an implementation of this for entities (no callback for nodes or particlespawners).
Instead of a callback an entity gets detected collisions in `on_step` and can decide to act on it.

**Comment by rubenwardy** [comment] 2021-01-31 18:44
Minetest has move results in on_step

**Closed** 2021-01-31 18:43 UTC
Labels: @ Script API, Feature request, Supported by core dev
