### ISSUE TITLE
Update Notifications In Menu

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#13454] opened 2023-04-23 08:08 UTC
## Problem

Currently, there is no way for people to get notified of any updates to any of the games, mods, or texture packs right from the main menu. People have to explicitly click on the "Install games from ContentDB" button in order to see if there are any updates available for any of the installed packages.

## Solutions

Add some sort of indicator which allows people to see if there are any updates available in ContentDB from the main menu, instead of having them explicitly check. For example, a number near the `+` button which brings to ContentDB, which shows you how many packages can be updated.

## Additional context

Here is a quick mockup I've made of what I mean by this. Notice the big red notification which immediately catches the eye.

![Example Notification](https://user-images.githubusercontent.com/114245896/233827813-82e98141-fa4d-42c9-803e-26ba5cb565dd.png)

**Comment by farfind-gpt** [comment] 2023-04-23 13:06
I think it would be nice to show an update icon near a mod/game that can be updated. Like this:
![mods](https://user-images.githubusercontent.com/95576096/233841380-6c69b5eb-008e-43e2-970d-f369f8cc89d6.png)
![content](https://user-images.githubusercontent.com/95576096/233841389-9fb002df-e0d2-4e3b-b7e0-961ae44444f5.png)
![mainmenu](https://user-images.githubusercontent.com/95576096/233841391-7a235a2f-22fc-4d8e-96a2-5f2523b92d7e.png)

**Comment by rubenwardy** [comment] 2023-04-23 13:16
Duplicate of #7327

**Closed by rubenwardy** 2023-04-23 13:16 UTC
Labels: Feature request

**Comment by rubenwardy** [comment] 2023-04-23 15:18
No, that PR is about settings and is unrelated
