### ISSUE TITLE
Gravity (movement_gravity) and other physics variables not documented properly

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#8536] opened 2019-05-15 11:15 UTC
##### Issue type

 - Documentation issue
 
##### Minetest version

```
Minetest 5.1.0-dev-debug-56869412 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Ubuntu Linux 18.04.2 LTS
CPU: Pentium(R) Dual-Core CPU E6300 @ 2.80GHz

##### Summary

Tinkering around some minetest settings I found that there's no documentation for gravity variable (movement_gravity) found in All Settings section. Digging deeper I found that there're more undocumented variables (belonging to Physics section, in file minetest.conf.example)
**Screenshot:**
![Minetest 5 1 0-dev-debug-56869412  Main Menu  2019-05-15 13:52:48](https://user-images.githubusercontent.com/6626242/57771085-6e9abb00-771a-11e9-8eac-fffcb9950081.png)
All below are not documented in file minetest.conf.example and I didn't test any of them (except for gravity, the last one) while ingame.
<details>
<summary><b>All undocumented Physics variables are under the hood</b></summary>

```
### Physics

#    type: float
# movement_acceleration_default = 3

#    type: float
# movement_acceleration_air = 2

#    type: float
# movement_acceleration_fast = 10

#    type: float
# movement_speed_walk = 4

#    type: float
# movement_speed_crouch = 1.35

#    type: float
# movement_speed_fast = 20

#    type: float
# movement_speed_climb = 3

#    type: float
# movement_speed_jump = 6.5

#    type: float
# movement_liquid_fluidity = 1

#    type: float
# movement_liquid_fluidity_smooth = 0.5

#    type: float
# movement_liquid_sink = 10

#    type: float
# movement_gravity = 9.81
```

</details>

##### Steps to reproduce

1. Open latest minetest dev. build (56869412)
2. Look for gravity or any other physics variables in All Settings section
3. Open editing dialog
4. Find no documention except for configuration title there (as in screenshot above)

**Comment by paramat** [comment] 2019-05-16 17:39
Being a physicist this may be a job for me =)

**Comment by paramat** [comment] 2019-08-27 03:38
Duplicate of #4903

**Closed by paramat** 2019-08-27 03:38 UTC
Labels: @ Documentation, Duplicate, Request / Suggestion
