### ISSUE TITLE
New movement code sneak related problems (table of bugs)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5535] opened 2017-04-07 15:58 UTC
List of sneak related bugs (work in progress, updated 14Sep2018)
I've tried to catch most of the issues posted, this may be useful during this epoch of fixing sneak problems.

Issues:
https://github.com/minetest/minetest/issues/5438 Sneaking on 1/16th slab bug, and other sneak issues / **mostly fixed, only minor issues remain**
https://github.com/minetest/minetest/issues/5861 Can jump over nodes with height of 1.5 by sneaking
https://github.com/minetest/minetest/issues/7725 "New" movement code bugs

**Comment by paramat** [comment] 2017-04-08 03:10
#2063 is not a bug, more a requset.

**Comment by paramat** [comment] 2017-04-10 19:45
#329 is partially fixed and the remaining damage evasion may have a solution (not yet applied).
See https://github.com/minetest/minetest/issues/329#issuecomment-292794065 and following comment.

**Comment by Fixer-007** [comment] 2017-04-11 15:56
I've retested #329 and it looks like bugs I posted were invalid since I didn't wait for 3 seconds of cooldown that disables the damage after teleportation, I've tried to evade many times, including on edges and jumping on slabs/stairs/doors without luck, so I requested to close that issue.

**Comment by paramat** [comment] 2017-04-12 05:19
@Fixer-007 this https://github.com/minetest/minetest/issues/329#issuecomment-289311843 is no longer an issue?

**Comment by paramat** [comment] 2017-04-12 05:33
#2774 is not really a sneak issue a sit happens when sneak is disabled.

> It appears that `disable_jump` does not work correctly when the player attempting to jump has no sneaking capability (`player:set_physics_override({sneak=false})`).

**Comment by paramat** [comment] 2017-04-12 05:37
Once #5449 is fixed all that remains is #5438

**Comment by Fixer-007** [comment] 2017-04-12 11:16
>this #329 (comment) is no longer an issue?

No longer an issue, I've tried to reproduce it many times and failed (the reason it worked before was 3 second cooldown), if you wait >3 seconds after teleport - it is not possible to do it anymore. I've tried it many times.

**Comment by paramat** [comment] 2017-04-24 18:28
#5464 merged.

**Comment by ClaudiusMinimus** [comment] 2017-04-24 20:37
It seems the sneak ladder feature/glitch has been disabled for the 0.4.15-dev; how do I re-enable sneak ladders?

**Comment by paramat** [comment] 2017-04-24 21:36
It has, i'll add a forum post soon.

**Comment by paramat** [comment] 2017-05-03 02:27
#5675 merged (replaces #5533)

**Comment by paramat** [comment] 2017-05-23 18:30
Current situation: Only remaining issues are detailed in #5438 ...

"Current remaining issues:

> "falling down if the node forward down is walkable but a nodebox."
"Confirmed, if on a flat surface you have a full node next to a snow slab and sneak towards the snow sneak fails."

> "You can't walk across a default:snow or a 1/16 node while holding shift. To see this: drop a single node of default:snow on a flat surface, stand on the edge, hold shift and try to walk over it. You walk into an invisible wall and can't cross with shift held."

> "Actually the biggest new problem in my opinion is that you can't jump if you are sneaking over the edge."

> Sneak distance being smaller, 0.29 instead of 0.4.

> Cannot sneak around corners of 1-node-high grooves in a wall.

1 Is a minor issue, you land on the nodebox below.
2 Was also present in old code, although the invisible barrier was smaller. A fairly minor issue anyway."

**Comment by paramat** [comment] 2017-07-22 17:10
#5533 merged so points 3 and 5 are fixed.
That also fixes taking damage when sneaking out over a void in a nodebox.

**Comment by paramat** [comment] 2017-07-22 17:12
Current remaining issues:

> "falling down if the node forward down is walkable but a nodebox."
"Confirmed, if on a flat surface you have a full node next to a snow slab and sneak towards the snow sneak fails."

> "You can't walk across a default:snow or a 1/16 node while holding shift. To see this: drop a single node of default:snow on a flat surface, stand on the edge, hold shift and try to walk over it. You walk into an invisible wall and can't cross with shift held."

> Sneak distance being smaller, 0.29 instead of 0.4.

1 Is a minor issue, you land on the nodebox below.
2 Was also present in old code, although the invisible barrier was smaller. A fairly minor issue anyway.
3 Seems an issue of getting used to the slightly smaller sneak distance, not a bifg issue.

**Comment by Megaf** [comment] 2017-12-09 00:13
Add https://github.com/minetest/minetest/issues/6727

**Comment by paramat** [comment] 2017-12-09 00:27
I think we can close this now, as there are very few issues and PRs left.

**Comment by Megaf** [comment] 2017-12-09 00:30
I like this list, maybe it could have only the unsolved stuff there though, and remove the strikethrough ones.

**Comment by paramat** [comment] 2017-12-09 00:32
Will do.

**Comment by Megaf** [comment] 2017-12-09 00:37
@paramat Thank you. It looks better now in my opinion. And more clear what still has to be fixed.

**Comment by paramat** [comment] 2019-02-08 01:31
Closed as duplicating issues like this is a pain for issue management. The 3 linked issues are open.

**Closed by paramat** 2019-02-08 01:31 UTC
Labels: @ Client / Audiovisuals, @ Server / Client / Env., Bug
