### ISSUE TITLE
--gameid CLI parameter does not work on Windows

### ISSUE THREAD

**Issue by recluse4615** [minetest/minetest#12743] opened 2022-09-05 03:49 UTC
##### Minetest version

```
Minetest 5.6.0 (Windows)
Using Irrlicht 1.9.0mt7
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Windows 10

##### Summary

In brief, `--gameid list` does not return anything on Windows when using the provided folder structure.

```
PS C:\dir\versions\5.6.0\bin> ls ../games


    Directory: C:\dir\versions\5.6.0\games


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         04-Sep-22  10:52 PM                devtest
d-----         05-Sep-22   2:04 AM                mineclone2
d-----         04-Sep-22  10:52 PM                minetest_game


PS C:\dir\versions\5.6.0\bin> ./minetest.exe --gameid list
(empty)
```

As a side-effect, trying to load minetest with `--gameid (id)` it doesn't launch with the correct game. Running with `--worldname {name}` loads the correct game as expected.

I believe this is because of this line:
https://github.com/minetest/minetest/blob/4e9e230e34912d08ec0f0fc01d14ef80654c7cac/src/content/subgames.cpp#L206

Although the engine recognises games installed in `{MINETEST_DIR}/games/`, it doesn't seem to when running via the CLI. I suggest that it should search in `{MINETEST_DIR}/games/`, too.

##### Steps to reproduce
- Download Minetest 5.6.0 (possibly happens in older versions, too)
- Unzip
- Launch `bin/minetest.exe`
- Manually download a game (eg: `mineclone2`) via ContentDB and move in to the `games/` directory (you can do this via the ContentDB tab in-game, too)
- Confirm that the game is visible in the bottom of the UI under "Start Game"
- Exit minetest
- Then, run in PowerShell/cmd: `./bin/minetest.exe --gameid {game you just installed}`
- Observe that the Minetest Game menu, worlds, etc show up

**Comment by rubenwardy** [comment] 2022-09-05 08:47
> Observe that the Minetest Game menu, worlds, etc show up

This is currently the expected behaviour. The mainmenu doesn't read gameid, it's only used by the server or singleplayer.

Just testing this now, and it doesn't seem to work in singleplayer for me:

```
$ ./bin/minetest --gameid nodecore --name "singleplayer" --password "" --worldname world --go

2022-09-05 09:45:31: [Main]: Using game specified by --gameid on the command line
2022-09-05 09:45:32: ERROR[Main]: Could not find or load game: minetest
```

**Comment by Zughy** [comment] 2023-10-18 23:22
Can't reproduce the empty list, it works as intended on Windows 10, MT 5.7. Closing.

Consider opening a feature request for the last paragraph in the comment above mine

**Closed by Zughy** 2023-10-18 23:22 UTC
Labels: Unconfirmed bug, @ Startup / Config / Util
