### ISSUE TITLE
Attached particlespawners aren't attached in 1st person mode

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#9152] opened 2019-11-28 19:37 UTC
##### Minetest version
```
5.1
```

GPU model: Radeon RX 570
OpenGL version: 4.5

##### Summary
The attached particles don't follow me when I'm in first person mode. They will in the other mods though
https://vimeo.com/376236130

##### Steps to reproduce
Here's the code I used
```lua
local function attach_snow_spawner(player)
	minetest.add_particlespawner{
		amount = math.random(50, 100),
		time = 0,
		minpos = vector.new(-17, 20, -17),
		maxpos = vector.new(17, 25, 17),
		minvel = {x = 0, y = -10, z = 0},
		maxvel = {x = 0, y = -15, z = 0},
		minacc = vector.new(),
		maxacc = vector.new(),
		minexptime = 9,
		maxexptime = 10,
		minsize = 1,
		maxsize = 4,
		collisiondetection = true,
		collision_removal = true,
		object_collision = true,
		vertical = false,
		texture = "default_snow.png",
		glow = 0,
		attached = player,
	}
end

minetest.register_on_joinplayer(function(player)
	attach_snow_spawner(player)
end)
```

**Comment by SmallJoker** [comment] 2019-11-28 19:59
Duplicate of #8038

**Comment by LoneWolfHT** [comment] 2019-11-28 22:07
@SmallJoker This is for particles, not entities. And I can still see the particles. They just don't follow me

**Comment by paramat** [comment] 2019-11-30 17:45
This is an infinite life spawner, does the bug occur for a finite life spawner?

**Comment by LoneWolfHT** [comment] 2019-11-30 18:37
Same for a 60-second one too

**Comment by paramat** [comment] 2019-12-01 00:59
Ok thanks.

**Comment by appgurueu** [comment] 2021-01-11 13:39
Possible workaround: Attach the particlespawner to an invisible entity which is attached to the player.

**Comment by appgurueu** [comment] 2021-01-11 14:00
Cannot reproduce in 5.4-dev.

**Closed** 2021-05-25 19:21 UTC
Labels: @ Client / Audiovisuals, Unconfirmed bug
