### ISSUE TITLE
"Climbing" out of water seems randomly broken

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#5718] opened 2017-05-07 15:17 UTC
This seems related to recent change to player's collision box.

See last comment on #5713 .

Indeed when I change
`m_prop.collisionbox = aabb3f(-0.3f, -1.0f, -0.3f, 0.3f, 0.75f, 0.3f);`
to
`m_prop.collisionbox = aabb3f(-0.3f, -0.9f, -0.3f, 0.3f, 0.75f, 0.3f);`
in  src/content_sao.cpp fixes the problem, but I am sure that causes some other issues.

**Comment by BluebirdGreycoat** [comment] 2017-05-07 15:19
A number of things related to player moment is currently broken.

**Comment by lhofhansl** [comment] 2017-05-07 17:54
Nope. I tried with an upgraded server - my own :)

**Comment by UgnilJoZ** [comment] 2017-05-07 19:10
@lhofhansl Can you walk through doors?
I had two hitbox issues today: This and https://github.com/Wuzzy2/MineClone2-Bugs/issues/185 (I cannot move through doors or under low-hanging roofs.)

**Comment by TeTpaAka** [comment] 2017-05-07 19:28
Are you sure it is caused by the collision box changed and not the recent addition of custom step heights? 45ab62d6a3d90ab3b97aec88251a766cb5dd1899

**Comment by paramat** [comment] 2017-05-07 20:33
TeTpaAka i think you are correct, will fix.

**Comment by lhofhansl** [comment] 2017-05-07 22:10
I can confirm that @TeTpaAka 's suggestion fixes the problem.

**Comment by TeTpaAka** [comment] 2017-05-07 23:39
I'm not sure if the approach is correct: Is it really 0.4 Blocks lower than the normal stepheight and not maybe one third of the stepheight?

0.6 - 0.4 = 0.2
0.6 / 3    = 0.2

The results are the same with the default stepheight, but they vary when the stepheight is changed. I don't know the exact reasons for the difference, so either can be right.

**Comment by paramat** [comment] 2017-05-07 23:59
```
-	float player_stepheight = touching_ground ? (BS*0.6) : (BS*0.2);
+	float player_stepheight = (m_cao == 0) ? 0.0 :
+				(touching_ground ?
+				(m_cao->getStepheight() * BS) :
+				(m_cao->getStepheight() -0.4 * BS));
```
Just realised this has another bug.
Previously step height was 0.6 when walking on ground, to climb half-slabs. But when jumping it is 0.2 to enable a slight rise when catching the edge of a ledge.
The custom step height should only apply when the player is walking, 0.2 should remain unchanged by custom step height.

Will fix.

**Comment by paramat** [comment] 2017-05-08 00:36
Fix #5724

**Comment by paramat** [comment] 2017-05-08 00:44
I guess also a player could not jump up onto a node with a snow quarter-slab on it?

**Comment by paramat** [comment] 2017-05-08 05:09
#5724 merged but please test, and try custom stepheights with a mod that depends on default and has this code:
```
minetest.register_on_joinplayer(function(player)
	player:set_properties({stepheight = 0.6})
end)
```

**Closed** 2017-05-08 05:12 UTC
Labels: Bug, High priority

**Comment by lhofhansl** [comment] 2017-05-08 05:18
Seems to work. Thanks for looking!
