### ISSUE TITLE
Greyscreen when Minetest crashes with chat open

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#8469] opened 2019-04-13 03:22 UTC
##### Issue type
 - Bug report
 
##### Minetest version
```
Minetest 5.1.0-dev-1e5f2e0f (Linux)
Using Irrlicht 1.8.4
```

##### OS / Hardware

Operating system: Ubuntu 18.10 cosmic
CPU: AMD Ryzen 7 2700

GPU model: Radeon RX 570
OpenGL version: 4.4

##### Summary
When Minetest crashes while chat is open (T) the game will crash with a grey screen. If chat isn't open during the same crash it exits to menu *without* a grey screen

##### Steps to reproduce
Create a mod with the code `minetest.after(3, function() meintest.log("This shouldn't work") end)`
Join a world with the mod enabled
Press `T` and wait for game to crash

**Comment by ClobberXD** [comment] 2019-04-13 04:12
Are there any errors in the logs?

**Comment by SmallJoker** [comment] 2019-04-13 08:18
```Lua
2019-04-13 10:14:40: WARNING[Server]: Undeclared global variable "meintest" accessed at MT_PATH/bin/../mods/lab/init.lua:3
2019-04-13 10:14:40: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'lab' in callback environment_Step(): MT_PATH/bin/../mods/lab/init.lua:3: attempt to index global 'meintest' (a nil value)
2019-04-13 10:14:40: ERROR[Main]: stack traceback:
2019-04-13 10:14:40: ERROR[Main]: 	MT_PATH/bin/../mods/lab/init.lua:3: in function 'func'
2019-04-13 10:14:40: ERROR[Main]: 	MT_PATH/bin/../builtin/common/after.lua:20: in function <MT_PATH/bin/../builtin/common/after.lua:5>
2019-04-13 10:14:40: ERROR[Main]: 	MT_PATH/bin/../builtin/game/register.lua:419: in function <MT_PATH/bin/../builtin/game/register.lua:399>
2019-04-13 10:14:40: ERROR[Main]: stack traceback:
[Thread 0x7fffafbff700 (LWP 2602) exited]
```

This is especially interesting because it only happens with the chat or any formspec opened. Apparently they're not destructed well as soon a Lua crash occurs.

**Comment by SmallJoker** [comment] 2019-04-13 08:19
Duplicate of #4482

**Closed by SmallJoker** 2019-04-13 08:19 UTC
