### ISSUE TITLE
Sound: Device Open crash in Snap version

### ISSUE THREAD

**Issue by StorinOfKel** [minetest/minetest#8947] opened 2019-09-18 12:32 UTC
##### Minetest version

Minetest 5.0.1 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/share/minetest"

```
![1568744611_2023_17 09 2019_1920x1200](https://user-images.githubusercontent.com/48694883/65148534-af844280-da20-11e9-9894-1913f47dcb39.png)
```
##### OS / Hardware

Operating system: Lubuntu 18.04 (Not sure if important: i3-Gaps as WM)
CPU: See below
lscpu

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              6
On-line CPU(s) list: 0-5
Thread(s) per core:  1
Core(s) per socket:  6
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               158
Model name:          Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
Stepping:            10
CPU MHz:             800.056
CPU max MHz:         4000.0000
CPU min MHz:         800.0000
BogoMIPS:            5616.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            9216K
NUMA node0 CPU(s):   0-5
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d

##### Audio devices

charlie@storin:~$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC887-VD Analog [ALC887-VD Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 2: ALC887-VD Alt Analog [ALC887-VD Alt Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

##### Summary

charlie@storin:~$ minetest 
2019-09-18 14:21:39: WARNING[Main]: system-wide share not found at "/share/minetest"
2019-09-18 14:21:39: WARNING[Main]: system-wide share found at "/snap/minetest/1094/bin/../share/minetest"
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
2019-09-18 14:21:39: ERROR[Main]: An unhandled exception occurred: Audio: Global Initialization: Device Open
2019-09-18 14:21:39: ERROR[Main]: In thread 7f39b2541900:
2019-09-18 14:21:39: ERROR[Main]: /build/minetest/parts/minetest/src/src/main.cpp:e2: int main(int, char**): A fatal error occurred: Audio: Global Initialization: Device Open
Aborted (core dumped)

##### Steps to reproduce

1) I installed Minetest 5.0.1 from snap in Lubuntu 18.04
2) I just run minetest from the terminal and I get the above mentioned error.
3) HDA Intel PCH/Realtek ALC887-VD is working like a charm on anything else (browser, 0ad, mplayer, etc)

I am unsure how to continue.

**Comment by SmallJoker** [comment] 2019-09-18 16:26
Is `alsa-base` and `alsa-utils` installed?
Does it also happen with `apt`-installed Minetest? I've seen several snap-related issues.

**Comment by charliek0031** [comment] 2019-09-18 16:40
> Is `alsa-base` and `alsa-utils` installed?
> Does it also happen with `apt`-installed Minetest? I've seen several snap-related issues.

Yes, both alsa-base and alsa-utils are installed.

Also from apt I get this version:

$ minetest --version
Minetest 0.4.16 (Linux)
Using Irrlicht 1.8.4
Build info: VER=0.4.16 BUILD_TYPE=None RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/share/games/minetest"

Kind of very out of date. :)

**Comment by rubenwardy** [comment] 2019-09-18 16:47
Duplicate of #7250

**Comment by rubenwardy** [comment] 2019-09-18 16:47
I suppose maybe this issue is more useful for debugging this specific situation

**Comment by charliek0031** [comment] 2019-09-18 17:49
> I suppose maybe this issue is more useful for debugging this specific situation

I understand. Didn't even see the other post. I see still no solution. :/

**Comment by charliek0031** [comment] 2019-09-23 14:05
One solution that now works, one I only found in the description of a youtube video is adding the following repository.

```
sudo add-apt-repository ppa:minetestdevs/stable
sudo apt update
sudo apt install minetest
```

Don't use the snap version.

**Closed** 2021-01-28 18:06 UTC
Labels: Duplicate, Unconfirmed bug
