### ISSUE TITLE
Airlike nodes with a valid mesh defined draw the mesh anyways

### ISSUE THREAD

**Issue by ExeVirus** [minetest/minetest#10631] opened 2020-11-14 00:48 UTC
I have a mod where I am making dummy nodes to represent collision boxes for a parent node. I.e getting around the collision box limit of 3x3x3 volume. 

These dummy nodes I am simply setting the node definition identical to the parent node and then overwriting the drawtype, selection, and collision boxes (and taking it out of creative inventory). 

When I change the drawtype to "airlike", but still have the mesh set:
mesh = "example.obj"

Then the object mesh is still being drawn. Airlike drawtype nodes should never have anything drawn. This also means the texture is getting loaded properly and is taking up memory space as well.

**Comment by Zughy** [comment] 2022-06-06 14:34
Tested with 5.5.0, both with `.b3d` and `.obj` extension. Can't reproduce, closing

**Closed by Zughy** 2022-06-06 14:34 UTC
Labels: Unconfirmed bug, @ Client / Audiovisuals
