### ISSUE TITLE
Velocity ignored in function minetest.add_particle

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#1789] opened 2014-10-31 20:37 UTC
This some code spawns smoke - it does not have any velocity.

```Lua
minetest.add_particle({
	pos = pos,
	velocity = {x=0, y=2, z=0},
	size = 2,
	texture = "smoke_puff.png",
})
```

The velocity works fine with minetest.add_particlespawner()

![Example of a not moving smike particle]
(http://i.imgur.com/E517b5z.png)

**Comment by VanessaE** [comment] 2015-03-29 14:22
It's an API "misprint" of a sort (see #1280), use vel={foo}.

**Comment by est31** [comment] 2015-06-23 06:13
dupe of #1280

**Closed by est31** 2015-06-23 06:13 UTC
Labels: @ Script API, bug
