### ISSUE TITLE
Send particlespawners on load mapblock

### ISSUE THREAD

**Issue by octacian** [minetest/minetest#6121] opened 2017-07-11 00:24 UTC
When a particlespawner is added to the world, it only affects clients that have the mapblock loaded at the time when the particlespawner was added. If a particular client does not have the mapblock in which the particlespawner was added loaded, then that client will not see *any* particles as a result of that spawner. However, if the client had the mapblock loaded at the time at which the particlespawner was added, particles are shown.

I am not suggesting that particlespawners be sent to all players, but rather that particlespawners be somehow attached to each mapblock and sent to each individual player as they load the particular block.

**Comment by paramat** [comment] 2017-07-11 00:32
Seems expected behaviour. Did this not happen before that commit?

**Comment by octacian** [comment] 2017-07-11 00:35
I'm not sure, will have to test. Why would that behavior be expected? In the case of a particlespawner I'd personally expect it to be applied to all clients in the area, considering that it is just a continuous spawning of particles (i.e. if I were to simply use an ABM or nodetimer to spawn the particles individually, they are shown to all players in the area, so I'd expect that particles added with a particlespawner would also be shown to all players in the area whether they were there when the particlespawner was added or not).

**Comment by paramat** [comment] 2017-07-11 00:39
Updated my comment to explain.

**Comment by octacian** [comment] 2017-07-11 00:43
hmmm, I understand the current setup now. However, would it not make more sense for particlespawners to be sent to the client when they enter the mapblock? My understanding is that a particlespawner would be more efficient than using an ABM to spawn individual particles, so I'd expect that this would be the better solution.

Maybe I should edit my initial post and change this to a feature request?

**Comment by raymoo** [comment] 2017-07-11 05:08
@paramat Individual particles are too inefficient to be a general solution for particle spawners. I thought that particle spawners used to be sent to all players, but if not then I'm assuming it wouldn't be a big change to do so. Particle spawners spawned before a player joins could also be sent to the player if the particle spawner definition is kept around.

@octacian Was the client that didn't see the particles connected to the server when the particle spawner was added?

**Comment by paramat** [comment] 2017-07-12 01:52
My commit linked here did origianlly not send particlespawners to distant clients, but was changed on request, so particlespawners are still sent to all clients at whatever distance and the distance checks are done per-particle.

I'm not sure if a mapblock needs to be loaded in a client for a particlespawner to be sent to that client.

>  Individual particles are too inefficient to be a general solution for particle spawners.

Yes.

Generally though, particlespawners are not meant to be used for long periods due to the issues this causes.

**Comment by ExeterDad** [comment] 2017-07-12 22:21
This makes sense now. We had fireworks displays for 4th of July that many people complained they couldn't see. They must of been teleporting into the area "during" the already started show.

**Comment by paramat** [comment] 2017-07-13 10:57
It's possible that particle spawners have never been sent to clients that do not have that mapblock loaded, i'm not sure, could you test? if so there may be a good reason.

For example if every particle spawner created on a server is sent to every connected player whether they have the mapblock loaded or not, those particle spawners are then running on those clients unnecessarily.
I feel it's good to avoid every particle spawner on a server running invisibly on a client, but this issue is the downside to that.

**Comment by raymoo** [comment] 2017-07-13 17:26
It's not that complex to send a particle with less time / particles left. The server keeps track of the lifetime of particle spawners already (for id allocation purposes) and you could obtain the time and particles easily from that and the particle spawner definition (which is not saved in the current code as far as I know). The particle spawner definition also includes the extent of particle spawning area, so you could determine how close a player is using it.

It doesn't really matter for this issue whether implementing sending old particle spawners is tricky or hard, it's still a desirable feature and if it gets in people will be able to use it over and over. And it doesn't seem that tricky or hard.

**Comment by paramat** [comment] 2017-07-13 19:03
octacian if you intend this issue to be a request for the feature described in the previous post i'll add the label.

**Comment by octacian** [comment] 2017-07-13 20:35
@paramat That'd be good, I will try to edit the initial post.

**Comment by paramat** [comment] 2018-01-04 06:06
Related #4624

**Comment by SmallJoker** [comment] 2018-01-04 08:29
This is a duplicate of #4624

**Closed by SmallJoker** 2018-01-04 08:29 UTC
Labels: Feature request
