### ISSUE TITLE
Drop texture-modifier-generated textures from memory after a timeout

### ISSUE THREAD

**Issue by MisterE123** [minetest/minetest#14884] opened 2024-07-26 18:18 UTC
### Problem

Related: https://github.com/minetest/minetest/issues/3528#issuecomment-2252796632

I need a way to continuously update a complex HUD that is based on texture modifiers without creating a memory leak.

The problem is that all texture modifiers are saved as a new media file in client memory.
When I build an image using texture modifiers from parts that the client already has, and then set the HUD to that image every globalstep, the client's ram fills up.

### Solutions

Suggested by @celeron55: 
Let clients drop texture-modifier-generated textures from memory after they have not been used for a while, since the client can always re-generate them from the texture-modifier-name string if needed.

### Alternatives

An alternative would be to have a way to drop any media as suggested in #3528, but celeron55 thinks his suggestion is simpler and more achieveable

### Additional context

IRC discussion: https://irc.minetest.net/minetest-dev/2024-07-26#i_6187630

My minimap, the texture modifier string of which is sent every global step or, at this point, every second:
![image](https://github.com/user-attachments/assets/2bdfb7c1-e7da-4785-aabc-b89e41b173e1)

**Comment by appgurueu** [comment] 2024-07-26 18:31
Effectively a duplicate of #11531, with the specific suggestion of a timeout (which is probably necessary to avoid unnecessarily regenerating textures excessively often in some case)?

**Comment by MisterE123** [comment] 2024-07-26 18:38
I mean, it seems you are not wrong that it is a duplicate, but I think the name of my issue is clearer from a modder's gripe perspective

**Comment by MisterE123** [comment] 2024-07-26 18:48
@appgurueu Warr suggested we ask you: could you fix this issue?

Here is a cat:
🐱

**Closed** 2024-08-11 18:13 UTC
Labels: Feature request, Possible close
