### ISSUE TITLE
Client and server position not matching up after player movement

### ISSUE THREAD

**Issue by FatalError42O** [minetest/minetest#12503] opened 2022-07-03 02:22 UTC
##### Minetest version

```
5.5.1
```

##### OS / Hardware
Operating system: Windows 10
CPU: AMD Ryzen 5 5600H
##### Summary

After movement using WASD the client's location will not match up with the server's location.

##### Steps to reproduce

IMPORTANT: TURN VIEW BOBBING OFF!

This code will basically allow you to see the problem for yourself, simply move around sporadically and the crosshair will become randomly misaligned from whatever image you use (with some luck)

*Note: it's not look_dir, I both manually recreated look_dir using vector.rotate(), and tried it without the dir, without the dir it simply disappears when this bug occurs (for obvious reasons), the look_dir is simply for demonstrational purposes.*
```
minetest.register_globalstep(function(dtime)
    for i, player in pairs(minetest.get_connected_players()) do
        local player_properties = player:get_properties()
        player:set_fov(90/8)
        local hud = player:hud_add({
            hud_elem_type = "image_waypoint",
            text = "crosshair.png",
            world_pos =  player:get_pos()+vector.new(0, player_properties.eye_height, 0)+player:get_look_dir()/10,
            scale = {x=1, y=1},
            alignment = {x=0,y=0},
            offset = {x=0,y=0},
        })
        player:set_eye_offset(vector.new())
        minetest.after(0, function(hud)
            player:hud_remove(hud) 
        end, hud)
    end
end)
```
This demonstrates that the player's position is wrong, as eye_height is observably correct, and the problem can be seen without look_dir present. This bug will happen at random, and will return to normal position after additional movement (but only occasionally).

This bug will affect virtually everything, especially raycasting that requires precision and lineup with the player camera....

**Comment by sfan5** [comment] 2022-07-03 13:05
Using the following testing code I can't find any desync issues:
(use in third-person mode)
```lua
local hi = {}

minetest.register_globalstep(function(dtime)
    for _, player in pairs(minetest.get_connected_players()) do
        local prop = player:get_properties()
		if not hi[player] then
			hi[player] = player:hud_add({
	            hud_elem_type = "image_waypoint",
	            text = "object_marker_red.png",
	            scale = {x=1, y=1},
	            alignment = {x=0, y=0},
	            offset = {x=0, y=0},
	        })
		end
		player:hud_change(hi[player], "world_pos",
			vector.offset(player:get_pos(), 0, prop.eye_height, 0)
		)
    end
end)
```

Since you said this is not about look_dir I specifically avoided including it in the test code.

**Comment by SmallJoker** [comment] 2022-07-03 13:19
Duplicate of #12317?

**Comment by FatalError42O** [comment] 2022-07-03 17:49
> Using the following testing code I can't find any desync issues: (use in third-person mode)
> 
> ```lua
> local hi = {}
> 
> minetest.register_globalstep(function(dtime)
> 	for _, player in pairs(minetest.get_connected_players()) do
> 		local prop = player:get_properties()
> 		if not hi[player] then
> 			hi[player] = player:hud_add({
> 				hud_elem_type = "image_waypoint",
> 				text = "object_marker_red.png",
> 				scale = {x=1, y=1},
> 				alignment = {x=0, y=0},
> 				offset = {x=0, y=0},
> 			})
> 		end
> 		player:hud_change(hi[player], "world_pos",
> 			vector.offset(player:get_pos(), 0, prop.eye_height, 0)
> 		)
> 	end
> end)
> ```
> 
> Since you said this is not about look_dir I specifically avoided including it in the test code. You also didn't mention whether this is supposed to happen in singleplayer or multiplayer.

The amount of offset is so small that the FOV change is needed to see it, this however does not mean it's negligible.
This happened in singleplayer but I imagine it'd happen in both

If there's a way to find the clientside's exact position (with floats) then you could probably see it as well, but I don't know how or if that's possible.

**Comment by FatalError42O** [comment] 2022-07-03 17:51
> Duplicate of #12317?

no.

**Comment by FatalError42O** [comment] 2022-07-03 17:52
> > Using the following testing code I can't find any desync issues: (use in third-person mode)
> > ```lua
> > local hi = {}
> > 
> > minetest.register_globalstep(function(dtime)
> > 	for _, player in pairs(minetest.get_connected_players()) do
> > 		local prop = player:get_properties()
> > 		if not hi[player] then
> > 			hi[player] = player:hud_add({
> > 				hud_elem_type = "image_waypoint",
> > 				text = "object_marker_red.png",
> > 				scale = {x=1, y=1},
> > 				alignment = {x=0, y=0},
> > 				offset = {x=0, y=0},
> > 			})
> > 		end
> > 		player:hud_change(hi[player], "world_pos",
> > 			vector.offset(player:get_pos(), 0, prop.eye_height, 0)
> > 		)
> > 	end
> > end)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Since you said this is not about look_dir I specifically avoided including it in the test code. You also didn't mention whether this is supposed to happen in singleplayer or multiplayer.
> 
> The amount of offset is so small that the FOV change is needed to see it, this however does not mean it's negligible. This happened in singleplayer but I imagine it'd happen in both
> 
> If there's a way to find the clientside's exact position (with floats) then you could probably see it as well, but I don't know how or if that's possible.

Upon using you're methods as shown, I still see the issue when the player moves sporadically (i.e. tapping randomly?)
code:
```
minetest.register_globalstep(function(dtime)
    for i, player in pairs(minetest.get_connected_players()) do
        local player_properties = player:get_properties()
        player:set_fov(90/8)
        local hud = player:hud_add({
            hud_elem_type = "image_waypoint",
            text = "scope.png",
            world_pos =  player:get_pos()+vector.new(0, player_properties.eye_height, 0),
            scale = {x=1, y=1},
            alignment = {x=0,y=0},
            offset = {x=0,y=0},
        })
        minetest.after(0, function(hud)
            player:hud_remove(hud) 
        end, hud)
    end
end)
```

**Comment by sfan5** [comment] 2022-07-03 18:34
Not calling `hud_set` every server step in my test code was on purpose, to remove the unlikely possibility that HUD-related issues impact this.
I also have neither `crosshair.png` nor `scope.png`, please choose a different texture or provide them with your bug report.

**Comment by FatalError42O** [comment] 2022-07-03 18:37
> Not calling `hud_set` every server step in my test code was on purpose, to remove the unlikely possibility that HUD-related issues impact this. I also have neither `crosshair.png` nor `scope.png`, please choose a different texture or provide them with your bug report.

oh I didn't see that... also "scope.png" is just the crosshair but red

**Comment by FatalError42O** [comment] 2022-07-03 18:37
I'll try what you did momentarily

**Comment by FatalError42O** [comment] 2022-07-03 18:44
With your code and the FOV change, I still see this issue. Unless you want to entertain the possibility that it's a issue with set_fov, which... to be honest wouldn't make much sense, it does appear to exist.

code:
```
local hi = {}

minetest.register_globalstep(function(dtime)
	for _, player in pairs(minetest.get_connected_players()) do
		local prop = player:get_properties()
		if not hi[player] then
			hi[player] = player:hud_add({
				hud_elem_type = "image_waypoint",
				text = "scope.png",
				scale = {x=1, y=1},
				alignment = {x=0, y=0},
				offset = {x=0, y=0},
			})
		end
        player:set_fov(90/8)
		player:hud_change(hi[player], "world_pos",
			vector.offset(player:get_pos(), 0, prop.eye_height, 0)
		)
	end
end)
```

screenshots:
![image](https://user-images.githubusercontent.com/58855799/177053045-53753737-4388-4dde-aadf-4330262885bc.png)
![image](https://user-images.githubusercontent.com/58855799/177053085-7406eaff-1cc2-45f8-8d19-f605d18ab76a.png)

Once again, I feel it's worth reiterating how randomly this will occur, I'm not even sure what exactly causes it anymore, I just know it's when you move in various ways.

"scope.png":
![scope](https://user-images.githubusercontent.com/58855799/177053031-7b844653-c0bd-4d7f-8d08-4f0a92ce033b.png)

**Comment by FatalError42O** [comment] 2022-07-03 18:47
notably, if the waypoint was in the right place, I should be able to see it in first person as well, which I cannot in any state.

**Comment by sfan5** [comment] 2022-07-03 19:03
On my system the red crosshair is often not in sync with the crosshair, just rotating the camera is enough to get it offset.
Since the position does not change at all, there should be no way for it to not match. Maybe there's a bug in the [HUD code](https://github.com/minetest/minetest/blob/master/src/client/hud.cpp#L316) (too)?

**Comment by FatalError42O** [comment] 2022-07-03 19:06
> On my system the red crosshair is often not in sync with the crosshair, just rotating the camera is enough to get it offset. Since the position does not change at all, there should be no way for it to not match. Maybe there's a bug in the [HUD code](https://github.com/minetest/minetest/blob/master/src/client/hud.cpp#L316) (too)?

Possibly? it also could be get_pos(), hell it could even just be an issue with floating point numbers being floating point numbers- but when it gets offset it seems to stay at the same position and that's what suggests that the server is somehow tracking it wrong to me.

**Comment by vvv112** [comment] 2022-07-04 13:30
maybe you have a high ping?

**Comment by FatalError42O** [comment] 2022-07-04 17:23
> maybe you have a high ping?

Short answer: no
Long answer: no you don't know how to read.
 Firstly, this is not fixed in post by the server, is does the client positioning wrong, but doesn't update it in post.
Secondly: This was tested on my PC its a singleplayer world, meaning i should have no network ping.
Thirdly: even if it is caused by ping, this does not change the fact that its a persistent bug. If it fixed itself then I wouldn't be concerned, however, it does not reset client position after movement.

**Comment by vvv112** [comment] 2022-07-07 12:36
and the client transmits thousandths of the coordinates?

**Comment by vvv112** [comment] 2022-07-07 12:37
this is not particularly noticeable on servers, maybe it's a feature?

**Comment by Zughy** [comment] 2024-08-18 23:29
@FatalError42O still present?

**Comment by appgurueu** [comment] 2024-08-19 00:34
`TOSERVER_PLAYERPOS` is an unreliable packet, it can get lost. The client only sends it when the player state has changed. This alone would make desync possible (though it should usually be resolved very quickly, as soon as the user does anything changing player state). Similarly, network race conditions would be thinkable where an older packet somehow arrives after a newer one, again leading to the server working with an outdated position.

But that's probably not the issue here. This looks to me like an artifact of the weird way we send player position: It is first multiplied by 100, and then truncated (see `writePlayerPos`). This basically means that there can and will be up to one hundreth of a node margin of error in player pos, which may lead to this artifact (quick estimate, crosshair is off by a few pixels, this may very well correspond to one hundreth of a node in the image).

A fix for this should be relatively straightforward (make the client send and the server receive position in a more precise format). Care needs to be taken to remain backwards compatible.

**Comment by FatalError42O** [comment] 2024-08-19 08:27
> @FatalError42O still present?

I mean it's a 2 year old issue. I think Lar's theory makes the most sense. I haven't witnessed any precision issues that have had an impact on my mod at this point and it uses some pretty serious precision. In all cases any projection onto the player's hud will still be parallel. This is a _very very_ minor precision error and I don't believe it's an issue. If nobody has any objections ill close this issue

**Closed** 2024-09-17 11:36 UTC
Labels: Unconfirmed bug, @ Server / Client / Env., Low priority, Possible close
