### ISSUE TITLE
Multiple instances of particle spawners not visible

### ISSUE THREAD

**Issue by discon-nected** [minetest/minetest#8256] opened 2019-02-18 17:40 UTC
Bug report
`Minetest 5.0.0-dev-291b244-dirty (Linux)`
Operating system: Ubuntu 16.04

##### Summary
If I try to place multiple instances of a node which has a particle spawning ABM, only one node emits the particles...
![selection_024](https://user-images.githubusercontent.com/20234985/52967922-89f27480-3410-11e9-9be5-28b99f641ae7.png)
If the fire emitting particles in the above image is dug, the next in line will emit particles. Also, the node which emits the particles seems to be determined by look direction and player position. I have tried other fire mods including more_fire with the same results. Occasionally the particle spawner will jump from node to node.

##### Steps to reproduce
Use this particle spawner script and place mutiple basic or permanent fire nodes...
```
minetest.register_abm({
    nodenames = {"fire:basic_flame", "fire:permanent_flame"},
    interval = 1,
    chance = 1,
    action = function(pos, node)
            smoke_particles(pos)
    end
})

function smoke_particles(pos)
    local pid = minetest.add_particlespawner({
        amount = 20,
        time = 1,
        minpos = {x=pos.x, y=pos.y, z=pos.z},
        maxpos = {x=pos.x, y=pos.y, z=pos.z},
        minvel = {x=-.2, y=-.2, z=-.2},
        maxvel = {x=.1,  y=.5,  z=.1},
        minacc = {x=0, y=0, z=0},
        maxacc = {x=.1, y=.5, z=.1},
        minexptime = 1,
        maxexptime = 4,
        minsize = 1,
        maxsize = 10,
        collisiondetection = true,
        texture = 'smoke.png',
        vertical = false,
        glow = 2,
    })
end
```
![smoke](https://user-images.githubusercontent.com/20234985/52968040-eb1a4800-3410-11e9-94c7-1820cdfa3e28.png)

The code above works properly in 0.4.17.1, but not in 5.0.0-dev. Tested with MT5 on 2 machines, same result.

This issue was originally posted here: https://forum.minetest.net/viewtopic.php?f=6&t=22144&p=343902

**Comment by sofar** [comment] 2019-02-18 18:32
The ABM is properly firing at all positions, but the particlespawner is only being generated at one position.

**Comment by sofar** [comment] 2019-02-18 18:40
If I spawn indiviual particles instead of particle spawners the problem doesn't exist.

**Comment by discon-nected** [comment] 2019-02-18 18:42
> The ABM is properly firing at all positions, but the particlespawner is only being generated at one position.

Why does this work with 0.4.17.1 and not 5.0.0-dev?

**Comment by sofar** [comment] 2019-02-18 18:45
> Why does this work with 0.4.17.1 and not 5.0.0-dev?

If I knew the answer to that then we'd have the solution, too.

**Comment by discon-nected** [comment] 2019-02-18 18:57
OK, I thought you were implying this was expected behavior.

**Comment by sfan5** [comment] 2019-02-20 12:34
The server is sending the spawners correctly, the client receives them but assigns the same ID to both.

probably cause is 5dab7426451842793b183fbd961ad2ae83c8acbd (@red-001)
`handleCommand_AddParticleSpawner` will take the first free ID and push the spawner into the queue
since this is async, the ID will not be actually assigned until later and it takes the same ID twice

**Comment by paramat** [comment] 2019-02-24 20:29
@sfan5 this has been made a blocker, please could you work on this?

**Comment by sfan5** [comment] 2019-02-24 22:34
This bug can be hotfixed*, no idea how much more complex a proper fix would be.

*claim spawner IDs at the point the network packet is received, it might be possible that the actual spawner never gets added (rejected by the client code later), so this could leak IDs, but it would work.

**Comment by paramat** [comment] 2019-02-25 21:24
Thanks, possibly not a blocker then.

**Comment by discon-nected** [comment] 2019-02-25 22:15
> The bug actually isn't that bad, because this only happens if particle spawners are added in batches
The example I gave was not added in a 'batch', unless I don't understand what that means. I am just adding flames one by one. This problem is present whenever a node has a particle spawning ABM, and more than one node is placed regardless of when they are placed.

**Comment by paramat** [comment] 2019-02-25 23:21
How about we revert that commit? It's only one minor feature of CSM (which is unfinished and has a slightly uncertain future).

**Comment by paramat** [comment] 2019-02-26 01:34
First i'll bisect to check if it is that commit.

**Comment by paramat** [comment] 2019-02-26 02:19
Bug is present in https://github.com/minetest/minetest/commit/5dab7426451842793b183fbd961ad2ae83c8acbd
I sometimes see a second active particle spawner at a mapblock border:

![screenshot_20190226_021741](https://user-images.githubusercontent.com/3686677/53382652-ed2e5a80-396c-11e9-81c8-67b4c37f64a7.png)

**Comment by paramat** [comment] 2019-02-26 02:24
Bug is not present in the previous commit da80e8af8adee493e698227cfc201859a1515c81 so confirmed the breaking commit is 5dab7426451842793b183fbd961ad2ae83c8acbd

![screenshot_20190226_022143](https://user-images.githubusercontent.com/3686677/53382859-7e9dcc80-396d-11e9-82ee-89e28de686b9.png)

Test code is:
```
minetest.register_abm({
    nodenames = {"fire:basic_flame", "fire:permanent_flame"},
    interval = 1,
    chance = 1,
    action = function(pos, node)
            smoke_particles(pos)
    end
})

function smoke_particles(pos)
    local pid = minetest.add_particlespawner({
        amount = 2,
        time = 1,
        minpos = {x=pos.x, y=pos.y, z=pos.z},
        maxpos = {x=pos.x, y=pos.y, z=pos.z},
        minvel = {x=-0.1, y=0.1, z=-0.1},
        maxvel = {x=0.1, y=0.5, z=0.1},
        minacc = {x=0, y=0, z=0},
        maxacc = {x=0, y=0.5, z=0},
        minexptime = 1,
        maxexptime = 4,
        minsize = 1,
        maxsize = 10,
        collisiondetection = true,
        texture = "smoke_puff.png",
        vertical = false,
    })
end
```

**Comment by paramat** [comment] 2019-02-26 02:29
Working on a revert PR.

**Comment by paramat** [comment] 2019-02-26 03:06
PR #8288

**Comment by paramat** [comment] 2019-02-26 04:28
PR merged.

**Comment by nerzhul** [comment] 2019-02-26 07:57
PR reverted. The fix should not be so difficult to do. @sfan5 did the root cause analysis.

**Comment by discon-nected** [comment] 2019-02-26 08:06
This issue should be reopened as the PR was reverted.

**Comment by nerzhul** [comment] 2019-02-26 08:15
I'm working on the fix it should not be so difficult

**Comment by nerzhul** [comment] 2019-02-26 08:20
Main problem is here:

```
u32 client_id = m_particle_manager.generateSpawnerId();
	m_particles_server_to_client[server_id] = client_id;
```
We loose some things. I think i will work on a huge refactor on that event based useless part in 5.1

**Comment by nerzhul** [comment] 2019-02-26 09:03
see #8289

**Comment by paramat** [comment] 2019-02-26 21:52
> PR reverted

Note, this was done without agreement so was against dev rules.

**Comment by jastevenson303** [comment] 2019-02-26 22:47
No, Paramat, you went ahead and did everything on your own accord without waiting.

**Comment by rubenwardy** [comment] 2019-02-27 03:29
Paramat followed the rules, his revert had the proper approval. Nerzhul's didn't

**Comment by jastevenson303** [comment] 2019-02-27 04:38
He made a PR, you approved it in like an hour or two, and then it got
merged.

**Comment by sofar** [comment] 2019-02-27 05:01
These sort of things happen in many projects and especially close to releases. Everyone is acting in what they think is the best interest. The only thing that matters in the end is to test everything one more time and just get over it - it's not worth the discussion.

**Comment by nerzhul** [comment] 2019-02-27 06:44
nobody took time to look at the issue which is a simple issue. it's unacceptable to revert a feature like this. i suspect he seem oh a CSM PR, reverting is nice :), but anyway now there is the acceptable PR to merge.

**Comment by rubenwardy** [comment] 2019-02-27 18:09
Reverting a broken feature in an unsupported area of the API is acceptable if the fix would take too long or cause problems

**Comment by jastevenson303** [comment] 2019-02-27 18:25
Would it have taken too long?  Would it have caused problems?  There's a lot of 'ifs' there, and nerzhul already has a fix open.

**Comment by nerzhul** [comment] 2019-03-01 19:16
Fixed by #8289

**Comment by nerzhul** [comment] 2019-03-01 19:16
Don't hesitate to test it yourself :)

**Closed by nerzhul** 2019-03-01 19:16 UTC
Labels: @ Server / Client / Env., Blocker, Bug, High priority

**Comment by paramat** [comment] 2019-03-01 19:56
jastevenson303,
> No, Paramat, you went ahead and did everything on your own accord without waiting.

That's very silly because it's actually the opposite, i didn't, and that is exactly what nerzhul did by reverting a commit without agreement of any other core dev, a serious breaking of dev rules. Rubenwardy and i merged a PR with the required 2 approvals.
> He made a PR, you approved it in like an hour or two, and then it got merged.

Yes, that is allowed by dev rules, commits can be merged on the agreement of 2 core devs, many commits have been made quickly like this. Please read the dev rules instead of making silly accusations.
> nobody took time to look at the issue which is a simple issue
Well, sfan5 did, and you could have done so earlier, but didn't, which is ok of course, but why blame others for this?
> it's unacceptable to revert a feature like this

Only according to you.
This feature has not been released into stable MT yet, so in a way it is not removing a feature.
In some situations yes it is obviously best to revert a broken unstable feature just before a release if the risk caused by a bugfix is too high. In some situations you would make the same decision.

However, it seems that the fix is simple and the risk is not too high, so i am actualy ok with a fix being made instead of a revert, what i object to is impulsive reverting and breaking of dev rules. If nerzhul had asked first i would have agreed to a fix instead of a revert, once the fix had been tested.
> i suspect he seem oh a CSM PR, reverting is nice

I would have done the same whatever the feature was. I have no problem with client side particles as i support SSCSM, as you know. I have been asking for it to be completed for years, while you were absent from MT and refused to complete it.
This accusation makes me suspect more that you got defensive because this is CSM related.

**Comment by jastevenson303** [comment] 2019-03-01 20:31
Wow.

**Comment by discon-nected** [comment] 2019-03-01 20:51
> Wow

He's right but your cynicism obscures your understanding

**Comment by paramat** [comment] 2019-03-01 22:56
To clarify ...

We are, or were, aiming for a release this weekend (tomorrow). 5 days ago we decided this issue is a release blocker, quite a critical situation. So the options were: a fix, or if a fix is too complex and too risky, a revert (of an unstable feature not yet released into stable MT) followed by a fix straight after release.

I had no idea what should be done as it depends on the riskyness of the fix, so i asked a question above about the riskyness and sfan5 wasn't sure how complex a fix would be:
> It can be hotfixed*, no idea how much more complex a proper fix would be.

So no fix appeared to be coming, or even an idea of how risky a fix would be, so the situation became even more critical.

4 days ago in IRC http://irc.minetest.net/minetest-dev/2019-02-25#i_5501326 i'm still not sure what to do:

21:25 paramat    #8256 is possibly not a blocker, apparently the bug is somewhat rare
21:25 ShadowBot  https://github.com/minetest/minetest/issues/8256 -- Multiple instances of particle spawners not visible
21:26 paramat    not sure what to do
21:30 p_gimeno   is it a regression?
21:35 paramat    yes, and a bug not present in last stable MT
21:35 Wuzzy      as far i know, yes
21:35 Wuzzy      based on claims from others
21:59 p_gimeno   I haven't looked into it, but is rolling back the commit that introduced the problem out of the table?
23:19 paramat    no, it was A CSM commit and CSM is unfinished so, worth considering
23:22 paramat    if reverting is less risky  than a workaround or a fix then i support a revert
23:38 rubenwardy I'd support reverting it

At this point i wasn't going to make a PR. I expected a revert would not be supported by another core dev and i wasn't going to do all that work for nothing.
It's clear i still had no preference for what to do and that my decision would only be based on what is best for MT 5.0.0.
To my surprise rubenwardy stated he would support a revert, so i was like 'oh ... ok' and wrote the PR.

So notice i only wrote the PR due to rubenwardy's support, and he approved it. So any criticism should be directed to both of us.
(jastevenson303 seems to have a problem with me, i'm aware of it, there has been some strange behviour.)

It's good to see a fix eventually happened and i appreciate it being made.

**Comment by jastevenson303** [comment] 2019-03-02 01:57
my understanding is definitely obscured.  it doesn't trouble me personally,
though, and so there is no cynicism.

i too am glad everything worked out in the end, as i knew it would.
