### ISSUE TITLE
Slime model from Mineclonia not rendered behind partially transparent nodes

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11856] opened 2021-12-13 07:39 UTC
##### Minetest version
Minetest commit 76aa610

##### OS / Hardware
Operating system: Debian GNU/Linux
CPU: Intel Core i7-8565U

GPU model: Intel UHD Graphics 620 (Whiskey Lake) rev 02
OpenGL version: 3.0 Mesa 18.3.6

##### Summary
The Mineclonia slime model is not rendered behind partially transparent nodes.

Screenshot: https://mister-muffin.de/p/XAo_.png

Note that this is a *fundamentally* different bug than https://github.com/minetest/minetest/issues/11852 and closing this bug as a duplicate just because the other bug also deals with parts of the slime model not being visible would seem a bit stupid to me. You can verify that this bug is different by reproducing it, then turning off shaders, which is a workaround to the other one, but not to this one.

##### Steps to reproduce
1. Get Mineclonia from https://git.minetest.land/Mineclonia/Mineclonia/ and install into Minetest's `games` folder.
2. Create a new world with Minetest at commit 76aa610.
3. Deactivate the `mcl_selftest` mod to get around the bug that `minetest.find_nodes_in_area()` can no longer find all nodes in the map right now – see https://github.com/minetest/minetest/issues/11828 . The `mcl_selftests` mod contains a self test that will fail if `minetest.find_nodes_in_area()` can not find all nodes that the test has placed.
4. Enter the world in creative mode with damage turned off.
5. Get a glass node and a slime spawn egg and a magma cube spawn egg.
6. Spawn a slime and a magma cube.
7. Build a glass tower next to the slime and the magma cube.
8. Look at the slime and the magma cube through the glass towwer.
9. Note that the part of the slime that should be visible through the glass is invisible.

**Comment by sfan5** [comment] 2021-12-13 13:16
This is a duplicate of #95, which serves as a placeholder for transculency sorting issues.

**Closed by sfan5** 2021-12-13 13:16 UTC
Labels: Unconfirmed bug

**Comment by erlehmann** [comment] 2021-12-13 16:32
I must admit: I did not expect that, as #95 is about nodes.
