### ISSUE TITLE
No lava damage

### ISSUE THREAD

**Issue by wilkgr76** [minetest/minetest#3064] opened 2015-08-15 11:05 UTC
The other day, I was playing linuxgaming.us multiplayer, and before the nightly backup, everyone was immune to lava damage - including me. I was using Krock's build. Thron said that if he holds Left-shift, he doesn't get damaged. Even after the server restart, some people were immune to it. Just today, the same happened with a different player.

The server was running 0.4.12 at the time of this issue. (I, too, have not been able to reproduce this in the last couple of days)

**Comment by paramat** [comment] 2015-08-15 16:39
0.4.12 latest dev?

**Comment by kwolekr** [comment] 2015-08-15 17:38
BlockMen and I are having trouble reproducing locally and on that server.

**Comment by LazyJ** [comment] 2015-08-15 19:08
LinuxGaming is using Minetest 0.4.12 stable, released back in... February(?).

iirc, deezl and CWz have also mentioned this bug on their servers *(MTZ-Basic, BlueLobster-Pro)*.

**Comment by wilkgr76** [comment] 2015-08-16 05:22
I have also noticed if you hold LShift while clicking respawn, you don't
get that red "flash" when you get hurt until you're down to 2 hearts.

**Comment by paramat** [comment] 2015-08-16 16:48
There have been changes and fixes to damage since 0.4.12 stable.

**Comment by kilbith** [comment] 2015-08-16 17:27
The damage bug has been introduced during the beginning of 0.4.13 devel with the network rewrite. 0.4.12-stable does not contain any of the network rewrite.

**Comment by amadin** [comment] 2015-08-17 14:46
If you use hunger mod with hud and 3d armor mod you must update 3d armor mod to last version. There are was conflict between this mods

**Comment by wilkgr76** [comment] 2015-08-19 05:32
@amadin The 3D armour mod wasn't being used, nor the hunger mod, and IIRC, neither was the hud mod.

**Comment by amadin** [comment] 2015-08-19 07:26
Try to turn off all mods besides "default"

**Comment by paramat** [comment] 2016-04-03 00:52
@wilkgr76 Still happening?

**Comment by wilkgr76** [comment] 2016-04-06 02:12
@paramat I completely forgot about this. I don't go swimming in lava anymore so can't confirm/deny.

Different note: Pressing 'sneak' while respawning sometimes respawns you a couple blocks above your death, sometimes works, sometimes doesn't.

**Comment by ObaniGemini** [comment] 2016-04-06 06:00
@wilkgr76 : this should be fixed by https://github.com/minetest/minetest/pull/3535 , do you use the latest git ?

**Comment by paramat** [comment] 2016-04-06 14:52
Closing due to being a 0.4.12 bug that is difficult to reproduce.

**Closed by paramat** 2016-04-06 14:52 UTC
Labels: Unconfirmed bug

**Comment by wilkgr76** [comment] 2016-04-06 23:36
@ObaniGemini No, and I only play on servers. Note that this issue is now closed and I won't be replying to it anymore.
