### ISSUE TITLE
Unimportant settings in the main menu

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#8367] opened 2019-03-12 14:27 UTC
##### Issue type

 - Feature request

##### Summary

In my opinion some settings should be removed from the main menu:
* 3D Clouds: As far as I know, the performance impact of 3D clouds is very small and I doubt that there are many players who find this setting (enabled by default) so important that its presence in the advanced settings does not suffice.
* Opaque Water: Analogous to the 3D clouds setting
* Antialiasing: FSAA is a rather experimental setting; it looks wrong for many nodes because the other end of the texture (next texel) is used for the corner, see #6860
* Waving Water: It makes low flowing water visually disappear and reappear, which makes gameplay more difficult/annoying:
![2019-03-12-152332_1920x1056_scrot](https://user-images.githubusercontent.com/3192173/54207803-20c7c380-44db-11e9-8cad-d2de88f41bee.jpg)

Please tell me if you also think that these settings should be removed from the main menu (still accessible in advanced settings).

**Comment by ClobberXD** [comment] 2019-03-12 15:10
> Waving Water: It makes low flowing water visually disappear and reappear, which makes gameplay more difficult/annoying

I think it's that visual bug that has to be fixed then. I do toggle that setting at times, and having it in the basic settings would be nice.

**Comment by paramat** [comment] 2019-03-12 19:39
Waving water is part of shaders, i think all shader options should remain together in one place as they are now.

**Comment by benrob0329** [comment] 2019-03-12 20:09
Then waving water needs to be fixed so that it doesn't change/break gameplay.

**Comment by paramat** [comment] 2019-03-12 20:38
Waving water isn't broken, it's expected behaviour and unfixable. I still think that waving water should be removed as a feature (as it was about to be by RBA) because it causes so much visual weirdness, but i expect there will be complaints if it was.

**Comment by LoneWolfHT** [comment] 2019-03-12 20:47
Yes for waving and opaque water. Not sure about the others

**Comment by HybridDog** [comment] 2019-03-12 20:50
> Waving water is part of shaders, i think all shader options should remain together in one place as they are now.

Currently not all shader options are shown, you can for example fine-tune the water wave behaviour:
https://github.com/minetest/minetest/blob/e22a69d61a04624fe1eca818740b90dbb958e658/minetest.conf.example#L657-L664
Bumpmapping and Normalmap generation can be adjusted, too.

**Comment by benrob0329** [comment] 2019-03-12 21:35
>it's expected behaviour and unfixable

No, no it's not. Expected behavior would be a slight change in water height variation, not so much that it literally disappears into the floor. This is hardly unfixable, and a change in the default settings would at least help.

**Comment by paramat** [comment] 2019-03-13 00:51
I mean, the shader master options.

Sorry for writing 'unfixable', edited. It 'seems' unfixable to me currently. 
'Expected' as in expected considering how the shader code is written, not expected appearence. By 'not broken' i mean it's not broken code, just a bad appearence. And i wouldn't consider it a 'bug' as it is bad design not broken code.
All this is down to various meanings of words.

**Comment by ClobberXD** [comment] 2019-04-08 12:33
I support removing anti-aliasing and texture filtering options from the basic settings, and adding more important fundamental options instead (mouse sensitivity, FOV, etc.).

(Context: https://github.com/minetest/minetest/issues/8459#issuecomment-480778800)

**Comment by benrob0329** [comment] 2020-03-13 02:02
This still seems like a problem, although waving water has been mostly fixed now.

**Comment by HybridDog** [comment] 2020-03-13 15:00
> […] waving water has been mostly fixed now.

When I tested the new waving water, small flowing water nodes were still visually dis- and reappearing:
![fot_2020-03-13-15:49:00_891015697](https://user-images.githubusercontent.com/3192173/76631664-536b2880-6542-11ea-85d4-48f43202b0ca.jpg)
![fot_2020-03-13-15:49:08_699763222](https://user-images.githubusercontent.com/3192173/76631672-56feaf80-6542-11ea-878e-3772ed485135.jpg)

>  No core dev support long term 

I don't want to make a PR for this because if I removed those settings, I would need to add new (currently only in advanced) settings so that the settings page does not look naked. If I chose these new settings, people may often find better or controversial choices and the PR would not be merged for several months.

**Comment by paramat** [comment] 2020-03-13 20:48
Sorry, i do not know why i closed this. I support removing unimportant settings.
'3D clouds' seems the obvious one. 'Opaque water' probably has a significat performance impact so not sure about that. 'Waving water' cannot be removed as explained above, it is a primary shaders feature.

**Comment by Wuzzy2** [comment] 2020-04-30 15:33
I suggest to use the gained space to add sound settings.

**Comment by HybridDog** [comment] 2020-04-30 16:51
There are already sound settings ingame. As far as I know, it is common practice to show sound volume settings first in a situation where sound is (or can be) played; if, for example, the volume of a switched off Smart TV is set to 100% and I want to watch TV, I need to switch it on and try to lower the volume while it is loud. It is not possible to change the volume while it is muted and lowering the volume is slow because the software is slow, especially when it loads things after the device is switched on.

I have removed three settings and added undersampling in that branch:
https://github.com/HybridDog/minetest/tree/m_settings_unimportant
I'm not sure what to do with the shader settings. Bumpmapping, (Normalmaps Generation), Parallax Occlusion and Waving Water have some visual bugs/problems.

**Comment by Desour** [comment] 2020-04-30 17:46
The main menu could use a scroll container to gain space in the settings tab. This would allow to put many more settings there, with more space between the checkboxes.

**Comment by grorp** [comment] 2023-09-14 06:30
Since the settings menu has been reworked completely (see #12480), the points stated in this issue are not applicable anymore.

**Closed by grorp** 2023-09-14 06:30 UTC
Labels: Request / Suggestion, @ Mainmenu, Supported by core dev
