### ISSUE TITLE
Coloured lights

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7754] opened 2018-09-28 16:37 UTC
##### Issue type
- Feature request
____
<h1>Colored lighting</h1>
Please make a way to have coloured light coming from nodes

`    light_colour = {`
`      r=50,`
`      g=7,`
`      b=130`
   ` },`
As the parameter in the node registration

**Comment by rubenwardy** [comment] 2018-09-28 16:42
Duplicate of #2670

Please search before opening an issue

**Closed** 2018-09-28 16:41 UTC
