### ISSUE TITLE
Everything in view freezes when opening chat on android.

### ISSUE THREAD

**Issue by nininik0** [minetest/minetest#14465] opened 2024-03-16 15:08 UTC
### Minetest version

```true
5.8.0 android
```

### Irrlicht device

Doesn't matter 

### Operating system and version

Android

### CPU model

Dosent matter

### GPU model

Any

### Active renderer

Any android device

### Summary

Whenever you open chat on minetest in android everything outside of it freezes. Like the view freezes and you can't see anyone or anything approaching you slowly. Which is a big issue for some games such as ctf because you can easily get killed while chatting. Another issue is that it also drops YOUR framerate and can sometimes make you hover in the air. However, multicraft somehow managed to overcome this issue. Maybe we can too.

### Steps to reproduce

Open chat on android and watch the background

**Comment by grorp** [comment] 2024-03-16 15:39
Duplicate of https://github.com/minetest/minetest/issues/10842, already fixed by https://github.com/minetest/irrlicht/pull/255. The fix was merged before the 5.8.0 release, but unfortunately the official 5.8.0 build on the Play Store was compiled with an outdated Irrlicht version. The fix will be included in 5.9.0.

**Closed** 2024-03-16 15:45 UTC
Labels: Unconfirmed bug, Possible close

**Comment by oong819** [comment] 2024-04-09 12:22
You can try apk on Github or F-Droid
