### ISSUE TITLE
Too damn many unconfirmed bugs

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11998] opened 2022-01-28 11:53 UTC
Title says it [all](https://github.com/minetest/minetest/issues?q=is%3Aissue+is%3Aopen+label%3A%22Unconfirmed+bug%22). Many of these should long have been retagged to "Bug".

**Comment by Zughy** [comment] 2022-01-28 14:08
#11568 might help

**Comment by grorp** [comment] 2022-01-28 14:29
Really like this "Not a bug" label :D

**Comment by Wuzzy2** [comment] 2022-01-29 11:59
Do you want "label rights"? If yes, then say so. Maybe you get them.

**Comment by appgurueu** [comment] 2022-01-29 12:30
> Do you want "label rights"? If yes, then say so. Maybe you get them.

I just want the issues to be labeled correctly, that's all - I don't care how they get there.

**Comment by NathanSalapat** [comment] 2022-01-29 17:19
<sarcasm>Well maybe if you confirmed every unconfirmed bug they could be changed.</sarcasm>

Seriously though, if no core dev is going around checking every bug report to see if it's valid there's not much that can be done about it.

**Comment by appgurueu** [comment] 2022-01-29 17:33
> [sarcasm]Well maybe if you confirmed every unconfirmed bug they could be changed.[/sarcasm]
> 
> Seriously though, if no core dev is going around checking every bug report to see if it's valid there's not much that can be done about it.

Let me rephrase: I believe the bar for "bug confirmation" is way too high. The default is that bugs are assumed to be unconfirmed - fair enough. But if a detailed report is provided, that alone should count as "confirmation".

**Comment by appgurueu** [comment] 2022-01-29 17:36
> [sarcasm]Well maybe if you confirmed every unconfirmed bug they could be changed.[/sarcasm]
> 
> Seriously though, if no core dev is going around checking every bug report to see if it's valid there's not much that can be done about it.

Let me rephrase: I believe the bar for "bug confirmation" is way too high. The default is that bugs are assumed to be unconfirmed - fair enough. But if a detailed report is provided, that alone should count as "confirmation".

**Comment by randomMesh** [comment] 2022-02-01 10:37
I like how this issue it both an unconfirmed bug but at the same time is not a bug. You guys need to get your labels straight.

**Comment by Zughy** [comment] 2022-03-28 21:25
I suggest to close this issue, I don't know what could be the purpose of it, except underlying a meta problem (maybe more suited for the forum)

**Closed** 2022-03-28 21:37 UTC
Labels: Unconfirmed bug, Not a bug
