### ISSUE TITLE
[Feature Request] Local Server List

### ISSUE THREAD

**Issue by DustyBagel** [minetest/minetest#14729] opened 2024-06-05 01:11 UTC
### Problem

There is currently no way to see what servers/games are being hosted on your local network. I think it would be nice to be able to see what local games are going on.

### Solutions

Have a separate list in the 'Join Game' tab of servers that are locally hosted.

### Alternatives

Another idea would be to just save local servers you have joined in the past like how they are already saved in the favorites tab but have the minetest client be able to check if that server is online or not and have the server status in the favorites list with the rest of the server information like address and port. Maybe we could have the question mark symbol next to the server address in the favorites tab change to something else if it is currently online.

**Comment by rubenwardy** [comment] 2024-06-05 08:48
Thanks for the suggestion. This is a duplicate of #10208

**Closed by rubenwardy** 2024-06-05 08:48 UTC
Labels: Feature request

**Comment by DustyBagel** [comment] 2024-06-06 02:17
Oh sorry. I tried looking for a similar feature request with github's search bar on this repository, but I wasn't able to find one.
