### ISSUE TITLE
Crash on pasting wrong data into formspec fields on Windows

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#14617] opened 2024-05-06 11:49 UTC
### Minetest version

```true
5.8.0
```

### Operating system and version

Windows 11

### Summary

Reported by mr.917 on Discord:

> pasting wrong data into formspec fields results in a game crash, with wrong data being something like a copied image/a copied file

I haven't been able to reproduce this on Ubuntu 22.04 (tried copying image data from GIMP), so this might be a platform-specific issue.

**Comment by grorp** [comment] 2024-05-06 13:06
Duplicate of fixed #14150.

**Closed** 2024-05-06 13:37 UTC
Labels: Unconfirmed bug, Windows, Possible close
