### ISSUE TITLE
HUD texture scaling bug? (verified using Wuzzy's "hudbars" mod)

### ISSUE THREAD

**Issue by Pilcrow182** [minetest/minetest#2558] opened 2015-03-25 22:40 UTC
There seems to be a HUD texture scaling bug, making certain textures scale much larger than they should be. I've only encountered it using Wuzzy's "hudbars" mod, but I'm betting there are other affected mods, and everything was fine a few days ago...

How it should look (modified slightly):
![](http://i.imgur.com/GHqPuEH.png)

How it looks in the latest git version:
![](https://i.imgur.com/IHC1j9J.png)

**Comment by kilbith** [comment] 2015-03-25 23:02
I may observe the same HUD bug...

**0.4.12-stable** : 
![screenshot_1283499211](https://cloud.githubusercontent.com/assets/7883281/6837308/3e0d80ac-d34b-11e4-83e2-fb2c9dc59165.png)

**0.4.12-dev** : 
![screenshot_1279681088](https://cloud.githubusercontent.com/assets/7883281/6837315/4a8b3590-d34b-11e4-9289-98193a8b252a.png)

**Comment by Pilcrow182** [comment] 2015-03-26 01:04
I've been compiling different versions to test, and this issue seems to have originated from commit 1e4fb80d46da634f04d84e3f1065aaabc6909468 (march 7th), as this issue was not present in 26153bab7dbe57a0200949c9a121058150e67f6c (right before it). I'm still no C/C++ programmer, but I'm sure somebody can squash this bug...  ;)

**Comment by Pilcrow182** [comment] 2015-03-26 03:08
It would seem this might be two seperate issues: the bars themselves (the big colored areas) -- as well as the lobby area pointed out by kilbith, probably -- seem to have originated from commit 1e4fb80d46da634f04d84e3f1065aaabc6909468, while the oversized icons (the bread and heart in my screenshot) were from a later commit, 11372ac646440c789ac568133699a20938e33dad.

Still, at the suggestion of est31, I tried adding 'texture_min_size = 0' to my minetest.conf and discovered it does actually resolve -both- problems...

**Comment by crazyR14** [comment] 2015-03-26 19:48
so in the core someone needs to add texture_min_size = 0 by default if it is not defined in the conf

**Comment by Pilcrow182** [comment] 2015-03-27 08:14
Well, yes and no, crazyR14. If you look at the commits I mentioned, it's obvious they've changed the default texture_min_size value for a reason.

My guess is that they changed it to improve node textures or something, but didn't realize it would affect the HUD elements as well. If that is the case, it might be a better solution to just remove any references to texture_min_size from whichever function/calculation handles HUD scaling, and leave texture_min_size itself alone.

That may not be right though; I'd know more if I understood the code...  :P

**Comment by Warr1024** [comment] 2015-03-27 19:11
The problem seems to be caused by the fact that the Lua API for some HUD types doesn't require a "scale" factor, and thus just uses whatever size the original image is.  This will also break if someone is using a high-resolution texture pack, and the texture pack author didn't specifically avoid creating a high-res texture for the HUD bar, e.g. if the same texture by name was used in a different context where scaling wasn't a problem.

Should it even be permissible to create HUD's without specifying their on-screen size?  It may have made sense in the past, when there was no need to scale the images, but HUD elements now scale manually via gui_scaling, and automatically based on DPI; since the original pixels in the HUD image might now be *larger* than 1 on-screen pixel, there is now a reason to *want* to create high-resolution textures for HUD elements.

**Comment by Warr1024** [comment] 2015-03-27 19:14
Also, texture_min_size is applied at the time textures are uploaded to the video card, after combining and transforms are applied.  Unfortunately, at that time, there is no way to know whether they're *destined* to be used as mesh textures, HUD elements, or *both*.

The quickest solution may be to keep track of what upscaling was used to generate each texture, and simply apply the reverse scaling factor when rendering as HUD elements.  Alternatively, an alernative texture could be created with the *original* scaling (if different than the final scaling) and looked up when drawing the HUD elements.

**Comment by SmallJoker** [comment] 2015-03-28 09:48
Got the same problem with my crosshair.png
![Kitten](http://i.imgur.com/ffTyWhh.png)

**Comment by kilbith** [comment] 2015-03-29 21:07
**[!] This must be marked as [blocker]**

Ethic Rush server...

![screenshot_20150329_230613](https://cloud.githubusercontent.com/assets/7883281/6887716/4474c520-d668-11e4-8eff-96be5fef31e0.png)

**Closed** 2015-03-31 07:03 UTC
Labels: @ Client / Audiovisuals, bug, High priority

**Comment by Zeno-** [comment] 2015-03-31 07:09
fixed by db32e6c5aa3bf79c23fa51f9297440fcaf09215d
