### ISSUE TITLE
Server receives an incorrect player position after attaching to an entity

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#9139] opened 2019-11-22 22:41 UTC
5.1.0 and earlier
_different behavior but still broken in 5.2.0dev_
I've been plagued by this elusive bug which causes the player to get teleported to a past position. The position could be from as little as a second ago, to several minutes ago and dozens of blocks away. Sometimes the server would get possessed and teleport me to the same spot over and over, laughing evilly until I rebooted it and dunked it in holy water for good measure.
This is sadly one of those bugs that seem to happen randomly and without a single clear cause.
It resembles the horrible anticheat "feature" and how it tends to punish players for server issues, but I have that turned off too.
Possible aggravating factors:
- Attaching a player to an entity and detaching frequently, such as boarding/leaving a boat over and over
- Calling ObjectRef:get_pos() on the player for any reason
- Interacting with entities with LMB or RMB
- Travelling many mapblocks in a short time
- Server load
- Network lag
- Gremlins

Now keep in mind this does NOT have to occur during a server freeze, so this is not a case of client side movement disagreeing with the server. This is the server just deciding to teleport me to a past position, even as I monitor the position and deltaTime with lua to rule out esoteric quantum effects.

I can _try_ to give you a video of it happening, but hunting this thing is like trying to get the bigfoot and the chupacabra to pose for a family photo; recording several hours of footage in hopes that it will actually happen.

**Comment by ClobberXD** [comment] 2019-11-23 06:50
I've fallen prey to this bug a billion times, thanks for taking the time to create an issue. While I still do tend to face this issue from time to time, it manifests far too less in `5.x.x+` compared to `0.4.x` from what I've observed.

> - Server load
> - Network lag

These two seem to be the (much) more likely causes for the annoying phenomenon. Also, this seems to manifest more when the network lag is on the client-side, and not as much when on the server-side. This leads me to believe that this might be caused due to the incorrect order of packets  received by the server, because an older movement packet might've reached the server last, making the server consider the older pos and view dir to be the latest.

If my aforementioned suspicions are right, perhaps this issue could be fixed by attaching some sort of data to the packet that can be used by the server to determine the latest packet according to the *sending* order in the client-side. The server could store the data from the last x packets and select the latest data (acc. to sending order) as current.

**Comment by style-nine** [comment] 2019-11-23 07:21
How to repro this issue in singleplayer:

1) Create a new Flat, MTG world
2) Enable Creative
3) /grantme all
4) Give yourself Powered Rail and a Cart
5) Place a track about 500 blocks long (just hold right-click while moving forward)
6) Add a mod that has this one line: carts.speed_max = 64
7) Ride the cart back and forth a few times in your world

**Comment by sfan5** [comment] 2019-11-23 17:39
Note that the issue reporter said that this happens with <b>anticheat disabled</b>.
Is this also true for the problems either of you mentioned?

**Comment by style-nine** [comment] 2019-11-23 19:27
My above observations have been confirmed here with both with disable_anticheat set to true and false.

**Comment by style-nine** [comment] 2019-11-23 19:39
If you want to see some serious rubber-banding, all you need to do is to make a loop in the track and ride it for a couple of minutes.
![screenshot_20191123_143629](https://user-images.githubusercontent.com/41269111/69484251-0b8f8c80-0dff-11ea-81c0-20905cab1cee.jpg)

**Comment by hecktest** [comment] 2019-11-23 19:49
Going too far too fast is in fact a major factor so I believe you.
I'm gonna have to knock out network lag as a cause; simulating a horrible connection with clumsy did not increase my chances of spotting the chupacabra.
Spamming right click on my waifu doesn't seem to do it anymore either, though I _swear_ last night it made me teleport around like a wizard. I'll try the cart thing.

**Comment by hecktest** [comment] 2019-11-23 20:10
Aaaand negative; I observed some jittering due to overzealous extrapolation, but this isn't it. We're talking here about being teleported hundreds of nodes away. There's probably something extra in my code that attracts the demons.
Looks like it's time for an isolated repro.

**Comment by ClobberXD** [comment] 2019-11-24 04:14
> Going too far too fast is in fact a major factor so I believe you.

I've encountered the "chupacabra" even while sprinting, which isn't that fast or far, I think.

**Comment by hecktest** [comment] 2019-11-24 07:23
Well who would've thought, the beast was particularly active today so I finally caught it on camera!
Now this isn't the "big one" that yanks you back 500 nodes but I assure you it's the same bug.
![chupacabra](https://user-images.githubusercontent.com/42101236/69491298-9e7a0680-0e93-11ea-9d19-5375a83a2fc8.gif)

**Comment by hecktest** [comment] 2019-11-24 07:39
And I also managed to repro the big one - it is pretty consistent, but it takes time to set up, and I don't know which part makes it break yet.
![bigfoot](https://user-images.githubusercontent.com/42101236/69491425-54922000-0e95-11ea-872a-cfdb9ce8cfd0.gif)
Things I've done here:
- Strafe around for a few kilometers (not shown)
- Return to the spot where the entity is
- Fiddle with the entity some while moving (LMB/RMB events and get_pos getting called)
- Stop. The rooting code spawns a dummy entity and attaches me to it. I get teleported at about the same frame. Get_pos gets called somewhere here, then set_attach. I don't know at which point precisely do I get teleported, and whether it happens to me or the parent entity first.

**Comment by ClobberXD** [comment] 2019-11-24 12:26
The issue title suggests that this bug is related to entity attachment, but all of my experiences with this bug have occurred when I was "free". I haven't ever encountered the bigger badder version of this bug that yanks me back hundreds of nodes, but the small yanker is way too familiar for me.

**Comment by style-nine** [comment] 2019-11-24 17:27
The problem with more dramatic teleports is the possibility of it being flawed Lua code rather than an engine bug. The bug I can repro is a genuine bug and not something that could have been a logical error in some mod somewhere.

**Comment by hecktest** [comment] 2019-11-24 19:53
>possibility of it being flawed Lua code 
How nice of you, but I would not submit this if I had any doubt that it's minetest; you can encounter this in minetest_game too, only there aren't as many opportunities for it to happen. I spawn the entity anew every time and never cache any position vector, precisely because of this. Still happens.

sfan, in the first gif the teleports happen precisely as I hit RMB or LMB, are you sure this is attachment related? I would say the demons live in get_pos or somewhere close to it

**Comment by SmallJoker** [comment] 2019-11-24 20:46
@style-nine 
> If you want to see some serious rubber-banding, all you need to do is to make a loop in the track and ride it for a couple of minutes.

If you're talking about being moved back and then slowly catching up to the previous position: caused by erroneous `dtime` calculation. The server and client don't predict exactly the same movement - maybe picking up #9116 again would help a little bit.

**Comment by sfan5** [comment] 2019-11-24 22:32
> sfan, in the first gif the teleports happen precisely as I hit RMB or LMB, are you sure this is attachment related? I would say the demons live in get_pos or somewhere close to it

I am not __sure__ about it, just a guess since your mod/game seems to use attachments heavily.

**Comment by ClobberXD** [comment] 2019-11-25 03:40
> I am not sure about it, just a guess since your mod/game seems to use attachments heavily.

I'm *almost* sure this has nothing to do with attachments - it's on CTF that I used to experience this bug, although it has drastically decreased since the server updated to 5.0.0.

**Comment by hecktest** [comment] 2019-11-25 04:48
I also failed to reproduce this using boats and carts alone, there must be some other factor here. After banging my head a bit trying to remember where I first saw this, I'd say it was when flying a frameship in technic, and that's... get_pos & set_pos again

**Comment by hecktest** [comment] 2019-11-28 02:18
More evidence in favor of get_pos causing it: having a light node follow the player (fake dynlight) can summon the demons as well, and I did not have to stop in order to get yanked.

**Comment by hecktest** [comment] 2019-12-03 19:47
Oh dear, turns out placing nodes can summon satan as well.
![demons](https://user-images.githubusercontent.com/42101236/70083928-9fd2ce00-160d-11ea-842d-005608f37b0a.gif)
Hitting RMB is definitely a trigger, both on nodes and on entities. The teleport happens before interaction; you can see the node being placed in the wrong spot, and I've had the same thing happen with NPCs.

**Comment by SmallJoker** [comment] 2019-12-05 18:22
Trying to exclude possible causes. Attachments are special, so there shouldn't be any involved in the following cases:
Checked = confirmed to have no relation with this issue

 - [x] Anticheat. Still happens when it's disabled (singleplayer, for example)
 - [x] Servers. Happens on CTF (@ClobberXD), although anticheat is enabled there
 - [ ] Mods. Do the same issues persist without any additional mods?
 - [ ] Minetest Game. Does it happen with say - MineClone2 - too?
-  [ ] Network. Does it happen in 5.2.0-dev too?

**Comment by ClobberXD** [comment] 2019-12-05 18:41
> Happens on CTF

This used to be very common when the server was running 0.4.16. I think this became less frequent even in 0.4.17.x, though I'm not very sure. But it has definitely reached an all-time low after the server upgraded to 5.x, although I still do encounter this at times of severe lag.

**Comment by hecktest** [comment] 2019-12-06 15:50
Definitely nothing to do with minetest_game, ctf or any specific subgame, mine is done from scratch.
Another stab in the dark: this is a desync caused by attachments, manifesting when the player tries to interact. The position is usually the last one I detached at (or 0,0,0 if freshly spawned) and there is this thing where you're kinda in two places at once, look carefully at the last gif.
I'll try 5.2.0, but, this happens in singleplayer too, so not sure if it's the network.

**Comment by SmallJoker** [comment] 2019-12-06 17:33
@hecktest Does that mean the problem no longer occurs if there aren't any attachments in the game?

**Comment by hecktest** [comment] 2019-12-07 14:16
I'll test that.
In the meantime, look what I've caught:
![warnings](https://user-images.githubusercontent.com/42101236/70375820-c725e580-1902-11ea-90eb-bf573575f52f.png)
This warning is emitted if the last frame's get_pos() is 10 or more nodes away from the current frame's. It happens when I board an entity, and is framerate dependent: almost never with good fps, and guaranteed if the game is chugging.
In order, this happens:
- Entity releases the player
- Player starts walking
- Player is done walking
- Entity captures the player
- Player's get_pos returns a bogus value for one frame, which is either the last detach point or 0,0,0
- Player's get_pos returns the right value
This does not summon the diablo by itself; it is unnoticeable unless you're monitoring it. But if something were to attempt to use that broken position... not necessarily user code, either. Gremlins guaranteed.
Also, notice the recurring "one frame delay" theme. #9129 #9140 and the big bad #2813 would like to say hello. There's a monster of a bug somewhere around here, and maybe #9150 has already slain it.

**Comment by hecktest** [comment] 2019-12-07 14:34
And, bingo, attempting to rapidly cycle the attachments unleashes the beast. I call get_pos to spawn the entity in the right spot, before attaching... if this happens during the single frame when the position is broken, the entity gets spawned at the past position, and attaching to it yanks me back. The lower the framerate, the greater the time window to catch the gremlins.
Here it is, the chupacabra in captivity.
![chup](https://user-images.githubusercontent.com/42101236/70376217-dd35a500-1906-11ea-8a68-e36c02981866.gif)

So the Big Yanker is in fact endemic to my game, but it's still a pretty nasty engine bug. (and can be encountered in other games as long as the same conditions are present)
And the smaller version, related to interaction, is likely caused by same thing, only the distance involved is more limited.

**Comment by ClobberXD** [comment] 2019-12-07 14:37
> is framerate dependent: almost never with good fps, and guaranteed if the game is chugging.

It's great that you've mentioned this. I haven't ever considered this bug to be (loosely-)tied to the frame-rate, but now that I think about it, I'm sure I've encountered this more/worse when my FPS is low.

**Comment by hecktest** [comment] 2019-12-07 16:03
Uh oh.
![baaaaaaaaad](https://user-images.githubusercontent.com/42101236/70377170-7c5f9a00-1911-11ea-9f7f-8430d4f36d18.png)
![oops2](https://user-images.githubusercontent.com/42101236/70377174-7ff32100-1911-11ea-9d04-c903ae3c17c4.png)
This is with #9150 merged, and I just got yanked to one of those positions. This means that the client produces a broken position, sends it to the server, and the server either wrongly punishes the player for it, or naively accepts it, depending on the anticheat state.
Actually, I left the anticheat on here...

**Comment by hecktest** [comment] 2019-12-07 16:14
Since the position is this weird multiple of 200 now, other side effects have surfaced.
![whoops](https://user-images.githubusercontent.com/42101236/70377439-c8600e00-1914-11ea-8565-e5f51ab51e0d.gif)
You can see the exact moment when the server gets a bad position, as the position is no longer guaranteed to lie on the ground. (hence the falling animation)

**Comment by hecktest** [comment] 2019-12-11 18:09
More paranormal activity caught on camera! Here we see a rare unstable position inbetween blocks.
![unstable](https://user-images.githubusercontent.com/42101236/70647413-2b211480-1c49-11ea-99c1-7c0ddc1e3c3a.gif)
And here's the superposition bug, observed in the client's own debug view. This is a smoking gun that something's rotten on the client side.
![inconsistent](https://user-images.githubusercontent.com/42101236/70647422-33794f80-1c49-11ea-9e70-fee3124446d8.gif)

**Comment by hecktest** [comment] 2019-12-12 18:58
![square](https://user-images.githubusercontent.com/42101236/70740407-6559e700-1d19-11ea-99f5-3370996baa5f.gif)
Same thing observed with the pointed thing cursor.
Can we please get a high priority on this? I just tried doing something that required teleporting the player as soon as they spawn, even without attachments involved, and the whole thing pretty much exploded in my face. Not being able to trust an entity's position get/set functions is pretty serious.

**Comment by sfan5** [comment] 2019-12-12 20:52
All these demonstration GIFs are cool & fancy, but we need explanations and exact reproduction steps preferably with code to debug and fix these.
Despite all the brokenness you point out, Minetest Game does not experience any of these problems just by calling `get_pos`, so there is <i>something</i> you must be doing differently.

**Comment by hecktest** [comment] 2019-12-12 22:45
Could you please pay attention? I already confirmed this is caused by attachments and triggered by a position fetch, I gave you repro steps, several different side effects, and the gifs show _the binary client environment being affected by it_. If there's any info I haven't provided, that's because I haven't understood it that well yet, and there are people here who are better qualified to poke through the movement code.
Minetest Game doesn't experience any of this because it's primitive, its features are half hardcoded and the side effects are just unnoticed, or extremely rare. To have this to happen to you in MTG, you'd have to board a boat and then try to interact with something or use the player position _in the same client frame_. Since this happens more easily with lower latency, and a higher server framerate, a typical MT server (running at about 12 fps) is even less likely to catch this.

Once again:
**When you attach a player to something, the client environment will put the player in an invalid position for exactly one frame.** Since movement happens entirely client-side, and the server tends to just believe whatever the client sends without validating it properly, the server will use that broken position if it is needed for anything, including:
- A direct get_pos call; this can cause a misplaced set_pos or in my case, spawning a parent entity in the wrong place
- Interaction (punch, interact, etc. even if the current tool has 0 range), this I don't know much about but it seems to be able to cause a teleport entirely on its own.

Since this happens exactly for one client frame, a lower framerate (higher delta time) extends the time window when the server may receive a wrong position and use it.

**Comment by sfan5** [comment] 2019-12-13 00:33
>  To have this to happen to you in MTG, you'd have to [...]. Since [...], a typical MT server (running at about 12 fps) is even less likely to catch this.

This is exactly what I meant by "exact reproduction steps". Assume one has a fresh install of Minetest and state the settings and conditions that can reproduce the bug.

> Once again:

Thanks for clarifying.

Do you think these steps are workable to isolate the issue?:
* create an entity at the same position as the player
* attach the player to it
* watch the client-side position for sudden "spikes"

**Comment by hecktest** [comment] 2019-12-14 05:04
It's best if you reproduce what my code does; attach when stationary, detach when moving. Then it will no doubt be observable.

**Comment by hecktest** [comment] 2020-06-06 19:14
Here's a crude repro mod. It's easier to reproduce when the client framerate is chugging.
[attachbug.zip](https://github.com/minetest/minetest/files/4740848/attachbug.zip)

**Comment by hecktest** [comment] 2020-06-06 22:00
Doing a
`parent_node->updateAbsolutePosition()`
while parenting partially fixes it, but the camera offset is still applied twice during the 'bad' frame.

**Closed** 2020-06-09 17:36 UTC
Labels: Bug
