### ISSUE TITLE
on_change_wield

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7877] opened 2018-11-20 20:02 UTC
##### Issue type

 - Feature request
 
##### Summary

Add a function run before changing wielded item

##### Steps to reproduce

Register two items
```
minetest.register_craftitem("mymod:rod1", {
	description = "rod1",
	inventory_image = "default_stick.png",
	stack_max = 1,
        on_use = function(itemstack, user)
              itemstack:replace("mymod:rod2")
        end,
})
minetest.register_craftitem("mymod:rod2", {
	description = "rod2",
	inventory_image = "default_stick.png",
	stack_max = 1,
        on_change_wield = function(itemstack, user)
              itemstack:replace("mymod:rod1")
        end,
})
```
But there's no way of doing this
`If there is please close and tell me how`

**Comment by paramat** [comment] 2018-11-20 21:08
Duplicate of #1377 which i will reopen.

**Closed by paramat** 2018-11-20 21:08 UTC
Labels: Duplicate, Feature request
