### ISSUE TITLE
Pressing number four (4) tries to connect to the server

### ISSUE THREAD

**Issue by baptistepouget** [minetest/minetest#4465] opened 2016-08-25 19:26 UTC
when i press on the 4 key on top of the keyboard not the numpad and shift to write the number 4 the game tries to connect to the server

here is a video of the issue
https://youtu.be/o8uesny8Jm0

i'm running fedora 24, minetest 0.4.14

It's the first time I experience this...

**Comment by rubenwardy** [comment] 2016-08-25 19:38
what keyboard layout do you use? As in, QWERTY/AZERTY etc

**Comment by baptistepouget** [comment] 2016-08-25 19:40
I use bépo

**Comment by baptistepouget** [comment] 2016-08-25 19:42
Ok so I changed my main layout to azerty and it seems to be working now, weird though

**Comment by red-001** [comment] 2016-09-15 17:58
Wouldn't this be an Irrlicht bug?

**Comment by red-001** [comment] 2016-09-23 15:48
Isn't this a duplicate of #302?

**Closed** 2016-10-02 22:29 UTC
Labels: Bug, Obscure, Upstream issue
