### ISSUE TITLE
Cannot select games or have multiple worlds in singleplayer.

### ISSUE THREAD

**Issue by Darker** [minetest/minetest#7311] opened 2018-05-09 12:59 UTC
On android, singleplayer is totally useless. Selecting games is impossible. Managing saved games also impossible. Multiplayer does not make much sense on phone, since it would cost data bills.

![screenshot_20180509-145850](https://user-images.githubusercontent.com/5508988/39815815-87d9a2ac-5399-11e8-85f3-14f5d83fdcd7.png)

**Comment by rubenwardy** [comment] 2018-05-09 13:27
I'm pretty sure this is a duplicate, but I can't find the original issue

**Comment by Wayward1** [comment] 2018-05-09 13:38
Duplicate of #2600, which has since been fixed by #6737

**Comment by rubenwardy** [comment] 2018-05-09 13:39
Duplicate of #2600

**Closed by rubenwardy** 2018-05-09 13:39 UTC
Labels: @ Mainmenu, Android, Feature request

**Comment by Darker** [comment] 2018-05-18 10:09
The issue was closed, but I still do not know how to access the fixed version.

Could you please help me a bit with that?

**Comment by SmallJoker** [comment] 2018-05-18 10:30
@Darker 
1) Get a 0.5.0-dev build from [the forums](https://forum.minetest.net/viewtopic.php?p=316739#p316739) or this [little bit older build](https://github.com/minetest/minetest/pull/7126#issuecomment-380381620).
2) Install the apk - may need enabling the setting to allow unofficial application sources
3) Main Menu -> Advanced Settings -> Search the setting `main_menu_style` (Main menu style) -> Change the value from `auto` to `full`

As it's already pointed out [here](https://github.com/minetest/minetest/issues/2600#issuecomment-387742026) the issue isn't really solved yet. Maybe detecting the screen size to decide the mode would help - but yet there's only a platform (Android) check.
