### ISSUE TITLE
Text bug on Android

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2287] opened 2015-02-11 17:18 UTC
I test last commit. All text is simply mad: on the screen jump letters values html-color (# 532654 example) and so on. It is impossible to describe. Just get Minetest Android and see for yourself!

**Comment by nerzhul** [comment] 2015-02-11 19:02
Can you tell me how you compile minetest for Linux, my documentation isn't complete or wrong, i'll test it.

**Comment by MoNTE48** [comment] 2015-02-11 19:06
Lol, sorry.

cd build/android
make release -j12 ;)

I tested previously commit - all good work.
I Dldev MultiCraft fork fo Android :)

**Comment by nerzhul** [comment] 2015-02-12 09:51
I see, it's difficult to compile it on FreeBSD at this time (makefile errors).

**Comment by MoNTE48** [comment] 2015-02-12 09:52
I use Ubuntu 13.10

**Comment by nerzhul** [comment] 2015-02-12 11:04
on linux it's not a problem, i just need to build it on FreeBSD because it's my jenkins (and it build APK java applications, but i need to find the problem with minetest)

**Comment by MoNTE48** [comment] 2015-02-12 11:05
U can use virtual box? On FreeBSD build android appis very bad idea.

**Comment by nerzhul** [comment] 2015-02-12 11:07
It works very well for tests and i use it for building testing and deploying applications on google play store :)

**Comment by MoNTE48** [comment] 2015-02-12 11:09
@nerzhul , OK, wait your test and fix bug ;)

**Comment by nerzhul** [comment] 2015-02-12 11:12
At this time i don't have time for fixing compilation on Android, i'm working on networking, which is a most important part

**Comment by MoNTE48** [comment] 2015-02-12 11:13
Bad news...

**Comment by Zeno-** [comment] 2015-02-12 14:23
@MoNTE48 Do you have any suggestions how it could be fixed?

**Comment by MoNTE48** [comment] 2015-02-12 14:42
@Zeno- , no, sorry.I do not write on C++. :(

**Comment by MoNTE48** [comment] 2015-02-14 15:39
Look this (Note 4. Activate Shaders and see bug).
![screenshot_2015-02-14-17-37-24](https://cloud.githubusercontent.com/assets/6764600/6200074/29e6baf2-b470-11e4-93ac-06cd600e8245.png)

On Galaxy S1 all text invisible!!! And I all button don't press.

**Comment by MoNTE48** [comment] 2015-02-19 14:50
Pls, confirm this bug!

**Comment by nanepiwo** [comment] 2015-02-19 17:52
If you post a compiled version, I can confirm/deny the bug on a Motorola X, Android 4.4

**Comment by MoNTE48** [comment] 2015-02-19 18:01
I can open a thread in the forum and create a repository of regular build. Ok?

**Comment by Zeno-** [comment] 2015-03-02 08:58
This is hopefully fixed by commit aefe80769bc515e0ddbfc734d41de396aca1259c

**Comment by Zeno-** [comment] 2015-03-05 13:25
Confirmed by @est31 and myself. The problem seems to have gotten worse.

Difficult to bisect because not all commits build on Android.

**Comment by est31** [comment] 2015-03-06 01:22
I have bisected the issue to [these commits](https://github.com/minetest/minetest/compare/84c367bb468441efe428478d3918f07a9b6c2d72...8252e1ecd097abd83a3e9ef95aba37a3d837e00b), but couldn't exclude more commits, as I can't build inside. Thats why I opened #2436 to fix this in the long term. About screenshots, I'm getting:
![1whqgrxu](https://cloud.githubusercontent.com/assets/8872119/6518541/9d6bf668-c3a7-11e4-8cda-eb0cbfd500bc.png)

**Comment by MoNTE48** [comment] 2015-03-06 05:16
You have to remember, but the problem does not occur on all devices. On my Galaxy Note 4, Galaxy Note Edge galaxy S5 and everything works fine! But on the Galaxy Note Pro, Galaxy S1 and many other phones problem.

**Comment by est31** [comment] 2015-03-06 05:46
Zeno has reported that the problem only occurs when you have another locale set. Monte, do you have non-english locales on the devices that work?

**Comment by MoNTE48** [comment] 2015-03-06 05:53
@est31, On Android, never worked a specific locale! Nevertheless, I tried to make the English language on the phone and run the game. The situation has not changed, unfortunately.

**Comment by MoNTE48** [comment] 2015-03-06 05:54
@Zeno- ! The first screenshot shows 4 Note! Your correction (in your repository) fixes the problem on it. On other devices, the problem remained.

**Comment by Warr1024** [comment] 2015-03-06 21:08
![screenshot_2015-03-06-15-59-56](https://cloud.githubusercontent.com/assets/324806/6536280/4d52569a-c41a-11e4-8c8a-ff914ddc16c4.png)

I'm able to reproduce the problem on my Samsung Galaxy Tab 2 10.1" (GT-P5113) running Android 4.2.2 build JDQ39.P5113UEUCMK3.  The junk text is different (though always junk) each time the application is launched, i.e. kill the activity in the task manager.  I tried building both e9eda2b0d0019890cd404e4af25b7adf349e288f and 7993a403f2c17a215e4895ba1848aaf69bb61980 with very similar results.  Built using Debian Wheezy 64-bit.

**Comment by Warr1024** [comment] 2015-03-06 23:11
Commit 84c367bb46 DOES work for me, on the same tablet as I described above.

**Comment by Zeno-** [comment] 2015-03-07 10:54
Fixed :)

5698e2b

**Closed by Zeno-** 2015-03-07 10:54 UTC
Labels: Android, blocker, bug
