### ISSUE TITLE
Chests get stuck at open state

### ISSUE THREAD

**Issue by Dieter44** [minetest/minetest#11655] opened 2021-09-24 21:26 UTC
##### Minetest version

```
5.4.1
```

##### OS / Hardware

Operating system: macOS
CPU: Intel i5

##### Summary
Chests can get stuck in an open state.

##### Steps to reproduce
Quickly open a chest and close it again. Repeat that until the chest gets stuck eventually.

![Bildschirmfoto 2021-09-24 um 23 24 11](https://user-images.githubusercontent.com/55900078/134741393-affba6b9-a1e7-4e62-8d16-ca273d5a7552.png)

**Comment by sfan5** [comment] 2021-09-24 21:59
Closing as a duplicate of https://github.com/minetest/minetest_game/issues/2031 (the other repo tracks issues related to the default shipped game)

**Closed by sfan5** 2021-09-24 21:59 UTC
Labels: Unconfirmed bug
