### ISSUE TITLE
Content DB Title Buttons can't scroll

### ISSUE THREAD

**Issue by Python-Sargent** [minetest/minetest#15474] opened 2024-11-23 17:45 UTC
### Luanti version

```true
Luanti 5.11.0-dev-9b6a39901-dirty (Linux)
Using LuaJIT 2.1.1725453128
Built by GCC 14.2
Running on Linux/6.6.54 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Manjaro 24.1

### CPU model

AMD Ryzen 5

### GPU model

NVIDIA Geforce GTX 1050 Ti

### Active renderer

OpenGL 4.6.0

### Summary

The content in the builtin Content DB browser of the Luanti Main Menu doesn't allow for scrolling in the individual containers, even though the scroll bar is there.

### Steps to reproduce

Start up Luanti 5.10.x and go to Main Menu >> Content >> Browse Online Content >> Search for "MeseCraft", or another game with a pretty long description. The Title Button doesn't scroll, because it is acting like a button.

**Comment by rubenwardy** [comment] 2024-11-23 18:00
The title/descriptions are intended to be truncated and not scrollable. There should be a new formspec element that can truncate text without a scrollbar

Related: https://github.com/minetest/minetest/issues/7408

**Comment by sfan5** [comment] 2024-11-24 14:15
duplicate of #15339

**Closed by sfan5** 2024-11-24 14:15 UTC
Labels: Bug, @ Mainmenu
