### ISSUE TITLE
Lighting nodes are not rendered if they are behind opaque ones.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#10218] opened 2020-07-22 16:13 UTC
##### Minetest version
Minetest-5.4.0-dev-cfaef5b1c

##### Summary
If any opaque nodes (e.g. window plains from homedecor) cover lighting nodes, those can not be viewed through them (see gif below to reproduce better).
![lighting_nodes_render_bug](https://user-images.githubusercontent.com/25750346/88200746-3d3b4a80-cc4f-11ea-92ab-75f619168d8c.gif)

**Comment by SmallJoker** [comment] 2020-07-22 18:09
Duplicate of #95

Closely related: #3761, #5083

**Closed by SmallJoker** 2020-07-22 18:09 UTC
Labels: Unconfirmed bug
