### ISSUE TITLE
The game logo crosses over the game menu.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#9963] opened 2020-05-29 15:26 UTC
##### Minetest version
```
Minetest-5.3.0-dev-82e413789
```

##### Summary
The game logo crosses over the menu`s tabs as seen on the screenshot below:
![Screenshot_20200529_182302](https://user-images.githubusercontent.com/25750346/83276559-76b88200-a1d9-11ea-8835-53bfa0247fd5.png)

I think it certainly should be heightened a bit.

**Comment by paramat** [comment] 2020-05-29 17:18
Duplicate of #6571

**Closed by paramat** 2020-05-29 17:18 UTC
Labels: Unconfirmed bug
