### ISSUE TITLE
Android shaders are broken

### ISSUE THREAD

**Issue by nininik0** [minetest/minetest#13578] opened 2023-06-11 00:50 UTC
![Screenshot_20230610-173732_Minetest](https://github.com/minetest/minetest/assets/132112852/35298794-1c23-43eb-b3ce-4cca3250aca8)
![Screenshot_20230610-173711_Minetest](https://github.com/minetest/minetest/assets/132112852/2d0ac7e2-1533-4d5c-924c-9cd83d6d46c9)
![Screenshot_20230610-173650_Minetest](https://github.com/minetest/minetest/assets/132112852/d18d55d1-4a81-41d4-bf6a-3f165eccd370)
![Screenshot_20230610-173518_Minetest](https://github.com/minetest/minetest/assets/132112852/307fa2af-9e04-436f-b5ff-83c407cd4c22)
![Screenshot_20230610-173324_Minetest](https://github.com/minetest/minetest/assets/132112852/d6935ed9-ce8c-4691-987b-1fa9bf8a25d8)
Minetest version 5.70
Android
Summary
 ok so shaders for Android are broken. Animated sprites don't animate when the shaders are enabled even if none of the check marks are enabled only the shaders experimental one is enabled but not the waving stuff of lighting are enabled then the sprites don't animate, and if you disable shaders they animate but the lighting of some of them is incorrect like its dark but they are light
Steps to reproduce
 ok go to devtest or minetest classic and enable any shaders this includes the checkmark for experimental shaders even if none of them are enabled. Then spawn in a yawsprite or an animated sprite or a mobv2 and then see look at them they don't move but their lighting is correct. However if you do the same thing they are disabled the shaders are, the sprites do animate but some sprites are LIGHT when there's NIGHT AND ITS DARK this is so broken even tho they are shaded that also relates to MESHES.

**Comment by nininik0** [comment] 2023-06-11 00:55
Ok im on android version 5.7.0

**Comment by oong819** [comment] 2023-06-11 02:55
1. can you use the MarkDown bug template?
2. unity .shader? Minetest use irrlich(Mt)
3. i will test this bug

**Comment by oong819** [comment] 2023-06-11 03:08
duplicate of #13511?

**Comment by Zughy** [comment] 2023-06-11 10:21
Hello, please open a new issue and follow the template, it's very hard to understand what you're saying

**Closed** 2023-06-11 10:21 UTC
Labels: Unconfirmed bug, Android, Invalid

**Comment by nininik0** [comment] 2023-06-11 15:59
Ok, it just took a while to explain

**Comment by nininik0** [comment] 2023-06-11 16:05
What's wrong with my sentence

**Comment by nininik0** [comment] 2023-07-09 18:38
.
