### ISSUE TITLE
Command autocompletion

### ISSUE THREAD

**Issue by vanillajonathan** [minetest/minetest#11097] opened 2021-03-21 12:26 UTC
## Problem

It is tricky to discover commands, remember commands and tedious to type commands. It is unexpected that autocompletion doesn't work when it works in so many other games and programs.

## Solutions

When I write `/` and maybe a letter and press the <kbd>Tab</kbd> key it should autocomplete the command if just one command is found, or present me with a list of all commands that start with the letters I typed.

## Additional context

    [/set<tab>
    set	setpassord	setspawn	settime
    [/clear<tab>
    clearinv	clearobjects	clearpassword

`/setp` + <kbd>Tab</kbd> --> `/setpassword `

**Comment by hlqkj** [comment] 2021-03-21 12:29
I'd love to have this!! Full support

**Comment by rubenwardy** [comment] 2021-03-21 16:09
Duplicate of #9663

**Closed by rubenwardy** 2021-03-21 16:09 UTC
Labels: Feature request
