### ISSUE TITLE
Add waterlogged nodes

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10253] opened 2020-08-02 09:15 UTC
## Problem

If i place a sign/fence/rail near a liquid, it looks strange: The sign/fence/rail still have space but liquids never flow in.

## Solutions

Add a param in `minetest.register_node`, add a `waterlog` to `node_definition`.

the `waterlog` can be:
 - `"off"` or `false` or `nil`: Disable waterlog (default
 - `"auto"`: If liquid come into the block, automacly set the liquid type in the node (source, flow)
 - `"source"` or `"flow"`: Force the logged liquid to be source or flow
 - `"destroy"`: Destroy the nod when waterlogged

## Additional context

Here have some examples of strange liquid:
![screenshot_20200802_171232](https://user-images.githubusercontent.com/55009343/89119779-67102f00-d4e3-11ea-9cbe-2ab84ca63fd5.png)
![screenshot_20200802_171420](https://user-images.githubusercontent.com/55009343/89119811-a76fad00-d4e3-11ea-9216-13a638bb78ef.png)

**Comment by SmallJoker** [comment] 2020-08-02 09:21
Duplicate of #3074

**Closed by SmallJoker** 2020-08-02 09:21 UTC
Labels: Feature request
